/**
 * Source Registry — the twenty-five-domain expansion, free tier only.
 * ════════════════════════════════════════════════════════════════════════════
 *
 * Every source here is open, free-key, an HTML page we can parse, or a manual
 * read. **No paid feed is registered** — paid ones stay in
 * `docs/synthesis/12_MACRO_DOMAIN_EXPANSION.md` as catalogue entries until the
 * operator buys one. The order of the blocks is the build order the operator
 * asked for; `EXPANSION_BUILD_ORDER` below states it explicitly with the
 * reason for each position.
 *
 * `stmt` in `provides` marks a source that feeds the statement ledger (what
 * they said → what happened); `40y+` marks machine-readable history to 1986
 * or earlier.
 */
import type { AccessMode, Cadence, Domain, Jurisdiction, MacroSource, SourceTier } from "./types";

function s(
  id: string,
  name: string,
  entity: string,
  jurisdiction: Jurisdiction,
  tier: SourceTier,
  access: AccessMode,
  cadence: Cadence,
  domains: Domain[],
  url: string,
  provides: string,
  extra: Partial<Pick<MacroSource, "apiUrl" | "keyEnv" | "caveat" | "language">> = {},
): MacroSource {
  return { id, name, entity, jurisdiction, tier, access, cadence, domains, url, provides, ...extra };
}

export const EXPANSION_SOURCES: MacroSource[] = [
  // ═══ 1. FEDERAL RESERVE ══════════════════════════════════════════════════
  s("fed-fomc-statements", "FOMC statements, minutes, SEP", "Federal Reserve Board", "US", "primary-official", "open-api", "irregular", ["fed", "rates-markets"], "https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm", "stmt 1994+ (minutes 1993+, SEP 2007+): the decision, the dots, the dissent.", { apiUrl: "https://www.federalreserve.gov/feeds/press_monetary.xml" }),
  s("fed-transcripts", "FOMC transcripts (five-year lag)", "Federal Reserve Board", "US", "primary-official", "page", "annual", ["fed"], "https://www.federalreserve.gov/monetarypolicy/fomc_historical.htm", "stmt 1976–2021: what was said in the room, verbatim."),
  s("fed-speeches", "Speeches and testimony", "Federal Reserve Board", "US", "primary-official", "open-api", "daily", ["fed"], "https://www.federalreserve.gov/newsevents/speeches.htm", "stmt 1996+: signalling between meetings.", { apiUrl: "https://www.federalreserve.gov/feeds/speeches.xml" }),
  s("fed-press-all", "All press releases (RSS)", "Federal Reserve Board", "US", "primary-official", "open-api", "daily", ["fed", "fin-stability"], "https://www.federalreserve.gov/newsevents/pressreleases.htm", "stmt: every release the Board issues, the day it issues it.", { apiUrl: "https://www.federalreserve.gov/feeds/press_all.xml" }),
  s("fed-beige-book", "Beige Book", "Federal Reserve Board", "US", "primary-official", "page", "irregular", ["fed"], "https://www.federalreserve.gov/monetarypolicy/beige-book-default.htm", "1970+: regional anecdote eight times a year."),
  s("fed-ddp", "Data Download Program (H.4.1, H.8, H.15, G.19, Z.1)", "Federal Reserve Board", "US", "primary-official", "open-api", "weekly", ["fed", "fin-stability", "treasury-holdings"], "https://www.federalreserve.gov/datadownload/", "40y+: balance sheet, bank credit, rates, consumer credit, flow of funds as CSV.", { apiUrl: "https://www.federalreserve.gov/datadownload/Output.aspx?rel=H15&series=bf17364827e38702b42a58cf8eaa3f78&lastobs=5&filetype=csv&label=include&layout=seriescolumn" }),
  s("nyfed-markets", "NY Fed: ACM term premium, SOMA, primary dealer statistics, GSCPI", "Federal Reserve Bank of New York", "US", "primary-official", "open-api", "daily", ["fed", "fin-stability", "rates-markets"], "https://www.newyorkfed.org/markets", "30y: term premium daily, SOMA weekly, dealer positions weekly, supply-chain pressure monthly (1997+)."),
  s("fed-sloos", "Senior Loan Officer Opinion Survey", "Federal Reserve Board", "US", "primary-official", "open-api", "quarterly", ["fed", "fin-stability"], "https://www.federalreserve.gov/data/sloos.htm", "1967+: credit standards, the cleanest leading indicator of a credit crunch."),
  s("fed-fsr", "Financial Stability Report", "Federal Reserve Board", "US", "primary-official", "page", "semiannual", ["fed", "fin-stability"], "https://www.federalreserve.gov/publications/financial-stability-report.htm", "stmt 2018+: the Fed's own ranked risk list."),
  s("fed-chair-pressconf", "Chair's press-conference transcripts", "Federal Reserve Board", "US", "primary-official", "page", "irregular", ["fed"], "https://www.federalreserve.gov/monetarypolicy/fomcpresconf.htm", "stmt 2011+: tone, hedges, what was refused."),
  s("cme-fedwatch", "CME FedWatch (fed funds futures implied path)", "CME Group", "US", "research", "page", "realtime", ["fed", "rates-markets"], "https://www.cmegroup.com/markets/interest-rates/cme-fedwatch-tool.html", "1990s+: the market's path to score the dots against."),

  // ═══ 4. BIS ══════════════════════════════════════════════════════════════
  s("bis-stats-api", "BIS Statistics Explorer (SDMX API)", "Bank for International Settlements", "INTL", "multilateral", "open-api", "quarterly", ["bis", "fin-stability", "sovereign-debt", "reserves-fx"], "https://data.bis.org/", "40y+: credit-to-GDP gaps, property prices, debt securities, banking, effective exchange rates (1964).", { apiUrl: "https://stats.bis.org/api/v2/data/dataflow/BIS/WS_CREDIT_GAP/1.0/Q.US.P.A.C?format=csv&lastNObservations=4" }),
  s("bis-speeches", "Central bank speeches database", "Bank for International Settlements", "INTL", "multilateral", "open-api", "daily", ["bis", "fed", "ecb", "boe"], "https://www.bis.org/cbspeeches/index.htm", "stmt 1997+: every governor's speech, searchable; the largest ledger of central-bank words on earth.", { apiUrl: "https://www.bis.org/doclist/cbspeeches.rss" }),
  s("bis-annual-report", "Annual Economic Report", "Bank for International Settlements", "INTL", "multilateral", "page", "annual", ["bis"], "https://www.bis.org/publ/arpdf/index.htm", "stmt 1931+: the central banks' bank's view."),
  s("bis-quarterly", "BIS Quarterly Review", "Bank for International Settlements", "INTL", "multilateral", "page", "quarterly", ["bis", "fin-stability"], "https://www.bis.org/quarterlyreviews/index.htm", "1990s+: market analysis with the data behind it."),
  s("bis-basel", "Basel Committee publications", "Bank for International Settlements", "INTL", "multilateral", "page", "irregular", ["bis", "fin-stability"], "https://www.bis.org/bcbs/publications.htm", "stmt 1988+: capital rules and their timelines vs adoption."),
  s("bis-cpmi", "CPMI and Innovation Hub (mBridge, Agorá)", "Bank for International Settlements", "INTL", "multilateral", "page", "irregular", ["bis", "oil-settlement"], "https://www.bis.org/about/bisih/topics/cbdc.htm", "2019+: the plumbing projects behind non-dollar settlement."),
  s("bis-credit-gap", "Credit-to-GDP gap early-warning series", "Bank for International Settlements", "INTL", "multilateral", "open-api", "quarterly", ["bis", "fin-stability"], "https://data.bis.org/topics/CREDIT_GAPS", "40y+: the best single published predictor of banking crises."),
  s("bis-papers", "BIS Papers and Working Papers", "Bank for International Settlements", "INTL", "research", "page", "irregular", ["bis"], "https://www.bis.org/publ/work.htm", "1990s+: the research the models cite."),
  s("bis-triennial-survey", "Triennial Central Bank Survey of FX and OTC derivatives turnover", "Bank for International Settlements", "INTL", "primary-official", "open-api", "irregular", ["bis", "reserves-fx", "oil-settlement"], "https://www.bis.org/statistics/rpfx22.htm", "1989+: every three years, each currency's share of global FX turnover — the dollar's share measured in the market, not in speeches."),
  s("bis-eer", "Effective exchange rate indices (daily, 64 economies)", "Bank for International Settlements", "INTL", "primary-official", "open-api", "daily", ["bis", "reserves-fx"], "https://www.bis.org/statistics/eer.htm", "1964+: nominal and real effective rates; the yen and yuan pressure gauge.", { apiUrl: "https://stats.bis.org/api/v2/data/dataflow/BIS/WS_EER/1.0/D.N.B.JP?format=csv&lastNObservations=1" }),

  // ═══ 5. IMF beyond the WEO ═══════════════════════════════════════════════
  s("imf-ifs", "International Financial Statistics (SDMX JSON API)", "International Monetary Fund", "INTL", "multilateral", "open-api", "monthly", ["imf", "reserves-fx", "rates-markets"], "https://data.imf.org/", "1948+: reserves, rates, money, 190 countries.", { apiUrl: "https://dataservices.imf.org/REST/SDMX_JSON.svc/CompactData/IFS/M.JP.RAFA_USD?startPeriod=2025" }),
  s("imf-mona", "MONA — Monitoring of Fund Arrangements", "International Monetary Fund", "INTL", "multilateral", "open-api", "quarterly", ["imf", "sovereign-debt"], "https://www.imf.org/external/np/pdr/mona/index.aspx", "stmt 2002+: programme conditions and whether they were met — a pre-coded said-vs-did ledger for 180 countries."),
  s("imf-gfsr", "Global Financial Stability Report", "International Monetary Fund", "INTL", "multilateral", "page", "semiannual", ["imf", "fin-stability"], "https://www.imf.org/en/publications/gfsr", "2002+: systemic risk, global."),
  s("imf-dots", "Direction of Trade Statistics", "International Monetary Fund", "INTL", "multilateral", "open-api", "monthly", ["imf", "trade-shipping"], "https://data.imf.org/?sk=9d6028d4-f14a-464c-a2f2-59b2cd424b85", "1948+: bilateral trade."),
  s("imf-gdd", "Global Debt Database", "International Monetary Fund", "INTL", "multilateral", "open-api", "annual", ["imf", "sovereign-debt"], "https://www.imf.org/external/datamapper/datasets/GDD", "1950+: public and private debt.", { apiUrl: "https://www.imf.org/external/datamapper/api/v1/PVD_LS" }),
  s("imf-esr", "External Sector Report", "International Monetary Fund", "INTL", "multilateral", "page", "annual", ["imf", "reserves-fx"], "https://www.imf.org/en/publications/esr", "stmt 2012+: currency misalignment verdicts by country."),
  s("imf-press", "IMF press releases and speeches (RSS)", "International Monetary Fund", "INTL", "multilateral", "open-api", "daily", ["imf"], "https://www.imf.org/en/news", "stmt: Managing Director and Board statements.", { apiUrl: "https://www.imf.org/en/news/rss?language=eng" }),
  s("imf-sdr", "SDR allocations, holdings and valuation", "International Monetary Fund", "INTL", "multilateral", "open-api", "daily", ["imf", "reserves-fx"], "https://www.imf.org/external/np/fin/data/rms_sdrv.aspx", "1969+: reserve-asset plumbing."),
  s("imf-hpdd", "Historical Public Debt Database", "International Monetary Fund", "INTL", "multilateral", "open-api", "annual", ["imf", "sovereign-debt"], "https://www.imf.org/external/datamapper/datasets/DEBT", "1800+: debt/GDP for 180 countries."),

  // ═══ 10. SUMMITS with compliance scoring ═════════════════════════════════
  s("g7-info-centre", "G7 Information Centre — every communiqué", "G7 Research Group, University of Toronto", "INTL", "research", "open-api", "annual", ["summits"], "http://www.g7.utoronto.ca/", "stmt 1975+: every summit document."),
  s("g7-compliance", "G7 compliance reports", "G7 Research Group, University of Toronto", "INTL", "research", "open-api", "annual", ["summits"], "http://www.g7.utoronto.ca/evaluations/", "1996+: each commitment scored +1 / 0 / −1 — the calibration set for the credibility multiplier."),
  s("g20-compliance", "G20 compliance reports", "G20 Research Group, University of Toronto", "INTL", "research", "open-api", "annual", ["summits"], "http://www.g20.utoronto.ca/compliance/", "2008+: the same for the G20."),
  s("brics-info-centre", "BRICS Information Centre", "BRICS Research Group", "INTL", "research", "open-api", "annual", ["summits", "oil-settlement"], "http://www.brics.utoronto.ca/", "stmt 2009+: declarations and compliance."),
  s("g20-fmcbg", "G20 Finance Ministers and Central Bank Governors communiqués", "G20 Presidency", "INTL", "primary-official", "page", "irregular", ["summits"], "https://g20.org/", "stmt 1999+: financial coordination promises."),
  s("fsb-g20-reports", "FSB progress reports to the G20", "Financial Stability Board", "INTL", "multilateral", "page", "annual", ["summits", "fin-stability"], "https://www.fsb.org/publications/", "stmt 2009+: reform delivery vs promise."),
  s("sco-declarations", "Shanghai Cooperation Organisation declarations", "SCO Secretariat", "INTL", "primary-official", "page", "annual", ["summits", "china-policy"], "https://eng.sectsco.org/", "stmt 2001+: the Eurasian bloc."),
  s("asean-statements", "ASEAN summit statements", "ASEAN Secretariat", "INTL", "primary-official", "page", "annual", ["summits", "taiwan-risk"], "https://asean.org/", "stmt 1967+."),
  s("quad-aukus", "Quad and AUKUS joint statements", "U.S. State Department / partners", "US", "primary-official", "page", "irregular", ["summits", "taiwan-risk"], "https://www.state.gov/", "stmt 2017+: Indo-Pacific security commitments."),
  s("nato-declarations", "NATO summit declarations and defence-expenditure tables", "NATO", "INTL", "primary-official", "open-api", "annual", ["summits", "political-risk"], "https://www.nato.int/cps/en/natohq/topics_49198.htm", "stmt 1949+; spending tables: the 2 % pledge vs delivery by member."),

  // ═══ 12. U.S. FISCAL, LEGISLATIVE, PRESIDENTIAL ══════════════════════════
  s("congress-api", "Congress.gov API", "Library of Congress", "US", "primary-official", "keyed-api", "daily", ["us-fiscal", "sanctions", "taiwan-risk"], "https://api.congress.gov/", "1973+: bills, votes, Taiwan / China / sanctions legislation.", { apiUrl: "https://api.congress.gov/v3/bill?api_key={KEY}&format=json", keyEnv: "CONGRESS_API_KEY" }),
  s("presidency-project", "The American Presidency Project", "UC Santa Barbara", "US", "research", "open-api", "daily", ["us-fiscal"], "https://www.presidency.ucsb.edu/", "stmt 1789+: every presidential document."),
  s("cbo-accuracy", "CBO baselines and forecast-accuracy studies", "Congressional Budget Office", "US", "primary-official", "page", "semiannual", ["us-fiscal", "sovereign-debt"], "https://www.cbo.gov/topics/budget/accuracy-projections", "stmt 1976+: CBO grading its own forecasts against outturn."),
  s("treasury-refunding", "Quarterly Refunding statements and TBAC minutes", "U.S. Department of the Treasury", "US", "primary-official", "page", "quarterly", ["us-fiscal", "treasury-holdings"], "https://home.treasury.gov/policy-issues/financing-the-government/quarterly-refunding", "stmt 1990s+: issuance signalling; buybacks."),
  s("gao", "GAO reports and High-Risk List", "Government Accountability Office", "US", "primary-official", "open-api", "daily", ["us-fiscal"], "https://www.gao.gov/", "1990+: delivery audits.", { apiUrl: "https://www.gao.gov/rss/reports.xml" }),
  s("ssa-trustees", "Social Security Trustees Reports", "Social Security Administration", "US", "primary-official", "page", "annual", ["us-fiscal", "demographics"], "https://www.ssa.gov/oact/tr/", "stmt 1941+: depletion-date projections vs outcomes — eighty years of official forecasts with answers attached."),
  s("medicare-trustees", "Medicare Trustees Reports", "CMS", "US", "primary-official", "page", "annual", ["us-fiscal", "demographics"], "https://www.cms.gov/oact/tr", "stmt 1970+."),
  s("fiscaldata-debt", "Fiscal Data — Debt to the Penny (API)", "Bureau of the Fiscal Service", "US", "primary-official", "open-api", "daily", ["us-fiscal", "sovereign-debt"], "https://fiscaldata.treasury.gov/datasets/debt-to-the-penny/", "1993+ daily: total public debt.", { apiUrl: "https://api.fiscaldata.treasury.gov/services/api/fiscal_service/v2/accounting/od/debt_to_penny?sort=-record_date&page[size]=1" }),
  s("fiscaldata-mts", "Monthly Treasury Statement (API)", "Bureau of the Fiscal Service", "US", "primary-official", "open-api", "monthly", ["us-fiscal"], "https://fiscaldata.treasury.gov/datasets/monthly-treasury-statement/", "1980s+: actual outlays, receipts, interest.", { apiUrl: "https://api.fiscaldata.treasury.gov/services/api/fiscal_service/v1/accounting/mts/mts_table_1?sort=-record_date&page[size]=1" }),
  s("federal-register-api", "Federal Register API", "Office of the Federal Register", "US", "primary-official", "open-api", "daily", ["us-fiscal", "sanctions"], "https://www.federalregister.gov/developers/documentation/api/v1", "1994+: rules, executive orders, notices.", { apiUrl: "https://www.federalregister.gov/api/v1/documents.json?conditions[type][]=PRESDOCU&order=newest&per_page=5" }),
  s("whitehouse-briefing", "White House briefing room (RSS)", "Executive Office of the President", "US", "primary-official", "open-api", "daily", ["us-fiscal", "sanctions", "taiwan-risk"], "https://www.whitehouse.gov/briefing-room/", "stmt: statements and executive orders the day they issue.", { apiUrl: "https://www.whitehouse.gov/feed/" }),

  // ═══ 15. OPEC+ ═══════════════════════════════════════════════════════════
  s("opec-press", "OPEC press releases and Conference communiqués (RSS)", "OPEC Secretariat", "INTL", "primary-official", "open-api", "irregular", ["opec", "oil-settlement"], "https://www.opec.org/opec_web/en/press_room/28.htm", "stmt 1960+: quota decisions.", { apiUrl: "https://www.opec.org/opec_web/en/pressreleases.rss" }),
  s("opec-asb", "OPEC Annual Statistical Bulletin", "OPEC Secretariat", "INTL", "multilateral", "open-api", "annual", ["opec"], "https://asb.opec.org/", "1965+: production, exports, reserves by member."),
  s("eia-international", "EIA International Energy Statistics", "U.S. Energy Information Administration", "US", "primary-official", "keyed-api", "monthly", ["opec", "oil-settlement"], "https://www.eia.gov/international/data/world", "1973+: production by country — the independent check on quota compliance.", { keyEnv: "EIA_API_KEY" }),
  s("eia-spr", "Strategic Petroleum Reserve levels", "U.S. Energy Information Administration", "US", "primary-official", "keyed-api", "weekly", ["opec"], "https://www.eia.gov/dnav/pet/pet_stoc_typ_d_nus_SAS_mbbl_w.htm", "1977+: the U.S. counter-move to a cut.", { keyEnv: "EIA_API_KEY" }),
  s("baker-hughes", "Baker Hughes rig count", "Baker Hughes", "US", "research", "page", "weekly", ["opec"], "https://rigcount.bakerhughes.com/", "1987+: the U.S. supply response."),
  s("doc-cooperation", "OPEC+ Declaration of Cooperation records", "OPEC Secretariat", "INTL", "primary-official", "page", "irregular", ["opec"], "https://www.opec.org/opec_web/en/publications/4580.htm", "stmt 2016+: the alliance's rules and each member's quota."),
  s("ru-energy-ministry", "Russian Ministry of Energy statements", "Government of Russia", "RU", "primary-official", "page", "irregular", ["opec"], "https://minenergo.gov.ru/", "stmt 2016+: the '+' side of OPEC+.", { caveat: "Sanctioned issuer; declared, cross-check with tanker data." }),

  // ═══ 16. SANCTIONS ═══════════════════════════════════════════════════════
  s("eu-sanctions-map", "EU Sanctions Map", "European Commission / EEAS", "EU", "primary-official", "open-api", "daily", ["sanctions"], "https://www.sanctionsmap.eu/", "stmt 2014+: EU designations and packages."),
  s("uk-ofsi", "UK OFSI consolidated list", "HM Treasury", "GB", "primary-official", "open-api", "daily", ["sanctions"], "https://www.gov.uk/government/publications/the-uk-sanctions-list", "stmt 2000s+: UK designations (CSV/JSON)."),
  s("opensanctions", "OpenSanctions", "OpenSanctions.org", "INTL", "research", "open-api", "daily", ["sanctions"], "https://www.opensanctions.org/", "2010s+: consolidated, machine-readable designations across regimes.", { apiUrl: "https://data.opensanctions.org/datasets/latest/sanctions/index.json" }),
  s("crea-fossil-tracker", "Russia Fossil Tracker", "Centre for Research on Energy and Clean Air", "INTL", "research", "open-api", "daily", ["sanctions", "oil-settlement"], "https://energyandcleanair.org/russia-fossil-tracker/", "2022+ daily: Russian fossil revenue by buyer country — sanctions leakage, measured.", { apiUrl: "https://api.russiafossiltracker.com/v0/counter_last" }),
  s("kse-oil-tracker", "Russian Oil Tracker", "Kyiv School of Economics Institute", "UA", "research", "page", "monthly", ["sanctions"], "https://kse.ua/russian-oil-tracker/", "2022+: price-cap compliance."),
  s("un-panel-experts", "UN Panel of Experts reports (DPRK, Libya, others)", "UN Security Council", "INTL", "multilateral", "page", "semiannual", ["sanctions"], "https://www.un.org/securitycouncil/sanctions/information", "stmt 2010+: evasion typologies."),
  s("fincen-advisories", "FinCEN advisories", "U.S. Treasury FinCEN", "US", "primary-official", "open-api", "irregular", ["sanctions"], "https://www.fincen.gov/resources/advisoriesbulletinsfact-sheets", "stmt 2000s+."),
  s("ru-minfin-nwf", "National Wealth Fund statistics", "Russian Ministry of Finance", "RU", "primary-official", "page", "monthly", ["sanctions", "reserves-fx"], "https://minfin.gov.ru/en/", "2008+: the sanctioned side's liquid reserves (yuan and gold now)."),

  // ═══ 19. TRADE AND SHIPPING ══════════════════════════════════════════════
  s("wto-stats", "WTO Stats portal and dispute-settlement database", "World Trade Organization", "INTL", "multilateral", "open-api", "monthly", ["trade-shipping"], "https://stats.wto.org/", "1948+ / 1995+: trade and its disputes.", { apiUrl: "https://api.wto.org/timeseries/v1/data" }),
  s("kiel-trade-indicator", "Kiel Trade Indicator", "Kiel Institute for the World Economy", "DE", "research", "open-api", "monthly", ["trade-shipping"], "https://www.ifw-kiel.de/topics/international-trade/kiel-trade-indicator/", "2019+: AIS-based nowcast of trade for 75 countries."),
  s("port-la", "Port of Los Angeles TEU statistics", "Port of Los Angeles", "US", "primary-official", "page", "monthly", ["trade-shipping"], "https://www.portoflosangeles.org/business/statistics/container-statistics", "1995+: the largest U.S. gateway, monthly."),
  s("port-long-beach", "Port of Long Beach TEU statistics", "Port of Long Beach", "US", "primary-official", "page", "monthly", ["trade-shipping"], "https://polb.com/business/port-statistics/", "1995+: monthly TEU counts for the largest U.S. container gateway; the physical read on the trade truce."),
  s("panama-canal", "Panama Canal Authority transit statistics", "ACP", "INTL", "primary-official", "page", "monthly", ["trade-shipping"], "https://pancanal.com/en/statistics/", "2000s+: the drought-constrained chokepoint."),
  s("suez-canal", "Suez Canal Authority navigation statistics", "SCA", "EG", "primary-official", "page", "monthly", ["trade-shipping"], "https://www.suezcanal.gov.eg/English/Navigation/Pages/NavigationStatistics.aspx", "2000s+: Red Sea diversion, measured."),
  s("global-trade-alert", "Global Trade Alert", "St. Gallen Endowment", "CH", "research", "open-api", "daily", ["trade-shipping"], "https://www.globaltradealert.org/", "stmt 2009+: protectionist measures announced and enacted, by country."),
  s("ustr-notices", "USTR Section 301 and tariff notices", "Office of the U.S. Trade Representative", "US", "primary-official", "open-api", "irregular", ["trade-shipping", "china-policy"], "https://ustr.gov/about-us/policy-offices/press-office/press-releases", "stmt 1974+: U.S. trade actions.", { apiUrl: "https://ustr.gov/rss.xml" }),
  s("wto-trade-monitoring", "WTO Trade Monitoring Reports", "World Trade Organization", "INTL", "multilateral", "page", "semiannual", ["trade-shipping", "summits"], "https://www.wto.org/english/tratop_e/tpr_e/trade_monitoring_e.htm", "stmt 2009+: G20 trade measures vs the standstill pledge."),
  s("drewry-wci", "Drewry World Container Index", "Drewry", "GB", "research", "page", "weekly", ["trade-shipping"], "https://www.drewry.co.uk/supply-chain-advisors/supply-chain-expertise/world-container-index-assessed-by-drewry", "2011+: the headline container rate, free weekly."),

  // ═══ 23. FINANCIAL STABILITY ═════════════════════════════════════════════
  s("fsb-nbfi", "FSB Global Monitoring Report on Non-Bank Financial Intermediation", "Financial Stability Board", "INTL", "multilateral", "page", "annual", ["fin-stability"], "https://www.fsb.org/work-of-the-fsb/financial-innovation-and-structural-change/non-bank-financial-intermediation/", "2011+: shadow-bank leverage by sector and country."),
  s("ofr-fsi", "OFR Financial Stress Index and Hedge Fund Monitor", "Office of Financial Research", "US", "primary-official", "open-api", "daily", ["fin-stability"], "https://www.financialresearch.gov/financial-stress-index/", "2000+ daily; hedge-fund leverage quarterly — the basis-trade amplifier.", { apiUrl: "https://www.financialresearch.gov/financial-stress-index/data/fsi.csv" }),
  s("ecb-fsr", "ECB Financial Stability Review", "European Central Bank", "EU", "primary-official", "page", "semiannual", ["fin-stability", "ecb"], "https://www.ecb.europa.eu/press/financial-stability-publications/fsr/html/index.en.html", "2004+: euro-area financial stability review; the risks the ECB names against the ones that materialise."),
  s("nyfed-gscpi", "Global Supply Chain Pressure Index", "Federal Reserve Bank of New York", "US", "primary-official", "open-api", "monthly", ["fin-stability", "trade-shipping"], "https://www.newyorkfed.org/research/policy/gscpi", "1997+: Global Supply Chain Pressure Index, monthly; the shipping-inflation link the models use."),
  s("fred-hy-oas", "ICE BofA US High Yield OAS (FRED BAMLH0A0HYM2)", "Federal Reserve Bank of St. Louis", "US", "primary-official", "open-api", "daily", ["fin-stability", "rates-markets"], "https://fred.stlouisfed.org/series/BAMLH0A0HYM2", "1996+: credit stress, daily, keyless."),
  s("moodys-default-study", "Annual default study (public summary)", "Moody's", "US", "research", "page", "annual", ["fin-stability", "sovereign-debt"], "https://www.moodys.com/", "1920+: default rates by rating; the summary is public."),
  s("cftc-cot", "Commitments of Traders", "Commodity Futures Trading Commission", "US", "primary-official", "open-api", "weekly", ["fin-stability", "opec", "food"], "https://www.cftc.gov/MarketReports/CommitmentsofTraders/index.htm", "1986+: positioning in Treasuries, FX, oil, grains.", { apiUrl: "https://publicreporting.cftc.gov/resource/jun7-fc8e.json?$limit=50&$order=report_date_as_yyyy_mm_dd%20DESC" }),
  s("sifma-stats", "SIFMA U.S. Treasury and repo statistics", "SIFMA", "US", "research", "page", "monthly", ["fin-stability", "treasury-holdings"], "https://www.sifma.org/resources/research/statistics/", "2000s+: trading volume, issuance, repo."),
  s("dtcc-repo", "DTCC Treasury repo and clearing statistics", "DTCC / FICC", "US", "research", "page", "daily", ["fin-stability"], "https://www.dtcc.com/charts/daily-volume-and-value", "2010s+: sponsored repo, the funding plumbing."),

  // ═══ 24. POLITICAL RISK ══════════════════════════════════════════════════
  s("gdelt-doc-api", "GDELT 2.0 DOC API (timeline volume)", "The GDELT Project", "INTL", "research", "open-api", "realtime", ["political-risk", "taiwan-risk", "china-policy"], "https://www.gdeltproject.org/", "2015+ (1979+ in events): global news volume and tone for any query, every 15 minutes.", { apiUrl: "https://api.gdeltproject.org/api/v2/doc/doc?query=%22Taiwan%20blockade%22&mode=timelinevol&format=json&timespan=90d" }),
  s("acled", "ACLED", "Armed Conflict Location & Event Data", "INTL", "research", "keyed-api", "weekly", ["political-risk"], "https://acleddata.com/", "1997+: conflict events by location.", { keyEnv: "ACLED_API_KEY" }),
  s("ucdp", "Uppsala Conflict Data Program", "Uppsala University", "INTL", "research", "open-api", "annual", ["political-risk"], "https://ucdp.uu.se/", "1946+: armed-conflict onsets, the base rates.", { apiUrl: "https://ucdpapi.pcr.uu.se/api/gedevents/25.1?pagesize=1" }),
  s("correlates-of-war", "Correlates of War", "COW Project", "INTL", "research", "open-api", "irregular", ["political-risk"], "https://correlatesofwar.org/", "1816+: interstate war, alliances, capabilities."),
  s("vdem", "V-Dem", "Varieties of Democracy Institute", "INTL", "research", "open-api", "annual", ["political-risk"], "https://v-dem.net/", "1789+: democracy indices by country-year."),
  s("freedom-house", "Freedom in the World", "Freedom House", "US", "research", "open-api", "annual", ["political-risk"], "https://freedomhouse.org/report/freedom-world", "1973+: political rights and civil liberties scores for every country, annually."),
  s("ifes-electionguide", "ElectionGuide", "IFES", "INTL", "research", "open-api", "daily", ["political-risk"], "https://www.electionguide.org/", "1998+: every election, dated."),
  s("metaculus", "Metaculus API", "Metaculus", "INTL", "secondary", "open-api", "realtime", ["political-risk", "taiwan-risk"], "https://www.metaculus.com/", "2015+: forecaster-community odds.", { apiUrl: "https://www.metaculus.com/api2/questions/?search=Taiwan&limit=5" }),
  s("kalshi", "Kalshi API", "Kalshi", "US", "secondary", "keyed-api", "realtime", ["political-risk", "fed"], "https://kalshi.com/", "2021+: regulated event contracts (Fed decisions, elections).", { keyEnv: "KALSHI_API_KEY" }),
  s("un-votes-voeten", "UN General Assembly voting data (Voeten)", "Harvard Dataverse", "INTL", "research", "open-api", "annual", ["political-risk", "un"], "https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/LEJUQZ", "1946+: alignment blocs."),

  // ═══ 2. ECB ══════════════════════════════════════════════════════════════
  s("ecb-data-portal", "ECB Data Portal (SDMX API)", "European Central Bank", "EU", "primary-official", "open-api", "daily", ["ecb", "rates-markets", "reserves-fx"], "https://data.ecb.europa.eu/", "1999+ (Bundesbank before): rates, balance sheet, money, bank lending.", { apiUrl: "https://data-api.ecb.europa.eu/service/data/FM/B.U2.EUR.4F.KR.MRR_FR.LEV?format=csvdata&lastNObservations=1" }),
  s("ecb-press", "ECB press releases and press-conference transcripts (RSS)", "European Central Bank", "EU", "primary-official", "open-api", "daily", ["ecb"], "https://www.ecb.europa.eu/press/pressconf/html/index.en.html", "stmt 1998+: the President's signalling, verbatim.", { apiUrl: "https://www.ecb.europa.eu/rss/press.html" }),
  s("ecb-accounts", "Governing Council monetary policy accounts", "European Central Bank", "EU", "primary-official", "page", "irregular", ["ecb"], "https://www.ecb.europa.eu/press/accounts/html/index.en.html", "stmt 2015+: options considered, dissent."),
  s("target2-balances", "TARGET balances", "European Central Bank / Bundesbank", "EU", "primary-official", "open-api", "monthly", ["ecb", "fin-stability"], "https://data.ecb.europa.eu/data/datasets/TGB", "2001+: intra-euro stress — the euro's fault line.", { apiUrl: "https://data-api.ecb.europa.eu/service/data/TGB/M.DE.N.A094T.U2.EUR.E?format=csvdata&lastNObservations=1" }),
  s("ecb-app-pepp", "APP and PEPP holdings by country", "European Central Bank", "EU", "primary-official", "page", "monthly", ["ecb"], "https://www.ecb.europa.eu/mopo/implement/app/html/index.en.html", "2015+: who the ECB backstops."),
  s("ecb-spf", "Survey of Professional Forecasters", "European Central Bank", "EU", "primary-official", "open-api", "quarterly", ["ecb"], "https://www.ecb.europa.eu/stats/ecb_surveys/survey_of_professional_forecasters/html/index.en.html", "1999+: consensus vs outcome."),
  s("ameco", "AMECO database", "European Commission DG ECFIN", "EU", "primary-official", "open-api", "semiannual", ["ecb", "sovereign-debt"], "https://economy-finance.ec.europa.eu/economic-research-and-databases/economic-databases/ameco-database_en", "1960+: fiscal and macro for every member, plus the Commission's twice-yearly forecasts."),
  s("eu-fiscal-board", "European Fiscal Board and Stability Programmes", "European Commission", "EU", "primary-official", "page", "annual", ["ecb", "sovereign-debt"], "https://commission.europa.eu/business-economy-euro/economic-and-fiscal-governance/european-fiscal-board-efb_en", "stmt 2016+: fiscal promises vs delivery by member."),
  s("esm-programmes", "ESM / EFSF programme documents", "European Stability Mechanism", "EU", "primary-official", "page", "irregular", ["ecb", "sovereign-debt"], "https://www.esm.europa.eu/", "stmt 2010+: bailout terms and compliance."),
  s("bundesbank-stats", "Bundesbank time series database", "Deutsche Bundesbank", "DE", "primary-official", "open-api", "monthly", ["ecb", "rates-markets"], "https://www.bundesbank.de/en/statistics/time-series-databases", "40y+: German series to the 1950s; the pre-euro record."),

  // ═══ 7. OECD ═════════════════════════════════════════════════════════════
  s("oecd-data-explorer", "OECD Data Explorer (SDMX API)", "OECD", "INTL", "multilateral", "open-api", "monthly", ["oecd"], "https://data-explorer.oecd.org/", "40y+: everything, 38 members and partners.", { apiUrl: "https://sdmx.oecd.org/public/rest/data/OECD.SDD.STES,DSD_STES@DF_CLI,4.1/USA.M.LI...AA...H?format=csvfilewithlabels&lastNObservations=1" }),
  s("oecd-cli", "Composite Leading Indicators", "OECD", "INTL", "multilateral", "open-api", "monthly", ["oecd", "rates-markets"], "https://www.oecd.org/en/data/indicators/composite-leading-indicator-cli.html", "1960s+: the standard turning-point signal."),
  s("oecd-economic-outlook", "Economic Outlook and archive", "OECD", "INTL", "multilateral", "page", "semiannual", ["oecd"], "https://www.oecd.org/en/publications/serials/oecd-economic-outlook_g1gh2f7a.html", "stmt 1967+: sixty years of forecasts to score."),
  s("oecd-mei", "Main Economic Indicators", "OECD", "INTL", "multilateral", "open-api", "monthly", ["oecd"], "https://www.oecd.org/en/data/datasets/main-economic-indicators-database.html", "40y+: Main Economic Indicators, monthly, for every member and key partner."),
  s("oecd-tax-database", "Tax Database and Revenue Statistics", "OECD", "INTL", "multilateral", "open-api", "annual", ["oecd", "us-fiscal"], "https://www.oecd.org/en/topics/sub-issues/tax-policy-analysis/oecd-tax-database.html", "1965+: rates by country and year."),
  s("oecd-pensions", "Pensions at a Glance / Global Pension Statistics", "OECD", "INTL", "multilateral", "open-api", "annual", ["oecd", "demographics"], "https://www.oecd.org/en/publications/pensions-at-a-glance-2023_678055dd-en.html", "2005+: replacement rates, funding."),
  s("oecd-surveys", "OECD Economic Surveys", "OECD", "INTL", "multilateral", "page", "irregular", ["oecd"], "https://www.oecd.org/en/publications/serials/oecd-economic-surveys_16097513.html", "stmt 1960s+: country verdicts."),
  s("oecd-interim", "Interim Economic Outlook", "OECD", "INTL", "multilateral", "page", "quarterly", ["oecd"], "https://www.oecd.org/en/about/news/press-releases.html", "2010+: quarterly revisions."),
  s("oecd-beps", "BEPS / Pillar Two documents", "OECD", "INTL", "multilateral", "page", "irregular", ["oecd", "us-fiscal"], "https://www.oecd.org/en/topics/base-erosion-and-profit-shifting-beps.html", "stmt 2013+: global tax rules that reach clients."),
  s("oecd-employment-outlook", "OECD Employment Outlook and labour statistics", "OECD", "INTL", "multilateral", "open-api", "annual", ["oecd", "demographics"], "https://www.oecd.org/en/publications/serials/oecd-employment-outlook_g1g1b0d8.html", "1983+: participation, ageing and wages across members; the retirement-age assumptions the pension engines use."),

  // ═══ 9. UNITED NATIONS ═══════════════════════════════════════════════════
  s("unsc-resolutions", "Security Council resolutions and voting records", "United Nations", "INTL", "primary-official", "open-api", "irregular", ["un", "political-risk"], "https://www.un.org/securitycouncil/content/resolutions-0", "stmt 1946+: the geopolitical statement ledger."),
  s("un-press-rss", "UN press releases (RSS)", "United Nations", "INTL", "primary-official", "open-api", "daily", ["un"], "https://press.un.org/en", "stmt: Secretary-General and Council statements.", { apiUrl: "https://press.un.org/en/rss.xml" }),
  s("unctad-stats", "UNCTADstat", "UN Trade and Development", "INTL", "multilateral", "open-api", "annual", ["un", "trade-shipping"], "https://unctadstat.unctad.org/", "1970+: FDI, trade, commodity dependence."),
  s("un-desa-wesp", "World Economic Situation and Prospects", "UN DESA", "INTL", "multilateral", "page", "semiannual", ["un"], "https://www.un.org/development/desa/dpad/publication/world-economic-situation-and-prospects-2026/", "1990s+: forecasts."),
  s("fao-fpi", "FAO Food Price Index", "Food and Agriculture Organization", "INTL", "multilateral", "open-api", "monthly", ["un", "food"], "https://www.fao.org/worldfoodsituation/foodpricesindex/en/", "1990+ monthly: the number behind food-driven unrest."),
  s("un-wpp", "World Population Prospects", "UN DESA Population Division", "INTL", "multilateral", "open-api", "irregular", ["un", "demographics"], "https://population.un.org/wpp/", "1950+: fertility, ageing, dependency, revised every two years."),
  s("unhcr-data", "UNHCR Refugee Data Finder", "UNHCR", "INTL", "multilateral", "open-api", "annual", ["un", "demographics"], "https://www.unhcr.org/refugee-statistics/", "1951+: displacement.", { apiUrl: "https://api.unhcr.org/population/v1/population/?limit=1" }),
  s("iaea-statements", "IAEA statements and Board reports", "International Atomic Energy Agency", "INTL", "multilateral", "open-api", "irregular", ["un", "political-risk"], "https://www.iaea.org/newscenter", "stmt 1957+: Iran and nuclear signalling.", { apiUrl: "https://www.iaea.org/feeds/topnews" }),
  s("un-sdg-report", "Sustainable Development Report", "UN SDSN", "INTL", "research", "page", "annual", ["un"], "https://dashboards.sdgindex.org/", "stmt 2016+: national commitments vs delivery."),

  // ═══ 13. CHINA PARTY-STATE, READ THROUGH U.S. AND ALLIED ANALYSTS ═════════
  s("csis-interpret-china", "Interpret: China", "Center for Strategic and International Studies", "US", "research", "open-api", "daily", ["china-party", "china-policy"], "https://interpret.csis.org/", "2020+: authoritative translations of policy documents (the documents themselves are older)."),
  s("merics", "MERICS China analysis", "Mercator Institute for China Studies", "DE", "research", "page", "weekly", ["china-party"], "https://merics.org/en", "2013+: independent reading of reforms."),

  // ═══ 20. FOOD ════════════════════════════════════════════════════════════
  s("usda-wasde", "WASDE", "USDA", "US", "primary-official", "open-api", "monthly", ["food"], "https://www.usda.gov/oce/commodity/wasde", "1973+: world supply and demand estimates."),
  s("usda-psd", "FAS Production, Supply and Distribution database", "USDA Foreign Agricultural Service", "US", "primary-official", "keyed-api", "monthly", ["food"], "https://apps.fas.usda.gov/psdonline/", "1960+: by country and commodity.", { keyEnv: "USDA_FAS_API_KEY" }),
  s("ifpri-export-restrictions", "Food and Fertilizer Export Restrictions Tracker", "IFPRI", "US", "research", "open-api", "weekly", ["food", "trade-shipping"], "https://www.ifpri.org/project/food-and-fertilizer-export-restrictions-tracker", "stmt 2022+ (2008 in reports): who banned exports and for how long."),
  s("igc-gmr", "Grain Market Report", "International Grains Council", "GB", "multilateral", "page", "monthly", ["food"], "https://www.igc.int/en/gmr_summary.aspx", "1990s+: Grain Market Report — world stocks, trade and prices, monthly."),
  s("fews-net", "FEWS NET", "USAID Famine Early Warning Systems Network", "US", "primary-official", "open-api", "monthly", ["food", "political-risk"], "https://fews.net/", "1985+: famine early warning."),
  s("worldbank-pink-sheet", "Commodity Price Data (Pink Sheet)", "World Bank", "INTL", "multilateral", "page", "monthly", ["food", "mdb", "minerals", "opec"], "https://www.worldbank.org/en/research/commodity-markets", "1960+ monthly: 70 commodities including fertilizer (Excel; parse monthly)."),
  s("amis-market-monitor", "AMIS Market Monitor", "Agricultural Market Information System (G20)", "INTL", "multilateral", "page", "monthly", ["food", "summits"], "https://www.amis-outlook.org/amis-monitoring", "2011+: the G20's coordinated view."),
  s("noaa-enso", "ENSO status and outlook", "NOAA Climate Prediction Center", "US", "primary-official", "open-api", "monthly", ["food", "catastrophe"], "https://www.cpc.ncep.noaa.gov/products/analysis_monitoring/enso_advisory/", "1950+: the weather driver of harvests."),

  // ═══ 3. BANK OF ENGLAND / UK ═════════════════════════════════════════════
  s("boe-iadb", "Bank of England Database (IADB)", "Bank of England", "GB", "primary-official", "open-api", "daily", ["boe", "rates-markets"], "https://www.bankofengland.co.uk/boeapps/database/", "40y+: rates, money, gilts as CSV.", { apiUrl: "https://www.bankofengland.co.uk/boeapps/database/_iadb-fromshowcolumns.asp?csv.x=yes&SeriesCodes=IUMABEDR&UsingCodes=Y&CSVF=TN&Datefrom=01/Jan/2025" }),
  s("boe-millennium", "A millennium of macroeconomic data", "Bank of England", "GB", "primary-official", "open-api", "irregular", ["boe"], "https://www.bankofengland.co.uk/statistics/research-datasets", "UK series to the 1200s."),
  s("boe-mpc", "MPC minutes and Monetary Policy Reports", "Bank of England", "GB", "primary-official", "open-api", "irregular", ["boe"], "https://www.bankofengland.co.uk/monetary-policy-summary-and-minutes", "stmt 1997+: votes and forecasts.", { apiUrl: "https://www.bankofengland.co.uk/rss/news" }),
  s("boe-speeches", "Speeches", "Bank of England", "GB", "primary-official", "page", "daily", ["boe"], "https://www.bankofengland.co.uk/news/speeches", "stmt 1990s+."),
  s("uk-dmo", "Debt Management Office", "HM Treasury DMO", "GB", "primary-official", "open-api", "daily", ["boe", "sovereign-debt"], "https://www.dmo.gov.uk/", "1998+: gilt issuance and auctions (the 2022 LDI episode)."),
  s("uk-obr", "Office for Budget Responsibility forecasts and accuracy evaluations", "OBR", "GB", "primary-official", "page", "semiannual", ["boe", "sovereign-debt"], "https://obr.uk/", "stmt 2010+: forecast vs outturn, self-audited."),
  s("uk-ons-api", "ONS API", "Office for National Statistics", "GB", "primary-official", "open-api", "monthly", ["boe"], "https://developer.ons.gov.uk/", "40y+: CPI, GDP, labour.", { apiUrl: "https://api.beta.ons.gov.uk/v1/datasets/cpih01/editions/time-series/versions" }),
  s("uk-hmt-budget", "HM Treasury budget documents", "HM Treasury", "GB", "primary-official", "page", "semiannual", ["boe", "sovereign-debt"], "https://www.gov.uk/government/organisations/hm-treasury", "stmt 1990s+: fiscal promises."),
  s("boe-fpc", "Financial Policy Committee record", "Bank of England", "GB", "primary-official", "page", "quarterly", ["boe", "fin-stability"], "https://www.bankofengland.co.uk/financial-policy-summary-and-record", "2011+: macroprudential."),

  // ═══ 6. WORLD BANK / MDBs ════════════════════════════════════════════════
  s("wb-gep", "Global Economic Prospects", "World Bank", "INTL", "multilateral", "page", "semiannual", ["mdb"], "https://www.worldbank.org/en/publication/global-economic-prospects", "1990s+: forecasts."),
  s("wb-wgi", "Worldwide Governance Indicators", "World Bank", "INTL", "multilateral", "open-api", "annual", ["mdb", "political-risk"], "https://www.worldbank.org/en/publication/worldwide-governance-indicators", "1996+: rule of law, corruption, stability.", { apiUrl: "https://api.worldbank.org/v2/country/all/indicator/RL.EST?format=json&mrv=1&per_page=400" }),
  s("wb-lic-dsf", "Debt Sustainability Framework ratings", "World Bank / IMF", "INTL", "multilateral", "page", "monthly", ["mdb", "sovereign-debt"], "https://www.worldbank.org/en/programs/debt-toolkit/dsa", "stmt 2005+: distress classifications for 70 countries."),
  s("wb-bready", "Business Ready (B-READY)", "World Bank", "INTL", "multilateral", "open-api", "annual", ["mdb"], "https://www.worldbank.org/en/businessready", "2024+ (Doing Business 2003–2019)."),
  s("adb-key-indicators", "Key Indicators for Asia and the Pacific", "Asian Development Bank", "INTL", "multilateral", "open-api", "annual", ["mdb", "nea-allies"], "https://kidb.adb.org/", "1970s+: Key Indicators for Asia and the Pacific — growth, debt and demography for 49 economies."),
  s("afdb-stats", "African Development Bank statistics", "African Development Bank", "INTL", "multilateral", "open-api", "annual", ["mdb"], "https://www.afdb.org/en/knowledge/statistics", "20y: African Development Bank statistics portal — debt, growth, commodity dependence."),
  s("iadb-stats", "Inter-American Development Bank data", "IDB", "INTL", "multilateral", "open-api", "annual", ["mdb"], "https://data.iadb.org/", "20y: Inter-American Development Bank data — Latin American fiscal and external positions."),
  s("wb-board-approvals", "World Bank Board approvals and country strategies", "World Bank", "INTL", "multilateral", "open-api", "daily", ["mdb"], "https://projects.worldbank.org/", "stmt: lending signals.", { apiUrl: "https://search.worldbank.org/api/v2/projects?format=json&rows=5" }),
  s("ebrd-transition-report", "EBRD Transition Report and country assessments", "European Bank for Reconstruction and Development", "INTL", "multilateral", "page", "annual", ["mdb", "political-risk"], "https://www.ebrd.com/transition-report", "1994+: reform scores for Eastern Europe, Türkiye and Central Asia; what the bank says a country will do versus its next score."),

  // ═══ 11. SOVEREIGN WEALTH FUNDS ══════════════════════════════════════════
  s("nbim-holdings", "NBIM full holdings", "Norges Bank Investment Management", "NO", "primary-official", "open-api", "annual", ["swf", "treasury-holdings"], "https://www.nbim.no/en/investments/", "1998+: every position of the $1.8 tn fund, annually; fixed-income by issuer."),
  s("adia-review", "ADIA annual review", "Abu Dhabi Investment Authority", "AE", "primary-official", "page", "annual", ["swf"], "https://www.adia.ae/", "2009+: allocation ranges."),
  s("temasek-gic", "Temasek Review and GIC annual report", "Temasek / GIC", "SG", "primary-official", "page", "annual", ["swf"], "https://www.temasekreview.com.sg/", "2004+: Temasek and GIC annual reviews — Singapore's stated allocation and the realised one."),
  s("kic-report", "Korea Investment Corporation annual report", "KIC", "KR", "primary-official", "page", "annual", ["swf", "nea-allies"], "https://www.kic.kr/en/", "2006+: Korea Investment Corporation annual report — Korean sovereign allocation."),
  s("swf-institute", "SWF Institute rankings", "SWFI", "US", "secondary", "page", "quarterly", ["swf"], "https://www.swfinstitute.org/fund-rankings/sovereign-wealth-fund", "2008+: size and transparency."),
  s("ifswf", "IFSWF Santiago Principles self-assessments", "International Forum of SWFs", "INTL", "multilateral", "page", "annual", ["swf"], "https://www.ifswf.org/", "stmt 2009+: governance commitments."),
  s("pif-annual", "PIF annual report", "Public Investment Fund", "SA", "primary-official", "page", "annual", ["swf", "oil-settlement"], "https://www.pif.gov.sa/en/", "2016+: Gulf allocation."),
  s("qia-report", "Qatar Investment Authority annual review and statements", "Qatar Investment Authority", "QA", "primary-official", "page", "annual", ["swf", "oil-settlement"], "https://www.qia.qa/", "2010s+: Gulf allocation and stated strategy; the declared U.S. commitments versus later filings."),
  s("kia-report", "Kuwait Investment Authority public statements", "Kuwait Investment Authority", "KW", "primary-official", "page", "irregular", ["swf", "oil-settlement"], "https://www.kia.gov.kw/", "1953+: the oldest sovereign fund; disclosure thin, statements to parliament recorded."),

  // ═══ 14. NORTH-EAST ASIAN ALLIES ═════════════════════════════════════════
  s("bok-ecos", "Bank of Korea ECOS API", "Bank of Korea", "KR", "primary-official", "keyed-api", "monthly", ["nea-allies", "rates-markets"], "https://ecos.bok.or.kr/api/", "1960+: everything Korean.", { keyEnv: "BOK_ECOS_API_KEY" }),
  s("kr-customs-20day", "Korea Customs Service first-20-days exports", "Korea Customs Service", "KR", "primary-official", "page", "monthly", ["nea-allies", "trade-shipping"], "https://www.customs.go.kr/english/main.do", "2000s+: the world's fastest hard trade indicator, day 21 of each month."),
  s("kr-moef-bok-statements", "MOEF and Bank of Korea statements", "Ministry of Economy and Finance / Bank of Korea", "KR", "primary-official", "page", "irregular", ["nea-allies"], "https://english.moef.go.kr/", "stmt 1990s+."),
  s("krx-foreign-flows", "Korea Exchange foreign investor flows", "Korea Exchange", "KR", "primary-official", "page", "daily", ["nea-allies"], "https://global.krx.co.kr/", "1990s+: risk appetite for Asia."),
  s("tw-moea-export-orders", "Export orders", "Taiwan Ministry of Economic Affairs", "TW", "primary-official", "open-api", "monthly", ["nea-allies", "taiwan-risk"], "https://www.moea.gov.tw/MNS/dos_e/home/Home.aspx", "1990s+: the chip-demand nowcast."),
  s("tw-dgbas", "DGBAS national statistics", "Taiwan DGBAS", "TW", "primary-official", "open-api", "monthly", ["nea-allies"], "https://eng.stat.gov.tw/", "1980s+: GDP, trade, CPI."),
  s("twse-foreign", "TWSE foreign investor trading", "Taiwan Stock Exchange", "TW", "primary-official", "open-api", "daily", ["nea-allies", "taiwan-risk"], "https://www.twse.com.tw/en/", "2000s+: the capital-flight tell."),
  s("boj-tankan", "Tankan survey", "Bank of Japan", "JP", "primary-official", "open-api", "quarterly", ["nea-allies", "japan-policy"], "https://www.boj.or.jp/en/statistics/tk/index.htm", "1974+: the quarterly business survey."),
  s("jp-esri-meti", "Cabinet Office ESRI and METI indices", "Government of Japan", "JP", "primary-official", "open-api", "monthly", ["nea-allies", "japan-policy"], "https://www.esri.cao.go.jp/en/", "1970s+: GDP, industrial output."),

  // ═══ 17. INDIA ═══════════════════════════════════════════════════════════
  s("rbi-dbie", "RBI Database on Indian Economy", "Reserve Bank of India", "IN", "primary-official", "open-api", "monthly", ["india", "reserves-fx"], "https://data.rbi.org.in/", "1950s+: money, credit, rates, reserves."),
  s("rbi-mpc", "Monetary Policy statements and minutes", "Reserve Bank of India", "IN", "primary-official", "open-api", "irregular", ["india"], "https://www.rbi.org.in/Scripts/BS_PressReleaseDisplay.aspx", "stmt 1990s+.", { apiUrl: "https://www.rbi.org.in/pressreleases_rss.xml" }),
  s("in-economic-survey", "Economic Survey and Union Budget speech", "Ministry of Finance, India", "IN", "primary-official", "page", "annual", ["india", "sovereign-debt"], "https://www.indiabudget.gov.in/", "stmt 1950s+: promises vs delivery."),
  s("in-mospi", "MOSPI", "Ministry of Statistics, India", "IN", "primary-official", "open-api", "monthly", ["india"], "https://www.mospi.gov.in/", "1950s+: GDP, CPI."),
  s("in-sebi-nse", "SEBI / NSE foreign portfolio flows", "SEBI / NSE", "IN", "primary-official", "open-api", "daily", ["india"], "https://www.nseindia.com/", "1990s+: SEBI and NSE statistics — foreign portfolio flows, the daily India risk read."),
  s("in-niti-aayog", "NITI Aayog", "Government of India", "IN", "primary-official", "page", "irregular", ["india"], "https://www.niti.gov.in/", "stmt 2015+: policy signalling."),
  s("in-eci", "Election Commission of India", "ECI", "IN", "primary-official", "open-api", "irregular", ["india", "political-risk"], "https://eci.gov.in/", "1951+: election calendar and results."),
  s("rbi-fsr", "RBI Financial Stability Report", "Reserve Bank of India", "IN", "primary-official", "page", "semiannual", ["india", "fin-stability"], "https://www.rbi.org.in/Scripts/FsReports.aspx", "2010+: bank stress tests and the systemic risk survey; the Governor's stated risks against the next report's realised ones."),
  s("in-pib-rss", "Press Information Bureau releases (Ministry of Finance)", "Government of India", "IN", "primary-official", "open-api", "daily", ["india"], "https://pib.gov.in/", "stmt 2000s+: GST collections, fiscal targets and budget statements as released.", { apiUrl: "https://pib.gov.in/RssMain.aspx?ModId=6&Lang=1&Regid=3" }),
  s("in-dea-debt-report", "Public Debt Management quarterly report", "Ministry of Finance, Department of Economic Affairs", "IN", "primary-official", "page", "quarterly", ["india", "sovereign-debt"], "https://dea.gov.in/public-debt-management", "2010+: central government borrowing, maturity profile and ownership — the borrowing plan stated versus the borrowing done."),

  // ═══ 18. EM CENTRAL BANKS WITH OPEN APIs ═════════════════════════════════
  s("bcb-sgs", "Banco Central do Brasil SGS API", "Banco Central do Brasil", "BR", "primary-official", "open-api", "daily", ["em-central-banks", "rates-markets"], "https://www3.bcb.gov.br/sgspub/", "1980s+: 20,000 series.", { apiUrl: "https://api.bcb.gov.br/dados/serie/bcdata.sgs.432/dados/ultimos/1?formato=json" }),
  s("banxico-sie", "Banxico SIE API", "Banco de México", "MX", "primary-official", "keyed-api", "daily", ["em-central-banks"], "https://www.banxico.org.mx/SieAPIRest/service/v1/", "1990s+: Banco de México SIE API — policy rate, peso, remittances.", { keyEnv: "BANXICO_TOKEN" }),
  s("cbrt-evds", "CBRT EVDS API", "Central Bank of the Republic of Türkiye", "TR", "primary-official", "keyed-api", "daily", ["em-central-banks"], "https://evds2.tcmb.gov.tr/", "1980s+: the political-pressure case study.", { keyEnv: "CBRT_EVDS_KEY" }),
  s("sarb-api", "SARB Web API", "South African Reserve Bank", "ZA", "primary-official", "open-api", "daily", ["em-central-banks"], "https://www.resbank.co.za/en/home/what-we-do/statistics", "1960s+: South African Reserve Bank data — repo rate, rand, reserves.", { apiUrl: "https://custom.resbank.co.za/SarbWebApi/WebIndicators/HomePageRates" }),
  s("bi-indonesia", "Bank Indonesia statistics", "Bank Indonesia", "ID", "primary-official", "page", "monthly", ["em-central-banks"], "https://www.bi.go.id/en/statistik/", "1990s+: Bank Indonesia statistics — BI rate, rupiah, external debt."),
  s("bcch-api", "Banco Central de Chile API", "Banco Central de Chile", "CL", "primary-official", "keyed-api", "daily", ["em-central-banks", "minerals"], "https://si3.bcentral.cl/Siete/en/api", "1980s+: the copper economy.", { keyEnv: "BCCH_API_USER" }),
  s("cbe-egypt", "Central Bank of Egypt", "CBE", "EG", "primary-official", "page", "monthly", ["em-central-banks", "sovereign-debt"], "https://www.cbe.org.eg/en", "2000s+: the distress case."),
  s("sbp-pakistan", "State Bank of Pakistan", "SBP", "PK", "primary-official", "page", "monthly", ["em-central-banks", "sovereign-debt"], "https://www.sbp.org.pk/", "2000s+: State Bank of Pakistan data — policy rate, reserves, IMF programme compliance."),
  s("bcra-api", "BCRA principal variables API", "Banco Central de la República Argentina", "AR", "primary-official", "open-api", "daily", ["em-central-banks", "sovereign-debt"], "https://www.bcra.gob.ar/", "1990s+: the default case.", { apiUrl: "https://api.bcra.gob.ar/estadisticas/v3.0/monetarias/1" }),
  s("cbn-nigeria", "Central Bank of Nigeria statistics", "CBN", "NG", "primary-official", "page", "monthly", ["em-central-banks", "opec"], "https://www.cbn.gov.ng/rates/", "2000s+: Central Bank of Nigeria statistics — MPR, naira windows, reserves."),

  // ═══ 21. ENERGY TRANSITION AND CRITICAL MINERALS ═════════════════════════
  s("usgs-mcs", "Mineral Commodity Summaries", "U.S. Geological Survey", "US", "primary-official", "open-api", "annual", ["minerals"], "https://www.usgs.gov/centers/national-minerals-information-center/mineral-commodity-summaries", "1930s+: production, reserves, import reliance by mineral."),
  s("iea-critical-minerals", "Critical Minerals Outlook and Data Explorer", "International Energy Agency", "INTL", "multilateral", "page", "annual", ["minerals"], "https://www.iea.org/topics/critical-minerals", "2021+: IEA Critical Minerals Market Review — supply concentration by country and mineral."),
  s("ember", "Ember electricity data", "Ember", "GB", "research", "open-api", "monthly", ["minerals"], "https://ember-energy.org/data/", "2000+: generation by source, monthly, open CSV."),
  s("irena", "IRENA statistics", "International Renewable Energy Agency", "INTL", "multilateral", "open-api", "annual", ["minerals"], "https://www.irena.org/Data", "2000+: capacity and cost."),
  s("lme-reports", "LME daily reports and stocks", "London Metal Exchange", "GB", "research", "page", "daily", ["minerals"], "https://www.lme.com/en/market-data/reports-and-data", "1980s+: prices and warehouse stocks (headline data free)."),
  s("eia-electricity", "EIA electricity data (grid and AI-load demand)", "U.S. Energy Information Administration", "US", "primary-official", "keyed-api", "monthly", ["minerals"], "https://www.eia.gov/electricity/data.php", "1990+: EIA electricity data — generation mix, prices and the data-centre load build.", { keyEnv: "EIA_API_KEY" }),
  s("copernicus-c3s", "Copernicus Climate Data Store", "ECMWF / EU", "EU", "multilateral", "keyed-api", "monthly", ["minerals", "catastrophe"], "https://cds.climate.copernicus.eu/", "1979+: temperature, drought.", { keyEnv: "CDS_API_KEY" }),

  // ═══ 22. DEMOGRAPHICS, PENSIONS, MIGRATION ═══════════════════════════════
  s("jp-ipss", "IPSS population projections", "National Institute of Population and Social Security Research, Japan", "JP", "primary-official", "open-api", "irregular", ["demographics", "japan-policy"], "https://www.ipss.go.jp/index-e.asp", "1960s+: the oldest society's own projections."),
  s("eurostat-population", "Eurostat population and migration", "Eurostat", "EU", "primary-official", "open-api", "annual", ["demographics"], "https://ec.europa.eu/eurostat/web/population-demography", "1960+: Eurostat population and projections — the ageing baseline for European debt.", { apiUrl: "https://ec.europa.eu/eurostat/api/dissemination/statistics/1.0/data/demo_pjan?format=JSON&lastTimePeriod=1&geo=EU27_2020&sex=T&age=TOTAL" }),
  s("us-census-pop", "Census population estimates and projections", "U.S. Census Bureau", "US", "primary-official", "open-api", "annual", ["demographics"], "https://www.census.gov/programs-surveys/popest.html", "1900+: Census population estimates and projections — the U.S. dependency ratio the pension engines use.", { apiUrl: "https://api.census.gov/data/2023/pep/population?get=POP_2023,NAME&for=us:*" }),
  s("dhs-cbp-encounters", "CBP encounters", "U.S. Department of Homeland Security", "US", "primary-official", "open-api", "monthly", ["demographics", "political-risk"], "https://www.cbp.gov/newsroom/stats/southwest-land-border-encounters", "2000+: U.S. migration flows."),
  s("mercer-cfa-pension-index", "Mercer CFA Institute Global Pension Index", "Mercer / CFA Institute", "AU", "research", "page", "annual", ["demographics"], "https://www.mercer.com/insights/investments/market-outlook-and-trends/mercer-cfa-global-pension-index/", "2009+: system rankings."),
  s("hmd-mortality", "Human Mortality Database", "Max Planck / UC Berkeley", "INTL", "research", "open-api", "annual", ["demographics"], "https://www.mortality.org/", "40y+: the longevity assumption behind every policy."),
  s("soa-mortality", "SOA mortality tables and improvement scales", "Society of Actuaries", "US", "research", "open-api", "annual", ["demographics"], "https://www.soa.org/resources/experience-studies/", "40y+: what the carriers actually price on."),

  // ═══ 25. CATASTROPHE, CLIMATE, INSURANCE ═════════════════════════════════
  s("noaa-billion-dollar", "Billion-Dollar Weather and Climate Disasters", "NOAA NCEI", "US", "primary-official", "open-api", "monthly", ["catastrophe"], "https://www.ncei.noaa.gov/access/billions/", "1980+: U.S. losses by event."),
  s("em-dat", "EM-DAT International Disaster Database", "CRED, UCLouvain", "INTL", "research", "keyed-api", "monthly", ["catastrophe"], "https://www.emdat.be/", "1900+: global disasters (free academic/non-commercial key).", { keyEnv: "EMDAT_API_KEY" }),
  s("swiss-re-sigma", "sigma research (public summaries)", "Swiss Re Institute", "CH", "research", "page", "annual", ["catastrophe"], "https://www.swissre.com/institute/research/sigma-research.html", "1970+: insured losses."),
  s("munich-re-natcat", "NatCatSERVICE (public releases)", "Munich Re", "DE", "research", "page", "annual", ["catastrophe"], "https://www.munichre.com/en/solutions/for-industry-clients/natcatservice.html", "1980+: Munich Re NatCatSERVICE — insured and economic loss by event, annually."),
  s("nhc-hurricanes", "National Hurricane Center", "NOAA", "US", "primary-official", "open-api", "daily", ["catastrophe"], "https://www.nhc.noaa.gov/", "1950+: the season, live.", { apiUrl: "https://www.nhc.noaa.gov/CurrentStorms.json" }),
  s("fema-nri", "National Risk Index", "FEMA", "US", "primary-official", "open-api", "annual", ["catastrophe"], "https://hazards.fema.gov/nri/", "2020+: county-level risk."),
  s("naic-filings", "NAIC and state insurance-department rate filings", "NAIC / state DOIs", "US", "primary-official", "page", "daily", ["catastrophe"], "https://content.naic.org/", "stmt 2000s+: rate requests vs approvals; insurer withdrawals."),
  s("ambest-actions", "A.M. Best rating actions (public press releases)", "AM Best", "US", "research", "open-api", "daily", ["catastrophe"], "https://news.ambest.com/", "stmt 1990s+: solvency of the carriers in `carrier_rate_sheets`.", { apiUrl: "https://news.ambest.com/rss/pressreleases.aspx" }),
  s("fl-oir-ca-doi", "Florida OIR and California DOI announcements", "State regulators", "US", "primary-official", "page", "daily", ["catastrophe"], "https://www.floir.com/", "stmt 2000s+: the two markets in crisis."),

  // ═══ 8. WORLD ECONOMIC FORUM — sentiment tier, last ══════════════════════
  s("wef-global-risks", "Global Risks Report and Perception Survey", "World Economic Forum", "CH", "research", "page", "annual", ["wef"], "https://www.weforum.org/publications/global-risks-report-2026/", "stmt 2006+: what 1,000 executives feared, and whether it happened."),
  s("wef-davos", "Annual Meeting sessions and press releases", "World Economic Forum", "CH", "research", "open-api", "annual", ["wef"], "https://www.weforum.org/press/", "stmt 2000s+: the elite narrative.", { apiUrl: "https://www.weforum.org/feeds/press.rss" }),
  s("wef-chief-economists", "Chief Economists Outlook", "World Economic Forum", "CH", "research", "page", "quarterly", ["wef"], "https://www.weforum.org/publications/series/chief-economists-outlook/", "2020+: quarterly consensus."),
  s("jackson-hole", "Jackson Hole Economic Symposium papers", "Federal Reserve Bank of Kansas City", "US", "primary-official", "page", "annual", ["wef", "fed"], "https://www.kansascityfed.org/research/jackson-hole-economic-symposium/", "stmt 1978+: the central-bank intellectual agenda."),
  s("munich-security-report", "Munich Security Report", "Munich Security Conference", "DE", "research", "page", "annual", ["wef", "political-risk"], "https://securityconference.org/en/publications/munich-security-report/", "2015+: Munich Security Report — the transatlantic threat consensus each February, scored against the year."),
  s("iif-public", "IIF public research and Global Debt Monitor summaries", "Institute of International Finance", "US", "research", "page", "quarterly", ["wef", "sovereign-debt"], "https://www.iif.com/", "2000s+: bank-CEO narrative and the debt headline."),
  s("wef-future-of-jobs", "Future of Jobs Report", "World Economic Forum", "CH", "research", "page", "irregular", ["wef", "demographics"], "https://www.weforum.org/publications/the-future-of-jobs-report-2025/", "2016+: what employers say they will do about automation; scored against BLS outcomes five years on."),
  s("spief", "St Petersburg International Economic Forum plenary record", "Roscongress Foundation", "RU", "research", "page", "annual", ["wef", "sanctions", "oil-settlement"], "https://forumspb.com/", "stmt 1997+: the non-Western settlement and de-dollarisation claims, verbatim, for the petrodollar ledger."),
  s("milken-global", "Milken Institute Global Conference sessions", "Milken Institute", "US", "research", "page", "annual", ["wef", "fin-stability"], "https://milkeninstitute.org/events/global-conference", "stmt 1998+: the U.S. asset-manager consensus on record each spring."),

  // ═══ W8. Keyless history sources for the factor panel and the ledger ═══════
  s("nyfed-acm", "ACM term premium (Adrian–Crump–Moench), daily CSV", "Federal Reserve Bank of New York", "US", "primary-official", "open-api", "daily", ["fed", "rates-markets"], "https://www.newyorkfed.org/research/data_indicators/term-premia-tabs", "1961+: the 10-year term premium the liquidation engine's yield channel is priced against; one CSV, no key.", { apiUrl: "https://www.newyorkfed.org/medialibrary/media/research/data_indicators/ACMTermPremium.csv" }),
  s("nyfed-soma", "System Open Market Account holdings (Markets Data API)", "Federal Reserve Bank of New York", "US", "primary-official", "open-api", "weekly", ["fed", "treasury-holdings"], "https://www.newyorkfed.org/markets/soma-holdings", "2003+: Fed Treasury holdings by week, JSON, no key; the buyer of last resort's actual book.", { apiUrl: "https://markets.newyorkfed.org/api/soma/summary.json" }),
  s("fed-h8", "H.8 Assets and Liabilities of Commercial Banks (Data Download Program)", "Federal Reserve Board", "US", "primary-official", "open-api", "weekly", ["fed", "fin-stability"], "https://www.federalreserve.gov/releases/h8/", "1973+: bank credit, securities and deposits weekly; the same DDP CSV transport as H.15.", { apiUrl: "https://www.federalreserve.gov/datadownload/Output.aspx?rel=H8&filetype=csv&label=include&layout=seriescolumn" }),
  s("wb-wdi-api", "World Development Indicators API (any indicator, any country, JSON)", "World Bank", "INTL", "multilateral", "open-api", "annual", ["mdb", "demographics", "sovereign-debt"], "https://datahelpdesk.worldbank.org/knowledgebase/articles/889392", "1960+: 1,400 indicators for 217 economies, keyless JSON; world growth for the factor panel.", { apiUrl: "https://api.worldbank.org/v2/country/WLD/indicator/NY.GDP.MKTP.KD.ZG?format=json&per_page=100" }),
  s("sipri-milex", "SIPRI Military Expenditure Database", "Stockholm International Peace Research Institute", "INTL", "research", "page", "annual", ["political-risk", "taiwan-risk"], "https://www.sipri.org/databases/milex", "1949+: military spending for 170 states in constant dollars; the annual release is an .xlsx, read on the 36-hour review, not by a connector."),
  s("wikidata", "Wikidata (SPARQL and entity search)", "Wikimedia Foundation", "INTL", "secondary", "open-api", "realtime", ["political-risk", "summits"], "https://www.wikidata.org/", "Persons and offices for the ledger: who holds which office as of when, with the office item's cited start date; keyless, rate-limited, parse only.", { apiUrl: "https://query.wikidata.org/sparql?format=json&query=" }),

  // ═══ HOUSEHOLD LAYER — what families pay and do, forty years back ═════════
  // FRED carries most of the price and behaviour series keyless (registry id
  // `fred`); these rows are the publishers behind the rest.
  s("nces-digest", "NCES Digest of Education Statistics, Table 330.10 (tuition, room and board since 1963)", "National Center for Education Statistics", "US", "primary-official", "page", "annual", ["cost-of-living"], "https://nces.ed.gov/programs/digest/d23/tables/dt23_330.10.asp", "1963+: average undergraduate tuition, fees, room and board by institution type in current and constant dollars; the sixty-year college-cost record."),
  s("college-board-trends", "Trends in College Pricing and Student Aid", "College Board", "US", "research", "page", "annual", ["cost-of-living"], "https://research.collegeboard.org/trends/college-pricing", "1971+: published sticker and net prices by sector, books and supplies, other expenses; the annual October release the estimator's baseline rows cite."),
  s("studentaid-rates", "Federal student loan interest rates and fees", "U.S. Department of Education, Federal Student Aid", "US", "primary-official", "page", "annual", ["cost-of-living"], "https://studentaid.gov/understand-aid/types/loans/interest-rates", "2006+: Direct undergraduate, graduate and PLUS rates by award year with origination fees; the loan side of the total college package."),
  s("nyfed-hhdc", "Quarterly Report on Household Debt and Credit", "Federal Reserve Bank of New York", "US", "primary-official", "page", "quarterly", ["household"], "https://www.newyorkfed.org/microeconomics/hhdc", "2003+: mortgage, auto, card and student balances, delinquency transitions by age; the balance-sheet stress read."),
  s("fed-scf", "Survey of Consumer Finances", "Federal Reserve Board", "US", "primary-official", "page", "irregular", ["household"], "https://www.federalreserve.gov/econres/scfindex.htm", "1989+ every three years: net worth and income by age, education, occupation category and percentile; the relative-wealth module's reference table (2022 wave, published Oct 2023)."),
  s("fed-dfa", "Distributional Financial Accounts (CSV download)", "Federal Reserve Board", "US", "primary-official", "open-api", "quarterly", ["household"], "https://www.federalreserve.gov/releases/z1/dataviz/dfa/", "1989+: household net worth by wealth percentile, age, generation, education and race, quarterly, keyless CSV; refreshes the SCF table between waves.", { apiUrl: "https://www.federalreserve.gov/releases/z1/dataviz/download/zips/dfa-networth-levels-age.csv" }),
  s("bls-oes", "Occupational Employment and Wage Statistics", "Bureau of Labor Statistics", "US", "primary-official", "open-api", "annual", ["household"], "https://www.bls.gov/oes/", "1997+: median and mean wages for 800+ occupations by state and metro; the profession-peer income the relative-wealth module compares against (API v1 keyless, 25 queries a day).", { apiUrl: "https://api.bls.gov/publicAPI/v1/timeseries/data/" }),
  s("census-acs", "American Community Survey API", "U.S. Census Bureau", "US", "primary-official", "open-api", "annual", ["household"], "https://www.census.gov/data/developers/data-sets/acs-1year.html", "2005+: income by age, occupation and geography; keyless up to 500 requests a day.", { apiUrl: "https://api.census.gov/data/2023/acs/acs1" }),
  s("sec-edgar-xbrl", "SEC EDGAR XBRL company facts and frames (keyless JSON)", "U.S. Securities and Exchange Commission", "US", "primary-official", "open-api", "quarterly", ["household"], "https://www.sec.gov/edgar/sec-api-documentation", "2009+: every filer's reported revenues by quarter; McDonald's, Walmart, Dollar General, Costco, Kroger, AutoZone as the 'where people eat and shop' tells, from the filings themselves (User-Agent header required).", { apiUrl: "https://data.sec.gov/api/xbrl/companyfacts/CIK0000063908.json" }),
  s("cox-manheim", "Manheim Used Vehicle Value Index and Cox Automotive sales forecasts", "Cox Automotive", "US", "research", "page", "monthly", ["cost-of-living"], "https://www.coxautoinc.com/insights/", "1995+: used-vehicle wholesale prices monthly; new-vehicle average transaction price (Kelley Blue Book) monthly since 2012."),
  s("bea-motor-vehicles", "BEA motor vehicle unit sales and average expenditure", "Bureau of Economic Analysis", "US", "primary-official", "open-api", "monthly", ["cost-of-living"], "https://www.bea.gov/data/consumer-spending/motor-vehicles", "1967+: light-vehicle unit sales and average expenditure per new vehicle; the forty-year average-car-price record (FRED carries the unit series as TOTALSA).", { apiUrl: "https://fred.stlouisfed.org/graph/fredgraph.csv?id=TOTALSA" }),
  s("zillow-research", "Zillow Home Value Index and Observed Rent Index (CSV downloads)", "Zillow", "US", "research", "open-api", "monthly", ["cost-of-living"], "https://www.zillow.com/research/data/", "1996+ (ZHVI) and 2015+ (ZORI): home values and asking rents by metro and zip, keyless CSV.", { apiUrl: "https://files.zillowstatic.com/research/public_csvs/zhvi/Metro_zhvi_uc_sfrcondo_tier_0.33_0.67_sm_sa_month.csv" }),
  s("redfin-data-center", "Redfin housing market data (TSV downloads)", "Redfin", "US", "research", "open-api", "weekly", ["cost-of-living"], "https://www.redfin.com/news/data-center/", "2012+: weekly pending sales, median sale price, days on market, price drops; the daily-cadence read on the housing market the owner asked for."),
  s("usda-food-plans", "USDA Food Plans: cost of food at home, monthly", "U.S. Department of Agriculture", "US", "primary-official", "page", "monthly", ["cost-of-living"], "https://www.fns.usda.gov/research/cnpp/usda-food-plans/cost-food-monthly-reports", "1994+: what a family of four spends on the thrifty, low, moderate and liberal food plans; the grocery line of the household budget."),
  s("kff-ehbs", "Employer Health Benefits Survey", "KFF", "US", "research", "page", "annual", ["cost-of-living"], "https://www.kff.org/health-costs/report/employer-health-benefits-survey/", "1999+: average family premium and worker contribution; the health line of the household budget."),
  s("ssa-awi", "National Average Wage Index", "Social Security Administration", "US", "primary-official", "page", "annual", ["household"], "https://www.ssa.gov/oact/cola/AWI.html", "1951+: the average wage every American's benefit is indexed to; the wage denominator for a seventy-year affordability ratio."),
  s("bls-cex", "Consumer Expenditure Surveys", "Bureau of Labor Statistics", "US", "primary-official", "open-api", "annual", ["household"], "https://www.bls.gov/cex/", "1984+: what households spend by category, income decile and age; food away from home versus at home is the fast-food tell measured properly.", { apiUrl: "https://api.bls.gov/publicAPI/v1/timeseries/data/" }),
  s("opentable-state", "OpenTable State of the Industry (seated diners)", "OpenTable", "US", "research", "page", "daily", ["household"], "https://www.opentable.com/state-of-industry", "2020+: seated diners versus 2019 by day and city; the fastest read on discretionary dining."),
  s("tsa-throughput", "TSA checkpoint travel numbers", "Transportation Security Administration", "US", "primary-official", "page", "daily", ["household"], "https://www.tsa.gov/travel/passenger-volumes", "2019+: daily passengers screened; discretionary travel in near-real time."),
  s("nahb-hmi", "NAHB/Wells Fargo Housing Market Index", "National Association of Home Builders", "US", "research", "page", "monthly", ["cost-of-living"], "https://www.nahb.org/news-and-economics/housing-economics/indices/housing-market-index", "1985+: builder sentiment; leads starts and permits."),
  s("challenger-layoffs", "Challenger, Gray & Christmas job-cut announcements", "Challenger, Gray & Christmas", "US", "research", "page", "monthly", ["household"], "https://www.challengergray.com/blog/category/job-cut-report/", "1993+: announced layoffs by sector; leads claims by a month or two."),
];

/**
 * The build order the operator asked for, with the reason. Ten P1 domains
 * first (all free, all with a said-vs-did ledger), then the P2 set, WEF last.
 */
export const EXPANSION_BUILD_ORDER: Array<{ order: number; domain: Domain; catalogueNumber: number; why: string }> = [
  { order: 1, domain: "fed", catalogueNumber: 1, why: "The most consequential speaker; RSS feeds and DDP CSV are live today; dots-vs-outcome is a ready ledger." },
  { order: 2, domain: "bis", catalogueNumber: 4, why: "One SDMX API for the credit-gap crisis predictor and one RSS for every governor's speech since 1997." },
  { order: 3, domain: "imf", catalogueNumber: 5, why: "IFS JSON API to 1948 plus MONA, a pre-coded compliance ledger for 180 countries." },
  { order: 4, domain: "summits", catalogueNumber: 10, why: "Compliance reports already score decades of promises; import them to calibrate the credibility multiplier." },
  { order: 5, domain: "us-fiscal", catalogueNumber: 12, why: "Fiscal Data and Federal Register APIs are keyless JSON; Trustees and CBO give eighty years of forecasts with outcomes." },
  { order: 6, domain: "opec", catalogueNumber: 15, why: "The cleanest said-vs-did series in commodities: communiqué RSS against production numbers we already pull." },
  { order: 7, domain: "sanctions", catalogueNumber: 16, why: "OpenSanctions and CREA are open JSON; every corridor in the petrodollar ledger has a sanction behind it." },
  { order: 8, domain: "trade-shipping", catalogueNumber: 19, why: "WTO API, Global Trade Alert and port statistics; Korea's 20-day exports arrive with domain 14." },
  { order: 9, domain: "fin-stability", catalogueNumber: 23, why: "OFR stress index CSV daily, CFTC positioning JSON weekly, HY OAS keyless on FRED — the amplifiers of any Treasury sale." },
  { order: 10, domain: "political-risk", catalogueNumber: 24, why: "GDELT DOC API for event volume, UCDP API for forty years of conflict onsets — the base rates the Taiwan priors need." },
  { order: 11, domain: "ecb", catalogueNumber: 2, why: "SDMX CSV for rates and TARGET balances; press RSS since 1998." },
  { order: 12, domain: "oecd", catalogueNumber: 7, why: "SDMX for the CLI turning-point signal; sixty years of forecasts." },
  { order: 13, domain: "un", catalogueNumber: 9, why: "FAO food prices, population, UNHCR API, Security Council ledger since 1946." },
  { order: 14, domain: "china-party", catalogueNumber: 13, why: "Extends the existing China panel with the party-state's own targets vs outturn since 1954." },
  { order: 15, domain: "food", catalogueNumber: 20, why: "WASDE, ENSO, export-restriction tracker — the inflation and unrest channel." },
  { order: 16, domain: "boe", catalogueNumber: 3, why: "IADB CSV is keyless; OBR self-audits its forecasts." },
  { order: 17, domain: "mdb", catalogueNumber: 6, why: "World Bank APIs already wired; add governance indicators and project approvals." },
  { order: 18, domain: "swf", catalogueNumber: 11, why: "NBIM publishes every holding; the quarterly allocation shift out of Treasuries." },
  { order: 19, domain: "nea-allies", catalogueNumber: 14, why: "Korea's 20-day exports and Taiwan's export orders are the fastest hard reads on demand and chips." },
  { order: 20, domain: "india", catalogueNumber: 17, why: "RBI RSS and DBIE; the rupee corridor in the oil ledger." },
  { order: 21, domain: "em-central-banks", catalogueNumber: 18, why: "Brazil, Argentina and South Africa have keyless JSON APIs; Türkiye is the follow-through case study." },
  { order: 22, domain: "minerals", catalogueNumber: 21, why: "USGS annual, Ember monthly; the export-control channel already tracked under China." },
  { order: 23, domain: "demographics", catalogueNumber: 22, why: "Slow-moving; Eurostat and Census APIs are keyless; Trustees arrive with domain 12." },
  { order: 24, domain: "catastrophe", catalogueNumber: 25, why: "NHC JSON live; NOAA annual; A.M. Best RSS watches the carriers in the rate-sheet table." },
  { order: 25, domain: "wef", catalogueNumber: 8, why: "Sentiment only; last, and never as a fact source." },
];
