// Generated deterministically from App.tsx and AppShell.tsx.
// Do not remove routes here; the page audit may later change recommendations.
export type SecondaryCatalogCategory =
  | "Advanced Analysis"
  | "Reports & Documents"
  | "Reference & Education"
  | "Operations & Administration"
  | "Experience & Experimental"
  | "Additional Tools";

export type SecondaryCatalogItem = { path: string; label: string; category: SecondaryCatalogCategory };

export const SECONDARY_CATALOG: SecondaryCatalogItem[] = [
  { path: "/portal/admin", label: "Admin", category: "Operations & Administration" },
  { path: "/portal/advanced-reporting", label: "Advanced Reporting", category: "Reports & Documents" },
  { path: "/portal/advisor-chat", label: "Advisor Chat", category: "Additional Tools" },
  { path: "/portal/advisor-directory", label: "Advisor Directory", category: "Additional Tools" },
  { path: "/portal/advisor-training", label: "Advisor Training", category: "Reference & Education" },
  { path: "/portal/affiliate-links", label: "Affiliate Links", category: "Additional Tools" },
  { path: "/portal/agency-tutorial", label: "Agency Tutorial", category: "Reference & Education" },
  { path: "/portal/ai", label: "AI", category: "Additional Tools" },
  { path: "/portal/annuity-memory", label: "Annuity Memory", category: "Additional Tools" },
  { path: "/portal/athene-guaranteed-income", label: "Athene Guaranteed Income", category: "Additional Tools" },
  { path: "/portal/athene-pe-plus15", label: "Athene Pe Plus15", category: "Additional Tools" },
  { path: "/portal/audit-timeline", label: "Audit Timeline", category: "Operations & Administration" },
  { path: "/portal/axonic-sp500", label: "Axonic Sp500", category: "Additional Tools" },
  { path: "/portal/batch-illustration", label: "Batch Illustration", category: "Additional Tools" },
  { path: "/portal/batch-slides", label: "Batch Slides", category: "Reports & Documents" },
  { path: "/portal/branding", label: "Branding", category: "Additional Tools" },
  { path: "/portal/carrier-rates", label: "Carrier Rates", category: "Additional Tools" },
  { path: "/portal/carrier-ratings", label: "Carrier Ratings", category: "Additional Tools" },
  { path: "/portal/carrier-settings", label: "Carrier Settings", category: "Operations & Administration" },
  { path: "/portal/charitable-giving", label: "Charitable Giving", category: "Additional Tools" },
  { path: "/portal/client-comparison", label: "Client Comparison", category: "Advanced Analysis" },
  { path: "/portal/client-files", label: "Client Files", category: "Additional Tools" },
  { path: "/portal/client-onboarding-auto", label: "Client Onboarding Auto", category: "Additional Tools" },
  { path: "/portal/client-portal-config", label: "Client Portal Config", category: "Additional Tools" },
  { path: "/portal/client-scorecard", label: "Client Scorecard", category: "Additional Tools" },
  { path: "/portal/client-self-service", label: "Client Self Service", category: "Additional Tools" },
  { path: "/portal/collaborative-planning", label: "Collaborative Planning", category: "Additional Tools" },
  { path: "/portal/commission-calculator", label: "Commission Calculator", category: "Advanced Analysis" },
  { path: "/portal/commission-tracker", label: "Commission Tracker", category: "Additional Tools" },
  { path: "/portal/compliance-audit", label: "Compliance Audit", category: "Operations & Administration" },
  { path: "/portal/compliance-reports", label: "Compliance Reports", category: "Reports & Documents" },
  { path: "/portal/crypto-corner", label: "Crypto Corner", category: "Additional Tools" },
  { path: "/portal/document-vault", label: "Document Vault", category: "Reports & Documents" },
  { path: "/portal/education", label: "Education", category: "Reference & Education" },
  { path: "/portal/email-campaigns", label: "Email Campaigns", category: "Additional Tools" },
  { path: "/portal/engagement-score", label: "Engagement Score", category: "Additional Tools" },
  { path: "/portal/enterprise", label: "Enterprise", category: "Additional Tools" },
  { path: "/portal/estate-document-gen", label: "Estate Document Gen", category: "Reports & Documents" },
  { path: "/portal/fee-transparency", label: "Fee Transparency", category: "Additional Tools" },
  { path: "/portal/financial-vitals", label: "Financial Vitals", category: "Additional Tools" },
  { path: "/portal/goals-planning", label: "Goals Planning", category: "Additional Tools" },
  { path: "/portal/hidden-material", label: "Hidden Material", category: "Additional Tools" },
  { path: "/portal/hubspot", label: "Hubspot", category: "Additional Tools" },
  { path: "/portal/inflation", label: "Inflation", category: "Additional Tools" },
  { path: "/portal/knowledge", label: "Knowledge", category: "Reference & Education" },
  { path: "/portal/legal-payment-folder", label: "Legal Payment Folder", category: "Additional Tools" },
  { path: "/portal/market-data", label: "Market Data", category: "Additional Tools" },
  { path: "/portal/medicare-irmaa", label: "Medicare Irmaa", category: "Additional Tools" },
  { path: "/portal/meeting-agenda", label: "Meeting Agenda", category: "Additional Tools" },
  { path: "/portal/meetings", label: "Meetings", category: "Additional Tools" },
  { path: "/portal/monitoring-agreement", label: "Monitoring Agreement", category: "Operations & Administration" },
  { path: "/portal/multi-gen-wealth", label: "Multi Gen Wealth", category: "Additional Tools" },
  { path: "/portal/onboarding", label: "Onboarding", category: "Additional Tools" },
  { path: "/portal/onboarding-v2", label: "Onboarding V2", category: "Additional Tools" },
  { path: "/portal/owner-oversight", label: "Owner Oversight", category: "Additional Tools" },
  { path: "/portal/pipeline", label: "Pipeline", category: "Additional Tools" },
  { path: "/portal/policy-review", label: "Policy Review", category: "Additional Tools" },
  { path: "/portal/policy-review-checklist", label: "Policy Review Checklist", category: "Additional Tools" },
  { path: "/portal/portfolio-drift", label: "Portfolio Drift", category: "Additional Tools" },
  { path: "/portal/quick-quote", label: "Quick Quote", category: "Additional Tools" },
  { path: "/portal/quotes", label: "Quotes", category: "Additional Tools" },
  { path: "/portal/rebalance", label: "Rebalance", category: "Additional Tools" },
  { path: "/portal/recommendations", label: "Recommendations", category: "Additional Tools" },
  { path: "/portal/referral-tracker", label: "Referral Tracker", category: "Additional Tools" },
  { path: "/portal/referral-tracking", label: "Referral Tracking", category: "Additional Tools" },
  { path: "/portal/retirement-guardrails", label: "Retirement Guardrails", category: "Additional Tools" },
  { path: "/portal/retirement-projection", label: "Retirement Projection", category: "Additional Tools" },
  { path: "/portal/saved-scenarios", label: "Saved Scenarios", category: "Advanced Analysis" },
  { path: "/portal/scenario-play", label: "Scenario Play", category: "Advanced Analysis" },
  { path: "/portal/seminar-generator", label: "Seminar Generator", category: "Additional Tools" },
  { path: "/portal/slack", label: "Slack", category: "Additional Tools" },
  { path: "/portal/smart-rebalancing", label: "Smart Rebalancing", category: "Additional Tools" },
  { path: "/portal/succession-planning", label: "Succession Planning", category: "Additional Tools" },
  { path: "/portal/tax-brackets", label: "Tax Brackets", category: "Additional Tools" },
  { path: "/portal/tax-loss-harvesting", label: "Tax Loss Harvesting", category: "Additional Tools" },
  { path: "/portal/tax-opportunities", label: "Tax Opportunities", category: "Additional Tools" },
  { path: "/portal/tax-return-upload", label: "Tax Return Upload", category: "Additional Tools" },
  { path: "/portal/team", label: "Team", category: "Additional Tools" },
  { path: "/portal/team-management", label: "Team Management", category: "Additional Tools" },
  { path: "/portal/voice-plan", label: "Voice Plan", category: "Additional Tools" },
  { path: "/portal/wealth-reels", label: "Wealth Reels", category: "Experience & Experimental" },
  { path: "/portal/webhooks", label: "Webhooks", category: "Operations & Administration" },
  { path: "/portal/website-usage", label: "Website Usage", category: "Additional Tools" },
  { path: "/portal/welcome", label: "Welcome", category: "Additional Tools" },
  { path: "/portal/workflow-automations", label: "Workflow Automations", category: "Additional Tools" },
];

export const SECONDARY_CATEGORIES: SecondaryCatalogCategory[] = [
  "Advanced Analysis",
  "Reports & Documents",
  "Reference & Education",
  "Operations & Administration",
  "Experience & Experimental",
  "Additional Tools",
];
