// ─── Route manifest ─────────────────────────────────────────────────────────
//
// Every route the application serves, one per line.
//
// ## Why this replaced an integer
//
// Two smoke tests used to assert `expect(currentRoutes.size).toBe(N)`. That
// integer was the single most reliable merge conflict in the repository: any
// two branches that each added a route collided on it, every time, and the
// resolution was always the sum of both sides rather than either side's number
// — which is a merge a machine should do and a human kept doing by hand.
//
// A list does not collide. Two branches adding different routes produce two
// non-overlapping line insertions, and git merges them without help.
//
// It also catches what a count cannot. A count passes when one route is
// deleted and another added in the same change; the manifest shows exactly
// which line moved. And a duplicate route — the same path registered twice —
// is invisible to `.size` because a Set swallows it, but visible here.
//
// ## Keeping it current
//
// Adding a route means adding its path here. The smoke tests compare this list
// against the routes actually registered in App.tsx and fail with the specific
// paths that differ, in both directions, so the fix is always named.
//
// Generated from client/src/App.tsx on 2026-09-18; maintained by hand thereafter.

export const ROUTE_MANIFEST: readonly string[] = [
  "/",
  "/404",
  "/administrator",
  "/calculators",
  "/client-portal/:token",
  "/executive",
  "/fact-finder",
  "/for",
  "/for/:slug",
  "/forgot-password",
  "/invite",
  "/login",
  "/onboarding",
  "/portal",
  "/portal/admin",
  "/portal/advanced-reporting",
  "/portal/advisor",
  "/portal/advisor-chat",
  "/portal/advisor-directory",
  "/portal/advisor-income-calculator",
  "/portal/advisor-training",
  "/portal/advisory-summary",
  "/portal/affiliate-links",
  "/portal/agency-tutorial",
  "/portal/amt-calculator",
  "/portal/agent-tutorial",
  "/portal/ai",
  "/portal/ai-advisor",
  "/portal/ai-assist",
  "/portal/ai-brain-hub",
  "/portal/ai-meeting-notes",
  "/portal/ai-policy-review",
  "/portal/ai-recommender",
  "/portal/ai-slides",
  "/portal/alt-credit",
  "/portal/alt-credit/:slug",
  "/portal/annuity-accumulation-db",
  "/portal/annuity-explorer",
  "/portal/annuity-memory",
  "/portal/arena",
  "/portal/athene-guaranteed-income",
  "/portal/athene-pe-plus15",
  "/portal/audit-timeline",
  "/portal/auto-closer",
  "/portal/avatar-twins",
  "/portal/axonic-sp500",
  "/portal/batch-illustration",
  "/portal/batch-slides",
  "/portal/beneficiary-optimization",
  "/portal/billing",
  "/portal/black-mirror",
  "/portal/branding",
  "/portal/bulk-generation",
  "/portal/business-owner",
  "/portal/career-path",
  "/portal/carrier-comparison",
  "/portal/carrier-rates",
  "/portal/carrier-ratings",
  "/portal/carrier-settings",
  "/portal/certifications",
  "/portal/chain",
  "/portal/charitable-giving",
  "/portal/client",
  "/portal/client-comparison",
  "/portal/client-files",
  "/portal/client-health",
  "/portal/client-intake",
  "/portal/client-intake-recommender",
  "/portal/client-onboarding",
  "/portal/client-onboarding-auto",
  "/portal/client-portal-config",
  "/portal/client-portfolio",
  "/portal/client-report-generator",
  "/portal/client-scorecard",
  "/portal/client-self-service",
  "/portal/client-snapshot",
  "/portal/clients",
  "/portal/clients/:id",
  "/portal/co-pilot",
  "/portal/collaborative-planning",
  "/portal/combo-recommender",
  "/portal/command",
  "/portal/command-center",
  "/portal/commission-calculator",
  "/portal/commission-tracker",
  "/portal/comparison",
  "/portal/compete",
  "/portal/competitive",
  "/portal/compliance",
  "/portal/compliance-alerts",
  "/portal/compliance-audit",
  "/portal/compliance-audit-trail",
  "/portal/compliance-monitoring",
  "/portal/compliance-reports",
  "/portal/compliance-vault",
  "/portal/connections",
  "/portal/controls",
  "/portal/couples",
  "/portal/crypto-corner",
  "/portal/crypto-cycle",
  "/portal/daily-briefing",
  "/portal/daily-discovery",
  "/portal/dashboard",
  "/portal/data-query",
  "/portal/deal-room",
  "/portal/disability-gap-analyzer",
  "/portal/divorce-calculator",
  "/portal/divorce-ilit",
  "/portal/divorce-recovery",
  "/portal/document-templates",
  "/portal/document-vault",
  "/portal/earn",
  "/portal/ecological-drivers",
  "/portal/education",
  "/portal/email-campaigns",
  "/portal/endgame",
  "/portal/engagement-score",
  "/portal/enterprise",
  "/portal/erosion",
  "/portal/estate-document-gen",
  "/portal/estate-flow",
  "/portal/estate-planning",
  "/portal/estate-tax",
  "/portal/exchange-chain",
  "/portal/existing-annuities",
  "/portal/explore",
  "/portal/fee-transparency",
  "/portal/fia-collateral",
  "/portal/fia-top10",
  "/portal/financial-assessment",
  "/portal/financial-vitals",
  "/portal/forgiveness",
  "/portal/genome-strategies",
  "/portal/goals-planning",
  "/portal/growth-annuities",
  "/portal/hidden-material",
  "/portal/hot-income",
  "/portal/house-recycling",
  "/portal/household-genome",
  "/portal/household-wealth",
  "/portal/how-a-figure-is-made",
  "/portal/hubspot",
  "/portal/hybrid-income-floor",
  "/portal/ibbotson-charts",
  "/portal/illustration-compare",
  "/portal/income-annuity",
  "/portal/income-annuity-top10",
  "/portal/income-for-life",
  "/portal/income-gap",
  "/portal/income-timeline",
  "/portal/index-backtester",
  "/portal/index-backtester-pro",
  "/portal/index-strategies",
  "/portal/infinite-banking",
  "/portal/infinite-scroll",
  "/portal/inflation",
  "/portal/inheritance",
  "/portal/integration-scorecard",
  "/portal/integrations",
  "/portal/interior",
  "/portal/interop-engine",
  "/portal/iul-engine",
  "/portal/iul-historical",
  "/portal/iul-loan-optimizer",
  "/portal/iul-projection",
  "/portal/iul-vs-roth",
  "/portal/key-person-valuation",
  "/portal/knowledge",
  "/portal/lead-generator",
  "/portal/leaderboard",
  "/portal/leads",
  "/portal/legal-payment-folder",
  "/portal/lifetime-income",
  "/portal/liquidity-routes",
  "/portal/long-term-care",
  "/portal/market-data",
  "/portal/market-pulse",
  "/portal/market-stress-test",
  "/portal/match-and-deploy",
  "/portal/mechanism/:slug",
  "/portal/mechanism/:slug/providers",
  "/portal/mechanism/:slug/sequences",
  "/portal/mechanisms",
  "/portal/medicare-irmaa",
  "/portal/meeting-agenda",
  "/portal/meeting-prep",
  "/portal/meetings",
  "/portal/monitoring-agreement",
  "/portal/morning-ritual",
  "/portal/mortgage-killer",
  "/portal/mortgage-killer-v2",
  "/portal/mortgage-killer-v3",
  "/portal/mortgage-ledger",
  "/portal/multi-gen-transfer",
  "/portal/multi-gen-wealth",
  "/portal/my-journey",
  "/portal/my-slides",
  "/portal/my-world",
  "/portal/myga-fixed-rate",
  "/portal/myga-waterfall",
  "/portal/nerve-center",
  "/portal/oil-gas",
  "/portal/onboarding",
  "/portal/onboarding-v2",
  "/portal/outside-forces",
  "/portal/owner-oversight",
  "/portal/patent-showcase",
  "/portal/pet",
  "/portal/physician",
  "/portal/physician-loan-refi",
  "/portal/physicians-edge",
  "/portal/pipeline",
  "/portal/plan-ledger",
  "/portal/planning-cases",
  "/portal/policy-cost-lab",
  "/portal/policy-loans",
  "/portal/policy-review",
  "/portal/policy-review-checklist",
  "/portal/portfolio-drift",
  "/portal/practice-acquisition",
  "/portal/predictive-analytics",
  "/portal/premium-financing",
  "/portal/presentation-builder",
  "/portal/qbi-optimizer",
  "/portal/quick-quote",
  "/portal/quotes",
  "/portal/real-estate",
  "/portal/real-estate-mogul",
  "/portal/rebalance",
  "/portal/recin",
  "/portal/recommendations",
  "/portal/referral-engine",
  "/portal/referral-tracker",
  "/portal/referral-tracking",
  "/portal/rental-enterprise",
  "/portal/retirement-guardrails",
  "/portal/retirement-opportunities",
  "/portal/retirement-projection",
  "/portal/revenue-guarantee",
  "/portal/reverse-heloc",
  "/portal/rewards",
  "/portal/risk-score",
  "/portal/risk-tolerance",
  "/portal/roth-conversion",
  "/portal/russell-number",
  "/portal/sales-story",
  "/portal/saved-scenarios",
  "/portal/scenario-play",
  "/portal/scenario-side-by-side",
  "/portal/scenarios",
  "/portal/secondary-information",
  "/portal/secret-secrets",
  "/portal/secret-secrets/:id",
  "/portal/seminar-generator",
  "/portal/sequence-planner",
  "/portal/settings-classic",
  "/portal/short-term-rentals",
  "/portal/site-health",
  "/portal/slack",
  "/portal/smart-rebalancing",
  "/portal/social",
  "/portal/social-security",
  "/portal/sphere",
  "/portal/stale-digest",
  "/portal/story-generator",
  "/portal/str-strategy",
  "/portal/str-tax-eliminator",
  "/portal/strategy",
  "/portal/strategy-combos",
  "/portal/strategy-compare",
  "/portal/succession-planning",
  "/portal/support-desk",
  "/portal/system-health",
  "/portal/tax-advantaged-growth",
  "/portal/tax-brackets",
  "/portal/tax-combos",
  "/portal/tax-combos/:id",
  "/portal/tax-loss-harvesting",
  "/portal/tax-opportunities",
  "/portal/tax-return-upload",
  "/portal/tax-schedule",
  "/portal/tax-waterfall",
  "/portal/team",
  "/portal/team-management",
  "/portal/the-arrival",
  "/portal/the-brotherhood",
  "/portal/the-experience",
  "/portal/the-field",
  "/portal/the-legacy",
  "/portal/the-map",
  "/portal/the-mirror",
  "/portal/the-strategy-table",
  "/portal/thresholds",
  "/portal/time-lapse",
  "/portal/time-machine",
  "/portal/time-machine-ag49",
  "/portal/time-machine-calculator",
  "/portal/time-machine-method",
  "/portal/toilet",
  "/portal/training",
  "/portal/transcend",
  "/portal/trusts",
  "/portal/video-library",
  "/portal/video-proposals",
  "/portal/voice",
  "/portal/voice-plan",
  "/portal/war-room",
  "/portal/war-story-generator",
  "/portal/wealth-genome",
  "/portal/wealth-reels",
  "/portal/webhooks",
  "/portal/website-usage",
  "/portal/welcome",
  "/portal/whisper-coach",
  "/portal/whisperer",
  "/portal/will-writer",
  "/portal/withdrawal-sequencing",
  "/portal/workflow-automations",
  "/portal/wrapped",
  "/portal/zip-engine",
  "/pricing",
  "/privacy",
  "/register",
  "/reset-password",
  "/shared-slides/:token",
  "/shared/:token",
  "/support",
  "/terms",
  "/trial",
  "/ultra-calculator",
  "/video/:token",
];

/** Convenience for tests and the scorecard. */
export const ROUTE_COUNT = ROUTE_MANIFEST.length;

/** Paths registered but absent from the manifest, and vice versa. */
export function diffRoutes(actual: Iterable<string>): { missing: string[]; unexpected: string[]; duplicates: string[] } {
  const actualList: string[] = [];
  const it = actual as Iterable<string>;
  for (const a of Array.from(it)) actualList.push(a);
  const seen: Record<string, number> = {};
  for (let i = 0; i < actualList.length; i++) seen[actualList[i]] = (seen[actualList[i]] || 0) + 1;
  const duplicates = Object.keys(seen).filter((k) => seen[k] > 1).sort();
  const declared: Record<string, true> = {};
  for (let i = 0; i < ROUTE_MANIFEST.length; i++) declared[ROUTE_MANIFEST[i]] = true;
  const present: Record<string, true> = {};
  for (let i = 0; i < actualList.length; i++) present[actualList[i]] = true;
  const missing = ROUTE_MANIFEST.filter((r) => !present[r]).sort();
  const unexpected = Object.keys(present).filter((r) => !declared[r]).sort();
  return { missing, unexpected, duplicates };
}
