/**
 * Authoritative Source Registry — who we listen to, every day.
 * ════════════════════════════════════════════════════════════════════════════
 *
 * Standing order: at least 15 individually authoritative sources for Japan,
 * 25 or more for oil settlement outside the dollar, plus the sovereign-debt and
 * Taiwan panels. No source may be a Chinese government, Party or state-media
 * site or sit on a .cn/.hk host (owner's order, 23 Sep 2026); China is read
 * only through U.S. and allied publishers that carry it as a country row. Each row says what it gives, how it is
 * reached, how often it moves, and what it cannot tell us.
 *
 * Tier is assigned once here and used by the confidence engine everywhere.
 *
 * Endpoints: `{KEY}` marks where an API key goes; the connector substitutes the
 * environment variable named in `keyEnv`. A source with `access: "page"` is
 * parsed from HTML and its parse date is recorded; one with `access: "manual"`
 * is read by Thomas through a search tool or entered by hand.
 */
import type { MacroSource } from "./types";
import { EXPANSION_SOURCES } from "./sourcesExpansion";

/** The original eight-domain registry. `MACRO_SOURCES` below is this plus the twenty-five-domain expansion. */
export const CORE_SOURCES: MacroSource[] = [
  // ═══════════════════════════════════════════════════════════════════════
  // UNITED STATES — the holdings and the market they land in
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "us-tic-mfh",
    name: "TIC Major Foreign Holders of Treasury Securities (Table 5)",
    entity: "U.S. Department of the Treasury",
    jurisdiction: "US",
    tier: "primary-official",
    access: "open-api",
    cadence: "monthly",
    domains: ["treasury-holdings"],
    url: "https://ticdata.treasury.gov/resource-center/data-chart-center/tic/Documents/slt_table5.html",
    apiUrl: "https://ticdata.treasury.gov/Publish/mfh.txt",
    provides: "Month-end Treasury holdings by country — the series Japan and China liquidation is measured against.",
    caveat: "Custodial basis; Belgium, Luxembourg, Cayman and UK figures hide the ultimate owner. Six-week lag. Annual benchmark revisions.",
  },
  {
    id: "us-tic-press",
    name: "TIC monthly press release (net flows)",
    entity: "U.S. Department of the Treasury",
    jurisdiction: "US",
    tier: "primary-official",
    access: "page",
    cadence: "monthly",
    domains: ["treasury-holdings", "reserves-fx"],
    url: "https://home.treasury.gov/news/press-releases",
    provides: "Net foreign official vs private purchases of long-term Treasuries — transaction basis, separates selling from valuation.",
  },
  {
    id: "fred",
    name: "FRED (Federal Reserve Economic Data)",
    entity: "Federal Reserve Bank of St. Louis",
    jurisdiction: "US",
    tier: "primary-official",
    access: "keyed-api",
    cadence: "daily",
    domains: ["rates-markets", "sovereign-debt", "reserves-fx"],
    url: "https://fred.stlouisfed.org",
    apiUrl: "https://api.stlouisfed.org/fred/series/observations?series_id={SERIES}&api_key={KEY}&file_type=json",
    keyEnv: "FRED_API_KEY",
    provides: "DGS10, DGS30, MORTGAGE30US, DTWEXBGS (dollar index), GFDEGDQ188S (US debt/GDP), FDHBFIN (foreign-held federal debt), T10YIE (breakevens), DCOILBRENTEU.",
    caveat: "Keyless CSV fallback at fred.stlouisfed.org/graph/fredgraph.csv?id={SERIES} is used when no key is set.",
  },
  {
    id: "fed-h41",
    name: "Federal Reserve H.4.1 (custody holdings for foreign official accounts)",
    entity: "Board of Governors of the Federal Reserve System",
    jurisdiction: "US",
    tier: "primary-official",
    access: "open-api",
    cadence: "weekly",
    domains: ["treasury-holdings", "reserves-fx"],
    url: "https://www.federalreserve.gov/releases/h41/",
    apiUrl: "https://www.federalreserve.gov/datadownload/Output.aspx?rel=H41&series=…&filetype=csv",
    provides: "Weekly marketable securities held in custody for foreign official and international accounts — the fastest public read on official selling, four weeks ahead of TIC.",
    caveat: "Covers only what is custodied at the New York Fed (roughly half of foreign official holdings).",
  },
  {
    id: "fed-fima",
    name: "FIMA Repo Facility usage",
    entity: "Federal Reserve",
    jurisdiction: "US",
    tier: "primary-official",
    access: "open-api",
    cadence: "weekly",
    domains: ["treasury-holdings", "japan-policy"],
    url: "https://www.federalreserve.gov/monetarypolicy/fima-repo-facility.htm",
    provides: "Whether a foreign official holder is borrowing dollars against Treasuries instead of selling them — Japan's finance minister named this as an intervention funding route (Sept 2026).",
  },
  {
    id: "us-treasury-auctions",
    name: "Treasury auction results (indirect bidder share)",
    entity: "TreasuryDirect",
    jurisdiction: "US",
    tier: "primary-official",
    access: "open-api",
    cadence: "weekly",
    domains: ["rates-markets", "treasury-holdings"],
    url: "https://www.treasurydirect.gov/auctions/announcements-data-results/",
    apiUrl: "https://api.fiscaldata.treasury.gov/services/api/fiscal_service/v1/accounting/od/auctions_query",
    provides: "Indirect bidder take-down — the proxy for foreign official demand at each 10- and 30-year auction.",
  },
  {
    id: "us-fiscaldata",
    name: "Fiscal Data — Debt to the Penny, interest expense",
    entity: "U.S. Treasury Bureau of the Fiscal Service",
    jurisdiction: "US",
    tier: "primary-official",
    access: "open-api",
    cadence: "daily",
    domains: ["sovereign-debt"],
    url: "https://fiscaldata.treasury.gov",
    apiUrl: "https://api.fiscaldata.treasury.gov/services/api/fiscal_service/v2/accounting/od/debt_to_penny",
    provides: "Total public debt outstanding daily; interest expense monthly.",
  },
  {
    id: "cbo",
    name: "Congressional Budget Office — Budget and Economic Outlook",
    entity: "CBO",
    jurisdiction: "US",
    tier: "primary-official",
    access: "page",
    cadence: "semiannual",
    domains: ["sovereign-debt"],
    url: "https://www.cbo.gov/topics/budget",
    provides: "Ten-year debt path, net interest as share of revenue.",
  },
  {
    id: "us-odni-ata",
    name: "Annual Threat Assessment",
    entity: "Office of the Director of National Intelligence",
    jurisdiction: "US",
    tier: "primary-official",
    access: "page",
    cadence: "annual",
    domains: ["taiwan-risk", "china-policy"],
    url: "https://www.dni.gov/index.php/newsroom/reports-publications",
    provides: "The intelligence community's stated judgement on Beijing's Taiwan timeline (2026: no fixed timeline; invasion seen as high-risk).",
  },
  {
    id: "us-dod-cmpr",
    name: "China Military Power Report",
    entity: "U.S. Department of Defense",
    jurisdiction: "US",
    tier: "primary-official",
    access: "page",
    cadence: "annual",
    domains: ["taiwan-risk"],
    url: "https://www.defense.gov/News/Releases/",
    provides: "PLA force structure, amphibious lift, readiness milestones (the 2027 benchmark).",
  },

  // ═══════════════════════════════════════════════════════════════════════
  // JAPAN — fifteen sources
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "jp-mof-reserves",
    name: "International Reserves / Foreign Currency Liquidity",
    entity: "Ministry of Finance, Japan",
    jurisdiction: "JP",
    tier: "primary-official",
    access: "page",
    cadence: "monthly",
    domains: ["japan-policy", "treasury-holdings", "reserves-fx"],
    url: "https://www.mof.go.jp/english/policy/international_policy/reference/official_reserve_assets/index.htm",
    provides: "Month-end reserves and the 'foreign securities' line whose fall (−$87.8 bn, Aug 2026) revealed Treasury sales funding intervention.",
    caveat: "No maturity or issuer breakdown; ~70% Treasuries is a market estimate.",
  },
  {
    id: "jp-mof-intervention",
    name: "Foreign Exchange Intervention Operations",
    entity: "Ministry of Finance, Japan",
    jurisdiction: "JP",
    tier: "primary-official",
    access: "page",
    cadence: "monthly",
    domains: ["japan-policy", "reserves-fx"],
    url: "https://www.mof.go.jp/english/policy/international_policy/reference/feio/index.html",
    provides: "Confirmed intervention amounts (¥15.4 tn record, month to 26 Aug 2026) and quarterly day-by-day detail.",
  },
  {
    id: "jp-mof-portfolio-flows",
    name: "International Transactions in Securities (weekly)",
    entity: "Ministry of Finance, Japan",
    jurisdiction: "JP",
    tier: "primary-official",
    access: "page",
    cadence: "weekly",
    domains: ["japan-policy", "treasury-holdings"],
    url: "https://www.mof.go.jp/english/policy/international_policy/reference/itn_transactions_in_securities/index.htm",
    provides: "Net purchases of foreign bonds by Japanese residents, by investor type (life insurers, banks, trusts) — the private-sector half of Japan's Treasury demand.",
  },
  {
    id: "jp-mof-jgb",
    name: "JGB issuance plan and auction results",
    entity: "Ministry of Finance, Japan",
    jurisdiction: "JP",
    tier: "primary-official",
    access: "page",
    cadence: "weekly",
    domains: ["japan-policy", "rates-markets"],
    url: "https://www.mof.go.jp/english/policy/jgbs/index.htm",
    provides: "Domestic yield pull: 10-year JGB at 3% (Sept 2026) makes home bonds compete with Treasuries.",
  },
  {
    id: "jp-mof-minister",
    name: "Finance Minister press conferences",
    entity: "Ministry of Finance, Japan",
    jurisdiction: "JP",
    tier: "primary-official",
    access: "page",
    cadence: "weekly",
    domains: ["japan-policy"],
    url: "https://www.mof.go.jp/english/public_relations/conference/index.html",
    provides: "Signalling on the yen, on coordination with the U.S. Treasury, on FIMA use. Twice-weekly transcripts.",
    language: "ja",
  },
  {
    id: "jp-boj-mpm",
    name: "Monetary Policy Meeting statements and Outlook Report",
    entity: "Bank of Japan",
    jurisdiction: "JP",
    tier: "primary-official",
    access: "page",
    cadence: "irregular",
    domains: ["japan-policy", "rates-markets"],
    url: "https://www.boj.or.jp/en/mopo/mpmdeci/index.htm",
    provides: "Policy-rate path and JGB purchase taper — the rate differential that decides whether Japanese money stays home.",
  },
  {
    id: "jp-boj-stats",
    name: "BOJ Time-Series Data (flow of funds, balance of payments)",
    entity: "Bank of Japan",
    jurisdiction: "JP",
    tier: "primary-official",
    access: "open-api",
    cadence: "monthly",
    domains: ["japan-policy", "reserves-fx"],
    url: "https://www.stat-search.boj.or.jp/index_en.html",
    provides: "Sectoral holdings of foreign securities; the balance-of-payments portfolio account.",
  },
  {
    id: "jp-gpif",
    name: "GPIF quarterly results and asset allocation",
    entity: "Government Pension Investment Fund",
    jurisdiction: "JP",
    tier: "primary-official",
    access: "page",
    cadence: "quarterly",
    domains: ["japan-policy", "treasury-holdings"],
    url: "https://www.gpif.go.jp/en/performance/",
    provides: "The world's largest pension fund's foreign-bond weight (25% policy target) — a quiet, structural Treasury buyer or seller.",
  },
  {
    id: "jp-life-insurers",
    name: "Life Insurance Association of Japan — investment plans",
    entity: "LIAJ / member disclosures",
    jurisdiction: "JP",
    tier: "primary-official",
    access: "manual",
    cadence: "semiannual",
    domains: ["japan-policy", "treasury-holdings"],
    url: "https://www.seiho.or.jp/english/",
    provides: "Twice-yearly hedged-vs-unhedged foreign bond intentions of the nine majors — the single best leading indicator of Japanese private Treasury flows.",
  },
  {
    id: "jp-fsa",
    name: "Financial Services Agency — supervisory policy, ESR solvency regime",
    entity: "FSA Japan",
    jurisdiction: "JP",
    tier: "primary-official",
    access: "page",
    cadence: "irregular",
    domains: ["japan-policy"],
    url: "https://www.fsa.go.jp/en/",
    provides: "The 2025 economic-value solvency rules that changed insurers' appetite for long foreign bonds.",
  },
  {
    id: "jp-kantei",
    name: "Prime Minister's Office — policy speeches, Diet answers",
    entity: "Kantei",
    jurisdiction: "JP",
    tier: "primary-official",
    access: "page",
    cadence: "daily",
    domains: ["japan-policy"],
    url: "https://japan.kantei.go.jp/",
    provides: "Cabinet-level political signalling: fiscal packages, security posture, U.S. relationship.",
  },
  {
    id: "jp-diet",
    name: "National Diet proceedings (Budget and Finance committees)",
    entity: "House of Representatives / Councillors",
    jurisdiction: "JP",
    tier: "primary-official",
    access: "manual",
    cadence: "daily",
    domains: ["japan-policy"],
    url: "https://kokkai.ndl.go.jp/",
    provides: "What ministers say under questioning about reserves, intervention and Treasury holdings — anything put into law or mandate appears here first.",
    language: "ja",
  },
  {
    id: "jp-egov-law",
    name: "e-Gov Law Search and Official Gazette (Kanpō)",
    entity: "Government of Japan",
    jurisdiction: "JP",
    tier: "primary-official",
    access: "page",
    cadence: "daily",
    domains: ["japan-policy"],
    url: "https://laws.e-gov.go.jp/",
    provides: "Every enacted law, cabinet order and ministerial ordinance — the 'put into law' feed.",
    language: "ja",
  },
  {
    id: "jp-nikkei",
    name: "Nikkei Asia",
    entity: "Nikkei Inc.",
    jurisdiction: "JP",
    tier: "wire-service",
    access: "manual",
    cadence: "daily",
    domains: ["japan-policy", "treasury-holdings"],
    url: "https://asia.nikkei.com/",
    provides: "The best-sourced reporting on MOF and BOJ intent; often carries the leak before the release.",
  },
  {
    id: "jp-japantimes",
    name: "The Japan Times (Business / Markets)",
    entity: "The Japan Times",
    jurisdiction: "JP",
    tier: "wire-service",
    access: "open-api",
    cadence: "daily",
    domains: ["japan-policy"],
    url: "https://www.japantimes.co.jp/business/",
    apiUrl: "https://www.japantimes.co.jp/feed/",
    provides: "English wire on intervention and reserve moves (carried the 7 Sept 2026 Treasury-sales story).",
  },
  {
    id: "jp-jsda",
    name: "Japan Securities Dealers Association — bond trading by investor type",
    entity: "JSDA",
    jurisdiction: "JP",
    tier: "primary-official",
    access: "page",
    cadence: "monthly",
    domains: ["japan-policy", "rates-markets"],
    url: "https://www.jsda.or.jp/en/statistics/",
    provides: "Who is buying and selling JGBs — the domestic mirror of foreign-bond flows.",
  },

  // ═══════════════════════════════════════════════════════════════════════
  // CHINA — no Chinese government, Party, state-media or .cn/.hk source is
  // read (owner's order, 23 Sep 2026). China is watched through U.S. and
  // allied publishers: TIC (China as a country row), IMF IFS and Article IV,
  // BIS, USDA PSD, UN WPP and Comtrade, SIPRI, DoD, ODNI, CSIS, MERICS, OFAC.
  // ═══════════════════════════════════════════════════════════════════════

  // ═══════════════════════════════════════════════════════════════════════
  // OIL SETTLEMENT OUTSIDE THE DOLLAR — twenty-five-plus sources
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "eia-api",
    name: "EIA Open Data API",
    entity: "U.S. Energy Information Administration",
    jurisdiction: "US",
    tier: "primary-official",
    access: "keyed-api",
    cadence: "daily",
    domains: ["oil-settlement"],
    url: "https://www.eia.gov/opendata/",
    apiUrl: "https://api.eia.gov/v2/petroleum/pri/spt/data/?api_key={KEY}&frequency=daily&data[0]=value&facets[series][]=RBRTE",
    keyEnv: "EIA_API_KEY",
    provides: "Brent and WTI spot, global production and consumption by country — the volume base every settlement share is measured against.",
  },
  {
    id: "iea-omr",
    name: "Oil Market Report",
    entity: "International Energy Agency",
    jurisdiction: "INTL",
    tier: "multilateral",
    access: "page",
    cadence: "monthly",
    domains: ["oil-settlement"],
    url: "https://www.iea.org/topics/oil-market-report",
    provides: "Trade flows by origin and destination; who buys from whom.",
  },
  {
    id: "opec-momr",
    name: "Monthly Oil Market Report",
    entity: "OPEC Secretariat",
    jurisdiction: "INTL",
    tier: "multilateral",
    access: "page",
    cadence: "monthly",
    domains: ["oil-settlement"],
    url: "https://www.opec.org/opec_web/en/publications/338.htm",
    provides: "Member export volumes; OPEC Reference Basket.",
  },
  {
    id: "jodi",
    name: "JODI Oil World Database",
    entity: "Joint Organisations Data Initiative",
    jurisdiction: "INTL",
    tier: "multilateral",
    access: "open-api",
    cadence: "monthly",
    domains: ["oil-settlement"],
    url: "https://www.jodidata.org/oil/",
    provides: "Country-reported crude exports and imports — the bilateral volume matrix.",
  },
  {
    id: "un-comtrade",
    name: "UN Comtrade (HS 2709 crude, 2710 products)",
    entity: "United Nations Statistics Division",
    jurisdiction: "INTL",
    tier: "multilateral",
    access: "keyed-api",
    cadence: "monthly",
    domains: ["oil-settlement"],
    url: "https://comtradeplus.un.org/",
    apiUrl: "https://comtradeapi.un.org/data/v1/get/C/M/HS?cmdCode=2709&subscription-key={KEY}",
    keyEnv: "COMTRADE_API_KEY",
    provides: "Bilateral trade values back to 1962 — the twenty-year historical base.",
  },
  {
    id: "swift-rmb-tracker",
    name: "SWIFT RMB Tracker",
    entity: "SWIFT",
    jurisdiction: "INTL",
    tier: "research",
    access: "page",
    cadence: "monthly",
    domains: ["oil-settlement"],
    url: "https://www.swift.com/our-solutions/compliance-and-shared-services/business-intelligence/renminbi/rmb-tracker",
    provides: "Yuan share of global payments; excludes CIPS-only traffic, so it understates.",
  },
  {
    id: "imf-cofer",
    name: "COFER — Currency Composition of Official FX Reserves",
    entity: "International Monetary Fund",
    jurisdiction: "INTL",
    tier: "multilateral",
    access: "open-api",
    cadence: "quarterly",
    domains: ["reserves-fx", "oil-settlement"],
    url: "https://data.imf.org/?sk=E6A5F467-C14B-4AA8-9F6D-5A09EC4E62A4",
    provides: "Dollar share of reserves (56.3% Q1 2026, from 71% in 2000); yuan share 3.1%.",
  },
  {
    id: "bis-triennial",
    name: "BIS Triennial Central Bank Survey (FX turnover)",
    entity: "Bank for International Settlements",
    jurisdiction: "INTL",
    tier: "multilateral",
    access: "open-api",
    cadence: "irregular",
    domains: ["oil-settlement", "reserves-fx"],
    url: "https://www.bis.org/statistics/rpfx22.htm",
    provides: "Currency shares of global FX turnover, every three years.",
  },
  {
    id: "bis-debt",
    name: "BIS total credit to the non-financial sector",
    entity: "Bank for International Settlements",
    jurisdiction: "INTL",
    tier: "multilateral",
    access: "open-api",
    cadence: "quarterly",
    domains: ["sovereign-debt"],
    url: "https://data.bis.org/topics/TOTAL_CREDIT",
    apiUrl: "https://stats.bis.org/api/v2/data/dataflow/BIS/WS_TC/1.0/Q.CN.C.A.M.770.A?format=csv",
    provides: "Total (government + household + corporate) debt to GDP — the '300% China' number.",
  },
  {
    id: "sa-sama",
    name: "Saudi Central Bank (SAMA) monthly statistical bulletin",
    entity: "SAMA",
    jurisdiction: "SA",
    tier: "primary-official",
    access: "page",
    cadence: "monthly",
    domains: ["oil-settlement", "reserves-fx"],
    url: "https://www.sama.gov.sa/en-US/EconomicReports/Pages/MonthlyStatistics.aspx",
    provides: "Reserve assets and the currency composition hints behind 12–15% of crude exports settled in yuan (2026 estimates).",
  },
  {
    id: "sa-aramco",
    name: "Saudi Aramco disclosures",
    entity: "Saudi Aramco",
    jurisdiction: "SA",
    tier: "primary-official",
    access: "page",
    cadence: "quarterly",
    domains: ["oil-settlement"],
    url: "https://www.aramco.com/en/investors",
    provides: "Sales by region; settlement currency only when disclosed.",
  },
  {
    id: "ae-cbuae",
    name: "Central Bank of the UAE — swap lines and reserves",
    entity: "CBUAE",
    jurisdiction: "AE",
    tier: "primary-official",
    access: "page",
    cadence: "monthly",
    domains: ["oil-settlement", "reserves-fx"],
    url: "https://www.centralbank.ae/en/",
    provides: "Dirham–yuan swap line usage; the April 2026 signal that the UAE could shift oil settlement.",
  },
  {
    id: "ae-adnoc",
    name: "ADNOC / Murban futures (IFAD)",
    entity: "ADNOC / ICE Futures Abu Dhabi",
    jurisdiction: "AE",
    tier: "primary-official",
    access: "page",
    cadence: "daily",
    domains: ["oil-settlement"],
    url: "https://www.ice.com/futures-abu-dhabi",
    provides: "Murban benchmark pricing; still dollar-denominated, watched for a yuan contract.",
  },
  {
    id: "in-rbi",
    name: "Reserve Bank of India — rupee trade settlement, Vostro accounts",
    entity: "RBI",
    jurisdiction: "IN",
    tier: "primary-official",
    access: "page",
    cadence: "monthly",
    domains: ["oil-settlement"],
    url: "https://www.rbi.org.in/",
    provides: "Special Rupee Vostro framework volumes — Russian crude into India in rupees and dirhams.",
  },
  {
    id: "in-ppac",
    name: "Petroleum Planning & Analysis Cell — imports by source",
    entity: "PPAC, Ministry of Petroleum, India",
    jurisdiction: "IN",
    tier: "primary-official",
    access: "page",
    cadence: "monthly",
    domains: ["oil-settlement"],
    url: "https://ppac.gov.in/",
    provides: "India's crude import mix; Russia's share is the non-dollar corridor.",
  },
  {
    id: "ru-cbr",
    name: "Bank of Russia — currency structure of settlements for exports",
    entity: "Central Bank of the Russian Federation",
    jurisdiction: "RU",
    tier: "primary-official",
    access: "page",
    cadence: "monthly",
    domains: ["oil-settlement"],
    url: "https://www.cbr.ru/eng/statistics/",
    provides: "The only central bank that publishes export settlement by currency (ruble / 'friendly' / 'unfriendly').",
    caveat: "Sanctioned issuer; treat as declared, cross-check with importers' data.",
  },
  {
    id: "ru-mosprime",
    name: "Moscow Exchange — yuan/ruble turnover",
    entity: "MOEX",
    jurisdiction: "RU",
    tier: "primary-official",
    access: "page",
    cadence: "daily",
    domains: ["oil-settlement"],
    url: "https://www.moex.com/en/",
    provides: "CNY/RUB became the most traded pair after 2022 — the ruble side of yuan oil settlement.",
  },
  {
    id: "br-bcb",
    name: "Banco Central do Brasil — yuan clearing, swap line",
    entity: "BCB",
    jurisdiction: "BR",
    tier: "primary-official",
    access: "open-api",
    cadence: "monthly",
    domains: ["oil-settlement"],
    url: "https://www.bcb.gov.br/en",
    provides: "Yuan settlement of Brazil–China commodity trade under the 2023 agreement.",
  },
  {
    id: "brics-ndb",
    name: "BRICS summit declarations / New Development Bank",
    entity: "BRICS",
    jurisdiction: "INTL",
    tier: "primary-official",
    access: "manual",
    cadence: "annual",
    domains: ["oil-settlement", "china-policy"],
    url: "https://www.ndb.int/",
    provides: "Stated payment-system and local-currency settlement commitments; NDB local-currency lending share.",
  },
  {
    id: "kpler",
    name: "Kpler tanker tracking",
    entity: "Kpler",
    jurisdiction: "INTL",
    tier: "research",
    access: "paid-api",
    cadence: "realtime",
    domains: ["oil-settlement"],
    url: "https://www.kpler.com/",
    keyEnv: "KPLER_API_KEY",
    provides: "Cargo-level flows including shadow-fleet movements the official data misses.",
  },
  {
    id: "vortexa",
    name: "Vortexa",
    entity: "Vortexa",
    jurisdiction: "INTL",
    tier: "research",
    access: "paid-api",
    cadence: "realtime",
    domains: ["oil-settlement"],
    url: "https://www.vortexa.com/",
    keyEnv: "VORTEXA_API_KEY",
    provides: "Seaborne crude flows by origin–destination; the sanctioned-corridor volumes.",
  },
  {
    id: "argus",
    name: "Argus Media",
    entity: "Argus",
    jurisdiction: "INTL",
    tier: "research",
    access: "paid-api",
    cadence: "daily",
    domains: ["oil-settlement"],
    url: "https://www.argusmedia.com/",
    provides: "Price assessments including yuan-denominated and discounted Russian grades.",
  },
  {
    id: "platts",
    name: "S&P Global Commodity Insights (Platts)",
    entity: "S&P Global",
    jurisdiction: "INTL",
    tier: "research",
    access: "paid-api",
    cadence: "daily",
    domains: ["oil-settlement"],
    url: "https://www.spglobal.com/commodityinsights/",
    provides: "Benchmarks and the 3.7%-of-trade-in-yuan (2024) settlement estimate.",
  },
  {
    id: "jpm-research",
    name: "J.P. Morgan Global Research — de-dollarisation series",
    entity: "JPMorgan Chase",
    jurisdiction: "US",
    tier: "research",
    access: "manual",
    cadence: "irregular",
    domains: ["oil-settlement", "reserves-fx"],
    url: "https://www.jpmorgan.com/insights/global-research",
    provides: "The 80%-of-oil-trade-in-dollars (2023) benchmark most later estimates are anchored to.",
  },
  {
    id: "carnegie",
    name: "Carnegie Endowment — renminbi internationalisation research",
    entity: "Carnegie Endowment for International Peace",
    jurisdiction: "US",
    tier: "research",
    access: "manual",
    cadence: "irregular",
    domains: ["oil-settlement", "china-policy"],
    url: "https://carnegieendowment.org/",
    provides: "Sceptical, sourced accounting of what has and has not moved out of the dollar (Hormuz conflict paper, July 2026).",
  },
  {
    id: "atlantic-council-dollar",
    name: "Atlantic Council Dollar Dominance Monitor",
    entity: "Atlantic Council GeoEconomics Center",
    jurisdiction: "US",
    tier: "research",
    access: "page",
    cadence: "quarterly",
    domains: ["oil-settlement", "reserves-fx"],
    url: "https://www.atlanticcouncil.org/programs/geoeconomics-center/dollar-dominance-monitor/",
    provides: "A maintained composite of reserve, invoicing and settlement shares.",
  },
  {
    id: "cnbc-reuters-energy",
    name: "Reuters Energy / Commodities wire",
    entity: "Reuters",
    jurisdiction: "INTL",
    tier: "wire-service",
    access: "manual",
    cadence: "realtime",
    domains: ["oil-settlement"],
    url: "https://www.reuters.com/business/energy/",
    provides: "Deal-level reporting of yuan-, rupee- and dirham-settled cargoes.",
  },
  {
    id: "bloomberg-energy",
    name: "Bloomberg — energy and FX",
    entity: "Bloomberg L.P.",
    jurisdiction: "INTL",
    tier: "wire-service",
    access: "paid-api",
    cadence: "realtime",
    domains: ["oil-settlement", "japan-policy", "treasury-holdings"],
    url: "https://www.bloomberg.com/energy",
    keyEnv: "BLOOMBERG_API_KEY",
    provides: "Flow analysis (broke the Japan Treasury-sales story, 6 Sept 2026); Bloomberg Economics Taiwan scenarios.",
  },
  {
    id: "ofac",
    name: "OFAC sanctions lists and general licences",
    entity: "U.S. Treasury Office of Foreign Assets Control",
    jurisdiction: "US",
    tier: "primary-official",
    access: "open-api",
    cadence: "daily",
    domains: ["oil-settlement", "china-policy"],
    url: "https://ofac.treasury.gov/",
    apiUrl: "https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/SDN.XML",
    provides: "Every sanctioned tanker, trader and bank — the reason a corridor leaves the dollar.",
  },

  // ═══════════════════════════════════════════════════════════════════════
  // SOVEREIGN DEBT — the country-by-country panel
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "imf-weo",
    name: "World Economic Outlook database (GGXWDG_NGDP and companions)",
    entity: "International Monetary Fund",
    jurisdiction: "INTL",
    tier: "multilateral",
    access: "open-api",
    cadence: "semiannual",
    domains: ["sovereign-debt", "imf"],
    url: "https://www.imf.org/en/publications/weo",
    apiUrl: "https://www.imf.org/external/datamapper/api/v1/GGXWDG_NGDP",
    provides: "General government gross debt, % of GDP, 196 economies, 1980–2031. April 2026: US 125.8, Japan 204.4, China 106.9, Italy 138.4, world 95.3.",
    caveat: "China figure uses the narrow perimeter; Article IV 'augmented' debt is far higher.",
  },
  {
    id: "imf-fiscal-monitor",
    name: "Fiscal Monitor",
    entity: "International Monetary Fund",
    jurisdiction: "INTL",
    tier: "multilateral",
    access: "page",
    cadence: "semiannual",
    domains: ["sovereign-debt", "imf"],
    url: "https://www.imf.org/en/publications/fm",
    provides: "Interest burden, gross financing needs, debt-at-risk. April 2026: global debt 93.9% (2025), 100% by 2029.",
  },
  {
    id: "imf-article-iv",
    name: "Article IV staff reports (China augmented debt, Japan DSA)",
    entity: "International Monetary Fund",
    jurisdiction: "INTL",
    tier: "multilateral",
    access: "page",
    cadence: "annual",
    domains: ["sovereign-debt", "china-policy", "japan-policy"],
    url: "https://www.imf.org/en/countries",
    provides: "Debt sustainability analyses; the augmented China measure that adds LGFVs.",
  },
  {
    id: "worldbank-ids",
    name: "World Bank International Debt Statistics / WDI",
    entity: "World Bank",
    jurisdiction: "INTL",
    tier: "multilateral",
    access: "open-api",
    cadence: "annual",
    domains: ["sovereign-debt"],
    url: "https://data.worldbank.org/",
    apiUrl: "https://api.worldbank.org/v2/country/all/indicator/GC.DOD.TOTL.GD.ZS?format=json&mrv=5&per_page=400",
    provides: "Central government debt, external debt stocks, debt service ratios for developing economies.",
  },
  {
    id: "iif-gdm",
    name: "Global Debt Monitor",
    entity: "Institute of International Finance",
    jurisdiction: "INTL",
    tier: "research",
    access: "manual",
    cadence: "quarterly",
    domains: ["sovereign-debt"],
    url: "https://www.iif.com/Research/Capital-Flows-and-Debt/Global-Debt-Monitor",
    provides: "Total global debt (all sectors), the source of the '$300+ trillion' headlines.",
  },
  {
    id: "oecd-debt",
    name: "OECD Government at a Glance / Sovereign Borrowing Outlook",
    entity: "OECD",
    jurisdiction: "INTL",
    tier: "multilateral",
    access: "open-api",
    cadence: "annual",
    domains: ["sovereign-debt"],
    url: "https://www.oecd.org/en/publications/oecd-sovereign-borrowing-outlook_23060476.html",
    provides: "Gross borrowing requirements and refinancing walls for members.",
  },
  {
    id: "eurostat-gov",
    name: "Eurostat government finance statistics",
    entity: "Eurostat",
    jurisdiction: "EU",
    tier: "primary-official",
    access: "open-api",
    cadence: "quarterly",
    domains: ["sovereign-debt"],
    url: "https://ec.europa.eu/eurostat/web/government-finance-statistics",
    apiUrl: "https://ec.europa.eu/eurostat/api/dissemination/statistics/1.0/data/gov_10q_ggdebt?format=JSON",
    provides: "Quarterly Maastricht debt for the euro area (Italy, France, Greece).",
  },
  {
    id: "ratings-fitch-moodys-sp",
    name: "Sovereign rating actions (Fitch, Moody's, S&P)",
    entity: "Rating agencies",
    jurisdiction: "INTL",
    tier: "research",
    access: "manual",
    cadence: "irregular",
    domains: ["sovereign-debt"],
    url: "https://www.fitchratings.com/sovereigns",
    provides: "Rating and outlook changes — the market's default-probability proxy alongside CDS.",
  },
  {
    id: "cds-markit",
    name: "Sovereign CDS spreads (5-year)",
    entity: "S&P Global Market Intelligence (IHS Markit)",
    jurisdiction: "INTL",
    tier: "research",
    access: "paid-api",
    cadence: "daily",
    domains: ["sovereign-debt"],
    url: "https://www.spglobal.com/marketintelligence/",
    provides: "Market-implied default probability by sovereign.",
  },
  {
    id: "un-dsa",
    name: "UN Trade and Development — A World of Debt",
    entity: "UNCTAD",
    jurisdiction: "INTL",
    tier: "multilateral",
    access: "page",
    cadence: "annual",
    domains: ["sovereign-debt"],
    url: "https://unctad.org/publication/world-of-debt",
    provides: "Countries paying more in interest than on health or education; the distress list.",
  },

  // ═══════════════════════════════════════════════════════════════════════
  // TAIWAN — the strike-risk panel
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: "tw-mnd-daily",
    name: "Ministry of National Defense — daily PLA activity report",
    entity: "MND, Republic of China (Taiwan)",
    jurisdiction: "TW",
    tier: "primary-official",
    access: "page",
    cadence: "daily",
    domains: ["taiwan-risk"],
    url: "https://www.mnd.gov.tw/english/",
    provides: "Daily count of PLA aircraft, ships and balloons around Taiwan; median-line crossings. The heartbeat series (record 244 ships in July 2026).",
  },
  {
    id: "tw-cga",
    name: "Coast Guard Administration — China Coast Guard incursions",
    entity: "CGA, Taiwan",
    jurisdiction: "TW",
    tier: "primary-official",
    access: "page",
    cadence: "daily",
    domains: ["taiwan-risk"],
    url: "https://www.cga.gov.tw/GipOpen/wSite/mp?mp=9997",
    provides: "Kinmen and Matsu restricted-water incursions — the gray-zone 'quarantine rehearsal' series.",
  },
  {
    id: "tw-mac",
    name: "Mainland Affairs Council — cross-strait statements and polling",
    entity: "MAC, Taiwan",
    jurisdiction: "TW",
    tier: "primary-official",
    access: "page",
    cadence: "weekly",
    domains: ["taiwan-risk"],
    url: "https://www.mac.gov.tw/en/",
    provides: "Taipei's read of Beijing's signalling; public opinion on unification/independence.",
  },
  {
    id: "tw-cbc",
    name: "Central Bank of the Republic of China (Taiwan) — reserves, TWD",
    entity: "CBC Taiwan",
    jurisdiction: "TW",
    tier: "primary-official",
    access: "page",
    cadence: "monthly",
    domains: ["taiwan-risk", "reserves-fx"],
    url: "https://www.cbc.gov.tw/en/",
    provides: "Capital-flight tell: reserve drawdowns and TWD defence.",
  },
  {
    id: "tw-tsmc",
    name: "TSMC quarterly reports and overseas fab schedule",
    entity: "Taiwan Semiconductor Manufacturing Company",
    jurisdiction: "TW",
    tier: "primary-official",
    access: "page",
    cadence: "quarterly",
    domains: ["taiwan-risk"],
    url: "https://investor.tsmc.com/",
    provides: "Share of advanced nodes still on-island — the size of the global chip exposure (roughly 90% of leading-edge).",
  },
  {
    id: "csis-china-power",
    name: "CSIS ChinaPower / Taiwan Strait shipping analysis",
    entity: "Center for Strategic and International Studies",
    jurisdiction: "US",
    tier: "research",
    access: "page",
    cadence: "irregular",
    domains: ["taiwan-risk"],
    url: "https://chinapower.csis.org/",
    provides: "$2.4 tn of goods through the strait (2024), 21% of maritime trade; exercise-by-exercise timelines.",
  },
  {
    id: "rhodium-taiwan",
    name: "Rhodium Group — Taiwan blockade economic exposure",
    entity: "Rhodium Group",
    jurisdiction: "US",
    tier: "research",
    access: "manual",
    cadence: "irregular",
    domains: ["taiwan-risk"],
    url: "https://rhg.com/",
    provides: ">$2 tn annual activity exposed, $565 bn Taiwanese value-added at high risk, $1.6 tn chip-dependent revenue.",
  },
  {
    id: "bloomberg-economics-taiwan",
    name: "Bloomberg Economics — Taiwan conflict scenarios",
    entity: "Bloomberg Economics",
    jurisdiction: "INTL",
    tier: "research",
    access: "manual",
    cadence: "irregular",
    domains: ["taiwan-risk"],
    url: "https://www.bloomberg.com/economics",
    provides: "Feb 2026 model: blockade −5.3% of global GDP in year one; war $10.6 tn, −9.6%.",
  },
  {
    id: "lloyds-jwc",
    name: "Lloyd's Joint War Committee listed areas / war-risk premia",
    entity: "Lloyd's Market Association",
    jurisdiction: "GB",
    tier: "primary-official",
    access: "page",
    cadence: "irregular",
    domains: ["taiwan-risk", "oil-settlement"],
    url: "https://www.lmalloyds.com/LMA/Underwriting/Marine/Joint_War_Committee.aspx",
    provides: "The insurance market's own probability: when the Strait is listed, premia move before ships do.",
  },
  {
    id: "polymarket-taiwan",
    name: "Prediction markets (Polymarket, Metaculus) — Taiwan questions",
    entity: "Polymarket / Metaculus",
    jurisdiction: "INTL",
    tier: "secondary",
    access: "open-api",
    cadence: "realtime",
    domains: ["taiwan-risk"],
    url: "https://polymarket.com/",
    apiUrl: "https://gamma-api.polymarket.com/markets?tag=taiwan",
    provides: "Crowd probability for blockade/invasion by date. Leads, never confirms.",
  },
  {
    id: "jp-mod-taiwan",
    name: "Japan Ministry of Defense — Joint Staff press releases (PLA transits)",
    entity: "MOD Japan / Joint Staff",
    jurisdiction: "JP",
    tier: "primary-official",
    access: "page",
    cadence: "daily",
    domains: ["taiwan-risk", "japan-policy"],
    url: "https://www.mod.go.jp/js/en/",
    provides: "Carrier group transits of the Miyako Strait — the northern flank of any Taiwan operation.",
  },
  {
    id: "ais-marinetraffic",
    name: "AIS vessel tracking (MarineTraffic / Windward)",
    entity: "MarineTraffic",
    jurisdiction: "INTL",
    tier: "research",
    access: "paid-api",
    cadence: "realtime",
    domains: ["taiwan-risk", "oil-settlement"],
    url: "https://www.marinetraffic.com/",
    keyEnv: "MARINETRAFFIC_API_KEY",
    provides: "Strait transit counts, coast-guard loitering, tanker dark periods.",
  },
];

export const MACRO_SOURCES: MacroSource[] = [...CORE_SOURCES, ...EXPANSION_SOURCES];

export const SOURCE_BY_ID: ReadonlyMap<string, MacroSource> = new Map(MACRO_SOURCES.map(s => [s.id, s]));

export function sourcesFor(domain: MacroSource["domains"][number]): MacroSource[] {
  return MACRO_SOURCES.filter(s => s.domains.includes(domain));
}

export function sourcesByJurisdiction(j: MacroSource["jurisdiction"]): MacroSource[] {
  return MACRO_SOURCES.filter(s => s.jurisdiction === j);
}

/** The standing-order minimums, enforced by test. */
export const SOURCE_MINIMUMS = {
  JP: 15,
  /** A ceiling, not a floor: no Chinese-jurisdiction source may be registered. */
  CN: 0,
  "oil-settlement": 25,
  "sovereign-debt": 10,
  "taiwan-risk": 10,
} as const;
