import { useState } from "react";
import { Link } from "wouter";

// Layer 2 — "The Lab": supporting/advanced tools kept out of the primary nav.
// Routes below are the REAL routes pulled from App.tsx, so every link resolves.
const LAB_TOOLS: { path: string; label: string }[] = [
  { path: "/", label: "" },
  { path: "/administrator", label: "Administrator" },
  { path: "/executive", label: "Executive" },
  { path: "/login", label: "Login" },
  { path: "/portal/1031-advanced", label: "1031 Advanced" },
  { path: "/portal/1031-exchange", label: "1031 Exchange" },
  { path: "/portal/529-advanced", label: "529 Advanced" },
  { path: "/portal/aca-subsidy", label: "Aca Subsidy" },
  { path: "/portal/admin", label: "Admin" },
  { path: "/portal/admin/health", label: "Health" },
  { path: "/portal/advisor-income-calculator", label: "Advisor Income Calculator" },
  { path: "/portal/affiliate-links", label: "Affiliate Links" },
  { path: "/portal/ai-brain-hub", label: "Ai Brain Hub" },
  { path: "/portal/ai-meeting-notes", label: "Ai Meeting Notes" },
  { path: "/portal/alimony-tax-impact", label: "Alimony Tax Impact" },
  { path: "/portal/alt-allocator", label: "Alt Allocator" },
  { path: "/portal/alternative-investment", label: "Alternative Investment" },
  { path: "/portal/alternative-investments", label: "Alternative Investments" },
  { path: "/portal/amt-planner", label: "Amt Planner" },
  { path: "/portal/annuity-income-bridge", label: "Annuity Income Bridge" },
  { path: "/portal/annuity-waterfall", label: "Annuity Waterfall" },
  { path: "/portal/asset-allocation", label: "Asset Allocation" },
  { path: "/portal/asset-protection", label: "Asset Protection" },
  { path: "/portal/audit-defense", label: "Audit Defense" },
  { path: "/portal/autopilot", label: "Autopilot" },
  { path: "/portal/avatar-twins", label: "Avatar Twins" },
  { path: "/portal/behavioral-bias", label: "Behavioral Bias" },
  { path: "/portal/behavioral-planning", label: "Behavioral Planning" },
  { path: "/portal/billing", label: "Billing" },
  { path: "/portal/bond-ladder", label: "Bond Ladder" },
  { path: "/portal/branding", label: "Branding" },
  { path: "/portal/budget-50-30-20", label: "Budget 50 30 20" },
  { path: "/portal/calculator-hub", label: "Calculator Hub" },
  { path: "/portal/carrier-ratings", label: "Carrier Ratings" },
  { path: "/portal/carrier-settings", label: "Carrier Settings" },
  { path: "/portal/carrier-strength", label: "Carrier Strength" },
  { path: "/portal/cascading-optimizer", label: "Cascading Optimizer" },
  { path: "/portal/cash-flow-optimizer", label: "Cash Flow Optimizer" },
  { path: "/portal/ce-credits", label: "Ce Credits" },
  { path: "/portal/charitable-giving-dashboard", label: "Charitable Giving Dashboard" },
  { path: "/portal/charitable-stock-donation", label: "Charitable Stock Donation" },
  { path: "/portal/client-onboarding", label: "Client Onboarding" },
  { path: "/portal/client-portfolio", label: "Client Portfolio" },
  { path: "/portal/client-retention", label: "Client Retention" },
  { path: "/portal/client-retention-ai", label: "Client Retention Ai" },
  { path: "/portal/clients", label: "Clients" },
  { path: "/portal/co-pilot", label: "Co Pilot" },
  { path: "/portal/college-aid", label: "College Aid" },
  { path: "/portal/compliance-center", label: "Compliance Center" },
  { path: "/portal/compliance-doc-gen", label: "Compliance Doc Gen" },
  { path: "/portal/compound-interest", label: "Compound Interest" },
  { path: "/portal/concentrated-stock", label: "Concentrated Stock" },
  { path: "/portal/concierge", label: "Concierge" },
  { path: "/portal/cost-of-living", label: "Cost Of Living" },
  { path: "/portal/cost-of-waiting", label: "Cost Of Waiting" },
  { path: "/portal/cost-segregation", label: "Cost Segregation" },
  { path: "/portal/cost-segregation-engine", label: "Cost Segregation Engine" },
  { path: "/portal/couples", label: "Couples" },
  { path: "/portal/credit-card-payoff", label: "Credit Card Payoff" },
  { path: "/portal/cross-border-wealth", label: "Cross Border Wealth" },
  { path: "/portal/cross-feature-intelligence", label: "Cross Feature Intelligence" },
  { path: "/portal/crt-calculator", label: "Crt Calculator" },
  { path: "/portal/crt-wealth-replacement", label: "Crt Wealth Replacement" },
  { path: "/portal/crypto-tax", label: "Crypto Tax" },
  { path: "/portal/daf-strategic", label: "Daf Strategic" },
  { path: "/portal/daf-vs-direct-giving", label: "Daf Vs Direct Giving" },
  { path: "/portal/daily-briefing", label: "Daily Briefing" },
  { path: "/portal/dashboard", label: "Dashboard" },
  { path: "/portal/data-bus-dashboard", label: "Data Bus Dashboard" },
  { path: "/portal/dca-vs-lump-sum", label: "Dca Vs Lump Sum" },
  { path: "/portal/deal-closer", label: "Deal Closer" },
  { path: "/portal/debt-payoff", label: "Debt Payoff" },
  { path: "/portal/debt-payoff-optimizer", label: "Debt Payoff Optimizer" },
  { path: "/portal/deduction-optimizer", label: "Deduction Optimizer" },
  { path: "/portal/deep-organism", label: "Deep Organism" },
  { path: "/portal/defined-benefit", label: "Defined Benefit" },
  { path: "/portal/depreciation-tax-shield", label: "Depreciation Tax Shield" },
  { path: "/portal/digital-estate", label: "Digital Estate" },
  { path: "/portal/direct-indexing", label: "Direct Indexing" },
  { path: "/portal/divorce-financial", label: "Divorce Financial" },
  { path: "/portal/divorce-impact", label: "Divorce Impact" },
  { path: "/portal/divorce-settlement-enhanced", label: "Divorce Settlement Enhanced" },
  { path: "/portal/document-templates", label: "Document Templates" },
  { path: "/portal/document-vault", label: "Document Vault" },
  { path: "/portal/drip-growth", label: "Drip Growth" },
  { path: "/portal/dst-analyzer", label: "Dst Analyzer" },
  { path: "/portal/education-529", label: "Education 529" },
  { path: "/portal/email-campaigns", label: "Email Campaigns" },
  { path: "/portal/emergency-fund", label: "Emergency Fund" },
  { path: "/portal/employee-retention", label: "Employee Retention" },
  { path: "/portal/employee-stock-options", label: "Employee Stock Options" },
  { path: "/portal/engine-chaining", label: "Engine Chaining" },
  { path: "/portal/engine-fusion", label: "Engine Fusion" },
  { path: "/portal/estate-wealth-transfer", label: "Estate Wealth Transfer" },
  { path: "/portal/expat-tax", label: "Expat Tax" },
  { path: "/portal/family-bank", label: "Family Bank" },
  { path: "/portal/family-constitution", label: "Family Constitution" },
  { path: "/portal/family-governance", label: "Family Governance" },
  { path: "/portal/family-limited-partnership", label: "Family Limited Partnership" },
  { path: "/portal/family-office", label: "Family Office" },
  { path: "/portal/family-tree", label: "Family Tree" },
  { path: "/portal/fbar-fatca", label: "Fbar Fatca" },
  { path: "/portal/fee-impact", label: "Fee Impact" },
  { path: "/portal/fiduciary-compliance", label: "Fiduciary Compliance" },
  { path: "/portal/fiduciary-tracker", label: "Fiduciary Tracker" },
  { path: "/portal/financial-dna", label: "Financial Dna" },
  { path: "/portal/financial-freedom-number", label: "Financial Freedom Number" },
  { path: "/portal/financial-health-score", label: "Financial Health Score" },
  { path: "/portal/financial-independence", label: "Financial Independence" },
  { path: "/portal/financial-nerve-center", label: "Financial Nerve Center" },
  { path: "/portal/financial-plan-checklist", label: "Financial Plan Checklist" },
  { path: "/portal/fire-calculator", label: "Fire Calculator" },
  { path: "/portal/fluency-academy", label: "Fluency Academy" },
  { path: "/portal/grantor-trust", label: "Grantor Trust" },
  { path: "/portal/gstt-calculator", label: "Gstt Calculator" },
  { path: "/portal/healthcare-cost", label: "Healthcare Cost" },
  { path: "/portal/hot-income", label: "Hot Income" },
  { path: "/portal/hsa-maximizer", label: "Hsa Maximizer" },
  { path: "/portal/hsa-triple-tax", label: "Hsa Triple Tax" },
  { path: "/portal/hubspot", label: "Hubspot" },
  { path: "/portal/idgt-modeler", label: "Idgt Modeler" },
  { path: "/portal/impact-scorecard", label: "Impact Scorecard" },
  { path: "/portal/income-floor-strategy", label: "Income Floor Strategy" },
  { path: "/portal/income-protection", label: "Income Protection" },
  { path: "/portal/income-shifting", label: "Income Shifting" },
  { path: "/portal/inflation-adjusted-income", label: "Inflation Adjusted Income" },
  { path: "/portal/inflation-protection", label: "Inflation Protection" },
  { path: "/portal/inflation-returns", label: "Inflation Returns" },
  { path: "/portal/innovation-dashboard", label: "Innovation Dashboard" },
  { path: "/portal/insurance-coverage-command", label: "Insurance Coverage Command" },
  { path: "/portal/insurance-gap", label: "Insurance Gap" },
  { path: "/portal/international-tax", label: "International Tax" },
  { path: "/portal/irc-reference", label: "Irc Reference" },
  { path: "/portal/journey-navigator", label: "Journey Navigator" },
  { path: "/portal/knowledge", label: "Knowledge" },
  { path: "/portal/leaderboard", label: "Leaderboard" },
  { path: "/portal/lease-vs-buy", label: "Lease Vs Buy" },
  { path: "/portal/legacy-vault", label: "Legacy Vault" },
  { path: "/portal/life-settlement", label: "Life Settlement" },
  { path: "/portal/lifestyle-inflation", label: "Lifestyle Inflation" },
  { path: "/portal/like-kind-exchange", label: "Like Kind Exchange" },
  { path: "/portal/living-risk-profile", label: "Living Risk Profile" },
  { path: "/portal/long-term-care", label: "Long Term Care" },
  { path: "/portal/longitudinal-risk", label: "Longitudinal Risk" },
  { path: "/portal/marginal-tax-rate", label: "Marginal Tax Rate" },
  { path: "/portal/market-pulse", label: "Market Pulse" },
  { path: "/portal/mastery-nexus", label: "Mastery Nexus" },
  { path: "/portal/medicaid-planning", label: "Medicaid Planning" },
  { path: "/portal/medicare-part-d", label: "Medicare Part D" },
  { path: "/portal/meeting-prep", label: "Meeting Prep" },
  { path: "/portal/meetings", label: "Meetings" },
  { path: "/portal/millionaire-calculator", label: "Millionaire Calculator" },
  { path: "/portal/morning-ritual", label: "Morning Ritual" },
  { path: "/portal/multi-currency", label: "Multi Currency" },
  { path: "/portal/muni-bond-ladder", label: "Muni Bond Ladder" },
  { path: "/portal/my-world", label: "My World" },
  { path: "/portal/nerve-center", label: "Nerve Center" },
  { path: "/portal/net-worth-tracker", label: "Net Worth Tracker" },
  { path: "/portal/nii-surtax", label: "Nii Surtax" },
  { path: "/portal/nua-planner", label: "Nua Planner" },
  { path: "/portal/oil-gas-strategy", label: "Oil Gas Strategy" },
  { path: "/portal/onboarding-quiz", label: "Onboarding Quiz" },
  { path: "/portal/onboarding-v2", label: "Onboarding V2" },
  { path: "/portal/onboarding-workflow", label: "Onboarding Workflow" },
  { path: "/portal/options-profit-loss", label: "Options Profit Loss" },
  { path: "/portal/organism-control", label: "Organism Control" },
  { path: "/portal/organism-dashboard", label: "Organism Dashboard" },
  { path: "/portal/organism-health", label: "Organism Health" },
  { path: "/portal/patent-showcase", label: "Patent Showcase" },
  { path: "/portal/pe-irr-calculator", label: "Pe Irr Calculator" },
  { path: "/portal/pe-secondary-market", label: "Pe Secondary Market" },
  { path: "/portal/pe-tax", label: "Pe Tax" },
  { path: "/portal/peer-intel", label: "Peer Intel" },
  { path: "/portal/pension-maximization", label: "Pension Maximization" },
  { path: "/portal/persona-hub", label: "Persona Hub" },
  { path: "/portal/philanthropy", label: "Philanthropy" },
  { path: "/portal/physician-blueprint", label: "Physician Blueprint" },
  { path: "/portal/physician-forum", label: "Physician Forum" },
  { path: "/portal/physician-mortgage", label: "Physician Mortgage" },
  { path: "/portal/physician-retirement", label: "Physician Retirement" },
  { path: "/portal/physician-vitals", label: "Physician Vitals" },
  { path: "/portal/physicians-edge", label: "Physicians Edge" },
  { path: "/portal/policy-replacement", label: "Policy Replacement" },
  { path: "/portal/portfolio-risk-return", label: "Portfolio Risk Return" },
  { path: "/portal/post-mortem-tax", label: "Post Mortem Tax" },
  { path: "/portal/private-foundation", label: "Private Foundation" },
  { path: "/portal/private-reit", label: "Private Reit" },
  { path: "/portal/projection-theater", label: "Projection Theater" },
  { path: "/portal/property-tax-appeal", label: "Property Tax Appeal" },
  { path: "/portal/prospect-qualification", label: "Prospect Qualification" },
  { path: "/portal/pslf-calculator", label: "Pslf Calculator" },
  { path: "/portal/qlac-calculator", label: "Qlac Calculator" },
  { path: "/portal/qsbs-exclusion", label: "Qsbs Exclusion" },
  { path: "/portal/qualified-opportunity-fund", label: "Qualified Opportunity Fund" },
  { path: "/portal/qualified-plan-maximizer", label: "Qualified Plan Maximizer" },
  { path: "/portal/real-estate-portfolio", label: "Real Estate Portfolio" },
  { path: "/portal/refinance-break-even", label: "Refinance Break Even" },
  { path: "/portal/rental-property-roi", label: "Rental Property Roi" },
  { path: "/portal/report-builder", label: "Report Builder" },
  { path: "/portal/residency-to-attending", label: "Residency To Attending" },
  { path: "/portal/retirement-advantage", label: "Retirement Advantage" },
  { path: "/portal/retirement-budget", label: "Retirement Budget" },
  { path: "/portal/retirement-distributions", label: "Retirement Distributions" },
  { path: "/portal/retirement-gap", label: "Retirement Gap" },
  { path: "/portal/retirement-healthcare", label: "Retirement Healthcare" },
  { path: "/portal/retirement-income-proj", label: "Retirement Income Proj" },
  { path: "/portal/revenue-guarantee", label: "Revenue Guarantee" },
  { path: "/portal/risk-compliance", label: "Risk Compliance" },
  { path: "/portal/risk-tolerance", label: "Risk Tolerance" },
  { path: "/portal/roth-vs-traditional", label: "Roth Vs Traditional" },
  { path: "/portal/rsu-tax", label: "Rsu Tax" },
  { path: "/portal/rsu-tax-planning", label: "Rsu Tax Planning" },
  { path: "/portal/russell-number", label: "Russell Number" },
  { path: "/portal/sabbatical-planner", label: "Sabbatical Planner" },
  { path: "/portal/savings-rate-impact", label: "Savings Rate Impact" },
  { path: "/portal/secret-secrets", label: "Secret Secrets" },
  { path: "/portal/secret-secrets/:id", label: ":Id" },
  { path: "/portal/section-1202", label: "Section 1202" },
  { path: "/portal/section-2701", label: "Section 2701" },
  { path: "/portal/sector-rotation", label: "Sector Rotation" },
  { path: "/portal/self-employment-tax", label: "Self Employment Tax" },
  { path: "/portal/sequence-of-returns", label: "Sequence Of Returns" },
  { path: "/portal/serp-analyzer", label: "Serp Analyzer" },
  { path: "/portal/severance-calculator", label: "Severance Calculator" },
  { path: "/portal/short-term-rental", label: "Short Term Rental" },
  { path: "/portal/special-needs", label: "Special Needs" },
  { path: "/portal/spend-vs-invest", label: "Spend Vs Invest" },
  { path: "/portal/spending-guardrails", label: "Spending Guardrails" },
  { path: "/portal/spousal-lifetime-access", label: "Spousal Lifetime Access" },
  { path: "/portal/spousal-ss-coordination", label: "Spousal Ss Coordination" },
  { path: "/portal/state-tax-arbitrage", label: "State Tax Arbitrage" },
  { path: "/portal/str-strategy", label: "Str Strategy" },
  { path: "/portal/str-tax-strategy", label: "Str Tax Strategy" },
  { path: "/portal/strategy-synergy", label: "Strategy Synergy" },
  { path: "/portal/stress-test", label: "Stress Test" },
  { path: "/portal/stretch-ira", label: "Stretch Ira" },
  { path: "/portal/structured-notes", label: "Structured Notes" },
  { path: "/portal/structured-settlement", label: "Structured Settlement" },
  { path: "/portal/student-loan-optimizer", label: "Student Loan Optimizer" },
  { path: "/portal/student-loan-vs-invest", label: "Student Loan Vs Invest" },
  { path: "/portal/survivor-benefits", label: "Survivor Benefits" },
  { path: "/portal/syndication-deal", label: "Syndication Deal" },
  { path: "/portal/tax-combos/:id", label: ":Id" },
  { path: "/portal/tax-optimization-command", label: "Tax Optimization Command" },
  { path: "/portal/team", label: "Team" },
  { path: "/portal/team-management", label: "Team Management" },
  { path: "/portal/tenant-in-common", label: "Tenant In Common" },
  { path: "/portal/time-lapse", label: "Time Lapse" },
  { path: "/portal/trust-decanting", label: "Trust Decanting" },
  { path: "/portal/usage-analytics", label: "Usage Analytics" },
  { path: "/portal/vacation-rental", label: "Vacation Rental" },
  { path: "/portal/variable-annuity", label: "Variable Annuity" },
  { path: "/portal/video-library", label: "Video Library" },
  { path: "/portal/w4-optimizer", label: "W4 Optimizer" },
  { path: "/portal/wealth-accumulation", label: "Wealth Accumulation" },
  { path: "/portal/wealth-canvas", label: "Wealth Canvas" },
  { path: "/portal/wealth-dashboard", label: "Wealth Dashboard" },
  { path: "/portal/wealth-erosion", label: "Wealth Erosion" },
  { path: "/portal/wealth-rituals", label: "Wealth Rituals" },
  { path: "/portal/wealth-timeline", label: "Wealth Timeline" },
  { path: "/portal/wealth-transfer-scoreboard", label: "Wealth Transfer Scoreboard" },
  { path: "/portal/wealth-transfer-scorecard", label: "Wealth Transfer Scorecard" },
  { path: "/portal/wealth-transfer-timeline", label: "Wealth Transfer Timeline" },
  { path: "/portal/webhooks", label: "Webhooks" },
  { path: "/portal/website-usage", label: "Website Usage" },
  { path: "/portal/windfall-management", label: "Windfall Management" },
  { path: "/portal/wrapped", label: "Wrapped" },
  { path: "/portal/zero-based-budget", label: "Zero Based Budget" },
  { path: "/pricing", label: "Pricing" },
  { path: "/register", label: "Register" },
  { path: "/reset-password", label: "Reset Password" },
  { path: "/shared/:token", label: ":Token" },
  { path: "/trial", label: "Trial" },
  { path: "/video/:token", label: ":Token" }
];

export default function LabLayer2() {
  const [q, setQ] = useState("");
  const tools = LAB_TOOLS.filter((t) => t.label.toLowerCase().includes(q.toLowerCase()));
  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 p-8">
      <h1 className="text-2xl font-semibold text-amber-400">The Lab — Advanced &amp; Supporting Tools</h1>
      <p className="mt-1 text-sm text-slate-400">{LAB_TOOLS.length} tools. Search to find one.</p>
      <input
        value={q}
        onChange={(e) => setQ(e.target.value)}
        placeholder="Search tools…"
        className="mt-4 w-full max-w-md rounded-md bg-slate-800 px-3 py-2 text-sm outline-none"
      />
      <div className="mt-6 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-2">
        {tools.map((t) => (
          <Link key={t.path} href={t.path}>
            <a className="block rounded-md bg-slate-900 px-3 py-2 text-sm hover:bg-slate-800">{t.label}</a>
          </Link>
        ))}
      </div>
    </div>
  );
}
