import { useState } from "react";
import { Link } from "wouter";

// Layer 2 — "The Lab": supporting/advanced tools kept out of the primary nav.
// Routes below are the REAL routes pulled from App.tsx, so every link resolves.
const LAB_TOOLS: { path: string; label: string }[] = [
  { path: "/", label: "" },
  { path: "/administrator", label: "Administrator" },
  { path: "/executive", label: "Executive" },
  { path: "/login", label: "Login" },
  { path: "/portal/1031-advanced", label: "1031 Advanced" },
  { path: "/portal/1031-exchange-analyzer", label: "1031 Exchange" },
  { path: "/portal/admin/health", label: "Health" },
  { path: "/portal/advisor-income-calculator", label: "Advisor Income Calculator" },
  { path: "/portal/affiliate-links", label: "Affiliate Links" },
  { path: "/portal/ai-brain-hub", label: "Ai Brain Hub" },
  { path: "/portal/ai-meeting-notes", label: "Ai Meeting Notes" },
  { path: "/portal/alt-allocator", label: "Alt Allocator" },
  { path: "/portal/annuity-waterfall", label: "Annuity Waterfall" },
  { path: "/portal/asset-protection", label: "Asset Protection" },
  { path: "/portal/avatar-twins", label: "Avatar Twins" },
  { path: "/portal/billing", label: "Billing" },
  { path: "/portal/branding", label: "Branding" },
  { path: "/portal/calculator-hub", label: "Calculator Hub" },
  { path: "/portal/carrier-ratings", label: "Carrier Ratings" },
  { path: "/portal/carrier-settings", label: "Carrier Settings" },
  { path: "/portal/cash-flow-optimizer", label: "Cash Flow Optimizer" },
  { path: "/portal/certifications", label: "Ce Credits" },
  { path: "/portal/charitable-giving-dashboard", label: "Charitable Giving Dashboard" },
  { path: "/portal/client-onboarding", label: "Client Onboarding" },
  { path: "/portal/client-portfolio", label: "Client Portfolio" },
  { path: "/portal/clients", label: "Clients" },
  { path: "/portal/co-pilot", label: "Co Pilot" },
  { path: "/portal/college-aid", label: "College Aid" },
  { path: "/portal/compliance", label: "Compliance Center" },
  { path: "/portal/compliance-reports", label: "Compliance Doc Gen" },
  { path: "/portal/concentrated-stock", label: "Concentrated Stock" },
  { path: "/portal/cost-segregation", label: "Cost Segregation" },
  { path: "/portal/cost-segregation-engine", label: "Cost Segregation Engine" },
  { path: "/portal/couples", label: "Couples" },
  { path: "/portal/crypto-tax-strategy", label: "Crypto Tax" },
  { path: "/portal/daf-strategic", label: "Daf Strategic" },
  { path: "/portal/daily-briefing", label: "Daily Briefing" },
  { path: "/portal/dashboard", label: "Dashboard" },
  { path: "/portal/digital-estate-planner", label: "Digital Estate" },
  { path: "/portal/direct-indexing", label: "Direct Indexing" },
  { path: "/portal/divorce-financial", label: "Divorce Financial" },
  { path: "/portal/document-templates", label: "Document Templates" },
  { path: "/portal/document-vault", label: "Document Vault" },
  { path: "/portal/dst-analyzer", label: "Dst Analyzer" },
  { path: "/portal/education-529", label: "Education 529" },
  { path: "/portal/email-campaigns", label: "Email Campaigns" },
  { path: "/portal/employee-retention", label: "Employee Retention" },
  { path: "/portal/engine-chaining", label: "Engine Chaining" },
  { path: "/portal/multi-gen-transfer", label: "Estate Wealth Transfer" },
  { path: "/portal/international-tax-planner", label: "Expat Tax" },
  { path: "/portal/family-bank", label: "Family Bank" },
  { path: "/portal/family-constitution", label: "Family Constitution" },
  { path: "/portal/family-governance", label: "Family Governance" },
  { path: "/portal/family-limited-partnership", label: "Family Limited Partnership" },
  { path: "/portal/fbar-fatca", label: "Fbar Fatca" },
  { path: "/portal/fiduciary-compliance", label: "Fiduciary Compliance" },
  { path: "/portal/fiduciary-tracker", label: "Fiduciary Tracker" },
  { path: "/portal/client-financial-health-score", label: "Financial Health Score" },
  { path: "/portal/financial-plan-checklist", label: "Financial Plan Checklist" },
  { path: "/portal/grantor-trust", label: "Grantor Trust" },
  { path: "/portal/hot-income", label: "Hot Income" },
  { path: "/portal/hubspot", label: "Hubspot" },
  { path: "/portal/idgt-modeler", label: "Idgt Modeler" },
  { path: "/portal/income-floor-strategy", label: "Income Floor Strategy" },
  { path: "/portal/inflation", label: "Inflation Adjusted Income" },
  { path: "/portal/innovation-dashboard", label: "Innovation Dashboard" },
  { path: "/portal/irc-reference", label: "Irc Reference" },
  { path: "/portal/knowledge", label: "Knowledge" },
  { path: "/portal/leaderboard", label: "Leaderboard" },
  { path: "/portal/life-settlement", label: "Life Settlement" },
  { path: "/portal/long-term-care", label: "Long Term Care" },
  { path: "/portal/market-pulse", label: "Market Pulse" },
  { path: "/portal/medicaid-planning", label: "Medicaid Planning" },
  { path: "/portal/meeting-prep", label: "Meeting Prep" },
  { path: "/portal/meetings", label: "Meetings" },
  { path: "/portal/morning-ritual", label: "Morning Ritual" },
  { path: "/portal/my-world", label: "My World" },
  { path: "/portal/nerve-center", label: "Nerve Center" },
  { path: "/portal/nii-surtax", label: "Nii Surtax" },
  { path: "/portal/nua-strategy", label: "Nua Planner" },
  { path: "/portal/oil-gas", label: "Oil Gas Strategy" },
  { path: "/portal/onboarding-quiz", label: "Onboarding Quiz" },
  { path: "/portal/onboarding-v2", label: "Onboarding V2" },
  { path: "/portal/client-onboarding-auto", label: "Onboarding Workflow" },
  { path: "/portal/organism-control", label: "Organism Control" },
  { path: "/portal/organism-health", label: "Organism Health" },
  { path: "/portal/patent-showcase", label: "Patent Showcase" },
  { path: "/portal/pe-secondary-market", label: "Pe Secondary Market" },
  { path: "/portal/pension-max-engine", label: "Pension Maximization" },
  { path: "/portal/philanthropy", label: "Philanthropy" },
  { path: "/portal/physician-forum", label: "Physician Forum" },
  { path: "/portal/physician-mortgage", label: "Physician Mortgage" },
  { path: "/portal/physicians-edge", label: "Physicians Edge" },
  { path: "/portal/post-mortem-tax", label: "Post Mortem Tax" },
  { path: "/portal/private-foundation", label: "Private Foundation" },
  { path: "/portal/forgiveness", label: "Pslf Calculator" },
  { path: "/portal/qsbs-exclusion", label: "Qsbs Exclusion" },
  { path: "/portal/qualified-opportunity-fund", label: "Qualified Opportunity Fund" },
  { path: "/portal/real-estate-portfolio", label: "Real Estate Portfolio" },
  { path: "/portal/report-builder", label: "Report Builder" },
  { path: "/portal/retirement-advantage", label: "Retirement Advantage" },
  { path: "/portal/income-gap", label: "Retirement Gap" },
  { path: "/portal/retirement-projection", label: "Retirement Income Proj" },
  { path: "/portal/revenue-guarantee", label: "Revenue Guarantee" },
  { path: "/portal/risk-tolerance", label: "Risk Tolerance" },
  { path: "/portal/russell-number", label: "Russell Number" },
  { path: "/portal/secret-secrets", label: "Secret Secrets" },
  { path: "/portal/secret-secrets/:id", label: ":Id" },
  { path: "/portal/withdrawal-sequencing", label: "Sequence Of Returns" },
  { path: "/portal/short-term-rentals", label: "Short Term Rental" },
  { path: "/portal/special-needs", label: "Special Needs" },
  { path: "/portal/spending-guardrails", label: "Spending Guardrails" },
  { path: "/portal/slat-planner", label: "Spousal Lifetime Access" },
  { path: "/portal/str-strategy", label: "Str Strategy" },
  { path: "/portal/str-tax-eliminator", label: "Str Tax Strategy" },
  { path: "/portal/market-stress-test", label: "Stress Test" },
  { path: "/portal/structured-notes", label: "Structured Notes" },
  { path: "/portal/structured-settlement", label: "Structured Settlement" },
  { path: "/portal/syndication-deal", label: "Syndication Deal" },
  { path: "/portal/tax-combos/:id", label: ":Id" },
  { path: "/portal/team", label: "Team" },
  { path: "/portal/team-management", label: "Team Management" },
  { path: "/portal/time-lapse", label: "Time Lapse" },
  { path: "/portal/trust-decanting", label: "Trust Decanting" },
  { path: "/portal/usage-analytics", label: "Usage Analytics" },
  { path: "/portal/video-library", label: "Video Library" },
  { path: "/portal/wealth-dashboard", label: "Wealth Dashboard" },
  { path: "/portal/wealth-erosion", label: "Wealth Erosion" },
  { path: "/portal/wealth-transfer-scorecard", label: "Wealth Transfer Scorecard" },
  { path: "/portal/estate-timeline", label: "Wealth Transfer Timeline" },
  { path: "/portal/webhooks", label: "Webhooks" },
  { path: "/portal/website-usage", label: "Website Usage" },
  { path: "/portal/wrapped", label: "Wrapped" },
  { path: "/pricing", label: "Pricing" },
  { path: "/register", label: "Register" },
  { path: "/reset-password", label: "Reset Password" },
  { path: "/shared/:token", label: ":Token" },
  { path: "/trial", label: "Trial" },
  { path: "/video/:token", label: ":Token" }
];

export default function LabLayer2() {
  const [q, setQ] = useState("");
  const tools = LAB_TOOLS.filter((t) => t.label.toLowerCase().includes(q.toLowerCase()));
  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 p-8">
      <h1 className="text-2xl font-semibold text-amber-400">The Lab — Advanced &amp; Supporting Tools</h1>
      <p className="mt-1 text-sm text-slate-400">{LAB_TOOLS.length} tools. Search to find one.</p>
      <input
        value={q}
        onChange={(e) => setQ(e.target.value)}
        placeholder="Search tools…"
        className="mt-4 w-full max-w-md rounded-md bg-slate-800 px-3 py-2 text-sm outline-none"
      />
      <div className="mt-6 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-2">
        {tools.map((t) => (
          <Link key={t.path} href={t.path}>
            <a className="block rounded-md bg-slate-900 px-3 py-2 text-sm hover:bg-slate-800">{t.label}</a>
          </Link>
        ))}
      </div>
    </div>
  );
}
