CREATE TABLE `video_assessments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`assessmentId` int,
	`videoUrl` text,
	`audioUrl` text,
	`durationMs` int,
	`videoStatus` enum('pending','processing','complete','failed') NOT NULL DEFAULT 'pending',
	`processingStartedAt` bigint,
	`completedAt` bigint,
	`errorMessage` text,
	`bodyLanguage` json,
	`gesturePatterns` json,
	`postureShifts` json,
	`microExpressions` json,
	`eyePatterns` json,
	`dominantAccessPattern` varchar(32),
	`eyeMovementSequences` json,
	`leadSystem` varchar(20),
	`congruenceScore` float,
	`authenticityMarkers` json,
	`stressIndicators` json,
	`rapportSignals` json,
	`behavioralProfile` json,
	`axisAdjustments` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `video_assessments_id` PRIMARY KEY(`id`)
);
