// Goal shelf, WAVE 2: BUSINESS — start and grow a business (sections 8550–8599).
// Verification: every DOI below was resolved against the Crossref record
// (api.crossref.org) on 2026-09-11. See ../types.ts for the contract.
import { doi, type GoalShelfCluster } from "../types";

export const SECTIONS: Record<string, string> = {
  "8550": "Pricing Psychology — Price Endings, Anchors & Field Price Tests",
  "8551": "Customer Retention & Loyalty Economics",
  "8552": "Online Reviews & Reputation",
  "8553": "Word of Mouth & Referral Programs",
  "8554": "Cold Outreach & Sales Conversion",
  "8555": "Customer Feedback Loops, Hypothesis Tests & Pivots",
  "8556": "Hiring the First Employee & Learning to Delegate",
  "8557": "Cofounder Conflict & Equity Splits",
  "8558": "Entrepreneurial Overconfidence & Base Rates",
  "8559": "Business Coaching, Consulting & Training — The Trials",
  "8560": "Personal-Initiative Training",
  "8561": "Peer Groups for Founders",
  "8562": "Family Business Succession",
  "8563": "Women & Minority Entrepreneurship — Programs & the Credit Gap",
  "8564": "SBA Loans, Bank Relationships & Small-Business Credit",
  "8565": "Crowdfunding",
  "8566": "Self-Employment, Job Satisfaction & Happiness",
  "8567": "The Gig Economy as a Path",
  "8568": "Business Exit & Selling the Company",
};

export const CLUSTERS: GoalShelfCluster[] = [
  {
    id: "gs-business-w2-price-test",
    goal: "business", tier: "moderate", section: "8550",
    title: "Test the Price — Endings, Anchors and a Real Split Test",
    subtitle: "Price is the most under-tested lever a small business owns",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "weeks", durability: "sustained", effort: "moderate" },
    feeds: ["Margin discipline", "Evidence-based decisions"],
    description:
      "Field experiments in catalogs and retail show that a $9 or 99-cent ending can lift demand for the same item, that buyers read the left-most digit first, and that even arbitrary anchors move what people will pay. Pay-what-you-want and 'fairness' studies add the boundary: prices customers perceive as unfair or manipulative depress demand and self-image. The honest limit is that these effects are context-specific, so the protocol is to run your own test rather than copy a rule.",
    action: "Pick one product this month and run a two-arm price test for four weeks (for example a round price versus a 9-ending, or two anchor presentations), splitting customers by day or channel. Keep the arm that wins on profit, not just units.",
    reinforcement: [
      { kind: "book", title: "Priceless: The Myth of Fair Value", by: "William Poundstone", note: "Popular treatment of the anchoring and price-perception experiments cited here." },
    ],
    sources: [
      { cite: "Anderson, E. T., & Simester, D. I. (2003). Effects of $9 price endings on retail sales: Evidence from field experiments. Quantitative Marketing and Economics, 1(1), 93–110.", note: "Mail-order field experiments in which 9-ending prices raised demand for the same goods, with the effect strongest for new items; the paper on which most 'charm pricing' advice rests.", link: doi("10.1023/A:1023581927405"), kind: "doi" },
      { cite: "Schindler, R. M., & Kibarian, T. M. (1996). Increased consumer sales response though use of 99-ending prices. Journal of Retailing, 72(2), 187–199.", note: "An earlier catalog experiment finding higher sales response to 99-ending prices, replicated by later field work.", link: doi("10.1016/S0022-4359(96)90013-5"), kind: "doi" },
      { cite: "Thomas, M., & Morwitz, V. (2005). Penny wise and pound foolish: The left-digit effect in price cognition. Journal of Consumer Research, 32(1), 54–64.", note: "Lab evidence that buyers encode the left-most digit first, which is why $2.99 reads as 'two dollars' and why the ending matters only when the left digit changes.", link: doi("10.1086/429600"), kind: "doi" },
      { cite: "Ariely, D., Loewenstein, G., & Prelec, D. (2003). \"Coherent arbitrariness\": Stable demand curves without stable preferences. The Quarterly Journal of Economics, 118(1), 73–106.", note: "Arbitrary anchors shifted what people would pay while relative preferences stayed orderly; the reason your first stated price frames every later one.", link: doi("10.1162/00335530360535153"), kind: "doi" },
      { cite: "Anderson, E. T., & Simester, D. I. (2008). Research note—Does demand fall when customers perceive that prices are unfair? The case of premium pricing for large sizes. Marketing Science, 27(3), 492–500.", note: "Field evidence that a pricing rule customers perceive as unfair reduced demand, the boundary on aggressive pricing tactics.", link: doi("10.1287/mksc.1070.0323"), kind: "doi" },
      { cite: "Kim, J.-Y., Natter, M., & Spann, M. (2009). Pay what you want: A new participative pricing mechanism. Journal of Marketing, 73(1), 44–58.", note: "Field studies of pay-what-you-want pricing in which customers paid positive amounts and in some settings revenue held or rose, showing how much social norms shape willingness to pay.", link: doi("10.1509/jmkg.73.1.044"), kind: "doi" },
      { cite: "Gneezy, A., Gneezy, U., Riener, G., & Nelson, L. D. (2012). Pay-what-you-want, identity, and self-signaling in markets. Proceedings of the National Academy of Sciences, 109(19), 7236–7240.", note: "Field experiments showing that when paying feels like a statement about who you are, some customers pay more and others opt out entirely; pricing is partly identity.", link: doi("10.1073/pnas.1120893109"), kind: "doi" },
    ],
  },
  {
    id: "gs-business-w2-retention-review",
    goal: "business", tier: "fundamental", section: "8551",
    title: "The Monthly Retention Review",
    subtitle: "Satisfaction, repurchase and the real economics of keeping a customer",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "months", durability: "lasting", effort: "low" },
    feeds: ["Customer focus", "Financial literacy"],
    description:
      "Duration models of customer relationships show that satisfaction predicts how long a customer stays, that negative experiences hurt repurchase more than positive ones help, and that customer equity is a usable frame for where marketing money should go. The loyalty-program meta-analysis finds positive average effects on loyalty, while the long-life-customer study warns that tenure and profitability are not the same thing. The protocol is a monthly look at who left, who stayed and why.",
    action: "On the first business day of each month, list the customers who churned or lapsed in the prior month, call three of them, and log the reason. Track one retention number (repeat-purchase rate or month-to-month retention) on the same page as revenue.",
    sources: [
      { cite: "Bolton, R. N. (1998). A dynamic model of the duration of the customer's relationship with a continuous service provider: The role of satisfaction. Marketing Science, 17(1), 45–65.", note: "Modeled how long customers stayed with a service provider; prior satisfaction lengthened the relationship, and existing customers weighed new experiences against their history.", link: doi("10.1287/mksc.17.1.45"), kind: "doi" },
      { cite: "Anderson, E. W., Fornell, C., & Lehmann, D. R. (1994). Customer satisfaction, market share, and profitability: Findings from Sweden. Journal of Marketing, 58(3), 53–66.", note: "National satisfaction data linked to firm profitability, the foundational evidence that satisfaction is an economic asset rather than a soft metric.", link: doi("10.1177/002224299405800304"), kind: "doi" },
      { cite: "Mittal, V., Ross, W. T., Jr., & Baldasare, P. M. (1998). The asymmetric impact of negative and positive attribute-level performance on overall satisfaction and repurchase intentions. Journal of Marketing, 62(1), 33–47.", note: "Negative performance on an attribute hurt satisfaction and repurchase intent more than equivalent positive performance helped; fix failures before adding delights.", link: doi("10.1177/002224299806200104"), kind: "doi" },
      { cite: "Rust, R. T., Lemon, K. N., & Zeithaml, V. A. (2004). Return on marketing: Using customer equity to focus marketing strategy. Journal of Marketing, 68(1), 109–127.", note: "A customer-equity framework for judging marketing spend by its effect on the lifetime value of the customer base, the accounting frame this review uses.", link: doi("10.1509/jmkg.68.1.109.24030"), kind: "doi" },
      { cite: "Reinartz, W. J., & Kumar, V. (2000). On the profitability of long-life customers in a noncontractual setting: An empirical investigation and implications for marketing. Journal of Marketing, 64(4), 17–35.", note: "In a noncontractual catalog business, long-tenure customers were not reliably the most profitable ones; the caution against assuming loyalty equals margin.", link: doi("10.1509/jmkg.64.4.17.18077"), kind: "doi" },
      { cite: "Belli, A., O'Rourke, A.-M., Carrillat, F. A., Pupovac, L., Melnyk, V., & Napolova, E. (2021). 40 years of loyalty programs: How effective are they? Generalizations from a meta-analysis. Journal of the Academy of Marketing Science, 50(1), 147–173.", note: "Meta-analysis of four decades of loyalty-program studies reporting positive average effects on customer loyalty with sizable variation by program design.", link: doi("10.1007/s11747-021-00804-z"), kind: "doi" },
    ],
  },
  {
    id: "gs-business-w2-reviews-channel",
    goal: "business", tier: "moderate", section: "8552",
    title: "Run the Reviews Channel Like a Sales Channel",
    subtitle: "Ratings move revenue; management responses move ratings",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "weeks", durability: "sustained", effort: "moderate" },
    feeds: ["Reputation", "Customer focus"],
    description:
      "Online book-review and Yelp studies with quasi-experimental designs show that ratings causally shift sales and restaurant capacity, and a meta-analysis across retail confirms review valence and volume affect sales. A Marketing Science study found that when businesses began responding to reviews, subsequent ratings improved. The boundary: platforms filter suspicious reviews, and the studies here measure honest, systematic engagement, not gaming.",
    action: "Set a weekly 20-minute slot to ask five recent customers for a review and to reply, in your own words, to every new review from the past week, positive or negative. Do this for three months and compare your average rating and review count to the quarter before.",
    sources: [
      { cite: "Chevalier, J. A., & Mayzlin, D. (2006). The effect of word of mouth on sales: Online book reviews. Journal of Marketing Research, 43(3), 345–354.", note: "Compared the same books across Amazon and Barnes & Noble; better reviews raised relative sales, and one-star reviews hurt more than five-star reviews helped.", link: doi("10.1509/jmkr.43.3.345"), kind: "doi" },
      { cite: "Anderson, M., & Magruder, J. (2012). Learning from the crowd: Regression discontinuity estimates of the effects of an online review database. The Economic Journal, 122(563), 957–989.", note: "Used Yelp's rounding of star ratings as a natural experiment; crossing a half-star threshold raised the chance a restaurant sold out its reservations.", link: doi("10.1111/j.1468-0297.2012.02512.x"), kind: "doi" },
      { cite: "Floyd, K., Freling, R., Alhoqail, S., Cho, H. Y., & Freling, T. (2014). How online product reviews affect retail sales: A meta-analysis. Journal of Retailing, 90(2), 217–232.", note: "Meta-analysis of review effects on retail sales finding that review valence and volume matter, with the size of the effect depending on product and platform context.", link: doi("10.1016/j.jretai.2014.04.004"), kind: "doi" },
      { cite: "Proserpio, D., & Zervas, G. (2017). Online reputation management: Estimating the impact of management responses on consumer reviews. Marketing Science, 36(5), 645–665.", note: "Hotels that started responding to reviews subsequently received better ratings; the study behind the 'reply to every review' step.", link: doi("10.1287/mksc.2017.1043"), kind: "doi" },
      { cite: "Luca, M., & Zervas, G. (2016). Fake it till you make it: Reputation, competition, and Yelp review fraud. Management Science, 62(12), 3412–3427.", note: "Roughly 16% of Yelp restaurant reviews were filtered as suspicious; businesses with weak reputations were most likely to solicit fakes, which is what platform filters target.", link: doi("10.1287/mnsc.2015.2304"), kind: "doi" },
      { cite: "Mayzlin, D., Dover, Y., & Chevalier, J. (2014). Promotional reviews: An empirical investigation of online review manipulation. American Economic Review, 104(8), 2421–2455.", note: "Cross-platform comparison of hotel reviews showing that manipulation is more common where it is cheap to post; independent hotels next to competitors had more suspicious extreme reviews.", link: doi("10.1257/aer.104.8.2421"), kind: "doi" },
    ],
  },
  {
    id: "gs-business-w2-fake-reviews",
    goal: "business", tier: "fundamental", section: "8552",
    title: "Buying or Faking Reviews",
    subtitle: "Rated at the floor: platforms filter it, and it signals weakness",
    evidenceTag: "Strong",
    impact: { magnitude: 1, latency: "days", durability: "transient", effort: "low" },
    callout: "Do not do this. The Yelp and hotel-review studies find that fake reviews cluster among businesses with weak reputations, that platforms filter a large share of suspicious reviews, and that sting operations have caught businesses soliciting them. The measured upside is transient and the downside is a filtered profile or public exposure.",
    description:
      "This protocol is on the shelf so the library counts it as debunked. Review fraud is most common where reputations are weakest, platforms identify and suppress a substantial fraction of it, and the same research shows that the honest levers (responding to reviews, asking satisfied customers) move ratings without the risk.",
    action: "If you have ever paid for or written reviews of your own business, stop, and redirect the time to the weekly ask-and-reply routine above.",
    sources: [
      { cite: "Luca, M., & Zervas, G. (2016). Fake it till you make it: Reputation, competition, and Yelp review fraud. Management Science, 62(12), 3412–3427.", note: "About 16% of restaurant reviews were filtered as suspicious; fraud rose when a restaurant's reputation was weak, and Yelp's sting caught businesses soliciting fakes.", link: doi("10.1287/mnsc.2015.2304"), kind: "doi" },
      { cite: "Mayzlin, D., Dover, Y., & Chevalier, J. (2014). Promotional reviews: An empirical investigation of online review manipulation. American Economic Review, 104(8), 2421–2455.", note: "Evidence of systematic review manipulation on platforms where posting is unverified, concentrated among independent hotels facing nearby competitors.", link: doi("10.1257/aer.104.8.2421"), kind: "doi" },
      { cite: "Proserpio, D., & Zervas, G. (2017). Online reputation management: Estimating the impact of management responses on consumer reviews. Marketing Science, 36(5), 645–665.", note: "The legitimate alternative: management responses were followed by better subsequent ratings.", link: doi("10.1287/mksc.2017.1043"), kind: "doi" },
    ],
  },
  {
    id: "gs-business-w2-referral-program",
    goal: "business", tier: "moderate", section: "8553",
    title: "Build a Referral Program, Then Measure Referred-Customer Value",
    subtitle: "Referred customers are worth more, and word of mouth outlasts paid media",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "months", durability: "lasting", effort: "moderate" },
    feeds: ["Customer focus", "Systems thinking"],
    description:
      "A German bank's referral program produced customers with higher margins and lower churn than other new customers, and follow-up work showed the effect is strongest when referrer and referred are alike. Studies of a social-networking site found word-of-mouth referrals had substantially longer carryover than traditional marketing, and research on customer referral value shows that the customers who refer are often not the ones who buy the most. Content that evokes high-arousal emotion gets shared more.",
    action: "Write a one-line referral offer this month and ask every satisfied customer for one introduction at the moment of delivery. After 90 days, compare referred customers' repeat rate and margin against your other new customers.",
    sources: [
      { cite: "Schmitt, P., Skiera, B., & Van den Bulte, C. (2011). Referral programs and customer value. Journal of Marketing, 75(1), 46–59.", note: "Referred customers at a German bank had higher contribution margins and lower churn than non-referred customers, so the program paid back; the cornerstone study on referral programs.", link: doi("10.1509/jm.75.1.46"), kind: "doi" },
      { cite: "Van den Bulte, C., Bayer, E., Skiera, B., & Schmitt, P. (2018). How customer referral programs turn social capital into economic capital. Journal of Marketing Research, 55(1), 132–146.", note: "Extension showing the referral premium was largest when referrer and referred customer were similar, pointing to better matching as the mechanism.", link: doi("10.1509/jmr.14.0653"), kind: "doi" },
      { cite: "Kumar, V., Petersen, J. A., & Leone, R. P. (2010). Driving profitability by encouraging customer referrals: Who, when, and how. Journal of Marketing, 74(5), 1–17.", note: "Field studies in telecom and financial services separated customers' purchase value from their referral value and found the two often diverge; target referral asks accordingly.", link: doi("10.1509/jmkg.74.5.001"), kind: "doi" },
      { cite: "Trusov, M., Bucklin, R. E., & Pauwels, K. (2009). Effects of word-of-mouth versus traditional marketing: Findings from an internet social networking site. Journal of Marketing, 73(5), 90–102.", note: "Word-of-mouth referrals to a social-networking site had a much longer carryover effect on sign-ups than traditional marketing events.", link: doi("10.1509/jmkg.73.5.90"), kind: "doi" },
      { cite: "Godes, D., & Mayzlin, D. (2004). Using online conversations to study word-of-mouth communication. Marketing Science, 23(4), 545–560.", note: "Showed that the dispersion of online conversation across communities predicted television ratings, establishing online conversation as a measurable word-of-mouth signal.", link: doi("10.1287/mksc.1040.0071"), kind: "doi" },
      { cite: "Berger, J., & Milkman, K. L. (2012). What makes online content viral? Journal of Marketing Research, 49(2), 192–205.", note: "Analysis of New York Times articles: content evoking high-arousal emotions (awe, anger, anxiety) was shared more, sadness less; a guide for what customers pass along.", link: doi("10.1509/jmr.10.0353"), kind: "doi" },
      { cite: "Libai, B., Bolton, R., Bügel, M. S., de Ruyter, K., Götz, O., Risselada, H., & Stephen, A. T. (2010). Customer-to-customer interactions: Broadening the scope of word of mouth research. Journal of Service Research, 13(3), 267–282.", note: "Review framing word of mouth as one form of customer-to-customer interaction and summarizing what is known about measuring its value.", link: doi("10.1177/1094670510375600"), kind: "doi" },
    ],
  },
  {
    id: "gs-business-w2-outreach-block",
    goal: "business", tier: "fundamental", section: "8554",
    title: "The Daily Outreach Block, Sold Adaptively",
    subtitle: "What the sales-performance meta-analyses actually support",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "moderate" },
    feeds: ["Discipline", "Communication"],
    description:
      "There is little peer-reviewed research on 'cold email' as such; what exists is meta-analytic work on what predicts salesperson performance. Adaptive selling (adjusting the pitch to the buyer) and customer orientation are reliably associated with performance, role clarity and skill matter more than personality traits, and a large sales-force study found empowering leadership improved customer satisfaction. The honest boundary: these are correlational syntheses from employed salespeople, not trials of outreach scripts.",
    action: "Block the same 45 minutes every working day for outreach. Before each contact, write one sentence about what this specific prospect needs; after each, log what you learned. Review the log weekly and change one thing in the approach.",
    sources: [
      { cite: "Franke, G. R., & Park, J.-E. (2006). Salesperson adaptive selling behavior and customer orientation: A meta-analysis. Journal of Marketing Research, 43(4), 693–702.", note: "Meta-analysis finding adaptive selling and customer orientation related to salesperson performance and satisfaction; the basis for tailoring each contact.", link: doi("10.1509/jmkr.43.4.693"), kind: "doi" },
      { cite: "Verbeke, W., Dietz, B., & Verwaal, E. (2010). Drivers of sales performance: A contemporary meta-analysis. Have salespeople become knowledge brokers? Journal of the Academy of Marketing Science, 39(3), 407–428.", note: "Updated meta-analysis in which selling-related knowledge, adaptiveness, role ambiguity and cognitive aptitude were among the strongest correlates of performance.", link: doi("10.1007/s11747-010-0211-8"), kind: "doi" },
      { cite: "Churchill, G. A., Jr., Ford, N. M., Hartley, S. W., & Walker, O. C., Jr. (1985). The determinants of salesperson performance: A meta-analysis. Journal of Marketing Research, 22(2), 103.", note: "The classic meta-analysis: role perceptions, skill and motivation predicted performance better than aptitude or personal characteristics.", link: doi("10.2307/3151357"), kind: "doi" },
      { cite: "Ahearne, M., Mathieu, J., & Rapp, A. (2005). To empower or not to empower your sales force? An empirical examination of the influence of leadership empowerment behavior on customer satisfaction and performance. Journal of Applied Psychology, 90(5), 945–955.", note: "In a pharmaceutical sales force, empowering leadership improved customer satisfaction through salesperson self-efficacy and adaptability; relevant once you manage others who sell.", link: doi("10.1037/0021-9010.90.5.945"), kind: "doi" },
    ],
  },
  {
    id: "gs-business-w2-scientific-method",
    goal: "business", tier: "advanced", section: "8555",
    title: "The Scientific Founder — Hypotheses, Tests and Deliberate Pivots",
    subtitle: "The randomized trial behind 'talk to customers, then decide'",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "months", durability: "lasting", effort: "high" },
    feeds: ["Evidence-based decisions", "Adaptability"],
    description:
      "In a randomized trial with Italian startups, founders trained to frame their idea as explicit hypotheses and test them with customers earned more revenue on average and were more likely to pivot or exit early rather than persist with a weak idea; a later large-scale replication across several countries confirmed the pattern. Qualitative work on lean-startup adoption shows how teams actually run these loops. The boundary is that the training was structured and instructor-led, not a book read alone.",
    action: "Write your business model as five falsifiable hypotheses (customer, problem, solution, channel, price). Each week for eight weeks, run one cheap test (ten customer interviews, a landing-page test, a small pilot) against one hypothesis and record in advance what result would make you change course.",
    reinforcement: [
      { kind: "book", title: "The Lean Startup", by: "Eric Ries", note: "The practitioner method that the Camuffo trials formalized and tested." },
    ],
    sources: [
      { cite: "Camuffo, A., Cordova, A., Gambardella, A., & Spina, C. (2020). A scientific approach to entrepreneurial decision making: Evidence from a randomized control trial. Management Science, 66(2), 564–586.", note: "Randomized trial with Italian startups: founders taught to state and test hypotheses earned more revenue and were more likely to pivot or drop weak ideas than controls.", link: doi("10.1287/mnsc.2018.3249"), kind: "doi" },
      { cite: "Camuffo, A., Gambardella, A., Messinese, D., Novelli, E., Paolucci, E., & Spina, C. (2024). A scientific approach to entrepreneurial decision-making: Large-scale replication and extension. Strategic Management Journal, 45(6), 1209–1237.", note: "Multi-country replication of the scientific-approach trial extending the original findings on performance and decision quality.", link: doi("10.1002/smj.3580"), kind: "doi" },
      { cite: "Ghezzi, A. (2019). Digital startups and the adoption and implementation of Lean Startup approaches: Effectuation, bricolage and opportunity creation in practice. Technological Forecasting and Social Change, 146, 945–960.", note: "Case studies of how digital startups actually implement build-measure-learn loops, useful for translating the trial into weekly practice.", link: doi("10.1016/j.techfore.2018.09.017"), kind: "doi" },
      { cite: "McKenzie, D., & Woodruff, C. (2017). Business practices in small firms in developing countries. Management Science, 63(9), 2967–2981.", note: "Across thousands of small firms, a simple index of business practices (record-keeping, marketing, planning) predicted survival, sales and profits, the practices these loops build.", link: doi("10.1287/mnsc.2016.2492"), kind: "doi" },
      { cite: "Bloom, N., Eifert, B., Mahajan, A., McKenzie, D., & Roberts, J. (2012). Does management matter? Evidence from India. The Quarterly Journal of Economics, 128(1), 1–51.", note: "Randomized management consulting in Indian textile plants raised productivity; the strongest causal evidence that adopting measured practices changes outcomes.", link: doi("10.1093/qje/qjs044"), kind: "doi" },
    ],
  },
  {
    id: "gs-business-w2-first-hire",
    goal: "business", tier: "advanced", section: "8556",
    title: "The First Hire and the Delegation Threshold",
    subtitle: "What predicts a solo founder becoming an employer, and why owners fail to delegate",
    evidenceTag: "Moderate",
    impact: { magnitude: 4, latency: "months", durability: "lasting", effort: "high" },
    feeds: ["Leadership", "Systems thinking"],
    description:
      "Census-linked data show the first hire usually happens early or not at all, and that owners who make it differ in prior earnings, hours and business type. A Danish register study found the first employee's characteristics predicted subsequent growth, and a model fitted to Indian and US firm data shows that where owners cannot trust delegated managers, firms stay small. Founder-CEO succession research shows that success itself raises the odds the founder is replaced. The boundary: mostly observational, so treat this as a map of the terrain rather than a guarantee.",
    action: "Write the job description for your first hire this month, listing the tasks that only you can do and the tasks you currently do that someone else could. Set a revenue or hours trigger at which you will hire, and a 90-day delegation plan for the first three tasks you hand off.",
    reinforcement: [
      { kind: "book", title: "The Founder's Dilemmas", by: "Noam Wasserman", note: "Trade book by the author of the founder-CEO succession and founder-equity studies." },
    ],
    sources: [
      { cite: "Fairlie, R. W., & Miranda, J. (2016). Taking the leap: The determinants of entrepreneurs hiring their first employee. Journal of Economics & Management Strategy, 26(1), 3–34.", note: "Linked Census data on non-employer businesses: most first hires occurred in the first years, and owner and business characteristics predicted who took the leap.", link: doi("10.1111/jems.12176"), kind: "doi" },
      { cite: "Coad, A., Nielsen, K., & Timmermans, B. (2016). My first employee: An empirical investigation. Small Business Economics, 48(1), 25–45.", note: "Danish register data on the first hire showing who founders chose and how the first employee's profile related to the firm's later growth and survival.", link: doi("10.1007/s11187-016-9748-3"), kind: "doi" },
      { cite: "Akcigit, U., Alp, H., & Peters, M. (2021). Lack of selection and limits to delegation: Firm dynamics in developing countries. American Economic Review, 111(1), 231–275.", note: "Model and data showing that when owners cannot delegate to trusted managers, firms stop growing at the owner's own capacity; delegation is the growth constraint.", link: doi("10.1257/aer.20180555"), kind: "doi" },
      { cite: "Bloom, N., Eifert, B., Mahajan, A., McKenzie, D., & Roberts, J. (2012). Does management matter? Evidence from India. The Quarterly Journal of Economics, 128(1), 1–51.", note: "Randomized management intervention in which owners' reluctance to delegate to non-family managers was a documented brake on plant growth.", link: doi("10.1093/qje/qjs044"), kind: "doi" },
      { cite: "Wasserman, N. (2003). Founder-CEO succession and the paradox of entrepreneurial success. Organization Science, 14(2), 149–172.", note: "Study of founder-led firms in which reaching milestones such as product completion raised the chance the founder was replaced as CEO; growth changes the job.", link: doi("10.1287/orsc.14.2.149.14995"), kind: "doi" },
    ],
  },
  {
    id: "gs-business-w2-founder-agreement",
    goal: "business", tier: "moderate", section: "8557",
    title: "The Founder Agreement — Negotiate Equity Before the First Dollar",
    subtitle: "Splits, perceived fairness and the conflict they seed",
    evidenceTag: "Moderate",
    impact: { magnitude: 4, latency: "weeks", durability: "lasting", effort: "moderate" },
    feeds: ["Communication", "Fairness"],
    description:
      "A survey of thousands of startups found that founding teams who split equity equally and quickly were less likely to raise outside financing, a pattern the authors attribute to selection and to avoiding a hard conversation rather than to the split itself. Interview and survey work on entrepreneurial teams shows that perceived justice in the split, not the numbers, predicts team satisfaction and conflict; studies of new-venture teams and venture boards find that affective conflict over money damages performance. The protocol is a written agreement reached through a real negotiation.",
    action: "Before incorporating or accepting money, spend one working session with each cofounder listing contributions, risk taken, and future roles, then agree a split with vesting in writing. Revisit it at twelve months.",
    sources: [
      { cite: "Hellmann, T., & Wasserman, N. (2017). The first deal: The division of founder equity in new ventures. Management Science, 63(8), 2647–2666.", note: "Survey of startup founding teams: quick, equal splits were associated with a lower chance of later outside financing, consistent with teams avoiding a difficult negotiation.", link: doi("10.1287/mnsc.2016.2474"), kind: "doi" },
      { cite: "Breugst, N., Patzelt, H., & Rathgeber, P. (2015). How should we divide the pie? Equity distribution and its impact on entrepreneurial teams. Journal of Business Venturing, 30(1), 66–94.", note: "Qualitative study of entrepreneurial teams in which perceived justice of the equity split, rather than the split itself, shaped team dynamics and conflict.", link: doi("10.1016/j.jbusvent.2014.07.006"), kind: "doi" },
      { cite: "Ensley, M. D., Pearson, A. W., & Amason, A. C. (2002). Understanding the dynamics of new venture top management teams: Cohesion, conflict, and new venture performance. Journal of Business Venturing, 17(4), 365–386.", note: "Among fast-growth new ventures, affective (personal) conflict in the founding team was associated with worse performance while cohesion helped.", link: doi("10.1016/S0883-9026(00)00065-3"), kind: "doi" },
      { cite: "Forbes, D. P., Korsgaard, M. A., & Sapienza, H. J. (2010). Financing decisions as a source of conflict in venture boards. Journal of Business Venturing, 25(6), 579–592.", note: "Financing decisions were a recurring trigger of conflict between founders and investors on venture boards; the money conversation does not end at founding.", link: doi("10.1016/j.jbusvent.2009.03.001"), kind: "doi" },
    ],
  },
  {
    id: "gs-business-w2-base-rate-check",
    goal: "business", tier: "fundamental", section: "8558",
    title: "The Base-Rate Check",
    subtitle: "Entrepreneurs overestimate their odds; write the real ones down",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "days", durability: "sustained", effort: "low" },
    feeds: ["Judgment", "Humility"],
    description:
      "Surveys of new business owners find most rate their own chance of success far above the odds they assign to businesses like theirs; laboratory market-entry games show overconfidence produces excess entry; and cross-country data link confidence to the decision to start a firm. Hubris theory and behavioral-economics reviews connect this to overinvestment and failure, while later work shows confident founders also rebound and try again. The protocol is not to become pessimistic but to put a number on the table.",
    action: "Once a quarter, write down the survival rate for businesses like yours over five years, your own estimate of your odds, and the three specific reasons you think you will beat the base rate. Show it to one person who will argue with you.",
    sources: [
      { cite: "Cooper, A. C., Woo, C. Y., & Dunkelberg, W. C. (1988). Entrepreneurs' perceived chances for success. Journal of Business Venturing, 3(2), 97–108.", note: "Survey of new business owners in which most rated their own chances of success as far better than those of similar businesses; the original overconfidence finding.", link: doi("10.1016/0883-9026(88)90020-1"), kind: "doi" },
      { cite: "Camerer, C., & Lovallo, D. (1999). Overconfidence and excess entry: An experimental approach. American Economic Review, 89(1), 306–318.", note: "Market-entry experiments in which participants entered more when payoffs depended on their own skill, producing losses; 'reference group neglect' as the mechanism.", link: doi("10.1257/aer.89.1.306"), kind: "doi" },
      { cite: "Koellinger, P., Minniti, M., & Schade, C. (2007). \"I think I can, I think I can\": Overconfidence and entrepreneurial behavior. Journal of Economic Psychology, 28(4), 502–527.", note: "Cross-country survey data in which subjective confidence in one's skills was among the strongest predictors of starting a business, independent of objective conditions.", link: doi("10.1016/j.joep.2006.11.002"), kind: "doi" },
      { cite: "Hayward, M. L. A., Shepherd, D. A., & Griffin, D. (2006). A hubris theory of entrepreneurship. Management Science, 52(2), 160–172.", note: "Theory paper linking founder overconfidence to overcommitting resources and to venture failure.", link: doi("10.1287/mnsc.1050.0483"), kind: "doi" },
      { cite: "Åstebro, T., Herz, H., Nanda, R., & Weber, R. A. (2014). Seeking the roots of entrepreneurship: Insights from behavioral economics. Journal of Economic Perspectives, 28(3), 49–70.", note: "Review of why people enter entrepreneurship despite low average returns, weighing overconfidence, risk preferences and nonpecuniary benefits.", link: doi("10.1257/jep.28.3.49"), kind: "doi" },
      { cite: "Hayward, M. L. A., Forster, W. R., Sarasvathy, S. D., & Fredrickson, B. L. (2010). Beyond hubris: How highly confident entrepreneurs rebound to venture again. Journal of Business Venturing, 25(6), 569–578.", note: "Argues the same confidence that causes failure helps founders recover and start again; the reason to calibrate confidence rather than eliminate it.", link: doi("10.1016/j.jbusvent.2009.03.002"), kind: "doi" },
    ],
  },
  {
    id: "gs-business-w2-consulting-trials",
    goal: "business", tier: "advanced", section: "8559",
    title: "Buy Expert Help — What the Consulting and Training Trials Found",
    subtitle: "Subsidized consulting raised sales and employment; generic training is weaker",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "months", durability: "lasting", effort: "high" },
    feeds: ["Evidence-based decisions", "Management skill"],
    description:
      "A randomized trial in Mexico gave small firms a year of subsidized consulting and found higher sales, profits and, years later, employment. A second trial compared training, consulting, hiring a specialist and outsourcing marketing and finance tasks, and found that both insourcing and outsourcing expertise improved practices and sales. Reviews of dozens of training evaluations conclude that classroom training has modest average effects that are easy to miss in underpowered studies. The boundary: these were subsidized, structured programs in developing-country contexts.",
    action: "Within the next 90 days, buy a defined block of expert help for the function you are weakest at (a bookkeeper for two months, a marketing consultant for a fixed project, or a management-practices course). Define the practice you expect to change and measure it before and after.",
    sources: [
      { cite: "Bruhn, M., Karlan, D., & Schoar, A. (2018). The impact of consulting services on small and medium enterprises: Evidence from a randomized trial in Mexico. Journal of Political Economy, 126(2), 635–687.", note: "Randomized subsidized consulting for small firms in Mexico raised productivity and sales, with employment gains visible years later.", link: doi("10.1086/696154"), kind: "doi" },
      { cite: "Anderson, S. J., & McKenzie, D. (2022). Improving business practices and the boundary of the entrepreneur: A randomized experiment comparing training, consulting, insourcing, and outsourcing. Journal of Political Economy, 130(1), 157–209.", note: "Four-arm trial in Nigeria: insourcing a specialist worker or outsourcing marketing and finance improved practices and sales as much as or more than training the owner.", link: doi("10.1086/717044"), kind: "doi" },
      { cite: "McKenzie, D., & Woodruff, C. (2013). What are we learning from business training and entrepreneurship evaluations around the developing world? The World Bank Research Observer, 29(1), 48–82.", note: "Review of business-training evaluations finding modest effects on practices and weaker, imprecise effects on profits, with most studies too small to detect them.", link: doi("10.1093/wbro/lkt007"), kind: "doi" },
      { cite: "McKenzie, D. (2021). Small business training to improve management practices in developing countries: Re-assessing the evidence for 'training doesn't work'. Oxford Review of Economic Policy, 37(2), 276–301.", note: "Reassessment pooling later trials: training raised profits by a meaningful average amount, contrary to the earlier 'training doesn't work' reading.", link: doi("10.1093/oxrep/grab002"), kind: "doi" },
      { cite: "Karlan, D., & Valdivia, M. (2011). Teaching entrepreneurship: Impact of business training on microfinance clients and institutions. Review of Economics and Statistics, 93(2), 510–527.", note: "Randomized business training for microfinance clients in Peru improved business knowledge and practices and client retention for the lender, with limited measured effect on profits.", link: doi("10.1162/REST_a_00074"), kind: "doi" },
    ],
  },
  {
    id: "gs-business-w2-personal-initiative",
    goal: "business", tier: "elite", section: "8560",
    title: "Personal-Initiative Training",
    subtitle: "The psychology-based program that beat standard business training in a Science trial",
    evidenceTag: "Strong",
    impact: { magnitude: 5, latency: "months", durability: "lasting", effort: "high" },
    feeds: ["Proactivity", "Persistence", "Goal-setting"],
    description:
      "A randomized trial with Togolese microenterprises compared a personal-initiative course (self-starting, future-oriented, persistent behavior) against a traditional business course and a control group; the initiative-trained owners raised profits substantially while the traditional course did not differ from control. An earlier German randomized field intervention with owners produced similar gains, and the underlying construct has validated measures. The boundary is that these were multi-day, facilitated programs, and US replications are thinner.",
    action: "Find or assemble a facilitated personal-initiative program (multi-day, action-based, with follow-up): set three self-started goals for your business, plan for the obstacles in writing, and act on each before being asked. Review progress monthly with the group for six months.",
    sources: [
      { cite: "Campos, F., Frese, M., Goldstein, M., Iacovone, L., Johnson, H. C., McKenzie, D., & Mensmann, M. (2017). Teaching personal initiative beats traditional training in boosting small business in West Africa. Science, 357(6357), 1287–1290.", note: "Randomized trial in Togo: personal-initiative training raised firm profits while traditional business training did not differ from control.", link: doi("10.1126/science.aan5329"), kind: "doi" },
      { cite: "Glaub, M. E., Frese, M., Fischer, S., & Hoppe, M. (2014). Increasing personal initiative in small business managers or owners leads to entrepreneurial success: A theory-based controlled randomized field intervention for evidence-based management. Academy of Management Learning & Education, 13(3), 354–379.", note: "Randomized field intervention with small business owners in Uganda in which the personal-initiative course raised initiative and business success measures.", link: doi("10.5465/amle.2013.0234"), kind: "doi" },
      { cite: "Frese, M., Fay, D., Hilburger, T., Leng, K., & Tag, A. (1997). The concept of personal initiative: Operationalization, reliability and validity in two German samples. Journal of Occupational and Organizational Psychology, 70(2), 139–161.", note: "Defines and validates personal initiative (self-starting, proactive, persistent), the construct the training targets.", link: doi("10.1111/j.2044-8325.1997.tb00639.x"), kind: "doi" },
      { cite: "Frese, M., & Gielnik, M. M. (2014). The psychology of entrepreneurship. Annual Review of Organizational Psychology and Organizational Behavior, 1(1), 413–438.", note: "Review of the psychological predictors of entrepreneurial success, placing personal initiative and action-oriented training in the wider evidence.", link: doi("10.1146/annurev-orgpsych-031413-091326"), kind: "doi" },
    ],
  },
  {
    id: "gs-business-w2-peer-group",
    goal: "business", tier: "moderate", section: "8561",
    title: "A Monthly Founder Peer Group",
    subtitle: "Randomized meetings between owners raised sales and spread good practices",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "months", durability: "lasting", effort: "moderate" },
    feeds: ["Network", "Learning from others"],
    description:
      "A randomized experiment in China assigned firm owners to monthly meetings with other owners; the meetings raised revenue, profits and the adoption of management practices, and the effects persisted after the meetings ended. Random section assignment at Harvard Business School showed that peers with entrepreneurial experience changed classmates' founding decisions, and randomized networking among African manufacturers spread information and practices. The boundary: the strongest trial was in Nanchang, and the mechanism is information plus accountability, not friendship alone.",
    action: "Join or form a group of four to eight owners in non-competing businesses that meets monthly for two hours with a fixed agenda: each member shares one number, one problem and one commitment. Attend for at least a year.",
    sources: [
      { cite: "Cai, J., & Szeidl, A. (2017). Interfirm relationships and business performance. The Quarterly Journal of Economics, 133(3), 1229–1282.", note: "Randomized monthly peer meetings among Chinese firm owners raised sales and profits and spread management practices, with effects persisting after meetings stopped.", link: doi("10.1093/qje/qjx049"), kind: "doi" },
      { cite: "Lerner, J., & Malmendier, U. (2013). With a little help from my (random) friends: Success and failure in post-business school entrepreneurship. Review of Financial Studies, 26(10), 2411–2452.", note: "Random section assignment at business school: exposure to peers with entrepreneurial backgrounds reduced unsuccessful founding attempts, consistent with peers sharing hard information.", link: doi("10.1093/rfs/hht024"), kind: "doi" },
      { cite: "Fafchamps, M., & Quinn, S. (2016). Networks and manufacturing firms in Africa: Results from a randomized field experiment. The World Bank Economic Review, lhw057.", note: "Randomized introductions among manufacturers in three African countries led to diffusion of business practices between newly connected owners.", link: doi("10.1093/wber/lhw057"), kind: "doi" },
      { cite: "Berge, L. I. O., Bjorvatn, K., & Tungodden, B. (2015). Human and financial capital for microenterprise development: Evidence from a field and lab experiment. Management Science, 61(4), 707–722.", note: "Randomized training and grants for Tanzanian microenterprises: training improved outcomes for men more than women, a reminder that group and training effects are not uniform.", link: doi("10.1287/mnsc.2014.1933"), kind: "doi" },
    ],
  },
  {
    id: "gs-business-w2-succession-plan",
    goal: "business", tier: "elite", section: "8562",
    title: "The Ten-Year Succession Plan",
    subtitle: "Family successors underperform on average; choose competence and plan early",
    evidenceTag: "Strong",
    impact: { magnitude: 5, latency: "months", durability: "lasting", effort: "high" },
    feeds: ["Legacy", "Governance"],
    description:
      "Danish register data using the gender of the founder's first child as an instrument show family CEO successions lowered firm performance relative to outside successions; US and French data find inherited control by heirs hurts performance while founder-led and family-owned firms with professional management do well. Reviews of succession research and of the factors that derail intra-family succession point to the same fixes: an explicit process started years ahead, a successor chosen and prepared for competence, and governance that lets non-family managers run things. The boundary is that these are large-company data; the direction, not the size, transfers to a small firm.",
    action: "If you intend the business to outlive you, write a succession page this year: the date you will step back, the two or three candidates (family or not), what each must demonstrate by when, and who decides. Review it every twelve months with an outside advisor.",
    sources: [
      { cite: "Bennedsen, M., Nielsen, K. M., Pérez-González, F., & Wolfenzon, D. (2007). Inside the family firm: The role of families in succession decisions and performance. The Quarterly Journal of Economics, 122(2), 647–691.", note: "Danish firms: using the first child's gender as an instrument, family CEO successions caused lower profitability than professional successions.", link: doi("10.1162/qjec.122.2.647"), kind: "doi" },
      { cite: "Pérez-González, F. (2006). Inherited control and firm performance. American Economic Review, 96(5), 1559–1588.", note: "US firms where an heir took over underperformed, especially when the heir had not attended a selective college; competence, not blood, predicted results.", link: doi("10.1257/aer.96.5.1559"), kind: "doi" },
      { cite: "Villalonga, B., & Amit, R. (2006). How do family ownership, control and management affect firm value? Journal of Financial Economics, 80(2), 385–417.", note: "Family ownership created value when the founder served as CEO or chair, and destroyed it when descendants ran the firm.", link: doi("10.1016/j.jfineco.2004.12.005"), kind: "doi" },
      { cite: "Anderson, R. C., & Reeb, D. M. (2003). Founding-family ownership and firm performance: Evidence from the S&P 500. The Journal of Finance, 58(3), 1301–1328.", note: "Founding-family firms in the S&P 500 performed at least as well as non-family firms, showing family ownership itself is not the problem; succession is.", link: doi("10.1111/1540-6261.00567"), kind: "doi" },
      { cite: "Sraer, D., & Thesmar, D. (2007). Performance and behavior of family firms: Evidence from the French stock market. Journal of the European Economic Association, 5(4), 709–751.", note: "French listed family firms, including heir-managed ones, outperformed widely held firms, in part through more stable employment; the counterweight to the US results.", link: doi("10.1162/JEEA.2007.5.4.709"), kind: "doi" },
      { cite: "Handler, W. C. (1994). Succession in family business: A review of the research. Family Business Review, 7(2), 133–157.", note: "Review of succession research emphasizing succession as a multi-year process involving founder, successor and family, not an event.", link: doi("10.1111/j.1741-6248.1994.00133.x"), kind: "doi" },
      { cite: "De Massis, A., Chua, J. H., & Chrisman, J. J. (2008). Factors preventing intra-family succession. Family Business Review, 21(2), 183–199.", note: "Catalogs the individual, relational, financial and process factors that derail planned family successions; a checklist for the plan.", link: doi("10.1111/j.1741-6248.2008.00118.x"), kind: "doi" },
    ],
  },
  {
    id: "gs-business-w2-targeted-programs",
    goal: "business", tier: "moderate", section: "8563",
    title: "Use Targeted Programs, and Know the Capital Gap Going In",
    subtitle: "What evaluations of women's and minority entrepreneurship programs show",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "months", durability: "sustained", effort: "moderate" },
    feeds: ["Access to capital", "Network"],
    description:
      "US survey data attribute much of the gap in business outcomes by race and gender to differences in startup capital, prior business experience and family business background rather than to owner effort; small-business credit data show Black-owned firms were more likely to be denied loans and charged higher rates after controlling for creditworthiness. Randomized business training for women in India raised business activity for some groups and not others, and a Ghana grant experiment found capital given to women's smaller businesses often did not grow them. The lesson is to target the specific constraint: capital, experience or networks.",
    action: "This month, apply to one program built for your group (a women's or minority business development center, a targeted lending program, or a mentored accelerator) and, before the first meeting, write down which of the three constraints (capital, experience, network) you most need it to address.",
    sources: [
      { cite: "Fairlie, R. W., & Robb, A. M. (2009). Gender differences in business performance: Evidence from the Characteristics of Business Owners survey. Small Business Economics, 33(4), 375–395.", note: "Women-owned firms had lower survival, profits and employment on average; less startup capital and less prior business experience explained much of the gap.", link: doi("10.1007/s11187-009-9207-5"), kind: "doi" },
      { cite: "Fairlie, R. W., & Robb, A. M. (2007). Why are Black-owned businesses less successful than White-owned businesses? The role of families, inheritances, and business human capital. Journal of Labor Economics, 25(2), 289–323.", note: "Lower rates of prior work experience in a family business and less startup capital accounted for a large part of the racial gap in business outcomes.", link: doi("10.1086/510763"), kind: "doi" },
      { cite: "Blanchflower, D. G., Levine, P. B., & Zimmerman, D. J. (2003). Discrimination in the small-business credit market. Review of Economics and Statistics, 85(4), 930–943.", note: "Black-owned small businesses were more likely to be denied credit and paid higher rates after controlling for creditworthiness, and were more likely not to apply for fear of denial.", link: doi("10.1162/003465303772815835"), kind: "doi" },
      { cite: "Bates, T., & Robb, A. (2013). Small-business viability in America's urban minority communities. Urban Studies, 51(13), 2844–2862.", note: "Minority-owned firms in urban minority neighborhoods faced weaker survival and profitability tied to location and capital access, not to owner characteristics alone.", link: doi("10.1177/0042098013514462"), kind: "doi" },
      { cite: "Field, E., Jayachandran, S., & Pande, R. (2010). Do traditional institutions constrain female entrepreneurship? A field experiment on business training in India. American Economic Review, 100(2), 125–129.", note: "Randomized business counseling for poor women in India raised borrowing and business activity for some caste and religious groups but not for those facing the strictest social restrictions.", link: doi("10.1257/aer.100.2.125"), kind: "doi" },
      { cite: "Fafchamps, M., McKenzie, D., Quinn, S., & Woodruff, C. (2014). Microenterprise growth and the flypaper effect: Evidence from a randomized experiment in Ghana. Journal of Development Economics, 106, 211–226.", note: "In-kind grants raised profits for many businesses but cash grants to women's smaller enterprises often did not; capital alone does not fix a constrained business.", link: doi("10.1016/j.jdeveco.2013.09.010"), kind: "doi" },
      { cite: "Jennings, J. E., & Brush, C. G. (2013). Research on women entrepreneurs: Challenges to (and from) the broader entrepreneurship literature? Academy of Management Annals, 7(1), 663–715.", note: "Review of the women's entrepreneurship literature summarizing what is known about motives, resources and performance differences.", link: doi("10.5465/19416520.2013.782190"), kind: "doi" },
    ],
  },
  {
    id: "gs-business-w2-bank-relationship",
    goal: "business", tier: "advanced", section: "8564",
    title: "Build the Bank Relationship Before You Need the Loan",
    subtitle: "Relationship lending and SBA-guaranteed loans, with the evidence on growth",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "months", durability: "lasting", effort: "moderate" },
    feeds: ["Access to capital", "Financial literacy"],
    description:
      "Small-business lending research finds that firms with longer, broader relationships with a lender get more credit at lower cost, and that new firms rely on bank debt far more than folklore about friends-and-family suggests. Matched-firm analysis of SBA-guaranteed loans found recipients added employment and survived at higher rates than similar non-recipients, and county-level data link SBA lending to local growth. The frameworks of small-business finance describe which lending technologies fit an opaque young firm. This is a description of what the studies measured, not a recommendation to borrow.",
    action: "Open the business account at a bank with a local small-business lender, meet the banker within 60 days with clean financials, and check in twice a year with updated numbers. When you consider a loan, ask specifically about SBA-guaranteed programs and compare total cost.",
    sources: [
      { cite: "Petersen, M. A., & Rajan, R. G. (1994). The benefits of lending relationships: Evidence from small business data. The Journal of Finance, 49(1), 3–37.", note: "Small firms with longer and broader lender relationships had greater credit availability, with a smaller effect on price; the founding paper on relationship lending.", link: doi("10.1111/j.1540-6261.1994.tb04418.x"), kind: "doi" },
      { cite: "Brown, J. D., & Earle, J. S. (2017). Finance and growth at the firm level: Evidence from SBA loans. The Journal of Finance, 72(3), 1039–1080.", note: "Matched analysis of SBA 7(a) and 504 loan recipients found higher employment growth after the loan than for comparable non-recipient firms.", link: doi("10.1111/jofi.12492"), kind: "doi" },
      { cite: "Craig, B. R., Jackson, W. E., & Thomson, J. B. (2007). Small firm finance, credit rationing, and the impact of SBA-guaranteed lending on local economic growth. Journal of Small Business Management, 45(1), 116–132.", note: "County-level SBA-guaranteed lending was associated with higher local employment growth, especially in low-income markets, consistent with easing credit rationing.", link: doi("10.1111/j.1540-627X.2007.00202.x"), kind: "doi" },
      { cite: "Berger, A. N., & Udell, G. F. (1998). The economics of small business finance: The roles of private equity and debt markets in the financial growth cycle. Journal of Banking & Finance, 22(6-8), 613–673.", note: "The financial growth cycle: which sources of finance fit a firm at each stage as it becomes less informationally opaque.", link: doi("10.1016/S0378-4266(98)00038-7"), kind: "doi" },
      { cite: "Berger, A. N., & Udell, G. F. (2006). A more complete conceptual framework for SME finance. Journal of Banking & Finance, 30(11), 2945–2966.", note: "Maps lending technologies (financial statements, credit scoring, asset-based, relationship) to the small firms each can serve; useful for knowing what a lender will look at.", link: doi("10.1016/j.jbankfin.2006.05.008"), kind: "doi" },
      { cite: "Robb, A. M., & Robinson, D. T. (2012). The capital structure decisions of new firms. Review of Financial Studies, 27(1), 153–179.", note: "Kauffman Firm Survey data: new firms relied heavily on formal bank debt, including owner-backed loans, rather than mainly on friends and family.", link: doi("10.1093/rfs/hhs072"), kind: "doi" },
    ],
  },
  {
    id: "gs-business-w2-crowdfunding",
    goal: "business", tier: "moderate", section: "8565",
    title: "A Crowdfunding Campaign Done the Way Successful Ones Are Done",
    subtitle: "Preparedness, network and geography decide most campaigns",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "weeks", durability: "transient", effort: "high" },
    feeds: ["Market validation", "Network"],
    description:
      "Analysis of tens of thousands of Kickstarter projects found that signals of preparedness (a video, frequent updates, no spelling errors), the founder's social network and a sensible goal predicted success, that most campaigns failed by small margins or succeeded by small margins, and that outright fraud was rare though delivery delays were common. A comparison with expert judges found crowds and experts largely agreed. Economic analyses describe the incentives, and all-or-nothing campaigns were more likely to succeed than keep-it-all ones. The boundary: crowdfunding is a launch channel and market test, not a durable funding source.",
    action: "If you run a campaign, spend the month before launch lining up the first 30% of pledges from your own network, produce a two-minute video, set an all-or-nothing goal you can justify line by line, and plan an update every week of the campaign.",
    sources: [
      { cite: "Mollick, E. (2014). The dynamics of crowdfunding: An exploratory study. Journal of Business Venturing, 29(1), 1–16.", note: "Large Kickstarter dataset: preparedness signals, network size and geography predicted success; most projects narrowly succeeded or failed, and delays were common.", link: doi("10.1016/j.jbusvent.2013.06.005"), kind: "doi" },
      { cite: "Mollick, E., & Nanda, R. (2016). Wisdom or madness? Comparing crowds with expert evaluation in funding the arts. Management Science, 62(6), 1533–1553.", note: "Crowd funding decisions for theater projects broadly agreed with expert judges, and crowd-funded projects the experts rejected did as well as others.", link: doi("10.1287/mnsc.2015.2207"), kind: "doi" },
      { cite: "Agrawal, A., Catalini, C., & Goldfarb, A. (2014). Some simple economics of crowdfunding. Innovation Policy and the Economy, 14, 63–97.", note: "Lays out the incentives of creators, funders and platforms and the information problems each faces.", link: doi("10.1086/674021"), kind: "doi" },
      { cite: "Belleflamme, P., Lambert, T., & Schwienbacher, A. (2014). Crowdfunding: Tapping the right crowd. Journal of Business Venturing, 29(5), 585–609.", note: "Model comparing pre-ordering and profit-sharing crowdfunding, showing when each is preferable depending on the amount raised and the community benefits offered.", link: doi("10.1016/j.jbusvent.2013.07.003"), kind: "doi" },
      { cite: "Cumming, D. J., Leboeuf, G., & Schwienbacher, A. (2019). Crowdfunding models: Keep-It-All vs. All-Or-Nothing. Financial Management, 49(2), 331–360.", note: "Across Indiegogo campaigns, all-or-nothing campaigns set larger goals and were more likely to reach them than keep-it-all campaigns, consistent with a credibility signal.", link: doi("10.1111/fima.12262"), kind: "doi" },
    ],
  },
  {
    id: "gs-business-w2-autonomy-audit",
    goal: "business", tier: "fundamental", section: "8566",
    title: "The Autonomy Audit — Why the Self-Employed Are Happier, and What It Costs",
    subtitle: "Higher job and life satisfaction, lower median earnings, real mental-health risks",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "months", durability: "sustained", effort: "low" },
    feeds: ["Self-knowledge", "Wellbeing"],
    description:
      "Panel data across countries show the self-employed report higher job satisfaction than employees, largely because of autonomy; matching studies find a life-satisfaction gain for those who move from paid work into self-employment (but not from unemployment), and occupation-level work finds the gain depends on the type of work. Earnings studies show the median self-employed person earns less than they would as an employee, and a review of entrepreneurs' mental health documents both higher wellbeing and elevated stress. The protocol is to know which of these you are buying.",
    action: "Each quarter, score four things for the past three months: hours worked, take-home pay versus your last salaried job, how much control you had over your day, and how many nights stress kept you up. Decide in writing whether the trade is still one you would choose.",
    sources: [
      { cite: "Benz, M., & Frey, B. S. (2008). Being independent is a great thing: Subjective evaluations of self-employment and hierarchy. Economica, 75(298), 362–383.", note: "Across countries, the self-employed reported higher job satisfaction than employees, explained by independence and autonomy rather than pay.", link: doi("10.1111/j.1468-0335.2007.00594.x"), kind: "doi" },
      { cite: "Binder, M., & Coad, A. (2012). Life satisfaction and self-employment: A matching approach. Small Business Economics, 40(4), 1009–1033.", note: "British panel data with matching: moving from regular employment into self-employment raised life satisfaction, while moving from unemployment did not.", link: doi("10.1007/s11187-011-9413-9"), kind: "doi" },
      { cite: "Binder, M., & Coad, A. (2015). How satisfied are the self-employed? A life domain view. Journal of Happiness Studies, 17(4), 1409–1433.", note: "Self-employment raised satisfaction with work but not with other life domains such as leisure or health; the gain is domain-specific.", link: doi("10.1007/s10902-015-9650-8"), kind: "doi" },
      { cite: "Hessels, J., Arampatzi, E., van der Zwan, P., & Burger, M. (2017). Life satisfaction and self-employment in different types of occupations. Applied Economics Letters, 25(11), 734–740.", note: "The life-satisfaction premium of self-employment varied by occupation type, larger in some kinds of work than others.", link: doi("10.1080/13504851.2017.1361003"), kind: "doi" },
      { cite: "Stephan, U. (2018). Entrepreneurs' mental health and well-being: A review and research agenda. Academy of Management Perspectives, 32(3), 290–322.", note: "Review of studies on entrepreneurs' mental health finding both higher wellbeing on some measures and elevated stress and strain on others.", link: doi("10.5465/amp.2017.0001"), kind: "doi" },
      { cite: "Hamilton, B. H. (2000). Does entrepreneurship pay? An empirical analysis of the returns to self-employment. Journal of Political Economy, 108(3), 604–631.", note: "US panel data: most self-employed people earned less than they would have as employees, implying they accept lower pay for nonpecuniary benefits.", link: doi("10.1086/262131"), kind: "doi" },
      { cite: "Blanchflower, D. G., & Oswald, A. J. (1998). What makes an entrepreneur? Journal of Labor Economics, 16(1), 26–60.", note: "Access to capital (including inheritances) predicted becoming self-employed, and the self-employed reported higher job and life satisfaction.", link: doi("10.1086/209881"), kind: "doi" },
    ],
  },
  {
    id: "gs-business-w2-gig-bridge",
    goal: "business", tier: "fundamental", section: "8567",
    title: "Gig Work as a Bridge, With Eyes Open",
    subtitle: "Flexibility is real and valued; so is algorithmic control and thin earnings",
    evidenceTag: "Mixed",
    impact: { magnitude: 2, latency: "days", durability: "transient", effort: "low" },
    feeds: ["Cash-flow bridging", "Self-knowledge"],
    description:
      "Studies of Uber drivers find most work part-time and value schedule flexibility highly, and a structural estimate puts a large dollar value on that flexibility. Survey work finds alternative work arrangements grew modestly over two decades, and qualitative research on remote gig platforms documents both autonomy and the strain of algorithmic control, insecurity and long hours. The honest reading is that gig work can fund a launch or test a service, and that it is not itself a business with equity.",
    action: "If you use gig platforms while starting a business, cap it at a written number of hours per week, track net hourly earnings after expenses monthly, and set the date by which the business must replace that income.",
    sources: [
      { cite: "Hall, J. V., & Krueger, A. B. (2017). An analysis of the labor market for Uber's driver-partners in the United States. ILR Review, 71(3), 705–732.", note: "Survey and administrative data on Uber drivers: most drove part-time, many alongside other work, and cited flexibility as the main reason.", link: doi("10.1177/0019793917717222"), kind: "doi" },
      { cite: "Chen, M. K., Chevalier, J. A., Rossi, P. E., & Oehlsen, E. (2019). The value of flexible work: Evidence from Uber drivers. Journal of Political Economy, 127(6), 2735–2794.", note: "Estimated that drivers placed a substantial value on hour-by-hour flexibility relative to fixed schedules at the same wage.", link: doi("10.1086/702171"), kind: "doi" },
      { cite: "Katz, L. F., & Krueger, A. B. (2018). The rise and nature of alternative work arrangements in the United States, 1995–2015. ILR Review, 72(2), 382–416.", note: "Survey evidence on the growth and composition of contract, temp and gig work over two decades.", link: doi("10.1177/0019793918820008"), kind: "doi" },
      { cite: "Wood, A. J., Graham, M., Lehdonvirta, V., & Hjorth, I. (2018). Good gig, bad gig: Autonomy and algorithmic control in the global gig economy. Work, Employment and Society, 33(1), 56–75.", note: "Interviews and surveys with remote gig workers documenting autonomy and flexibility alongside low pay, insecurity, overwork and rating-driven control.", link: doi("10.1177/0950017018785616"), kind: "doi" },
    ],
  },
  {
    id: "gs-business-w2-exit-design",
    goal: "business", tier: "elite", section: "8568",
    title: "Design the Exit From the Start",
    subtitle: "Closure is not failure, and exit routes are chosen years before they happen",
    evidenceTag: "Moderate",
    impact: { magnitude: 4, latency: "months", durability: "lasting", effort: "high" },
    feeds: ["Legacy", "Financial planning"],
    description:
      "Census data show a large share of businesses that close were successful at closure, so exit and failure are distinct; theory and survey work on entrepreneurial exit distinguish sale, succession, liquidation and other routes and find founders' intended route relates to their experience, age and the firm's characteristics. Founders who think about exit early make different investment and hiring choices. The boundary is that most of this research is descriptive; it maps the choices rather than proving one route pays better.",
    action: "Write a one-page exit thesis this year: the route you intend (sell to a buyer, hand to a successor, wind down profitably), the number that would make you take it, and the three things the business must have (documented systems, a manager who is not you, clean books) to be worth that number. Revisit it annually.",
    sources: [
      { cite: "Headd, B. (2003). Redefining business success: Distinguishing between closure and failure. Small Business Economics, 21(1), 51–61.", note: "US Census business data: a substantial share of firms that closed reported being successful at closure, separating exit from failure.", link: doi("10.1023/A:1024433630958"), kind: "doi" },
      { cite: "DeTienne, D. R. (2010). Entrepreneurial exit as a critical component of the entrepreneurial process: Theoretical development. Journal of Business Venturing, 25(2), 203–215.", note: "Theory of exit as part of the entrepreneurial process, arguing that intended exit shapes decisions long before it occurs.", link: doi("10.1016/j.jbusvent.2008.05.004"), kind: "doi" },
      { cite: "Wennberg, K., Wiklund, J., DeTienne, D. R., & Cardon, M. S. (2010). Reconceptualizing entrepreneurial exit: Divergent exit routes and their drivers. Journal of Business Venturing, 25(4), 361–375.", note: "Swedish data distinguishing harvest sales, distress sales, harvest liquidations and distress liquidations, with different drivers for each.", link: doi("10.1016/j.jbusvent.2009.01.001"), kind: "doi" },
      { cite: "DeTienne, D. R., & Cardon, M. S. (2010). Impact of founder experience on exit intentions. Small Business Economics, 38(4), 351–374.", note: "Founders' prior experience, education and age were related to which exit route (sale, succession, liquidation) they intended.", link: doi("10.1007/s11187-010-9284-5"), kind: "doi" },
      { cite: "DeTienne, D. R., McKelvie, A., & Chandler, G. N. (2015). Making sense of entrepreneurial exit strategies: A typology and test. Journal of Business Venturing, 30(2), 255–272.", note: "A tested typology of exit strategies (financial harvest, stewardship, voluntary cessation) with the founder and firm characteristics associated with each.", link: doi("10.1016/j.jbusvent.2014.07.007"), kind: "doi" },
    ],
  },
];
