// Goal shelf: DEBT — wave 2 (sections 8250–8268). Widens the wave-1 debt shelf.
// Verification: every DOI below was resolved against the Crossref record
// (api.crossref.org) on 2026-09-11. See ../types.ts for the contract.
import { doi, type GoalShelfCluster } from "../types";

export const SECTIONS: Record<string, string> = {
  "8250": "Cash, Envelopes & the Pain of Paying",
  "8251": "Automation, Savings Apps & Precommitment",
  "8252": "Income Volatility & Smoothing",
  "8253": "Emergency Savings & Hardship",
  "8254": "Payday Loans, Earned Wage Access & Buy-Now-Pay-Later — Honest Verdict",
  "8255": "Card Interest, Balance Transfers & Minimum Payments",
  "8256": "Credit Counseling & Debt Management Plans",
  "8257": "Money Talk with a Partner & Financial Infidelity",
  "8258": "Financial Shame & Help-Seeking",
  "8259": "Scarcity, Financial Stress & Work Productivity",
  "8260": "Gambling & Debt",
  "8261": "Subscriptions & Unused Memberships",
  "8262": "Car Loans, Long Terms & Negative Equity",
  "8263": "Tax Refunds as a Saving Moment",
  "8264": "401(k) Loans & Hardship Withdrawals",
  "8265": "Co-Signing & Guaranteeing Loans",
  "8266": "Medical Bills, Charity Care & Negotiation",
  "8267": "Benefits Take-Up — EITC & SNAP",
  "8268": "Savings Groups, ROSCAs & Peer Accountability",
};

export const CLUSTERS: GoalShelfCluster[] = [
  {
    id: "gs-debt-w2-cash-envelopes",
    goal: "debt", tier: "fundamental", section: "8250",
    title: "Pay Discretionary Spending in Cash from Labeled Envelopes",
    subtitle: "Make the pain of paying visible again — the credit-card effect works against you",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "low" },
    feeds: ["Spending awareness", "Impulse control", "Budget adherence"],
    description:
      "A long line of consumer research shows that paying by card blunts the felt cost of a purchase: people bid more, spend more and remember past spending less accurately than when cash leaves their hand. Mental budgeting research adds that money assigned to a labeled category is treated as less fungible, so a physical envelope becomes a hard category limit. The boundary: envelopes work on discretionary categories (groceries, eating out, fun), not on fixed bills, and the effect fades if you refill an empty envelope from a card.",
    action: "This month withdraw your discretionary budget in cash on payday and split it into three or four labeled envelopes; when an envelope is empty, that category is closed until next payday. Track how often you hit empty.",
    sources: [
      { cite: "Prelec, D., & Simester, D. (2001). Always leave home without it: A further investigation of the credit-card effect on willingness to pay. Marketing Letters, 12(1), 5–12.", note: "Experimental auctions found willingness to pay was higher when participants expected to pay by credit card rather than cash — the 'credit-card premium' the envelope method removes.", link: doi("10.1023/a:1008196717017"), kind: "doi" },
      { cite: "Raghubir, P., & Srivastava, J. (2008). Monopoly money: The effect of payment coupling and form on spending behavior. Journal of Experimental Psychology: Applied, 14(3), 213–225.", note: "Across experiments, less transparent payment forms (cards, gift certificates) were treated like play money and increased spending relative to cash of the same value.", link: doi("10.1037/1076-898x.14.3.213"), kind: "doi" },
      { cite: "Soman, D. (2001). Effects of payment mechanism on spending behavior: The role of rehearsal and immediacy of payments. Journal of Consumer Research, 27(4), 460–474.", note: "Payment mechanisms that make the outflow immediate and rehearsed (writing an amount, handing over cash) reduced subsequent spending compared with cards.", link: doi("10.1086/319621"), kind: "doi" },
      { cite: "Prelec, D., & Loewenstein, G. (1998). The red and the black: Mental accounting of savings and debt. Marketing Science, 17(1), 4–28.", note: "Introduced the pain-of-paying framework: prepayment and cash 'couple' consumption to its cost, while deferred card payment decouples them and makes borrowing feel cheaper than it is.", link: doi("10.1287/mksc.17.1.4"), kind: "doi" },
      { cite: "Heath, C., & Soll, J. B. (1996). Mental budgeting and consumer decisions. Journal of Consumer Research, 23(1), 40–52.", note: "Consumers set budgets for categories and then track expenses against them; once a category budget is reached, further spending in that category is suppressed — the mechanism envelopes make physical.", link: doi("10.1086/209465"), kind: "doi" },
      { cite: "Thaler, R. H. (1990). Anomalies: Saving, fungibility, and mental accounts. Journal of Economic Perspectives, 4(1), 193–205.", note: "Reviewed the evidence that households treat money in different mental accounts as non-fungible, which is why earmarking cash for a purpose changes what gets spent.", link: doi("10.1257/jep.4.1.193"), kind: "doi" },
      { cite: "Cheema, A., & Soman, D. (2006). Malleable mental accounting: The effect of flexibility on the justification of attractive spending and consumption decisions. Journal of Consumer Psychology, 16(1), 33–44.", note: "Showed the weakness of envelopes: when an expense can plausibly fit more than one category, people reassign it to justify spending — so keep category definitions unambiguous.", link: doi("10.1207/s15327663jcp1601_6"), kind: "doi" },
    ],
  },
  {
    id: "gs-debt-w2-automate-saving",
    goal: "debt", tier: "fundamental", section: "8251",
    title: "Automate the Transfer — Defaults, Round-Ups and Goal Apps",
    subtitle: "Inertia is the strongest force in household finance; point it at saving",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "weeks", durability: "lasting", effort: "low" },
    feeds: ["Consistency", "Savings rate", "Cash-flow buffer"],
    description:
      "The best-replicated result in behavioral finance is that what happens by default happens: automatic enrollment and automatic escalation raise participation and contribution rates far more than education does. Newer work on fintech goal-setting and round-up apps finds that users who set a specific savings goal inside an app save more, and that the effect is driven by the goal plus the automatic mechanism rather than by the app alone. The honest boundary is that round-ups are small; the transfer size, not the gimmick, determines the outcome.",
    action: "Set one automatic transfer to a separate savings account for the day after each payday, sized so you notice it (start at 3–5% of take-home) and raise it by 1% every quarter; if you use a round-up app, set a named goal inside it.",
    sources: [
      { cite: "Madrian, B. C., & Shea, D. F. (2001). The power of suggestion: Inertia in 401(k) participation and savings behavior. The Quarterly Journal of Economics, 116(4), 1149–1187.", note: "Switching a plan to automatic enrollment sharply raised participation and left most employees at the default contribution rate and fund — the canonical demonstration that defaults drive saving.", link: doi("10.1162/003355301753265543"), kind: "doi" },
      { cite: "Thaler, R. H., & Benartzi, S. (2004). Save More Tomorrow: Using behavioral economics to increase employee saving. Journal of Political Economy, 112(S1), S164–S187.", note: "Employees who precommitted to automatic contribution increases at future raises stayed enrolled and raised their saving rates substantially over several years.", link: doi("10.1086/380085"), kind: "doi" },
      { cite: "Gargano, A., & Rossi, A. G. (2024). Goal setting and saving in the FinTech era. The Journal of Finance, 79(3), 1931–1976.", note: "Using data from a savings app, setting a concrete savings goal increased saving; the study is the closest peer-reviewed evidence on the app-based micro-saving tools members actually use.", link: doi("10.1111/jofi.13339"), kind: "doi" },
      { cite: "Karlan, D., McConnell, M., Mullainathan, S., & Zinman, J. (2016). Getting to the top of mind: How reminders increase saving. Management Science, 62(12), 3393–3411.", note: "Randomized reminder messages tied to a named goal raised savings deposits, supporting the practice of naming the automatic transfer after its purpose.", link: doi("10.1287/mnsc.2015.2296"), kind: "doi" },
      { cite: "Despard, M., Grinstein-Weiss, M., deRuyter, A., Guo, S., Oliphant, J. E., & Friedline, T. (2018). Effects of a randomized tax-time savings intervention on savings account ownership among low- and moderate-income households. Journal of Financial Counseling and Planning, 29(2), 219–233.", note: "A randomized prompt at tax filing increased savings-account ownership among low- and moderate-income filers, showing that a one-click deposit choice at a cash moment moves behavior.", link: doi("10.1891/1052-3073.29.2.219"), kind: "doi" },
    ],
  },
  {
    id: "gs-debt-w2-precommitment",
    goal: "debt", tier: "moderate", section: "8251",
    title: "Pay Yourself First with a Locked Account and a Written Commitment",
    subtitle: "Tie yourself to the mast: restricted-access saving beats willpower",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "months", durability: "sustained", effort: "moderate" },
    feeds: ["Self-control", "Goal follow-through"],
    description:
      "Field experiments show that people who choose accounts they cannot easily withdraw from — until a date or a target balance — accumulate more than people with ordinary accounts, and that simply providing a safe, labeled place to put money raises saving. A large tax-time experiment found that asking filers to precommit to a deposit before the refund arrived raised deposits. The boundary: commitment products help people who already want to save and know they are tempted; they do not help households whose income genuinely cannot cover essentials.",
    action: "Open a savings account with no debit card that requires a transfer to access, write a one-line commitment ('I move $X on payday until the balance is $Y'), and sign it with a witness; review the balance once a month, not daily.",
    sources: [
      { cite: "Ashraf, N., Karlan, D., & Yin, W. (2006). Tying Odysseus to the mast: Evidence from a commitment savings product in the Philippines. The Quarterly Journal of Economics, 121(2), 635–672.", note: "Randomized offer of a savings account restricted until a goal date or amount raised balances, with the largest take-up among people who showed present-biased preferences.", link: doi("10.1162/qjec.2006.121.2.635"), kind: "doi" },
      { cite: "Dupas, P., & Robinson, J. (2013). Why don't the poor save more? Evidence from health savings experiments. American Economic Review, 103(4), 1138–1171.", note: "Providing a simple labeled, safe place to save — a lockbox or earmarked account — increased saving for health expenses, showing that the container matters even without interest.", link: doi("10.1257/aer.103.4.1138"), kind: "doi" },
      { cite: "Roll, S., Grinstein-Weiss, M., Gallagher, E., & Cryder, C. (2020). Can pre-commitment increase savings deposits? Evidence from a tax-time field experiment. Journal of Economic Behavior & Organization, 180, 357–380.", note: "Asking low- and moderate-income filers to commit to a refund deposit before filing increased deposits relative to asking at the moment of the refund.", link: doi("10.1016/j.jebo.2020.10.011"), kind: "doi" },
      { cite: "Karlan, D., McConnell, M., Mullainathan, S., & Zinman, J. (2016). Getting to the top of mind: How reminders increase saving. Management Science, 62(12), 3393–3411.", note: "Reminders that mentioned the saver's own stated goal were the most effective at increasing deposits toward commitment savings targets.", link: doi("10.1287/mnsc.2015.2296"), kind: "doi" },
      { cite: "Thaler, R. H., & Benartzi, S. (2004). Save More Tomorrow: Using behavioral economics to increase employee saving. Journal of Political Economy, 112(S1), S164–S187.", note: "Precommitting today to a future increase, when the increase does not yet hurt, is the design principle behind pay-yourself-first plans that survive.", link: doi("10.1086/380085"), kind: "doi" },
    ],
  },
  {
    id: "gs-debt-w2-income-volatility",
    goal: "debt", tier: "fundamental", section: "8252",
    title: "Smooth a Lumpy Income — Budget on the Low Month, Bank the High One",
    subtitle: "Month-to-month swings, not just low income, are what push households into debt",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "months", durability: "sustained", effort: "moderate" },
    feeds: ["Cash-flow stability", "Overdraft avoidance"],
    description:
      "Financial-diary and administrative studies show that many US households experience large month-to-month income swings from variable hours, gig work and irregular pay, and that spells in and out of poverty often track those swings rather than annual income. Economists find households only partially insure against income shocks, so a spike month spent as if permanent becomes next month's card balance. The evidence supports budgeting from a conservative baseline month and parking the surplus of good months in a buffer account rather than treating it as a raise.",
    action: "Look at your last 12 months of take-home pay, find the second-lowest month, and build next month's budget on that number; route anything above it into a separate 'smoothing' account you draw from only in low months.",
    sources: [
      { cite: "Morduch, J., & Siwicki, J. (2017). In and out of poverty: Episodic poverty and income volatility in the US Financial Diaries. Social Service Review, 91(3), 390–421.", note: "Month-level diaries of US households showed large within-year income swings and episodic poverty spells that annual measures hide — the case for month-by-month buffering.", link: doi("10.1086/694180"), kind: "doi" },
      { cite: "Dynan, K., Elmendorf, D., & Sichel, D. (2012). The evolution of household income volatility. The B.E. Journal of Economic Analysis & Policy, 12(2).", note: "Documented a rise in household income volatility in the United States over recent decades, with large drops becoming more common.", link: doi("10.1515/1935-1682.3347"), kind: "doi" },
      { cite: "Hardy, B., & Ziliak, J. P. (2013). Decomposing trends in income volatility: The 'wild ride' at the top and bottom. Economic Inquiry, 52(1), 459–476.", note: "Found income volatility highest at the bottom and top of the distribution, so low-income households face the largest swings relative to their means.", link: doi("10.1111/ecin.12044"), kind: "doi" },
      { cite: "Blundell, R., Pistaferri, L., & Preston, I. (2008). Consumption inequality and partial insurance. American Economic Review, 98(5), 1887–1921.", note: "Households only partially insure consumption against income shocks, and least against permanent shocks — private buffers are the main protection that exists.", link: doi("10.1257/aer.98.5.1887"), kind: "doi" },
      { cite: "Lusardi, A., Schneider, D., & Tufano, P. (2011). Financially fragile households: Evidence and implications. Brookings Papers on Economic Activity, 2011(1), 83–134.", note: "A large share of US households reported they could not come up with a modest sum within a month, and many would rely on borrowing from family or credit — the fragility a smoothing account targets.", link: doi("10.1353/eca.2011.0002"), kind: "doi" },
    ],
  },
  {
    id: "gs-debt-w2-emergency-fund",
    goal: "debt", tier: "moderate", section: "8253",
    title: "Build a Small Emergency Fund Before Attacking the Last Debts",
    subtitle: "Even a few hundred dollars of liquid savings predicts far less hardship",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "months", durability: "lasting", effort: "moderate" },
    feeds: ["Resilience", "Hardship avoidance", "Debt prevention"],
    description:
      "Studies using national surveys find that households with even modest liquid emergency savings are much less likely to skip bills, miss meals, forgo medical care or fall into new high-cost debt after a shock, and that this holds after accounting for income. The mechanism is that without a buffer every surprise becomes a card balance or payday loan. The boundary: the research identifies association and protective buffers, not a magic number; the useful practice is a first tier of one month of essential expenses, built while making at least minimum debt payments.",
    action: "Set a first emergency-fund target equal to one month of essential expenses, fund it with the automatic transfer from the shelf above, and do not touch it except for a genuine surprise; once it is full, redirect the transfer to the highest-rate debt.",
    sources: [
      { cite: "Gjertson, L. (2014). Emergency saving and household hardship. Journal of Family and Economic Issues, 37(1), 1–17.", note: "Households with emergency savings reported significantly less material hardship, and the protective association held at low income levels.", link: doi("10.1007/s10834-014-9434-z"), kind: "doi" },
      { cite: "Despard, M. R., Friedline, T., & Martin-West, S. (2020). Why do households lack emergency savings? The role of financial capability. Journal of Family and Economic Issues, 41(3), 542–557.", note: "Found that access to appropriate accounts and financial capability, not only income, explain who holds emergency savings — supporting a deliberate account-and-rule setup.", link: doi("10.1007/s10834-020-09679-8"), kind: "doi" },
      { cite: "Babiarz, P., & Robb, C. A. (2013). Financial literacy and emergency saving. Journal of Family and Economic Issues, 35(1), 40–50.", note: "Both objective and perceived financial knowledge were associated with holding emergency savings, after controlling for income and demographics.", link: doi("10.1007/s10834-013-9369-9"), kind: "doi" },
      { cite: "Lusardi, A., Schneider, D., & Tufano, P. (2011). Financially fragile households: Evidence and implications. Brookings Papers on Economic Activity, 2011(1), 83–134.", note: "Measured financial fragility as the inability to raise a modest emergency sum within a month and found it widespread, including among middle-income households.", link: doi("10.1353/eca.2011.0002"), kind: "doi" },
      { cite: "Despard, M., Grinstein-Weiss, M., deRuyter, A., Guo, S., Oliphant, J. E., & Friedline, T. (2018). Effects of a randomized tax-time savings intervention on savings account ownership among low- and moderate-income households. Journal of Financial Counseling and Planning, 29(2), 219–233.", note: "A randomized savings prompt increased account ownership, the first step toward a buffer, among low- and moderate-income filers.", link: doi("10.1891/1052-3073.29.2.219"), kind: "doi" },
      { cite: "Grinstein-Weiss, M., Cryder, C., Despard, M. R., Perantie, D. C., Oliphant, J. E., & Ariely, D. (2017). The role of choice architecture in promoting saving at tax time: Evidence from a large-scale field experiment. Behavioral Science & Policy, 3(2), 20–38.", note: "Simple changes to how the deposit choice was presented at filing raised the share of refunds saved, an easy funding route for a first emergency tier.", link: doi("10.1353/bsp.2017.0011"), kind: "doi" },
    ],
  },
  {
    id: "gs-debt-w2-payday-ewa-bnpl",
    goal: "debt", tier: "fundamental", section: "8254",
    title: "Payday Loans, Earned Wage Access and Buy-Now-Pay-Later as a Budget Tool",
    subtitle: "Honest verdict: short-term liquidity products mostly move the shortfall, and often widen it",
    evidenceTag: "Mixed",
    impact: { magnitude: 1, latency: "days", durability: "transient", effort: "low" },
    callout: "Floor-rated. The best studies of payday borrowing find more difficulty paying other bills and more overdrafts, not less; the peer-reviewed evidence on earned-wage-access apps shows engagement gains that weaken for users who pay instant-withdrawal fees; and card-linked BNPL is associated with more, not less, revolving balance. None of these is a route out of debt.",
    description:
      "Payday lending research finds that access to small-dollar loans is associated with greater difficulty paying mortgage, rent and utility bills and higher bankruptcy and overdraft rates in several designs, with some studies finding help in genuine emergencies. The one peer-reviewed study of an earned-wage-access platform found small increases in saving frequency and dashboard use, weakened among users who paid fees for instant access. UK bank data show consumers charging BNPL installments to credit cards, and a US study links BNPL access to higher overdrafts and card fees. The shelf verdict: treat these as last-resort emergency tools, not budgeting devices.",
    action: "Before using any payday, wage-advance or BNPL product this month, write down the total fee as an annualized rate and the exact date the money leaves; if you cannot name the account that will cover it, do not take it — call the biller and ask for a payment plan instead.",
    sources: [
      { cite: "Melzer, B. T. (2011). The real costs of credit access: Evidence from the payday lending market. The Quarterly Journal of Economics, 126(1), 517–555.", note: "Geographic access to payday loans was associated with greater difficulty paying mortgage, rent and utility bills and delayed medical care among low-income households.", link: doi("10.1093/qje/qjq009"), kind: "doi" },
      { cite: "Morse, A. (2011). Payday lenders: Heroes or villains? Journal of Financial Economics, 102(1), 28–44.", note: "After natural disasters, payday-lender access reduced foreclosures and some hardship — the honest counterpoint that the products can help in a true emergency.", link: doi("10.1016/j.jfineco.2011.03.022"), kind: "doi" },
      { cite: "Bhutta, N., Skiba, P. M., & Tobacman, J. (2015). Payday loan choices and consequences. Journal of Money, Credit and Banking, 47(2–3), 223–260.", note: "Matched loan applications to credit records and found applicants were already in deep financial distress, with little detectable improvement or harm on credit scores from approval.", link: doi("10.1111/jmcb.12175"), kind: "doi" },
      { cite: "Zinman, J. (2010). Restricting consumer credit access: Household survey evidence on effects around the Oregon rate cap. Journal of Banking & Finance, 34(3), 546–556.", note: "After Oregon capped payday rates, households shifted to other costly alternatives and some reported worse financial condition — cutting access alone does not solve the underlying shortfall.", link: doi("10.1016/j.jbankfin.2009.08.024"), kind: "doi" },
      { cite: "Kim, J., Yoon, S., Chung, S., & Oh, W. (2025). Working daily, paid monthly? Effects of on-demand wage access on the financial engagement of low-wage workers. Information Systems Research.", note: "Transaction data from about 4,000 users of a US earned-wage-access platform showed monthly saving frequency up 3.7% and dashboard monitoring up 12.9% after adoption, with effects weakened among users who frequently paid instant-withdrawal fees.", link: doi("10.1287/isre.2023.0673"), kind: "doi" },
      { cite: "Guttman-Kenney, B., Firth, C., & Gathergood, J. (2023). Buy now, pay later (BNPL) ...on your credit card. Journal of Behavioral and Experimental Finance, 37, 100788.", note: "UK credit-card data showed a meaningful share of consumers paying BNPL installments with credit cards, stacking interest-bearing debt on 'interest-free' installments.", link: doi("10.1016/j.jbef.2023.100788"), kind: "doi" },
      { cite: "deHaan, E., Kim, J., Lourie, B., & Zhu, C. (2024). Buy now pay (pain?) later. Management Science, 70(8), 5586–5598.", note: "Linked BNPL use to subsequent increases in overdraft charges and credit-card interest and fees, consistent with BNPL loosening rather than tightening budgets.", link: doi("10.1287/mnsc.2022.03266"), kind: "doi" },
    ],
  },
  {
    id: "gs-debt-w2-card-rates",
    goal: "debt", tier: "moderate", section: "8255",
    title: "Shop the Rate, Ask for a Lower APR, and Pay More Than the Minimum on the Costliest Card",
    subtitle: "Card borrowers routinely leave money on the table through inattention and bad allocation",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "moderate" },
    feeds: ["Interest cost", "Repayment speed"],
    description:
      "Administrative data show wide dispersion in the rates people pay for identical credit, driven mostly by how much they shop; borrowers also tend to split repayments in proportion to balances rather than paying the highest-rate card first, and anchor on the minimum payment. Studies of teaser-rate contracts find many consumers choose the wrong contract and fail to switch when the rate rises. The evidence supports three cheap moves: shop or ask for a rate reduction, allocate extra payments to the highest APR, and set payments well above the minimum. The boundary: balance transfers only help if the old card is not re-spent and the transfer fee is below the interest saved.",
    action: "Call each card issuer this month and ask for a lower APR (mention a competing offer if you have one); then set automatic payments above the minimum on every card and direct all extra money to the single highest-APR balance until it is gone.",
    sources: [
      { cite: "Stango, V., & Zinman, J. (2015). Borrowing high versus borrowing higher: Price dispersion and shopping behavior in the U.S. credit card market. Review of Financial Studies, 29(4), 979–1006.", note: "Found large dispersion in credit-card APRs paid by similar borrowers, much of it explained by how much they shopped — the direct case for rate shopping and asking.", link: doi("10.1093/rfs/hhv072"), kind: "doi" },
      { cite: "Agarwal, S., Chomsisengphet, S., Liu, C., & Souleles, N. S. (2015). Do consumers choose the right credit contracts? Review of Corporate Finance Studies, 4(2), 239–257.", note: "Given a choice between a fee-plus-low-rate card and a no-fee higher-rate card, many consumers chose wrongly for their borrowing pattern, though some switched after learning.", link: doi("10.1093/rcfs/cfv003"), kind: "doi" },
      { cite: "Ponce, A., Seira, E., & Zamarripa, G. (2017). Borrowing on the wrong credit card? Evidence from Mexico. American Economic Review, 107(4), 1335–1361.", note: "Cardholders with two cards borrowed substantially on the higher-rate card when the cheaper one had room, paying avoidable interest.", link: doi("10.1257/aer.20120273"), kind: "doi" },
      { cite: "Gathergood, J., Mahoney, N., Stewart, N., & Weber, J. (2019). How do individuals repay their debt? The balance-matching heuristic. American Economic Review, 109(3), 844–875.", note: "Borrowers repaid cards in proportion to balances rather than by interest rate, a costly heuristic the highest-APR-first rule corrects.", link: doi("10.1257/aer.20180288"), kind: "doi" },
      { cite: "Keys, B. J., & Wang, J. (2019). Minimum payments and debt paydown in consumer credit cards. Journal of Financial Economics, 131(3), 528–548.", note: "A large share of cardholders pay exactly the minimum or an amount anchored to it, and disclosures that show a higher example payment shift some toward paying more.", link: doi("10.1016/j.jfineco.2018.09.009"), kind: "doi" },
      { cite: "Gathergood, J., Sakaguchi, H., Stewart, N., & Weber, J. (2021). How do consumers avoid penalty fees? Evidence from credit cards. Management Science, 67(4).", note: "Consumers who set up automatic payments avoided late fees far more reliably than those paying manually, supporting autopay above the minimum.", link: doi("10.1287/mnsc.2019.3568"), kind: "doi" },
      { cite: "Agarwal, S., Chomsisengphet, S., Mahoney, N., & Stroebel, J. (2014). Regulating consumer financial products: Evidence from credit cards. The Quarterly Journal of Economics, 130(1), 111–164.", note: "Documented the size of fees and interest borne by card borrowers and how regulation reduced fee costs, useful context for what a rate request can recover.", link: doi("10.1093/qje/qju037"), kind: "doi" },
    ],
  },
  {
    id: "gs-debt-w2-counseling-dmp",
    goal: "debt", tier: "elite", section: "8256",
    title: "Nonprofit Credit Counseling and a Multi-Year Debt Management Plan",
    subtitle: "Consolidate through a counselor, not a new loan, when balances outrun cash flow",
    evidenceTag: "Moderate",
    impact: { magnitude: 4, latency: "months", durability: "lasting", effort: "high" },
    feeds: ["Debt reduction", "Credit recovery", "Financial behavior"],
    description:
      "Observational studies with credit-bureau matching find that people who complete nonprofit credit counseling reduce debt and delinquency and improve credit trajectories relative to similar non-clients, and a randomized study of distressed card borrowers found that debt relief that lowered required payments reduced later financial distress and even improved employment outcomes. Research on consolidation loans shows lenders screen on loan terms, so a new loan can be adverse-selected. The boundary: counseling evidence is mostly non-randomized; benefits concentrate among clients who follow through on plans for years.",
    action: "Book a session with a nonprofit credit counseling agency this month, bring every statement, and ask specifically whether a debt management plan would lower your total interest; if you enroll, treat the 3–5 year plan payment as a fixed bill and review progress quarterly.",
    sources: [
      { cite: "Dobbie, W., & Song, J. (2020). Targeted debt relief and the origins of financial distress: Experimental evidence from distressed credit card borrowers. American Economic Review, 110(4), 984–1018.", note: "A randomized experiment with distressed card borrowers found that relief lowering current payments reduced later distress and increased employment, supporting structured payment reduction.", link: doi("10.1257/aer.20171541"), kind: "doi" },
      { cite: "Elliehausen, G., Lundquist, E. C., & Staten, M. E. (2007). The impact of credit counseling on subsequent borrower behavior. Journal of Consumer Affairs, 41(1), 1–28.", note: "Counseled borrowers showed better subsequent credit behavior — lower balances and delinquency — than a comparison group, with the largest gains among those with the worst starting profiles.", link: doi("10.1111/j.1745-6606.2006.00066.x"), kind: "doi" },
      { cite: "Roll, S., & Moulton, S. (2019). Credit counseling and consumer credit trajectories. Economic Inquiry, 57(4), 1981–1996.", note: "Using matched credit-bureau data, counseling clients reduced revolving debt and improved credit outcomes over time relative to matched non-clients.", link: doi("10.1111/ecin.12802"), kind: "doi" },
      { cite: "Xiao, J. J., Sorhaindo, B., & Garman, E. T. (2005). Financial behaviours of consumers in credit counselling. International Journal of Consumer Studies, 30(2), 108–121.", note: "Clients who adopted recommended behaviors during counseling reported better financial outcomes, pointing to follow-through as the active ingredient.", link: doi("10.1111/j.1470-6431.2005.00455.x"), kind: "doi" },
      { cite: "Kim, J., Sorhaindo, B., & Garman, E. T. (2006). Relationship between financial stress and workplace absenteeism of credit counseling clients. Journal of Family and Economic Issues, 27(3), 458–478.", note: "Among counseling clients, financial stress was linked to workplace absenteeism, a cost that improved as financial stress fell during counseling.", link: doi("10.1007/s10834-006-9024-9"), kind: "doi" },
      { cite: "Hertzberg, A., Liberman, A., & Paravisini, D. (2018). Screening on loan terms: Evidence from maturity choice in consumer credit. The Review of Financial Studies, 31(9), 3532–3567.", note: "Consumer lenders use maturity choice to screen borrowers; those who select longer-term consolidation loans are riskier — a caution before consolidating with a new loan.", link: doi("10.1093/rfs/hhy024"), kind: "doi" },
    ],
  },
  {
    id: "gs-debt-w2-money-talk",
    goal: "debt", tier: "fundamental", section: "8257",
    title: "A Weekly 20-Minute Money Conversation with Your Partner",
    subtitle: "Financial secrecy and money arguments predict divorce more than the balances themselves",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "low" },
    feeds: ["Relationship trust", "Shared budgeting", "Conflict reduction"],
    description:
      "National panel data show money arguments are among the strongest predictors of later divorce, and consumer research documents financial infidelity — hiding purchases, accounts or debt — as a distinct behavior that damages both finances and relationship well-being, especially when one partner hides more than the other. Financial stress erodes marital satisfaction through perceived unfairness and secrecy rather than through income alone. The evidence supports short, regular, low-stakes conversations that make both partners' spending visible before it becomes a confrontation.",
    action: "Put a recurring 20-minute 'money date' on the calendar each week; each partner shows last week's spending, names one upcoming expense, and asks one question — no blame, no decisions larger than $100 in the meeting.",
    sources: [
      { cite: "Garbinsky, E. N., Gladstone, J. J., Nikolova, H., & Olson, J. G. (2019). Love, lies, and money: Financial infidelity in romantic relationships. Journal of Consumer Research, 47(1), 1–24.", note: "Defined and measured financial infidelity, showing that concealing spending and accounts is common, predicts worse relationship outcomes, and is reduced when partners expect disclosure.", link: doi("10.1093/jcr/ucz052"), kind: "doi" },
      { cite: "Nikolova, H., Olson, J. G., & Gladstone, J. J. (2026). Financial infidelity asymmetry predicts couples' financial and relationship well-being. International Journal of Research in Marketing, 43(2), 362–382.", note: "In couples data, an imbalance in how much each partner hides financially predicted lower financial and relationship well-being — the case for symmetric, regular disclosure.", link: doi("10.1016/j.ijresmar.2025.07.003"), kind: "doi" },
      { cite: "Dew, J., Britt, S., & Huston, S. (2012). Examining the relationship between financial issues and divorce. Family Relations, 61(4), 615–628.", note: "In a national longitudinal sample, financial disagreements were among the strongest predictors of subsequent divorce for both husbands and wives.", link: doi("10.1111/j.1741-3729.2012.00715.x"), kind: "doi" },
      { cite: "Britt, S. L., & Huston, S. J. (2012). The role of money arguments in marriage. Journal of Family and Economic Issues, 33(4), 464–476.", note: "Money arguments were associated with lower marital satisfaction independent of income, with perceived fairness of financial behavior a key pathway.", link: doi("10.1007/s10834-012-9304-5"), kind: "doi" },
      { cite: "Britt, S. L., Huston, S., & Durband, D. B. (2010). The determinants of money arguments between spouses. Journal of Financial Therapy, 1(1).", note: "Identified which financial behaviors and perceptions predict money arguments, pointing to spending transparency as a lever couples can control.", link: doi("10.4148/jft.v1i1.253"), kind: "doi" },
      { cite: "Archuleta, K. L., Britt, S. L., Tonn, T. J., & Grable, J. E. (2011). Financial satisfaction and financial stressors in marital satisfaction. Psychological Reports, 108(2), 563–576.", note: "Financial satisfaction and stressors explained a meaningful share of marital satisfaction, supporting joint financial routines as relationship maintenance.", link: doi("10.2466/07.21.pr0.108.2.563-576"), kind: "doi" },
    ],
  },
  {
    id: "gs-debt-w2-shame-help-seeking",
    goal: "debt", tier: "advanced", section: "8258",
    title: "Break the Shame Spiral — Disclose the Debt to One Person and One Professional",
    subtitle: "Shame drives avoidance, and avoidance compounds the debt",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "moderate" },
    feeds: ["Help-seeking", "Mental health", "Financial engagement"],
    description:
      "A multi-study program found that financial shame leads people to withdraw from their finances — not opening statements, not seeking help — which worsens hardship and produces more shame. Systematic reviews and panel studies link unsecured debt to depression, anxiety and worse physical health, with the relationship running partly through stress and avoidance. Counseling studies show clients who engage improve. The boundary: these are largely correlational, and disclosure helps only when it lands with someone who responds without judgment, which is why the protocol names a professional as well as a friend.",
    action: "This week tell one trusted person the actual total you owe, out loud, and book one appointment with a nonprofit counselor or financial therapist; open every statement the day it arrives for 30 days and log the number, not the feeling.",
    sources: [
      { cite: "Gladstone, J. J., Jachimowicz, J. M., Greenberg, A. E., & Galinsky, A. D. (2021). Financial shame spirals: How shame intensifies financial hardship. Organizational Behavior and Human Decision Processes, 167, 42–56.", note: "Across correlational and experimental studies, financial shame predicted withdrawal from one's finances and worse subsequent financial outcomes — a self-reinforcing spiral.", link: doi("10.1016/j.obhdp.2021.06.002"), kind: "doi" },
      { cite: "Sweet, E., Nandi, A., Adam, E. K., & McDade, T. W. (2013). The high price of debt: Household financial debt and its impact on mental and physical health. Social Science & Medicine, 91, 94–100.", note: "In a national young-adult cohort, higher debt relative to assets was associated with worse perceived stress, depressive symptoms, and blood pressure.", link: doi("10.1016/j.socscimed.2013.05.009"), kind: "doi" },
      { cite: "Richardson, T., Elliott, P., & Roberts, R. (2013). The relationship between personal unsecured debt and mental and physical health: A systematic review and meta-analysis. Clinical Psychology Review, 33(8), 1148–1162.", note: "Meta-analysis found unsecured debt was associated with higher odds of mental disorder, depression, suicidal ideation and problem drinking.", link: doi("10.1016/j.cpr.2013.08.009"), kind: "doi" },
      { cite: "Hiilamo, A. (2020). Debt matters? Mental wellbeing of older adults with household debt in England. SSM – Population Health, 12, 100658.", note: "Longitudinal English data linked household debt to lower mental wellbeing among older adults, showing the burden persists across the life course.", link: doi("10.1016/j.ssmph.2020.100658"), kind: "doi" },
      { cite: "Xiao, J. J., Sorhaindo, B., & Garman, E. T. (2005). Financial behaviours of consumers in credit counselling. International Journal of Consumer Studies, 30(2), 108–121.", note: "Counseling clients who adopted recommended behaviors reported improved financial well-being, evidence that engagement after disclosure pays off.", link: doi("10.1111/j.1470-6431.2005.00455.x"), kind: "doi" },
    ],
  },
  {
    id: "gs-debt-w2-scarcity-productivity",
    goal: "debt", tier: "fundamental", section: "8259",
    title: "Clear the Bandwidth Tax — Handle the Worst Money Worry Before Work",
    subtitle: "Financial worry measurably degrades attention and output; schedule the fix, do not carry it",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "days", durability: "sustained", effort: "low" },
    feeds: ["Focus", "Work performance", "Decision quality"],
    description:
      "Experiments show that financial worry consumes cognitive bandwidth: the same people perform worse on attention and reasoning tasks when money concerns are primed, and a field experiment found workers were measurably less productive before payday than after, with errors falling once cash arrived. Workplace studies link financial stress to lower pay satisfaction, absenteeism and performance. The practical reading is that an unresolved money problem is a work problem; putting the call or the plan first in the day returns attention to everything else.",
    action: "Each morning this month, before work, spend 10 minutes on the single most pressing money task (a call, a payment, a plan line) and write down what is now resolved; notice whether your focus for the rest of the day changes.",
    sources: [
      { cite: "Kaur, S., Mullainathan, S., Oh, S., & Schilbach, F. (2024). Do financial concerns make workers less productive? The Quarterly Journal of Economics, 140(1), 635–689.", note: "A field experiment with piece-rate workers found productivity and attention improved after earnings were paid early, indicating that financial concerns themselves reduce output.", link: doi("10.1093/qje/qjae038"), kind: "doi" },
      { cite: "Mani, A., Mullainathan, S., Shafir, E., & Zhao, J. (2013). Poverty impedes cognitive function. Science, 341(6149), 976–980.", note: "Priming financial concerns reduced cognitive performance among lower-income participants, and farmers performed worse before harvest than after — the bandwidth tax.", link: doi("10.1126/science.1238041"), kind: "doi" },
      { cite: "Shah, A. K., Mullainathan, S., & Shafir, E. (2012). Some consequences of having too little. Science, 338(6107), 682–685.", note: "Scarcity focused attention on immediate needs and led to over-borrowing in experimental tasks, explaining why debt decisions made under stress are worse.", link: doi("10.1126/science.1222426"), kind: "doi" },
      { cite: "Schilbach, F., Schofield, H., & Mullainathan, S. (2016). The psychological lives of the poor. American Economic Review, 106(5), 435–440.", note: "Reviewed evidence that poverty and financial stress tax mental bandwidth, with consequences for productivity and decision making.", link: doi("10.1257/aer.p20161101"), kind: "doi" },
      { cite: "Kim, J., & Garman, E. T. (2004). Financial stress, pay satisfaction and workplace performance. Compensation & Benefits Review, 36(1), 69–76.", note: "Workers reporting higher financial stress reported lower pay satisfaction and more work-time spent on personal financial matters.", link: doi("10.1177/0886368703261215"), kind: "doi" },
      { cite: "Kim, J., Sorhaindo, B., & Garman, E. T. (2006). Relationship between financial stress and workplace absenteeism of credit counseling clients. Journal of Family and Economic Issues, 27(3), 458–478.", note: "Financial stress predicted absenteeism among credit counseling clients, connecting household debt to lost work.", link: doi("10.1007/s10834-006-9024-9"), kind: "doi" },
    ],
  },
  {
    id: "gs-debt-w2-gambling",
    goal: "debt", tier: "moderate", section: "8260",
    title: "If Gambling Touches the Budget: Bank Blocks, Self-Exclusion and a Credit Freeze",
    subtitle: "Gambling spend predicts missed payments and payday borrowing in bank data",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "weeks", durability: "sustained", effort: "moderate" },
    feeds: ["Debt prevention", "Impulse control"],
    description:
      "Analysis of millions of UK bank accounts found that higher gambling spend predicted more missed payments, payday loans, and later adverse financial and health outcomes, in a dose-response pattern. Reviews document how gambling is financed with consumer credit and how debt problems mediate the link between problem gambling and psychological distress in young adults. Evaluations of self-exclusion find it reduces gambling and improves finances for many who use it, and researchers have called for bank-level gambling blocks. The boundary: self-exclusion is only partly enforced and works best combined with other barriers.",
    action: "If any gambling spend appears in your last three statements, this month turn on your bank's gambling-transaction block, register for the relevant self-exclusion scheme, and place a freeze on your credit reports so new credit cannot be opened impulsively.",
    sources: [
      { cite: "Muggleton, N., Parpart, P., Newall, P., Leake, D., Gathergood, J., & Stewart, N. (2021). The association between gambling and financial, social and health outcomes in big financial data. Nature Human Behaviour, 5(3), 319–326.", note: "In large-scale UK bank transaction data, higher gambling spend was associated with more missed payments, payday loans, unemployment and mortality, in a dose-response pattern.", link: doi("10.1038/s41562-020-01045-w"), kind: "doi" },
      { cite: "Swanton, T. B., & Gainsbury, S. M. (2020). Gambling-related consumer credit use and debt problems: A brief review. Current Opinion in Behavioral Sciences, 31, 21–31.", note: "Reviewed evidence that gamblers commonly finance play with credit cards and loans and that debt problems are a core gambling harm.", link: doi("10.1016/j.cobeha.2019.09.002"), kind: "doi" },
      { cite: "Oksanen, A., Savolainen, I., Sirola, A., & Kaakinen, M. (2018). Problem gambling and psychological distress: A cross-national perspective on the mediating effect of consumer debt and debt problems among emerging adults. Harm Reduction Journal, 15(1).", note: "Among young adults in several countries, consumer debt and debt problems mediated the relationship between problem gambling and psychological distress.", link: doi("10.1186/s12954-018-0251-9"), kind: "doi" },
      { cite: "Gainsbury, S. M. (2013). Review of self-exclusion from gambling venues as an intervention for problem gambling. Journal of Gambling Studies, 30(2), 229–251.", note: "Self-exclusion programs reduced gambling and improved financial and psychological outcomes for many participants, though enforcement and breaches limit the effect.", link: doi("10.1007/s10899-013-9362-0"), kind: "doi" },
      { cite: "Swanton, T. B., Gainsbury, S. M., & Blaszczynski, A. (2019). The role of financial institutions in gambling. International Gambling Studies, 19(3), 377–398.", note: "Argued from the evidence that banks can reduce gambling harm through transaction blocks and credit controls, the basis for the bank-block step.", link: doi("10.1080/14459795.2019.1575450"), kind: "doi" },
    ],
  },
  {
    id: "gs-debt-w2-subscriptions",
    goal: "debt", tier: "fundamental", section: "8261",
    title: "The Quarterly Subscription and Membership Audit",
    subtitle: "People overpay for gyms and subscriptions they do not use; inattention is the business model",
    evidenceTag: "Strong",
    impact: { magnitude: 2, latency: "days", durability: "sustained", effort: "low" },
    feeds: ["Spending awareness", "Fixed-cost reduction"],
    description:
      "The classic gym study found that members on monthly contracts attended so rarely that they paid far more per visit than the pay-per-visit price, and delayed cancelling after they stopped going. Recent work on subscriptions shows that cancellations spike when a payment card is replaced and consumers are forced to re-decide, implying much subscription revenue comes from inattention. Payment research shows the pain of a past payment fades, so sunk memberships keep renewing. A scheduled audit re-creates the forced decision.",
    action: "Once a quarter, list every recurring charge from your statements, and for each one write the date you last used it; cancel anything unused in 60 days and downgrade anything used less than monthly.",
    sources: [
      { cite: "DellaVigna, S., & Malmendier, U. (2006). Paying not to go to the gym. American Economic Review, 96(3), 694–719.", note: "Gym members on monthly contracts attended infrequently enough that per-visit costs far exceeded the pay-as-you-go option, and cancellation lagged well behind last attendance.", link: doi("10.1257/aer.96.3.694"), kind: "doi" },
      { cite: "Einav, L., Klopack, B., & Mahoney, N. (2025). Selling subscriptions. American Economic Review, 115(5), 1650–1671.", note: "Using card-replacement events that force consumers to re-enter payment details, the authors found a large share of subscriptions were cancelled when attention was forced — inattention sustains renewals.", link: doi("10.1257/aer.20231612"), kind: "doi" },
      { cite: "Gourville, J. T., & Soman, D. (1998). Payment depreciation: The behavioral effects of temporally separating payments from consumption. Journal of Consumer Research, 25(2), 160–174.", note: "The felt cost of a payment fades with time, so members use facilities most right after paying and least months later — which is when an audit should re-ask the question.", link: doi("10.1086/209533"), kind: "doi" },
      { cite: "Stango, V., & Zinman, J. (2014). Limited and varying consumer attention: Evidence from shocks to the salience of bank overdraft fees. Review of Financial Studies, 27(4), 990–1030.", note: "When fees became salient (for example after a survey question), consumers reduced avoidable fees — evidence that periodic attention to recurring charges changes behavior.", link: doi("10.1093/rfs/hhu008"), kind: "doi" },
      { cite: "Soman, D. (2001). Effects of payment mechanism on spending behavior: The role of rehearsal and immediacy of payments. Journal of Consumer Research, 27(4), 460–474.", note: "Automatic, unrehearsed payments are poorly recalled and weakly felt, which is why recurring card charges escape notice until listed.", link: doi("10.1086/319621"), kind: "doi" },
    ],
  },
  {
    id: "gs-debt-w2-car-loans",
    goal: "debt", tier: "advanced", section: "8262",
    title: "Buy the Car by Total Cost, Not Monthly Payment — and Avoid Negative Equity",
    subtitle: "Monthly-payment targeting stretches terms and leaves owners underwater",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "months", durability: "lasting", effort: "moderate" },
    feeds: ["Total interest paid", "Asset-debt balance"],
    description:
      "Auto-lending research shows borrowers focus on the monthly payment and respond by taking longer maturities rather than cheaper cars, paying much more interest; search frictions leave many borrowers with worse rates than were available nearby. Subprime auto studies find down payments strongly reduce default, and analysis of bankruptcy reform shows how negative equity — owing more than the car is worth — traps borrowers. The evidence supports fixing the total price and term first, bringing a pre-approval to the dealer, and putting enough down that the loan starts at or below the car's value.",
    action: "Before your next car purchase, get a rate quote from your own bank or credit union, set a maximum total price and a term of no more than 60 months, and put down enough that the loan balance starts below the vehicle's resale value; negotiate price only, never payment.",
    sources: [
      { cite: "Argyle, B. S., Nadauld, T. D., & Palmer, C. J. (2020). Monthly payment targeting and the demand for maturity. The Review of Financial Studies, 33(11), 5416–5462.", note: "Auto borrowers responded to rate changes by adjusting loan maturity to hit a target monthly payment, revealing payment-focused decision making that raises total cost.", link: doi("10.1093/rfs/hhaa004"), kind: "doi" },
      { cite: "Argyle, B., Nadauld, T., & Palmer, C. (2022). Real effects of search frictions in consumer credit markets. The Review of Financial Studies, 36(7), 2685–2720.", note: "Borrowers frequently accepted auto-loan rates well above those available from nearby lenders, and higher rates led to cheaper cars and more default — the cost of not shopping.", link: doi("10.1093/rfs/hhac088"), kind: "doi" },
      { cite: "Adams, W., Einav, L., & Levin, J. (2009). Liquidity constraints and imperfect information in subprime lending. American Economic Review, 99(1), 49–84.", note: "In subprime auto lending, larger down payments substantially reduced default, and demand was highly sensitive to the down payment rather than the interest rate.", link: doi("10.1257/aer.99.1.49"), kind: "doi" },
      { cite: "Chakrabarti, R., & Pattison, N. (2019). Auto credit and the 2005 bankruptcy reform: The impact of eliminating cramdowns. The Review of Financial Studies, 32(12), 4734–4766.", note: "Removing the ability to reduce an auto loan to the car's value in bankruptcy changed lending terms, illustrating how negative equity binds borrowers.", link: doi("10.1093/rfs/hhz039"), kind: "doi" },
    ],
  },
  {
    id: "gs-debt-w2-tax-refund",
    goal: "debt", tier: "moderate", section: "8263",
    title: "Split the Tax Refund Before It Arrives",
    subtitle: "Refund to Savings: the one moment each year most households hold a lump sum",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "months", durability: "sustained", effort: "low" },
    feeds: ["Emergency savings", "Debt paydown"],
    description:
      "The Refund to Savings program ran large randomized experiments inside tax-filing software and found that simple prompts, suggested percentages and precommitment before filing raised the share of refunds deposited to savings, with effects persisting months later. Earlier work on refund splitting showed that letting filers direct part of a refund to a savings account increased saving. The boundary: effects are meaningful but modest in dollars, and the decision must be made before the refund lands.",
    action: "When you file this year, decide in advance to direct a fixed share (for example 25%) of the refund to your emergency account and the rest to your highest-rate debt, using the split-deposit option on the return.",
    sources: [
      { cite: "Grinstein-Weiss, M., Russell, B. D., Gale, W. G., Key, C., & Ariely, D. (2016). Behavioral interventions to increase tax-time saving: Evidence from a national randomized trial. Journal of Consumer Affairs, 51(1), 3–26.", note: "A national randomized trial in tax software found that savings prompts and suggested deposit amounts increased refund saving among low- and moderate-income filers.", link: doi("10.1111/joca.12114"), kind: "doi" },
      { cite: "Grinstein-Weiss, M., Cryder, C., Despard, M. R., Perantie, D. C., Oliphant, J. E., & Ariely, D. (2017). The role of choice architecture in promoting saving at tax time: Evidence from a large-scale field experiment. Behavioral Science & Policy, 3(2), 20–38.", note: "Varying how the deposit choice was framed changed the share saved, showing that the default presentation of the split matters.", link: doi("10.1353/bsp.2017.0011"), kind: "doi" },
      { cite: "Roll, S., Grinstein-Weiss, M., Gallagher, E., & Cryder, C. (2020). Can pre-commitment increase savings deposits? Evidence from a tax-time field experiment. Journal of Economic Behavior & Organization, 180, 357–380.", note: "Filers asked to commit to a savings deposit before knowing their refund saved more than those asked afterward — decide the split first.", link: doi("10.1016/j.jebo.2020.10.011"), kind: "doi" },
      { cite: "Despard, M., Grinstein-Weiss, M., deRuyter, A., Guo, S., Oliphant, J. E., & Friedline, T. (2018). Effects of a randomized tax-time savings intervention on savings account ownership among low- and moderate-income households. Journal of Financial Counseling and Planning, 29(2), 219–233.", note: "The tax-time intervention raised savings account ownership, the precondition for a split deposit.", link: doi("10.1891/1052-3073.29.2.219"), kind: "doi" },
      { cite: "Beverly, S., Schneider, D., & Tufano, P. (2006). Splitting tax refunds and building savings: An empirical test. Tax Policy and the Economy, 20, 111–162.", note: "An early field test found that offering low-income filers the option to split refunds into a savings account increased saving relative to a comparison group.", link: doi("10.1086/tpe.20.20061906"), kind: "doi" },
    ],
  },
  {
    id: "gs-debt-w2-401k-loans",
    goal: "debt", tier: "advanced", section: "8264",
    title: "401(k) Loans and Hardship Withdrawals — Use the Loan Rarely, the Withdrawal Almost Never",
    subtitle: "Plan loans are cheap until you leave the job; withdrawals are permanent leakage",
    evidenceTag: "Moderate",
    impact: { magnitude: 2, latency: "months", durability: "lasting", effort: "moderate" },
    callout: "A 401(k) loan repaid on schedule costs little, but a large share of loans default when borrowers separate from the employer, converting the loan into a taxed, penalized withdrawal. Hardship and early withdrawals are a major source of permanent leakage from retirement savings. Neither is a routine debt tool.",
    description:
      "Plan-record studies show 401(k) loans are widely used, that most are repaid, but that default is common when a borrower changes jobs and the balance comes due. Tax-data studies quantify early withdrawals and leakage, which rose sharply in the Great Recession and represent a large drain relative to contributions. The honest reading: a plan loan can beat a high-rate card only if the job is stable and the repayment is automatic; a hardship withdrawal should be compared against every other option first.",
    action: "Before taking a plan loan, confirm in writing what happens to the balance if you leave the job and set repayment to payroll deduction; treat a hardship withdrawal as a last resort taken only after a counselor has reviewed alternatives.",
    sources: [
      { cite: "Lu, T. J., Mitchell, O. S., Utkus, S. P., & Young, J. A. (2017). Borrowing from the future? 401(k) plan loans and loan defaults. National Tax Journal, 70(1), 77–109.", note: "Using recordkeeper data, the authors found plan loans common and mostly repaid, but with substantial default at job separation that converts loans into taxable distributions.", link: doi("10.17310/ntj.2017.1.03"), kind: "doi" },
      { cite: "Beshears, J., Choi, J. J., Laibson, D., & Madrian, B. C. (2012). The availability and utilization of 401(k) loans. In Investigations in the Economics of Aging (pp. 145–172).", note: "Examined how loan provisions affect participation and borrowing, finding loan availability encourages contributions while borrowing is driven by liquidity needs.", link: doi("10.7208/chicago/9780226903163.003.0005"), kind: "doi" },
      { cite: "Mitchell, O. S., Utkus, S. P., & Yang, T. (2007). Turning workers into savers? Incentives, liquidity, and choice in 401(k) plan design. National Tax Journal, 60(3), 469–489.", note: "Plan features including loan access shaped saving behavior, showing liquidity provisions are a designed trade-off rather than free money.", link: doi("10.17310/ntj.2007.3.08"), kind: "doi" },
      { cite: "Argento, R., Bryant, V. L., & Sabelhaus, J. (2014). Early withdrawals from retirement accounts during the Great Recession. Contemporary Economic Policy, 33(1), 1–16.", note: "Tax data showed early withdrawals rose sharply in the recession, concentrated among households under financial stress, quantifying leakage from retirement accounts.", link: doi("10.1111/coep.12064"), kind: "doi" },
      { cite: "Goodman, L., Mortenson, J., Mackie, K., & Schramm, H. R. (2021). Leakage from retirement savings accounts in the United States. National Tax Journal, 74(3), 689–719.", note: "Comprehensive tax-record estimates of pre-retirement withdrawals showed leakage is large relative to contributions, especially among lower-income savers.", link: doi("10.1086/715819"), kind: "doi" },
    ],
  },
  {
    id: "gs-debt-w2-cosigning",
    goal: "debt", tier: "advanced", section: "8265",
    title: "Co-Signing a Loan to Help Family",
    subtitle: "Honest verdict: co-signing transfers the risk to you and can push the borrower to over-borrow",
    evidenceTag: "Emerging",
    impact: { magnitude: 1, latency: "months", durability: "lasting", effort: "low" },
    callout: "Floor-rated. Lender data show co-signers and guarantors genuinely absorb defaults — that is why lenders want them — and recent mortgage data show parental co-signing leads adult children to buy more house than they can afford. If you are working to get out of debt, do not add a contingent liability; if you must help, give a smaller gift instead.",
    description:
      "Studies of co-signed loans find that co-signers reduce lender losses because family co-signers step in and repay when the borrower falls behind — meaning the co-signer, not the lender, carries the loss. A recent study of Canadian mortgage data found parental co-signing relaxed credit constraints but led children to take on larger mortgages and more financial stress. Theory on cosigned versus group loans explains why lenders prefer the structure. For someone paying down debt, a co-signature is an unpriced loan you may have to repay.",
    action: "If asked to co-sign this year, decline the signature and, if you want to help, offer a one-time gift you can afford to lose; if you have already co-signed, get statement access and set an alert for any late payment.",
    sources: [
      { cite: "dalla Pellegrina, L., & Scollo, A. (2016). The role of borrower-cosigner kinship relations on loan default. Italian Economic Journal, 2(3), 421–444.", note: "In 2,350 microfinance loans, closely related cosigners reduced default, partly because relatives stepped in to contribute to repayment when borrowers struggled — the cosigner pays.", link: doi("10.1007/s40797-016-0039-6"), kind: "doi" },
      { cite: "Allen, J., Carmichael, K., Clark, R., Li, S., & Vincent, N. (2026). Housing affordability and parental income support: The role of mortgage co-signing. Journal of Financial Economics, 178, 104239.", note: "Canadian loan-level data showed rising parental co-signing that helped children buy earlier but incentivized them to lever up beyond what they could afford, raising financial-stress risk.", link: doi("10.1016/j.jfineco.2026.104239"), kind: "doi" },
      { cite: "Bond, P., & Rai, A. S. (2008). Cosigned vs. group loans. Journal of Development Economics, 85(1–2), 58–80.", note: "Theoretical analysis of why lenders use cosigners: the cosigner's liability substitutes for collateral and enforcement, shifting risk from lender to guarantor.", link: doi("10.1016/j.jdeveco.2006.05.006"), kind: "doi" },
    ],
  },
  {
    id: "gs-debt-w2-medical-bills",
    goal: "debt", tier: "moderate", section: "8266",
    title: "Never Pay a Hospital Bill at Face Value — Ask for Charity Care, an Itemized Bill and a Plan",
    subtitle: "Medical debt is the largest collections category, and hospitals hold unused financial assistance",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "moderate" },
    feeds: ["Debt avoidance", "Negotiation"],
    description:
      "Credit-bureau research shows medical debt is the most common type of debt in collections in the United States, concentrated in states that did not expand Medicaid, and that hospital admissions cause lasting income loss and unpaid bills even for the insured. Nonprofit hospitals receive tax exemptions in exchange for charity care that many provide at low levels, and insurance coverage measurably reduces medical debt and bankruptcy. The evidence supports asking every hospital for its financial-assistance policy, requesting an itemized bill, and negotiating an interest-free plan before a bill reaches collections.",
    action: "For any medical bill over $200, call billing before paying: ask for the itemized statement, ask whether you qualify for financial assistance or charity care under the hospital's policy, and request a zero-interest payment plan in writing.",
    sources: [
      { cite: "Kluender, R., Mahoney, N., Wong, F., & Yin, W. (2021). Medical debt in the US, 2009–2020. JAMA, 326(3), 250.", note: "Credit-record analysis found medical debt the largest source of debt in collections, concentrated in the South and in non-Medicaid-expansion states.", link: doi("10.1001/jama.2021.8694"), kind: "doi" },
      { cite: "Dobkin, C., Finkelstein, A., Kluender, R., & Notowidigdo, M. J. (2018). The economic consequences of hospital admissions. American Economic Review, 108(2), 308–352.", note: "Hospital admissions led to persistent declines in earnings and increases in unpaid medical bills and bankruptcy, especially for the uninsured.", link: doi("10.1257/aer.20161038"), kind: "doi" },
      { cite: "Bai, G., Zare, H., Eisenberg, M. D., Polsky, D., & Anderson, G. F. (2021). Analysis suggests government and nonprofit hospitals' charity care is not aligned with their favorable tax treatment. Health Affairs, 40(4), 629–636.", note: "Many nonprofit hospitals provided charity care worth less than their tax benefits, meaning financial-assistance programs exist but are underused — ask.", link: doi("10.1377/hlthaff.2020.01627"), kind: "doi" },
      { cite: "Batty, M., Gibbs, C., & Ippolito, B. (2018). Unlike medical spending, medical bills in collections decrease with patients' age. Health Affairs, 37(8), 1257–1264.", note: "Medical collections peak among younger adults despite lower spending, consistent with unpaid bills rather than illness driving the debt.", link: doi("10.1377/hlthaff.2018.0349"), kind: "doi" },
      { cite: "Batty, M., Gibbs, C., & Ippolito, B. (2022). Health insurance, medical debt, and financial well-being. Health Economics, 31(5), 689–728.", note: "Gaining insurance coverage reduced medical debt and improved broader financial well-being in credit records.", link: doi("10.1002/hec.4472"), kind: "doi" },
      { cite: "Mahoney, N. (2015). Bankruptcy as implicit health insurance. American Economic Review, 105(2), 710–746.", note: "Uninsured households with few seizable assets treated bankruptcy as implicit insurance and paid a smaller share of hospital bills — evidence hospitals routinely accept partial payment.", link: doi("10.1257/aer.20131408"), kind: "doi" },
      { cite: "Gross, T., & Notowidigdo, M. J. (2011). Health insurance and the consumer bankruptcy decision: Evidence from expansions of Medicaid. Journal of Public Economics, 95(7–8), 767–778.", note: "Medicaid expansions reduced personal bankruptcy filings, quantifying how much medical costs drive consumer insolvency.", link: doi("10.1016/j.jpubeco.2011.01.012"), kind: "doi" },
    ],
  },
  {
    id: "gs-debt-w2-benefits-takeup",
    goal: "debt", tier: "moderate", section: "8267",
    title: "Claim Every Benefit You Qualify For — EITC, SNAP and the Annual Eligibility Check",
    subtitle: "Billions go unclaimed because of confusion and hassle, not ineligibility",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "weeks", durability: "sustained", effort: "low" },
    feeds: ["Household income", "Debt prevention"],
    description:
      "Randomized IRS mailings showed that simplifying the notice and reducing perceived complexity substantially increased EITC claims among eligible non-claimants, and a SNAP experiment found that information plus application assistance roughly tripled enrollment among eligible elderly non-participants. Follow-up reminder experiments and multi-state EITC nudges show effects are real but depend on the message reaching people who can act. The boundary: nudges do not create eligibility, and take-up help works best when someone assists with the form.",
    action: "Once a year, before filing taxes, use a free eligibility screener or a VITA site to check EITC, child credits, SNAP and utility assistance; if eligible for anything, apply with assistance rather than alone.",
    sources: [
      { cite: "Bhargava, S., & Manoli, D. (2015). Psychological frictions and the incomplete take-up of social benefits: Evidence from an IRS field experiment. American Economic Review, 105(11), 3489–3529.", note: "Simplified, salient notices sent to eligible non-claimants significantly raised EITC take-up, showing that complexity and confusion — not stigma alone — suppress claims.", link: doi("10.1257/aer.20121493"), kind: "doi" },
      { cite: "Finkelstein, A., & Notowidigdo, M. J. (2019). Take-up and targeting: Experimental evidence from SNAP. The Quarterly Journal of Economics, 134(3), 1505–1556.", note: "Among elderly eligible non-participants, information alone raised SNAP enrollment and information plus application assistance raised it much more.", link: doi("10.1093/qje/qjz013"), kind: "doi" },
      { cite: "Linos, E., Prohofsky, A., Ramesh, A., Rothstein, J., & Unrath, M. (2022). Can nudges increase take-up of the EITC? Evidence from multiple field experiments. American Economic Journal: Economic Policy, 14(4), 432–452.", note: "Across several large mailing experiments, low-cost nudges produced small or no increases in EITC claiming, a sober boundary on what reminders alone can do.", link: doi("10.1257/pol.20200603"), kind: "doi" },
      { cite: "Guyton, J., Langetieg, P., Manoli, D., Payne, M., Schafer, B., & Sebastiani, M. (2017). Reminders and recidivism: Using administrative data to characterize nonfilers and conduct EITC outreach. American Economic Review, 107(5), 471–475.", note: "IRS reminder mailings to nonfilers increased filing and EITC claims, with repeated reminders needed to sustain the effect.", link: doi("10.1257/aer.p20171062"), kind: "doi" },
    ],
  },
  {
    id: "gs-debt-w2-savings-groups",
    goal: "debt", tier: "elite", section: "8268",
    title: "Join or Form a Savings Group with a Named Monitor",
    subtitle: "Peer accountability roughly doubles deposits in field experiments",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "months", durability: "lasting", effort: "high" },
    feeds: ["Consistency", "Social support", "Savings rate"],
    description:
      "Field experiments find that people who save in a group with public commitments deposit more often and accumulate more than those saving alone, and that the mechanism is monitoring and feedback rather than the group meeting itself — a simple text-message feedback system replicated most of the effect. A randomized study in India showed that assigning a savings monitor with social standing raised savings substantially. Rotating savings and credit associations (ROSCAs) formalize this in many communities. The boundary: peer information can backfire when it makes people feel behind, so the group should share progress, not rankings.",
    action: "Recruit two to four people with a similar goal, agree a weekly deposit amount and a named monitor who receives a screenshot every week, and meet monthly for 12 months; report deposits made, not balances.",
    sources: [
      { cite: "Kast, F., Meier, S., & Pomeranz, D. (2018). Saving more in groups: Field experimental evidence from Chile. Journal of Development Economics, 133, 275–294.", note: "Members assigned to self-help savings groups deposited far more often and saved more than controls, and a feedback-message treatment reproduced much of the effect without meetings.", link: doi("10.1016/j.jdeveco.2018.01.006"), kind: "doi" },
      { cite: "Breza, E., & Chandrasekhar, A. G. (2019). Social networks, reputation, and commitment: Evidence from a savings monitors experiment. Econometrica, 87(1), 175–216.", note: "Randomly assigning a savings monitor increased savings, most when the monitor was socially central, showing reputation with a known person drives follow-through.", link: doi("10.3982/ecta13683"), kind: "doi" },
      { cite: "Karlan, D., Savonitto, B., Thuysbaert, B., & Udry, C. (2017). Impact of savings groups on the lives of the poor. Proceedings of the National Academy of Sciences, 114(12), 3079–3084.", note: "Randomized evaluations across three countries found savings groups increased savings and access to credit, with modest effects on broader welfare.", link: doi("10.1073/pnas.1611520114"), kind: "doi" },
      { cite: "Beshears, J., Choi, J. J., Laibson, D., Madrian, B. C., & Milkman, K. L. (2015). The effect of providing peer information on retirement savings decisions. The Journal of Finance, 70(3), 1161–1201.", note: "Telling low savers how many peers saved more reduced their enrollment — a warning that group comparison can discourage, so share progress rather than rankings.", link: doi("10.1111/jofi.12258"), kind: "doi" },
      { cite: "Besley, T., Coate, S., & Loury, G. (1994). Rotating savings and credit associations, credit markets and efficiency. The Review of Economic Studies, 61(4), 701–719.", note: "Formal analysis of ROSCAs showing how rotating pooled contributions let members reach lump-sum goals sooner than saving alone.", link: doi("10.2307/2297915"), kind: "doi" },
    ],
  },
];
