// Goal shelf: EDUCATION & CAREER — wave 2 (sections 8750–8769). Widens the wave-1 college & career shelf.
// Verification: every DOI below was resolved against the Crossref record (api.crossref.org, works endpoint)
// on 2026-09-11; the cite text is taken from that record. See ../types.ts for the contract.

import { doi, type GoalShelfCluster } from "../types";

export const SECTIONS: Record<string, string> = {
  "8750": "Study Groups and Peer Learning — Supplemental Instruction, Peer Instruction, Small Groups",
  "8751": "Office Hours and Help-Seeking — Asking Early Is a Strategy, Not a Weakness",
  "8752": "Tutoring — The Best-Evidenced Academic Intervention There Is",
  "8753": "Summer Melt — Getting From Acceptance to the First Day of Class",
  "8754": "Developmental Education — Co-Requisite Over Remedial Sequences",
  "8755": "Online vs In-Person Courses — Who Loses Ground Online",
  "8756": "Working While Studying — Hours, Grades and Completion",
  "8757": "Student Loans — Counseling, Repayment-Plan Choice and Defaults",
  "8758": "College Major and Earnings — The Choice That Moves Lifetime Income Most",
  "8759": "College Selectivity and Earnings — What Prestige Buys, and for Whom",
  "8760": "Apprenticeships and Certificates — Credentials That Pay Without a Bachelor's",
  "8761": "Career Counseling — What the Meta-Analyses Say Works",
  "8762": "Referrals in Hiring — Why an Inside Word Changes the Odds",
  "8763": "Job Search, Unemployment and Well-Being — Structure Beats Intensity",
  "8764": "Career Adaptability — Concern, Control, Curiosity, Confidence",
  "8765": "Retraining After Displacement and for Older Workers",
  "8766": "Women and Salary Negotiation — The Evidence on Asking",
  "8767": "Job Satisfaction — Core Self-Evaluations and Job Design",
  "8768": "Commuting and Job Choice — The Stress That Doesn't Pay",
  "8769": "Myth — The One Perfect 'Dream Job'",
};

export const CLUSTERS: GoalShelfCluster[] = [
  {
    id: "gs-education-career-w2-study-groups",
    goal: "education-career", tier: "fundamental", section: "8750",
    title: "Join (or Start) a Structured Weekly Study Group for Your Hardest Course",
    subtitle: "Supplemental instruction and structured small-group learning raise grades; passive 'hangout' groups do not",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "low" },
    feeds: ["retrieval practice", "belonging", "help-seeking"],
    description:
      "Meta-analyses and systematic reviews of college peer learning — supplemental instruction sessions led by a senior student, peer instruction in lecture, and structured small-group work in STEM — consistently find higher course grades and lower failure rates than lecture alone. The active ingredient is structure: problems worked aloud, explanations to peers, and regular attendance. The boundary: most studies are quasi-experimental and self-selected attenders are more motivated, so treat the effect as real but probably smaller than the raw comparisons suggest.",
    action: "This month, attend every supplemental-instruction or peer-led session offered for your hardest course, or form a three-to-five-person group that meets weekly for 60–90 minutes to work problems aloud and quiz each other, with a rotating leader who sets the agenda.",
    sources: [
      { cite: "Dawson, P., van der Meer, J., Skalicky, J., & Cowley, K. (2014). On the Effectiveness of Supplemental Instruction. Review of Educational Research, 84(4), 609-639.", note: "Systematic review of 29 supplemental-instruction studies (2001–2010): where effect sizes on final grades could be calculated they ranged from d = 0.29 to 0.60, though heterogeneous designs limit causal claims.", link: doi("10.3102/0034654314540007"), kind: "doi" },
      { cite: "Springer, L., Stanne, M. E., & Donovan, S. S. (1999). Effects of Small-Group Learning on Undergraduates in Science, Mathematics, Engineering, and Technology: A Meta-Analysis. Review of Educational Research, 69(1), 21-51.", note: "Meta-analysis of small-group learning in undergraduate science, mathematics, engineering and technology courses reporting gains in achievement, persistence and attitudes.", link: doi("10.3102/00346543069001021"), kind: "doi" },
      { cite: "Freeman, S., Eddy, S. L., McDonough, M., Smith, M. K., Okoroafor, N., Jordt, H., & Wenderoth, M. P. (2014). Active learning increases student performance in science, engineering, and mathematics. Proceedings of the National Academy of Sciences, 111(23), 8410-8415.", note: "Meta-analysis of 225 studies: active learning raised examination performance by about half a letter grade and failure rates under traditional lecturing were 55% higher than under active learning.", link: doi("10.1073/pnas.1319030111"), kind: "doi" },
      { cite: "Bengesai, A. V., Amusa, L. B., & Dhunpath, R. (2023). A meta-analysis on the effect of formal peer learning approaches on course performance in higher education. Cogent Education, 10(1).", note: "Recent meta-analysis of formal peer-learning approaches on course performance in higher education, confirming a positive pooled effect across program types.", link: doi("10.1080/2331186x.2023.2203990"), kind: "doi" },
      { cite: "Crouch, C. H., & Mazur, E. (2001). Peer Instruction: Ten years of experience and results. American Journal of Physics, 69(9), 970-977.", note: "Ten years of peer-instruction data from Harvard physics courses: students who discuss concept questions with neighbours show larger conceptual gains than lecture cohorts.", link: doi("10.1119/1.1374249"), kind: "doi" },
    ],
  },
  {
    id: "gs-education-career-w2-office-hours",
    goal: "education-career", tier: "fundamental", section: "8751",
    title: "Go to Office Hours in the First Three Weeks, With One Specific Question",
    subtitle: "Instrumental help-seeking is what strong students do; avoiding help is driven by fear of looking incompetent",
    evidenceTag: "Moderate",
    impact: { magnitude: 2, latency: "weeks", durability: "sustained", effort: "low" },
    feeds: ["help-seeking", "faculty relationships", "self-regulated learning"],
    description:
      "A long program of educational-psychology research shows that students who seek help early and instrumentally — asking for a hint or an explanation rather than the answer — use more learning strategies and earn better grades, while students who most need help are the ones most likely to avoid asking because they fear it signals low ability. Perceptions of a mastery-oriented classroom reduce that avoidance. The boundary: these are correlational and classroom-experimental studies, not trials of 'office-hours attendance' as an intervention.",
    action: "Within the first three weeks of any course, attend one office hour with one prepared, specific question about material you attempted and could not finish; repeat every two weeks in the course you find hardest.",
    sources: [
      { cite: "Karabenick, S. A., & Knapp, J. R. (1991). Relationship of academic help seeking to the use of learning strategies and other instrumental achievement behavior in college students. Journal of Educational Psychology, 83(2), 221-230.", note: "College students who sought academic help reported greater use of learning strategies and other instrumental achievement behaviours; help-seeking clustered with effective study rather than with weakness.", link: doi("10.1037/0022-0663.83.2.221"), kind: "doi" },
      { cite: "Karabenick, S. A. (2004). Perceived Achievement Goal Structure and College Student Help Seeking. Journal of Educational Psychology, 96(3), 569-581.", note: "Perceived achievement-goal structure of the class predicted whether college students sought help; mastery-oriented classrooms encouraged instrumental help-seeking and reduced avoidance.", link: doi("10.1037/0022-0663.96.3.569"), kind: "doi" },
      { cite: "Ryan, A. M., Pintrich, P. R., & Midgley, C. (2001). Avoiding Seeking Help in the Classroom: Who and Why?. Educational Psychology Review, 13(2), 93-114.", note: "Review of who avoids seeking help in classrooms and why: threat to self-worth and perceived incompetence are the main drivers, and low achievers are the most avoidant.", link: doi("10.1023/a:1009013420053"), kind: "doi" },
      { cite: "Butler, R. (1998). Determinants of help seeking: Relations between perceived reasons for classroom help-avoidance and help-seeking behaviors in an experimental context. Journal of Educational Psychology, 90(4), 630-643.", note: "Experimental study of help-seeking determinants: perceived reasons for help-avoidance (ability concerns) predicted actual help-seeking behaviour on a task.", link: doi("10.1037/0022-0663.90.4.630"), kind: "doi" },
      { cite: "Karabenick, S. A., & Knapp, J. R. (1988). Help seeking and the need for academic assistance. Journal of Educational Psychology, 80(3), 406-408.", note: "Early study showing that the students with the greatest need for academic assistance were among the least likely to seek it.", link: doi("10.1037/0022-0663.80.3.406"), kind: "doi" },
    ],
  },
  {
    id: "gs-education-career-w2-tutoring",
    goal: "education-career", tier: "advanced", section: "8752",
    title: "Buy (or Borrow) High-Dosage Tutoring for the Course You Cannot Afford to Fail",
    subtitle: "Structured one-to-one or small-group tutoring several times a week is among the largest effects in education research",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "weeks", durability: "sustained", effort: "moderate" },
    feeds: ["mastery", "course completion", "confidence"],
    description:
      "From Bloom's 'two sigma' demonstration to the 2020 meta-analysis of randomized tutoring trials, the pattern is stable: tutoring delivered by trained tutors, in small ratios, several times a week and tied to the curriculum, produces large learning gains — larger than almost any other intervention. Most trials are in schools rather than colleges, but the college supplemental-instruction and tutoring-center literature points the same way. The boundary: dosage and tutor training drive the effect; occasional drop-in help is not the same treatment.",
    action: "For one make-or-break course this term, arrange tutoring at least twice a week for the full term — through the campus tutoring center, a trained peer tutor, or a paid tutor — and bring your graded work so every session targets a specific gap.",
    sources: [
      { cite: "Nickow, A., Oreopoulos, P., & Quan, V. (2020). The Impressive Effects of Tutoring on PreK-12 Learning: A Systematic Review and Meta-Analysis of the Experimental Evidence. NBER Working Paper 27476, National Bureau of Economic Research.", note: "Systematic review and meta-analysis of the randomized experimental evidence on tutoring in PreK–12: consistently large effects, strongest for programs with trained tutors, high frequency and curriculum alignment.", link: doi("10.3386/w27476"), kind: "doi" },
      { cite: "Bloom, B. S. (1984). The 2 Sigma Problem: The Search for Methods of Group Instruction as Effective as One-to-One Tutoring. Educational Researcher, 13(6), 4-16.", note: "Bloom's classic 'two sigma' paper: students tutored one-to-one performed about two standard deviations above conventionally taught students, setting the benchmark for group instruction.", link: doi("10.3102/0013189x013006004"), kind: "doi" },
      { cite: "Cohen, P. A., Kulik, J. A., & Kulik, C. L. C. (1982). Educational Outcomes of Tutoring: A Meta-analysis of Findings. American Educational Research Journal, 19(2), 237-248.", note: "Early meta-analysis of tutoring programs finding positive effects on tutees' achievement and attitudes, with structured programs of shorter duration showing the largest effects.", link: doi("10.3102/00028312019002237"), kind: "doi" },
      { cite: "Ritter, G. W., Barnett, J. H., Denny, G. S., & Albin, G. R. (2009). The Effectiveness of Volunteer Tutoring Programs for Elementary and Middle School Students: A Meta-Analysis. Review of Educational Research, 79(1), 3-38.", note: "Meta-analysis of volunteer tutoring programs showing positive effects on reading outcomes for elementary and middle-school students even with non-professional tutors.", link: doi("10.3102/0034654308325690"), kind: "doi" },
      { cite: "Dietrichson, J., Bøg, M., Filges, T., & Klint Jørgensen, A. M. (2017). Academic Interventions for Elementary and Middle School Students With Low Socioeconomic Status: A Systematic Review and Meta-Analysis. Review of Educational Research, 87(2), 243-282.", note: "Systematic review and meta-analysis of academic interventions for low-SES students: tutoring and feedback-based interventions were among the most effective categories.", link: doi("10.3102/0034654316687036"), kind: "doi" },
      { cite: "Guryan, J., Ludwig, J., Bhatt, M. P., Cook, P. J., Davis, J. M. V., Dodge, K., et al. (2023). Not Too Late: Improving Academic Outcomes among Adolescents. American Economic Review, 113(3), 738-765.", note: "Randomized trials of intensive, individualized in-school math tutoring for adolescents (the 'Not Too Late' program) showing substantial gains in math achievement, evidence that intensive tutoring works well beyond early childhood.", link: doi("10.1257/aer.20210434"), kind: "doi" },
    ],
  },
  {
    id: "gs-education-career-w2-summer-melt",
    goal: "education-career", tier: "moderate", section: "8753",
    title: "If You Are College-Bound, Run a Summer Checklist and Answer the Nudges",
    subtitle: "A meaningful share of accepted students never enroll; cheap summer outreach and counseling reduce that loss",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "weeks", durability: "lasting", effort: "low" },
    feeds: ["enrollment follow-through", "financial-aid completion", "parent involvement"],
    description:
      "Castleman and Page documented that many college-intending graduates, especially low-income students, 'melt' between June and September because of unfinished paperwork, unpaid deposits and unanswered aid letters. Randomized trials of summer counselor outreach, text-message reminders and even an AI chatbot raised on-time enrollment at low cost. The boundary: effects are concentrated among first-generation and low-income students with real logistical barriers, and later large-scale nudge campaigns have found smaller effects than the early trials.",
    action: "Between acceptance and move-in, keep a dated checklist of every task (deposit, FAFSA verification, orientation, housing, health forms, placement tests) and reply to every message from the college or your high-school counselor within 48 hours; ask a counselor to review the list with you in July.",
    sources: [
      { cite: "Castleman, B. L., & Page, L. C. (2013). A Trickle or a Torrent? Understanding the Extent of Summer “Melt” Among College‐Intending High School Graduates. Social Science Quarterly, 95(1), 202-220.", note: "Documents the extent of summer melt among college-intending high-school graduates, with substantial shares failing to enroll anywhere in the fall.", link: doi("10.1111/ssqu.12032"), kind: "doi" },
      { cite: "Castleman, B. L., Page, L. C., & Schooley, K. (2014). The Forgotten Summer: Does the Offer of College Counseling After High School Mitigate Summer Melt Among College-Intending, Low-Income High School Graduates?. Journal of Policy Analysis and Management, 33(2), 320-344.", note: "Experimental study of offering college counseling after high-school graduation: outreach increased on-time college enrollment among low-income, college-intending graduates.", link: doi("10.1002/pam.21743"), kind: "doi" },
      { cite: "Castleman, B. L., Arnold, K., & Wartman, K. L. (2012). Stemming the Tide of Summer Melt: An Experimental Study of the Effects of Post-High School Summer Intervention on Low-Income Students’ College Enrollment. Journal of Research on Educational Effectiveness, 5(1), 1-17.", note: "Experimental study of post-high-school summer intervention showing increased fall college enrollment for low-income students who received summer support.", link: doi("10.1080/19345747.2011.618214"), kind: "doi" },
      { cite: "Castleman, B. L., Owen, L., & Page, L. C. (2015). Stay late or start early? Experimental evidence on the benefits of college matriculation support from high schools versus colleges. Economics of Education Review, 47, 168-179.", note: "Experimental comparison of matriculation support delivered by high schools versus colleges; both helped, with implications for who should own the summer outreach.", link: doi("10.1016/j.econedurev.2015.05.010"), kind: "doi" },
      { cite: "Page, L. C., & Gehlbach, H. (2017). How an Artificially Intelligent Virtual Assistant Helps Students Navigate the Road to College. AERA Open, 3(4).", note: "Randomized test of an artificially intelligent text-message assistant that answered students' questions over the summer and increased on-time enrollment.", link: doi("10.1177/2332858417749220"), kind: "doi" },
    ],
  },
  {
    id: "gs-education-career-w2-corequisite",
    goal: "education-career", tier: "moderate", section: "8754",
    title: "Placed Into Remedial Math or English? Ask for the Co-Requisite Section",
    subtitle: "Randomized trials show students placed directly into college-level courses with support pass at higher rates than those routed through remedial prerequisites",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "months", durability: "lasting", effort: "moderate" },
    feeds: ["credit accumulation", "momentum", "completion"],
    description:
      "Traditional prerequisite remediation diverts students into non-credit courses that many never complete. A CUNY randomized trial assigned 907 students to remedial algebra, algebra with workshops, or college-level statistics with support workshops; the statistics group passed at a rate 16 percentage points higher and accumulated more credits, with gains persisting in follow-up. Regression-discontinuity studies find remediation does little to build skills and mostly delays college-level work, while placement tests misassign many students. The boundary: co-requisite support must actually be provided, and effects vary by preparation level.",
    action: "If a placement test routes you into developmental coursework, ask the advising office this week whether a co-requisite (college-level course plus mandatory support lab) section is available, and whether multiple measures such as high-school GPA can be used to reassess your placement.",
    sources: [
      { cite: "Logue, A. W., Watanabe-Rose, M., & Douglas, D. (2016). Should Students Assessed as Needing Remedial Mathematics Take College-Level Quantitative Courses Instead? A Randomized Controlled Trial. Educational Evaluation and Policy Analysis, 38(3), 578-598.", note: "Randomized controlled trial of 907 CUNY students: those assigned to college-level statistics with workshops (co-requisite remediation) passed at a rate 16 percentage points higher than those assigned to remedial algebra and subsequently accumulated more credits.", link: doi("10.3102/0162373716649056"), kind: "doi" },
      { cite: "Logue, A. W., Douglas, D., & Watanabe-Rose, M. (2019). Corequisite Mathematics Remediation: Results Over Time and in Different Contexts. Educational Evaluation and Policy Analysis, 41(3), 294-315.", note: "Follow-up of the CUNY trial over time and across institutional contexts, examining whether the co-requisite advantage persisted.", link: doi("10.3102/0162373719848777"), kind: "doi" },
      { cite: "Bettinger, E. P., & Long, B. T. (2009). Addressing the Needs of Underprepared Students in Higher Education. Journal of Human Resources, 44(3), 736-771.", note: "Quasi-experimental evidence from Ohio on whether college remediation works for underprepared students, a foundational study in the debate over remedial sequences.", link: doi("10.3368/jhr.44.3.736"), kind: "doi" },
      { cite: "Scott-Clayton, J., & Rodriguez, O. (2015). Development, Discouragement, or Diversion? New Evidence on the Effects of College Remediation Policy. Education Finance and Policy, 10(1), 4-45.", note: "Regression-discontinuity study in a large urban community-college system: remedial assignment did little to develop skills and its main effect was diversion — students took remedial rather than college-level courses.", link: doi("10.1162/edfp_a_00150"), kind: "doi" },
      { cite: "Boatman, A., & Long, B. T. (2017). Does Remediation Work for All Students? How the Effects of Postsecondary Remedial and Developmental Courses Vary by Level of Academic Preparation. Educational Evaluation and Policy Analysis, 40(1), 29-58.", note: "Shows the effects of remedial and developmental courses vary by level of academic preparation, so blanket policies help some students and harm others.", link: doi("10.3102/0162373717715708"), kind: "doi" },
      { cite: "Scott-Clayton, J., Crosta, P. M., & Belfield, C. R. (2014). Improving the Targeting of Treatment. Educational Evaluation and Policy Analysis, 36(3), 371-393.", note: "Examines placement accuracy and finds that using high-school achievement alongside test scores reduces severe misassignment to remediation.", link: doi("10.3102/0162373713517935"), kind: "doi" },
      { cite: "Jaggars, S. S., Hodara, M., Cho, S. W., & Xu, D. (2014). Three Accelerated Developmental Education Programs. Community College Review, 43(1), 3-26.", note: "Descriptive evaluation of three accelerated developmental education models, including co-requisite designs, and their effects on progression.", link: doi("10.1177/0091552114551752"), kind: "doi" },
    ],
  },
  {
    id: "gs-education-career-w2-online-vs-inperson",
    goal: "education-career", tier: "fundamental", section: "8755",
    title: "Take Gateway and Hard Courses In Person When You Have the Choice",
    subtitle: "Online sections lower grades and persistence on average, with the largest losses for less-prepared students",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "months", durability: "sustained", effort: "low" },
    feeds: ["course completion", "GPA protection", "engagement"],
    description:
      "The best-identified studies — a large for-profit university with quasi-random instructor and mode assignment, a randomized economics course, and Washington State community-college records — find that taking a course online rather than face to face reduces course grades and the chance of passing, and lowers persistence, with the gap widest for students with lower prior GPA and in quantitative subjects. Blended formats with in-person meetings do about as well as traditional instruction in randomized trials. The boundary: fully online is not 'bad'; it is a format that demands more self-regulation, which is exactly what struggling students have least of.",
    action: "When registering, put your hardest required course and any math or writing gateway course in an in-person or blended section; reserve fully online sections for courses in your strength area, and if you must go online, schedule fixed weekly work blocks as if they were class meetings.",
    sources: [
      { cite: "Bettinger, E. P., Fox, L., Loeb, S., & Taylor, E. S. (2017). Virtual Classrooms: How Online College Courses Affect Student Success. American Economic Review, 107(9), 2855-2875.", note: "Using a large for-profit university where students took the same course online or in person, online enrollment lowered course grades and reduced subsequent persistence, especially for students with lower prior achievement.", link: doi("10.1257/aer.20151193"), kind: "doi" },
      { cite: "Xu, D., & Jaggars, S. S. (2013). The impact of online learning on students’ course outcomes: Evidence from a large community and technical college system. Economics of Education Review, 37, 46-57.", note: "Washington State community and technical college data: students were less likely to complete and earned lower grades in online than in face-to-face sections of the same courses.", link: doi("10.1016/j.econedurev.2013.08.001"), kind: "doi" },
      { cite: "Xu, D., & Jaggars, S. S. (2014). Performance Gaps between Online and Face-to-Face Courses: Differences across Types of Students and Academic Subject Areas. The Journal of Higher Education, 85(5), 633-659.", note: "Performance gaps between online and face-to-face courses were larger for males, younger students, Black students and students with lower prior GPA, and in some subject areas.", link: doi("10.1080/00221546.2014.11777343"), kind: "doi" },
      { cite: "Figlio, D., Rush, M., & Yin, L. (2013). Is It Live or Is It Internet? Experimental Estimates of the Effects of Online Instruction on Student Learning. Journal of Labor Economics, 31(4), 763-784.", note: "Randomized experiment assigning students to live lectures or internet delivery of the same microeconomics course: live instruction produced better outcomes, particularly for Hispanic, male and lower-achieving students.", link: doi("10.1086/669930"), kind: "doi" },
      { cite: "Alpert, W. T., Couch, K. A., & Harmon, O. R. (2016). A Randomized Assessment of Online Learning. American Economic Review, 106(5), 378-382.", note: "Randomized assessment of online learning in a principles course finding lower outcomes for the purely online arm relative to face-to-face and blended arms.", link: doi("10.1257/aer.p20161057"), kind: "doi" },
      { cite: "Bowen, W. G., Chingos, M. M., Lack, K. A., & Nygren, T. I. (2013). Interactive Learning Online at Public Universities: Evidence from a Six‐Campus Randomized Trial. Journal of Policy Analysis and Management, 33(1), 94-111.", note: "Six-campus randomized trial of a hybrid interactive statistics course: hybrid students did about as well as those in traditional sections, showing blended formats can hold outcomes steady.", link: doi("10.1002/pam.21728"), kind: "doi" },
    ],
  },
  {
    id: "gs-education-career-w2-working-while-studying",
    goal: "education-career", tier: "fundamental", section: "8756",
    title: "Cap Paid Work Near 15 Hours a Week During Term — and Prefer On-Campus Jobs",
    subtitle: "Some work is harmless or helpful; long hours cost grades and completion, especially for full-time students",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "months", durability: "sustained", effort: "moderate" },
    feeds: ["time protection", "completion", "financial stability"],
    description:
      "Studies that deal with the fact that students who work are different from those who do not find that additional hours of paid work reduce grades among full-time students, with the harm growing as hours rise, while modest hours have small or no effects. Federal work-study participation, which caps hours and keeps students on campus, is associated with better outcomes for lower-income students than off-campus work. A review of the literature concludes that intensity and job type matter more than working per se. The boundary: for students who must work to stay enrolled, the alternative is not fewer hours but dropping out, so the practical target is the schedule, not zero.",
    action: "Set a term-time ceiling of about 15 hours a week of paid work, favour on-campus or work-study positions with fixed shifts, and put class, study blocks and sleep on the calendar before you accept shifts.",
    sources: [
      { cite: "Stinebrickner, R., & Stinebrickner, T. R. (2003). Working during School and Academic Performance. Journal of Labor Economics, 21(2), 473-491.", note: "Using Berea College's random work-study job assignments as an instrument, additional hours of work during school were found to lower academic performance.", link: doi("10.1086/345565"), kind: "doi" },
      { cite: "Darolia, R. (2014). Working (and studying) day and night: Heterogeneous effects of working on the academic performance of full-time and part-time students. Economics of Education Review, 38, 38-50.", note: "Heterogeneous effects of working on academic performance: full-time students' grades suffered with more work hours while part-time students were less affected.", link: doi("10.1016/j.econedurev.2013.10.004"), kind: "doi" },
      { cite: "Scott-Clayton, J., & Minaya, V. (2016). Should student employment be subsidized? Conditional counterfactuals and the outcomes of work-study participation. Economics of Education Review, 52, 1-18.", note: "Conditional-counterfactual analysis of federal work-study: participation improved outcomes for students who would otherwise have worked off campus, especially lower-income students.", link: doi("10.1016/j.econedurev.2015.06.006"), kind: "doi" },
      { cite: "Neyt, B., Omey, E., Verhaest, D., & Baert, S. (2018). DOES STUDENT WORK REALLY AFFECT EDUCATIONAL OUTCOMES? A REVIEW OF THE LITERATURE. Journal of Economic Surveys, 33(3), 896-921.", note: "Literature review concluding that the effect of student work on educational outcomes depends on intensity and job characteristics, with high hours the consistent risk.", link: doi("10.1111/joes.12301"), kind: "doi" },
      { cite: "Kalenkoski, C. M., & Pabilonia, S. W. (2008). Parental transfers, student achievement, and the labor supply of college students. Journal of Population Economics, 23(2), 469-496.", note: "Links parental transfers, student labour supply and achievement, showing how family support shifts the hours students work during college.", link: doi("10.1007/s00148-008-0221-8"), kind: "doi" },
    ],
  },
  {
    id: "gs-education-career-w2-student-loans",
    goal: "education-career", tier: "moderate", section: "8757",
    title: "Read the Loan Letter, Borrow to the Plan, and Choose Repayment Deliberately",
    subtitle: "Defaults, framing and complexity shape borrowing and repayment more than interest rates do",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "months", durability: "lasting", effort: "moderate" },
    feeds: ["financial literacy", "default avoidance", "borrowing discipline"],
    description:
      "Experiments show that how loan information is presented changes what students do: a debt letter shifted borrowing decisions, a nudge that removed a loan from the default aid package cut borrowing, and the framing of repayment plans altered which plan people chose. Complexity and default options push borrowers into standard repayment even when income-driven plans would prevent default, and the rise in defaults has been concentrated among non-traditional borrowers with small balances. The boundary: none of this is advice on whether to borrow; it is evidence that the decision is manipulable, so make it on paper.",
    action: "Before accepting an aid package, write down total expected debt at graduation against the typical starting salary for your major; each year, complete the required loan counseling attentively; and at exit, compare standard and income-driven repayment on the official simulator before the first payment is due.",
    sources: [
      { cite: "Darolia, R., & Harper, C. (2017). Information Use and Attention Deferment in College Student Loan Decisions: Evidence From a Debt Letter Experiment. Educational Evaluation and Policy Analysis, 40(1), 129-150.", note: "Debt-letter experiment: providing personalized loan information changed how students used information and deferred attention to borrowing decisions.", link: doi("10.3102/0162373717734368"), kind: "doi" },
      { cite: "Marx, B. M., & Turner, L. J. (2019). Student Loan Nudges: Experimental Evidence on Borrowing and Educational Attainment. American Economic Journal: Economic Policy, 11(2), 108-141.", note: "Experimental evidence that changing whether a loan appears in the default aid package altered borrowing and, in turn, educational attainment.", link: doi("10.1257/pol.20180279"), kind: "doi" },
      { cite: "Abraham, K. G., Filiz-Ozbay, E., Ozbay, E. Y., & Turner, L. J. (2020). Framing effects, earnings expectations, and the design of student loan repayment schemes. Journal of Public Economics, 183, 104067.", note: "Framing effects and earnings expectations shaped which repayment scheme people chose, informing the design of loan repayment options.", link: doi("10.1016/j.jpubeco.2019.104067"), kind: "doi" },
      { cite: "Cox, J. C., Kreisman, D., & Dynarski, S. (2020). Designed to fail: Effects of the default option and information complexity on student loan repayment. Journal of Public Economics, 192, 104298.", note: "Shows that the default option and information complexity drive repayment-plan choice, leaving many borrowers in plans that raise their risk of default.", link: doi("10.1016/j.jpubeco.2020.104298"), kind: "doi" },
      { cite: "Mueller, H. M., & Yannelis, C. (2019). The rise in student loan defaults. Journal of Financial Economics, 131(1), 1-19.", note: "Documents the rise in student loan defaults and its concentration among particular borrower groups, useful context for why plan choice matters.", link: doi("10.1016/j.jfineco.2018.07.013"), kind: "doi" },
      { cite: "Herbst, D. (2023). The Impact of Income-Driven Repayment on Student Borrower Outcomes. American Economic Journal: Applied Economics, 15(1), 1-25.", note: "Evidence on how enrolling in income-driven repayment affected borrower outcomes such as delinquency and consumption.", link: doi("10.1257/app.20200362"), kind: "doi" },
    ],
  },
  {
    id: "gs-education-career-w2-major-earnings",
    goal: "education-career", tier: "advanced", section: "8758",
    title: "Treat Major Choice as a Six-Figure Decision — Read the Earnings Evidence Before You Declare",
    subtitle: "Differences in earnings across majors are large and mostly survive corrections for ability sorting",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "months", durability: "lasting", effort: "moderate" },
    feeds: ["earnings trajectory", "informed choice", "fit"],
    description:
      "Across reviews and quasi-experimental studies, the field a student majors in explains a large share of variation in later earnings — comparable to or larger than the college-versus-no-college gap — and the differences persist after accounting for ability sorting into majors. Norwegian admission-cutoff data and Chilean cutoff data show causal payoffs to particular fields; information experiments show students hold inaccurate beliefs about major-specific earnings and update when told. The boundary: earnings are one input; interest fit (wave 1) predicts persistence, and mismatched majors are abandoned.",
    action: "Before declaring, pull the median earnings by major for your institution or state, list your top three candidate majors with their first-year and mid-career figures next to your interest-inventory results, and discuss the table with an advisor and one graduate of each major.",
    sources: [
      { cite: "Altonji, J. G., Blom, E., & Meghir, C. (2012). Heterogeneity in Human Capital Investments: High School Curriculum, College Major, and Careers. Annual Review of Economics, 4(1), 185-223.", note: "Review of heterogeneity in human-capital investments: college major is a major source of earnings variation, with returns to some fields rivalling the college premium itself.", link: doi("10.1146/annurev-economics-080511-110908"), kind: "doi" },
      { cite: "Kirkeboen, L. J., Leuven, E., & Mogstad, M. (2016). Field of Study, Earnings, and Self-Selection*. The Quarterly Journal of Economics, 131(3), 1057-1111.", note: "Using Norwegian admission cutoffs, estimates causal payoffs to field of study and shows students select into fields where they have comparative advantage.", link: doi("10.1093/qje/qjw019"), kind: "doi" },
      { cite: "Arcidiacono, P. (2004). Ability sorting and the returns to college major. Journal of Econometrics, 121(1-2), 343-375.", note: "Shows that a large part of major-related earnings differences remain after modelling ability sorting into majors.", link: doi("10.1016/j.jeconom.2003.10.010"), kind: "doi" },
      { cite: "Webber, D. A. (2014). The lifetime earnings premia of different majors: Correcting for selection based on cognitive, noncognitive, and unobserved factors. Labour Economics, 28, 14-23.", note: "Estimates lifetime earnings premia of different majors correcting for selection on cognitive, non-cognitive and unobserved factors.", link: doi("10.1016/j.labeco.2014.03.009"), kind: "doi" },
      { cite: "Altonji, J., Arcidiacono, P., & Maurel, A. (2016). The Analysis of Field Choice in College and Graduate School. Handbook of the Economics of Education, 305-396.", note: "Handbook chapter synthesising the economics of field choice in college and graduate school, including returns and the role of preferences and information.", link: doi("10.1016/b978-0-444-63459-7.00007-5"), kind: "doi" },
      { cite: "Wiswall, M., & Zafar, B. (2014). Determinants of College Major Choice: Identification using an Information Experiment. The Review of Economic Studies, 82(2), 791-824.", note: "Information experiment: students' beliefs about major-specific earnings were inaccurate and providing information changed their intended majors.", link: doi("10.1093/restud/rdu044"), kind: "doi" },
      { cite: "Stinebrickner, R., & Stinebrickner, T. R. (2013). A Major in Science? Initial Beliefs and Final Outcomes for College Major and Dropout. The Review of Economic Studies, 81(1), 426-472.", note: "Longitudinal data on initial beliefs and final outcomes for college major and dropout, showing many students leave science majors after learning about their grades and interests.", link: doi("10.1093/restud/rdt025"), kind: "doi" },
      { cite: "Hastings, J., Neilson, C., & Zimmerman, S. (2013). Are Some Degrees Worth More than Others? Evidence from college admission cutoffs in Chile. NBER Working Paper 19241, National Bureau of Economic Research.", note: "Chilean college admission cutoffs used to estimate whether some degrees are worth more than others, finding large differences in returns across degree-institution combinations.", link: doi("10.3386/w19241"), kind: "doi" },
    ],
  },
  {
    id: "gs-education-career-w2-selectivity",
    goal: "education-career", tier: "moderate", section: "8759",
    title: "Chase Fit and Cost Before Prestige — Unless You Are From a Low-Income or First-Generation Background",
    subtitle: "For most students, attending a more selective college adds little to earnings once you account for who applies; for disadvantaged students it adds a lot",
    evidenceTag: "Mixed",
    impact: { magnitude: 2, latency: "months", durability: "lasting", effort: "moderate" },
    callout: "Rated honestly, not at the floor: Dale and Krueger's matched-applicant studies found no earnings payoff to selectivity for the average student once the set of colleges applied to is held constant, but substantial payoffs for Black, Hispanic and first-generation students; regression-discontinuity studies of flagship admission and the Chetty mobility data likewise show gains concentrated among marginal and lower-income admits.",
    feeds: ["college choice", "debt avoidance", "social mobility"],
    description:
      "Two matched-applicant studies (1970s and 1990s cohorts) found that students admitted to more and less selective colleges earned about the same later in life when the colleges they applied to were the same — except students from disadvantaged backgrounds, who gained. Regression-discontinuity evidence around flagship-university admission thresholds finds sizeable earnings gains for marginal admits, and mobility-report-card data show that selective institutions move low-income students up the distribution but admit few of them. The boundary: 'selectivity' bundles peers, resources, networks and cost; the honest read is that it matters most for those with the least access to those things elsewhere.",
    action: "Rank your admits on net cost, graduation rate for students like you, and major strength before name recognition; if you are first-generation or low-income and a selective college's net price is comparable, the evidence favours the selective option.",
    sources: [
      { cite: "Dale, S. B., & Krueger, A. B. (2002). Estimating the Payoff to Attending a More Selective College: An Application of Selection on Observables and Unobservables. The Quarterly Journal of Economics, 117(4), 1491-1527.", note: "Matching students by the colleges they applied to, attending a more selective college had little effect on earnings for the average student but a positive effect for students from disadvantaged backgrounds.", link: doi("10.1162/003355302320935089"), kind: "doi" },
      { cite: "Dale, S. B., & Krueger, A. B. (2014). Estimating the Effects of College Characteristics over the Career Using Administrative Earnings Data. Journal of Human Resources, 49(2), 323-358.", note: "Extension using administrative earnings over the career for later cohorts, reproducing the pattern of no average payoff to selectivity after self-revelation controls, with gains for disadvantaged students.", link: doi("10.3368/jhr.49.2.323"), kind: "doi" },
      { cite: "Hoekstra, M. (2009). The Effect of Attending the Flagship State University on Earnings: A Discontinuity-Based Approach. Review of Economics and Statistics, 91(4), 717-724.", note: "Regression-discontinuity study around a flagship state university's admission cutoff finding a large earnings premium for white men who were barely admitted.", link: doi("10.1162/rest.91.4.717"), kind: "doi" },
      { cite: "Zimmerman, S. D. (2014). The Returns to College Admission for Academically Marginal Students. Journal of Labor Economics, 32(4), 711-754.", note: "Academically marginal students admitted to a four-year university near the cutoff had higher later earnings, indicating substantial returns to access for students on the margin.", link: doi("10.1086/676661"), kind: "doi" },
      { cite: "Chetty, R., Friedman, J. N., Saez, E., Turner, N., & Yagan, D. (2020). Income Segregation and Intergenerational Mobility Across Colleges in the United States*. The Quarterly Journal of Economics, 135(3), 1567-1633.", note: "Mobility report cards: selective colleges produce good outcomes for low-income students but enrol few of them, so access rather than selectivity per se is the lever for mobility.", link: doi("10.1093/qje/qjaa005"), kind: "doi" },
      { cite: "Black, D. A., & Smith, J. A. (2004). How robust is the evidence on the effects of college quality? Evidence from matching. Journal of Econometrics, 121(1-2), 99-124.", note: "Matching-based estimates of college quality effects showing the evidence is sensitive to method, a caution for reading simple prestige comparisons.", link: doi("10.1016/j.jeconom.2003.10.006"), kind: "doi" },
    ],
  },
  {
    id: "gs-education-career-w2-apprenticeships-certificates",
    goal: "education-career", tier: "elite", section: "8760",
    title: "Consider a Registered Apprenticeship or a Labor-Market-Aligned Certificate Instead of a Default Bachelor's",
    subtitle: "Returns to health and technical certificates and to apprenticeships are substantial; returns to generic or short certificates are often near zero",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "months", durability: "lasting", effort: "high" },
    feeds: ["earnings", "credential value", "employer connection"],
    description:
      "Administrative-data studies from Kentucky, Washington, North Carolina, Virginia and California find that associate degrees and longer certificates raise quarterly earnings, with the largest returns in health and technical fields and small or zero returns for short certificates in low-wage fields. English administrative data show apprenticeships pay, especially at higher levels and for men, and reviews of employer investment show firms recoup training costs. The boundary: field and length matter more than the credential label, so choose by the occupation's wage data, not the program's marketing.",
    action: "Before enrolling in any sub-baccalaureate program, look up its field-specific earnings return in your state's data and the local registered-apprenticeship listings; commit only to a credential whose graduates show a clear wage premium, and prefer programs that include paid work with an employer.",
    sources: [
      { cite: "Jepsen, C., Troske, K., & Coomes, P. (2014). The Labor-Market Returns to Community College Degrees, Diplomas, and Certificates. Journal of Labor Economics, 32(1), 95-121.", note: "Kentucky administrative data: associate degrees and diplomas carried large quarterly earnings returns, certificates smaller ones, with variation by field and gender.", link: doi("10.1086/671809"), kind: "doi" },
      { cite: "Dadgar, M., & Trimble, M. J. (2015). Labor Market Returns to Sub-Baccalaureate Credentials. Educational Evaluation and Policy Analysis, 37(4), 399-418.", note: "Washington State data: returns to sub-baccalaureate credentials were substantial for associate degrees and long certificates but near zero for short-term certificates in some fields.", link: doi("10.3102/0162373714553814"), kind: "doi" },
      { cite: "Xu, D., & Trimble, M. (2016). What About Certificates? Evidence on the Labor Market Returns to Nondegree Community College Awards in Two States. Educational Evaluation and Policy Analysis, 38(2), 272-292.", note: "Evidence from two states on labour-market returns to non-degree community-college awards: returns depend heavily on field of study and certificate length.", link: doi("10.3102/0162373715617827"), kind: "doi" },
      { cite: "Cavaglia, C., McNally, S., & Ventura, G. (2020). Do Apprenticeships Pay? Evidence for England. Oxford Bulletin of Economics and Statistics, 82(5), 1094-1134.", note: "English administrative data: apprenticeships raise earnings, with larger returns for higher-level apprenticeships and considerable variation by sector.", link: doi("10.1111/obes.12363"), kind: "doi" },
      { cite: "Stevens, A. H., Kurlaender, M., & Grosz, M. (2018). Career Technical Education and Labor Market Outcomes. Journal of Human Resources, 54(4), 986-1036.", note: "California community-college data: career technical education credentials in health and technical fields carried the largest earnings gains.", link: doi("10.3368/jhr.54.4.1015.7449r2"), kind: "doi" },
      { cite: "Backes, B., Holzer, H. J., & Velez, E. D. (2015). Is it worth it? Postsecondary education and labor market outcomes for the disadvantaged. IZA Journal of Labor Policy, 4(1).", note: "Examines postsecondary education and labour-market outcomes for disadvantaged students, showing credential and field choice shape whether the investment pays off.", link: doi("10.1186/s40173-014-0027-0"), kind: "doi" },
      { cite: "Lerman, R. (2014). Do firms benefit from apprenticeship investments?. IZA World of Labor.", note: "Reviews evidence that firms benefit from apprenticeship investments, supporting the employer side of the apprenticeship bargain.", link: doi("10.15185/izawol.55"), kind: "doi" },
    ],
  },
  {
    id: "gs-education-career-w2-career-counseling",
    goal: "education-career", tier: "moderate", section: "8761",
    title: "Use Career Counseling That Has the Five Critical Ingredients — Not a Single Test Printout",
    subtitle: "Individual counseling and structured groups outperform self-directed or computer-only interventions",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "moderate" },
    feeds: ["career decidedness", "self-efficacy", "working alliance"],
    description:
      "A lineage of meta-analyses from 1988 to 2017 finds career interventions produce moderate gains in career decidedness, maturity and decision self-efficacy, that individual counseling is the most effective modality per session, and that computer-only or unguided self-help is the least effective. Brown and Ryan Krane identified critical ingredients — written exercises, individualized feedback, world-of-work information, modelling, and attention to building support — and interventions with more of them work better. The boundary: outcome measures are mostly attitudes and decisions, not later earnings.",
    action: "Book career counseling at your college or through a credentialed counselor, and choose a format that includes written exercises, individualized interpretation of your interest results, occupational information, and at least one follow-up session; skip 'take the test, read the printout' services.",
    sources: [
      { cite: "Oliver, L. W., & Spokane, A. R. (1988). Career-intervention outcome: What contributes to client gain?. Journal of Counseling Psychology, 35(4), 447-462.", note: "Foundational meta-analysis of career-intervention outcomes identifying what contributed to client gain across intervention types.", link: doi("10.1037/0022-0167.35.4.447"), kind: "doi" },
      { cite: "Whiston, S. C., Sexton, T. L., & Lasoff, D. L. (1998). Career-intervention outcome: A replication and extension of Oliver and Spokane (1988). Journal of Counseling Psychology, 45(2), 150-165.", note: "Replication and extension finding career interventions effective overall, with individual counseling among the most efficient modalities.", link: doi("10.1037/0022-0167.45.2.150"), kind: "doi" },
      { cite: "Whiston, S. C., Brecheisen, B. K., & Stephens, J. (2003). Does treatment modality affect career counseling effectiveness?. Journal of Vocational Behavior, 62(3), 390-410.", note: "Meta-analytic comparison of treatment modalities: counselor-involved interventions outperformed computer-only and self-directed approaches.", link: doi("10.1016/s0001-8791(02)00050-7"), kind: "doi" },
      { cite: "Brown, S. D., Ryan Krane, N. E., Brecheisen, J., Castelino, P., Budisin, I., Miller, M., & Edens, L. (2003). Critical ingredients of career choice interventions: More analyses and new hypotheses. Journal of Vocational Behavior, 62(3), 411-428.", note: "Identified critical ingredients (written exercises, individualized interpretation, world-of-work information, modelling, support building) whose presence predicted larger effects.", link: doi("10.1016/s0001-8791(02)00052-0"), kind: "doi" },
      { cite: "Whiston, S. C., Li, Y., Goodrich Mitts, N., & Wright, L. (2017). Effectiveness of career choice interventions: A meta-analytic replication and extension. Journal of Vocational Behavior, 100, 175-184.", note: "Meta-analytic replication and extension confirming the effectiveness of career-choice interventions and the value of counselor support and written exercises.", link: doi("10.1016/j.jvb.2017.03.010"), kind: "doi" },
      { cite: "Whiston, S. C., Rossier, J., & Barón, P. M. H. (2016). The Working Alliance in Career Counseling. Journal of Career Assessment, 24(4), 591-604.", note: "Systematic overview of the working alliance in career counseling, linking a strong counselor–client alliance to better outcomes.", link: doi("10.1177/1069072715615849"), kind: "doi" },
    ],
  },
  {
    id: "gs-education-career-w2-referrals",
    goal: "education-career", tier: "fundamental", section: "8762",
    title: "Get Referred — Ask One Employee at Each Target Company to Put Your Name In",
    subtitle: "Referred applicants are far more likely to be interviewed and hired, and referred hires stay longer",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "weeks", durability: "sustained", effort: "low" },
    feeds: ["network activation", "hiring odds", "retention"],
    description:
      "Personnel data from large firms show referred applicants are more likely to be hired and, once hired, less likely to quit, with firms gaining through lower turnover and screening costs rather than dramatically higher productivity. Field experiments and administrative network data show referrals flow through co-worker networks and disproportionately to people who resemble the referrer, which is why asking explicitly matters for people outside those networks. The boundary: a referral raises the odds of a look, not of a job you are unqualified for.",
    action: "For every job you apply to this month, find one current employee (alumni network, former colleague, second-degree contact), ask for a 15-minute conversation about the role, and then ask directly whether they would submit you as a referral.",
    sources: [
      { cite: "Burks, S. V., Cowgill, B., Hoffman, M., & Housman, M. (2015). The Value of Hiring through Employee Referrals *. The Quarterly Journal of Economics, 130(2), 805-839.", note: "Personnel records from nine large firms: referred applicants were more likely to be hired and referred workers had lower turnover, with firms profiting mainly through retention and hiring costs.", link: doi("10.1093/qje/qjv010"), kind: "doi" },
      { cite: "Brown, M., Setren, E., & Topa, G. (2016). Do Informal Referrals Lead to Better Matches? Evidence from a Firm’s Employee Referral System. Journal of Labor Economics, 34(1), 161-209.", note: "A firm's referral system produced better matches: referred candidates were more likely to be interviewed and hired and had longer tenure.", link: doi("10.1086/682338"), kind: "doi" },
      { cite: "Fernandez, R. M., Castilla, E. J., & Moore, P. (2000). Social Capital at Work: Networks and Employment at a Phone Center. American Journal of Sociology, 105(5), 1288-1356.", note: "Phone-center hiring data showing how referral networks raised applicants' hiring odds and how firms benefited from network-based screening.", link: doi("10.1086/210432"), kind: "doi" },
      { cite: "Pallais, A., & Sands, E. G. (2015). Why the Referential Treatment: Evidence from Field Experiments on Referrals. NBER Working Paper 21357, National Bureau of Economic Research.", note: "Field experiments on referrals finding referred workers performed better and were less likely to quit, particularly when paired with their referrer.", link: doi("10.3386/w21357"), kind: "doi" },
      { cite: "Dustmann, C., Glitz, A., Schönberg, U., & Brücker, H. (2015). Referral-based Job Search Networks. The Review of Economic Studies, 83(2), 514-546.", note: "German administrative data linking co-worker networks to job search: referral-based hiring raised starting wages and lowered separations.", link: doi("10.1093/restud/rdv045"), kind: "doi" },
      { cite: "Beaman, L., & Magruder, J. (2012). Who Gets the Job Referral? Evidence from a Social Networks Experiment. American Economic Review, 102(7), 3574-3593.", note: "Social-networks experiment showing who receives job referrals: referrers favoured relatives and people like themselves, so outsiders must ask.", link: doi("10.1257/aer.102.7.3574"), kind: "doi" },
      { cite: "Castilla, E. J. (2005). Social Networks and Employee Performance in a Call Center. American Journal of Sociology, 110(5), 1243-1283.", note: "Call-center study of referral networks and employee performance, documenting the retention advantage of referred hires.", link: doi("10.1086/427319"), kind: "doi" },
    ],
  },
  {
    id: "gs-education-career-w2-job-search-wellbeing",
    goal: "education-career", tier: "moderate", section: "8763",
    title: "Run a Structured Job Search With Daily Goals — and Protect Routine, Sleep and Contact While Unemployed",
    subtitle: "Unemployment reliably harms mental health; structured search programs raise re-employment and buffer the harm",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "weeks", durability: "sustained", effort: "moderate" },
    feeds: ["re-employment", "mental health", "self-efficacy"],
    description:
      "Meta-analyses of hundreds of studies show unemployment causally worsens mental health and well-being, that recovery follows re-employment, and that job-search self-efficacy, clarity and structured search behaviour predict finding work. A meta-analysis of job-search intervention trials found programs that combine skills training, goal setting, self-efficacy building and social support roughly triple the odds of employment relative to controls. The boundary: search intensity alone is not the lever — quality, structure and psychological support are.",
    action: "If you are searching, join a structured job-search program or club (many workforce centers run them), set a written weekly plan with daily contact and application targets, keep fixed wake, exercise and social routines, and review the plan with someone every Friday.",
    sources: [
      { cite: "McKee-Ryan, F., Song, Z., Wanberg, C. R., & Kinicki, A. J. (2005). Psychological and Physical Well-Being During Unemployment: A Meta-Analytic Study. Journal of Applied Psychology, 90(1), 53-76.", note: "Meta-analysis of psychological and physical well-being during unemployment: unemployed people had markedly lower well-being, and coping resources and re-employment predicted recovery.", link: doi("10.1037/0021-9010.90.1.53"), kind: "doi" },
      { cite: "Paul, K. I., & Moser, K. (2009). Unemployment impairs mental health: Meta-analyses. Journal of Vocational Behavior, 74(3), 264-282.", note: "Meta-analyses showing unemployment impairs mental health, with longitudinal and natural-experiment evidence supporting a causal interpretation.", link: doi("10.1016/j.jvb.2009.01.001"), kind: "doi" },
      { cite: "Kanfer, R., Wanberg, C. R., & Kantrowitz, T. M. (2001). Job search and employment: A personality–motivational analysis and meta-analytic review. Journal of Applied Psychology, 86(5), 837-855.", note: "Personality–motivational meta-analysis of job search: self-efficacy, conscientiousness and structured search behaviour predicted employment outcomes.", link: doi("10.1037/0021-9010.86.5.837"), kind: "doi" },
      { cite: "Liu, S., Huang, J. L., & Wang, M. (2014). Effectiveness of job search interventions: A meta-analytic review. Psychological Bulletin, 140(4), 1009-1041.", note: "Meta-analytic review of job-search interventions: programs teaching search skills, goal setting, self-efficacy and enlisting social support substantially increased the odds of employment.", link: doi("10.1037/a0035923"), kind: "doi" },
      { cite: "Wanberg, C. R. (2012). The Individual Experience of Unemployment. Annual Review of Psychology, 63(1), 369-396.", note: "Review of the individual experience of unemployment, integrating evidence on well-being, coping and job-search behaviour.", link: doi("10.1146/annurev-psych-120710-100500"), kind: "doi" },
      { cite: "van Hooft, E. A. J., Kammeyer-Mueller, J. D., Wanberg, C. R., Kanfer, R., & Basbug, G. (2021). Job search and employment success: A quantitative review and future research agenda. Journal of Applied Psychology, 106(5), 674-713.", note: "Quantitative review of job search and employment success linking search quality and self-regulation to outcomes, beyond sheer intensity.", link: doi("10.1037/apl0000675"), kind: "doi" },
    ],
  },
  {
    id: "gs-education-career-w2-career-adaptability",
    goal: "education-career", tier: "moderate", section: "8764",
    title: "Build Career Adaptability Deliberately — Concern, Control, Curiosity, Confidence",
    subtitle: "Adaptability resources predict career success and can be raised by a short training",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "moderate" },
    feeds: ["career self-management", "transition readiness", "decision self-efficacy"],
    description:
      "Savickas's Career Adapt-Abilities Scale measures four resources — concern about the future, control over one's path, curiosity about options and confidence to act — and meta-analyses show these predict career decision self-efficacy, employability, engagement and subjective career success beyond personality and core self-evaluations. A training study with graduates showed adaptability could be increased and led to better-quality employment. The boundary: much of the literature is cross-sectional and self-reported, so treat effects as moderate.",
    action: "Take the CAAS (or write two lines under each of concern, control, curiosity, confidence) and pick the weakest resource; run a four-week plan for it — e.g. for curiosity, three informational interviews; for concern, a written one-year and five-year plan reviewed monthly.",
    sources: [
      { cite: "Savickas, M. L., & Porfeli, E. J. (2012). Career Adapt-Abilities Scale: Construction, reliability, and measurement equivalence across 13 countries. Journal of Vocational Behavior, 80(3), 661-673.", note: "Construction of the Career Adapt-Abilities Scale with reliability and measurement equivalence across 13 countries, defining the four resources.", link: doi("10.1016/j.jvb.2012.01.011"), kind: "doi" },
      { cite: "Rudolph, C. W., Lavigne, K. N., & Zacher, H. (2017). Career adaptability: A meta-analysis of relationships with measures of adaptivity, adapting responses, and adaptation results. Journal of Vocational Behavior, 98, 17-34.", note: "Meta-analysis linking career adaptability to adaptivity, adapting responses and adaptation results such as career satisfaction and performance.", link: doi("10.1016/j.jvb.2016.09.002"), kind: "doi" },
      { cite: "Rudolph, C. W., Lavigne, K. N., Katz, I. M., & Zacher, H. (2017). Linking dimensions of career adaptability to adaptation results: A meta-analysis. Journal of Vocational Behavior, 102, 151-173.", note: "Meta-analysis of the four adaptability dimensions and their links to adaptation results, showing which resources matter most for which outcomes.", link: doi("10.1016/j.jvb.2017.06.003"), kind: "doi" },
      { cite: "Koen, J., Klehe, U. C., & Van Vianen, A. E. (2012). Training career adaptability to facilitate a successful school-to-work transition. Journal of Vocational Behavior, 81(3), 395-408.", note: "Training study: a career-adaptability intervention for graduates increased adaptability resources and facilitated the school-to-work transition.", link: doi("10.1016/j.jvb.2012.10.003"), kind: "doi" },
      { cite: "Zacher, H. (2014). Career adaptability predicts subjective career success above and beyond personality traits and core self-evaluations. Journal of Vocational Behavior, 84(1), 21-30.", note: "Career adaptability predicted subjective career success above and beyond personality traits and core self-evaluations.", link: doi("10.1016/j.jvb.2013.10.002"), kind: "doi" },
      { cite: "Johnston, C. S. (2016). A Systematic Review of the Career Adaptability Literature and Future Outlook. Journal of Career Assessment, 26(1), 3-30.", note: "Systematic review of the career adaptability literature summarising antecedents, outcomes and measurement issues.", link: doi("10.1177/1069072716679921"), kind: "doi" },
      { cite: "Stead, G. B., LaVeck, L. M., & Hurtado Rúa, S. M. (2021). Career Adaptability and Career Decision Self-Efficacy: Meta-Analysis. Journal of Career Development, 49(4), 951-964.", note: "Meta-analysis of career adaptability and career decision self-efficacy showing a robust positive relationship.", link: doi("10.1177/08948453211012477"), kind: "doi" },
    ],
  },
  {
    id: "gs-education-career-w2-retraining",
    goal: "education-career", tier: "elite", section: "8765",
    title: "After Displacement, Retrain Through a Sector-Aligned Program — Technical Fields Pay, Generic Courses Often Don't",
    subtitle: "Returns to community-college retraining and sectoral programs are real but concentrated in quantitative and health fields; effects take years to show",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "months", durability: "lasting", effort: "high" },
    feeds: ["re-employment earnings", "skills relevance", "long-horizon planning"],
    description:
      "Displaced workers who completed community-college coursework in technically oriented, quantitative or health fields saw meaningful long-run earnings gains, while courses in other fields yielded little. Meta-analyses of active labour-market programs find training effects are small or negative in the first year and turn positive after two to three years, with larger effects for women and the long-term unemployed. Sectoral programs that train for specific in-demand occupations with employer involvement show the strongest experimental results, and a Dutch study found training reduced job loss even for older workers. The boundary: the payoff is slow and field-specific; a generic course is not the same investment.",
    action: "If displaced or planning a mid-career switch, choose a program tied to a named local occupation with wage data and employer partners (sectoral training, health or technical certificate), budget for a two-to-three-year horizon before returns appear, and use any available displaced-worker funding rather than loans.",
    sources: [
      { cite: "Jacobson, L., LaLonde, R., & G. Sullivan, D. (2005). Estimating the returns to community college schooling for displaced workers. Journal of Econometrics, 125(1-2), 271-304.", note: "Displaced workers who completed community-college schooling in quantitative or technically oriented fields earned substantially more in the long run than non-participants; other fields showed little gain.", link: doi("10.1016/j.jeconom.2004.04.010"), kind: "doi" },
      { cite: "Card, D., Kluve, J., & Weber, A. (2010). Active Labour Market Policy Evaluations: A Meta‐Analysis. The Economic Journal, 120(548), F452-F477.", note: "Meta-analysis of active labour-market policy evaluations: classroom and on-the-job training programs had modest short-run effects that turned more positive after two years.", link: doi("10.1111/j.1468-0297.2010.02387.x"), kind: "doi" },
      { cite: "Card, D., Kluve, J., & Weber, A. (2017). What Works? A Meta Analysis of Recent Active Labor Market Program Evaluations. Journal of the European Economic Association, 16(3), 894-931.", note: "Larger meta-analysis of recent program evaluations confirming that training effects grow with time since program entry and are larger for women and long-term unemployed participants.", link: doi("10.1093/jeea/jvx028"), kind: "doi" },
      { cite: "Picchio, M., & van Ours, J. C. (2013). Retaining through training even for older workers. Economics of Education Review, 32, 29-48.", note: "Dutch panel evidence that training participation reduced the probability of job loss even among older workers.", link: doi("10.1016/j.econedurev.2012.08.004"), kind: "doi" },
      { cite: "Katz, L. F., Roth, J., Hendra, R., & Schaberg, K. (2022). Why Do Sectoral Employment Programs Work? Lessons from WorkAdvance. Journal of Labor Economics, 40(S1), S249-S291.", note: "Experimental evidence from WorkAdvance sectoral employment programs: sustained earnings gains driven by moving participants into targeted higher-wage sectors.", link: doi("10.1086/717932"), kind: "doi" },
      { cite: "Heinrich, C. J., Mueser, P. R., Troske, K. R., Jeon, K. S., & Kahvecioglu, D. C. (2013). Do Public Employment and Training Programs Work?. IZA Journal of Labor Economics, 2(1).", note: "Non-experimental evaluation of U.S. public employment and training programs finding positive earnings effects for adult trainees that emerge over time.", link: doi("10.1186/2193-8997-2-6"), kind: "doi" },
      { cite: "Andersson, F., Holzer, H., Lane, J., Rosenblum, D., & Smith, J. (2013). Does Federally-Funded Job Training Work? Nonexperimental Estimates of WIA Training Impacts Using Longitudinal Data on Workers and Firms. NBER Working Paper 19446, National Bureau of Economic Research.", note: "Longitudinal worker–firm data on WIA training impacts, showing gains depend on training type and on placement with higher-paying employers.", link: doi("10.3386/w19446"), kind: "doi" },
    ],
  },
  {
    id: "gs-education-career-w2-women-negotiation",
    goal: "education-career", tier: "moderate", section: "8766",
    title: "Negotiate — But Know the Evidence: Ask When Asking Is Signalled as Acceptable, and Use Communal Framing",
    subtitle: "Women initiate negotiations less often, are penalised more for assertive asking, and close the gap when the situation makes negotiation explicitly appropriate",
    evidenceTag: "Mixed",
    impact: { magnitude: 3, latency: "weeks", durability: "lasting", effort: "low" },
    feeds: ["pay equity", "situational awareness", "framing skill"],
    description:
      "Meta-analyses find women are somewhat less likely to initiate negotiations and obtain slightly worse economic outcomes on average, but the gaps shrink or reverse when negotiating is clearly appropriate, when women have experience, or when they negotiate for others. Laboratory and field experiments show evaluators penalise women more than men for initiating salary talks and that stating a job is negotiable closes the gender gap in who negotiates; one experiment found that women who avoided negotiating were often correctly reading situations where asking would hurt. The boundary: the honest lesson is situational — negotiate, and choose the moment and framing with the evidence in mind.",
    action: "Before any offer conversation, find out whether the employer signals negotiability (ask HR or check the posting); prepare a market-anchored ask framed around the role and team ('for this scope, the range is…'), and practise it aloud twice with someone who will push back.",
    sources: [
      { cite: "Bowles, H. R., Babcock, L., & Lai, L. (2007). Social incentives for gender differences in the propensity to initiate negotiations: Sometimes it does hurt to ask. Organizational Behavior and Human Decision Processes, 103(1), 84-103.", note: "Experiments showing evaluators were less willing to work with women who initiated salary negotiations than men who did — the social cost of asking.", link: doi("10.1016/j.obhdp.2006.09.001"), kind: "doi" },
      { cite: "Bowles, H. R., Babcock, L., & McGinn, K. L. (2005). Constraints and triggers: Situational mechanics of gender in negotiation. Journal of Personality and Social Psychology, 89(6), 951-965.", note: "Situational mechanics of gender in negotiation: gender differences appeared under ambiguity and low structure and disappeared when the situation was clear.", link: doi("10.1037/0022-3514.89.6.951"), kind: "doi" },
      { cite: "Mazei, J., Hüffmeier, J., Freund, P. A., Stuhlmacher, A. F., Bilke, L., & Hertel, G. (2015). A meta-analysis on gender differences in negotiation outcomes and their moderators. Psychological Bulletin, 141(1), 85-104.", note: "Meta-analysis of gender differences in negotiation outcomes: women obtained somewhat lower economic outcomes on average, with the gap reduced by experience and by negotiating for others.", link: doi("10.1037/a0038184"), kind: "doi" },
      { cite: "Kugler, K. G., Reif, J. A. M., Kaschner, T., & Brodbeck, F. C. (2018). Gender differences in the initiation of negotiations: A meta-analysis. Psychological Bulletin, 144(2), 198-222.", note: "Meta-analysis of the initiation of negotiations: women initiated less often than men, but the difference was smaller when negotiating was framed as appropriate.", link: doi("10.1037/bul0000135"), kind: "doi" },
      { cite: "Leibbrandt, A., & List, J. A. (2015). Do Women Avoid Salary Negotiations? Evidence from a Large-Scale Natural Field Experiment. Management Science, 61(9), 2016-2024.", note: "Natural field experiment: when job postings stated that wages were negotiable, women were as likely as men to negotiate, and the gap appeared only when negotiability was ambiguous.", link: doi("10.1287/mnsc.2014.1994"), kind: "doi" },
      { cite: "Exley, C. L., Niederle, M., & Vesterlund, L. (2020). Knowing When to Ask: The Cost of Leaning In. Journal of Political Economy, 128(3), 816-854.", note: "Laboratory experiment finding women who chose not to negotiate were often correctly avoiding situations where negotiating would have lowered their payoff, cautioning against blanket 'always ask' advice.", link: doi("10.1086/704616"), kind: "doi" },
      { cite: "Small, D. A., Gelfand, M., Babcock, L., & Gettman, H. (2007). Who goes to the bargaining table? The influence of gender and framing on the initiation of negotiation. Journal of Personality and Social Psychology, 93(4), 600-613.", note: "Framing the interaction as an opportunity to 'ask' rather than 'negotiate' reduced the gender gap in initiating.", link: doi("10.1037/0022-3514.93.4.600"), kind: "doi" },
      { cite: "Stuhlmacher, A. F., & Walters, A. E. (1999). GENDER DIFFERENCES IN NEGOTIATION OUTCOME: A META‐ANALYSIS. Personnel Psychology, 52(3), 653-677.", note: "Earlier meta-analysis of gender differences in negotiation outcome establishing a small average difference favouring men.", link: doi("10.1111/j.1744-6570.1999.tb00175.x"), kind: "doi" },
    ],
  },
  {
    id: "gs-education-career-w2-job-satisfaction",
    goal: "education-career", tier: "fundamental", section: "8767",
    title: "Judge a Job by Its Design — Autonomy, Skill Variety, Feedback, Social Support — and Know Your Own Baseline",
    subtitle: "Job characteristics and core self-evaluations together explain much of job satisfaction; pay explains little",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "months", durability: "sustained", effort: "low" },
    feeds: ["job choice", "self-knowledge", "well-being"],
    description:
      "Judge and colleagues' core self-evaluations — self-esteem, generalised self-efficacy, locus of control and emotional stability — predict job and life satisfaction across studies, and the work-design meta-analysis shows autonomy, task variety, significance, feedback and social support account for a large share of satisfaction variance. Job satisfaction in turn relates to performance and, in a meta-analysis, to health. The boundary: dispositions set a baseline, so a job change moves satisfaction less than people expect; the design features are what you can actually choose.",
    action: "When comparing offers, score each on autonomy, skill variety, task significance, feedback and social support (1–5 each) and weight that total more than the salary difference; separately, take one core self-evaluations inventory so you know how much of your satisfaction travels with you.",
    sources: [
      { cite: "Judge, T. A., & Bono, J. E. (2001). Relationship of core self-evaluations traits—self-esteem, generalized self-efficacy, locus of control, and emotional stability—with job satisfaction and job performance: A meta-analysis. Journal of Applied Psychology, 86(1), 80-92.", note: "Meta-analysis: core self-evaluation traits (self-esteem, generalized self-efficacy, locus of control, emotional stability) related to both job satisfaction and job performance.", link: doi("10.1037/0021-9010.86.1.80"), kind: "doi" },
      { cite: "Judge, T. A., Locke, E. A., Durham, C. C., & Kluger, A. N. (1998). Dispositional effects on job and life satisfaction: The role of core evaluations. Journal of Applied Psychology, 83(1), 17-34.", note: "Introduced core evaluations as dispositional predictors of job and life satisfaction, with effects operating partly through perceptions of the job.", link: doi("10.1037/0021-9010.83.1.17"), kind: "doi" },
      { cite: "Judge, T. A., Heller, D., & Mount, M. K. (2002). Five-factor model of personality and job satisfaction: A meta-analysis. Journal of Applied Psychology, 87(3), 530-541.", note: "Meta-analysis of the five-factor model and job satisfaction: neuroticism, conscientiousness and extraversion were the strongest personality correlates.", link: doi("10.1037/0021-9010.87.3.530"), kind: "doi" },
      { cite: "Humphrey, S. E., Nahrgang, J. D., & Morgeson, F. P. (2007). Integrating motivational, social, and contextual work design features: A meta-analytic summary and theoretical extension of the work design literature. Journal of Applied Psychology, 92(5), 1332-1356.", note: "Meta-analytic summary of work design: motivational, social and contextual characteristics explained substantial variance in satisfaction and other attitudes.", link: doi("10.1037/0021-9010.92.5.1332"), kind: "doi" },
      { cite: "Judge, T. A., Thoresen, C. J., Bono, J. E., & Patton, G. K. (2001). The job satisfaction–job performance relationship: A qualitative and quantitative review. Psychological Bulletin, 127(3), 376-407.", note: "Qualitative and quantitative review of the job satisfaction–job performance relationship finding a moderate positive correlation.", link: doi("10.1037/0033-2909.127.3.376"), kind: "doi" },
      { cite: "Chang, C. H. (., Ferris, D. L., Johnson, R. E., Rosen, C. C., & Tan, J. A. (2011). Core Self-Evaluations. Journal of Management, 38(1), 81-128.", note: "Meta-analytic review of core self-evaluations and their relationships with work outcomes.", link: doi("10.1177/0149206311419661"), kind: "doi" },
      { cite: "Bowling, N. A., Eschleman, K. J., & Wang, Q. (2010). A meta‐analytic examination of the relationship between job satisfaction and subjective well‐being. Journal of Occupational and Organizational Psychology, 83(4), 915-934.", note: "Meta-analysis of job satisfaction and subjective well-being showing the two are linked, with evidence that dispositions drive part of both.", link: doi("10.1348/096317909x478557"), kind: "doi" },
      { cite: "Faragher, E. B., Cass, M., & Cooper, C. L. (2005). The relationship between job satisfaction and health: a meta-analysis. Occupational and Environmental Medicine, 62(2), 105-112.", note: "Meta-analysis relating job satisfaction to health, with the strongest associations for mental-health outcomes such as burnout and depression.", link: doi("10.1136/oem.2002.006734"), kind: "doi" },
    ],
  },
  {
    id: "gs-education-career-w2-commuting",
    goal: "education-career", tier: "fundamental", section: "8768",
    title: "Price the Commute Into Every Job Decision — Long Drives Cost Well-Being People Do Not Get Paid For",
    subtitle: "Commuting ranks among the least pleasant daily activities, and longer commutes predict lower life satisfaction and worse mental health, especially for women",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "weeks", durability: "lasting", effort: "low" },
    feeds: ["time budget", "job choice", "mental health"],
    description:
      "Day-reconstruction data place the morning commute near the bottom of daily activities for positive affect; German panel data show people with longer commutes report systematically lower life satisfaction — the 'commuting paradox', because wages do not appear to compensate — and UK panel data find the psychological cost falls disproportionately on women. Reviews of the commuting-and-wellbeing literature and health studies link long car commutes to stress, lower physical activity and worse health, while experimental evidence shows workers value flexible schedules and working from home. The boundary: active commutes (walking, cycling) and shorter commutes do not carry these costs, and some people adapt.",
    action: "Before accepting an offer, calculate the weekly door-to-door commute time and treat every extra daily 30 minutes as a real pay cut; negotiate remote or flexible days, or choose the closer job when the offers are otherwise close.",
    sources: [
      { cite: "Stutzer, A., & Frey, B. S. (2008). Stress that Doesn't Pay: The Commuting Paradox*. The Scandinavian Journal of Economics, 110(2), 339-366.", note: "German panel data: people with longer commutes reported systematically lower subjective well-being, and compensating wage or housing benefits did not appear to offset it.", link: doi("10.1111/j.1467-9442.2008.00542.x"), kind: "doi" },
      { cite: "Chatterjee, K., Chng, S., Clark, B., Davis, A., De Vos, J., Ettema, D., et al. (2019). Commuting and wellbeing: a critical overview of the literature with implications for policy and future research. Transport Reviews, 40(1), 5-34.", note: "Critical overview of the commuting-and-wellbeing literature with policy implications, summarising consistent negative associations for long and stressful commutes.", link: doi("10.1080/01441647.2019.1649317"), kind: "doi" },
      { cite: "Clark, B., Chatterjee, K., Martin, A., & Davis, A. (2019). How commuting affects subjective wellbeing. Transportation, 47(6), 2777-2805.", note: "Panel analysis of how commuting affects subjective well-being, finding longer commutes reduced satisfaction with leisure time and raised strain.", link: doi("10.1007/s11116-019-09983-9"), kind: "doi" },
      { cite: "Kahneman, D., Krueger, A. B., Schkade, D. A., Schwarz, N., & Stone, A. A. (2004). A Survey Method for Characterizing Daily Life Experience: The Day Reconstruction Method. Science, 306(5702), 1776-1780.", note: "Day Reconstruction Method survey in which the morning commute ranked among the least enjoyable daily episodes.", link: doi("10.1126/science.1103572"), kind: "doi" },
      { cite: "Mas, A., & Pallais, A. (2017). Valuing Alternative Work Arrangements. American Economic Review, 107(12), 3722-3759.", note: "Discrete-choice experiment: workers were willing to give up a share of wages for flexible scheduling and working from home, valuing arrangements that shorten or remove commutes.", link: doi("10.1257/aer.20161500"), kind: "doi" },
      { cite: "Le Barbanchon, T., Rathelot, R., & Roulet, A. (2020). Gender Differences in Job Search: Trading off COMMUTE AGAINST WAGE*. The Quarterly Journal of Economics, 136(1), 381-426.", note: "French administrative data: women's job search traded off commute against wage more strongly than men's, contributing to gender wage gaps.", link: doi("10.1093/qje/qjaa033"), kind: "doi" },
      { cite: "Künn‐Nelen, A. (2015). Does Commuting Affect Health?. Health Economics, 25(8), 984-1004.", note: "Panel study finding that longer commutes were associated with worse self-reported health and health behaviours.", link: doi("10.1002/hec.3199"), kind: "doi" },
      { cite: "Roberts, J., Hodgson, R., & Dolan, P. (2011). “It's driving her mad”: Gender differences in the effects of commuting on psychological health. Journal of Health Economics, 30(5), 1064-1076.", note: "British panel data: commuting time worsened psychological health for women but not men, plausibly because of women's greater household responsibilities.", link: doi("10.1016/j.jhealeco.2011.07.006"), kind: "doi" },
    ],
  },
  {
    id: "gs-education-career-w2-myth-dream-job",
    goal: "education-career", tier: "fundamental", section: "8769",
    title: "Myth: There Is One 'Dream Job' That Will Make You Happy Once You Find It",
    subtitle: "Satisfaction after a job change follows a honeymoon and a hangover; callings are built through work, and they cut both ways",
    evidenceTag: "Strong",
    impact: { magnitude: 1, latency: "months", durability: "transient", effort: "low" },
    callout: "Rated at the floor as a belief to act on: longitudinal studies show job satisfaction rises after a voluntary change and then declines back toward baseline (the honeymoon–hangover pattern), panel data show the 'magic of the new' fades, and calling research finds that people who feel called often develop it through engagement rather than discover it, and that unanswered or deeply felt callings carry real costs. Pursue good job design and craft meaning; do not wait for a perfect job to appear.",
    feeds: ["realistic expectations", "job crafting", "meaning-making"],
    description:
      "Two longitudinal studies of voluntary job changers found satisfaction jumped in the new role and then fell within a year or two; German panel data replicate the pattern. The calling literature finds callings are associated with meaning and satisfaction, but also that they are often developed over time, that ability matters for whether pursuing one pays off, and that zookeepers with a strong sense of calling accepted low pay and sacrifice. The evidence points toward building satisfaction through job characteristics and crafting rather than waiting for a single ideal job.",
    action: "Stop searching for the perfect job title; instead write down which two of autonomy, skill use, meaning, colleagues and feedback your current role lacks, and spend this month changing one of them (task, relationship or framing) before deciding whether to move.",
    sources: [
      { cite: "Boswell, W. R., Boudreau, J. W., & Tichy, J. (2005). The Relationship Between Employee Job Change and Job Satisfaction: The Honeymoon-Hangover Effect. Journal of Applied Psychology, 90(5), 882-892.", note: "Longitudinal study of managers who changed jobs: satisfaction rose after the move and then declined — the honeymoon–hangover effect.", link: doi("10.1037/0021-9010.90.5.882"), kind: "doi" },
      { cite: "Boswell, W. R., Shipp, A. J., Payne, S. C., & Culbertson, S. S. (2009). Changes in newcomer job satisfaction over time: Examining the pattern of honeymoons and hangovers. Journal of Applied Psychology, 94(4), 844-858.", note: "Newcomer job satisfaction over time showed honeymoon and hangover patterns, with initial enthusiasm fading over the first year.", link: doi("10.1037/a0014975"), kind: "doi" },
      { cite: "Chadi, A., & Hetschko, C. (2017). The magic of the new: How job changes affect job satisfaction. Journal of Economics & Management Strategy, 27(1), 23-39.", note: "German panel data: job changes produced a temporary rise in job satisfaction that faded — 'the magic of the new'.", link: doi("10.1111/jems.12217"), kind: "doi" },
      { cite: "Duffy, R. D., & Dik, B. J. (2013). Research on calling: What have we learned and where are we going?. Journal of Vocational Behavior, 83(3), 428-436.", note: "Review of research on calling summarising its links to satisfaction and meaning, and open questions about whether callings are discovered or developed.", link: doi("10.1016/j.jvb.2013.06.006"), kind: "doi" },
      { cite: "Berg, J. M., Grant, A. M., & Johnson, V. (2010). When Callings Are Calling: Crafting Work and Leisure in Pursuit of Unanswered Occupational Callings. Organization Science, 21(5), 973-994.", note: "Qualitative study of people with unanswered occupational callings who crafted work and leisure to pursue them, showing callings are enacted rather than simply found.", link: doi("10.1287/orsc.1090.0497"), kind: "doi" },
      { cite: "Bunderson, J. S., & Thompson, J. A. (2009). The Call of the Wild: Zookeepers, Callings, and the Double-edged Sword of Deeply Meaningful Work. Administrative Science Quarterly, 54(1), 32-57.", note: "Zookeepers with a strong sense of calling found deep meaning but accepted low pay, personal sacrifice and heightened vulnerability — the double-edged sword.", link: doi("10.2189/asqu.2009.54.1.32"), kind: "doi" },
      { cite: "Dobrow, S. R., & Heller, D. (2015). Follow your heart or your head? A longitudinal study of the facilitating role of calling and ability in the pursuit of a challenging career. Journal of Applied Psychology, 100(3), 695-712.", note: "Longitudinal study of musicians: calling facilitated pursuit of a challenging career but ability shaped whether that pursuit paid off.", link: doi("10.1037/a0038011"), kind: "doi" },
      { cite: "Duffy, R. D., Dik, B. J., Douglass, R. P., England, J. W., & Velez, B. L. (2018). Work as a calling: A theoretical model. Journal of Counseling Psychology, 65(4), 423-439.", note: "Theoretical model of work as a calling distinguishing perceiving a calling from living one, with the latter depending on opportunity and resources.", link: doi("10.1037/cou0000276"), kind: "doi" },
    ],
  },
];
