// Goal shelf: HAPPINESS — wave 2 (sections 8350–8371). Widens the wave-1 happiness shelf.
// Verification: every DOI below was resolved against the PubMed record or the Crossref record
// (api.crossref.org) on 2026-09-11. See ../types.ts for the contract.
import { doi, type GoalShelfCluster } from "../types";

export const SECTIONS: Record<string, string> = {
  "8350": "Loneliness — What Actually Reduces It",
  "8351": "Social Prescribing — Link Workers and Community Referral",
  "8352": "Pets and Wellbeing — The Honest Evidence",
  "8353": "Bright Light and the Winter Dip",
  "8354": "Alcohol and Wellbeing",
  "8355": "Diet and Depression — SMILES and After",
  "8356": "Music Listening for Mood and Stress",
  "8357": "Laughter and Humor Interventions",
  "8358": "Self-Compassion",
  "8359": "Acceptance and Commitment Therapy",
  "8360": "Problem-Solving Therapy",
  "8361": "CBT for Insomnia — Sleep First, Mood Follows",
  "8362": "Social Media Reduction — The Randomized Trials",
  "8363": "News Diet — Exposure, Mood and Catastrophizing",
  "8364": "Awe Walks and Daily Awe",
  "8365": "Expressive Writing — Small, Real, Oversold",
  "8366": "Strengths Use — Modest Gains, Honest Limits",
  "8367": "Goal Progress and Wellbeing",
  "8368": "Autonomy at Work — Self-Determination Theory",
  "8369": "Micro-Breaks",
  "8370": "Boredom — A Signal, Not a Verdict",
  "8371": "Cold-Water Immersion for Mood",
};

export const CLUSTERS: GoalShelfCluster[] = [
  {
    id: "gs-happiness-w2-loneliness-social-cognition",
    goal: "happiness", tier: "advanced", section: "8350",
    title: "If You Are Lonely, Work on the Thinking, Not Just the Calendar",
    subtitle: "Meta-analyses find interventions that target maladaptive social cognition beat ones that only add social contact",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "months", durability: "sustained", effort: "high" },
    feeds: ["social cognition", "connection", "mortality risk reduction"],
    description:
      "Loneliness predicts later depressive symptoms in five-year cross-lagged analyses and, in a meta-analytic review, carries a mortality risk comparable with established risk factors. The Masi meta-analysis of loneliness interventions found that among randomized comparisons the most successful programs addressed maladaptive social cognition (expecting rejection, over-monitoring for threat), not merely social skills or more opportunities for contact; a 2021 meta-analysis of 28 randomized trials of psychological interventions found a small-to-medium pooled reduction in loneliness, most often via cognitive-behavioural therapy. The boundary: effects are moderate, heterogeneity is large, and simply joining a group is not the mechanism these trials tested.",
    action: "If loneliness has lasted more than a few months, ask a therapist for a CBT-based program that targets social cognition (rejection expectations, self-critical reading of interactions) and run it for 8–12 weekly sessions; keep a weekly log of one social interaction and what you predicted versus what happened.",
    sources: [
      { cite: "Masi, C. M., Chen, H.-Y., Hawkley, L. C., & Cacioppo, J. T. (2011). A meta-analysis of interventions to reduce loneliness. Personality and Social Psychology Review, 15(3), 219–266.", note: "Integrative meta-analysis of four intervention strategies; among randomized comparison studies the most successful interventions addressed maladaptive social cognition.", link: doi("10.1177/1088868310377394"), kind: "doi" },
      { cite: "Cacioppo, S., Grippo, A. J., London, S., Goossens, L., & Cacioppo, J. T. (2015). Loneliness: Clinical import and interventions. Perspectives on Psychological Science, 10(2), 238–249.", note: "Review building on the Masi meta-analysis; argues for well-controlled trials of interventions that rehabilitate maladaptive social cognition.", link: doi("10.1177/1745691615570616"), kind: "doi" },
      { cite: "Hickin, N., Käll, A., Shafran, R., Sutcliffe, S., Manzotti, G., & Langan, D. (2021). The effectiveness of psychological interventions for loneliness: A systematic review and meta-analysis. Clinical Psychology Review, 88, 102066.", note: "Meta-analysis of 28 randomized trials (N = 3,039): psychological interventions reduced loneliness with a small-to-medium effect (g = 0.43); CBT was the most common approach.", link: doi("10.1016/j.cpr.2021.102066"), kind: "doi" },
      { cite: "Holt-Lunstad, J., Smith, T. B., Baker, M., Harris, T., & Stephenson, D. (2015). Loneliness and social isolation as risk factors for mortality: A meta-analytic review. Perspectives on Psychological Science, 10(2), 227–237.", note: "Meta-analytic review: loneliness (OR = 1.26), social isolation (1.29) and living alone (1.32) each raised mortality risk — the stakes behind this protocol.", link: doi("10.1177/1745691614568352"), kind: "doi" },
      { cite: "Cacioppo, J. T., Hawkley, L. C., & Thisted, R. A. (2010). Perceived social isolation makes me sad: 5-year cross-lagged analyses of loneliness and depressive symptomatology in the Chicago Health, Aging, and Social Relations Study. Psychology and Aging, 25(2), 453–463.", note: "Five-year cross-lagged panel in 229 adults aged 50–68: loneliness predicted subsequent depressive symptoms, not the reverse, independent of objective isolation and social support.", link: doi("10.1037/a0017216"), kind: "doi" },
      { cite: "Ugurlu, Ö., Zerwas, F., Monroy, M., Corona, R., Amster, M., Eagle, J., & Keltner, D. (2026). Experiencing awe in daily life is linked to lower loneliness. Scientific Reports, 16(1).", note: "22-day daily diary study in healthcare workers and a community sample: days with more awe than usual were days with less loneliness, explained by a sense of connectedness.", link: doi("10.1038/s41598-025-34864-w"), kind: "doi" },
    ],
  },
  {
    id: "gs-happiness-w2-social-prescribing",
    goal: "happiness", tier: "moderate", section: "8351",
    title: "Ask About Social Prescribing — Then Treat It as an Introduction, Not a Treatment",
    subtitle: "Link workers connect you to community activities; controlled evidence of benefit is thin, uncontrolled evidence is glowing",
    evidenceTag: "Mixed",
    impact: { magnitude: 2, latency: "months", durability: "sustained", effort: "moderate" },
    feeds: ["community connection", "activity uptake", "help-seeking"],
    description:
      "Social prescribing routes people from primary care to community activities through a link worker. Two systematic reviews of UK evaluations found most studies small, uncontrolled and at high risk of bias yet reporting positive conclusions; a 2022 review of controlled trials of link workers (eight studies, five randomized) found no impact on health-related quality of life in four and no mental-health effect in three of four. A realist review explains what makes referrals stick — a credible referrer, an accessible first session, a skilled activity leader — and a German pragmatic randomized feasibility trial is under way. The boundary: the mechanism is plausible and the harms minimal, but the effect is unproven; the value is in the activity you land in, not the referral itself.",
    action: "If your clinic or health system offers a link worker or community-referral program, take the appointment, and commit to attending the first three sessions of whatever activity they connect you with before judging it; if there is no program, use the same logic yourself and pick one weekly community activity within 15 minutes of home.",
    sources: [
      { cite: "Kiely, B., Croke, A., O'Shea, M., Boland, F., O'Shea, E., Connolly, D., & Smith, S. M. (2022). Effect of social prescribing link workers on health outcomes and costs for adults in primary care and community settings: A systematic review. BMJ Open, 12(10), e062951.", note: "Eight controlled studies (n = 6,500): four reported no impact on health-related quality of life and three of four found no mental-health effect; certainty of evidence low or very low.", link: doi("10.1136/bmjopen-2022-062951"), kind: "doi" },
      { cite: "Bickerdike, L., Booth, A., Wilson, P. M., Farley, K., & Wright, K. (2017). Social prescribing: Less rhetoric and more reality. A systematic review of the evidence. BMJ Open, 7(4), e013384.", note: "Fifteen UK evaluations, all rated high risk of bias, mostly lacking controls; positive conclusions despite methodological shortcomings.", link: doi("10.1136/bmjopen-2016-013384"), kind: "doi" },
      { cite: "Husk, K., Blockley, K., Lovell, R., Bethel, A., Lang, I., Byng, R., & Garside, R. (2020). What approaches to social prescribing work, for whom, and in what circumstances? A realist review. Health & Social Care in the Community, 28(2), 309–324.", note: "Realist synthesis of 109 studies identifying what drives enrolment, engagement and adherence — a believable referral, supported transit to the first session, a skilled activity leader.", link: doi("10.1111/hsc.12839"), kind: "doi" },
      { cite: "Napierala, H., Krüger, K., Kuschick, D., Heintze, C., Herrmann, W. J., & Holzinger, F. (2022). Social prescribing: Systematic review of the effectiveness of psychosocial community referral interventions in primary care. International Journal of Integrated Care, 22(3), 11.", note: "68 reports from 53 projects, only three controlled; short uncontrolled studies reported positive effects that largely did not appear in controlled designs or longer follow-ups.", link: doi("10.5334/ijic.6472"), kind: "doi" },
      { cite: "Napierala, H., Jeske, N., Roll, S., Köberlein-Neu, J., & Herrmann, W. J. (2025). Social prescribing to improve health and well-being of patients presenting with non-medical health related social needs in primary care: Study protocol of a multi-center randomized controlled pragmatic feasibility trial. PLoS One, 20(5), e0322372.", note: "Protocol for a 300-patient randomized feasibility trial of link-worker referral in German general practice — the kind of controlled test the field still lacks.", link: doi("10.1371/journal.pone.0322372"), kind: "doi" },
    ],
  },
  {
    id: "gs-happiness-w2-pets-honest",
    goal: "happiness", tier: "fundamental", section: "8352",
    title: "Get a Pet Because You Want One — Not as a Wellbeing Intervention",
    subtitle: "Systematic reviews find pet ownership and mental health mixed to null; dog owners walk more, and a small controlled study saw less loneliness after dog acquisition",
    evidenceTag: "Mixed",
    impact: { magnitude: 2, latency: "months", durability: "sustained", effort: "high" },
    callout: "The popular claim that a pet reliably improves mental health is not supported: a 54-study review found positive, mixed, null and negative findings, and a 21-study meta-analysis found no association between ownership and depression. The credible benefits are specific — more walking for dog owners and a possible loneliness reduction — and the costs (money, time, grief, care burden) are real.",
    feeds: ["daily walking", "routine", "companionship"],
    description:
      "A 2011 critical review argued the health claims for pets outrun the evidence, and later syntheses agree: of 54 studies on pet ownership and mental health, 17 found benefit, 19 mixed results, 13 no effect and 5 harm; a 2025 meta-analysis of 159,322 participants found no overall association with depression. What does hold up is narrower — a nationwide Swedish cohort linked dog ownership to lower mortality, especially in single-person households; an Australian study found dog owners were more active, but that only activity independent of the dog tracked with mental health; and an eight-month three-arm controlled study found loneliness fell in people who acquired a dog. The boundary: selection effects are everywhere and no randomized trial of pet acquisition exists.",
    action: "Do not acquire an animal to fix your mood. If you already want one and can afford it, choose a dog only if you will walk it daily, and treat the twice-daily walk — not the animal — as the wellbeing protocol; if you are lonely and not ready to own, volunteer to walk shelter dogs one morning a week.",
    sources: [
      { cite: "Herzog, H. (2011). The impact of pets on human health and psychological well-being: Fact, fiction, or hypothesis? Current Directions in Psychological Science, 20(4), 236–239.", note: "Critical review arguing that popular claims about pets and health exceed the evidence and that selection effects and publication bias inflate the picture.", link: doi("10.1177/0963721411415220"), kind: "doi" },
      { cite: "Scoresby, K. J., Strand, E. B., Ng, Z., Brown, K. C., Stilz, C. R., Strobel, K., Barroso, C. S., & Souza, M. (2021). Pet ownership and quality of life: A systematic review of the literature. Veterinary Sciences, 8(12), 332.", note: "54 studies: 17 positive, 19 mixed, 13 no impact and 5 negative — results variable and not wholly supportive of a mental-health benefit.", link: doi("10.3390/vetsci8120332"), kind: "doi" },
      { cite: "Moshfeghinia, R., Rostamipourfard, S., Kamran, M., Mostafavi, S., Golabi, F., Ayano, G., & Ahmadi, J. (2025). Pet ownership and risk of depression: A systematic review and meta-analysis. Annals of General Psychiatry, 24(1), 66.", note: "21 observational studies (159,322 participants): no association between pet ownership and depression overall (OR 1.03); cat ownership modestly higher risk, dog ownership null.", link: doi("10.1186/s12991-025-00600-x"), kind: "doi" },
      { cite: "Zablan, K., Melvin, G., & Hayley, A. (2024). Dog ownership, physical activity, loneliness and mental health: A comparison of older adult and younger adult companion animal owners. BMC Psychology, 12(1), 618.", note: "Path analysis in 588 owners: dog owners were more active, but only activity performed independently of the dog was associated with less loneliness and better mental health.", link: doi("10.1186/s40359-024-02104-x"), kind: "doi" },
      { cite: "Powell, L., Edwards, K. M., McGreevy, P., Bauman, A., Podberscek, A., Neilly, B., Sherrington, C., & Stamatakis, E. (2019). Companion dog acquisition and mental well-being: A community-based three-arm controlled study. BMC Public Health, 19(1), 1428.", note: "Eight-month controlled study (n = 71): loneliness fell by an estimated 8.4 points at three months in the dog-acquisition group; positive affect did not change.", link: doi("10.1186/s12889-019-7770-5"), kind: "doi" },
      { cite: "Bao, K. J., & Schreer, G. (2016). Pets and happiness: Examining the association between pet ownership and wellbeing. Anthrozoös, 29(2), 283–296.", note: "Cross-sectional comparison of owners and non-owners on wellbeing measures — associations, not effects.", link: doi("10.1080/08927936.2016.1152721"), kind: "doi" },
      { cite: "Mubanga, M., Byberg, L., Nowak, C., Egenvall, A., Magnusson, P. K., Ingelsson, E., & Fall, T. (2017). Dog ownership and the risk of cardiovascular disease and death — a nationwide cohort study. Scientific Reports, 7(1), 15821.", note: "Register cohort of 3.4 million Swedes: dog ownership associated with lower all-cause and cardiovascular death, strongest in single-person households; twin analyses could not replicate the CVD finding.", link: doi("10.1038/s41598-017-16118-6"), kind: "doi" },
    ],
  },
  {
    id: "gs-happiness-w2-bright-light",
    goal: "happiness", tier: "moderate", section: "8353",
    title: "For a Winter Dip, Try Morning Bright Light for Four Weeks",
    subtitle: "Bright light is efficacious for seasonal depression and, in one well-designed trial, for nonseasonal depression too",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "low" },
    feeds: ["circadian regularity", "morning energy", "seasonal resilience"],
    description:
      "A meta-analysis of randomized trials found bright light treatment for seasonal affective disorder produced an effect size (0.84) comparable with antidepressant trials, and a later meta-analysis of randomized trials confirmed efficacy for seasonal depression. In an eight-week randomized trial in nonseasonal major depression, 30 minutes of 10,000-lux light each morning beat placebo (d = 0.80) and the combination with fluoxetine did best. The honest limit: a Cochrane review found the evidence for preventing seasonal episodes in advance is very low quality, so the case is for treating a dip, not for routine winter prophylaxis; anyone with bipolar disorder or eye disease should discuss light with a clinician first.",
    action: "From the first week you notice the seasonal slump, sit within arm's length of a 10,000-lux light box for 30 minutes each morning within an hour of waking for four weeks, keeping wake time fixed; note mood on a 0–10 scale weekly and stop if it does not move by week four.",
    sources: [
      { cite: "Golden, R. N., Gaynes, B. N., Ekstrom, R. D., Hamer, R. M., Jacobsen, F. M., Suppes, T., Wisner, K. L., & Nemeroff, C. B. (2005). The efficacy of light therapy in the treatment of mood disorders: A review and meta-analysis of the evidence. American Journal of Psychiatry, 162(4), 656–662.", note: "Meta-analysis of randomized trials: bright light for seasonal affective disorder (effect size 0.84) and for nonseasonal depression (0.53) both efficacious; light as an adjunct to medication was not.", link: doi("10.1176/appi.ajp.162.4.656"), kind: "doi" },
      { cite: "Lam, R. W., Levitt, A. J., Levitan, R. D., Michalak, E. E., Cheung, A. H., Morehouse, R., Ramasubbu, R., Yatham, L. N., & Tam, E. M. (2016). Efficacy of bright light treatment, fluoxetine, and the combination in patients with nonseasonal major depressive disorder: A randomized clinical trial. JAMA Psychiatry, 73(1), 56–63.", note: "Eight-week double-blind trial (n = 122): light monotherapy (d = 0.80) and light plus fluoxetine (d = 1.11) beat placebo; fluoxetine alone did not.", link: doi("10.1001/jamapsychiatry.2015.2235"), kind: "doi" },
      { cite: "Pjrek, E., Friedrich, M.-E., Cambioli, L., Dold, M., Jäger, F., Komorowski, A., Lanzenberger, R., Kasper, S., & Winkler, D. (2020). The efficacy of light therapy in the treatment of seasonal affective disorder: A meta-analysis of randomized controlled trials. Psychotherapy and Psychosomatics, 89(1), 17–24.", note: "Meta-analysis of randomized trials confirming bright light treatment for seasonal affective disorder.", link: doi("10.1159/000502891"), kind: "doi" },
      { cite: "Nussbaumer-Streit, B., Forneris, C. A., Morgan, L. C., Van Noord, M. G., Gaynes, B. N., Greenblatt, A., Wipplinger, J., Lux, L. J., Winkler, D., & Gartlehner, G. (2019). Light therapy for preventing seasonal affective disorder. Cochrane Database of Systematic Reviews, 3(3), CD011269.", note: "Cochrane review: evidence that light therapy prevents seasonal episodes before they start is very low quality — the honest limit on prophylactic use.", link: doi("10.1002/14651858.CD011269.pub3"), kind: "doi" },
    ],
  },
  {
    id: "gs-happiness-w2-alcohol-myth",
    goal: "happiness", tier: "fundamental", section: "8354",
    title: "Myth: A Drink Makes You Happier",
    subtitle: "Alcohol lifts mood for the hour and lowers wellbeing over the year; the risk threshold is lower than most people assume",
    evidenceTag: "Strong",
    impact: { magnitude: 1, latency: "days", durability: "transient", effort: "low" },
    callout: "Rated at the floor because the popular protocol — drink to feel better — is contradicted by the evidence. Momentary happiness rises while drinking, but drinking is not associated with higher life satisfaction, alcohol problems predict depression, and pooled data from 599,912 drinkers place the threshold for lowest mortality at roughly 100 g of alcohol a week.",
    feeds: ["sleep quality", "mood stability", "money"],
    description:
      "Using smartphone experience sampling, Geiger and MacKerron found drinking raises momentary happiness in the moment but shows no relationship with longer-run life satisfaction, and heavier drinkers are not more satisfied. A review of the alcohol–depression literature concluded that alcohol misuse increases the risk of major depression through a causal pathway. Combined analysis of individual-participant data from 83 prospective studies found all-cause mortality rising above about 100 g per week — well under many national guidelines. Reducing intake, per a systematic review of harm-reduction studies, improves physical and mental symptoms. The boundary: none of this is medical advice; anyone with dependence should reduce with clinical support.",
    action: "Track drinks for two weeks; if you exceed about seven standard drinks a week or use alcohol to manage mood, set two alcohol-free days and a per-occasion cap for the next month and re-rate mood and sleep at the end, and if you cannot hold the plan for a month talk to a clinician.",
    sources: [
      { cite: "Geiger, B. B., & MacKerron, G. (2016). Can alcohol make you happy? A subjective wellbeing approach. Social Science & Medicine, 156, 184–191.", note: "Experience-sampling data show alcohol raises happiness in the moment; panel data show no association with life satisfaction and worse outcomes for people developing drinking problems.", link: doi("10.1016/j.socscimed.2016.03.034"), kind: "doi" },
      { cite: "Wood, A. M., Kaptoge, S., Butterworth, A. S., Willeit, P., Warnakula, S., Bolton, T., et al. (2018). Risk thresholds for alcohol consumption: Combined analysis of individual-participant data for 599 912 current drinkers in 83 prospective studies. The Lancet, 391(10129), 1513–1523.", note: "Pooled individual-level analysis: the threshold for lowest all-cause mortality was about 100 g/week; higher intake shortened life expectancy at age 40.", link: doi("10.1016/S0140-6736(18)30134-X"), kind: "doi" },
      { cite: "Boden, J. M., & Fergusson, D. M. (2011). Alcohol and depression. Addiction, 106(5), 906–914.", note: "Review concluding that alcohol use disorders increase the risk of major depression via a causal pathway rather than the reverse.", link: doi("10.1111/j.1360-0443.2010.03351.x"), kind: "doi" },
      { cite: "Charlet, K., & Heinz, A. (2017). Harm reduction — a systematic review on effects of alcohol reduction on physical and mental symptoms. Addiction Biology, 22(5), 1119–1159.", note: "Systematic review showing that reducing alcohol intake, even without abstinence, improves physical and mental symptoms.", link: doi("10.1111/adb.12414"), kind: "doi" },
    ],
  },
  {
    id: "gs-happiness-w2-diet-smiles",
    goal: "happiness", tier: "advanced", section: "8355",
    title: "Run a 12-Week Mediterranean-Style Diet Overhaul With Dietitian Support",
    subtitle: "The SMILES trial and a 16-trial meta-analysis show dietary improvement reduces depressive symptoms, with small effects on anxiety",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "high" },
    feeds: ["energy", "sleep", "cardiometabolic health"],
    description:
      "SMILES randomized 67 adults with major depression to a dietitian-delivered Mediterranean-style diet or social support for 12 weeks; the diet group improved substantially more on the MADRS and a third reached remission. A meta-analysis of 16 randomized trials found dietary interventions significantly reduced depressive symptoms (small effect) with a larger effect in women, and non-significant effects on anxiety; a brief three-week diet intervention in young adults and a Mediterranean-plus-fish-oil trial replicated the direction. A meta-analysis of observational cohorts links adherence to healthy dietary indices with lower depression risk. The boundary: effects are modest, trials are small and not blinded, and diet is an adjunct to, not a replacement for, treatment of depression.",
    action: "Book two dietitian sessions this month and run a 12-week plan built on vegetables, legumes, whole grains, fish, olive oil and nuts while cutting ultra-processed food and sugary drinks; weigh nothing, but score mood weekly and re-assess at week 12.",
    sources: [
      { cite: "Jacka, F. N., O'Neil, A., Opie, R., Itsiopoulos, C., Cotton, S., Mohebbi, M., Castle, D., Dash, S., Mihalopoulos, C., Chatterton, M. L., Brazionis, L., Dean, O. M., Hodge, A. M., & Berk, M. (2017). A randomised controlled trial of dietary improvement for adults with major depression (the 'SMILES' trial). BMC Medicine, 15(1), 23.", note: "The SMILES trial: 12 weeks of dietitian-supported dietary improvement versus social support in adults with major depression, with greater MADRS improvement in the diet group.", link: doi("10.1186/s12916-017-0791-y"), kind: "doi" },
      { cite: "Firth, J., Marx, W., Dash, S., Carney, R., Teasdale, S. B., Solmi, M., Stubbs, B., Schuch, F. B., Carvalho, A. F., Jacka, F., & Sarris, J. (2019). The effects of dietary improvement on symptoms of depression and anxiety: A meta-analysis of randomized controlled trials. Psychosomatic Medicine, 81(3), 265–280.", note: "16 randomized trials: dietary interventions reduced depressive symptoms (small effect), with no significant effect on anxiety; larger effects in women and in trials delivered by dietitians.", link: doi("10.1097/PSY.0000000000000673"), kind: "doi" },
      { cite: "Lassale, C., Batty, G. D., Baghdadli, A., Jacka, F., Sánchez-Villegas, A., Kivimäki, M., & Akbaraly, T. (2019). Healthy dietary indices and risk of depressive outcomes: A systematic review and meta-analysis of observational studies. Molecular Psychiatry, 24(7), 965–986.", note: "Meta-analysis of observational studies linking adherence to healthy dietary patterns with lower risk of depressive outcomes.", link: doi("10.1038/s41380-018-0237-8"), kind: "doi" },
      { cite: "Francis, H. M., Stevenson, R. J., Chambers, J. R., Gupta, D., Newey, B., & Lim, C. K. (2019). A brief diet intervention can reduce symptoms of depression in young adults — A randomised controlled trial. PLoS One, 14(10), e0222768.", note: "Three-week diet intervention in young adults with elevated depressive symptoms produced lower depression scores than a control condition.", link: doi("10.1371/journal.pone.0222768"), kind: "doi" },
      { cite: "Parletta, N., Zarnowiecki, D., Cho, J., Wilson, A., Bogomolova, S., Villani, A., Itsiopoulos, C., Niyonsenga, T., Blunden, S., Meyer, B., Segal, L., Baune, B. T., & O'Dea, K. (2019). A Mediterranean-style dietary intervention supplemented with fish oil improves diet quality and mental health in people with depression: A randomized controlled trial (HELFIMED). Nutritional Neuroscience, 22(7), 474–487.", note: "Randomized trial of a Mediterranean-style diet with fish oil in people with depression reporting improved diet quality and mental health.", link: doi("10.1080/1028415X.2017.1411320"), kind: "doi" },
    ],
  },
  {
    id: "gs-happiness-w2-music-listening",
    goal: "happiness", tier: "fundamental", section: "8356",
    title: "Use Music Deliberately — 20 Minutes of Chosen Music for Stress, Daily",
    subtitle: "Meta-analyses find music interventions reduce stress with medium effects; music therapy adds to usual care for depression",
    evidenceTag: "Moderate",
    impact: { magnitude: 2, latency: "days", durability: "transient", effort: "low" },
    feeds: ["stress recovery", "mood regulation", "sleep onset"],
    description:
      "Two meta-analyses of music interventions found medium-sized reductions in physiological and psychological stress outcomes, and a Cochrane review found music therapy added to treatment as usual reduces depressive symptoms and anxiety. A systematic review of music and singing for wellbeing in adults and a review of music interventions for depression point the same way, while noting heterogeneity and short follow-ups. The boundary: most trials are brief and effects on mood are transient; passive background listening is not what was tested — chosen music, attended to, was.",
    action: "Pick a 20-minute playlist of music you find calming or uplifting and listen to it with full attention at the same point each day for three weeks — ideally the transition home from work or before bed — and rate tension before and after.",
    sources: [
      { cite: "de Witte, M., Spruit, A., van Hooren, S., Moonen, X., & Stams, G.-J. (2020). Effects of music interventions on stress-related outcomes: A systematic review and two meta-analyses. Health Psychology Review, 14(2), 294–324.", note: "Two meta-analyses: music interventions produced medium-sized reductions in physiological and psychological stress outcomes.", link: doi("10.1080/17437199.2019.1627897"), kind: "doi" },
      { cite: "Aalbers, S., Fusar-Poli, L., Freeman, R. E., Spreen, M., Ket, J. C., Vink, A. C., Maratos, A., Crawford, M., Chen, X.-J., & Gold, C. (2017). Music therapy for depression. Cochrane Database of Systematic Reviews, 11(11), CD004517.", note: "Cochrane review: music therapy plus treatment as usual reduces depressive symptoms and anxiety more than treatment as usual alone in the short term.", link: doi("10.1002/14651858.CD004517.pub3"), kind: "doi" },
      { cite: "Leubner, D., & Hinterberger, T. (2017). Reviewing the effectiveness of music interventions in treating depression. Frontiers in Psychology, 8, 1109.", note: "Review of music interventions for depression across trial designs and populations.", link: doi("10.3389/fpsyg.2017.01109"), kind: "doi" },
      { cite: "Daykin, N., Mansfield, L., Meads, C., Julier, G., Tomlinson, A., Payne, A., Grigsby Duffy, L., Lane, J., D'Innocenzo, G., Burnett, A., Kay, T., Dolan, P., Testoni, S., & Victor, C. (2018). What works for wellbeing? A systematic review of wellbeing outcomes for music and singing in adults. Perspectives in Public Health, 138(1), 39–46.", note: "Systematic review of wellbeing outcomes for music and singing in adults, summarizing where the evidence is strongest and where it is thin.", link: doi("10.1177/1757913917740391"), kind: "doi" },
    ],
  },
  {
    id: "gs-happiness-w2-laughter",
    goal: "happiness", tier: "fundamental", section: "8357",
    title: "Laughter Sessions Are Cheap and Low-Risk — Expect a Small Lift, Not a Cure",
    subtitle: "Simulated laughter (laughter yoga) shows small effects on depression in low-quality trials",
    evidenceTag: "Emerging",
    impact: { magnitude: 2, latency: "weeks", durability: "transient", effort: "low" },
    feeds: ["positive affect", "social ease"],
    description:
      "A systematic review and meta-analysis of laughter-inducing therapies found they can improve depression and that simulated (non-humorous) laughter outperformed humor-based laughter — but overall study quality was low with substantial risk of bias in all studies. A systematic review in older adults found every laughter intervention reported at least one positive wellbeing outcome while noting confounds and no measurement of actual laughter; a narrative review found few adverse effects. A feasibility protocol for a daily one-minute smartphone laughter prescription illustrates the direction of current work. The boundary: small, short-lived effects from weak trials; worth trying because it costs nothing, not because it is proven.",
    action: "Join a weekly laughter-yoga or improv-style laughter group for six weeks, or record a one-minute clip of your own laughter and play and join it three times a day for two weeks; treat it as a mood experiment and keep it only if your weekly mood rating moves.",
    sources: [
      { cite: "van der Wal, C. N., & Kok, R. N. (2019). Laughter-inducing therapies: Systematic review and meta-analysis. Social Science & Medicine, 232, 473–488.", note: "Meta-analysis of randomized and quasi-experimental studies: laughter therapies can improve depression and simulated laughter outperformed humorous laughter; study quality low.", link: doi("10.1016/j.socscimed.2019.02.018"), kind: "doi" },
      { cite: "Gonot-Schoupinsky, F. N., & Garip, G. (2018). Laughter and humour interventions for well-being in older adults: A systematic review and intervention classification. Complementary Therapies in Medicine, 38, 85–91.", note: "Five laughter interventions (369 participants) all showed at least one positive wellbeing effect; confounds and lack of laughter measurement limit the inference.", link: doi("10.1016/j.ctim.2018.04.009"), kind: "doi" },
      { cite: "Gonot-Schoupinsky, F. N., Garip, G., Sheffield, D., Omar, O. M., & Arora, T. (2020). Prescribing laughter to ameliorate mental health, sleep, and wellbeing in university students: A protocol for a feasibility study of a randomised controlled trial. Contemporary Clinical Trials Communications, 20, 100676.", note: "Protocol for a randomized feasibility trial of a two-week daily laughter prescription using a one-minute self-recorded laugh, with actigraphy sleep outcomes.", link: doi("10.1016/j.conctc.2020.100676"), kind: "doi" },
      { cite: "Mora-Ripoll, R. (2011). Potential health benefits of simulated laughter: A narrative review of the literature and recommendations for future research. Complementary Therapies in Medicine, 19(3), 170–177.", note: "Narrative review finding limited but suggestive evidence for simulated laughter with very few adverse effects.", link: doi("10.1016/j.ctim.2011.05.003"), kind: "doi" },
    ],
  },
  {
    id: "gs-happiness-w2-self-compassion",
    goal: "happiness", tier: "moderate", section: "8358",
    title: "Take an Eight-Week Mindful Self-Compassion Course",
    subtitle: "Self-compassion correlates strongly with wellbeing and inversely with psychopathology; randomized trials of interventions show moderate gains",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "moderate" },
    feeds: ["emotion regulation", "resilience after failure", "reduced rumination"],
    description:
      "Neff defined self-compassion as kindness toward oneself, common humanity and mindfulness in the face of failure. Meta-analyses find it correlates with wellbeing at r = .47 across 79 samples and with psychopathology at r = −.54, and a meta-analysis of randomized trials of self-compassion interventions found moderate effects on self-compassion, depression, anxiety and stress. The eight-week Mindful Self-Compassion program produced larger gains than a waitlist in a randomized trial, with effects maintained at one year. The boundary: most trials are small, self-report based and compare against waitlists; effects are real but moderate.",
    action: "Enroll in an eight-week Mindful Self-Compassion course (in person or online) and do the daily 10–15 minute practices; between sessions, when you catch self-criticism after a mistake, write three sentences answering how you would speak to a friend in the same spot.",
    sources: [
      { cite: "Neff, K. (2003). Self-compassion: An alternative conceptualization of a healthy attitude toward oneself. Self and Identity, 2(2), 85–101.", note: "The founding conceptual paper defining self-compassion and its three components.", link: doi("10.1080/15298860309032"), kind: "doi" },
      { cite: "Zessin, U., Dickhäuser, O., & Garbade, S. (2015). The relationship between self-compassion and well-being: A meta-analysis. Applied Psychology: Health and Well-Being, 7(3), 340–364.", note: "79 samples (N = 16,416): overall correlation between self-compassion and wellbeing of r = .47, stronger for cognitive and psychological than affective wellbeing.", link: doi("10.1111/aphw.12051"), kind: "doi" },
      { cite: "MacBeth, A., & Gumley, A. (2012). Exploring compassion: A meta-analysis of the association between self-compassion and psychopathology. Clinical Psychology Review, 32(6), 545–552.", note: "Meta-analysis of 20 samples: large inverse association between self-compassion and psychopathology (r = −.54).", link: doi("10.1016/j.cpr.2012.06.003"), kind: "doi" },
      { cite: "Ferrari, M., Hunt, C., Harrysunker, A., Abbott, M. J., Beath, A. P., & Einstein, D. A. (2019). Self-compassion interventions and psychosocial outcomes: A meta-analysis of RCTs. Mindfulness, 10(8), 1455–1473.", note: "Meta-analysis of randomized trials of self-compassion interventions reporting moderate effects across psychosocial outcomes.", link: doi("10.1007/s12671-019-01134-6"), kind: "doi" },
      { cite: "Neff, K. D., & Germer, C. K. (2013). A pilot study and randomized controlled trial of the mindful self-compassion program. Journal of Clinical Psychology, 69(1), 28–44.", note: "Randomized waitlist-controlled trial of the eight-week Mindful Self-Compassion program with gains in self-compassion, mindfulness and wellbeing maintained at 6 and 12 months.", link: doi("10.1002/jclp.21923"), kind: "doi" },
    ],
  },
  {
    id: "gs-happiness-w2-act",
    goal: "happiness", tier: "advanced", section: "8359",
    title: "Do a Course of Acceptance and Commitment Therapy When Avoidance Is Running Your Life",
    subtitle: "ACT outperforms waitlist and treatment as usual and matches CBT across anxiety, depression and health problems",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "months", durability: "lasting", effort: "high" },
    feeds: ["psychological flexibility", "values-based action", "tolerance of discomfort"],
    description:
      "ACT trains psychological flexibility — noticing thoughts without obeying them and acting on chosen values even while uncomfortable. A meta-analysis of 39 randomized trials found ACT outperformed control conditions (g = 0.57) and treatment as usual, with no significant difference from CBT; an updated systematic review reached broadly similar conclusions while criticizing methodological quality, and a 2020 review of 20 meta-analyses summarizes the field. The founding review lays out the model and its processes. The boundary: ACT is a therapy, best delivered by a trained clinician over weeks to months; self-help versions exist but the trial evidence is mainly for guided delivery.",
    action: "Find a therapist trained in ACT and commit to 8–12 sessions; before the first session write down your five most important values and the three things you have been avoiding because of anxiety, low mood or discomfort.",
    sources: [
      { cite: "Hayes, S. C., Luoma, J. B., Bond, F. W., Masuda, A., & Lillis, J. (2006). Acceptance and commitment therapy: Model, processes and outcomes. Behaviour Research and Therapy, 44(1), 1–25.", note: "Foundational review of the ACT model of psychopathology and treatment and the early outcome evidence.", link: doi("10.1016/j.brat.2005.06.006"), kind: "doi" },
      { cite: "A-Tjak, J. G. L., Davis, M. L., Morina, N., Powers, M. B., Smits, J. A. J., & Emmelkamp, P. M. G. (2015). A meta-analysis of the efficacy of acceptance and commitment therapy for clinically relevant mental and physical health problems. Psychotherapy and Psychosomatics, 84(1), 30–36.", note: "39 randomized trials (1,821 patients): ACT beat controls (g = 0.57) and treatment as usual (g = 0.64), with no significant difference from CBT.", link: doi("10.1159/000365764"), kind: "doi" },
      { cite: "Öst, L.-G. (2014). The efficacy of Acceptance and Commitment Therapy: An updated systematic review and meta-analysis. Behaviour Research and Therapy, 61, 105–121.", note: "Updated systematic review and meta-analysis of ACT trials, critical of methodological quality while confirming efficacy relative to controls.", link: doi("10.1016/j.brat.2014.07.018"), kind: "doi" },
      { cite: "Gloster, A. T., Walder, N., Levin, M. E., Twohig, M. P., & Karekla, M. (2020). The empirical status of acceptance and commitment therapy: A review of meta-analyses. Journal of Contextual Behavioral Science, 18, 181–192.", note: "Review of 20 meta-analyses of ACT summarizing efficacy across conditions and comparators.", link: doi("10.1016/j.jcbs.2020.09.009"), kind: "doi" },
    ],
  },
  {
    id: "gs-happiness-w2-problem-solving-therapy",
    goal: "happiness", tier: "advanced", section: "8360",
    title: "Learn Problem-Solving Therapy — Especially if Low Mood Comes From Real, Solvable Problems",
    subtitle: "PST is effective for adult depression with effects comparable with other psychotherapies; the full package beats skills-only training",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "moderate" },
    feeds: ["problem orientation", "decision-making", "agency"],
    description:
      "Problem-solving therapy trains a positive problem orientation plus four skills — defining the problem, generating alternatives, deciding, implementing and verifying. A meta-analysis of 30 randomized trials (3,530 patients) found PST effective versus controls, with effects in low-risk-of-bias trials (g = 0.34) comparable with other psychotherapies; an earlier meta-analysis found PST worked best when training included problem orientation and all four skills. In a randomized trial with 75 older adults with major depression, 12 weekly group PST sessions beat both reminiscence therapy and a waitlist. The boundary: effects are small to moderate, heterogeneity is high, and researcher allegiance inflates some comparisons.",
    action: "Work through a manualized PST course with a therapist or a structured self-help workbook over 6–8 weeks; each week pick one concrete problem, write the definition, at least five options, the decision and the implementation date, and review it the following week.",
    sources: [
      { cite: "Cuijpers, P., de Wit, L., Kleiboer, A., Karyotaki, E., & Ebert, D. D. (2018). Problem-solving therapy for adult depression: An updated meta-analysis. European Psychiatry, 48, 27–37.", note: "30 randomized trials: PST versus controls g = 0.79 overall, g = 0.34 in low-risk-of-bias studies — comparable with other psychotherapies for depression.", link: doi("10.1016/j.eurpsy.2017.11.006"), kind: "doi" },
      { cite: "Bell, A. C., & D'Zurilla, T. J. (2009). Problem-solving therapy for depression: A meta-analysis. Clinical Psychology Review, 29(4), 348–353.", note: "Meta-analysis of 21 samples: PST as effective as other psychosocial therapies and medication, and more effective when it trains positive problem orientation plus all four skills.", link: doi("10.1016/j.cpr.2009.02.003"), kind: "doi" },
      { cite: "Arean, P. A., Perri, M. G., Nezu, A. M., Schein, R. L., Christopher, F., & Joseph, T. X. (1993). Comparative effectiveness of social problem-solving therapy and reminiscence therapy as treatments for depression in older adults. Journal of Consulting and Clinical Psychology, 61(6), 1003–1010.", note: "Randomized trial (n = 75): 12 weekly group PST sessions reduced depression more than reminiscence therapy and a waiting-list control.", link: doi("10.1037//0022-006x.61.6.1003"), kind: "doi" },
      { cite: "Huang, C., Fang, Y., Yan, F., et al. (2024). Efficacy of problem-solving therapy in treating late-life depression with potential cognitive impairment. BMJ Open, 14(10), e084130.", note: "Recent trial-based evaluation of PST for late-life depression in people with possible cognitive impairment — a population where structured, skills-based therapy is attractive.", link: doi("10.1136/bmjopen-2024-084130"), kind: "doi" },
    ],
  },
  {
    id: "gs-happiness-w2-cbt-insomnia",
    goal: "happiness", tier: "elite", section: "8361",
    title: "If You Sleep Badly, Treat the Insomnia With CBT-I Before Anything Else on This Shelf",
    subtitle: "CBT-I is the first-line treatment for chronic insomnia and, in a 3,755-person randomized trial, improving sleep reduced depression, anxiety and paranoia",
    evidenceTag: "Strong",
    impact: { magnitude: 5, latency: "weeks", durability: "lasting", effort: "moderate" },
    feeds: ["sleep", "mood", "daytime energy", "anxiety"],
    description:
      "Meta-analyses of randomized trials find cognitive and behavioural therapies for insomnia produce clinically meaningful, durable improvements in sleep onset, wake after sleep onset and sleep efficiency; a network meta-analysis finds they also improve daytime symptoms and depressive and fatigue symptoms. OASIS randomized 3,755 university students with insomnia to digital CBT-I or usual practice: sleep improved and the improvement mediated reductions in paranoia, hallucinations, depression and anxiety. The GoodNight trial found an online insomnia program reduced depressive symptoms at six weeks. This is placed at the elite tier because, when insomnia is present, it is the single highest-leverage move on the shelf. The boundary: it requires several weeks of sleep restriction that feels worse before it feels better; discuss with a clinician if you have bipolar disorder, seizures or drive for a living.",
    action: "If you take more than 30 minutes to fall asleep or lie awake at night three or more nights a week for three months, start a six-session CBT-I program (a trained clinician or an evidence-based digital program) this month, keep a sleep diary, hold a fixed wake time seven days a week and follow the sleep-restriction schedule exactly for six weeks.",
    sources: [
      { cite: "van Straten, A., van der Zweerde, T., Kleiboer, A., Cuijpers, P., Morin, C. M., & Lancee, J. (2018). Cognitive and behavioral therapies in the treatment of insomnia: A meta-analysis. Sleep Medicine Reviews, 38, 3–16.", note: "Meta-analysis of randomized trials of cognitive and behavioural therapies for insomnia showing large improvements in insomnia severity and sleep parameters.", link: doi("10.1016/j.smrv.2017.02.001"), kind: "doi" },
      { cite: "Trauer, J. M., Qian, M. Y., Doyle, J. S., Rajaratnam, S. M. W., & Cunnington, D. (2015). Cognitive behavioral therapy for chronic insomnia: A systematic review and meta-analysis. Annals of Internal Medicine, 163(3), 191–204.", note: "Systematic review and meta-analysis establishing CBT-I as effective for chronic insomnia with improvements maintained after treatment ends.", link: doi("10.7326/M14-2841"), kind: "doi" },
      { cite: "Benz, F., Knoop, T., Ballesio, A., Bacaro, V., Johann, A. F., Rücker, G., Feige, B., Riemann, D., & Baglioni, C. (2020). The efficacy of cognitive and behavior therapies for insomnia on daytime symptoms: A systematic review and network meta-analysis. Clinical Psychology Review, 80, 101873.", note: "Network meta-analysis showing cognitive and behavioural insomnia therapies improve daytime symptoms, not only sleep.", link: doi("10.1016/j.cpr.2020.101873"), kind: "doi" },
      { cite: "Ballesio, A., Aquino, M. R. J. V., Feige, B., Johann, A. F., Kyle, S. D., Spiegelhalder, K., Lombardo, C., Rücker, G., Riemann, D., & Baglioni, C. (2018). The effectiveness of behavioural and cognitive behavioural therapies for insomnia on depressive and fatigue symptoms: A systematic review and network meta-analysis. Sleep Medicine Reviews, 37, 114–129.", note: "Network meta-analysis: insomnia therapies reduce depressive and fatigue symptoms — the mood dividend of treating sleep.", link: doi("10.1016/j.smrv.2017.01.006"), kind: "doi" },
      { cite: "Freeman, D., Sheaves, B., Goodwin, G. M., Yu, L.-M., Nickless, A., Harrison, P. J., et al. (2017). The effects of improving sleep on mental health (OASIS): A randomised controlled trial with mediation analysis. The Lancet Psychiatry, 4(10), 749–758.", note: "3,755 students randomized to digital CBT-I or usual practice: improved sleep mediated reductions in paranoia, hallucinations, depression and anxiety.", link: doi("10.1016/S2215-0366(17)30328-0"), kind: "doi" },
      { cite: "Christensen, H., Batterham, P. J., Gosling, J. A., Ritterband, L. M., Griffiths, K. M., Thorndike, F. P., Glozier, N., O'Dea, B., Hickie, I. B., & Mackinnon, A. J. (2016). Effectiveness of an online insomnia program (SHUTi) for prevention of depressive episodes (the GoodNight Study): A randomised controlled trial. The Lancet Psychiatry, 3(4), 333–341.", note: "Randomized trial of an online CBT-I program in adults with insomnia and subclinical depression: lower depressive symptoms at six weeks and six months.", link: doi("10.1016/S2215-0366(15)00536-2"), kind: "doi" },
    ],
  },
  {
    id: "gs-happiness-w2-social-media-reduction",
    goal: "happiness", tier: "fundamental", section: "8362",
    title: "Cap Social Media at 30 Minutes a Day, or Take a Full Week Off",
    subtitle: "Randomized trials of limiting or deactivating social media find lower loneliness, depression and anxiety and higher wellbeing",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "low" },
    feeds: ["attention", "sleep", "comparison-free mood"],
    description:
      "Hunt and colleagues randomized 143 students to limit Facebook, Instagram and Snapchat to 10 minutes per platform per day for three weeks and found reduced loneliness and depression versus usual use. Allcott and colleagues paid 1,661 U.S. adults to deactivate Facebook for the four weeks before the 2018 midterms: subjective wellbeing improved and post-experiment use fell. A one-week Facebook break in 1,095 Danes raised life satisfaction and positive emotion, most for heavy, passive and envious users; a one-week break from four platforms in 154 adults improved wellbeing, depression and anxiety; a 20-minute-a-day Facebook reduction improved wellbeing and lifestyle. The boundary: samples are mostly young, self-report dominates, and effects are moderate — the trials tested limiting, not abstaining forever.",
    action: "For the next three weeks set a 30-minute daily cap across all social apps using your phone's screen-time tools, move the apps off your home screen, and do one full seven-day break during the month; rate loneliness and mood weekly.",
    sources: [
      { cite: "Hunt, M. G., Marx, R., Lipson, C., & Young, J. (2018). No more FOMO: Limiting social media decreases loneliness and depression. Journal of Social and Clinical Psychology, 37(10), 751–768.", note: "Randomized three-week trial: limiting social media to 10 minutes per platform per day reduced loneliness and depression compared with usual use.", link: doi("10.1521/jscp.2018.37.10.751"), kind: "doi" },
      { cite: "Allcott, H., Braghieri, L., Eichmeyer, S., & Gentzkow, M. (2020). The welfare effects of social media. American Economic Review, 110(3), 629–676.", note: "Randomized four-week Facebook deactivation in 1,661 U.S. adults improved subjective wellbeing and reduced post-experiment use.", link: doi("10.1257/aer.20190658"), kind: "doi" },
      { cite: "Tromholt, M. (2016). The Facebook experiment: Quitting Facebook leads to higher levels of well-being. Cyberpsychology, Behavior, and Social Networking, 19(11), 661–666.", note: "One-week experiment with 1,095 participants: a Facebook break increased life satisfaction and positive emotions, especially for heavy, passive and envious users.", link: doi("10.1089/cyber.2016.0259"), kind: "doi" },
      { cite: "Brailovskaia, J., Ströse, F., Schillack, H., & Margraf, J. (2020). Less Facebook use — More well-being and a healthier lifestyle? An experimental intervention study. Computers in Human Behavior, 108, 106332.", note: "Experimental intervention reducing daily Facebook use by 20 minutes for two weeks with gains in wellbeing and lifestyle measures.", link: doi("10.1016/j.chb.2020.106332"), kind: "doi" },
      { cite: "Lambert, J., Barnstable, G., Minter, E., Cooper, J., & McEwan, D. (2022). Taking a one-week break from social media improves well-being, depression, and anxiety: A randomized controlled trial. Cyberpsychology, Behavior, and Social Networking, 25(5), 287–293.", note: "154 adults randomized to a one-week break from Facebook, Instagram, Twitter and TikTok: better wellbeing, depression and anxiety at one week.", link: doi("10.1089/cyber.2021.0324"), kind: "doi" },
    ],
  },
  {
    id: "gs-happiness-w2-news-diet",
    goal: "happiness", tier: "fundamental", section: "8363",
    title: "Put the News on a Schedule — Once a Day, Not All Day",
    subtitle: "Negative news bulletins raise anxiety and catastrophizing of personal worries; daily news exposure tracks negative affect",
    evidenceTag: "Moderate",
    impact: { magnitude: 2, latency: "days", durability: "sustained", effort: "low" },
    feeds: ["attention", "calm", "civic knowledge kept"],
    description:
      "In a classic experiment, watching a negative TV news bulletin increased anxious and sad mood and led people to catastrophize their own unrelated worries. A ten-day experience-sampling study found that negative news perceptions were followed by more negative and less positive affect, moderated by personal relevance; a panel study linked some forms of news consumption with poorer wellbeing over time, and a 2026 cross-sectional study tied COVID-19 news consumption to mental-health complaints. The boundary: effects are modest, the causal evidence is mostly short-term and experimental, and total avoidance carries a civic cost — the protocol is scheduling, not abstinence.",
    action: "Turn off news push notifications, remove news apps from your phone's home screen, and read or watch the news once a day at a fixed time for no more than 20 minutes for the next month; keep a subscription to one outlet you trust so you stay informed.",
    sources: [
      { cite: "Johnston, W. M., & Davey, G. C. L. (1997). The psychological impact of negative TV news bulletins: The catastrophizing of personal worries. British Journal of Psychology, 88(1), 85–91.", note: "Experiment: a negative news bulletin increased anxious and sad mood and made participants catastrophize personal worries unrelated to the news.", link: doi("10.1111/j.2044-8295.1997.tb02622.x"), kind: "doi" },
      { cite: "de Hoog, N., & Verboon, P. (2020). Is the news making us unhappy? The influence of daily news exposure on emotional states. British Journal of Psychology, 111(2), 157–173.", note: "Ten-day ecological momentary assessment (63 adults): negative news perceptions related to more negative and less positive affect, moderated by personal relevance.", link: doi("10.1111/bjop.12389"), kind: "doi" },
      { cite: "Boukes, M., & Vliegenthart, R. (2017). News consumption and its unpleasant side effect. Journal of Media Psychology, 29(3), 137–147.", note: "Panel study of hard and soft news exposure and mental wellbeing over time.", link: doi("10.1027/1864-1105/a000224"), kind: "doi" },
      { cite: "Rahaman, H. M. S., & Samad, R. (2026). How and when COVID-19-related news consumption relates to mental health complaints — A cross-sectional study. Health Science Reports, 9(8), e72999.", note: "Cross-sectional study relating pandemic news consumption to mental-health complaints and the conditions under which the link is strongest.", link: doi("10.1002/hsr2.72999"), kind: "doi" },
    ],
  },
  {
    id: "gs-happiness-w2-awe-walks",
    goal: "happiness", tier: "fundamental", section: "8364",
    title: "Take a Weekly 15-Minute Awe Walk",
    subtitle: "An eight-week randomized trial in older adults found awe walks raised prosocial positive emotion and lowered daily distress",
    evidenceTag: "Moderate",
    impact: { magnitude: 2, latency: "weeks", durability: "sustained", effort: "low" },
    feeds: ["small self", "daily positive emotion", "stress perspective"],
    description:
      "Sixty older adults were randomized to weekly 15-minute outdoor awe walks or control walks for eight weeks; awe walkers reported more joy and prosocial positive emotion during walks, their selfies showed an increasingly small self, and their daily distress fell — though anxiety, depression and life-satisfaction questionnaires did not change. Six further studies link awe to lower daily stress and higher life satisfaction, awe in nature predicted wellbeing gains in veterans and youth, daily awe tracked lower stress and somatic symptoms over 22 days, and a brief online awe intervention reduced depressive symptoms in a randomized trial with long-COVID patients. The boundary: samples are small and mostly self-report; the trial evidence is promising rather than settled.",
    action: "Once a week for eight weeks, take a 15-minute walk somewhere with vastness — trees, water, a skyline, a big sky — phone silenced, and deliberately turn attention outward to what is larger than you; take one photo at the end and note how you felt.",
    sources: [
      { cite: "Sturm, V. E., Datta, S., Roy, A. R. K., Sible, I. J., Kosik, E. L., Veziris, C. R., Chow, T. E., Morris, N. A., Neuhaus, J., Kramer, J. H., Miller, B. L., Holley, S. R., & Keltner, D. (2022). Big smile, small self: Awe walks promote prosocial positive emotions in older adults. Emotion, 22(5), 1044–1058.", note: "Eight-week randomized trial (n = 60): weekly awe walks increased prosocial positive emotions and reduced daily distress versus control walks; clinical questionnaires did not change.", link: doi("10.1037/emo0000876"), kind: "doi" },
      { cite: "Monroy, M., & Keltner, D. (2023). Awe as a pathway to mental and physical health. Perspectives on Psychological Science, 18(2), 309–320.", note: "Review proposing five processes through which awe benefits wellbeing — neurophysiological shifts, diminished self-focus, prosociality, social integration and meaning.", link: doi("10.1177/17456916221094856"), kind: "doi" },
      { cite: "Bai, Y., Ocampo, J., Jin, G., Chen, S., Benet-Martinez, V., Monroy, M., Anderson, C., & Keltner, D. (2021). Awe, daily stress, and elevated life satisfaction. Journal of Personality and Social Psychology, 120(4), 837–860.", note: "Six studies: trait and induced awe associated with lower daily stress and, through it, higher life satisfaction; a naturalistic tower-top awe induction reduced daily stress.", link: doi("10.1037/pspa0000267"), kind: "doi" },
      { cite: "Anderson, C. L., Monroy, M., & Keltner, D. (2018). Awe in nature heals: Evidence from military veterans, at-risk youth, and college students. Emotion, 18(8), 1195–1202.", note: "Awe during whitewater rafting predicted wellbeing and stress-symptom improvements a week later; everyday nature experiences improved wellbeing via awe.", link: doi("10.1037/emo0000442"), kind: "doi" },
      { cite: "Piff, P. K., Dietze, P., Feinberg, M., Stancato, D. M., & Keltner, D. (2015). Awe, the small self, and prosocial behavior. Journal of Personality and Social Psychology, 108(6), 883–899.", note: "Five studies (N = 2,078): awe diminishes the individual self and increases prosocial behaviour, including in a grove of towering trees.", link: doi("10.1037/pspi0000018"), kind: "doi" },
      { cite: "Rudd, M., Vohs, K. D., & Aaker, J. (2012). Awe expands people's perception of time, alters decision making, and enhances well-being. Psychological Science, 23(10), 1130–1136.", note: "Three experiments: awe made people feel time-rich, less impatient and more satisfied with life.", link: doi("10.1177/0956797612438731"), kind: "doi" },
      { cite: "Monroy, M., Uğurlu, Ö., Zerwas, F., Corona, R., Keltner, D., Eagle, J., & Amster, M. (2023). The influences of daily experiences of awe on stress, somatic health, and well-being: A longitudinal study during COVID-19. Scientific Reports, 13(1), 9336.", note: "22-day diary in community adults and healthcare workers: more daily awe went with less stress, fewer somatic symptoms and greater wellbeing.", link: doi("10.1038/s41598-023-35200-w"), kind: "doi" },
      { cite: "Monroy, M., Amster, M., Eagle, J., Zerwas, F. K., Keltner, D., & López, J. E. (2025). Awe reduces depressive symptoms and improves well-being in a randomized-controlled clinical trial. Scientific Reports, 15(1), 16453.", note: "Randomized trial of a brief online awe intervention in long-COVID patients: lower stress and depressive symptoms and higher wellbeing (d = 0.78–0.96).", link: doi("10.1038/s41598-025-96555-w"), kind: "doi" },
    ],
  },
  {
    id: "gs-happiness-w2-expressive-writing-honest",
    goal: "happiness", tier: "fundamental", section: "8365",
    title: "Expressive Writing: Three 20-Minute Sessions, Small Benefit, No Substitute for Therapy",
    subtitle: "Meta-analyses find small average effects of writing about emotional experiences; depression effects are small",
    evidenceTag: "Mixed",
    impact: { magnitude: 2, latency: "weeks", durability: "transient", effort: "low" },
    feeds: ["emotional processing", "clarity"],
    description:
      "Pennebaker's paradigm — writing about an upsetting experience for 15–20 minutes on three or four days — produced health benefits in early studies, and a 1998 meta-analysis found a modest overall effect. Frattaroli's meta-analysis of 146 studies found a small but reliable effect (r = .075) with strong moderation by dose, setting and follow-up; a meta-analysis of effects on depressive symptoms found small effects, and a review in adolescents found a small overall effect (g = 0.13) that was larger with more sessions. The boundary: expressive writing helps a little for some people, can transiently increase distress, and is not a treatment for depression.",
    action: "On three consecutive days this month, write continuously for 20 minutes about the most stressful thing on your mind — thoughts and feelings, not just events — then stop; expect to feel a little worse that evening and somewhat better a week later, and do not repeat it more than once a season.",
    sources: [
      { cite: "Frattaroli, J. (2006). Experimental disclosure and its moderators: A meta-analysis. Psychological Bulletin, 132(6), 823–865.", note: "146 studies: a small but reliable overall effect of experimental disclosure with moderators including dose, privacy and outcome timing.", link: doi("10.1037/0033-2909.132.6.823"), kind: "doi" },
      { cite: "Smyth, J. M. (1998). Written emotional expression: Effect sizes, outcome types, and moderating variables. Journal of Consulting and Clinical Psychology, 66(1), 174–184.", note: "Early meta-analysis of written emotional expression reporting a modest average effect across outcome types.", link: doi("10.1037/0022-006X.66.1.174"), kind: "doi" },
      { cite: "Reinhold, M., Bürkner, P.-C., & Holling, H. (2018). Effects of expressive writing on depressive symptoms — A meta-analysis. Clinical Psychology: Science and Practice, 25(1), e12224.", note: "Meta-analysis of expressive writing effects on depressive symptoms: small effects, not a substitute for psychotherapy.", link: doi("10.1037/h0101749"), kind: "doi" },
      { cite: "Travagin, G., Margola, D., & Revenson, T. A. (2015). How effective are expressive writing interventions for adolescents? A meta-analytic review. Clinical Psychology Review, 36, 42–55.", note: "21 studies in adolescents: small overall effect (g = 0.13), larger with a higher number and spacing of sessions.", link: doi("10.1016/j.cpr.2015.01.003"), kind: "doi" },
      { cite: "Pennebaker, J. W. (1997). Writing about emotional experiences as a therapeutic process. Psychological Science, 8(3), 162–166.", note: "The originator's summary of the expressive-writing paradigm and its early evidence.", link: doi("10.1111/j.1467-9280.1997.tb00403.x"), kind: "doi" },
    ],
  },
  {
    id: "gs-happiness-w2-strengths-use",
    goal: "happiness", tier: "moderate", section: "8366",
    title: "Use a Signature Strength in a New Way Each Day for a Week — and Keep Expectations Modest",
    subtitle: "Strengths use predicts wellbeing gains over time and interventions show small-to-moderate effects; benefits fade without repetition",
    evidenceTag: "Moderate",
    impact: { magnitude: 2, latency: "weeks", durability: "transient", effort: "low" },
    feeds: ["engagement", "self-efficacy"],
    description:
      "In a longitudinal study, using personal strengths predicted increases in wellbeing over three and six months. A meta-analysis of signature-strengths interventions found small-to-moderate benefits on wellbeing and depression, and a randomized placebo-controlled online trial found using either signature or lesser strengths in new ways raised happiness for up to three months and reduced depressive symptoms in the short term. A literature review of strengths interventions concludes the outcomes are positive but the evidence base is young and reliant on self-report and short follow-up. The boundary: these are small, transient effects from brief online exercises — useful as a weekly habit, not a transformation.",
    action: "Take a free character-strengths survey, pick your top strength, and for seven days use it in a way you have not before (a new setting, a new person, a new task); at the end of the week choose one use to keep as a weekly ritual.",
    sources: [
      { cite: "Wood, A. M., Linley, P. A., Maltby, J., Kashdan, T. B., & Hurling, R. (2011). Using personal and psychological strengths leads to increases in well-being over time: A longitudinal study and the development of the strengths use questionnaire. Personality and Individual Differences, 50(1), 15–19.", note: "Longitudinal study: strengths use predicted increases in wellbeing at three and six months, independent of baseline wellbeing.", link: doi("10.1016/j.paid.2010.08.004"), kind: "doi" },
      { cite: "Schutte, N. S., & Malouff, J. M. (2019). The impact of signature character strengths interventions: A meta-analysis. Journal of Happiness Studies, 20(4), 1179–1196.", note: "Meta-analysis of signature-strengths interventions finding small-to-moderate improvements in wellbeing and reductions in depression.", link: doi("10.1007/s10902-018-9990-2"), kind: "doi" },
      { cite: "Proyer, R. T., Gander, F., Wellenzohn, S., & Ruch, W. (2015). Strengths-based positive psychology interventions: A randomized placebo-controlled online trial on long-term effects for a signature strengths- vs. a lesser strengths-intervention. Frontiers in Psychology, 6, 456.", note: "375 adults randomized: using signature or lesser strengths in new ways increased happiness for up to three months and reduced depressive symptoms short-term versus placebo.", link: doi("10.3389/fpsyg.2015.00456"), kind: "doi" },
      { cite: "Ghielen, S. T. S., van Woerkom, M., & Christina Meyers, M. (2018). Promoting positive outcomes through strengths interventions: A literature review. The Journal of Positive Psychology, 13(6), 573–585.", note: "Literature review of strengths interventions summarizing positive outcomes alongside methodological limits.", link: doi("10.1080/17439760.2017.1365164"), kind: "doi" },
    ],
  },
  {
    id: "gs-happiness-w2-goal-progress-system",
    goal: "happiness", tier: "elite", section: "8367",
    title: "Build a Multi-Year Goal System: Self-Concordant Goals, Written Plans, Weekly Progress Checks",
    subtitle: "Progress on personal goals predicts wellbeing in longitudinal studies and a meta-analysis; self-concordance plus implementation intentions drives attainment",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "months", durability: "lasting", effort: "high" },
    feeds: ["meaning", "agency", "self-efficacy"],
    description:
      "Brunstein's longitudinal study found that progress toward personal goals — not merely having them — predicted later wellbeing, and a meta-analysis confirmed a robust link between goal progress and subjective wellbeing. Goals that are self-concordant (chosen for interest and value rather than pressure) and backed by implementation intentions are attained more often; low goal ambivalence explains part of why self-concordant goals raise wellbeing, and in couples one partner's progress raises the other's satisfaction. Progress also helps most when initial confidence is low, and believing willpower is limited undermines both progress and wellbeing. The boundary: correlational and longitudinal designs dominate; the mechanism is well supported, the exact protocol is a synthesis.",
    action: "Write three goals for the next 12–36 months that you would pursue even if no one knew, each with a why, a first step this week, and an if-then plan for the most likely obstacle; review progress for 15 minutes every Sunday and re-plan quarterly, keeping the goals that still feel like yours and dropping the ones that feel imposed.",
    sources: [
      { cite: "Brunstein, J. C. (1993). Personal goals and subjective well-being: A longitudinal study. Journal of Personality and Social Psychology, 65(5), 1061–1070.", note: "Longitudinal study showing perceived progress toward personal goals predicted subsequent subjective wellbeing.", link: doi("10.1037/0022-3514.65.5.1061"), kind: "doi" },
      { cite: "Klug, H. J. P., & Maier, G. W. (2015). Linking goal progress and subjective well-being: A meta-analysis. Journal of Happiness Studies, 16(1), 37–65.", note: "Meta-analysis establishing a positive association between goal progress and subjective wellbeing across studies.", link: doi("10.1007/s10902-013-9493-0"), kind: "doi" },
      { cite: "Koestner, R., Lekes, N., Powers, T. A., & Chicoine, E. (2002). Attaining personal goals: Self-concordance plus implementation intentions equals success. Journal of Personality and Social Psychology, 83(1), 231–244.", note: "Self-concordant goals combined with implementation intentions produced the highest goal attainment.", link: doi("10.1037/0022-3514.83.1.231"), kind: "doi" },
      { cite: "Koletzko, S. H., Herrmann, M., & Brandstätter, V. (2015). Unconflicted goal striving: Goal ambivalence as a mediator between goal self-concordance and well-being. Personality and Social Psychology Bulletin, 41(1), 140–156.", note: "Three studies: low ambivalence toward a goal mediates the effect of self-concordance on wellbeing, with longitudinal gains explained by perceived progress.", link: doi("10.1177/0146167214559711"), kind: "doi" },
      { cite: "Holding, A. C., Barlow, M., Koestner, R., & Wrosch, C. (2020). Why are we together? A dyadic longitudinal investigation of relationship motivation, goal progress, and adjustment. Journal of Personality, 88(3), 464–477.", note: "One-year dyadic study of 153 couples: autonomous motivation predicted goal progress, and both partners' goal progress predicted increases in wellbeing and relationship satisfaction.", link: doi("10.1111/jopy.12503"), kind: "doi" },
      { cite: "Pomaki, G., Karoly, P., & Maes, S. (2009). Linking goal progress to subjective well-being at work: The moderating role of goal-related self-efficacy and attainability. Journal of Occupational Health Psychology, 14(2), 206–218.", note: "Longitudinal study of 172 nurses: goal progress raised wellbeing most for people who began with low self-efficacy and attainability beliefs.", link: doi("10.1037/a0014605"), kind: "doi" },
      { cite: "Bernecker, K., Herrmann, M., Brandstätter, V., & Job, V. (2017). Implicit theories about willpower predict subjective well-being. Journal of Personality, 85(2), 136–150.", note: "Three studies: believing willpower is a limited resource predicted lower wellbeing under high demands, mediated by poorer personal goal progress.", link: doi("10.1111/jopy.12225"), kind: "doi" },
    ],
  },
  {
    id: "gs-happiness-w2-autonomy-at-work",
    goal: "happiness", tier: "elite", section: "8368",
    title: "Engineer Autonomy Into Your Work — Negotiate It, Craft It, or Change Jobs to Get It",
    subtitle: "Self-determination theory: satisfying autonomy, competence and relatedness at work predicts wellbeing; autonomy-supportive leaders and job autonomy track higher wellbeing",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "months", durability: "lasting", effort: "high" },
    feeds: ["intrinsic motivation", "work satisfaction", "life satisfaction"],
    description:
      "Self-determination theory holds that wellbeing depends on satisfying three needs — autonomy, competence and relatedness — and a review of the theory in work organizations summarizes decades of evidence that need-supportive work environments yield better motivation and wellbeing. A meta-analytic review of basic needs at work finds each need independently predicts wellbeing and performance; a meta-analysis of 72 studies (N = 32,870) finds leader autonomy support relates to autonomous motivation, need satisfaction and wellbeing and inversely to distress; and UK panel data show autonomy in paid work — especially over the manner and pace of tasks — relates to employee subjective wellbeing, with differences by gender and job type. The boundary: most evidence is correlational, and autonomy that comes with chronic overload does not help.",
    action: "Over the next quarter, identify the two aspects of your work where you have the least say (schedule, method, pace, who you work with) and negotiate one concrete change with your manager; if in 12 months the job still leaves all three needs unmet, begin a deliberate search for a role or self-employment that meets them.",
    sources: [
      { cite: "Ryan, R. M., & Deci, E. L. (2000). Self-determination theory and the facilitation of intrinsic motivation, social development, and well-being. American Psychologist, 55(1), 68–78.", note: "The foundational statement of self-determination theory and its three basic psychological needs.", link: doi("10.1037//0003-066x.55.1.68"), kind: "doi" },
      { cite: "Deci, E. L., Olafsen, A. H., & Ryan, R. M. (2017). Self-determination theory in work organizations: The state of a science. Annual Review of Organizational Psychology and Organizational Behavior, 4(1), 19–43.", note: "Annual Review synthesis of the workplace evidence for need support, autonomous motivation and wellbeing.", link: doi("10.1146/annurev-orgpsych-032516-113108"), kind: "doi" },
      { cite: "Van den Broeck, A., Ferris, D. L., Chang, C.-H., & Rosen, C. C. (2016). A review of self-determination theory's basic psychological needs at work. Journal of Management, 42(5), 1195–1229.", note: "Meta-analytic review showing autonomy, competence and relatedness satisfaction each uniquely predict work wellbeing and outcomes.", link: doi("10.1177/0149206316632058"), kind: "doi" },
      { cite: "Slemp, G. R., Kern, M. L., Patrick, K. J., & Ryan, R. M. (2018). Leader autonomy support in the workplace: A meta-analytic review. Motivation and Emotion, 42(5), 706–724.", note: "72 studies (N = 32,870): leader autonomy support correlates with autonomous motivation, need satisfaction, wellbeing and positive work behaviours and negatively with distress.", link: doi("10.1007/s11031-018-9698-y"), kind: "doi" },
      { cite: "Wheatley, D. (2017). Autonomy in paid work and employee subjective well-being. Work and Occupations, 44(3), 296–328.", note: "UK panel analysis relating different dimensions of job autonomy to employee subjective wellbeing, with gender and occupational differences.", link: doi("10.1177/0730888417697232"), kind: "doi" },
    ],
  },
  {
    id: "gs-happiness-w2-micro-breaks",
    goal: "happiness", tier: "fundamental", section: "8369",
    title: "Take a Real Micro-Break Every 90 Minutes",
    subtitle: "A meta-analysis finds short breaks boost vigor and reduce fatigue; what you do in the break matters",
    evidenceTag: "Moderate",
    impact: { magnitude: 2, latency: "days", durability: "transient", effort: "low" },
    feeds: ["energy", "recovery", "afternoon mood"],
    description:
      "A meta-analysis of 22 study samples found micro-breaks produced small but significant gains in vigor (d = 0.36) and reductions in fatigue (d = 0.35), with performance benefits only for less cognitively demanding tasks and longer breaks doing more. Diary studies show that relaxing and social micro-break activities help recovery from daily demands whereas cognitive activities do not, that work-related energy-management strategies during the day help and that respite activities during breaks improve emotional experience and positive displays. The boundary: effects are small and short-lived — this is maintenance, not a mood treatment.",
    action: "Set a timer for every 90 minutes of focused work and take a 5–10 minute break away from the screen — stretch, walk, look out a window, chat with someone — never email or news; for two weeks note energy at 3 p.m. on a 1–10 scale.",
    sources: [
      { cite: "Albulescu, P., Macsinga, I., Rusu, A., Sulea, C., Bodnaru, A., & Tulbure, B. T. (2022). 'Give me a break!' A systematic review and meta-analysis on the efficacy of micro-breaks for increasing well-being and performance. PLoS One, 17(8), e0272460.", note: "22 samples (N = 2,335): micro-breaks raised vigor (d = 0.36) and lowered fatigue (d = 0.35); performance gains only for less demanding tasks and longer breaks.", link: doi("10.1371/journal.pone.0272460"), kind: "doi" },
      { cite: "Kim, S., Park, Y., & Niu, Q. (2017). Micro-break activities at work to recover from daily work demands. Journal of Organizational Behavior, 38(1), 28–44.", note: "Diary study: relaxation and social micro-break activities buffered the effect of daily work demands on end-of-day affect; cognitive activities did not.", link: doi("10.1002/job.2109"), kind: "doi" },
      { cite: "Zacher, H., Brailsford, H. A., & Parker, S. L. (2014). Micro-breaks matter: A diary study on the effects of energy management strategies on occupational well-being. Journal of Vocational Behavior, 85(3), 287–297.", note: "Diary study linking micro-break energy-management strategies during the workday with vitality and fatigue.", link: doi("10.1016/j.jvb.2014.08.005"), kind: "doi" },
      { cite: "Trougakos, J. P., Beal, D. J., Green, S. G., & Weiss, H. M. (2008). Making the break count: An episodic examination of recovery activities, emotional experiences, and positive affective displays. Academy of Management Journal, 51(1), 131–146.", note: "Episodic study of break activities showing respite activities during breaks improve emotional experience and positive affective displays afterward.", link: doi("10.5465/amj.2008.30764063"), kind: "doi" },
    ],
  },
  {
    id: "gs-happiness-w2-boredom-signal",
    goal: "happiness", tier: "fundamental", section: "8370",
    title: "Treat Boredom as Data: Fix Meaning or Fix Attention, Then Act",
    subtitle: "Boredom is an aversive signal that current activity fails on meaning or attentional fit — not a defect to numb",
    evidenceTag: "Moderate",
    impact: { magnitude: 2, latency: "days", durability: "sustained", effort: "low" },
    feeds: ["self-awareness", "engagement", "goal switching"],
    description:
      "The Meaning and Attentional Components model defines boredom as the affective signal of unsuccessful engagement in valued activity, arising from a mismatch of cognitive demand with resources (under- or over-stimulation) or from activities that do not serve valued goals. Functional accounts argue boredom motivates pursuit of alternative goals, an attention-based definition frames it as wanting but being unable to engage, and neuroimaging shows boredom as a failure to recruit executive-control networks. The boundary: this is theory-and-mechanism evidence, not an intervention trial; the protocol is a way of responding that the models imply.",
    action: "When bored, ask two questions before reaching for your phone — is this task too easy or too hard, and does it connect to anything I value? — then either change the difficulty (add a challenge or break the task down) or change the task; keep a one-line log of what you did for a week and notice which fix worked.",
    sources: [
      { cite: "Westgate, E. C., & Wilson, T. D. (2018). Boring thoughts and bored minds: The MAC model of boredom and cognitive engagement. Psychological Review, 125(5), 689–713.", note: "The Meaning and Attentional Components model: boredom results from mismatches of attention and of meaning, each producing distinct boredom profiles.", link: doi("10.1037/rev0000097"), kind: "doi" },
      { cite: "Bench, S. W., & Lench, H. C. (2013). On the function of boredom. Behavioral Sciences, 3(3), 459–472.", note: "Functional account: boredom motivates pursuit of new goals when the current one is no longer beneficial.", link: doi("10.3390/bs3030459"), kind: "doi" },
      { cite: "Eastwood, J. D., Frischen, A., Fenske, M. J., & Smilek, D. (2012). The unengaged mind: Defining boredom in terms of attention. Perspectives on Psychological Science, 7(5), 482–495.", note: "Defines boredom as the aversive state of wanting, but being unable, to engage in satisfying activity.", link: doi("10.1177/1745691612456044"), kind: "doi" },
      { cite: "Danckert, J., & Merrifield, C. (2018). Boredom, sustained attention and the default mode network. Experimental Brain Research, 236(9), 2507–2518.", note: "fMRI study: boredom reflects a failure to engage executive-control networks when a task demands engagement but is too mundane to hold it.", link: doi("10.1007/s00221-016-4617-5"), kind: "doi" },
    ],
  },
  {
    id: "gs-happiness-w2-cold-water",
    goal: "happiness", tier: "moderate", section: "8371",
    title: "Cold Water for Mood: A Short-Lived Lift, Not a Treatment",
    subtitle: "One large randomized trial found cold showers cut sickness absence but not illness; single immersions raise mood briefly; the depression claim rests on a hypothesis paper",
    evidenceTag: "Emerging",
    impact: { magnitude: 2, latency: "days", durability: "transient", effort: "moderate" },
    callout: "Popular claims that cold plunges treat depression trace to a 2008 hypothesis paper, not a trial. The controlled evidence supports a brief mood lift after a single immersion and a reduction in sickness absence with routine cold showers; cold-water swimming also carries drowning and cardiac risks for unacclimatized people.",
    feeds: ["alertness", "vigor"],
    description:
      "In a randomized trial of 3,018 Dutch adults, a routine hot-to-cold shower reduced self-reported sickness absence by 29% but not illness days, with quality-of-life and anxiety measured as secondary outcomes. A single 20-minute immersion in cold seawater improved mood in a small study, and Finnish winter swimmers reported less tension and fatigue and more vigor than controls over a four-month season in a non-randomized comparison. The adapted-cold-shower proposal for depression is explicitly a hypothesis with anecdotal support. The boundary: transient effects, small or uncontrolled studies, and real safety considerations around cold-water swimming.",
    action: "If you want to try it, end your morning shower with 30–60 seconds of cold for 30 days and rate mood and energy weekly; do not swim in open cold water without acclimatization, company and a clinician's clearance if you have heart disease.",
    sources: [
      { cite: "Buijze, G. A., Sierevelt, I. N., van der Heijden, B. C. J. M., Dijkgraaf, M. G., & Frings-Dresen, M. H. W. (2016). The effect of cold showering on health and work: A randomized controlled trial. PLoS One, 11(9), e0161749.", note: "3,018 adults randomized to 30, 60 or 90 seconds of cold showering or control for 30 days: 29% fewer sickness-absence days, no change in illness days.", link: doi("10.1371/journal.pone.0161749"), kind: "doi" },
      { cite: "Kelly, J. S., & Bird, E. (2022). Improved mood following a single immersion in cold water. Lifestyle Medicine, 3(1).", note: "Small study reporting improved mood after a single immersion in cold water — acute, not durable, evidence.", link: doi("10.1002/lim2.53"), kind: "doi" },
      { cite: "Huttunen, P., Kokko, L., & Ylijukuri, V. (2004). Winter swimming improves general well-being. International Journal of Circumpolar Health, 63(2), 140–144.", note: "Four-month non-randomized comparison: winter swimmers reported less tension and fatigue and more vigor than controls by season's end.", link: doi("10.3402/ijch.v63i2.17700"), kind: "doi" },
      { cite: "Shevchuk, N. A. (2008). Adapted cold shower as a potential treatment for depression. Medical Hypotheses, 70(5), 995–1001.", note: "The source of the depression claim: an explicit hypothesis with practical testing in a statistically insignificant number of people, not a trial.", link: doi("10.1016/j.mehy.2007.04.052"), kind: "doi" },
    ],
  },
];
