// Goal shelf: HOME — wave 2 (sections 8950–8967). Widens the wave-1 home shelf.
// Verification: every DOI below was resolved against the Crossref record (api.crossref.org)
// on 2026-09-11. See ../types.ts for the contract. Nothing here is legal, tax or investment advice.
import { doi, type GoalShelfCluster } from "../types";

export const SECTIONS: Record<string, string> = {
  "8950": "Lender Discrimination — What the Research Found and How to Shop Around It",
  "8951": "Appraisal Gaps — Why the Appraisal Is Not an Independent Check",
  "8952": "Energy Efficiency and Home Value — Labels, Solar and the Payback Wedge",
  "8953": "School Quality Capitalization — The Premium You Pay for the District",
  "8954": "Flood and Climate Risk — Only Partly in the Price",
  "8955": "Homeowners Associations — Read Them Like a Second Mortgage",
  "8956": "New Construction vs Existing — Depreciation Is the Constant",
  "8957": "Property Tax Capitalization — The Bill After Reassessment",
  "8958": "Home Maintenance — The Reserve Nobody Budgets",
  "8959": "House Hacking — Renting a Room, an ADU or a Unit",
  "8960": "Buying With Family or Friends — Co-Residence, Co-Buying and Shared Equity",
  "8961": "FHA vs Conventional — Total Cost Over Your Horizon",
  "8962": "Down-Payment Gifts and Intergenerational Help",
  "8963": "Manufactured Housing — On Land You Own",
  "8964": "Relocation Stress — Moving as a Life Event",
  "8965": "Homeownership and Civic Engagement — Showing Up, and the Homevoter Reflex",
  "8966": "Rent Control — What It Does to the Rent-vs-Buy Decision",
  "8967": "The Starter Home and Trading Up — Transaction Costs and Lock-In",
};

export const CLUSTERS: GoalShelfCluster[] = [
  {
    id: "gs-home-w2-lender-discrimination",
    goal: "home", tier: "moderate", section: "8950",
    title: "Know the Discrimination Evidence — Then Shop Lenders, Including Online Ones",
    subtitle: "Minority borrowers have historically paid more and been denied more; algorithmic lenders narrowed but did not erase pricing gaps",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "moderate" },
    feeds: ["rate outcome", "approval odds", "lender leverage"],
    description:
      "From the Boston Fed HMDA study of the 1990s through a 2020 quantitative review of four decades of audits, research has documented higher denial rates and worse pricing for Black and Hispanic mortgage applicants, with the review finding lending discrimination declined but persisted. A correspondence experiment found loan officers responded less helpfully to Black-named inquiries, a Review of Financial Studies study found borrower and broker race both affected mortgage costs, and the FinTech-era study found both face-to-face and algorithmic lenders charged Latinx and African-American borrowers more, though algorithmic lenders discriminated less and did not discriminate in approvals. The boundary: these are population-level findings — they tell you the market's tendency, not what any one lender will do to you.",
    action: "Get written loan estimates from at least four lenders on the same day, including at least one online or algorithmic lender and one credit union, and compare rate and total fees side by side. If you believe you were treated unfairly, keep every communication and know that you can file a complaint with the CFPB or HUD.",
    sources: [
      { cite: "Ladd, H. F. (1998). Evidence on discrimination in mortgage lending. Journal of Economic Perspectives, 12(2), 41–62.", note: "Survey of the evidence on mortgage-lending discrimination, including the Boston Fed study and what the denial-rate gaps do and do not show.", link: doi("10.1257/jep.12.2.41"), kind: "doi" },
      { cite: "Quillian, L., Lee, J. J., & Honoré, B. (2020). Racial discrimination in the U.S. housing and mortgage lending markets: A quantitative review of trends, 1976–2016. Race and Social Problems, 12(1), 13–28.", note: "Quantitative review of four decades of housing and lending audit studies: discrimination declined over time but persisted, especially in mortgage costs and in the treatment of Black and Hispanic applicants.", link: doi("10.1007/s12552-019-09276-x"), kind: "doi" },
      { cite: "Hanson, A., Hawley, Z., Martin, H., & Liu, B. (2016). Discrimination in mortgage lending: Evidence from a correspondence experiment. Journal of Urban Economics, 92, 48–65.", note: "Emails to loan officers with randomly assigned names: inquiries from Black-named borrowers received less favorable treatment — direct experimental evidence at the inquiry stage.", link: doi("10.1016/j.jue.2015.12.004"), kind: "doi" },
      { cite: "Ambrose, B. W., Conklin, J. N., & Lopez, L. A. (2021). Does borrower and broker race affect the cost of mortgage credit? The Review of Financial Studies, 34(2), 790–826.", note: "Loan-level evidence that both the borrower's and the broker's race affected the cost of mortgage credit.", link: doi("10.1093/rfs/hhaa087"), kind: "doi" },
      { cite: "Bartlett, R., Morse, A., Stanton, R., & Wallace, N. (2022). Consumer-lending discrimination in the FinTech era. Journal of Financial Economics, 143(1), 30–56.", note: "Both face-to-face and algorithmic lenders charged Latinx and African-American borrowers more; algorithmic lenders discriminated less on price and showed no discrimination in accept/reject decisions — the reason to include an online lender in your quotes.", link: doi("10.1016/j.jfineco.2021.05.047"), kind: "doi" },
      { cite: "Gabriel, S. A., & Rosenthal, S. S. (1991). Credit rationing, race, and the mortgage market. Journal of Urban Economics, 29(3), 371–379.", note: "Early evidence on race and credit rationing in the mortgage market, part of the literature that motivated later audit studies.", link: doi("10.1016/0094-1190(91)90007-t"), kind: "doi" },
    ],
  },
  {
    id: "gs-home-w2-appraisal-myth",
    goal: "home", tier: "fundamental", section: "8951",
    title: "Myth: The Appraisal Is an Independent Check on the Price",
    subtitle: "Appraisers anchor on the contract price, and appraisals in Black and Latino neighborhoods come in systematically lower — order your own comps and an inspection",
    evidenceTag: "Strong",
    impact: { magnitude: 1, latency: "days", durability: "lasting", effort: "low" },
    callout: "Rated at the floor because the belief is false. Repeat-appraisal and loan-level studies show appraisals substitute the contract price for an independent estimate — confirmation bias — and that the appraisal industry's neighborhood-comparison methods reproduce racial gaps in value. An appraisal protects the lender's collateral; it is not evidence you paid a fair price.",
    feeds: ["price discipline", "negotiation leverage"],
    description:
      "Studies of repeat appraisals of the same property and of the influence of contract prices and lender relationships find that purchase appraisals cluster at or just above the contract price, consistent with appraisers confirming rather than testing the deal. Sociological work on the modern appraisal industry shows that comparable-sales methods embed historical neighborhood racial composition into current values, and that the effect of neighborhood racial composition on housing values grew between 1980 and 2015. The boundary: reforms after 2008 changed some incentives, and a low appraisal can still surface a genuine overpayment — the myth is that a matching appraisal certifies the price.",
    action: "Before you make an offer, pull your own three to five closed comparable sales from the last six months and set your walk-away price from them, not from the list price. Always get an independent inspection, and if an appraisal comes in low on a home in a minority neighborhood, ask the lender for a reconsideration of value with your comps.",
    sources: [
      { cite: "Eriksen, M. D., Fout, H. B., Palim, M., & Rosenblatt, E. (2020). Contract price confirmation bias: Evidence from repeat appraisals. The Journal of Real Estate Finance and Economics, 60(1–2), 77–98.", note: "Repeat appraisals of the same properties show appraisers confirming the contract price rather than producing an independent value.", link: doi("10.1007/s11146-019-09716-w"), kind: "doi" },
      { cite: "Eriksen, M. D., Fout, H. B., Palim, M., & Rosenblatt, E. (2019). The influence of contract prices and relationships on appraisal bias. Journal of Urban Economics, 111, 132–143.", note: "Loan-level evidence that contract prices and lender–appraiser relationships shift appraised values — the mechanism behind the myth.", link: doi("10.1016/j.jue.2019.04.007"), kind: "doi" },
      { cite: "Howell, J., & Korver-Glenn, E. (2018). Neighborhoods, race, and the twenty-first-century housing appraisal industry. Sociology of Race and Ethnicity, 4(4), 473–490.", note: "Shows how the appraisal industry's neighborhood-based comparison methods reproduce racial inequality in home values.", link: doi("10.1177/2332649218755178"), kind: "doi" },
      { cite: "Howell, J., & Korver-Glenn, E. (2021). The increasing effect of neighborhood racial composition on housing values, 1980–2015. Social Problems, 68(4), 1051–1071.", note: "Documents that the effect of neighborhood racial composition on housing values increased between 1980 and 2015 — the appraisal gap is not a historical artifact.", link: doi("10.1093/socpro/spaa033"), kind: "doi" },
    ],
  },
  {
    id: "gs-home-w2-energy-efficiency-value",
    goal: "home", tier: "moderate", section: "8952",
    title: "Buy Documented Efficiency, and Discount the Payback Projections by Half",
    subtitle: "Energy labels and solar carry real resale premiums; retrofit savings in the field run well below engineering projections",
    evidenceTag: "Strong",
    impact: { magnitude: 2, latency: "months", durability: "lasting", effort: "moderate" },
    feeds: ["operating cost", "resale value", "realistic budgeting"],
    description:
      "Hedonic studies in the Netherlands, England and California find that homes with better energy labels or green certifications sell at a premium, that the premium tracks realized energy savings, and that solar installations carry a price premium partly explained by green social status. On the retrofit side, evaluations of weatherization and efficiency programs find realized savings a fraction of projected savings, with a decomposition study attributing the wedge largely to engineering-model errors rather than rebound behavior. The boundary: premiums vary by market and label, and the U.S. evidence on labels is thinner than the European.",
    action: "When comparing homes, ask for twelve months of utility bills and any energy audit or certification, and treat a documented efficient home as worth a modest premium. Before paying for a retrofit, halve the contractor's projected annual savings and compute payback on that number; do the cheap envelope work first.",
    sources: [
      { cite: "Brounen, D., & Kok, N. (2011). On the economics of energy labels in the housing market. Journal of Environmental Economics and Management, 62(2), 166–179.", note: "Dutch transactions: homes with better energy labels sold at a premium consistent with the value of expected energy savings.", link: doi("10.1016/j.jeem.2010.11.006"), kind: "doi" },
      { cite: "Fuerst, F., McAllister, P., Nanda, A., & Wyatt, P. (2015). Does energy efficiency matter to home-buyers? An investigation of EPC ratings and transaction prices in England. Energy Economics, 48, 145–156.", note: "English transaction data showing a positive relationship between energy performance ratings and sale prices.", link: doi("10.1016/j.eneco.2014.12.012"), kind: "doi" },
      { cite: "Kahn, M. E., & Kok, N. (2014). The capitalization of green labels in the California housing market. Regional Science and Urban Economics, 47, 25–34.", note: "California homes with green certifications sold at a premium, larger in hotter climates and among environmentally minded buyers.", link: doi("10.1016/j.regsciurbeco.2013.07.001"), kind: "doi" },
      { cite: "Aydin, E., Brounen, D., & Kok, N. (2020). The capitalization of energy efficiency: Evidence from the housing market. Journal of Urban Economics, 117, 103243.", note: "Links measured energy efficiency to house prices, testing whether the market capitalizes actual rather than labeled efficiency.", link: doi("10.1016/j.jue.2020.103243"), kind: "doi" },
      { cite: "Dastrup, S. R., Graff Zivin, J., Costa, D. L., & Kahn, M. E. (2012). Understanding the solar home price premium: Electricity generation and \"green\" social status. European Economic Review, 56(5), 961–973.", note: "Solar homes in California sold at a premium explained partly by electricity value and partly by green social status.", link: doi("10.1016/j.euroecorev.2012.02.006"), kind: "doi" },
      { cite: "Fowlie, M., Greenstone, M., & Wolfram, C. (2018). Do energy efficiency investments deliver? Evidence from the Weatherization Assistance Program. The Quarterly Journal of Economics, 133(3), 1597–1644.", note: "Randomized encouragement evaluation of the federal Weatherization Assistance Program: realized energy savings were far below engineering projections and the upfront cost exceeded the value of savings — the strongest evidence for discounting payback claims.", link: doi("10.1093/qje/qjy005"), kind: "doi" },
      { cite: "Christensen, P., Francisco, P., Myers, E., & Souza, M. (2023). Decomposing the wedge between projected and realized returns in energy efficiency programs. Review of Economics and Statistics, 105(4), 798–817.", note: "Field data from a weatherization program: realized savings fell well short of projections, with the wedge attributed mostly to engineering-model error rather than occupant rebound — the reason to discount payback claims.", link: doi("10.1162/rest_a_01087"), kind: "doi" },
    ],
  },
  {
    id: "gs-home-w2-school-premium",
    goal: "home", tier: "advanced", section: "8953",
    title: "Price the School Premium Before You Pay It",
    subtitle: "Parents pay measurably more for homes on the better side of a school boundary; the premium is real, partly a neighborhood premium, and worth computing against private-school or tutoring alternatives",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "months", durability: "lasting", effort: "moderate" },
    feeds: ["price discipline", "school decision", "resale liquidity"],
    description:
      "Boundary-discontinuity studies beginning with Black's comparison of homes on either side of Massachusetts attendance-zone lines find that parents pay a premium for better elementary schools, with later work showing that part of the raw premium reflects neighbors and neighborhood sorting rather than the school itself. School report-card grades in Florida moved house prices when information was new, and reviews synthesize dozens of capitalization estimates. The boundary: estimates vary widely by method and place, and the premium capitalizes test scores and peers, not necessarily the value added a particular child would receive.",
    action: "If you are choosing a home for its school, pull sale prices for comparable homes just inside and just outside the attendance boundary and write the difference down as the school premium. Compare that number, over the years your children will attend, against the cost of the alternative (a different school choice, tutoring, or a shorter commute) before you decide.",
    sources: [
      { cite: "Black, S. E. (1999). Do better schools matter? Parental valuation of elementary education. The Quarterly Journal of Economics, 114(2), 577–599.", note: "Foundational boundary-discontinuity study: homes on the better-school side of attendance boundaries sold for more, isolating the school premium from neighborhood differences.", link: doi("10.1162/003355399556070"), kind: "doi" },
      { cite: "Bayer, P., Ferreira, F., & McMillan, R. (2007). A unified framework for measuring preferences for schools and neighborhoods. Journal of Political Economy, 115(4), 588–638.", note: "Shows that a substantial part of the raw school premium reflects sorting of neighbors across boundaries — the school premium is partly a neighbor premium.", link: doi("10.1086/522381"), kind: "doi" },
      { cite: "Kane, T. J., Riegg, S. K., & Staiger, D. O. (2006). School quality, neighborhoods, and housing prices. American Law and Economics Review, 8(2), 183–212.", note: "Uses school reassignments in Charlotte-Mecklenburg to separate the effect of school quality on house prices from neighborhood effects.", link: doi("10.1093/aler/ahl007"), kind: "doi" },
      { cite: "Figlio, D. N., & Lucas, M. E. (2004). What's in a grade? School report cards and the housing market. American Economic Review, 94(3), 591–604.", note: "Florida's school letter grades moved house prices and sorting when introduced, showing buyers respond to school-quality signals.", link: doi("10.1257/0002828041464489"), kind: "doi" },
      { cite: "Nguyen-Hoang, P., & Yinger, J. (2011). The capitalization of school quality into house values: A review. Journal of Housing Economics, 20(1), 30–48.", note: "Review of the capitalization literature summarizing methods and the range of estimated premiums.", link: doi("10.1016/j.jhe.2011.02.001"), kind: "doi" },
      { cite: "Gibbons, S., & Machin, S. (2008). Valuing school quality, better transport, and lower crime: Evidence from house prices. Oxford Review of Economic Policy, 24(1), 99–119.", note: "Reviews house-price evidence on what people pay for school quality relative to transport and crime.", link: doi("10.1093/oxrep/grn008"), kind: "doi" },
      { cite: "Gibbons, S., Machin, S., & Silva, O. (2013). Valuing school quality using boundary discontinuities. Journal of Urban Economics, 75, 15–28.", note: "English boundary-discontinuity estimates of the school-quality premium using both test scores and value-added measures.", link: doi("10.1016/j.jue.2012.11.001"), kind: "doi" },
    ],
  },
  {
    id: "gs-home-w2-flood-risk-check",
    goal: "home", tier: "fundamental", section: "8954",
    title: "Check Flood and Climate Risk Beyond the FEMA Map — Prices Only Partly Reflect It",
    subtitle: "Homes exposed to sea-level rise sell at a discount only where buyers believe in the risk; nationally, flood-exposed homes appear overvalued",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "days", durability: "lasting", effort: "low" },
    feeds: ["insurance cost", "resale risk", "physical safety"],
    description:
      "Studies of coastal transactions find that homes exposed to projected sea-level rise sell at a discount relative to otherwise similar homes, that the discount depends on buyers' beliefs about climate risk, and that flood-map updates change prices only partially. A national analysis estimated that flood-exposed U.S. homes are overvalued relative to their expected flood losses, with the gap concentrated in areas where risk is not disclosed. One prominent study found little capitalization of sea-level-rise risk in most markets. The boundary: results differ by method and time horizon, and price discounts do not protect you from an uninsured loss.",
    action: "Before you offer, look up the address in a flood-risk model that goes beyond the FEMA 100-year zone, get a flood insurance quote even if the lender does not require one, and ask the seller in writing about past water intrusion. Treat a home the map calls safe but the model calls exposed as needing a price discount or a walk-away.",
    sources: [
      { cite: "Bernstein, A., Gustafson, M. T., & Lewis, R. (2019). Disaster on the horizon: The price effect of sea level rise. Journal of Financial Economics, 134(2), 253–272.", note: "Homes exposed to projected sea-level rise sold at a discount relative to unexposed homes equidistant from the beach, with the discount larger among sophisticated buyers.", link: doi("10.1016/j.jfineco.2019.03.013"), kind: "doi" },
      { cite: "Bakkensen, L. A., & Barrage, L. (2022). Going underwater? Flood risk belief heterogeneity and coastal home price dynamics. The Review of Financial Studies, 35(8), 3666–3709.", note: "Combines survey beliefs with transactions: heterogeneous flood-risk beliefs mean coastal prices can exceed fundamentals, with optimistic buyers sorting into exposed homes.", link: doi("10.1093/rfs/hhab122"), kind: "doi" },
      { cite: "Hino, M., & Burke, M. (2021). The effect of information about climate risk on property values. Proceedings of the National Academy of Sciences, 118(17), e2003374118.", note: "Floodplain designation changes had limited effects on prices, implying flood-zone information alone is only partly capitalized.", link: doi("10.1073/pnas.2003374118"), kind: "doi" },
      { cite: "Gourevitch, J. D., Kousky, C., Liao, Y., Nolte, C., Pollack, A. B., Porter, J. R., & Weill, J. A. (2023). Unpriced climate risk and the potential consequences of overvaluation in US housing markets. Nature Climate Change, 13(3), 250–257.", note: "National estimate that flood-exposed U.S. residential property is overvalued relative to expected flood losses, with the gap concentrated where risk is undisclosed.", link: doi("10.1038/s41558-023-01594-8"), kind: "doi" },
      { cite: "Murfin, J., & Spiegel, M. (2020). Is the risk of sea level rise capitalized in residential real estate? The Review of Financial Studies, 33(3), 1217–1255.", note: "Finds little evidence that sea-level-rise risk is capitalized into prices in most markets — the honest counterweight, and a reason not to rely on the market to warn you.", link: doi("10.1093/rfs/hhz134"), kind: "doi" },
      { cite: "Bin, O., & Landry, C. E. (2013). Changes in implicit flood risk premiums: Empirical evidence from the housing market. Journal of Environmental Economics and Management, 65(3), 361–376.", note: "Flood-risk price discounts rise after major storms and fade over time — market memory is short.", link: doi("10.1016/j.jeem.2012.12.002"), kind: "doi" },
    ],
  },
  {
    id: "gs-home-w2-hoa-read-it",
    goal: "home", tier: "moderate", section: "8955",
    title: "Read the HOA Like a Second Mortgage",
    subtitle: "Associations are capitalized into prices in some markets and not others; the dues, the reserves and the rules are the number to underwrite",
    evidenceTag: "Moderate",
    impact: { magnitude: 2, latency: "weeks", durability: "lasting", effort: "low" },
    feeds: ["true monthly cost", "resale risk", "neighborhood control"],
    description:
      "Roughly a fifth of U.S. housing sits in homeowners associations, and Florida transaction studies find association membership is capitalized into prices in a way that varies with what the association provides and how it is governed. Associations also change local politics — HOA neighborhoods demand less municipal land-use regulation — and their presence relates to citywide segregation patterns and to whether cities cohere. The boundary: the price effect is context-dependent and modest on average; the risks that matter for a buyer are special assessments, underfunded reserves and rule enforcement, which the studies do not price for you.",
    action: "Before you waive contingencies on an HOA property, get the last two years of financial statements, the reserve study, the minutes of the last four board meetings and the covenants, and read them yourself. Add the dues plus one-tenth of any reserve shortfall per unit to your monthly cost, and walk away from a board that cannot produce the documents.",
    sources: [
      { cite: "Meltzer, R., & Cheung, R. (2014). How are homeowners associations capitalized into property values? Regional Science and Urban Economics, 46, 93–102.", note: "Florida transactions: HOA membership is capitalized into home prices, with the size and sign of the effect depending on the association's characteristics and context.", link: doi("10.1016/j.regsciurbeco.2014.03.005"), kind: "doi" },
      { cite: "Clarke, W., & Freedman, M. (2019). The rise and effects of homeowners associations. Journal of Urban Economics, 112, 1–15.", note: "National analysis of the growth of HOAs and their effects on prices and neighborhood characteristics.", link: doi("10.1016/j.jue.2019.05.001"), kind: "doi" },
      { cite: "Cheung, R., & Meltzer, R. (2013). Homeowners associations and the demand for local land use regulation. Journal of Regional Science, 53(3), 511–534.", note: "Jurisdictions with more HOA housing demand less public land-use regulation — private governance substitutes for public rules.", link: doi("10.1111/j.1467-9787.2012.00783.x"), kind: "doi" },
      { cite: "Meltzer, R. (2013). Do homeowners associations affect citywide segregation? Evidence from Florida municipalities. Housing Policy Debate, 23(4), 688–713.", note: "Tests whether the spread of HOAs relates to segregation patterns across Florida municipalities.", link: doi("10.1080/10511482.2013.812571"), kind: "doi" },
      { cite: "Cheung, R., Salmon, T. C., & Xie, K. (2022). Homeowner associations and city cohesion. Regional Science and Urban Economics, 93, 103760.", note: "Examines how HOA prevalence relates to civic cohesion at the city level — the community side of the private-governance trade.", link: doi("10.1016/j.regsciurbeco.2021.103760"), kind: "doi" },
    ],
  },
  {
    id: "gs-home-w2-depreciation-new-vs-existing",
    goal: "home", tier: "moderate", section: "8956",
    title: "Budget Depreciation Whether the House Is New or Old",
    subtitle: "Housing capital depreciates a few percent a year gross of maintenance; new homes filter down and existing homes filter up depending on the market",
    evidenceTag: "Strong",
    impact: { magnitude: 2, latency: "months", durability: "lasting", effort: "low" },
    feeds: ["true cost of ownership", "new-vs-existing decision", "resale expectations"],
    description:
      "Repeat-sales estimates put gross depreciation of housing capital at roughly 2.5–3% a year, offset partly by maintenance, and show that owners who maintain less see faster price depreciation. Filtering studies find that in most metros housing filters down in real terms as it ages — which is how new construction eventually supplies lower-cost housing — while in tight markets it can filter up. The boundary: a new home avoids deferred maintenance for a few years but not depreciation, and builder-market premiums for 'new' fade with the first resale.",
    action: "Whichever house you buy, put a line in the ownership budget of one to two percent of the home's value per year for depreciation and maintenance, and treat the 'new home, no repairs' pitch as a five-year window rather than a permanent saving. When comparing a new build against an existing home, ask what the same builder's homes from five years ago resold for.",
    sources: [
      { cite: "Harding, J. P., Rosenthal, S. S., & Sirmans, C. F. (2007). Depreciation of housing capital, maintenance, and house price inflation: Estimates from a repeat sales model. Journal of Urban Economics, 61(2), 193–217.", note: "Repeat-sales model separating depreciation, maintenance and price inflation; the standard reference for the annual depreciation rate of owner-occupied housing.", link: doi("10.1016/j.jue.2006.07.007"), kind: "doi" },
      { cite: "Knight, J. R., & Sirmans, C. F. (1996). Depreciation, maintenance, and housing prices. Journal of Housing Economics, 5(4), 369–389.", note: "Shows that the level of maintenance affects the rate at which house prices depreciate with age.", link: doi("10.1006/jhec.1996.0019"), kind: "doi" },
      { cite: "Shilling, J. D., Sirmans, C. F., & Dombrow, J. F. (1991). Measuring depreciation in single-family rental and owner-occupied housing. Journal of Housing Economics, 1(4), 368–383.", note: "Early estimates of depreciation rates for rental versus owner-occupied single-family housing.", link: doi("10.1016/s1051-1377(05)80018-x"), kind: "doi" },
      { cite: "Wilhelmsson, M. (2008). House price depreciation rates and level of maintenance. Journal of Housing Economics, 17(1), 88–101.", note: "Swedish evidence that depreciation depends on maintenance level — owners who maintain lose less value.", link: doi("10.1016/j.jhe.2007.09.001"), kind: "doi" },
      { cite: "Rosenthal, S. S. (2014). Are private markets and filtering a viable source of low-income housing? Estimates from a \"repeat income\" model. American Economic Review, 104(2), 687–706.", note: "Repeat-income model showing that housing filters down in real terms as it ages in most markets, at rates that vary with local price appreciation.", link: doi("10.1257/aer.104.2.687"), kind: "doi" },
      { cite: "Mast, E. (2023). JUE Insight: The effect of new market-rate housing construction on the low-income housing market. Journal of Urban Economics, 133, 103383.", note: "Traces migration chains from new market-rate buildings to show how new construction loosens the market for existing, lower-cost housing.", link: doi("10.1016/j.jue.2021.103383"), kind: "doi" },
    ],
  },
  {
    id: "gs-home-w2-property-tax-reassessment",
    goal: "home", tier: "fundamental", section: "8957",
    title: "Model the Property Tax at Reassessment, Not at the Seller's Bill",
    subtitle: "Taxes are capitalized into prices, and buyers routinely ignore that assessment caps reset on sale",
    evidenceTag: "Strong",
    impact: { magnitude: 2, latency: "days", durability: "lasting", effort: "low" },
    feeds: ["true monthly cost", "offer price", "escrow surprise"],
    description:
      "Since Oates's 1969 test of the Tiebout hypothesis, studies have found that property taxes and the local services they fund are capitalized into house prices — higher taxes for the same services mean lower prices. In states with assessment caps, the seller's tax bill can be far below what the buyer will owe once the assessment resets, and Michigan evidence shows buyers largely fail to anticipate the increase and overpay. The boundary: capitalization rates vary, and in some states caps are portable or partially transferable.",
    action: "Do not use the seller's current tax bill. Look up the jurisdiction's millage rate and assessment rules, estimate the bill on your purchase price, and put that number in your monthly cost and your offer. If your state has an assessment cap that resets on sale, assume it resets.",
    sources: [
      { cite: "Oates, W. E. (1969). The effects of property taxes and local public spending on property values: An empirical study of tax capitalization and the Tiebout hypothesis. Journal of Political Economy, 77(6), 957–971.", note: "The foundational study finding property taxes and school spending capitalized into house values across New Jersey municipalities.", link: doi("10.1086/259584"), kind: "doi" },
      { cite: "Palmon, O., & Smith, B. A. (1998). New evidence on property tax capitalization. Journal of Political Economy, 106(5), 1099–1111.", note: "Uses variation in tax rates across otherwise similar Houston-area subdivisions to estimate near-full capitalization of property tax differences.", link: doi("10.1086/250041"), kind: "doi" },
      { cite: "Bradley, S. (2017). Inattention to deferred increases in tax bases: How Michigan home buyers are paying for assessment limits. Review of Economics and Statistics, 99(1), 53–66.", note: "Michigan buyers largely ignore that the seller's capped assessment resets at sale, and pay more than they would if they anticipated the higher tax bill.", link: doi("10.1162/rest_a_00597"), kind: "doi" },
      { cite: "Sirmans, S., Gatzlaff, D., & Macpherson, D. (2008). The history of property tax capitalization in real estate. Journal of Real Estate Literature, 16(3), 327–344.", note: "Review of four decades of property-tax capitalization studies and the range of estimated capitalization rates.", link: doi("10.1080/10835547.2008.12090233"), kind: "doi" },
      { cite: "Hilber, C. A. L. (2017). The economic implications of house price capitalization: A synthesis. Real Estate Economics, 45(2), 301–339.", note: "Synthesis of how taxes, amenities and regulation are capitalized into house prices and what that implies for buyers and policy.", link: doi("10.1111/1540-6229.12129"), kind: "doi" },
    ],
  },
  {
    id: "gs-home-w2-maintenance-reserve",
    goal: "home", tier: "fundamental", section: "8958",
    title: "Fund a Maintenance Reserve From Month One",
    subtitle: "Owners treat maintenance as the flexible line and cut it when income dips — and the house depreciates faster when they do",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "months", durability: "lasting", effort: "low" },
    feeds: ["home value", "cash-flow resilience", "avoided emergency borrowing"],
    description:
      "Panel evidence shows households use home maintenance and repairs to smooth variable earnings — spending less on the house when income falls — and depreciation studies show under-maintained homes lose value faster. Research on improvement spending and on whether owners do the work themselves or hire it out describes maintenance as a lumpy investment decision that owners defer. The boundary: the right reserve depends on the home's age and systems, and none of these studies gives a single correct percentage.",
    action: "Open a separate account and automate a monthly transfer of one percent of the home's value per year, divided by twelve, from the first mortgage payment. Spend from it only on the house, and on the day you buy, list the age and expected replacement year of the roof, furnace, water heater and appliances so the reserve has named targets.",
    sources: [
      { cite: "Gyourko, J., & Tracy, J. (2006). Using home maintenance and repairs to smooth variable earnings. Review of Economics and Statistics, 88(4), 736–747.", note: "Households cut maintenance and repair spending when earnings fall and raise it when they rise — maintenance is the shock absorber, at the house's expense.", link: doi("10.1162/rest.88.4.736"), kind: "doi" },
      { cite: "Harding, J. P., Rosenthal, S. S., & Sirmans, C. F. (2007). Depreciation of housing capital, maintenance, and house price inflation: Estimates from a repeat sales model. Journal of Urban Economics, 61(2), 193–217.", note: "Estimates how much maintenance offsets gross depreciation — the return on the reserve.", link: doi("10.1016/j.jue.2006.07.007"), kind: "doi" },
      { cite: "Knight, J. R., & Sirmans, C. F. (1996). Depreciation, maintenance, and housing prices. Journal of Housing Economics, 5(4), 369–389.", note: "Lower maintenance is associated with faster price depreciation.", link: doi("10.1006/jhec.1996.0019"), kind: "doi" },
      { cite: "Montgomery, C. (1992). Explaining home improvement in the context of household investment in residential housing. Journal of Urban Economics, 32(3), 326–350.", note: "Models improvement spending as a household investment decision shaped by income, tenure and house characteristics.", link: doi("10.1016/0094-1190(92)90022-d"), kind: "doi" },
      { cite: "Bogdon, A. S. (1996). Homeowner renovation and repair: The decision to hire someone else to do the project. Journal of Housing Economics, 5(4), 323–350.", note: "Examines when owners do repairs themselves versus hire contractors — the labor side of the maintenance budget.", link: doi("10.1006/jhec.1996.0017"), kind: "doi" },
      { cite: "Boehm, T. P., & Ihlanfeldt, K. R. (1986). The improvement expenditures of urban homeowners: An empirical analysis. Real Estate Economics, 14(1), 48–60.", note: "Early empirical analysis of what drives urban homeowners' improvement spending.", link: doi("10.1111/1540-6229.00368"), kind: "doi" },
      { cite: "Wilhelmsson, M. (2008). House price depreciation rates and level of maintenance. Journal of Housing Economics, 17(1), 88–101.", note: "Maintenance level and depreciation rate move together in Swedish data.", link: doi("10.1016/j.jhe.2007.09.001"), kind: "doi" },
    ],
  },
  {
    id: "gs-home-w2-house-hacking",
    goal: "home", tier: "advanced", section: "8959",
    title: "Rent a Room, an ADU or a Unit — and Underwrite It as a Small Landlord",
    subtitle: "Taking in lodgers is an old American strategy; accessory units and small rentals are real income, with vacancy, wear and regulation to price in",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "months", durability: "sustained", effort: "high" },
    feeds: ["mortgage coverage", "affordability", "landlord skills"],
    description:
      "Historical demography shows boarding and lodging were common ways American households met housing costs, and planning research documents accessory dwelling units, backyard cottages and garage conversions as a source of hidden density and household income, alongside the regulatory barriers to building them. Studies of small rental properties show they supply much of the unsubsidized affordable stock but are hard to keep in good repair, while home-sharing platforms raise local rents and prices. The boundary: none of this estimates the return to a given owner; the risks — vacancy, damage, tenant law, and the effect on your own household — are yours to model.",
    action: "If you are considering a duplex, a home with an ADU or renting a room, build a one-page pro forma: realistic rent from three comparable listings, minus 8% vacancy, minus a maintenance line, minus insurance and tax increases, and check the local rules on rentals before you offer. Run it again assuming the unit sits empty for three months.",
    sources: [
      { cite: "Modell, J., & Hareven, T. K. (1973). Urbanization and the malleable household: An examination of boarding and lodging in American families. Journal of Marriage and the Family, 35(3), 467–479.", note: "Historical evidence that taking in boarders and lodgers was a widespread, normal way American families balanced housing costs across the life cycle.", link: doi("10.2307/350582"), kind: "doi" },
      { cite: "Wegmann, J., & Chapple, K. (2014). Hidden density in single-family neighborhoods: Backyard cottages as an equitable smart growth strategy. Journal of Urbanism: International Research on Placemaking and Urban Sustainability, 7(3), 307–329.", note: "Survey of backyard cottages and secondary units in the East Bay: who builds them, who lives in them and what they rent for.", link: doi("10.1080/17549175.2013.879453"), kind: "doi" },
      { cite: "Brown, A., Mukhija, V., & Shoup, D. (2020). Converting garages into housing. Journal of Planning Education and Research, 40(1), 56–68.", note: "Examines garage conversions as a low-cost path to accessory units and the parking and permitting rules that block them.", link: doi("10.1177/0739456x17741965"), kind: "doi" },
      { cite: "Garboden, P. M. E., & Newman, S. (2012). Is preserving small, low-end rental housing feasible? Housing Policy Debate, 22(4), 507–526.", note: "Small rental properties supply much affordable housing but their owners struggle with thin margins and repair costs — the landlord economics to expect.", link: doi("10.1080/10511482.2012.697909"), kind: "doi" },
      { cite: "Decker, N. (2021). Affordable housing without public subsidies: Rent-setting practices in small rental properties. Journal of the American Planning Association, 87(1), 62–72.", note: "Interviews with small landlords on how they actually set rents — often below market and shaped by tenant relationships.", link: doi("10.1080/01944363.2020.1798806"), kind: "doi" },
      { cite: "Decker, N. (2023). The prevalence, profitability, and risks of milking among low-end small rental properties. Housing Policy Debate, 33(6), 1536–1553.", note: "Documents the temptation and risks of under-maintaining low-end rentals to extract cash flow — the trap a house hacker should name in advance.", link: doi("10.1080/10511482.2023.2210560"), kind: "doi" },
      { cite: "Barron, K., Kung, E., & Proserpio, D. (2021). The effect of home-sharing on house prices and rents: Evidence from Airbnb. Marketing Science, 40(1), 23–47.", note: "Airbnb listings raise local rents and house prices, with the effect concentrated where owners are less likely to live in the property — context for short-term rental plans and local rules.", link: doi("10.1287/mksc.2020.1227"), kind: "doi" },
      { cite: "Farronato, C., & Fradkin, A. (2022). The welfare effects of peer entry: The case of Airbnb and the accommodation industry. American Economic Review, 112(6), 1782–1817.", note: "Estimates the welfare effects of peer-to-peer accommodation supply, including how returns to hosts depend on local hotel capacity and demand peaks.", link: doi("10.1257/aer.20180260"), kind: "doi" },
    ],
  },
  {
    id: "gs-home-w2-co-buy-co-reside",
    goal: "home", tier: "elite", section: "8960",
    title: "Co-Reside, Co-Buy or Share Equity — On Paper, With an Exit",
    subtitle: "Moving home to save is insurance the research can measure; buying with relatives or friends is a legal structure first and a shortcut second",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "months", durability: "lasting", effort: "high" },
    feeds: ["down-payment speed", "risk sharing", "relationship protection"],
    description:
      "Economic studies show that the option to move back in with parents acts as insurance against labor-market risk for young adults, that debt and recessions push co-residence up, and that supported home purchases — through co-residence, gifts, loans and co-signing — are widespread and socially patterned. Evaluations of shared-equity homeownership programs find they preserve affordability and deliver near-term ownership stability, and cohousing research shows deliberately designed shared neighborhoods sustain interaction. The boundary: there is no peer-reviewed evidence on informal co-buying among friends specifically; what the literature supports is that shared arrangements work when the terms are explicit.",
    action: "If you would co-reside to save, set a target amount and end date on day one and pay something toward the household. If you would co-buy with a relative or friend, do it only with a written co-ownership agreement covering shares, payments, repairs, buyout formula and what happens on death, divorce or default, reviewed by a lawyer before you go under contract; if a local shared-equity program exists, compare its resale formula honestly against the equity you would give up.",
    sources: [
      { cite: "Kaplan, G. (2012). Moving back home: Insurance against labor market risk. Journal of Political Economy, 120(3), 446–512.", note: "Structural model and NLSY evidence that the option to move back in with parents insures young adults against labor-market risk and supports job search.", link: doi("10.1086/666588"), kind: "doi" },
      { cite: "Dettling, L. J., & Hsu, J. W. (2018). Returning to the nest: Debt and parental co-residence among young adults. Labour Economics, 54, 225–236.", note: "Credit-record evidence that rising debt and delinquency push young adults into co-residence with parents — the saving-at-home path is often a response to strain.", link: doi("10.1016/j.labeco.2017.12.006"), kind: "doi" },
      { cite: "Lee, K. O., & Painter, G. (2013). What happens to household formation in a recession? Journal of Urban Economics, 76, 93–109.", note: "Household formation and headship fall in recessions as young adults double up — context for how common co-residence before buying is.", link: doi("10.1016/j.jue.2013.03.004"), kind: "doi" },
      { cite: "Coulter, R. (2024). Patterns of supported home purchase in the United Kingdom. International Journal of Housing Policy, 26(4), 644–664.", note: "Shows supported purchase — co-residence to save, gifts, loans — is widespread and multichannelled, with support concentrated among younger and more marginal buyers.", link: doi("10.1080/19491247.2024.2417318"), kind: "doi" },
      { cite: "Temkin, K. M., Theodos, B., & Price, D. (2013). Sharing equity with future generations: An evaluation of long-term affordable homeownership programs in the USA. Housing Studies, 28(4), 553–578.", note: "Evaluation of shared-equity programs finding they preserved affordability across resales while owners built modest equity.", link: doi("10.1080/02673037.2013.759541"), kind: "doi" },
      { cite: "Theodos, B., Stacy, C. P., Braga, B., & Daniels, R. (2019). Affordable homeownership: An evaluation of the near-term effects of shared equity programs. Housing Policy Debate, 29(6), 865–879.", note: "Near-term outcomes for shared-equity buyers compared with similar households — stability and credit effects.", link: doi("10.1080/10511482.2019.1596965"), kind: "doi" },
      { cite: "Williams, J. (2005). Designing neighbourhoods for social interaction: The case of cohousing. Journal of Urban Design, 10(2), 195–227.", note: "Case studies of cohousing showing how physical design and governance sustain social interaction in intentionally shared communities.", link: doi("10.1080/13574800500086998"), kind: "doi" },
    ],
  },
  {
    id: "gs-home-w2-fha-vs-conventional",
    goal: "home", tier: "moderate", section: "8961",
    title: "Choose FHA or Conventional on Total Cost Over Your Horizon, Not on the Minimum Down Payment",
    subtitle: "FHA opens the door for thinner credit and smaller down payments; low equity is the strongest single default predictor, and insurance premiums move buying behavior",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "weeks", durability: "lasting", effort: "moderate" },
    feeds: ["financing cost", "default risk", "refinance path"],
    description:
      "Research on the FHA–conventional choice shows borrowers with weaker credit histories sort into FHA, that FHA market share rises where conventional credit is rationed, and that FHA served as the mainstream alternative to subprime lending. Studies of zero-down-payment loans find that having no equity — 'no skin in the game' — sharply raises default, and a study of a mortgage-insurance premium cut found that lower premiums measurably increased home purchases, showing how sensitive buyers are to the insurance line. The boundary: the right program depends on credit score, down payment and how long you will hold the loan; none of these papers compares total cost for an individual buyer.",
    action: "Get one FHA and one conventional loan estimate on the same day and compare the all-in monthly payment including mortgage insurance, then the total cost at years three, seven and ten, noting when conventional insurance can be cancelled and whether FHA's cannot. Pick the cheaper loan over your realistic holding period, and put down more than the minimum if it takes you off the highest-default tier.",
    sources: [
      { cite: "Pennington-Cross, A., & Nichols, J. (2000). Credit history and the FHA–conventional choice. Real Estate Economics, 28(2), 307–336.", note: "Borrowers with weaker credit histories are more likely to choose FHA over conventional loans — FHA as the access route.", link: doi("10.1111/1540-6229.00803"), kind: "doi" },
      { cite: "Ambrose, B. W., Pennington-Cross, A., & Yezer, A. M. (2002). Credit rationing in the U.S. mortgage market: Evidence from variation in FHA market shares. Journal of Urban Economics, 51(2), 272–294.", note: "FHA market shares rise where conventional lenders ration credit, showing FHA's role as the lender of resort.", link: doi("10.1006/juec.2001.2245"), kind: "doi" },
      { cite: "Karikari, J. A., Voicu, I., & Fang, I. (2011). FHA vs. subprime mortgage originations: Is FHA the answer to subprime lending? The Journal of Real Estate Finance and Economics, 43(4), 441–458.", note: "Compares FHA and subprime originations, finding FHA served similar borrowers at lower cost during the subprime era.", link: doi("10.1007/s11146-009-9218-7"), kind: "doi" },
      { cite: "Kelly, A. (2008). \"Skin in the game\": Zero downpayment mortgage default. Journal of Housing Research, 17(2), 75–99.", note: "FHA loans with zero down payment — including gifted down payments — defaulted at much higher rates than loans with borrower equity.", link: doi("10.1080/10835547.2008.12091991"), kind: "doi" },
      { cite: "Bhutta, N., & Ringo, D. (2021). The effect of interest rates on home buying: Evidence from a shock to mortgage insurance premiums. Journal of Monetary Economics, 118, 195–211.", note: "A cut in FHA mortgage insurance premiums increased home purchases among affected borrowers, showing how much the insurance line matters to the decision.", link: doi("10.1016/j.jmoneco.2020.10.001"), kind: "doi" },
      { cite: "Gabriel, S. A., & Rosenthal, S. S. (1991). Credit rationing, race, and the mortgage market. Journal of Urban Economics, 29(3), 371–379.", note: "Early evidence on credit rationing in conventional lending, part of why government-insured programs exist.", link: doi("10.1016/0094-1190(91)90007-t"), kind: "doi" },
      { cite: "Immergluck, D. (2011). From risk-limited to risk-loving mortgage markets: Origins of the U.S. subprime crisis and prospects for reform. Journal of Housing and the Built Environment, 26(3), 245–262.", note: "History of how the mortgage market moved from limited to excessive risk-taking — context for why FHA's rules are conservative.", link: doi("10.1007/s10901-011-9224-y"), kind: "doi" },
    ],
  },
  {
    id: "gs-home-w2-down-payment-gift",
    goal: "home", tier: "moderate", section: "8962",
    title: "Ask for the Gift, Document It, and Do Not Let It Replace Your Own Equity",
    subtitle: "Parental transfers move first-time buyers into ownership earlier and are a major channel of the racial wealth gap; a gifted down payment with no owner equity defaults like a zero-down loan",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "months", durability: "lasting", effort: "moderate" },
    feeds: ["down-payment speed", "borrowing-constraint relief", "family transparency"],
    description:
      "Studies from the 1990s onward show that intergenerational transfers relax borrowing constraints and accelerate first-time purchase, that recipients often reduce their own saving in response, and that differences in parental help explain part of the Black–White gap in the transition to ownership. Swedish, Dutch and U.S. cohort studies confirm that parental wealth and assistance predict who buys and when. The FHA evidence that gifted down payments without borrower equity default at high rates is the caution. The boundary: gift rules, documentation and tax reporting differ by loan program and jurisdiction; check them with the lender.",
    action: "If family can help, ask early and specifically — an amount, a date, and whether it is a gift or a loan — and get the lender's gift-letter requirements before the money moves. Keep contributing your own savings so you hold real equity at closing, and if help comes from siblings or grandparents, tell everyone involved to avoid later resentment.",
    sources: [
      { cite: "Engelhardt, G. V., & Mayer, C. J. (1998). Intergenerational transfers, borrowing constraints, and saving behavior: Evidence from the housing market. Journal of Urban Economics, 44(1), 135–157.", note: "Transfers from relatives relax down-payment constraints for first-time buyers, who in turn save less themselves — the substitution effect to guard against.", link: doi("10.1006/juec.1997.2064"), kind: "doi" },
      { cite: "Guiso, L., & Jappelli, T. (2002). Private transfers, borrowing constraints, and timing of homeownership. Journal of Money, Credit, and Banking, 34(2), 315–339.", note: "Italian survey evidence that private transfers shorten the time to first homeownership for credit-constrained households.", link: doi("10.1353/mcb.2002.0039"), kind: "doi" },
      { cite: "Charles, K. K., & Hurst, E. (2002). The transition to home ownership and the black-white wealth gap. Review of Economics and Statistics, 84(2), 281–297.", note: "Differences in parental help with down payments and in loan-application behavior explain part of the Black–White gap in the transition to ownership.", link: doi("10.1162/003465302317411532"), kind: "doi" },
      { cite: "Lee, H., Myers, D., Painter, G., Thunell, J., & Zissimopoulos, J. (2020). The role of parental financial assistance in the transition to homeownership by young adults. Journal of Housing Economics, 47, 101597.", note: "U.S. panel data on how parental financial assistance shapes young adults' transition into homeownership.", link: doi("10.1016/j.jhe.2018.08.002"), kind: "doi" },
      { cite: "Helderman, A., & Mulder, C. (2007). Intergenerational transmission of homeownership: The roles of gifts and continuities in housing market characteristics. Urban Studies, 44(2), 231–247.", note: "Dutch evidence that gifts and shared housing-market context both transmit ownership across generations.", link: doi("10.1080/00420980601075018"), kind: "doi" },
      { cite: "Öst, C. E. (2012). Parental wealth and first-time homeownership: A cohort study of family background and young adults' housing situation in Sweden. Urban Studies, 49(10), 2137–2152.", note: "Swedish cohort study linking parental wealth to young adults' first-time homeownership.", link: doi("10.1177/0042098011427185"), kind: "doi" },
      { cite: "Luea, H. M. (2008). The impact of financial help and gifts on housing demand and cost burdens. Contemporary Economic Policy, 26(3), 420–432.", note: "Estimates how financial help and gifts change housing demand and cost burdens for recipients.", link: doi("10.1111/j.1465-7287.2008.00106.x"), kind: "doi" },
      { cite: "Kelly, A. (2008). \"Skin in the game\": Zero downpayment mortgage default. Journal of Housing Research, 17(2), 75–99.", note: "Gifted down payments that leave the borrower with no equity of their own defaulted at rates similar to zero-down loans — the reason to keep saving.", link: doi("10.1080/10835547.2008.12091991"), kind: "doi" },
    ],
  },
  {
    id: "gs-home-w2-manufactured-on-owned-land",
    goal: "home", tier: "advanced", section: "8963",
    title: "Consider a Manufactured Home — on Land You Own, Titled as Real Property",
    subtitle: "Manufactured housing is the largest unsubsidized source of affordable homes; the outcomes split on whether you own the lot",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "months", durability: "lasting", effort: "high" },
    feeds: ["affordability", "ownership access", "displacement risk"],
    description:
      "Housing-policy research finds manufactured housing contributes substantially to affordable housing in the United States, with very different outcomes across tenures: owners who also own the land face lower cost and displacement risk than residents of rented lots in parks, where park closures displace low-income residents wholesale. Studies document zoning and financing barriers to placing manufactured homes in metropolitan areas, stigma that residents actively manage, and little or no negative effect of manufactured homes on adjacent property values. The boundary: appreciation evidence in the peer-reviewed literature is thin, and financing terms for homes titled as personal property are worse than mortgages.",
    action: "If a site-built home is out of reach, price a new manufactured home on a lot you would own, titled as real property with a conventional or FHA mortgage rather than a chattel loan, and check local zoning for placement rules. Do not buy in a rented-lot park without reading the lease, the rent history and the park owner's track record.",
    sources: [
      { cite: "Durst, N. J., & Sullivan, E. (2019). The contribution of manufactured housing to affordable housing in the United States: Assessing variation among manufactured housing tenures and community types. Housing Policy Debate, 29(6), 880–898.", note: "Quantifies manufactured housing's share of affordable housing and shows how affordability and risk vary by tenure and community type — land ownership is the dividing line.", link: doi("10.1080/10511482.2019.1605534"), kind: "doi" },
      { cite: "Genz, R. (2001). Why advocates need to rethink manufactured housing. Housing Policy Debate, 12(2), 393–414.", note: "Argues that the depreciation and instability associated with manufactured homes stem from land tenure, financing and titling rules rather than the homes themselves.", link: doi("10.1080/10511482.2001.9521411"), kind: "doi" },
      { cite: "Dawkins, C. J., & Koebel, C. T. (2010). Overcoming barriers to placing manufactured housing in metropolitan communities. Journal of the American Planning Association, 76(1), 73–88.", note: "Identifies zoning, financing and perception barriers to placing manufactured homes in metropolitan areas.", link: doi("10.1080/01944360903401052"), kind: "doi" },
      { cite: "Sullivan, E. (2017). Moving out: Mapping mobile home park closures to analyze spatial patterns of low-income residential displacement. City & Community, 16(3), 304–329.", note: "Maps park closures in Texas and Florida to show how rented-lot residents are displaced when land is redeveloped.", link: doi("10.1111/cico.12252"), kind: "doi" },
      { cite: "Wubneh, M., & Shen, G. (2004). The impact of manufactured housing on adjacent residential property values: A GIS approach based on three North Carolina counties. Review of Urban & Regional Development Studies, 16(1), 56–73.", note: "GIS analysis finding manufactured housing had little negative effect on adjacent property values.", link: doi("10.1111/j.1467-940x.2004.00080.x"), kind: "doi" },
      { cite: "MacTavish, K. A. (2007). The wrong side of the tracks: Social inequality and mobile home park residence. Community Development, 38(1), 74–91.", note: "Ethnographic account of how park residence shapes families' social standing and children's opportunities.", link: doi("10.1080/15575330709490186"), kind: "doi" },
      { cite: "Kusenbach, M. (2009). Salvaging decency: Mobile home residents' strategies of managing the stigma of \"trailer\" living. Qualitative Sociology, 32(4), 399–428.", note: "Interview study of how residents manage the stigma attached to manufactured housing.", link: doi("10.1007/s11133-009-9139-z"), kind: "doi" },
    ],
  },
  {
    id: "gs-home-w2-relocation-stress",
    goal: "home", tier: "fundamental", section: "8964",
    title: "Plan the Move as a Stressor, Not a Reward",
    subtitle: "Moving ranks on the classic life-events scale, frequent childhood moves predict worse outcomes, and the happiness bump from a move fades",
    evidenceTag: "Moderate",
    impact: { magnitude: 2, latency: "weeks", durability: "transient", effort: "low" },
    feeds: ["family stability", "social ties", "realistic expectations"],
    description:
      "Residential change appears on the Social Readjustment Rating Scale, and psychological research links frequent moves to weaker social ties and lower wellbeing, with mortality effects among introverts in one large panel. A systematic review associates childhood residential mobility with worse health and behavioral outcomes, British panel data show wellbeing rising in anticipation of a move and then returning to baseline, and women in low-income samples bear a larger psychological cost. The boundary: much of this concerns frequent or forced moves; a single planned move into ownership is not the same exposure, but it is still a disruption to plan for.",
    action: "Give the move a budget line for the first three months — not just boxes but time off, meals and childcare — and decide in advance how you will rebuild the social layer: the first neighbor you will invite over, the club or congregation you will join, the school contact you will make. Do not schedule any other major life change within sixty days of closing.",
    sources: [
      { cite: "Holmes, T. H., & Rahe, R. H. (1967). The social readjustment rating scale. Journal of Psychosomatic Research, 11(2), 213–218.", note: "The original life-events scale, on which a change in residence is one of the scored stressors.", link: doi("10.1016/0022-3999(67)90010-4"), kind: "doi" },
      { cite: "Oishi, S. (2010). The psychology of residential mobility: Implications for the self, social relationships, and well-being. Perspectives on Psychological Science, 5(1), 5–21.", note: "Review of how residential mobility shapes identity, friendships and wellbeing.", link: doi("10.1177/1745691609356781"), kind: "doi" },
      { cite: "Oishi, S., & Schimmack, U. (2010). Residential mobility, well-being, and mortality. Journal of Personality and Social Psychology, 98(6), 980–994.", note: "Frequent childhood moves were associated with lower wellbeing and higher mortality in adulthood, especially for introverts, with social relationships as the mediator.", link: doi("10.1037/a0019389"), kind: "doi" },
      { cite: "Jelleyman, T., & Spencer, N. (2008). Residential mobility in childhood and health outcomes: A systematic review. Journal of Epidemiology and Community Health, 62(7), 584–592.", note: "Systematic review linking childhood residential mobility to behavioral and health problems.", link: doi("10.1136/jech.2007.060103"), kind: "doi" },
      { cite: "Nowok, B., van Ham, M., Findlay, A. M., & Gayle, V. (2013). Does migration make you happy? A longitudinal study of internal migration and subjective well-being. Environment and Planning A: Economy and Space.", note: "British panel evidence that wellbeing rises before an internal move and returns to its prior level afterward — the reward is temporary.", link: doi("10.1068/a45287"), kind: "doi" },
      { cite: "Magdol, L. (2002). Is moving gendered? The effects of residential mobility on the psychological well-being of men and women. Sex Roles, 47(11–12), 553–560.", note: "Moving carried larger psychological costs for women than men in a low-income sample.", link: doi("10.1023/a:1022025905755"), kind: "doi" },
      { cite: "Winstanley, A., Thorns, D. C., & Perkins, H. C. (2002). Moving house, creating home: Exploring residential mobility. Housing Studies, 17(6), 813–832.", note: "Qualitative study of how households turn a new house into a home after moving — the work the plan should fund.", link: doi("10.1080/02673030216000"), kind: "doi" },
    ],
  },
  {
    id: "gs-home-w2-civic-engagement",
    goal: "home", tier: "moderate", section: "8965",
    title: "Show Up Locally After You Buy — and Watch the Homevoter Reflex",
    subtitle: "Owners participate more in local civic life and local politics; much of that participation is defending property values, which is not the same as being a better neighbor",
    evidenceTag: "Strong",
    impact: { magnitude: 2, latency: "months", durability: "lasting", effort: "low" },
    feeds: ["neighborhood ties", "local voice", "honest self-awareness"],
    description:
      "National surveys find homeowners participate more in neighborhood and civic activity, and early panel work with low-income buyers found ownership raised social and political involvement. Administrative studies of property records and meeting minutes show buying a home causes people to turn out in local elections and to appear at zoning meetings — mostly to oppose nearby development — and renters facing high rents behave the same way. Reviews of the micro-level consequences of ownership caution that much of the civic effect reflects stability and self-interest rather than ownership itself. The boundary: the effects are real but modest, and the strongest causal evidence is about protecting property values.",
    action: "In your first six months, do three things: introduce yourself to the neighbors on both sides and across the street, attend one local government or school-board meeting, and join one neighborhood organization. When a development proposal comes up, notice whether you are objecting on the merits or on price anxiety before you speak.",
    sources: [
      { cite: "McCabe, B. J. (2013). Are homeowners better citizens? Homeownership and community participation in the United States. Social Forces, 91(3), 929–954.", note: "National survey data: homeowners participate more in neighborhood groups and local politics, with the effect concentrated in activities that protect property values.", link: doi("10.1093/sf/sos185"), kind: "doi" },
      { cite: "Rohe, W. M., & Stegman, M. A. (1994). The impact of home ownership on the social and political involvement of low-income people. Urban Affairs Quarterly, 30(1), 152–172.", note: "Panel of low-income buyers in Baltimore finding ownership increased some forms of neighborhood and political involvement.", link: doi("10.1177/004208169403000108"), kind: "doi" },
      { cite: "Yoder, J. (2020). Does property ownership lead to participation in local politics? Evidence from property records and meeting minutes. American Political Science Review, 114(4), 1213–1229.", note: "Links property records to meeting minutes: buying a home increases participation in local government meetings, largely to oppose new housing.", link: doi("10.1017/s0003055420000556"), kind: "doi" },
      { cite: "Hall, A. B., & Yoder, J. (2022). Does homeownership influence political behavior? Evidence from administrative data. The Journal of Politics, 84(1), 351–366.", note: "Administrative data on millions of individuals: becoming a homeowner increases local election turnout, with the effect larger where more is at stake for property values.", link: doi("10.1086/714932"), kind: "doi" },
      { cite: "Hankinson, M. (2018). When do renters behave like homeowners? High rent, price anxiety, and NIMBYism. American Political Science Review, 112(3), 473–493.", note: "Survey experiments showing renters in high-rent cities oppose nearby development much as owners do — price anxiety, not ownership, drives the reflex.", link: doi("10.1017/s0003055418000035"), kind: "doi" },
      { cite: "Dietz, R. D., & Haurin, D. R. (2003). The social and private micro-level consequences of homeownership. Journal of Urban Economics, 54(3), 401–450.", note: "Review of the evidence on ownership's social and private consequences, including civic participation, and of how much is selection versus effect.", link: doi("10.1016/s0094-1190(03)00080-9"), kind: "doi" },
    ],
  },
  {
    id: "gs-home-w2-rent-control-decision",
    goal: "home", tier: "fundamental", section: "8966",
    title: "If You Rent Under Rent Control, Price the Control Into the Buy Decision",
    subtitle: "Rent control keeps incumbent tenants in place and lowers their rent, but shrinks supply and raises market rents around them; leaving a controlled unit is a real cost",
    evidenceTag: "Strong",
    impact: { magnitude: 2, latency: "weeks", durability: "lasting", effort: "low" },
    feeds: ["rent-vs-buy math", "mobility planning", "realistic rent forecasts"],
    description:
      "The San Francisco expansion study found rent control reduced covered tenants' mobility by about 20 percent and prevented displacement, while landlords cut rental supply by about 15 percent, likely raising market rents. Massachusetts studies of the end of rent control found decontrol raised prices of both formerly controlled and neighboring properties and increased investment. Classic work shows rent control misallocates housing — people stay in units that no longer fit — and reviews of the international evidence summarize consistent supply and misallocation costs alongside real tenant benefits. The boundary: effects depend on the design of the control, and the benefit to an incumbent tenant is exactly what makes leaving expensive.",
    action: "If you live in a rent-stabilized unit, compute the gap between your rent and the market rent for a comparable unit, multiply by twelve, and add it to the annual cost of buying in your rent-vs-buy comparison. If you decide to stay, use the discount to save the down payment faster, and know that the discount grows the longer you stay — which is why the decision gets harder, not easier, each year.",
    sources: [
      { cite: "Diamond, R., McQuade, T., & Qian, F. (2019). The effects of rent control expansion on tenants, landlords, and inequality: Evidence from San Francisco. American Economic Review, 109(9), 3365–3394.", note: "Quasi-experimental San Francisco evidence: rent control cut covered renters' mobility by 20% and prevented displacement, while landlords reduced rental supply by 15%, likely raising market rents in the long run.", link: doi("10.1257/aer.20181289"), kind: "doi" },
      { cite: "Autor, D. H., Palmer, C. J., & Pathak, P. A. (2014). Housing market spillovers: Evidence from the end of rent control in Cambridge, Massachusetts. Journal of Political Economy, 122(3), 661–717.", note: "Decontrol in Cambridge raised the value of formerly controlled properties and of neighboring uncontrolled ones — rent control's effects spill over.", link: doi("10.1086/675536"), kind: "doi" },
      { cite: "Sims, D. P. (2007). Out of control: What can we learn from the end of Massachusetts rent control? Journal of Urban Economics, 61(1), 129–151.", note: "The end of Massachusetts rent control raised rents and increased maintenance and new supply in formerly controlled areas.", link: doi("10.1016/j.jue.2006.06.004"), kind: "doi" },
      { cite: "Glaeser, E. L., & Luttmer, E. F. P. (2003). The misallocation of housing under rent control. American Economic Review, 93(4), 1027–1046.", note: "New York evidence that rent control leads to substantial misallocation — households living in apartments that no longer match their needs because moving means losing the discount.", link: doi("10.1257/000282803769206188"), kind: "doi" },
      { cite: "Arnott, R. (1995). Time for revisionism on rent control? Journal of Economic Perspectives, 9(1), 99–120.", note: "Argues that modern, moderate rent-control designs differ from the textbook case and that their effects are more nuanced.", link: doi("10.1257/jep.9.1.99"), kind: "doi" },
      { cite: "Early, D. W. (2000). Rent control, rental housing supply, and the distribution of tenant benefits. Journal of Urban Economics, 48(2), 185–204.", note: "Estimates who actually captures rent-control benefits and how supply responds — the benefits are unevenly distributed among tenants.", link: doi("10.1006/juec.1999.2163"), kind: "doi" },
      { cite: "Kholodilin, K. A. (2024). Rent control effects through the lens of empirical research: An almost complete review of the literature. Journal of Housing Economics, 63, 101983.", note: "Near-comprehensive review of the empirical rent-control literature across countries, summarizing effects on rents, supply, quality, mobility and misallocation.", link: doi("10.1016/j.jhe.2024.101983"), kind: "doi" },
    ],
  },
  {
    id: "gs-home-w2-hold-seven-years",
    goal: "home", tier: "elite", section: "8967",
    title: "Buy the House You Can Hold for Seven Years",
    subtitle: "Transaction costs and the expected length of stay decide whether owning beats renting; equity constraints and price drops lock owners in",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "months", durability: "lasting", effort: "high" },
    feeds: ["ownership timing", "risk management", "equity building"],
    description:
      "Models and data on housing careers show that the value of owning rises with the expected length of stay because transaction costs are large and paid at each move, and that households with little equity are the ones most exposed when prices fall — they cannot trade up, and they are far less likely to move at all, even for a better job. Owner-occupied housing also hedges rent risk, a benefit that accrues only to those who stay. The boundary: the seven-year rule of thumb is a planning heuristic, not a finding; the research says 'longer is better' and 'thin equity is dangerous', and the right horizon depends on local transaction costs and price volatility.",
    action: "Before you buy, write down the probability you will still want this house in seven years — job, family size, school, aging parents — and if it is under half, keep renting or buy something you would be content to stay in. Put down enough that a 10 percent price decline would not leave you underwater, so the decision to move stays yours.",
    sources: [
      { cite: "Haurin, D. R., & Gill, H. L. (2002). The impact of transaction costs and the expected length of stay on homeownership. Journal of Urban Economics, 51(3), 563–584.", note: "Households with a shorter expected length of stay are less likely to own, because transaction costs make ownership uneconomic over short horizons.", link: doi("10.1006/juec.2001.2258"), kind: "doi" },
      { cite: "Stein, J. C. (1995). Prices and trading volume in the housing market: A model with down-payment effects. The Quarterly Journal of Economics, 110(2), 379–406.", note: "Model showing how down-payment constraints make thin-equity owners unable to trade up when prices fall, amplifying price and volume swings.", link: doi("10.2307/2118444"), kind: "doi" },
      { cite: "Ortalo-Magné, F., & Rady, S. (2006). Housing market dynamics: On the contribution of income shocks and credit constraints. Review of Economic Studies, 73(2), 459–485.", note: "Life-cycle model of the housing ladder in which credit constraints on first-time buyers drive the dynamics of the whole market.", link: doi("10.1111/j.1467-937x.2006.383_1.x"), kind: "doi" },
      { cite: "Ferreira, F., Gyourko, J., & Tracy, J. (2010). Housing busts and household mobility. Journal of Urban Economics, 68(1), 34–45.", note: "Owners with negative equity were roughly a third less likely to move — lock-in that a larger down payment prevents.", link: doi("10.1016/j.jue.2009.10.007"), kind: "doi" },
      { cite: "Engelhardt, G. V. (2003). Nominal loss aversion, housing equity constraints, and household mobility: Evidence from the United States. Journal of Urban Economics, 53(1), 171–195.", note: "Nominal losses and equity constraints both reduce household mobility in U.S. panel data.", link: doi("10.1016/s0094-1190(02)00511-9"), kind: "doi" },
      { cite: "Clark, W. A. V., Deurloo, M. C., & Dieleman, F. M. (2003). Housing careers in the United States, 1968-93: Modelling the sequencing of housing states. Urban Studies, 40(1), 143–160.", note: "Twenty-five years of PSID housing careers showing the typical sequencing of renting, first ownership and later moves.", link: doi("10.1080/00420980220080211"), kind: "doi" },
      { cite: "Sinai, T., & Souleles, N. S. (2005). Owner-occupied housing as a hedge against rent risk. Quarterly Journal of Economics, 120(2), 763–789.", note: "Owning hedges the risk of future rent increases, and the value of that hedge rises with the expected length of stay.", link: doi("10.1162/0033553053970197"), kind: "doi" },
    ],
  },
  {
    id: "gs-home-w2-starter-home-myth",
    goal: "home", tier: "fundamental", section: "8967",
    title: "Myth: Buy a Starter Home Now and Trade Up in Three Years",
    subtitle: "Two rounds of transaction costs in a few years eat the equity, and a price dip leaves the starter-home owner unable to move at all",
    evidenceTag: "Strong",
    impact: { magnitude: 1, latency: "months", durability: "lasting", effort: "moderate" },
    callout: "Rated at the floor because the plan fails on the research's own terms. Ownership pays over long stays because selling costs are large; a planned short hold hands those costs to agents and lenders twice, and if prices fall in between, thin equity locks you in rather than launching you up the ladder.",
    feeds: ["honest ownership math", "risk awareness"],
    description:
      "The housing-ladder literature describes trading up as something households do over long housing careers, constrained by the equity they have built. Studies of transaction costs show short expected stays make ownership uneconomic, and studies of housing busts show owners with little or negative equity are markedly less likely to move — the opposite of the starter-home story. The boundary: buying a modest home you intend to keep is sound; the myth is the deliberate short hold as a stepping stone.",
    action: "If your plan for a home is 'three years and then something bigger', run the numbers with 8–10 percent round-trip transaction costs and a flat-price scenario before you sign; if the result is a loss, either rent for those three years or buy the home you would keep.",
    sources: [
      { cite: "Haurin, D. R., & Gill, H. L. (2002). The impact of transaction costs and the expected length of stay on homeownership. Journal of Urban Economics, 51(3), 563–584.", note: "Transaction costs and expected length of stay jointly determine whether owning makes sense — short planned stays fail the test.", link: doi("10.1006/juec.2001.2258"), kind: "doi" },
      { cite: "Ferreira, F., Gyourko, J., & Tracy, J. (2010). Housing busts and household mobility. Journal of Urban Economics, 68(1), 34–45.", note: "Negative equity sharply reduces mobility — the starter-home owner who bought at the top cannot trade up.", link: doi("10.1016/j.jue.2009.10.007"), kind: "doi" },
      { cite: "Engelhardt, G. V. (2003). Nominal loss aversion, housing equity constraints, and household mobility: Evidence from the United States. Journal of Urban Economics, 53(1), 171–195.", note: "Owners facing nominal losses and equity constraints move less — behavioral and financial lock-in at once.", link: doi("10.1016/s0094-1190(02)00511-9"), kind: "doi" },
      { cite: "Stein, J. C. (1995). Prices and trading volume in the housing market: A model with down-payment effects. The Quarterly Journal of Economics, 110(2), 379–406.", note: "Formalizes why down-payment constraints stop thin-equity owners from trading up after a price decline.", link: doi("10.2307/2118444"), kind: "doi" },
      { cite: "Clark, W. A. V., Deurloo, M. C., & Dieleman, F. M. (2003). Housing careers in the United States, 1968-93: Modelling the sequencing of housing states. Urban Studies, 40(1), 143–160.", note: "Real housing careers unfold over decades, with trading up tied to life-course events rather than a fixed timetable.", link: doi("10.1080/00420980220080211"), kind: "doi" },
    ],
  },
];
