// Goal shelf, WAVE 2: LEGACY — memorialize a life in meaningful ways (sections 9250–9299).
// Verification: every DOI below was resolved against the Crossref record
// (api.crossref.org) on 2026-09-11. See ../types.ts for the contract. Popular
// advice the evidence does not support is rated at the floor (magnitude 1) with
// a callout. Nothing here is medical, legal, tax or financial advice.
import { doi, type GoalShelfCluster } from "../types";

export const SECTIONS: Record<string, string> = {
  "9250": "Guided Autobiography, Memoir Programs and Life-Review Therapy",
  "9251": "Recorded Life-Story Interviews and Narrative Identity",
  "9252": "Genealogy, Family History and the Intergenerational Self",
  "9253": "Heirlooms and the Transmission of Objects",
  "9254": "Advance Funeral Planning and Advance Care Planning",
  "9255": "Organ and Body Donation Decisions",
  "9256": "Planned Giving and Philanthropy in Later Life",
  "9257": "Scholarships, Endowments and Named Gifts as Memorials",
  "9258": "Experience Corps, Volunteering and Intergenerational Mentoring",
  "9259": "Meaning-Centered Psychotherapy and Dignity Therapy",
  "9260": "Wisdom — Self-Distancing and Wise Reasoning",
  "9261": "Life-Story Work in Dementia Care",
  "9262": "Letters to Your Future Self and Time Capsules",
  "9263": "Legacy, Generativity and Posttraumatic Growth",
  "9264": "Continuing Bonds and Grief Rituals",
  "9265": "Digital Afterlife and Account Planning",
  "9266": "Death Cafés and Death Education",
  "9267": "The Bucket List — What the Evidence Says",
};

export const CLUSTERS: GoalShelfCluster[] = [
  {
    id: "gs-legacy-w2-guided-autobiography",
    goal: "legacy", tier: "moderate", section: "9250",
    title: "Write Your Life in a Guided Autobiography Group",
    subtitle: "Themed weekly writing plus a small group is the memoir method with the longest research record",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "weeks", durability: "lasting", effort: "moderate" },
    feeds: ["narrative identity", "family memory", "wellbeing"],
    description:
      "Guided autobiography, developed by James Birren, pairs weekly themed writing (branching points, family, work, money, health, love, death) with reading aloud in a small group; an early study traced its effects on adult development in the family context. Meta-analyses of reminiscence interventions find moderate improvements in psychological well-being and reductions in depressive symptoms in older adults, with structured, integrative life review outperforming simple reminiscence. Narrative-identity research explains why: the story a person tells of their life is a working part of personality, and revising it changes how the past is carried. The boundary is that most trials are with older adults and effects are moderate, so treat this as a durable, not dramatic, investment.",
    action: "Join or start a guided-autobiography group: ten weekly sessions, one two-page life-theme essay written before each, read aloud to four to eight people. Keep the ten essays as the first draft of your memoir.",
    reinforcement: [
      { kind: "book", title: "Telling the Stories of Life through Guided Autobiography Groups", by: "James E. Birren & Kathryn N. Cochran", note: "The manual for the method the cited studies evaluate; themes and session structure." },
    ],
    sources: [
      { cite: "de Vries, B., Birren, J. E., & Deutchman, D. E. (1990). Adult development through guided autobiography: The family context. Family Relations, 39(1), 3–7.", note: "Guided autobiography groups examined in the family context: structured life-theme writing and sharing supported adult development and family understanding.", link: doi("10.2307/584941"), kind: "doi" },
      { cite: "Bohlmeijer, E., Roemer, M., Cuijpers, P., & Smit, F. (2007). The effects of reminiscence on psychological well-being in older adults: A meta-analysis. Aging & Mental Health, 11(3), 291–300.", note: "Meta-analysis of reminiscence interventions in older adults: moderate positive effects on psychological well-being, larger for structured life review.", link: doi("10.1080/13607860600963547"), kind: "doi" },
      { cite: "Pinquart, M., & Forstmeier, S. (2012). Effects of reminiscence interventions on psychosocial outcomes: A meta-analysis. Aging & Mental Health, 16(5), 541–558.", note: "Large meta-analysis of reminiscence interventions: improvements across depression, ego-integrity, purpose in life and death preparation, with life review the most effective form.", link: doi("10.1080/13607863.2011.651434"), kind: "doi" },
      { cite: "Westerhof, G. J., Bohlmeijer, E., & Webster, J. D. (2010). Reminiscence and mental health: A review of recent progress in theory, research and interventions. Ageing and Society, 30(4), 697–721.", note: "Review of reminiscence and mental health distinguishing simple, evaluative and instrumental reminiscence and the conditions under which each helps.", link: doi("10.1017/s0144686x09990328"), kind: "doi" },
      { cite: "Webster, J. D., Bohlmeijer, E. T., & Westerhof, G. J. (2010). Mapping the future of reminiscence: A conceptual guide for research and practice. Research on Aging, 32(4), 527–564.", note: "Conceptual guide to reminiscence research and practice: which functions of remembering (identity, problem-solving, teaching) support health and which do not.", link: doi("10.1177/0164027510364122"), kind: "doi" },
      { cite: "McAdams, D. P. (2001). The psychology of life stories. Review of General Psychology, 5(2), 100–122.", note: "The life-story model of identity: people construct an internalised, evolving narrative that provides unity and purpose, and that narrative can be revised.", link: doi("10.1037/1089-2680.5.2.100"), kind: "doi" },
      { cite: "McAdams, D. P., & McLean, K. C. (2013). Narrative identity. Current Directions in Psychological Science, 22(3), 233–238.", note: "Narrative identity as a core layer of personality, with themes of redemption and agency linked to well-being across studies.", link: doi("10.1177/0963721413475622"), kind: "doi" },
    ],
  },
  {
    id: "gs-legacy-w2-life-review-therapy",
    goal: "legacy", tier: "advanced", section: "9250",
    title: "Life-Review Therapy When Looking Back Hurts",
    subtitle: "A therapist-guided life review reduced depressive symptoms in randomized trials, through improved meaning",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "weeks", durability: "lasting", effort: "moderate" },
    feeds: ["meaning in life", "mood", "integrated life story"],
    description:
      "For people whose memories bring more regret than integration, structured life-review therapy delivered by a trained facilitator has randomized-trial support: a pragmatic RCT in older adults with moderate depressive symptoms found reduced depression versus usual care, and a second trial showed the effect ran through improvement in personal meaning. Meta-analysis of reminiscence and life review for late-life depression found effects comparable to other established treatments. The protocol is clinical rather than a hobby: sessions follow a set structure (childhood, adolescence, adulthood, integration) and target the evaluative stance toward one's past.",
    action: "If reviewing your life brings persistent low mood, ask a licensed therapist for a structured life-review protocol (eight to twelve sessions moving from childhood to integration). Bring photographs, letters and a timeline to the first session.",
    sources: [
      { cite: "Korte, J., Bohlmeijer, E. T., Cappeliez, P., Smit, F., & Westerhof, G. J. (2012). Life review therapy for older adults with moderate depressive symptomatology: A pragmatic randomized controlled trial. Psychological Medicine, 42(6), 1163–1173.", note: "Pragmatic randomized controlled trial: life-review therapy reduced depressive symptoms in older adults with moderate depression compared with care as usual.", link: doi("10.1017/s0033291711002042"), kind: "doi" },
      { cite: "Westerhof, G. J., Bohlmeijer, E. T., van Beljouw, I. M. J., & Pot, A. M. (2010). Improvement in personal meaning mediates the effects of a life review intervention on depressive symptoms in a randomized controlled trial. The Gerontologist, 50(4), 541–549.", note: "In an RCT, improvement in personal meaning mediated the effect of a life-review intervention on depressive symptoms.", link: doi("10.1093/geront/gnp168"), kind: "doi" },
      { cite: "Bohlmeijer, E., Smit, F., & Cuijpers, P. (2003). Effects of reminiscence and life review on late-life depression: A meta-analysis. International Journal of Geriatric Psychiatry, 18(12), 1088–1094.", note: "Meta-analysis of reminiscence and life review for late-life depression: effect sizes comparable to pharmacotherapy and psychotherapy.", link: doi("10.1002/gps.1018"), kind: "doi" },
      { cite: "Pinquart, M., & Forstmeier, S. (2012). Effects of reminiscence interventions on psychosocial outcomes: A meta-analysis. Aging & Mental Health, 16(5), 541–558.", note: "Meta-analysis across outcomes: life-review interventions produced the largest gains, particularly for people with depressive symptoms.", link: doi("10.1080/13607863.2011.651434"), kind: "doi" },
    ],
  },
  {
    id: "gs-legacy-w2-recorded-interviews",
    goal: "legacy", tier: "fundamental", section: "9251",
    title: "Record One Life-Story Interview a Month",
    subtitle: "The stories parents and grandparents tell become part of the next generation's identity",
    evidenceTag: "Emerging",
    impact: { magnitude: 3, latency: "weeks", durability: "lasting", effort: "low" },
    feeds: ["family memory", "intergenerational identity", "connection"],
    description:
      "Narrative-identity research shows that people build a sense of self from stories, and a developmental review finds that intergenerational narratives — the stories parents and grandparents tell about their own lives — become part of adolescents' and young adults' identity and well-being. Children whose families narrate together with more elaboration and collaboration show a stronger sense of self, and knowing more of the family's story is linked to better adjustment. Direct evidence that recording an interview improves the interviewer's or interviewee's well-being is limited, so this is an emerging protocol: cheap, durable, and the raw material for everything else on this shelf.",
    action: "Once a month, record a 40-minute audio interview with a parent, grandparent or elder using ten fixed questions (earliest memory, hardest year, proudest moment, what they want remembered). Store two copies and share one with the family.",
    sources: [
      { cite: "McAdams, D. P. (2001). The psychology of life stories. Review of General Psychology, 5(2), 100–122.", note: "Life stories as identity: a person's internalised narrative gives their life unity and purpose and is shaped by the stories they hear.", link: doi("10.1037/1089-2680.5.2.100"), kind: "doi" },
      { cite: "McAdams, D. P., & McLean, K. C. (2013). Narrative identity. Current Directions in Psychological Science, 22(3), 233–238.", note: "Narrative identity research: the way people narrate their past, including themes of growth and redemption, is associated with well-being.", link: doi("10.1177/0963721413475622"), kind: "doi" },
      { cite: "Merrill, N., & Fivush, R. (2016). Intergenerational narratives and identity across development. Developmental Review, 40, 72–92.", note: "Developmental review of intergenerational narratives: stories told about parents' and grandparents' lives contribute to children's and adolescents' identity.", link: doi("10.1016/j.dr.2016.03.001"), kind: "doi" },
      { cite: "Bohanek, J. G., Marin, K. A., Fivush, R., & Duke, M. P. (2006). Family narrative interaction and children's sense of self. Family Process, 45(1), 39–54.", note: "Families that narrated shared events in a more collaborative, elaborative style had children with a stronger sense of self.", link: doi("10.1111/j.1545-5300.2006.00079.x"), kind: "doi" },
      { cite: "Duke, M. P., Lazarus, A., & Fivush, R. (2008). Knowledge of family history as a clinically useful index of psychological well-being and prognosis: A brief report. Psychotherapy: Theory, Research, Practice, Training, 45(2), 268–272.", note: "Knowledge of family history was associated with better psychological well-being in children and adolescents, proposed as a clinically useful index.", link: doi("10.1037/0033-3204.45.2.268"), kind: "doi" },
    ],
  },
  {
    id: "gs-legacy-w2-family-history",
    goal: "legacy", tier: "moderate", section: "9252",
    title: "Build the Family Narrative, Not Just the Family Tree",
    subtitle: "Knowing the family's story tracks well-being; genealogy is a demanding, rewarding lifelong hobby",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "months", durability: "lasting", effort: "moderate" },
    feeds: ["identity", "belonging", "intergenerational connection"],
    description:
      "The 'Do You Know?' line of research found that children and adolescents who knew more about their family's history — how their parents met, where grandparents grew up, family hardships — had higher well-being and self-esteem, and family narrative work links this to the way families talk about the past together. Studies of family historians describe genealogy as a serious lifelong learning pursuit driven by identity, connection and a wish to leave something behind. The evidence is correlational; the protocol therefore focuses on the part that plausibly does the work — the narrative that gets told — rather than on the completeness of the tree.",
    action: "Over three months, complete a written 'family story' of two pages per generation for three generations, using the recorded interviews on this shelf and one genealogy source per generation. Read it aloud at a family gathering and give each household a copy.",
    sources: [
      { cite: "Duke, M. P., Lazarus, A., & Fivush, R. (2008). Knowledge of family history as a clinically useful index of psychological well-being and prognosis: A brief report. Psychotherapy: Theory, Research, Practice, Training, 45(2), 268–272.", note: "Adolescents' knowledge of family history was associated with better psychological functioning, proposed as an index of family cohesion and resilience.", link: doi("10.1037/0033-3204.45.2.268"), kind: "doi" },
      { cite: "Bohanek, J. G., Marin, K. A., Fivush, R., & Duke, M. P. (2006). Family narrative interaction and children's sense of self. Family Process, 45(1), 39–54.", note: "Elaborative, collaborative family narration of shared events was associated with children's stronger sense of self.", link: doi("10.1111/j.1545-5300.2006.00079.x"), kind: "doi" },
      { cite: "Merrill, N., & Fivush, R. (2016). Intergenerational narratives and identity across development. Developmental Review, 40, 72–92.", note: "Intergenerational narratives about parents' and grandparents' experiences contribute to identity development from childhood into emerging adulthood.", link: doi("10.1016/j.dr.2016.03.001"), kind: "doi" },
      { cite: "Shaw, E. (2020). \"Who we are, and why we do it\": A demographic overview and the cited motivations of Australia's family historians. Journal of Family History, 45(1), 109–124.", note: "Survey of family historians: demographic profile and the cited motivations, including identity, curiosity and the desire to preserve stories for descendants.", link: doi("10.1177/0363199019880238"), kind: "doi" },
      { cite: "Hershkovitz, A., & Hardof-Jaffe, S. (2017). Genealogy as a lifelong learning endeavor. Leisure/Loisir, 41(4), 535–560.", note: "Genealogy studied as a lifelong learning endeavour: hobbyists develop research and technical skills while pursuing meaning and connection.", link: doi("10.1080/14927713.2017.1399817"), kind: "doi" },
    ],
  },
  {
    id: "gs-legacy-w2-heirlooms",
    goal: "legacy", tier: "fundamental", section: "9253",
    title: "Attach the Story to the Object Before You Pass It On",
    subtitle: "Possessions become 'inalienable wealth' only when the meaning travels with them",
    evidenceTag: "Moderate",
    impact: { magnitude: 2, latency: "weeks", durability: "lasting", effort: "low" },
    feeds: ["family continuity", "identity", "reduced burden on heirs"],
    description:
      "Consumer researchers who followed older adults' cherished possessions found that objects become family heirlooms — inalienable wealth that is kept out of the market — through storytelling, ritual and deliberate choice of a guardian, not through monetary value. Studies of household disbandment in later life show that deciding what to keep and where things go is emotionally taxing work, and that family members often attend to the process; valued objects also carry identity through late-life transitions. The practical implication is small and concrete: the story, the intended recipient and the reason should be written down while the owner can still tell them.",
    action: "This month, choose ten objects you want to outlast you. For each, write a card with its story and the person you intend it for, photograph the object with the card, and tell that person now.",
    sources: [
      { cite: "Price, L. L., Arnould, E. J., & Curasi, C. F. (2000). Older consumers' disposition of special possessions. Journal of Consumer Research, 27(2), 179–201.", note: "Older consumers' disposition of special possessions: the meanings, rituals and choices of recipients through which cherished objects are passed on.", link: doi("10.1086/314319"), kind: "doi" },
      { cite: "Curasi, C. F., Price, L. L., & Arnould, E. J. (2004). How individuals' cherished possessions become families' inalienable wealth. Journal of Consumer Research, 31(3), 609–622.", note: "How individuals' cherished possessions become families' inalienable wealth: storytelling, guardianship and shared meaning keep objects out of the market across generations.", link: doi("10.1086/425096"), kind: "doi" },
      { cite: "Kroger, J., & Adair, V. (2008). Symbolic meanings of valued personal objects in identity transitions of late adulthood. Identity, 8(1), 5–24.", note: "Valued personal objects carried symbolic meanings that supported identity through the transitions of late adulthood.", link: doi("10.1080/15283480701787251"), kind: "doi" },
      { cite: "Ekerdt, D. J., Sergeant, J. F., Dingel, M., & Bowen, M. E. (2004). Household disbandment in later life. The Journals of Gerontology Series B: Psychological Sciences and Social Sciences, 59(5), S265–S273.", note: "Household disbandment in later life: older adults reducing possessions faced substantial emotional and practical work in deciding what to keep and give.", link: doi("10.1093/geronb/59.5.s265"), kind: "doi" },
      { cite: "Ekerdt, D. J., & Sergeant, J. F. (2006). Family things: Attending the household disbandment of older adults. Journal of Aging Studies, 20(3), 193–205.", note: "Family members attending an older adult's household disbandment negotiated the meaning and destination of 'family things'.", link: doi("10.1016/j.jaging.2005.10.001"), kind: "doi" },
    ],
  },
  {
    id: "gs-legacy-w2-advance-planning",
    goal: "legacy", tier: "moderate", section: "9254",
    title: "Write the Care Plan and the Funeral Plan in the Same Month",
    subtitle: "Advance care planning improved end-of-life care and family outcomes in an RCT; funeral participation shapes grief",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "weeks", durability: "lasting", effort: "moderate" },
    feeds: ["family peace of mind", "control", "reduced conflict"],
    description:
      "A randomized trial of facilitated advance care planning in elderly inpatients found that patients' wishes were more likely to be known and followed and that bereaved family members had less stress, anxiety and depression; a systematic review found advance care planning consistently improved concordance between preferences and care received. Funeral research is more mixed: reviews find that funerals can help grief when the bereaved participate and find the ritual meaningful, while adverse funeral events are associated with worse adjustment, and mortuary practices vary widely in who arranges what. A written funeral plan removes decisions from the worst week of a family's life; it should be documented, not just discussed.",
    action: "This month, complete a state-recognised advance directive with a facilitator or your physician, then write a one-page funeral plan (burial or cremation, the people to involve, what you want said and played, and the budget). Give copies to two people and tell them where the originals are.",
    sources: [
      { cite: "Detering, K. M., Hancock, A. D., Reade, M. C., & Silvester, W. (2010). The impact of advance care planning on end of life care in elderly patients: Randomised controlled trial. BMJ, 340, c1345.", note: "Randomised controlled trial in elderly inpatients: facilitated advance care planning improved end-of-life care and reduced stress, anxiety and depression in surviving relatives.", link: doi("10.1136/bmj.c1345"), kind: "doi" },
      { cite: "Brinkman-Stoppelenburg, A., Rietjens, J. A. C., & van der Heide, A. (2014). The effects of advance care planning on end-of-life care: A systematic review. Palliative Medicine, 28(8), 1000–1025.", note: "Systematic review: advance care planning improved compliance with patients' wishes and reduced unwanted hospital care and family distress.", link: doi("10.1177/0269216314526272"), kind: "doi" },
      { cite: "Sudore, R. L., Lum, H. D., You, J. J., Hanson, L. C., Meier, D. E., Pantilat, S. Z., … Heyland, D. K. (2017). Defining advance care planning for adults: A consensus definition from a multidisciplinary Delphi panel. Journal of Pain and Symptom Management, 53(5), 821–832.e1.", note: "Consensus definition of advance care planning as a process of understanding and sharing values and preferences for future medical care.", link: doi("10.1016/j.jpainsymman.2016.12.331"), kind: "doi" },
      { cite: "Burrell, A., & Selman, L. E. (2022). How do funeral practices impact bereaved relatives' mental health, grief and bereavement? A mixed methods review with implications for COVID-19. OMEGA - Journal of Death and Dying, 85(2), 345–383.", note: "Mixed-methods review: funeral practices influenced bereaved relatives' grief, with participation and meaningful ritual generally helpful and exclusion harmful.", link: doi("10.1177/0030222820941296"), kind: "doi" },
      { cite: "Mitima-Verloop, H. B., Mooren, T. T. M., & Boelen, P. A. (2021). Facilitating grief: An exploration of the function of funerals and rituals in relation to grief reactions. Death Studies, 45(9), 735–745.", note: "Funerals and rituals that were perceived as helpful were associated with grief facilitation, whereas the ritual's form alone did not predict outcomes.", link: doi("10.1080/07481187.2019.1686090"), kind: "doi" },
      { cite: "Gamino, L. A., Easterling, L. W., Stirman, L. S., & Sewell, K. W. (2000). Grief adjustment as influenced by funeral participation and occurrence of adverse funeral events. OMEGA - Journal of Death and Dying, 41(2), 79–92.", note: "Grief adjustment was better with funeral participation and worse when adverse funeral events occurred.", link: doi("10.2190/qmv2-3nt5-bkd5-6aav"), kind: "doi" },
      { cite: "Walter, T. (2005). Three ways to arrange a funeral: Mortuary variation in the modern West. Mortality, 10(3), 173–192.", note: "Three ways of arranging a funeral in the modern West — by family, by professionals, or by the deceased's own plan — and their implications.", link: doi("10.1080/13576270500178369"), kind: "doi" },
    ],
  },
  {
    id: "gs-legacy-w2-donation-decision",
    goal: "legacy", tier: "fundamental", section: "9255",
    title: "Register, Then Tell Your Family — Donation Decisions Are Made by Survivors",
    subtitle: "Family consent follows prior discussion; defaults change registration but not family choices",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "days", durability: "lasting", effort: "low" },
    feeds: ["altruism", "family clarity"],
    description:
      "Studies of families asked about organ donation find that consent depends heavily on whether the family knew the person's wishes: donor families were far more likely to have discussed donation beforehand, and relatives who refused often framed the decision as protecting the body rather than giving a gift. Default rules matter at the population level — opt-out countries have higher registration and deceased-donation rates — but the family conversation still decides individual cases. Whole-body donation to medical schools is a separate decision with its own motives (usefulness, gratitude, avoiding funeral cost) and procedures. None of this is medical advice; it is a decision to make explicit while you are healthy.",
    action: "Today, record your organ-donation decision in your state registry and on your licence, then tell the two people most likely to be asked. If you are considering whole-body donation, request the program's written terms from a medical school this month and file them with your funeral plan.",
    sources: [
      { cite: "Siminoff, L. A., Gordon, N., Hewlett, J., & Arnold, R. M. (2001). Factors influencing families' consent for donation of solid organs for transplantation. JAMA, 286(1), 71–77.", note: "Families' consent to solid-organ donation was strongly associated with prior knowledge of the patient's wishes and with how the request was made.", link: doi("10.1001/jama.286.1.71"), kind: "doi" },
      { cite: "Rodrigue, J. R., Cornell, D. L., & Howard, R. J. (2006). Organ donation decision: Comparison of donor and nondonor families. American Journal of Transplantation, 6(1), 190–198.", note: "Comparison of donor and nondonor families: prior discussion of donation and knowledge of the deceased's preferences distinguished those who consented.", link: doi("10.1111/j.1600-6143.2005.01130.x"), kind: "doi" },
      { cite: "Sque, M., Long, T., Payne, S., & Allardyce, D. (2008). Why relatives do not donate organs for transplants: 'Sacrifice' or 'gift of life'?. Journal of Advanced Nursing, 61(2), 134–144.", note: "Relatives who declined donation described protecting the body and 'sacrifice' framings rather than the 'gift of life' framing used by professionals.", link: doi("10.1111/j.1365-2648.2007.04491.x"), kind: "doi" },
      { cite: "Johnson, E. J., & Goldstein, D. (2003). Do defaults save lives?. Science, 302(5649), 1338–1339.", note: "Countries with opt-out defaults had far higher organ-donation consent rates, demonstrating the power of defaults on registration.", link: doi("10.1126/science.1091721"), kind: "doi" },
      { cite: "Rithalia, A., McDaid, C., Suekarran, S., Myers, L., & Sowden, A. (2009). Impact of presumed consent for organ donation on donation rates: A systematic review. BMJ, 338, a3162.", note: "Systematic review: presumed-consent legislation was associated with higher donation rates, though other system factors also contribute.", link: doi("10.1136/bmj.a3162"), kind: "doi" },
      { cite: "Shepherd, L., O'Carroll, R. E., & Ferguson, E. (2014). An international comparison of deceased and living organ donation/transplant rates in opt-in and opt-out systems: A panel study. BMC Medicine, 12(1), 131.", note: "Panel study across countries: opt-out systems had higher deceased-donor rates but lower living-donor rates.", link: doi("10.1186/s12916-014-0131-4"), kind: "doi" },
      { cite: "Bolt, S., Venbrux, E., Eisinga, R., Kuks, J. B. M., Veening, J. G., & Gerrits, P. O. (2010). Motivation for body donation to science: More than an altruistic act. Annals of Anatomy, 192(2), 70–74.", note: "Body donors described motives beyond altruism, including gratitude to medicine, usefulness after death and practical considerations.", link: doi("10.1016/j.aanat.2010.02.002"), kind: "doi" },
      { cite: "Cornwall, J., Perry, G. F., Louw, G., & Stringer, M. D. (2012). Who donates their body to science? An international, multicenter, prospective study. Anatomical Sciences Education, 5(4), 208–216.", note: "International prospective study of who donates their body to science, characterising donors' demographics and motives.", link: doi("10.1002/ase.1278"), kind: "doi" },
    ],
  },
  {
    id: "gs-legacy-w2-planned-giving",
    goal: "legacy", tier: "advanced", section: "9256",
    title: "Make a Planned Gift Part of Your Estate — With an Advisor",
    subtitle: "Charitable estate plans track health and wealth; giving to others reliably raises well-being",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "months", durability: "lasting", effort: "moderate" },
    feeds: ["generativity", "meaning", "wellbeing"],
    description:
      "Longitudinal analysis of US older adults found that charitable estate plans rose with wealth and changed with health and family circumstances, and neuroimaging work suggests people process charitable bequest decisions as a form of visualised autobiography — imagining the story of their life. A review of the empirical literature identifies the mechanisms that drive giving (awareness of need, solicitation, costs and benefits, altruism, reputation, values, efficacy), and experimental and cross-cultural studies show that spending on others raises happiness. The boundary: the well-being evidence concerns giving while alive; a bequest's benefit to the giver is the meaning of planning it. This is not tax or legal advice — involve a qualified advisor.",
    action: "This quarter, meet an estate attorney or planned-giving officer and add one charitable component to your plan — a bequest, beneficiary designation or donor-advised fund — chosen to match a cause you have given to while alive. Write one paragraph for your family explaining why.",
    sources: [
      { cite: "James, R. N., III (2009). Health, wealth, and charitable estate planning: A longitudinal examination of testamentary charitable giving plans. Nonprofit and Voluntary Sector Quarterly, 38(6), 1026–1043.", note: "Longitudinal examination of testamentary charitable giving plans in older US adults: plans varied with wealth, health and family structure.", link: doi("10.1177/0899764008323860"), kind: "doi" },
      { cite: "James, R. N., III, & O'Boyle, M. W. (2014). Charitable estate planning as visualized autobiography: An fMRI study of its neural correlates. Nonprofit and Voluntary Sector Quarterly, 43(2), 355–373.", note: "fMRI study: contemplating charitable bequests engaged regions associated with autobiographical memory and visualisation, framing legacy giving as visualised autobiography.", link: doi("10.1177/0899764012463121"), kind: "doi" },
      { cite: "Bekkers, R., & Wiepking, P. (2011). A literature review of empirical studies of philanthropy: Eight mechanisms that drive charitable giving. Nonprofit and Voluntary Sector Quarterly, 40(5), 924–973.", note: "Review of empirical philanthropy research identifying eight mechanisms that drive charitable giving.", link: doi("10.1177/0899764010380927"), kind: "doi" },
      { cite: "Dunn, E. W., Aknin, L. B., & Norton, M. I. (2008). Spending money on others promotes happiness. Science, 319(5870), 1687–1688.", note: "Experimental and survey evidence that spending money on others promotes happiness more than spending on oneself.", link: doi("10.1126/science.1150952"), kind: "doi" },
      { cite: "Aknin, L. B., Barrington-Leigh, C. P., Dunn, E. W., Helliwell, J. F., Burns, J., Biswas-Diener, R., … Norton, M. I. (2013). Prosocial spending and well-being: Cross-cultural evidence for a psychological universal. Journal of Personality and Social Psychology, 104(4), 635–652.", note: "Cross-cultural evidence that prosocial spending is associated with well-being across rich and poor countries.", link: doi("10.1037/a0031578"), kind: "doi" },
    ],
  },
  {
    id: "gs-legacy-w2-named-endowment",
    goal: "legacy", tier: "elite", section: "9257",
    title: "Endow a Named Scholarship or Fund",
    subtitle: "A permanent, named gift turns a life story into an ongoing act — the evidence is about giving, not the name",
    evidenceTag: "Emerging",
    impact: { magnitude: 3, latency: "months", durability: "lasting", effort: "high" },
    feeds: ["generativity", "community ties", "meaning"],
    description:
      "A named scholarship or endowed fund is the rare legacy move that keeps acting after death, and it draws on the best-supported parts of the philanthropy literature: giving increases well-being, legacy giving is processed as a story of one's life, and typologies of legacy describe passing on values and resources as central to how older adults want to be remembered. What the research does not show is any specific benefit of naming; reputation and identity are among the documented mechanisms of giving, but no study has compared named with anonymous memorial gifts on the giver's or family's outcomes. The honest tag is emerging. The leverage is in scale and permanence, which is why it sits at the elite tier.",
    action: "Choose one institution you already have a relationship with, ask its development office for the minimum to endow a named fund and the written terms, and set a multi-year funding schedule you can meet without debt. Write the fund's purpose statement in your own words and file it with your estate plan.",
    sources: [
      { cite: "James, R. N., III, & O'Boyle, M. W. (2014). Charitable estate planning as visualized autobiography: An fMRI study of its neural correlates. Nonprofit and Voluntary Sector Quarterly, 43(2), 355–373.", note: "Charitable estate planning engaged autobiographical-memory regions, supporting the idea that legacy gifts are experienced as a story of one's life.", link: doi("10.1177/0899764012463121"), kind: "doi" },
      { cite: "Bekkers, R., & Wiepking, P. (2011). A literature review of empirical studies of philanthropy: Eight mechanisms that drive charitable giving. Nonprofit and Voluntary Sector Quarterly, 40(5), 924–973.", note: "Review identifying reputation, values and psychological benefits among the mechanisms that drive charitable giving.", link: doi("10.1177/0899764010380927"), kind: "doi" },
      { cite: "James, R. N., III (2009). Health, wealth, and charitable estate planning: A longitudinal examination of testamentary charitable giving plans. Nonprofit and Voluntary Sector Quarterly, 38(6), 1026–1043.", note: "Charitable estate plans in older adults tracked wealth and health, a reminder to size a permanent gift to actual means.", link: doi("10.1177/0899764008323860"), kind: "doi" },
      { cite: "Dunn, E. W., Aknin, L. B., & Norton, M. I. (2008). Spending money on others promotes happiness. Science, 319(5870), 1687–1688.", note: "Giving to others raised happiness in experimental tests, the well-being basis for giving while alive.", link: doi("10.1126/science.1150952"), kind: "doi" },
      { cite: "Aknin, L. B., Barrington-Leigh, C. P., Dunn, E. W., Helliwell, J. F., Burns, J., Biswas-Diener, R., … Norton, M. I. (2013). Prosocial spending and well-being: Cross-cultural evidence for a psychological universal. Journal of Personality and Social Psychology, 104(4), 635–652.", note: "Prosocial spending was associated with well-being across cultures, suggesting a broadly human benefit of giving.", link: doi("10.1037/a0031578"), kind: "doi" },
      { cite: "Hunter, E. G., & Rowles, G. D. (2005). Leaving a legacy: Toward a typology. Journal of Aging Studies, 19(3), 327–347.", note: "A typology of how older adults think about leaving a legacy — biological, material and values legacies — with named gifts an example of the material-values form.", link: doi("10.1016/j.jaging.2004.08.002"), kind: "doi" },
    ],
  },
  {
    id: "gs-legacy-w2-experience-corps",
    goal: "legacy", tier: "elite", section: "9258",
    title: "Join an Experience Corps-Style Program — Fifteen Hours a Week in a School",
    subtitle: "The intergenerational trial that improved generativity, activity, cognition and brain volume in older adults",
    evidenceTag: "Strong",
    impact: { magnitude: 5, latency: "months", durability: "lasting", effort: "high" },
    feeds: ["generativity", "cognition", "physical activity", "children's outcomes"],
    description:
      "Experience Corps places older adults in public elementary schools for roughly fifteen hours a week as tutors and mentors, designed as a health-promotion program in the guise of service. Pilot and randomized trials in Baltimore found increases in physical activity and lifestyle activity, gains in executive function and memory, evidence of neurocognitive plasticity in at-risk older adults, and in the full trial increases in generativity — the felt sense of contributing to the next generation — and protection of cortical and hippocampal volume. The commitment is large and the program must be joined where it exists (or reproduced with a school partner), which is why it is the elite move on this shelf.",
    action: "Apply to an Experience Corps (AmeriCorps Seniors) or equivalent school-based program this year, committing to a school year at fifteen hours a week. If none exists locally, propose the same structure to one elementary school with two other volunteers.",
    sources: [
      { cite: "Fried, L. P., Carlson, M. C., Freedman, M., Frick, K. D., Glass, T. A., Hill, J., … Zeger, S. (2004). A social model for health promotion for an aging population: Initial evidence on the Experience Corps model. Journal of Urban Health, 81(1), 64–78.", note: "Initial evidence for the Experience Corps model as a social model of health promotion for an aging population.", link: doi("10.1093/jurban/jth094"), kind: "doi" },
      { cite: "Glass, T. A., Freedman, M., Carlson, M. C., Hill, J., Frick, K. D., Ialongo, N., … Fried, L. P. (2004). Experience Corps: Design of an intergenerational program to boost social capital and promote the health of an aging society. Journal of Urban Health, 81(1), 94–105.", note: "Design of the Experience Corps program: intergenerational tutoring intended to boost social capital and promote older adults' health.", link: doi("10.1093/jurban/jth096"), kind: "doi" },
      { cite: "Tan, E. J., Xue, Q.-L., Li, T., Carlson, M. C., & Fried, L. P. (2006). Volunteering: A physical activity intervention for older adults—The Experience Corps program in Baltimore. Journal of Urban Health, 83(5), 954–969.", note: "Experience Corps participation functioned as a physical-activity intervention for older adults in Baltimore.", link: doi("10.1007/s11524-006-9060-7"), kind: "doi" },
      { cite: "Carlson, M. C., Saczynski, J. S., Rebok, G. W., Seeman, T., Glass, T. A., McGill, S., Tielsch, J., Frick, K. D., Hill, J., & Fried, L. P. (2008). Exploring the effects of an \"everyday\" activity program on executive function and memory in older adults: Experience Corps. The Gerontologist, 48(6), 793–801.", note: "Exploratory trial: participation in the 'everyday activity' program improved executive function and memory in older adults.", link: doi("10.1093/geront/48.6.793"), kind: "doi" },
      { cite: "Carlson, M. C., Erickson, K. I., Kramer, A. F., Voss, M. W., Bolea, N., Mielke, M., … Fried, L. P. (2009). Evidence for neurocognitive plasticity in at-risk older adults: The Experience Corps program. The Journals of Gerontology Series A: Biological Sciences and Medical Sciences, 64A(12), 1275–1282.", note: "Evidence for neurocognitive plasticity in at-risk older adults after Experience Corps participation.", link: doi("10.1093/gerona/glp117"), kind: "doi" },
      { cite: "Fried, L. P., Carlson, M. C., McGill, S., Seeman, T., Xue, Q.-L., Frick, K., … Rebok, G. W. (2013). Experience Corps: A dual trial to promote the health of older adults and children's academic success. Contemporary Clinical Trials, 36(1), 1–13.", note: "Design of the Baltimore Experience Corps dual trial to promote older adults' health and children's academic success.", link: doi("10.1016/j.cct.2013.05.003"), kind: "doi" },
      { cite: "Gruenewald, T. L., Tanner, E. K., Fried, L. P., Carlson, M. C., Xue, Q.-L., Parisi, J. M., Rebok, G. W., Yarnell, L. M., & Seeman, T. E. (2016). The Baltimore Experience Corps Trial: Enhancing generativity via intergenerational activity engagement in later life. The Journals of Gerontology Series B: Psychological Sciences and Social Sciences, 71(4), 661–670.", note: "The Baltimore Experience Corps Trial increased generativity through intergenerational activity engagement in later life.", link: doi("10.1093/geronb/gbv005"), kind: "doi" },
      { cite: "Carlson, M. C., Kuo, J. H., Chuang, Y.-F., Varma, V. R., Harris, G., Albert, M. S., … Fried, L. P. (2015). Impact of the Baltimore Experience Corps Trial on cortical and hippocampal volumes. Alzheimer's & Dementia, 11(11), 1340–1348.", note: "Trial participants showed protection of cortical and hippocampal volumes relative to controls.", link: doi("10.1016/j.jalz.2014.12.005"), kind: "doi" },
    ],
  },
  {
    id: "gs-legacy-w2-volunteer-mentor",
    goal: "legacy", tier: "moderate", section: "9258",
    title: "Volunteer on a Schedule and Mentor One Young Person",
    subtitle: "Volunteering by older adults is linked to lower mortality; structured youth mentoring has modest, real effects",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "months", durability: "lasting", effort: "moderate" },
    feeds: ["generativity", "health", "social ties"],
    description:
      "Meta-analyses find that older adults who volunteer have lower mortality risk and better health and well-being, with a critical review cautioning that most evidence is observational and that the benefit appears at moderate, regular doses. Experience Corps data show volunteering raised lifestyle activity across domains. On the receiving end, a systematic assessment of youth mentoring programs found modest positive effects that grow with program quality and relationship duration, and a multidisciplinary meta-analysis found mentored individuals fared better on a range of outcomes. The generative legacy here is a person, and the protocol is regularity rather than intensity.",
    action: "Commit to two hours a week of volunteering for six months in one organisation, and within it (or through a structured mentoring program) take on one young person for at least a year of regular meetings.",
    sources: [
      { cite: "Okun, M. A., Yeung, E. W., & Brown, S. (2013). Volunteering by older adults and risk of mortality: A meta-analysis. Psychology and Aging, 28(2), 564–577.", note: "Meta-analysis: volunteering by older adults was associated with reduced mortality risk.", link: doi("10.1037/a0031519"), kind: "doi" },
      { cite: "Jenkinson, C. E., Dickens, A. P., Jones, K., Thompson-Coon, J., Taylor, R. S., Rogers, M., Bambra, C. L., Lang, I., & Richards, S. H. (2013). Is volunteering a public health intervention? A systematic review and meta-analysis of the health and survival of volunteers. BMC Public Health, 13(1), 773.", note: "Systematic review and meta-analysis: volunteering was associated with lower mortality and better well-being, with observational designs limiting causal claims.", link: doi("10.1186/1471-2458-13-773"), kind: "doi" },
      { cite: "Anderson, N. D., Damianakis, T., Kröger, E., Wagner, L. M., Dawson, D. R., Binns, M. A., … Robinson, B. (2014). The benefits associated with volunteering among seniors: A critical review and recommendations for future research. Psychological Bulletin, 140(6), 1505–1533.", note: "Critical review of the benefits of volunteering among seniors, with recommendations for stronger designs and attention to dose.", link: doi("10.1037/a0037610"), kind: "doi" },
      { cite: "Parisi, J. M., Kuo, J., Rebok, G. W., Xue, Q.-L., Fried, L. P., Gruenewald, T. L., … Carlson, M. C. (2015). Increases in lifestyle activities as a result of Experience Corps participation. Journal of Urban Health, 92(1), 55–66.", note: "Experience Corps participation increased lifestyle activities across intellectual, social and physical domains.", link: doi("10.1007/s11524-014-9918-z"), kind: "doi" },
      { cite: "DuBois, D. L., Portillo, N., Rhodes, J. E., Silverthorn, N., & Valentine, J. C. (2011). How effective are mentoring programs for youth? A systematic assessment of the evidence. Psychological Science in the Public Interest, 12(2), 57–91.", note: "Systematic assessment of youth mentoring programs: modest positive effects on youth outcomes, larger with quality practices and longer relationships.", link: doi("10.1177/1529100611414806"), kind: "doi" },
      { cite: "Eby, L. T., Allen, T. D., Evans, S. C., Ng, T., & DuBois, D. L. (2008). Does mentoring matter? A multidisciplinary meta-analysis comparing mentored and non-mentored individuals. Journal of Vocational Behavior, 72(2), 254–267.", note: "Multidisciplinary meta-analysis: mentored individuals showed better behavioural, attitudinal and career outcomes than non-mentored peers, with small effects.", link: doi("10.1016/j.jvb.2007.04.005"), kind: "doi" },
    ],
  },
  {
    id: "gs-legacy-w2-meaning-centered",
    goal: "legacy", tier: "advanced", section: "9259",
    title: "Meaning-Centered Psychotherapy or Dignity Therapy When Illness Is Serious",
    subtitle: "Randomized trials in advanced cancer improved meaning, spiritual well-being and end-of-life experience",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "weeks", durability: "lasting", effort: "moderate" },
    feeds: ["meaning", "dignity", "legacy document"],
    description:
      "Two structured therapies turn legacy into a clinical intervention. Meaning-centered psychotherapy, in group and individual formats, improved spiritual well-being, sense of meaning and quality of life and reduced despair in randomized trials with advanced-cancer patients. Dignity therapy, a brief guided interview that produces a written legacy document for the family, was rated as helpful by patients and, in a multisite randomized trial, improved aspects of end-of-life experience though not distress on the primary measures. A legacy-activities pilot and a later randomized trial with senior volunteers suggest simpler versions can be delivered outside oncology. These are offered by trained clinicians; the protocol is to ask for them by name.",
    action: "If you or a family member has a serious illness, ask the palliative or oncology team specifically for meaning-centered psychotherapy or dignity therapy and, if offered, complete the legacy document and give copies to the family.",
    sources: [
      { cite: "Breitbart, W., Rosenfeld, B., Gibson, C., Pessin, H., Poppito, S., Nelson, C., … Olden, M. (2010). Meaning-centered group psychotherapy for patients with advanced cancer: A pilot randomized controlled trial. Psycho-Oncology, 19(1), 21–28.", note: "Pilot randomized trial of meaning-centered group psychotherapy in advanced cancer: gains in spiritual well-being and sense of meaning.", link: doi("10.1002/pon.1556"), kind: "doi" },
      { cite: "Breitbart, W., Poppito, S., Rosenfeld, B., Vickers, A. J., Li, Y., Abbey, J., … Cassileth, B. R. (2012). Pilot randomized controlled trial of individual meaning-centered psychotherapy for patients with advanced cancer. Journal of Clinical Oncology, 30(12), 1304–1309.", note: "Pilot randomized trial of individual meaning-centered psychotherapy: improvements in spiritual well-being and quality of life.", link: doi("10.1200/jco.2011.36.2517"), kind: "doi" },
      { cite: "Breitbart, W., Rosenfeld, B., Pessin, H., Applebaum, A., Kulikowski, J., & Lichtenthal, W. G. (2015). Meaning-centered group psychotherapy: An effective intervention for improving psychological well-being in patients with advanced cancer. Journal of Clinical Oncology, 33(7), 749–754.", note: "Randomized trial: meaning-centered group psychotherapy improved psychological well-being in patients with advanced cancer.", link: doi("10.1200/jco.2014.57.2198"), kind: "doi" },
      { cite: "Breitbart, W., Pessin, H., Rosenfeld, B., Applebaum, A. J., Lichtenthal, W. G., Li, Y., … Fenn, N. (2018). Individual meaning-centered psychotherapy for the treatment of psychological and existential distress: A randomized controlled trial in patients with advanced cancer. Cancer, 124(15), 3231–3239.", note: "Randomized trial of individual meaning-centered psychotherapy for psychological and existential distress in advanced cancer.", link: doi("10.1002/cncr.31539"), kind: "doi" },
      { cite: "Chochinov, H. M., Hack, T., Hassard, T., Kristjanson, L. J., McClement, S., & Harlos, M. (2005). Dignity therapy: A novel psychotherapeutic intervention for patients near the end of life. Journal of Clinical Oncology, 23(24), 5520–5525.", note: "Dignity therapy introduced: a brief intervention producing a legacy document, rated as helpful by patients near the end of life.", link: doi("10.1200/jco.2005.08.391"), kind: "doi" },
      { cite: "Chochinov, H. M., Kristjanson, L. J., Breitbart, W., McClement, S., Hack, T. F., Hassard, T., & Harlos, M. (2011). Effect of dignity therapy on distress and end-of-life experience in terminally ill patients: A randomised controlled trial. The Lancet Oncology, 12(8), 753–762.", note: "Multisite randomised trial of dignity therapy: improved end-of-life experience on several measures, without a difference in distress on primary outcomes.", link: doi("10.1016/s1470-2045(11)70153-x"), kind: "doi" },
      { cite: "Allen, R. S., Hilgeman, M. M., Ege, M. A., Shuster, J. L., Jr., & Burgio, L. D. (2008). Legacy activities as interventions approaching the end of life. Journal of Palliative Medicine, 11(7), 1029–1038.", note: "Pilot of legacy activities as interventions approaching the end of life, delivered to patient–caregiver dyads.", link: doi("10.1089/jpm.2007.0294"), kind: "doi" },
      { cite: "Allen, R. S., Harris, G. M., Burgio, L. D., Azuero, C. B., Miller, L. A., Shin, H. J., … Parmelee, P. (2014). Can senior volunteers deliver reminiscence and creative activity interventions? Results of the Legacy Intervention Family Enactment randomized controlled trial. Journal of Pain and Symptom Management, 48(4), 590–601.", note: "Randomized trial: trained senior volunteers could deliver reminiscence and creative legacy-activity interventions to families.", link: doi("10.1016/j.jpainsymman.2013.11.012"), kind: "doi" },
    ],
  },
  {
    id: "gs-legacy-w2-wisdom-practice",
    goal: "legacy", tier: "moderate", section: "9260",
    title: "Practise Wise Reasoning by Reasoning From a Distance",
    subtitle: "Wisdom is measurable, grows with age in social reasoning, and improves when you step outside your own view",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "low" },
    feeds: ["perspective", "conflict resolution", "what you pass on"],
    description:
      "Wisdom research offers two validated self-report scales and a performance measure of wise reasoning about social conflicts — recognising limits of knowledge, others' perspectives, the possibility of change and compromise. Reasoning about social conflicts improved into old age in a large sample, and experiments show that people reason more wisely about others' problems than their own, an asymmetry eliminated by self-distancing: taking a third-person view of one's own conflict raised wise reasoning, attitudes and behaviour. The 'metaheuristic' account frames wisdom as orchestrating knowledge and virtue toward the good life, which is what a person hoping to leave a legacy is trying to model. The practice is a written reasoning exercise, not a personality change.",
    action: "Once a week for eight weeks, write about one current conflict or decision in the third person ('she is worried that…'), listing what you do not know, the other party's view, how it might change and where compromise lies. Apply the same frame when giving advice to family.",
    sources: [
      { cite: "Ardelt, M. (2003). Empirical assessment of a three-dimensional wisdom scale. Research on Aging, 25(3), 275–324.", note: "Empirical assessment of a three-dimensional (cognitive, reflective, affective) wisdom scale in older adults.", link: doi("10.1177/0164027503025003004"), kind: "doi" },
      { cite: "Ardelt, M. (2004). Wisdom as expert knowledge system: A critical review of a contemporary operationalization of an ancient concept. Human Development, 47(5), 257–285.", note: "Critical review of the expert-knowledge operationalisation of wisdom and the case for a personality-based view.", link: doi("10.1159/000079154"), kind: "doi" },
      { cite: "Baltes, P. B., & Staudinger, U. M. (2000). Wisdom: A metaheuristic (pragmatic) to orchestrate mind and virtue toward excellence. American Psychologist, 55(1), 122–136.", note: "Wisdom as a metaheuristic orchestrating mind and virtue toward excellence, and the Berlin paradigm for measuring it.", link: doi("10.1037/0003-066x.55.1.122"), kind: "doi" },
      { cite: "Grossmann, I., Na, J., Varnum, M. E. W., Park, D. C., Kitayama, S., & Nisbett, R. E. (2010). Reasoning about social conflicts improves into old age. Proceedings of the National Academy of Sciences, 107(16), 7246–7250.", note: "Wise reasoning about social conflicts improved into old age, independent of intelligence.", link: doi("10.1073/pnas.1001715107"), kind: "doi" },
      { cite: "Grossmann, I., & Kross, E. (2014). Exploring Solomon's paradox: Self-distancing eliminates the self-other asymmetry in wise reasoning about close relationships in younger and older adults. Psychological Science, 25(8), 1571–1580.", note: "Solomon's paradox: people reasoned more wisely about others' relationship conflicts than their own, and self-distancing eliminated the asymmetry.", link: doi("10.1177/0956797614535400"), kind: "doi" },
      { cite: "Kross, E., & Grossmann, I. (2012). Boosting wisdom: Distance from the self enhances wise reasoning, attitudes, and behavior. Journal of Experimental Psychology: General, 141(1), 43–48.", note: "Distance from the self (a third-person perspective) enhanced wise reasoning, attitudes and behaviour in experiments.", link: doi("10.1037/a0024158"), kind: "doi" },
      { cite: "Grossmann, I. (2017). Wisdom in context. Perspectives on Psychological Science, 12(2), 233–257.", note: "Wisdom in context: wise reasoning varies across situations and can be fostered by the situation and by perspective-taking.", link: doi("10.1177/1745691616672066"), kind: "doi" },
      { cite: "Webster, J. D. (2003). An exploratory analysis of a self-assessed wisdom scale. Journal of Adult Development, 10(1), 13–22.", note: "Exploratory analysis of a self-assessed wisdom scale covering experience, emotion regulation, reminiscence, openness and humour.", link: doi("10.1023/a:1020782619051"), kind: "doi" },
    ],
  },
  {
    id: "gs-legacy-w2-dementia-life-story",
    goal: "legacy", tier: "moderate", section: "9261",
    title: "Make a Life-Story Book With a Person Living With Dementia",
    subtitle: "Individual life-story work improved mood and quality of life and helped staff see the person",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "moderate" },
    feeds: ["personhood", "family connection", "care quality"],
    description:
      "A Cochrane review of reminiscence therapy for dementia found some evidence of benefit for quality of life, cognition, communication and mood, varying by format and setting, with individual approaches showing effects on mood. A randomised trial found that people with mild-to-moderate dementia who created a life-story book through structured life review improved in quality of life and autobiographical memory, and a systematic review of individual reminiscence therapy supported its use; qualitative work found life-story books helped care staff and relatives see the person and deliver more person-centred care. A feasibility study mapped how life-story work is used in practice. The protocol is a family project done with, not for, the person.",
    action: "Over eight weekly sessions, build a life-story book with the person: one chapter a week (childhood, family, work, places, achievements, likes), using their photographs and their words, and leave it with their care team with a one-page 'about me' summary.",
    sources: [
      { cite: "Woods, B., O'Philbin, L., Farrell, E. M., Spector, A. E., & Orrell, M. (2018). Reminiscence therapy for dementia. Cochrane Database of Systematic Reviews, 2018(3).", note: "Cochrane review of reminiscence therapy for dementia: benefits for quality of life, cognition, communication and mood varied by format and setting.", link: doi("10.1002/14651858.cd001120.pub3"), kind: "doi" },
      { cite: "Subramaniam, P., Woods, B., & Whitaker, C. (2014). Life review and life story books for people with mild to moderate dementia: A randomised controlled trial. Aging & Mental Health, 18(3), 363–375.", note: "Randomised controlled trial: life review producing a life-story book improved quality of life and autobiographical memory in mild-to-moderate dementia.", link: doi("10.1080/13607863.2013.837144"), kind: "doi" },
      { cite: "Subramaniam, P., & Woods, B. (2012). The impact of individual reminiscence therapy for people with dementia: Systematic review. Expert Review of Neurotherapeutics, 12(5), 545–555.", note: "Systematic review of individual reminiscence therapy for people with dementia, supporting benefits for mood and cognition.", link: doi("10.1586/ern.12.35"), kind: "doi" },
      { cite: "McKeown, J., Clarke, A., Ingleton, C., Ryan, T., & Repper, J. (2010). The use of life story work with people with dementia to enhance person-centred care. International Journal of Older People Nursing, 5(2), 148–158.", note: "Life-story work helped care staff and relatives see the person behind the dementia and supported person-centred care.", link: doi("10.1111/j.1748-3743.2010.00219.x"), kind: "doi" },
      { cite: "Gridley, K., Brooks, J., Birks, Y., Baxter, K., & Parker, G. (2016). Improving care for people with dementia: Development and initial feasibility study for evaluation of life story work in dementia care. Health Services and Delivery Research, 4(23), 1–298.", note: "Development and feasibility study for evaluating life-story work in dementia care, mapping good practice and outcome measures.", link: doi("10.3310/hsdr04230"), kind: "doi" },
    ],
  },
  {
    id: "gs-legacy-w2-future-self-letters",
    goal: "legacy", tier: "fundamental", section: "9262",
    title: "Write to Your Future Self, Reply as Your Future Self, and Seal a Capsule",
    subtitle: "A letter exchange with the future self raised self-continuity and planning; rediscovery is undervalued",
    evidenceTag: "Moderate",
    impact: { magnitude: 2, latency: "weeks", durability: "sustained", effort: "low" },
    feeds: ["future self-continuity", "planning", "savouring"],
    description:
      "In a controlled study, students who wrote a letter to their future self and then wrote the reply as that future self showed higher self-continuity, more career planning and better academic outcomes, and a pandemic-era version of the exercise reduced negative affect. Future self-continuity — feeling connected to the person you will become — is associated with saving, exercise and health, and can be raised by vivid representations of the future self. Time capsules draw on a different finding: people underestimate how much they will enjoy rediscovering ordinary records of the present, so they fail to make them. Both are cheap, and both make the legacy you are building concrete to the person who has to build it.",
    action: "Tonight, write a one-page letter to yourself ten years from now, then write the reply in that future self's voice. Put both, plus five ordinary artefacts of this month, in a sealed capsule with an opening date one year out, and repeat annually.",
    sources: [
      { cite: "Chishima, Y., & Wilson, A. E. (2021). Conversation with a future self: A letter-exchange exercise enhances student self-continuity, career planning, and academic thinking. Self and Identity, 20(5), 646–671.", note: "A letter-exchange exercise with the future self enhanced students' self-continuity, career planning and academic thinking.", link: doi("10.1080/15298868.2020.1754283"), kind: "doi" },
      { cite: "Chishima, Y., Huai-Ching Liu, I.-T., & Wilson, A. E. (2021). Temporal distancing during the COVID-19 pandemic: Letter writing with future self can mitigate negative affect. Applied Psychology: Health and Well-Being, 13(2), 406–418.", note: "Letter writing to a future self during the pandemic mitigated negative affect through temporal distancing.", link: doi("10.1111/aphw.12256"), kind: "doi" },
      { cite: "Hershfield, H. E., Goldstein, D. G., Sharpe, W. F., Fox, J., Yeykelis, L., Carstensen, L. L., & Bailenson, J. N. (2011). Increasing saving behavior through age-progressed renderings of the future self. Journal of Marketing Research, 48(SPL), S23–S37.", note: "Age-progressed renderings of the future self increased saving behaviour in experiments.", link: doi("10.1509/jmkr.48.spl.s23"), kind: "doi" },
      { cite: "Rutchick, A. M., Slepian, M. L., Reyes, M. O., Pleskus, L. N., & Hershfield, H. E. (2018). Future self-continuity is associated with improved health and increases exercise behavior. Journal of Experimental Psychology: Applied, 24(1), 72–80.", note: "Future self-continuity was associated with better health and, when raised, increased exercise behaviour.", link: doi("10.1037/xap0000153"), kind: "doi" },
      { cite: "Ersner-Hershfield, H., Wimmer, G. E., & Knutson, B. (2009). Saving for the future self: Neural measures of future self-continuity predict temporal discounting. Social Cognitive and Affective Neuroscience, 4(1), 85–92.", note: "Neural measures of future self-continuity predicted temporal discounting, linking connection to the future self with patience for it.", link: doi("10.1093/scan/nsn042"), kind: "doi" },
      { cite: "Zhang, T., Kim, T., Brooks, A. W., Gino, F., & Norton, M. I. (2014). A \"present\" for the future: The unexpected value of rediscovery. Psychological Science, 25(10), 1851–1860.", note: "People underestimated the value of rediscovering ordinary present-day experiences in the future and so underinvested in creating time capsules.", link: doi("10.1177/0956797614542274"), kind: "doi" },
      { cite: "Kumar, A., Killingsworth, M. A., & Gilovich, T. (2014). Waiting for Merlot: Anticipatory consumption of experiential and material purchases. Psychological Science, 25(10), 1924–1931.", note: "Anticipating experiences produced more excitement than anticipating material purchases — the anticipatory side of a dated capsule.", link: doi("10.1177/0956797614546556"), kind: "doi" },
    ],
  },
  {
    id: "gs-legacy-w2-generativity-growth",
    goal: "legacy", tier: "moderate", section: "9263",
    title: "Turn Loss Into Generativity — Carefully",
    subtitle: "Generativity tracks well-being; self-reported growth after trauma may not reflect real change",
    evidenceTag: "Mixed",
    impact: { magnitude: 3, latency: "months", durability: "lasting", effort: "moderate" },
    feeds: ["generativity", "meaning", "resilience"],
    description:
      "Generativity — caring for and contributing to the next generation — is measurable through self-report, acts and narrative themes, and midlife adults higher in generativity report better psychosocial adaptation; in older age it is part of what successful ageing means. Posttraumatic growth is the popular idea that loss produces growth, and meta-analysis links reported benefit-finding to less depression and more well-being. The honest boundary is a prospective study that found self-reported growth after trauma did not track actual change in the same domains, and a conceptual review that treats growth as possible rather than expected. The protocol builds generativity through action and lets any 'growth' be a by-product rather than a demand.",
    action: "After a loss, wait until the acute grief has eased, then choose one generative act tied to the person — a scholarship, a mentoring role, a family project — and pursue it for six months. Do not require yourself to feel grown; measure what you did.",
    sources: [
      { cite: "McAdams, D. P., & de St. Aubin, E. (1992). A theory of generativity and its assessment through self-report, behavioral acts, and narrative themes in autobiography. Journal of Personality and Social Psychology, 62(6), 1003–1015.", note: "Generativity assessed through self-report, behavioural acts and narrative themes in autobiography, and its links to well-being.", link: doi("10.1037/0022-3514.62.6.1003"), kind: "doi" },
      { cite: "Cox, K. S., Wilt, J., Olson, B., & McAdams, D. P. (2010). Generativity, the Big Five, and psychosocial adaptation in midlife adults. Journal of Personality, 78(4), 1185–1208.", note: "Generativity related to psychosocial adaptation in midlife adults over and above the Big Five traits.", link: doi("10.1111/j.1467-6494.2010.00647.x"), kind: "doi" },
      { cite: "Villar, F. (2012). Successful ageing and development: The contribution of generativity in older age. Ageing and Society, 32(7), 1087–1105.", note: "Generativity as a contributor to successful ageing and development in older age.", link: doi("10.1017/s0144686x11000973"), kind: "doi" },
      { cite: "Hunter, E. G., & Rowles, G. D. (2005). Leaving a legacy: Toward a typology. Journal of Aging Studies, 19(3), 327–347.", note: "A typology of legacy in older adults — biological, material and values legacies — and the motives behind leaving one.", link: doi("10.1016/j.jaging.2004.08.002"), kind: "doi" },
      { cite: "Tedeschi, R. G., & Calhoun, L. G. (1996). The Posttraumatic Growth Inventory: Measuring the positive legacy of trauma. Journal of Traumatic Stress, 9(3), 455–471.", note: "The Posttraumatic Growth Inventory, measuring the positive legacy of trauma across domains such as relating to others and appreciation of life.", link: doi("10.1002/jts.2490090305"), kind: "doi" },
      { cite: "Tedeschi, R. G., & Calhoun, L. G. (2004). Posttraumatic growth: Conceptual foundations and empirical evidence. Psychological Inquiry, 15(1), 1–18.", note: "Conceptual foundations of posttraumatic growth: growth as a possible outcome of struggling with adversity, not an automatic one.", link: doi("10.1207/s15327965pli1501_01"), kind: "doi" },
      { cite: "Helgeson, V. S., Reynolds, K. A., & Tomich, P. L. (2006). A meta-analytic review of benefit finding and growth. Journal of Consulting and Clinical Psychology, 74(5), 797–816.", note: "Meta-analytic review: benefit finding was associated with less depression and more positive well-being, with effects varying by measure and time since event.", link: doi("10.1037/0022-006x.74.5.797"), kind: "doi" },
      { cite: "Frazier, P., Tennen, H., Gavian, M., Park, C., Tomich, P., & Tashiro, T. (2009). Does self-reported posttraumatic growth reflect genuine positive change?. Psychological Science, 20(7), 912–919.", note: "Prospective study: self-reported posttraumatic growth did not correspond to measured change in the same domains, cautioning against taking growth reports at face value.", link: doi("10.1111/j.1467-9280.2009.02381.x"), kind: "doi" },
    ],
  },
  {
    id: "gs-legacy-w2-continuing-bonds",
    goal: "legacy", tier: "fundamental", section: "9264",
    title: "Keep a Healthy Continuing Bond, and Use Ritual to Grieve",
    subtitle: "Ongoing connection to the dead can help or hinder; performed rituals reduce grief experimentally",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "weeks", durability: "lasting", effort: "low" },
    feeds: ["grief regulation", "family memory", "meaning"],
    description:
      "Bereavement research moved from 'letting go' to continuing bonds, but the evidence is conditional: attachment-based and integrative reviews find that bonds that are internalised (carrying the person's values, remembering) support adjustment, while bonds that seek to hold on to the person as if present can prolong grief, and the dual-process model shows healthy grieving oscillates between loss and restoration. Meaning reconstruction moderates whether a bond helps. Experiments found that performing rituals after loss reduced grief, even for people who did not believe rituals work, and funeral research finds rituals experienced as meaningful facilitate grief. The fundamental protocol is a small, repeated, personally meaningful ritual paired with an internalised bond.",
    action: "Choose one repeatable ritual for the person you lost — a weekly walk to a place, a monthly meal cooked their way, an annual letter — and do it for a year. Pair it with one internalised bond: a value or habit of theirs you practise, rather than an attempt to keep them present.",
    sources: [
      { cite: "Field, N. P., Gao, B., & Paderna, L. (2005). Continuing bonds in bereavement: An attachment theory based perspective. Death Studies, 29(4), 277–299.", note: "Attachment-based perspective on continuing bonds: internalised bonds support adjustment, while externalised, proximity-seeking bonds are associated with worse grief.", link: doi("10.1080/07481180590923689"), kind: "doi" },
      { cite: "Stroebe, M., Schut, H., & Boerner, K. (2010). Continuing bonds in adaptation to bereavement: Toward theoretical integration. Clinical Psychology Review, 30(2), 259–268.", note: "Integrative review: whether continuing bonds help depends on the type of bond, the circumstances of the loss and the bereaved person's attachment.", link: doi("10.1016/j.cpr.2009.11.007"), kind: "doi" },
      { cite: "Stroebe, M., & Schut, H. (1999). The dual process model of coping with bereavement: Rationale and description. Death Studies, 23(3), 197–224.", note: "The dual process model: adaptive grieving oscillates between loss-oriented and restoration-oriented coping.", link: doi("10.1080/074811899201046"), kind: "doi" },
      { cite: "Neimeyer, R. A., Baldwin, S. A., & Gillies, J. (2006). Continuing bonds and reconstructing meaning: Mitigating complications in bereavement. Death Studies, 30(8), 715–738.", note: "Continuing bonds interacted with sense-making: bonds were associated with less complicated grief when the loss could be given meaning.", link: doi("10.1080/07481180600848322"), kind: "doi" },
      { cite: "Root, B. L., & Exline, J. J. (2014). The role of continuing bonds in coping with grief: Overview and future directions. Death Studies, 38(1), 1–8.", note: "Overview of the role of continuing bonds in coping with grief, with directions for distinguishing helpful and unhelpful forms.", link: doi("10.1080/07481187.2012.712608"), kind: "doi" },
      { cite: "Norton, M. I., & Gino, F. (2014). Rituals alleviate grieving for loved ones, lovers, and lotteries. Journal of Experimental Psychology: General, 143(1), 266–272.", note: "Experiments: performing rituals after loss reduced grief, with effects present even among people who did not believe in rituals' efficacy.", link: doi("10.1037/a0031772"), kind: "doi" },
      { cite: "Mitima-Verloop, H. B., Mooren, T. T. M., & Boelen, P. A. (2021). Facilitating grief: An exploration of the function of funerals and rituals in relation to grief reactions. Death Studies, 45(9), 735–745.", note: "Funerals and rituals perceived as helpful were associated with grief facilitation.", link: doi("10.1080/07481187.2019.1686090"), kind: "doi" },
    ],
  },
  {
    id: "gs-legacy-w2-digital-afterlife",
    goal: "legacy", tier: "moderate", section: "9265",
    title: "Appoint a Digital Executor and Set Every Account's Afterlife",
    subtitle: "The dead are accumulating online; survivors need access, decisions and a steward",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "weeks", durability: "lasting", effort: "low" },
    feeds: ["family burden reduction", "privacy", "memorial control"],
    description:
      "Big-data projections suggest the profiles of the dead will come to rival the living on major platforms, and studies of Facebook after a death show profiles become sites of mourning and continuing bonds that survivors did not design and cannot always control. Interviews with the bereaved document the practical problems — locked accounts, unwanted reminders, lost photographs — and design work on 'legacy contact' shows that a designated steward with defined powers reduces conflict. People express a posthumous privacy paradox, wanting control over their digital remains but doing nothing about it, and hold divided views on posthumous communication technologies. The protocol is an inventory, a decision per account and a named steward.",
    action: "This month, list every account and device with a login, decide for each whether it should be memorialised, transferred or deleted, set the platform's legacy-contact or inactive-account option where it exists, and name one digital executor in writing with the password-manager access they will need.",
    sources: [
      { cite: "Öhman, C. J., & Watson, D. (2019). Are the dead taking over Facebook? A Big Data approach to the future of death online. Big Data & Society, 6(1).", note: "Big-data projections of deceased users on Facebook, raising questions about stewardship of digital remains at population scale.", link: doi("10.1177/2053951719842540"), kind: "doi" },
      { cite: "Brubaker, J. R., Hayes, G. R., & Dourish, P. (2013). Beyond the grave: Facebook as a site for the expansion of death and mourning. The Information Society, 29(3), 152–163.", note: "Facebook profiles of the dead became sites for the expansion of death and mourning, with implications for survivors and platforms.", link: doi("10.1080/01972243.2013.777300"), kind: "doi" },
      { cite: "Brubaker, J. R., & Callison-Burch, V. (2016). Legacy Contact: Designing and implementing post-mortem stewardship at Facebook. Proceedings of the 2016 CHI Conference on Human Factors in Computing Systems, 2908–2919.", note: "Design and implementation of Facebook's Legacy Contact feature for post-mortem stewardship of accounts.", link: doi("10.1145/2858036.2858254"), kind: "doi" },
      { cite: "Massimi, M., & Baecker, R. M. (2010). A death in the family: Opportunities for designing technologies for the bereaved. Proceedings of the SIGCHI Conference on Human Factors in Computing Systems, 1821–1830.", note: "Bereaved participants' experiences with a deceased person's technology and data, identifying opportunities for design and planning.", link: doi("10.1145/1753326.1753600"), kind: "doi" },
      { cite: "Gulotta, R., Odom, W., Forlizzi, J., & Faste, H. (2013). Digital artifacts as legacy: Exploring the lifespan and value of digital data. Proceedings of the SIGCHI Conference on Human Factors in Computing Systems, 1813–1822.", note: "Digital artefacts as legacy: how people value, curate and imagine the lifespan of their digital possessions.", link: doi("10.1145/2470654.2466240"), kind: "doi" },
      { cite: "Morse, T., & Birnhack, M. (2022). The posthumous privacy paradox: Privacy preferences and behavior regarding digital remains. New Media & Society, 24(6), 1343–1362.", note: "The posthumous privacy paradox: people wanted control over their digital remains but rarely took steps to secure it.", link: doi("10.1177/1461444820974955"), kind: "doi" },
      { cite: "Morse, T. (2024). Digital necromancy: Users' perceptions of digital afterlife and posthumous communication technologies. Information, Communication & Society, 27(2), 240–256.", note: "Users' perceptions of digital-afterlife and posthumous-communication technologies, including discomfort with 'digital necromancy'.", link: doi("10.1080/1369118x.2023.2205467"), kind: "doi" },
      { cite: "Kasket, E. (2012). Continuing bonds in the age of social networking: Facebook as a modern-day medium. Bereavement Care, 31(2), 62–69.", note: "Facebook as a medium for continuing bonds after death, with implications for how survivors use the deceased's profile.", link: doi("10.1080/02682621.2012.710493"), kind: "doi" },
      { cite: "Bassett, D. J. (2021). Ctrl+Alt+Delete: The changing landscape of the uncanny valley and the fear of second loss. Current Psychology, 40(2), 813–821.", note: "The fear of 'second loss' — losing digital remains of the dead — and the changing landscape of digital mourning.", link: doi("10.1007/s12144-018-0006-5"), kind: "doi" },
    ],
  },
  {
    id: "gs-legacy-w2-death-cafe",
    goal: "legacy", tier: "moderate", section: "9266",
    title: "Attend a Death Café, Then a Death-Education Course",
    subtitle: "Talking about death in a group is widely reported as helpful; didactic courses reduce death anxiety more than experiential ones",
    evidenceTag: "Moderate",
    impact: { magnitude: 2, latency: "weeks", durability: "sustained", effort: "low" },
    feeds: ["death awareness", "planning follow-through", "community"],
    description:
      "Death Cafés — informal, facilitated conversations about death over tea and cake — have spread to dozens of countries; descriptive and qualitative studies find attendees value the openness and report increased death awareness and motivation to plan, while researchers note the absence of outcome trials. Death education has a longer record: meta-analyses of death-education courses found that didactic programs reduced death anxiety, whereas experiential programs sometimes increased it in the short term, and death anxiety itself is a transdiagnostic factor that tracks the severity of many mental disorders. The pairing — a low-stakes café to open the subject, then a structured course — matches what the evidence supports.",
    action: "Attend one Death Café in the next two months and, if it helps, enrol in a structured death-education or end-of-life planning course (community college, hospice or faith community). Use the sessions to complete the advance plans on this shelf.",
    sources: [
      { cite: "Miles, L., & Corr, C. A. (2017). Death Cafe: What is it and what we can learn from it. OMEGA - Journal of Death and Dying, 75(2), 151–165.", note: "Description and analysis of the Death Café model and what can be learned from it about community death conversations.", link: doi("10.1177/0030222815612602"), kind: "doi" },
      { cite: "Richards, N., Koksvik, G. H., Gerson, S. M., & Clark, D. (2020). The global spread of Death Café: A cultural intervention relevant to policy?. Social Policy and Society, 19(4), 553–572.", note: "Study of the global spread of Death Café as a cultural intervention and its possible relevance to end-of-life policy.", link: doi("10.1017/s1474746420000081"), kind: "doi" },
      { cite: "Seifu, F., Morgan, M. M., DeDiego, A. C., & Rassier, A. (2024). Conversations of life and death: Experiences of death awareness and Death Café participation. The Journal of Humanistic Counseling, 63(1), 53–66.", note: "Qualitative study of Death Café participants' experiences of death awareness and conversation.", link: doi("10.1002/johc.12199"), kind: "doi" },
      { cite: "Maglio, C. J., & Robinson, S. E. (1994). The effects of death education on death anxiety: A meta-analysis. OMEGA - Journal of Death and Dying, 29(4), 319–335.", note: "Meta-analysis: death education reduced death anxiety, with didactic formats more effective than experiential ones.", link: doi("10.2190/kea9-2g73-amjm-mnp6"), kind: "doi" },
      { cite: "Durlak, J. A., & Riesenberg, L. A. (1991). The impact of death education. Death Studies, 15(1), 39–58.", note: "Meta-analytic review of death-education outcomes across formats and populations.", link: doi("10.1080/07481189108252408"), kind: "doi" },
      { cite: "Menzies, R. E., Sharpe, L., & Dar-Nimrod, I. (2019). The relationship between death anxiety and severity of mental illnesses. British Journal of Clinical Psychology, 58(4), 452–467.", note: "Death anxiety was associated with the severity of mental illnesses across diagnoses, supporting its treatment as a transdiagnostic construct.", link: doi("10.1111/bjc.12229"), kind: "doi" },
    ],
  },
  {
    id: "gs-legacy-w2-bucket-list-honest",
    goal: "legacy", tier: "fundamental", section: "9267",
    title: "The Bucket List — Rate Honestly",
    subtitle: "Most people have one; no study shows that having one improves well-being or preparation for death",
    evidenceTag: "Emerging",
    impact: { magnitude: 1, latency: "months", durability: "transient", effort: "moderate" },
    callout: "Floor-rated. The only sizeable study of bucket lists is descriptive — it catalogues what people put on them — and there is no outcome evidence that writing or completing one improves well-being, meaning or end-of-life preparedness. What the adjacent research supports is narrower: experiences beat possessions, anticipation is part of the value, and enduring regrets are about the self one failed to become rather than the trips not taken. Spend the energy on those.",
    description:
      "A survey of more than three thousand adults found bucket lists were common and clustered into travel, achievements, relationships, financial goals and time with family, and proposed the list as a way for clinicians to learn what matters to a patient. That is the extent of the evidence. The experiential-consumption literature shows experiences bring more lasting satisfaction than possessions and that anticipation of experiences is itself enjoyable; regret research finds people's most enduring regrets concern inaction and unmet ideals of who they wanted to be. A list of experiences is not harmful, but as a legacy tool it is unproven, and it can crowd out the 'ought' and 'ideal' self-work that the regret evidence points to.",
    action: "If you keep a bucket list, cut it to three experiences you will share with the people who will remember them, and add one item from the ideal-self column: who you wanted to become, and the first step toward it this month.",
    sources: [
      { cite: "Periyakoil, V. S., Neri, E., & Kraemer, H. (2018). Common items on a bucket list. Journal of Palliative Medicine, 21(5), 652–658.", note: "Survey of common bucket-list items: travel, achievement, relationship and financial goals, proposed as a clinical tool for eliciting what matters to patients.", link: doi("10.1089/jpm.2017.0512"), kind: "doi" },
      { cite: "Van Boven, L., & Gilovich, T. (2003). To do or to have? That is the question. Journal of Personality and Social Psychology, 85(6), 1193–1202.", note: "Experiential purchases made people happier than material purchases in surveys and experiments.", link: doi("10.1037/0022-3514.85.6.1193"), kind: "doi" },
      { cite: "Kumar, A., Killingsworth, M. A., & Gilovich, T. (2014). Waiting for Merlot: Anticipatory consumption of experiential and material purchases. Psychological Science, 25(10), 1924–1931.", note: "Anticipation of experiential purchases was more pleasurable than anticipation of material ones.", link: doi("10.1177/0956797614546556"), kind: "doi" },
      { cite: "Gilovich, T., Kumar, A., & Jampol, L. (2015). A wonderful life: Experiential consumption and the pursuit of happiness. Journal of Consumer Psychology, 25(1), 152–165.", note: "Review of why experiential consumption contributes more to happiness: social connection, identity and fewer comparisons.", link: doi("10.1016/j.jcps.2014.08.004"), kind: "doi" },
      { cite: "Gilovich, T., & Medvec, V. H. (1995). The experience of regret: What, when, and why. Psychological Review, 102(2), 379–395.", note: "The experience of regret: in the long run people regret inactions more than actions.", link: doi("10.1037/0033-295x.102.2.379"), kind: "doi" },
      { cite: "Davidai, S., & Gilovich, T. (2018). The ideal road not taken: The self-discrepancies involved in people's most enduring regrets. Emotion, 18(3), 439–452.", note: "People's most enduring regrets involved failures to live up to their ideal self more than failures of duty.", link: doi("10.1037/emo0000326"), kind: "doi" },
    ],
  },
];
