// Goal shelf, WAVE 2: PARENTING — be a better parent (sections 8150–8199).
// Wave 2 widens the wave-1 parenting shelf with the topics listed in the wave-2 brief.
// Verification: every DOI below was resolved against the Crossref record or the
// PubMed record on 2026-09-11 (ledger: scratchpad/shelves/parenting.w2.ledger.json).
// See ../types.ts for the contract. Nothing here is medical, legal or financial advice.
import { doi, type GoalShelfCluster } from "../types";

export const SECTIONS: Record<string, string> = {
  "8150": "Infant Sleep Training — What the Trials Actually Show",
  "8151": "Breastfeeding — PROBIT and the Sibling Studies",
  "8152": "Early Childhood Education — Perry, Abecedarian, Head Start, Tennessee",
  "8153": "Math Talk & Number Sense at Home",
  "8154": "Raising Bilingual Children",
  "8155": "Allowance & Money Socialization",
  "8156": "Youth Sports — Sampling, Specialization & Long-Run Outcomes",
  "8157": "Homework by Age, and Tutoring",
  "8158": "Adolescent Sleep & School Start Times",
  "8159": "Parental Phone Use Around Children",
  "8160": "Sibling Conflict — Skills, Not Referees",
  "8161": "Bullying Prevention — KiVa, Olweus & the Meta-Analyses",
  "8162": "Family-Based Drug & Alcohol Prevention — Strengthening Families 10–14",
  "8163": "Teen Driving — Graduated Licensing & Parent-Teen Agreements",
  "8164": "Self-Regulation Curricula — Tools of the Mind (Honest)",
  "8165": "Shared & Dialogic Reading",
  "8166": "Nature Time for Children",
  "8167": "Child Anxiety Programs — Cool Kids & Parent-Led CBT",
  "8168": "Positive Memories — Family Rituals, Meals & Vacations",
  "8169": "Corporal Punishment — the Meta-Analyses (Debunked)",
};

export const CLUSTERS: GoalShelfCluster[] = [
  {
    id: "gs-parenting-w2-sleep-training",
    goal: "parenting", tier: "moderate", section: "8150",
    title: "Behavioral Infant Sleep Training (Graduated Extinction, Bedtime Fading)",
    subtitle: "Works within weeks in trials; five-year follow-up found no measurable harm",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "moderate" },
    feeds: ["Parent sleep and mood", "Infant sleep consolidation", "Family routine"],
    description:
      "Behavioral sleep programs for infants over about six months (graduated extinction, bedtime fading, parent education) were tested in randomized trials and a task-force review. They reliably reduce night wakings and settling time and lower parent stress; the Melbourne trial's five-year follow-up found no differences in child emotional health, behavior or parent-child attachment. The honest boundary: effects are on sleep and parent mood, trials are small, and the programs are for healthy infants past the newborn months.",
    action: "If your baby is over six months and waking repeatedly, pick one method (graduated extinction or bedtime fading), agree the plan with your partner, and run it consistently for 14 nights before judging it; track wake-ups in a simple log.",
    sources: [
      { cite: "Gradisar, M., Jackson, K., Spurrier, N. J., Gibson, J., Whitham, J., Williams, A. S., & … Kennaway, D. J. (2016). Behavioral Interventions for Infant Sleep Problems: A Randomized Controlled Trial. Pediatrics, 137(6).", note: "Randomized trial of 43 infants: graduated extinction and bedtime fading cut sleep latency and wakings versus education control, with no adverse effects on infant cortisol, child behavior or attachment at 12 months.", link: doi("10.1542/peds.2015-1486"), kind: "doi" },
      { cite: "Price, A. M. H., Wake, M., Ukoumunne, O. C., & Hiscock, H. (2012). Five-Year Follow-up of Harms and Benefits of Behavioral Infant Sleep Intervention: Randomized Trial. Pediatrics.", note: "Five-year follow-up of the Melbourne randomized trial: no differences in child mental health, sleep, stress regulation or parent-child relationship, and no lasting harm from the intervention.", link: doi("10.1542/peds.2011-3467"), kind: "doi" },
      { cite: "Hiscock, H., Bayer, J. K., Hampton, A., Ukoumunne, O. C., & Wake, M. (2008). Long-term Mother and Child Mental Health Effects of a Population-Based Infant Sleep Intervention: Cluster-Randomized, Controlled Trial. Pediatrics.", note: "Cluster-randomized population trial: a brief nurse-delivered sleep program reduced infant sleep problems and maternal depression symptoms, with benefits still visible at the two-year follow-up.", link: doi("10.1542/peds.2007-3783"), kind: "doi" },
      { cite: "Mindell, J. A., Kuhn, B., Lewin, D. S., Meltzer, L. J., & Sadeh, A. (2006). Behavioral treatment of bedtime problems and night wakings in infants and young children. Sleep, 29(10), 1263-1276.", note: "Task-force review of 52 treatment studies: behavioral interventions were efficacious in the great majority, with strongest support for extinction and preventive parent education.", link: doi("10.1093/sleep/29.10.1263"), kind: "doi" },
      { cite: "Moore, M., Meltzer, L. J., & Mindell, J. A. (2008). Bedtime problems and night wakings in children. Primary care, 35(3), 569-81, viii.", note: "Clinical review of empirically supported treatments for bedtime problems and night wakings, including graduated extinction and positive routines, and the practical challenges of delivering them.", link: doi("10.1016/j.pop.2008.06.002"), kind: "doi" },
    ],
  },
  {
    id: "gs-parenting-w2-breastfeeding",
    goal: "parenting", tier: "fundamental", section: "8151",
    title: "Breastfeeding — What a Randomized Trial and Sibling Comparisons Show",
    subtitle: "Real but modest benefits; most long-term claims shrink once family background is held constant",
    evidenceTag: "Mixed",
    impact: { magnitude: 2, latency: "months", durability: "lasting", effort: "moderate" },
    feeds: ["Infant nutrition", "Early cognitive development", "Realistic expectations"],
    description:
      "PROBIT, the only large randomized trial of breastfeeding promotion, found modest gains in child cognitive scores but no effect on later behavior, height, adiposity or blood pressure. A US sibling-comparison study found most of the usual long-term advantages attributed to breastfeeding shrink toward zero when siblings fed differently are compared. The honest picture: breastfeeding is worthwhile where it works, and parents who cannot or choose not to breastfeed are not consigning a child to worse outcomes.",
    action: "If you plan to breastfeed, front-load support in the first two weeks (a lactation consultant or clinic, and a partner who handles everything else); if it is not working, switch without guilt and put the energy into responsive feeding and reading.",
    sources: [
      { cite: "Kramer, M. S., Chalmers, B., Hodnett, E. D., Sevkovskaya, Z., Dzikovich, I., Shapiro, S., & …  (2001). Promotion of Breastfeeding Intervention Trial (PROBIT): a randomized trial in the Republic of Belarus. JAMA, 285(4), 413-20.", note: "The PROBIT cluster-randomized trial in Belarus: a hospital breastfeeding-promotion intervention raised exclusive breastfeeding rates, creating the only large experimental test of breastfeeding effects.", link: doi("10.1001/jama.285.4.413"), kind: "doi" },
      { cite: "Kramer, M. S., Aboud, F., Mironova, E., Vanilovich, I., Platt, R. W., Matush, L., & …  (2008). Breastfeeding and child cognitive development: new evidence from a large randomized trial. Archives of general psychiatry, 65(5), 578-84.", note: "PROBIT follow-up at 6.5 years: children in the promotion arm scored higher on verbal IQ and teacher ratings, the strongest experimental evidence for a cognitive benefit.", link: doi("10.1001/archpsyc.65.5.578"), kind: "doi" },
      { cite: "Kramer, M. S., Fombonne, E., Igumnov, S., Vanilovich, I., Matush, L., Mironova, E., & …  (2008). Effects of prolonged and exclusive breastfeeding on child behavior and maternal adjustment: evidence from a large, randomized trial. Pediatrics, 121(3), e435-40.", note: "PROBIT follow-up on behavior and maternal adjustment: prolonged and exclusive breastfeeding did not improve child behavior or maternal outcomes at 6.5 years.", link: doi("10.1542/peds.2007-1248"), kind: "doi" },
      { cite: "Kramer, M. S., Matush, L., Vanilovich, I., Platt, R. W., Bogdanovich, N., Sevkovskaya, Z., & … Collet, J. P. (2007). Effects of prolonged and exclusive breastfeeding on child height, weight, adiposity, and blood pressure at age 6.5 y: evidence from a large randomized trial. The American Journal of Clinical Nutrition.", note: "PROBIT follow-up at 6.5 years: no effect of the breastfeeding intervention on child height, weight, adiposity or blood pressure.", link: doi("10.1093/ajcn/86.5.1717"), kind: "doi" },
      { cite: "Colen, C. G., & Ramey, D. M. (2014). Is breast truly best? Estimating the effects of breastfeeding on long-term child health and wellbeing in the United States using sibling comparisons. Social science & medicine (1982), 109, 55-65.", note: "US sibling comparisons: differences on 11 child health and wellbeing outcomes largely disappeared within families, suggesting selection explains much of the apparent benefit.", link: doi("10.1016/j.socscimed.2014.01.027"), kind: "doi" },
    ],
  },
  {
    id: "gs-parenting-w2-early-childhood-education",
    goal: "parenting", tier: "elite", section: "8152",
    title: "High-Quality Early Childhood Education — Perry, Abecedarian and the Modern Programs",
    subtitle: "Intensive, well-run programs had lifelong effects; ordinary scaled pre-K has not reliably reproduced them",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "months", durability: "lasting", effort: "high" },
    feeds: ["School readiness", "Adult earnings and health", "Non-cognitive skills"],
    description:
      "The Perry Preschool and Abecedarian experiments, both randomized and followed for decades, raised adult earnings, employment and health and reduced crime, with much of the effect running through non-cognitive skills rather than IQ. Head Start shows smaller but real long-run gains once you account for what the comparison children were doing instead. The honest caution is Tennessee: a statewide voluntary pre-K program produced early gains that faded and turned negative by sixth grade, so quality and what happens afterwards matter more than enrollment itself.",
    action: "If you use preschool, judge it on the things the successful programs shared: small groups, trained teachers, a stable relationship with the same adult, and a curriculum built on play and language; visit twice, watch how adults talk to children, and keep your own reading and math talk going at home.",
    sources: [
      { cite: "Heckman, J. J., Moon, S. H., Pinto, R., Savelyev, P. A., & Yavitz, A. (2010). The rate of return to the HighScope Perry Preschool Program. Journal of Public Economics, 94(1-2), 114-128.", note: "Re-analysis of the Perry Preschool randomized experiment estimating a substantial annual social rate of return on the program through age 40.", link: doi("10.1016/j.jpubeco.2009.11.001"), kind: "doi" },
      { cite: "Heckman, J., Pinto, R., & Savelyev, P. (2013). Understanding the Mechanisms Through Which an Influential Early Childhood Program Boosted Adult Outcomes. American Economic Review, 103(6), 2052-2086.", note: "Perry mechanisms study: experimentally induced changes in personality skills explain a sizable portion of the adult treatment effects, more than IQ gains.", link: doi("10.1257/aer.103.6.2052"), kind: "doi" },
      { cite: "Campbell, F. A., Ramey, C. T., Pungello, E., Sparling, J., & Miller-Johnson, S. (2002). Early Childhood Education: Young Adult Outcomes From the Abecedarian Project. Applied Developmental Science, 6(1), 42-57.", note: "Abecedarian young-adult follow-up: the randomized full-day program from infancy produced higher cognitive scores and educational attainment at age 21.", link: doi("10.1207/s1532480xads0601_05"), kind: "doi" },
      { cite: "Campbell, F., Conti, G., Heckman, J. J., Moon, S. H., Pinto, R., Pungello, E., & Pan, Y. (2014). Early Childhood Investments Substantially Boost Adult Health. Science, 343(6178), 1478-1485.", note: "Abecedarian at the mid-30s: the treatment group had better metabolic and cardiovascular health markers, linking early education to adult physical health.", link: doi("10.1126/science.1248429"), kind: "doi" },
      { cite: "Kline, P., & Walters, C. R. (2016). Evaluating Public Programs with Close Substitutes: The Case of Head Start. The Quarterly Journal of Economics, 131(4), 1795-1848.", note: "Head Start evaluated against close substitutes: effects are larger for children who would otherwise have stayed home than for those who would have attended other preschools.", link: doi("10.1093/qje/qjw027"), kind: "doi" },
      { cite: "Deming, D. (2009). Early Childhood Intervention and Life-Cycle Skill Development: Evidence from Head Start. American Economic Journal: Applied Economics, 1(3), 111-134.", note: "Sibling-comparison evidence that Head Start participation improved long-term outcomes such as educational attainment despite test-score fade-out.", link: doi("10.1257/app.1.3.111"), kind: "doi" },
      { cite: "Lipsey, M. W., Farran, D. C., & Durkin, K. (2018). Effects of the Tennessee Prekindergarten Program on children's achievement and behavior through third grade. Early Childhood Research Quarterly, 45, 155-176.", note: "Tennessee's randomized statewide pre-K study through third grade: early gains faded, and the pre-K group did not outperform controls.", link: doi("10.1016/j.ecresq.2018.03.005"), kind: "doi" },
      { cite: "Durkin, K., Lipsey, M. W., Farran, D. C., & Wiesen, S. E. (2022). Effects of a statewide pre-kindergarten program on children's achievement and behavior through sixth grade. Developmental Psychology, 58(3), 470-484.", note: "Tennessee follow-up through sixth grade: the pre-K group scored lower on achievement and had more disciplinary infractions, a warning that scaled programs can miss.", link: doi("10.1037/dev0001301"), kind: "doi" },
    ],
  },
  {
    id: "gs-parenting-w2-math-talk",
    goal: "parenting", tier: "fundamental", section: "8153",
    title: "Math Talk and Number Games at Home",
    subtitle: "Counting, labeling quantities and board games move early number knowledge",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "low" },
    feeds: ["Number sense", "School math achievement", "Parent-child interaction"],
    description:
      "How much parents talk about numbers in ordinary conversation predicts children's number knowledge, and randomized studies show causation: brief parent number-talk interventions and linear number board games raise preschoolers' counting, comparison and number-line skills. A randomized app-based study of first graders found that families who did short math problems together at bedtime gained in math achievement, most for children of math-anxious parents. The boundary: effects are on early skills, and the games work best when numbers are said aloud, not just moved.",
    action: "Three times a week, count and label quantities out loud with your child (stairs, grapes, blocks) and play a linear number board game for 15 minutes; at bedtime, do one short math story problem the way you would read a book.",
    sources: [
      { cite: "Levine, S. C., Suriyakham, L. W., Rowe, M. L., Huttenlocher, J., & Gunderson, E. A. (2010). What counts in the development of young children's number knowledge?. Developmental Psychology, 46(5), 1309-1319.", note: "Longitudinal home-observation study: the amount of parent number talk between 14 and 30 months predicted children's cardinal-number knowledge at 46 months.", link: doi("10.1037/a0019671"), kind: "doi" },
      { cite: "Gunderson, E. A., & Levine, S. C. (2011). Some types of parent number talk count more than others: relations between parents' input and children's cardinal-number knowledge. Developmental science, 14(5), 1021-32.", note: "Parent talk about the cardinal values of visible sets of objects predicted later number knowledge more than other kinds of number talk.", link: doi("10.1111/j.1467-7687.2011.01050.x"), kind: "doi" },
      { cite: "Gibson, D. J., Gunderson, E. A., & Levine, S. C. (2020). Causal Effects of Parent Number Talk on Preschoolers' Number Knowledge. Child development, 91(6), e1162-e1177.", note: "Randomized experiment: a parent number-talk intervention causally increased preschoolers' number knowledge.", link: doi("10.1111/cdev.13423"), kind: "doi" },
      { cite: "Berkowitz, T., Schaeffer, M. W., Maloney, E. A., Peterson, L., Gregor, C., Levine, S. C., & Beilock, S. L. (2015). Math at home adds up to achievement in school. Science.", note: "Randomized field study of first graders: brief bedtime math talk via an app improved math achievement, especially for children of math-anxious parents.", link: doi("10.1126/science.aac7427"), kind: "doi" },
      { cite: "Ramani, G. B., & Siegler, R. S. (2008). Promoting broad and stable improvements in low-income children's numerical knowledge through playing number board games. Child development, 79(2), 375-94.", note: "Randomized study: playing a linear number board game with low-income preschoolers produced broad, stable gains in numerical knowledge.", link: doi("10.1111/j.1467-8624.2007.01131.x"), kind: "doi" },
      { cite: "Siegler, R. S., & Ramani, G. B. (2008). Playing linear numerical board games promotes low-income children's numerical development. Developmental science, 11(5), 655-61.", note: "Linear (but not circular) number board games improved low-income children's numerical estimation and comparison.", link: doi("10.1111/j.1467-7687.2008.00714.x"), kind: "doi" },
    ],
  },
  {
    id: "gs-parenting-w2-bilingual",
    goal: "parenting", tier: "moderate", section: "8154",
    title: "Raising Bilingual Children — Input, Not Magic",
    subtitle: "Two languages are a real gift; the executive-function bonus is smaller than advertised",
    evidenceTag: "Mixed",
    impact: { magnitude: 3, latency: "months", durability: "lasting", effort: "moderate" },
    feeds: ["Second-language fluency", "Family and cultural connection", "Vocabulary in each language"],
    description:
      "Children raised with two languages develop each in proportion to how much rich input they get in it, and early on their vocabulary in either single language runs somewhat behind monolingual peers while their total vocabulary does not. Early studies reported bilingual advantages in attention and cognitive control, but a large meta-analysis of adults found the executive-function advantage small and unreliable once publication bias is considered. The honest verdict: raise the second language for the language itself and the relationships it opens, not for a cognitive edge.",
    action: "Decide which adult or context carries each language and protect the minority language's input (books, songs, video calls with relatives, a weekly playgroup) so it gets several hours a week; do not worry about early single-language vocabulary gaps if total vocabulary is growing.",
    sources: [
      { cite: "Lehtonen, M., Soveri, A., Laine, A., Järvenpää, J., de Bruin, A., & Antfolk, J. (2018). Is bilingualism associated with enhanced executive functioning in adults? A meta-analytic review. Psychological bulletin, 144(4), 394-425.", note: "Meta-analysis of 152 studies: the bilingual executive-function advantage in adults was small and vanished after correcting for publication bias.", link: doi("10.1037/bul0000142"), kind: "doi" },
      { cite: "Bialystok, E., Craik, F. I. M., Klein, R., & Viswanathan, M. (2004). Bilingualism, aging, and cognitive control: evidence from the Simon task. Psychology and Aging, 19(2), 290-303.", note: "Early evidence of a bilingual cognitive-control advantage on the Simon task, larger in older adults, that later meta-analyses tempered.", link: doi("10.1037/0882-7974.19.2.290"), kind: "doi" },
      { cite: "Bialystok, E., Luk, G., Peets, K. F., & Yang, S. (2010). Receptive vocabulary differences in monolingual and bilingual children. Bilingualism (Cambridge, England), 13(4), 525-531.", note: "Bilingual children scored lower than monolinguals on single-language receptive vocabulary, mainly for home-context words, with no gap in school-related words.", link: doi("10.1017/S1366728909990423"), kind: "doi" },
      { cite: "Hoff, E., Core, C., Place, S., Rumiche, R., Señor, M., & Parra, M. (2011). Dual language exposure and early bilingual development. Journal of child language, 39(1), 1-27.", note: "Dual-language exposure study of toddlers: relative amount of exposure to each language predicted vocabulary and grammar in that language.", link: doi("10.1017/S0305000910000759"), kind: "doi" },
      { cite: "Place, S., & Hoff, E. (2011). Properties of dual language exposure that influence 2-year-olds' bilingual proficiency. Child development, 82(6), 1834-49.", note: "Properties of dual-language exposure (native-speaker input, number of speakers) predicted 2-year-olds' bilingual proficiency.", link: doi("10.1111/j.1467-8624.2011.01660.x"), kind: "doi" },
      { cite: "Marchman, V. A., Martínez-Sussmann, C., & Dale, P. S. (2004). The language-specific nature of grammatical development: evidence from bilingual language learners. Developmental science, 7(2), 212-24.", note: "Bilingual toddlers' grammatical development in each language tracked vocabulary in that same language, showing development is language-specific.", link: doi("10.1111/j.1467-7687.2004.00340.x"), kind: "doi" },
    ],
  },
  {
    id: "gs-parenting-w2-allowance",
    goal: "parenting", tier: "fundamental", section: "8155",
    title: "Allowance and Everyday Money Socialization",
    subtitle: "What parents model and discuss shapes saving more than the allowance itself",
    evidenceTag: "Moderate",
    impact: { magnitude: 2, latency: "months", durability: "lasting", effort: "low" },
    feeds: ["Saving habits", "Financial self-efficacy", "Family money conversations"],
    description:
      "Family financial socialization research finds that children learn money habits mainly by watching parents, having money explained, and being given real (small) decisions, and that adolescent saving behavior predicts adult saving. Allowance studies are mostly surveys of parental attitudes and child behavior, not experiments, so the evidence is correlational. What the literature supports: a regular allowance with a saving expectation and open conversation about household choices, not money as an unexplained reward or punishment.",
    action: "Give a fixed weekly allowance from about age six, split by rule into spend, save and give, and once a month walk your child through one real household decision (a grocery trade-off, a bill) out loud.",
    sources: [
      { cite: "Gudmunson, C. G., & Danes, S. M. (2011). Family Financial Socialization: Theory and Critical Review. Journal of Family and Economic Issues, 32(4), 644-667.", note: "Theory and critical review of family financial socialization: parents transmit financial attitudes and behaviors mostly implicitly, through modeling and everyday interaction.", link: doi("10.1007/s10834-011-9275-y"), kind: "doi" },
      { cite: "Webley, P., & Nyhus, E. K. (2006). Parents' influence on children's future orientation and saving. Journal of Economic Psychology, 27(1), 140-164.", note: "Longitudinal Dutch data: parents' own orientation to the future and discussion of money predicted their children's later saving as adults.", link: doi("10.1016/j.joep.2005.06.016"), kind: "doi" },
      { cite: "Furnham, A. (2001). Parental attitudes to pocket money/allowances for children. Journal of Economic Psychology, 22(3), 397-422.", note: "Survey of parental attitudes to pocket money: most parents favored regular, rule-based allowances and expected children to budget and save from them.", link: doi("10.1016/s0167-4870(01)00040-x"), kind: "doi" },
      { cite: "Ashby, J. S., Schoon, I., & Webley, P. (2011). Save Now, Save Later? Linkages Between Saving Behavior in Adolescence and Adulthood. European Psychologist, 16(3), 227-237.", note: "British cohort analysis: saving behavior in adolescence predicted saving in adulthood, supporting early habit formation.", link: doi("10.1027/1016-9040/a000067"), kind: "doi" },
    ],
  },
  {
    id: "gs-parenting-w2-youth-sports",
    goal: "parenting", tier: "moderate", section: "8156",
    title: "Youth Sports — Sample Widely, Specialize Late",
    subtitle: "Participation carries psychosocial benefits; early single-sport specialization raises injury and dropout risk",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "months", durability: "lasting", effort: "moderate" },
    feeds: ["Physical activity that persists into adulthood", "Self-esteem and social skills", "Injury prevention"],
    description:
      "Reviews of youth sport find psychological and social benefits, particularly from team sport, and physical activity in youth tracks into adulthood. The same literature finds high dropout driven by pressure and lost enjoyment, and a meta-analysis links early single-sport specialization to higher overuse-injury risk. Expert position statements converge on sampling several sports and free play before adolescence and deferring intense specialization.",
    action: "Before about age 12, enroll your child in two or three different sports across the year with at least one season off from any single sport, keep total organized hours below their age in years per week, and make the post-game conversation about effort and fun, not results.",
    sources: [
      { cite: "Eime, R. M., Young, J. A., Harvey, J. T., Charity, M. J., & Payne, W. R. (2013). A systematic review of the psychological and social benefits of participation in sport for children and adolescents: informing development of a conceptual model of health through sport. The international journal of behavioral nutrition and physical activity, 10, 98.", note: "Systematic review of 30 studies: sport participation in children and adolescents was associated with better self-esteem, social skills and fewer depressive symptoms, especially team sport.", link: doi("10.1186/1479-5868-10-98"), kind: "doi" },
      { cite: "Telama, R., Yang, X., Viikari, J., Välimäki, I., Wanne, O., & Raitakari, O. (2005). Physical activity from childhood to adulthood: a 21-year tracking study. American journal of preventive medicine, 28(3), 267-73.", note: "21-year Finnish tracking study: physical activity in childhood and adolescence predicted activity in adulthood.", link: doi("10.1016/j.amepre.2004.12.003"), kind: "doi" },
      { cite: "Crane, J., & Temple, V. (2015). A systematic review of dropout from organized sport among children and youth. European Physical Education Review, 21(1), 114-131.", note: "Systematic review of dropout from organized youth sport: lack of enjoyment, perceived competence and pressure were the recurring drivers.", link: doi("10.1177/1356336x14555294"), kind: "doi" },
      { cite: "Fraser-Thomas, J. L., Côté, J., & Deakin, J. (2005). Youth sport programs: an avenue to foster positive youth development. Physical Education & Sport Pedagogy, 10(1), 19-40.", note: "Framework paper on how youth sport programs foster positive youth development when structured around enjoyment and skill.", link: doi("10.1080/1740898042000334890"), kind: "doi" },
      { cite: "Jayanthi, N., Pinkham, C., Dugas, L., Patrick, B., & Labella, C. (2013). Sports specialization in young athletes: evidence-based recommendations. Sports health, 5(3), 251-7.", note: "Evidence-based recommendations on sports specialization for young athletes, favoring diversification before adolescence.", link: doi("10.1177/1941738112464626"), kind: "doi" },
      { cite: "Bell, D. R., Post, E. G., Biese, K., Bay, C., & Valovich McLeod, T. (2018). Sport Specialization and Risk of Overuse Injuries: A Systematic Review With Meta-analysis. Pediatrics, 142(3).", note: "Meta-analysis: higher levels of sport specialization were associated with increased risk of overuse injury.", link: doi("10.1542/peds.2018-0657"), kind: "doi" },
      { cite: "Myer, G. D., Jayanthi, N., DiFiori, J. P., Faigenbaum, A. D., Kiefer, A. W., Logerstedt, D., & Micheli, L. J. (2015). Sport Specialization, Part I: Does Early Sports Specialization Increase Negative Outcomes and Reduce the Opportunity for Success in Young Athletes?. Sports Health, 7(5), 437-442.", note: "Review concluding that early specialization increases injury and burnout risk without improving the odds of elite success.", link: doi("10.1177/1941738115598747"), kind: "doi" },
      { cite: "Côté, J., Lidor, R., & Hackfort, D. (2009). ISSP position stand: To sample or to specialize? Seven postulates about youth sport activities that lead to continued participation and elite performance. International Journal of Sport and Exercise Psychology, 7(1), 7-17.", note: "International Society of Sport Psychology position stand with seven postulates favoring sampling over early specialization.", link: doi("10.1080/1612197x.2009.9671889"), kind: "doi" },
    ],
  },
  {
    id: "gs-parenting-w2-homework-tutoring",
    goal: "parenting", tier: "moderate", section: "8157",
    title: "Homework by Age, and Tutoring That Moves Achievement",
    subtitle: "Homework pays off mainly in secondary school; structured tutoring has large, consistent effects",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "months", durability: "sustained", effort: "moderate" },
    feeds: ["Academic achievement", "Study habits", "Targeted support for a struggling child"],
    description:
      "The major syntheses find the homework-achievement link is positive in middle and high school and near zero in elementary grades, and that quality and effort matter more than minutes spent. Parent involvement in homework helps when it is autonomy-supporting and hurts when it becomes control. For a child who is behind, the experimental literature on tutoring is unusually consistent: structured, frequent tutoring by trained tutors produces large gains, one of the most effective interventions in education.",
    action: "For elementary children, cap homework to short daily reading plus whatever the teacher assigns and stop policing minutes; for a child who is behind in reading or math, arrange three 30-minute sessions a week of structured tutoring for a semester before trying anything else.",
    sources: [
      { cite: "Cooper, H., Robinson, J. C., & Patall, E. A. (2006). Does Homework Improve Academic Achievement? A Synthesis of Research, 1987-2003. Review of Educational Research, 76(1), 1-62.", note: "Synthesis of 1987-2003 research: homework-achievement correlations were positive for secondary students and negligible in elementary grades.", link: doi("10.3102/00346543076001001"), kind: "doi" },
      { cite: "Fan, H., Xu, J., Cai, Z., He, J., & Fan, X. (2017). Homework and students' achievement in math and science: A 30-year meta-analysis, 1986-2015. Educational Research Review, 20, 35-54.", note: "30-year meta-analysis in math and science: homework effects were small overall and varied by grade level and how homework was measured.", link: doi("10.1016/j.edurev.2016.11.003"), kind: "doi" },
      { cite: "Trautwein, U. (2007). The homework-achievement relation reconsidered: Differentiating homework time, homework frequency, and homework effort. Learning and Instruction, 17(3), 372-388.", note: "Homework frequency and effort predicted achievement; sheer time spent did not, and could reflect struggle rather than learning.", link: doi("10.1016/j.learninstruc.2007.02.009"), kind: "doi" },
      { cite: "Patall, E. A., Cooper, H., & Robinson, J. C. (2008). Parent Involvement in Homework: A Research Synthesis. Review of Educational Research, 78(4), 1039-1101.", note: "Research synthesis on parent involvement in homework: rule-setting and autonomy support helped, while direct control was associated with worse outcomes.", link: doi("10.3102/0034654308325185"), kind: "doi" },
      { cite: "Fernández-Alonso, R., Suárez-Álvarez, J., & Muñiz, J. (2015). Adolescents' homework performance in mathematics and science: Personal factors and teaching practices. Journal of Educational Psychology, 107(4), 1075-1085.", note: "Adolescents' homework performance related to how they worked and how teachers set homework, not simply to time spent.", link: doi("10.1037/edu0000032"), kind: "doi" },
      { cite: "Nickow, A., Oreopoulos, P., & Quan, V. (2020). The Impressive Effects of Tutoring on PreK-12 Learning: A Systematic Review and Meta-Analysis of the Experimental Evidence. NBER Working Paper Series (National Bureau of Economic Research).", note: "Systematic review and meta-analysis of experimental tutoring studies: consistent large effects on PreK-12 learning, strongest for frequent, structured programs.", link: doi("10.3386/w27476"), kind: "doi" },
      { cite: "Dietrichson, J., Bøg, M., Filges, T., & Klint Jørgensen, A. M. (2017). Academic Interventions for Elementary and Middle School Students With Low Socioeconomic Status: A Systematic Review and Meta-Analysis. Review of Educational Research, 87(2), 243-282.", note: "Meta-analysis of academic interventions for low-SES students: tutoring was among the most effective, alongside feedback and cooperative learning.", link: doi("10.3102/0034654316687036"), kind: "doi" },
    ],
  },
  {
    id: "gs-parenting-w2-adolescent-sleep",
    goal: "parenting", tier: "moderate", section: "8158",
    title: "Adolescent Sleep and Later School Start Times",
    subtitle: "Teens' clocks shift later; when schools start later, they sleep more and do better",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "moderate" },
    feeds: ["Teen mood and attention", "Academic performance", "Safer driving"],
    description:
      "Adolescents' circadian timing shifts later, and early school start times cut sleep. Reviews and natural experiments, including Seattle's district-wide delay, show that later starts add real sleep, reduce daytime sleepiness and tardiness, and in some studies improve grades and attendance. At home the parallel levers are a protected wake time, dim evenings without screens, and morning light.",
    action: "Set a fixed wake time seven days a week and a device-off point 60 minutes before bed for your teenager, and add a bright-light morning routine; if your district still starts before 8:30, join or start the parent effort to move it.",
    sources: [
      { cite: "Wheaton, A. G., Chapman, D. P., & Croft, J. B. (2016). School Start Times, Sleep, Behavioral, Health, and Academic Outcomes: A Review of the Literature. The Journal of school health, 86(5), 363-81.", note: "Literature review: later school start times were associated with more sleep, better attendance and fewer behavioral and health problems in adolescents.", link: doi("10.1111/josh.12388"), kind: "doi" },
      { cite: "Minges, K. E., & Redeker, N. S. (2015). Delayed school start times and adolescent sleep: A systematic review of the experimental evidence. Sleep medicine reviews, 28, 86-95.", note: "Systematic review of experimental evidence: delaying school start times increased adolescent sleep duration across studies.", link: doi("10.1016/j.smrv.2015.06.002"), kind: "doi" },
      { cite: "Dunster, G. P., de la Iglesia, L., Ben-Hamo, M., Nave, C., Fleischer, J. G., Panda, S., & de la Iglesia, H. O. (2018). Sleepmore in Seattle: Later school start times are associated with more sleep and better performance in high school students. Science advances, 4(12), eaau6200.", note: "Seattle's school start-time delay: actigraphy showed students gained sleep, with better grades and attendance in the follow-up cohort.", link: doi("10.1126/sciadv.aau6200"), kind: "doi" },
      { cite: "Owens, J. A., Belon, K., & Moss, P. (2010). Impact of delaying school start time on adolescent sleep, mood, and behavior. Archives of pediatrics & adolescent medicine, 164(7), 608-14.", note: "A 30-minute later start at one school increased sleep, improved mood and reduced daytime sleepiness among students.", link: doi("10.1001/archpediatrics.2010.96"), kind: "doi" },
      { cite: "Bowers, J. M., & Moyer, A. (2017). Effects of school start time on students' sleep duration, daytime sleepiness, and attendance: a meta-analysis. Sleep Health, 3(6), 423-431.", note: "Meta-analysis of 20 studies: later starts were associated with longer sleep, less daytime sleepiness and less tardiness.", link: doi("10.1016/j.sleh.2017.08.004"), kind: "doi" },
      { cite: "Alfonsi, V., Palmizio, R., Rubino, A., Scarpelli, S., Gorgoni, M., D'Atri, A., & … De Gennaro, L. (2020). The Association Between School Start Time and Sleep Duration, Sustained Attention, and Academic Performance. Nature and Science of Sleep, 12, 1161-1172.", note: "A one-hour later start class slept longer, sustained attention better and improved academically over a year compared with an earlier class.", link: doi("10.2147/NSS.S273875"), kind: "doi" },
      { cite: "Alfonsi, V., Scarpelli, S., D'Atri, A., Stella, G., & De Gennaro, L. (2020). Later School Start Time: The Impact of Sleep on Academic Performance and Health in the Adolescent Population. International Journal of Environmental Research and Public Health, 17(7).", note: "Review of recent studies on modified school start times, sleep patterns and academic performance in adolescents.", link: doi("10.3390/ijerph17072574"), kind: "doi" },
    ],
  },
  {
    id: "gs-parenting-w2-parent-phone-use",
    goal: "parenting", tier: "fundamental", section: "8159",
    title: "Parental Phone Use Around Children (\"Technoference\")",
    subtitle: "Parents absorbed in devices respond less, and children act out more",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "low" },
    feeds: ["Responsive parenting", "Child behavior", "Mealtime connection"],
    description:
      "Observational and longitudinal studies find that parents' device use interrupts interaction with children, is associated with harsher or fewer responses, and predicts more child behavior problems over time. Using a device to calm a toddler is associated with poorer social-emotional development in some studies. The evidence is mostly correlational and the effect sizes modest, but the mechanism, lost responsive moments, is well documented.",
    action: "Make two daily windows phone-free and visible to your child (the first 20 minutes after you reunite and every family meal); park the phone in another room during them, and narrate what you are doing when you do need it.",
    sources: [
      { cite: "McDaniel, B. T., & Radesky, J. S. (2017). Technoference: Parent Distraction With Technology and Associations With Child Behavior Problems. Child development, 89(1), 100-109.", note: "Longitudinal parent reports: technology interference in parent-child interactions predicted more child externalizing and internalizing problems over time.", link: doi("10.1111/cdev.12822"), kind: "doi" },
      { cite: "Radesky, J. S., Kistin, C. J., Zuckerman, B., Nitzberg, K., Gross, J., Kaplan-Sanoff, M., & … Silverstein, M. (2014). Patterns of mobile device use by caregivers and children during meals in fast food restaurants. Pediatrics, 133(4), e843-9.", note: "Naturalistic observation of caregivers in fast-food restaurants: many were absorbed in devices and responded more harshly to children's bids for attention.", link: doi("10.1542/peds.2013-3703"), kind: "doi" },
      { cite: "Radesky, J. S., Peacock-Chambers, E., Zuckerman, B., & Silverstein, M. (2016). Use of Mobile Technology to Calm Upset Children. JAMA Pediatrics, 170(4), 397.", note: "Parents who reported using mobile devices to calm upset children had children with poorer social-emotional development in this observational study.", link: doi("10.1001/jamapediatrics.2015.4260"), kind: "doi" },
      { cite: "Kildare, C. A., & Middlemiss, W. (2017). Impact of parents mobile device use on parent-child interaction: A literature review. Computers in Human Behavior, 75, 579-593.", note: "Literature review of parents' mobile device use: consistent evidence of reduced responsiveness and interrupted parent-child interaction.", link: doi("10.1016/j.chb.2017.06.003"), kind: "doi" },
    ],
  },
  {
    id: "gs-parenting-w2-sibling-conflict",
    goal: "parenting", tier: "moderate", section: "8160",
    title: "Sibling Conflict — Teach Skills, Coach the Fight, Don't Referee",
    subtitle: "Sibling aggression is common and not harmless; social-skills and coaching programs reduce it",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "moderate" },
    feeds: ["Sibling warmth", "Conflict-resolution skills", "Lower family stress"],
    description:
      "Sibling victimization is more common than peer bullying and is prospectively linked to depression, anxiety and self-harm, so it is not just noise. Programs that teach children perspective-taking and problem-solving with their siblings (More Fun with Sisters and Brothers, Siblings Are Special) improved sibling relationships and reduced problem behaviors in trials, and studies of parents show that coaching children through a conflict works better for older children than imposing a solution. Effects are moderate and require sustained practice.",
    action: "For the next month, when a fight starts, stay neutral and walk both children through the same three steps (each says what they want, they propose two solutions, they pick one); run a 20-minute cooperative sibling activity three times a week.",
    sources: [
      { cite: "Kramer, L., & Radey, C. (1997). Improving Sibling Relationships among Young Children: A Social Skills Training Model. Family Relations, 46(3), 237.", note: "A social-skills training program for young siblings improved sibling relationship quality compared with controls.", link: doi("10.2307/585121"), kind: "doi" },
      { cite: "Kramer, L., Perozynski, L. A., & Chung, T. Y. (1999). Parental Responses to Sibling Conflict: The Effects of Development and Parent Gender. Child Development, 70(6), 1401-1414.", note: "Parents' responses to sibling conflict: coaching-style intervention was more effective with older children, while control worked only with very young ones.", link: doi("10.1111/1467-8624.00102"), kind: "doi" },
      { cite: "Feinberg, M. E., Solmeyer, A. R., Hostetler, M. L., Sakuma, K. L., Jones, D., & McHale, S. M. (2012). Siblings are special: initial test of a new approach for preventing youth behavior problems. The Journal of adolescent health : official publication of the Society for Adolescent Medicine, 53(2), 166-73.", note: "Initial randomized test of Siblings Are Special: the program improved sibling relationships and reduced youth problem behaviors.", link: doi("10.1016/j.jadohealth.2012.10.004"), kind: "doi" },
      { cite: "Tucker, C. J., Finkelhor, D., Shattuck, A. M., & Turner, H. (2013). Prevalence and correlates of sibling victimization types. Child abuse & neglect, 37(4), 213-23.", note: "National survey: sibling victimization was prevalent across types and associated with worse mental health in children and adolescents.", link: doi("10.1016/j.chiabu.2013.01.006"), kind: "doi" },
      { cite: "Wolke, D., Tippett, N., & Dantchev, S. (2015). Bullying in the family: sibling bullying. The lancet. Psychiatry, 2(10), 917-29.", note: "Review of sibling bullying: it is common, often overlooked, and linked to later mental health problems.", link: doi("10.1016/S2215-0366(15)00262-X"), kind: "doi" },
      { cite: "Bowes, L., Wolke, D., Joinson, C., Lereya, S. T., & Lewis, G. (2014). Sibling bullying and risk of depression, anxiety, and self-harm: a prospective cohort study. Pediatrics, 134(4), e1032-9.", note: "Prospective cohort: being bullied by a sibling at 12 predicted depression, anxiety and self-harm at 18.", link: doi("10.1542/peds.2014-0832"), kind: "doi" },
    ],
  },
  {
    id: "gs-parenting-w2-bullying-prevention",
    goal: "parenting", tier: "elite", section: "8161",
    title: "Whole-School Bullying Prevention — KiVa, Olweus and What the Meta-Analyses Say",
    subtitle: "School-wide programs cut bullying by a modest but real margin; a parent's leverage is getting one adopted",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "months", durability: "sustained", effort: "high" },
    feeds: ["Child safety at school", "Bystander skills", "School climate"],
    description:
      "Meta-analyses of school-based anti-bullying programs find they reduce bullying perpetration and victimization by roughly a fifth on average, with whole-school, multi-component programs such as Olweus and Finland's KiVa performing best. KiVa's large randomized and nationwide evaluations showed reduced victimization and improved wellbeing. A single family cannot run a school program, so the elite move for a parent is advocacy: getting an evidence-based program adopted and monitored at their child's school, while teaching their own child to report and to support targets.",
    action: "Ask your school which named anti-bullying program it runs and how it measures victimization each year; if the answer is vague, bring the KiVa and Olweus evidence to the PTA and push for adoption of a whole-school program with annual surveys.",
    sources: [
      { cite: "Kärnä, A., Voeten, M., Little, T. D., Poskiparta, E., Kaljonen, A., & Salmivalli, C. (2011). A large-scale evaluation of the KiVa antibullying program: grades 4-6. Child development, 82(1), 311-30.", note: "Large randomized evaluation of KiVa in grades 4-6: the program reduced self-reported victimization and bullying.", link: doi("10.1111/j.1467-8624.2010.01557.x"), kind: "doi" },
      { cite: "Kärnä, A., Voeten, M., Little, T. D., Poskiparta, E., Alanen, E., & Salmivalli, C. (2011). Going to scale: a nonrandomized nationwide trial of the KiVa antibullying program for grades 1-9. Journal of consulting and clinical psychology, 79(6), 796-805.", note: "Nationwide non-randomized KiVa rollout in Finland: reductions in bullying and victimization replicated at scale.", link: doi("10.1037/a0025740"), kind: "doi" },
      { cite: "Williford, A., Boulton, A., Noland, B., Little, T. D., Kärnä, A., & Salmivalli, C. (2012). Effects of the KiVa anti-bullying program on adolescents' depression, anxiety, and perception of peers. Journal of abnormal child psychology, 40(2), 289-300.", note: "KiVa reduced adolescents' depression and anxiety and improved perceptions of peers alongside reductions in bullying.", link: doi("10.1007/s10802-011-9551-1"), kind: "doi" },
      { cite: "Olweus, D. (1994). Bullying at school: basic facts and effects of a school based intervention program. Journal of Child Psychology and Psychiatry, 35(7), 1171-1190.", note: "Olweus's original whole-school intervention in Norway, with substantial reductions in reported bullying.", link: doi("10.1111/j.1469-7610.1994.tb01229.x"), kind: "doi" },
      { cite: "Gaffney, H., Ttofi, M. M., & Farrington, D. P. (2019). Evaluating the effectiveness of school-bullying prevention programs: An updated meta-analytical review. Aggression and Violent Behavior, 45, 111-133.", note: "Updated meta-analysis of school-bullying prevention programs: significant average reductions in perpetration and victimization.", link: doi("10.1016/j.avb.2018.07.001"), kind: "doi" },
      { cite: "Gaffney, H., Ttofi, M. M., & Farrington, D. P. (2021). Effectiveness of school-based programs to reduce bullying perpetration and victimization: An updated systematic review and meta-analysis. Campbell Systematic Reviews, 17(2).", note: "Campbell systematic review and meta-analysis confirming modest but consistent effectiveness of school-based programs.", link: doi("10.1002/cl2.1143"), kind: "doi" },
    ],
  },
  {
    id: "gs-parenting-w2-strengthening-families",
    goal: "parenting", tier: "advanced", section: "8162",
    title: "Family-Based Substance-Use Prevention — Strengthening Families Program 10–14",
    subtitle: "Seven family sessions in early adolescence, with effects on use years later",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "months", durability: "lasting", effort: "moderate" },
    feeds: ["Teen substance use prevention", "Parent-teen communication", "Rules and monitoring"],
    description:
      "The Strengthening Families Program for Parents and Youth 10-14 is a seven-session universal program of joint parent and youth sessions on communication, rules and refusal skills. Randomized school-based trials in Iowa found lower initiation and use of alcohol and other drugs years after the program, including methamphetamine, and a Cochrane review of universal family programs found small but persistent effects on alcohol misuse. The boundary: effects are modest per family and depend on attending most sessions.",
    action: "When your child is 10 to 14, find a local Strengthening Families 10-14 series (often run through extension offices, schools or community agencies) and attend all seven sessions together; if none exists, adopt its core habits: a weekly family meeting, clear substance rules stated before they are tested, and practiced refusal lines.",
    sources: [
      { cite: "Spoth, R., Redmond, C., Shin, C., & Azevedo, K. (2004). Brief Family Intervention Effects on Adolescent Substance Initiation: School-Level Growth Curve Analyses 6 Years Following Baseline. Journal of Consulting and Clinical Psychology, 72(3), 535-542.", note: "Randomized school-level trial: the brief family intervention slowed adolescent substance initiation over six years.", link: doi("10.1037/0022-006x.72.3.535"), kind: "doi" },
      { cite: "Spoth, R. L., Clair, S., Shin, C., & Redmond, C. (2006). Long-term effects of universal preventive interventions on methamphetamine use among adolescents. Archives of Pediatrics & Adolescent Medicine, 160(9), 876-882.", note: "Two randomized prevention trials: family-focused programs reduced adolescent methamphetamine use years after the intervention.", link: doi("10.1001/archpedi.160.9.876"), kind: "doi" },
      { cite: "Foxcroft, D. R., & Tsertsvadze, A. (2011). Universal family-based prevention programs for alcohol misuse in young people. The Cochrane database of systematic reviews, CD009308.", note: "Cochrane review of universal family-based programs: small but generally consistent reductions in alcohol misuse among young people.", link: doi("10.1002/14651858.CD009308"), kind: "doi" },
    ],
  },
  {
    id: "gs-parenting-w2-teen-driving",
    goal: "parenting", tier: "advanced", section: "8163",
    title: "Teen Driving — Graduated Licensing Plus a Parent-Teen Driving Agreement",
    subtitle: "Licensing stages cut fatal crashes; parent-imposed limits add protection in the first year",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "months", durability: "sustained", effort: "moderate" },
    feeds: ["Teen crash risk", "Parent monitoring", "Clear expectations"],
    description:
      "Graduated driver licensing, which staggers unsupervised, night and passenger driving, is associated with fewer fatal crashes among 16-year-olds in national analyses and a Cochrane review. The Checkpoints program, tested in randomized trials, used persuasive materials and a written parent-teen driving agreement to get parents to impose stricter limits; teens reported less risky driving and fewer violations, though crash effects were not significant. Both work by keeping new drivers out of the highest-risk conditions during the first months of licensure.",
    action: "Before your teen's license, write and sign a driving agreement that starts strict (no night driving, no teen passengers, no phone) and loosens in stages every three months of clean driving; review it at each stage.",
    sources: [
      { cite: "Masten, S. V., Foss, R. D., & Marshall, S. W. (2011). Graduated Driver Licensing and Fatal Crashes Involving 16- to 19-Year-Old Drivers. JAMA, 306(10), 1098.", note: "National analysis: stronger graduated licensing programs were associated with fewer fatal crashes among 16-year-old drivers.", link: doi("10.1001/jama.2011.1277"), kind: "doi" },
      { cite: "Russell, K. F., Vandermeer, B., & Hartling, L. (2011). Graduated driver licensing for reducing motor vehicle crashes among young drivers. The Cochrane database of systematic reviews, 2011(10), CD003300.", note: "Cochrane review: graduated driver licensing was associated with reductions in crash rates among young drivers.", link: doi("10.1002/14651858.CD003300.pub3"), kind: "doi" },
      { cite: "Shope, J. T. (2007). Graduated driver licensing: review of evaluation results since 2002. Journal of safety research, 38(2), 165-75.", note: "Review of evaluations since 2002: graduated licensing consistently reduced novice teen crashes.", link: doi("10.1016/j.jsr.2007.02.004"), kind: "doi" },
      { cite: "Hedlund, J. (2007). Novice teen driving: GDL and beyond. Journal of safety research, 38(2), 259-66.", note: "Overview of novice teen driving risk and what remains to be done beyond graduated licensing.", link: doi("10.1016/j.jsr.2007.03.003"), kind: "doi" },
      { cite: "Simons-Morton, B. G., Hartos, J. L., Leaf, W. A., & Preusser, D. F. (2006). The effect on teen driving outcomes of the Checkpoints Program in a state-wide trial. Accident Analysis & Prevention, 38(5), 907-912.", note: "Statewide randomized trial of Checkpoints in 3,743 families: greater parent limits, less risky driving and fewer violations, with no significant effect on crashes.", link: doi("10.1016/j.aap.2006.03.001"), kind: "doi" },
      { cite: "Simons-Morton, B. G., Hartos, J. L., Leaf, W. A., & Preusser, D. F. (2005). Persistence of effects of the Checkpoints program on parental restrictions of teen driving privileges. American Journal of Public Health, 95(3), 447-452.", note: "Randomized trial: Checkpoints families kept stricter driving limits through 12 months after licensure.", link: doi("10.2105/AJPH.2003.023127"), kind: "doi" },
      { cite: "Simons-Morton, B. G., Hartos, J. L., Leaf, W. A., & Preusser, D. F. (2006). The effects of the checkpoints program on parent-imposed driving limits and crash outcomes among Connecticut novice teen drivers at 6-months post-licensure. Journal of Safety Research, 37(1), 9-15.", note: "Six-month outcomes of the Checkpoints trial: stronger parent-imposed limits, though not enough to change crashes or violations by then.", link: doi("10.1016/j.jsr.2005.10.015"), kind: "doi" },
    ],
  },
  {
    id: "gs-parenting-w2-tools-of-the-mind",
    goal: "parenting", tier: "moderate", section: "8164",
    title: "Self-Regulation Curricula — Tools of the Mind, Honestly Rated",
    subtitle: "Some trials show gains in executive function; others show none — it depends on implementation",
    evidenceTag: "Mixed",
    impact: { magnitude: 2, latency: "months", durability: "sustained", effort: "moderate" },
    callout: "Evidence is genuinely mixed: strong randomized trials in kindergarten found benefits, while a large randomized preschool trial found no advantage over comparison classrooms. Treat it as promising, not proven.",
    feeds: ["Executive function", "Classroom self-regulation", "Play-based learning"],
    description:
      "Tools of the Mind is a play-based curriculum designed to build executive function through structured make-believe play and self-regulation routines. An early study and a large cluster-randomized kindergarten trial reported gains in cognitive control, stress physiology and academic skills, but a randomized preschool trial by an independent team found no advantage, and the developers' own research suggests effects depend on implementation quality. Parents can borrow its core practices at home without waiting for the verdict.",
    action: "Borrow the mechanism at home: before pretend play, have your child plan the role and story out loud, use a simple visual plan for routines, and play games that require stopping and switching (freeze dance, Simon Says) most days for a month.",
    sources: [
      { cite: "Diamond, A., Barnett, W. S., Thomas, J., & Munro, S. (2007). Preschool program improves cognitive control. Science (New York, N.Y.), 318(5855), 1387-8.", note: "Early evaluation: preschoolers in Tools of the Mind classrooms outperformed controls on executive-function tasks.", link: doi("10.1126/science.1151148"), kind: "doi" },
      { cite: "Blair, C., & Raver, C. C. (2014). Closing the achievement gap through modification of neurocognitive and neuroendocrine function: results from a cluster randomized controlled trial of an innovative approach to the education of children in kindergarten. PloS one, 9(11), e112393.", note: "Cluster-randomized kindergarten trial: improvements in executive function, stress response and academic outcomes, largest in high-poverty schools.", link: doi("10.1371/journal.pone.0112393"), kind: "doi" },
      { cite: "Diamond, A., Lee, C., Senften, P., Lam, A., & Abbott, D. (2019). Randomized control trial of Tools of the Mind: Marked benefits to kindergarten children and their teachers. PloS one, 14(9), e0222447.", note: "Randomized kindergarten trial reporting marked benefits for children and teachers across academic and social measures.", link: doi("10.1371/journal.pone.0222447"), kind: "doi" },
      { cite: "Nesbitt, K. T., & Farran, D. C. (2021). Effects of Prekindergarten Curricula: Tools of the Mind as a Case Study. Monographs of the Society for Research in Child Development, 86(1), 7-119.", note: "Monograph on prekindergarten curricula using Tools of the Mind as the case study, including the null findings from an independent randomized preschool trial.", link: doi("10.1111/mono.12425"), kind: "doi" },
    ],
  },
  {
    id: "gs-parenting-w2-dialogic-reading",
    goal: "parenting", tier: "fundamental", section: "8165",
    title: "Shared and Dialogic Reading",
    subtitle: "Reading together builds language; asking questions while you read builds it faster",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "weeks", durability: "lasting", effort: "low" },
    feeds: ["Vocabulary and expressive language", "Reading readiness", "Daily bonding ritual"],
    description:
      "Meta-analyses find that shared book reading in the preschool years predicts language and later reading, and that dialogic reading, in which the adult prompts the child to talk about the pictures and story, adds to ordinary reading, with the largest gains for younger children. The original randomized study trained parents for a month and saw measurable expressive-language gains. Clinic-based programs that give books and coaching at pediatric visits show the practice can be spread cheaply.",
    action: "Read with your child every day, and on at least half the pages turn it into a conversation: ask what is happening, expand what they say, and let them 'read' the book back to you; keep the habit through the early school years.",
    sources: [
      { cite: "Whitehurst, G. J., Falco, F. L., Lonigan, C. J., Fischel, J. E., DeBaryshe, B. D., Valdez-Menchaca, M. C., & Caulfield, M. (1988). Accelerating language development through picture book reading. Developmental Psychology, 24(4), 552-559.", note: "Original randomized study: a month of parent training in dialogic picture-book reading accelerated toddlers' expressive language.", link: doi("10.1037/0012-1649.24.4.552"), kind: "doi" },
      { cite: "Bus, A. G., van IJzendoorn, M. H., & Pellegrini, A. D. (1995). Joint Book Reading Makes for Success in Learning to Read: A Meta-Analysis on Intergenerational Transmission of Literacy. Review of Educational Research, 65(1), 1.", note: "Meta-analysis on the intergenerational transmission of literacy: joint book reading was associated with language growth and later reading success.", link: doi("10.2307/1170476"), kind: "doi" },
      { cite: "Mol, S. E., Bus, A. G., de Jong, M. T., & Smeets, D. J. H. (2008). Added Value of Dialogic Parent-Child Book Readings: A Meta-Analysis. Early Education and Development, 19(1), 7-26.", note: "Meta-analysis: dialogic reading added value over standard shared reading for expressive vocabulary, especially for younger children.", link: doi("10.1080/10409280701838603"), kind: "doi" },
      { cite: "Noble, C., Sala, G., Peter, M., Lingwood, J., Rowland, C., Gobet, F., & Pine, J. (2019). The impact of shared book reading on children's language skills: A meta-analysis. Educational Research Review, 28, 100290.", note: "Updated meta-analysis: shared book reading interventions improved children's language skills, with smaller effects in the best-controlled studies.", link: doi("10.1016/j.edurev.2019.100290"), kind: "doi" },
      { cite: "Mendelsohn, A. L., Mogilner, L. N., Dreyer, B. P., Forman, J. A., Weinstein, S. C., Broderick, M., & … Napier, C. (2001). The impact of a clinic-based literacy intervention on language development in inner-city preschool children. Pediatrics, 107(1), 130-134.", note: "Clinic-based literacy program (Reach Out and Read): exposure was associated with more parent-child reading and higher receptive and expressive language.", link: doi("10.1542/peds.107.1.130"), kind: "doi" },
    ],
  },
  {
    id: "gs-parenting-w2-nature-time",
    goal: "parenting", tier: "fundamental", section: "8166",
    title: "Nature Time for Children",
    subtitle: "Green settings improve attention in the short term and track with mental health over years",
    evidenceTag: "Moderate",
    impact: { magnitude: 2, latency: "days", durability: "sustained", effort: "low" },
    feeds: ["Attention and self-regulation", "Mood", "Physical activity"],
    description:
      "A controlled crossover study found children with ADHD concentrated better after a 20-minute walk in a park than after equivalent walks in built settings, and a national survey found after-school activities in green settings reduced symptoms. Population studies link residential green space in childhood to cognitive development and lower later psychiatric risk, and a systematic review finds mostly positive but heterogeneous associations with children's mental health. Causal evidence is strongest for short-term attention; the long-term links are observational.",
    action: "Build one daily outdoor window of at least 20 minutes in the greenest place you can reach (a park, a trail, a yard with trees) and one longer weekend nature outing, and use the park walk deliberately before homework on hard days.",
    sources: [
      { cite: "Kuo, F. E., & Taylor, A. F. (2004). A potential natural treatment for attention-deficit/hyperactivity disorder: evidence from a national study. American journal of public health, 94(9), 1580-6.", note: "National survey of parents of children with ADHD: activities in green outdoor settings were associated with milder symptoms.", link: doi("10.2105/ajph.94.9.1580"), kind: "doi" },
      { cite: "Taylor, A. F., & Kuo, F. E. (2009). Children with attention deficits concentrate better after walk in the park. Journal of Attention Disorders, 12(5), 402-409.", note: "Single-blind crossover trial with 17 children with ADHD: concentration was better after a park walk than after downtown or neighborhood walks, with effect sizes of .52 and .77.", link: doi("10.1177/1087054708323000"), kind: "doi" },
      { cite: "Dadvand, P., Nieuwenhuijsen, M. J., Esnaola, M., Forns, J., Basagaña, X., Alvarez-Pedrerol, M., & … Sunyer, J. (2015). Green spaces and cognitive development in primary schoolchildren. Proceedings of the National Academy of Sciences of the United States of America, 112(26), 7937-42.", note: "Cohort of primary schoolchildren: greenness around schools was associated with better cognitive development over a year.", link: doi("10.1073/pnas.1503402112"), kind: "doi" },
      { cite: "Engemann, K., Pedersen, C. B., Arge, L., Tsirogiannis, C., Mortensen, P. B., & Svenning, J. C. (2019). Residential green space in childhood is associated with lower risk of psychiatric disorders from adolescence into adulthood. Proceedings of the National Academy of Sciences of the United States of America, 116(11), 5188-5193.", note: "Danish national data: more residential green space in childhood was associated with lower risk of psychiatric disorders into adulthood.", link: doi("10.1073/pnas.1807504116"), kind: "doi" },
      { cite: "Tillmann, S., Tobin, D., Avison, W., & Gilliland, J. (2018). Mental health benefits of interactions with nature in children and teenagers: a systematic review. Journal of Epidemiology and Community Health.", note: "Systematic review of nature and mental health in children and teenagers: mostly positive associations across diverse study designs.", link: doi("10.1136/jech-2018-210436"), kind: "doi" },
    ],
  },
  {
    id: "gs-parenting-w2-child-anxiety",
    goal: "parenting", tier: "advanced", section: "8167",
    title: "Child Anxiety — Cool Kids and Parent-Led CBT",
    subtitle: "CBT works for childhood anxiety, and parents can deliver much of it with guidance",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "weeks", durability: "lasting", effort: "moderate" },
    feeds: ["Child anxiety recovery", "Parent coaching skills", "Early intervention"],
    description:
      "Cognitive behavioral therapy is an established treatment for childhood anxiety disorders: the Cochrane review finds it roughly doubles remission versus waiting lists. Randomized trials show that guided parent-delivered CBT, where parents work through a book with brief clinician support, and the Cool Kids program are effective, and that an early parent program for inhibited preschoolers reduced later anxiety. Parent-led formats are cheaper and less stigmatizing, though children with severe or complex presentations still need clinician-led care.",
    action: "If your child's worries limit school, sleep or friendships, ask for a CBT-based program (Cool Kids or guided parent-delivered CBT) rather than waiting; commit to eight to twelve weeks of graded practice at home with the exposure steps written down.",
    sources: [
      { cite: "James, A. C., Reardon, T., Soler, A., James, G., & Creswell, C. (2020). Cognitive behavioural therapy for anxiety disorders in children and adolescents. The Cochrane database of systematic reviews, 11(11), CD013162.", note: "Cochrane review: CBT increased remission of childhood anxiety disorders compared with waitlist, across delivery formats.", link: doi("10.1002/14651858.CD013162.pub2"), kind: "doi" },
      { cite: "Thirlwall, K., Cooper, P. J., Karalus, J., Voysey, M., Willetts, L., & Creswell, C. (2013). Treatment of child anxiety disorders via guided parent-delivered cognitive-behavioural therapy: randomised controlled trial. The British journal of psychiatry : the journal of mental science, 203(6), 436-44.", note: "Randomized trial: guided parent-delivered CBT with brief therapist contact produced recovery rates comparable to more intensive treatment.", link: doi("10.1192/bjp.bp.113.126698"), kind: "doi" },
      { cite: "Kendall, P. C., Hudson, J. L., Gosch, E., Flannery-Schroeder, E., & Suveg, C. (2008). Cognitive-behavioral therapy for anxiety disordered youth: a randomized clinical trial evaluating child and family modalities. Journal of consulting and clinical psychology, 76(2), 282-97.", note: "Randomized trial of child- and family-focused CBT for anxious youth: both active treatments outperformed the control condition.", link: doi("10.1037/0022-006X.76.2.282"), kind: "doi" },
      { cite: "Rapee, R. M., Abbott, M. J., & Lyneham, H. J. (2006). Bibliotherapy for children with anxiety disorders using written materials for parents: A randomized controlled trial. Journal of consulting and clinical psychology, 74(3), 436-44.", note: "Randomized trial: bibliotherapy for parents produced clinically meaningful improvement in children's anxiety, though less than clinician-led treatment.", link: doi("10.1037/0022-006X.74.3.436"), kind: "doi" },
      { cite: "Rapee, R. M., Kennedy, S., Ingram, M., Edwards, S., & Sweeney, L. (2005). Prevention and early intervention of anxiety disorders in inhibited preschool children. Journal of consulting and clinical psychology, 73(3), 488-97.", note: "Brief parent program for inhibited preschoolers reduced anxiety diagnoses at 12-month follow-up.", link: doi("10.1037/0022-006X.73.3.488"), kind: "doi" },
      { cite: "Arendt, K., Thastum, M., & Hougaard, E. (2015). Efficacy of a Danish version of the Cool Kids program: a randomized wait-list controlled trial. Acta psychiatrica Scandinavica, 133(2), 109-121.", note: "Randomized wait-list controlled trial of the Danish Cool Kids program: significant reductions in child anxiety.", link: doi("10.1111/acps.12448"), kind: "doi" },
    ],
  },
  {
    id: "gs-parenting-w2-rituals-vacations",
    goal: "parenting", tier: "fundamental", section: "8168",
    title: "Positive Memories — Family Rituals, Meals and Vacations",
    subtitle: "Predictable routines and shared leisure are associated with cohesion and adolescent wellbeing",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "weeks", durability: "lasting", effort: "low" },
    feeds: ["Family cohesion", "Adolescent wellbeing", "A bank of positive childhood experiences"],
    description:
      "Fifty years of research find that family routines and rituals are associated with children's adjustment and family cohesion, and regular family meals track with better adolescent psychosocial outcomes. Studies of family leisure and vacations link shared core and balance activities to perceived family functioning, and positive childhood experiences predict adult mental and relational health even after adversity. Almost all of this is correlational; what it justifies is protecting a few predictable shared rituals rather than buying bigger trips.",
    action: "Fix three rituals for the next year and defend them on the calendar: a family meal most nights, one weekly low-cost outing, and one annual trip with a repeated element your children can count on; let the children own one part of each.",
    sources: [
      { cite: "Fiese, B. H., Tomcho, T. J., Douglas, M., Josephs, K., Poltrock, S., & Baker, T. (2002). A review of 50 years of research on naturally occurring family routines and rituals: cause for celebration?. Journal of family psychology : JFP : journal of the Division of Family Psychology of the American Psychological Association (Division 43), 16(4), 381-90.", note: "Review of 50 years of research: family routines and rituals were associated with marital satisfaction, children's health and adolescent identity.", link: doi("10.1037//0893-3200.16.4.381"), kind: "doi" },
      { cite: "Spagnola, M., & Fiese, B. H. (2007). Family Routines and Rituals. Infants & Young Children, 20(4), 284-299.", note: "Family routines and rituals as a developmental context for young children, with implications for language, social and emotional growth.", link: doi("10.1097/01.iyc.0000290352.32170.5a"), kind: "doi" },
      { cite: "Eisenberg, M. E., Olson, R. E., Neumark-Sztainer, D., Story, M., & Bearinger, L. H. (2004). Correlations between family meals and psychosocial well-being among adolescents. Archives of pediatrics & adolescent medicine, 158(8), 792-6.", note: "Survey of adolescents: more frequent family meals were associated with better psychosocial wellbeing and fewer risk behaviors.", link: doi("10.1001/archpedi.158.8.792"), kind: "doi" },
      { cite: "Bethell, C., Jones, J., Gombojav, N., Linkenbach, J., & Sege, R. (2019). Positive Childhood Experiences and Adult Mental and Relational Health in a Statewide Sample: Associations Across Adverse Childhood Experiences Levels. JAMA pediatrics, 173(11), e193007.", note: "Statewide sample: positive childhood experiences were associated with better adult mental and relational health across levels of adversity.", link: doi("10.1001/jamapediatrics.2019.3007"), kind: "doi" },
      { cite: "Zabriskie, R. B., & McCormick, B. P. (2001). The Influences of Family Leisure Patterns on Perceptions of Family Functioning. Family Relations, 50(3), 281-289.", note: "Family leisure patterns (core and balance activities) were associated with perceptions of family cohesion and adaptability.", link: doi("10.1111/j.1741-3729.2001.00281.x"), kind: "doi" },
      { cite: "Lehto, X. Y., Choi, S., Lin, Y. C., & MacDermid, S. M. (2009). Vacation and Family Functioning. Annals of Tourism Research, 36(3), 459-479.", note: "Vacation study: shared family travel was associated with communication, cohesion and family functioning.", link: doi("10.1016/j.annals.2009.04.003"), kind: "doi" },
      { cite: "Durko, A. M., & Petrick, J. F. (2013). Family and Relationship Benefits of Travel Experiences. Journal of Travel Research, 52(6), 720-730.", note: "Literature review of the family and relationship benefits of travel experiences.", link: doi("10.1177/0047287513496478"), kind: "doi" },
    ],
  },
  {
    id: "gs-parenting-w2-corporal-punishment",
    goal: "parenting", tier: "fundamental", section: "8169",
    title: "Spanking and Corporal Punishment — What the Meta-Analyses Show",
    subtitle: "No evidence of benefit; consistent links to worse behavior and mental health",
    evidenceTag: "Strong",
    impact: { magnitude: 1, latency: "weeks", durability: "lasting", effort: "low" },
    callout: "Rated at the floor because the evidence does not support the practice: across meta-analyses and prospective studies, spanking is associated with more, not less, child aggression and worse mental health, and the one meta-analysis arguing for conditional spanking finds at most small differences from alternatives.",
    feeds: ["Non-violent discipline", "Child mental health", "Parent-child trust"],
    description:
      "Gershoff's meta-analyses of hundreds of effect sizes find parental corporal punishment is associated with more aggression, more antisocial behavior and worse mental health, and not with better long-term compliance; a stronger-causal analysis using matched samples in a national cohort reached the same conclusion. Critics who reanalyzed the data (Ferguson) found the associations smaller but still not favorable, and a Lancet narrative review of prospective studies found the association with worse outcomes across countries. The honest verdict is that spanking has no measurable benefit over non-violent discipline and carries real risks.",
    action: "Retire spanking entirely and replace it with a written discipline plan you both use: state the rule before it is tested, give one calm warning, and apply a short, immediate, non-physical consequence (time-out for young children, a lost privilege for older ones) every time.",
    sources: [
      { cite: "Gershoff, E. T. (2002). Corporal punishment by parents and associated child behaviors and experiences: a meta-analytic and theoretical review. Psychological bulletin, 128(4), 539-79.", note: "Meta-analytic review of 88 studies: corporal punishment was associated with immediate compliance but also with aggression, delinquency and worse mental health.", link: doi("10.1037/0033-2909.128.4.539"), kind: "doi" },
      { cite: "Gershoff, E. T., & Grogan-Kaylor, A. (2016). Spanking and child outcomes: Old controversies and new meta-analyses. Journal of family psychology : JFP : journal of the Division of Family Psychology of the American Psychological Association (Division 43), 30(4), 453-69.", note: "Updated meta-analyses isolating spanking from harsher punishment: spanking was associated with detrimental child outcomes and not with compliance.", link: doi("10.1037/fam0000191"), kind: "doi" },
      { cite: "Gershoff, E. T., Sattler, K. M. P., & Ansari, A. (2017). Strengthening Causal Estimates for Links Between Spanking and Children's Externalizing Behavior Problems. Psychological science, 29(1), 110-120.", note: "Propensity-matched analysis of a national cohort strengthened causal estimates linking spanking to later externalizing problems.", link: doi("10.1177/0956797617729816"), kind: "doi" },
      { cite: "Ferguson, C. J. (2013). Spanking, corporal punishment and negative long-term outcomes: a meta-analytic review of longitudinal studies. Clinical psychology review, 33(1), 196-208.", note: "Critical meta-analysis of longitudinal studies: effects were smaller than earlier estimates but remained unfavorable to spanking.", link: doi("10.1016/j.cpr.2012.11.002"), kind: "doi" },
      { cite: "Larzelere, R. E., & Kuhn, B. R. (2005). Comparing child outcomes of physical punishment and alternative disciplinary tactics: a meta-analysis. Clinical child and family psychology review, 8(1), 1-37.", note: "Meta-analysis comparing physical punishment with alternatives: only conditional, mild spanking compared neutrally; harsher forms compared worse.", link: doi("10.1007/s10567-005-2340-z"), kind: "doi" },
      { cite: "Heilmann, A., Mehay, A., Watt, R. G., Kelly, Y., Durrant, J. E., van Turnhout, J., & Gershoff, E. T. (2021). Physical punishment and child outcomes: a narrative review of prospective studies. Lancet (London, England), 398(10297), 355-364.", note: "Lancet narrative review of prospective studies: physical punishment was consistently associated with worse child outcomes and no benefits.", link: doi("10.1016/S0140-6736(21)00582-1"), kind: "doi" },
    ],
  },
];
