// Goal shelf: RETIREMENT — wave 2 (sections 8450–8469). Widens the wave-1 retirement shelf.
// Verification: every DOI below was resolved against the Crossref record
// (api.crossref.org) on 2026-09-11. See ../types.ts for the contract.
import { doi, type GoalShelfCluster } from "../types";

export const SECTIONS: Record<string, string> = {
  "8450": "Medicare Plan Choice — Re-Shop Every Year",
  "8451": "Health Insurance Before Medicare & Retirement Timing",
  "8452": "Health Savings Accounts",
  "8453": "Relocation, Downsizing & Housing Wealth",
  "8454": "Bridge Employment & Part-Time Work",
  "8455": "Grandparenting in Retirement",
  "8456": "Loneliness After Retirement",
  "8457": "Marriage in Retirement",
  "8458": "Volunteering & Experience Corps",
  "8459": "Lifelong Learning & Sustained Engagement",
  "8460": "Lump Sum vs Annuity",
  "8461": "Target-Date Funds as the Default",
  "8462": "Robo-Advisors — Honest Evidence",
  "8463": "Tax-Loss Harvesting",
  "8464": "Withdrawal Sequencing, RMDs & Charitable Distributions",
  "8465": "Elder Financial Exploitation — Prevention",
  "8466": "Cognitive Decline & Financial Capacity",
  "8467": "Advance Directives & Powers of Attorney",
  "8468": "Identity, Purpose & the Retirement Transition",
  "8469": "Retire Early (FIRE) — Honest Verdict on Health",
};

export const CLUSTERS: GoalShelfCluster[] = [
  {
    id: "gs-retirement-w2-medicare-choice",
    goal: "retirement", tier: "moderate", section: "8450",
    title: "Re-Shop Your Medicare Drug and Advantage Plan Every Open Enrollment",
    subtitle: "Most beneficiaries leave money on the table by staying in last year's plan",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "weeks", durability: "sustained", effort: "moderate" },
    feeds: ["Out-of-pocket cost", "Decision quality"],
    description:
      "Studies of Medicare Part D choices find that beneficiaries systematically choose plans that cost more than the cheapest option for their own prescriptions, overweight premiums relative to expected out-of-pocket costs, and rarely switch even when a better plan exists. A randomized experiment showed that simply mailing people a personalized comparison of plan costs increased switching and lowered spending — the friction is comparison, not availability. The boundary: some studies show people learn and improve over time, and the cheapest plan is not always the right plan if it drops a needed drug or doctor.",
    action: "Each October, enter your actual prescriptions and pharmacies into the official plan-finder tool, compare total annual cost (premium plus expected out-of-pocket) for the top three plans, and switch if the saving exceeds the hassle; ask a SHIP counselor if you are unsure.",
    sources: [
      { cite: "Abaluck, J., & Gruber, J. (2011). Choice inconsistencies among the elderly: Evidence from plan choice in the Medicare Part D program. American Economic Review, 101(4), 1180–1210.", note: "Beneficiaries placed far more weight on premiums than on expected out-of-pocket costs and often chose plans dominated by cheaper alternatives for their own drug use.", link: doi("10.1257/aer.101.4.1180"), kind: "doi" },
      { cite: "Ketcham, J. D., Lucarelli, C., Miravete, E. J., & Roebuck, M. C. (2012). Sinking, swimming, or learning to swim in Medicare Part D. American Economic Review, 102(6), 2639–2673.", note: "Tracked beneficiaries over time and found overspending fell as people switched plans, with the largest improvements among those who had overspent most — re-shopping works.", link: doi("10.1257/aer.102.6.2639"), kind: "doi" },
      { cite: "Ketcham, J. D., Lucarelli, C., & Powers, C. A. (2015). Paying attention or paying too much in Medicare Part D. American Economic Review, 105(1), 204–233.", note: "Beneficiaries who paid attention and switched reduced their costs; inattention, not lack of options, explained persistent overpayment.", link: doi("10.1257/aer.20120651"), kind: "doi" },
      { cite: "Kling, J. R., Mullainathan, S., Shafir, E., Vermeulen, L. C., & Wrobel, M. V. (2012). Comparison friction: Experimental evidence from Medicare drug plans. The Quarterly Journal of Economics, 127(1), 199–235.", note: "A randomized mailing of personalized plan-cost comparisons raised plan switching and lowered predicted spending, isolating comparison friction as the barrier.", link: doi("10.1093/qje/qjr055"), kind: "doi" },
      { cite: "Polyakova, M. (2016). Regulation of insurance with adverse selection and switching costs: Evidence from Medicare Part D. American Economic Journal: Applied Economics, 8(3), 165–195.", note: "Estimated substantial switching costs in Part D that keep beneficiaries in plans that no longer fit, a reason to force the annual comparison.", link: doi("10.1257/app.20150004"), kind: "doi" },
    ],
  },
  {
    id: "gs-retirement-w2-pre-medicare-insurance",
    goal: "retirement", tier: "advanced", section: "8451",
    title: "Solve the Pre-65 Health Insurance Gap Before Choosing a Retirement Date",
    subtitle: "Insurance access is one of the strongest determinants of when people actually retire",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "months", durability: "lasting", effort: "high" },
    feeds: ["Retirement timing", "Financial security", "Health-care access"],
    description:
      "Structural and quasi-experimental studies show that Medicare eligibility and the availability of retiree health insurance strongly shape retirement timing: people with employer-provided retiree coverage retire earlier, and those without it work until 65. Simulations show that the value of health coverage before Medicare is large relative to other retirement incentives. The boundary: these studies predate or only partly reflect the marketplace subsidies now available; the practical rule is to price the gap explicitly before setting a date.",
    action: "Before setting a retirement date earlier than 65, get written quotes for coverage through your spouse's plan, COBRA, and the marketplace (with subsidy estimates based on your projected retirement income) and put the annual cost as a line item in your retirement budget.",
    sources: [
      { cite: "Rust, J., & Phelan, C. (1997). How Social Security and Medicare affect retirement behavior in a world of incomplete markets. Econometrica, 65(4), 781–831.", note: "A structural model showed that lack of private health insurance before Medicare eligibility keeps workers on the job until 65, explaining the spike in retirements at that age.", link: doi("10.2307/2171940"), kind: "doi" },
      { cite: "Madrian, B. C., Burtless, G., & Gruber, J. (1994). The effect of health insurance on retirement. Brookings Papers on Economic Activity, 1994(1), 181–252.", note: "Retiree health insurance availability was associated with earlier retirement, quantifying how much coverage matters for the retirement decision.", link: doi("10.2307/2534632"), kind: "doi" },
      { cite: "Nyce, S., Schieber, S. J., Shoven, J. B., Slavov, S. N., & Wise, D. A. (2013). Does retiree health insurance encourage early retirement? Journal of Public Economics, 104, 40–51.", note: "Using employer plan data, retiree health coverage significantly raised the probability of retiring before 65, especially for workers with health problems.", link: doi("10.1016/j.jpubeco.2013.04.007"), kind: "doi" },
      { cite: "Shoven, J. B., & Slavov, S. N. (2014). The role of retiree health insurance in the early retirement of public sector employees. Journal of Health Economics, 38, 99–108.", note: "Public employees with retiree health insurance retired substantially earlier, reinforcing that the pre-65 coverage gap is a binding constraint for many.", link: doi("10.1016/j.jhealeco.2014.03.013"), kind: "doi" },
    ],
  },
  {
    id: "gs-retirement-w2-hsa",
    goal: "retirement", tier: "moderate", section: "8452",
    title: "Use a Health Savings Account as a Long-Horizon Account, Not a Checking Account",
    subtitle: "The tax treatment is unique, but the evidence on high-deductible plans is mixed on care",
    evidenceTag: "Mixed",
    impact: { magnitude: 3, latency: "months", durability: "lasting", effort: "moderate" },
    feeds: ["Tax-advantaged saving", "Retirement health costs"],
    description:
      "Research on consumer-directed health plans finds they reduce health spending, partly by cutting both low-value and some high-value care, and that HSA balances and contributions are concentrated among higher-income households and large employers, with many accounts used as pass-through spending vehicles rather than savings. The unique feature for retirement is the triple tax advantage when contributions are invested and left to grow. The boundary: the evidence supports the account as a savings vehicle for those who can afford to pay current medical costs from cash flow; it does not show high-deductible plans are right for everyone.",
    action: "If you are enrolled in an HSA-eligible plan, set the contribution to the maximum you can afford, invest the balance above a one-deductible cash cushion, and pay routine medical costs from your checking account while saving the receipts.",
    sources: [
      { cite: "Haviland, A. M., Eisenberg, M. D., Mehrotra, A., Huckfeldt, P. J., & Sood, N. (2016). Do 'consumer-directed' health plans bend the cost curve over time? Journal of Health Economics, 46, 33–51.", note: "Firms offering high-deductible, account-based plans saw sustained reductions in health spending over three years, driven by lower utilization including some preventive care.", link: doi("10.1016/j.jhealeco.2016.01.001"), kind: "doi" },
      { cite: "Helmchen, L. A., Brown, D. W., Lurie, I. Z., & Lo Sasso, A. T. (2015). Health savings accounts: Growth concentrated among high-income households and large employers. Health Affairs, 34(9), 1594–1598.", note: "Tax data showed HSA contributions and balances grew fastest among high-income households, indicating the accounts function as tax-advantaged savings mainly for those with slack cash flow.", link: doi("10.1377/hlthaff.2015.0480"), kind: "doi" },
      { cite: "Lo Sasso, A. T., Shah, M., & Frogner, B. K. (2010). Health savings accounts and health care spending. Health Services Research, 45(4), 1041–1060.", note: "Enrollees in HSA-eligible plans had lower spending than comparison enrollees, with account balances influencing how much care was used.", link: doi("10.1111/j.1475-6773.2010.01124.x"), kind: "doi" },
      { cite: "Buntin, M. B., Damberg, C., Haviland, A., Kapur, K., Lurie, N., McDevitt, R., & Marquis, M. S. (2006). Consumer-directed health care: Early evidence about effects on cost and quality. Health Affairs, 25(Suppl 1), w516–w530.", note: "An early review found consumer-directed plans lowered costs but raised concerns about reductions in needed care, the trade-off to weigh before enrolling.", link: doi("10.1377/hlthaff.25.w516"), kind: "doi" },
    ],
  },
  {
    id: "gs-retirement-w2-relocation",
    goal: "retirement", tier: "advanced", section: "8453",
    title: "Decide on Relocation and Downsizing as a Staged Plan, Not a Single Move",
    subtitle: "Most retirees do not tap housing equity until a health or widowhood shock forces it",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "months", durability: "lasting", effort: "high" },
    feeds: ["Housing wealth use", "Social ties", "Later-life care access"],
    description:
      "Longitudinal studies find older households rarely downsize voluntarily; housing equity is typically released only after widowhood, disability, or a move into care, and mobility at older ages is lower in the United States than in Britain. Gerontologists describe three typical late-life moves — an amenity move soon after retirement, a move closer to family when help is needed, and a move into care — and retirement migration transfers income across states. The evidence supports planning the sequence deliberately (where you would go for the second move) rather than treating the first, amenity-driven move as final.",
    action: "Write a two-stage housing plan this year: where you would live for the active decade and where you would move if you needed daily help, including which family members and health systems are within 30 minutes; revisit it every five years or after any health event.",
    sources: [
      { cite: "Venti, S. F., & Wise, D. A. (1991). Aging and the income value of housing wealth. Journal of Public Economics, 44(3), 371–397.", note: "Older US households rarely reduced housing equity as they aged, even when it represented most of their wealth — voluntary downsizing is uncommon.", link: doi("10.1016/0047-2727(91)90020-3"), kind: "doi" },
      { cite: "Banks, J., Blundell, R., Oldfield, Z., & Smith, J. P. (2011). Housing mobility and downsizing at older ages in Britain and the USA. Economica, 79(313), 1–26.", note: "Compared older households in the two countries and found downsizing mostly followed shocks such as widowhood or health decline, with lower mobility in the US.", link: doi("10.1111/j.1468-0335.2011.00878.x"), kind: "doi" },
      { cite: "Litwak, E., & Longino, C. F. (1987). Migration patterns among the elderly: A developmental perspective. The Gerontologist, 27(3), 266–272.", note: "Proposed the three-stage model of late-life moves — amenity, assistance, and institutional — that a staged housing plan is built around.", link: doi("10.1093/geront/27.3.266"), kind: "doi" },
      { cite: "Longino, C. F., & Crown, W. H. (1990). Retirement migration and interstate income transfers. The Gerontologist, 30(6), 784–789.", note: "Documented the scale of interstate retirement migration and the income it moves, showing relocation is a common and financially significant retirement decision.", link: doi("10.1093/geront/30.6.784"), kind: "doi" },
    ],
  },
  {
    id: "gs-retirement-w2-bridge-employment",
    goal: "retirement", tier: "moderate", section: "8454",
    title: "Take a Bridge Job — Part-Time, Chosen, and Ideally in Your Field",
    subtitle: "Voluntary bridge employment predicts better health and life satisfaction; forced work does not",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "months", durability: "sustained", effort: "moderate" },
    feeds: ["Purpose", "Income", "Physical and mental health"],
    description:
      "Longitudinal studies of the Health and Retirement Study find that retirees who take bridge jobs, especially in their career field, report fewer major diseases and functional limitations and better mental health than those who fully retire, after accounting for prior health. Life-satisfaction gains are concentrated among people who chose to work; those forced into retirement recover satisfaction when they find a bridge job, while forced work does not help. The boundary: selection into bridge work is only partly controlled, and the benefits depend on job quality and voluntariness.",
    action: "In the year before or after retiring, line up a part-time role of 10–20 hours a week that uses your existing skills and that you can quit without financial harm; keep it for at least a year before deciding whether to stop.",
    sources: [
      { cite: "Wang, M. (2007). Profiling retirees in the retirement transition and adjustment process: Examining the longitudinal change patterns of retirees' psychological well-being. Journal of Applied Psychology, 92(2), 455–474.", note: "Identified distinct well-being trajectories after retirement; bridge employment and planning were among the factors linked to the stable or improving paths.", link: doi("10.1037/0021-9010.92.2.455"), kind: "doi" },
      { cite: "Kim, S., & Feldman, D. C. (2000). Working in retirement: The antecedents of bridge employment and its consequences for quality of life in retirement. Academy of Management Journal, 43(6), 1195–1210.", note: "Among early retirees, bridge employment was associated with higher retirement and life satisfaction.", link: doi("10.2307/1556345"), kind: "doi" },
      { cite: "Zhan, Y., Wang, M., Liu, S., & Shultz, K. S. (2009). Bridge employment and retirees' health: A longitudinal investigation. Journal of Occupational Health Psychology, 14(4), 374–389.", note: "Retirees in bridge employment reported fewer major diseases and functional limitations than full retirees, with career-field bridge jobs also linked to better mental health.", link: doi("10.1037/a0015285"), kind: "doi" },
      { cite: "Wang, M., Zhan, Y., Liu, S., & Shultz, K. S. (2008). Antecedents of bridge employment: A longitudinal investigation. Journal of Applied Psychology, 93(4), 818–830.", note: "Health, finances and job attitudes predicted who takes bridge jobs, useful for understanding what makes the move feasible.", link: doi("10.1037/0021-9010.93.4.818"), kind: "doi" },
      { cite: "Dingemans, E., & Henkens, K. (2013). Involuntary retirement, bridge employment, and satisfaction with life: A longitudinal investigation. Journal of Organizational Behavior, 35(4), 575–591.", note: "Involuntary retirement lowered life satisfaction, and taking a bridge job restored it — but only for those whose retirement had been forced.", link: doi("10.1002/job.1914"), kind: "doi" },
      { cite: "Beehr, T. A., & Bennett, M. M. (2014). Working after retirement: Features of bridge employment and research directions. Work, Aging and Retirement, 1(1), 112–128.", note: "Reviewed the bridge-employment literature and distinguished the features (voluntariness, fit, hours) that determine whether it helps well-being.", link: doi("10.1093/workar/wau007"), kind: "doi" },
    ],
  },
  {
    id: "gs-retirement-w2-grandparenting",
    goal: "retirement", tier: "fundamental", section: "8455",
    title: "Regular but Bounded Grandchild Care",
    subtitle: "Occasional grandparenting is linked to better health and cognition; custodial care is not",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "months", durability: "sustained", effort: "low" },
    feeds: ["Purpose", "Family bonds", "Cognitive engagement"],
    description:
      "European and US panel studies find that grandparents who provide non-intensive, regular care for grandchildren report better health, fewer depressive symptoms and, in one study, better cognitive functioning than those who provide none, while custodial or very intensive care — especially raising grandchildren in the home — is associated with worse health and more depression. Effects are stronger for grandmothers and depend on prior health and resources. The evidence supports a rhythm of predictable, limited care that the grandparent controls.",
    action: "Agree a fixed, recurring slot (for example one afternoon a week or one overnight a month) for grandchild care that you set and can adjust; if you are being asked to provide daily or live-in care, ask for respite help before your own health slips.",
    sources: [
      { cite: "Di Gessa, G., Glaser, K., & Tinker, A. (2016). The impact of caring for grandchildren on the health of grandparents in Europe: A lifecourse approach. Social Science & Medicine, 152, 166–175.", note: "Across European countries, grandparents providing occasional care had better health than non-carers after adjusting for life-course factors, while intensive care showed no benefit.", link: doi("10.1016/j.socscimed.2016.01.041"), kind: "doi" },
      { cite: "Hughes, M. E., Waite, L. J., LaPierre, T. A., & Luo, Y. (2007). All in the family: The impact of caring for grandchildren on grandparents' health. The Journals of Gerontology Series B, 62(2), S108–S119.", note: "Using the Health and Retirement Study, non-residential grandchild care was not harmful and was linked to some health benefits, whereas raising grandchildren was associated with worse outcomes.", link: doi("10.1093/geronb/62.2.s108"), kind: "doi" },
      { cite: "Luo, Y., LaPierre, T. A., Hughes, M. E., & Waite, L. J. (2012). Grandparents providing care to grandchildren. Journal of Family Issues, 33(9), 1143–1167.", note: "Described the prevalence and patterns of grandparent care in the US and the characteristics distinguishing intensive from occasional carers.", link: doi("10.1177/0192513x12438685"), kind: "doi" },
      { cite: "Arpino, B., & Bordone, V. (2014). Does grandparenting pay off? The effect of child care on grandparents' cognitive functioning. Journal of Marriage and Family, 76(2), 337–351.", note: "Using European survey data, providing grandchild care was associated with better verbal fluency, consistent with cognitive engagement benefits.", link: doi("10.1111/jomf.12096"), kind: "doi" },
      { cite: "Szinovacz, M. E., & Davey, A. (2006). Effects of retirement and grandchild care on depressive symptoms. The International Journal of Aging and Human Development, 62(1), 1–20.", note: "Examined how the combination of retirement and grandchild care affected depressive symptoms, finding effects depended on the intensity and gender of the carer.", link: doi("10.2190/8q46-gjx4-m2vm-w60v"), kind: "doi" },
    ],
  },
  {
    id: "gs-retirement-w2-loneliness",
    goal: "retirement", tier: "fundamental", section: "8456",
    title: "Replace Work Contact Deliberately — Three Standing Social Commitments a Week",
    subtitle: "Loneliness after retirement is a mortality-level risk factor, and it is preventable by structure",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "weeks", durability: "sustained", effort: "low" },
    feeds: ["Social connection", "Mental health", "Longevity"],
    description:
      "Meta-analyses of prospective studies find that loneliness and social isolation raise mortality risk by a magnitude comparable to well-established health risks. Panel studies show loneliness predicts later depressive symptoms independent of other factors, and that the retirement transition changes the loneliness-depression link, with recent work distinguishing social loneliness (fewer contacts) from emotional loneliness. Work supplies incidental contact; retirement removes it. The protocol replaces it with standing commitments rather than intentions.",
    action: "Put three recurring social commitments on your weekly calendar (a class, a volunteer shift, a standing meal or walk with the same people) and treat them as appointments for the first six months of retirement; track attendance, not enjoyment.",
    sources: [
      { cite: "Holt-Lunstad, J., Smith, T. B., Baker, M., Harris, T., & Stephenson, D. (2015). Loneliness and social isolation as risk factors for mortality: A meta-analytic review. Perspectives on Psychological Science, 10(2), 227–237.", note: "Meta-analysis of prospective studies found loneliness, social isolation and living alone each predicted increased mortality.", link: doi("10.1177/1745691614568352"), kind: "doi" },
      { cite: "Holt-Lunstad, J., Smith, T. B., & Layton, J. B. (2010). Social relationships and mortality risk: A meta-analytic review. PLoS Medicine, 7(7), e1000316.", note: "Stronger social relationships were associated with substantially higher survival odds across many cohorts, comparable to major health behaviors.", link: doi("10.1371/journal.pmed.1000316"), kind: "doi" },
      { cite: "Segel-Karpas, D., Ayalon, L., & Lachman, M. E. (2016). Loneliness and depressive symptoms: The moderating role of the transition into retirement. Aging & Mental Health, 22(1), 135–140.", note: "The association between loneliness and depressive symptoms was stronger for people who had transitioned into retirement, making the first years a critical window.", link: doi("10.1080/13607863.2016.1226770"), kind: "doi" },
      { cite: "Cacioppo, J. T., Hughes, M. E., Waite, L. J., Hawkley, L. C., & Thisted, R. A. (2006). Loneliness as a specific risk factor for depressive symptoms: Cross-sectional and longitudinal analyses. Psychology and Aging, 21(1), 140–151.", note: "In a population-based older-adult sample, loneliness predicted later depressive symptoms independent of social support and stress.", link: doi("10.1037/0882-7974.21.1.140"), kind: "doi" },
      { cite: "Bosma, J., Henkens, K., & van Solinge, H. (2025). The differential impact of retirement on social and emotional loneliness. Work, Aging and Retirement.", note: "Distinguished social from emotional loneliness after retirement, showing retirement's main effect runs through lost social contact — which structured commitments replace.", link: doi("10.1093/workar/waaf019"), kind: "doi" },
    ],
  },
  {
    id: "gs-retirement-w2-marriage",
    goal: "retirement", tier: "fundamental", section: "8457",
    title: "Plan Retirement Timing as a Couple and Renegotiate the Household",
    subtitle: "The years right after one spouse retires are the hardest on marital quality",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "months", durability: "sustained", effort: "low" },
    feeds: ["Marital quality", "Retirement adjustment"],
    description:
      "Longitudinal couple studies find that marital quality dips during the transition itself, particularly when one spouse retires while the other keeps working or when spouses retire out of sync, and that depressive symptoms rise when retirement coincides with a spouse's disability. Retirement adjustment differs by gender and by whether the timing was chosen. The evidence supports discussing timing jointly, expecting a rough first year, and explicitly redividing household work and time rather than assuming it will settle.",
    action: "Before either partner retires, hold two conversations: one on timing (retire together, staggered, or one only) and one on the daily division of chores, time apart and time together for the first year; revisit both at the six-month mark.",
    sources: [
      { cite: "Moen, P., Kim, J. E., & Hofmeister, H. (2001). Couples' work/retirement transitions, gender, and marital quality. Social Psychology Quarterly, 64(1), 55–71.", note: "Couples in the midst of retirement transitions reported more marital conflict, especially when one spouse retired and the other continued working.", link: doi("10.2307/3090150"), kind: "doi" },
      { cite: "Szinovacz, M. E., & Davey, A. (2004). Retirement transitions and spouse disability: Effects on depressive symptoms. The Journals of Gerontology Series B, 59(6), S333–S342.", note: "Retirement combined with a spouse's disability raised depressive symptoms, showing that retirement timing interacts with the partner's health.", link: doi("10.1093/geronb/59.6.s333"), kind: "doi" },
      { cite: "Kim, J. E., & Moen, P. (2002). Retirement transitions, gender, and psychological well-being: A life-course, ecological model. The Journals of Gerontology Series B, 57(3), P212–P222.", note: "Well-being after retirement depended on marital quality and the spouse's employment status, differently for men and women.", link: doi("10.1093/geronb/57.3.p212"), kind: "doi" },
      { cite: "Szinovacz, M. E., & Davey, A. (2006). Effects of retirement and grandchild care on depressive symptoms. The International Journal of Aging and Human Development, 62(1), 1–20.", note: "Showed retirement's effect on mood depends on the family context — including care roles — reinforcing the need for couples to plan roles explicitly.", link: doi("10.2190/8q46-gjx4-m2vm-w60v"), kind: "doi" },
    ],
  },
  {
    id: "gs-retirement-w2-volunteering",
    goal: "retirement", tier: "elite", section: "8458",
    title: "High-Commitment Volunteering — the Experience Corps Model",
    subtitle: "Fifteen hours a week tutoring children improved older adults' physical activity, executive function and social ties",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "months", durability: "lasting", effort: "high" },
    feeds: ["Purpose", "Cognition", "Physical activity", "Social connection"],
    description:
      "Experience Corps, a program placing older adults in elementary schools for roughly 15 hours a week, was tested in pilot and randomized trials: volunteers increased physical activity, strength and walking, showed gains in executive function and memory, and expanded social networks relative to controls. Meta-analyses of volunteering more broadly find lower mortality among older volunteers, strongest when motives are other-oriented, though selection effects remain. The boundary: benefits scale with dose and structure; sporadic volunteering shows much smaller effects.",
    action: "Commit to a structured volunteer role of at least 10–15 hours a week for a full school year or program cycle — ideally one with training, a team and a clear beneficiary — and hold it for at least 12 months before judging it.",
    sources: [
      { cite: "Fried, L. P., et al. (2004). A social model for health promotion for an aging population: Initial evidence on the Experience Corps model. Journal of Urban Health, 81(1), 64–78.", note: "The pilot trial found increased physical activity, strength and social engagement among older volunteers placed in schools compared with controls.", link: doi("10.1093/jurban/jth094"), kind: "doi" },
      { cite: "Carlson, M. C., Saczynski, J. S., Rebok, G. W., Seeman, T., Glass, T. A., McGill, S., Tielsch, J., Frick, K. D., Hill, J., & Fried, L. P. (2008). Exploring the effects of an 'everyday' activity program on executive function and memory in older adults: Experience Corps. The Gerontologist, 48(6), 793–801.", note: "Volunteers showed improvements in executive function and memory over the intervention period, with the largest gains among those with poorer baseline function.", link: doi("10.1093/geront/48.6.793"), kind: "doi" },
      { cite: "Tan, E. J., Xue, Q.-L., Li, T., Carlson, M. C., & Fried, L. P. (2006). Volunteering: A physical activity intervention for older adults — The Experience Corps program in Baltimore. Journal of Urban Health, 83(5), 954–969.", note: "Participation increased physical activity and walking among volunteers, including those who were previously inactive.", link: doi("10.1007/s11524-006-9060-7"), kind: "doi" },
      { cite: "Martinez, I. L., Frick, K., Glass, T. A., Carlson, M., Tanner, E., Ricks, M., & Fried, L. P. (2006). Engaging older adults in high impact volunteering that enhances health: Recruitment and retention in the Experience Corps Baltimore. Journal of Urban Health, 83(5), 941–953.", note: "Documented how older adults were recruited and retained in a demanding volunteer role, useful for choosing a program you will actually keep.", link: doi("10.1007/s11524-006-9058-1"), kind: "doi" },
      { cite: "Okun, M. A., Yeung, E. W., & Brown, S. (2013). Volunteering by older adults and risk of mortality: A meta-analysis. Psychology and Aging, 28(2), 564–577.", note: "Meta-analysis found older volunteers had lower mortality risk than non-volunteers after adjustment, though causality cannot be assumed.", link: doi("10.1037/a0031519"), kind: "doi" },
      { cite: "Konrath, S., Fuhrel-Forbis, A., Lou, A., & Brown, S. (2012). Motives for volunteering are associated with mortality risk in older adults. Health Psychology, 31(1), 87–96.", note: "Only volunteering motivated by others' welfare predicted lower mortality; self-oriented motives did not — choose a role where someone depends on you.", link: doi("10.1037/a0025226"), kind: "doi" },
      { cite: "Anderson, N. D., et al. (2014). The benefits associated with volunteering among seniors: A critical review and recommendations for future research. Psychological Bulletin, 140(6), 1505–1533.", note: "Critical review concluded volunteering is associated with reduced depression, better functioning and lower mortality, with a plausible dose-response, while flagging selection limits.", link: doi("10.1037/a0037610"), kind: "doi" },
      { cite: "Jenkinson, C. E., et al. (2013). Is volunteering a public health intervention? A systematic review and meta-analysis of the health and survival of volunteers. BMC Public Health, 13, 773.", note: "Systematic review found volunteering associated with lower depression and mortality in cohort studies, but trials showed weaker effects — structure matters.", link: doi("10.1186/1471-2458-13-773"), kind: "doi" },
    ],
  },
  {
    id: "gs-retirement-w2-lifelong-learning",
    goal: "retirement", tier: "moderate", section: "8459",
    title: "Learn Something Genuinely Hard — a Sustained Skill Course, Not a Lecture Series",
    subtitle: "Cognitive benefits come from demanding, sustained engagement; passive classes mostly bring social benefits",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "months", durability: "sustained", effort: "moderate" },
    feeds: ["Cognition", "Wellbeing", "Social connection"],
    description:
      "A randomized trial assigned older adults to learn demanding new skills (digital photography, quilting) for about 15 hours a week over three months and found memory improvements relative to social or low-demand activities; learning to use a tablet also produced gains. Population studies of lifelong-learning programs find participation is associated with maintained wellbeing and health, particularly for more vulnerable older adults, and economists document cognitive decline after leaving mentally demanding work. The boundary: effects require sustained, effortful novelty; a weekly lecture is good for social contact but shows little cognitive effect.",
    action: "Enroll in a course with graded, cumulative skill demands (a language with a tutor, an instrument, coding, photography with critique) at 5–15 hours a week for at least 12 weeks, through a community college, OLLI or similar program; schedule practice like a job.",
    sources: [
      { cite: "Park, D. C., Lodi-Smith, J., Drew, L., Haber, S., Hebrank, A., Bischof, G. N., & Aamodt, W. (2013). The impact of sustained engagement on cognitive function in older adults: The Synapse Project. Psychological Science, 25(1), 103–112.", note: "Older adults randomized to learn demanding skills for three months improved episodic memory relative to those assigned to social or low-demand activities.", link: doi("10.1177/0956797613499592"), kind: "doi" },
      { cite: "Chan, M. Y., Haber, S., Drew, L. M., & Park, D. C. (2014). Training older adults to use tablet computers: Does it enhance cognitive function? The Gerontologist, 56(3), 475–484.", note: "Ten weeks of tablet training improved processing speed and episodic memory relative to controls, showing that a practical new skill counts.", link: doi("10.1093/geront/gnu057"), kind: "doi" },
      { cite: "Narushima, M., Liu, J., & Diestelkamp, N. (2016). Lifelong learning in active ageing discourse: Its conserving effect on wellbeing, health and vulnerability. Ageing and Society, 38(4), 651–675.", note: "Among older adults in continuing-education programs, sustained participation was associated with maintained psychological wellbeing, especially for those in poorer health.", link: doi("10.1017/s0144686x16001136"), kind: "doi" },
      { cite: "Rohwedder, S., & Willis, R. J. (2010). Mental retirement. Journal of Economic Perspectives, 24(1), 119–138.", note: "Cross-national comparisons found earlier retirement associated with faster cognitive decline, consistent with a use-it-or-lose-it effect that structured learning counters.", link: doi("10.1257/jep.24.1.119"), kind: "doi" },
      { cite: "Bonsang, E., Adam, S., & Perelman, S. (2012). Does retirement affect cognitive functioning? Journal of Health Economics, 31(3), 490–501.", note: "Using US panel data, retirement had a negative effect on cognitive functioning that emerged after a lag, motivating deliberate cognitive engagement.", link: doi("10.1016/j.jhealeco.2012.03.005"), kind: "doi" },
    ],
  },
  {
    id: "gs-retirement-w2-annuity",
    goal: "retirement", tier: "advanced", section: "8460",
    title: "Frame the Lump-Sum-vs-Annuity Decision as Consumption, Not Investment",
    subtitle: "How the choice is described changes what people pick more than the numbers do",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "months", durability: "lasting", effort: "moderate" },
    feeds: ["Longevity protection", "Decision quality"],
    description:
      "Economic theory says people facing uncertain lifespans should value lifetime income, yet few annuitize. Experiments show the decision flips with framing: when described as guaranteed monthly spending for life, most people prefer the annuity; when described as an investment with a risky return, most reject it. Pricing studies find annuities offer reasonable value for the average buyer, and partial annuitization and inflation protection make them more appealing. The shelf does not recommend a product; it describes how to evaluate one so the frame does not decide for you.",
    action: "When offered a pension lump sum or considering an annuity, write out both options as monthly spending for the rest of your life (not as a pile of money), compare that against your essential expenses, and consider covering only the essentials with guaranteed income; get an independent fee-only review before signing.",
    sources: [
      { cite: "Brown, J. R., Kling, J. R., Mullainathan, S., & Wrobel, M. V. (2008). Why don't people insure late-life consumption? A framing explanation of the under-annuitization puzzle. American Economic Review, 98(2), 304–309.", note: "In a survey experiment, a consumption frame made most respondents prefer the annuity while an investment frame made most reject it.", link: doi("10.1257/aer.98.2.304"), kind: "doi" },
      { cite: "Benartzi, S., Previtero, A., & Thaler, R. H. (2011). Annuitization puzzles. Journal of Economic Perspectives, 25(4), 143–164.", note: "Reviewed why annuitization is rare despite its theoretical appeal and how plan design, defaults and framing shape the choice.", link: doi("10.1257/jep.25.4.143"), kind: "doi" },
      { cite: "Mitchell, O. S., Poterba, J. M., Warshawsky, M. J., & Brown, J. R. (1999). New evidence on the money's worth of individual annuities. American Economic Review, 89(5), 1299–1318.", note: "Estimated the expected payout of individual annuities relative to their price, finding reasonable value that improved over time.", link: doi("10.1257/aer.89.5.1299"), kind: "doi" },
      { cite: "Beshears, J., Choi, J. J., Laibson, D., Madrian, B. C., & Zeldes, S. P. (2014). What makes annuitization more appealing? Journal of Public Economics, 116, 2–16.", note: "Surveys showed demand for annuitization rose when partial annuitization, flexibility and inflation protection were offered.", link: doi("10.1016/j.jpubeco.2013.05.007"), kind: "doi" },
    ],
  },
  {
    id: "gs-retirement-w2-target-date-funds",
    goal: "retirement", tier: "fundamental", section: "8461",
    title: "Let a Low-Cost Target-Date Fund Be the Default — Then Check Its Glide Path Once",
    subtitle: "Target-date defaults improved portfolios for most participants; funds differ more than their names suggest",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "months", durability: "lasting", effort: "low" },
    feeds: ["Diversification", "Cost control", "Decision simplicity"],
    description:
      "Plan-level studies show that when target-date funds became the default, participants who would otherwise have held extreme or undiversified portfolios ended up with age-appropriate, diversified allocations and traded less. Research on the funds themselves finds large differences in equity share and risk across funds with the same target year, and performance analyses show fees and glide path drive outcomes. A study of a default that was previously conflicted advice found the target-date default served most participants at least as well. The boundary: a TDF is a floor, not an optimum; the check is cost and equity share, not the label.",
    action: "If your plan offers a target-date fund, use it as the default for your whole balance; once a year look at its expense ratio and current stock percentage, and switch to a cheaper series or a nearer/farther date only if either is clearly out of line with your risk tolerance.",
    sources: [
      { cite: "Mitchell, O. S., & Utkus, S. P. (2021). Target-date funds and portfolio choice in 401(k) plans. Journal of Pension Economics and Finance, 21(4), 519–536.", note: "Participants defaulted into target-date funds held better-diversified, age-appropriate portfolios and traded less than those choosing their own funds.", link: doi("10.1017/s1474747221000263"), kind: "doi" },
      { cite: "Balduzzi, P., & Reuter, J. (2018). Heterogeneity in target date funds: Strategic risk-taking or risk matching? The Review of Financial Studies, 32(1), 300–337.", note: "Funds with the same target date differed widely in risk, with newer entrants taking more idiosyncratic risk — why the equity share, not the name, needs checking.", link: doi("10.1093/rfs/hhy054"), kind: "doi" },
      { cite: "Shoven, J. B., & Walton, D. B. (2021). An analysis of the performance of target date funds. The Journal of Retirement, 8(4), 43–65.", note: "Compared target-date fund outcomes and found costs and glide-path design were the main drivers of differences in performance.", link: doi("10.3905/jor.2021.1.084"), kind: "doi" },
      { cite: "Chalmers, J., & Reuter, J. (2020). Is conflicted investment advice better than no advice? Journal of Financial Economics, 138(2), 366–387.", note: "Participants who followed broker advice held higher-fee, lower-return portfolios than those defaulted into a target-date fund, supporting the TDF as a baseline.", link: doi("10.1016/j.jfineco.2020.05.005"), kind: "doi" },
    ],
  },
  {
    id: "gs-retirement-w2-robo-advisors",
    goal: "retirement", tier: "moderate", section: "8462",
    title: "Robo-Advisors — Good for Diversification and Discipline, Weak on Everything Else",
    subtitle: "Honest evidence: algorithmic advice helped under-diversified investors most and widened access",
    evidenceTag: "Emerging",
    impact: { magnitude: 2, latency: "months", durability: "sustained", effort: "low" },
    feeds: ["Diversification", "Behavioral discipline"],
    description:
      "Studies of robo-advice adoption find that investors who had been poorly diversified improved diversification and reduced some behavioral biases after adopting, while already-diversified investors gained little; a study of a minimum-balance cut found robo-advisors widened access to wealth management for middle-income households. Survey research finds people who distrust human advisors are more open to robo-advice. The boundary: robo-advisors handle portfolio construction; the retirement-planning questions on this shelf (withdrawal sequencing, taxes, insurance, capacity) are outside their scope.",
    action: "If you hold a self-managed portfolio with more than a handful of individual stocks or no rebalancing rule, move it to a low-fee robo-advisor or target-date fund this quarter; keep a human, fee-only planner for the tax, insurance and drawdown questions.",
    sources: [
      { cite: "D'Acunto, F., Prabhala, N., & Rossi, A. G. (2019). The promises and pitfalls of robo-advising. The Review of Financial Studies, 32(5), 1983–2020.", note: "Adopters who were under-diversified increased diversification and showed reduced behavioral biases after adopting a robo-advisor, while well-diversified adopters saw little change.", link: doi("10.1093/rfs/hhz014"), kind: "doi" },
      { cite: "Reher, M., & Sokolinski, S. (2024). Robo advisors and access to wealth management. Journal of Financial Economics, 155, 103829.", note: "A reduction in a robo-advisor's account minimum increased participation by middle-income households, showing the technology broadens access to managed portfolios.", link: doi("10.1016/j.jfineco.2024.103829"), kind: "doi" },
      { cite: "Brenner, L., & Meyll, T. (2020). Robo-advisors: A substitute for human financial advice? Journal of Behavioral and Experimental Finance, 25, 100275.", note: "Survey data showed robo-advice use substitutes for human advice mainly among investors worried about conflicts of interest, clarifying who benefits.", link: doi("10.1016/j.jbef.2020.100275"), kind: "doi" },
    ],
  },
  {
    id: "gs-retirement-w2-tax-loss-harvesting",
    goal: "retirement", tier: "advanced", section: "8463",
    title: "Tax-Loss Harvesting in Taxable Accounts — Real but Modest, and Only Outside Retirement Accounts",
    subtitle: "The value comes from deferral and rate differences; it is not free money",
    evidenceTag: "Moderate",
    impact: { magnitude: 2, latency: "months", durability: "sustained", effort: "moderate" },
    feeds: ["After-tax return"],
    description:
      "Theory established that with capital-gains taxes on realization, the optimal policy is to realize losses promptly and defer gains, and dynamic models quantify how much this adds to after-tax wealth under trading costs and wash-sale-style constraints. Empirical work on investment taxation shows taxes materially reduce realized portfolio performance, which is what harvesting partially recovers. The honest boundary: benefits are modest, largest for high-bracket investors with volatile taxable holdings, zero inside IRAs and 401(k)s, and can be undone by re-buying the same security within the wash-sale window.",
    action: "If you hold investments in a taxable account, once a year (or after a market drop) review positions below cost, sell the losers and immediately buy a similar but not identical fund, and record the realized loss for your return; never do this inside a retirement account.",
    sources: [
      { cite: "Constantinides, G. M. (1983). Capital market equilibrium with personal tax. Econometrica, 51(3), 611–636.", note: "Showed that under realization-based capital-gains taxes the optimal strategy is to realize losses immediately and defer gains — the theoretical basis of harvesting.", link: doi("10.2307/1912150"), kind: "doi" },
      { cite: "Dammon, R. M., Spatt, C. S., & Zhang, H. H. (2001). Optimal consumption and investment with capital gains taxes. Review of Financial Studies, 14(3), 583–616.", note: "Dynamic model quantifying how loss realization and gain deferral change optimal portfolios and after-tax wealth over a lifetime.", link: doi("10.1093/rfs/14.3.583"), kind: "doi" },
      { cite: "Dammon, R. M., & Spatt, C. S. (1996). The optimal trading and pricing of securities with asymmetric capital gains taxes and transaction costs. Review of Financial Studies, 9(3), 921–952.", note: "Analyzed how transaction costs and the asymmetric treatment of gains and losses limit the value of tax-motivated trading.", link: doi("10.1093/rfs/9.3.921"), kind: "doi" },
      { cite: "Bergstresser, D., & Pontiff, J. (2013). Investment taxation and portfolio performance. Journal of Public Economics, 97, 245–257.", note: "Estimated the drag of taxes on realized returns across investor types, quantifying what tax-aware management can recover.", link: doi("10.1016/j.jpubeco.2012.04.005"), kind: "doi" },
    ],
  },
  {
    id: "gs-retirement-w2-withdrawal-sequencing",
    goal: "retirement", tier: "advanced", section: "8464",
    title: "Sequence Withdrawals Across Taxable, Tax-Deferred and Roth Accounts — and Plan for RMDs",
    subtitle: "The order you draw from accounts can add years to a portfolio; required distributions change behavior",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "months", durability: "lasting", effort: "high" },
    feeds: ["Portfolio longevity", "Tax efficiency"],
    description:
      "Practitioner-academic studies model withdrawal strategies and find that the conventional order (taxable first, then tax-deferred, then Roth) is beaten by strategies that fill low tax brackets each year from tax-deferred accounts and use Roth conversions in low-income years, extending portfolio life. Tax-record studies show required minimum distribution rules bind: withdrawals jump at the required age and many households take only the minimum, and a one-year suspension of the rule sharply reduced withdrawals. Peer-reviewed evidence specific to qualified charitable distributions is thin; they are a tax-rule feature to review with a professional. Nothing here is tax advice.",
    action: "Before your first retirement year, map each account type and its balance, then work with a fee-only planner or tax professional to set an annual withdrawal order that fills your target tax bracket from tax-deferred accounts; review it each December, and from the RMD age decide whether charitable giving should come directly from the IRA.",
    sources: [
      { cite: "Cook, K. A., Meyer, W., & Reichenstein, W. (2015). Tax-efficient withdrawal strategies. Financial Analysts Journal, 71(2), 16–29.", note: "Modeled withdrawal sequences and found strategies that use low brackets and Roth conversions extended portfolio longevity relative to the conventional order.", link: doi("10.2469/faj.v71.n2.2"), kind: "doi" },
      { cite: "Horan, S. M. (2006). Withdrawal location with progressive tax rates. Financial Analysts Journal, 62(6), 77–87.", note: "Showed that with progressive tax rates the optimal withdrawal location depends on filling brackets, not a fixed account order.", link: doi("10.2469/faj.v62.n6.4355"), kind: "doi" },
      { cite: "Reichenstein, W. (2006). After-tax asset allocation. Financial Analysts Journal, 62(4), 14–19.", note: "Argued that account balances should be compared after tax, which changes both allocation and the apparent size of tax-deferred holdings.", link: doi("10.2469/faj.v62.n4.4183"), kind: "doi" },
      { cite: "Arnold, T., Earl, J. H., Marshall, C. D., & Schwartz, A. (2018). Using 'equivalent tax rates' to determine tax-efficient retirement investment and withdrawal. The Journal of Wealth Management, 21(2), 55–69.", note: "Provided a framework for comparing the tax cost of drawing from different account types in a given year.", link: doi("10.3905/jwm.2018.1.063"), kind: "doi" },
      { cite: "Poterba, J., Venti, S., & Wise, D. (2011). The composition and drawdown of wealth in retirement. Journal of Economic Perspectives, 25(4), 95–118.", note: "Documented that most retirees draw down financial assets slowly and that housing and annuitized income dominate, context for how large sequencing gains can be.", link: doi("10.1257/jep.25.4.95"), kind: "doi" },
      { cite: "Brown, J. R., Poterba, J., & Richardson, D. P. (2017). Do required minimum distribution rules matter? The effect of the 2009 holiday on retirement plan distributions. Journal of Public Economics, 151, 96–109.", note: "When RMDs were suspended for one year, a large share of participants stopped withdrawing, showing the rule drives distributions rather than consumption needs.", link: doi("10.1016/j.jpubeco.2016.08.010"), kind: "doi" },
      { cite: "Mortenson, J. A., Schramm, H. R., & Whitten, A. (2019). The effects of required minimum distribution rules on withdrawals from traditional IRAs. National Tax Journal, 72(3), 507–542.", note: "Tax data showed withdrawals jump at the RMD age and many account holders withdraw only the minimum, evidence for planning distributions before the rule binds.", link: doi("10.17310/ntj.2019.3.02"), kind: "doi" },
    ],
  },
  {
    id: "gs-retirement-w2-exploitation",
    goal: "retirement", tier: "fundamental", section: "8465",
    title: "Set Up Fraud Defenses Now — a Trusted Contact, Alerts and a 24-Hour Rule",
    subtitle: "Financial exploitation of older adults is common and predicted by loneliness and low decision confidence",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "weeks", durability: "lasting", effort: "low" },
    feeds: ["Asset protection", "Decision safety"],
    description:
      "National surveys find financial exploitation is among the most common forms of elder mistreatment, and longitudinal work by Lichtenberg and colleagues shows that psychological vulnerability — depression, loneliness, low fulfillment — predicts later fraud victimization, independent of cognition. Validated rating scales can flag risky financial decisions in advance. Studies of older Americans document substantial fraud losses and the difficulty of recovering them. The protocol installs friction and a second set of eyes before any large or unusual transaction.",
    action: "This month name a trusted contact on every financial account, turn on transaction alerts, and adopt a household rule that any unplanned payment over $500 or any request involving gift cards, wire transfers or urgency waits 24 hours and one phone call to the trusted contact.",
    sources: [
      { cite: "Lichtenberg, P. A., Stickney, L., & Paulson, D. (2013). Is psychological vulnerability related to the experience of fraud in older adults? Clinical Gerontologist, 36(2), 132–146.", note: "In a national sample, older adults with depression and low social-needs fulfillment were markedly more likely to report having been defrauded.", link: doi("10.1080/07317115.2012.749323"), kind: "doi" },
      { cite: "Lichtenberg, P. A., Sugarman, M. A., Paulson, D., Ficker, L. J., & Rahman-Filipiak, A. (2015). Psychological and functional vulnerability predicts fraud cases in older adults: Results of a longitudinal study. Clinical Gerontologist, 39(1), 48–63.", note: "Longitudinal data showed psychological vulnerability predicted new fraud cases over time, supporting social connection as a fraud defense.", link: doi("10.1080/07317115.2015.1101632"), kind: "doi" },
      { cite: "Lichtenberg, P. A., Ficker, L. J., & Rahman-Filipiak, A. (2015). Financial decision-making abilities and financial exploitation in older African Americans: Preliminary validity evidence for the Lichtenberg Financial Decision Rating Scale (LFDRS). Journal of Elder Abuse & Neglect, 28(1), 14–33.", note: "Validated a structured rating scale that identifies vulnerable financial decisions, the kind of screen a trusted contact can informally apply.", link: doi("10.1080/08946566.2015.1078760"), kind: "doi" },
      { cite: "Acierno, R., Hernandez, M. A., Amstadter, A. B., Resnick, H. S., Steve, K., Muzzy, W., & Kilpatrick, D. G. (2010). Prevalence and correlates of emotional, physical, sexual, and financial abuse and potential neglect in the United States: The National Elder Mistreatment Study. American Journal of Public Health, 100(2), 292–297.", note: "The national study established the prevalence of financial exploitation among older adults and its association with low social support.", link: doi("10.2105/ajph.2009.163089"), kind: "doi" },
      { cite: "DeLiema, M., Deevy, M., Lusardi, A., & Mitchell, O. S. (2018). Financial fraud among older Americans: Evidence and implications. The Journals of Gerontology: Series B, 75(4), 861–868.", note: "Health and Retirement Study data documented the share of older adults reporting fraud and its financial and psychological consequences.", link: doi("10.1093/geronb/gby151"), kind: "doi" },
    ],
  },
  {
    id: "gs-retirement-w2-cognitive-decline",
    goal: "retirement", tier: "advanced", section: "8466",
    title: "Simplify and Automate the Finances Before Capacity Declines",
    subtitle: "Financial skill peaks in middle age; missed payments can precede a dementia diagnosis by years",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "months", durability: "lasting", effort: "moderate" },
    feeds: ["Asset protection", "Family burden", "Decision safety"],
    description:
      "Economists find that financial decision quality peaks around the early fifties and declines afterward, and that financial literacy falls with age while confidence does not. Clinical studies show financial capacity is among the first abilities lost in dementia, and linked credit and Medicare records show missed payments and credit-score declines appear years before a diagnosis. The evidence supports consolidating accounts, automating bills, and putting a review system in place while you can still design it — not after a problem.",
    action: "Over the next year, reduce to one checking, one savings and as few investment accounts as possible, put every recurring bill on autopay, and give a trusted person view-only access with an agreed monthly check-in; write down where everything is.",
    sources: [
      { cite: "Agarwal, S., Driscoll, J. C., Gabaix, X., & Laibson, D. (2009). The age of reason: Financial decisions over the life cycle and implications for regulation. Brookings Papers on Economic Activity, 2009(2), 51–117.", note: "Across ten financial products, the cost of mistakes followed a U-shape with age, lowest around the early fifties and rising in later life.", link: doi("10.1353/eca.0.0067"), kind: "doi" },
      { cite: "Boyle, P. A., Yu, L., Wilson, R. S., Gamble, K., Buchman, A. S., & Bennett, D. A. (2012). Poor decision making is a consequence of cognitive decline among older persons without Alzheimer's disease or mild cognitive impairment. PLoS ONE, 7(8), e43647.", note: "Even without a dementia diagnosis, subtle cognitive decline predicted worse financial and health-care decision making in older adults.", link: doi("10.1371/journal.pone.0043647"), kind: "doi" },
      { cite: "Finke, M. S., Howe, J. S., & Huston, S. J. (2017). Old age and the decline in financial literacy. Management Science, 63(1), 213–230.", note: "Financial literacy scores declined steadily after age 60 while confidence in financial decisions did not, a dangerous gap.", link: doi("10.1287/mnsc.2015.2293"), kind: "doi" },
      { cite: "Nicholas, L. H., Langa, K. M., Bynum, J. P. W., & Hsu, J. W. (2021). Financial presentation of Alzheimer disease and related dementias. JAMA Internal Medicine, 181(2), 220–227.", note: "Linked credit and Medicare data showed missed payments and subprime credit scores emerging years before a dementia diagnosis.", link: doi("10.1001/jamainternmed.2020.6432"), kind: "doi" },
      { cite: "Marson, D. C., Sawrie, S. M., Snyder, S., McInturff, B., Stalvey, T., Boothe, A., Aldridge, T., Chatterjee, A., & Harrell, L. E. (2000). Assessing financial capacity in patients with Alzheimer disease: A conceptual model and prototype instrument. Archives of Neurology, 57(6), 877–884.", note: "Introduced a structured model of financial capacity and showed impairment even at mild stages of Alzheimer disease.", link: doi("10.1001/archneur.57.6.877"), kind: "doi" },
    ],
  },
  {
    id: "gs-retirement-w2-advance-directives",
    goal: "retirement", tier: "moderate", section: "8467",
    title: "Complete an Advance Directive and Durable Powers of Attorney, and Tell Your Family",
    subtitle: "Advance care planning improves end-of-life care and reduces family distress; two-thirds of adults have none",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "weeks", durability: "lasting", effort: "moderate" },
    feeds: ["Family burden", "Autonomy", "Care quality"],
    description:
      "A randomized trial of facilitated advance care planning in hospitalized older patients found wishes were more likely to be known and followed and that surviving family had less stress, anxiety and depression. National data show most older adults who need surrogate decisions have lost capacity, and those with directives receive care more consistent with their preferences. A systematic review confirms these effects across studies, and a large pooled analysis found roughly one in three US adults has any directive. Financial powers of attorney are far less studied but follow the same logic: decide and document while capable.",
    action: "This quarter, complete your state's advance directive and a durable financial power of attorney with a lawyer or a recognized free form, name a health-care proxy, and hold a 30-minute conversation with that person and your closest family about what you wrote.",
    sources: [
      { cite: "Detering, K. M., Hancock, A. D., Reade, M. C., & Silvester, W. (2010). The impact of advance care planning on end of life care in elderly patients: Randomised controlled trial. BMJ, 340, c1345.", note: "Facilitated advance care planning made end-of-life wishes more likely to be known and respected and reduced stress, anxiety and depression in surviving relatives.", link: doi("10.1136/bmj.c1345"), kind: "doi" },
      { cite: "Silveira, M. J., Kim, S. Y. H., & Langa, K. M. (2010). Advance directives and outcomes of surrogate decision making before death. New England Journal of Medicine, 362(13), 1211–1218.", note: "Among older Americans needing end-of-life decisions, most lacked capacity, and those with directives received care strongly associated with their stated preferences.", link: doi("10.1056/nejmsa0907901"), kind: "doi" },
      { cite: "Brinkman-Stoppelenburg, A., Rietjens, J. A. C., & van der Heide, A. (2014). The effects of advance care planning on end-of-life care: A systematic review. Palliative Medicine, 28(8), 1000–1025.", note: "Systematic review found advance care planning increased compliance with wishes and reduced hospitalization and unwanted treatment.", link: doi("10.1177/0269216314526272"), kind: "doi" },
      { cite: "Yadav, K. N., et al. (2017). Approximately one in three US adults completes any type of advance directive for end-of-life care. Health Affairs, 36(7), 1244–1251.", note: "Pooled analysis of many studies found only about a third of US adults had completed any advance directive, including among those with chronic illness.", link: doi("10.1377/hlthaff.2017.0175"), kind: "doi" },
    ],
  },
  {
    id: "gs-retirement-w2-identity-purpose",
    goal: "retirement", tier: "fundamental", section: "8468",
    title: "Write the Purpose Before the Date — a Weekly Structure for the First Year",
    subtitle: "Adjustment to retirement is a process; purpose in life predicts survival and function",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "months", durability: "lasting", effort: "low" },
    feeds: ["Purpose", "Wellbeing", "Longevity"],
    description:
      "Reviews of retirement adjustment find most people adapt well but a meaningful minority struggle, with outcomes shaped by voluntariness, health, finances and — critically — whether work roles are replaced. Studies distinguish adjustment (the process) from satisfaction (the state). Prospective cohorts find that a stronger sense of purpose predicts lower mortality across adulthood and lower risk of disability among older adults. The protocol converts purpose from a feeling into a weekly schedule before the last day of work.",
    action: "Three months before retiring, write one page answering 'what will I be for?' and turn it into a weekly template with fixed blocks for contribution, learning, movement and people; run the template for the first 12 months and adjust it monthly.",
    sources: [
      { cite: "Wang, M., Henkens, K., & van Solinge, H. (2011). Retirement adjustment: A review of theoretical and empirical advancements. American Psychologist, 66(3), 204–213.", note: "Reviewed the evidence that retirement adjustment is a longitudinal process shaped by resources and role replacement, not a single event.", link: doi("10.1037/a0022414"), kind: "doi" },
      { cite: "van Solinge, H., & Henkens, K. (2008). Adjustment to and satisfaction with retirement: Two of a kind? Psychology and Aging, 23(2), 422–434.", note: "Separated adjustment difficulty from retirement satisfaction and found involuntary and abrupt retirement predicted harder adjustment.", link: doi("10.1037/0882-7974.23.2.422"), kind: "doi" },
      { cite: "Hill, P. L., & Turiano, N. A. (2014). Purpose in life as a predictor of mortality across adulthood. Psychological Science, 25(7), 1482–1486.", note: "Over 14 years, higher purpose in life predicted lower mortality risk at every adult age, including older adults.", link: doi("10.1177/0956797614531799"), kind: "doi" },
      { cite: "Boyle, P. A., Barnes, L. L., Buchman, A. S., & Bennett, D. A. (2009). Purpose in life is associated with mortality among community-dwelling older persons. Psychosomatic Medicine, 71(5), 574–579.", note: "Older adults with greater purpose had substantially lower mortality over follow-up after adjusting for health and depression.", link: doi("10.1097/psy.0b013e3181a5a7c0"), kind: "doi" },
      { cite: "Boyle, P. A., Buchman, A. S., & Bennett, D. A. (2010). Purpose in life is associated with a reduced risk of incident disability among community-dwelling older persons. The American Journal of Geriatric Psychiatry, 18(12), 1093–1102.", note: "Purpose in life predicted lower risk of developing disability in daily activities, linking purpose to functional independence.", link: doi("10.1097/jgp.0b013e3181d6c259"), kind: "doi" },
      { cite: "Kim, J. E., & Moen, P. (2002). Retirement transitions, gender, and psychological well-being: A life-course, ecological model. The Journals of Gerontology Series B, 57(3), P212–P222.", note: "Well-being after retirement depended on the resources and roles carried into it, supporting deliberate role planning.", link: doi("10.1093/geronb/57.3.p212"), kind: "doi" },
    ],
  },
  {
    id: "gs-retirement-w2-fire",
    goal: "retirement", tier: "elite", section: "8469",
    title: "Retire Early for Your Health (FIRE)",
    subtitle: "Honest verdict: early retirement does not reliably improve health or longevity, and can cost cognition",
    evidenceTag: "Mixed",
    impact: { magnitude: 1, latency: "months", durability: "lasting", effort: "high" },
    callout: "Floor-rated as a health claim. The best cohorts and quasi-experiments disagree: one industrial cohort found retiring at 55 was associated with higher mortality than retiring at 65; cross-national and US panel studies find retirement accelerates cognitive decline; some European studies find health improvements; a Norwegian pension reform found no mortality effect. Financial independence is a legitimate goal — the shelf does not rate that — but 'retire early to be healthier' is not supported.",
    description:
      "Studies of early retirement and health reach different conclusions depending on design and country. A large industrial cohort found employees retiring at 55 had higher subsequent mortality than those retiring at 65, though selection on health is hard to exclude. Cross-country and US panel studies find retirement followed by faster cognitive decline. Quasi-experimental European work finds retirement improves self-reported health for some groups, while a Norwegian reform lowering the retirement age showed no effect on mortality. The honest reading: what you retire into — activity, purpose, social contact — matters more than the age you retire at.",
    action: "If you are planning to retire well before 65, build the post-retirement week (purpose, learning, people, movement, and health coverage) before you set the date, and treat the health case for early retirement as unproven rather than as a reason.",
    sources: [
      { cite: "Tsai, S. P., Wendt, J. K., Donnelly, R. P., de Jong, G., & Ahmed, F. S. (2005). Age at retirement and long term survival of an industrial population: Prospective cohort study. BMJ, 331(7523), 995.", note: "In a large petrochemical cohort, employees who retired at 55 had higher mortality over follow-up than those who retired at 65, with no survival advantage from early retirement.", link: doi("10.1136/bmj.38586.448704.e0"), kind: "doi" },
      { cite: "Rohwedder, S., & Willis, R. J. (2010). Mental retirement. Journal of Economic Perspectives, 24(1), 119–138.", note: "Across countries, earlier retirement ages were associated with lower cognitive performance among 60–64 year olds, consistent with a causal effect of leaving work.", link: doi("10.1257/jep.24.1.119"), kind: "doi" },
      { cite: "Bonsang, E., Adam, S., & Perelman, S. (2012). Does retirement affect cognitive functioning? Journal of Health Economics, 31(3), 490–501.", note: "US panel data with instruments showed retirement reduced cognitive functioning, with the effect appearing after a lag.", link: doi("10.1016/j.jhealeco.2012.03.005"), kind: "doi" },
      { cite: "Coe, N. B., & Zamarro, G. (2011). Retirement effects on health in Europe. Journal of Health Economics, 30(1), 77–86.", note: "Using pension-age thresholds across Europe, retirement improved self-reported general health — the strongest evidence on the other side.", link: doi("10.1016/j.jhealeco.2010.11.002"), kind: "doi" },
      { cite: "Dave, D., Rashad, I., & Spasojevic, J. (2008). The effects of retirement on physical and mental health outcomes. Southern Economic Journal, 75(2), 497–523.", note: "US panel data linked complete retirement to declines in physical and mental health, moderated by remaining physically active and socially engaged.", link: doi("10.1002/j.2325-8012.2008.tb00916.x"), kind: "doi" },
      { cite: "Hernaes, E., Markussen, S., Piggott, J., & Vestad, O. L. (2013). Does retirement age impact mortality? Journal of Health Economics, 32(3), 586–598.", note: "A Norwegian reform that lowered the retirement age for some workers had no detectable effect on mortality, arguing against either a large harm or a large benefit.", link: doi("10.1016/j.jhealeco.2013.03.001"), kind: "doi" },
    ],
  },
];
