// Goal shelf (WAVE 2): TRAVEL — go traveling (sections 9050–9099).
// Wave 2 widens the wave-1 travel shelf with a separate topic list: pilgrimage
// walking, slow travel, family travel, study abroad, language immersion, nature
// and forest bathing, medical tourism, long-haul flight health, digital-detox
// travel, group vs independent travel, travel and cognition in later life,
// camping and the circadian clock, culture shock and re-entry, photography and
// memory, anticipation, expatriate wellbeing, retirement abroad, sustainable
// choices, volunteer tourism and solo female travel.
// Verification: every DOI below was resolved against the Crossref record or the
// PubMed record on 2026-09-11 (see the ledger travel.w2.ledger.json). Nothing on
// this shelf is medical, legal or financial advice.
import { doi, type GoalShelfCluster } from "../types";

export const SECTIONS: Record<string, string> = {
  "9050": "Pilgrimage Walking — the Camino and Long-Distance Walking for Wellbeing",
  "9051": "Slow Travel — Fewer Places, Longer Stays, Overland Where Possible",
  "9052": "Travelling With Children — Family Vacations and Child Outcomes",
  "9053": "Study Abroad — What a Semester or Year Away Actually Changes",
  "9054": "Language Immersion — Gains From Living in the Language",
  "9055": "Nature Travel & Forest Bathing — Shinrin-yoku, Honestly Weighed",
  "9056": "Medical Tourism — Surgery Abroad, the Complication and Cost Record",
  "9057": "Long-Haul Flight Health — Clots, Cabin Hypoxia, Dehydration & Jet Lag",
  "9058": "Digital-Detox Travel — Disconnected Trips and Smartphone Restriction",
  "9059": "Group Tours vs Independent Travel — Choosing the Format That Fits",
  "9060": "Travel & Cognition in Later Life — Trips, Leisure and Dementia Risk",
  "9061": "Camping & the Circadian Reset — A Weekend Under Natural Light",
  "9062": "Culture Shock & Reverse Culture Shock — Adjustment and Re-entry",
  "9063": "Travel Photography & Memory — When the Camera Helps and When It Hurts",
  "9064": "Planning & Anticipation — Where the Happiness of a Trip Really Lives",
  "9065": "Expatriate Wellbeing — Adjusting to a Life Abroad",
  "9066": "Retirement Abroad — International Retirement Migration, Honestly Weighed",
  "9067": "Sustainable Travel Choices — Flying, Footprints and the Attitude–Behaviour Gap",
  "9068": "Volunteer Tourism — Good Intentions, Documented Harms",
  "9069": "Solo Female Travel — Safety Research, Fear and Freedom",
};

export const CLUSTERS: GoalShelfCluster[] = [
  {
    id: "gs-travel-w2-forest-bathing",
    goal: "travel", tier: "fundamental", section: "9055",
    title: "Forest Bathing: Two Slow Hours Under Trees, Weekly",
    subtitle: "Shinrin-yoku lowers cortisol and blood pressure in trials; the immune claims rest on small studies",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "days", durability: "transient", effort: "low" },
    feeds: ["stress recovery", "attention restoration", "blood pressure"],
    description:
      "Shinrin-yoku is unhurried, sensory time in a forest with no exercise target. Systematic reviews and meta-analyses find short-term reductions in salivary cortisol, blood pressure, anxiety and depressive symptoms after forest sessions compared with urban control walks. The honest boundary: most trials are small, short and unblinded, effects are largely transient, and the well-known natural-killer-cell findings come from a handful of Japanese studies that have not been widely replicated.",
    action: "Once a week for the next month, spend at least two hours walking slowly in the nearest forest or wooded park with your phone on silent, stopping to sit for ten minutes at the halfway point. Plan one full nature day trip in the month.",
    sources: [
      { cite: "Hansen, M. M., Jones, R., & Tocchini, K. (2017). Shinrin-Yoku (Forest Bathing) and Nature Therapy: A State-of-the-Art Review. International Journal of Environmental Research and Public Health, 14(8).", note: "State-of-the-art review of the shinrin-yoku literature that frames what forest bathing is, what has been measured and where the evidence is still thin.", link: doi("10.3390/ijerph14080851"), kind: "doi" },
      { cite: "Antonelli, M., Barbieri, G., & Donelli, D. (2019). Effects of forest bathing (shinrin-yoku) on levels of cortisol as a stress biomarker: a systematic review and meta-analysis. International Journal of Biometeorology, 63(8), 1117-1134.", note: "Systematic review and meta-analysis pooling trials of forest bathing on salivary cortisol, the most common stress biomarker in this literature.", link: doi("10.1007/s00484-019-01717-x"), kind: "doi" },
      { cite: "Siah, C. J. R., Goh, Y. S., Lee, J., Poon, S. N., Ow Yong, J. Q. Y., & Tam, W. W. (2023). The effects of forest bathing on psychological well-being: A systematic review and meta-analysis. International Journal of Mental Health Nursing, 32(4), 1038-1054.", note: "Meta-analysis of forest-bathing trials on psychological wellbeing outcomes such as anxiety, depression and mood.", link: doi("10.1111/inm.13131"), kind: "doi" },
      { cite: "Ideno, Y., Hayashi, K., Abe, Y., Ueda, K., Iso, H., Noda, M., Lee, J. S., & Suzuki, S. (2017). Blood pressure-lowering effect of Shinrin-yoku (Forest bathing): a systematic review and meta-analysis. BMC Complementary and Alternative Medicine, 17(1), 409.", note: "Meta-analysis of the blood-pressure-lowering effect of forest environments versus non-forest controls.", link: doi("10.1186/s12906-017-1912-z"), kind: "doi" },
      { cite: "Antonelli, M., Donelli, D., Carlone, L., Maggini, V., Firenzuoli, F., & Bedeschi, E. (2021). Effects of forest bathing (shinrin-yoku) on individual well-being: an umbrella review. International Journal of Environmental Health Research, 32(8), 1842-1867.", note: "Umbrella review of systematic reviews on forest bathing and individual wellbeing, useful for the overall quality-of-evidence picture.", link: doi("10.1080/09603123.2021.1919293"), kind: "doi" },
      { cite: "Li, Q. (2010). Effect of forest bathing trips on human immune function. Environmental Health and Preventive Medicine, 15(1), 9-17.", note: "The original forest-bathing immune study (natural-killer activity after forest trips); small samples, so treat the immune story as preliminary.", link: doi("10.1007/s12199-008-0068-3"), kind: "doi" },
      { cite: "Queirolo, L., Fazia, T., Roccon, A., Pistollato, E., Gatti, L., Bernardinelli, L., Zanette, G., & Berrino, F. (2024). Effects of forest bathing (Shinrin-yoku) in stressed people. Frontiers in Psychology, 15, 1458418.", note: "Recent trial of forest bathing in stressed adults, showing the kind of short-term stress outcomes the field measures.", link: doi("10.3389/fpsyg.2024.1458418"), kind: "doi" },
    ],
  },
  {
    id: "gs-travel-w2-flight-health",
    goal: "travel", tier: "fundamental", section: "9057",
    title: "Long-Haul Flight Protocol: Move, Hydrate, Know Your Clot Risk",
    subtitle: "Travel roughly doubles venous thromboembolism risk, rising with each 2 hours aloft; stockings help those at risk, aspirin does not",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "days", durability: "transient", effort: "low" },
    feeds: ["circulation", "arrival energy"],
    description:
      "A meta-analysis of 14 studies found travellers had about twice the risk of venous thromboembolism of non-travellers, with an 18% higher risk per 2 hours of any travel and 26% per 2 hours of air travel. Absolute risk stays low for healthy people (clinical events are rare per flight), cabin pressure lowers blood-oxygen saturation by a few points in everyone, and graduated compression stockings reduced leg swelling and clots in trials while aspirin did not. Anyone with prior clots, recent surgery, pregnancy or hormone use should discuss prophylaxis with a clinician before a long flight.",
    action: "On every flight over four hours: walk the aisle or do calf raises every hour, drink water rather than alcohol, and if you have any clot risk factor wear below-knee graduated compression stockings and book a clinician conversation before you fly.",
    sources: [
      { cite: "Chandra, D., Parisini, E., & Mozaffarian, D. (2009). Meta-analysis: travel and risk for venous thromboembolism. Annals of Internal Medicine, 151(3), 180-190.", note: "Meta-analysis of 14 studies (4,055 VTE cases): pooled relative risk 2.0 for travellers, 2.8 once biased control groups were excluded, with an 18% higher risk per 2-hour increase in travel and 26% per 2 hours of air travel.", link: doi("10.7326/0003-4819-151-3-200908040-00129"), kind: "doi" },
      { cite: "Philbrick, J. T., Shumate, R., Siadaty, M. S., & Becker, D. M. (2007). Air travel and venous thromboembolism: a systematic review. Journal of General Internal Medicine, 22(1), 107-114.", note: "Systematic review of 25 studies: symptomatic clots after long flights are rare (about 27 pulmonary emboli per million flights), compression stockings prevented travel-related VTE in 4 of 6 studies, aspirin did not.", link: doi("10.1007/s11606-006-0016-0"), kind: "doi" },
      { cite: "McKerrow Johnson, I., Shatzel, J., Olson, S., Kohl, T., Hamilton, A., & DeLoughery, T. G. (2022). Travel-Associated Venous Thromboembolism. Wilderness & Environmental Medicine, 33(2), 169-178.", note: "Systematic review of 18 studies with a summary of five guideline groups: association is mild to moderate, dose-related from 4 hours, and guidelines favour stockings over drugs for at-risk travellers.", link: doi("10.1016/j.wem.2022.02.004"), kind: "doi" },
      { cite: "da Silva, L. F., Porto, M. S. R., de Sousa, A. B., & Avena, K. M. (2021). Graduated compression stockings as a prophylactic measure in venous thromboembolism and edema of lower limbs triggered by air travel: a systematic review of clinical trials. Jornal Vascular Brasileiro, 20, e20200164.", note: "Systematic review of eight clinical trials (2,022 passengers) finding high-quality evidence that graduated compression stockings prevent oedema and moderate-quality evidence that they reduce VTE on flights over 3 hours.", link: doi("10.1590/1677-5449.200164"), kind: "doi" },
      { cite: "Humphreys, S., Deyermond, R., Bali, I., Stevenson, M., & Fee, J. P. H. (2005). The effect of high altitude commercial air travel on oxygen saturation. Anaesthesia, 60(5), 458-460.", note: "Pulse oximetry in 84 passengers: mean oxygen saturation fell from 97% at ground level to 93% at cruising altitude, with 54% at or below 94%.", link: doi("10.1111/j.1365-2044.2005.04124.x"), kind: "doi" },
      { cite: "Smith, T. G., Talbot, N. P., Chang, R. W., Wilkinson, E., Nickol, A. H., Newman, D. G., Robbins, P. A., & Dorrington, K. L. (2012). Pulmonary artery pressure increases during commercial air travel in healthy passengers. Aviation, Space, and Environmental Medicine, 83(7), 673-676.", note: "In-flight echocardiography on a 9-hour flight: pulmonary artery pressure rose by about 20% in healthy passengers, a reminder that cabin hypoxia is real even when unnoticed.", link: doi("10.3357/asem.3235.2012"), kind: "doi" },
      { cite: "Ansari, M. T., Cheung, B. M. Y., Qing Huang, J., Eklof, B., & Karlberg, J. P. E. (2005). Traveler's thrombosis: a systematic review. Journal of Travel Medicine, 12(3), 142-154.", note: "Earlier systematic review of observational studies on traveller's thrombosis, showing that higher-quality studies found a strong association with prolonged air travel, especially in people with pre-existing risk factors.", link: doi("10.2310/7060.2005.12303"), kind: "doi" },
    ],
  },
  {
    id: "gs-travel-w2-camping-circadian",
    goal: "travel", tier: "fundamental", section: "9061",
    title: "A Weekend of Camping to Reset Your Body Clock",
    subtitle: "Natural light and no screens pull the biological night earlier within days; the effect fades on return",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "days", durability: "transient", effort: "low" },
    feeds: ["sleep timing", "morning energy"],
    description:
      "In Kenneth Wright's field studies, a week camping under the natural summer light-dark cycle shifted the internal clock so that biological night began near sunset and ended near sunrise, with the biggest advances in night owls. A follow-up found a single weekend of camping achieved roughly 69% of that week-long shift, and a study of children showed dim-light melatonin onset advanced by about two hours after two weeks at camp. The honest boundary: the reset is transient unless you keep morning daylight and dim evenings at home.",
    action: "Book one weekend of camping (or a cabin with no electric light after dusk) this month, leave screens in the car, and on return keep the shift by getting outside within an hour of waking every day.",
    sources: [
      { cite: "Wright, K. P., McHill, A. W., Birks, B. R., Griffin, B. R., Rusterholz, T., & Chinoy, E. D. (2013). Entrainment of the human circadian clock to the natural light-dark cycle. Current Biology, 23(16), 1554-1558.", note: "After a week of camping in a natural 14h40:9h20 light-dark cycle, participants' circadian clocks synchronised to solar time; later chronotypes showed the largest advances.", link: doi("10.1016/j.cub.2013.06.039"), kind: "doi" },
      { cite: "Stothard, E. R., McHill, A. W., Depner, C. M., Birks, B. R., Moehlman, T. M., Ritchie, H. K., Guzzetti, J. R., Chinoy, E. D., LeBourgeois, M. K., Axelsson, J., & Wright, K. P. (2017). Circadian Entrainment to the Natural Light-Dark Cycle across Seasons and the Weekend. Current Biology, 27(4), 508-513.", note: "Weekend camping in summer produced earlier circadian and sleep timing, achieving about 69% of the shift seen after a full week; winter camping expanded the biological night.", link: doi("10.1016/j.cub.2016.12.041"), kind: "doi" },
      { cite: "Eto, T., Kitamura, S., Nishimura, K., Takeoka, K., Nishimura, Y., Lee, S.-I., Ohashi, M., Shikano, A., Noi, S., & Higuchi, S. (2022). Circadian phase advances in children during camping life according to the natural light-dark cycle. Journal of Physiological Anthropology, 41(1), 42.", note: "In 42 children, roughly two weeks of camping with little artificial light advanced dim-light melatonin onset by about two hours, most in those with delayed sleep habits.", link: doi("10.1186/s40101-022-00316-x"), kind: "doi" },
      { cite: "Hester, L., Dang, D., Barker, C. J., Heath, M., Mesiya, S., Tienabeso, T., & Watson, K. (2021). Evening wear of blue-blocking glasses for sleep and mood disorders: a systematic review. Chronobiology International, 38(10), 1375-1383.", note: "Systematic review of blue-blocking glasses worn in the evening; a home-based way to protect the darker evenings that camping provides.", link: doi("10.1080/07420528.2021.1930029"), kind: "doi" },
    ],
  },
  {
    id: "gs-travel-w2-photo-memory",
    goal: "travel", tier: "fundamental", section: "9063",
    title: "Photograph With Intention, Then Put the Camera Away",
    subtitle: "Volitional photos can sharpen visual memory and enjoyment; shooting to share, and shooting everything, blunts both",
    evidenceTag: "Moderate",
    impact: { magnitude: 2, latency: "days", durability: "sustained", effort: "low" },
    feeds: ["memory for experiences", "presence"],
    description:
      "Linda Henkel's museum experiments found people remembered fewer objects they had photographed wholesale, but zooming in on a detail preserved memory. Barasch and colleagues showed that choosing what to photograph improves visual memory while impairing memory for what was heard, that taking photos can increase engagement and enjoyment, and that photographing with the intention to share lowers enjoyment by making people self-focused. Tamir and colleagues found that recording an experience to post online reduced memory for it.",
    action: "On your next trip, set a rule: photograph only what you deliberately choose, never for an audience while the moment is happening, and leave the phone in your bag for at least one full experience each day.",
    sources: [
      { cite: "Henkel, L. A. (2014). Point-and-Shoot Memories: The Influence of Taking Photos on Memory for a Museum Tour. Psychological Science, 25(2), 396-402.", note: "Museum-tour experiment: participants remembered fewer objects and fewer details of objects they photographed as a whole, but zooming in on part of an object preserved memory (the photo-taking-impairment effect).", link: doi("10.1177/0956797613504438"), kind: "doi" },
      { cite: "Barasch, A., Diehl, K., Silverman, J., & Zauberman, G. (2017). Photographic Memory: The Effects of Volitional Photo Taking on Memory for Visual and Auditory Aspects of an Experience. Psychological Science, 28(8), 1056-1066.", note: "Volitional photo taking improved visual memory for an experience while impairing auditory memory, across multiple studies.", link: doi("10.1177/0956797617694868"), kind: "doi" },
      { cite: "Diehl, K., Zauberman, G., & Barasch, A. (2016). How taking photos increases enjoyment of experiences. Journal of Personality and Social Psychology, 111(2), 119-140.", note: "Across field and laboratory studies, taking photos increased enjoyment of positive experiences by raising engagement.", link: doi("10.1037/pspa0000055"), kind: "doi" },
      { cite: "Barasch, A., Zauberman, G., & Diehl, K. (2018). How the Intention to Share Can Undermine Enjoyment: Photo-Taking Goals and Evaluation of Experiences. Journal of Consumer Research, 44(6).", note: "Taking photos with the intention to share them with others undermined enjoyment relative to taking them for oneself, via self-presentational concern.", link: doi("10.1093/jcr/ucx112"), kind: "doi" },
      { cite: "Tamir, D. I., Templeton, E. M., Ward, A. F., & Zaki, J. (2018). Media usage diminishes memory for experiences. Journal of Experimental Social Psychology, 76, 161-168.", note: "Recording an experience with media (to share or not) diminished memory for it compared with simply experiencing it.", link: doi("10.1016/j.jesp.2018.01.006"), kind: "doi" },
      { cite: "Soares, J. S., & Storm, B. C. (2018). Forget in a flash: A further investigation of the photo-taking-impairment effect. Journal of Applied Research in Memory and Cognition, 7(1), 154-160.", note: "Replication and extension of the photo-taking-impairment effect, showing it persists even when photos are deleted immediately.", link: doi("10.1016/j.jarmac.2017.10.004"), kind: "doi" },
    ],
  },
  {
    id: "gs-travel-w2-anticipation",
    goal: "travel", tier: "fundamental", section: "9064",
    title: "Book Early and Savour the Wait: The Anticipation Dividend",
    subtitle: "Vacationers are happier before a trip than non-vacationers; the post-trip lift mostly fades within weeks",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "weeks", durability: "transient", effort: "low" },
    feeds: ["positive anticipation", "recovery from work"],
    description:
      "Nawijn and colleagues found that people with an upcoming holiday reported higher pre-trip happiness than non-vacationers, while post-trip happiness returned to baseline for most. A meta-analysis of vacation effects on health and wellbeing found improvements that faded quickly after return, and de Bloom's work shows what you do on holiday (relaxation, sleep, pleasure) predicts the after-effect. Experiences are anticipated with more excitement than material purchases. The practical implication: spread trips out, plan them early, and protect sleep and pleasure while away.",
    action: "This month, book a trip at least eight weeks out and schedule a 15-minute planning session each week to look forward to it; while away, protect sleep and unstructured pleasure over sightseeing volume.",
    sources: [
      { cite: "Nawijn, J., Marchand, M. A., Veenhoven, R., & Vingerhoets, A. J. (2010). Vacationers Happier, but Most not Happier After a Holiday. Applied Research in Quality of Life, 5(1), 35-47.", note: "Dutch panel study: vacationers reported higher pre-trip happiness than non-vacationers, while post-trip happiness was not higher for most, only for those who had a very relaxed holiday.", link: doi("10.1007/s11482-009-9091-9"), kind: "doi" },
      { cite: "Kumar, A., Killingsworth, M. A., & Gilovich, T. (2014). Waiting for Merlot: Anticipatory Consumption of Experiential and Material Purchases. Psychological Science, 25(10), 1924-1931.", note: "Anticipating experiential purchases produced more excitement and less impatience than anticipating material purchases, across studies including a large experience-sampling sample.", link: doi("10.1177/0956797614546556"), kind: "doi" },
      { cite: "de Bloom, J., Kompier, M., Geurts, S., de Weerth, C., Taris, T., & Sonnentag, S. (2009). Do We Recover from Vacation? Meta-analysis of Vacation Effects on Health and Well-being. Journal of Occupational Health, 51(1), 13-25.", note: "Meta-analysis of vacation effects on health and wellbeing: positive effects after a holiday were present but faded quickly after return to work.", link: doi("10.1539/joh.k8004"), kind: "doi" },
      { cite: "de Bloom, J., Geurts, S. A. E., & Kompier, M. A. J. (2013). Vacation (after-) effects on employee health and well-being, and the role of vacation activities, experiences and sleep. Journal of Happiness Studies, 14(2), 613-633.", note: "Longitudinal study of employees around a vacation: health and wellbeing improved during the trip and the after-effect depended on vacation activities, experiences and sleep.", link: doi("10.1007/s10902-012-9345-3"), kind: "doi" },
      { cite: "Nawijn, J. (2011). Happiness Through Vacationing: Just a Temporary Boost or Long-Term Benefits?. Journal of Happiness Studies, 12(4), 651-665.", note: "Follow-up study asking whether vacationing gives a temporary boost or long-term benefit; the evidence pointed to short-lived effects.", link: doi("10.1007/s10902-010-9221-y"), kind: "doi" },
      { cite: "Nawijn, J. (2011). Determinants of Daily Happiness on Vacation. Journal of Travel Research, 50(5), 559-566.", note: "Daily-diary study of what determines happiness during a holiday itself, showing mood varies across the trip rather than being uniformly high.", link: doi("10.1177/0047287510379164"), kind: "doi" },
      { cite: "Gilbert, D., & Abdullah, J. (2004). Holidaytaking and the sense of well-being. Annals of Tourism Research, 31(1), 103-121.", note: "UK study comparing holiday-takers and non-holiday-takers on sense of wellbeing before and after the holiday period.", link: doi("10.1016/j.annals.2003.06.001"), kind: "doi" },
    ],
  },
  {
    id: "gs-travel-w2-group-vs-independent",
    goal: "travel", tier: "fundamental", section: "9059",
    title: "Choose the Travel Format That Matches Your Appetite for Uncertainty",
    subtitle: "Package tours buy predictability and service; independent travel buys flexibility and self-reliance—satisfaction follows fit",
    evidenceTag: "Moderate",
    impact: { magnitude: 2, latency: "weeks", durability: "sustained", effort: "low" },
    feeds: ["travel confidence", "planning skill"],
    description:
      "Tourism research describes independent travel as an evolving, loosely planned journey that trades certainty for flexibility, while group package tours are chosen for convenience, safety, price and the tour leader's service. Studies of backpackers versus mainstream tourists find the two groups are more alike than the stereotypes suggest. The honest reading is that neither format is superior; satisfaction depends on matching the format to your tolerance for uncertainty, budget and companions.",
    action: "Before booking your next trip, write down your tolerance for uncertainty (1–5), your budget and who is coming; if you score under 3 or are travelling with dependents, book a guided or partly packaged trip and use it to learn the destination for a later independent return.",
    sources: [
      { cite: "Hyde, K. F., & Lawson, R. (2003). The Nature of Independent Travel. Journal of Travel Research, 42(1), 13-23.", note: "Study of the nature of independent travel: itineraries evolve en route, planning is minimal and the traveller is willing to accept uncertainty.", link: doi("10.1177/0047287503253944"), kind: "doi" },
      { cite: "Wang, K.-C., Hsieh, A.-T., & Huan, T.-C. (2000). Critical service features in group package tour: An exploratory research. Tourism Management, 21(2), 177-189.", note: "Exploratory research on the critical service features of group package tours, including the role of the tour leader and pre-tour arrangements.", link: doi("10.1016/s0261-5177(99)00047-3"), kind: "doi" },
      { cite: "Wong, C.-k. S., & Kwong, W.-Y. Y. (2004). Outbound tourists' selection criteria for choosing all-inclusive package tours. Tourism Management, 25(5), 581-592.", note: "Survey of outbound tourists' selection criteria for all-inclusive package tours, identifying what buyers weigh when choosing a packaged trip.", link: doi("10.1016/j.tourman.2003.06.002"), kind: "doi" },
      { cite: "Larsen, S., Øgaard, T., & Brun, W. (2011). Backpackers and mainstreamers: Realities and myths. Annals of Tourism Research, 38(2), 690-707.", note: "Comparison of backpackers and mainstream tourists showing the popular myths about backpackers largely do not hold; the two groups overlap substantially.", link: doi("10.1016/j.annals.2011.01.003"), kind: "doi" },
    ],
  },
  {
    id: "gs-travel-w2-slow-travel",
    goal: "travel", tier: "moderate", section: "9051",
    title: "Slow Travel: One Base, Two Weeks, Overland Where You Can",
    subtitle: "Slower modes and longer stays reshape the experience and cut emissions; the wellbeing evidence is qualitative",
    evidenceTag: "Emerging",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "moderate" },
    feeds: ["presence", "lower travel stress", "carbon reduction"],
    description:
      "Slow travel is defined in the tourism literature as travelling overland by slower modes, staying longer in fewer places and engaging with locality; Dickinson and Lumsdon link it directly to lower travel emissions. Oh, Assaf and Baloglu built a goal-driven model of slow tourism from qualitative work at US destinations and found slow and fast modes coexist and contribute differently to experience outcomes. The evidence base is conceptual and qualitative rather than controlled trials, so the wellbeing claims are plausible but not yet measured.",
    action: "Design your next trip around one base for at least a week, arrive overland if the journey is under ten hours, and cap planned activities at one per day, leaving afternoons unscheduled.",
    sources: [
      { cite: "Dickinson, J. E., Lumsdon, L. M., & Robbins, D. (2011). Slow travel: issues for tourism and climate change. Journal of Sustainable Tourism, 19(3), 281-300.", note: "Defines slow travel and sets out its issues for tourism and climate change, including the emissions case for slower modes and longer stays.", link: doi("10.1080/09669582.2010.524704"), kind: "doi" },
      { cite: "Lumsdon, L. M., & McGrath, P. (2011). Developing a conceptual framework for slow travel: a grounded theory approach. Journal of Sustainable Tourism, 19(3), 265-279.", note: "Grounded-theory framework for slow travel built from traveller interviews, identifying its core ingredients.", link: doi("10.1080/09669582.2010.519438"), kind: "doi" },
      { cite: "Oh, H., Assaf, A. G., & Baloglu, S. (2016). Motivations and Goals of Slow Tourism. Journal of Travel Research, 55(2), 205-219.", note: "Qualitative and survey research at four US destinations building a conceptual model and measurement scales for slow tourism motivations and goals.", link: doi("10.1177/0047287514546228"), kind: "doi" },
      { cite: "Conway, D., & Timms, B. F. (2010). Re-Branding Alternative Tourism in the Caribbean: The Case for 'Slow Tourism'. Tourism and Hospitality Research, 10(4), 329-344.", note: "Argues for slow tourism as a re-branding of alternative tourism in the Caribbean, with attention to local benefit and pace.", link: doi("10.1057/thr.2010.12"), kind: "doi" },
    ],
  },
  {
    id: "gs-travel-w2-family-travel",
    goal: "travel", tier: "moderate", section: "9052",
    title: "The Annual Family Trip as a Cohesion Ritual",
    subtitle: "Shared vacation activities are linked to family cohesion and communication; children and parents value different parts",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "moderate" },
    feeds: ["family cohesion", "shared memories"],
    description:
      "Lehto and colleagues found that family vacations were associated with better family functioning, and that the activities families do together on vacation relate to cohesion. Research contrasting parents' and children's perspectives shows they want different things from the same trip, and Shaw's interviews with parents found they explicitly invest in vacations to build children's memories. Reviews of the family benefits of travel support a positive association but note most studies are cross-sectional and self-reported.",
    action: "Put one family trip on the calendar for the next twelve months, let each child choose one activity, and hold a ten-minute family debrief on the last evening about what to repeat next year.",
    sources: [
      { cite: "Lehto, X. Y., Choi, S., Lin, Y.-C., & MacDermid, S. M. (2009). Vacation and family functioning. Annals of Tourism Research, 36(3), 459-479.", note: "Study linking family vacations to dimensions of family functioning such as cohesion and communication.", link: doi("10.1016/j.annals.2009.04.003"), kind: "doi" },
      { cite: "Lehto, X. Y., Lin, Y.-C., Chen, Y., & Choi, S. (2012). Family Vacation Activities and Family Cohesion. Journal of Travel & Tourism Marketing, 29(8), 835-850.", note: "Examined which family vacation activities were associated with family cohesion.", link: doi("10.1080/10548408.2012.730950"), kind: "doi" },
      { cite: "Durko, A. M., & Petrick, J. F. (2013). Family and Relationship Benefits of Travel Experiences: A Literature Review. Journal of Travel Research, 52(6), 720-730.", note: "Literature review of the family and relationship benefits of travel experiences, summarising the evidence base and its limits.", link: doi("10.1177/0047287513496478"), kind: "doi" },
      { cite: "Fu, X., Lehto, X., & Park, O. (2014). What Does Vacation do to our Family? Contrasting the Perspectives of Parents and Children. Journal of Travel & Tourism Marketing, 31(4), 461-475.", note: "Contrasted parents' and children's perspectives on what a family vacation does for the family.", link: doi("10.1080/10548408.2014.883350"), kind: "doi" },
      { cite: "Shaw, S. M., Havitz, M. E., & Delemere, F. M. (2008). \"I Decided to Invest in My Kids' Memories\": Family Vacations, Memories, and the Social Construction of the Family. Tourism Culture & Communication, 8(1), 13-26.", note: "Interview study in which parents described investing in family vacations to create children's memories and construct family identity.", link: doi("10.3727/109830408783900361"), kind: "doi" },
    ],
  },
  {
    id: "gs-travel-w2-jet-lag",
    goal: "travel", tier: "moderate", section: "9057",
    title: "A Jet-Lag Protocol Built on Light Timing, Not Gadgets",
    subtitle: "Melatonin probably reduces symptoms; scheduled light and darkness are the mechanism; most other interventions have failed in trials",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "days", durability: "transient", effort: "moderate" },
    feeds: ["arrival alertness", "sleep timing"],
    description:
      "Circadian science says the clock shifts in response to the timing of light and darkness, and a summary of four systematic reviews concluded oral melatonin probably reduces jet-lag symptoms with mild adverse effects at most. A systematic review of non-pharmacological interventions found nine of thirteen studies showed no significant benefit, which the authors attributed to poorly designed light schedules that ignored darkness. Athlete reviews find long-haul travel raises perceived jet lag and disturbs physiology, with inconclusive effects on performance. Keep expectations modest and plan light exposure by destination time.",
    action: "For your next eastward trip of five or more time zones, start going to bed 30–60 minutes earlier for three nights before departure, seek morning daylight and avoid evening light on arrival, and keep any melatonin use low-dose and timed to destination bedtime after discussing it with a pharmacist or clinician.",
    sources: [
      { cite: "Tortorolo, F., Farren, F., & Rada, G. (2015). Is melatonin useful for jet lag?. Medwave, 15(Suppl 3), e6343.", note: "Structured summary of four systematic reviews (11 randomised trials): oral melatonin probably reduces jet-lag symptoms, with adverse effects unclear but probably mild.", link: doi("10.5867/medwave.2015.6343"), kind: "doi" },
      { cite: "Bin, Y. S., Postnova, S., & Cistulli, P. A. (2018). What works for jetlag? A systematic review of non-pharmacological interventions. Sleep Medicine Reviews, 43, 47-59.", note: "Systematic review of 13 non-pharmacological jet-lag interventions: nine found no significant change, three mixed, one positive, largely because light was scheduled without darkness.", link: doi("10.1016/j.smrv.2018.09.005"), kind: "doi" },
      { cite: "Janse van Rensburg, D. C. C., Jansen van Rensburg, A., Fowler, P., Fullagar, H., Stevens, D., Halson, S., Bender, A., Vincent, G., Claassen-Smithers, A., Dunican, I., Roach, G. D., Sargent, C., Lastella, M., & Cronje, T. (2020). How to manage travel fatigue and jet lag in athletes? A systematic review of interventions. British Journal of Sports Medicine, 54(16), 960-968.", note: "Systematic review of 22 studies on managing travel fatigue and jet lag in athletes: evidence quality was low and no literature addressed travel fatigue itself.", link: doi("10.1136/bjsports-2019-101635"), kind: "doi" },
      { cite: "Rossiter, A., Warrington, G. D., & Comyns, T. M. (2022). Effects of Long-Haul Travel on Recovery and Performance in Elite Athletes: A Systematic Review. Journal of Strength and Conditioning Research, 36(11), 3234-3245.", note: "Systematic review of 14 studies (197 elite athletes): long-haul travel increased perceived jet lag and disturbed physiological markers, sleep was not impaired, and performance effects were inconclusive.", link: doi("10.1519/JSC.0000000000004021"), kind: "doi" },
      { cite: "Ahmed, O., Ibrahiam, A. T., Al-Qassab, Z. M., Kannan, V., Ullah, N., Geddada, S., & Nassar, S. T. (2024). Unraveling the Impact of Travel on Circadian Rhythm and Crafting Optimal Management Approaches: A Systematic Review. Cureus, 16(10), e71316.", note: "Recent systematic review of interventions to realign circadian rhythm after travel, covering melatonin, personalised light and chrono-modulation.", link: doi("10.7759/cureus.71316"), kind: "doi" },
    ],
  },
  {
    id: "gs-travel-w2-digital-detox",
    goal: "travel", tier: "moderate", section: "9058",
    title: "A Disconnected Trip: Three Days With the Phone Off",
    subtitle: "Digital-free travellers report anxiety, then liberation; smartphone-restriction trials improve sleep and attention",
    evidenceTag: "Emerging",
    impact: { magnitude: 3, latency: "days", durability: "transient", effort: "moderate" },
    feeds: ["presence", "sleep", "attention"],
    description:
      "Cai, McKenna and Waizenegger followed 24 travellers through diaries and interviews and mapped an emotional arc from withdrawal anxiety to enjoyment and liberation once disconnected. Motivational studies find people seek digital-free trips to escape and reconnect, and campsite research shows the tension between wanting to disconnect and staying reachable. Outside tourism, randomised trials of smartphone restriction report better sleep efficiency and time-of-day cognitive performance. The honest boundary: tourism studies are small and qualitative; expect the first day to be uncomfortable.",
    action: "On your next trip, run a 72-hour digital-free block: tell two people how to reach you in an emergency, switch the phone fully off, carry a paper map and a notebook, and write one page each evening about what you noticed.",
    sources: [
      { cite: "Cai, W., McKenna, B., & Waizenegger, L. (2020). Turning It Off: Emotions in Digital-Free Travel. Journal of Travel Research, 59(5), 909-927.", note: "Diary and interview study of 24 travellers on digital-free trips, charting emotional episodes from initial anxiety through withdrawal to enjoyment and liberation.", link: doi("10.1177/0047287519868314"), kind: "doi" },
      { cite: "Egger, I., Lei, S. I., & Wassler, P. (2020). Digital free tourism – An exploratory study of tourist motivations. Tourism Management, 79, 104098.", note: "Exploratory study of the motivations behind digital-free tourism, such as escape, relaxation and reconnection with self and others.", link: doi("10.1016/j.tourman.2020.104098"), kind: "doi" },
      { cite: "Dickinson, J. E., Hibbert, J. F., & Filimonau, V. (2016). Mobile technology and the tourist experience: (Dis)connection at the campsite. Tourism Management, 57, 193-201.", note: "Campsite study of mobile technology and the tourist experience, showing how campers negotiate disconnection with the pull to stay connected.", link: doi("10.1016/j.tourman.2016.06.005"), kind: "doi" },
      { cite: "Alaya, W. B., Dhahbi, W., Souissi, M. A., Jebabli, N., Ceylan, H. İ., Ceylan, N. B., Muntean, R. I., & Souissi, N. (2026). Progressive Smartphone Restriction Combined with Psychoeducational Guidance and Pre-Sleep Autonomic Regulation Improves Sleep Efficiency and Time-of-Day Cognitive Performance in Physically Active Students with Nomophobia: A Randomized Controlled Trial. Life, 16(2).", note: "Randomised controlled trial of progressive smartphone restriction with psychoeducation and pre-sleep regulation, improving sleep efficiency and time-of-day cognitive performance in students with nomophobia.", link: doi("10.3390/life16020212"), kind: "doi" },
      { cite: "Farrukh, S., Reza, S., Babar, S., Alam, M. F., & Imtiaz, M. (2025). From screens to serenity: evaluating the effect of digital detox on mental and physiological health. BMC Medical Education, 25(1), 1738.", note: "Study evaluating the effect of a digital detox on mental and physiological health measures in students.", link: doi("10.1186/s12909-025-08267-4"), kind: "doi" },
      { cite: "Vu, T. H., & Tagliabue, M. (2025). Active nudging towards digital well-being: reducing excessive screen time on mobile phones and potential improvement for sleep quality. Frontiers in Psychiatry, 16, 1602997.", note: "Nudging intervention that reduced excessive mobile screen time, with potential improvement in sleep quality.", link: doi("10.3389/fpsyt.2025.1602997"), kind: "doi" },
    ],
  },
  {
    id: "gs-travel-w2-later-life-cognition",
    goal: "travel", tier: "moderate", section: "9060",
    title: "Keep Travelling After 65: Trips as Cognitive Reserve",
    subtitle: "Travel as a hobby predicted lower dementia incidence in a large Japanese cohort; leisure engagement protects cognition",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "months", durability: "lasting", effort: "moderate" },
    feeds: ["cognitive reserve", "social engagement", "novelty"],
    description:
      "In a six-year Japanese cohort of 49,705 older adults, travel as a hobby was associated with a lower hazard of incident dementia in both men (0.80) and women (0.76), and risk fell as the number of hobbies rose. The classic Bronx cohort found leisure activities such as reading, games and dancing were linked to lower dementia risk, and tourism researchers have proposed travel as a positive-psychology intervention for dementia. The boundary: these are observational associations vulnerable to reverse causation—healthier people travel more—so travel is best seen as one component of an engaged life.",
    action: "If you or a parent are over 65, schedule at least two trips a year that involve new places, planning and other people, and pair them with two other regular hobbies; keep the trips physically active with daily walking.",
    sources: [
      { cite: "Ling, L., Tsuji, T., Nagamine, Y., Miyaguni, Y., & Kondo, K. (2020). Types and number of hobbies and incidence of dementia among older adults: A six-year longitudinal study from the Japan Gerontological Evaluation Study (JAGES). Nihon Koshu Eisei Zasshi (Japanese Journal of Public Health), 67(11), 800-810.", note: "JAGES cohort of 49,705 adults aged 65+ followed six years: travel as a hobby was associated with lower dementia incidence (hazard ratios 0.80 in men, 0.76 in women) and more hobbies meant lower risk.", link: doi("10.11236/jph.67.11_800"), kind: "doi" },
      { cite: "Verghese, J., Lipton, R. B., Katz, M. J., Hall, C. B., Derby, C. A., Kuslansky, G., Ambrose, A. F., Sliwinski, M., & Buschke, H. (2003). Leisure activities and the risk of dementia in the elderly. The New England Journal of Medicine, 348(25), 2508-16.", note: "Bronx Aging Study: participation in cognitively engaging leisure activities was associated with a reduced risk of dementia over follow-up.", link: doi("10.1056/NEJMoa022252"), kind: "doi" },
      { cite: "Wen, J., Zheng, D., Hou, H., Phau, I., & Wang, W. (2022). Tourism as a dementia treatment based on positive psychology. Tourism Management, 92, 104556.", note: "Conceptual paper proposing tourism as a dementia intervention grounded in positive psychology, mapping travel elements to known protective factors.", link: doi("10.1016/j.tourman.2022.104556"), kind: "doi" },
      { cite: "Smith, L., Veronese, N., López-Sánchez, G. F., Yang, L., Pizzol, D., Butler, L. T., Barnett, Y., Felez-Nobrega, M., Jacob, L., Shin, J. I., Tully, M. A., Gorely, T., Oh, H., & Koyanagi, A. (2021). Active Travel and Mild Cognitive Impairment among Older Adults from Low- and Middle-Income Countries. Journal of Clinical Medicine, 10(6).", note: "Multi-country analysis of active travel (walking or cycling to get places) and mild cognitive impairment among older adults in low- and middle-income countries.", link: doi("10.3390/jcm10061243"), kind: "doi" },
      { cite: "Phansikar, M., & Mullen, S. P. (2019). Exploring Active Travel and Leisure-Time Physical Activity Relationships With Cognition Among Older Adults. Journal of Aging and Physical Activity, 28(4), 580-587.", note: "Explored how active travel and leisure-time physical activity relate to cognition in older adults.", link: doi("10.1123/japa.2019-0125"), kind: "doi" },
    ],
  },
  {
    id: "gs-travel-w2-culture-shock",
    goal: "travel", tier: "moderate", section: "9062",
    title: "Plan for the Dip: Culture Shock and the Harder Return Home",
    subtitle: "The neat U-curve of adjustment was not supported longitudinally; re-entry is often harder than departure",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "moderate" },
    feeds: ["adaptability", "emotional regulation abroad"],
    description:
      "The popular U-curve (honeymoon, crisis, recovery) was extended to a W-curve to include re-entry, but Ward's longitudinal study of sojourners found adjustment problems were greatest at entry and decreased over time rather than following a U. Ward and Kennedy distinguish psychological adjustment (mood) from sociocultural adaptation (skills), which improve on different timelines, and reviews of re-entry show returning home is frequently more disorienting than going abroad because nobody expects it.",
    action: "Before any stay abroad of a month or more, write a one-page plan for the first two weeks (routines, two social anchors, one weekly call home) and a matching plan for the two weeks after you return.",
    sources: [
      { cite: "Gullahorn, J. T., & Gullahorn, J. E. (1963). An Extension of the U-Curve Hypothesis. Journal of Social Issues, 19(3), 33-47.", note: "Classic extension of the U-curve hypothesis to a W-curve, adding the re-entry phase after returning home.", link: doi("10.1111/j.1540-4560.1963.tb00447.x"), kind: "doi" },
      { cite: "Ward, C., Okura, Y., Kennedy, A., & Kojima, T. (1998). The U-Curve on trial: a longitudinal study of psychological and sociocultural adjustment during cross-cultural transition. International Journal of Intercultural Relations, 22(3), 277-291.", note: "Longitudinal study of Japanese students in New Zealand: adjustment difficulties were greatest at entry and decreased over time, not supporting the U-curve.", link: doi("10.1016/s0147-1767(98)00008-x"), kind: "doi" },
      { cite: "Ward, C., & Kennedy, A. (1999). The measurement of sociocultural adaptation. International Journal of Intercultural Relations, 23(4), 659-677.", note: "Introduces and validates the Sociocultural Adaptation Scale, separating skill-based adaptation from psychological wellbeing.", link: doi("10.1016/s0147-1767(99)00014-0"), kind: "doi" },
      { cite: "Szkudlarek, B. (2010). Reentry—A review of the literature. International Journal of Intercultural Relations, 34(1), 1-21.", note: "Review of the re-entry literature: returning home is a distinct transition with its own difficulties and is under-prepared for.", link: doi("10.1016/j.ijintrel.2009.06.006"), kind: "doi" },
      { cite: "Martin, J. N. (1984). The intercultural reentry: Conceptualization and directions for future research. International Journal of Intercultural Relations, 8(2), 115-134.", note: "Early conceptualisation of intercultural re-entry and the research agenda it set.", link: doi("10.1016/0147-1767(84)90035-X"), kind: "doi" },
    ],
  },
  {
    id: "gs-travel-w2-solo-female",
    goal: "travel", tier: "moderate", section: "9069",
    title: "Solo Female Travel: Manage the Geography of Fear, Keep the Freedom",
    subtitle: "Women travelling alone report specific constraints and harassment risks alongside strong gains in confidence and self",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "weeks", durability: "lasting", effort: "moderate" },
    feeds: ["self-efficacy", "risk judgement"],
    description:
      "Wilson and Little's interviews with solo women travellers describe a 'geography of women's fear' that shapes where and when they go, while Yang and colleagues' work with Asian solo female travellers shows risk-taking is also how they construct space and self. A systematic review of risk and gender in tourism finds women's risk is under-researched, and Bianchi's study of solo travellers identifies what drives satisfaction and dissatisfaction. The practical stance: precise, place-specific precautions rather than blanket avoidance.",
    action: "For your next solo trip, research destination-specific safety for women from at least two independent sources, book the first two nights in advance, share a live itinerary with one person, and set one non-negotiable rule for night-time transport.",
    sources: [
      { cite: "Wilson, E., & Little, D. E. (2008). The Solo Female Travel Experience: Exploring the 'Geography of Women's Fear'. Current Issues in Tourism, 11(2), 167-186.", note: "Interview study of solo women travellers exploring how fear shapes their spatial behaviour and the strategies they use.", link: doi("10.2167/cit342.0"), kind: "doi" },
      { cite: "Yang, E. C. L., Khoo-Lattimore, C., & Arcodia, C. (2018). Constructing Space and Self through Risk Taking: A Case of Asian Solo Female Travelers. Journal of Travel Research, 57(2), 260-272.", note: "Asian solo female travellers: risk-taking as a means of constructing space and self, with safety negotiated rather than avoided.", link: doi("10.1177/0047287517692447"), kind: "doi" },
      { cite: "Yang, E. C. L., Khoo-Lattimore, C., & Arcodia, C. (2017). A systematic literature review of risk and gender research in tourism. Tourism Management, 58, 89-100.", note: "Systematic literature review of risk and gender research in tourism, mapping what is known about women's travel risk.", link: doi("10.1016/j.tourman.2016.10.011"), kind: "doi" },
      { cite: "Bianchi, C. (2016). Solo Holiday Travellers: Motivators and Drivers of Satisfaction and Dissatisfaction. International Journal of Tourism Research, 18(2), 197-208.", note: "Study of solo holiday travellers' motivators and the drivers of their satisfaction and dissatisfaction.", link: doi("10.1002/jtr.2049"), kind: "doi" },
    ],
  },
  {
    id: "gs-travel-w2-sustainable-choices",
    goal: "travel", tier: "moderate", section: "9067",
    title: "Fly Less, Stay Longer: The Honest Version of Sustainable Travel",
    subtitle: "Flights dominate a trip's footprint and most travellers do not act on green attitudes; the effective levers are few",
    evidenceTag: "Strong",
    impact: { magnitude: 2, latency: "months", durability: "lasting", effort: "moderate" },
    feeds: ["carbon literacy", "values-behaviour alignment"],
    description:
      "Lenzen and colleagues estimated tourism's carbon footprint at roughly 8% of global emissions, with air travel the dominant component, and Wynes and Nicholas rank avoiding a transatlantic flight among the highest-impact individual actions. Juvan and Dolnicar documented the attitude–behaviour gap: environmentally minded people rarely change their holiday behaviour, and Cohen's 'binge flying' work shows frequent flying resists change. The honest verdict is that small on-site gestures (towel reuse) are marginal; the levers that matter are flight frequency, distance, trip length and ground transport.",
    action: "For the next year, set a personal flight budget (for example, one long-haul return or three short-haul flights), replace one planned flight with a train or a longer single stay, and track the decision in your travel notes.",
    sources: [
      { cite: "Lenzen, M., Sun, Y.-Y., Faturay, F., Ting, Y.-P., Geschke, A., & Malik, A. (2018). The carbon footprint of global tourism. Nature Climate Change, 8(6), 522-528.", note: "Global multi-regional input-output analysis estimating the carbon footprint of tourism and its growth, with transport as the main driver.", link: doi("10.1038/s41558-018-0141-x"), kind: "doi" },
      { cite: "Wynes, S., & Nicholas, K. A. (2017). The climate mitigation gap: education and government recommendations miss the most effective individual actions. Environmental Research Letters, 12(7), 074024.", note: "Ranks individual climate actions by impact, placing avoiding air travel among the most effective personal choices.", link: doi("10.1088/1748-9326/aa7541"), kind: "doi" },
      { cite: "Juvan, E., & Dolnicar, S. (2014). The attitude–behaviour gap in sustainable tourism. Annals of Tourism Research, 48, 76-95.", note: "Interview study documenting the attitude–behaviour gap in sustainable tourism: pro-environmental people rationalise unchanged holiday behaviour.", link: doi("10.1016/j.annals.2014.05.012"), kind: "doi" },
      { cite: "Cohen, S. A., Higham, J. E. S., & Cavaliere, C. T. (2011). Binge flying: Behavioural addiction and climate change. Annals of Tourism Research, 38(3), 1070-1089.", note: "Introduces 'binge flying' as a behavioural pattern resistant to climate concern.", link: doi("10.1016/j.annals.2011.01.013"), kind: "doi" },
      { cite: "Hares, A., Dickinson, J., & Wilkes, K. (2010). Climate change and the air travel decisions of UK tourists. Journal of Transport Geography, 18(3), 466-473.", note: "UK tourists' air travel decisions showed climate change played little role in choices.", link: doi("10.1016/j.jtrangeo.2009.06.018"), kind: "doi" },
      { cite: "Gössling, S., & Humpe, A. (2020). The global scale, distribution and growth of aviation: Implications for climate change. Global Environmental Change, 65, 102194.", note: "Analysis of the global scale, distribution and growth of aviation and what it implies for climate change, including how concentrated flying is among frequent flyers.", link: doi("10.1016/j.gloenvcha.2020.102194"), kind: "doi" },
      { cite: "Gössling, S., & Peeters, P. (2007). 'It Does Not Harm the Environment!' An Analysis of Industry Discourses on Tourism, Air Travel and the Environment. Journal of Sustainable Tourism, 15(4), 402-417.", note: "Analysis of tourism-industry discourses that downplay aviation's environmental harm; useful for reading marketing claims critically.", link: doi("10.2167/jost672.0"), kind: "doi" },
    ],
  },
  {
    id: "gs-travel-w2-camino",
    goal: "travel", tier: "advanced", section: "9050",
    title: "Walk a Multi-Week Pilgrimage (the Camino de Santiago)",
    subtitle: "Pilgrims report restoration, reflection and stronger bonds; a 758 km walk improved cardiovascular risk markers",
    evidenceTag: "Emerging",
    impact: { magnitude: 4, latency: "weeks", durability: "lasting", effort: "high" },
    feeds: ["reflection", "physical fitness", "relationship repair"],
    description:
      "Survey research on 745 Camino pilgrims from 49 countries found more than three-quarters described an enduring attachment to the route, reporting physical and emotional restoration, self-reflection and stronger social bonds. A small before-after study of a 758 km pilgrimage found improved cardiovascular disease risk markers, exploratory work links the walk to marital and family relationship effects, and older adults describe adventure and spiritual restoration as motives. The evidence is largely self-report and uncontrolled; a Campbell scoping review of long-distance walking is under way.",
    action: "Choose a pilgrimage or long-distance route of at least ten days within the next year, train with three 15–20 km walks a week for eight weeks beforehand, and keep a daily written reflection while walking.",
    sources: [
      { cite: "Mróz, F., Roszak, P., & Krogmann, A. (2026). Social, Health, and Religious Contexts of Caminophilia: Fascination and Attachment to the Camino de Santiago. Journal of Religion and Health, 65(4), 3197-3225.", note: "Survey of 745 pilgrims from 49 countries (2022–2025): over 75% self-identified as 'caminophiles', reporting restoration, self-reflection, transformation and social bonds.", link: doi("10.1007/s10943-026-02623-4"), kind: "doi" },
      { cite: "Harris, M. B., & Wolf, M. R. (2013). Cardiovascular disease risk following a 758 km pilgrimage. International Journal of Sports Medicine, 34(8), 727-31.", note: "Before-after study of cardiovascular disease risk markers in participants completing a 758 km pilgrimage walk.", link: doi("10.1055/s-0032-1331172"), kind: "doi" },
      { cite: "Tykarski, S., & Mróz, F. (2023). The Pilgrimage on the Camino de Santiago and Its Impacts on Marital and Familial Relationships: An Exploratory Study. Journal of Religion and Health, 63(1), 109-132.", note: "Exploratory study of the Camino's impacts on pilgrims' marital and familial relationships.", link: doi("10.1007/s10943-023-01825-4"), kind: "doi" },
      { cite: "Nelson-Becker, H., Pickard, J. G., & Sichling, F. (2023). Adventure and Spiritual Restoration: Older Adult Motivations for Undertaking a Pilgrimage on El Camino de Santiago. Journal of Gerontological Social Work, 66(6), 822-838.", note: "Qualitative study of older adults' motivations for undertaking the Camino: adventure and spiritual restoration.", link: doi("10.1080/01634372.2023.2181906"), kind: "doi" },
      { cite: "Roszak, P., & Mróz, F. (2024). The Camino de Santiago as a 'Spiritual Journey': A Contemporary Challenge to Religion?. Journal of Religion and Health, 63(6), 4861-4875.", note: "Examines the Camino as a 'spiritual journey' for contemporary walkers, including the non-religious.", link: doi("10.1007/s10943-024-02108-2"), kind: "doi" },
      { cite: "Sabri, H., Ghogomu, E. T., Barbeau, V., Howe, T., White, H., Li, Y., Liu, Q., Kong, W., Cruz, N. D., & Welch, V. (2026). Protocol: Long Distance Walking and Psychosocial Health and Wellbeing: A Scoping Review. Campbell Systematic Reviews, 22(2), 18911803261439277.", note: "Registered protocol for a Campbell scoping review of long-distance walking (20 km or more) and psychosocial health and wellbeing—the systematic evidence is still being assembled.", link: doi("10.1177/18911803261439277"), kind: "doi" },
      { cite: "Moulaei, K., Bastaminejad, S., & Haghdoost, A. (2024). Health challenges and facilitators of arbaeen pilgrimage: a scoping review. BMC Public Health, 24(1), 132.", note: "Scoping review of the health challenges and facilitators of the Arbaeen mass walking pilgrimage, a reminder that long walks carry infection, heat and injury risks.", link: doi("10.1186/s12889-024-17640-9"), kind: "doi" },
    ],
  },
  {
    id: "gs-travel-w2-language-immersion",
    goal: "travel", tier: "advanced", section: "9054",
    title: "Live in the Language: Immersion Abroad for Fluency",
    subtitle: "Study abroad and intensive domestic immersion beat the regular classroom for fluency; gains depend on actually using the language",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "months", durability: "lasting", effort: "high" },
    feeds: ["second-language fluency", "confidence speaking"],
    description:
      "Freed, Segalowitz and Dewey compared regular classroom, study-abroad and intensive domestic immersion French programs and found the immersion contexts produced the largest oral fluency gains, with the domestic immersion group gaining as much as or more than those abroad. Segalowitz and Freed's Spanish study found study-abroad learners outperformed classroom peers on oral measures, Llanes and Muñoz found even a short stay abroad made a difference, and Llanes' review shows gains concentrate in fluency and listening and depend on how much learners engage with locals.",
    action: "Commit to a four-week (or longer) stay where the language is spoken, arrange a homestay or language exchange for daily conversation, and log at least two hours of real speaking per day; if you cannot go, enrol in an intensive domestic immersion program instead.",
    sources: [
      { cite: "Freed, B. F., Segalowitz, N., & Dewey, D. P. (2004). Context of learning and second language fluency in French: Comparing regular classroom, study abroad, and intensive domestic immersion programs. Studies in Second Language Acquisition, 26(2).", note: "Compared regular classroom, study abroad and intensive domestic immersion contexts for French oral fluency; immersion contexts produced the greatest fluency gains.", link: doi("10.1017/s0272263104262064"), kind: "doi" },
      { cite: "Segalowitz, N., Freed, B., Collentine, J., Lafford, B., Lazar, N., & Díaz-Campos, M. (2004). A Comparison of Spanish Second Language Acquisition in Two Different Learning Contexts: Study Abroad and the Domestic Classroom. Frontiers: The Interdisciplinary Journal of Study Abroad, 10(1), 1-18.", note: "Spanish learners in study abroad versus the domestic classroom: the study-abroad context produced greater gains on oral proficiency and fluency measures.", link: doi("10.36366/frontiers.v10i1.130"), kind: "doi" },
      { cite: "Llanes, À., & Muñoz, C. (2009). A short stay abroad: Does it make a difference?. System, 37(3), 353-365.", note: "Found that even a short stay abroad produced measurable second-language gains compared with staying home.", link: doi("10.1016/j.system.2009.03.001"), kind: "doi" },
      { cite: "Llanes, À. (2011). The many faces of study abroad: an update on the research on L2 gains emerged during a study abroad experience. International Journal of Multilingualism, 8(3), 189-215.", note: "Review updating what is known about L2 gains during study abroad, including which skills gain most and why individual variation is so large.", link: doi("10.1080/14790718.2010.550297"), kind: "doi" },
    ],
  },
  {
    id: "gs-travel-w2-medical-tourism",
    goal: "travel", tier: "advanced", section: "9056",
    title: "Surgery Abroad: The Complication and Cost Record",
    subtitle: "Cosmetic and bariatric tourism carries documented infection, revision and follow-up gaps that fall on home health systems",
    evidenceTag: "Moderate",
    impact: { magnitude: 1, latency: "weeks", durability: "lasting", effort: "high" },
    callout: "Rated at the floor: the systematic evidence on medical and surgical tourism shows recurring surgical-site infections, complications and costly revisions treated back home, with fragmented follow-up and little outcome data from providers abroad. Price savings are real; the risk transfer is also real.",
    description:
      "A systematic review of medical and surgical tourism found the outcome literature thin and dominated by complication reports. Recent reviews document complications and costs to the UK National Health Service from outward medical tourism, surgical-site infections in returning medical tourists, and the cost burden of aesthetic-surgery complications treated at home centres. A large single-network series reports acceptable safety under strict protocols, which shows outcomes depend heavily on the specific provider rather than the country.",
    action: "If you are considering surgery abroad, do not book until you have verified the surgeon's credentials and facility accreditation in writing, arranged named follow-up care at home, and priced the cost of a complication or revision; if any of the three is unavailable, treat that as the answer.",
    sources: [
      { cite: "Foley, B. M., Haglin, J. M., Tanzer, J. R., & Eberson, C. P. (2019). Patient care without borders: a systematic review of medical and surgical tourism. Journal of Travel Medicine.", note: "Systematic review of medical and surgical tourism outcomes, finding limited high-quality data and frequent reports of complications managed after return.", link: doi("10.1093/jtm/taz049"), kind: "doi" },
      { cite: "England, C., Bromham, N., Needham-Taylor, A., Hounsome, J., Gillen, E., Ingram, B. J., Davies, J., Edwards, A., & Lewis, R. (2026). Complications and costs to the UK National Health Service due to outward medical tourism for elective surgery: a rapid review. BMJ Open, 16(1), e109050.", note: "Rapid review of the complications and costs to the UK NHS arising from elective surgery abroad.", link: doi("10.1136/bmjopen-2025-109050"), kind: "doi" },
      { cite: "Kelly, S., O'Sullivan, B., White, M., Reidy, N., Doherty, A., Clover, J., Egan, C., Mc Dermott, S., Woods, J., O'Dwyer, Á., Heneghan, H. M., Potter, S., Feeley, A., Humphreys, H., & O'Neill, E. (2026). Surgical site infections in the returning medical tourist: bridging the knowledge gap and identifying areas for improvement. The Journal of Hospital Infection, 174, 380-388.", note: "Review of surgical-site infections in returning medical tourists and gaps in surveillance and management.", link: doi("10.1016/j.jhin.2026.05.033"), kind: "doi" },
      { cite: "Andreoli, S., Fischer, G., Danuser, K., Parodi, C., Schmauss, D., Holzbach, T., & Harder, Y. (2026). The cost burden resulting from post-surgical complications caused by aesthetic surgery abroad: A retrospective two-center experience. Journal of Plastic, Reconstructive & Aesthetic Surgery, 119, 234-242.", note: "Two-centre retrospective series quantifying the cost burden of treating complications from aesthetic surgery performed abroad.", link: doi("10.1016/j.bjps.2026.06.013"), kind: "doi" },
      { cite: "Nichol, B., Ray, D., Tanner, L., Oliver, E. J., Vlaev, I., Sniehotta, F., & McGowan, L. (2026). Decision-making about bariatric and cosmetic medical tourism from countries with universal healthcare: a rapid systematic review. Globalization and Health, 22(1).", note: "Rapid systematic review of how people from universal-healthcare countries decide on bariatric and cosmetic medical tourism, including what information they lack.", link: doi("10.1186/s12992-026-01207-x"), kind: "doi" },
      { cite: "Campbell, A., Restrepo, C., Luna-Pisciotti, T., & Hernandez, M. (2025). Safety and Outcomes in Plastic Surgery Medical Tourism: A Review of 2324 Patients and 7141 Procedures. Plastic and Reconstructive Surgery. Global Open, 13(9), e7113.", note: "Review of 2,324 patients and 7,141 procedures in one plastic-surgery medical-tourism program, showing safety depends on provider-level protocols.", link: doi("10.1097/GOX.0000000000007113"), kind: "doi" },
    ],
  },
  {
    id: "gs-travel-w2-volunteer-tourism",
    goal: "travel", tier: "advanced", section: "9068",
    title: "Volunteer Tourism: Why Short 'Voluntourism' Trips Are Rated at the Floor",
    subtitle: "Reviews document unskilled labour displacing local workers, dependency, orphanage harms and cross-cultural misunderstanding",
    evidenceTag: "Moderate",
    impact: { magnitude: 1, latency: "weeks", durability: "transient", effort: "high" },
    callout: "Rated at the floor for the standard short, unskilled, paid volunteer trip: the tourism literature documents possible negative impacts on host communities, the reinforcement of stereotypes rather than understanding, and locals' ambivalence about who the trips really serve. Skilled, long-term, community-led service is a different thing and is not what this cluster rates.",
    description:
      "Guttentag's review catalogued possible negative impacts of volunteer tourism including neglect of locals' desires, hindering work progress, completing unsatisfactory work, disrupting local economies and reinforcing conceptualisations of the 'other'. Raymond and Hall showed that cross-cultural understanding is not an automatic outcome and can become misunderstanding, Sin's fieldwork recorded locals asking who volunteers are responsible to, and Wearing and McGehee's review sets out the field's contested evidence. Any benefit accrues mostly to the volunteer.",
    action: "If you want to serve while travelling, skip short paid placements involving children or unskilled construction; instead give money to a vetted local organisation and, if you go, commit a skill you actually have for a month or more under local direction.",
    sources: [
      { cite: "Guttentag, D. A. (2009). The possible negative impacts of volunteer tourism. International Journal of Tourism Research, 11(6), 537-551.", note: "Review of the possible negative impacts of volunteer tourism on host communities, local labour, economies and cross-cultural perceptions.", link: doi("10.1002/jtr.727"), kind: "doi" },
      { cite: "Raymond, E. M., & Hall, C. M. (2008). The Development of Cross-Cultural (Mis)Understanding Through Volunteer Tourism. Journal of Sustainable Tourism, 16(5), 530-543.", note: "Shows that cross-cultural understanding is not an automatic product of volunteer tourism and can tip into misunderstanding without careful program design.", link: doi("10.1080/09669580802159610"), kind: "doi" },
      { cite: "Sin, H. L. (2010). Who are we responsible to? Locals' tales of volunteer tourism. Geoforum, 41(6), 983-992.", note: "Ethnographic study of locals' accounts of volunteer tourism, questioning who the volunteers are responsible to.", link: doi("10.1016/j.geoforum.2010.08.007"), kind: "doi" },
      { cite: "Wearing, S., & McGehee, N. G. (2013). Volunteer tourism: A review. Tourism Management, 38, 120-130.", note: "Comprehensive review of the volunteer tourism literature, its claimed benefits and its critiques.", link: doi("10.1016/j.tourman.2013.03.002"), kind: "doi" },
      { cite: "McGehee, N. G., & Santos, C. A. (2005). Social change, discourse and volunteer tourism. Annals of Tourism Research, 32(3), 760-779.", note: "Examined whether volunteer tourism fosters social-change discourse among participants, and under what conditions.", link: doi("10.1016/j.annals.2004.12.002"), kind: "doi" },
    ],
  },
  {
    id: "gs-travel-w2-study-abroad",
    goal: "travel", tier: "elite", section: "9053",
    title: "A Semester or Year Abroad as a Personality and Career Investment",
    subtitle: "Sojourners show gains in openness and agreeableness and drops in neuroticism; longer programs and social ties amplify the effect",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "months", durability: "lasting", effort: "high" },
    feeds: ["openness", "intercultural competence", "independence"],
    description:
      "Zimmermann and Neyer's longitudinal study of German students found those who went abroad increased in openness and agreeableness and decreased in neuroticism relative to peers who stayed, with new international relationships mediating the change; Greischel and colleagues found similar effects in adolescents on a year abroad, and Niehoff's work separates selection from socialisation effects. Deardorff's consensus model defines the intercultural competence outcome institutions aim for, and Dwyer's alumni study found longer programs produced more durable gains. Costs and access are the honest limit.",
    action: "If you or your child are in education, apply for a full semester or academic year abroad rather than a short trip, choose a program with a homestay or mixed-nationality housing, and set a goal of three friendships with locals by mid-stay.",
    sources: [
      { cite: "Zimmermann, J., & Neyer, F. J. (2013). Do we become a different person when hitting the road? Personality development of sojourners. Journal of Personality and Social Psychology, 105(3), 515-530.", note: "Longitudinal comparison of sojourning and non-sojourning students: sojourners gained in openness and agreeableness and decreased in neuroticism, mediated by new international relationships.", link: doi("10.1037/a0033019"), kind: "doi" },
      { cite: "Greischel, H., Noack, P., & Neyer, F. J. (2016). Sailing Uncharted Waters: Adolescent Personality Development and Social Relationship Experiences During a Year Abroad. Journal of Youth and Adolescence, 45(11), 2307-2320.", note: "Adolescents on a year abroad showed personality development and social-relationship experiences distinct from peers who stayed home.", link: doi("10.1007/s10964-016-0479-1"), kind: "doi" },
      { cite: "Niehoff, E., Petersdotter, L., & Freund, P. A. (2017). International sojourn experience and personality development: Selection and socialization effects of studying abroad and the Big Five. Personality and Individual Differences, 112, 55-61.", note: "Disentangles selection effects (who chooses to go) from socialisation effects (what the sojourn changes) in Big Five personality among study-abroad students.", link: doi("10.1016/j.paid.2017.02.043"), kind: "doi" },
      { cite: "Deardorff, D. K. (2006). Identification and Assessment of Intercultural Competence as a Student Outcome of Internationalization. Journal of Studies in International Education, 10(3), 241-266.", note: "Delphi consensus defining intercultural competence as a student outcome, the standard used to evaluate study-abroad programs.", link: doi("10.1177/1028315306287002"), kind: "doi" },
      { cite: "Dwyer, M. M. (2004). More Is Better: The Impact of Study Abroad Program Duration. Frontiers: The Interdisciplinary Journal of Study Abroad, 10(1), 151-164.", note: "Alumni study finding that longer study-abroad programs produced greater and more sustained academic, personal and career impacts.", link: doi("10.36366/frontiers.v10i1.139"), kind: "doi" },
    ],
  },
  {
    id: "gs-travel-w2-expat-wellbeing",
    goal: "travel", tier: "elite", section: "9065",
    title: "Take the Overseas Assignment, but Engineer the Adjustment",
    subtitle: "Expatriate adjustment is predictable from role clarity, spousal adjustment and support; expatriates report worse mental-health status than domestic peers",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "months", durability: "lasting", effort: "high" },
    feeds: ["cross-cultural adjustment", "career capital", "family resilience"],
    description:
      "Black, Mendenhall and Oddou's model distinguishes general, interaction and work adjustment, and the meta-analysis by Bhaskar-Shrinivas and colleagues (and Hechanova's) confirm the strongest predictors: role clarity and discretion, spouse and family adjustment, self-efficacy and social support, with time abroad following a curvilinear pattern. Truman's comparison found expatriate workers reported worse mental-health status than US domestic workers, and reviews of third-culture kids show children adjust but carry their own transition costs. The move pays when the family system is planned for, not just the job.",
    action: "Before accepting an assignment, negotiate in writing: a defined role, language and cultural training for the whole family, a spouse-career or activity plan, and an employee-assistance provider that operates in the destination; schedule a family check-in at 3, 6 and 12 months.",
    sources: [
      { cite: "Black, J. S., Mendenhall, M., & Oddou, G. (1991). Toward a Comprehensive Model of International Adjustment: An Integration of Multiple Theoretical Perspectives. The Academy of Management Review, 16(2), 291.", note: "Foundational model of international adjustment integrating anticipatory and in-country factors across general, interaction and work adjustment.", link: doi("10.2307/258863"), kind: "doi" },
      { cite: "Bhaskar-Shrinivas, P., Harrison, D. A., Shaffer, M. A., & Luk, D. M. (2005). Input-Based and Time-Based Models of International Adjustment: Meta-Analytic Evidence and Theoretical Extensions. Academy of Management Journal, 48(2), 257-281.", note: "Meta-analysis of expatriate adjustment predictors and time-based patterns, quantifying the roles of role clarity, spousal adjustment and support.", link: doi("10.5465/amj.2005.16928400"), kind: "doi" },
      { cite: "Hechanova, R., Beehr, T. A., & Christiansen, N. D. (2003). Antecedents and Consequences of Employees' Adjustment to Overseas Assignment: A Meta-analytic Review. Applied Psychology, 52(2), 213-236.", note: "Meta-analytic review of antecedents and consequences of employees' adjustment to overseas assignments.", link: doi("10.1111/1464-0597.00132"), kind: "doi" },
      { cite: "Truman, S. D., Sharar, D. A., & Pompe, J. C. (2011). The Mental Health Status of Expatriate Versus U.S. Domestic Workers. International Journal of Mental Health, 40(4), 3-18.", note: "Compared the mental-health status of expatriate workers with US domestic workers, finding poorer status among expatriates.", link: doi("10.2753/imh0020-7411400401"), kind: "doi" },
      { cite: "Takeuchi, R. (2010). A Critical Review of Expatriate Adjustment Research Through a Multiple Stakeholder View: Progress, Emerging Trends, and Prospects. Journal of Management, 36(4), 1040-1064.", note: "Critical review of expatriate adjustment research through a multiple-stakeholder lens, including spouses, children and host colleagues.", link: doi("10.1177/0149206309349308"), kind: "doi" },
      { cite: "Jones, E. M., Reed, M., Gaab, J., & Ooi, Y. P. (2022). Adjustment in third culture kids: A systematic review of literature. Frontiers in Psychology.", note: "Systematic review of adjustment in third-culture kids—the children who move with expatriate parents.", link: doi("10.3389/fpsyg.2022.939044"), kind: "doi" },
    ],
  },
  {
    id: "gs-travel-w2-retirement-abroad",
    goal: "travel", tier: "elite", section: "9066",
    title: "Retiring Abroad: Lifestyle Gains Now, Care Gaps Later",
    subtitle: "International retirement migrants report climate, cost and lifestyle benefits; frailty, care and return migration are the under-planned second act",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "months", durability: "lasting", effort: "high" },
    feeds: ["retirement lifestyle", "financial flexibility"],
    description:
      "Studies of North Europeans retiring to Spain and US retirees moving to Lake Chapala, Mexico document motives of climate, cost of living, pace of life and community, and Gustafson describes the transnational lifestyles retirees build between two countries. Hall and Hardill's 'other story' records what happens when retirement migrants become frail far from family and entitlement systems, and Warnes and Williams frame older migrants as a distinct policy group. The evidence is sociological rather than health-outcome data, and the risks cluster in the later years.",
    action: "If retirement abroad is on your list, spend at least two off-season months in the destination before selling anything, price private health cover and long-term care there, and write a return plan that names who would help if you became frail.",
    sources: [
      { cite: "Casado-Díaz, M. A. (2006). Retiring to Spain: An Analysis of Differences among North European Nationals. Journal of Ethnic and Migration Studies, 32(8), 1321-1339.", note: "Survey analysis of North European retirees in Spain, comparing nationalities on motives, integration and intentions.", link: doi("10.1080/13691830600928714"), kind: "doi" },
      { cite: "Sunil, T. S., Rojas, V., & Bradley, D. E. (2007). United States' international retirement migration: the reasons for retiring to the environs of Lake Chapala, Mexico. Ageing and Society, 27(4), 489-510.", note: "Study of US retirees around Lake Chapala, Mexico, on the reasons for retiring abroad, including cost, climate and community.", link: doi("10.1017/s0144686x07005934"), kind: "doi" },
      { cite: "Gustafson, P. (2001). Retirement migration and transnational lifestyles. Ageing and Society, 21(4), 371-394.", note: "Describes the transnational lifestyles of retirement migrants who divide time between origin and destination.", link: doi("10.1017/s0144686x01008327"), kind: "doi" },
      { cite: "Hall, K., & Hardill, I. (2016). Retirement migration, the 'other' story: caring for frail elderly British citizens in Spain. Ageing and Society, 36(3), 562-585.", note: "The 'other' story of retirement migration: the care needs of frail elderly British citizens in Spain and the gaps they encounter.", link: doi("10.1017/s0144686x14001342"), kind: "doi" },
      { cite: "Warnes, A. M., & Williams, A. (2006). Older Migrants in Europe: A New Focus for Migration Studies. Journal of Ethnic and Migration Studies, 32(8), 1257-1281.", note: "Positions older migrants in Europe as a new focus for migration studies, summarising their diversity and welfare issues.", link: doi("10.1080/13691830600927617"), kind: "doi" },
    ],
  },
];
