export type SupportInvention = {
  id: string;
  number: number;
  name: string;
  category: "Sensemaking" | "Action" | "Identity" | "Regulation" | "Relationships" | "Privacy";
  userValue: string;
  mechanism: string;
  starter: string;
  claimKernel: string;
};

export const SUPPORT_INVENTIONS: SupportInvention[] = [
  { id:"intervention-genome", number:1, name:"Intervention Genome", category:"Regulation", userValue:"Builds tiny support exercises around what actually fits you instead of giving everyone the same worksheet.", mechanism:"Breaks exercises into duration, effort, sensory mode, emotional intensity, privacy level, and social exposure, then recombines those dimensions from your feedback.", starter:"Describe one situation where you want a more useful response from yourself.", claimKernel:"Adaptive recombination of behavioral-support primitives from a user-specific engagement vector." },
  { id:"regulation-compiler", number:2, name:"Personal Regulation Compiler", category:"Regulation", userValue:"Turns your own words about what helps you reset into reusable, context-specific routines.", mechanism:"Converts natural-language self-instructions into short sequences that can be recompiled for home, work, nighttime, social, or high-pressure contexts.", starter:"Tell me what has helped you regain clarity or steadiness before, even once.", claimKernel:"Natural-language compilation of user-authored regulation instructions into context-variable support routines." },
  { id:"assumption-drawer", number:3, name:"Assumption Drawer", category:"Sensemaking", userValue:"Separates what you know from what your mind is filling in.", mechanism:"Sorts a concern into known facts, interpretations, predictions, missing information, and controllable actions without declaring one story psychologically correct.", starter:"Write the situation exactly as it is running through your head.", claimKernel:"Epistemic decomposition interface for user narratives with action extraction." },
  { id:"emotional-latency", number:4, name:"Emotional Latency Map", category:"Sensemaking", userValue:"Shows how long it usually takes you to notice, react to, and understand difficult moments.", mechanism:"Maps event time, noticed reaction, behavior, and later understanding to reveal your self-reported reaction-latency pattern.", starter:"Think of a recent moment that hit you emotionally. What happened first, and what did you realize later?", claimKernel:"Temporal mapping of event-to-recognition-to-behavior-to-insight intervals." },
  { id:"future-self-jury", number:5, name:"Future-Self Jury", category:"Action", userValue:"Lets several future versions of you weigh in on one decision.", mechanism:"Evaluates a choice from 24-hour, 30-day, one-year, and ten-year perspectives using only goals and principles you provide.", starter:"What decision are you trying to make right now?", claimKernel:"Multi-horizon self-simulation constrained by user-declared goals and values." },
  { id:"counterfactual-ledger", number:6, name:"Counterfactual Progress Ledger", category:"Identity", userValue:"Makes invisible wins visible — especially bad outcomes you prevented.", mechanism:"Records avoided arguments, delayed impulses, protected time, kept promises, and other non-events caused by better choices.", starter:"What did not happen recently because you handled something better than usual?", claimKernel:"Progress accounting based on beneficial counterfactual non-events rather than completed events alone." },
  { id:"micro-closure", number:7, name:"Micro-Closure Engine", category:"Regulation", userValue:"Helps unfinished reflection end with a small sense of completion instead of hanging open.", mechanism:"Detects unresolved threads in an exercise and offers a user-approved closure question, summary, or next action.", starter:"What feels unfinished in your head right now?", claimKernel:"Unresolved-thread detection followed by adaptive cognitive closure generation." },
  { id:"goal-gravity", number:8, name:"Goal Gravity Field", category:"Action", userValue:"Shows whether a choice is pulling you toward or away from what you say matters.", mechanism:"Represents goals as weighted directional objects and maps contemplated actions as vectors rather than good/bad judgments.", starter:"Name one goal and one choice you're considering.", claimKernel:"Directional action-to-goal vectorization across weighted user-defined objectives." },
  { id:"value-collision", number:9, name:"Value Collision Resolver", category:"Sensemaking", userValue:"Works on conflicts where two good values are fighting each other.", mechanism:"Identifies competing values and searches for actions that preserve more of both instead of forcing a binary choice.", starter:"What two things both matter to you but seem to conflict here?", claimKernel:"Constraint-solving over competing user-defined values with dual-preservation scoring." },
  { id:"identity-distance", number:10, name:"Identity Distance Meter", category:"Identity", userValue:"Shows the gap between the person you want to be and the choices you're actually making — without shaming you.", mechanism:"Translates user-defined qualities and recent self-reported behavior into directional alignment and one small corrective action.", starter:"What quality do you want to embody more consistently?", claimKernel:"User-authored identity vector compared with self-reported behavior vectors to derive minimum corrective action." },
  { id:"memory-palace", number:11, name:"Support Memory Palace", category:"Identity", userValue:"Turns insights, strengths, values, and coping resources into memorable 'rooms' you can revisit.", mechanism:"Spatially organizes user-approved resources into a virtual architecture for retrieval by place rather than menu search.", starter:"What is one lesson, person, phrase, or memory you never want to lose access to when things get hard?", claimKernel:"Spatial encoding and retrieval of user-approved psychosocial support resources." },
  { id:"metaphor-os", number:12, name:"Personal Metaphor OS", category:"Identity", userValue:"Lets Doctor Buddy explain things in the symbolic language that naturally clicks for you.", mechanism:"Learns only metaphors you choose and translates future exercises into those symbolic frameworks.", starter:"What worlds make instant sense to you — sports, chess, ocean, music, building, travel, something else?", claimKernel:"User-selected metaphor ontology dynamically mapped onto support interactions." },
  { id:"experience-refraction", number:13, name:"Experience Refraction", category:"Sensemaking", userValue:"Lets one event be viewed through several useful lenses before you lock onto a single meaning.", mechanism:"Renders facts, neutral observer, compassionate observer, future-self, systems, uncertainty, and opportunity views for user comparison.", starter:"Describe one event you may be seeing from only one angle.", claimKernel:"Parallel lens transformation of a single user event with user-controlled interpretation selection." },
  { id:"narrative-branches", number:14, name:"Narrative Branch Simulator", category:"Action", userValue:"Lets you rehearse several possible next chapters instead of treating one future as inevitable.", mechanism:"Builds branching scenarios from user-selected actions and goals while labeling them simulations, not predictions.", starter:"What unresolved situation would you like to see three possible next chapters for?", claimKernel:"Goal-constrained narrative branching from user-controlled action nodes." },
  { id:"meaning-gradient", number:15, name:"Meaning Gradient", category:"Sensemaking", userValue:"Moves you out of all-or-nothing interpretation by showing a spectrum of plausible meanings.", mechanism:"Builds a continuum from threatening to neutral to constructive interpretations and asks what evidence supports each.", starter:"What meaning are you currently giving this situation?", claimKernel:"Evidence-linked interpretation continuum generation without forced cognitive replacement." },
  { id:"story-action", number:16, name:"Story-to-Action Compiler", category:"Action", userValue:"Turns a long story into the few pieces you can actually do something with.", mechanism:"Extracts people, desired outcomes, unresolved questions, controllable variables, and smallest next actions from a narrative.", starter:"Tell the whole story the way you'd naturally tell it.", claimKernel:"Narrative decomposition into controllability graph and executable next-action set." },
  { id:"wisdom-recycler", number:17, name:"Personal Wisdom Recycler", category:"Identity", userValue:"Returns your own best advice to you when you need it.", mechanism:"Captures principles from advice you give and resurfaces them when a structurally similar situation appears later.", starter:"What's advice you've given someone else that you secretly know applies to you too?", claimKernel:"Semantic extraction and later analogical resurfacing of user-authored advice principles." },
  { id:"cross-time", number:18, name:"Cross-Time Conversation", category:"Identity", userValue:"Lets today's you compare notes with earlier versions of you.", mechanism:"Places prior user-approved reflections next to the present one and highlights changed beliefs, stable values, and repeated patterns.", starter:"What question would you want to ask a past version of yourself?", claimKernel:"Longitudinal self-dialogue using user-owned prior reflections with belief-change mapping." },
  { id:"narrative-checksum", number:19, name:"Narrative Checksum", category:"Sensemaking", userValue:"Stops the AI from quietly building on a misunderstanding of what you meant.", mechanism:"Summaries require a fast user correction loop; corrections become meaning preferences for later interactions when memory is enabled.", starter:"Tell me something that people or apps often misunderstand about how you describe your experience.", claimKernel:"User-validated semantic checksum layer for adaptive conversational interpretation." },
  { id:"identity-evidence", number:20, name:"Identity Evidence Vault", category:"Identity", userValue:"Builds confidence from receipts, not generic affirmations.", mechanism:"Creates strengths statements only from user-provided examples and keeps each statement traceable to its evidence.", starter:"Name something hard you handled better than you usually give yourself credit for.", claimKernel:"Evidence-traceable identity statement generation from user-authorized autobiographical events." },
  { id:"friction-fingerprint", number:21, name:"Friction Fingerprint", category:"Action", userValue:"Learns how you disengage so the app can stop fighting your attention.", mechanism:"Tracks user-selected friction such as length, choice overload, timing, repetition, or format and reshapes future exercises around it.", starter:"What makes you quit an app, exercise, conversation, or plan even when you wanted to continue?", claimKernel:"Interaction-friction phenotype used to adapt delivery dimensions of future support content." },
  { id:"shape-shifter", number:22, name:"Intervention Shape-Shifter", category:"Regulation", userValue:"Keeps the purpose of an exercise while changing its form until it fits you.", mechanism:"Transforms the same underlying task among dialogue, checklist, visualization, story, game, analogy, audio prompt, or single question.", starter:"Which format do you respond to best: talking, lists, stories, visuals, challenges, or one sharp question?", claimKernel:"Modality transformation preserving intervention objective while adapting interaction form." },
  { id:"minimum-reflection", number:23, name:"Minimum Effective Reflection", category:"Regulation", userValue:"Finds the shortest reflection that still gives you useful clarity.", mechanism:"Adjusts session length based on voluntary completion and user-rated usefulness rather than forcing fixed durations.", starter:"How much attention do you realistically have right now: 30 seconds, 2 minutes, 5 minutes, or more?", claimKernel:"Adaptive minimization of support-session length subject to user-rated utility threshold." },
  { id:"load-governor", number:24, name:"Cognitive Load Governor", category:"Regulation", userValue:"Makes the whole interaction lighter when your brain is overloaded.", mechanism:"Changes vocabulary, number of choices, screen density, and exercise complexity using the capacity level you choose right now.", starter:"Choose your current mental bandwidth: tiny, low, normal, or deep-focus.", claimKernel:"User-controlled real-time interface complexity scaling across linguistic and interaction dimensions." },
  { id:"decision-entropy", number:25, name:"Decision Entropy Meter", category:"Action", userValue:"Shrinks an overwhelming decision tree until one reversible next move remains.", mechanism:"Counts unresolved branches, groups dependent choices, and collapses low-value branches around a smallest reversible decision.", starter:"What decision currently feels like it has too many moving pieces?", claimKernel:"Decision-tree entropy reduction toward minimal reversible action." },
  { id:"streak-forgiveness", number:26, name:"Streak Forgiveness Protocol", category:"Identity", userValue:"Prevents one missed day from mathematically erasing months of progress.", mechanism:"Scores continuity using recovery, return speed, accumulated behavior, and recommitment instead of binary streak reset.", starter:"What habit or goal did you miss recently that made you feel like you were 'back at zero'?", claimKernel:"Continuity metric incorporating recovery dynamics rather than consecutive-event count alone." },
  { id:"momentum-preservation", number:27, name:"Momentum Preservation Engine", category:"Action", userValue:"Restarts you exactly where you fell off instead of making you begin again.", mechanism:"Stores the cognitive stopping point and offers a smaller continuation step matched to the reason you stopped.", starter:"What did you start but never finish — and where exactly did you lose momentum?", claimKernel:"Stateful resumption from user-specific abandonment point with friction-adaptive continuation." },
  { id:"effort-exchange", number:28, name:"Effort Exchange", category:"Action", userValue:"Makes time and attention tradeoffs visible like moving money between accounts.", mechanism:"Converts time removed from one activity into visible investment toward a user-selected priority.", starter:"Where is your attention leaking, and where would you rather invest it?", claimKernel:"Cross-goal effort reallocation ledger with user-defined value destinations." },
  { id:"challenge-ladder", number:29, name:"Confidence-Calibrated Challenge Ladder", category:"Action", userValue:"Keeps challenges neither too easy nor too overwhelming.", mechanism:"Adjusts difficulty from user confidence, completion, and perceived effort — not diagnostic or physiologic measurements.", starter:"Name one thing you want to practice and rate your confidence from 1–10.", claimKernel:"Closed-loop challenge adaptation using voluntary confidence, completion, and effort signals." },
  { id:"context-mutation", number:30, name:"Context Mutation Engine", category:"Action", userValue:"If something keeps failing, the app changes the conditions instead of blaming you.", mechanism:"Mutates time, duration, location category, modality, sequence, difficulty, and prompt style until a workable variant emerges.", starter:"What useful thing keeps failing even though you've tried more than once?", claimKernel:"Multi-dimensional context mutation loop for repeated user-declared task failure." },
  { id:"state-atlas", number:31, name:"Personal State Transition Atlas", category:"Regulation", userValue:"Maps how you move between states using your own names for them.", mechanism:"Lets users define states like 'foggy' or 'locked in' and records self-reported actions and contexts around transitions.", starter:"Name two states you commonly move between in your own language.", claimKernel:"User-defined state ontology with transition graph learned from self-reported contextual events." },
  { id:"state-bridge", number:32, name:"State Bridge Generator", category:"Regulation", userValue:"Reminds you what has previously helped you move from one state toward another.", mechanism:"Uses the user's own transition history to surface prior activities associated with movement toward a preferred state, without medical interpretation.", starter:"What state are you in now, and what state would you rather move toward?", claimKernel:"Personal transition-history retrieval for non-diagnostic state-to-state bridge generation." },
  { id:"sensory-translation", number:33, name:"Sensory Translation Engine", category:"Regulation", userValue:"Lets you work with an experience as an image, sound, distance, movement, or other representation when words aren't enough.", mechanism:"Converts user-described experience into chosen sensory metaphors and supports user-directed transformation of those representations.", starter:"If this feeling or situation had a shape, movement, distance, texture, or sound, what would it be?", claimKernel:"Cross-modal symbolic representation and user-directed transformation of subjective experience." },
  { id:"cognitive-zoom", number:34, name:"Cognitive Zoom Lens", category:"Sensemaking", userValue:"Shows how the same concern looks at five minutes, today, a month, a year, and a lifetime.", mechanism:"Re-renders one problem at multiple user-selected temporal scales to expose what changes and what remains important.", starter:"What feels enormous right now that you'd like to zoom in and out on?", claimKernel:"Multi-timescale reframing interface for subjective concern weighting." },
  { id:"attention-portfolio", number:35, name:"Attention Portfolio", category:"Action", userValue:"Treats attention like capital you can intentionally allocate.", mechanism:"Lets users assign mental-attention percentages to life areas and rebalance them toward personally chosen priorities.", starter:"Where did most of your attention go this week, and where do you wish it had gone?", claimKernel:"Portfolio-style allocation and rebalance model for user-declared attentional investment." },
  { id:"recovery-dividend", number:36, name:"Recovery Dividend", category:"Identity", userValue:"Makes intentional rest and reset visible as an investment rather than 'doing nothing.'", mechanism:"Tracks user-labeled reset time and links it to later self-rated capacity or follow-through without medical claims.", starter:"What kind of reset tends to leave you more capable afterward?", claimKernel:"Longitudinal linkage of user-labeled recovery investments to later self-rated capacity outcomes." },
  { id:"reaction-half-life", number:37, name:"Reaction Half-Life", category:"Sensemaking", userValue:"Shows how your own intensity ratings tend to change with time so 'right now' isn't mistaken for 'forever.'", mechanism:"Uses repeated user ratings to display personal decay curves for similar experiences without assigning diagnoses.", starter:"Rate the intensity now from 0–10 and tell me when it started.", claimKernel:"User-specific temporal decay modeling of self-rated experience intensity." },
  { id:"choice-buffer", number:38, name:"Trigger-to-Choice Buffer", category:"Regulation", userValue:"Builds a pause between a recurring situation and the response you later wish you'd changed.", mechanism:"Lets users insert a chosen question, countdown, phrase, future-self note, or ritual before a voluntary action.", starter:"What recurring situation makes you act faster than you want to?", claimKernel:"Personalized pre-action buffer dynamically selected from user-approved interruption mechanisms." },
  { id:"one-degree", number:39, name:"One-Degree Engine", category:"Action", userValue:"Finds a tiny directional move when the full goal feels impossible.", mechanism:"Generates the smallest action that meaningfully points toward a goal, then compounds only after successful completion.", starter:"Name a goal that currently feels too big to touch.", claimKernel:"Recursive micro-action generation with completion-gated scaling." },
  { id:"resilience-recipe", number:40, name:"Personal Resilience Recipe", category:"Regulation", userValue:"Builds a reusable recipe from the pieces you say actually helped you before.", mechanism:"Learns user-rated helpful components and recombines them for future difficult contexts instead of prescribing a universal routine.", starter:"Think of one hard day you handled surprisingly well. What ingredients helped?", claimKernel:"User-rated component learning and context-aware recombination into individualized resilience sequences." },
  { id:"boundary-simulator", number:41, name:"Relationship Boundary Simulator", category:"Relationships", userValue:"Lets you rehearse a difficult conversation against several response styles before you have it.", mechanism:"Simulates supportive, defensive, confused, dismissive, inquisitive, or angry counterparts while the user adjusts clarity, warmth, brevity, and firmness.", starter:"What conversation do you want to rehearse, and what boundary or request matters most?", claimKernel:"Multi-counterpart conversational simulation with user-controlled communication-dimension tuning." },
  { id:"conversation-tree", number:42, name:"Conversation Consequence Tree", category:"Relationships", userValue:"Shows how different wording can open different conversation paths without pretending to predict another person.", mechanism:"Branches a message into multiple plausible dialogue paths and labels all branches as simulation.", starter:"Paste or describe the message you're considering sending.", claimKernel:"Non-predictive branching simulation of communication variants and downstream dialogue states." },
  { id:"repair-lab", number:43, name:"Repair Sequence Laboratory", category:"Relationships", userValue:"Helps you design a repair conversation instead of improvising under pressure.", mechanism:"Lets users rearrange acknowledge, clarify, own, ask, boundary, and next-action components and rehearse the resulting flow.", starter:"What relationship rupture or misunderstanding are you trying to repair?", claimKernel:"Composable interpersonal repair-sequence engine with order-sensitive simulation." },
  { id:"reciprocity-map", number:44, name:"Relationship Reciprocity Map", category:"Relationships", userValue:"Makes patterns of requests, promises, effort, support, and cancellations visible without labeling anybody.", mechanism:"Maps user-entered reciprocal events while prohibiting personality or pathology labels for other people.", starter:"Which relationship feels hard to evaluate clearly right now?", claimKernel:"Event-based reciprocity mapping with label-suppression constraint." },
  { id:"perspective-exchange", number:45, name:"Perspective Exchange Chamber", category:"Relationships", userValue:"Compares two descriptions of the same event without making either person the villain.", mechanism:"Separates agreed facts, differing interpretations, unanswered questions, and possible shared goals from two independently supplied accounts.", starter:"Describe the event from your side. You can add the other person's account separately if you have it.", claimKernel:"Dual-narrative overlap/difference extraction with fact-interpretation separation." },
  { id:"context-capsule", number:46, name:"Selective Context Capsule", category:"Privacy", userValue:"Lets you share only the exact piece of context needed for one conversation instead of exposing your whole history.", mechanism:"Creates purpose-bound summaries from user-selected fields, with explicit preview and expiration metadata before sharing.", starter:"What are you trying to communicate, and what information should stay private?", claimKernel:"Purpose-scoped selective disclosure packet generated from user-authorized source elements." },
  { id:"consent-waterfall", number:47, name:"Consent Waterfall", category:"Privacy", userValue:"The app asks for less data first and only asks for more when a feature truly needs it.", mechanism:"Each workflow begins at minimum-data capability and requests additional categories only when the user selects a function requiring them.", starter:"Which feature are you trying to use, and how private do you want to keep the experience?", claimKernel:"Progressive data-permission escalation with functional fallback at each denied consent tier." },
  { id:"ephemeral-computing", number:48, name:"Ephemeral Reflection", category:"Privacy", userValue:"Lets sensitive reflection disappear instead of becoming permanent history unless you choose to save a takeaway.", mechanism:"Runs sessions without local persistence by default and allows the user to save only an approved distilled note.", starter:"What do you want to work through without keeping the raw reflection in your personal toolkit?", claimKernel:"User-controlled distillation from ephemeral session data into selectively retained output." },
  { id:"privacy-utility", number:49, name:"Privacy–Utility Dial", category:"Privacy", userValue:"Shows what personalization you gain before you share more information.", mechanism:"Pairs each optional data category with a plain-language explanation of the additional feature utility it enables.", starter:"Would you rather maximize privacy, personalization, or find a specific middle ground?", claimKernel:"Feature-level visualization and control of marginal utility per additional data category." },
  { id:"portable-model", number:50, name:"User-Owned Support Model", category:"Privacy", userValue:"Keeps the useful things Doctor Buddy learns about how to support you portable and under your control.", mechanism:"Builds an exportable model of user-approved preferences, goals, terminology, successful routines, and interaction style while optionally excluding raw conversations.", starter:"What should a new support system understand about you without needing your private conversation history?", claimKernel:"Portable user-owned adaptation model separated from raw conversational content." },
];

export const INVENTION_CATEGORIES = ["Sensemaking", "Action", "Identity", "Regulation", "Relationships", "Privacy"] as const;
