// Goal shelf, wave 3: TRAVEL — go traveling (sections 11001–11099).
// Widens the wave-1 (9000s) and wave-2 (9050s) travel shelves with new angles only.
// Verification: every DOI below was resolved against the Crossref record or the
// PubMed record on 2026-09-11 (ledger: shelves/travel.w3.ledger.json). See types.ts
// for the contract. Popular advice the evidence does not support is rated at the
// floor (magnitude 1) with a callout. Nothing here is medical advice: the medical
// clusters describe what studies tested so a member can have an informed
// conversation with a travel-medicine clinician.
import { doi, type GoalShelfCluster } from "../types";

export const SECTIONS: Record<string, string> = {
  "11001": "Family Travel With Teens & Reunions — Holidays That Hold Together",
  "11002": "Adventure Travel — Risk, Injury and the Operators Who Manage It",
  "11003": "Cruise Health — Outbreaks, Respiratory Illness and the Older Passenger",
  "11004": "Travel Scams, Crime & Safety — Perceived Risk vs Real Risk",
  "11005": "Accessible Travel — Disability and Dementia",
  "11006": "Senior Travel — Holidays, Health and Educational Programs in Later Life",
  "11007": "Frequent-Flyer Points — The Honest Verdict on Chasing Status",
  "11008": "Off-Season Travel — Crowding, Seasonality and the Shoulder Months",
  "11009": "Train, Road-Trip & RV Travel — The Long Overland Journey",
  "11010": "House Swapping, Couchsurfing & Peer-to-Peer Stays",
  "11011": "Food Tourism — Eating Local as the Point of the Trip",
  "11012": "Wellness & Yoga Retreats — What the Follow-Up Studies Show",
  "11013": "Meditation Retreats — Vipassana and Intensive Silent Practice",
  "11014": "Music Festivals — Wellbeing, Hearing and Harm Reduction",
  "11015": "Journaling on the Road — Writing and Rediscovery",
  "11016": "Motion Sickness — Habituation, Breathing and Medication",
  "11017": "Altitude — Ascent Rate and Prophylaxis (Described, Not Advised)",
  "11018": "Field Hygiene — Traveler's Diarrhea, Heat and Sun",
  "11019": "The Pre-Travel Clinic — Vaccines and Malaria Prophylaxis (Described)",
  "11020": "Travel With a Chronic Condition or in Pregnancy",
};

export const CLUSTERS: GoalShelfCluster[] = [
  {
    id: "gs-travel-w3-family-teens",
    goal: "travel", tier: "fundamental", section: "11001",
    title: "Plan the Trip With the Teenagers, Not for Them — and Keep One Reunion Trip on the Calendar",
    subtitle: "Shared decision-making, unstructured time together and the multigenerational reunion",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "low" },
    feeds: ["family cohesion", "adolescent connection", "memory-making"],
    description:
      "Qualitative and survey studies of family holidays find that parents and adolescents want different things from the same trip, that children increasingly act as co-decision makers, and that holidays carry mixed emotions for both generations — 'bliss or blitz'. What holds the group together is unstructured 'being together' time and activities the whole party chose. Reunion travel with the wider family has its own measured motivations (kinship, ritual, storytelling). The honest boundary: this is descriptive research, not trials; the mechanisms are plausible, the effect sizes unknown.",
    action: "Before booking the next family trip, hold a 20-minute planning meeting where each teenager names one activity that goes on the itinerary unchanged, and protect one unscheduled day. Put one multigenerational reunion trip on the calendar this year.",
    sources: [
      { cite: "Schänzel, H. A., & Smith, K. A. (2014). The socialization of families away from home: Group dynamics and family functioning on holiday. Leisure Sciences, 36(2), 126–143.", note: "Examines how family groups actually function while on holiday — the group dynamics, roles and negotiations that decide whether a trip strengthens or strains the family.", link: doi("10.1080/01490400.2013.857624"), kind: "doi" },
      { cite: "Carr, N. (2006). A comparison of adolescents' and parents' holiday motivations and desires. Tourism and Hospitality Research, 6(2), 129–142.", note: "Compares what adolescents and their parents each want from a holiday; the gap between the two is the reason teenagers need a real say in the plan.", link: doi("10.1057/palgrave.thr.6040051"), kind: "doi" },
      { cite: "Gram, M. (2007). Children as co-decision makers in the family? The case of family holidays. Young Consumers, 8(1), 19–28.", note: "Studies children's role in family holiday decisions; the case for treating them as co-planners rather than passengers.", link: doi("10.1108/17473610710733749"), kind: "doi" },
      { cite: "Gram, M., Therkelsen, A., & Larsen, J. R. K. (2018). Family bliss or blitz? Parents' and children's mixed emotions towards family holidays. Young Consumers, 19(2), 185–198.", note: "Documents the mixed emotions parents and children hold about family holidays — the realistic starting point for planning rather than the brochure version.", link: doi("10.1108/yc-06-2017-00703"), kind: "doi" },
      { cite: "Larsen, J. R. K. (2013). Family flow: The pleasures of 'being together' in a holiday home. Scandinavian Journal of Hospitality and Tourism, 13(3), 153–174.", note: "Describes 'family flow' — the pleasure of simply being together in a holiday home — the unstructured time this protocol tells you to protect.", link: doi("10.1080/15022250.2013.808523"), kind: "doi" },
      { cite: "Lehto, X. Y., Fu, X., Li, H., & Zhou, L. (2017). Vacation benefits and activities. Journal of Hospitality & Tourism Research, 41(3), 301–328.", note: "Links the activities families do on vacation to the benefits they report; supports choosing activities the whole party endorses.", link: doi("10.1177/1096348013515921"), kind: "doi" },
      { cite: "Kluin, J. Y., & Lehto, X. Y. (2012). Measuring family reunion travel motivations. Annals of Tourism Research, 39(2), 820–841.", note: "Develops a measure of why families travel to reunions — the evidence base for the multigenerational reunion trip as a distinct kind of travel.", link: doi("10.1016/j.annals.2011.09.008"), kind: "doi" },
      { cite: "Schänzel, H. A., & Yeoman, I. (2015). Trends in family tourism. Journal of Tourism Futures, 1(2), 141–147.", note: "Reviews the trends shaping family travel, including multigenerational trips; useful context for what a 'family holiday' now means.", link: doi("10.1108/jtf-12-2014-0006"), kind: "doi" },
    ],
  },
  {
    id: "gs-travel-w3-adventure-risk",
    goal: "travel", tier: "moderate", section: "11002",
    title: "Do the Adventure Activity — With an Operator Whose Safety Record You Checked",
    subtitle: "Injury surveillance says the risk is real, concentrated in a few activities, and manageable",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "days", durability: "sustained", effort: "moderate" },
    feeds: ["confidence", "novelty", "physical capability"],
    description:
      "New Zealand's injury surveillance of the adventure-tourism sector, and the follow-up survey of operators, mapped which activities generate claims and what operators do about it. Participants' own perception of risk is part of the appeal — the 'rush' resolves the paradox of paying to be scared — but it is poorly calibrated to the actual injury data. The honest boundary: the surveillance is national and dated; your specific operator's record matters more than the sector average.",
    action: "For any guided adventure activity this year, ask the operator two questions before paying — what their safety audit or certification is, and what their injury record was last season — and choose the one who answers both.",
    sources: [
      { cite: "Bentley, T. A., Page, S. J., & Laird, I. S. (2001). Accidents in the New Zealand adventure tourism industry. Safety Science, 38(1), 31–48.", note: "Foundational analysis of accidents across the New Zealand adventure-tourism industry — the first sector-wide picture of where injuries concentrate.", link: doi("10.1016/s0925-7535(00)00053-9"), kind: "doi" },
      { cite: "Bentley, T. A., Page, S., & Walker, L. (2006). The safety experience of New Zealand adventure tourism operators. Journal of Travel Medicine, 11(5), 280–286.", note: "Surveys operators on their safety experience and management practices; the basis for asking an operator about their own record.", link: doi("10.2310/7060.2004.19103"), kind: "doi" },
      { cite: "Bentley, T. A., Page, S. J., & Macky, K. A. (2007). Adventure tourism and adventure sports injury: The New Zealand experience. Applied Ergonomics, 38(6), 791–796.", note: "Reviews the New Zealand injury experience across adventure activities, distinguishing higher- and lower-risk activities.", link: doi("10.1016/j.apergo.2006.10.007"), kind: "doi" },
      { cite: "Cater, C. I. (2006). Playing with risk? Participant perceptions of risk and management implications in adventure tourism. Tourism Management, 27(2), 317–325.", note: "Shows that participants' perceived risk is part of the product and diverges from actual risk — why you should check records rather than trust your gut.", link: doi("10.1016/j.tourman.2004.10.005"), kind: "doi" },
      { cite: "Buckley, R. (2012). Rush as a key motivation in skilled adventure tourism: Resolving the risk recreation paradox. Tourism Management, 33(4), 961–970.", note: "Explains the 'rush' that motivates skilled adventure participants and resolves why people seek activities they perceive as risky.", link: doi("10.1016/j.tourman.2011.10.002"), kind: "doi" },
    ],
  },
  {
    id: "gs-travel-w3-cruise-health",
    goal: "travel", tier: "moderate", section: "11003",
    title: "Cruise Without Catching the Ship's Bug — Hand Hygiene, the Flu Shot and Knowing the Base Rates",
    subtitle: "Norovirus and respiratory outbreaks are the two documented risks of a closed ship",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "days", durability: "transient", effort: "low" },
    feeds: ["health on the road", "risk literacy"],
    description:
      "Outbreak investigations and multi-year prospective studies aboard cruise ships describe two recurring problems: norovirus gastroenteritis spreading through passenger behaviour, and respiratory infections including influenza that can seed new strains across borders because passengers are older and travel far. Port-based surveillance programmes and a recent scoping review summarise the prevention measures that work on ships. The honest boundary: base rates per cruise are low; the point is to know which behaviours the investigations flagged rather than to fear the ship.",
    action: "Before a cruise, get the seasonal influenza vaccine if it is available to you, then aboard wash hands with soap before every meal and after every public-area contact, and report any vomiting or diarrhoea to the ship's medical centre the same day.",
    sources: [
      { cite: "Wikswo, M. E., Cortes, J., Hall, A. J., Vaughan, G., Howard, C., Gregoricus, N., & Cramer, E. H. (2011). Disease transmission and passenger behaviors during a high morbidity norovirus outbreak on a cruise ship, January 2009. Clinical Infectious Diseases, 52(9), 1116–1122.", note: "Retrospective cohort aboard a ship with a large norovirus outbreak; notes that norovirus caused an average of 27 confirmed cruise-ship outbreaks a year over the preceding five years and links spread to passenger behaviours.", link: doi("10.1093/cid/cir144"), kind: "doi" },
      { cite: "Miller, J. M., Tam, T. W., Maloney, S., Fukuda, K., Cox, N., Hockin, J., Kertesz, D., Klimov, A., & Cetron, M. (2000). Cruise ships: High-risk passengers and the global spread of new influenza viruses. Clinical Infectious Diseases, 31(2), 433–438.", note: "Reviewed a ship's medical records across three 1997 cruises with acute respiratory illness; argued that older passengers on long itineraries make cruise ships a vehicle for spreading new influenza strains.", link: doi("10.1086/313974"), kind: "doi" },
      { cite: "Pavli, A., Maltezou, H. C., Papadakis, A., Katerelos, P., Saroglou, G., Tsakris, A., & Tsiodras, S. (2016). Respiratory infections and gastrointestinal illness on a cruise ship: A three-year prospective study. Travel Medicine and Infectious Disease, 14(4), 389–397.", note: "Three-year prospective study estimating the incidence and spectrum of respiratory and gastrointestinal illness among people on one cruise ship.", link: doi("10.1016/j.tmaid.2016.05.019"), kind: "doi" },
      { cite: "Rogers, K. B., Roohi, S., Uyeki, T. M., Montgomery, D., Parker, J., Fowler, N. H., Xu, X., Ingram, D. J., Fearey, D., Williams, S. M., Tarling, G., Brown, C. M., & Cohen, N. J. (2017). Laboratory-based respiratory virus surveillance pilot project on select cruise ships in Alaska, 2013–15. Journal of Travel Medicine, 24(6), tax069.", note: "Pilot surveillance on Alaska cruises showing influenza outbreaks occur among passengers and crew in the summer season, not only in winter.", link: doi("10.1093/jtm/tax069"), kind: "doi" },
      { cite: "Fernandes, E. G., de Souza, P. B., de Oliveira, M. E. B., Lima, G. D. F., Pellini, A. C. G., Ribeiro, M. C. S. A., Sato, H. K., Ribeiro, A. F., & Yu, A. L. F. (2014). Influenza B outbreak on a cruise ship off the São Paulo coast, Brazil. Journal of Travel Medicine, 21(5), 298–303.", note: "Field investigation of an influenza B outbreak that hospitalised crew and passengers — an example of how a respiratory outbreak unfolds on a ship.", link: doi("10.1111/jtm.12132"), kind: "doi" },
      { cite: "Marshall, C. A., Morris, E., & Unwin, N. (2016). An epidemiological study of rates of illness in passengers and crew at a busy Caribbean cruise port. BMC Public Health, 16, 314.", note: "Port-level epidemiology of illness among cruise passengers and crew in Barbados; gives a sense of the base rates behind the headlines.", link: doi("10.1186/s12889-016-2991-3"), kind: "doi" },
      { cite: "Anagnostopoulos, L., Vasileiadis, S., Kourentis, L., Bogogiannidou, Z., Mouchtouri, V. A., & Hadjichristodoulou, C. (2025). Scoping review of infectious disease prevention, mitigation and management in passenger ships and at ports: Mapping the evidence. Tropical Medicine and Health, 53(1), 3.", note: "Maps the evidence on preventing and managing infectious disease on passenger ships and at ports — the current summary of what works.", link: doi("10.1186/s41182-025-00681-0"), kind: "doi" },
    ],
  },
  {
    id: "gs-travel-w3-scams-safety",
    goal: "travel", tier: "fundamental", section: "11004",
    title: "Learn the Six Scam Scripts and Keep Your Fear Proportionate to the Data",
    subtitle: "Tourists are targeted by predictable scams; fear of crime on holiday outruns actual victimisation",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "days", durability: "lasting", effort: "low" },
    feeds: ["street awareness", "calm judgement", "risk literacy"],
    description:
      "Tourism researchers have catalogued the dimensions of tourist scams and, more recently, deconstructed them as social practices with recognisable scripts. Victimisation surveys of British holidaymakers found that fear of crime on holiday and actual victimisation are different things, and risk-perception studies show how perceived terrorism or crime risk drives destination decisions more than base rates do. The protocol is to know the scripts, take the ordinary precautions, and refuse to let disproportionate fear cancel the trip.",
    action: "Before you leave, spend 15 minutes reading the common scams for your destination and write your three counter-moves (say no and walk on; never hand over a passport or phone; agree prices before a service). Then decide in advance which one fear you are going to stop entertaining.",
    sources: [
      { cite: "Pearce, P. (2011). Tourist scams: Exploring the dimensions of an international tourism phenomenon. European Journal of Tourism Research, 4(2), 147–156.", note: "Maps the dimensions of tourist scams across countries — the taxonomy behind the 'know the scripts' step.", link: doi("10.54055/ejtr.v4i2.71"), kind: "doi" },
      { cite: "Xu, D., Pearce, P. L., & Chen, T. (2021). Deconstructing tourist scams: A social-practice-theory perspective. Tourism Management, 82, 104186.", note: "Analyses scams as social practices with routines and scripts; once you can see the script you can step out of it.", link: doi("10.1016/j.tourman.2020.104186"), kind: "doi" },
      { cite: "Brunt, P., Mawby, R., & Hambly, Z. (2000). Tourist victimisation and the fear of crime on holiday. Tourism Management, 21(4), 417–424.", note: "Survey of holidaymakers separating fear of crime from actual victimisation on holiday — the evidence that fear tends to outrun the data.", link: doi("10.1016/s0261-5177(99)00084-9"), kind: "doi" },
      { cite: "Mawby, R. I., Brunt, P., & Hambly, Z. (1999). Victimisation on holiday: A British survey. International Review of Victimology, 6(3), 201–211.", note: "British survey of victimisation experienced on holiday; establishes the base rates against which travellers can calibrate their worry.", link: doi("10.1177/026975809900600303"), kind: "doi" },
      { cite: "Sönmez, S. F., & Graefe, A. R. (1998). Influence of terrorism risk on foreign tourism decisions. Annals of Tourism Research, 25(1), 112–144.", note: "Classic study of how perceived terrorism risk shapes whether and where people travel abroad — perception, not incidence, drives the decision.", link: doi("10.1016/s0160-7383(97)00072-8"), kind: "doi" },
      { cite: "Reisinger, Y., & Mavondo, F. (2005). Travel anxiety and intentions to travel internationally: Implications of travel risk perception. Journal of Travel Research, 43(3), 212–225.", note: "Models how travel anxiety and risk perception reduce intentions to travel internationally; the case for deliberately right-sizing fear.", link: doi("10.1177/0047287504272017"), kind: "doi" },
    ],
  },
  {
    id: "gs-travel-w3-accessible-travel",
    goal: "travel", tier: "moderate", section: "11005",
    title: "Travel With a Disability or Dementia — Plan the Access, Not Just the Destination",
    subtitle: "Access information, attitudinal barriers and dementia-friendly destinations",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "moderate" },
    feeds: ["independence", "inclusion", "caregiver relief"],
    description:
      "The accessible-tourism literature shows that people with disabilities travel as much as they can get information about, that the barriers are as often attitudinal and informational as physical, and that a 'whole-of-life' view of access serves everyone, including the ageing. Dementia-specific studies from Bournemouth identify what people living with dementia and their carers need from destinations and what stops them taking part in leisure at all. The honest boundary: this is planning and design research, not outcome trials; it tells you what to ask for.",
    action: "For a traveller with a disability or dementia, phone every accommodation and attraction two weeks ahead with a written list of specific access questions (step-free route, quiet space, accessible bathroom dimensions, staff briefing), and book only where the answers were specific.",
    sources: [
      { cite: "Darcy, S., & Dickson, T. J. (2009). A whole-of-life approach to tourism: The case for accessible tourism experiences. Journal of Hospitality and Tourism Management, 16(1), 32–44.", note: "Argues that accessible tourism is a whole-of-life issue — everyone needs access at some stage — and sets out what accessible experiences require.", link: doi("10.1375/jhtm.16.1.32"), kind: "doi" },
      { cite: "Yau, M. K., McKercher, B., & Packer, T. L. (2004). Traveling with a disability. Annals of Tourism Research, 31(4), 946–960.", note: "Qualitative study of how people with disabilities become travellers — the stages and the planning burden involved.", link: doi("10.1016/j.annals.2004.03.007"), kind: "doi" },
      { cite: "Darcy, S. (2010). Inherent complexity: Disability, accessible tourism and accommodation information preferences. Tourism Management, 31(6), 816–826.", note: "Shows that what disabled travellers want most from accommodation is detailed, specific access information — the reason to ask precise questions.", link: doi("10.1016/j.tourman.2009.08.010"), kind: "doi" },
      { cite: "McKercher, B., & Darcy, S. (2018). Re-conceptualizing barriers to travel by people with disabilities. Tourism Management Perspectives, 26, 59–66.", note: "Reframes travel barriers for people with disabilities into tiers, from those common to all travellers to those specific to an impairment.", link: doi("10.1016/j.tmp.2018.01.003"), kind: "doi" },
      { cite: "Page, S. J., Innes, A., & Cutler, C. (2015). Developing dementia-friendly tourism destinations. Journal of Travel Research, 54(4), 467–481.", note: "Exploratory analysis of what makes a destination dementia-friendly — the checklist a carer can use when choosing where to go.", link: doi("10.1177/0047287514522881"), kind: "doi" },
      { cite: "Innes, A., Page, S. J., & Cutler, C. (2016). Barriers to leisure participation for people with dementia and their carers: An exploratory analysis of carer and people with dementia's experiences. Dementia, 15(6), 1643–1665.", note: "Identifies the barriers that keep people with dementia and their carers from leisure and travel, as reported by both.", link: doi("10.1177/1471301215570346"), kind: "doi" },
    ],
  },
  {
    id: "gs-travel-w3-senior-travel",
    goal: "travel", tier: "moderate", section: "11006",
    title: "After Retirement, Join a Structured Travel Program — Educational, Social or Group",
    subtitle: "Holiday-taking tracks self-assessed health in older adults; programs remove the planning barrier",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "months", durability: "sustained", effort: "moderate" },
    feeds: ["social connection", "purpose", "cognitive engagement"],
    description:
      "Studies of retirees find that leisure activities, travel among them, contribute to life satisfaction, and that holiday-taking is associated with better self-assessed health in senior tourists. Social-tourism evaluations in later life and research on educational travel programmes (the Elderhostel model) describe how a structured programme lowers the effort and loneliness that otherwise stop older people travelling. Senior RV travellers form durable 'mobile communities'. The honest boundary: associations, with likely reverse causation from health to travel; the programmes are well described, not trialled.",
    action: "If you are retired, enrol in one structured travel programme this year — an educational tour, a group trip through a club, or a social-tourism scheme — and book the second one before the first ends.",
    sources: [
      { cite: "Nimrod, G. (2007). Retirees' leisure: Activities, benefits, and their contribution to life satisfaction. Leisure Studies, 26(1), 65–80.", note: "Examines which leisure activities and benefits contribute to retirees' life satisfaction — the wider frame in which travel sits.", link: doi("10.1080/02614360500333937"), kind: "doi" },
      { cite: "Hunter-Jones, P., & Blackburn, A. (2007). Understanding the relationship between holiday taking and self-assessed health: An exploratory study of senior tourism. International Journal of Consumer Studies, 31(5), 509–516.", note: "Exploratory study linking holiday-taking to self-assessed health among older tourists.", link: doi("10.1111/j.1470-6431.2007.00607.x"), kind: "doi" },
      { cite: "Morgan, N., Pritchard, A., & Sedgley, D. (2015). Social tourism and well-being in later life. Annals of Tourism Research, 52, 1–15.", note: "Evaluates social tourism for older people and its contribution to their well-being — the case for subsidised or organised group travel.", link: doi("10.1016/j.annals.2015.02.015"), kind: "doi" },
      { cite: "Sedgley, D., Pritchard, A., & Morgan, N. (2011). Tourism and ageing. Annals of Tourism Research, 38(2), 422–436.", note: "Sets out the research agenda on tourism and ageing, including the barriers that keep older people from travelling.", link: doi("10.1016/j.annals.2010.09.002"), kind: "doi" },
      { cite: "Arsenault, N., Anderson, G., & Swedburg, R. (1998). Understanding older adults in education: Decision-making and Elderhostel. Educational Gerontology, 24(2), 101–114.", note: "Studies how older adults decide to join Elderhostel educational travel programmes — the original model for structured learning trips in later life.", link: doi("10.1080/0360127980240201"), kind: "doi" },
      { cite: "Pearce, P. L., & Wu, M.-Y. (2018). A mobile narrative community: Communication among senior recreational vehicle travellers. Tourist Studies, 18(2), 194–212.", note: "Describes the narrative community that forms among senior RV travellers — evidence that travel formats can supply the social connection retirees lose.", link: doi("10.1177/1468797617723469"), kind: "doi" },
    ],
  },
  {
    id: "gs-travel-w3-points-honest",
    goal: "travel", tier: "fundamental", section: "11007",
    title: "Frequent-Flyer Points: Take Them, Never Chase Them",
    subtitle: "Loyalty programmes are built on effort justification, illusory progress and status tiers",
    evidenceTag: "Strong",
    impact: { magnitude: 1, latency: "months", durability: "transient", effort: "low" },
    callout: "Rated at the floor. The consumer-research record shows loyalty programmes work by making you spend more to 'earn' rewards, accelerate purchases as a goal nears, and value status tiers that exist to keep you flying one airline — none of which makes a trip better. Collect what you get; do not route, upgrade or overspend to collect.",
    feeds: ["financial discipline"],
    description:
      "The programmes are effective marketing: laboratory and field research shows people prefer rewards they had to work for, that artificial progress toward a goal accelerates spending, and that tiered status confers a feeling of superiority strong enough to change behaviour. A long-term panel study found loyalty programmes change purchase behaviour mainly among lighter customers, and a widely cited review questioned whether they build real loyalty at all. For a traveller, points are a rebate — worth taking, worth nothing as a reason to fly.",
    action: "Keep one loyalty account per alliance and let it fill passively. Set a rule now: never pay more, fly a worse route, or book a trip you did not already want in order to earn or keep status.",
    sources: [
      { cite: "Kivetz, R., & Simonson, I. (2002). Earning the right to indulge: Effort as a determinant of customer preferences toward frequency program rewards. Journal of Marketing Research, 39(2), 155–170.", note: "Shows that the effort required by a frequency programme changes which rewards people prefer — the psychology that makes points feel earned rather than trivial.", link: doi("10.1509/jmkr.39.2.155.19084"), kind: "doi" },
      { cite: "Kivetz, R., Urminsky, O., & Zheng, Y. (2006). The goal-gradient hypothesis resurrected: Purchase acceleration, illusionary goal progress, and customer retention. Journal of Marketing Research, 43(1), 39–58.", note: "Demonstrates that people accelerate purchases as they approach a reward and that illusory progress alone increases effort — the mechanism behind 'just one more flight'.", link: doi("10.1509/jmkr.43.1.39"), kind: "doi" },
      { cite: "Nunes, J. C., & Drèze, X. (2006). The endowed progress effect: How artificial advancement increases effort. Journal of Consumer Research, 32(4), 504–512.", note: "Shows that giving customers artificial head-start progress toward a reward increases their effort to complete it.", link: doi("10.1086/500480"), kind: "doi" },
      { cite: "Drèze, X., & Nunes, J. C. (2009). Feeling superior: The impact of loyalty program structure on consumers' perceptions of status. Journal of Consumer Research, 35(6), 890–905.", note: "Finds that tiered programme structures create feelings of status that depend on the number of people below you — status is the product.", link: doi("10.1086/593946"), kind: "doi" },
      { cite: "Liu, Y. (2007). The long-term impact of loyalty programs on consumer purchase behavior and loyalty. Journal of Marketing, 71(4), 19–35.", note: "Longitudinal study of a loyalty programme's effect on purchase behaviour over time; the effects are real but uneven across customer types.", link: doi("10.1509/jmkg.71.4.019"), kind: "doi" },
      { cite: "Uncles, M. D., Dowling, G. R., & Hammond, K. (2003). Customer loyalty and customer loyalty programs. Journal of Consumer Marketing, 20(4), 294–316.", note: "Critical review of what loyalty programmes can and cannot do to build genuine loyalty.", link: doi("10.1108/07363760310483676"), kind: "doi" },
    ],
  },
  {
    id: "gs-travel-w3-off-season",
    goal: "travel", tier: "fundamental", section: "11008",
    title: "Travel in the Shoulder Season — Crowding Is the Variable You Control",
    subtitle: "Perceived crowding lowers destination attractiveness; seasonality is measurable and avoidable",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "days", durability: "sustained", effort: "low" },
    feeds: ["value for money", "presence", "patience"],
    description:
      "Studies of historic cities and hotspots show that visitors perceive crowding and that it becomes unacceptable at identifiable thresholds; hotspot crowding reduces a destination's attractiveness. The seasonality literature documents how sharply demand peaks and troughs and what off-season visitors are like. Cultural destinations show flatter seasonality than beach resorts. The honest boundary: the research is about destinations, not about travellers' wellbeing; the inference that a less crowded trip is a better one is reasonable but not directly tested.",
    action: "For your next trip, book the two weeks either side of the peak season rather than inside it, and choose one 'cultural' destination with flat seasonality over a beach resort.",
    sources: [
      { cite: "Neuts, B., & Nijkamp, P. (2012). Tourist crowding perception and acceptability in cities. Annals of Tourism Research, 39(4), 2133–2153.", note: "Measures how city tourists perceive crowding and at what point they find it unacceptable.", link: doi("10.1016/j.annals.2012.07.016"), kind: "doi" },
      { cite: "Jacobsen, J. K. S., Iversen, N. M., & Hem, L. E. (2019). Hotspot crowding and over-tourism: Antecedents of destination attractiveness. Annals of Tourism Research, 76, 53–66.", note: "Links crowding at hotspots to lower destination attractiveness — the reason the shoulder season pays.", link: doi("10.1016/j.annals.2019.02.011"), kind: "doi" },
      { cite: "Koenig-Lewis, N., & Bischoff, E. E. (2005). Seasonality research: The state of the art. International Journal of Tourism Research, 7(4–5), 201–219.", note: "Reviews how tourism seasonality is measured and what causes it — the reference for finding a destination's true shoulder months.", link: doi("10.1002/jtr.531"), kind: "doi" },
      { cite: "Cuccia, T., & Rizzo, I. (2011). Tourism seasonality in cultural destinations: Empirical evidence from Sicily. Tourism Management, 32(3), 589–595.", note: "Shows that cultural destinations have different, flatter seasonality than sun-and-sea destinations.", link: doi("10.1016/j.tourman.2010.05.008"), kind: "doi" },
      { cite: "Lundtorp, S., Rassing, C. R., & Wanhill, S. (2001). Off-season is no season: The case of Bornholm. Seasonality in Tourism, 89–108.", note: "Case study of an island's off-season — who visits then and why — from the standard volume on tourism seasonality.", link: doi("10.1016/b978-0-08-043674-6.50009-x"), kind: "doi" },
    ],
  },
  {
    id: "gs-travel-w3-overland-rv",
    goal: "travel", tier: "elite", section: "11009",
    title: "The Long Overland Journey — Weeks by Train, Road or RV",
    subtitle: "Drive tourism, RV neo-tribes and rail: the format for a rare, long-horizon trip",
    evidenceTag: "Emerging",
    impact: { magnitude: 3, latency: "months", durability: "lasting", effort: "high" },
    feeds: ["autonomy", "community", "sustained novelty"],
    description:
      "Research on recreational-vehicle users describes 'travelling neo-tribes' — mobile communities with their own norms — and studies of drive tourism in remote regions show heritage and landscape as motives for long road journeys. High-speed rail research documents how rail changes travel behaviour and reach. A multi-week overland trip is the rare, high-effort move: it needs money, time and planning, and the payoff is a different kind of travel rather than a better version of the ordinary holiday. The honest boundary: descriptive and motivational research; no outcome trials.",
    action: "Plan one overland journey of at least three weeks in the next three years — a rail circuit, a road trip or an RV season — and start it with a two-week savings and route-planning block this month.",
    sources: [
      { cite: "Hardy, A., Gretzel, U., & Hanson, D. (2013). Travelling neo-tribes: Conceptualising recreational vehicle users. Journal of Tourism and Cultural Change, 11(1–2), 48–60.", note: "Conceptualises RV users as travelling neo-tribes — mobile communities with shared norms — the social side of the long road journey.", link: doi("10.1080/14766825.2013.783584"), kind: "doi" },
      { cite: "Pearce, P. L., & Wu, M.-Y. (2014). Building familiarity with a new market: Motivations for Chinese recreational vehicle tourists in Australia. Journal of Hospitality & Tourism Cases, 3(1), 20–29.", note: "Case study of the motivations of RV tourists new to the format; what draws people to weeks on the road.", link: doi("10.1177/216499871400300103"), kind: "doi" },
      { cite: "Carson, D., Prideaux, B., Coghlan, A., & Taylor, A. (2009). Heritage as a motivation for four-wheel-drive tourism in desert Australia. Journal of Heritage Tourism, 4(3), 217–225.", note: "Identifies heritage as a motive for long-distance four-wheel-drive journeys through remote desert country.", link: doi("10.1080/17438730802691707"), kind: "doi" },
      { cite: "Chan, C.-S., & Yuan, J. (2017). Changing travel behaviour of high-speed rail passengers in China. Asia Pacific Journal of Tourism Research, 22(12), 1221–1237.", note: "Shows how high-speed rail changes where and how far tourists travel — rail as the enabler of the overland circuit.", link: doi("10.1080/10941665.2017.1391303"), kind: "doi" },
      { cite: "Liu, C. (2018). The motivations and experiences of young Chinese self-drive tourists. Asian Youth Travellers, 135–152.", note: "Explores the motivations and experiences of younger self-drive tourists; the road trip as a distinct experience rather than transport.", link: doi("10.1007/978-981-10-8539-0_8"), kind: "doi" },
    ],
  },
  {
    id: "gs-travel-w3-house-swap",
    goal: "travel", tier: "moderate", section: "11010",
    title: "Swap Homes or Couchsurf — Trust Mechanisms Make Peer-to-Peer Stays Work",
    subtitle: "Reputation, photos and reciprocity are the documented levers; expect longer, more local trips",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "moderate" },
    feeds: ["frugality", "local connection", "trust"],
    description:
      "Studies of CouchSurfing found belonging and trust developing inside a globally cooperative network; research on Italian home-swapping describes who swaps and why; and Airbnb studies show that personal photos and reputation drive trust and that peer-to-peer accommodation changes travel patterns toward longer stays and more local spending. Home-exchange hosts and guests in Budapest describe it as a special-interest form of travel in its own right. The honest boundary: self-selected participants; the trust mechanisms are well documented, the outcomes for wellbeing are not.",
    action: "Join one home-exchange or hospitality network this month, complete a full profile with real photos and one verified reference, and do a first short swap or stay within a day's travel of home before attempting a long one.",
    sources: [
      { cite: "Rosen, D., Lafontaine, P. R., & Hendrickson, B. (2011). CouchSurfing: Belonging and trust in a globally cooperative online social network. New Media & Society, 13(6), 981–998.", note: "Studies how belonging and trust develop among CouchSurfing members — the social capital that makes staying with strangers workable.", link: doi("10.1177/1461444810390341"), kind: "doi" },
      { cite: "Liu, Y., Nie, L., & Li, L. (2016). Homogeneity, trust, and reciprocity: Three keys to the sustainable hospitality exchange of Couchsurfing. Tourism Analysis, 21(2), 145–157.", note: "Identifies homogeneity, trust and reciprocity as the three conditions that keep hospitality exchange sustainable.", link: doi("10.3727/108354216x14559233984610"), kind: "doi" },
      { cite: "Forno, F., & Garibaldi, R. (2015). Sharing economy in travel and tourism: The case of home-swapping in Italy. Journal of Quality Assurance in Hospitality & Tourism, 16(2), 202–220.", note: "Profiles Italian home-swappers — who they are, what motivates them and how the exchange is organised.", link: doi("10.1080/1528008x.2015.1013409"), kind: "doi" },
      { cite: "Pal, A., Asztalos, R., Farzad, F., & Ban, A. (2025). Home exchange as a form of special interest tourism: Exploring experiences of Budapest home exchange hosts and guests. Worldwide Hospitality and Tourism Themes, 17(4), 465–473.", note: "Recent qualitative study of home-exchange hosts and guests, framing the practice as special-interest tourism.", link: doi("10.1108/whatt-01-2025-0046"), kind: "doi" },
      { cite: "Ert, E., Fleischer, A., & Magen, N. (2016). Trust and reputation in the sharing economy: The role of personal photos in Airbnb. Tourism Management, 55, 62–73.", note: "Shows that hosts' personal photos affect trust and price on Airbnb — why a complete, human profile matters.", link: doi("10.1016/j.tourman.2016.01.013"), kind: "doi" },
      { cite: "Tussyadiah, I. P., & Pesonen, J. (2016). Impacts of peer-to-peer accommodation use on travel patterns. Journal of Travel Research, 55(8), 1022–1040.", note: "Finds that using peer-to-peer accommodation changes travel patterns — longer stays, more trips and more local activities.", link: doi("10.1177/0047287515608505"), kind: "doi" },
      { cite: "Guttentag, D. (2015). Airbnb: Disruptive innovation and the rise of an informal tourism accommodation sector. Current Issues in Tourism, 18(12), 1192–1217.", note: "Frames peer-to-peer accommodation as a disruptive innovation and sets out its trade-offs for travellers.", link: doi("10.1080/13683500.2013.827159"), kind: "doi" },
    ],
  },
  {
    id: "gs-travel-w3-food-tourism",
    goal: "travel", tier: "fundamental", section: "11011",
    title: "Make Local Food the Itinerary — One Market, One Home Kitchen, One Regional Dish a Day",
    subtitle: "Local food consumption is a modelled, memorable part of the trip",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "days", durability: "sustained", effort: "low" },
    feeds: ["curiosity", "cultural connection", "memory-making"],
    description:
      "Grounded-theory work and its later empirical verification built a model of why tourists eat local food (cultural experience, sensory appeal, health concern, excitement) and what drives it; a definitional review settled what 'food tourism' is; and studies show local food acting as a destination attraction and generating memorable experiences tied to emotion and motivation. The protocol makes food the organising thread of a trip because it is cheap, daily and reliably memorable. The honest boundary: survey and qualitative research on satisfaction and memory, not health outcomes.",
    action: "On each travel day, do one of three things: visit a food market, eat a named regional dish you have not had before, or take a meal in a home or small family kitchen — and write down the dish and who made it.",
    sources: [
      { cite: "Kim, Y. G., Eves, A., & Scarles, C. (2009). Building a model of local food consumption on trips and holidays: A grounded theory approach. International Journal of Hospitality Management, 28(3), 423–431.", note: "Builds the standard model of why tourists consume local food on holiday from interview data.", link: doi("10.1016/j.ijhm.2008.11.005"), kind: "doi" },
      { cite: "Kim, Y. G., Eves, A., & Scarles, C. (2013). Empirical verification of a conceptual model of local food consumption at a tourist destination. International Journal of Hospitality Management, 33, 484–489.", note: "Tests the local-food consumption model quantitatively at a destination.", link: doi("10.1016/j.ijhm.2012.06.005"), kind: "doi" },
      { cite: "Ellis, A., Park, E., Kim, S., & Yeoman, I. (2018). What is food tourism? Tourism Management, 68, 250–263.", note: "Systematic definitional review of food tourism — what the field means by it and which themes dominate.", link: doi("10.1016/j.tourman.2018.03.025"), kind: "doi" },
      { cite: "Björk, P., & Kauppinen-Räisänen, H. (2016). Local food: A source for destination attraction. International Journal of Contemporary Hospitality Management, 28(1), 177–194.", note: "Shows local food functioning as an attraction that shapes destination choice and experience.", link: doi("10.1108/ijchm-05-2014-0214"), kind: "doi" },
      { cite: "Sthapit, E., Piramanayayagam, S., & Björk, P. (2020). Tourists' motivations, emotions, and memorable local food experiences. Journal of Gastronomy and Tourism, 5(1), 17–32.", note: "Links motivations and emotions to memorable local-food experiences — why a dish becomes the memory of the trip.", link: doi("10.3727/216929720x15968961037881"), kind: "doi" },
      { cite: "Sthapit, E. (2017). Exploring tourists' memorable food experiences: A study of visitors to Santa's official hometown. Anatolia, 28(3), 404–421.", note: "Explores what makes food experiences memorable for visitors to one destination; the ingredients of a memorable meal abroad.", link: doi("10.1080/13032917.2017.1328607"), kind: "doi" },
    ],
  },
  {
    id: "gs-travel-w3-wellness-retreat",
    goal: "travel", tier: "advanced", section: "11012",
    title: "A Week-Long Wellness Retreat — Real Short-Term Gains, Uncertain Durability",
    subtitle: "Observational and quasi-randomised studies show mood and health markers improve; follow-up is thin",
    evidenceTag: "Emerging",
    impact: { magnitude: 3, latency: "days", durability: "transient", effort: "high" },
    callout: "Rated honestly, not at the floor: a residential week does move mood, weight and some biomarkers in the studies, but most are uncontrolled, industry-adjacent or short in follow-up. Treat it as a reset, not a cure, and price it against a cheaper retreat with the same components — meditation, movement, diet, sleep and no phone.",
    feeds: ["reset", "self-regulation"],
    description:
      "A systematic review of residential retreats and an observational study of a week-long retreat both report improvements in multiple dimensions of health and well-being, with some persisting at six weeks. A quasi-randomised trial comparing a six-day mind-body programme with a plain six-day vacation at the same resort found the programme produced gains in spirituality, gratitude and self-compassion and less anxiety at one month, while the vacation alone did not. A three-month yoga-and-meditation retreat changed BDNF and cortisol awakening response, and a large observational study of an eight-day retreat with two months of preparation found sustained mental-health gains at three months. Wellness tourists themselves describe seeking transformation. The honest boundary: uncontrolled or small studies, self-selected participants, and no long-term follow-up in most.",
    action: "If you book a wellness retreat, choose one of at least five nights that includes daily meditation and movement, keep the phone off, and schedule a written check-in at six weeks to see whether anything you started there is still running.",
    sources: [
      { cite: "Naidoo, D., Schembri, A., & Cohen, M. (2018). The health impact of residential retreats: A systematic review. BMC Complementary and Alternative Medicine, 18(1), 8.", note: "Systematic review of immersive residential retreats and their effects on health and lifestyle behaviours.", link: doi("10.1186/s12906-017-2078-4"), kind: "doi" },
      { cite: "Cohen, M. M., Elliott, F., Oates, L., Schembri, A., & Mantri, N. (2017). Do wellness tourists get well? An observational study of multiple dimensions of health and well-being after a week-long retreat. The Journal of Alternative and Complementary Medicine, 23(2), 140–148.", note: "Observational study of a week-long retreat measuring multiple health and well-being dimensions before, after and at follow-up.", link: doi("10.1089/acm.2016.0268"), kind: "doi" },
      { cite: "Mills, P. J., Wilson, K. L., Pung, M. A., Weiss, L., Patel, S., Doraiswamy, P. M., Peterson, C., Porter, V., Schadt, E., Chopra, D., & Tanzi, R. E. (2016). The Self-Directed Biological Transformation Initiative and well-being. The Journal of Alternative and Complementary Medicine, 22(8), 627–634.", note: "Quasi-randomised comparison of a six-day residential mind-body programme against a six-day vacation at the same retreat in 69 adults; the programme group gained in spirituality, gratitude and self-compassion and had less anxiety at one month, the vacation group did not change.", link: doi("10.1089/acm.2016.0002"), kind: "doi" },
      { cite: "Cahn, B. R., Goodman, M. S., Peterson, C. T., Maturi, R., & Mills, P. J. (2017). Yoga, meditation and mind-body health: Increased BDNF, cortisol awakening response, and altered inflammatory marker expression after a 3-month yoga and meditation retreat. Frontiers in Human Neuroscience, 11, 315.", note: "Assessed 38 participants before and after a three-month yoga-and-meditation retreat for psychometric measures, BDNF, salivary cortisol and inflammatory markers.", link: doi("10.3389/fnhum.2017.00315"), kind: "doi" },
      { cite: "Sadhasivam, S., Alankar, S., Maturi, R., Williams, A., Vishnubhotla, R. V., Hariri, S., Mudigonda, M., Pawale, D., Dubbireddi, S., Packiasabapathy, S., Castelluccio, P., Ram, C., Renschler, J., Chang, T., & Subramaniam, B. (2021). Isha yoga practices and participation in Samyama program are associated with reduced HbA1c and systemic inflammation, improved lipid profile, and short-term and sustained improvement in mental health: A prospective observational study of meditators. Frontiers in Psychology, 12, 659667.", note: "Prospective observational study of 632 adults around an eight-day residential retreat with two months of preparation; depression and anxiety scores fell and remained below baseline at three months, with weight and some blood markers improved.", link: doi("10.3389/fpsyg.2021.659667"), kind: "doi" },
      { cite: "Voigt, C., Brown, G., & Howat, G. (2011). Wellness tourists: In search of transformation. Tourism Review, 66(1/2), 16–30.", note: "Characterises what wellness tourists are looking for — transformation rather than pampering — which sets the expectation a retreat has to meet.", link: doi("10.1108/16605371111127206"), kind: "doi" },
    ],
  },
  {
    id: "gs-travel-w3-meditation-retreat",
    goal: "travel", tier: "elite", section: "11013",
    title: "A Ten-Day Silent Retreat — The Intensive Practice Block With Measured Effects",
    subtitle: "Vipassana and month-long insight retreats: migraine, telomerase and inflammatory-gene findings",
    evidenceTag: "Emerging",
    impact: { magnitude: 4, latency: "weeks", durability: "sustained", effort: "high" },
    feeds: ["equanimity", "attention", "stress regulation"],
    description:
      "Two systematic reviews of Vipassana meditation — the original and a 2025 update covering eleven studies — find moderate evidence for reductions in stress and anxiety and gains in mindfulness and well-being, with stronger effects in intensive retreat formats. A single-arm trial of a silent ten-day Vipassana retreat in people with migraine reduced monthly migraine days at twelve months, with sustained gains in quality of life and perceived stress. A three-month retreat raised immune-cell telomerase activity relative to wait-list controls, and a month-long insight retreat down-regulated inflammatory (TNF pathway) gene expression compared with matched practitioners at home. Psychophysiology studies document attention and heart-rate-variability differences in experienced practitioners. The honest boundary: small samples, mostly unblinded, often experienced meditators; a retreat is demanding and not for someone in acute psychiatric crisis.",
    action: "Book a residential silent retreat of ten days within the next two years — after at least three months of a daily sitting practice — and clear the two days after it before returning to work.",
    sources: [
      { cite: "Chiesa, A. (2010). Vipassana meditation: Systematic review of current evidence. Journal of Alternative and Complementary Medicine, 16(1), 37–46.", note: "First systematic review of the neurobiological and clinical evidence specific to Vipassana meditation.", link: doi("10.1089/acm.2009.0362"), kind: "doi" },
      { cite: "Giridharan, S., Soumian, S., Kumar, N. V., & Godbole, M. (2025). The impact of Vipassana meditation on health and well-being: A systematic review of current evidence. Cureus, 17(9), e93355.", note: "Updated systematic review of eleven studies published since 2010; reports moderate evidence for reduced stress and anxiety and gains in mindfulness and well-being, with effects stronger in intensive retreats, and notes small samples and risk of bias.", link: doi("10.7759/cureus.93355"), kind: "doi" },
      { cite: "Goyal, M., Haythornthwaite, J. A., Jain, S., Peterlin, B. L., Mehrotra, M., Levine, D., Rosenberg, J. D., Minges, M., Seminowicz, D. A., & Ford, D. E. (2023). Intensive mindfulness meditation reduces frequency and burden of migraine: An unblinded single-arm trial. Mindfulness, 14(2), 406–417.", note: "Fifty-eight people with migraine attended a silent ten-day Vipassana retreat; at twelve months average migraine frequency fell by 2.7 days per 28 from 16.6 at baseline, with sustained gains in migraine-specific quality of life, pain catastrophising and perceived stress.", link: doi("10.1007/s12671-023-02073-z"), kind: "doi" },
      { cite: "Jacobs, T. L., Epel, E. S., Lin, J., Blackburn, E. H., Wolkowitz, O. M., Bridwell, D. A., Zanesco, A. P., Aichele, S. R., Sahdra, B. K., MacLean, K. A., King, B. G., Shaver, P. R., Rosenberg, E. L., Ferrer, E., Wallace, B. A., & Saron, C. D. (2011). Intensive meditation training, immune cell telomerase activity, and psychological mediators. Psychoneuroendocrinology, 36(5), 664–681.", note: "Thirty people who meditated about six hours a day for three months had greater telomerase activity than 30 matched wait-list controls at the end of the retreat, mediated by increased perceived control and decreased neuroticism.", link: doi("10.1016/j.psyneuen.2010.09.010"), kind: "doi" },
      { cite: "Álvarez-López, M. J., Conklin, Q. A., Cosín-Tomás, M., Shields, G. S., King, B. G., Zanesco, A. P., Kaliman, P., & Saron, C. D. (2022). Changes in the expression of inflammatory and epigenetic-modulatory genes after an intensive meditation retreat. Comprehensive Psychoneuroendocrinology, 11, 100152.", note: "Twenty-eight experienced meditators on a month-long silent insight retreat showed down-regulation of the TNF inflammatory pathway not seen in 34 practitioner controls living their everyday lives.", link: doi("10.1016/j.cpnec.2022.100152"), kind: "doi" },
      { cite: "Zeng, X., Oei, T. P. S., Ye, Y., & Liu, X. (2015). A critical analysis of the concepts and measurement of awareness and equanimity in Goenka's Vipassana meditation. Journal of Religion and Health, 54(2), 399–412.", note: "Critical analysis of the two capacities Goenka's ten-day Vipassana courses train — awareness and equanimity — and how they are measured.", link: doi("10.1007/s10943-013-9796-9"), kind: "doi" },
      { cite: "Delgado-Pastor, L. C., Perakakis, P., Subramanya, P., Telles, S., & Vila, J. (2013). Mindfulness (Vipassana) meditation: Effects on P3b event-related potential and heart rate variability. International Journal of Psychophysiology, 90(2), 207–214.", note: "Psychophysiological study of experienced Vipassana meditators testing attention (P3b) and autonomic regulation (heart-rate variability).", link: doi("10.1016/j.ijpsycho.2013.07.006"), kind: "doi" },
    ],
  },
  {
    id: "gs-travel-w3-music-festivals",
    goal: "travel", tier: "moderate", section: "11014",
    title: "Go to the Festival — With Earplugs In and a Plan for the Medical Tent",
    subtitle: "Festival attendance lifts social wellbeing; hearing loss and drug harms are the documented costs",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "days", durability: "transient", effort: "low" },
    feeds: ["belonging", "joy", "hearing protection"],
    description:
      "A study of young festival-goers found attendance contributes to psychological and social well-being. Against that, a randomised clinical trial at a festival showed earplugs prevent the temporary hearing loss that follows hours of amplified music, and a secondary analysis identified which behaviours track hearing damage. Harm-reduction research — festival drug checking, barriers to help-seeking, and a review of drug-related deaths at Australian festivals — describes where the serious risks lie and what reduces them. Medical-care reports from Glastonbury show what the on-site services handle.",
    action: "For any festival or loud concert, wear filtered earplugs from the first set to the last, locate the medical tent on arrival, and agree with your group that anyone who feels unwell gets walked there immediately, no questions asked.",
    sources: [
      { cite: "Packer, J., & Ballantyne, J. (2011). The impact of music festival attendance on young people's psychological and social well-being. Psychology of Music, 39(2), 164–181.", note: "Examines how attending music festivals affects young people's psychological and social well-being.", link: doi("10.1177/0305735610372611"), kind: "doi" },
      { cite: "Ramakers, G. G. J., Kraaijenga, V. J. C., Cattani, G., van Zanten, G. A., & Grolman, W. (2016). Effectiveness of earplugs in preventing recreational noise-induced hearing loss: A randomized clinical trial. JAMA Otolaryngology–Head & Neck Surgery, 142(6), 551–558.", note: "Randomised clinical trial at an outdoor music festival testing whether earplugs prevent temporary hearing loss immediately after music exposure.", link: doi("10.1001/jamaoto.2016.0225"), kind: "doi" },
      { cite: "Kraaijenga, V. J. C., van Munster, J. J. C. M., & van Zanten, G. A. (2018). Association of behavior with noise-induced hearing loss among attendees of an outdoor music festival: A secondary analysis of a randomized clinical trial. JAMA Otolaryngology–Head & Neck Surgery, 144(6), 490–497.", note: "Secondary analysis of the festival trial identifying which attendee behaviours were associated with noise-induced hearing loss.", link: doi("10.1001/jamaoto.2018.0272"), kind: "doi" },
      { cite: "Olsen, A., Wong, G., & McDonald, D. (2022). Music festival drug checking: Evaluation of an Australian pilot program. Harm Reduction Journal, 19(1), 127.", note: "Evaluates a festival-based drug-checking service — feasibility, design and acceptability to users and stakeholders.", link: doi("10.1186/s12954-022-00708-3"), kind: "doi" },
      { cite: "Page, R., Healey, A., Siefried, K. J., Harrod, M. E., Franklin, E., Peacock, A., Brett, J., Freeman, G., & Ezard, N. (2022). Barriers to help-seeking among music festival attendees in New South Wales, Australia. Drug and Alcohol Review, 41(6), 1322–1330.", note: "Explores why festival attendees delay seeking help when unwell — the reason to agree the 'walk them to the tent' rule in advance.", link: doi("10.1111/dar.13479"), kind: "doi" },
      { cite: "Santamarina, R., Caldicott, D., Fitzgerald, J., & Schumann, J. L. (2023). Drug-related deaths at Australian music festivals. International Journal of Drug Policy, 123, 104274.", note: "Reviews drug-related deaths at Australian music festivals and the circumstances around them.", link: doi("10.1016/j.drugpo.2023.104274"), kind: "doi" },
      { cite: "Bennett, J. F., & Cottrell, D. J. (2024). Glastonbury Festival: Medical care at the world's largest greenfield music festival. Prehospital and Disaster Medicine, 39(2), 170–177.", note: "Describes the medical care provided at Glastonbury — what the on-site services see and treat.", link: doi("10.1017/S1049023X24000256"), kind: "doi" },
    ],
  },
  {
    id: "gs-travel-w3-journaling",
    goal: "travel", tier: "fundamental", section: "11015",
    title: "Write Ten Minutes a Night on the Road — Then Reread It Six Months Later",
    subtitle: "Rediscovery of ordinary documented moments is undervalued; writing about positive experiences has measured benefits",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "weeks", durability: "lasting", effort: "low" },
    feeds: ["savoring", "memory", "reflection"],
    description:
      "Experiments on 'rediscovery' show that people systematically underestimate how much they will enjoy rereading records of ordinary present moments. Writing about intensely positive experiences for a few days improved mood and reduced illness visits in a controlled study; the broader expressive-writing literature reports emotional and physical health benefits, though a comparison of writing, talking and thinking found that writing about triumphs helped less than replaying them mentally — so keep travel entries concrete and descriptive rather than analytical. Positive reminiscence practices raise happiness. The honest boundary: lab and student samples; the travel-specific version is an inference.",
    action: "Each night of a trip, write ten minutes by hand: the day's best moment, one sensory detail, one person's name. Put a calendar reminder to reread the notebook six months after you get home.",
    sources: [
      { cite: "Zhang, T., Kim, T., Brooks, A. W., Gino, F., & Norton, M. I. (2014). A \"present\" for the future: The unexpected value of rediscovery. Psychological Science, 25(10), 1851–1860.", note: "Shows people underestimate the future value of documenting ordinary present experiences and the pleasure of rediscovering them later.", link: doi("10.1177/0956797614542274"), kind: "doi" },
      { cite: "Burton, C. M., & King, L. A. (2004). The health benefits of writing about intensely positive experiences. Journal of Research in Personality, 38(2), 150–163.", note: "Controlled study in which writing about intensely positive experiences for a few days produced mood and health benefits.", link: doi("10.1016/s0092-6566(03)00058-8"), kind: "doi" },
      { cite: "Baikie, K. A., & Wilhelm, K. (2005). Emotional and physical health benefits of expressive writing. Advances in Psychiatric Treatment, 11(5), 338–346.", note: "Review of the expressive-writing paradigm and its emotional and physical health benefits.", link: doi("10.1192/apt.11.5.338"), kind: "doi" },
      { cite: "Lyubomirsky, S., Sousa, L., & Dickerhoof, R. (2006). The costs and benefits of writing, talking, and thinking about life's triumphs and defeats. Journal of Personality and Social Psychology, 90(4), 692–708.", note: "Compares writing, talking and thinking about positive and negative life events; the caution that analysing happy events in writing can blunt them, so travel entries should describe rather than dissect.", link: doi("10.1037/0022-3514.90.4.692"), kind: "doi" },
      { cite: "Bryant, F. B., Smart, C. M., & King, S. P. (2005). Using the past to enhance the present: Boosting happiness through positive reminiscence. Journal of Happiness Studies, 6(3), 227–260.", note: "Shows structured positive reminiscence increases happiness — the reread-six-months-later step.", link: doi("10.1007/s10902-005-3889-4"), kind: "doi" },
    ],
  },
  {
    id: "gs-travel-w3-motion-sickness",
    goal: "travel", tier: "fundamental", section: "11016",
    title: "Motion Sickness — Habituate With Controlled Breathing; Scopolamine Is the Best-Evidenced Drug",
    subtitle: "Desensitisation training works; ginger is weakly supported",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "low" },
    feeds: ["comfort in transit", "self-regulation"],
    description:
      "A Cochrane review and a 2024 meta-analysis with trial sequential analysis (20 trials, 753 participants) find scopolamine reduces motion-sickness nausea compared with placebo; a trial in aircrew compared it with an antihistamine for simulator sickness. A randomised study found a graded motion-desensitisation regime with controlled breathing speeds habituation — the drug-free route for people who travel often. Ginger has a small early trial and reviews describing weaker evidence than for pregnancy or post-operative nausea. Described, not advised: medication choices belong with a clinician.",
    action: "If you get motion sick, practise slow diaphragmatic breathing (about six breaths a minute) during short, repeated exposures — a 15-minute bus or boat ride three times a week for a month — and discuss the medication options with a clinician before a long crossing.",
    sources: [
      { cite: "Spinks, A., & Wasiak, J. (2011). Scopolamine (hyoscine) for preventing and treating motion sickness. Cochrane Database of Systematic Reviews, 2011(6), CD002851.", note: "Cochrane review of scopolamine for preventing and treating motion sickness.", link: doi("10.1002/14651858.CD002851.pub4"), kind: "doi" },
      { cite: "Zhang, Y. X., Niu, X. Y., Xiao, Z. Y., Wang, M. T., & Zhang, Y. L. (2024). Scopolamine for patients with motion sickness: A systematic review and meta-analysis with trial sequential analysis. Acta Oto-Laryngologica, 144(7–8), 429–438.", note: "Meta-analysis of 20 randomised trials (753 participants) with trial sequential analysis; scopolamine reduced reported nausea versus placebo.", link: doi("10.1080/00016489.2024.2397556"), kind: "doi" },
      { cite: "Yen Pik Sang, F., Billar, J., Gresty, M. A., & Golding, J. F. (2005). Effect of a novel motion desensitization training regime and controlled breathing on habituation to motion sickness. Perceptual and Motor Skills, 101(1), 244–256.", note: "Randomised 30 participants to a controlled-breathing group or control during an accelerated desensitisation regime; tests whether breathing speeds habituation to nauseogenic motion.", link: doi("10.2466/pms.101.1.244-256"), kind: "doi" },
      { cite: "Ben-Ari, O., Sarfati, S., Gordon, B., Assa, A., & Nachum, Z. (2023). Anticholinergic versus antihistaminic treatment for simulator sickness prevention. Journal of Clinical Pharmacology, 63(10), 1119–1125.", note: "Randomised comparison of scopolamine and cinnarizine for preventing simulator sickness in aircrew.", link: doi("10.1002/jcph.2319"), kind: "doi" },
      { cite: "Lagami, D., Shupak, A., Jamison, A., & Tal, D. (2023). The vestibular time constant and clinical response to antimotion sickness medication. Ear and Hearing, 44(6), 1404–1409.", note: "Randomised study of why individual responses to scopolamine-based seasickness medication vary, using the vestibular time constant.", link: doi("10.1097/AUD.0000000000001385"), kind: "doi" },
      { cite: "Mowrey, D. B., & Clayson, D. E. (1982). Motion sickness, ginger, and psychophysics. Lancet, 1(8273), 655–657.", note: "The early controlled trial of ginger for motion sickness that started the ginger claim.", link: doi("10.1016/s0140-6736(82)92205-x"), kind: "doi" },
      { cite: "Grant, K. L., & Lutz, R. B. (2000). Ginger. American Journal of Health-System Pharmacy, 57(10), 945–947.", note: "Pharmacy review of ginger, including its use for motion sickness and post-operative nausea.", link: doi("10.1093/ajhp/57.10.945"), kind: "doi" },
    ],
  },
  {
    id: "gs-travel-w3-altitude",
    goal: "travel", tier: "elite", section: "11017",
    title: "The High-Altitude Trek — Ascend Slowly, Know the Acetazolamide Evidence, Do Not Trust Your History",
    subtitle: "Kilimanjaro and Whitney cohorts on ascent rate; meta-analyses on prophylaxis (described, not advised)",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "weeks", durability: "lasting", effort: "high" },
    feeds: ["physical capability", "risk literacy", "achievement"],
    description:
      "Cohort studies on Kilimanjaro and Mount Whitney identify the determinants of summit success and acute mountain sickness (AMS), with ascent profile prominent; a meta-analysis found a previous history of AMS is a poor predictor of getting it again (summary sensitivity 0.50, specificity 0.72), so a prior good trip is no guarantee. Meta-analyses and a Cochrane review agree acetazolamide reduces AMS risk (Cochrane RR 0.47 versus placebo, with more paraesthesia), that 250 mg a day is the lowest dose with evidence (BMJ meta-analysis: NNT 6), and that benefit is largest when the baseline risk — fast ascent — is high. Ibuprofen has a smaller supporting literature. The honest boundary: prophylaxis is a clinician's decision; the slow ascent is yours.",
    action: "For any trek above 2,500 m, choose the itinerary with the most acclimatisation days (and a rest day every third day above 3,000 m), track symptoms with a written daily score, and book a pre-travel consultation to discuss prophylaxis at least a month out.",
    sources: [
      { cite: "Jackson, S. J., Varley, J., Sellers, C., Josephs, K., Codrington, L., Duke, G., Njelekela, M. A., Drummond, G., Sutherland, A. I., Thompson, A. A. R., & Baillie, J. K. (2010). Incidence and predictors of acute mountain sickness among trekkers on Mount Kilimanjaro. High Altitude Medicine & Biology, 11(3), 217–222.", note: "Cohort of Kilimanjaro trekkers measuring how common AMS is and what predicts it.", link: doi("10.1089/ham.2010.1003"), kind: "doi" },
      { cite: "Davies, A. J., Kalson, N. S., Stokes, S., Earl, M. D., Whitehead, A. G., Frost, H., Tyrell-Marsh, I., & Naylor, J. (2009). Determinants of summiting success and acute mountain sickness on Mt Kilimanjaro (5895 m). Wilderness & Environmental Medicine, 20(4), 311–317.", note: "Identifies the determinants of reaching the summit and of AMS on Kilimanjaro.", link: doi("10.1580/1080-6032-020.004.0311"), kind: "doi" },
      { cite: "Wagner, D. R., D'Zatko, K., Tatsugawa, K., Murray, K., Parker, D., Streeper, T., & Willard, K. (2008). Mt. Whitney: Determinants of summit success and acute mountain sickness. Medicine and Science in Sports and Exercise, 40(10), 1820–1827.", note: "Determinants of summit success and AMS on Mount Whitney — a one- or two-day ascent that many first-time high-altitude hikers attempt.", link: doi("10.1249/MSS.0b013e31817e91b8"), kind: "doi" },
      { cite: "MacInnis, M. J., Lohse, K. R., Strong, J. K., & Koehle, M. S. (2015). Is previous history a reliable predictor for acute mountain sickness susceptibility? A meta-analysis of diagnostic accuracy. British Journal of Sports Medicine, 49(2), 69–75.", note: "Across 17 studies (7,921 participants), a history of AMS had summary sensitivity 0.50 and specificity 0.72 for predicting future AMS — too weak to guide prophylaxis on its own.", link: doi("10.1136/bjsports-2013-092921"), kind: "doi" },
      { cite: "Nieto Estrada, V. H., Molano Franco, D., Medina, R. D., Gonzalez Garay, A. G., Martí-Carvajal, A. J., & Arevalo-Rodriguez, I. (2017). Interventions for preventing high altitude illness: Part 1. Commonly-used classes of drugs. Cochrane Database of Systematic Reviews, 6(6), CD009761.", note: "Cochrane review of 64 studies (4,547 participants): acetazolamide reduced AMS risk (RR 0.47) with an increased risk of paraesthesia; evidence for dexamethasone, budesonide and ibuprofen was low quality.", link: doi("10.1002/14651858.CD009761.pub2"), kind: "doi" },
      { cite: "Low, E. V., Avery, A. J., Gupta, V., Schedlbauer, A., & Grocott, M. P. W. (2012). Identifying the lowest effective dose of acetazolamide for the prophylaxis of acute mountain sickness: Systematic review and meta-analysis. BMJ, 345, e6779.", note: "Eleven trials: acetazolamide at 250, 500 and 750 mg daily all prevented AMS above 3,000 m (combined OR 0.36); 250 mg daily was the lowest effective dose, with a number needed to treat of 6.", link: doi("10.1136/bmj.e6779"), kind: "doi" },
      { cite: "Kayser, B., Dumont, L., Lysakowski, C., Combescure, C., Haller, G., & Tramèr, M. R. (2012). Reappraisal of acetazolamide for the prevention of acute mountain sickness: A systematic review and meta-analysis. High Altitude Medicine & Biology, 13(2), 82–92.", note: "Twenty-four trials: the number needed to treat with acetazolamide fell from about 6 when climbing slowly to about 3–4 when ascending by transport, showing the drug matters most when the ascent is fast.", link: doi("10.1089/ham.2011.1084"), kind: "doi" },
      { cite: "Wang, J., Lian, N., Tang, K., Deng, Y., & Li, T. (2025). Comparative effects of pharmacological interventions for the prevention of acute mountain sickness: A systematic review and Bayesian network meta-analysis. Travel Medicine and Infectious Disease, 66, 102868.", note: "Network meta-analysis of 28 trials and 13 drugs; 250 mg twice-daily acetazolamide reduced AMS incidence (OR 0.31) with a longer preventive window than higher doses, and no drug reduced severe AMS.", link: doi("10.1016/j.tmaid.2025.102868"), kind: "doi" },
    ],
  },
  {
    id: "gs-travel-w3-field-hygiene",
    goal: "travel", tier: "fundamental", section: "11018",
    title: "The Daily Field Routine — Food and Water Rules, Shade Hours, Sunscreen Reapplied",
    subtitle: "Traveler's diarrhea prevention and heat/sun protection in tourist settings",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "days", durability: "transient", effort: "low" },
    feeds: ["health on the road", "daily discipline"],
    description:
      "Traveler's diarrhea affects a large share of visitors to lower-income destinations; the graded expert guideline and systematic reviews cover what prevents it — food and water choices, and in selected travellers chemoprophylaxis with a non-absorbed antibiotic or a probiotic yeast, both described here rather than advised. Heat-related illness research from the Hajj and from desert expeditions shows the pattern of who gets sick and when, and a systematic review found that interventions promoting sun-protective behaviour in recreational and tourist settings can work. The routine is unglamorous and daily, which is why it is fundamental.",
    action: "Every day in a hot or lower-income destination: drink only sealed or treated water, eat food that is cooked and hot or peeled by you, stay in shade between 11 and 3, and reapply sunscreen at midday — write the four items on a card and tick them off.",
    sources: [
      { cite: "Riddle, M. S., Connor, B. A., Beeching, N. J., DuPont, H. L., Hamer, D. H., Kozarsky, P., Libman, M., Steffen, R., Taylor, D., Tribble, D. R., Vila, J., Zanger, P., & Ericsson, C. D. (2017). Guidelines for the prevention and treatment of travelers' diarrhea: A graded expert panel report. Journal of Travel Medicine, 24(suppl_1), S57–S74.", note: "The graded expert-panel guideline on preventing and treating travelers' diarrhea.", link: doi("10.1093/jtm/tax026"), kind: "doi" },
      { cite: "DuPont, H. L. (2008). Systematic review: Prevention of travellers' diarrhoea. Alimentary Pharmacology & Therapeutics, 27(9), 741–751.", note: "Systematic review of prevention options, including the renewed case for non-absorbed antibiotic prophylaxis in some travellers.", link: doi("10.1111/j.1365-2036.2008.03647.x"), kind: "doi" },
      { cite: "Alajbegovic, S., Sanders, J. W., Atherly, D. E., & Riddle, M. S. (2012). Effectiveness of rifaximin and fluoroquinolones in preventing travelers' diarrhea (TD): A systematic review and meta-analysis. Systematic Reviews, 1, 39.", note: "Meta-analysis of antibiotic prophylaxis for travelers' diarrhea — described so a member can discuss it with a clinician, not a recommendation.", link: doi("10.1186/2046-4053-1-39"), kind: "doi" },
      { cite: "McFarland, L. V. (2010). Systematic review and meta-analysis of Saccharomyces boulardii in adult patients. World Journal of Gastroenterology, 16(18), 2202–2222.", note: "Reviews the randomised evidence for the probiotic yeast S. boulardii across indications, including travellers' diarrhoea.", link: doi("10.3748/wjg.v16.i18.2202"), kind: "doi" },
      { cite: "Ericsson, C. D. (2003). Travellers' diarrhoea. International Journal of Antimicrobial Agents, 21(2), 116–124.", note: "Review putting the risk at about 7% for travel in developed countries and 20–50% in the developing world, with education and chemoprophylaxis as the prevention options.", link: doi("10.1016/s0924-8579(02)00282-0"), kind: "doi" },
      { cite: "Rodrigues, A., Sniehotta, F. F., & Araujo-Soares, V. (2013). Are interventions to promote sun-protective behaviors in recreational and tourist settings effective? A systematic review with meta-analysis and meta-regression. Annals of Behavioral Medicine, 45(2), 224–238.", note: "Systematic review with meta-analysis of interventions promoting sun-protective behaviour specifically in recreational and tourist settings.", link: doi("10.1007/s12160-012-9444-8"), kind: "doi" },
      { cite: "Yezli, S. (2021). Risk factors for heat-related illnesses during the Hajj mass gathering: An expert review. Reviews on Environmental Health, 38(1), 33–43.", note: "Expert review of the risk factors for heat-related illness among Hajj pilgrims — the largest natural experiment in travel and heat.", link: doi("10.1515/reveh-2021-0097"), kind: "doi" },
      { cite: "Tonna, J. E., Lewin, M. R., Hahn, I. H., Platts-Mills, T. F., & Mistry, N. (2009). A prospective, multi-year analysis of illness and injury during summer travel to arid environments. Wilderness & Environmental Medicine, 20(2), 107–112.", note: "Six field seasons of illness and injury records from desert expeditions — what actually goes wrong in hot, arid travel.", link: doi("10.1580/08-WEME-OR-193R3.1"), kind: "doi" },
    ],
  },
  {
    id: "gs-travel-w3-pre-travel-clinic",
    goal: "travel", tier: "advanced", section: "11019",
    title: "See a Travel-Medicine Clinic Six Weeks Out — Vaccines and Malaria Prophylaxis, Described",
    subtitle: "Illness in returned travellers is predictable by destination; adherence to prophylaxis is the weak link",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "weeks", durability: "sustained", effort: "moderate" },
    feeds: ["health on the road", "risk literacy"],
    description:
      "GeoSentinel surveillance across 30 sites showed that the illnesses ill returned travellers present with are predictable from where they went, and that roughly 8% of travellers to the developing world need medical care during or after a trip. Studies of students and migrants visiting friends and relatives show low uptake of pre-travel advice. For malaria, JAMA reviews set out the controversies in chemoprophylaxis and the special case of long-term travellers, while a systematic review and prospective cohorts show that adherence — not the drug — is where prevention fails. Vaccine reviews cover the older traveller. All of this is described so a member arrives at the clinic informed; the decisions are the clinician's.",
    action: "Book a travel-medicine consultation at least six weeks before any trip outside high-income countries, bring your vaccine record and itinerary, and if malaria prophylaxis is prescribed, set a daily phone alarm for the full course including the days after you get home.",
    sources: [
      { cite: "Freedman, D. O., Weld, L. H., Kozarsky, P. E., Fisk, T., Robins, R., von Sonnenburg, F., Keystone, J. S., Pandey, P., & Cetron, M. S. (2006). Spectrum of disease and relation to place of exposure among ill returned travelers. New England Journal of Medicine, 354(2), 119–130.", note: "GeoSentinel analysis from 30 sites: about 8% of travellers to the developing world need medical care during or after travel, and the diagnosis spectrum depends on the region visited.", link: doi("10.1056/NEJMoa051331"), kind: "doi" },
      { cite: "Hagmann, S. H. F., Han, P. V., Stauffer, W. M., Miller, A. O., Connor, B. A., Hale, D. C., Coyle, C. M., Cahill, J. D., Marano, C., Esposito, D. H., & Kozarsky, P. E. (2014). Travel-associated disease among US residents visiting US GeoSentinel clinics after return from international travel. Family Practice, 31(6), 678–687.", note: "Describes the travel-associated diseases US residents bring to GeoSentinel clinics after international trips — the US-specific picture.", link: doi("10.1093/fampra/cmu063"), kind: "doi" },
      { cite: "Heywood, A. E., Zhang, M., MacIntyre, C. R., & Seale, H. (2012). Travel risk behaviours and uptake of pre-travel health preventions by university students in Australia. BMC Infectious Diseases, 12, 43.", note: "Shows how rarely students take up pre-travel preventions despite risky itineraries — the gap this protocol closes.", link: doi("10.1186/1471-2334-12-43"), kind: "doi" },
      { cite: "Chen, L. H., Wilson, M. E., & Schlagenhauf, P. (2007). Controversies and misconceptions in malaria chemoprophylaxis for travelers. JAMA, 297(20), 2251–2263.", note: "Review of the controversies and misconceptions around malaria chemoprophylaxis, including how risk thresholds differ between guidelines.", link: doi("10.1001/jama.297.20.2251"), kind: "doi" },
      { cite: "Chen, L. H., Wilson, M. E., & Schlagenhauf, P. (2006). Prevention of malaria in long-term travelers. JAMA, 296(18), 2234–2244.", note: "Review of malaria prevention for people travelling six months or longer, whose challenges differ from short-term tourists.", link: doi("10.1001/jama.296.18.2234"), kind: "doi" },
      { cite: "Ahluwalia, J., Brooks, S. K., Weinman, J., & Rubin, G. J. (2020). A systematic review of factors affecting adherence to malaria chemoprophylaxis amongst travellers from non-endemic countries. Malaria Journal, 19(1), 16.", note: "Systematic review of what predicts whether travellers actually take their malaria prophylaxis.", link: doi("10.1186/s12936-020-3104-4"), kind: "doi" },
      { cite: "Stoney, R. J., Chen, L. H., Jentes, E. S., Wilson, M. E., Han, P. V., Benoit, C. M., MacLeod, W. B., Hamer, D. H., & Barnett, E. D. (2016). Malaria prevention strategies: Adherence among Boston area travelers visiting malaria-endemic countries. American Journal of Tropical Medicine and Hygiene, 94(1), 136–142.", note: "Prospective Boston cohort measuring adherence to prescribed chemoprophylaxis, reasons for non-adherence and use of other protective measures.", link: doi("10.4269/ajtmh.15-0565"), kind: "doi" },
      { cite: "Leder, K., Weller, P. F., & Wilson, M. E. (2001). Travel vaccines and elderly persons: Review of vaccines available in the United States. Clinical Infectious Diseases, 33(9), 1553–1566.", note: "Reviews how ageing changes the safety and immunogenicity of travel vaccines available in the United States.", link: doi("10.1086/322968"), kind: "doi" },
    ],
  },
  {
    id: "gs-travel-w3-chronic-pregnancy",
    goal: "travel", tier: "advanced", section: "11020",
    title: "Travelling With a Chronic Condition or in Pregnancy — Build the Plan With Your Specialist",
    subtitle: "Insulin across time zones, HIV and other chronic illness, and the air-travel-in-pregnancy record",
    evidenceTag: "Moderate",
    impact: { magnitude: 4, latency: "weeks", durability: "sustained", effort: "moderate" },
    feeds: ["health on the road", "planning"],
    description:
      "Evidence-based reviews set out the practical challenges of international travel with a chronic illness, and diabetes research shows that crossing time zones on insulin needs a specific plan (a pilot randomised trial compared two basal insulins for exactly this). For pregnancy, a systematic review and several cohort studies find no clear excess of adverse pregnancy outcomes from air travel in healthy women, but venous thromboembolism risk is raised by both pregnancy and long-haul flight, and a review estimates the baseline long-haul VTE risk at about 2.8 per 1,000 travellers before pregnancy adds to it. None of this is advice: it is the literature to bring to the appointment.",
    action: "If you have a chronic condition or are pregnant, book an appointment with your treating specialist at least a month before travel and leave with a written plan covering medication timing across time zones, what to do if unwell, insurance that names the condition, and — for long flights — the clot-prevention steps your clinician chooses.",
    sources: [
      { cite: "Darrat, M., & Flaherty, G. T. (2020). International travel with a chronic medical illness – Health risks, practical challenges and evidence-based recommendations. International Journal of Travel Medicine and Global Health, 9(2), 44–59.", note: "Evidence-based review of the risks and practical challenges of international travel with a chronic medical illness.", link: doi("10.34172/ijtmgh.2021.09"), kind: "doi" },
      { cite: "Huang, J., Yeung, A. M., Klonoff, D. C., Abdel-Malek, A., Rushing, G. M., & Kerr, D. (2023). People with diabetes using insulin flying across multiple time zones: Limitations and opportunities for diabetes technology. Endocrine Practice, 29(10), 830–847.", note: "Review of the problems and device opportunities for insulin users flying across several time zones.", link: doi("10.1016/j.eprac.2023.07.003"), kind: "doi" },
      { cite: "Bevier, W. C., Castorino, K. N., Axelrod, C., Haroush, G., Kerr, D., & Pinsker, J. E. (2022). Traveling across time zones with type 1 diabetes: A pilot study comparing insulin degludec with insulin glargine U100. Diabetes Care, 45(1), 67–73.", note: "Pilot randomised comparison of two basal insulins in adults with type 1 diabetes travelling across multiple time zones.", link: doi("10.2337/dc21-1524"), kind: "doi" },
      { cite: "Gill, G. V., & Redmond, S. (1993). Insulin treatment, time-zones and air travel: A survey of current advice from British diabetic clinics. Diabetic Medicine, 10(8), 764–767.", note: "Survey showing how variable clinic advice on insulin and time zones was — why you should leave with a written plan rather than a verbal one.", link: doi("10.1111/j.1464-5491.1993.tb00161.x"), kind: "doi" },
      { cite: "Magann, E. F., Chauhan, S. P., Dahlke, J. D., McKelvey, S. S., Watson, E. M., & Morrison, J. C. (2010). Air travel and pregnancy outcomes: A review of pregnancy regulations and outcomes for passengers, flight attendants, and aviators. Obstetrical & Gynecological Survey, 65(6), 396–402.", note: "Review of airline regulations and the gestational complications studied in pregnant passengers, flight attendants and aviators.", link: doi("10.1097/OGX.0b013e3181e572ae"), kind: "doi" },
      { cite: "Shalev Ram, H., Ram, S., Miller, N., Rosental, Y. S., & Chodick, G. (2020). Air travel during pregnancy and the risk of adverse pregnancy outcomes as gestational age and weight at birth: A retrospective study among 284,069 women in Israel between the years 2000 to 2016. PLoS ONE, 15(2), e0228639.", note: "Large retrospective cohort examining whether air travel during pregnancy is associated with gestational age and birth weight outcomes.", link: doi("10.1371/journal.pone.0228639"), kind: "doi" },
      { cite: "Ram, S., Shalev-Ram, H., Neuhof, B., Shlezinger, R., Rosin, D., & Chodick, G. (2022). Air travel during pregnancy and the risk of venous thrombosis. American Journal of Obstetrics & Gynecology MFM, 5(1), 100751.", note: "Examines whether air travel during pregnancy adds to the venous-thrombosis risk that pregnancy and flying each carry.", link: doi("10.1016/j.ajogmf.2022.100751"), kind: "doi" },
      { cite: "Karsanji, D. J., Bates, S. M., & Skeith, L. (2020). The risk and prevention of venous thromboembolism in the pregnant traveller. Journal of Travel Medicine, 27(2), taz091.", note: "Review putting average long-haul VTE risk at about 2.8 per 1,000 travellers and discussing what is and is not known for pregnant travellers.", link: doi("10.1093/jtm/taz091"), kind: "doi" },
    ],
  },
];
