// ============================================================
// JOURNEY CATALOG — the pages the Financial Librarian can send a client to.
//
// Every entry is a real route in the app. `tags` are the topics a client's
// questions and fact-finder signals are matched against; `kind` tells the
// librarian whether a page teaches, calculates, compares, or protects, so a
// journey can be sequenced (understand → measure → compare → decide → protect).
// `builds` is a soft ordering weight: lower numbers belong earlier in a journey.
// ============================================================

export type PageKind = "orientation" | "education" | "calculator" | "comparison" | "protection" | "legacy" | "review";

export type JourneyPage = {
  id: string;
  path: string;
  title: string;
  purpose: string;
  kind: PageKind;
  tags: string[];
  builds: number; // 0 = start of any journey … 9 = closing/review
  /** What to do on this page and what to carry to the next — the librarian's walkthrough. */
  walkthrough: string;
};

export const JOURNEY_CATALOG: JourneyPage[] = [
  // ── orientation ──────────────────────────────────────────────────────────
  { id: "assessment", path: "/portal/financial-assessment", title: "Financial Assessment", purpose: "Your complete financial picture — the foundation every answer rests on.", kind: "orientation", tags: ["start", "assessment", "everything"], builds: 0, walkthrough: "Answer every section; the librarian will not advise on gaps. Carry forward: a complete picture." },
  { id: "arrival", path: "/portal/the-arrival", title: "The Arrival", purpose: "Orientation and calibration: what the plan will do and in what order.", kind: "orientation", tags: ["start", "orientation", "goals"], builds: 0, walkthrough: "Read the seven-step arc once so you know where each later page fits. Carry forward: the order of operations." },
  { id: "mirror", path: "/portal/the-mirror", title: "The Mirror", purpose: "Your personal dashboard — where you stand today, in one view.", kind: "orientation", tags: ["start", "dashboard", "net-worth", "goals"], builds: 0, walkthrough: "Look at the balance sheet as a whole — what you own, what you owe, what it earns. Note the two numbers that surprise you. Carry forward: your starting point." },
  { id: "wealth-genome", path: "/portal/wealth-genome", title: "Wealth Genome Analysis", purpose: "Eight-dimension financial health score: where you are strong and where the plan must work hardest.", kind: "orientation", tags: ["start", "score", "risk", "tax", "insurance", "estate", "debt", "retirement"], builds: 1, walkthrough: "Open each of the eight dimensions and read why it scored that way. Note the two weakest — those set the journey's priorities. Carry forward: your weakest dimensions." },
  { id: "russell-number", path: "/portal/russell-number", title: "Russell Number", purpose: "A single number that tracks whether the coordinated plan is on course.", kind: "review", tags: ["score", "progress", "review"], builds: 8, walkthrough: "Read your Russell Number and what moves it. This is the one figure to re-check after every change. Carry forward: your baseline." },

  // ── taxes ────────────────────────────────────────────────────────────────
  { id: "tax-waterfall", path: "/portal/tax-waterfall", title: "Tax Waterfall", purpose: "How income flows through brackets today, and what changes the order of the buckets.", kind: "education", tags: ["tax", "income", "brackets", "waterfall"], builds: 2, walkthrough: "Follow your income down through the brackets. Find the bracket where your last dollar lands — that is the rate every later strategy is measured against. Carry forward: your marginal rate." },
  { id: "roth-conversion", path: "/portal/roth-conversion", title: "Roth Strategies", purpose: "Six ways to convert tax-deferred money into tax-free money, and when each fits.", kind: "calculator", tags: ["tax", "roth", "conversion", "retirement", "tax-free"], builds: 4, walkthrough: "Use the pre-filled tax-deferred balance. Compare the six conversion paces and watch lifetime tax, not this year's bill. Carry forward: the conversion pace that keeps you below the bracket line." },
  { id: "tax-advantaged-growth", path: "/portal/tax-advantaged-growth", title: "Tax-Advantaged Growth", purpose: "Taxable vs tax-deferred vs tax-free growth over decades, side by side.", kind: "comparison", tags: ["tax", "investments", "growth", "tax-free"], builds: 3, walkthrough: "Put the same dollar in taxable, tax-deferred, and tax-free and watch thirty years. Carry forward: why the tax-free bucket matters most for you." },
  { id: "hot-income", path: "/portal/hot-income", title: "Hot Income (Oil & Gas)", purpose: "How intangible drilling deductions can offset high W-2 income — and the risks that come with them.", kind: "education", tags: ["tax", "deduction", "oil-gas", "high-income"], builds: 5, walkthrough: "Read the deduction mechanics and the risk section with equal attention. Decide whether the income offset is worth the illiquidity for you. Carry forward: a yes, no, or 'ask the advisor'." },
  { id: "str-strategy", path: "/portal/str-strategy", title: "STR Tax Strategy", purpose: "Short-term-rental real estate as an active-income tax lever.", kind: "education", tags: ["tax", "real-estate", "deduction"], builds: 5, walkthrough: "Check whether the material-participation rules fit your schedule before the numbers. Carry forward: whether real estate can be an active tax lever for you." },
  { id: "tax-combos", path: "/portal/tax-combos", title: "100 Tax-Free Combos", purpose: "How the individual strategies combine — the coordinated plan is the product.", kind: "education", tags: ["tax", "tax-free", "combination", "strategy"], builds: 6, walkthrough: "Find the combination that names the strategies you have already met. Read how they compound. Carry forward: your combination." },

  // ── debt, mortgage, home equity ──────────────────────────────────────────
  { id: "mortgage-killer", path: "/portal/mortgage-killer", title: "Mortgage Killer", purpose: "Accelerated payoff: how the same payments retire the mortgage years sooner and what that interest is worth.", kind: "calculator", tags: ["mortgage", "debt", "interest", "home", "payoff"], builds: 3, walkthrough: "Your balance, rate and term are pre-filled. Try the accelerated schedule and read total interest recovered, then the years saved. Carry forward: the interest you can recover." },
  { id: "house-recycling", path: "/portal/house-recycling", title: "House Recycling", purpose: "Cycling home equity into a liquid, tax-advantaged war chest and back again.", kind: "calculator", tags: ["mortgage", "equity", "heloc", "war-chest", "iul", "liquidity"], builds: 4, walkthrough: "Start from the equity figure in your assessment. Trace one full cycle: equity out, war chest funded, equity back. Carry forward: how liquidity and payoff can happen together." },
  { id: "reverse-heloc", path: "/portal/reverse-heloc", title: "Reverse HELOC", purpose: "Using a credit line deliberately instead of accidentally.", kind: "education", tags: ["heloc", "equity", "liquidity", "debt"], builds: 4, walkthrough: "Read how a credit line becomes a deliberate tool rather than an emergency one. Carry forward: the rule for when to draw and when to repay." },
  { id: "household-wealth", path: "/portal/household-wealth", title: "Household Wealth", purpose: "The whole household balance sheet in motion — income, debt, equity, and savings together.", kind: "calculator", tags: ["net-worth", "debt", "student-loans", "cash-flow", "household"], builds: 2, walkthrough: "Watch income, debt, and savings move together over ten years. Change the savings rate once and watch everything else respond. Carry forward: the savings rate the plan needs." },
  { id: "real-estate-mogul", path: "/portal/real-estate-mogul", title: "Real Estate Mogul", purpose: "Rental and investment property modelled with leverage, tax, and cash flow.", kind: "calculator", tags: ["real-estate", "rental", "leverage"], builds: 5, walkthrough: "Model one property with your real leverage and tax rate. Carry forward: the cash-on-cash figure a property must clear to belong in your plan." },

  // ── retirement and income ────────────────────────────────────────────────
  { id: "retirement-drivers", path: "/portal/ecological-drivers", title: "Retirement Drivers", purpose: "The handful of variables that decide retirement outcomes — and which you control.", kind: "education", tags: ["retirement", "variables", "control", "volatility"], builds: 2, walkthrough: "Sort the drivers into two lists: the ones you control (savings, timing, taxes, protection) and the ones you don't (markets, law, longevity). Carry forward: your two lists." },
  { id: "income-gap", path: "/portal/income-gap", title: "Income Gap Analyzer", purpose: "Desired retirement income versus what today's assets will produce.", kind: "calculator", tags: ["retirement", "income", "gap", "goals"], builds: 3, walkthrough: "Age and target are pre-filled. Read the gap in today's dollars, then the three ways to close it. Carry forward: the size of the gap." },
  { id: "withdrawal-sequencing", path: "/portal/withdrawal-sequencing", title: "Withdrawal Sequencing", purpose: "Which bucket to draw first — the order changes lifetime taxes.", kind: "calculator", tags: ["retirement", "tax", "withdrawal", "sequence"], builds: 5, walkthrough: "Compare drawing from taxable, tax-deferred, and tax-free in different orders. Watch lifetime tax, not year one. Carry forward: your draw order." },
  { id: "lifetime-income", path: "/portal/lifetime-income", title: "Lifetime Income", purpose: "Income that cannot be outlived, and what it costs to guarantee it.", kind: "education", tags: ["retirement", "income", "guarantee", "annuity", "longevity"], builds: 5, walkthrough: "Read what a guaranteed income floor costs and what it removes from the plan: the fear of outliving money. Carry forward: the floor you would want." },
  { id: "income-timeline", path: "/portal/income-timeline", title: "Income Timeline", purpose: "Every income source laid out year by year to retirement and beyond.", kind: "calculator", tags: ["retirement", "income", "timeline", "social-security"], builds: 4, walkthrough: "Lay every income source on the timeline to age 95. Find the years with a hole. Carry forward: the years the plan must cover." },
  { id: "social-security", path: "/portal/social-security", title: "Social Security", purpose: "Claiming age, spousal strategy, and taxation of benefits.", kind: "calculator", tags: ["retirement", "social-security", "claiming"], builds: 4, walkthrough: "Compare claiming ages for you and your spouse. Note the difference in lifetime benefit. Carry forward: your claiming age." },

  // ── volatility, risk, and protection ─────────────────────────────────────
  { id: "risk-tolerance", path: "/portal/risk-tolerance", title: "Risk Tolerance", purpose: "How much volatility you can actually live with — measured, not guessed.", kind: "education", tags: ["risk", "volatility", "behavior", "investments"], builds: 2, walkthrough: "Answer honestly — the questions measure how you would behave in a fall, not how you'd like to. Carry forward: your real tolerance." },
  { id: "market-stress-test", path: "/portal/market-stress-test", title: "Market Stress Test", purpose: "Your plan run through the worst historical markets: what breaks and what holds.", kind: "calculator", tags: ["risk", "volatility", "stress", "investments", "sequence-risk"], builds: 4, walkthrough: "Run your plan through the worst historical periods. Note where it breaks and which protection stops the break. Carry forward: the protection that held." },
  { id: "ibbotson-charts", path: "/portal/ibbotson-charts", title: "Ibbotson Charts", purpose: "A century of returns by asset class — the evidence behind every projection.", kind: "education", tags: ["investments", "evidence", "history", "volatility"], builds: 3, walkthrough: "Read a century of returns by asset class. Note how often a ten-year window was negative for stocks alone versus a mix. Carry forward: why floors and mixes exist." },
  { id: "iul-vs-roth", path: "/portal/iul-vs-roth", title: "IUL vs Roth", purpose: "Two tax-free vehicles compared honestly: costs, floors, caps, access, and legacy.", kind: "comparison", tags: ["iul", "roth", "tax-free", "insurance", "comparison"], builds: 5, walkthrough: "Compare the two tax-free vehicles on cost, floor, cap, access, and legacy — not on returns alone. Carry forward: which fits which job in your plan." },
  { id: "iul-historical", path: "/portal/iul-historical", title: "IUL Historical", purpose: "How indexed life would have credited through real market history — floors and caps in action.", kind: "education", tags: ["iul", "volatility", "floor", "insurance"], builds: 4, walkthrough: "Watch how an indexed policy would have credited through real crashes. Note the floor years. Carry forward: what a zero floor is worth to you." },
  { id: "policy-loans", path: "/portal/policy-loans", title: "Policy Loans", purpose: "Tax-free access to cash value — how loans, wash loans, and repayment really work.", kind: "education", tags: ["iul", "liquidity", "war-chest", "tax-free", "loans"], builds: 6, walkthrough: "Read how tax-free access to cash value works and where wash loans can go wrong. Carry forward: the rules for reaching the war chest." },
  { id: "ai-policy-review", path: "/portal/ai-policy-review", title: "Policy Gap Analysis", purpose: "Existing life, disability, and liability coverage checked for gaps.", kind: "review", tags: ["insurance", "disability", "malpractice", "gaps", "protection"], builds: 6, walkthrough: "Read your existing coverage against the gaps flagged from your assessment. Carry forward: the coverage to fix first." },
  { id: "divorce-calculator", path: "/portal/divorce-calculator", title: "Divorce Devastation Engine", purpose: "What a divorce does to an unprotected plan — and what a protected one keeps.", kind: "protection", tags: ["divorce", "protection", "asset-protection"], builds: 6, walkthrough: "Run the unprotected and protected versions of your balance sheet. Carry forward: what structure would have kept." },
  { id: "trusts", path: "/portal/trusts", title: "Trust Structures", purpose: "Revocable, irrevocable, ILIT, asset-protection trusts: which does what.", kind: "protection", tags: ["trust", "estate", "asset-protection", "creditor", "legacy"], builds: 7, walkthrough: "Match each trust type to a job: probate, protection, legacy, insurance ownership. Carry forward: the one or two you likely need." },

  // ── strategy, comparison, decision ───────────────────────────────────────
  { id: "strategy-lab", path: "/portal/strategy", title: "Strategy Lab", purpose: "Your numbers inside the coordinated strategy engine.", kind: "calculator", tags: ["strategy", "plan", "coordination"], builds: 5, walkthrough: "Your numbers are already loaded. Toggle each strategy on and off and watch the combined result. Carry forward: the strategies that earn their place." },
  { id: "strategy-compare", path: "/portal/strategy-compare", title: "Strategy Compare", purpose: "Two or more strategies side by side on the same assumptions.", kind: "comparison", tags: ["strategy", "comparison", "decision"], builds: 6, walkthrough: "Put your two leading strategies side by side on identical assumptions. Carry forward: the winner and the margin." },
  { id: "scenarios", path: "/portal/scenarios", title: "Scenario Builder", purpose: "Change one variable at a time and watch the plan respond.", kind: "calculator", tags: ["variables", "control", "scenario", "sensitivity"], builds: 6, walkthrough: "Change one variable at a time — savings rate, payoff speed, conversion pace, coverage — and watch the plan. Carry forward: the variables that move the outcome most." },
  { id: "time-machine", path: "/portal/time-machine-calculator", title: "Time Machine", purpose: "The plan viewed from the future: what each year of delay costs.", kind: "calculator", tags: ["time", "delay", "compounding", "urgency"], builds: 7, walkthrough: "Look at the plan from the future and read what each year of delay costs. Carry forward: why the first move happens now." },
  { id: "business-owner", path: "/portal/business-owner", title: "Business Owner", purpose: "Entity, retirement plan design, and exit planning for practice owners.", kind: "calculator", tags: ["practice", "business", "entity", "succession", "cash-balance"], builds: 4, walkthrough: "Model the entity, the retirement plan design, and the exit. Carry forward: the structure that pays you best after tax." },
  { id: "physicians-edge", path: "/portal/physicians-edge", title: "Physician's Edge", purpose: "The strategies that matter most for physician income and liability.", kind: "education", tags: ["physician", "high-income", "malpractice", "student-loans"], builds: 2, walkthrough: "Read the strategies built around physician income and liability. Carry forward: the two that apply to you." },
  { id: "combo-recommender", path: "/portal/combo-recommender", title: "AI Combo Recommender", purpose: "Which strategy combination fits your facts — ranked.", kind: "review", tags: ["strategy", "combination", "recommendation"], builds: 7, walkthrough: "Let the recommender rank combinations against your facts. Compare its top pick to your own. Carry forward: the ranked list." },

  // ── legacy and closing ───────────────────────────────────────────────────
  { id: "estate-flow", path: "/portal/estate-flow", title: "Estate Flow Chart", purpose: "Where everything goes at death today, drawn as a flow — and where it should go.", kind: "legacy", tags: ["estate", "legacy", "heirs", "beneficiaries"], builds: 7, walkthrough: "Trace where each asset goes at death today. Mark every arrow you don't like. Carry forward: the arrows to redraw." },
  { id: "beneficiary-optimization", path: "/portal/beneficiary-optimization", title: "Beneficiary Optimizer", purpose: "Beneficiary designations checked against the plan and the tax code.", kind: "legacy", tags: ["estate", "beneficiaries", "legacy"], builds: 7, walkthrough: "Check each beneficiary designation against the estate flow — designations override the will. Carry forward: the forms to update." },
  { id: "estate-tax", path: "/portal/estate-tax", title: "Estate Tax", purpose: "Whether the estate tax touches you, and the levers if it will.", kind: "calculator", tags: ["estate", "tax", "legacy"], builds: 7, walkthrough: "See whether the estate tax touches you and, if it will, which levers reduce it. Carry forward: exposed or not." },
  { id: "will-writer", path: "/portal/will-writer", title: "Will Writer", purpose: "Draft the documents that are missing.", kind: "legacy", tags: ["estate", "will", "documents"], builds: 8, walkthrough: "Draft the documents your estate dimension showed missing. Carry forward: a draft for the attorney." },
  { id: "the-legacy", path: "/portal/the-legacy", title: "The Legacy", purpose: "What the money is for after you.", kind: "legacy", tags: ["legacy", "estate", "meaning"], builds: 8, walkthrough: "Write, in a sentence, what the money is for after you. Carry forward: the sentence." },
  { id: "the-map", path: "/portal/the-map", title: "The Map", purpose: "Portfolio and allocation: the whole plan on one map.", kind: "review", tags: ["review", "allocation", "plan"], builds: 8, walkthrough: "See the whole plan on one map. Confirm every earlier carry-forward has a place on it. Carry forward: the map." },
  { id: "the-brotherhood", path: "/portal/the-brotherhood", title: "The Brotherhood", purpose: "Community and accountability so the plan survives real life.", kind: "review", tags: ["review", "community", "behavior"], builds: 9, walkthrough: "Join the community and set the review cadence. Plans survive because someone checks. Carry forward: your review date." },
];

export const CATALOG_BY_ID: Record<string, JourneyPage> = Object.fromEntries(JOURNEY_CATALOG.map((p) => [p.id, p]));
