// ============================================================
// HYPNOSIS LIBRARY — 50 guided self-hypnosis / mental-rehearsal
// sessions (/hypnosis + /hypnosis/:id). HONESTY FRAME, printed
// on every page: these are OVERT sessions — relaxation, guided
// imagery, rehearsal, future-pacing — listened to on purpose,
// by choice, with full knowledge of what they are. The evidence
// family is real but bounded (strong for relaxation/rehearsal
// uses, overclaimed elsewhere — see the Myth Museum for the
// overclaims). Not medical treatment; never a substitute for a
// licensed clinician.
// Titles are kept ≤ 28 chars so every page title fits 60.
// ============================================================

export type HypnosisFamily = "line" | "state" | "future" | "habit" | "recover";
export type HypnosisTopic = {
  id: string;
  title: string;       // ≤ 28 chars
  family: HypnosisFamily;
  target: string;      // the line / goal / state it serves
  purpose: string;     // what the session is for, honestly
  suggestions: string; // the overt suggestion themes the script should carry
  imagery: string;     // the sensory scene(s) to build
  length: string;      // recommended runtime
};

export const HYPNOSIS_TOPICS: HypnosisTopic[] = [
  // ── Line-targeted rehearsal (16) ──────────────────────────────────────────
  { id: "emotional-steadiness", title: "Emotional Steadiness", family: "line", target: "Emotional line",
    purpose: "Rehearse meeting a strong emotion — yours or someone else's — without being run by it.",
    suggestions: "Name the feeling, breathe around it, let it crest and pass; 'I can feel this fully and still choose my next move.'",
    imagery: "Standing calm in shallow surf: waves arrive, break against you, and drain away while your footing holds.", length: "12–15 min" },
  { id: "street-smarts-scan", title: "Street-Smarts Scan", family: "line", target: "Street Smarts line",
    purpose: "Sharpen the habit of reading rooms, incentives, and angles before acting.",
    suggestions: "Slow down the entrance; ask 'who wants what here'; trust the detail that doesn't fit; act early, not paranoid.",
    imagery: "Walking into a busy marketplace and calmly noticing everything — exits, faces, the deal behind the deal.", length: "10–12 min" },
  { id: "money-composure", title: "Money Composure", family: "line", target: "Financial line",
    purpose: "Rehearse calm, deliberate money decisions — the pause between impulse and purchase, the unemotional look at the numbers.",
    suggestions: "'Numbers are information, not verdicts'; open the account statement breathing slowly; delay any decision 24 hours.",
    imagery: "Sitting at a clean desk at dawn, ledgers open, heartbeat slow, moving one number at a time with full attention.", length: "12–15 min" },
  { id: "follow-through", title: "Follow-Through", family: "line", target: "Volitional line",
    purpose: "Strengthen the identity of a person who finishes — rehearsing the exact moment of wanting to quit and continuing anyway.",
    suggestions: "'The urge to stop is a sensation, not an instruction'; see the finished thing; start the next smallest step.",
    imagery: "Mile eighteen of a marathon: legs heavy, breath steady, one lamppost at a time, and the finish line growing.", length: "12–15 min" },
  { id: "clear-reasoning", title: "Clear Reasoning", family: "line", target: "Logical line",
    purpose: "Prime unhurried, sequential thinking before analytical work — slowing the jump to conclusions.",
    suggestions: "'One claim at a time'; ask what would change my mind; separate what I know from what I want.",
    imagery: "A workshop bench with a complex mechanism disassembled into ordered parts, each examined under a bright lamp.", length: "10–12 min" },
  { id: "reading-the-room", title: "Reading the Room", family: "line", target: "Interpersonal line",
    purpose: "Rehearse genuine curiosity about other minds — listening past words to what people are protecting and hoping.",
    suggestions: "'Everyone is the hero of a story I haven't heard yet'; ask one more question; notice who's gone quiet.",
    imagery: "A dinner table seen with warm x-ray vision — feeling each person's day arrive at the table with them.", length: "12–15 min" },
  { id: "inner-honesty", title: "Inner Honesty", family: "line", target: "Intrapersonal line",
    purpose: "A structured meeting with yourself: what am I actually feeling, wanting, avoiding — said plainly, without flinching.",
    suggestions: "'I can know this about myself and remain on my own side'; name the avoided thing once, gently.",
    imagery: "A quiet study with a fireplace and two chairs — you, and the version of you that always tells the truth.", length: "15–20 min" },
  { id: "creative-permission", title: "Creative Permission", family: "line", target: "Creative line",
    purpose: "Dissolve the pre-judgment that kills drafts — rehearse making bad first versions freely and shipping.",
    suggestions: "'Quantity buys quality'; the critic is invited to the SECOND draft only; done is a form of beautiful.",
    imagery: "A sunlit studio where every surface holds a cheerful, imperfect prototype — and the door where finished work leaves.", length: "12–15 min" },
  { id: "calm-command", title: "Calm Command", family: "line", target: "Leadership line",
    purpose: "Rehearse being the least anxious person in the room — steady voice, clear ask, warm authority under pressure.",
    suggestions: "'Calm is contagious and so is panic — I choose what I spread'; decide, communicate, own it.",
    imagery: "A ship's bridge in weather: instruments read, orders given quietly, the crew steadying because you are steady.", length: "12–15 min" },
  { id: "magnetic-presence", title: "Magnetic Presence", family: "line", target: "Seduction line",
    purpose: "Rehearse unhurried, attentive presence — the charisma of full attention honestly given, nothing performed.",
    suggestions: "'I am completely here, and that is enough'; slow the pace; enjoy the person in front of you.",
    imagery: "A long conversation at a corner table where time goes soft — you, fully arrived, nowhere else to be.", length: "10–12 min" },
  { id: "lightness-on-demand", title: "Lightness on Demand", family: "line", target: "Humor line",
    purpose: "Loosen the grip of over-seriousness — rehearse finding the absurd angle and the well-timed lighter touch.",
    suggestions: "'Almost nothing is as heavy as it's pretending to be'; look for the angle that makes it human.",
    imagery: "Watching your own stressful day replayed as an affectionate comedy — narrated by someone who loves you.", length: "10–12 min" },
  { id: "patient-parenting", title: "Patient Parenting", family: "line", target: "Parenting line",
    purpose: "Rehearse the hardest parenting moments — tantrum, defiance, the button only your child can press — met with regulated warmth.",
    suggestions: "'My calm is the lesson'; get low, get quiet, get curious; repair fast after rupture.",
    imagery: "Kneeling to a small storming person and becoming the lighthouse instead of the second storm.", length: "12–15 min" },
  { id: "pattern-sight", title: "Pattern Sight", family: "line", target: "Pattern-Recognition line",
    purpose: "Prime the wide-angle mind that lets recurring shapes surface — in markets, behavior, your own history.",
    suggestions: "'What does this remind me of'; zoom out one level; let the data speak before the story does.",
    imagery: "Rising slowly above a landscape until the paths people walk reveal their geometry.", length: "10–12 min" },
  { id: "body-signal-tuning", title: "Body Signal Tuning", family: "line", target: "Interoceptive line",
    purpose: "Train the inward channel: a slow, precise tour of the body's signals — hunger, tension, fatigue, ease — read early.",
    suggestions: "'My body reports before my mind decides'; find the signal's edge, name it, thank it.",
    imagery: "A dim control room coming online: gauge by gauge lighting up — jaw, chest, gut — each with its honest reading.", length: "15–20 min" },
  { id: "composure-under-fire", title: "Composure Under Fire", family: "line", target: "Adversarial line",
    purpose: "Rehearse staying strategic when someone is working against you — pressure, insult, bad-faith moves — without freezing or flaring.",
    suggestions: "'Their move is information'; slow the exchange down; protect the goal, not the ego.",
    imagery: "A chess table in a loud room: noise everywhere, and your hand moving only when the move is right.", length: "12–15 min" },
  { id: "meaning-anchor", title: "Meaning Anchor", family: "line", target: "Existential line",
    purpose: "Reconnect daily effort to what it's actually for — a session for the weeks when the point goes missing.",
    suggestions: "'This day is a brick in something I chose'; recall the chooser; choose again on purpose.",
    imagery: "Standing at a high overlook at dusk seeing your whole path — where it came from, where it's pointed, why.", length: "15–20 min" },
  // ── State sessions (10) ───────────────────────────────────────────────────
  { id: "deep-sleep-descent", title: "Deep Sleep Descent", family: "state", target: "Sleep onset",
    purpose: "A descent protocol for racing-mind bedtimes — downshifting body first, thoughts second.",
    suggestions: "Heavy limbs, slow warm breath, 'the day is filed; nothing needs me until morning.'",
    imagery: "Descending a wide staircase, ten floors, each darker and warmer, into a room that is only bed.", length: "20 min (designed to be slept through)" },
  { id: "morning-ignition", title: "Morning Ignition", family: "state", target: "Morning activation",
    purpose: "The anti-snooze: a short session that trades grog for deliberate ignition and a chosen first hour.",
    suggestions: "'Feet on floor starts the engine'; preview the first three moves of the day; light, water, motion.",
    imagery: "Sunrise filling a kitchen; the day's first hour laid out like tools on a clean bench.", length: "8–10 min" },
  { id: "pre-performance-calm", title: "Pre-Performance Calm", family: "state", target: "Pre-performance nerves",
    purpose: "The green-room session: convert stage adrenaline into focus before anything that counts.",
    suggestions: "'This energy is fuel, not fear'; slow exhale twice as long as inhale; first thirty seconds rehearsed.",
    imagery: "Backstage in warm half-dark, crowd murmur beyond the curtain — and the curtain opening to a room that wants you to win.", length: "8–10 min" },
  { id: "deep-focus-entry", title: "Deep Focus Entry", family: "state", target: "Focus block entry",
    purpose: "A launch ramp into deep work — closing the mental tabs and entering the single-task tunnel on purpose.",
    suggestions: "'Everything else has an appointment later'; one target named; the first ugly minute begun.",
    imagery: "A library carrel with one perfect pool of lamplight; the rest of the world politely out of frame.", length: "8–10 min" },
  { id: "stress-discharge", title: "Stress Discharge", family: "state", target: "Post-stress downshift",
    purpose: "The decompression chamber between a hard day and your actual evening — discharging the residue on purpose.",
    suggestions: "Shoulders drop, jaw unclenches, 'the day ends when I end it'; leave work at a marked door.",
    imagery: "Hanging up a heavy coat of the day on a hook by the door — and feeling the exact weight leave.", length: "10–12 min" },
  { id: "quiet-confidence", title: "Quiet Confidence", family: "state", target: "Baseline confidence",
    purpose: "Rehearse operating from evidence-based self-respect — recalling proof, not pep talk.",
    suggestions: "'I have receipts'; recall three handled hard things in sensory detail; walk in at that height.",
    imagery: "A corridor hung with accurate portraits of your hardest wins, walked slowly, ending at today's door.", length: "10–12 min" },
  { id: "public-speaking-ease", title: "Public Speaking Ease", family: "state", target: "Speaking anxiety",
    purpose: "Systematic rehearsal of the whole speaking arc — walking up, opening line, the friendly faces, the recovery from a stumble.",
    suggestions: "'The audience wants me to succeed'; stumble, smile, continue — rehearsed until boring.",
    imagery: "Delivering the first minute to a warm room over and over, each repetition smoother, until it feels like a hallway you know.", length: "12–15 min" },
  { id: "exam-steadiness", title: "Exam Steadiness", family: "state", target: "Test-day nerves",
    purpose: "Rehearse the test-day sequence — the blank moment, the skipped question, the reset breath — until the day feels rehearsed.",
    suggestions: "'A blank mind is a pause, not a verdict'; skip, breathe, return; what I know is still in there.",
    imagery: "Sitting down to the paper as a pilot to a preflight checklist — every contingency already flown.", length: "10–12 min" },
  { id: "cold-approach-courage", title: "Cold-Approach Courage", family: "state", target: "Sales & outreach courage",
    purpose: "For the dial tone and the doorstep: rehearse the moment before the ask, and a relationship with 'no' that keeps you swinging.",
    suggestions: "'Every no is a paid rep'; the first sentence rehearsed; warmth over polish; next call within a minute.",
    imagery: "A batting cage: pitch after pitch, misses shrugged off, the swing grooving — and loving the at-bat itself.", length: "10–12 min" },
  { id: "difficult-conversation", title: "Hard-Talk Rehearsal", family: "state", target: "Difficult conversations",
    purpose: "Rehearse the conversation you're avoiding — opening line, their worst response, your regulated reply — until avoidance loses its grip.",
    suggestions: "'Clear is kind'; say the true sentence early; their reaction is theirs to have; stay in your chair.",
    imagery: "Two chairs in a quiet room: the talk run three times — easy, hard, and real — your voice level in all three.", length: "15 min" },
  // ── Future-pacing (8) ─────────────────────────────────────────────────────
  { id: "ninety-day-rehearsal", title: "90-Day Goal Rehearsal", family: "future", target: "Any 90-day goal",
    purpose: "Classic future-pacing: live a day, ninety days out, with the goal already achieved — in enough sensory detail that the path back to today feels obvious.",
    suggestions: "'This is what done feels like'; walk backward from the achieved day to today's single next action.",
    imagery: "Waking up on day ninety: the room, the body, the schedule, the proof — then the film run in reverse to now.", length: "15–20 min" },
  { id: "career-vision-walk", title: "Career Vision Walk", family: "future", target: "Career direction",
    purpose: "A guided tour of the working life you're actually building toward — used to make Monday's choices sort themselves.",
    suggestions: "'My calendar votes for my future'; notice which current habits exist in that future and which don't.",
    imagery: "Shadowing your future self through a full workday — the room, the work, the people, the way it feels to be them.", length: "15–20 min" },
  { id: "financial-discipline", title: "Wealth-Builder Identity", family: "future", target: "Saving & investing behavior",
    purpose: "Future-pace the compounding decade: rehearse the identity of a person whose automatic behaviors build wealth quietly.",
    suggestions: "'I pay my future first'; feel the transfer leave on payday and land somewhere that grows.",
    imagery: "Standing in the same doorway at five-year intervals, watching the same small habits change every number in the room.", length: "12–15 min" },
  { id: "training-adherence", title: "Training Adherence", family: "future", target: "Exercise consistency",
    purpose: "Rehearse the skip-day moment — shoes on despite the mood — and future-pace the body and energy on the far side of consistency.",
    suggestions: "'I train on the days I don't feel like it — those are the ones that count'; shoes on is the whole decision.",
    imagery: "The version of you one year of unbroken Tuesdays from now, met and briefly inhabited.", length: "10–12 min" },
  { id: "deep-work-identity", title: "Deep Work Identity", family: "future", target: "Focused-professional identity",
    purpose: "Install the self-image of a person whose mornings are deep, whose phone waits, and whose output shows it.",
    suggestions: "'I am someone who goes deep before noon'; the closed door as self-respect, not rudeness.",
    imagery: "A reputation arriving before you into rooms: the one who does the real work — and the quiet mornings that built it.", length: "10–12 min" },
  { id: "morning-routine-install", title: "Routine Install", family: "future", target: "Morning routine adherence",
    purpose: "Mentally rehearse the exact morning sequence — anchor by anchor — until the real one runs on rails.",
    suggestions: "Each step chains to the last; 'the routine runs me, and I built the routine.'",
    imagery: "The morning executed once in slow motion, each anchor glowing as it completes, ending ahead of the day.", length: "10 min" },
  { id: "comeback-blueprint", title: "Comeback Blueprint", family: "future", target: "Recovery after setback",
    purpose: "Future-pace the rebuilt version: the person eighteen months after the loss, sturdier for it — and the first brick they laid.",
    suggestions: "'The setback is material'; find the first brick; lay it today.",
    imagery: "Walking through the rebuilt structure — stronger where it broke — with the memory of laying brick one.", length: "15 min" },
  { id: "founding-member-year", title: "The Measured Year", family: "future", target: "Using your AQAL profile",
    purpose: "Future-pace one year of actually running your profile's plan — the weak line raised, the feedback loop kept, the compounding felt.",
    suggestions: "'Thirty minutes at lunch, five days a week'; see the 30-day re-maps stacking into a different year.",
    imagery: "Twelve monthly maps of your own mind laid in a row — watching one line rise across them like a sunrise.", length: "12–15 min" },
  // ── Habit support (8) ─────────────────────────────────────────────────────
  { id: "urge-surfing", title: "Urge Surfing", family: "habit", target: "Any craving or urge",
    purpose: "The classic urge-surfing protocol in session form: ride the wave of a craving to its crest and down the far side without acting.",
    suggestions: "'Urges peak and pass in minutes — I can outlast weather'; locate it in the body; breathe at it.",
    imagery: "Surfing a swell that rises, rises — and always, always breaks and flattens into calm water.", length: "10–12 min" },
  { id: "procrastination-break", title: "Procrastination Break", family: "habit", target: "Task avoidance",
    purpose: "Rehearse the five-minute start — the only proven exit from avoidance — until beginning is smaller than dreading.",
    suggestions: "'I only owe it five minutes'; the dread is the biggest part and it dies on contact.",
    imagery: "A huge gray boulder that, touched, turns out to be paper-mâché — and light enough to move.", length: "10 min" },
  { id: "phone-loosening", title: "Phone Loosening", family: "habit", target: "Compulsive phone use",
    purpose: "Loosen the reach-grab loop: rehearse noticing the reach, feeling the itch pass, and returning to the room.",
    suggestions: "'The reach is a reflex, not a need'; one breath before any unlock; the room is where life is.",
    imagery: "The phone dimming into an ordinary tool on a shelf — while the actual room turns up its color and sound.", length: "10–12 min" },
  { id: "bedtime-boundary", title: "Bedtime Boundary", family: "habit", target: "Revenge bedtime procrastination",
    purpose: "For the one-more-episode hour: rehearse closing the day deliberately instead of scrolling past your own bedtime.",
    suggestions: "'Tomorrow-me is someone I take care of'; the day is allowed to end; closing ritual, then descent.",
    imagery: "Turning off a house light by light, each switch a small kept promise, the last one your own.", length: "10–12 min" },
  { id: "mindful-plate", title: "Mindful Plate", family: "habit", target: "Autopilot eating",
    purpose: "Rehearse eating as a single-task activity — pace, taste, and the body's actual enough-signal heard in time.",
    suggestions: "'Fork down between bites'; taste the third bite as fully as the first; stop at enough, not at empty.",
    imagery: "One meal in vivid slow motion — color, heat, salt — and the quiet gauge that says 'enough' being heard.", length: "10–12 min" },
  { id: "impulse-spend-pause", title: "Impulse-Spend Pause", family: "habit", target: "Impulse purchases",
    purpose: "Install the 24-hour pause: rehearse the add-to-cart moment becoming a note-to-tomorrow instead of a charge.",
    suggestions: "'If it's real, it survives a day'; feel the buying itch AS an itch; future-me signs the receipts.",
    imagery: "A checkout page fading into a parking lot ticket stamped TOMORROW — and most tickets, tomorrow, left unclaimed.", length: "10 min" },
  { id: "steady-hands", title: "Steady Hands", family: "habit", target: "Fidget habits (nail-biting etc.)",
    purpose: "A competing-response rehearsal for body-focused fidget loops: catch the hand en route, give it a job, release the loop.",
    suggestions: "'Hands have better work'; catch, redirect, soften; the urge decays every time it's caught.",
    imagery: "Hands resting warm and heavy on your lap like well-trained animals — alert, calm, employed.", length: "10 min" },
  { id: "evening-alcohol-swap", title: "The Unwind Swap", family: "habit", target: "The autopilot evening drink",
    purpose: "Rehearse a real decompression that arrives BEFORE the default pour — so the unwind need gets met on purpose. (Habit support for the autopilot pattern — dependence is clinical territory: see a professional.)",
    suggestions: "'What I want is the exhale, and I can pour that straight'; ritual, glass, breath — contents optional.",
    imagery: "The evening's first ten minutes rebuilt: the chair, the music, the long exhale arriving BEFORE any bottle decision.", length: "12 min" },
  // ── Recovery & processing (8) ─────────────────────────────────────────────
  { id: "post-conflict-cooldown", title: "Post-Conflict Cooldown", family: "recover", target: "After an argument",
    purpose: "The half-hour-after session: discharge the adrenaline, reclaim your side of it, and choose the repair move.",
    suggestions: "'I can be right later; I can be regulated now'; find your 10 percent; plan one repair sentence.",
    imagery: "A shaken snow-globe set down on a shelf — watching the storm inside settle clear in its own time.", length: "12–15 min" },
  { id: "letting-go-ledger", title: "The Letting-Go Ledger", family: "recover", target: "Old resentments",
    purpose: "A structured release of a carried grievance — not excusing, un-carrying: for your sake, on your schedule.",
    suggestions: "'Putting this down is strength, not surrender'; the debt is real AND the carrying is optional.",
    imagery: "Setting a heavy ledger down on a stone table, writing 'carried long enough,' and walking lighter without it.", length: "15–20 min" },
  { id: "self-compassion-repair", title: "Self-Compassion Repair", family: "recover", target: "Harsh self-talk after failure",
    purpose: "Rehearse speaking to yourself after a miss the way you'd speak to someone you're coaching — accurate AND on your side.",
    suggestions: "'Accountable without cruelty'; what would I tell my best friend; take the lesson, drop the lash.",
    imagery: "Reviewing the game film beside a coach who's exacting, warm, and completely convinced of your next season.", length: "12–15 min" },
  { id: "inner-critic-volume", title: "Inner-Critic Volume", family: "recover", target: "The running critic",
    purpose: "Not silencing the critic — re-hiring it: volume down, timing fixed (after drafts, not during), tone civilized.",
    suggestions: "'Noted — you're on after the draft'; the critic works for me now; its old fear job is done.",
    imagery: "A backseat driver moved to the map desk: still sharp-eyed, no longer grabbing the wheel.", length: "12 min" },
  { id: "rumination-interrupt", title: "Rumination Interrupt", family: "recover", target: "Thought loops",
    purpose: "A pattern-interrupt for the 2am replay: notice the loop, file it, and hand the mind a better track.",
    suggestions: "'This loop has no new information'; written down is handled; the body anchors what the mind circles.",
    imagery: "A record skipping — and your hand simply lifting the needle, sleeving the record, choosing another.", length: "12–15 min" },
  { id: "rejection-recovery", title: "Rejection Recovery", family: "recover", target: "After a no — sales, dating, work",
    purpose: "The between-rounds corner: metabolize a rejection in minutes, keep the lesson, and get back in the ring with your swing intact.",
    suggestions: "'A no is a door, not a diagnosis'; extract one improvement; next attempt scheduled before the sting fades.",
    imagery: "A boxer's corner between rounds: water, one instruction, breath — and rising for the next round loose.", length: "10–12 min" },
  { id: "worry-unwinding", title: "Worry Unwinding", family: "recover", target: "Everyday worry",
    purpose: "For garden-variety worry (clinical anxiety is clinician territory): sort the controllables, schedule the rest, unwind the body underneath.",
    suggestions: "'Worry is planning without a pen'; two lists — mine and not-mine; the second list handed over nightly.",
    imagery: "Untangling a knotted rope one loop at a time and coiling it clean — same rope, no knot.", length: "12–15 min" },
  { id: "grief-adjacent-gentleness", title: "Heavy-Season Gentleness", family: "recover", target: "Hard seasons (loss-adjacent)",
    purpose: "Not grief therapy — a gentleness protocol for heavy seasons: lowering the performance bar, keeping the basics, letting time do its slow work. (Real grief deserves real human support.)",
    suggestions: "'The bar this season is kept-alive, not optimized'; eat, sleep, walk, one person who knows.",
    imagery: "A winter garden tended lightly — nothing forced to bloom, everything kept alive for spring.", length: "15–20 min" },
];

export const HYPNOSIS_IDS: string[] = HYPNOSIS_TOPICS.map((t) => t.id);
export function hypnosisById(id: string): HypnosisTopic | undefined {
  return HYPNOSIS_TOPICS.find((t) => t.id === id);
}
