// ============================================================
// THERAPY → KIND classification. Lives in shared/ so both the
// client pages and the shared SEO sitemap (best-protocol combo
// pages) can read it. Re-exported by client/src/lib/therapyKinds.
// ============================================================
export const THERAPY_KIND: Record<string, string> = {
  "Action Video Game Training": "skill",
  "Acupuncture": "somatic",
  "Aerobic Exercise": "physical",
  "Approximate Number System Training": "skill",
  "Behavioral Activation": "psychotherapy",
  "Bibliotherapy (Guided Self-Help)": "psychotherapy",
  "Biofeedback HRV": "neuromodulation",
  "CBT-I (Cognitive Behavioral Therapy for Insomnia)": "psychotherapy",
  "Clinical Hypnosis": "psychotherapy",
  "Cognitive Defusion (ACT)": "psychotherapy",
  "Cognitive Processing Therapy (CPT)": "psychotherapy",
  "Cognitive Stimulation Therapy (CST)": "skill",
  "Cold Exposure (Wim Hof)": "somatic",
  "Communication Skills Training (structured, feedback-based)": "skill",
  "Compassion-Focused Therapy (CFT)": "psychotherapy",
  "Complex Problem Solving Microworlds": "skill",
  "Contingency Management": "psychotherapy",
  "DBT (Linehan)": "psychotherapy",
  "Dance Therapy (Wu 2021)": "expressive",
  "Dialogic Argumentation Practice": "skill",
  "EMDR": "psychotherapy",
  "Emotionally Focused Couples Therapy (EFT)": "relational",
  "Emotionally Focused Therapy (EFT)": "psychotherapy",
  "Executive Coaching": "skill",
  "Financial Education Programs": "skill",
  "Float Tanks REST": "somatic",
  "Flow State Training": "skill",
  "Forest Bathing (Shinrin-yoku)": "physical",
  "Forgiveness Interventions (Wade)": "psychotherapy",
  "Goal-Setting Theory (SMART goals)": "skill",
  "Gottman Method Couples Therapy": "relational",
  "Gratitude Interventions": "mindfulness",
  "Group Therapy": "community",
  "Gut Microbiome Probiotics": "lifestyle",
  "Habit Stacking": "skill",
  "High-Validity Feedback Environments (deliberate intuition training)": "skill",
  "Implementation Intentions (Gollwitzer)": "skill",
  "Individualized Instrumental Instruction (adult)": "skill",
  "Internal Family Systems (IFS)": "psychotherapy",
  "Interpersonal Therapy (IPT)": "psychotherapy",
  "Ketamine-Assisted Therapy": "psychedelic",
  "Laughter Therapy": "expressive",
  "Light Therapy": "lifestyle",
  "Logotherapy (Frankl)": "psychotherapy",
  "MBCT (Mindfulness-Based Cognitive Therapy)": "mindfulness",
  "MBSR (Mindfulness-Based Stress Reduction)": "mindfulness",
  "MDMA-Assisted Therapy": "psychedelic",
  "Meaning-Oriented Grief Therapy (Neimeyer)": "psychotherapy",
  "Mediterranean Diet": "lifestyle",
  "Mentalization-Based Treatment (MBT)": "psychotherapy",
  "Mindful Self-Compassion (MSC)": "mindfulness",
  "Motivational Interviewing Training": "skill",
  "Music Therapy": "expressive",
  "Musical Training as Neuroplasticity Protocol": "skill",
  "Narrative Therapy": "psychotherapy",
  "Negotiation Skills Training": "skill",
  "Neurofeedback": "neuromodulation",
  "Occupational Therapy (CO-OP)": "skill",
  "Parent-Child Interaction Therapy (PCIT)": "relational",
  "Perceptual Learning Modules": "skill",
  "Pet-Assisted Therapy": "expressive",
  "Polyvagal Exercises": "somatic",
  "Positive Psychology Interventions (Strengths-Based)": "mindfulness",
  "Progressive Muscle Relaxation (PMR)": "somatic",
  "Prolonged Exposure (PE)": "psychotherapy",
  "Psilocybin-Assisted Therapy": "psychedelic",
  "Psychodynamic Therapy": "psychotherapy",
  "Reminiscence Therapy": "psychotherapy",
  "Resistance Training": "physical",
  "Sandplay Therapy": "expressive",
  "Schema Therapy": "psychotherapy",
  "Self-Compassion (Neff)": "mindfulness",
  "Self-Distancing Third-Person Self-Talk (Kross)": "skill",
  "Social Prescribing": "community",
  "Social Skills Training (romantic-adjacent)": "skill",
  "Solution-Focused Brief Therapy (SFBT)": "psychotherapy",
  "Somatic Experiencing": "somatic",
  "Spaced Repetition Retrieval Practice": "skill",
  "Spatial Skills Training (mental rotation, sketching, gesture)": "skill",
  "Statistical Reasoning Training": "skill",
  "Structured Aesthetic Appraisal Practice": "skill",
  "Structured Negotiation Pedagogy": "skill",
  "Structured Philosophical Dialogue (P4C-style communities of inquiry)": "skill",
  "Systems Dynamics Training": "skill",
  "Tai Chi": "somatic",
  "Targeted Financial Literacy Instruction": "skill",
  "Transcendental Meditation ™": "mindfulness",
  "Transcranial Magnetic Stimulation (TMS)": "neuromodulation",
  "Trauma-Focused CBT (TF-CBT)": "psychotherapy",
  "Virtual Reality Exposure Therapy": "psychotherapy",
  "Walking in Nature": "physical",
  "Yoga Nidra (NSDR)": "mindfulness",
  // Batch 2 — authored Aug 2026 (citations pending external audit).
  "Acceptance and Commitment Therapy (ACT)": "psychotherapy",
  "Active Listening Training": "skill",
  "After-Action Reviews (structured debriefs)": "skill",
  "Art Therapy (visual)": "expressive",
  "Assertiveness Training": "skill",
  "Attention Training Technique (ATT)": "psychotherapy",
  "Best Possible Self Exercise": "skill",
  "Body-Scan Meditation": "mindfulness",
  "CBT-Based Anger Management": "psychotherapy",
  "Checklist Implementation": "skill",
  "Choir Singing (group)": "community",
  "Circle of Security Parenting": "relational",
  "Cognitive Bias Modification": "psychotherapy",
  "Cognitive Reappraisal Training": "psychotherapy",
  "Compassion Cultivation Training (CCT)": "mindfulness",
  "Complicated Grief Treatment (Shear)": "psychotherapy",
  "Dignity Therapy": "psychotherapy",
  "Emotion Coaching (Gottman)": "relational",
  "Error-Management Training": "skill",
  "Exposure and Response Prevention (ERP)": "psychotherapy",
  "Expressive Writing (Pennebaker)": "psychotherapy",
  "Forecasting Calibration Training": "skill",
  "Group Drumming Programs": "expressive",
  "Habit Reversal Training": "psychotherapy",
  "Hatha Yoga (general practice)": "somatic",
  "High-Intensity Interval Training (HIIT)": "physical",
  "Horticultural Therapy": "physical",
  "Imagery Rehearsal Therapy": "psychotherapy",
  "Improvisational Theater Training": "expressive",
  "Instructional Self-Talk Training": "skill",
  "Integrative Behavioral Couples Therapy": "relational",
  "Interpersonal and Social Rhythm Therapy": "psychotherapy",
  "JOBS Program (job-search training)": "skill",
  "Loving-Kindness Meditation": "mindfulness",
  "Martial Arts Training": "physical",
  "Meaning-Centered Group Psychotherapy": "psychotherapy",
  "Mental Contrasting (WOOP)": "skill",
  "Mental Practice (Motor Imagery)": "skill",
  "Metacognitive Therapy (Wells)": "psychotherapy",
  "Mindful Eating Training": "mindfulness",
  "Mindfulness-Based Relapse Prevention": "mindfulness",
  "Multisystemic Therapy (MST)": "relational",
  "One-on-One Financial Coaching": "skill",
  "Parent Management Training (Incredible Years)": "relational",
  "Perspective-Taking Training": "skill",
  "Premarital Relationship Education (PREP)": "relational",
  "Premortem Technique (Klein)": "skill",
  "Problem-Solving Therapy": "psychotherapy",
  "Public-Speaking Exposure Training": "psychotherapy",
  "Qigong Practice": "somatic",
  "Savoring Practice": "mindfulness",
  "Second-Language Learning (adult)": "skill",
  "Self-Regulated Learning Training": "skill",
  "Slow-Paced (Resonance) Breathing": "somatic",
  "Stress Inoculation Training": "psychotherapy",
  "Structured Volunteering": "community",
  "Team Sport Participation": "community",
  "Time-Management Training": "skill",
  "Triple P (Positive Parenting Program)": "relational",
  "Twelve-Step Facilitation / AA Linkage": "community",
  "Unified Protocol (Barlow)": "psychotherapy",
  "Wellness Recovery Action Planning (WRAP)": "skill",
  "Worry Postponement (Stimulus Control)": "psychotherapy",
  "Written Exposure Therapy": "psychotherapy",
};

