// ============================================================
// THERAPY → INTELLIGENCE-LINE MAP (audit-derived lookup table)
// ============================================================
// Source: the Manus therapy→line mapping audit (Aug 2026) over the 143
// audited, citation-backed therapies — parsed, deduped, and validated
// against ALL_AXES. Powers "more that lifts this line" prescriptions on
// top of the curated keystone practices. Role = how directly the therapy
// targets the line (PRIMARY strongest).

export type TherapyRole = "PRIMARY" | "SECONDARY" | "TERTIARY";
export type TherapyLineEntry = { line: string; therapy: string; role: TherapyRole };

export const THERAPY_LINE_MAP: TherapyLineEntry[] = [
  { line: "Adaptive", therapy: "Occupational Therapy", role: "PRIMARY" },
  { line: "Adaptive", therapy: "Ketamine-Assisted Therapy", role: "SECONDARY" },
  { line: "Adaptive", therapy: "Cognitive Defusion", role: "TERTIARY" },
  { line: "Adaptive", therapy: "Light Therapy", role: "TERTIARY" },
  { line: "Adaptive", therapy: "Solution-Focused Brief Therapy", role: "TERTIARY" },
  { line: "Adaptive", therapy: "Stimulation", role: "TERTIARY" },
  { line: "Community-Founding", therapy: "Social Prescribing", role: "SECONDARY" },
  { line: "Community-Founding", therapy: "Group Therapy", role: "TERTIARY" },
  { line: "Empathic", therapy: "Forgiveness Interventions", role: "PRIMARY" },
  { line: "Empathic", therapy: "Pet-Assisted Therapy", role: "PRIMARY" },
  { line: "Empathic", therapy: "(CFT)", role: "SECONDARY" },
  { line: "Empathic", therapy: "(EFT)", role: "SECONDARY" },
  { line: "Empathic", therapy: "Group Therapy", role: "SECONDARY" },
  { line: "Empathic", therapy: "Interpersonal Therapy (IPT)", role: "SECONDARY" },
  { line: "Empathic", therapy: "MDMA-Assisted Therapy", role: "SECONDARY" },
  { line: "Empathic", therapy: "Mindful Self-Compassion (MSC)", role: "TERTIARY" },
  { line: "Empathic", therapy: "Self-Compassion (Neﬀ)", role: "TERTIARY" },
  { line: "Existential", therapy: "Grief Therapy", role: "PRIMARY" },
  { line: "Existential", therapy: "Ketamine-Assisted Therapy", role: "PRIMARY" },
  { line: "Existential", therapy: "Logotherapy", role: "PRIMARY" },
  { line: "Existential", therapy: "Narrative Therapy", role: "PRIMARY" },
  { line: "Existential", therapy: "Psilocybin-Assisted Therapy", role: "PRIMARY" },
  { line: "Existential", therapy: "12-Step Programs (AA/NA)", role: "SECONDARY" },
  { line: "Existential", therapy: "Reminiscence Therapy", role: "SECONDARY" },
  { line: "Humor", therapy: "Laughter Therapy", role: "PRIMARY" },
  { line: "Influence", therapy: "Executive Coaching", role: "PRIMARY" },
  { line: "Integrative", therapy: "Internal Family Systems (IFS)", role: "SECONDARY" },
  { line: "Integrative", therapy: "EMDR", role: "TERTIARY" },
  { line: "Integrative", therapy: "Psilocybin-Assisted Therapy", role: "TERTIARY" },
  { line: "Interoceptive", therapy: "Biofeedback (HRV)", role: "PRIMARY" },
  { line: "Interoceptive", therapy: "Clinical Hypnosis", role: "PRIMARY" },
  { line: "Interoceptive", therapy: "Float Tanks REST", role: "PRIMARY" },
  { line: "Interoceptive", therapy: "Polyvagal Exercises", role: "PRIMARY" },
  { line: "Interoceptive", therapy: "Progressive Muscle Relaxation", role: "PRIMARY" },
  { line: "Interoceptive", therapy: "Somatic Experiencing", role: "PRIMARY" },
  { line: "Interoceptive", therapy: "Yoga Nidra / NSDR", role: "PRIMARY" },
  { line: "Interoceptive", therapy: "Acupuncture", role: "SECONDARY" },
  { line: "Interoceptive", therapy: "CBT-I for Insomnia", role: "SECONDARY" },
  { line: "Interoceptive", therapy: "EMDR", role: "SECONDARY" },
  { line: "Interoceptive", therapy: "Gut Microbiome Probiotics", role: "SECONDARY" },
  { line: "Interoceptive", therapy: "Light Therapy", role: "SECONDARY" },
  { line: "Interoceptive", therapy: "Sleep Restriction Therapy", role: "SECONDARY" },
  { line: "Interoceptive", therapy: "Stress Reduction", role: "SECONDARY" },
  { line: "Interoceptive", therapy: "Tai Chi", role: "SECONDARY" },
  { line: "Interoceptive", therapy: "Transcendental Meditation (TM)", role: "SECONDARY" },
  { line: "Interoceptive", therapy: "Cognitive Therapy", role: "TERTIARY" },
  { line: "Interoceptive", therapy: "Forest Bathing (Shinrin-yoku)", role: "TERTIARY" },
  { line: "Interoceptive", therapy: "Mediterranean Diet", role: "TERTIARY" },
  { line: "Interpersonal", therapy: "(EFT)", role: "PRIMARY" },
  { line: "Interpersonal", therapy: "(MBT)", role: "PRIMARY" },
  { line: "Interpersonal", therapy: "Group Therapy", role: "PRIMARY" },
  { line: "Interpersonal", therapy: "Interpersonal Therapy (IPT)", role: "PRIMARY" },
  { line: "Interpersonal", therapy: "Social Prescribing", role: "PRIMARY" },
  { line: "Interpersonal", therapy: "Forgiveness Interventions", role: "SECONDARY" },
  { line: "Interpersonal", therapy: "12-Step Programs (AA/NA)", role: "TERTIARY" },
  { line: "Interpersonal", therapy: "Cognitive Stimulation Therapy", role: "TERTIARY" },
  { line: "Interpersonal", therapy: "Executive Coaching", role: "TERTIARY" },
  { line: "Interpersonal", therapy: "Laughter Therapy", role: "TERTIARY" },
  { line: "Interpersonal", therapy: "Psychodynamic Therapy", role: "TERTIARY" },
  { line: "Intrapersonal", therapy: "(CFT)", role: "PRIMARY" },
  { line: "Intrapersonal", therapy: "Bibliotherapy guided self-help", role: "PRIMARY" },
  { line: "Intrapersonal", therapy: "Internal Family Systems (IFS)", role: "PRIMARY" },
  { line: "Intrapersonal", therapy: "Mindful Self-Compassion (MSC)", role: "PRIMARY" },
  { line: "Intrapersonal", therapy: "Psychodynamic Therapy", role: "PRIMARY" },
  { line: "Intrapersonal", therapy: "Sandplay/Play Therapy", role: "PRIMARY" },
  { line: "Intrapersonal", therapy: "Schema Therapy", role: "PRIMARY" },
  { line: "Intrapersonal", therapy: "Self-Compassion (Neﬀ)", role: "PRIMARY" },
  { line: "Intrapersonal", therapy: "(MBT)", role: "SECONDARY" },
  { line: "Intrapersonal", therapy: "Psilocybin-Assisted Therapy", role: "SECONDARY" },
  { line: "Intrapersonal", therapy: "(EFT)", role: "TERTIARY" },
  { line: "Intrapersonal", therapy: "Float Tanks REST", role: "TERTIARY" },
  { line: "Intrapersonal", therapy: "Forgiveness Interventions", role: "TERTIARY" },
  { line: "Intrapersonal", therapy: "Gratitude Interventions", role: "TERTIARY" },
  { line: "Intrapersonal", therapy: "Grief Therapy", role: "TERTIARY" },
  { line: "Intrapersonal", therapy: "Interpersonal Therapy (IPT)", role: "TERTIARY" },
  { line: "Intrapersonal", therapy: "Interventions", role: "TERTIARY" },
  { line: "Intrapersonal", therapy: "MDMA-Assisted Therapy", role: "TERTIARY" },
  { line: "Intrapersonal", therapy: "Music Therapy", role: "TERTIARY" },
  { line: "Intrapersonal", therapy: "Narrative Therapy", role: "TERTIARY" },
  { line: "Intrapersonal", therapy: "Polyvagal Exercises", role: "TERTIARY" },
  { line: "Intrapersonal", therapy: "Prolonged Exposure", role: "TERTIARY" },
  { line: "Intrapersonal", therapy: "Reminiscence Therapy", role: "TERTIARY" },
  { line: "Intrapersonal", therapy: "Self-Talk", role: "TERTIARY" },
  { line: "Intrapersonal", therapy: "Somatic Experiencing", role: "TERTIARY" },
  { line: "Intrapersonal", therapy: "Transcendental Meditation (TM)", role: "TERTIARY" },
  { line: "Intuitive", therapy: "Flow State Training", role: "SECONDARY" },
  { line: "Intuitive", therapy: "Sandplay/Play Therapy", role: "SECONDARY" },
  { line: "Kinesthetic", therapy: "Aerobic Exercise", role: "PRIMARY" },
  { line: "Kinesthetic", therapy: "Dance Therapy", role: "PRIMARY" },
  { line: "Kinesthetic", therapy: "Resistance Training", role: "PRIMARY" },
  { line: "Kinesthetic", therapy: "Tai Chi", role: "PRIMARY" },
  { line: "Kinesthetic", therapy: "Exercise)", role: "SECONDARY" },
  { line: "Kinesthetic", therapy: "Occupational Therapy", role: "SECONDARY" },
  { line: "Kinesthetic", therapy: "Progressive Muscle Relaxation", role: "SECONDARY" },
  { line: "Linguistic", therapy: "Cognitive Stimulation Therapy", role: "PRIMARY" },
  { line: "Logical", therapy: "Cognitive Stimulation Therapy", role: "SECONDARY" },
  { line: "Logical", therapy: "Implementation Intentions", role: "TERTIARY" },
  { line: "Meta-Cognitive", therapy: "(CPT)", role: "PRIMARY" },
  { line: "Meta-Cognitive", therapy: "Cognitive Defusion", role: "PRIMARY" },
  { line: "Meta-Cognitive", therapy: "Cognitive Therapy", role: "PRIMARY" },
  { line: "Meta-Cognitive", therapy: "Neurofeedback", role: "PRIMARY" },
  { line: "Meta-Cognitive", therapy: "Retrieval Practice", role: "PRIMARY" },
  { line: "Meta-Cognitive", therapy: "Self-Talk", role: "PRIMARY" },
  { line: "Meta-Cognitive", therapy: "Clinical Hypnosis", role: "SECONDARY" },
  { line: "Meta-Cognitive", therapy: "Trauma-Focused CBT", role: "SECONDARY" },
  { line: "Meta-Cognitive", therapy: "(MBT)", role: "TERTIARY" },
  { line: "Meta-Cognitive", therapy: "CBT-I for Insomnia", role: "TERTIARY" },
  { line: "Meta-Cognitive", therapy: "Internal Family Systems (IFS)", role: "TERTIARY" },
  { line: "Meta-Cognitive", therapy: "Schema Therapy", role: "TERTIARY" },
  { line: "Meta-Cognitive", therapy: "Stress Reduction", role: "TERTIARY" },
  { line: "Meta-Cognitive", therapy: "Tai Chi", role: "TERTIARY" },
  { line: "Meta-Cognitive", therapy: "Yoga Nidra / NSDR", role: "TERTIARY" },
  { line: "Musical", therapy: "Music Therapy", role: "PRIMARY" },
  { line: "Musical", therapy: "Dance Therapy", role: "SECONDARY" },
  { line: "Naturalistic", therapy: "Exercise)", role: "PRIMARY" },
  { line: "Naturalistic", therapy: "Forest Bathing (Shinrin-yoku)", role: "PRIMARY" },
  { line: "Naturalistic", therapy: "Pet-Assisted Therapy", role: "TERTIARY" },
  { line: "Philosophical", therapy: "Logotherapy", role: "SECONDARY" },
  { line: "Reflective", therapy: "12-Step Programs (AA/NA)", role: "PRIMARY" },
  { line: "Reflective", therapy: "Gratitude Interventions", role: "PRIMARY" },
  { line: "Reflective", therapy: "Reminiscence Therapy", role: "PRIMARY" },
  { line: "Reflective", therapy: "Bibliotherapy guided self-help", role: "SECONDARY" },
  { line: "Reflective", therapy: "Interventions", role: "SECONDARY" },
  { line: "Reflective", therapy: "Narrative Therapy", role: "SECONDARY" },
  { line: "Reflective", therapy: "Psychodynamic Therapy", role: "SECONDARY" },
  { line: "Reflective", therapy: "Schema Therapy", role: "SECONDARY" },
  { line: "Reflective", therapy: "(CPT)", role: "TERTIARY" },
  { line: "Reflective", therapy: "Trauma-Focused CBT", role: "TERTIARY" },
  { line: "Resilient", therapy: "Acupuncture", role: "PRIMARY" },
  { line: "Resilient", therapy: "EMDR", role: "PRIMARY" },
  { line: "Resilient", therapy: "Gut Microbiome Probiotics", role: "PRIMARY" },
  { line: "Resilient", therapy: "Interventions", role: "PRIMARY" },
  { line: "Resilient", therapy: "Light Therapy", role: "PRIMARY" },
  { line: "Resilient", therapy: "MDMA-Assisted Therapy", role: "PRIMARY" },
  { line: "Resilient", therapy: "Prolonged Exposure", role: "PRIMARY" },
  { line: "Resilient", therapy: "Stimulation", role: "PRIMARY" },
  { line: "Resilient", therapy: "Stress Reduction", role: "PRIMARY" },
  { line: "Resilient", therapy: "Transcendental Meditation (TM)", role: "PRIMARY" },
  { line: "Resilient", therapy: "Trauma-Focused CBT", role: "PRIMARY" },
  { line: "Resilient", therapy: "(CPT)", role: "SECONDARY" },
  { line: "Resilient", therapy: "Aerobic Exercise", role: "SECONDARY" },
  { line: "Resilient", therapy: "Biofeedback (HRV)", role: "SECONDARY" },
  { line: "Resilient", therapy: "Cognitive Defusion", role: "SECONDARY" },
  { line: "Resilient", therapy: "Cognitive Therapy", role: "SECONDARY" },
  { line: "Resilient", therapy: "Float Tanks REST", role: "SECONDARY" },
  { line: "Resilient", therapy: "Forest Bathing (Shinrin-yoku)", role: "SECONDARY" },
  { line: "Resilient", therapy: "Gratitude Interventions", role: "SECONDARY" },
  { line: "Resilient", therapy: "Grief Therapy", role: "SECONDARY" },
  { line: "Resilient", therapy: "Laughter Therapy", role: "SECONDARY" },
  { line: "Resilient", therapy: "Mediterranean Diet", role: "SECONDARY" },
  { line: "Resilient", therapy: "Mindful Self-Compassion (MSC)", role: "SECONDARY" },
  { line: "Resilient", therapy: "Music Therapy", role: "SECONDARY" },
  { line: "Resilient", therapy: "Pet-Assisted Therapy", role: "SECONDARY" },
  { line: "Resilient", therapy: "Polyvagal Exercises", role: "SECONDARY" },
  { line: "Resilient", therapy: "Self-Compassion (Neﬀ)", role: "SECONDARY" },
  { line: "Resilient", therapy: "Self-Talk", role: "SECONDARY" },
  { line: "Resilient", therapy: "Somatic Experiencing", role: "SECONDARY" },
  { line: "Resilient", therapy: "Yoga Nidra / NSDR", role: "SECONDARY" },
  { line: "Resilient", therapy: "(CFT)", role: "TERTIARY" },
  { line: "Resilient", therapy: "Behavioral Activation", role: "TERTIARY" },
  { line: "Resilient", therapy: "Clinical Hypnosis", role: "TERTIARY" },
  { line: "Resilient", therapy: "Exercise)", role: "TERTIARY" },
  { line: "Resilient", therapy: "Ketamine-Assisted Therapy", role: "TERTIARY" },
  { line: "Resilient", therapy: "Neurofeedback", role: "TERTIARY" },
  { line: "Resilient", therapy: "Progressive Muscle Relaxation", role: "TERTIARY" },
  { line: "Resilient", therapy: "Resistance Training", role: "TERTIARY" },
  { line: "Resilient", therapy: "Social Prescribing", role: "TERTIARY" },
  { line: "Spatial", therapy: "Dance Therapy", role: "TERTIARY" },
  { line: "Spatial", therapy: "Sandplay/Play Therapy", role: "TERTIARY" },
  { line: "Strategic", therapy: "Executive Coaching", role: "SECONDARY" },
  { line: "Strategic", therapy: "goals", role: "TERTIARY" },
  { line: "Systematic", therapy: "design", role: "PRIMARY" },
  { line: "Systematic", therapy: "Retrieval Practice", role: "SECONDARY" },
  { line: "Systematic", therapy: "Contingency Management", role: "TERTIARY" },
  { line: "Systematic", therapy: "Sleep Restriction Therapy", role: "TERTIARY" },
  { line: "Tactical", therapy: "Flow State Training", role: "PRIMARY" },
  { line: "Tactical", therapy: "Solution-Focused Brief Therapy", role: "PRIMARY" },
  { line: "Tactical", therapy: "goals", role: "PRIMARY" },
  { line: "Tactical", therapy: "Behavioral Activation", role: "SECONDARY" },
  { line: "Tactical", therapy: "Contingency Management", role: "SECONDARY" },
  { line: "Tactical", therapy: "Implementation Intentions", role: "SECONDARY" },
  { line: "Tactical", therapy: "Occupational Therapy", role: "TERTIARY" },
  { line: "Tactical", therapy: "design", role: "TERTIARY" },
  { line: "Volitional", therapy: "Behavioral Activation", role: "PRIMARY" },
  { line: "Volitional", therapy: "CBT-I for Insomnia", role: "PRIMARY" },
  { line: "Volitional", therapy: "Contingency Management", role: "PRIMARY" },
  { line: "Volitional", therapy: "Implementation Intentions", role: "PRIMARY" },
  { line: "Volitional", therapy: "Mediterranean Diet", role: "PRIMARY" },
  { line: "Volitional", therapy: "Sleep Restriction Therapy", role: "PRIMARY" },
  { line: "Volitional", therapy: "Neurofeedback", role: "SECONDARY" },
  { line: "Volitional", therapy: "Prolonged Exposure", role: "SECONDARY" },
  { line: "Volitional", therapy: "Resistance Training", role: "SECONDARY" },
  { line: "Volitional", therapy: "Solution-Focused Brief Therapy", role: "SECONDARY" },
  { line: "Volitional", therapy: "Stimulation", role: "SECONDARY" },
  { line: "Volitional", therapy: "design", role: "SECONDARY" },
  { line: "Volitional", therapy: "goals", role: "SECONDARY" },
  { line: "Volitional", therapy: "Aerobic Exercise", role: "TERTIARY" },
  { line: "Volitional", therapy: "Bibliotherapy guided self-help", role: "TERTIARY" },
  { line: "Volitional", therapy: "Flow State Training", role: "TERTIARY" },
  { line: "Volitional", therapy: "Retrieval Practice", role: "TERTIARY" },
];

/** Therapies mapped to a line, PRIMARY first. */
export function therapiesForLine(line: string, limit = 4): TherapyLineEntry[] {
  return THERAPY_LINE_MAP.filter((t) => t.line === line).slice(0, limit);
}

// Lines the audited-therapy literature does NOT yet cover (the research gap
// list — these lines rely on the wider library, not clinical therapies).
export const THERAPY_GAP_LINES = ["Mathematical", "Architectural", "Adversarial", "Aesthetic", "Seduction", "Financial-Self-Management"];
