// ============================================================
// MYTH WINGS — the museum's category system, mirroring what
// therapyKinds.ts does for the real protocol library. Every
// exhibit belongs to a wing; the wing carries the structural
// anatomy shared by its family: how the family claims to work,
// why it FEELS like it works (the honest psychology), the
// tell-tale signs, and the American-culture hook. The hook and
// seduction sections are cultural analysis and are labeled as
// analysis on the page — interpretation, not measurement.
// Coverage of every exhibit is enforced by test.
// ============================================================

export type WingProfile = {
  label: string;      // chip text
  pattern: string;    // how this family claims to work
  seduction: string;  // why it feels like it works — the honest psychology
  tell: string;       // the red flags that mark the family
  hook: string;       // the American-culture hook (labeled analysis)
};

export const WING_PROFILES: Record<string, WingProfile> = {
  "heroic-medicine": {
    label: "Heroic medicine — historical clinical overreach",
    pattern: "A dramatic physical intervention — bleeding, spinning, cutting, comas, radiation — justified by the reigning theory of its day and administered by its era's most credentialed authorities.",
    seduction: "Intensity impersonates efficacy. When a treatment visibly overwhelms the patient, everyone present — including the patient — experiences something happening, and 'something happening' is the mind's cheapest proof of healing. Add authority and desperation, and outcomes were simply never counted.",
    tell: "The treatment's drama is its argument; outcomes are testimonial; the era's experts closed ranks around it; and it collapsed the moment anyone ran an honest count.",
    hook: "Our analysis: America's medical marketplace has always rewarded the decisive gesture over the patient diary. The frontier surgeon who acts outranks the physician who waits — a preference that predates the republic's data.",
  },
  "miracle-cure": {
    label: "The miracle-cure hall — cancer & cure-all quackery",
    pattern: "One secret substance or procedure — suppressed, ancient, or newly discovered — claimed to cure the diseases medicine calls hardest, usually alongside a story about why the establishment hides it.",
    seduction: "Terminal diagnosis breaks the price mechanism of belief: when the alternative is nothing, any story with hope in it clears the market. Spontaneous remissions, staging errors, and the treatment-plus-real-care confound supply a steady drip of sincere testimonials.",
    tell: "Cures everything, cites patients instead of trials, explains missing evidence as suppression, and sells directly to the terrified. The conspiracy IS the product's immune system.",
    hook: "Our analysis: the suppressed-cure narrative fuses two founding American reflexes — distrust of concentrated power and faith in the garage inventor. It lets a purchase feel like a revolution.",
  },
  "substitution-harm": {
    label: "Substitution harms — when the myth takes the patient",
    pattern: "A treatment whose deepest cost is the real care it replaces: coercive programs, spiritual cures, and refusals administered while a treatable condition advances.",
    seduction: "These families sell meaning where medicine sells statistics. A cosmic diagnosis, a moral bootcamp, or a congregation's certainty offers identity and belonging — and the harm arrives on a delay, after the choice already feels like loyalty.",
    tell: "Leaving the treatment is framed as betrayal; the sick are blamed for failures ('you didn't believe enough'); and the outcome data, where anyone collected it, shows the substitution itself doing the damage.",
    hook: "Our analysis: a culture that moralizes health — where being well reads as being good — will always produce treatments that are really tests of virtue. Failing a virtue test feels different from failing a therapy, which is why patients protect these treatments to the end.",
  },
  "energy-device": {
    label: "The gadget gallery — energy fields, frequencies & devices",
    pattern: "An invisible force — magnetism, frequencies, ions, subtle energy — allegedly read or corrected by a device, a pendant, or trained hands. The force has never been demonstrated to exist; the hardware is the argument.",
    seduction: "Devices launder belief into measurement: dials, lights, and readouts borrow the laboratory's costume. Tingling, warmth, and relaxation during treatment are real sensations — supplied entirely by the body, credited entirely to the machine.",
    tell: "The mechanism can't be measured by anyone outside the field; blinded tests are refused or failed; and the same device treats dozens of unrelated conditions — a universality no real mechanism has.",
    hook: "Our analysis: America industrialized faith early — from patent-medicine electrotherapy onward, the gadget has been the national séance. A machine that heals lets a technological culture keep magic without admitting it.",
  },
  "purification": {
    label: "The purification wing — detox, cleansing & ordeal",
    pattern: "The body is framed as contaminated — by toxins, parasites, modern life itself — and the treatment is expulsion: cleanses, purges, sweats, fasts, and ordeals that produce visible, dramatic 'evidence' of what left you.",
    seduction: "Purging feels like progress because it produces artifacts: the stained pad, the brown water, the emptied gut, the survived ordeal. Relief after discomfort is read as healing, and the ritual's cost — suffering — is repurposed as its receipt.",
    tell: "The 'toxins' are never named or assayed; the proof is theater the protocol itself manufactures; and the organs that actually detoxify (liver, kidneys) are dismissed as insufficient without evidence.",
    hook: "Our analysis: purity is America's oldest inheritance — the Puritan body politic relocated into the colon. A culture soaked in abundance keeps buying absolution from it, one cleanse at a time.",
  },
  "pill-and-powder": {
    label: "The pill aisle — supplements that failed their exams",
    pattern: "A capsule, tincture, or powder promising medicine's benefits without medicine's gatekeepers — usually one real molecule or tradition stretched across a catalog of unrelated conditions.",
    seduction: "Swallowing something is the most rehearsed healing ritual in modern life; the form factor itself carries borrowed credibility. Regression to the mean does the rest — most conditions people supplement for fluctuate, and the pill gets credit for every upswing.",
    tell: "Structure/function weasel-wording ('supports,' 'boosts'), a mechanism story that stops at the stomach wall, and — the decisive one — large trials that exist and failed, still uncited on the label.",
    hook: "Our analysis: the supplement aisle is the deregulated id of American medicine — self-reliance, distrust of doctors, and shopping fused into a single gesture. The 1994 carve-out that freed it from efficacy testing made the aisle a monument to what the market does when proof is optional.",
  },
  "diet-cult": {
    label: "The diet-cult corridor — food as total explanation",
    pattern: "One dietary villain or savior — a blood type, a grain, a food dye, an all-meat plate — offered as the hidden cause of, and cure for, nearly everything wrong with body and mind.",
    seduction: "Any strict diet delivers a real honeymoon: attention to eating, dropped ultra-processed food, ritual structure, and community. The specific theory gets credit for generic benefits — and the restriction's cost gets reframed as devotion.",
    tell: "The theory explains everything, the elimination list grows over time, failures are blamed on imperfect compliance, and the blinded re-challenge — the one test that isolates the villain — is never run or never passed.",
    hook: "Our analysis: in a culture where the table lost its liturgy, diets supply one. Food rules are the last universally respected asceticism — the fastest route to feeling moral three times a day.",
  },
  "false-oracle": {
    label: "The false-oracle wing — pseudo-diagnostics & mind-reading",
    pattern: "A test — bumps, blots, blood drops, hair, gadget readouts, facial twitches — claiming to reveal hidden truths about your body, mind, or honesty that ordinary observation can't reach.",
    seduction: "A personalized report is inherently convincing: vague descriptions feel accurate when they arrive with your name on them (the Barnum effect), and any test that flags something feels like it caught something. The oracle's authority grows with the detail of its printout, not the validity of its method.",
    tell: "No published sensitivity or specificity; practitioners disagree with each other — and themselves — on identical samples; and the test conveniently diagnoses conditions only its vendor can treat.",
    hook: "Our analysis: America quantifies as a form of worship — the checkup, the credit score, the dashboard. A culture that trusts numbers over narratives will pay for fake numbers rather than sit with no number at all.",
  },
  "classroom-ghost": {
    label: "The classroom of ghosts — brain & learning products",
    pattern: "A drill, device, diet, or media product claiming to rewire the brain — smarter babies, cured dyslexia, unlocked potential — usually wrapped in the vocabulary of neuroscience and sold to parents and self-improvers.",
    seduction: "Children develop and adults practice — so anything administered alongside time and effort inherits their gains. 'Neuroplasticity' is real, which makes it the perfect loanword: the brain does change, just not because of the product.",
    tell: "Brain vocabulary without brain evidence; testimonials from parents rather than controlled cohorts; transfer claims (this drill improves everything) that the transfer literature specifically refutes; and pricing aimed at parental guilt.",
    hook: "Our analysis: American parenting is competitive admissions all the way down — the anxiety that a child's potential is being wasted is the most monetizable fear the culture produces, and the brain-product industry is its vending machine.",
  },
  "replication-graveyard": {
    label: "The replication graveyard — famous findings that fell",
    pattern: "A real study, by real scientists, in a real journal — whose dramatic result died under replication but lives on in keynotes, curricula, and product design. The failure here isn't fraud; it's a finding loved beyond its evidence.",
    seduction: "These ideas spread because they're excellent stories: a two-minute pose, a marshmallow, a smile that causes joy. Story-fitness and truth-fitness are different selection pressures, and the replication crisis is what happened when science finally checked which one had been winning.",
    tell: "The effect shrinks or vanishes when preregistered; the citation graph keeps growing anyway; and the strongest defenders are downstream industries — speakers, consultants, curricula — not the original data.",
    hook: "Our analysis: the TED-industrial complex is a distinctly American machine for converting preliminary findings into life advice at scale. A culture of self-optimization needs a constant supply of one-weird-trick science, and demand does not wait for replication.",
  },
  "unlicensed-couch": {
    label: "Therapy's unlicensed cousins — methods without evidence",
    pattern: "A branded therapeutic method — tapping sequences, gaze spots, ancestral constellations, trademarked touch — built around a proprietary mechanism, a certification pyramid, and a founder's revelation rather than controlled outcomes.",
    seduction: "Most contain a real therapeutic kernel: attention, exposure, catharsis, a caring witness. Clients genuinely feel better — through the common factors every therapy shares — and the brand claims the credit its proprietary mechanism never earned.",
    tell: "The mechanism is trademarked; training is tiered and expensive; dismantling studies (removing the special ingredient) change nothing; and the evidence page cites the founder more than the literature.",
    hook: "Our analysis: in a country where therapy is expensive and waitlisted, the certification economy fills the gap with confidence. Franchised healing is the wellness sector's answer to fast food — consistent, branded, and engineered for the seller's margins.",
  },
  "cosmic-counsel": {
    label: "Divination as counseling — the cosmos on retainer",
    pattern: "A system of hidden correspondences — stars, numbers, cycles, spirits, manifestation laws — offered as personal guidance, with the universe itself cast as your counselor.",
    seduction: "Divination systems are meaning machines: they always return an answer, the answer is always about you, and ambiguity lets every reading fit. Against life's genuine randomness, a cosmos that notices you is the product; accuracy was never the point.",
    tell: "Unfalsifiable by construction — hits are confirmed, misses are reinterpreted; the system predicts everything and therefore nothing; and its validity tests (they exist, they're old, they're unanimous) go permanently uncited.",
    hook: "Our analysis: America secularized faster than it found replacements. Astrology apps and manifestation coaches are congregations for the unchurched — the national religion of the self, with the universe recast as its responsive deity.",
  },
};

// Every exhibit id → its wing. Coverage enforced by test.
export const MYTH_WING: Record<string, string> = {
  // Historical foundations
  phrenology: "false-oracle",
  mesmerism: "energy-device",
  lobotomy: "heroic-medicine",
  "insulin-coma": "heroic-medicine",
  orgone: "energy-device",
  "trepanation-revival": "heroic-medicine",
  "facilitated-communication": "classroom-ghost",
  "recovered-memory": "unlicensed-couch",
  "conversion-therapy": "substitution-harm",
  "attachment-holding": "substitution-harm",
  cisd: "unlicensed-couch",
  "scared-straight": "substitution-harm",
  "dare-original": "substitution-harm",
  "boot-camps": "substitution-harm",
  "primal-scream": "unlicensed-couch",
  dianetics: "unlicensed-couch",
  "attack-therapy": "substitution-harm",
  "past-life-regression": "cosmic-counsel",
  polygraph: "false-oracle",
  graphology: "false-oracle",
  "learning-styles": "classroom-ghost",
  "brain-gym": "classroom-ghost",
  "mozart-effect": "classroom-ghost",
  "ten-percent-brain": "classroom-ghost",
  "left-right-brain": "classroom-ghost",
  "subliminal-tapes": "classroom-ghost",
  "speed-reading": "classroom-ghost",
  "sleep-learning": "classroom-ghost",
  "brain-training": "classroom-ghost",
  "growth-mindset-overclaim": "replication-graveyard",
  "power-posing": "replication-graveyard",
  "ego-depletion": "replication-graveyard",
  "mbti-clinical": "false-oracle",
  "enneagram-clinical": "false-oracle",
  "nlp-claims": "unlicensed-couch",
  homeopathy: "pill-and-powder",
  "bach-flowers": "pill-and-powder",
  "crystal-healing": "energy-device",
  "therapeutic-touch": "energy-device",
  "reiki-distant": "energy-device",
  "magnet-therapy": "energy-device",
  "ear-candling": "purification",
  "detox-cleanses": "purification",
  "adrenal-fatigue": "false-oracle",
  "candida-everything": "false-oracle",
  "applied-kinesiology": "false-oracle",
  craniosacral: "energy-device",
  "chiropractic-nonmsk": "miracle-cure",
  iridology: "false-oracle",
  "reflexology-diagnostic": "false-oracle",
  "grounding-claims": "energy-device",
  "binaural-claims": "energy-device",
  "essential-oil-cures": "pill-and-powder",
  "cbd-cure-all": "pill-and-powder",
  "microdosing-overclaim": "pill-and-powder",
  "law-of-attraction": "cosmic-counsel",
  "affirmations-backfire": "cosmic-counsel",
  "vision-boards": "cosmic-counsel",
  "astrology-counseling": "cosmic-counsel",
  numerology: "cosmic-counsel",
  "human-design": "cosmic-counsel",
  "psychic-mediums": "cosmic-counsel",
  "angel-therapy": "cosmic-counsel",
  "faith-healing-substitution": "substitution-harm",
  "intercessory-prayer-rct": "cosmic-counsel",
  "vaccines-autism": "substitution-harm",
  "chelation-autism": "substitution-harm",
  "mms-bleach": "substitution-harm",
  secretin: "miracle-cure",
  "dolphin-therapy": "unlicensed-couch",
  "wellness-mlm": "pill-and-powder",
  "prosperity-gospel-therapy": "cosmic-counsel",
  // Wing II–IV additions
  bloodletting: "heroic-medicine",
  "rotational-chair": "heroic-medicine",
  radithor: "heroic-medicine",
  "violet-ray": "energy-device",
  krebiozen: "miracle-cure",
  "refrigerator-mother": "heroic-medicine",
  rebirthing: "substitution-harm",
  orthomolecular: "pill-and-powder",
  laetrile: "miracle-cure",
  gerson: "miracle-cure",
  "black-salve": "miracle-cure",
  "shark-cartilage": "miracle-cure",
  essiac: "miracle-cure",
  "colloidal-silver": "miracle-cure",
  "ozone-therapy": "miracle-cure",
  "hbot-autism": "miracle-cure",
  "stem-cell-tourism": "miracle-cure",
  "iv-drips": "miracle-cure",
  "naturopathic-cancer": "substitution-harm",
  "exorcism-substitution": "substitution-harm",
  "troubled-teen": "substitution-harm",
  breatharianism: "purification",
  sungazing: "purification",
  kambo: "purification",
  "bee-venom": "heroic-medicine",
  "rasa-shastra": "pill-and-powder",
  aristolochia: "pill-and-powder",
  "placenta-encapsulation": "purification",
  "vaginal-steaming": "purification",
  "jade-eggs": "energy-device",
  "perineum-sunning": "purification",
  "urine-therapy": "purification",
  "oil-pulling": "purification",
  // Wing V–VI additions
  "hulda-clark-zapper": "energy-device",
  "rife-machines": "energy-device",
  bioresonance: "energy-device",
  radionics: "energy-device",
  "kirlian-aura": "false-oracle",
  "emf-harmonizers": "energy-device",
  "power-balance": "energy-device",
  "copper-bracelets": "energy-device",
  "pemf-consumer": "energy-device",
  "daith-piercing": "energy-device",
  "ionic-footbath": "purification",
  "detox-foot-pads": "purification",
  "salt-lamps": "energy-device",
  halotherapy: "purification",
  "oxygen-bars": "purification",
  "alkaline-water": "purification",
  "hydrogen-water": "pill-and-powder",
  "structured-water": "energy-device",
  solfeggio: "energy-device",
  chromotherapy: "energy-device",
  "blue-blockers": "classroom-ghost",
  "cryo-chambers": "heroic-medicine",
  "infrared-detox": "purification",
  "tdcs-consumer": "energy-device",
  "toning-shoes": "pill-and-powder",
  "kinesio-overclaim": "energy-device",
  "cupping-performance": "purification",
  "mouth-taping": "purification",
  "polyphasic-sleep": "purification",
  mewing: "classroom-ghost",
  "lymphatic-detox": "purification",
  // Wing VII–XII additions
  "live-blood-analysis": "false-oracle",
  "hair-mineral-analysis": "false-oracle",
  "igg-food-tests": "false-oracle",
  "mthfr-protocols": "false-oracle",
  "dna-diet-tests": "false-oracle",
  "microbiome-consumer": "false-oracle",
  "telomere-tests": "false-oracle",
  "epigenetic-clearing": "unlicensed-couch",
  airborne: "pill-and-powder",
  prevagen: "pill-and-powder",
  "ginkgo-memory": "pill-and-powder",
  "antioxidant-megadose": "pill-and-powder",
  "multivitamin-prevention": "pill-and-powder",
  "nootropic-stacks": "pill-and-powder",
  "t-boosters": "pill-and-powder",
  "celery-juice": "diet-cult",
  "acv-cureall": "diet-cult",
  "blood-type-diet": "diet-cult",
  "gaps-diet": "diet-cult",
  "feingold-cure": "diet-cult",
  "gluten-free-everyone": "diet-cult",
  "carnivore-cureall": "diet-cult",
  "doman-delacato": "classroom-ghost",
  "primitive-reflex": "classroom-ghost",
  "auditory-integration": "classroom-ghost",
  "son-rise": "classroom-ghost",
  "vision-therapy-ld": "classroom-ghost",
  "bates-method": "classroom-ghost",
  "irlen-lenses": "classroom-ghost",
  "dore-program": "classroom-ghost",
  "fast-forword": "classroom-ghost",
  "baby-genius-media": "classroom-ghost",
  "ambidexterity-movement": "classroom-ghost",
  "social-priming": "replication-graveyard",
  "marshmallow-destiny": "replication-graveyard",
  "facial-feedback-pencil": "replication-graveyard",
  "microexpression-detection": "false-oracle",
  "forensic-hypnosis": "false-oracle",
  "truth-serum": "false-oracle",
  "rorschach-overclaim": "false-oracle",
  "grit-revolution": "replication-graveyard",
  "ten-thousand-hours": "replication-graveyard",
  "eft-tapping": "unlicensed-couch",
  "thought-field-therapy": "unlicensed-couch",
  havening: "unlicensed-couch",
  brainspotting: "unlicensed-couch",
  "emotion-code": "unlicensed-couch",
  "family-constellations": "unlicensed-couch",
  lgat: "unlicensed-couch",
  "holotropic-overclaim": "unlicensed-couch",
  "ayahuasca-tourism": "unlicensed-couch",
  "equine-breakthrough": "unlicensed-couch",
  "indigo-children": "cosmic-counsel",
  biorhythms: "cosmic-counsel",
  "full-moon-effect": "cosmic-counsel",
};

export function wingFor(id: string): WingProfile | undefined {
  const w = MYTH_WING[id];
  return w ? WING_PROFILES[w] : undefined;
}
