// ============================================================
// THE MYTH MUSEUM — documented failed, debunked, and overclaimed
// therapies, each with: the claim, the verdict, WHY it failed
// (with a named, checkable source anchor), an honest analysis of
// its cultural appeal (labeled analysis, not fact), and where
// applicable a real, mapped alternative. Entries never contradict
// protocols in our own cited library. Source anchors are named
// works/rulings as documented in the skeptical and clinical
// literature; the standing citation audit covers this page family
// too (/corrections).
// ============================================================

export type MythVerdict = "DEBUNKED" | "NO EVIDENCE" | "HARMFUL" | "REPLICATION FAILED" | "OVERCLAIMED";

export type Myth = {
  id: string;
  name: string;
  claim: string;    // what it promised, one sentence
  verdict: MythVerdict;
  why: string;      // why it failed, sourced
  source: string;   // named checkable anchor (author/year/venue/ruling)
  appeal: string;   // the cultural-appeal analysis — labeled as analysis
  instead?: string; // a real library protocol or line to point to
};

export const MYTH_VERDICT_META: Record<MythVerdict, { color: string; note: string }> = {
  DEBUNKED: { color: "#E2604A", note: "tested properly, failed decisively" },
  "NO EVIDENCE": { color: "#D08B6C", note: "never produced controlled evidence for its claims" },
  HARMFUL: { color: "#C74634", note: "documented harm — worse than doing nothing" },
  "REPLICATION FAILED": { color: "#E0C68C", note: "a famous finding that would not replicate" },
  OVERCLAIMED: { color: "#CBAA6A", note: "a real kernel, sold far beyond its evidence" },
};

export const MYTHS: Myth[] = [
  // ── Historical foundations of overreach ─────────────────────
  { id: "phrenology", name: "Phrenology", verdict: "DEBUNKED",
    claim: "Skull bumps reveal character and mental faculties.",
    why: "Anatomy advanced and the skull-brain correspondence collapsed; controlled tests found zero predictive validity — the field survives only as the origin story of pseudo-neuroscience.",
    source: "As documented in histories of 19th-century neurology and modern re-tests (e.g., Parker Jones et al., 2018, Cortex).",
    appeal: "It offered what people still buy today: a fast, physical, no-effort readout of who someone really is.",
    instead: "A measured 32-line profile — slower, spoken, and checkable." },
  { id: "mesmerism", name: "Mesmerism / Animal Magnetism", verdict: "DEBUNKED",
    claim: "An invisible magnetic fluid, channeled by the healer, cures disease.",
    why: "The 1784 French Royal Commission (Franklin, Lavoisier) ran history's first blinded trials: effects followed belief, not magnets. The cures were real-feeling; the mechanism was imagination.",
    source: "The 1784 Franklin Commission report — the founding document of placebo-controlled testing.",
    appeal: "A charismatic healer plus an invisible force is the oldest and most durable therapeutic theater there is.",
    instead: "The placebo lesson itself: feeling better is not evidence of mechanism." },
  { id: "lobotomy", name: "Transorbital Lobotomy", verdict: "HARMFUL",
    claim: "Severing frontal-lobe connections cures mental illness.",
    why: "It traded agitation for blunted personhood; tens of thousands were damaged before follow-up studies and new medications ended it. A Nobel Prize was awarded for it — expert consensus is not evidence.",
    source: "As documented in the clinical histories of Freeman's practice and mid-century outcome reviews.",
    appeal: "Desperation plus institutional authority: when suffering is unbearable, drastic feels like decisive.",
    instead: "Evidence-tested psychotherapy and modern psychiatry — with outcome data." },
  { id: "insulin-coma", name: "Insulin Coma Therapy", verdict: "HARMFUL",
    claim: "Repeated insulin-induced comas cure schizophrenia.",
    why: "Controlled comparison (Ackner et al., 1957, Lancet) found outcomes no better than barbiturate sleep — the 'cures' were the ritual, and the comas killed some patients.",
    source: "Ackner, Harris & Oldham (1957), The Lancet.",
    appeal: "Dramatic, dangerous procedures feel powerful — the intensity of a treatment gets mistaken for its efficacy.",
    instead: "Nothing about intensity: dose–response must be measured, not felt." },
  { id: "orgone", name: "Orgone Therapy", verdict: "NO EVIDENCE",
    claim: "Sitting in a special box accumulates a universal life-energy that cures illness.",
    why: "Orgone energy was never detected by any instrument; the FDA enjoined the devices in 1954 after Reich offered no controlled evidence.",
    source: "U.S. FDA injunction proceedings, 1954.",
    appeal: "A scientific-sounding energy that mainstream science 'refuses to see' flatters the buyer as an insider.",
    instead: "Somatic protocols with trials — the body work in our library is cited." },
  { id: "trepanation-revival", name: "Modern Trepanation", verdict: "HARMFUL",
    claim: "Drilling a hole in the skull restores childhood consciousness and blood flow.",
    why: "There is no physiological basis and real surgical risk; no controlled evidence has ever existed — modern advocacy traces to a handful of self-experimenters, not studies.",
    source: "As documented in neurosurgical commentary on the modern advocacy movement.",
    appeal: "The ancient-wisdom frame: if early humans did it, it must encode lost knowledge rather than lost ignorance.",
    instead: "The Interoceptive line — reading your head without opening it." },

  // ── Debunked clinical psychotherapy ─────────────────────────
  { id: "facilitated-communication", name: "Facilitated Communication", verdict: "DEBUNKED",
    claim: "A facilitator supporting the hand lets non-verbal autistic people type fluent messages.",
    why: "Dozens of blinded message-passing tests found the same thing: when facilitators didn't know the answer, the typing didn't either. The words were the facilitator's — with devastating false-abuse accusations as collateral.",
    source: "Controlled reviews summarized by the American Psychological Association's 1994 resolution and subsequent replications.",
    appeal: "It let desperate families hear the voice they longed for — hope is the strongest confound there is.",
    instead: "Evidence-based augmentative communication, tested blind." },
  { id: "recovered-memory", name: "Recovered-Memory Therapy", verdict: "HARMFUL",
    claim: "Buried memories of trauma can be excavated intact through suggestion, hypnosis, and imagery.",
    why: "Memory research showed rich false memories are easy to implant; the therapy shattered families with confabulated accusations, and courts and licensing boards followed the science.",
    source: "Loftus's false-memory research program (e.g., Loftus & Pickrell, 1995, Psychiatric Annals).",
    appeal: "It offers a single hidden cause for diffuse pain — one buried key to explain everything.",
    instead: "Trauma-focused therapies in our library that treat the present symptoms, not archaeology." },
  { id: "conversion-therapy", name: "Conversion / Reparative Therapy", verdict: "HARMFUL",
    claim: "Sexual orientation can be changed through therapy.",
    why: "The APA's task force review found no credible evidence of orientation change and clear evidence of harm — depression, suicidality, family rupture. Banned for minors across much of the U.S.",
    source: "American Psychological Association Task Force Report, 2009.",
    appeal: "It sold a resolution to unbearable social and religious conflict — the market was shame, not science.",
    instead: "Affirming, evidence-based care. Full stop." },
  { id: "attachment-holding", name: "Holding / Rebirthing Attachment Therapy", verdict: "HARMFUL",
    claim: "Coercive restraint and simulated rebirth repair attachment in adopted children.",
    why: "No controlled evidence ever existed, and the practice killed — Candace Newmaker's 2000 death during a rebirthing session led to criminal convictions and state bans.",
    source: "As documented in the Newmaker case record and the APSAC task force report on attachment therapy (2006).",
    appeal: "It dressed control as love: a dramatic ritual promising to reset a child other methods moved slowly with.",
    instead: "Parent-Child Interaction Therapy — in our library, with trials." },
  { id: "cisd", name: "Single-Session Crisis Debriefing (CISD)", verdict: "HARMFUL",
    claim: "One mandatory group debriefing right after trauma prevents PTSD.",
    why: "Meta-analysis found no prevention — and signals of WORSE outcomes, plausibly by disrupting natural recovery. Institutions kept buying it for years because doing something visible beats doing nothing measurable.",
    source: "van Emmerik et al. (2002), The Lancet meta-analysis.",
    appeal: "Organizations need a ritual after tragedy; the ritual's audience was the org chart, not the survivors.",
    instead: "Watchful waiting plus indicated care (e.g., trauma-focused CBT) for those who develop symptoms." },
  { id: "scared-straight", name: "Scared Straight Programs", verdict: "HARMFUL",
    claim: "Terrifying at-risk teens with prison visits deters crime.",
    why: "Randomized trials pooled by Cochrane found the programs INCREASE offending. It ran for decades anyway, because the footage is spectacular television.",
    source: "Petrosino et al., Cochrane systematic review of Scared Straight programs.",
    appeal: "Punitive intuition: the belief that fear teaches, which feels truer than the data allows.",
    instead: "Skill-building interventions for the Volitional and Street Smarts lines." },
  { id: "dare-original", name: "D.A.R.E. (original curriculum)", verdict: "DEBUNKED",
    claim: "Police-led classroom lectures prevent teen drug use.",
    why: "Multiple large evaluations and meta-analyses found essentially zero effect on drug use; the program survived its own evidence for 20 years on institutional momentum before rewriting itself.",
    source: "West & O'Neal (2004), American Journal of Public Health meta-analysis.",
    appeal: "It let adults feel protective at scale — a visible program for an invisible fear.",
    instead: "Programs whose curricula were rebuilt around what trials supported." },
  { id: "boot-camps", name: "Teen Boot Camps / Tough-Love Wilderness Programs", verdict: "HARMFUL",
    claim: "Breaking teens down with military discipline rebuilds them.",
    why: "Recidivism studies found no benefit over regular supervision, and the U.S. GAO documented thousands of abuse allegations and multiple deaths in the troubled-teen industry.",
    source: "U.S. Government Accountability Office testimony, 2007.",
    appeal: "The transformation-through-ordeal myth — America's frontier story sold back to frightened parents.",
    instead: "Family-based therapies with trial evidence (in our library)." },
  { id: "primal-scream", name: "Primal Scream Therapy", verdict: "NO EVIDENCE",
    claim: "Reliving and screaming out birth pain cures neurosis.",
    why: "No controlled trial ever supported it; the theory (stored primal pain) was untestable by design, and outcomes were never tracked beyond testimonials.",
    source: "As reviewed in Lilienfeld et al., Science and Pseudoscience in Clinical Psychology (2003).",
    appeal: "Catharsis feels like progress — intensity of emotion mistaken for depth of change.",
    instead: "Emotion-focused therapies that measure outcomes, not volume." },
  { id: "dianetics", name: "Dianetics / Auditing", verdict: "NO EVIDENCE",
    claim: "Clearing 'engrams' with an E-meter produces superhuman mental function.",
    why: "The claimed engram mechanism has no empirical support; promised outcomes ('Clear') have never been demonstrated under controlled conditions in seven decades.",
    source: "As documented in decades of independent reviews of Hubbard's claims.",
    appeal: "A total system: one purchaseable ladder explaining all suffering, with status at every rung.",
    instead: "The 32-line map — which shows you the ladder's rungs are plural." },
  { id: "attack-therapy", name: "Attack Therapy (Synanon-style)", verdict: "HARMFUL",
    claim: "Brutal group verbal assault strips defenses and heals addiction.",
    why: "No controlled support ever existed; documented outcomes included trauma, coercive control, and the movement's collapse into abuses — a template repeated by later 'confrontation' programs.",
    source: "As documented in histories of Synanon and confrontation-based addiction programs.",
    appeal: "Cruelty wearing honesty's clothes — 'someone finally told the truth' is a powerful, dangerous feeling.",
    instead: "Motivational Interviewing — the opposite approach, with the evidence." },
  { id: "past-life-regression", name: "Past-Life Regression Therapy", verdict: "NO EVIDENCE",
    claim: "Hypnosis retrieves memories of former lives whose traumas explain today's symptoms.",
    why: "Hypnotic 'memories' track suggestion and imagination; checkable historical details fail verification at chance rates. It is confabulation with a costume department.",
    source: "Hypnosis and memory research reviewed in Spanos's work on past-life reports (1990s).",
    appeal: "It grants a self bigger than one lifetime — and outsources this life's pain to a previous tenant.",
    instead: "The Existential line: meaning built in the life you can verify." },
  { id: "polygraph", name: "The Polygraph as Lie Detector", verdict: "OVERCLAIMED",
    claim: "Physiology reveals deception reliably enough to grade truth.",
    why: "The National Academy of Sciences reviewed the evidence and found accuracy far below the claims, with dangerous error rates in both directions — yet it still gates jobs and shapes interrogations.",
    source: "National Research Council, The Polygraph and Lie Detection (2003).",
    appeal: "A machine that settles honesty removes the burden of judging people — accountability outsourced to a needle.",
    instead: "The Adversarial and Social-Perceptual lines — trained judgment, honestly bounded." },
  { id: "graphology", name: "Graphology (Handwriting Analysis)", verdict: "DEBUNKED",
    claim: "Handwriting reveals personality and job performance.",
    why: "Meta-analyses found validity indistinguishable from zero once content of the writing was controlled; it persisted in European hiring for decades anyway.",
    source: "Neter & Ben-Shakhar (1989), Personality and Individual Differences meta-analysis.",
    appeal: "Everyone leaves handwriting; a readable trace of the soul in something so personal feels intuitive.",
    instead: "Structured interviews and work samples — boring, and predictive." },

  // ── Education & self-improvement myths ──────────────────────
  { id: "learning-styles", name: "Learning-Styles Matching", verdict: "DEBUNKED",
    claim: "Teaching to a student's visual/auditory/kinesthetic style improves learning.",
    why: "The definitive review found the field's core prediction — style-matched instruction beats mismatched — almost never tested properly, and unsupported when it was. Preferences exist; matching benefits don't.",
    source: "Pashler, McDaniel, Rohrer & Bjork (2008), Psychological Science in the Public Interest.",
    appeal: "It flatters every learner as a special type and gives teachers a humane-sounding taxonomy.",
    instead: "Spaced Repetition Retrieval Practice — in our library, and it actually works for everyone." },
  { id: "brain-gym", name: "Brain Gym", verdict: "NO EVIDENCE",
    claim: "Specific movement exercises ('brain buttons') integrate brain hemispheres for learning.",
    why: "Its physiological claims are neurologically incoherent and its educational claims never survived controlled testing — UK scientists publicly dismantled it in schools.",
    source: "Reviewed critically by Goswami (2006), Nature Reviews Neuroscience, among others.",
    appeal: "It converts exercise's real general benefits into a proprietary, purchasable curriculum.",
    instead: "Aerobic Exercise — the real version, cited in our library." },
  { id: "mozart-effect", name: "The Mozart Effect", verdict: "REPLICATION FAILED",
    claim: "Listening to Mozart raises intelligence, especially in babies.",
    why: "Meta-analysis of dozens of attempts found a tiny, short-lived arousal effect — nothing about Mozart, nothing about lasting IQ. A U.S. state still shipped classical CDs to newborns.",
    source: "Pietschnig, Voracek & Formann (2010), Intelligence meta-analysis.",
    appeal: "Effortless enrichment: culture as a pill you can play at your child.",
    instead: "Individualized Instrumental Instruction — actually playing music, which does train the ear." },
  { id: "ten-percent-brain", name: "The 10% Brain Myth", verdict: "DEBUNKED",
    claim: "We use only 10% of our brains — unlocking the rest is possible.",
    why: "Imaging shows essentially all brain tissue active across ordinary days; lesion evidence shows no expendable 90%. The number was never a finding — it is a marketing artifact quoted into 'fact.'",
    source: "As documented across neuroimaging literature and myth surveys of educators (Dekker et al., 2012, Frontiers in Psychology).",
    appeal: "It monetizes hope of a locked room in the self — every seller of keys needs one.",
    instead: "The 32-line map: your capacity is plural, not percentage-gated." },
  { id: "left-right-brain", name: "Left-Brain / Right-Brain Personality", verdict: "DEBUNKED",
    claim: "People are logical left-brains or creative right-brains.",
    why: "Large-scale imaging found no global hemisphere dominance across individuals — lateralization is task-level, not personality-level.",
    source: "Nielsen et al. (2013), PLoS ONE, resting-state analysis of 1,011 brains.",
    appeal: "A two-box self is the cheapest identity on the market and fits on a mug.",
    instead: "Thirty-two boxes, measured — the un-mug-sized truth." },
  { id: "subliminal-tapes", name: "Subliminal Self-Help Tapes", verdict: "DEBUNKED",
    claim: "Messages below awareness reprogram self-esteem and memory while you relax.",
    why: "The classic double-cross experiment swapped labels and found improvement followed the LABEL, not the content — a pure placebo with a cassette price.",
    source: "Greenwald, Spangenberg, Pratkanis & Eskenazi (1991), Psychological Science.",
    appeal: "Change without effort or even attention — the perfected American convenience product.",
    instead: "Implementation Intentions — one deliberate minute that outperforms a thousand hidden whispers." },
  { id: "speed-reading", name: "Extreme Speed-Reading / PhotoReading", verdict: "DEBUNKED",
    claim: "Training lets you read thousands of words per minute with full comprehension.",
    why: "Reading science shows comprehension collapses past ~500–600 wpm; a NASA-funded test of PhotoReading found no advantage and worse comprehension. Skimming exists; magic doesn't.",
    source: "Rayner et al. (2016), Psychological Science in the Public Interest; McNamara's NASA evaluation (2000).",
    appeal: "Information anxiety: the pile grows, so buyers purchase a bigger shovel that turns out to be a picture of one.",
    instead: "Spaced retrieval on less material — comprehension compounds; blur doesn't." },
  { id: "sleep-learning", name: "Sleep Learning (Hypnopedia)", verdict: "DEBUNKED",
    claim: "Play recordings while sleeping and wake up knowing them.",
    why: "EEG-controlled studies found 'sleep-learned' material was learned in brief awakenings, not sleep; complex learning during verified sleep does not occur.",
    source: "Simon & Emmons (1956), Journal of Experimental Psychology — the controlled classic.",
    appeal: "It promises the third of life you can't optimize can be put to work anyway.",
    instead: "Sleep protection — sleep already consolidates learning; that part is real and in our library." },
  { id: "brain-training", name: "Commercial Brain-Training Games", verdict: "OVERCLAIMED",
    claim: "Daily app puzzles make you smarter and stave off decline.",
    why: "Training improves the trained puzzles; broad transfer to intelligence or daily cognition kept failing in trials — and the FTC fined Lumosity $2M for exactly these claims.",
    source: "FTC v. Lumos Labs settlement (2016); Simons et al. (2016), Psychological Science in the Public Interest review.",
    appeal: "Gamified virtue: it feels like the gym, bills like the gym, and transfers like a slot machine.",
    instead: "Complex Problem Solving Microworlds and real skill training — transfer is the test." },
  { id: "growth-mindset-overclaim", name: "Growth Mindset (as a cure-all)", verdict: "OVERCLAIMED",
    claim: "Teaching that ability is malleable transforms achievement across the board.",
    why: "The kernel replicates small and situational; the sweeping version doesn't — meta-analysis found weak average effects and many null implementations. A real idea, oversold into an educational religion.",
    source: "Macnamara & Burgoyne (2022), Psychological Bulletin meta-analysis.",
    appeal: "It moralizes optimism: failure becomes a fixable attitude, which comforts institutions more than it moves students.",
    instead: "Deliberate skill training with feedback — mindset follows competence more than it causes it." },
  { id: "power-posing", name: "Power Posing", verdict: "REPLICATION FAILED",
    claim: "Two minutes of expansive posture changes hormones and life outcomes.",
    why: "The hormonal and risk-taking effects failed high-powered replication; the original first author publicly disavowed the effect. The felt-confidence sliver may survive; the biology didn't.",
    source: "Ranehill et al. (2015), Psychological Science replication; Carney's public statement (2016).",
    appeal: "A TED-sized lever: enormous claimed output from adorable input is the signature shape of viral science.",
    instead: "Rhetorical and Leadership lines — trained delivery, not posture magic." },
  { id: "ego-depletion", name: "Ego Depletion (willpower as fuel tank)", verdict: "REPLICATION FAILED",
    claim: "Willpower draws on one small energy reserve that glucose refills.",
    why: "The multi-lab registered replication found no depletion effect; the glucose model collapsed. Self-control matters — the fuel-tank metaphor was the part that died.",
    source: "Hagger et al. (2016), Perspectives on Psychological Science registered replication report.",
    appeal: "It excused lapses biologically — 'my tank was empty' is kinder than 'my systems were absent.'",
    instead: "Habit Stacking and Implementation Intentions — structure outperforms tank management." },
  { id: "mbti-clinical", name: "Myers-Briggs (as clinical/hiring instrument)", verdict: "OVERCLAIMED",
    claim: "Sixteen types capture personality well enough to guide hiring, teams, and therapy.",
    why: "Psychometrics found weak test-retest stability (types flip on retake) and bimodality that isn't there; it predicts job performance about as well as astrology with better fonts. As entertainment: fine. As instrument: no.",
    source: "Pittenger (1993), Review of Educational Research, and subsequent psychometric reviews.",
    appeal: "Barnum warmth plus tribe membership — a flattering type is a souvenir self you can trade with friends.",
    instead: "Measured lines with error bars — less flattering, more true." },
  { id: "enneagram-clinical", name: "Enneagram (as diagnostic tool)", verdict: "NO EVIDENCE",
    claim: "Nine ancient types explain your core wound and growth path.",
    why: "Peer-reviewed validation is nearly absent; type assignment is unreliable across raters and instruments. Its lineage is esoteric, not empirical — which its best teachers admit and its industry doesn't.",
    source: "Reviewed in the sparse psychometric literature (e.g., Hook et al., 2021, Journal of Clinical Psychology review).",
    appeal: "It pairs confession with cosmology — your flaws get a sacred map, which therapy-flavored America finds irresistible.",
    instead: "The Intrapersonal line, measured against behavior instead of archetype." },
  { id: "nlp-claims", name: "NLP Practitioner Claims", verdict: "DEBUNKED",
    claim: "Eye-accessing cues, representational matching, and fast-phobia cures reprogram minds in minutes.",
    why: "Controlled tests of NLP's core tenets (eye cues, matching) failed repeatedly; reviews found the empirical base 'in tatters.' Useful communication heuristics exist inside it; the science costume does not fit.",
    source: "Witkowski (2010), Polish Psychological Bulletin systematic review.",
    appeal: "Engineering language for the psyche — 'programming' promises the precision therapy can't honestly offer.",
    instead: "Communication Skills Training — the tested core, minus the mythology." },

  // ── Energy, body, and wellness claims ───────────────────────
  { id: "homeopathy", name: "Homeopathy", verdict: "DEBUNKED",
    claim: "Substances diluted past a single remaining molecule cure like-with-like.",
    why: "Government-commissioned mega-reviews (Australia's NHMRC; UK Commons committee) found no condition for which it beats placebo — as chemistry predicts, since the remedies are water.",
    source: "NHMRC Statement on Homeopathy (2015); UK House of Commons S&T Committee (2010).",
    appeal: "Gentleness as ideology: medicine without side effects, because without effects.",
    instead: "Anything in our library — every entry has at least one molecule of evidence." },
  { id: "bach-flowers", name: "Bach Flower Remedies", verdict: "DEBUNKED",
    claim: "Flower essences in brandy-water rebalance emotional states.",
    why: "Systematic review of randomized trials found effects indistinguishable from placebo across all uses.",
    source: "Ernst (2010), Swiss Medical Weekly systematic review.",
    appeal: "Botanical innocence — nature's pharmacy, minus the pharmacy.",
    instead: "Emotion regulation training — the Empathic/Emotional line protocols." },
  { id: "crystal-healing", name: "Crystal Healing", verdict: "NO EVIDENCE",
    claim: "Mineral crystals channel healing energies into body and mind.",
    why: "No detectable mechanism, and the one controlled study found suggestion produced identical 'crystal sensations' with glass fakes.",
    source: "French, O'Donnell & Williams (2001), presented controlled comparison of real vs. sham crystals.",
    appeal: "Beauty as evidence — an object lovely enough to hold feels like it must be doing something.",
    instead: "The Aesthetic line: beauty matters; it just isn't medicine." },
  { id: "therapeutic-touch", name: "Therapeutic Touch", verdict: "DEBUNKED",
    claim: "Practitioners smooth the human energy field without touching the patient.",
    why: "A nine-year-old's blinded JAMA experiment asked practitioners to detect the field they claimed to manipulate: 44% accuracy — worse than coin-flipping at their own foundational claim.",
    source: "Rosa, Rosa, Sarner & Barrett (1998), JAMA.",
    appeal: "Care theater: focused attention from a calm person IS soothing — the field was never needed for that.",
    instead: "The real active ingredient — attentive human presence — which the relational protocols use openly." },
  { id: "reiki-distant", name: "Distant Reiki / Remote Energy Healing", verdict: "NO EVIDENCE",
    claim: "Healing energy transmitted across any distance treats illness.",
    why: "High-quality trials show effects matching placebo/relaxation controls; the proposed transmission violates known physics and has never been measured.",
    source: "Systematic reviews of reiki RCTs (e.g., Lee, Pittler & Ernst, 2008, International Journal of Clinical Practice).",
    appeal: "It converts love-at-a-distance — a real human ache — into a purchasable service.",
    instead: "Community-Founding: the measurable version of not being alone." },
  { id: "magnet-therapy", name: "Static Magnet Therapy", verdict: "DEBUNKED",
    claim: "Wearable magnets relieve pain and restore energy balance.",
    why: "Systematic review of randomized trials: no effect beyond placebo for pain; the fields are too weak to influence tissue, as basic physics indicated all along.",
    source: "Pittler, Brown & Ernst (2007), CMAJ systematic review.",
    appeal: "Invisible force, visible bracelet — the accessory that flatters both wrist and worldview.",
    instead: "Resistance Training — the magnetism of actually getting stronger." },
  { id: "ear-candling", name: "Ear Candling", verdict: "HARMFUL",
    claim: "A burning cone draws toxins and wax from the ear canal.",
    why: "Measurement showed no negative pressure and no wax removal — but documented burns and canal injuries; the 'toxins' in the stub are candle residue, burned by demonstration.",
    source: "Seely, Quigley & Langman (1996), Laryngoscope.",
    appeal: "Extraction rituals satisfy — SEEING the (fake) yield is the oldest trick in folk medicine.",
    instead: "Skepticism's starter kit: if the demo works on a table with no ear, it's the candle." },
  { id: "detox-cleanses", name: "Detox Cleanses (for mind and mood)", verdict: "NO EVIDENCE",
    claim: "Juice fasts and cleanse kits purge unnamed toxins causing fog and fatigue.",
    why: "Sellers cannot name the toxin, the dose removed, or the measurement — reviews find no evidence commercial detoxes remove anything your liver wasn't already handling.",
    source: "Klein & Kiat (2015), Journal of Human Nutrition and Dietetics review.",
    appeal: "Purity theology in a bottle: sin, fast, absolution — the liturgy survives secularization.",
    instead: "Mediterranean Diet — eating patterns with actual cognition data, in our library." },
  { id: "adrenal-fatigue", name: "Adrenal Fatigue", verdict: "DEBUNKED",
    claim: "Chronic stress exhausts your adrenal glands, explaining tiredness — supplements restore them.",
    why: "Systematic review of 58 studies found no consistent cortisol signature; endocrinology societies state the diagnosis does not exist. Real exhaustion, invented gland.",
    source: "Cadegiani & Kater (2016), BMC Endocrine Disorders systematic review.",
    appeal: "It gives burnout a biological name your doctor 'missed' — validation plus a supplement aisle.",
    instead: "The Interoceptive line + sleep protection: the real fatigue diagnostics." },
  { id: "candida-everything", name: "Chronic Candida Syndrome", verdict: "NO EVIDENCE",
    claim: "Hidden yeast overgrowth causes fatigue, fog, anxiety, and cravings in millions.",
    why: "The double-blind test of antifungal treatment for the alleged syndrome found no benefit over placebo; the diagnosis never entered evidence-based practice.",
    source: "Dismukes et al. (1990), New England Journal of Medicine.",
    appeal: "An enemy within — vague suffering prefers a nameable invader to a systems answer.",
    instead: "A 32-line systems answer." },
  { id: "applied-kinesiology", name: "Applied Kinesiology (Muscle Testing)", verdict: "DEBUNKED",
    claim: "Muscle strength changes reveal allergies, deficiencies, and truths held in the body.",
    why: "Blinded trials show diagnostic accuracy at chance — the effect is ideomotor: the tester's expectations move the arm, exactly as with dowsing rods.",
    source: "Kenney, Clemens & Forsythe (1988), Journal of the American Dietetic Association, and later blinded replications.",
    appeal: "The body-doesn't-lie romance: outsourcing hard decisions to a twitch feels like deep listening.",
    instead: "Interoception training — listening to the body without the puppet show." },
  { id: "craniosacral", name: "Craniosacral Therapy", verdict: "NO EVIDENCE",
    claim: "Subtle manipulation of skull rhythms treats conditions from colic to trauma.",
    why: "Inter-rater studies show practitioners can't agree on the 'rhythm' they claim to palpate — the diagnostic signal fails before treatment claims even begin.",
    source: "Wirth-Pattullo & Hayes (1994), Physical Therapy inter-rater reliability study.",
    appeal: "Precision cosplay: tiny, expert-feeling touches imply a mechanism too subtle for skeptics.",
    instead: "Somatic protocols that survived controlled testing — mapped in the library." },
  { id: "chiropractic-nonmsk", name: "Chiropractic for Non-Spinal Disease", verdict: "NO EVIDENCE",
    claim: "Spinal 'subluxations' cause organ disease; adjustment cures beyond back pain.",
    why: "The founding subluxation entity has no anatomical validation; reviews find no evidence for visceral-disease claims (back-pain care is a separate, partly supported question).",
    source: "Mirtz et al. (2009), Chiropractic & Osteopathy — epidemiological examination of subluxation.",
    appeal: "One-cause medicine: a single adjustable spine is tidier than multifactorial illness.",
    instead: "For the mind's alignment: the pre-mortem, not the adjustment table." },
  { id: "iridology", name: "Iridology", verdict: "DEBUNKED",
    claim: "The iris maps every organ; its flecks diagnose disease.",
    why: "Blinded tests asked iridologists to identify patients with known conditions from iris photos — accuracy at chance, with confident wrong diagnoses both directions.",
    source: "Simon, Worthen & Mitas (1979), JAMA blinded evaluation.",
    appeal: "The eye-as-window poetry, literalized into a billing system.",
    instead: "Measurement that survives blinding — our panel scores transcripts it can't cold-read." },
  { id: "reflexology-diagnostic", name: "Reflexology (diagnostic claims)", verdict: "NO EVIDENCE",
    claim: "Foot zones correspond to organs; pressure there diagnoses and treats them.",
    why: "Controlled tests found reflexologists' organ diagnoses at chance; systematic reviews find no condition convincingly treated. Foot massage remains pleasant — the map is fiction.",
    source: "White et al. (2000), Complementary Therapies in Medicine blinded diagnosis study; Ernst (2009) review.",
    appeal: "Miniature-map magic: the whole self conveniently reachable from the easiest part to rub.",
    instead: "Progressive Muscle Relaxation — relaxation minus cartography." },
  { id: "grounding-claims", name: "Earthing / Grounding (disease claims)", verdict: "OVERCLAIMED",
    claim: "Skin contact with the earth's electrons cures inflammation and disease.",
    why: "The pleasant kernel (being outside, barefoot, relaxed) is real; the electron-transfer disease mechanism has only tiny, conflicted, industry-adjacent studies behind sweeping claims.",
    source: "Critically reviewed against the small primary literature (e.g., Chevalier et al.) and its methodological limits.",
    appeal: "Rousseau with product placement: modernity as illness, sold with a $200 conductive bedsheet.",
    instead: "Walking in Nature — the same walk, with actual attention-restoration data." },
  { id: "binaural-claims", name: "Binaural Beats (transformation claims)", verdict: "OVERCLAIMED",
    claim: "Specific frequencies entrain brainwaves into focus, sleep, or altered states on demand.",
    why: "Meta-analysis shows small, inconsistent effects on mood/attention; the strong entrainment-to-enlightenment claims outrun the EEG evidence by miles.",
    source: "Garcia-Argibay et al. (2019), Psychological Research meta-analysis.",
    appeal: "Precision mysticism — a Hz number makes transcendence feel like engineering.",
    instead: "Yoga Nidra (NSDR) — in our library with its honest, bounded evidence tier." },
  { id: "essential-oil-cures", name: "Essential Oils (cure claims)", verdict: "OVERCLAIMED",
    claim: "Oils treat anxiety, depression, infections — an oil for every ill.",
    why: "Mild relaxation aromas show small effects; the cure-level claims drew FDA warning letters to major sellers for illegal disease marketing.",
    source: "U.S. FDA warning letters to dōTERRA and Young Living distributors (2014).",
    appeal: "Scent memory is real intimacy — the industry bottles grandma's kitchen and sells it as pharmacology.",
    instead: "For anxiety: protocols with trials. Keep the nice smell as a nice smell." },
  { id: "cbd-cure-all", name: "CBD (as panacea)", verdict: "OVERCLAIMED",
    claim: "CBD treats anxiety, pain, sleep, focus — everything, in gummy form.",
    why: "Beyond specific seizure disorders (real, approved), most consumer claims rest on underpowered or absent trials, with unregulated dosing that often doesn't match labels.",
    source: "FDA consumer warnings and label-accuracy analyses (e.g., Bonn-Miller et al., 2017, JAMA).",
    appeal: "A legal, gentle rebellion: wellness with a whiff of the counterculture, minus commitment.",
    instead: "Named protocols per named problem — the opposite of panacea." },
  { id: "microdosing-overclaim", name: "Microdosing (as proven enhancer)", verdict: "OVERCLAIMED",
    claim: "Tiny regular psychedelic doses reliably boost creativity, focus, and mood.",
    why: "Placebo-controlled studies (including the large self-blinded citizen trial) found expectancy explains most reported benefits. Full-dose clinical protocols are a different, real literature.",
    source: "Szigeti et al. (2021), eLife self-blinding citizen science trial.",
    appeal: "Silicon Valley alchemy: optimization culture's wish for a daily pill of genius.",
    instead: "The clinical psychedelic protocols in our library — supervised, dosed, and cited." },

  // ── Manifestation, divination & spiritual services ──────────
  { id: "law-of-attraction", name: "The Law of Attraction / The Secret", verdict: "NO EVIDENCE",
    claim: "Thoughts vibrate reality into compliance — visualize wealth and the universe delivers.",
    why: "No mechanism, no controlled support — and the testable kernel points the other way: research on positive fantasies finds they can REDUCE goal attainment by draining motivation.",
    source: "Oettingen's fantasy-realization research program (e.g., Kappes & Oettingen, 2011).",
    appeal: "The prosperity gospel secularized: American optimism promoted from virtue to physics.",
    instead: "Mental contrasting + implementation intentions — visualization WITH obstacles, which works." },
  { id: "affirmations-backfire", name: "Blanket Positive Affirmations", verdict: "OVERCLAIMED",
    claim: "Repeating 'I am lovable' rewires self-esteem for anyone.",
    why: "The controlled test found affirmations helped high-self-esteem people slightly — and made LOW-self-esteem people feel worse, the exact population the products target.",
    source: "Wood, Perunovic & Lee (2009), Psychological Science.",
    appeal: "Language as paint: America's faith that saying the house is beautiful renovates it.",
    instead: "Self-Compassion (Neff) — in our library; talks to yourself honestly instead." },
  { id: "vision-boards", name: "Vision Boards (as attainment method)", verdict: "OVERCLAIMED",
    claim: "Collaging your desires causes their arrival.",
    why: "Follows the positive-fantasy literature: imagining attainment without process planning can lower effort. Clarifying goals helps; laminating them does not summon them.",
    source: "Same fantasy-realization literature (Oettingen et al.).",
    appeal: "Craft-store agency — a rainy afternoon that feels like a business plan.",
    instead: "Goal staircases with honest clocks — the version of the board that ticks." },
  { id: "astrology-counseling", name: "Astrology-Based Counseling", verdict: "DEBUNKED",
    claim: "Birth charts reveal personality and destiny for life guidance.",
    why: "The definitive double-blind test — astrologers matching charts to detailed personality profiles — found accuracy at chance, with astrologer confidence unrelated to correctness.",
    source: "Carlson (1985), Nature double-blind test of astrology.",
    appeal: "Cosmic belonging: your struggles pre-written in the sky beats their being nobody's plan.",
    instead: "The Existential line — meaning made, not natal." },
  { id: "numerology", name: "Numerology Coaching", verdict: "NO EVIDENCE",
    claim: "Your name and birthdate's numbers dictate life path and decisions.",
    why: "No validation exists or has been attempted seriously; readings run on Barnum statements — universally applicable descriptions experienced as personal.",
    source: "Forer (1949), the classic demonstration of personal-validation fallacy.",
    appeal: "Numbers borrow mathematics' authority the way lab coats borrow medicine's.",
    instead: "Numbers with error bars — ours come with a methods page." },
  { id: "human-design", name: "Human Design", verdict: "NO EVIDENCE",
    claim: "A synthesis of astrology, I-Ching, chakras, and physics assigns your decision 'strategy.'",
    why: "It has produced no peer-reviewed validation of any claim; its 'quantum' framing is decorative. It is a personality liturgy, not a measurement.",
    source: "Absence-of-evidence documented by its own citation record (none in indexed journals).",
    appeal: "Maximal systems glamour — five borrowed cosmologies feel more complete than one tested scale.",
    instead: "One tested scale." },
  { id: "psychic-mediums", name: "Grief Mediumship / Psychic Counseling", verdict: "NO EVIDENCE",
    claim: "Mediums relay messages from the dead to heal grief.",
    why: "Controlled readings with proper blinding collapse to cold-reading baselines; the hits are statistical fishing narrated warmly. Grief relief from ritual is real; the phone line is not.",
    source: "Controlled mediumship tests reviewed by O'Keeffe & Wiseman (2005), British Journal of Psychology.",
    appeal: "The cruelest market: love with nowhere to go will pay anything for one more sentence.",
    instead: "Meaning-Oriented Grief Therapy — in our library, and it honors the dead honestly." },
  { id: "angel-therapy", name: "Angel Therapy / Card Readings", verdict: "NO EVIDENCE",
    claim: "Angelic guidance channeled through practitioners or decks directs healing.",
    why: "No testable content; outcomes are Barnum-plus-comfort. Notably, its most famous proponent later renounced the practice herself.",
    source: "The practice's own literature contains no controlled studies to cite — which is the finding.",
    appeal: "Guardianship on demand: a universe with staff assigned personally to you.",
    instead: "A village with actual staff: Community-Founding." },
  { id: "faith-healing-substitution", name: "Faith Healing (as medical substitute)", verdict: "HARMFUL",
    claim: "Prayer and anointing cure disease, making medicine unnecessary.",
    why: "Pediatric mortality studies of sects refusing care document children dying of treatable conditions; where faith healing REPLACES treatment, the outcome data are graves.",
    source: "Asser & Swan (1998), Pediatrics — child fatalities from religiously motivated medical neglect.",
    appeal: "Total trust is the deepest comfort there is — which is exactly what makes its abuse lethal.",
    instead: "Faith AND medicine — the both/and every serious tradition permits." },
  { id: "intercessory-prayer-rct", name: "Intercessory Prayer (as clinical intervention)", verdict: "DEBUNKED",
    claim: "Strangers praying for patients improves surgical outcomes.",
    why: "The largest trial (1,802 cardiac patients) found no benefit — and slightly WORSE complications among patients told they were being prayed for, possibly via performance anxiety.",
    source: "Benson et al. (2006), American Heart Journal — the STEP trial.",
    appeal: "It tried to make grace legible to hospitals; some things don't fit on a chart, and the chart said so.",
    instead: "Prayer as meaning and community — measured effects live there, not in surgical stats." },

  // ── Autism & desperation markets ────────────────────────────
  { id: "vaccines-autism", name: "Vaccine-Causes-Autism (and its therapy industry)", verdict: "DEBUNKED",
    claim: "MMR vaccination causes autism; 'recovery' therapies undo it.",
    why: "The founding study was retracted as fraudulent and its author struck off; massive cohort studies across millions of children find no association. An entire pseudo-therapy industry grew on the fraud.",
    source: "The Lancet's 2010 retraction of Wakefield (1998); Hviid et al. (2019), Annals of Internal Medicine cohort of 657,461 children.",
    appeal: "A cause with a villain and a timeline beats an unexplained difference — grief for an expected child seeks a defendant.",
    instead: "Evidence-based supports that begin from acceptance, not blame." },
  { id: "chelation-autism", name: "Chelation for Autism", verdict: "HARMFUL",
    claim: "Stripping heavy metals from the body reverses autism.",
    why: "Built on the debunked mercury theory; no controlled benefit — and the treatment has killed (a 5-year-old died of hypocalcemia during chelation in 2005). NIH cancelled its trial as unjustifiable risk.",
    source: "Documented death (CDC MMWR, 2006); NIH trial cancellation (2008).",
    appeal: "Poison-and-purge is an ancient, intuitive medical story — wrong here, and lethal.",
    instead: "Nothing that removes; supports that build." },
  { id: "mms-bleach", name: "MMS / Chlorine Dioxide ('Miracle Mineral')", verdict: "HARMFUL",
    claim: "An industrial bleach solution cures autism, malaria, COVID — everything.",
    why: "It is bleach. The FDA has warned for years; sellers have been prosecuted; harm reports include chemical burns in children whose parents were sold hope by the bottle.",
    source: "U.S. FDA warnings (2010–2020); DOJ prosecutions of Genesis II sellers.",
    appeal: "The forbidden-cure conspiracy: suppression narratives convert toxicity into proof of potency.",
    instead: "Report sellers. That is the therapeutic intervention here." },
  { id: "secretin", name: "Secretin for Autism", verdict: "DEBUNKED",
    claim: "A gut hormone infusion dramatically improves autistic children.",
    why: "After a single televised anecdote created a market, more than a dozen randomized trials found secretin indistinguishable from placebo — one of the clearest anecdote-vs-trial stories in medicine.",
    source: "Sandler et al. (1999), NEJM, and the subsequent Cochrane review (Williams et al.).",
    appeal: "A single miracle child on television outweighs a thousand data points in the parental heart.",
    instead: "The lesson itself: one story is a hypothesis, never a result." },
  { id: "dolphin-therapy", name: "Dolphin-Assisted Therapy", verdict: "OVERCLAIMED",
    claim: "Swimming with dolphins produces breakthrough gains for disabled children.",
    why: "Methodological reviews found the studies confounded beyond interpretation (novelty, vacation, attention); risks to children and dolphins are real, and the fees are extraordinary.",
    source: "Marino & Lilienfeld (2007), Anthrozoös methodological review.",
    appeal: "Charismatic megafauna plus a desperate family plus a beautiful setting — hope's perfect photograph.",
    instead: "Pet-Assisted Therapy — the modest, cited, land-based version in our library." },

  // ── The verdict on culture itself (labeled analysis) ────────
  { id: "wellness-mlm", name: "Wellness MLMs (as healing communities)", verdict: "OVERCLAIMED",
    claim: "Joining the product family heals you while the downline funds your freedom.",
    why: "FTC income disclosures show the overwhelming majority of participants profit little or lose money; the 'healing' is community belonging — real — welded to products that mostly aren't.",
    source: "FTC business-guidance data on MLM participant earnings.",
    appeal: "It bundles America's two hungers — health and entrepreneurship — into one starter kit.",
    instead: "Community-Founding without a buy-in: the village is the product." },
  { id: "prosperity-gospel-therapy", name: "Prosperity Teaching (as therapy)", verdict: "NO EVIDENCE",
    claim: "Faith-seeded donations return healing and wealth multiplied.",
    why: "As a testable claim about donation-to-outcome mechanics it has none; as pastoral care it inverts care's direction — extracting most from those hurting most.",
    source: "Analysis, offered as analysis: the claim structure is unfalsifiable by design.",
    appeal: "It fuses the deepest American creed — abundance rewards belief — with the deepest human hope, and passes the plate.",
    instead: "Free for the first 10,000 was our answer to this one." },
];

export function mythById(id: string): Myth | undefined {
  return MYTHS.find((m) => m.id === id);
}
