// Goal shelf: ATHLETE — become a better athlete (sections 9400–9499).
// Verification: every DOI below was resolved against the PubMed record or the
// Crossref record on 2026-09-11. See types.ts for the contract. Popular advice the
// evidence does not support is rated at the floor (magnitude 1) with a callout.
// Nothing here is medical or nutritional advice; each note describes what the
// cited study tested. Creatine is covered briefly because library section 44
// already treats it in depth.
import { doi, type GoalShelfCluster } from "./types";

export const SECTIONS: Record<string, string> = {
  "9400": "How to Read This Shelf",
  "9401": "Intensity Distribution — Polarized and 80/20 Endurance Training",
  "9402": "Resistance Training — Volume and Frequency Dose–Response",
  "9403": "Plyometrics — Jump Height, Strength and Power",
  "9404": "Strength Training for Endurance Athletes, Running Economy and Cadence",
  "9405": "Sleep Extension — The Cheapest Ergogenic Aid",
  "9406": "Protein — How Much Actually Helps",
  "9407": "Creatine — Brief (See Library Section 44)",
  "9408": "Caffeine — Dose, Timing and Who Responds",
  "9409": "Carbohydrate Periodization — Fuel for the Work Required",
  "9410": "Heat Acclimation — Two Weeks That Raise Performance Even in the Cool",
  "9411": "Altitude — Live High, Train Low",
  "9412": "Mental Skills — Imagery and Self-Talk",
  "9413": "Deliberate Practice in Sport — What It Explains and What It Does Not",
  "9414": "Injury Prevention — FIFA 11+, Nordic Hamstring and Strength Training",
  "9415": "Myth — Ice Baths After Every Strength Session",
  "9416": "Massage and Compression — Small, Situational Gains",
  "9417": "HRV-Guided Training — Letting Recovery Set the Day's Intensity",
  "9418": "Overtraining and Load Management — Overload Without Maladaptation",
  "9419": "Masters Athletes — Limiting the Decline",
  "9420": "Myth — Static Stretching Right Before You Perform",
  "9421": "Myth — 'Toning' and Spot Reduction",
  "9422": "Myth — Sports Drinks for Short Sessions",
  "9423": "The Integrated Plan — Individualized Periodization with a Coach",
};

export const CLUSTERS: GoalShelfCluster[] = [
  {
    id: "gs-athlete-read-me-first",
    goal: "athlete", tier: "fundamental", section: "9400",
    title: "How to Read the Athlete Shelf",
    subtitle: "Protocols, not diagnoses — pick one per tier each month",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "low" },
    description:
      "Every protocol on this shelf is tagged fundamental, moderate, advanced or elite and carries a concrete action step. The monthly menu hands you one or two from each tier. Two things sit under everything else: the distribution of training intensity that elite endurance athletes converge on, and the fact that strength training is the best-supported way to avoid the injuries that interrupt training. Start with the fundamentals you are not doing before adding supplements or gadgets.",
    action: "This month, pick the one fundamental protocol on this shelf you are not already doing and run it for 30 days before adding anything else.",
    sources: [
      { cite: "Seiler, S. (2010). What is best practice for training intensity and duration distribution in endurance athletes? International Journal of Sports Physiology and Performance, 5(3), 276–291.", note: "Descriptive studies of nationally and internationally competitive endurance athletes converge on roughly 80% of sessions at low intensity and about 20% dominated by high-intensity work.", link: doi("10.1123/ijspp.5.3.276"), kind: "doi" },
      { cite: "Lauersen, J. B., Bertelsen, D. M., & Andersen, L. B. (2014). The effectiveness of exercise interventions to prevent sports injuries: A systematic review and meta-analysis of randomised controlled trials. British Journal of Sports Medicine, 48(11), 871–877.", note: "25 trials, 26,610 participants: strength training reduced sports injuries to less than a third (RR 0.315) and overuse injuries by almost half; stretching showed no benefit (RR 0.963).", link: doi("10.1136/bjsports-2013-092538"), kind: "doi" },
    ],
  },
  {
    id: "gs-athlete-polarized",
    goal: "athlete", tier: "fundamental", section: "9401",
    title: "Go Easy Most of the Time, Hard Some of the Time",
    subtitle: "About 80% of sessions low intensity, the rest genuinely hard — not everything in the middle",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "weeks", durability: "sustained", effort: "moderate" },
    feeds: ["VO2peak", "time to exhaustion", "sustainable training load"],
    description:
      "Quantifying the training of elite cross-country skiers, rowers, runners and cyclists shows a consistent pattern: most sessions are performed at low intensity and a minority at high intensity, with little time at threshold. In a 9-week randomised comparison of four models in 48 well-trained athletes, polarized training produced the largest gains in VO2peak (+11.7%), time to exhaustion (+17.4%) and peak velocity or power, while threshold and high-volume training produced little further improvement. A systematic review of randomised trials found a moderate effect favouring polarized over threshold distribution on time-trial performance. The boundary: the trials are small, and 'easy' means genuinely easy — below the first ventilatory or lactate threshold.",
    action: "Classify every session for the next four weeks as easy or hard using heart rate or talk test; make at least four of every five sessions easy enough to hold a conversation, and make the one or two hard sessions intervals at or above 90% of maximum heart rate.",
    sources: [
      { cite: "Seiler, S. (2010). What is best practice for training intensity and duration distribution in endurance athletes? International Journal of Sports Physiology and Performance, 5(3), 276–291.", note: "Review concluding that elite endurance athletes self-organise toward a high-volume, mostly low-intensity approach with carefully placed high-intensity work, and that intensification studies in already well-trained athletes show no long-term advantage.", link: doi("10.1123/ijspp.5.3.276"), kind: "doi" },
      { cite: "Seiler, K. S., & Kjerland, G. Ø. (2006). Quantifying training intensity distribution in elite endurance athletes: Is there evidence for an 'optimal' distribution? Scandinavian Journal of Medicine & Science in Sports, 16(1), 49–56.", note: "In 11 elite junior cross-country skiers, 384 training sessions were quantified by three methods, revealing a polarized distribution with most training below the first ventilatory threshold.", link: doi("10.1111/j.1600-0838.2004.00418.x"), kind: "doi" },
      { cite: "Stöggl, T., & Sperlich, B. (2014). Polarized training has greater impact on key endurance variables than threshold, high intensity, or high volume training. Frontiers in Physiology, 5, 33.", note: "48 runners, cyclists, triathletes and skiers randomised to four 9-week models: polarized training gave the greatest increase in VO2peak (+11.7%), time to exhaustion (+17.4%) and peak velocity/power (+5.1%).", link: doi("10.3389/fphys.2014.00033"), kind: "doi" },
      { cite: "Stöggl, T. L., & Sperlich, B. (2015). The training intensity distribution among well-trained and elite endurance athletes. Frontiers in Physiology, 6, 295.", note: "Review of retrospective and prospective studies: most elite programs are pyramidal or polarized, and prospective trials favour polarized over threshold-heavy distributions.", link: doi("10.3389/fphys.2015.00295"), kind: "doi" },
      { cite: "Rosenblat, M. A., Perrotta, A. S., & Vicenzino, B. (2019). Polarized vs. threshold training intensity distribution on endurance sport performance: A systematic review and meta-analysis of randomized controlled trials. Journal of Strength and Conditioning Research, 33(12), 3491–3500.", note: "Pooled time-trial results from randomised trials showed a moderate effect (ES = −0.66) favouring polarized over threshold training in endurance-trained athletes, from a small number of studies.", link: doi("10.1519/JSC.0000000000002618"), kind: "doi" },
    ],
  },
  {
    id: "gs-athlete-rt-volume-frequency",
    goal: "athlete", tier: "fundamental", section: "9402",
    title: "Train Each Muscle Twice a Week and Count Weekly Sets",
    subtitle: "More weekly sets grow more muscle; frequency matters mainly as a way to get the volume in",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "weeks", durability: "sustained", effort: "moderate" },
    feeds: ["muscle mass", "strength", "injury resilience"],
    description:
      "Meta-regression across 15 studies found a graded dose–response between weekly sets per muscle and hypertrophy: each added set was worth about a 0.37% greater gain, and higher- versus lower-volume conditions differed by 3.9%. On frequency, training a muscle twice a week beat once a week when volume was matched, but a later meta-analysis of 25 studies found no meaningful frequency effect once weekly volume is equated. For strength, higher frequencies produced larger gains largely because they carried more volume. The boundary: most trials use untrained participants and modest durations.",
    action: "For each major muscle group, schedule two sessions a week and log weekly hard sets; progress from about 10 toward 15–20 weekly sets per muscle over two months as recovery allows.",
    sources: [
      { cite: "Schoenfeld, B. J., Ogborn, D., & Krieger, J. W. (2017). Dose-response relationship between weekly resistance training volume and increases in muscle mass: A systematic review and meta-analysis. Journal of Sports Sciences, 35(11), 1073–1082.", note: "34 treatment groups from 15 studies: each additional weekly set was associated with a 0.37% larger gain in muscle size, and higher versus lower volumes differed by 3.9%.", link: doi("10.1080/02640414.2016.1210197"), kind: "doi" },
      { cite: "Schoenfeld, B. J., Ogborn, D., & Krieger, J. W. (2016). Effects of resistance training frequency on measures of muscle hypertrophy: A systematic review and meta-analysis. Sports Medicine, 46(11), 1689–1697.", note: "Ten studies: on a volume-equated basis, training a muscle group twice a week produced superior hypertrophy to once a week; whether three times beats two remained undetermined.", link: doi("10.1007/s40279-016-0543-8"), kind: "doi" },
      { cite: "Schoenfeld, B. J., Grgic, J., & Krieger, J. (2019). How many times per week should a muscle be trained to maximize muscle hypertrophy? A systematic review and meta-analysis of studies examining the effects of resistance training frequency. Journal of Sports Sciences, 37(11), 1286–1295.", note: "25 studies: no significant difference between higher and lower frequency when volume was equated — for a given volume, weekly frequency can follow preference.", link: doi("10.1080/02640414.2018.1555906"), kind: "doi" },
      { cite: "Grgic, J., Schoenfeld, B. J., Davies, T. B., Lazinica, B., Krieger, J. W., & Pedisic, Z. (2018). Effect of resistance training frequency on gains in muscular strength: A systematic review and meta-analysis. Sports Medicine, 48(5), 1207–1220.", note: "22 studies: strength effect sizes rose from 0.74 to 1.08 across 1 to 4+ sessions per week, but the frequency effect disappeared in volume-equated studies — volume was the driver.", link: doi("10.1007/s40279-018-0872-x"), kind: "doi" },
    ],
  },
  {
    id: "gs-athlete-plyometrics",
    goal: "athlete", tier: "moderate", section: "9403",
    title: "Add a Plyometric Block for Jump, Sprint and Strength",
    subtitle: "Six to ten weeks, more than 15 sessions, high-intensity jumps combined with lifting",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "moderate" },
    feeds: ["vertical jump", "power", "running economy"],
    description:
      "Meta-analyses of plyometric training show reliable gains in vertical jump height across jump types (about 4.7% pooled in one synthesis) and in maximal strength, with the largest effects when programs run under ten weeks with more than 15 sessions, use high-intensity work of more than 40 jumps per session, and combine plyometrics with weight training. Benefits are independent of baseline fitness and similar for women and men. In a season-long trial with collegiate cross-country runners, combining plyometrics with heavy resistance training changed biomechanics, although heavy resistance alone gave slightly better economy. The boundary: landing volume needs progression to keep tendons and joints safe.",
    action: "Run an 8-week block of two plyometric sessions a week — 40–60 total ground contacts per session of hurdle hops, drop jumps and bounds — placed after your warm-up and before lifting, and retest a countermovement jump at the end.",
    sources: [
      { cite: "Markovic, G. (2007). Does plyometric training improve vertical jump height? A meta-analytical review. British Journal of Sports Medicine, 41(6), 349–355.", note: "26 studies: pooled effect of plyometric training on vertical jump height was 4.7%, with improvements across squat, countermovement and drop jumps.", link: doi("10.1136/bjsm.2007.035113"), kind: "doi" },
      { cite: "Sáez de Villarreal, E., Kellis, E., Kraemer, W. J., & Izquierdo, M. (2009). Determining variables of plyometric training for improving vertical jump height performance: A meta-analysis. Journal of Strength and Conditioning Research, 23(2), 495–506.", note: "56 studies, 225 effect sizes: more experienced athletes gained more, benefit was independent of fitness level, and program variables such as intensity and session count moderated the effect.", link: doi("10.1519/JSC.0b013e318196b7c6"), kind: "doi" },
      { cite: "Sáez-Sáez de Villarreal, E., Requena, B., & Newton, R. U. (2010). Does plyometric training improve strength performance? A meta-analysis. Journal of Science and Medicine in Sport, 13(5), 513–522.", note: "15 studies, 31 effect sizes: plyometrics improved maximal strength; programs under 10 weeks with more than 15 sessions, high intensity with more than 40 jumps per session, and combined with weight training maximised gains.", link: doi("10.1016/j.jsams.2009.08.005"), kind: "doi" },
      { cite: "Barnes, K. R., Hopkins, W. G., McGuigan, M. R., Northuis, M. E., & Kilding, A. E. (2013). Effects of resistance training on running economy and cross-country performance. Medicine & Science in Sports & Exercise, 45(12), 2322–2331.", note: "50 collegiate cross-country runners randomised to heavy resistance or plyometric-plus-heavy training over a season: heavy resistance produced small-moderate gains in economy and peak speed relative to plyometric-plus-heavy, and women benefited more than men.", link: doi("10.1249/MSS.0b013e31829af603"), kind: "doi" },
    ],
  },
  {
    id: "gs-athlete-strength-endurance-economy",
    goal: "athlete", tier: "moderate", section: "9404",
    title: "Lift Heavy Twice a Week to Run and Ride More Economically",
    subtitle: "Heavy or explosive strength work improves economy; a 5–10% higher cadence lowers knee load",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "moderate" },
    feeds: ["running economy", "time to exhaustion", "joint loading"],
    description:
      "Reviews and meta-analyses of concurrent training in endurance-trained runners and cyclists find that adding heavy or explosive strength training improves economy and time-to-exhaustion at maximal aerobic speed or power without adding body mass, with heavy loads best for cycling economy. Running economy is a composite of metabolic, biomechanical and neuromuscular factors; the modifiable biomechanics associated with better economy include a stride length close to preferred, lower vertical oscillation and greater leg stiffness, and short-term resistance and plyometric training improves it. Raising step rate by 5–10% reduced energy absorbed at the knee and hip in 45 recreational runners, a plausible injury lever. The boundary: strength gains in economy are modest and take 6–14 weeks.",
    action: "Add two 30-minute heavy strength sessions a week (squats, deadlifts or step-ups at 3–6 reps, plus single-leg work) for ten weeks, and if you have knee pain when running, raise your cadence 5% using a metronome.",
    sources: [
      { cite: "Rønnestad, B. R., & Mujika, I. (2014). Optimizing strength training for running and cycling endurance performance: A review. Scandinavian Journal of Medicine & Science in Sports, 24(4), 603–612.", note: "Review: combining endurance training with heavy or explosive strength training improves running economy, while heavy strength training is recommended for cycling economy, with gains in speed or power at VO2max and time to exhaustion.", link: doi("10.1111/sms.12104"), kind: "doi" },
      { cite: "Beattie, K., Kenny, I. C., Lyons, M., & Carson, B. P. (2014). The effect of strength training on performance in endurance athletes. Sports Medicine, 44(6), 845–865.", note: "Systematic review of strength-training interventions in endurance athletes reporting improvements in economy, muscle power and performance without detriment to aerobic capacity.", link: doi("10.1007/s40279-014-0157-y"), kind: "doi" },
      { cite: "Balsalobre-Fernández, C., Santos-Concejero, J., & Grivas, G. V. (2016). Effects of strength training on running economy in highly trained runners: A systematic review with meta-analysis of controlled trials. Journal of Strength and Conditioning Research, 30(8), 2361–2368.", note: "Meta-analysis of controlled trials in competitive runners with VO2max above 60 ml/kg/min: strength programs improved running economy.", link: doi("10.1519/JSC.0000000000001316"), kind: "doi" },
      { cite: "Blagrove, R. C., Howatson, G., & Hayes, P. R. (2018). Effects of strength training on the physiological determinants of middle- and long-distance running performance: A systematic review. Sports Medicine, 48(5), 1117–1149.", note: "Systematic review of strength-training modalities in middle- and long-distance runners with best-practice recommendations for economy and performance determinants.", link: doi("10.1007/s40279-017-0835-7"), kind: "doi" },
      { cite: "Barnes, K. R., & Kilding, A. E. (2015). Strategies to improve running economy. Sports Medicine, 45(1), 37–56.", note: "Review of acute and chronic interventions on running economy: endurance training history and volume, uphill and interval training, short-term resistance and plyometric training, and altitude acclimatisation all improve it.", link: doi("10.1007/s40279-014-0246-y"), kind: "doi" },
      { cite: "Moore, I. S. (2016). Is there an economical running technique? A review of modifiable biomechanical factors affecting running economy. Sports Medicine, 46(6), 793–807.", note: "Modifiable factors associated with better economy include a stride length near preferred (up to 3% shorter), lower vertical oscillation and greater leg stiffness; recommending one universal technique is cautioned against.", link: doi("10.1007/s40279-016-0474-4"), kind: "doi" },
      { cite: "Heiderscheit, B. C., Chumanov, E. S., Michalski, M. P., Wille, C. M., & Ryan, M. B. (2011). Effects of step rate manipulation on joint mechanics during running. Medicine & Science in Sports & Exercise, 43(2), 296–302.", note: "In 45 recreational runners, increasing step rate 5–10% above preferred reduced energy absorbed at the knee and, at +10%, the hip, with shorter stride and less vertical excursion.", link: doi("10.1249/MSS.0b013e3181ebedf4"), kind: "doi" },
    ],
  },
  {
    id: "gs-athlete-sleep-extension",
    goal: "athlete", tier: "fundamental", section: "9405",
    title: "Extend Sleep Toward 9–10 Hours in Bed",
    subtitle: "Sprint times, shooting and serving accuracy improved when athletes banked more sleep",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "moderate" },
    feeds: ["reaction time", "skill accuracy", "mood"],
    description:
      "In the Stanford basketball study, eleven varsity players who aimed for at least ten hours in bed for 5–7 weeks improved timed sprint, free-throw and three-point accuracy, reaction time, mood and daytime sleepiness. College tennis players who extended sleep to at least nine hours for a week improved serving accuracy. A systematic review of sleep interventions in athletes found sleep extension, napping and sleep-hygiene education the most studied approaches with promising but small-sample evidence, and the 2021 expert consensus notes elite athletes commonly sleep under seven hours. The boundary: these are small, uncontrolled samples; the consistent direction is what justifies the low-cost trial.",
    action: "For the next three weeks, set a bedtime that allows at least nine hours in bed on training days, add a 20–30 minute early-afternoon nap when nights fall short, and record one sport-specific accuracy or sprint measure weekly.",
    sources: [
      { cite: "Mah, C. D., Mah, K. E., Kezirian, E. J., & Dement, W. C. (2011). The effects of sleep extension on the athletic performance of collegiate basketball players. Sleep, 34(7), 943–950.", note: "Eleven Stanford men's basketball players extended sleep for 5–7 weeks with a goal of 10 h in bed: faster timed sprints, improved shooting accuracy, better reaction time and mood, and less daytime sleepiness.", link: doi("10.5665/SLEEP.1132"), kind: "doi" },
      { cite: "Schwartz, J., & Simon, R. D. (2015). Sleep extension improves serving accuracy: A study with college varsity tennis players. Physiology & Behavior, 151, 541–544.", note: "Twelve college varsity tennis players who slept at least nine hours for one week improved serving accuracy compared with their sleep-deprived baseline.", link: doi("10.1016/j.physbeh.2015.08.035"), kind: "doi" },
      { cite: "Bonnar, D., Bartel, K., Kakoschke, N., & Lang, C. (2018). Sleep interventions designed to improve athletic performance and recovery: A systematic review of current approaches. Sports Medicine, 48(3), 683–703.", note: "Systematic review of sleep interventions in athletes: sleep extension, napping and sleep-hygiene approaches showed benefits for performance and recovery, with small samples and few controlled designs.", link: doi("10.1007/s40279-017-0832-x"), kind: "doi" },
      { cite: "Walsh, N. P., Halson, S. L., Sargent, C., Roach, G. D., Nédélec, M., Gupta, L., et al. (2021). Sleep and the athlete: Narrative review and 2021 expert consensus recommendations. British Journal of Sports Medicine.", note: "Consensus that elite athletes are prone to habitual short sleep (<7 h) and fragmentation, that a night without sleep impairs performance, and that targeted interventions are warranted.", link: doi("10.1136/bjsports-2020-102025"), kind: "doi" },
    ],
  },
  {
    id: "gs-athlete-protein",
    goal: "athlete", tier: "fundamental", section: "9406",
    title: "Eat About 1.6 g of Protein per Kilogram, Spread Through the Day",
    subtitle: "Supplementation adds modest muscle and strength; beyond ~1.6 g/kg/day the curve flattens",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "low" },
    feeds: ["fat-free mass", "strength gains", "recovery"],
    description:
      "A meta-analysis of 49 randomised trials with 1,863 participants found protein supplementation during resistance training of at least six weeks increased one-repetition-maximum strength by about 2.5 kg and fat-free mass by 0.30 kg, with larger effects in trained individuals and smaller ones with age; intakes beyond roughly 1.62 g/kg/day produced no further gain in fat-free mass. Position stands place a daily range of 1.4–2.0 g/kg as sufficient for most exercising people, with higher intakes only in specific cases such as energy restriction. The boundary: the gains are real but modest, and the source can be food rather than supplements.",
    action: "Weigh yourself, multiply by 1.6, and hit that many grams of protein daily from food in three or four servings of 25–40 g, one within a few hours of training.",
    sources: [
      { cite: "Morton, R. W., Murphy, K. T., McKellar, S. R., Schoenfeld, B. J., Henselmans, M., Helms, E., et al. (2018). A systematic review, meta-analysis and meta-regression of the effect of protein supplementation on resistance training-induced gains in muscle mass and strength in healthy adults. British Journal of Sports Medicine, 52(6), 376–384.", note: "49 studies, 1,863 participants: protein supplementation increased 1RM strength (+2.49 kg), fat-free mass (+0.30 kg) and fibre cross-sectional area; no further fat-free-mass gain beyond total intakes of about 1.62 g/kg/day.", link: doi("10.1136/bjsports-2017-097608"), kind: "doi" },
      { cite: "Jäger, R., Kerksick, C. M., Campbell, B. I., Cribb, P. J., Wells, S. D., Skwiat, T. M., et al. (2017). International Society of Sports Nutrition position stand: Protein and exercise. Journal of the International Society of Sports Nutrition, 14, 20.", note: "Position stand: 1.4–2.0 g/kg/day is sufficient for most exercising individuals to build and maintain muscle, with higher intakes potentially needed to preserve lean mass during energy restriction.", link: doi("10.1186/s12970-017-0177-8"), kind: "doi" },
      { cite: "Phillips, S. M., & Van Loon, L. J. C. (2011). Dietary protein for athletes: From requirements to optimum adaptation. Journal of Sports Sciences, 29(Suppl 1), S29–S38.", note: "Consensus review arguing athletes benefit from protein intakes above the RDA to support adaptation, with leucine-rich sources and distribution across the day.", link: doi("10.1080/02640414.2011.619204"), kind: "doi" },
    ],
  },
  {
    id: "gs-athlete-creatine",
    goal: "athlete", tier: "moderate", section: "9407",
    title: "Creatine Monohydrate — Brief",
    subtitle: "The best-supported strength supplement; see library section 44 for the full treatment",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "low" },
    feeds: ["high-intensity work capacity", "strength", "lean mass"],
    description:
      "Creatine supplementation consistently raises intramuscular creatine and improves high-intensity exercise performance and training adaptations; meta-analyses show small but reliable gains in upper- and lower-limb strength and in lean tissue mass when combined with resistance training, including in older adults. The position stand judges it safe at recommended doses in healthy people. This shelf keeps it brief because section 44 of the library covers dosing, safety and the evidence in depth; the boundary is that benefits are for short, high-intensity efforts rather than endurance.",
    action: "If your sport involves repeated sprints or heavy lifting, read library section 44 and, if it fits, take 3–5 g of creatine monohydrate daily with food for eight weeks alongside your strength program.",
    sources: [
      { cite: "Kreider, R. B., Kalman, D. S., Antonio, J., Ziegenfuss, T. N., Wildman, R., Collins, R., et al. (2017). International Society of Sports Nutrition position stand: Safety and efficacy of creatine supplementation in exercise, sport, and medicine. Journal of the International Society of Sports Nutrition, 14, 18.", note: "Position stand summarising that creatine increases intramuscular creatine, improves high-intensity exercise performance and training adaptations, and is safe at recommended doses.", link: doi("10.1186/s12970-017-0173-z"), kind: "doi" },
      { cite: "Branch, J. D. (2003). Effect of creatine supplementation on body composition and performance: A meta-analysis. International Journal of Sport Nutrition and Exercise Metabolism, 13(2), 198–226.", note: "Early meta-analysis establishing small positive effects of creatine on lean body mass and on short-duration high-intensity performance.", link: doi("10.1123/ijsnem.13.2.198"), kind: "doi" },
      { cite: "Lanhers, C., Pereira, B., Naughton, G., Trousselard, M., Lesage, F.-X., & Dutheil, F. (2017). Creatine supplementation and upper limb strength performance: A systematic review and meta-analysis. Sports Medicine, 47(1), 163–173.", note: "Meta-analysis showing creatine supplementation improves upper-limb strength performance in exercises of under three minutes.", link: doi("10.1007/s40279-016-0571-4"), kind: "doi" },
      { cite: "Lanhers, C., Pereira, B., Naughton, G., Trousselard, M., Lesage, F.-X., & Dutheil, F. (2015). Creatine supplementation and lower limb strength performance: A systematic review and meta-analyses. Sports Medicine, 45(9), 1285–1294.", note: "Meta-analyses finding creatine improves lower-limb strength performance, particularly in short-duration exercise.", link: doi("10.1007/s40279-015-0337-4"), kind: "doi" },
      { cite: "Chilibeck, P. D., Kaviani, M., Candow, D. G., & Zello, G. A. (2017). Effect of creatine supplementation during resistance training on lean tissue mass and muscular strength in older adults: A meta-analysis. Open Access Journal of Sports Medicine, 8, 213–226.", note: "Meta-analysis in older adults: creatine combined with resistance training increased lean tissue mass and strength more than resistance training alone.", link: doi("10.2147/oajsm.s123529"), kind: "doi" },
    ],
  },
  {
    id: "gs-athlete-caffeine",
    goal: "athlete", tier: "moderate", section: "9408",
    title: "Caffeine — 3–6 mg/kg About an Hour Before Hard Efforts",
    subtitle: "Ergogenic across endurance, strength, power and speed; effects vary by person",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "days", durability: "transient", effort: "low" },
    feeds: ["endurance time-trial performance", "muscular strength and endurance", "perceived exertion"],
    description:
      "An umbrella review of 21 meta-analyses found caffeine ergogenic for aerobic endurance, muscle strength, muscle endurance, power, jumping and exercise speed, with evidence quality generally moderate; a meta-analysis of endurance time trials confirmed a moderate benefit, and one on strength and power found small but significant gains. The position stand identifies 3–6 mg/kg body mass as the effective dose, with aerobic endurance the most consistent responder, and notes individual variation by habitual use and genotype. The boundary: caffeine can disrupt sleep, which this shelf treats as a bigger lever, and responses differ.",
    action: "Before your two hardest sessions or a race each week, take 3 mg per kilogram of body mass of caffeine 45–60 minutes beforehand, avoid it after early afternoon, and keep a note of how you respond.",
    sources: [
      { cite: "Grgic, J., Grgic, I., Pickering, C., Schoenfeld, B. J., Bishop, D. J., & Pedisic, Z. (2020). Wake up and smell the coffee: Caffeine supplementation and exercise performance — an umbrella review of 21 published meta-analyses. British Journal of Sports Medicine, 54(11), 681–688.", note: "Umbrella review of 11 reviews (21 meta-analyses): caffeine was ergogenic for aerobic endurance, strength, muscular endurance, power, jumping and speed, with generally moderate-quality evidence.", link: doi("10.1136/bjsports-2018-100278"), kind: "doi" },
      { cite: "Guest, N. S., VanDusseldorp, T. A., Nelson, M. T., Grgic, J., Schoenfeld, B. J., Jenkins, N. D. M., et al. (2021). International Society of Sports Nutrition position stand: Caffeine and exercise performance. Journal of the International Society of Sports Nutrition, 18, 1.", note: "Position stand: caffeine improves many aspects of performance at 3–6 mg/kg, with aerobic endurance the most consistent moderate-to-large responder and marked individual variation.", link: doi("10.1186/s12970-020-00383-4"), kind: "doi" },
      { cite: "Southward, K., Rutherfurd-Markwick, K. J., & Ali, A. (2018). The effect of acute caffeine ingestion on endurance performance: A systematic review and meta-analysis. Sports Medicine, 48(8), 1913–1928.", note: "Meta-analysis of caffeine and endurance time-trial performance quantifying a moderate ergogenic effect across studies.", link: doi("10.1007/s40279-018-0939-8"), kind: "doi" },
      { cite: "Grgic, J., Trexler, E. T., Lazinica, B., & Pedisic, Z. (2018). Effects of caffeine intake on muscle strength and power: A systematic review and meta-analysis. Journal of the International Society of Sports Nutrition, 15(1).", note: "Meta-analysis finding small but significant ergogenic effects of caffeine on maximal strength and power.", link: doi("10.1186/s12970-018-0216-0"), kind: "doi" },
      { cite: "Pickering, C., & Grgic, J. (2019). Caffeine and exercise: What next? Sports Medicine, 49(7), 1007–1030.", note: "Review of open questions — training status, habitual use, time of day, sex, genotype and effects on sleep and recovery — that modify how an individual should use caffeine.", link: doi("10.1007/s40279-019-01101-0"), kind: "doi" },
    ],
  },
  {
    id: "gs-athlete-carb-periodization",
    goal: "athlete", tier: "elite", section: "9409",
    title: "Periodize Carbohydrate — Train Low Sometimes, Never Race Low",
    subtitle: "Sleep-low blocks with a sports dietitian; chronic low-carb high-fat impairs economy",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "high" },
    feeds: ["endurance performance", "metabolic flexibility", "race-day fuelling"],
    description:
      "The 'fuel for the work required' framework proposes that periodically training with reduced carbohydrate availability — twice-a-day sessions, fasted training, or 'sleep low' — augments signalling and gene expression for endurance adaptation, while high availability is kept for the hardest sessions and competition. In 21 triathletes, three weeks of a sleep-low strategy at matched daily carbohydrate improved endurance performance compared with controls, and a one-week version in trained cyclists showed short-term gains. The counter-evidence is just as important: in elite race walkers, a chronic ketogenic low-carbohydrate high-fat diet raised fat oxidation but impaired economy and negated the performance benefit of intensified training, and a later study showed the impairment appears within days. This is elite because it needs expert supervision, careful sequencing and a competitive base; the boundary is that it is not for beginners or for anyone with disordered-eating history.",
    action: "Working with a qualified sports dietitian, run one 3-week block in a base phase in which two evenings a week you do a hard interval session, eat a low-carbohydrate dinner, and complete an easy morning session before breakfast — then fully carbohydrate-load every key session and race.",
    sources: [
      { cite: "Impey, S. G., Hearris, M. A., Hammond, K. M., Bartlett, J. D., Louis, J., Close, G. L., & Morton, J. P. (2018). Fuel for the work required: A theoretical framework for carbohydrate periodization and the glycogen threshold hypothesis. Sports Medicine, 48(5), 1031–1048.", note: "Framework paper: train-low models (twice-daily training, fasted sessions, post-exercise restriction, sleep low) augmented cell signalling in most studies reviewed, with a proposed glycogen threshold for the effect.", link: doi("10.1007/s40279-018-0867-7"), kind: "doi" },
      { cite: "Marquet, L.-A., Brisswalter, J., Louis, J., Tiollier, E., Burke, L. M., Hawley, J. A., & Hausswirth, C. (2016). Enhanced endurance performance by periodization of carbohydrate intake: 'Sleep low' strategy. Medicine & Science in Sports & Exercise, 48(4), 663–672.", note: "21 triathletes with the same daily carbohydrate intake (6 g/kg) but different timing: a 3-week sleep-low strategy improved endurance performance versus controls.", link: doi("10.1249/MSS.0000000000000823"), kind: "doi" },
      { cite: "Marquet, L.-A., Hausswirth, C., Molle, O., Hawley, J. A., Burke, L. M., Tiollier, E., & Brisswalter, J. (2016). Periodization of carbohydrate intake: Short-term effect on performance. Nutrients, 8(12), 755.", note: "Eleven trained cyclists: a one-week sleep-low exposure produced short-term endurance performance gains.", link: doi("10.3390/nu8120755"), kind: "doi" },
      { cite: "Burke, L. M., Hawley, J. A., Jeukendrup, A., Morton, J. P., Stellingwerff, T., & Maughan, R. J. (2018). Toward a common understanding of diet-exercise strategies to manipulate fuel availability for training and competition preparation in endurance sport. International Journal of Sport Nutrition and Exercise Metabolism, 28(5), 451–463.", note: "Defines the terminology — train low, train high, periodized carbohydrate, low-carbohydrate high-fat — and the conditions under which each strategy is intended to be used.", link: doi("10.1123/ijsnem.2018-0289"), kind: "doi" },
      { cite: "Burke, L. M., Ross, M. L., Garvican-Lewis, L. A., Welvaert, M., Heikura, I. A., Forbes, S. G., et al. (2017). Low carbohydrate, high fat diet impairs exercise economy and negates the performance benefit from intensified training in elite race walkers. The Journal of Physiology, 595(9), 2785–2807.", note: "Elite race walkers on a ketogenic diet for three weeks markedly increased fat oxidation but had reduced economy at race-relevant speeds and did not gain performance from intensified training, unlike high- and periodized-carbohydrate groups.", link: doi("10.1113/JP273230"), kind: "doi" },
      { cite: "Burke, L. M., Whitfield, J., Heikura, I. A., Ross, M. L. R., Tee, N., Forbes, S. F., et al. (2021). Adaptation to a low carbohydrate high fat diet is rapid but impairs endurance exercise metabolism and performance despite enhanced glycogen availability. The Journal of Physiology, 599(3), 771–790.", note: "A 5–6 day ketogenic adaptation raised fat oxidation to levels seen after weeks, with a 5–8% higher oxygen cost at race speeds; acute carbohydrate restoration only partly reversed it.", link: doi("10.1113/JP280221"), kind: "doi" },
    ],
  },
  {
    id: "gs-athlete-heat-acclimation",
    goal: "athlete", tier: "advanced", section: "9410",
    title: "Heat-Acclimate for 10–14 Days Before Hot Competitions",
    subtitle: "Repeated exercise-heat exposure lowers strain and raises performance in the heat and, in one trial, in the cool",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "weeks", durability: "transient", effort: "high" },
    feeds: ["plasma volume", "sweat response", "time-trial performance"],
    description:
      "The consensus recommendation for training and competing in the heat is to acclimatise with repeated exercise-heat exposures over 1–2 weeks, start euhydrated, and use pre-cooling where available. A meta-analysis of 96 articles found heat adaptation had a moderate beneficial effect on exercise capacity and performance in the heat, lowered core temperature and improved cardiovascular stability, with regimens longer than 14 days most effective. In 12 trained cyclists, a 10-day acclimation program raised VO2max by 5% in cool and 8% in hot conditions and time-trial performance by 6% and 8%, with plasma-volume expansion; the boundary is that this cross-over benefit in the cool has not been consistently replicated and adaptations decay within weeks.",
    action: "In the two weeks before a hot-weather race, do five to ten 60–90 minute sessions at moderate intensity in the heat or with added clothing, weigh yourself before and after to replace fluid, and finish the block 3–5 days before competing.",
    sources: [
      { cite: "Racinais, S., Alonso, J.-M., Coutts, A. J., Flouris, A. D., Girard, O., González-Alonso, J., et al. (2015). Consensus recommendations on training and competing in the heat. Sports Medicine, 45(7), 925–938.", note: "Consensus statement: heat acclimatisation through repeated exercise-heat exposures over 1–2 weeks is the most important intervention, alongside starting euhydrated and using cooling strategies.", link: doi("10.1007/s40279-015-0343-6"), kind: "doi" },
      { cite: "Périard, J. D., Racinais, S., & Sawka, M. N. (2015). Adaptations and mechanisms of human heat acclimation: Applications for competitive athletes and sports. Scandinavian Journal of Medicine & Science in Sports, 25(Suppl 1), 20–38.", note: "Review of the physiological adaptations to heat acclimation — improved sweating and skin blood flow, lower body temperatures, reduced cardiovascular strain, expanded plasma volume — and their application to athletes.", link: doi("10.1111/sms.12408"), kind: "doi" },
      { cite: "Tyler, C. J., Reeve, T., Hodges, G. J., & Cheung, S. S. (2016). The effects of heat adaptation on physiology, perception and exercise performance in the heat: A meta-analysis. Sports Medicine, 46(11), 1699–1724.", note: "96 articles: heat adaptation had a moderate beneficial effect on exercise capacity and performance in the heat regardless of regimen, with regimens longer than 14 days most effective and 7–14 days most common.", link: doi("10.1007/s40279-016-0538-5"), kind: "doi" },
      { cite: "Lorenzo, S., Halliwill, J. R., Sawka, M. N., & Minson, C. T. (2010). Heat acclimation improves exercise performance. Journal of Applied Physiology, 109(4), 1140–1147.", note: "12 trained cyclists after 10 days of heat acclimation: VO2max +5% in cool and +8% in hot conditions, time-trial performance +6% and +8%, lactate-threshold power +5%, plasma volume +6.5%; controls did not change.", link: doi("10.1152/japplphysiol.00495.2010"), kind: "doi" },
    ],
  },
  {
    id: "gs-athlete-altitude",
    goal: "athlete", tier: "elite", section: "9411",
    title: "Live High, Train Low for Four Weeks",
    subtitle: "About 2,500 m of living altitude with fast training near 1,250 m — roughly 1–1.5% on race performance",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "months", durability: "transient", effort: "high" },
    feeds: ["red cell mass", "VO2max", "sea-level endurance performance"],
    description:
      "In the original randomised comparison of 39 competitive runners, four weeks of living at 2,500 m while training at 1,250 m improved 5,000 m time by about 13 seconds, in proportion to a 5% rise in VO2max driven by a 9% increase in red cell mass; living and training high, or living low, did not improve times. The same model improved 3,000 m performance by 1.1% in 22 elite runners, and a meta-analysis of 51 studies rated natural live-high-train-low the best-supported protocol, with likely gains of about 4% in maximal power in sub-elite athletes and possible gains in elites. Responses vary widely — responders showed a larger erythropoietin rise — and living too far above the competition altitude slows early performance. This is elite because it costs four weeks away and access to terrain or altitude housing; the benefit lasts a few weeks and is partly a training-camp effect.",
    action: "If you compete at a high level in an endurance sport, plan a 4-week camp living at roughly 2,000–2,500 m with all hard sessions done below about 1,300 m, verify iron status beforehand with a clinician, and time the return 2–3 weeks before your goal race.",
    sources: [
      { cite: "Levine, B. D., & Stray-Gundersen, J. (1997). 'Living high-training low': Effect of moderate-altitude acclimatization with low-altitude training on performance. Journal of Applied Physiology, 83(1), 102–112.", note: "39 competitive runners randomised to high-low, high-high or low-low for four weeks: only high-low improved 5,000 m time (13.4 s), in proportion to a 5% rise in VO2max and a 9% rise in red cell mass.", link: doi("10.1152/jappl.1997.83.1.102"), kind: "doi" },
      { cite: "Stray-Gundersen, J., Chapman, R. F., & Levine, B. D. (2001). 'Living high-training low' altitude training improves sea level performance in male and female elite runners. Journal of Applied Physiology, 91(3), 1113–1120.", note: "22 elite runners after 27 days living at 2,500 m and training at 1,250 m: sea-level 3,000 m time improved 1.1% and VO2max 3%, with a third setting personal bests.", link: doi("10.1152/jappl.2001.91.3.1113"), kind: "doi" },
      { cite: "Chapman, R. F., Stray-Gundersen, J., & Levine, B. D. (1998). Individual variation in response to altitude training. Journal of Applied Physiology, 85(4), 1448–1456.", note: "Among 39 runners, responders showed a larger erythropoietin increase after 30 h at altitude and gains in red cell volume and VO2max, while non-responders slowed their interval training at altitude.", link: doi("10.1152/jappl.1998.85.4.1448"), kind: "doi" },
      { cite: "Bonetti, D. L., & Hopkins, W. G. (2009). Sea-level exercise performance following adaptation to hypoxia: A meta-analysis. Sports Medicine, 39(2), 107–127.", note: "51 studies: natural live-high-train-low gave the best-supported enhancement of endurance power output (about 4% in sub-elites, possible in elites), with placebo, nocebo and training-camp effects among the likely mediators.", link: doi("10.2165/00007256-200939020-00002"), kind: "doi" },
      { cite: "Chapman, R. F., Karlsen, T., Ge, R.-L., Stray-Gundersen, J., & Levine, B. D. (2016). Living altitude influences endurance exercise performance change over time at altitude. Journal of Applied Physiology, 120(10), 1151–1158.", note: "48 collegiate runners assigned to live at 1,780–2,800 m: living well above the competition altitude slowed early performance and needed up to 19 days of acclimatisation.", link: doi("10.1152/japplphysiol.00909.2015"), kind: "doi" },
      { cite: "Stray-Gundersen, J., & Levine, B. D. (2008). Live high, train low at natural altitude. Scandinavian Journal of Medicine & Science in Sports, 18(Suppl 1), 21–28.", note: "Review summarising an average improvement of about 1.5% in sea-level endurance performance (range 0–6%) lasting at least three weeks, via an approximately 8% rise in red cell mass.", link: doi("10.1111/j.1600-0838.2008.00829.x"), kind: "doi" },
    ],
  },
  {
    id: "gs-athlete-mental-skills",
    goal: "athlete", tier: "moderate", section: "9412",
    title: "Practise Imagery and Instructional Self-Talk Like a Physical Skill",
    subtitle: "Moderate effects on performance, larger for fine skills and when the skill itself is trained",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "low" },
    feeds: ["skill execution", "composure", "consistency under pressure"],
    description:
      "A meta-analysis of 32 self-talk studies found a moderate effect on performance (ES = .48), larger for fine-motor and novel tasks, with instructional self-talk best for fine tasks and interventions that included self-talk training more effective; a systematic review of 47 studies confirmed benefits and found negative self-talk did not impede performance. Imagery interventions show positive effects on sport outcomes in meta-analysis, and training imagery ability itself — layered stimulus-response training — improved both imagery ability and golf-putting execution in novices. Across randomised trials, psychological and psychosocial interventions improved sport performance (g = 0.57) with effects lasting at least a month. The boundary: effects are on average moderate and depend on practising the mental skill, not reading about it.",
    action: "Write two cue words for your key skill (one instructional, one motivational), use them on every repetition in practice for four weeks, and spend five minutes after each session imaging the skill from the inside with the sights, sounds and feel layered in.",
    sources: [
      { cite: "Hatzigeorgiadis, A., Zourbanos, N., Galanis, E., & Theodorakis, Y. (2011). Self-talk and sports performance: A meta-analysis. Perspectives on Psychological Science, 6(4), 348–356.", note: "32 studies, 62 effect sizes: moderate positive effect (ES = .48), larger for fine and novel tasks; instructional self-talk was more effective for fine tasks, and interventions with self-talk training outperformed those without.", link: doi("10.1177/1745691611413136"), kind: "doi" },
      { cite: "Tod, D., Hardy, J., & Oliver, E. (2011). Effects of self-talk: A systematic review. Journal of Sport & Exercise Psychology, 33(5), 666–687.", note: "47 studies: positive, instructional and motivational self-talk benefited performance; negative self-talk did not impede it, and thought-stopping was advised against.", link: doi("10.1123/jsep.33.5.666"), kind: "doi" },
      { cite: "Simonsmeier, B. A., Andronie, M., Buecker, S., & Frank, C. (2021). The effects of imagery interventions in sports: A meta-analysis. International Review of Sport and Exercise Psychology, 14(1), 186–207.", note: "Meta-analysis of imagery interventions in sport finding positive effects on motor and psychological outcomes, moderated by intervention characteristics.", link: doi("10.1080/1750984x.2020.1780627"), kind: "doi" },
      { cite: "Brown, D. J., & Fletcher, D. (2017). Effects of psychological and psychosocial interventions on sport performance: A meta-analysis. Sports Medicine, 47(1), 77–99.", note: "Randomised controlled trials (k = 35, n = 997): psychological and psychosocial interventions improved sport performance (g = 0.57) with effects persisting at follow-up (g = 1.16), larger when coach-delivered.", link: doi("10.1007/s40279-016-0552-7"), kind: "doi" },
      { cite: "Williams, S. E., Cooley, S. J., & Cumming, J. (2013). Layered stimulus response training improves motor imagery ability and movement execution. Journal of Sport & Exercise Psychology, 35(1), 60–71.", note: "24 novices low in imagery ability randomised to layered stimulus-response training, imagery practice or visual imagery: layered training improved imagery ability and golf-putting performance.", link: doi("10.1123/jsep.35.1.60"), kind: "doi" },
      { cite: "Tod, D., Edwards, C., McGuigan, M., & Lovell, G. (2015). A systematic review of the effect of cognitive strategies on strength performance. Sports Medicine, 45(11), 1589–1602.", note: "Systematic review of randomised studies finding cognitive strategies such as imagery, self-talk and goal setting influence strength performance.", link: doi("10.1007/s40279-015-0356-1"), kind: "doi" },
    ],
  },
  {
    id: "gs-athlete-deliberate-practice",
    goal: "athlete", tier: "advanced", section: "9413",
    title: "Structure Practice Around the Weak Sub-Skill, With a Coach's Eyes On It",
    subtitle: "Deliberate practice explains a real but partial share of sport performance",
    evidenceTag: "Mixed",
    impact: { magnitude: 3, latency: "months", durability: "lasting", effort: "high" },
    feeds: ["technical skill", "decision-making", "rate of improvement"],
    description:
      "A meta-analysis of sport studies found accumulated deliberate practice explained 18% of the variance in performance overall and only 1% among elite performers, and that high-level athletes did not begin their sport earlier than lower-level ones. Ericsson and Harwell replied that many included estimates did not meet the original definition — individualised, teacher-designed, feedback-rich practice — and that restricting to those raises the explained share substantially. Reviews of athlete development note the field has moved from counting hours toward understanding the conditions that make practice effective. The honest reading for an athlete: hours alone are a weak predictor, but designed practice on identified weaknesses with immediate expert feedback is the part of training most under your control.",
    action: "Ask your coach to name the single technical or tactical weakness that most limits your results, build two sessions a week around it with immediate feedback and video, and keep every other session as normal training.",
    sources: [
      { cite: "Macnamara, B. N., Moreau, D., & Hambrick, D. Z. (2016). The relationship between deliberate practice and performance in sports: A meta-analysis. Perspectives on Psychological Science, 11(3), 333–350.", note: "Deliberate practice accounted for 18% of the variance in sports performance overall and 1% among elite-level performers; high-skill athletes did not start earlier than lower-skill athletes.", link: doi("10.1177/1745691616635591"), kind: "doi" },
      { cite: "Ericsson, K. A., & Harwell, K. W. (2019). Deliberate practice and proposed limits on the effects of practice on the acquisition of expert performance: Why the original definition matters and recommendations for future research. Frontiers in Psychology, 10, 2396.", note: "Re-analysis excluding estimates that did not meet the original criteria for deliberate practice raised the explained variance to 29% (61% after attenuation correction), with a call to measure practice quality.", link: doi("10.3389/fpsyg.2019.02396"), kind: "doi" },
      { cite: "Macnamara, B. N., Hambrick, D. Z., & Oswald, F. L. (2014). Deliberate practice and performance in music, games, sports, education, and professions: A meta-analysis. Psychological Science, 25(8), 1608–1618.", note: "Across domains, deliberate practice explained 18% of variance in sports performance — important but not sufficient to account for expertise.", link: doi("10.1177/0956797614535810"), kind: "doi" },
      { cite: "Baker, J., Young, B. W., & Mann, D. (2017). Advances in athlete development: Understanding conditions of and constraints on optimal practice. Current Opinion in Psychology, 16, 24–27.", note: "Summarises the shift in athlete-development research from the role of deliberate practice toward the conditions under which practice best drives talent development across stages.", link: doi("10.1016/j.copsyc.2017.03.005"), kind: "doi" },
    ],
  },
  {
    id: "gs-athlete-injury-prevention",
    goal: "athlete", tier: "fundamental", section: "9414",
    title: "Run an Injury-Prevention Warm-Up and the Nordic Hamstring Curl",
    subtitle: "FIFA 11+ cuts football injuries by about 39%; Nordic curls halve hamstring injuries — if you actually do them",
    evidenceTag: "Strong",
    impact: { magnitude: 5, latency: "weeks", durability: "sustained", effort: "low" },
    feeds: ["training continuity", "hamstring injury risk", "ACL injury risk"],
    description:
      "A cluster-randomised trial in 1,892 young female footballers found a structured warm-up reduced overall, overuse and severe injuries, and a meta-analysis of FIFA 11+ trials reports a 39% reduction in overall injury rate (the earlier FIFA 11 showed none). In 65 US collegiate men's teams, the program cut injury rates by 46% and time lost by 29%, and a separate analysis found fewer ACL injuries. The Nordic hamstring exercise reduced acute hamstring injuries by about 70% in 942 professional and amateur players (recurrences by 86%), replicated in 579 amateur players, and a meta-analysis of 8,459 athletes found programs including it halve hamstring injury rates. Strength training in general is the best-supported preventive measure, with a dose–response: a 10% rise in strength-training volume lowered injury risk by more than four percentage points. The boundary is adherence — two years after a successful trial, 69% of players never did the exercise.",
    action: "Before every training session, run a 15–20 minute FIFA 11+-style neuromuscular warm-up, and twice a week do 2–3 sets of Nordic hamstring curls, progressing from 5 to 10 reps over ten weeks; put both in your training log so they cannot be skipped.",
    sources: [
      { cite: "Soligard, T., Myklebust, G., Steffen, K., Holme, I., Silvers, H., Bizzini, M., et al. (2008). Comprehensive warm-up programme to prevent injuries in young female footballers: Cluster randomised controlled trial. BMJ, 337, a2469.", note: "1,892 female players aged 13–17 in 125 clubs: the warm-up program lowered overall injury risk (RR 0.68), overuse injuries (0.47) and severe injuries (0.55); the primary lower-extremity outcome did not reach significance (0.71).", link: doi("10.1136/bmj.a2469"), kind: "doi" },
      { cite: "Thorborg, K., Krommes, K. K., Esteve, E., Clausen, M. B., Bartels, E. M., & Rathleff, M. S. (2017). Effect of specific exercise-based football injury prevention programmes on the overall injury rate in football: A systematic review and meta-analysis of the FIFA 11 and 11+ programmes. British Journal of Sports Medicine, 51(7), 562–571.", note: "Six cluster-randomised trials: FIFA 11+ reduced overall injuries by 39% (IRR 0.61), whereas the earlier FIFA 11 showed no effect.", link: doi("10.1136/bjsports-2016-097066"), kind: "doi" },
      { cite: "Silvers-Granelli, H., Mandelbaum, B., Adeniji, O., Insler, S., Bizzini, M., Pohlig, R., et al. (2015). Efficacy of the FIFA 11+ injury prevention program in the collegiate male soccer player. The American Journal of Sports Medicine, 43(11), 2628–2637.", note: "65 NCAA men's teams randomised: FIFA 11+ reduced injury rates by 46.1% (rate ratio 0.54) and time lost to injury by 28.6%.", link: doi("10.1177/0363546515602009"), kind: "doi" },
      { cite: "Petersen, J., Thorborg, K., Nielsen, M. B., Budtz-Jørgensen, E., & Hölmich, P. (2011). Preventive effect of eccentric training on acute hamstring injuries in men's soccer: A cluster-randomized controlled trial. The American Journal of Sports Medicine, 39(11), 2296–2303.", note: "942 Danish players in 50 teams: a 10-week progressive Nordic hamstring program cut acute hamstring injury rates (RR 0.293), with new injuries RR 0.41 and recurrent injuries RR 0.137; NNT 13.", link: doi("10.1177/0363546511419277"), kind: "doi" },
      { cite: "van der Horst, N., Smits, D.-W., Petersen, J., Goedhart, E. A., & Backx, F. J. G. (2015). The preventive effect of the Nordic hamstring exercise on hamstring injuries in amateur soccer players: A randomized controlled trial. The American Journal of Sports Medicine, 43(6), 1316–1323.", note: "579 amateur players in 40 teams: 25 Nordic sessions over 13 weeks reduced hamstring injury incidence (OR 0.282) with 91% compliance, without reducing injury severity.", link: doi("10.1177/0363546515574057"), kind: "doi" },
      { cite: "van Dyk, N., Behan, F. P., & Whiteley, R. (2019). Including the Nordic hamstring exercise in injury prevention programmes halves the rate of hamstring injuries: A systematic review and meta-analysis of 8459 athletes. British Journal of Sports Medicine, 53(21), 1362–1370.", note: "15 studies, 8,459 athletes across sports: programs including the Nordic hamstring exercise reduced hamstring injuries by up to 51% (RR 0.49).", link: doi("10.1136/bjsports-2018-100045"), kind: "doi" },
      { cite: "Lauersen, J. B., Andersen, T. E., & Andersen, L. B. (2018). Strength training as superior, dose-dependent and safe prevention of acute and overuse sports injuries: A systematic review, qualitative analysis and meta-analysis. British Journal of Sports Medicine, 52(24), 1557–1563.", note: "Six RCTs, 7,738 participants: strength-training programs reduced injuries (RR 0.338), and a 10% increase in strength-training volume reduced injury risk by more than four percentage points.", link: doi("10.1136/bjsports-2018-099078"), kind: "doi" },
      { cite: "van der Horst, N., van de Hoef, S., van Otterloo, P., Klein, M., Brink, M., & Backx, F. (2021). Effective but not adhered to: How can we improve adherence to evidence-based hamstring injury prevention in amateur football? Clinical Journal of Sport Medicine, 31(1), 42–48.", note: "Two years after the amateur trial, 69% of 264 players reported never performing the Nordic program; knowledge and personal motivation were the key factors for adherence.", link: doi("10.1097/JSM.0000000000000710"), kind: "doi" },
    ],
  },
  {
    id: "gs-athlete-myth-ice-bath",
    goal: "athlete", tier: "fundamental", section: "9415",
    title: "Myth: An Ice Bath After Every Strength Session Helps You Grow",
    subtitle: "Regular post-lift cold-water immersion blunts hypertrophy and some strength gains",
    evidenceTag: "Strong",
    impact: { magnitude: 1, latency: "weeks", durability: "transient", effort: "low" },
    callout: "Rated at the floor as advice for strength phases: in a 12-week trial, men who took 10-minute cold-water immersions after each strength session gained less strength and muscle mass than those doing active recovery, with type II fibre area rising 17% only in the active group; a 7-week trial found immersion attenuated fibre hypertrophy, and a meta-analysis found regular immersion impaired strength adaptations while not harming endurance adaptations. Save cold water for competition-day recovery when the next effort is hours away, not for the training block that is supposed to build muscle.",
    description:
      "Cold-water immersion is popular because it reduces soreness in the short term, and there is evidence it helps acute recovery of performance between closely spaced efforts. The problem is chronic use during a hypertrophy or strength block: cold blunts the acute anabolic signalling and satellite-cell responses that drive adaptation, and long-term trials show smaller gains. Endurance adaptations appear unaffected, so the verdict is specific: not after lifting, not routinely, and not if the goal is muscle.",
    action: "Drop post-lifting ice baths for the next training block; if you use cold water at all, reserve it for tournament days with several efforts, and use an easy 10-minute spin or walk as your default post-session recovery.",
    sources: [
      { cite: "Roberts, L. A., Raastad, T., Markworth, J. F., Figueiredo, V. C., Egner, I. M., Shield, A., et al. (2015). Post-exercise cold water immersion attenuates acute anabolic signalling and long-term adaptations in muscle to strength training. The Journal of Physiology, 593(18), 4285–4301.", note: "21 men trained for 12 weeks with 10 min cold-water immersion or active recovery after each session: strength and muscle mass rose more with active recovery, and type II fibre area (+17%) and myonuclei per fibre (+26%) increased only in that group.", link: doi("10.1113/JP270570"), kind: "doi" },
      { cite: "Fyfe, J. J., Broatch, J. R., Trewin, A. J., Hanson, E. D., Argus, C. K., Garnham, A. P., et al. (2019). Cold water immersion attenuates anabolic signaling and skeletal muscle fiber hypertrophy, but not strength gain, following whole-body resistance training. Journal of Applied Physiology, 127(5), 1403–1418.", note: "16 men, 7 weeks of resistance training with 15 min immersion at 10°C or passive recovery: immersion attenuated fibre hypertrophy and anabolic signalling while strength gains were similar.", link: doi("10.1152/japplphysiol.00127.2019"), kind: "doi" },
      { cite: "Malta, E. S., Dutra, Y. M., Broatch, J. R., Bishop, D. J., & Zagatto, A. M. (2021). The effects of regular cold-water immersion use on training-induced changes in strength and endurance performance: A systematic review with meta-analysis. Sports Medicine, 51(1), 161–174.", note: "Meta-analysis of regular immersion during training: harmful to resistance-training strength adaptations and not beneficial or harmful to endurance adaptations.", link: doi("10.1007/s40279-020-01362-0"), kind: "doi" },
      { cite: "Petersen, A. C., & Fyfe, J. J. (2021). Post-exercise cold water immersion effects on physiological adaptations to resistance training and the underlying mechanisms in skeletal muscle: A narrative review. Frontiers in Sports and Active Living, 3, 660291.", note: "Narrative review of the mechanisms — blunted anabolic signalling, satellite-cell and protein-synthesis responses — by which repeated post-exercise immersion diminishes long-term resistance-training adaptations.", link: doi("10.3389/fspor.2021.660291"), kind: "doi" },
    ],
  },
  {
    id: "gs-athlete-massage-compression",
    goal: "athlete", tier: "moderate", section: "9416",
    title: "Massage and Compression — Use Them for Soreness and Next-Day Recovery, Expect Small Gains",
    subtitle: "Short massage after mixed high-intensity work; compression after heavy lifting",
    evidenceTag: "Moderate",
    impact: { magnitude: 2, latency: "days", durability: "transient", effort: "low" },
    feeds: ["soreness", "strength recovery", "perceived fatigue"],
    description:
      "A meta-analytic review of 22 randomised trials found the effects of massage on performance recovery are small and partly unclear — larger for short massages (5–12 minutes, g = 0.34), for short-term recovery and after high-intensity mixed exercise, and questionable enough to doubt its widespread use in competitive athletes. Compression garments show small, likely benefits for recovery (ES = 0.38) with the largest effects on strength recovery 2–8 hours and more than 24 hours after resistance exercise; an earlier meta-analysis found moderate effects on soreness, strength, power and creatine kinase. A 99-study meta-analysis ranks massage among the more effective techniques for soreness and perceived fatigue. The verdict: fine for how you feel and for next-day strength, but not a substitute for sleep, nutrition or load management.",
    action: "After heavy lifting or tournament days, wear compression garments for the following 12–24 hours and, if available, take a 10-minute massage; skip both as daily habits and put the time into sleep.",
    sources: [
      { cite: "Poppendieck, W., Wegmann, M., Ferrauti, A., Kellmann, M., Pfeiffer, M., & Meyer, T. (2016). Massage and performance recovery: A meta-analytical review. Sports Medicine, 46(2), 183–204.", note: "22 randomised trials: small, partly unclear effects; shorter massage (5–12 min, +6.6%, g = 0.34) and short-term recovery after high-intensity mixed exercise showed the largest effects, and untrained subjects benefited more than trained athletes.", link: doi("10.1007/s40279-015-0420-x"), kind: "doi" },
      { cite: "Dupuy, O., Douzi, W., Theurot, D., Bosquet, L., & Dugué, B. (2018). An evidence-based approach for choosing post-exercise recovery techniques to reduce markers of muscle damage, soreness, fatigue, and inflammation: A systematic review with meta-analysis. Frontiers in Physiology, 9, 403.", note: "99 studies: massage, active recovery, compression, immersion and cryotherapy were compared for effects on soreness, perceived fatigue and inflammatory markers, with massage among the most effective for soreness and fatigue.", link: doi("10.3389/fphys.2018.00403"), kind: "doi" },
      { cite: "Brown, F., Gissane, C., Howatson, G., van Someren, K., Pedlar, C., & Hill, J. (2017). Compression garments and recovery from exercise: A meta-analysis. Sports Medicine, 47(11), 2245–2267.", note: "23 studies: compression garments produced small, very likely benefits for recovery (ES = 0.38), largest for strength recovery at 2–8 h and beyond 24 h and after resistance exercise; pressure and training status did not moderate.", link: doi("10.1007/s40279-017-0728-9"), kind: "doi" },
      { cite: "Hill, J., Howatson, G., van Someren, K., Leeder, J., & Pedlar, C. (2014). Compression garments and recovery from exercise-induced muscle damage: A meta-analysis. British Journal of Sports Medicine, 48(18), 1340–1346.", note: "12 studies: compression garments had moderate effects on reducing delayed-onset muscle soreness (g = 0.40) and on recovery of strength (0.46), power (0.49) and creatine kinase (0.44).", link: doi("10.1136/bjsports-2013-092456"), kind: "doi" },
    ],
  },
  {
    id: "gs-athlete-hrv-guided",
    goal: "athlete", tier: "advanced", section: "9417",
    title: "Let Morning HRV Decide Whether Today Is Hard or Easy",
    subtitle: "HRV-guided prescription matched or beat predefined plans in small randomised trials",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "moderate" },
    feeds: ["VO2max", "time-trial performance", "avoiding non-functional overreaching"],
    description:
      "In the first randomised test, 26 moderately fit men were assigned to predefined training, HRV-guided training or control; the HRV-guided group trained hard only when morning vagal HRV was stable or rising and improved running performance with fewer high-intensity sessions. In 40 recreational runners, timing moderate and high-intensity sessions by HRV within an individual smallest-worthwhile-change band improved 3,000 m performance relative to a predefined program; in 17 well-trained cyclists, HRV-guided training raised peak power (+5.1%), threshold power and 40-minute time-trial performance while a traditional group did not change, and a later trial compared it with block periodization. A meta-analysis of 8 studies (198 participants) found HRV-guided training mostly equal or superior to predefined training. The boundary: small samples, recreational to well-trained rather than elite, and the method requires consistent measurement conditions.",
    action: "Measure resting HRV every morning for four weeks to set your baseline band, then for the following eight weeks do your planned hard session only on days HRV is within or above the band and swap in an easy session when it is below.",
    sources: [
      { cite: "Kiviniemi, A. M., Hautala, A. J., Kinnunen, H., & Tulppo, M. P. (2007). Endurance training guided individually by daily heart rate variability measurements. European Journal of Applied Physiology, 101(6), 743–751.", note: "26 moderately fit men randomised to predefined, HRV-guided or control: HRV-guided prescription (hard days only when HRV was stable or rising) improved performance with fewer high-intensity sessions.", link: doi("10.1007/s00421-007-0552-2"), kind: "doi" },
      { cite: "Vesterinen, V., Nummela, A., Heikura, I., Laine, T., Hynynen, E., Botella, J., & Häkkinen, K. (2016). Individual endurance training prescription with heart rate variability. Medicine & Science in Sports & Exercise, 48(7), 1347–1354.", note: "40 recreational runners: an 8-week program timing moderate and high-intensity sessions by morning HRV within an individual band improved 3,000 m running performance relative to a predefined program.", link: doi("10.1249/MSS.0000000000000910"), kind: "doi" },
      { cite: "Javaloyes, A., Sarabia, J. M., Lamberts, R. P., & Moya-Ramon, M. (2019). Training prescription guided by heart-rate variability in cycling. International Journal of Sports Physiology and Performance, 14(1), 23–32.", note: "17 well-trained cyclists over 8 weeks: the HRV-guided group improved peak power output (+5.1%), power at the second ventilatory threshold (+13.9%) and 40-min time trial (+7.3%), while the traditional periodization group did not improve significantly.", link: doi("10.1123/ijspp.2018-0122"), kind: "doi" },
      { cite: "Javaloyes, A., Sarabia, J. M., Lamberts, R. P., Plews, D., & Moya-Ramon, M. (2020). Training prescription guided by heart rate variability vs. block periodization in well-trained cyclists. Journal of Strength and Conditioning Research, 34(6), 1511–1518.", note: "20 well-trained cyclists compared HRV-guided prescription with block periodization, extending the earlier trial to a stronger predefined comparator.", link: doi("10.1519/JSC.0000000000003337"), kind: "doi" },
      { cite: "Düking, P., Zinner, C., Trabelsi, K., Reed, J. L., Holmberg, H.-C., Kunz, P., & Sperlich, B. (2021). Monitoring and adapting endurance training on the basis of heart rate variability monitored by wearable technologies: A systematic review with meta-analysis. Journal of Science and Medicine in Sport, 24(11), 1180–1192.", note: "8 studies, 198 participants: compared with predefined training, most HRV-guided approaches produced equal or more favourable endurance outcomes.", link: doi("10.1016/j.jsams.2021.04.012"), kind: "doi" },
    ],
  },
  {
    id: "gs-athlete-overtraining-load",
    goal: "athlete", tier: "moderate", section: "9418",
    title: "Overload Deliberately, Then Recover — and Do Not Spike the Load",
    subtitle: "Functional overreaching is planned; non-functional overreaching and overtraining are failures of recovery",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "moderate" },
    feeds: ["consistency", "injury avoidance", "adaptation"],
    description:
      "The joint ECSS–ACSM consensus distinguishes functional overreaching (a short performance decrement that rebounds after recovery) from non-functional overreaching and the overtraining syndrome, a prolonged maladaptation diagnosed by exclusion; the recognised cause is excessive overload combined with inadequate recovery. On the load side, athletes accustomed to high chronic training loads have fewer injuries than those training less, and rapid, excessive increases in load are implicated in a large share of non-contact soft-tissue injuries — the training–injury prevention paradox. The honest caveat: the acute:chronic workload ratio popularised from that work has been criticised as an inaccurate metric without established causal support, so track load and its rate of change without treating any ratio as a threshold.",
    action: "Log every session's duration and RPE, raise weekly load gradually rather than in jumps, schedule an easier week every third or fourth week, and treat two weeks of falling performance plus disturbed sleep or mood as a signal to cut load and consult your coach or clinician.",
    sources: [
      { cite: "Meeusen, R., Duclos, M., Foster, C., Fry, A., Gleeson, M., Nieman, D., et al. (2013). Prevention, diagnosis, and treatment of the overtraining syndrome: Joint consensus statement of the European College of Sport Science and the American College of Sports Medicine. Medicine & Science in Sports & Exercise, 45(1), 186–205.", note: "Consensus distinguishing functional overreaching, non-functional overreaching and overtraining syndrome, the last a prolonged maladaptation that follows excessive overload with inadequate recovery and is diagnosed by exclusion.", link: doi("10.1249/MSS.0b013e318279a10a"), kind: "doi" },
      { cite: "Gabbett, T. J. (2016). The training–injury prevention paradox: Should athletes be training smarter and harder? British Journal of Sports Medicine, 50(5), 273–280.", note: "Model paper: athletes accustomed to high training loads have fewer injuries than those training less, and excessive and rapid increases in load are likely responsible for a large proportion of non-contact soft-tissue injuries.", link: doi("10.1136/bjsports-2015-095788"), kind: "doi" },
      { cite: "Gabbett, T. J., Hulin, B. T., Blanch, P., & Whiteley, R. (2016). High training workloads alone do not cause sports injuries: How you get there is the real issue. British Journal of Sports Medicine, 50(8), 444–445.", note: "Editorial making the case that the path to a high workload — the rate of increase — rather than the workload itself drives injury risk.", link: doi("10.1136/bjsports-2015-095567"), kind: "doi" },
      { cite: "Impellizzeri, F. M., Tenan, M. S., Kempton, T., Novak, A., & Coutts, A. J. (2020). Acute:chronic workload ratio: Conceptual issues and fundamental pitfalls. International Journal of Sports Physiology and Performance, 15(6), 907–913.", note: "Critique concluding there is no evidence supporting the acute:chronic workload ratio for training recommendations aimed at reducing injury; the ratio is statistically inaccurate and its causal relation to injury has not been established.", link: doi("10.1123/ijspp.2019-0864"), kind: "doi" },
    ],
  },
  {
    id: "gs-athlete-masters",
    goal: "athlete", tier: "moderate", section: "9419",
    title: "Over 40: Keep the Intensity, Not Just the Miles",
    subtitle: "The decline is mostly VO2max; those who keep training hard limit it to under 7% per decade",
    evidenceTag: "Moderate",
    impact: { magnitude: 4, latency: "months", durability: "lasting", effort: "moderate" },
    feeds: ["VO2max", "power", "long-term participation"],
    description:
      "Peak endurance performance is maintained until about 35, declines modestly to 50–60 and steeply after 70; among the three determinants, VO2max falls most while exercise economy is preserved in trained adults, and the decline is mediated largely by a reduced intensity and volume of training that can be performed. Master world records decline linearly until about the eighth decade and then accelerate, and cycling performance holds up later into old age than running or swimming. The encouraging longitudinal data: 40 runners who stayed under three hours in the marathon across five decades slowed only about 0.67% per year, and in highly active cyclists aged 55–79 the muscle showed little age-related change apart from capillary density. The lever is the training stimulus, especially the intense fraction, sustained year over year.",
    action: "If you are over 40, keep one genuinely high-intensity session and two strength sessions in every training week year-round, and re-test a 5-km or 20-minute effort every three months so the decline is measured rather than assumed.",
    sources: [
      { cite: "Tanaka, H., & Seals, D. R. (2008). Endurance exercise performance in Masters athletes: Age-associated changes and underlying physiological mechanisms. The Journal of Physiology, 586(1), 55–63.", note: "Review: peak endurance performance holds until about 35, declines modestly to 50–60 and steeply thereafter; the fall in VO2max is the primary mechanism, economy does not change, and the decline is mediated largely by reduced training intensity and volume.", link: doi("10.1113/jphysiol.2007.141879"), kind: "doi" },
      { cite: "Tanaka, H., & Seals, D. R. (1997). Age and gender interactions in physiological functional capacity: Insight from swimming performance. Journal of Applied Physiology, 82(3), 846–851.", note: "US Masters swimming championship times: endurance performance declined linearly from peak at 35–40 until about 70, then exponentially, with steeper declines in women and in longer events.", link: doi("10.1152/jappl.1997.82.3.846"), kind: "doi" },
      { cite: "Lepers, R., & Stapley, P. J. (2016). Master athletes are extending the limits of human endurance. Frontiers in Physiology, 7, 613.", note: "Review: masters athletes' endurance performances have improved faster than younger athletes', VO2max is the determinant most altered by age, and maintaining a high training stimulus is the single most important means of limiting decline.", link: doi("10.3389/fphys.2016.00613"), kind: "doi" },
      { cite: "Lazarus, N. R., & Harridge, S. D. R. (2017). Declining performance of master athletes: Silhouettes of the trajectory of healthy human ageing? The Journal of Physiology, 595(9), 2941–2948.", note: "World-record analysis showing an essentially linear decline with age until around the eighth decade, then acceleration; proposes a physical-activity set point needed to age optimally.", link: doi("10.1113/JP272443"), kind: "doi" },
      { cite: "Lepers, R., Burfoot, A., & Stapley, P. J. (2021). Sub 3-hour marathon runners for five consecutive decades demonstrate a reduced age-related decline in performance. Frontiers in Physiology, 12, 649282.", note: "40 runners who broke three hours in five consecutive decades slowed about 1 min 4 s per year — a 0.67% annual decline in speed, under 7% per decade — with consistent training and racing.", link: doi("10.3389/fphys.2021.649282"), kind: "doi" },
      { cite: "Lepers, R., Stapley, P. J., & Cattagni, T. (2018). Variation of age-related changes in endurance performance between modes of locomotion in men: An analysis of master world records. International Journal of Sports Physiology and Performance, 13(3), 394–397.", note: "Master world records: the age-related decline in one-hour track cycling was less pronounced than in 1,500 m swimming and 10 km running after 60, while sprint declines were similar across modes.", link: doi("10.1123/ijspp.2017-0222"), kind: "doi" },
      { cite: "Pollock, R. D., O'Brien, K. A., Daniels, L. J., Nielsen, K. B., Rowlerson, A., Duggal, N. A., et al. (2018). Properties of the vastus lateralis muscle in relation to age and physiological function in master cyclists aged 55–79 years. Aging Cell, 17(2), e12735.", note: "Muscle biopsies from 90 highly active cyclists aged 55–79: apart from capillary density in men, muscle fibre type, size and mitochondrial protein content showed no association with age.", link: doi("10.1111/acel.12735"), kind: "doi" },
    ],
  },
  {
    id: "gs-athlete-myth-static-stretching",
    goal: "athlete", tier: "fundamental", section: "9420",
    title: "Myth: Long Static Stretches Before You Perform",
    subtitle: "Pre-exercise static stretching reduces strength and explosive performance and does not prevent injury",
    evidenceTag: "Strong",
    impact: { magnitude: 1, latency: "days", durability: "transient", effort: "low" },
    callout: "Rated at the floor as a warm-up practice: across 104 studies, pre-exercise static stretching reduced strength by 5.4% and explosive performance by 2.0%, with effects growing with total stretch duration; a systematic review put the deficit at 4.6% for 60 seconds or more per muscle versus 1.1% for shorter holds, and the injury-prevention meta-analysis found no protective effect of stretching (RR 0.96). Dynamic stretching and sport-specific activity are the warm-up; keep static holds short and after training.",
    description:
      "Static stretching improves range of motion for under half an hour and feels like preparation, but the acute effect on force production is negative, especially with holds of a minute or more, isometric tests and no subsequent dynamic activity. The systematic review notes that when stretching is followed by dynamic activity the performance effect washes out, which is why the honest recommendation is short holds inside a dynamic warm-up if range of motion is needed, not a stretching routine as the warm-up. For injury, the randomised evidence favours strength and proprioception work, not stretching.",
    action: "Replace pre-session static stretching with 10–15 minutes of progressive dynamic movement; if you need range of motion for your sport, hold static stretches under 30 seconds per muscle and follow them with dynamic drills, or do longer holds after training.",
    sources: [
      { cite: "Simic, L., Sarabon, N., & Markovic, G. (2013). Does pre-exercise static stretching inhibit maximal muscular performance? A meta-analytical review. Scandinavian Journal of Medicine & Science in Sports, 23(2), 131–148.", note: "104 studies: pre-exercise static stretching reduced strength by 5.4%, power by 1.9% and explosive performance by 2.0%, with larger effects for longer total stretch duration and isometric tests; using it as the sole warm-up activity should be avoided.", link: doi("10.1111/j.1600-0838.2012.01444.x"), kind: "doi" },
      { cite: "Behm, D. G., Blazevich, A. J., Kay, A. D., & McHugh, M. (2016). Acute effects of muscle stretching on physical performance, range of motion, and injury incidence in healthy active individuals: A systematic review. Applied Physiology, Nutrition, and Metabolism, 41(1), 1–11.", note: "Static stretching changed performance −3.7% and dynamic stretching +1.3%; deficits were 4.6% for 60 s or more per muscle versus 1.1% for shorter holds, disappeared when followed by dynamic activity, and static stretching had no clear effect on injury incidence.", link: doi("10.1139/apnm-2015-0235"), kind: "doi" },
      { cite: "Lauersen, J. B., Bertelsen, D. M., & Andersen, L. B. (2014). The effectiveness of exercise interventions to prevent sports injuries: A systematic review and meta-analysis of randomised controlled trials. British Journal of Sports Medicine, 48(11), 871–877.", note: "25 randomised trials: stretching showed no injury-prevention benefit (RR 0.963), whereas strength training (RR 0.315) and proprioception training (RR 0.550) did.", link: doi("10.1136/bjsports-2013-092538"), kind: "doi" },
    ],
  },
  {
    id: "gs-athlete-myth-toning",
    goal: "athlete", tier: "fundamental", section: "9421",
    title: "Myth: 'Toning' Exercises Burn the Fat Over the Muscle You Train",
    subtitle: "Spot reduction does not happen; muscle grows where you train it, fat leaves from everywhere",
    evidenceTag: "Strong",
    impact: { magnitude: 1, latency: "weeks", durability: "transient", effort: "low" },
    callout: "Rated at the floor as advice: six weeks of daily abdominal exercise changed no measure of abdominal fat; twelve weeks of 960–1,200 leg-press repetitions per session with one leg reduced fat mass in the trunk and upper body, not preferentially in the trained leg; and twelve weeks of one-arm resistance training changed subcutaneous fat similarly in both arms while muscle grew only in the trained arm. 'Toning' is muscle growth plus whole-body fat loss — there is no third thing.",
    description:
      "High-repetition, low-load exercise marketed as toning does not remove fat from the muscle underneath. Randomised and within-subject trials measured fat by DXA, MRI or skinfold at trained and untrained sites and found no localised fat loss. What changes appearance is hypertrophy — which follows the volume dose–response in the resistance-training cluster — combined with a whole-body energy deficit if fat loss is the goal.",
    action: "Stop programming 'toning' sets; give each muscle group the weekly hard sets from the volume protocol, and if you want visible definition manage overall energy balance rather than adding exercises for one body part.",
    sources: [
      { cite: "Vispute, S. S., Smith, J. D., LeCheminant, J. D., & Hurley, K. S. (2011). The effect of abdominal exercise on abdominal fat. Journal of Strength and Conditioning Research, 25(9), 2559–2564.", note: "24 sedentary adults randomised to six weeks of seven abdominal exercises five days a week or control on an isocaloric diet: no effect on body fat, android fat, abdominal circumference or skinfolds, despite improved muscular endurance.", link: doi("10.1519/JSC.0b013e3181fb4a46"), kind: "doi" },
      { cite: "Ramírez-Campillo, R., Andrade, D. C., Campos-Jara, C., Henríquez-Olguín, C., Alvarez-Lepín, C., & Izquierdo, M. (2013). Regional fat changes induced by localized muscle endurance resistance training. Journal of Strength and Conditioning Research, 27(8), 2219–2224.", note: "Eleven adults trained one leg for 12 weeks with 960–1,200 leg-press repetitions per session: fat mass fell in the trunk and upper body rather than in the trained leg.", link: doi("10.1519/JSC.0b013e31827e8681"), kind: "doi" },
      { cite: "Kostek, M. A., Pescatello, L. S., Seip, R. L., Angelopoulos, T. J., Clarkson, P. M., Gordon, P. M., et al. (2007). Subcutaneous fat alterations resulting from an upper-body resistance training program. Medicine & Science in Sports & Exercise, 39(7), 1177–1185.", note: "Twelve weeks of resistance training of the non-dominant arm: subcutaneous fat measured by MRI changed similarly in trained and untrained arms, while muscle changes were confined to the trained arm.", link: doi("10.1249/mss.0b0138058a5cb"), kind: "doi" },
    ],
  },
  {
    id: "gs-athlete-myth-sports-drinks",
    goal: "athlete", tier: "fundamental", section: "9422",
    title: "Myth: You Need a Sports Drink for a One-Hour Session",
    subtitle: "Carbohydrate drinks help in prolonged hard exercise; for short sessions, water and a mouth rinse do the job",
    evidenceTag: "Strong",
    impact: { magnitude: 1, latency: "days", durability: "transient", effort: "low" },
    callout: "Rated at the floor as everyday advice: an investigation into the evidence behind sports-drink marketing and a systematic assessment of 431 performance claims for 104 products found more than half of the claims unreferenced, 84% of the appraised studies at high risk of bias and only 2.7% of high quality. Carbohydrate ingestion does have a real effect — an 11% time-trial gain after two hours of cycling, with no placebo effect — which is exactly why it belongs in long, hard sessions and races, not the 45-minute gym visit.",
    description:
      "The commercial message that ordinary exercisers need electrolyte-carbohydrate drinks rests on weak evidence, while the physiology is clear for the other case: during prolonged endurance exercise, carbohydrate intake improves performance and high intakes are associated with better Ironman finishing times, at the cost of gut symptoms that must be trained for. For events under about an hour, a carbohydrate mouth rinse captures most of the benefit through the brain. So the honest rule is duration-based: water for short sessions, practised carbohydrate intake for long ones.",
    action: "For sessions under 75 minutes, drink water to thirst; for hard sessions and races over 90 minutes, practise taking 30–60 g of carbohydrate per hour (up to 90 g/h in the longest events) in training so your gut is ready on race day.",
    sources: [
      { cite: "Cohen, D. (2012). The truth about sports drinks. BMJ, 345, e4737.", note: "Investigation of the industry-funded science behind sports-drink hydration and performance claims, including the origin of the advice to drink ahead of thirst.", link: doi("10.1136/bmj.e4737"), kind: "doi" },
      { cite: "Heneghan, C., Gill, P., O'Neill, B., Lasserson, D., Thake, M., & Thompson, M. (2012). Mythbusting sports and exercise products. BMJ, 345, e4848.", note: "Companion analysis examining the evidence for sports drinks, protein and other performance products marketed to the general public.", link: doi("10.1136/bmj.e4848"), kind: "doi" },
      { cite: "Heneghan, C., Howick, J., O'Neill, B., Gill, P. J., Lasserson, D. S., Cohen, D., et al. (2012). The evidence underpinning sports performance products: A systematic assessment. BMJ Open, 2(4), e001702.", note: "431 performance claims for 104 products: 52.8% of websites gave no references, none cited systematic reviews, 84% of appraised studies were at high risk of bias and only 3 of 74 were high quality.", link: doi("10.1136/bmjopen-2012-001702"), kind: "doi" },
      { cite: "Hulston, C. J., & Jeukendrup, A. E. (2009). No placebo effect from carbohydrate intake during prolonged exercise. International Journal of Sport Nutrition and Exercise Metabolism, 19(3), 275–284.", note: "Ten trained cyclists: after 120 min of steady cycling, a 6% carbohydrate-electrolyte drink improved a roughly 60-min time trial by 10.6% versus a matched placebo and 11.3% versus water, with no placebo effect — the real benefit is in prolonged exercise.", link: doi("10.1123/ijsnem.19.3.275"), kind: "doi" },
      { cite: "Burke, L. M., Jeukendrup, A. E., Jones, A. M., & Mooses, M. (2019). Contemporary nutrition strategies to optimize performance in distance runners and race walkers. International Journal of Sport Nutrition and Exercise Metabolism, 29(2), 117–129.", note: "Review of race nutrition: beneficial carbohydrate intakes range from small amounts, including mouth rinsing, in shorter events to 75–90 g/h in the longest races, balanced against gut discomfort.", link: doi("10.1123/ijsnem.2019-0004"), kind: "doi" },
      { cite: "Pfeiffer, B., Stellingwerff, T., Hodgson, A. B., Randell, R., Pöttgen, K., Res, P., & Jeukendrup, A. E. (2012). Nutritional intake and gastrointestinal problems during competitive endurance events. Medicine & Science in Sports & Exercise, 44(2), 344–351.", note: "221 endurance athletes across Ironman, half-Ironman, marathon and cycling events: carbohydrate intake varied from 6 to 136 g/h, higher intake correlated with better Ironman finishing time and with nausea and flatulence, and serious GI symptoms affected about 31% in Ironman races.", link: doi("10.1249/MSS.0b013e31822dc809"), kind: "doi" },
    ],
  },
  {
    id: "gs-athlete-integrated-plan",
    goal: "athlete", tier: "elite", section: "9423",
    title: "Build a Multi-Year Individualized Plan with a Coach — Blocks, Variation, Monitoring",
    subtitle: "Periodized beats non-periodized for strength; the modern view is responsive, not rule-based",
    evidenceTag: "Moderate",
    impact: { magnitude: 4, latency: "months", durability: "lasting", effort: "high" },
    feeds: ["peak timing", "long-term progression", "avoiding plateaus"],
    description:
      "Periodized resistance training produced greater one-repetition-maximum gains than non-periodized training across 18 studies (ES = 0.43), with undulating models, higher frequency and longer programs favoured. Block periodization was proposed to overcome the conflicting adaptations of mixed training and the difficulty of multi-peaking, while Kiely's critique argues training responses vary so much between individuals that generic planning templates should give way to responsive, monitored systems. The evidence that HRV-guided prescription can match or beat block periodization in well-trained cyclists, and that elite endurance training self-organises toward a polarized distribution, points the same way. This is the elite move because it is a system run over years with a coach who adjusts to your data; the boundary is that the periodization trials are mostly in untrained lifters and the individualized-systems literature is young.",
    action: "Hire or partner with a qualified coach, agree a 12-month plan built from 3–6 week blocks with one clear emphasis each, share your daily load, sleep and HRV log, and review and re-plan the next block together every month.",
    sources: [
      { cite: "Williams, T. D., Tolusso, D. V., Fedewa, M. V., & Esco, M. R. (2017). Comparison of periodized and non-periodized resistance training on maximal strength: A meta-analysis. Sports Medicine, 47(10), 2083–2100.", note: "81 effects from 18 studies: periodized plans improved 1RM more than non-periodized plans (ES = 0.43), with undulating models, untrained participants, longer studies and higher training frequency associated with larger gains.", link: doi("10.1007/s40279-017-0734-y"), kind: "doi" },
      { cite: "Issurin, V. B. (2010). New horizons for the methodology and physiology of training periodization. Sports Medicine, 40(3), 189–206.", note: "Argues traditional mixed periodization produces conflicting responses and cannot serve multi-peak seasons, and proposes block periodization: sequenced mesocycles with highly concentrated loads on a minimal number of targeted abilities.", link: doi("10.2165/11319770-000000000-00000"), kind: "doi" },
      { cite: "Kiely, J. (2012). Periodization paradigms in the 21st century: Evidence-led or tradition-driven? International Journal of Sports Physiology and Performance, 7(3), 242–250.", note: "Review arguing that training responses vary extensively between individuals, that generic rule-based planning is not scientifically justified, and that sensitive, responsive training systems should guide context-specific planning.", link: doi("10.1123/ijspp.7.3.242"), kind: "doi" },
      { cite: "Javaloyes, A., Sarabia, J. M., Lamberts, R. P., Plews, D., & Moya-Ramon, M. (2020). Training prescription guided by heart rate variability vs. block periodization in well-trained cyclists. Journal of Strength and Conditioning Research, 34(6), 1511–1518.", note: "Compared a responsive HRV-guided prescription with block periodization in 20 well-trained cyclists — the direct test of monitored versus predefined planning.", link: doi("10.1519/JSC.0000000000003337"), kind: "doi" },
      { cite: "Stöggl, T. L., & Sperlich, B. (2015). The training intensity distribution among well-trained and elite endurance athletes. Frontiers in Physiology, 6, 295.", note: "Systematic overview of intensity distribution across preparation, pre-competition and competition phases in different endurance disciplines — the seasonal structure an integrated plan reproduces.", link: doi("10.3389/fphys.2015.00295"), kind: "doi" },
    ],
  },
];
