// Goal shelf: BUSINESS — start and grow a business (sections 8500–8599).
// Verification: every DOI below was resolved against the Crossref record on
// 2026-09-11 (see the ledger in the research scratchpad). See types.ts for the
// contract. Nothing here is legal, tax or investment advice; each note describes
// what the cited study tested.
import { doi, type GoalShelfCluster } from "./types";

export const SECTIONS: Record<string, string> = {
  "8500": "How to Read This Shelf",
  "8501": "Survival Odds — What Predicts Whether a New Business Lives",
  "8502": "Keep the Day Job — Hybrid Entry and Founder Age",
  "8503": "Test Before You Build — The Scientific Approach and Lean Experimentation",
  "8504": "Customer Discovery — Finding the Real Market Before Launch",
  "8505": "Plan or Storm the Castle — Business Plans and Effectuation",
  "8506": "Business Training, Coaching and Consulting — What the RCTs Show",
  "8507": "Entrepreneurship Education — Honest Effect Sizes",
  "8508": "Accelerators and Angel Networks",
  "8509": "Founding Teams vs. Going Solo",
  "8510": "Networking and Social Capital",
  "8511": "Pricing — What Field Experiments Say",
  "8512": "Selling — The Skills That Predict Sales Performance",
  "8513": "Cash Flow, Failure and Bankruptcy — Why Small Firms Die",
  "8514": "Financing — Bootstrapping vs. Outside Money",
  "8515": "Franchising — Buying a System Instead of Building One",
  "8516": "Digital Marketing — What Ads Actually Return",
  "8517": "Founder Wellbeing and Burnout",
  "8518": "Grit and Entrepreneurial Persistence",
  "8519": "Myth: Passion and Optimism Are a Business Plan",
  "8520": "Myth: 10,000 Hours of Practice Makes the Founder",
};

export const CLUSTERS: GoalShelfCluster[] = [
  {
    id: "gs-business-read-me-first",
    goal: "business", tier: "fundamental", section: "8500",
    title: "How to Read the Business Shelf",
    subtitle: "Protocols with base rates attached — pick one per tier each month",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "low" },
    description:
      "Every protocol on this shelf is tagged fundamental, moderate, advanced or elite and carries a concrete action. The monthly menu hands you one or two from each tier. Two things are different about this shelf: most 'closures' in the survival statistics are not failures, and most popular founder advice has never been tested. The floor-rated clusters at the end tell you which advice the evidence does not support.",
    action: "This month, read the survival-odds cluster first, then pick the one fundamental protocol you are not already doing and run it for 30 days before adding anything else.",
    sources: [
      { cite: "Headd, B. (2003). Redefining business success: Distinguishing between closure and failure. Small Business Economics, 21(1), 51–61.", note: "Uses U.S. Census business-owner data to separate firms that closed from firms that failed; a meaningful share of closures were reported as successful at closing, which changes how survival statistics should be read.", link: doi("10.1023/A:1024433630958"), kind: "doi" },
    ],
  },
  {
    id: "gs-business-survival-odds",
    goal: "business", tier: "fundamental", section: "8501",
    title: "Learn the Base Rates Before You Bet",
    subtitle: "Survival is predicted by starting size, capital, owner experience and founding conditions",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "days", durability: "lasting", effort: "low" },
    feeds: ["calibrated judgment", "risk literacy"],
    description:
      "Decades of firm-level data show new-business survival is not random: firms that start larger, better capitalized and run by owners with education and prior industry experience survive longer, and the conditions at founding keep mattering for years. Headd's Census analysis adds that many closures are voluntary and reported as successful. Knowing the predictors lets you score your own plan honestly rather than relying on the folk statistic that 'most businesses fail'.",
    action: "Before spending money, write a one-page scorecard of your venture against the documented predictors — starting capital, owner industry experience, education, founding-year market conditions — and list the two weakest items as the first things to fix.",
    sources: [
      { cite: "Headd, B. (2003). Redefining business success: Distinguishing between closure and failure. Small Business Economics, 21(1), 51–61.", note: "Separates closure from failure in U.S. Census business-owner data and identifies owner and firm characteristics associated with each outcome.", link: doi("10.1023/A:1024433630958"), kind: "doi" },
      { cite: "Bates, T. (1990). Entrepreneur human capital inputs and small business longevity. The Review of Economics and Statistics, 72(4), 551–559.", note: "Owner education and the capital invested at start-up are linked to whether small firms are still operating years later; human capital and financial capital reinforce each other.", link: doi("10.2307/2109594"), kind: "doi" },
      { cite: "Audretsch, D. B., & Mahmood, T. (1995). New firm survival: New results using a hazard function. The Review of Economics and Statistics, 77(1), 97–103.", note: "Hazard-function estimates of new-firm survival show that start-up size, industry conditions and ownership structure shift the probability of exit over time.", link: doi("10.2307/2109995"), kind: "doi" },
      { cite: "Geroski, P. A., Mata, J., & Portugal, P. (2010). Founding conditions and the survival of new firms. Strategic Management Journal, 31(5), 510–529.", note: "Conditions at the moment of founding are important determinants of exit rates and their effect persists with little attenuation for several years after founding.", link: doi("10.1002/smj.823"), kind: "doi" },
    ],
  },
  {
    id: "gs-business-hybrid-entry",
    goal: "business", tier: "fundamental", section: "8502",
    title: "Keep the Day Job While You Start",
    subtitle: "Hybrid entrepreneurs who test the water before quitting survive longer — and the best founders are middle-aged",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "months", durability: "lasting", effort: "moderate" },
    feeds: ["financial runway", "learning under low stakes"],
    description:
      "Two large administrative-data studies overturn the 'burn the boats' story. Raffiee and Feng find that people who enter self-employment while keeping wage work, then transition fully, have better survival than those who leap directly; Folta, Delmar and Wennberg show hybrid entry is a large share of all entrepreneurial activity and a stepping stone to full self-employment. Azoulay and colleagues find the fastest-growing U.S. start-ups are founded by people in middle age with prior industry experience, not by the young.",
    action: "Start your business as a hybrid: keep your income, set a fixed weekly block of hours for the venture, and write the specific revenue or customer threshold at which you would go full-time.",
    sources: [
      { cite: "Raffiee, J., & Feng, J. (2014). Should I quit my day job?: A hybrid path to entrepreneurship. Academy of Management Journal, 57(4), 936–963.", note: "Compares people who entered self-employment while keeping wage work against those who entered directly; the hybrid path is associated with better subsequent venture survival.", link: doi("10.5465/amj.2012.0522"), kind: "doi" },
      { cite: "Folta, T. B., Delmar, F., & Wennberg, K. (2010). Hybrid entrepreneurship. Management Science, 56(2), 253–269.", note: "Using matched employee–employer data over eight years, shows hybrid entrants are a significant share of entrepreneurial activity and that hybrid entry facilitates later full self-employment.", link: doi("10.1287/mnsc.1090.1094"), kind: "doi" },
      { cite: "Azoulay, P., Jones, B. F., Kim, J. D., & Miranda, J. (2020). Age and high-growth entrepreneurship. American Economic Review: Insights, 2(1), 65–82.", note: "Integrates U.S. administrative data on firms, workers and owners; the mean founder age for the 1-in-1,000 fastest-growing new ventures is 45, and prior experience in the specific industry predicts much higher success rates.", link: doi("10.1257/aeri.20180582"), kind: "doi" },
      { cite: "Lévesque, M., & Minniti, M. (2006). The effect of aging on entrepreneurial behavior. Journal of Business Venturing, 21(2), 177–194.", note: "Models how the opportunity cost of time changes with age and why the propensity to start a business peaks and then declines, framing when in life a founding decision is best made.", link: doi("10.1016/j.jbusvent.2005.04.003"), kind: "doi" },
    ],
  },
  {
    id: "gs-business-scientific-approach",
    goal: "business", tier: "moderate", section: "8503",
    title: "Run Your Idea Like an Experiment",
    subtitle: "Founders trained to state hypotheses and test them rigorously earned more and pivoted better in randomized trials",
    evidenceTag: "Strong",
    impact: { magnitude: 5, latency: "months", durability: "lasting", effort: "moderate" },
    feeds: ["decision quality", "willingness to kill bad ideas"],
    description:
      "The strongest causal evidence on how to start a business comes from randomized trials of a 'scientific' decision method: founders were taught to write a theory of their business, derive testable hypotheses, and run rigorous tests before committing. In the original trial with 116 Italian start-ups, treated founders performed better and were more likely to pivot; the 759-firm replication across four trials found higher rates of idea termination and a pattern of a few decisive pivots rather than none or many. This is the evidence-based core of what the lean-startup literature describes.",
    action: "Write your business idea as a one-page theory with three falsifiable hypotheses about customers, price and channel; for each, define in advance what result would make you drop it, then run the cheapest test you can within 30 days.",
    sources: [
      { cite: "Camuffo, A., Cordova, A., Gambardella, A., & Spina, C. (2020). A scientific approach to entrepreneurial decision making: Evidence from a randomized control trial. Management Science, 66(2), 564–586.", note: "RCT with 116 Italian start-ups over about a year; founders taught to form and test hypotheses like scientists performed better and were more likely to pivot without dropping out more often.", link: doi("10.1287/mnsc.2018.3249"), kind: "doi" },
      { cite: "Camuffo, A., Gambardella, A., Messinese, D., Novelli, E., Paolucci, E., & Spina, C. (2024). A scientific approach to entrepreneurial decision-making: Large-scale replication and extension. Strategic Management Journal, 45(6), 1209–1237.", note: "Replication involving 759 firms in four randomized trials; the scientific approach raised idea termination and produced a nonlinear effect on radical pivots — a few pivots rather than none or repeated ones.", link: doi("10.1002/smj.3580"), kind: "doi" },
      { cite: "Shepherd, D. A., & Gruber, M. (2021). The lean startup framework: Closing the academic–practitioner divide. Entrepreneurship Theory and Practice, 45(5), 967–998.", note: "Maps the five building blocks of lean startup (business model, validated learning, minimum viable product, persevere-vs-pivot, market navigation) onto existing research findings.", link: doi("10.1177/1042258719899415"), kind: "doi" },
      { cite: "Contigiani, A., & Levinthal, D. A. (2019). Situating the construct of lean start-up: Adjacent conversations and possible future directions. Industrial and Corporate Change, 28(3), 551–564.", note: "Places lean startup within research on experimentation, search and learning, and identifies where the practitioner method is and is not supported by theory.", link: doi("10.1093/icc/dtz013"), kind: "doi" },
    ],
  },
  {
    id: "gs-business-customer-discovery",
    goal: "business", tier: "moderate", section: "8504",
    title: "Talk to Lead Users Before You Pick a Market",
    subtitle: "Founders who consider several markets and learn from advanced users find better opportunities",
    evidenceTag: "Moderate",
    impact: { magnitude: 4, latency: "weeks", durability: "sustained", effort: "moderate" },
    feeds: ["market judgment", "product fit"],
    description:
      "Customer discovery is more than asking friends if they like the idea. Research on technology start-ups shows the number and variety of market opportunities a founding team identifies before entry depends on the team's prior knowledge and on deliberately escaping it. Lead-user studies at large firms found ideas sourced from advanced users generated substantially more commercial value than conventional idea generation. Parker's work shows entrepreneurs update their beliefs slowly, which is why structured feedback matters.",
    action: "Before committing to one market, list three distinct customer groups who could use what you make, interview at least five 'lead users' from each — people already improvising a solution — and record what they pay today to work around the problem.",
    sources: [
      { cite: "Gruber, M., MacMillan, I. C., & Thompson, J. D. (2013). Escaping the prior knowledge corridor: What shapes the number and variety of market opportunities identified before market entry of technology start-ups? Organization Science, 24(1), 280–300.", note: "Founding teams' prior knowledge shapes how many and how varied the market opportunities they see are; deliberate search widens the set considered before entry.", link: doi("10.1287/orsc.1110.0721"), kind: "doi" },
      { cite: "Lilien, G. L., Morrison, P. D., Searls, K., Sonnack, M., & von Hippel, E. (2002). Performance assessment of the lead user idea-generation process for new product development. Management Science, 48(8), 1042–1059.", note: "Compares product ideas generated through lead-user methods with conventional methods inside a large firm; lead-user projects were associated with markedly higher projected sales.", link: doi("10.1287/mnsc.48.8.1042.171"), kind: "doi" },
      { cite: "Franke, N., von Hippel, E., & Schreier, M. (2006). Finding commercially attractive user innovations: A test of lead-user theory. Journal of Product Innovation Management, 23(4), 301–315.", note: "Tests lead-user theory in a user community; innovations from users who are ahead of trends and have high expected benefit are more commercially attractive.", link: doi("10.1111/j.1540-5885.2006.00203.x"), kind: "doi" },
      { cite: "Parker, S. C. (2006). Learning about the unknown: How fast do entrepreneurs adjust their beliefs? Journal of Business Venturing, 21(1), 1–26.", note: "Models and estimates how quickly entrepreneurs revise their expectations in response to new information, finding adjustment is partial rather than immediate.", link: doi("10.1016/j.jbusvent.2004.07.005"), kind: "doi" },
    ],
  },
  {
    id: "gs-business-plan-or-effectuate",
    goal: "business", tier: "moderate", section: "8505",
    title: "Write a Short Plan, Then Act With What You Have",
    subtitle: "Planning helps new ventures on average, but the written document matters less than the thinking; effectuation explains what experts do instead",
    evidenceTag: "Mixed",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "moderate" },
    feeds: ["clarity of goals", "resource discipline"],
    description:
      "The evidence on business plans is genuinely mixed. A meta-analysis found planning has a small positive relationship with performance, stronger for established firms than for start-ups; Delmar and Shane's study of 223 Swedish ventures found planning reduced disbanding and sped product development; Honig and Karlsson's two-year study of 396 nascent firms found written plans were produced largely because institutions expected them and showed no profitability benefit. Sarasvathy's effectuation research describes how expert entrepreneurs start from their means and affordable losses rather than from a fixed plan, and a meta-analysis links effectual principles with venture performance.",
    action: "Write a two-page plan that states your goal, your means (what you know, whom you know, what you own) and the maximum loss you can afford this year; revisit and revise it monthly rather than writing a 40-page document once.",
    sources: [
      { cite: "Brinckmann, J., Grichnik, D., & Kapsa, D. (2010). Should entrepreneurs plan or just storm the castle? A meta-analysis on contextual factors impacting the business planning–performance relationship in small firms. Journal of Business Venturing, 25(1), 24–40.", note: "Meta-analysis of planning studies in small firms; planning is positively related to performance on average, with the relationship moderated by firm age and context.", link: doi("10.1016/j.jbusvent.2008.10.007"), kind: "doi" },
      { cite: "Delmar, F., & Shane, S. (2003). Does business planning facilitate the development of new ventures? Strategic Management Journal, 24(12), 1165–1185.", note: "Tracked 223 new ventures started by a random sample of Swedish founders; business planning reduced the likelihood of disbanding and accelerated product development and organizing activity.", link: doi("10.1002/smj.349"), kind: "doi" },
      { cite: "Honig, B., & Karlsson, T. (2004). Institutional forces and the written business plan. Journal of Management, 30(1), 29–48.", note: "Followed 396 nascent entrepreneurs for two years; coercive and mimetic institutional pressures predicted who wrote plans, and there was no evidence of profitability gains from having written one.", link: doi("10.1016/j.jm.2002.11.002"), kind: "doi" },
      { cite: "Sarasvathy, S. D. (2001). Causation and effectuation: Toward a theoretical shift from economic inevitability to entrepreneurial contingency. The Academy of Management Review, 26(2), 243–263.", note: "Introduces effectuation — starting from available means, affordable loss and partnerships rather than a predicted goal — as the logic expert entrepreneurs use under uncertainty.", link: doi("10.2307/259121"), kind: "doi" },
      { cite: "Read, S., Song, M., & Smit, W. (2009). A meta-analytic review of effectuation and venture performance. Journal of Business Venturing, 24(6), 573–587.", note: "Meta-analysis relating effectual principles (means, partnerships, affordable loss, leveraging contingency) to new-venture performance; most principles show positive associations.", link: doi("10.1016/j.jbusvent.2008.02.005"), kind: "doi" },
    ],
  },
  {
    id: "gs-business-training-consulting",
    goal: "business", tier: "advanced", section: "8506",
    title: "Buy Training That Changes Practices, Not Lectures",
    subtitle: "Randomized trials show classroom business training has modest effects; personal-initiative training and hands-on consulting do better",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "months", durability: "sustained", effort: "high" },
    feeds: ["management practices", "proactive habits"],
    description:
      "The World Bank review of business-training evaluations found that standard classroom training changes some practices but has small and often imprecisely measured effects on sales and profits; McKenzie's reassessment argues the pooled evidence is more positive than 'training doesn't work'. A Science trial in Togo found teaching personal initiative — proactive, self-starting behaviour — beat traditional training on sales and profits. Randomized consulting for Mexican SMEs and marketing-versus-finance training in South Africa show hands-on, skill-specific help improves practices and performance. Capital-grant experiments show returns to small injections of capital can be high for constrained firms.",
    action: "If you pay for training this year, choose a program built around implementing specific practices in your own business with follow-up (coaching, consulting, personal-initiative style), and write the three practices you will change before the first session.",
    sources: [
      { cite: "McKenzie, D., & Woodruff, C. (2014). What are we learning from business training and entrepreneurship evaluations around the developing world? The World Bank Research Observer, 29(1), 48–82.", note: "Reviews randomized and quasi-experimental evaluations of business training; training changes practices modestly and most studies are underpowered to detect profit effects.", link: doi("10.1093/wbro/lkt007"), kind: "doi" },
      { cite: "McKenzie, D. (2021). Small business training to improve management practices in developing countries: Re-assessing the evidence for 'training doesn't work'. Oxford Review of Economic Policy, 37(2), 276–301.", note: "Re-assesses the accumulated experimental literature and argues that, pooled, business training has positive effects on practices, sales and profits that individual studies could not detect.", link: doi("10.1093/oxrep/grab002"), kind: "doi" },
      { cite: "Campos, F., Frese, M., Goldstein, M., Iacovone, L., Johnson, H. C., McKenzie, D., & Mensmann, M. (2017). Teaching personal initiative beats traditional training in boosting small business in West Africa. Science, 357(6357), 1287–1290.", note: "Randomized trial in Togo; a psychology-based personal-initiative training raised sales and profits more than traditional business training.", link: doi("10.1126/science.aan5329"), kind: "doi" },
      { cite: "Karlan, D., & Valdivia, M. (2011). Teaching entrepreneurship: Impact of business training on microfinance clients and institutions. Review of Economics and Statistics, 93(2), 510–527.", note: "Randomized business training for microfinance clients in Peru improved business knowledge and practices and client retention for the lender, with weaker evidence on revenues.", link: doi("10.1162/rest_a_00074"), kind: "doi" },
      { cite: "Bruhn, M., Karlan, D., & Schoar, A. (2018). The impact of consulting services on small and medium enterprises: Evidence from a randomized trial in Mexico. Journal of Political Economy, 126(2), 635–687.", note: "Randomized subsidized consulting for Mexican SMEs; treated firms improved management practices and performance, with employment effects emerging over the longer term.", link: doi("10.1086/696154"), kind: "doi" },
      { cite: "Anderson, S. J., Chandy, R., & Zia, B. (2018). Pathways to profits: The impact of marketing vs. finance skills on business performance. Management Science, 64(12), 5559–5583.", note: "Randomized marketing training versus finance training for small firms in South Africa; both improved profits through different pathways — growth for marketing, efficiency for finance.", link: doi("10.1287/mnsc.2017.2920"), kind: "doi" },
      { cite: "Fafchamps, M., McKenzie, D., Quinn, S., & Woodruff, C. (2014). Microenterprise growth and the flypaper effect: Evidence from a randomized experiment in Ghana. Journal of Development Economics, 106, 211–226.", note: "Randomized cash versus in-kind grants to microenterprises; in-kind capital 'stuck' to the business and raised profits where cash did not, highlighting the discipline problem in small firms.", link: doi("10.1016/j.jdeveco.2013.09.010"), kind: "doi" },
    ],
  },
  {
    id: "gs-business-entrepreneurship-education",
    goal: "business", tier: "advanced", section: "8507",
    title: "Take a Course for Skills, Not for Motivation",
    subtitle: "Entrepreneurship education raises knowledge and skills; its effect on intentions vanishes once prior intentions are controlled",
    evidenceTag: "Mixed",
    impact: { magnitude: 2, latency: "months", durability: "sustained", effort: "high" },
    feeds: ["business knowledge", "realistic self-assessment"],
    description:
      "Meta-analyses of entrepreneurship education find positive effects on knowledge, skills and perceived capability, but Bae and colleagues' 73-study meta-analysis found the correlation with entrepreneurial intentions was small and became non-significant after controlling for pre-education intentions. A Dutch field study found a compulsory program did not raise skills or motivation and lowered intentions. Self-efficacy does relate to later firm performance, so courses that build real capability rather than enthusiasm are the ones worth paying for.",
    action: "If you enrol in an entrepreneurship course, pick one graded on a live project with real customers and measurable milestones, and judge it afterwards by the skills you can now perform, not by how motivated you feel.",
    sources: [
      { cite: "Martin, B. C., McNally, J. J., & Kay, M. J. (2013). Examining the formation of human capital in entrepreneurship: A meta-analysis of entrepreneurship education outcomes. Journal of Business Venturing, 28(2), 211–224.", note: "Meta-analysis of entrepreneurship education and training; positive relationships with entrepreneurship-related human capital and outcomes, larger in academic than in short training contexts.", link: doi("10.1016/j.jbusvent.2012.03.002"), kind: "doi" },
      { cite: "Bae, T. J., Qian, S., Miao, C., & Fiet, J. O. (2014). The relationship between entrepreneurship education and entrepreneurial intentions: A meta-analytic review. Entrepreneurship Theory and Practice, 38(2), 217–254.", note: "Meta-analysis of 73 studies (37,285 people); a small correlation between education and intentions that was not significant once pre-education intentions were controlled.", link: doi("10.1111/etap.12095"), kind: "doi" },
      { cite: "Nabi, G., Liñán, F., Fayolle, A., Krueger, N., & Walmsley, A. (2017). The impact of entrepreneurship education in higher education: A systematic review and research agenda. Academy of Management Learning & Education, 16(2), 277–299.", note: "Systematic review of higher-education entrepreneurship programs; impact is measured mostly on attitudes and intentions, with far less evidence on actual venture creation.", link: doi("10.5465/amle.2015.0026"), kind: "doi" },
      { cite: "Oosterbeek, H., van Praag, M., & Ijsselstein, A. (2010). The impact of entrepreneurship education on entrepreneurship skills and motivation. European Economic Review, 54(3), 442–454.", note: "Instrumental-variables evaluation of a compulsory entrepreneurship program at a Dutch college; no positive effect on self-assessed skills and a negative effect on intentions.", link: doi("10.1016/j.euroecorev.2009.08.002"), kind: "doi" },
      { cite: "Miao, C., Qian, S., & Ma, D. (2017). The relationship between entrepreneurial self-efficacy and firm performance: A meta-analysis of main and moderator effects. Journal of Small Business Management, 55(1), 87–107.", note: "Meta-analysis linking entrepreneurial self-efficacy to firm performance; a positive relationship that varies with context, supporting capability-building over motivation-only programs.", link: doi("10.1111/jsbm.12240"), kind: "doi" },
    ],
  },
  {
    id: "gs-business-accelerators-angels",
    goal: "business", tier: "elite", section: "8508",
    title: "Get Into an Accelerator or Angel Network — for the Learning, Not the Badge",
    subtitle: "Accelerators help mainly through intensive learning and entrepreneurship schooling; angel backing improves survival and growth",
    evidenceTag: "Moderate",
    impact: { magnitude: 4, latency: "months", durability: "lasting", effort: "high" },
    feeds: ["mentor access", "investor readiness"],
    description:
      "Evidence on accelerators comes from a regression-discontinuity study of Start-Up Chile, where the cash-only program had little effect but the added entrepreneurship schooling raised fundraising and growth, and from Hallen, Cohen and Bingham's matched comparison showing top accelerators speed venture development through intensive learning from others. Kerr, Lerner and Schoar's study of angel groups found ventures just above the funding threshold had better survival, growth and follow-on financing. These are rare, competitive, high-leverage moves.",
    action: "If you apply to an accelerator or angel group this year, choose by the quality of the mentors and curriculum rather than the cheque, and commit to attending every session and mentor meeting for the full cohort.",
    sources: [
      { cite: "Gonzalez-Uribe, J., & Leatherbee, M. (2018). The effects of business accelerators on venture performance: Evidence from Start-Up Chile. The Review of Financial Studies, 31(4), 1566–1603.", note: "Regression-discontinuity evidence from Start-Up Chile; basic cash and coworking had little effect, while the entrepreneurship-schooling component raised fundraising and firm growth.", link: doi("10.1093/rfs/hhx103"), kind: "doi" },
      { cite: "Hallen, B. L., Cohen, S. L., & Bingham, C. B. (2020). Do accelerators work? If so, how? Organization Science, 31(2), 378–414.", note: "Matched comparisons of accelerated and non-accelerated ventures; top accelerators speed development, with the mechanism being intensive, broad learning from others rather than signalling.", link: doi("10.1287/orsc.2019.1304"), kind: "doi" },
      { cite: "Kerr, W. R., Lerner, J., & Schoar, A. (2014). The consequences of entrepreneurial finance: Evidence from angel financings. The Review of Financial Studies, 27(1), 20–55.", note: "Regression-discontinuity design around angel-group funding decisions; ventures just above the threshold showed better survival, growth and subsequent financing.", link: doi("10.1093/rfs/hhr098"), kind: "doi" },
    ],
  },
  {
    id: "gs-business-founding-team",
    goal: "business", tier: "elite", section: "8509",
    title: "Build a Founding Team With Proven Operators",
    subtitle: "Most new ventures are team efforts; team functioning and prior success predict outcomes more than the lone-genius story",
    evidenceTag: "Moderate",
    impact: { magnitude: 4, latency: "months", durability: "lasting", effort: "high" },
    feeds: ["complementary skills", "shared leadership"],
    description:
      "Reviews of new-venture teams show most ventures are founded by teams, and that team processes — how members interact, share leadership and handle conflict — mediate the link between who is on the team and how the venture performs. Ruef, Aldrich and Carter's national sample shows founders overwhelmingly team up with people like themselves and with strong ties, which narrows skills. Gompers and colleagues find entrepreneurs with a prior successful venture are more likely to succeed again than first-timers or those who previously failed.",
    action: "Before recruiting a cofounder, write the three capabilities the venture needs that you lack, and screen candidates for those and for a track record of finishing things — not for friendship or similarity.",
    sources: [
      { cite: "Klotz, A. C., Hmieleski, K. M., Bradley, B. H., & Busenitz, L. W. (2014). New venture teams: A review of the literature and roadmap for future research. Journal of Management, 40(1), 226–255.", note: "Reviews two decades of new-venture team research through an inputs–mediators–outcomes lens; team processes explain why similar-looking teams reach different outcomes.", link: doi("10.1177/0149206313493325"), kind: "doi" },
      { cite: "Ensley, M. D., Hmieleski, K. M., & Pearce, C. L. (2006). The importance of vertical and shared leadership within new venture top management teams: Implications for the performance of startups. The Leadership Quarterly, 17(3), 217–231.", note: "Studies new-venture top management teams; both leadership by the lead founder and leadership shared across the team relate to venture performance.", link: doi("10.1016/j.leaqua.2006.02.002"), kind: "doi" },
      { cite: "Lechler, T. (2001). Social interaction: A determinant of entrepreneurial team venture success. Small Business Economics, 16(4), 263–278.", note: "Survey of entrepreneurial teams; the quality of social interaction within the team — communication, cohesion, conflict handling — is associated with venture success.", link: doi("10.1023/A:1011167519304"), kind: "doi" },
      { cite: "Ruef, M., Aldrich, H. E., & Carter, N. M. (2003). The structure of founding teams: Homophily, strong ties, and isolation among U.S. entrepreneurs. American Sociological Review, 68(2), 195–222.", note: "Nationally representative U.S. data on founding teams; teams form overwhelmingly along lines of similarity and strong ties, which constrains the diversity of skills brought in.", link: doi("10.1177/000312240306800202"), kind: "doi" },
      { cite: "Gompers, P., Kovner, A., Lerner, J., & Scharfstein, D. (2010). Performance persistence in entrepreneurship. Journal of Financial Economics, 96(1), 18–32.", note: "Entrepreneurs with a prior successful venture are more likely to succeed in a subsequent venture than first-time or previously unsuccessful founders — persistence of skill rather than luck.", link: doi("10.1016/j.jfineco.2009.11.001"), kind: "doi" },
    ],
  },
  {
    id: "gs-business-networking",
    goal: "business", tier: "fundamental", section: "8510",
    title: "Build Bridging Ties on Purpose",
    subtitle: "Social capital predicts small-firm performance, most for new firms and for ties that reach outside your circle",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "months", durability: "lasting", effort: "moderate" },
    feeds: ["resource access", "information flow"],
    description:
      "A meta-analysis of network studies found entrepreneurs' social capital is positively related to small-firm performance, with larger effects for new firms and for weak, bridging ties that reach diverse information. Davidsson and Honig's longitudinal study of nascent entrepreneurs found social capital — especially being a member of a business network — predicted progressing through the start-up process. Markman and Baron argue that social skills are part of what makes some people fit entrepreneurship better than others.",
    action: "Each week for the next three months, have one conversation with someone outside your usual circle who serves your target customers or sells to them, and keep a one-line log of what you learned and what you offered.",
    sources: [
      { cite: "Stam, W., Arzlanian, S., & Elfring, T. (2014). Social capital of entrepreneurs and small firm performance: A meta-analysis of contextual and methodological moderators. Journal of Business Venturing, 29(1), 152–173.", note: "Meta-analysis of social capital and small-firm performance; the relationship is positive and stronger for young firms and for network diversity and weak ties.", link: doi("10.1016/j.jbusvent.2013.01.002"), kind: "doi" },
      { cite: "Hoang, H., & Antoncic, B. (2003). Network-based research in entrepreneurship: A critical review. Journal of Business Venturing, 18(2), 165–187.", note: "Critical review of network research in entrepreneurship, organizing what is known about how network content, governance and structure relate to venture outcomes.", link: doi("10.1016/S0883-9026(02)00081-2"), kind: "doi" },
      { cite: "Davidsson, P., & Honig, B. (2003). The role of social and human capital among nascent entrepreneurs. Journal of Business Venturing, 18(3), 301–331.", note: "Longitudinal study of nascent entrepreneurs; social capital, particularly business-network membership, predicted progress toward a first sale more consistently than formal education.", link: doi("10.1016/S0883-9026(02)00097-6"), kind: "doi" },
      { cite: "Markman, G. D., & Baron, R. A. (2003). Person–entrepreneurship fit: Why some people are more successful as entrepreneurs than others. Human Resource Management Review, 13(2), 281–301.", note: "Proposes that self-efficacy, opportunity recognition, perseverance and social skills determine how well a person fits the demands of entrepreneurship.", link: doi("10.1016/S1053-4822(03)00018-4"), kind: "doi" },
    ],
  },
  {
    id: "gs-business-pricing",
    goal: "business", tier: "moderate", section: "8511",
    title: "Price by Experiment, Not by Gut",
    subtitle: "Field experiments show price endings, anchors and participative pricing move demand in ways intuition misses",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "weeks", durability: "sustained", effort: "moderate" },
    feeds: ["margin", "demand literacy"],
    description:
      "Pricing research is unusually experimental. Anderson and Simester's field experiments with catalog retailers found prices ending in 9 raised demand, sometimes even when the 9-ending price was higher. Ariely, Loewenstein and Prelec showed willingness to pay is anchored by arbitrary numbers yet stays internally consistent, and Wansink and colleagues found purchase-quantity anchors raise units bought. Pay-what-you-want studies found buyers often pay meaningful amounts, and a large field experiment in PNAS showed pay-what-you-want combined with a charitable component can raise both revenue and giving.",
    action: "Pick one product, run two price points (or one price and one framing such as an anchor or a 9-ending) for four weeks with customers randomly assigned, and keep the version with higher total margin — then repeat with the next variable.",
    sources: [
      { cite: "Anderson, E. T., & Simester, D. I. (2003). Effects of $9 price endings on retail sales: Evidence from field experiments. Quantitative Marketing and Economics, 1(1), 93–110.", note: "Field experiments with a catalog retailer; prices ending in 9 increased demand, an effect that held even in comparisons where the 9-ending price was higher.", link: doi("10.1023/A:1023581927405"), kind: "doi" },
      { cite: "Ariely, D., Loewenstein, G., & Prelec, D. (2003). \"Coherent arbitrariness\": Stable demand curves without stable preferences. The Quarterly Journal of Economics, 118(1), 73–106.", note: "Experiments showing that arbitrary anchors shift what people are willing to pay while relative valuations stay coherent — the basis for anchoring in price presentation.", link: doi("10.1162/00335530360535153"), kind: "doi" },
      { cite: "Wansink, B., Kent, R. J., & Hoch, S. J. (1998). An anchoring and adjustment model of purchase quantity decisions. Journal of Marketing Research, 35(1), 71–81.", note: "Field and lab studies showing purchase-quantity limits and multiple-unit pricing act as anchors that increase the number of units shoppers buy.", link: doi("10.2307/3151931"), kind: "doi" },
      { cite: "Kim, J.-Y., Natter, M., & Spann, M. (2009). Pay what you want: A new participative pricing mechanism. Journal of Marketing, 73(1), 44–58.", note: "Field studies of pay-what-you-want pricing in restaurants, cinema and delicatessen settings; buyers paid positive prices, and revenues in some settings did not fall.", link: doi("10.1509/jmkg.73.1.044"), kind: "doi" },
      { cite: "Gneezy, A., Gneezy, U., Riener, G., & Nelson, L. D. (2012). Pay-what-you-want, identity, and self-signaling in markets. Proceedings of the National Academy of Sciences, 109(19), 7236–7240.", note: "Large field experiments on pay-what-you-want pricing; fewer people buy but they pay more, and pairing it with a charitable component raised revenue and giving together.", link: doi("10.1073/pnas.1120893109"), kind: "doi" },
    ],
  },
  {
    id: "gs-business-selling",
    goal: "business", tier: "fundamental", section: "8512",
    title: "Learn Adaptive Selling — It Is the Sales Skill That Predicts Results",
    subtitle: "Meta-analyses of salespeople show adapting to the customer beats scripted pitches and raises objective performance",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "weeks", durability: "sustained", effort: "moderate" },
    feeds: ["revenue", "customer understanding"],
    description:
      "Two large meta-analyses agree on what predicts sales performance. Churchill and colleagues' synthesis of 116 studies ranked role clarity, skill and motivation ahead of aptitude and personality; Verbeke, Dietz and Verwaal's contemporary meta-analysis found selling-related knowledge, adaptiveness and role ambiguity among the strongest drivers. Franke and Park's meta-analysis of 155 samples found adaptive selling behaviour raised self-rated, manager-rated and objective performance, while customer orientation raised only self-ratings. Spiro and Weitz's scale defines the skill: altering the approach across and during interactions based on the customer.",
    action: "For the next ten sales conversations, write down before each one what you expect the customer's situation to be, ask three diagnostic questions before presenting, and note afterwards what you changed in your pitch based on the answers.",
    sources: [
      { cite: "Verbeke, W., Dietz, B., & Verwaal, E. (2011). Drivers of sales performance: A contemporary meta-analysis. Have salespeople become knowledge brokers? Journal of the Academy of Marketing Science, 39(3), 407–428.", note: "Meta-analysis of drivers of sales performance; selling-related knowledge, adaptiveness, role ambiguity, cognitive aptitude and work engagement emerge as the strongest predictors.", link: doi("10.1007/s11747-010-0211-8"), kind: "doi" },
      { cite: "Franke, G. R., & Park, J.-E. (2006). Salesperson adaptive selling behavior and customer orientation: A meta-analysis. Journal of Marketing Research, 43(4), 693–702.", note: "Meta-analysis of 155 samples and more than 31,000 salespeople; adaptive selling increased self-rated, manager-rated and objective performance, whereas customer orientation increased only self-rated performance.", link: doi("10.1509/jmkr.43.4.693"), kind: "doi" },
      { cite: "Churchill, G. A., Jr., Ford, N. M., Hartley, S. W., & Walker, O. C., Jr. (1985). The determinants of salesperson performance: A meta-analysis. Journal of Marketing Research, 22(2), 103–118.", note: "Meta-analysis of 116 articles and 1,653 associations; role variables, skill and motivation had the largest average associations with performance, with aptitude and personal factors weaker.", link: doi("10.1177/002224378502200201"), kind: "doi" },
      { cite: "Spiro, R. L., & Weitz, B. A. (1990). Adaptive selling: Conceptualization, measurement, and nomological validity. Journal of Marketing Research, 27(1), 61–69.", note: "Defines and measures adaptive selling — changing sales behaviour during and across customer interactions based on perceived information — and relates it to performance.", link: doi("10.2307/3172551"), kind: "doi" },
    ],
  },
  {
    id: "gs-business-cash-flow-failure",
    goal: "business", tier: "fundamental", section: "8513",
    title: "Run a Weekly Cash Review",
    subtitle: "Small firms die young from thin capital, debt structure and external shocks — problems a weekly cash discipline can see coming",
    evidenceTag: "Moderate",
    impact: { magnitude: 4, latency: "weeks", durability: "sustained", effort: "low" },
    feeds: ["financial control", "early warning"],
    description:
      "Studies of small-firm failure point to the same mechanisms: under-capitalization and reliance on debt at start-up (Carter and Van Auken's bankruptcy study), external risk factors such as interest rates and economic conditions (Everett and Watson), and the sharply elevated exit hazard of young plants documented in plant-level data. Cressy's model explains why most firms die young: they start with too little financial and human capital to survive early shocks. A weekly cash review does not remove these risks but makes them visible weeks earlier.",
    action: "Every week, on the same day, update a one-page sheet with cash on hand, money owed to you by date, money you owe by date, and weeks of runway; act on anything under eight weeks before doing any other work that day.",
    sources: [
      { cite: "Carter, R., & Van Auken, H. (2006). Small firm bankruptcy. Journal of Small Business Management, 44(4), 493–512.", note: "Compares bankrupt and non-bankrupt small firms; lack of knowledge, inability to access capital and heavy debt at start-up were associated with bankruptcy.", link: doi("10.1111/j.1540-627X.2006.00187.x"), kind: "doi" },
      { cite: "Everett, J., & Watson, J. (1998). Small business failure and external risk factors. Small Business Economics, 11(4), 371–390.", note: "Examines how macroeconomic conditions such as interest rates, unemployment and retail activity relate to small-business failure rates over time.", link: doi("10.1023/A:1008065527282"), kind: "doi" },
      { cite: "Dunne, T., Roberts, M. J., & Samuelson, L. (1989). The growth and failure of U.S. manufacturing plants. The Quarterly Journal of Economics, 104(4), 671–698.", note: "Plant-level Census data show failure rates decline with plant age and size; the youngest and smallest entrants face the highest exit hazards.", link: doi("10.2307/2937862"), kind: "doi" },
      { cite: "Cressy, R. (2006). Why do most firms die young? Small Business Economics, 26(2), 103–116.", note: "Models the early-life failure hazard of firms as a function of initial financial and human capital and stochastic shocks, explaining the peak in exits in the first years.", link: doi("10.1007/s11187-004-7813-9"), kind: "doi" },
    ],
  },
  {
    id: "gs-business-financing",
    goal: "business", tier: "advanced", section: "8514",
    title: "Bootstrap First, Borrow Deliberately",
    subtitle: "Most new firms are funded by owner money and bank debt; bootstrapping techniques stretch capital, and small capital injections can earn high returns",
    evidenceTag: "Moderate",
    impact: { magnitude: 4, latency: "months", durability: "lasting", effort: "high" },
    feeds: ["capital efficiency", "financing judgment"],
    description:
      "Robb and Robinson's analysis of the Kauffman Firm Survey found that new U.S. firms rely heavily on formal debt — much of it bank credit backed by the owner — rather than on friends, family or equity, contrary to the folk pecking order. Cassar documents how firm and owner characteristics shape start-up financing. Winborg and Landström catalogue bootstrapping methods founders use to acquire resources without external finance. Randomized capital grants to microenterprises show that small injections of capital can earn high returns for constrained owners, though returns differed sharply between male and female owners.",
    action: "List every bootstrapping lever you have not yet used (customer prepayment, shared equipment, delayed owner salary, supplier terms), apply two this quarter, and only then price out the cheapest external option against the return you can document.",
    sources: [
      { cite: "Robb, A. M., & Robinson, D. T. (2014). The capital structure decisions of new firms. The Review of Financial Studies, 27(1), 153–179.", note: "Kauffman Firm Survey evidence that new firms rely heavily on external debt, especially bank financing, rather than on informal or insider sources.", link: doi("10.1093/rfs/hhs072"), kind: "doi" },
      { cite: "Cassar, G. (2004). The financing of business start-ups. Journal of Business Venturing, 19(2), 261–283.", note: "Examines determinants of start-up capital structure; firm size, asset structure and owner characteristics relate to the use of debt, bank finance and outside equity.", link: doi("10.1016/S0883-9026(03)00029-6"), kind: "doi" },
      { cite: "Winborg, J., & Landström, H. (2001). Financial bootstrapping in small businesses: Examining small business managers' resource acquisition behaviors. Journal of Business Venturing, 16(3), 235–254.", note: "Identifies clusters of bootstrapping behaviours — owner financing, minimizing receivables, sharing resources, delaying payments, subsidies — used to acquire resources without new external finance.", link: doi("10.1016/S0883-9026(99)00055-5"), kind: "doi" },
      { cite: "de Mel, S., McKenzie, D., & Woodruff, C. (2008). Returns to capital in microenterprises: Evidence from a field experiment. The Quarterly Journal of Economics, 123(4), 1329–1372.", note: "Randomized grants to Sri Lankan microenterprises; the estimated real return to capital was well above market interest rates, indicating capital constraints.", link: doi("10.1162/qjec.2008.123.4.1329"), kind: "doi" },
      { cite: "de Mel, S., McKenzie, D., & Woodruff, C. (2009). Are women more credit constrained? Experimental evidence on gender and microenterprise returns. American Economic Journal: Applied Economics, 1(3), 1–32.", note: "Follow-up randomized grants; profits rose for male owners but not female owners, and the gap was not explained by ability, risk aversion or reporting.", link: doi("10.1257/app.1.3.1"), kind: "doi" },
    ],
  },
  {
    id: "gs-business-franchising",
    goal: "business", tier: "elite", section: "8515",
    title: "Buying a Franchise — Check the Survival Evidence First",
    subtitle: "Franchise outlets do not reliably outlive independent start-ups; young franchisors themselves fail often",
    evidenceTag: "Mixed",
    impact: { magnitude: 2, latency: "months", durability: "lasting", effort: "high" },
    feeds: ["due diligence", "system thinking"],
    description:
      "The franchise sales pitch rests on lower failure rates, and the evidence is mixed. Bates's comparison using Census owner data found franchise start-ups did not enjoy higher survival than independent start-ups once other factors were considered. Shane's study of new franchisors found the hybrid organizational form helps young systems grow but many fail early. Kosová and Lafontaine's panel of franchised chains shows chain-level survival and growth vary widely with chain age and size. Treat the brochure's failure statistics as a claim to test.",
    action: "Before signing a franchise agreement, obtain the unit-level closure and transfer counts from the disclosure document for the last three years, call at least five current and three former franchisees, and compare the answers with independent alternatives in the same trade.",
    sources: [
      { cite: "Bates, T. (1995). A comparison of franchise and independent small business survival rates. Small Business Economics, 7(5), 377–388.", note: "Uses Census Characteristics of Business Owners data to compare young franchise and independent firms; franchising did not confer the survival advantage commonly claimed.", link: doi("10.1007/BF01302738"), kind: "doi" },
      { cite: "Shane, S. A. (1996). Hybrid organizational arrangements and their implications for firm growth and survival: A study of new franchisors. Academy of Management Journal, 39(1), 216–234.", note: "Longitudinal study of new franchisors; franchising helps young systems grow and survive relative to company-owned expansion, but new franchisor mortality is substantial.", link: doi("10.2307/256637"), kind: "doi" },
      { cite: "Kosová, R., & Lafontaine, F. (2010). Survival and growth in retail and service industries: Evidence from franchised chains. The Journal of Industrial Economics, 58(3), 542–578.", note: "Panel data on franchised chains in the United States; chain survival and growth depend strongly on chain age and size, with high early exit among young systems.", link: doi("10.1111/j.1467-6451.2010.00431.x"), kind: "doi" },
    ],
  },
  {
    id: "gs-business-digital-marketing",
    goal: "business", tier: "moderate", section: "8516",
    title: "Measure Ad Returns With a Holdout, Not a Dashboard",
    subtitle: "Large experiments show paid search often has near-zero incremental return for known brands and that ad ROI is very hard to measure",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "moderate" },
    feeds: ["marketing discipline", "measurement literacy"],
    description:
      "eBay's large field experiment found that paid search on the company's own brand terms had close to zero incremental effect because those users would have arrived anyway, and non-brand search worked mainly for new and infrequent users. Lewis and Rao's 25 experiments show why dashboards mislead: sales are so volatile relative to ad spend that confidence intervals on return are enormous, and observational methods suffer severe selection bias. Ghost-ads methods make cheaper experiments possible. Firm-generated social content did raise customer spending in one longitudinal study, and earned media had measurable but different effects from traditional media.",
    action: "For your next paid campaign, hold out a random group of customers or regions who see no ads, run it for at least four weeks, and compare sales between the two groups before deciding to scale.",
    sources: [
      { cite: "Blake, T., Nosko, C., & Tadelis, S. (2015). Consumer heterogeneity and paid search effectiveness: A large-scale field experiment. Econometrica, 83(1), 155–174.", note: "Controlled experiments at eBay; brand-keyword search ads had almost no measurable effect, and non-brand ads mainly influenced new or infrequent users, so average returns were far below what click data implied.", link: doi("10.3982/ECTA12423"), kind: "doi" },
      { cite: "Lewis, R. A., & Rao, J. M. (2015). The unfavorable economics of measuring the returns to advertising. The Quarterly Journal of Economics, 130(4), 1941–1973.", note: "Twenty-five large field experiments representing $2.8 million in digital advertising; the median confidence interval on return on investment was over 100 percentage points wide, and selection bias cripples observational methods.", link: doi("10.1093/qje/qjv023"), kind: "doi" },
      { cite: "Johnson, G. A., Lewis, R. A., & Nubbemeyer, E. I. (2017). Ghost ads: Improving the economics of measuring online ad effectiveness. Journal of Marketing Research, 54(6), 867–884.", note: "Introduces ghost ads, which identify the control-group users who would have been shown an ad, making ad experiments far more statistically efficient and cheaper.", link: doi("10.1509/jmr.15.0297"), kind: "doi" },
      { cite: "Kumar, A., Bezawada, R., Rishika, R., Janakiraman, R., & Kannan, P. K. (2016). From social to sale: The effects of firm-generated content in social media on customer behavior. Journal of Marketing, 80(1), 7–25.", note: "Links customers' social-media participation to transaction data; firm-generated content had a positive effect on spending, cross-buying and profitability after accounting for TV and e-mail marketing.", link: doi("10.1509/jm.14.0249"), kind: "doi" },
      { cite: "Stephen, A. T., & Galak, J. (2012). The effects of traditional and social earned media on sales: A study of a microlending marketplace. Journal of Marketing Research, 49(5), 624–639.", note: "Models daily sales on a microlending marketplace; traditional earned media had larger per-event effects, but social earned media occurred far more often and also drove sales.", link: doi("10.1509/jmr.09.0401"), kind: "doi" },
    ],
  },
  {
    id: "gs-business-founder-wellbeing",
    goal: "business", tier: "fundamental", section: "8517",
    title: "Protect the Founder — Sleep, Recovery and a Stress Budget",
    subtitle: "Entrepreneurs report high autonomy and wellbeing alongside elevated stress and mental-health risk; stress trades health for wealth",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "low" },
    feeds: ["energy", "decision quality", "persistence"],
    description:
      "Reviews of entrepreneurs' mental health describe a paradox: self-employment is associated with higher job satisfaction and eudaimonic wellbeing, mediated by autonomy and psychological functioning, yet founders also report high stress, and one U.S. study found elevated rates of psychiatric conditions among entrepreneurs and their families. Cardon and Patel's panel work found stress raised entrepreneurs' income while damaging their health — a trade-off that compounds. Recovery is a business input, not a luxury.",
    action: "Set a fixed weekly recovery block (one protected half-day plus a nightly sleep window) and a written 'stress budget' listing the two demands you will drop or delegate this month; review it with someone who will hold you to it.",
    sources: [
      { cite: "Stephan, U. (2018). Entrepreneurs' mental health and well-being: A review and research agenda. Academy of Management Perspectives, 32(3), 290–322.", note: "Reviews the literature on entrepreneurs' mental health; entrepreneurship brings both stressors and resources such as autonomy, and outcomes depend on how the two balance.", link: doi("10.5465/amp.2017.0001"), kind: "doi" },
      { cite: "Wiklund, J., Nikolaev, B., Shir, N., Foo, M.-D., & Bradley, S. (2019). Entrepreneurship and well-being: Past, present, and future. Journal of Business Venturing, 34(4), 579–588.", note: "Editorial review of the entrepreneurship–wellbeing literature that frames wellbeing as both an input and an outcome of venturing and sets a research agenda.", link: doi("10.1016/j.jbusvent.2019.01.002"), kind: "doi" },
      { cite: "Cardon, M. S., & Patel, P. C. (2015). Is stress worth it? Stress-related health and wealth trade-offs for entrepreneurs. Applied Psychology, 64(2), 379–420.", note: "Panel evidence that entrepreneurs' stress is associated with higher personal income but poorer physical health, with passion moderating the relationship.", link: doi("10.1111/apps.12021"), kind: "doi" },
      { cite: "Freeman, M. A., Staudenmaier, P. J., Zisser, M. R., & Andresen, L. A. (2019). The prevalence and co-occurrence of psychiatric conditions among entrepreneurs and their families. Small Business Economics, 53(2), 323–342.", note: "Survey comparing entrepreneurs with a comparison group; entrepreneurs and their families reported higher lifetime prevalence of several mental-health conditions.", link: doi("10.1007/s11187-018-0059-8"), kind: "doi" },
      { cite: "Nikolaev, B., Boudreaux, C. J., & Wood, M. (2020). Entrepreneurship and subjective well-being: The mediating role of psychological functioning. Entrepreneurship Theory and Practice, 44(3), 557–586.", note: "Panel data showing self-employment relates to higher subjective wellbeing largely through better psychological functioning such as autonomy and purpose.", link: doi("10.1177/1042258719830314"), kind: "doi" },
    ],
  },
  {
    id: "gs-business-grit-persistence",
    goal: "business", tier: "moderate", section: "8518",
    title: "Practice Perseverance on One Venture, Not Grit as a Trait",
    subtitle: "Grit predicts venture outcomes modestly and mostly through its perseverance component; the meta-analysis says it is largely conscientiousness",
    evidenceTag: "Mixed",
    impact: { magnitude: 2, latency: "months", durability: "sustained", effort: "moderate" },
    feeds: ["follow-through", "realistic self-assessment"],
    description:
      "Duckworth's grit construct — perseverance and passion for long-term goals — has been tested in entrepreneurs with modest results. Mueller, Wolfe and Syed found grit relates to venture success mainly through its perseverance facet and entrepreneurs' engagement; Wolfe and Patel's multi-country study links grit to self-employment entry. Credé, Tynan and Harms' meta-analysis found grit's overall predictive validity is small, that it overlaps heavily with conscientiousness, and that the perseverance facet does most of the work. Build the behaviour, not the identity.",
    action: "Choose one venture milestone for the next 90 days, break it into weekly deliverables, and track completion on a visible chart; treat a missed week as a scheduling problem to fix, not a character verdict.",
    sources: [
      { cite: "Duckworth, A. L., Peterson, C., Matthews, M. D., & Kelly, D. R. (2007). Grit: Perseverance and passion for long-term goals. Journal of Personality and Social Psychology, 92(6), 1087–1101.", note: "Introduces and validates the grit scale across six samples, relating it to educational attainment and retention beyond IQ and conscientiousness.", link: doi("10.1037/0022-3514.92.6.1087"), kind: "doi" },
      { cite: "Credé, M., Tynan, M. C., & Harms, P. D. (2017). Much ado about grit: A meta-analytic synthesis of the grit literature. Journal of Personality and Social Psychology, 113(3), 492–511.", note: "Meta-analysis finding grit's relation to performance and retention is modest, that grit is strongly correlated with conscientiousness, and that perseverance carries most of the validity.", link: doi("10.1037/pspp0000102"), kind: "doi" },
      { cite: "Mueller, B. A., Wolfe, M. T., & Syed, I. (2017). Passion and grit: An exploration of the pathways leading to venture success. Journal of Business Venturing, 32(3), 260–279.", note: "Survey of entrepreneurs; passion and grit relate to venture success through engagement and effort, with perseverance the more consistent pathway.", link: doi("10.1016/j.jbusvent.2017.02.001"), kind: "doi" },
      { cite: "Wolfe, M. T., & Patel, P. C. (2016). Grit and self-employment: A multi-country study. Small Business Economics, 47(4), 853–874.", note: "Multi-country survey data linking grit to the likelihood of being self-employed, with the relationship varying across national contexts.", link: doi("10.1007/s11187-016-9737-6"), kind: "doi" },
    ],
  },
  {
    id: "gs-business-myth-passion-optimism",
    goal: "business", tier: "moderate", section: "8519",
    title: "Myth: 'Follow Your Passion' and 'Believe in Yourself' Are Enough",
    subtitle: "Passion and optimism help you start; overconfidence and dispositional optimism are associated with worse venture performance",
    evidenceTag: "Mixed",
    impact: { magnitude: 1, latency: "months", durability: "transient", effort: "low" },
    callout: "Rated at the floor as a plan, not as a feeling. Entrepreneurial passion is real and measurable, but the review literature finds inconsistent effects and measurement problems, while studies of optimism and overconfidence find they drive entry into ventures with low expected returns and, past a point, reduce performance. Passion is fuel; it is not evidence.",
    description:
      "Cardon and colleagues defined entrepreneurial passion as intense positive feelings for identity-central activities and built a validated scale; Newman and colleagues' review of the field notes inconsistent theory, causal ambiguity and measurement fallacies. Meanwhile Cooper, Woo and Dunkelberg documented entrepreneurs' perceived chances of success far above observed base rates; Koellinger and colleagues link overconfidence to entry; Hmieleski and Baron found dispositional optimism negatively related to new-venture performance; Kraft and colleagues' meta-analysis separates types of overconfidence and their stage-specific effects; and Åstebro and colleagues review why people enter and persist despite low risk-adjusted returns.",
    action: "Write down your honest estimate of the probability your venture is still operating in five years and your expected first-year income; compare both with the base rates on this shelf and with what a skeptical friend estimates, and adjust your runway to the lower number.",
    sources: [
      { cite: "Cardon, M. S., Wincent, J., Singh, J., & Drnovsek, M. (2009). The nature and experience of entrepreneurial passion. Academy of Management Review, 34(3), 511–532.", note: "Theory paper defining entrepreneurial passion as intense positive feelings toward identity-central roles (inventing, founding, developing) and proposing its effects on effort and persistence.", link: doi("10.5465/amr.2009.40633190"), kind: "doi" },
      { cite: "Cardon, M. S., Gregoire, D. A., Stevens, C. E., & Patel, P. C. (2013). Measuring entrepreneurial passion: Conceptual foundations and scale validation. Journal of Business Venturing, 28(3), 373–396.", note: "Develops and validates a multidimensional entrepreneurial passion scale, showing passion is domain-specific rather than a single feeling of enthusiasm.", link: doi("10.1016/j.jbusvent.2012.03.003"), kind: "doi" },
      { cite: "Newman, A., Obschonka, M., Moeller, J., & Chandan, G. G. (2021). Entrepreneurial passion: A review, synthesis, and agenda for future research. Applied Psychology, 70(2), 816–860.", note: "Comprehensive review of empirical passion research; flags inconsistent theory use, limits on causal inference and measurement fallacies, and reviews antecedents and outcomes.", link: doi("10.1111/apps.12236"), kind: "doi" },
      { cite: "Cooper, A. C., Woo, C. Y., & Dunkelberg, W. C. (1988). Entrepreneurs' perceived chances for success. Journal of Business Venturing, 3(2), 97–108.", note: "Survey of new business owners; most rated their own odds of success far higher than the odds of similar businesses, an early demonstration of founder overoptimism.", link: doi("10.1016/0883-9026(88)90020-1"), kind: "doi" },
      { cite: "Hmieleski, K. M., & Baron, R. A. (2009). Entrepreneurs' optimism and new venture performance: A social cognitive perspective. Academy of Management Journal, 52(3), 473–488.", note: "Founders' dispositional optimism was negatively related to new-venture revenue and employment growth, especially in dynamic environments and for experienced founders.", link: doi("10.5465/amj.2009.41330755"), kind: "doi" },
      { cite: "Koellinger, P., Minniti, M., & Schade, C. (2007). \"I think I can, I think I can\": Overconfidence and entrepreneurial behavior. Journal of Economic Psychology, 28(4), 502–527.", note: "Cross-country data linking subjective confidence in one's skills to the decision to start a business, with confidence often exceeding what objective information supports.", link: doi("10.1016/j.joep.2006.11.002"), kind: "doi" },
      { cite: "Kraft, P. S., Günther, C., Kammerlander, N. H., & Lampe, J. (2022). Overconfidence and entrepreneurship: A meta-analysis of different types of overconfidence in the entrepreneurial process. Journal of Business Venturing, 37(4), 106207.", note: "Meta-analysis distinguishing overestimation, overplacement and overprecision; their effects differ across entry, funding and performance stages of the entrepreneurial process.", link: doi("10.1016/j.jbusvent.2022.106207"), kind: "doi" },
      { cite: "Åstebro, T., Herz, H., Nanda, R., & Weber, R. A. (2014). Seeking the roots of entrepreneurship: Insights from behavioral economics. Journal of Economic Perspectives, 28(3), 49–70.", note: "Reviews evidence that many entrepreneurs enter and persist despite low risk-adjusted returns, and weighs risk preferences, overconfidence and non-pecuniary tastes as explanations.", link: doi("10.1257/jep.28.3.49"), kind: "doi" },
    ],
  },
  {
    id: "gs-business-myth-ten-thousand-hours",
    goal: "business", tier: "moderate", section: "8520",
    title: "Myth: 10,000 Hours of Practice Makes the Founder",
    subtitle: "Deliberate practice explains a minority of performance variance even in music and games, and under 1 percent in professions",
    evidenceTag: "Strong",
    impact: { magnitude: 1, latency: "months", durability: "transient", effort: "high" },
    callout: "Rated at the floor. The '10,000-hour rule' is a popularization of Ericsson's deliberate-practice studies of musicians; the meta-analysis of the whole literature found practice explained 26 percent of performance variance in games, 21 percent in music, 18 percent in sports, 4 percent in education and less than 1 percent in professions. For founders, task-related human capital and prior venture success matter, but there is no hours threshold that produces a good business.",
    description:
      "Ericsson, Krampe and Tesch-Römer proposed that expert performance is largely explained by accumulated deliberate practice. Macnamara, Hambrick and Oswald's meta-analysis across domains found deliberate practice important but far less so than claimed, with the smallest effects in professions. In entrepreneurship, Unger and colleagues' meta-analysis found human capital relates to success modestly, more so for task-related knowledge and skills than for years of experience or schooling, and Colombo and Grilli found founders' specific education and work experience relate to new-firm growth. Put your hours into deliberate tests of the business, not into a mythical apprenticeship count.",
    action: "Replace any 'hours logged' target with a monthly count of completed experiments, customer conversations and revenue-generating actions, and review which of those three moved the business.",
    sources: [
      { cite: "Ericsson, K. A., Krampe, R. T., & Tesch-Römer, C. (1993). The role of deliberate practice in the acquisition of expert performance. Psychological Review, 100(3), 363–406.", note: "The foundational deliberate-practice study of musicians that the '10,000-hour rule' popularized; it argued accumulated deliberate practice distinguishes expert levels.", link: doi("10.1037/0033-295X.100.3.363"), kind: "doi" },
      { cite: "Macnamara, B. N., Hambrick, D. Z., & Oswald, F. L. (2014). Deliberate practice and performance in music, games, sports, education, and professions: A meta-analysis. Psychological Science, 25(8), 1608–1618.", note: "Meta-analysis across domains; deliberate practice explained 26% of performance variance for games, 21% for music, 18% for sports, 4% for education and less than 1% for professions.", link: doi("10.1177/0956797614535810"), kind: "doi" },
      { cite: "Unger, J. M., Rauch, A., Frese, M., & Rosenbusch, N. (2011). Human capital and entrepreneurial success: A meta-analytical review. Journal of Business Venturing, 26(3), 341–358.", note: "Meta-analysis of human capital and entrepreneurial success; the relationship is modest overall and stronger for task-related knowledge and skills than for schooling or years of experience.", link: doi("10.1016/j.jbusvent.2009.09.004"), kind: "doi" },
      { cite: "Colombo, M. G., & Grilli, L. (2005). Founders' human capital and the growth of new technology-based firms: A competence-based view. Research Policy, 34(6), 795–816.", note: "Founders' specific education and prior work experience in the same sector relate to the growth of new technology-based firms, while generic experience matters less.", link: doi("10.1016/j.respol.2005.03.010"), kind: "doi" },
    ],
  },
];
