// Goal shelf: EDUCATION & CAREER — graduate college and find the right career (sections 8700–8799).
// Verification: every DOI below was resolved against the Crossref record or the
// PubMed record on 2026-09-11. See types.ts for the contract. Popular advice the
// evidence does not support is rated at the floor (magnitude 1) with a callout.
// Nothing here is academic, financial, legal or medical advice; each note describes
// what the cited study tested.
import { doi, type GoalShelfCluster } from "./types";

export const SECTIONS: Record<string, string> = {
  "8700": "How to Read This Shelf",
  "8701": "Belonging & Integration — Why Students Leave, and the Brief Interventions That Keep Them",
  "8702": "Study Technique — Retrieval Practice, Spacing and Interleaving",
  "8703": "Myth — Highlighting and Rereading as Study Methods",
  "8704": "Sleep and Grades — Duration, Regularity and the Energy-Drink Trap",
  "8705": "Procrastination — What Actually Moves the Needle",
  "8706": "Growth Mindset — What the Meta-Analyses Actually Show",
  "8707": "First-Generation Students — Difference-Education, Values and Utility-Value Writing",
  "8708": "Money — FAFSA, Aid Simplification, Nudges and Incentives",
  "8709": "Comprehensive Support Programs — CUNY ASAP and Its Relatives",
  "8710": "Community-College Transfer — Credits Are the Bottleneck",
  "8711": "Imposter Phenomenon — Prevalence, Measurement and What Helps",
  "8712": "Deliberate Practice — Building Real Skill",
  "8713": "Interest Fit — Holland RIASEC and Career Choice",
  "8714": "Myth — 'Follow Your Passion' as a Fixed Thing to Find",
  "8715": "Job Crafting — Reshaping the Job You Have",
  "8716": "Mentoring — What Protégés Actually Gain",
  "8717": "Internships and Early Labour-Market Outcomes",
  "8718": "Weak Ties — Networks, Job Search and the LinkedIn Experiment",
  "8719": "Interview Performance — Structure, First Impressions and Coaching",
  "8720": "Salary Negotiation — Who Asks, Who Receives, and Anchoring",
  "8721": "Faculty-Mentored Undergraduate Research",
  "8722": "Sponsors and the Developmental Network",
};

export const CLUSTERS: GoalShelfCluster[] = [
  {
    id: "gs-education-career-read-me-first",
    goal: "education-career", tier: "fundamental", section: "8700",
    title: "How to Read the College & Career Shelf",
    subtitle: "Protocols, not diagnoses — pick one per tier each month",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "low" },
    description:
      "Every protocol on this shelf is tagged fundamental, moderate, advanced or elite and carries a concrete action step. The monthly menu hands you one or two from each tier. The two best-replicated predictors of college grades are unglamorous — showing up to class and the quality of study habits — so start there before adding anything psychological or expensive.",
    action: "This month, pick the one fundamental protocol on this shelf you are not already doing and run it for 30 days before adding anything else.",
    sources: [
      { cite: "Credé, M., Roch, S. G., & Kieszczynka, U. M. (2010). Class attendance in college: A meta-analytic review of the relationship of class attendance with grades and student characteristics. Review of Educational Research, 80(2), 272–295.", note: "Across k = 69 studies (N = 21,195) attendance correlated ρ = .44 with class grades and ρ = .41 with GPA (k = 33, N = 9,243) — a better predictor of college grades than SAT scores, high-school GPA or study skills, and largely independent of them.", link: doi("10.3102/0034654310362998"), kind: "doi" },
      { cite: "Richardson, M., Abraham, C., & Bond, R. (2012). Psychological correlates of university students' academic performance: A systematic review and meta-analysis. Psychological Bulletin, 138(2), 353–387.", note: "The largest synthesis of psychological correlates of university GPA; the shelf's psychology sections draw on the constructs it ranks, with self-efficacy and effort regulation among the strongest.", link: doi("10.1037/a0026838"), kind: "doi" },
    ],
  },
  {
    id: "gs-education-career-belonging",
    goal: "education-career", tier: "fundamental", section: "8701",
    title: "Get Integrated — One Professor, One Group, One Belonging Story",
    subtitle: "Faculty contact outside class and a normalised transition predict staying",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "weeks", durability: "lasting", effort: "low" },
    feeds: ["persistence", "help-seeking", "first-year completion"],
    description:
      "Tinto's synthesis and the models that followed it explain dropout as a failure of academic and social integration rather than of ability, and early longitudinal work found informal student–faculty contact beyond the classroom predicted freshman persistence. The brief social-belonging intervention — reading older students' stories that worry about fitting in is normal and passes, then writing your own — raised minority students' GPA and health over three years in the original trial and, in a 22-institution randomised experiment with 26,911 students, increased full-time first-year completion, most for groups that historically progressed at lower rates. The honest boundary: the 2023 trial found the effect only where the institution actually afforded opportunities to belong.",
    action: "In your first month each term, attend one office hour with one professor and join one campus group; when you doubt you fit, write for 15 minutes about how the doubt is common and temporary.",
    sources: [
      { cite: "Tinto, V. (1975). Dropout from higher education: A theoretical synthesis of recent research. Review of Educational Research, 45(1), 89–125.", note: "The foundational model: voluntary withdrawal follows from insufficient integration into the academic and social systems of the college, not from ability alone.", link: doi("10.3102/00346543045001089"), kind: "doi" },
      { cite: "Pascarella, E. T., & Terenzini, P. T. (1977). Patterns of student-faculty informal interaction beyond the classroom and voluntary freshman attrition. The Journal of Higher Education, 48(5), 540–552.", note: "Early evidence that the amount and kind of informal contact with faculty outside class predicted which freshmen stayed.", link: doi("10.1080/00221546.1977.11776573"), kind: "doi" },
      { cite: "Bean, J. P. (1980). Dropouts and turnover: The synthesis and test of a causal model of student attrition. Research in Higher Education, 12(2), 155–187.", note: "A causal model of attrition adapted from employee-turnover research and tested on students, adding institutional commitment as the proximal driver of leaving.", link: doi("10.1007/bf00976194"), kind: "doi" },
      { cite: "Walton, G. M., & Cohen, G. L. (2007). A question of belonging: Race, social fit, and achievement. Journal of Personality and Social Psychology, 92(1), 82–96.", note: "Introduced belonging uncertainty and showed that a brief intervention framing social adversity as common and transient improved Black students' achievement.", link: doi("10.1037/0022-3514.92.1.82"), kind: "doi" },
      { cite: "Walton, G. M., & Cohen, G. L. (2011). A brief social-belonging intervention improves academic and health outcomes of minority students. Science, 331(6023), 1447–1451.", note: "A one-hour intervention in the first year raised Black students' GPA over three years and improved self-reported health and well-being.", link: doi("10.1126/science.1198364"), kind: "doi" },
      { cite: "Walton, G. M., Murphy, M. C., Logel, C., Yeager, D. S., Goyer, J. P., Brady, S. T., et al. (2023). Where and with whom does a brief social-belonging intervention promote progress in college? Science, 380(6644), 499–505.", note: "Randomised experiment with 26,911 students at 22 institutions: an online pre-college belonging intervention under 30 minutes increased full-time first-year completion, especially for historically lower-progressing groups, but only where the context afforded opportunities to belong.", link: doi("10.1126/science.ade4420"), kind: "doi" },
      { cite: "Broda, M., Yun, J., Schneider, B., Yeager, D. S., Walton, G. M., & Diemer, M. (2018). Reducing inequality in academic success for incoming college students: A randomized trial of growth mindset and belonging interventions. Journal of Research on Educational Effectiveness, 11(3), 317–338.", note: "A randomised trial with incoming students at a large public university comparing belonging and mindset messages delivered before arrival; effects were concentrated in specific subgroups rather than universal.", link: doi("10.1080/19345747.2018.1429037"), kind: "doi" },
    ],
  },
  {
    id: "gs-education-career-retrieval-spacing",
    goal: "education-career", tier: "fundamental", section: "8702",
    title: "Test Yourself, Space It Out, Mix the Problems",
    subtitle: "Practice testing and distributed practice — the two techniques rated high utility",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "weeks", durability: "lasting", effort: "moderate" },
    feeds: ["retention", "transfer", "exam performance"],
    description:
      "Dunlosky and colleagues reviewed ten study techniques and rated only two as high utility — practice testing and distributed (spaced) practice — with interleaving rated moderate. Repeated free recall of a prose passage beat repeated rereading on tests a week later even though rereading felt more effective; retrieval practice beat concept mapping on later inference questions; a meta-analysis of practice testing confirmed it outperforms restudying and every other comparison. Spacing effects are robust across hundreds of verbal-recall experiments, and interleaving different kinds of maths problems improved later test performance in classroom experiments. The boundary: benefits show up on delayed tests, so the techniques feel worse in the moment.",
    action: "For each course, close the notes and write out everything you can recall after every study session, review the same material again 2–3 days later and a week later, and mix problem types within each practice set rather than doing them in blocks.",
    sources: [
      { cite: "Dunlosky, J., Rawson, K. A., Marsh, E. J., Nathan, M. J., & Willingham, D. T. (2013). Improving students' learning with effective learning techniques: Promising directions from cognitive and educational psychology. Psychological Science in the Public Interest, 14(1), 4–58.", note: "Monograph rating ten techniques: practice testing and distributed practice received high utility; interleaving, elaborative interrogation and self-explanation moderate; highlighting, rereading, summarisation, keyword mnemonic and imagery low.", link: doi("10.1177/1529100612453266"), kind: "doi" },
      { cite: "Roediger, H. L., III, & Karpicke, J. D. (2006). Test-enhanced learning: Taking memory tests improves long-term retention. Psychological Science, 17(3), 249–255.", note: "Students who took free-recall tests on prose passages retained substantially more at 2 days and 1 week than students who restudied, even though restudying raised their confidence more.", link: doi("10.1111/j.1467-9280.2006.01693.x"), kind: "doi" },
      { cite: "Karpicke, J. D., & Blunt, J. R. (2011). Retrieval practice produces more learning than elaborative studying with concept mapping. Science, 331(6018), 772–775.", note: "Retrieval practice produced better performance on later verbatim and inference questions than concept mapping, including when students built concept maps with the text in front of them.", link: doi("10.1126/science.1199327"), kind: "doi" },
      { cite: "Cepeda, N. J., Pashler, H., Vul, E., Wixted, J. T., & Rohrer, D. (2006). Distributed practice in verbal recall tasks: A review and quantitative synthesis. Psychological Bulletin, 132(3), 354–380.", note: "Quantitative synthesis of the spacing literature in verbal recall: spaced study reliably beats massed study, with the optimal gap growing as the retention interval grows.", link: doi("10.1037/0033-2909.132.3.354"), kind: "doi" },
      { cite: "Rohrer, D., & Taylor, K. (2007). The shuffling of mathematics problems improves learning. Instructional Science, 35(6), 481–498.", note: "Shuffling (interleaving) practice problems across types, rather than blocking them, improved performance on a later test.", link: doi("10.1007/s11251-007-9015-8"), kind: "doi" },
      { cite: "Rohrer, D., Dedrick, R. F., & Burgess, K. (2014). The benefit of interleaved mathematics practice is not limited to superficially similar kinds of problems. Psychonomic Bulletin & Review, 21(5), 1323–1330.", note: "Classroom experiment showing the interleaving benefit held even when the mixed problem types did not look alike, so learners practise choosing the strategy, not just executing it.", link: doi("10.3758/s13423-014-0588-3"), kind: "doi" },
      { cite: "Adesope, O. O., Trevisan, D. A., & Sundararajan, N. (2017). Rethinking the use of tests: A meta-analysis of practice testing. Review of Educational Research, 87(3), 659–701.", note: "Meta-analysis finding practice tests more beneficial for learning than restudying and all other comparison conditions, with effects moderated by test format and feedback.", link: doi("10.3102/0034654316689306"), kind: "doi" },
    ],
  },
  {
    id: "gs-education-career-myth-highlighting",
    goal: "education-career", tier: "fundamental", section: "8703",
    title: "Myth: Highlighting and Rereading Are How You Study",
    subtitle: "The two most popular techniques were rated low utility",
    evidenceTag: "Strong",
    impact: { magnitude: 1, latency: "days", durability: "transient", effort: "low" },
    callout: "Rated at the floor as advice: highlighting and rereading were rated low utility in the Dunlosky review because they rarely improve later performance and can hurt it on inference questions; study-skill inventories based on the depth-of-processing perspective were the least predictive of grades. Time spent highlighting is time not spent on retrieval and spacing.",
    description:
      "Students overwhelmingly report highlighting and rereading, and both feel productive because the text becomes familiar. The evidence rates them low utility: highlighting does little for later recall, students' metacognitive beliefs about it are miscalibrated, and rereading produces fluency rather than durable memory. Popular strategies can be salvaged only when reworked into something that forces retrieval — for example, turning highlights into self-test questions.",
    action: "Retire the highlighter. Replace each highlighting session with a closed-book recall of the section and three self-written test questions you answer 48 hours later.",
    sources: [
      { cite: "Dunlosky, J., Rawson, K. A., Marsh, E. J., Nathan, M. J., & Willingham, D. T. (2013). Improving students' learning with effective learning techniques: Promising directions from cognitive and educational psychology. Psychological Science in the Public Interest, 14(1), 4–58.", note: "Highlighting and rereading were selected for review precisely because students rely on them, and both received a low-utility assessment.", link: doi("10.1177/1529100612453266"), kind: "doi" },
      { cite: "Yue, C. L., Storm, B. C., Kornell, N., & Bjork, E. L. (2015). Highlighting and its relation to distributed study and students' metacognitive beliefs. Educational Psychology Review, 27(1), 69–78.", note: "Experiments on highlighting during study found students' beliefs about its value poorly matched its actual effect on later test performance.", link: doi("10.1007/s10648-014-9277-z"), kind: "doi" },
      { cite: "Miyatsu, T., Nguyen, K., & McDaniel, M. A. (2018). Five popular study strategies: Their pitfalls and optimal implementations. Perspectives on Psychological Science, 13(3), 390–407.", note: "Reviews why rereading, highlighting, note-taking, outlining and flashcards underperform as typically used, and how each can be re-implemented to force retrieval and spacing.", link: doi("10.1177/1745691617710510"), kind: "doi" },
      { cite: "Credé, M., & Kuncel, N. R. (2008). Study habits, skills, and attitudes: The third pillar supporting collegiate academic performance. Perspectives on Psychological Science, 3(6), 425–453.", note: "Meta-analysis (N = 72,431, k = 344): scores on inventories based on the popular depth-of-processing perspective were the least predictive of grades, while traditional study-habit and motivation measures were the most predictive.", link: doi("10.1111/j.1745-6924.2008.00089.x"), kind: "doi" },
    ],
  },
  {
    id: "gs-education-career-sleep",
    goal: "education-career", tier: "fundamental", section: "8704",
    title: "Protect Nightly Sleep in the First Six Weeks of Term",
    subtitle: "Duration and regularity over the month before an exam, not the night before",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "moderate" },
    feeds: ["memory consolidation", "GPA", "mood"],
    description:
      "With wearable trackers in a college chemistry course, better quality, longer and more consistent sleep over the month and week before a test tracked higher grades, while sleep the single night before did not; sleep measures accounted for close to a quarter of the variance in performance. Across five actigraphy studies of first-year students at three universities, each extra hour of average nightly sleep early in the term predicted a 0.07 higher end-of-term GPA after controlling for prior GPA, with under six hours the point where sleep turned from helpful to harmful. Irregular sleep–wake timing was linked to delayed circadian rhythms and lower performance. The boundary: most of this is observational, and in medical students the link ran through sleep quality rather than hours.",
    action: "For the first six weeks of the term, keep a fixed wake time seven days a week and protect at least seven hours in bed; if you use energy drinks to study, replace them with a 20-minute earlier bedtime.",
    sources: [
      { cite: "Okano, K., Kaczmarzyk, J. R., Dave, N., Gabrieli, J. D. E., & Grossman, J. C. (2019). Sleep quality, duration, and consistency are associated with better academic performance in college students. npj Science of Learning, 4, 16.", note: "In 88 students wearing activity trackers, sleep quality, duration and consistency over the preceding month and week correlated with better grades and explained nearly 25% of the variance; sleep the night before a test did not.", link: doi("10.1038/s41539-019-0055-z"), kind: "doi" },
      { cite: "Creswell, J. D., Tumminia, M. J., Price, S., Sefidgar, Y., Cohen, S., Ren, Y., et al. (2023). Nightly sleep duration predicts grade point average in the first year of college. Proceedings of the National Academy of Sciences, 120(8), e2209123120.", note: "Five actigraphy studies at three universities: each additional hour of average nightly sleep early in the term was associated with a 0.07 higher end-of-term GPA, controlling for previous GPA; below six hours was the harmful zone.", link: doi("10.1073/pnas.2209123120"), kind: "doi" },
      { cite: "Phillips, A. J. K., Clerx, W. M., O'Brien, C. S., Sano, A., Barger, L. K., Picard, R. W., et al. (2017). Irregular sleep/wake patterns are associated with poorer academic performance and delayed circadian and sleep/wake timing. Scientific Reports, 7, 3216.", note: "In 61 undergraduates followed for 30 days, a sleep regularity index correlated r = 0.37 with academic performance, and irregular sleepers had later melatonin onset.", link: doi("10.1038/s41598-017-03171-4"), kind: "doi" },
      { cite: "Lund, H. G., Reider, B. D., Whiting, A. B., & Prichard, J. R. (2010). Sleep patterns and predictors of disturbed sleep in a large population of college students. Journal of Adolescent Health, 46(2), 124–132.", note: "Of 1,125 students, more than 60% were poor-quality sleepers; tension and stress explained 24% of the variance in sleep quality, and poor sleepers reported more physical and psychological problems.", link: doi("10.1016/j.jadohealth.2009.06.016"), kind: "doi" },
      { cite: "Seoane, H. A., Moschetto, L., Orliacq, F., Orliacq, J., Serrano, E., Cazenave, M. I., et al. (2020). Sleep disruption in medicine students and its relationship with impaired academic performance: A systematic review and meta-analysis. Sleep Medicine Reviews, 53, 101333.", note: "Across 41 papers, grades correlated with sleep quality (r = 0.15) and inversely with daytime sleepiness, but not with sleep duration — the honest caveat that quality and regularity matter alongside hours.", link: doi("10.1016/j.smrv.2020.101333"), kind: "doi" },
      { cite: "Champlin, S. E., Pasch, K. E., & Perry, C. L. (2016). Is the consumption of energy drinks associated with academic achievement among college students? The Journal of Primary Prevention, 37(4), 345–359.", note: "Among 844 first-year undergraduates, greater energy-drink consumption was associated with lower GPA even after controlling for sleep, stress and alcohol use.", link: doi("10.1007/s10935-016-0437-4"), kind: "doi" },
    ],
  },
  {
    id: "gs-education-career-procrastination",
    goal: "education-career", tier: "moderate", section: "8705",
    title: "Treat Procrastination as a Self-Regulation Problem, Not a Character Flaw",
    subtitle: "Implementation intentions, then an 8–10 week CBT-style program if it is severe",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "moderate" },
    feeds: ["task initiation", "deadline compliance", "well-being"],
    description:
      "Steel's meta-analytic review frames procrastination as a quintessential self-regulatory failure driven by task aversiveness, delay and impulsiveness. Intervention studies pooled in a meta-analysis show procrastination can be reduced, with cognitive-behavioural approaches the best supported. Two randomised trials of CBT for procrastination found moderate-to-large effects delivered online with or without a therapist, and a pragmatic trial in university students found group CBT held its gains at six months better than self-guided online treatment. Implementation intentions — 'when X, I will Y' plans — carry a medium-to-large effect on goal attainment across a large meta-analysis. The boundary: bedtime procrastination is a separate problem that eats the sleep the previous cluster protects.",
    action: "Write an if-then plan for the first ten minutes of each assignment ('When I sit down after lunch on Tuesday, I will open the file and write the first paragraph'). If you still lose whole weeks, enrol in an 8-week CBT-based procrastination course or group.",
    sources: [
      { cite: "Steel, P. (2007). The nature of procrastination: A meta-analytic and theoretical review of quintessential self-regulatory failure. Psychological Bulletin, 133(1), 65–94.", note: "Meta-analytic review establishing task aversiveness, delay of reward, low self-efficacy and impulsiveness as the strongest correlates of procrastination.", link: doi("10.1037/0033-2909.133.1.65"), kind: "doi" },
      { cite: "van Eerde, W., & Klingsieck, K. B. (2018). Overcoming procrastination? A meta-analysis of intervention studies. Educational Research Review, 25, 73–85.", note: "Meta-analysis of intervention studies showing procrastination can be reduced, with cognitive-behavioural interventions among the most effective.", link: doi("10.1016/j.edurev.2018.09.002"), kind: "doi" },
      { cite: "Rozental, A., Forsell, E., Svensson, A., Andersson, G., & Carlbring, P. (2015). Internet-based cognitive-behavior therapy for procrastination: A randomized controlled trial. Journal of Consulting and Clinical Psychology, 83(4), 808–824.", note: "150 participants randomised to guided self-help, unguided self-help or wait-list: between-group effects on the Pure Procrastination Scale were d = 0.70 (guided) and d = 0.50 (unguided), with 31–40% achieving clinically significant change.", link: doi("10.1037/ccp0000023"), kind: "doi" },
      { cite: "Rozental, A., Forsström, D., Lindner, P., Nilsson, S., Mårtensson, L., Rizzo, A., Andersson, G., & Carlbring, P. (2018). Treating procrastination using cognitive behavior therapy: A pragmatic randomized controlled trial comparing treatment delivered via the internet or in groups. Behavior Therapy, 49(2), 180–197.", note: "92 university students with severe procrastination: large within-group effects for internet CBT (d = 1.29) and group CBT (d = 1.24); group participants maintained gains at six months while some self-guided participants deteriorated.", link: doi("10.1016/j.beth.2017.08.002"), kind: "doi" },
      { cite: "Zacks, S., & Hen, M. (2018). Academic interventions for academic procrastination: A review of the literature. Journal of Prevention & Intervention in the Community, 46(2), 117–130.", note: "Review concluding that academic procrastination is best understood as a situational and self-regulation failure, and that interventions should target both.", link: doi("10.1080/10852352.2016.1198154"), kind: "doi" },
      { cite: "Kroese, F. M., De Ridder, D. T. D., Evers, C., & Adriaanse, M. A. (2014). Bedtime procrastination: Introducing a new area of procrastination. Frontiers in Psychology, 5, 611.", note: "In a community sample of 177 adults, bedtime procrastination was associated with lower self-regulation and predicted insufficient sleep beyond demographics — the bridge between this cluster and the sleep cluster.", link: doi("10.3389/fpsyg.2014.00611"), kind: "doi" },
      { cite: "Gollwitzer, P. M., & Sheeran, P. (2006). Implementation intentions and goal achievement: A meta-analysis of effects and processes. Advances in Experimental Social Psychology, 38, 69–119.", note: "Meta-analysis of implementation-intention studies showing 'if-then' plans have a medium-to-large effect on goal attainment by automating the start of intended action.", link: doi("10.1016/s0065-2601(06)38002-1"), kind: "doi" },
    ],
  },
  {
    id: "gs-education-career-growth-mindset",
    goal: "education-career", tier: "moderate", section: "8706",
    title: "Growth Mindset — Small, Targeted, Not a Cure",
    subtitle: "Weak average effects; real but modest gains for lower-achieving students in supportive classrooms",
    evidenceTag: "Mixed",
    impact: { magnitude: 2, latency: "weeks", durability: "sustained", effort: "low" },
    callout: "Rated honestly, not at the floor: two meta-analyses (k = 273, N = 365,915 for the correlation; k = 43, N = 57,155 for interventions) found overall effects weak, and a later systematic review found the apparent benefits shrank further when study quality was accounted for. The one large pre-registered national experiment found a short online mindset program raised grades among lower-achieving adolescents, but only where peer norms supported challenge-seeking. Treat it as a cheap add-on for a struggling student, not a program to build a semester around.",
    description:
      "The claim that believing intelligence is malleable transforms achievement does not survive the meta-analyses: correlations with achievement are small and intervention effects are weak on average. Yet the best-designed trial — a one-hour online intervention delivered to a national sample of 9th graders — did raise grades for lower-achieving students, and design-thinking revisions of the intervention improved it. The defensible use is narrow and specific: when a student is struggling and in an environment that rewards effort.",
    action: "If you are behind in a course, spend one hour reading and writing about how the brain builds skill through effortful practice, then pair it with the retrieval-practice protocol — and do not expect the belief alone to change your grade.",
    sources: [
      { cite: "Sisk, V. F., Burgoyne, A. P., Sun, J., Butler, J. L., & Macnamara, B. N. (2018). To what extent and under which circumstances are growth mind-sets important to academic achievement? Two meta-analyses. Psychological Science, 29(4), 549–571.", note: "First meta-analysis (k = 273, N = 365,915) on the mindset–achievement relationship and second (k = 43, N = 57,155) on interventions: overall effects were weak, with some support for benefits among low-SES or academically at-risk students.", link: doi("10.1177/0956797617739704"), kind: "doi" },
      { cite: "Macnamara, B. N., & Burgoyne, A. P. (2023). Do growth mindset interventions impact students' academic achievement? A systematic review and meta-analysis with recommendations for best practices. Psychological Bulletin, 149(3–4), 133–173.", note: "Systematic review and meta-analysis concluding that apparent effects of growth-mindset interventions on achievement are small and attenuated once study quality and potential bias are considered.", link: doi("10.1037/bul0000352"), kind: "doi" },
      { cite: "Burnette, J. L., Billingsley, J., Banks, G. C., Knouse, L. E., Hoyt, C. L., Pollack, J. M., & Simon, S. (2023). A systematic review and meta-analysis of growth mindset interventions: For whom, how, and why might such interventions work? Psychological Bulletin, 149(3–4), 174–205.", note: "A companion meta-analysis reaching a more optimistic reading: small overall effects with larger effects for targeted, at-risk groups and when the intervention includes specific implementation features.", link: doi("10.1037/bul0000368"), kind: "doi" },
      { cite: "Yeager, D. S., Hanselman, P., Walton, G. M., Murray, J. S., Crosnoe, R., Muller, C., et al. (2019). A national experiment reveals where a growth mindset improves achievement. Nature, 573(7774), 364–369.", note: "Pre-registered national experiment: a short online growth-mindset intervention improved grades among lower-achieving 9th-graders, with effects depending on whether peer norms supported challenge-seeking.", link: doi("10.1038/s41586-019-1466-y"), kind: "doi" },
      { cite: "Yeager, D. S., Romero, C., Paunesku, D., Hulleman, C. S., Schneider, B., Hinojosa, C., et al. (2016). Using design thinking to improve psychological interventions: The case of the growth mindset during the transition to high school. Journal of Educational Psychology, 108(3), 374–391.", note: "Iterative user-centred redesign of the mindset intervention improved its effects on grades among lower-achieving students in the transition to high school.", link: doi("10.1037/edu0000098"), kind: "doi" },
      { cite: "Yeager, D. S., & Walton, G. M. (2011). Social-psychological interventions in education: They're not magic. Review of Educational Research, 81(2), 267–301.", note: "The review that set expectations for brief interventions: they work through recursive processes in specific contexts and are not stand-alone fixes.", link: doi("10.3102/0034654311405999"), kind: "doi" },
    ],
  },
  {
    id: "gs-education-career-first-generation",
    goal: "education-career", tier: "moderate", section: "8707",
    title: "First-Generation and Under-Represented Students — Name the Difference, Write the Value",
    subtitle: "Difference-education panels, values affirmation and utility-value writing",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "weeks", durability: "lasting", effort: "low" },
    feeds: ["help-seeking", "grades in gateway courses", "sense of fit"],
    description:
      "Three brief writing- or panel-based interventions have randomised evidence for closing social-class and racial gaps. A one-hour difference-education panel, in which senior students explained how their backgrounds shaped their college experience, improved first-generation students' end-of-year GPA and their use of college resources. Values-affirmation writing reduced the gender gap in a college physics course and the racial gap among seventh-graders, with effects persisting. Utility-value writing — repeatedly explaining how course material connects to your own life — closed the achievement gap for first-generation and under-represented students in introductory biology. The boundary: these are cheap and specific, work best early, and depend on the course actually giving something to connect to.",
    action: "In the first two weeks of a gateway course, write for 15 minutes about which of your values matter most and why; then, before each major unit, write half a page on how the material is useful in your own life or future work.",
    sources: [
      { cite: "Stephens, N. M., Hamedani, M. G., & Destin, M. (2014). Closing the social-class achievement gap: A difference-education intervention improves first-generation students' academic performance and all students' college transition. Psychological Science, 25(4), 943–953.", note: "A one-hour panel in which senior students discussed how social-class background shaped their college experience eliminated the first-generation GPA gap at year's end and increased resource-seeking.", link: doi("10.1177/0956797613518349"), kind: "doi" },
      { cite: "Harackiewicz, J. M., Canning, E. A., Tibbetts, Y., Giffen, C. J., Blair, S. S., Rouse, D. I., & Hyde, J. S. (2014). Closing the social class achievement gap for first-generation students in undergraduate biology. Journal of Educational Psychology, 106(2), 375–389.", note: "A values-affirmation intervention in an introductory biology course improved first-generation students' grades and retention in the course sequence.", link: doi("10.1037/a0034679"), kind: "doi" },
      { cite: "Harackiewicz, J. M., Canning, E. A., Tibbetts, Y., Priniski, S. J., & Hyde, J. S. (2016). Closing achievement gaps with a utility-value intervention: Disentangling race and social class. Journal of Personality and Social Psychology, 111(5), 745–765.", note: "Utility-value writing assignments in introductory biology closed the achievement gap for first-generation under-represented minority students.", link: doi("10.1037/pspp0000075"), kind: "doi" },
      { cite: "Miyake, A., Kost-Smith, L. E., Finkelstein, N. D., Pollock, S. J., Cohen, G. L., & Ito, T. A. (2010). Reducing the gender achievement gap in college science: A classroom study of values affirmation. Science, 330(6008), 1234–1237.", note: "A brief values-affirmation writing exercise reduced the gender gap in an undergraduate physics course on exam scores and a standardised test.", link: doi("10.1126/science.1195996"), kind: "doi" },
      { cite: "Cohen, G. L., Garcia, J., Apfel, N., & Master, A. (2006). Reducing the racial achievement gap: A social-psychological intervention. Science, 313(5791), 1307–1310.", note: "Two randomised field experiments: a brief in-class values-affirmation assignment improved African American students' grades and reduced the racial achievement gap by 40%.", link: doi("10.1126/science.1128317"), kind: "doi" },
    ],
  },
  {
    id: "gs-education-career-money-aid",
    goal: "education-career", tier: "moderate", section: "8708",
    title: "File the FAFSA, Read the Aid Letter, Answer the Summer Texts",
    subtitle: "Complexity and uncertainty about cost are the barriers the experiments removed",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "months", durability: "lasting", effort: "low" },
    feeds: ["enrolment", "persistence", "debt avoidance"],
    description:
      "Randomised evidence shows the money barrier is often an information and paperwork barrier. Helping families complete the FAFSA during tax preparation raised college enrolment and aid receipt; a guaranteed, early, unconditional free-tuition offer to low-income high-achievers in Michigan more than doubled application and enrolment at the flagship even though most would have qualified for the same aid anyway; personalised summer text messages reduced 'summer melt' among college-intending low-income graduates. Performance-based incentives tied to credit completion raised achievement in one quasi-experiment. The boundary: these are US policy experiments about access; none replaces a completed degree plan.",
    action: "File the FAFSA in the first month it opens each year, reply to every message from your college's financial-aid and advising offices within 48 hours, and ask the aid office in writing for the total net cost for the coming year before the semester starts.",
    sources: [
      { cite: "Bettinger, E. P., Long, B. T., Oreopoulos, P., & Sanbonmatsu, L. (2012). The role of application assistance and information in college decisions: Results from the H&R Block FAFSA experiment. The Quarterly Journal of Economics, 127(3), 1205–1242.", note: "Randomised trial in which tax professionals helped low-income families complete the FAFSA: assistance raised aid applications, college enrolment and aid receipt; information alone did not.", link: doi("10.1093/qje/qjs017"), kind: "doi" },
      { cite: "Dynarski, S., Libassi, C. J., Michelmore, K., & Owen, S. (2021). Closing the gap: The effect of reducing complexity and uncertainty in college pricing on the choices of low-income students. American Economic Review, 111(6), 1721–1756.", note: "Randomised offer of guaranteed free tuition at the University of Michigan to low-income high achievers more than doubled application and enrolment rates, without changing the aid they were already eligible for.", link: doi("10.1257/aer.20200451"), kind: "doi" },
      { cite: "Castleman, B. L., & Page, L. C. (2015). Summer nudging: Can personalized text messages and peer mentor outreach increase college going among low-income high school graduates? Journal of Economic Behavior & Organization, 115, 144–160.", note: "Randomised trials of summer text-message reminders and peer-mentor outreach increased college enrolment among low-income, college-intending high-school graduates.", link: doi("10.1016/j.jebo.2014.12.008"), kind: "doi" },
      { cite: "Scott-Clayton, J. (2011). On money and motivation: A quasi-experimental analysis of financial incentives for college achievement. Journal of Human Resources, 46(3), 614–646.", note: "Quasi-experimental analysis of a merit scholarship with credit and GPA requirements: the performance incentive raised credits completed and GPA among eligible students.", link: doi("10.1353/jhr.2011.0013"), kind: "doi" },
      { cite: "Page, L. C., & Scott-Clayton, J. (2016). Improving college access in the United States: Barriers and policy responses. Economics of Education Review, 51, 4–22.", note: "Review of the evidence on informational, financial and behavioural barriers to college access and the policy responses with experimental support.", link: doi("10.1016/j.econedurev.2016.02.009"), kind: "doi" },
    ],
  },
  {
    id: "gs-education-career-asap",
    goal: "education-career", tier: "elite", section: "8709",
    title: "Enrol Full-Time in a Comprehensive Support Program (ASAP-Style)",
    subtitle: "Required full-time enrolment, intensive advising, tuition waiver and transport — for three years",
    evidenceTag: "Strong",
    impact: { magnitude: 5, latency: "months", durability: "lasting", effort: "high" },
    feeds: ["degree completion", "credit accumulation", "transfer to four-year college"],
    description:
      "CUNY's Accelerated Study in Associate Programs bundles requirements and supports — full-time enrolment, frequent advising, tutoring, a tuition gap waiver, free transit and textbooks — for up to three years. The randomised evaluation found it nearly doubled three-year graduation rates, and the long-term follow-up published in AEJ: Applied showed the effect on degree completion persisted at six years, with more students transferring to four-year colleges. Financial incentives tied to enrolment intensity, and simplifying the money, work in the same direction. This is the elite move because it is a multi-year commitment, not a tip; the boundary is eligibility — it requires being at a participating college and enrolling full-time.",
    action: "Before registering, ask your college whether it runs an ASAP-model or other comprehensive support program; if it does, enrol full-time in it and keep every advising appointment for the length of the program.",
    sources: [
      { cite: "Weiss, M. J., Ratledge, A., Sommo, C., & Gupta, H. (2019). Supporting community college students from start to degree completion: Long-term evidence from a randomized trial of CUNY's ASAP. American Economic Journal: Applied Economics, 11(3), 253–297.", note: "Long-term randomised evidence that ASAP's bundle of requirements and supports substantially increased degree completion, with effects persisting through six years.", link: doi("10.1257/app.20170430"), kind: "doi" },
      { cite: "Scott-Clayton, J. (2011). On money and motivation: A quasi-experimental analysis of financial incentives for college achievement. Journal of Human Resources, 46(3), 614–646.", note: "Evidence that aid tied to credit completion and GPA changes behaviour, the mechanism ASAP's full-time requirement leans on.", link: doi("10.1353/jhr.2011.0013"), kind: "doi" },
      { cite: "Bettinger, E. P., Long, B. T., Oreopoulos, P., & Sanbonmatsu, L. (2012). The role of application assistance and information in college decisions: Results from the H&R Block FAFSA experiment. The Quarterly Journal of Economics, 127(3), 1205–1242.", note: "Hands-on help with the paperwork — not information alone — moved enrolment, the same logic as ASAP's intensive advising.", link: doi("10.1093/qje/qjs017"), kind: "doi" },
      { cite: "Page, L. C., & Scott-Clayton, J. (2016). Improving college access in the United States: Barriers and policy responses. Economics of Education Review, 51, 4–22.", note: "Places comprehensive programs alongside simplification and nudges in the evidence on what actually raises access and completion.", link: doi("10.1016/j.econedurev.2016.02.009"), kind: "doi" },
    ],
  },
  {
    id: "gs-education-career-transfer",
    goal: "education-career", tier: "moderate", section: "8710",
    title: "Transferring from Community College — Protect Every Credit",
    subtitle: "Successful transfers finish at the same rate as native four-year students; lost credits are the gap",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "months", durability: "lasting", effort: "moderate" },
    feeds: ["bachelor's completion", "time to degree", "cost"],
    description:
      "Using national transcript data and propensity-score methods, students who begin at a community college are less likely to earn a bachelor's degree, but those who successfully transfer complete at rates equal to similar students who started at four-year colleges. The mechanism is credit loss: only about 58% of transfers bring 90% or more of their credits, and those who do are 2.5 times more likely to finish than those who lose more than half. Articulation policies were designed to prevent credit loss rather than raise transfer rates, and propensity-matched comparisons of transfers and rising juniors show similar attainment. The boundary: employment and stopping out after the second year also drive the divergence.",
    action: "Before you take any course at a community college, confirm in writing with the four-year college you intend to attend that the course counts toward your major, and keep a running credit map you check every term.",
    sources: [
      { cite: "Monaghan, D. B., & Attewell, P. (2015). The community college route to the bachelor's degree. Educational Evaluation and Policy Analysis, 37(1), 70–91.", note: "National transcript study: transfers who succeed graduate at the same rate as four-year starters; widespread credit loss after transfer is a major mechanism, and the greater the loss the lower the odds of a BA.", link: doi("10.3102/0162373714521865"), kind: "doi" },
      { cite: "Roksa, J., & Keith, B. (2008). Credits, time, and attainment: Articulation policies and success after transfer. Educational Evaluation and Policy Analysis, 30(3), 236–254.", note: "Articulation policies aim to prevent credit loss rather than raise transfer rates; evaluated on attainment, time to degree and credits required, using the National Education Longitudinal Study.", link: doi("10.3102/0162373708321383"), kind: "doi" },
      { cite: "Melguizo, T., Kienzl, G. S., & Alfonso, M. (2011). Comparing the educational attainment of community college transfer students and four-year college rising juniors using propensity score matching methods. The Journal of Higher Education, 82(3), 265–291.", note: "Propensity-matched comparison finding transfer students and native rising juniors reached similar educational attainment.", link: doi("10.1080/00221546.2011.11777202"), kind: "doi" },
      { cite: "Long, B. T., & Kurlaender, M. (2009). Do community colleges provide a viable pathway to a baccalaureate degree? Educational Evaluation and Policy Analysis, 31(1), 30–53.", note: "Ohio data showing a penalty in bachelor's completion for starting at a community college even after extensive controls — the honest counterweight to the transfer-success finding.", link: doi("10.3102/0162373708327756"), kind: "doi" },
      { cite: "Wang, X. (2009). Baccalaureate attainment and college persistence of community college transfer students at four-year institutions. Research in Higher Education, 50(6), 570–588.", note: "National longitudinal analysis of which transfer students persist and complete at four-year institutions, with community-college GPA and intent among the predictors.", link: doi("10.1007/s11162-009-9133-z"), kind: "doi" },
    ],
  },
  {
    id: "gs-education-career-imposter",
    goal: "education-career", tier: "moderate", section: "8711",
    title: "Imposter Phenomenon — Measure It, Name It, Find a Mentor",
    subtitle: "Common, measurable, tied to burnout; no treatment trials yet, so lean on what is associated with less of it",
    evidenceTag: "Moderate",
    impact: { magnitude: 2, latency: "weeks", durability: "sustained", effort: "low" },
    feeds: ["self-assessment accuracy", "persistence in demanding programs", "burnout prevention"],
    description:
      "First described by Clance and Imes in high-achieving women, imposter phenomenon is the persistent belief that one's success is undeserved. A systematic review of 62 studies (14,161 participants) found prevalence from 9% to 82% depending on the instrument, comorbidity with depression and anxiety, links to impaired performance and burnout — and no published treatment evaluations. Reviews of medical trainees put prevalence at 22–47%, roughly twice as high in women. What is associated with less of it in the data: mentorship and time in role. A workshop that measured it and taught mitigation strategies was rated useful by 96% of first-year medical students, but that is satisfaction, not outcome data. The boundary: everything here is observational.",
    action: "Take the Clance Impostor Phenomenon Scale once, tell one trusted mentor or peer your score and what triggers it, and keep a dated list of concrete things you did well that you reread before evaluations.",
    sources: [
      { cite: "Clance, P. R., & Imes, S. A. (1978). The imposter phenomenon in high achieving women: Dynamics and therapeutic intervention. Psychotherapy: Theory, Research & Practice, 15(3), 241–247.", note: "The original clinical description of the imposter phenomenon and the therapeutic approaches its authors used.", link: doi("10.1037/h0086006"), kind: "doi" },
      { cite: "Bravata, D. M., Watts, S. A., Keefer, A. L., Madhusudhan, D. K., Taylor, K. T., Clark, D. M., et al. (2020). Prevalence, predictors, and treatment of impostor syndrome: A systematic review. Journal of General Internal Medicine, 35(4), 1252–1275.", note: "62 studies, 14,161 participants: prevalence 9–82% depending on tool and cut-off, comorbid with depression and anxiety, associated with impaired performance and burnout; no published studies evaluated treatments.", link: doi("10.1007/s11606-019-05364-1"), kind: "doi" },
      { cite: "Mak, K. K. L., Kleitman, S., & Abbott, M. J. (2019). Impostor phenomenon measurement scales: A systematic review. Frontiers in Psychology, 10, 671.", note: "Systematic review of the available measurement scales and their psychometric support, with the Clance scale the most widely used.", link: doi("10.3389/fpsyg.2019.00671"), kind: "doi" },
      { cite: "Thomas, M., & Bigatti, S. (2020). Perfectionism, impostor phenomenon, and mental health in medicine: A literature review. International Journal of Medical Education, 11, 201–213.", note: "Across 16 studies of medical students, residents and physicians, imposter prevalence ranged from 22.5% to 46.6%, higher in women, with negative mental-health associations.", link: doi("10.5116/ijme.5f54.c8f8"), kind: "doi" },
      { cite: "Villwock, J. A., Sobin, L. B., Koester, L. A., & Harris, T. M. (2016). Impostor syndrome and burnout among American medical students: A pilot study. International Journal of Medical Education, 7, 364–369.", note: "In 138 medical students, 49.4% of women and 23.7% of men screened positive, and imposter syndrome was associated with exhaustion, cynicism and depersonalisation.", link: doi("10.5116/ijme.5801.eac4"), kind: "doi" },
      { cite: "Salari, N., Hashemian, S. H., Hosseinian-Far, A., Fallahi, A., Heidarian, P., Rasoulpoor, S., & Mohammadi, M. (2025). Global prevalence of imposter syndrome in health service providers: A systematic review and meta-analysis. BMC Psychology, 13, 571.", note: "Meta-analysis of 30 studies (11,483 people): pooled prevalence 62%, with self-esteem, anxiety, depression, stress and burnout the most important associated factors.", link: doi("10.1186/s40359-025-02898-4"), kind: "doi" },
      { cite: "Wrench, A., Padilla, M., O'Malley, C., & Levy, A. (2024). Impostor phenomenon: Prevalence among 1st year medical students and strategies for mitigation. Heliyon, 10(8), e29478.", note: "A 60-minute workshop with 50 first-year medical students: 40% screened positive, and 95.8% agreed the session identified risk factors and provided mitigation strategies — satisfaction data, not an outcome trial.", link: doi("10.1016/j.heliyon.2024.e29478"), kind: "doi" },
      { cite: "Halgas, B., Horton, J., & Cancio, L. (2024). Impostor phenomenon among recently graduated general surgeons. The American Surgeon, 90(11), 2994–2998.", note: "Among 24 recently graduated surgeons, those who participated in mentorship were less likely to report significant or intense imposterism.", link: doi("10.1177/00031348241259040"), kind: "doi" },
    ],
  },
  {
    id: "gs-education-career-deliberate-practice",
    goal: "education-career", tier: "advanced", section: "8712",
    title: "Deliberate Practice with a Coach — For the Skill Your Career Turns On",
    subtitle: "Designed, feedback-rich, effortful practice on the specific weakness, not more hours",
    evidenceTag: "Moderate",
    impact: { magnitude: 4, latency: "months", durability: "lasting", effort: "high" },
    feeds: ["professional skill", "performance under evaluation", "expertise"],
    description:
      "Ericsson's theory holds that expert performance is built by deliberate practice: individualised training designed by a teacher, immediate feedback, and repetition on tasks just beyond current ability. The honest debate: a meta-analysis found deliberate practice explained 26% of performance variance in games, 21% in music, 18% in sports, 4% in education and under 1% in professions — important but not sufficient — while Ericsson's re-analysis argued the meta-analysis used a broadened definition and that the original criteria explain far more. For a career, the practical reading is that unstructured experience is a weak teacher and that designed practice with feedback on a specific sub-skill is what moves professional performance.",
    action: "Pick the one skill your next promotion or admission depends on, find a coach or expert willing to give immediate feedback, and run three 45-minute sessions a week for three months on the specific sub-skill you are worst at.",
    sources: [
      { cite: "Ericsson, K. A., Krampe, R. T., & Tesch-Römer, C. (1993). The role of deliberate practice in the acquisition of expert performance. Psychological Review, 100(3), 363–406.", note: "The foundational paper defining deliberate practice and arguing that accumulated practice designed by teachers, with feedback and full concentration, accounts for expert performance.", link: doi("10.1037/0033-295X.100.3.363"), kind: "doi" },
      { cite: "Macnamara, B. N., Hambrick, D. Z., & Oswald, F. L. (2014). Deliberate practice and performance in music, games, sports, education, and professions: A meta-analysis. Psychological Science, 25(8), 1608–1618.", note: "Meta-analysis: deliberate practice explained 26% of performance variance in games, 21% in music, 18% in sports, 4% in education and under 1% in professions — important, but not as important as claimed.", link: doi("10.1177/0956797614535810"), kind: "doi" },
      { cite: "Ericsson, K. A., & Harwell, K. W. (2019). Deliberate practice and proposed limits on the effects of practice on the acquisition of expert performance: Why the original definition matters and recommendations for future research. Frontiers in Psychology, 10, 2396.", note: "Re-analysis arguing the 2014 meta-analysis used a broader definition; restricting to studies meeting the original criteria raised explained variance to 29% (61% after attenuation correction).", link: doi("10.3389/fpsyg.2019.02396"), kind: "doi" },
      { cite: "Ericsson, K. A. (2008). Deliberate practice and acquisition of expert performance: A general overview. Academic Emergency Medicine, 15(11), 988–994.", note: "Overview noting only a weak relationship between length of experience or reputation and observed performance, and describing the feedback-rich practice that does improve it.", link: doi("10.1111/j.1553-2712.2008.00227.x"), kind: "doi" },
      { cite: "Ericsson, K. A. (2004). Deliberate practice and the acquisition and maintenance of expert performance in medicine and related domains. Academic Medicine, 79(10 Suppl), S70–S81.", note: "Applies the expert-performance framework to professional training, where routine practice plateaus and designed practice is needed to keep improving.", link: doi("10.1097/00001888-200410001-00022"), kind: "doi" },
      { cite: "Ericsson, K. A., Nandagopal, K., & Roring, R. W. (2009). Toward a science of exceptional achievement: Attaining superior performance through deliberate practice. Annals of the New York Academy of Sciences, 1172, 199–217.", note: "Argues that elite performance among healthy individuals can be accounted for by sustained deliberate practice, motivation, support and access to good training environments rather than innate talent.", link: doi("10.1196/annals.1393.001"), kind: "doi" },
    ],
  },
  {
    id: "gs-education-career-interest-fit",
    goal: "education-career", tier: "moderate", section: "8713",
    title: "Choose by Interest Fit — Take a RIASEC Inventory and Match the Environment",
    subtitle: "Congruence between your interests and the field predicts performance, persistence and income",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "months", durability: "lasting", effort: "moderate" },
    feeds: ["major choice", "job satisfaction", "persistence"],
    description:
      "Holland's theory classifies people and work environments into Realistic, Investigative, Artistic, Social, Enterprising and Conventional types and predicts better outcomes when they match. A meta-analysis spanning 60 years (60 studies, about 568 correlations) found interests predict performance and persistence in work and school, and that person–environment congruence indices predict performance more strongly than interest scores alone; a follow-up re-analysis confirmed the congruence effect. Interest–major congruence predicted college persistence and timely graduation in a large longitudinal study; interest fit is a consistent correlate of job satisfaction in meta-analysis; and interests measured at the end of high school predicted income and life outcomes ten years later over and above IQ and personality. The boundary: fit is a probability shifter, not a guarantee, and interests keep developing.",
    action: "Take a validated RIASEC interest inventory this month, list the three-letter code of your intended major and of two alternative careers, and if your code and the field's code share fewer than two letters, interview two people working in a closer-matching field before you commit.",
    sources: [
      { cite: "Holland, J. L. (1959). A theory of vocational choice. Journal of Counseling Psychology, 6(1), 35–45.", note: "The original statement of the person–environment typology that became the RIASEC model used in most modern interest inventories.", link: doi("10.1037/h0040767"), kind: "doi" },
      { cite: "Nye, C. D., Su, R., Rounds, J., & Drasgow, F. (2012). Vocational interests and performance: A quantitative summary of over 60 years of research. Perspectives on Psychological Science, 7(4), 384–403.", note: "Meta-analysis of 60 studies and about 568 correlations: interests predict performance and persistence in work and academic settings, and congruence indices are more predictive than interest scores alone.", link: doi("10.1177/1745691612449021"), kind: "doi" },
      { cite: "Nye, C. D., Su, R., Rounds, J., & Drasgow, F. (2017). Interest congruence and performance: Revisiting recent meta-analytic findings. Journal of Vocational Behavior, 98, 138–151.", note: "Re-examination confirming that interest–environment congruence predicts performance, addressing methodological criticisms of the earlier synthesis.", link: doi("10.1016/j.jvb.2016.11.002"), kind: "doi" },
      { cite: "Hoff, K. A., Song, Q. C., Wee, C. J. M., Phan, W. M. J., & Rounds, J. (2020). Interest fit and job satisfaction: A systematic review and meta-analysis. Journal of Vocational Behavior, 123, 103503.", note: "Meta-analysis establishing a consistent positive relationship between interest fit and job satisfaction, with the size depending on how fit is measured.", link: doi("10.1016/j.jvb.2020.103503"), kind: "doi" },
      { cite: "Tracey, T. J. G., & Robbins, S. B. (2006). The interest–major congruence and college success relation: A longitudinal study. Journal of Vocational Behavior, 69(1), 64–89.", note: "Large longitudinal study linking congruence between measured interests and college major to persistence and academic success.", link: doi("10.1016/j.jvb.2005.11.003"), kind: "doi" },
      { cite: "Rounds, J., & Su, R. (2014). The nature and power of interests. Current Directions in Psychological Science, 23(2), 98–103.", note: "Reviews evidence that interests are stable, predict choice, performance and persistence, and are underused in guidance.", link: doi("10.1177/0963721414522812"), kind: "doi" },
      { cite: "Stoll, G., Rieger, S., Lüdtke, O., Nagengast, B., Trautwein, U., & Roberts, B. W. (2017). Vocational interests assessed at the end of high school predict life outcomes assessed 10 years later over and above IQ and Big Five personality traits. Journal of Personality and Social Psychology, 113(1), 167–184.", note: "In a large German cohort, RIASEC interests at the end of high school predicted income, employment and relationship outcomes a decade later beyond IQ and personality.", link: doi("10.1037/pspp0000117"), kind: "doi" },
    ],
  },
  {
    id: "gs-education-career-myth-follow-passion",
    goal: "education-career", tier: "fundamental", section: "8714",
    title: "Myth: 'Find Your Passion' — Passion Is Developed, Not Discovered",
    subtitle: "A fixed theory of interest makes people give up when a field gets hard",
    evidenceTag: "Strong",
    impact: { magnitude: 1, latency: "weeks", durability: "transient", effort: "low" },
    callout: "Rated at the floor as advice: in five studies, people who believed interests are fixed ('found') showed less interest outside their existing area and were more likely to lose interest when a new topic became difficult; people who believed interests develop stayed engaged. Grit's popular version — perseverance alone — predicts performance only weakly (meta-analytic ρ about .18) and partly because it overlaps with conscientiousness; it predicts better when passion is measured as something attained. 'Follow your passion' as a search for a pre-existing fit is the version the data do not support.",
    description:
      "The evidence points the other way from the slogan: implicit theories of interest matter. Believing you must find the one thing you are passionate about narrows exploration and predicts abandoning a field at the first hard patch, whereas a 'develop it' theory sustains interest through difficulty. A 'fit' theory of passion for work has similar costs. Grit research shows perseverance and passion must both be present to predict performance, and that passion is attained in a domain over time. The protocol is therefore to build interest in a promising, reasonably congruent field rather than wait to discover a calling.",
    action: "Stop asking 'is this my passion?' For the next 90 days ask 'am I getting better and more curious?' — commit to one field that fits your interest profile, track weekly skill gains, and only reconsider after the first hard stretch is behind you.",
    sources: [
      { cite: "O'Keefe, P. A., Dweck, C. S., & Walton, G. M. (2018). Implicit theories of interest: Finding your passion or developing it? Psychological Science, 29(10), 1653–1664.", note: "Five studies: a fixed theory of interest predicted less openness to new areas and, when a topic became difficult, a sharper drop in interest than a growth theory.", link: doi("10.1177/0956797618780643"), kind: "doi" },
      { cite: "Chen, P., Ellsworth, P. C., & Schwarz, N. (2015). Finding a fit or developing it: Implicit theories about achieving passion for work. Personality and Social Psychology Bulletin, 41(10), 1411–1424.", note: "People holding a 'fit' theory of work passion expected passion to be present from the start, while 'develop' theorists expected it to grow; both groups reported comparable passion, but the fit theory shaped how they chose and evaluated work.", link: doi("10.1177/0146167215596988"), kind: "doi" },
      { cite: "Jachimowicz, J. M., Wihler, A., Bailey, E. R., & Galinsky, A. D. (2018). Why grit requires perseverance and passion to positively predict performance. Proceedings of the National Academy of Sciences, 115(40), 9980–9985.", note: "Meta-analysis of 127 studies (n = 45,485) plus an employee study (n = 422) and a student study (n = 248): grit predicted performance better where participants were passionate for the domain, and the combination of perseverance with attained passion predicted job performance and GPA.", link: doi("10.1073/pnas.1803561115"), kind: "doi" },
      { cite: "Credé, M., Tynan, M. C., & Harms, P. D. (2017). Much ado about grit: A meta-analytic synthesis of the grit literature. Journal of Personality and Social Psychology, 113(3), 492–511.", note: "Meta-analytic synthesis finding grit only modestly related to performance and retention and strongly overlapping with conscientiousness, with perseverance the more useful facet.", link: doi("10.1037/pspp0000102"), kind: "doi" },
      { cite: "Duckworth, A. L., Peterson, C., Matthews, M. D., & Kelly, D. R. (2007). Grit: Perseverance and passion for long-term goals. Journal of Personality and Social Psychology, 92(6), 1087–1101.", note: "The original grit studies, which defined the construct as perseverance and passion for long-term goals and reported incremental prediction of retention and achievement.", link: doi("10.1037/0022-3514.92.6.1087"), kind: "doi" },
    ],
  },
  {
    id: "gs-education-career-job-crafting",
    goal: "education-career", tier: "moderate", section: "8715",
    title: "Craft the Job You Have — Tasks, Relationships, Meaning",
    subtitle: "A structured 4–6 week job-crafting plan raises engagement and performance modestly",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "moderate" },
    feeds: ["work engagement", "job satisfaction", "person–job fit"],
    description:
      "Job crafting is the self-initiated reshaping of task boundaries, relationships and the meaning of work. A validated scale distinguishes increasing structural resources, increasing social resources, increasing challenging demands and decreasing hindering demands; a meta-analysis of 122 independent samples links crafting to engagement, satisfaction and performance, with decreasing hindering demands the exception. Intervention studies — typically a workshop plus a personal crafting plan executed over several weeks — show small positive effects on engagement and performance in a meta-analysis. The boundary: effects are modest, self-reported in many studies, and cutting demands can backfire.",
    action: "This month, write a one-page crafting plan: add one task that uses a strength, seek one new relationship or feedback source, take on one stretch challenge, and review the plan with your manager; run it for six weeks.",
    sources: [
      { cite: "Wrzesniewski, A., & Dutton, J. E. (2001). Crafting a job: Revisioning employees as active crafters of their work. The Academy of Management Review, 26(2), 179–201.", note: "The theory paper introducing job crafting as changing task, relational and cognitive boundaries to alter the meaning and identity of work.", link: doi("10.2307/259118"), kind: "doi" },
      { cite: "Tims, M., Bakker, A. B., & Derks, D. (2012). Development and validation of the job crafting scale. Journal of Vocational Behavior, 80(1), 173–186.", note: "Validated the four-dimension job-crafting scale used in most later intervention and meta-analytic work.", link: doi("10.1016/j.jvb.2011.05.009"), kind: "doi" },
      { cite: "Rudolph, C. W., Katz, I. M., Lavigne, K. N., & Zacher, H. (2017). Job crafting: A meta-analysis of relationships with individual differences, job characteristics, and work outcomes. Journal of Vocational Behavior, 102, 112–138.", note: "Meta-analysis of 122 independent samples relating job crafting to engagement, satisfaction and performance, with decreasing hindering demands showing weaker or negative relations.", link: doi("10.1016/j.jvb.2017.05.008"), kind: "doi" },
      { cite: "Oprea, B. T., Barzin, L., Vîrgă, D., Iliescu, D., & Rusu, A. (2019). Effectiveness of job crafting interventions: A meta-analysis and utility analysis. European Journal of Work and Organizational Psychology, 28(6), 723–741.", note: "Meta-analysis of job-crafting interventions finding small positive effects on work engagement and performance, with a utility analysis of the return.", link: doi("10.1080/1359432x.2019.1646728"), kind: "doi" },
      { cite: "van Wingerden, J., Bakker, A. B., & Derks, D. (2017). Fostering employee well-being via a job crafting intervention. Journal of Vocational Behavior, 100, 164–174.", note: "Quasi-experimental intervention: a workshop plus a personal crafting plan increased job-crafting behaviour and well-being relative to controls.", link: doi("10.1016/j.jvb.2017.03.008"), kind: "doi" },
    ],
  },
  {
    id: "gs-education-career-mentoring",
    goal: "education-career", tier: "advanced", section: "8716",
    title: "Get a Mentor — and Ask for Career Functions, Not Just Support",
    subtitle: "Mentored people earn more and advance faster; informal mentors and career-focused help matter most",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "months", durability: "lasting", effort: "moderate" },
    feeds: ["promotion", "compensation", "career satisfaction"],
    description:
      "Meta-analyses find mentored individuals report higher compensation, more promotions and greater career satisfaction than non-mentored peers, with career-related mentoring functions (sponsorship, exposure, coaching) more strongly tied to objective outcomes and psychosocial functions to satisfaction. A multidisciplinary meta-analysis found benefits across youth, academic and workplace mentoring, larger for behavioural and attitudinal than objective outcomes; the largest interdisciplinary synthesis adds that protégé perceptions of instrumental and psychosocial support both predict outcomes. Informal mentors provided more career development than formally assigned ones in a classic comparison. The boundary: effect sizes are modest and much of the evidence is correlational.",
    action: "Identify one person two steps ahead of you whose work you admire, ask for a 30-minute monthly conversation, and bring a specific career question each time — a decision you face, a skill to build, a name you need.",
    sources: [
      { cite: "Allen, T. D., Eby, L. T., Poteet, M. L., Lentz, E., & Lima, L. (2004). Career benefits associated with mentoring for protégés: A meta-analysis. Journal of Applied Psychology, 89(1), 127–136.", note: "Meta-analysis: mentored protégés reported higher compensation, more promotions and greater career and job satisfaction, with career mentoring more tied to objective outcomes than psychosocial mentoring.", link: doi("10.1037/0021-9010.89.1.127"), kind: "doi" },
      { cite: "Eby, L. T., Allen, T. D., Evans, S. C., Ng, T., & DuBois, D. L. (2008). Does mentoring matter? A multidisciplinary meta-analysis comparing mentored and non-mentored individuals. Journal of Vocational Behavior, 72(2), 254–267.", note: "Across youth, academic and workplace mentoring, mentored individuals showed better behavioural, attitudinal, health, relational, motivational and career outcomes, with small-to-moderate effects.", link: doi("10.1016/j.jvb.2007.04.005"), kind: "doi" },
      { cite: "Eby, L. T. de T., Allen, T. D., Hoffman, B. J., Baranik, L. E., Sauer, J. B., Baldwin, S., et al. (2013). An interdisciplinary meta-analysis of the potential antecedents, correlates, and consequences of protégé perceptions of mentoring. Psychological Bulletin, 139(2), 441–476.", note: "Large interdisciplinary meta-analysis of protégé-perceived instrumental and psychosocial support and their antecedents and consequences across mentoring types.", link: doi("10.1037/a0029279"), kind: "doi" },
      { cite: "Kammeyer-Mueller, J. D., & Judge, T. A. (2008). A quantitative review of mentoring research: Test of a model. Journal of Vocational Behavior, 72(3), 269–283.", note: "Meta-analytic model test finding mentoring's links to salary and promotion are modest once individual differences such as ability and personality are accounted for.", link: doi("10.1016/j.jvb.2007.09.006"), kind: "doi" },
    ],
  },
  {
    id: "gs-education-career-internships",
    goal: "education-career", tier: "advanced", section: "8717",
    title: "Do a Real Internship Before You Graduate",
    subtitle: "Résumé audits show internship experience raises interview callbacks",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "months", durability: "lasting", effort: "high" },
    feeds: ["callbacks", "early employment", "realistic expectations"],
    description:
      "Two field experiments sent fictitious résumés of recent graduates to real job openings. In a US audit across majors, internship experience raised the interview callback rate substantially, and the effect was larger than that of choice of major for many business openings; in a European audit, a student internship on the résumé also increased positive employer responses. Reviews of business internships find realistic expectations, satisfaction and employment prospects improve. The boundary: audits measure callbacks, not job quality, and unpaid internships select on who can afford them.",
    action: "Secure at least one internship in your intended field before your final year; if paid options are scarce, ask your department for credit-bearing placements and treat the internship as a 10-week interview.",
    sources: [
      { cite: "Nunley, J. M., Pugh, A., Romero, N., & Seals, R. A., Jr. (2016). College major, internship experience, and employment opportunities: Estimates from a résumé audit. Labour Economics, 38, 37–46.", note: "Résumé audit of recent college graduates applying to real openings: internship experience raised callback rates, with an effect comparable to or larger than that of college major for many business positions.", link: doi("10.1016/j.labeco.2015.11.002"), kind: "doi" },
      { cite: "Baert, S., Neyt, B., Siedler, T., Tobback, I., & Verhaest, D. (2021). Student internships and employment opportunities after graduation: A field experiment. Economics of Education Review, 83, 102141.", note: "Field experiment sending fictitious graduate résumés with and without a student internship: internship experience increased positive employer reactions.", link: doi("10.1016/j.econedurev.2021.102141"), kind: "doi" },
      { cite: "Knouse, S. B., & Fontenot, G. (2008). Benefits of the business college internship: A research review. Journal of Employment Counseling, 45(2), 61–66.", note: "Review of internship research on employment opportunities, realistic expectations, satisfaction, prerequisites and mentoring, concluding the experience is beneficial overall.", link: doi("10.1002/j.2161-1920.2008.tb00045.x"), kind: "doi" },
    ],
  },
  {
    id: "gs-education-career-weak-ties",
    goal: "education-career", tier: "fundamental", section: "8718",
    title: "Work Your Weak Ties — One Reconnection a Week",
    subtitle: "Acquaintances carry job information; the LinkedIn experiment showed moderately weak ties create the most job moves",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "months", durability: "lasting", effort: "low" },
    feeds: ["job leads", "career mobility", "information reach"],
    description:
      "Granovetter's argument that weak ties bridge social worlds and carry novel job information was tested causally in randomised experiments on LinkedIn's People You May Know algorithm involving more than 20 million people: weaker ties increased job transmission up to a point, with moderately weak ties (few mutual connections) creating the most job mobility, and strong ties mattering more in less digital industries. Cross-national Facebook data show the paradox that most jobs come from weak ties in aggregate because there are so many of them, while any single strong tie is more likely to help. Networking behaviour predicted salary growth and career satisfaction in a longitudinal study, and networking intensity predicted reemployment among the unemployed.",
    action: "Each week, send one short message to someone you have not spoken to in over a year — a former classmate, colleague or acquaintance — asking what they are working on and mentioning what you are looking for.",
    sources: [
      { cite: "Granovetter, M. S. (1973). The strength of weak ties. American Journal of Sociology, 78(6), 1360–1380.", note: "The classic argument that weak ties bridge otherwise disconnected groups and are therefore the channel for novel information, including job leads.", link: doi("10.1086/225469"), kind: "doi" },
      { cite: "Rajkumar, K., Saint-Jacques, G., Bojinov, I., Brynjolfsson, E., & Aral, S. (2022). A causal test of the strength of weak ties. Science, 377(6612), 1304–1310.", note: "Randomised experiments varying weak-tie prevalence for over 20 million LinkedIn members over five years (2 billion ties, 600,000 jobs): an inverted-U — moderately weak ties created the most job mobility, and strong ties mattered more in less digital industries.", link: doi("10.1126/science.abl4476"), kind: "doi" },
      { cite: "Gee, L. K., Jones, J. J., Fariss, C. J., Burke, M., & Fowler, J. H. (2017). The paradox of weak ties in 55 countries. Journal of Economic Behavior & Organization, 133, 362–372.", note: "Facebook data from 55 countries: collectively most jobs are found through weak ties because they are numerous, but a single strong tie is individually more likely to lead to a job.", link: doi("10.1016/j.jebo.2016.12.004"), kind: "doi" },
      { cite: "Wolff, H.-G., & Moser, K. (2009). Effects of networking on career success: A longitudinal study. Journal of Applied Psychology, 94(1), 196–206.", note: "Three-year longitudinal study: networking behaviours predicted concurrent salary and salary growth as well as career satisfaction.", link: doi("10.1037/a0013350"), kind: "doi" },
      { cite: "Wanberg, C. R., Kanfer, R., & Banas, J. T. (2000). Predictors and outcomes of networking intensity among unemployed job seekers. Journal of Applied Psychology, 85(4), 491–503.", note: "Among unemployed job seekers, networking intensity was predicted by extraversion and networking comfort and predicted reemployment.", link: doi("10.1037/0021-9010.85.4.491"), kind: "doi" },
    ],
  },
  {
    id: "gs-education-career-interview",
    goal: "education-career", tier: "moderate", section: "8719",
    title: "Prepare for Structured Interviews — and Win the First Two Minutes",
    subtitle: "Coaching improves structured-interview scores; initial impressions predict offers",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "moderate" },
    feeds: ["offers", "interview scores", "composure"],
    description:
      "Structured interviews are among the most valid selection tools, and they are also learnable: a randomised study found coaching in how situational interviews work raised applicants' scores, and coaching on experience-based structured interviews improved subsequent performance. First impressions matter in a way you can prepare for — interviewers' initial evaluations in the rapport-building minutes predicted their final ratings and, through them, employment offers. The evidence base on selection validity has been revised downward recently, which if anything increases the relative weight of the structured interview.",
    action: "Before each interview, write six STAR stories (situation, task, action, result) matched to the job's stated competencies, rehearse them aloud with a friend who asks follow-ups, and script a warm 90-second opening exchange.",
    sources: [
      { cite: "Huffcutt, A. I., & Arthur, W. (1994). Hunter and Hunter (1984) revisited: Interview validity for entry-level jobs. Journal of Applied Psychology, 79(2), 184–190.", note: "Meta-analysis showing interview validity rises with structure; highly structured interviews approached the validity of cognitive-ability tests for entry-level jobs.", link: doi("10.1037/0021-9010.79.2.184"), kind: "doi" },
      { cite: "Levashina, J., Hartwell, C. J., Morgeson, F. P., & Campion, M. A. (2014). The structured employment interview: Narrative and quantitative review of the research literature. Personnel Psychology, 67(1), 241–293.", note: "Comprehensive review of structured interviews covering bias reduction, impression management, situational versus past-behaviour questions and rating scales.", link: doi("10.1111/peps.12052"), kind: "doi" },
      { cite: "Barrick, M. R., Swider, B. W., & Stewart, G. L. (2010). Initial evaluations in the interview: Relationships with subsequent interviewer evaluations and employment offers. Journal of Applied Psychology, 95(6), 1163–1172.", note: "Interviewers' impressions formed during rapport building predicted their later structured ratings and, through them, job offers.", link: doi("10.1037/a0019918"), kind: "doi" },
      { cite: "Maurer, T., Solamon, J., & Troxtel, D. (1998). Relationship of coaching with performance in situational employment interviews. Journal of Applied Psychology, 83(1), 128–136.", note: "Applicants who attended a coaching session on situational interviews scored higher than uncoached applicants in a real selection setting.", link: doi("10.1037//0021-9010.83.1.128"), kind: "doi" },
      { cite: "Tross, S. A., & Maurer, T. J. (2008). The effect of coaching interviewees on subsequent interview performance in structured experience-based interviews. Journal of Occupational and Organizational Psychology, 81(4), 589–605.", note: "Coaching on how to answer experience-based structured interview questions improved subsequent interview performance.", link: doi("10.1348/096317907x248653"), kind: "doi" },
      { cite: "Schmidt, F. L., & Hunter, J. E. (1998). The validity and utility of selection methods in personnel psychology: Practical and theoretical implications of 85 years of research findings. Psychological Bulletin, 124(2), 262–274.", note: "The classic summary of selection-method validities in which structured interviews rank among the most valid predictors of job performance.", link: doi("10.1037/0033-2909.124.2.262"), kind: "doi" },
      { cite: "Sackett, P. R., Zhang, C., Berry, C. M., & Lievens, F. (2022). Revisiting meta-analytic estimates of validity in personnel selection: Addressing systematic overcorrection for restriction of range. Journal of Applied Psychology, 107(11), 2040–2068.", note: "Revised validity estimates that lower many classic figures; structured interviews remain among the strongest predictors under the corrected estimates.", link: doi("10.1037/apl0000994"), kind: "doi" },
    ],
  },
  {
    id: "gs-education-career-negotiation",
    goal: "education-career", tier: "moderate", section: "8720",
    title: "Ask — and Anchor First When You Know the Market",
    subtitle: "Those who negotiate get more; ambiguity about whether pay is negotiable widens the gender gap",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "days", durability: "lasting", effort: "low" },
    feeds: ["starting salary", "lifetime earnings", "assertiveness"],
    description:
      "In a natural field experiment randomising nearly 2,500 job seekers, men negotiated more when the posting did not say pay was negotiable, women signalled willingness to work for less, and the gap vanished when the ad stated wages were negotiable. Graduates who negotiated their first offer received higher salaries; a meta-analysis confirms women initiate negotiation less often, with the gap shrinking when the situation is clearly negotiable. Laboratory work shows first offers anchor outcomes, and that women can face a social cost for asking in some evaluations — which is a reason to ask with a communal framing, not a reason not to ask.",
    action: "Before accepting any offer, research the market range, ask 'is there flexibility on the base?' and, when you have good information, make the first specific number yourself with a short justification tied to the role.",
    sources: [
      { cite: "Leibbrandt, A., & List, J. A. (2015). Do women avoid salary negotiations? Evidence from a large-scale natural field experiment. Management Science, 61(9), 2016–2024.", note: "Nearly 2,500 job seekers randomised across job ads: without an explicit statement that wages were negotiable, men negotiated more and women signalled lower reservation wages; stating negotiability erased the difference.", link: doi("10.1287/mnsc.2014.1994"), kind: "doi" },
      { cite: "Marks, M., & Harold, C. (2011). Who asks and who receives in salary negotiation. Journal of Organizational Behavior, 32(3), 371–394.", note: "Survey of recently hired professionals: those who negotiated their offers received higher starting salaries, with negotiation strategy shaping outcomes.", link: doi("10.1002/job.671"), kind: "doi" },
      { cite: "Small, D. A., Gelfand, M., Babcock, L., & Gettman, H. (2007). Who goes to the bargaining table? The influence of gender and framing on the initiation of negotiation. Journal of Personality and Social Psychology, 93(4), 600–613.", note: "Experiments showing women were less likely than men to initiate negotiation, a gap that diminished when the situation was framed as an opportunity to ask.", link: doi("10.1037/0022-3514.93.4.600"), kind: "doi" },
      { cite: "Bowles, H. R., Babcock, L., & Lai, L. (2007). Social incentives for gender differences in the propensity to initiate negotiations: Sometimes it does hurt to ask. Organizational Behavior and Human Decision Processes, 103(1), 84–103.", note: "Evaluators penalised women more than men for initiating negotiation in some conditions — evidence for a social cost that framing can mitigate.", link: doi("10.1016/j.obhdp.2006.09.001"), kind: "doi" },
      { cite: "Galinsky, A. D., & Mussweiler, T. (2001). First offers as anchors: The role of perspective-taking and negotiator focus. Journal of Personality and Social Psychology, 81(4), 657–669.", note: "Making the first offer anchored final agreements in the offerer's favour; focusing on one's own target or the counterpart's alternatives neutralised the anchor.", link: doi("10.1037/0022-3514.81.4.657"), kind: "doi" },
      { cite: "Kugler, K. G., Reif, J. A. M., Kaschner, T., & Brodbeck, F. C. (2018). Gender differences in the initiation of negotiations: A meta-analysis. Psychological Bulletin, 144(2), 198–222.", note: "Meta-analysis confirming a small gender difference in initiating negotiation that shrinks when negotiation is clearly appropriate and in more recent studies.", link: doi("10.1037/bul0000135"), kind: "doi" },
    ],
  },
  {
    id: "gs-education-career-undergrad-research",
    goal: "education-career", tier: "elite", section: "8721",
    title: "Join a Faculty Member's Research for a Full Year",
    subtitle: "Structured undergraduate research raises retention, science identity and graduate-school plans",
    evidenceTag: "Moderate",
    impact: { magnitude: 4, latency: "months", durability: "lasting", effort: "high" },
    feeds: ["retention", "graduate-school aspirations", "mentor relationships"],
    description:
      "A structured student–faculty research partnership program in the first two years was associated with higher retention, with the largest gains for under-represented students with lower grades. In a national longitudinal sample, participating in undergraduate research raised the probability of planning to enrol in STEM graduate programs; in a ten-year longitudinal study of minority students, research experience and quality mentoring predicted persistence into scientific careers. First-year research experiences were linked to better later outcomes in a large multi-institution sample. The boundary: selection into research is not random, and the strongest designs use propensity matching rather than randomisation.",
    action: "In your first or second year, email three professors whose work interests you with one specific question about a paper and an offer of 8–10 hours a week; commit to the lab or project for at least two semesters.",
    sources: [
      { cite: "Nagda, B. A., Gregerman, S. R., Jonides, J., von Hippel, W., & Lerner, J. S. (1998). Undergraduate student-faculty research partnerships affect student retention. The Review of Higher Education, 22(1), 55–72.", note: "Evaluation of a first- and second-year research partnership program: participants had higher retention, with the greatest effect for African American students with lower grades.", link: doi("10.1353/rhe.1998.0016"), kind: "doi" },
      { cite: "Eagan, M. K., Jr., Hurtado, S., Chang, M. J., Garcia, G. A., Herrera, F. A., & Garibay, J. C. (2013). Making a difference in science education: The impact of undergraduate research programs. American Educational Research Journal, 50(4), 683–713.", note: "Propensity-matched national longitudinal analysis: participating in undergraduate research increased the likelihood of intending to enrol in a STEM graduate program.", link: doi("10.3102/0002831213482038"), kind: "doi" },
      { cite: "Hernandez, P. R., Woodcock, A., Estrada, M., & Schultz, P. W. (2018). Undergraduate research experiences broaden diversity in the scientific workforce. BioScience, 68(3), 204–211.", note: "Ten-year longitudinal study of under-represented minority students: research experience, especially with quality mentoring, predicted persistence toward scientific careers.", link: doi("10.1093/biosci/bix163"), kind: "doi" },
      { cite: "Bowman, N. A., & Holmes, J. M. (2018). Getting off to a good start? First-year undergraduate research experiences and student outcomes. Higher Education, 76(1), 17–33.", note: "Multi-institution longitudinal data linking first-year undergraduate research participation to subsequent student outcomes.", link: doi("10.1007/s10734-017-0191-4"), kind: "doi" },
    ],
  },
  {
    id: "gs-education-career-developmental-network",
    goal: "education-career", tier: "elite", section: "8722",
    title: "Build a Developmental Network with at Least One Sponsor",
    subtitle: "Several developers across contexts, one of whom will spend capital on you",
    evidenceTag: "Moderate",
    impact: { magnitude: 4, latency: "months", durability: "lasting", effort: "high" },
    feeds: ["visibility", "promotion", "salary growth"],
    description:
      "Higgins and Kram reframed mentoring as a developmental network — several people, inside and outside the organisation, who provide career and psychosocial help — and argued network diversity and strength shape career outcomes. Informal mentors provided more career-development functions than formally assigned ones, and career functions such as sponsorship and exposure are the ones most tied to compensation and promotion in meta-analysis. Longitudinal data show networking behaviour predicts salary growth. This is the elite protocol because it takes years and deliberate cultivation; the boundary is that the evidence is largely correlational and the term sponsorship is used loosely in practice.",
    action: "Map your current developers on one page — who gives you information, feedback, visibility and advocacy — then over the next year add two people from outside your current organisation and ask one senior person explicitly to put your name forward for a stretch assignment.",
    sources: [
      { cite: "Higgins, M. C., & Kram, K. E. (2001). Reconceptualizing mentoring at work: A developmental network perspective. The Academy of Management Review, 26(2), 264–288.", note: "Theory of mentoring as a network of multiple developers whose diversity and tie strength are proposed to shape career and personal outcomes.", link: doi("10.2307/259122"), kind: "doi" },
      { cite: "Ragins, B. R., & Cotton, J. L. (1999). Mentor functions and outcomes: A comparison of men and women in formal and informal mentoring relationships. Journal of Applied Psychology, 84(4), 529–550.", note: "Protégés with informal mentors reported more career-development functions and higher compensation than those with formal mentors, with sponsorship and exposure among the functions measured.", link: doi("10.1037/0021-9010.84.4.529"), kind: "doi" },
      { cite: "Wolff, H.-G., & Moser, K. (2009). Effects of networking on career success: A longitudinal study. Journal of Applied Psychology, 94(1), 196–206.", note: "Networking behaviours predicted salary growth over three years — the outcome a developmental network is meant to move.", link: doi("10.1037/a0013350"), kind: "doi" },
      { cite: "Allen, T. D., Eby, L. T., Poteet, M. L., Lentz, E., & Lima, L. (2004). Career benefits associated with mentoring for protégés: A meta-analysis. Journal of Applied Psychology, 89(1), 127–136.", note: "Career-related mentoring functions, including sponsorship, were more strongly related to compensation and promotion than psychosocial functions.", link: doi("10.1037/0021-9010.89.1.127"), kind: "doi" },
    ],
  },
];
