// Goal shelf: FAMILY TIME — more time with family, kids and aging parents (sections 9100–9199).
// Verification: every DOI below was resolved against the Crossref record (api.crossref.org)
// or the PubMed record on 2026-09-11. See types.ts for the contract. Popular advice the
// evidence does not support is rated at the floor (magnitude 1) with a callout. Nothing on
// this shelf is medical, legal or financial advice; each source is described as what the
// study tested.
import { doi, type GoalShelfCluster } from "./types";

export const SECTIONS: Record<string, string> = {
  "9100": "How to Read This Shelf",
  "9101": "Family Meals — Frequency, Quality and the Honest Effect Size",
  "9102": "Time With Children — Engaged Time Versus Clocked Hours",
  "9103": "Family Rituals & Routines — Bedtime, Reading, the Weekly Anchor",
  "9104": "Technoference — Phones Inside Family Time",
  "9105": "Screen-Free Time — The Family Media Plan and Digital Detox Evidence",
  "9106": "Shared Leisure — Core-and-Balance Family Activities",
  "9107": "Work–Family Boundaries — Segmenting, After-Hours Email and Recovery",
  "9108": "Flexible Work & Schedule Control — Negotiating Time Back",
  "9109": "The Four-Day Week & Work-Time Reduction",
  "9110": "Time Affluence — Buying Time and Choosing Time Over Money",
  "9111": "Vacations & Family Wellbeing",
  "9112": "Sibling Relationships — Building the Longest Bond",
  "9113": "Grandparent Involvement — Outcomes for Children and Grandparents",
  "9114": "Adult Children & Aging Parents — Staying in Contact",
  "9115": "Caregiving for Aging Parents — Burden, Self-Check and Structured Support",
  "9116": "Respite Care — What the Trials Actually Show",
  "9117": "Intergenerational Programs — Experience Corps and Its Relatives",
};

export const CLUSTERS: GoalShelfCluster[] = [
  {
    id: "gs-family-time-read-me-first",
    goal: "family-time", tier: "fundamental", section: "9100",
    title: "How to Read the Family-Time Shelf",
    subtitle: "Protocols, not guilt — one from each tier, and the amount of time is not the metric",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "low" },
    description:
      "Every protocol on this shelf is tagged fundamental, moderate, advanced or elite and carries a concrete action. The best-known finding in this literature is that the sheer number of hours parents log with children is a weak predictor of how those children turn out; engaged, warm, unhurried time and the structures that protect it are what the evidence rewards. Start with one fundamental protocol and run it for a month before adding a work-schedule or caregiving change from the tiers above.",
    action: "This month, choose one fundamental protocol (a family meal rule, a bedtime routine or a phone-down window), run it daily for 30 days, and only then pick a moderate or advanced protocol that changes your work schedule or caregiving arrangement.",
    sources: [
      { cite: "Milkie, M. A., Nomaguchi, K. M., & Denny, K. E. (2015). Does the amount of time mothers spend with children or adolescents matter?. Journal of Marriage and Family, 77(2), 355–372.", note: "Using nationally representative time-diary data, this study tested whether the amount of time mothers spend with children and adolescents predicts their outcomes; the headline result was that quantity of maternal time was largely unrelated to child outcomes, with engaged time mattering for adolescents.", link: doi("10.1111/jomf.12170"), kind: "doi" },
      { cite: "Nomaguchi, K., & Milkie, M. A. (2020). Parenthood and well-being: A decade in review. Journal of Marriage and Family, 82(1), 198–223.", note: "A decade review of research on parenthood and well-being, summarising how the demands of parenting relate to parents' own happiness and mental health and why the design of family time matters as much as its volume.", link: doi("10.1111/jomf.12646"), kind: "doi" },
    ],
  },
  {
    id: "gs-family-time-family-meals",
    goal: "family-time", tier: "fundamental", section: "9101",
    title: "Eat Together Most Nights, Screens Off",
    subtitle: "Three or more shared meals a week, TV off, everyone at the table",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "low" },
    feeds: ["daily connection", "children's diet quality", "adolescent protective factors"],
    description:
      "Shared family meals are the most-studied family-time practice. Meta-analyses find that children who eat with their family three or more times a week are more likely to have healthier diets and weight, and the quality of the meal — TV off, a positive atmosphere, parents modelling healthy eating, children helping prepare — carries associations at least as large as the count. Cohort work with adolescents links regular family dinners to fewer substance-use and psychosocial problems. The honest boundary: nearly all of this is observational, effect sizes are small, and the strongest studies find much of the association explained by family connectedness rather than the meal itself (see the floor-rated cluster below).",
    action: "Set a household rule of at least three sit-down meals together per week with screens off and the television dark; involve one child in preparing each meal and aim for a meal that lasts long enough for real conversation.",
    sources: [
      { cite: "Hammons, A. J., & Fiese, B. H. (2011). Is frequency of shared family meals related to the nutritional health of children and adolescents?. Pediatrics, 127(6), e1565–e1574.", note: "Meta-analysis of 17 studies (182,836 children and adolescents): sharing three or more family meals a week was associated with lower odds of overweight (12%), unhealthy foods (20%) and disordered eating (35%), and higher odds of eating healthy foods (24%).", link: doi("10.1542/peds.2010-1440"), kind: "doi" },
      { cite: "Dallacker, M., Hertwig, R., & Mata, J. (2018). The frequency of family meals and nutritional health in children: A meta-analysis. Obesity Reviews, 19(5), 638–653.", note: "Meta-analysis of 57 studies (203,706 participants) found small but consistent associations between family-meal frequency and better diet quality (r = 0.13) and lower BMI (r = −0.05), across ages, countries and socioeconomic groups.", link: doi("10.1111/obr.12659"), kind: "doi" },
      { cite: "Dallacker, M., Hertwig, R., & Mata, J. (2019). Quality matters: A meta-analysis on components of healthy family meals. Health Psychology, 38(12), 1137–1149.", note: "Meta-analysis of 50 studies (49,137 participants) on the components of healthy family meals: turning the TV off, parental modelling, food quality, a positive atmosphere, children's involvement and longer meal duration (r = 0.20) were each associated with children's nutritional health — how families eat matters.", link: doi("10.1037/hea0000801"), kind: "doi" },
      { cite: "Eisenberg, M. E., Olson, R. E., Neumark-Sztainer, D., Story, M., & Bearinger, L. H. (2004). Correlations between family meals and psychosocial well-being among adolescents. Archives of Pediatrics & Adolescent Medicine, 158(8), 792.", note: "Large adolescent survey (Project EAT) that reported correlations between family-meal frequency and psychosocial well-being, including lower substance use and depressive symptoms.", link: doi("10.1001/archpedi.158.8.792"), kind: "doi" },
      { cite: "Fulkerson, J. A., Story, M., Mellin, A., Leffert, N., Neumark-Sztainer, D., & French, S. A. (2006). Family dinner meal frequency and adolescent development: Relationships with developmental assets and high-risk behaviors. Journal of Adolescent Health, 39(3), 337–345.", note: "Survey of adolescents linking family dinner frequency to more developmental assets and fewer high-risk behaviours.", link: doi("10.1016/j.jadohealth.2005.12.026"), kind: "doi" },
      { cite: "Eisenberg, M. E., Neumark-Sztainer, D., Fulkerson, J. A., & Story, M. (2008). Family meals and substance use: Is there a long-term protective association?. Journal of Adolescent Health, 43(2), 151–156.", note: "Longitudinal follow-up of adolescents asking whether family meals carry a long-term protective association with substance use — a test of durability rather than a cross-sectional snapshot.", link: doi("10.1016/j.jadohealth.2008.01.019"), kind: "doi" },
      { cite: "Fulkerson, J. A., Larson, N., Horning, M., & Neumark-Sztainer, D. (2014). A review of associations between family or shared meal frequency and dietary and weight status outcomes across the lifespan. Journal of Nutrition Education and Behavior, 46(1), 2–19.", note: "Review of associations between family or shared meal frequency and dietary and weight outcomes across the lifespan, including adults.", link: doi("10.1016/j.jneb.2013.07.012"), kind: "doi" },
      { cite: "Fiese, B. H., Hammons, A., & Grigsby-Toussaint, D. (2012). Family mealtimes: A contextual approach to understanding childhood obesity. Economics & Human Biology, 10(4), 365–374.", note: "Argues from mealtime observation research that the context of the meal — interaction quality, distraction, structure — is the mechanism behind the family-meal and childhood-obesity association.", link: doi("10.1016/j.ehb.2012.04.004"), kind: "doi" },
    ],
  },
  {
    id: "gs-family-time-meal-count-myth",
    goal: "family-time", tier: "fundamental", section: "9101",
    title: "Myth: Counting Dinners Is the Fix",
    subtitle: "The 'five dinners a week' rule as a stand-alone cure for grades, behaviour and drug use",
    evidenceTag: "Mixed",
    impact: { magnitude: 1, latency: "months", durability: "transient", effort: "low" },
    callout: "Rated at the floor because the best-controlled studies find little or no independent effect of dinner frequency on academic or behavioural outcomes once family connectedness and household resources are accounted for. The meal is a vehicle for connection, not a dose. Keep the meals (previous cluster), but do not expect the count to do the work.",
    description:
      "Popular parenting media present a fixed number of family dinners as a proven protective factor for grades, behaviour and substance use. When researchers used sibling and fixed-effects designs, or controlled for family connectedness, the protective associations mostly vanished or shrank, and a systematic review found that the analytic method predicted whether a study reported a benefit. Meal enjoyment and household structure, not frequency alone, tracked children's diets in a UK cohort.",
    action: "Stop tracking the number of dinners as a scorecard. Track instead whether the meals you do have are screen-free, unhurried and pleasant, and put the saved worry into the connection rituals elsewhere on this shelf.",
    sources: [
      { cite: "Miller, D. P., Waldfogel, J., & Han, W.-J. (2012). Family meals and child academic and behavioral outcomes. Child Development, 83(6), 2104–2120.", note: "Using a national kindergarten cohort with rigorous controls and fixed-effects models, this study found that family breakfast and dinner frequency had no consistent independent effect on children's academic and behavioural outcomes.", link: doi("10.1111/j.1467-8624.2012.01825.x"), kind: "doi" },
      { cite: "Meier, A., & Musick, K. (2014). Variation in associations between family dinners and adolescent well-being. Journal of Marriage and Family, 76(1), 13–23.", note: "Tested whether the family-dinner and adolescent well-being association survived controls for family quality; the associations were substantially attenuated and varied across outcomes, pointing to the quality of family relationships as the active ingredient.", link: doi("10.1111/jomf.12079"), kind: "doi" },
      { cite: "Goldfarb, S. S., Tarver, W. L., Locher, J. L., Preskitt, J., & Sen, B. (2015). A systematic review of the association between family meals and adolescent risk outcomes. Journal of Adolescence, 44, 134–149.", note: "Systematic review of 26 studies (254 analyses): models that controlled for family connectedness or used methods that handled family-level confounding were significantly less likely to report a protective family-meal effect.", link: doi("10.1016/j.adolescence.2015.07.008"), kind: "doi" },
      { cite: "Valdés, J., Rodríguez-Artalejo, F., Aguilar, L., Jaén-Casquero, M. B., & Royo-Bordonada, M. Á. (2013). Frequency of family meals and childhood overweight: A systematic review. Pediatric Obesity, 8(1), e1–e13.", note: "Systematic review of 15 studies found inconsistent and weak evidence for an inverse association between family-meal frequency and childhood overweight; only one study adjusted for the full set of confounders.", link: doi("10.1111/j.2047-6310.2012.00104.x"), kind: "doi" },
      { cite: "Skafida, V. (2013). The family meal panacea: Exploring how different aspects of family meal occurrence, meal habits and meal enjoyment relate to young children's diets. Sociology of Health & Illness, 35(6), 906–923.", note: "UK cohort analysis showing that meal enjoyment and the structure of meals related to young children's diets more than occurrence alone — the 'family meal panacea' framing oversells the count.", link: doi("10.1111/1467-9566.12007"), kind: "doi" },
    ],
  },
  {
    id: "gs-family-time-engaged-time",
    goal: "family-time", tier: "fundamental", section: "9102",
    title: "Protect Engaged Time, Not Clocked Time",
    subtitle: "A daily block of undistracted, child-led interaction — reading, talking, playing, homework help",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "weeks", durability: "lasting", effort: "low" },
    feeds: ["child cognitive development", "adolescent adjustment", "parent-child closeness"],
    description:
      "Time-diary research separates time that is merely co-present from time that is engaged — reading, talking, playing, helping. Engaged and educational time with parents predicts children's cognitive and non-cognitive development, and for adolescents, engaged time with parents tracks fewer behaviour problems and less substance use. Everyday moments — a car ride, cooking together — are where working families actually find quality time. The honest boundary: these are observational designs, and effects are small per hour; the leverage is in the kind of time, and in consistency, not in heroic weekend blocks.",
    action: "Every day, give each child one block of at least 20 minutes with no phone, no chores and no agenda but theirs — reading, a game, a walk or talking about their day — and protect it on the calendar the way you protect a work meeting.",
    sources: [
      { cite: "Milkie, M. A., Nomaguchi, K. M., & Denny, K. E. (2015). Does the amount of time mothers spend with children or adolescents matter?. Journal of Marriage and Family, 77(2), 355–372.", note: "Time-diary study: the quantity of mothers' time with children aged 3–11 was largely unrelated to child outcomes, but engaged time with adolescents was associated with fewer delinquent behaviours and less substance use.", link: doi("10.1111/jomf.12170"), kind: "doi" },
      { cite: "Hsin, A., & Felfe, C. (2014). When does time matter? Maternal employment, children's time with parents, and child development. Demography, 51(5), 1867–1894.", note: "Using children's time diaries, this study found that educational and structured time with parents predicted child development, and that maternal employment mattered only to the extent it displaced that engaged time.", link: doi("10.1007/s13524-014-0334-5"), kind: "doi" },
      { cite: "Fiorini, M., & Keane, M. P. (2014). How the allocation of children's time affects cognitive and noncognitive development. Journal of Labor Economics, 32(4), 787–836.", note: "Estimated how the allocation of children's time affected cognitive and non-cognitive skills; time spent in educational activities with parents was the most productive input for cognitive development.", link: doi("10.1086/677232"), kind: "doi" },
      { cite: "Kremer-Sadlik, T., & Paugh, A. L. (2007). Everyday moments: Finding 'quality time' in American working families. Time & Society, 16(2-3), 287–308.", note: "Ethnographic study of American working families showing that 'quality time' happens in everyday moments — errands, meals, chores — rather than in scheduled special events.", link: doi("10.1177/0961463X07080276"), kind: "doi" },
      { cite: "Fomby, P., & Musick, K. (2018). Mothers' time, the parenting package, and links to healthy child development. Journal of Marriage and Family, 80(1), 166–181.", note: "Examined mothers' time within the whole parenting package and found that engaged, developmentally rich time, together with warmth and stimulation, was linked to healthy child development.", link: doi("10.1111/jomf.12432"), kind: "doi" },
      { cite: "Price, J. (2008). Parent-child quality time: Does birth order matter?. Journal of Human Resources, 43(1), 240–265.", note: "Time-diary analysis of parent-child quality time showing first-borns receive more one-on-one engaged time than later-borns — a nudge to deliberately equalise it across children.", link: doi("10.1353/jhr.2008.0023"), kind: "doi" },
      { cite: "Sarkadi, A., Kristiansson, R., Oberklaid, F., & Bremberg, S. (2008). Fathers' involvement and children's developmental outcomes: A systematic review of longitudinal studies. Acta Paediatrica, 97(2), 153–158.", note: "Systematic review of longitudinal studies: active, engaged father involvement predicted better behavioural, social and cognitive outcomes for children.", link: doi("10.1111/j.1651-2227.2007.00572.x"), kind: "doi" },
    ],
  },
  {
    id: "gs-family-time-hours-myth",
    goal: "family-time", tier: "fundamental", section: "9102",
    title: "Myth: More Hours With the Kids Is the Metric",
    subtitle: "Maximising co-present hours — and the guilt that comes with it — as the goal",
    evidenceTag: "Strong",
    impact: { magnitude: 1, latency: "months", durability: "transient", effort: "moderate" },
    callout: "Rated at the floor because the best time-diary evidence shows the sheer quantity of parental time with young children does not predict their outcomes, while parents' stress and depletion during that time is associated with worse outcomes. Chasing hours produces guilt and hurried, distracted time — the opposite of what helps.",
    description:
      "A widespread belief is that good parenting means being physically present as many hours as possible. Time-diary studies find that the quantity of maternal time with children aged 3 to 11 is not associated with their achievement or behaviour, that parental time in the United States has actually risen across decades, and that parents' well-being during child-care time depends on the kind of activity and the stress they bring to it. Parents who spend long stretches of anxious, exhausted time with children are not helping them.",
    action: "Drop the hours target. Replace it with one daily engaged block per child (previous cluster) and one weekly family ritual, and spend the rest of your energy on sleep, work boundaries and the aging-parent plan rather than on guilt.",
    sources: [
      { cite: "Milkie, M. A., Nomaguchi, K. M., & Denny, K. E. (2015). Does the amount of time mothers spend with children or adolescents matter?. Journal of Marriage and Family, 77(2), 355–372.", note: "The amount of time mothers spent with children was not associated with outcomes for children aged 3–11 in nationally representative time-diary data; the paper explicitly challenged the cultural belief that more maternal time is always better.", link: doi("10.1111/jomf.12170"), kind: "doi" },
      { cite: "Musick, K., Meier, A., & Flood, S. (2016). How parents fare: Mothers' and fathers' subjective well-being in time with children. American Sociological Review, 81(5), 1069–1095.", note: "Time-diary study of how parents actually feel during time with children: mothers reported more stress, fatigue and less happiness than fathers in child-care time, with the activity type driving the difference.", link: doi("10.1177/0003122416663917"), kind: "doi" },
      { cite: "Roeters, A., & Gracia, P. (2016). Child care time, parents' well-being, and gender: Evidence from the American Time Use Survey. Journal of Child and Family Studies, 25(8), 2469–2479.", note: "American Time Use Survey analysis linking child-care time to parents' momentary well-being, showing that routine care and solo care carried lower well-being than interactive or shared care.", link: doi("10.1007/s10826-016-0416-7"), kind: "doi" },
      { cite: "Kalil, A., Ryan, R., & Corey, M. (2012). Diverging destinies: Maternal education and the developmental gradient in time with children. Demography, 49(4), 1361–1383.", note: "Documented a developmental gradient: more-educated mothers shift the kind of time they spend with children by age (teaching for pre-schoolers, management for adolescents) — the type of time, not the total, is what varies with outcomes.", link: doi("10.1007/s13524-012-0129-5"), kind: "doi" },
      { cite: "Guryan, J., Hurst, E., & Kearney, M. (2008). Parental education and parental time with children. Journal of Economic Perspectives, 22(3), 23–46.", note: "Showed that more-educated parents spend more time with children despite higher opportunity costs, and framed parental time as an investment whose composition matters.", link: doi("10.1257/jep.22.3.23"), kind: "doi" },
      { cite: "Sayer, L. C., Bianchi, S. M., & Robinson, J. P. (2004). Are parents investing less in children? Trends in mothers' and fathers' time with children. American Journal of Sociology, 110(1), 1–43.", note: "Trend study showing that mothers' and fathers' time with children rose over recent decades — parents are not investing less, despite the anxiety.", link: doi("10.1086/386270"), kind: "doi" },
      { cite: "Nomaguchi, K., & Milkie, M. A. (2020). Parenthood and well-being: A decade in review. Journal of Marriage and Family, 82(1), 198–223.", note: "Decade review of parenthood and well-being documenting the costs of intensive-parenting norms for parents' mental health.", link: doi("10.1111/jomf.12646"), kind: "doi" },
    ],
  },
  {
    id: "gs-family-time-rituals",
    goal: "family-time", tier: "fundamental", section: "9103",
    title: "Install a Bedtime Routine and One Weekly Family Ritual",
    subtitle: "The same nightly sequence for young children, and one predictable weekly event everyone can name",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "weeks", durability: "lasting", effort: "low" },
    feeds: ["child sleep", "emotional security", "family identity"],
    description:
      "Fifty years of research on naturally occurring family routines and rituals link them to children's health, academic performance and emotional security, and to family cohesion and identity. Bedtime routines show a dose-response association with better sleep in young children, and a nightly routine is a vehicle for reading, talking and physical closeness at an hour when parents are actually home. Routines also buffer families through chronic illness. The boundary: most evidence is correlational, and rituals lose their value when they become rigid or joyless.",
    action: "Fix a nightly bedtime sequence for each young child (bath, book, talk, lights) at the same time every night, and pick one weekly family ritual — a Sunday walk, Friday pizza, a game night — that stays on the calendar no matter what.",
    sources: [
      { cite: "Fiese, B. H., Tomcho, T. J., Douglas, M., Josephs, K., Poltrock, S., & Baker, T. (2002). A review of 50 years of research on naturally occurring family routines and rituals: Cause for celebration?. Journal of Family Psychology, 16(4), 381–390.", note: "Review of 50 years of research on family routines and rituals: routines relate to children's health and academic achievement, and rituals to family cohesion, marital satisfaction and adolescent identity.", link: doi("10.1037/0893-3200.16.4.381"), kind: "doi" },
      { cite: "Spagnola, M., & Fiese, B. H. (2007). Family routines and rituals. Infants & Young Children, 20(4), 284–299.", note: "Reviews how routines and rituals provide a context for young children's development, distinguishing predictable routines from emotionally meaningful rituals.", link: doi("10.1097/01.IYC.0000290352.32170.5a"), kind: "doi" },
      { cite: "Mindell, J. A., Li, A. M., Sadeh, A., Kwon, R., & Goh, D. Y. T. (2015). Bedtime routines for young children: A dose-dependent association with sleep outcomes. Sleep, 38(5), 717–722.", note: "Large multinational survey: a consistent bedtime routine was associated, in a dose-dependent way, with earlier bedtimes, shorter sleep-onset latency, fewer night wakings and longer sleep in young children.", link: doi("10.5665/sleep.4662"), kind: "doi" },
      { cite: "Mindell, J. A., & Williamson, A. A. (2018). Benefits of a bedtime routine in young children: Sleep, development, and beyond. Sleep Medicine Reviews, 40, 93–108.", note: "Conceptual review arguing that a nightly bedtime routine embodies nurturing care and supports sleep, language, literacy, emotional regulation and parent-child attachment.", link: doi("10.1016/j.smrv.2017.10.007"), kind: "doi" },
      { cite: "Muñiz, E. I., Silver, E. J., & Stein, R. E. K. (2014). Family routines and social-emotional school readiness among preschool-age children. Journal of Developmental & Behavioral Pediatrics, 35(2), 93–99.", note: "In a national cohort of about 8,550 pre-schoolers, each additional family routine (dinners, storytelling, singing, play) carried 1.47 greater odds of high social-emotional health.", link: doi("10.1097/DBP.0000000000000021"), kind: "doi" },
      { cite: "Crespo, C., Santos, S., Canavarro, M. C., Kielpikowski, M., Pryor, J., & Féres-Carneiro, T. (2013). Family routines and rituals in the context of chronic conditions: A review. International Journal of Psychology, 48(5), 729–746.", note: "Systematic review of 39 studies: family routines and rituals were linked to positive health and adaptation for patients and family members living with chronic conditions.", link: doi("10.1080/00207594.2013.806811"), kind: "doi" },
      { cite: "Duursma, E., Augustyn, M., & Zuckerman, B. (2008). Reading aloud to children: The evidence. Archives of Disease in Childhood, 93(7), 554–557.", note: "Reviews the evidence that reading aloud to children supports language development and the parent-child relationship — a routine that fits inside bedtime.", link: doi("10.1136/adc.2006.106336"), kind: "doi" },
    ],
  },
  {
    id: "gs-family-time-technoference",
    goal: "family-time", tier: "fundamental", section: "9104",
    title: "Put the Phone Away During Family Time",
    subtitle: "A phone-down window at meals, bedtime and the first 20 minutes home",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "days", durability: "sustained", effort: "low" },
    feeds: ["parent-child responsiveness", "child behaviour", "couple connection"],
    description:
      "'Technoference' — everyday interruptions of parent-child and couple interaction by devices — is associated in cross-sectional and longitudinal studies with more child behaviour problems and higher parenting stress, and observations of caregivers absorbed in phones at meals show reduced responsiveness to children. Partner phubbing tracks lower relationship satisfaction. The boundary: effects are small, causal direction is partly bidirectional (stressed parents reach for phones), and the evidence for adolescents is mostly correlational.",
    action: "Choose three daily windows — meals, the bedtime routine and the first 20 minutes after everyone gets home — and put every adult phone in a drawer or another room for those windows, starting tonight.",
    sources: [
      { cite: "McDaniel, B. T., & Radesky, J. S. (2018). Technoference: Parent distraction with technology and associations with child behavior problems. Child Development, 89(1), 100–109.", note: "Parents' reports of everyday technology interruptions in parent-child interaction were associated with more child externalising and internalising behaviour problems.", link: doi("10.1111/cdev.12822"), kind: "doi" },
      { cite: "McDaniel, B. T., & Radesky, J. S. (2018). Technoference: Longitudinal associations between parent technology use, parenting stress, and child behavior problems. Pediatric Research, 84(2), 210–218.", note: "Longitudinal study showing bidirectional associations over time between parent technology use during interaction, parenting stress and child behaviour problems.", link: doi("10.1038/s41390-018-0052-6"), kind: "doi" },
      { cite: "Radesky, J. S., Kistin, C. J., Zuckerman, B., Nitzberg, K., Gross, J., Kaplan-Sanoff, M., & … Silverstein, M. (2014). Patterns of mobile device use by caregivers and children during meals in fast food restaurants. Pediatrics, 133(4), e843–e849.", note: "Anonymous observations of caregivers with children in fast-food restaurants: many caregivers were absorbed in mobile devices, and absorbed caregivers responded more harshly to children's bids for attention.", link: doi("10.1542/peds.2013-3703"), kind: "doi" },
      { cite: "Kildare, C. A., & Middlemiss, W. (2017). Impact of parents mobile device use on parent-child interaction: A literature review. Computers in Human Behavior, 75, 579–593.", note: "Literature review concluding that parents' mobile-device use reduces the quantity and quality of parent-child interaction and responsiveness.", link: doi("10.1016/j.chb.2017.06.003"), kind: "doi" },
      { cite: "Stockdale, L. A., Coyne, S. M., & Padilla-Walker, L. M. (2018). Parent and child technoference and socioemotional behavioral outcomes: A nationally representative study of 10- to 20-year-old adolescents. Computers in Human Behavior, 88, 219–226.", note: "Nationally representative study of 10- to 20-year-olds linking parent and child technoference to worse socio-emotional and behavioural outcomes.", link: doi("10.1016/j.chb.2018.06.034"), kind: "doi" },
      { cite: "McDaniel, B. T., & Coyne, S. M. (2016). \"Technoference\": The interference of technology in couple relationships and implications for women's personal and relational well-being. Psychology of Popular Media Culture, 5(1), 85–98.", note: "Introduced the technoference construct for couples and linked everyday device interruptions to more conflict and lower relationship and life satisfaction for women.", link: doi("10.1037/ppm0000065"), kind: "doi" },
      { cite: "Radesky, J. S., Peacock-Chambers, E., Zuckerman, B., & Silverstein, M. (2016). Use of mobile technology to calm upset children: Associations with social-emotional development. JAMA Pediatrics, 170(4), 397–399.", note: "Parents who reported using mobile technology to calm upset children were more likely to have children with social-emotional difficulties — a caution against using the phone as the pacifier.", link: doi("10.1001/jamapediatrics.2015.4260"), kind: "doi" },
    ],
  },
  {
    id: "gs-family-time-media-plan",
    goal: "family-time", tier: "moderate", section: "9105",
    title: "Write a Family Media Plan",
    subtitle: "Household screen rules for adults and children, agreed together and reviewed monthly",
    evidenceTag: "Mixed",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "moderate" },
    feeds: ["shared attention", "children's sleep and activity", "adult modelling"],
    description:
      "The American Academy of Pediatrics' policy statements ask families to write a media plan: screen-free zones and times, limits by age and adult modelling. Trials of parent-mediated and school-based screen-time interventions produce modest reductions in screen use and small gains in physical activity, with larger effects when parents are actively involved. Digital-detox reviews find mixed effects on well-being; and the association between adolescent well-being and technology use is very small in the best-analysed data. So the plan is worth writing for the family time it frees — not because screens are ruinous.",
    action: "This week, hold a 30-minute family meeting to write a one-page media plan: screen-free zones (bedrooms, the table), screen-free hours, age limits and the adults' own rules; post it on the fridge and review it on the first of each month.",
    sources: [
      { cite: "Council on Communications and Media (2016). Media and young minds. Pediatrics, 138(5), e20162591.", note: "AAP policy statement for children under five recommending limits on screen media, co-viewing and a written family media use plan.", link: doi("10.1542/peds.2016-2591"), kind: "doi" },
      { cite: "Council on Communications and Media (2016). Media use in school-aged children and adolescents. Pediatrics, 138(5), e20162592.", note: "AAP policy statement for school-aged children and adolescents: consistent limits, media-free times and places, and a family media plan.", link: doi("10.1542/peds.2016-2592"), kind: "doi" },
      { cite: "Radtke, T., Apel, T., Schenkel, K., Keller, J., & von Lindern, E. (2022). Digital detox: An effective solution in the smartphone era? A systematic literature review. Mobile Media & Communication, 10(2), 190–215.", note: "Systematic review of digital-detox studies: effects on well-being were inconsistent, with some benefits for depressive symptoms and none reliably for life satisfaction — detoxes are a tool, not a cure.", link: doi("10.1177/20501579211028647"), kind: "doi" },
      { cite: "Song, S., Hua, X., & An, B. (2026). Effectiveness of screen-time interventions on BMI, daily screen use and diet behaviours in preschool children: A systematic review and meta-analysis of randomised controlled trials. Child: Care, Health and Development, 52(3), e70280.", note: "Meta-analysis of 10 RCTs (about 2,800 pre-schoolers): screen-time interventions produced a small BMI reduction, while reductions in daily screen time were not statistically significant.", link: doi("10.1111/cch.70280"), kind: "doi" },
      { cite: "Lai, N. M., Lim, Y. S., Chaiyakunapruk, N., Lee, S. W. H., Liabsuetrakul, T., Sabbir, M., & … Kuan, P. X. (2025). The effectiveness of school-based interventions for reducing screen time – a systematic review and meta-analysis. Child and Adolescent Mental Health, 30(3), 223–237.", note: "Meta-analysis of 39 school-based trials (95,033 participants): interventions modestly reduced screen time and increased physical activity, with low-certainty evidence.", link: doi("10.1111/camh.70022"), kind: "doi" },
      { cite: "Žmavc, M., Horvat, J., Židan, M., & Selak, Š. (2025). The effectiveness of school-based interventions to reduce problematic digital technology use and screen time: A systematic review and meta-analysis. Journal of Behavioral Addictions, 14(2), 571–589.", note: "Meta-analysis of 34 school-based interventions: large reductions in problematic digital use (d = 1.47) but small reductions in screen time (d = 0.15), with parent involvement improving effectiveness.", link: doi("10.1556/2006.2025.00043"), kind: "doi" },
      { cite: "Schwarz, S., Krafft, H., Maurer, T., Lange, S., Schemmer, J., Fischbach, T., & … Martin, D. (2024). Screen time, nature, and development: Baseline of the randomized controlled study \"Screen-free till 3\". Developmental Science, 28(1), e13578.", note: "Baseline of a German randomised intervention study ('Screen-free till 3') in 4,021 families: parents' own screen use predicted children's early screen use and correlated negatively with development.", link: doi("10.1111/desc.13578"), kind: "doi" },
      { cite: "Orben, A., & Przybylski, A. K. (2019). The association between adolescent well-being and digital technology use. Nature Human Behaviour, 3(2), 173–182.", note: "Specification-curve analysis of large adolescent datasets found the association between digital technology use and well-being was negative but very small — context for keeping the plan proportionate.", link: doi("10.1038/s41562-018-0506-1"), kind: "doi" },
    ],
  },
  {
    id: "gs-family-time-shared-leisure",
    goal: "family-time", tier: "moderate", section: "9106",
    title: "Plan Core and Balance Family Leisure",
    subtitle: "Frequent ordinary activities at home plus occasional novel outings — both, on the calendar",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "moderate" },
    feeds: ["family cohesion", "adaptability", "satisfaction with family life"],
    description:
      "The core-and-balance model of family leisure distinguishes common, low-cost, home-based activities (games, cooking, yard time) from novel, less frequent outings (trips, new activities). Studies with parents and children find that core activities track family cohesion and balance activities track adaptability, and that satisfaction with family leisure is the strongest leisure predictor of satisfaction with family life. Diary work with adolescents finds that shared family activities, especially leisure and meals, are associated with better emotional well-being. The boundary: samples are largely two-parent and middle-class, and the designs are cross-sectional.",
    action: "Each Sunday, schedule two 'core' activities for the week (a board game, cooking together, a walk) and one 'balance' outing per month that is new for the family; ask each family member to pick one of them.",
    sources: [
      { cite: "Zabriskie, R. B., & McCormick, B. P. (2001). The influences of family leisure patterns on perceptions of family functioning. Family Relations, 50(3), 281–289.", note: "Introduced the core-and-balance model: core family leisure was related to family cohesion and balance leisure to adaptability, together predicting perceptions of family functioning.", link: doi("10.1111/j.1741-3729.2001.00281.x"), kind: "doi" },
      { cite: "Zabriskie, R. B., & McCormick, B. P. (2003). Parent and child perspectives of family leisure involvement and satisfaction with family life. Journal of Leisure Research, 35(2), 163–189.", note: "Parent and child reports showed family leisure involvement predicted satisfaction with family life from both perspectives.", link: doi("10.1080/00222216.2003.11949989"), kind: "doi" },
      { cite: "Agate, J. R., Zabriskie, R. B., Agate, S. T., & Poff, R. (2009). Family leisure satisfaction and satisfaction with family life. Journal of Leisure Research, 41(2), 205–223.", note: "Family leisure satisfaction was the strongest predictor of satisfaction with family life among the leisure variables examined.", link: doi("10.1080/00222216.2009.11950166"), kind: "doi" },
      { cite: "Offer, S. (2013). Family time activities and adolescents' emotional well-being. Journal of Marriage and Family, 75(1), 26–41.", note: "Experience-sampling study of adolescents: time in family activities, particularly leisure and meals, was associated with more positive affect and less negative affect.", link: doi("10.1111/j.1741-3737.2012.01025.x"), kind: "doi" },
      { cite: "Sarkadi, A., Kristiansson, R., Oberklaid, F., & Bremberg, S. (2008). Fathers' involvement and children's developmental outcomes: A systematic review of longitudinal studies. Acta Paediatrica, 97(2), 153–158.", note: "Systematic review of longitudinal studies showing that fathers' active engagement in play and everyday activities predicted children's social and behavioural outcomes.", link: doi("10.1111/j.1651-2227.2007.00572.x"), kind: "doi" },
    ],
  },
  {
    id: "gs-family-time-boundaries",
    goal: "family-time", tier: "moderate", section: "9107",
    title: "Build Work–Home Boundaries That Fit You",
    subtitle: "Temporal, physical and communicative boundary tactics, and a firm rule on after-hours email",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "weeks", durability: "sustained", effort: "moderate" },
    feeds: ["work-to-family conflict", "recovery", "presence at home"],
    description:
      "Work–family conflict is time-based, strain-based and behaviour-based, and its consequences for satisfaction, health and family functioning are well documented. Qualitative and person-centred research identifies boundary-work tactics — fixed stop times, a physical work zone, communicating expectations, batching email — and finds that fit between preferred and actual segmentation, not segmentation per se, predicts well-being. Experimental and diary work shows after-hours electronic communication raises anger and work–nonwork conflict, and that smartphone use in the evening blocks recovery. The boundary: what fits differs by job and person, and boundaries need a supportive supervisor to hold.",
    action: "Write three boundary rules this week — a fixed daily stop time, a place where work does not happen, and a rule that work email is not opened between the evening meal and the children's bedtime — tell your team and your partner, and review what leaked after 30 days.",
    sources: [
      { cite: "Greenhaus, J. H., & Beutell, N. J. (1985). Sources of conflict between work and family roles. The Academy of Management Review, 10(1), 76–88.", note: "The foundational paper defining work–family conflict as time-based, strain-based and behaviour-based, and identifying the sources of each.", link: doi("10.2307/258214"), kind: "doi" },
      { cite: "Kreiner, G. E., Hollensbe, E. C., & Sheep, M. L. (2009). Balancing borders and bridges: Negotiating the work-home interface via boundary work tactics. Academy of Management Journal, 52(4), 704–730.", note: "Qualitative study identifying behavioural, temporal, physical and communicative boundary-work tactics people use to negotiate the work–home interface.", link: doi("10.5465/amj.2009.43669916"), kind: "doi" },
      { cite: "Kreiner, G. E. (2006). Consequences of work-home segmentation or integration: A person-environment fit perspective. Journal of Organizational Behavior, 27(4), 485–507.", note: "Person–environment fit study: it was the match between desired and supplied segmentation, not more segmentation per se, that predicted lower work–home conflict and higher satisfaction.", link: doi("10.1002/job.386"), kind: "doi" },
      { cite: "Kossek, E. E., Ruderman, M. N., Braddy, P. W., & Hannum, K. M. (2012). Work–nonwork boundary management profiles: A person-centered approach. Journal of Vocational Behavior, 81(1), 112–128.", note: "Person-centred profiles of work–nonwork boundary management, showing that boundary control and role identity distinguish profiles with better and worse well-being.", link: doi("10.1016/j.jvb.2012.04.003"), kind: "doi" },
      { cite: "Clark, S. C. (2000). Work/family border theory: A new theory of work/family balance. Human Relations, 53(6), 747–770.", note: "Work/family border theory: people are daily border-crossers, and permeability, flexibility and the border-keepers on each side shape balance.", link: doi("10.1177/0018726700536001"), kind: "doi" },
      { cite: "Butts, M. M., Becker, W. J., & Boswell, W. R. (2015). Hot buttons and time sinks: The effects of electronic communication during nonwork time on emotions and work-nonwork conflict. Academy of Management Journal, 58(3), 763–788.", note: "Experience-sampling study of electronic communication during nonwork time: messages that were negative in tone or required time raised anger and work–nonwork conflict.", link: doi("10.5465/amj.2014.0170"), kind: "doi" },
      { cite: "Derks, D., ten Brummelhuis, L. L., Zecic, D., & Bakker, A. B. (2014). Switching on and off …: Does smartphone use obstruct the possibility to engage in recovery activities?. European Journal of Work and Organizational Psychology, 23(1), 80–90.", note: "Diary study showing that evening smartphone use for work was associated with less psychological detachment and poorer recovery.", link: doi("10.1080/1359432X.2012.711013"), kind: "doi" },
    ],
  },
  {
    id: "gs-family-time-flexible-work",
    goal: "family-time", tier: "advanced", section: "9108",
    title: "Negotiate Schedule Control, Not Just Flexibility",
    subtitle: "A formal flexible-work or results-only arrangement, with supervisor support written in",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "months", durability: "lasting", effort: "high" },
    feeds: ["work-family conflict", "time adequacy with family", "turnover risk"],
    description:
      "Meta-analyses find that flexible schedules reduce work–family conflict modestly, with the effect depending on the type of flexibility and, above all, on supervisor and organisational support specific to work–family needs. The strongest evidence comes from the Work, Family and Health Network's group-randomised trial, which increased schedule control and supervisor support and reduced work–family conflict and improved time adequacy with family, and from a natural experiment in which a results-only work environment reduced turnover. The boundary: formal policies without a supportive manager deliver little, and gains are larger for employees with high family demands.",
    action: "Within 60 days, propose a written arrangement to your manager that specifies which hours are yours to control (start/end times, one remote day, or a compressed week), the results you will be measured on, and a 90-day review — and ask explicitly for their support with your team.",
    sources: [
      { cite: "Allen, T. D., Johnson, R. C., Kiburz, K. M., & Shockley, K. M. (2013). Work–family conflict and flexible work arrangements: Deconstructing flexibility. Personnel Psychology, 66(2), 345–376.", note: "Meta-analysis deconstructing flexibility: flextime reduced work-to-family conflict more than flexplace, and effects were smaller than popular claims suggest.", link: doi("10.1111/peps.12012"), kind: "doi" },
      { cite: "Baltes, B. B., Briggs, T. E., Huff, J. W., Wright, J. A., & Neuman, G. A. (1999). Flexible and compressed workweek schedules: A meta-analysis of their effects on work-related criteria. Journal of Applied Psychology, 84(4), 496–513.", note: "Meta-analysis of flexible and compressed workweek schedules showing positive effects on productivity, satisfaction and absenteeism, larger for flexible than compressed schedules.", link: doi("10.1037/0021-9010.84.4.496"), kind: "doi" },
      { cite: "Kelly, E. L., & Moen, P. (2007). Rethinking the clockwork of work: Why schedule control may pay off at work and at home. Advances in Developing Human Resources, 9(4), 487–506.", note: "Argued from evidence that schedule control — the ability to decide when and where work happens — is what pays off at work and at home.", link: doi("10.1177/1523422307305489"), kind: "doi" },
      { cite: "Kelly, E. L., Moen, P., Oakes, J. M., Fan, W., Okechukwu, C., Davis, K. D., & … Casper, L. M. (2014). Changing work and work-family conflict: Evidence from the Work, Family, and Health Network. American Sociological Review, 79(3), 485–516.", note: "Group-randomised field trial (STAR) in an IT firm: increasing schedule control and supervisor support for family reduced work–family conflict and improved schedule control and family time adequacy.", link: doi("10.1177/0003122414531435"), kind: "doi" },
      { cite: "Moen, P., Kelly, E. L., Fan, W., Lee, S.-R., Almeida, D., Kossek, E. E., & Buxton, O. M. (2016). Does a flexibility/support organizational initiative improve high-tech employees' well-being? Evidence from the Work, Family, and Health Network. American Sociological Review, 81(1), 134–164.", note: "Follow-up of the same trial showing improvements in employees' burnout, perceived stress and psychological distress relative to controls.", link: doi("10.1177/0003122415622391"), kind: "doi" },
      { cite: "Kossek, E. E., Pichler, S., Bodner, T., & Hammer, L. B. (2011). Workplace social support and work–family conflict: A meta-analysis clarifying the influence of general and work–family-specific supervisor and organizational support. Personnel Psychology, 64(2), 289–313.", note: "Meta-analysis showing that work–family-specific supervisor and organisational support reduced conflict more than general support — ask for the specific kind.", link: doi("10.1111/j.1744-6570.2011.01211.x"), kind: "doi" },
      { cite: "Michel, J. S., Kotrba, L. M., Mitchelson, J. K., Clark, M. A., & Baltes, B. B. (2011). Antecedents of work–family conflict: A meta-analytic review. Journal of Organizational Behavior, 32(5), 689–725.", note: "Meta-analytic review of the antecedents of work–family conflict, identifying role overload, hours, and lack of support as key drivers.", link: doi("10.1002/job.695"), kind: "doi" },
      { cite: "Allen, T. D., Herst, D. E. L., Bruck, C. S., & Sutton, M. (2000). Consequences associated with work-to-family conflict: A review and agenda for future research. Journal of Occupational Health Psychology, 5(2), 278–308.", note: "Review of the consequences of work-to-family conflict for job, life and family satisfaction, health and family functioning.", link: doi("10.1037/1076-8998.5.2.278"), kind: "doi" },
    ],
  },
  {
    id: "gs-family-time-four-day-week",
    goal: "family-time", tier: "elite", section: "9109",
    title: "Work-Time Reduction — The Four-Day Week",
    subtitle: "A 20% reduction in hours at full pay, negotiated as a trial with clear output measures",
    evidenceTag: "Emerging",
    impact: { magnitude: 4, latency: "months", durability: "lasting", effort: "high" },
    feeds: ["time with family", "burnout recovery", "work-family conflict"],
    description:
      "Coordinated four-day-week trials across many organisations report improvements in workers' well-being, burnout and sleep, with the gains tracking reductions in hours. A scoping review of reduced-hours-with-full-pay interventions found most studies reporting better work–life balance and mental health, and qualitative evidence of more family time — with the caveat that women often absorbed more unpaid work. A Belgian panel of a 30-hour week found the largest gain in reduced work–family conflict. The boundary: the trials are self-selected organisations without randomised controls, effects on productivity are employer-reported, and this is not available to most employees on request.",
    action: "If you have leverage — as an owner, executive or in a firm running a pilot — propose a six-month four-day-week trial with pre-agreed output measures and a survey of family time and burnout before and after; if you do not, negotiate a compressed or reduced schedule under the flexible-work protocol instead.",
    sources: [
      { cite: "Fan, W., Schor, J. B., Kelly, O., & Gu, G. (2025). Work time reduction via a 4-day workweek finds improvements in workers' well-being. Nature Human Behaviour, 9(10), 2153–2168.", note: "Six-month trials of a four-day workweek across many organisations: employees reported improvements in well-being, including burnout, job satisfaction and mental and physical health, relative to comparison employees.", link: doi("10.1038/s41562-025-02259-6"), kind: "doi" },
      { cite: "Utzet, M., Soler, M., Ramada, J. M., Menéndez, M., Silva-Peñaherrera, M., Benavides, F. G., & Serra, C. (2026). Exploring the health and well-being benefits of reduced working hours with maintained salary: A scoping review and evidence map. Scandinavian Journal of Work, Environment & Health, 52(2), 125–138.", note: "Scoping review of 10 articles and 5 reports on reduced working hours with full pay: most studies reported improved work–life balance and mental health, with gender differences in how freed time was used.", link: doi("10.5271/sjweh.4266"), kind: "doi" },
      { cite: "Mullens, F., & Laurijssen, I. (2024). An organizational working time reduction and its impact on three domains of mental well-being of employees: A panel study. BMC Public Health, 24(1), 1727.", note: "Panel study of a one-year 30-hour-week trial: the largest and most positive effect was a decrease in work–family conflict, partly explained by sufficient free time and schedule control.", link: doi("10.1186/s12889-024-19161-x"), kind: "doi" },
      { cite: "Moen, P., Kelly, E. L., & Hill, R. (2011). Does enhancing work-time control and flexibility reduce turnover? A naturally occurring experiment. Social Problems, 58(1), 69–98.", note: "Natural experiment of a results-only work environment showing that enhancing work-time control and flexibility reduced turnover.", link: doi("10.1525/sp.2011.58.1.69"), kind: "doi" },
    ],
  },
  {
    id: "gs-family-time-buy-time",
    goal: "family-time", tier: "advanced", section: "9110",
    title: "Buy Time Back and Choose Time Over Money",
    subtitle: "Outsource a hated chore, then spend the freed hour on family",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "moderate" },
    feeds: ["time affluence", "life satisfaction", "presence with family"],
    description:
      "Across large surveys and a pre-registered experiment, spending money on time-saving services was associated with greater life satisfaction, and a windfall spent on saving time raised end-of-day happiness more than the same money spent on material goods. People who value time over money report greater happiness, and time affluence predicts well-being beyond material affluence. Time poverty is now treated as a public-health and organisational problem in its own right. The boundary: most people do not buy time even when they can, effects are modest, and the benefit depends on using the freed hour for something connecting rather than more work.",
    action: "Pick the one household task you dislike most and pay to outsource it this month (cleaning, meal prep, a delivery), then book the freed hour each week as family time on the calendar before anything else can claim it.",
    sources: [
      { cite: "Whillans, A. V., Dunn, E. W., Smeets, P., Bekkers, R., & Norton, M. I. (2017). Buying time promotes happiness. Proceedings of the National Academy of Sciences, 114(32), 8523–8527.", note: "Across large surveys in several countries and a field experiment, spending money on time-saving services was associated with greater life satisfaction, and a time-saving purchase produced more end-of-day positive affect than a material purchase.", link: doi("10.1073/pnas.1706541114"), kind: "doi" },
      { cite: "Whillans, A. V., Weidman, A. C., & Dunn, E. W. (2016). Valuing time over money is associated with greater happiness. Social Psychological and Personality Science, 7(3), 213–222.", note: "Across several samples, people who prioritised time over money reported greater happiness, independent of income.", link: doi("10.1177/1948550615623842"), kind: "doi" },
      { cite: "Hershfield, H. E., Mogilner, C., & Barnea, U. (2016). People who choose time over money are happier. Social Psychological and Personality Science, 7(7), 697–706.", note: "People who chose time over money in trade-off decisions were happier, and the choice predicted well-being beyond demographics.", link: doi("10.1177/1948550616649239"), kind: "doi" },
      { cite: "Kasser, T., & Sheldon, K. M. (2009). Time affluence as a path toward personal happiness and ethical business practice: Empirical evidence from four studies. Journal of Business Ethics, 84(S2), 243–255.", note: "Four studies showing that time affluence predicted subjective well-being, partly through mindfulness and need satisfaction, above and beyond material affluence.", link: doi("10.1007/s10551-008-9696-1"), kind: "doi" },
      { cite: "Giurge, L. M., Whillans, A. V., & West, C. (2020). Why time poverty matters for individuals, organisations and nations. Nature Human Behaviour, 4(10), 993–1003.", note: "Review framing time poverty as a widespread, under-recognised problem for individuals, organisations and nations, with implications for well-being and productivity.", link: doi("10.1038/s41562-020-0920-z"), kind: "doi" },
      { cite: "Mogilner, C. (2010). The pursuit of happiness: Time, money, and social connection. Psychological Science, 21(9), 1348–1354.", note: "Experiments showing that shifting attention to time (versus money) led people to spend more time with friends and family and to report greater happiness.", link: doi("10.1177/0956797610380696"), kind: "doi" },
    ],
  },
  {
    id: "gs-family-time-vacations",
    goal: "family-time", tier: "advanced", section: "9111",
    title: "Take the Family Vacation — and Design the Re-Entry",
    subtitle: "A real break with shared activities, plus a plan for the fade-out afterwards",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "weeks", durability: "transient", effort: "moderate" },
    feeds: ["family cohesion", "recovery from work", "shared memories"],
    description:
      "Vacations improve health and well-being during and immediately after the trip, but a meta-analysis found the benefits fade within days to weeks of returning, and holiday-makers are not happier than non-vacationers once back at work. What lasts is relational: family vacation studies link shared travel to communication, cohesion and bonding, and reviews of family travel find memory-making and relationship benefits. The boundary: the family-functioning evidence is cross-sectional and self-reported, and a stressful trip with over-scheduling and screens can undo the point.",
    action: "Book one family trip per year (even a short one), protect it from work email, plan at least one shared activity per day that the children choose, and schedule a lighter first week back so the recovery does not evaporate on day one.",
    sources: [
      { cite: "de Bloom, J., Kompier, M., Geurts, S., de Weerth, C., Taris, T., & Sonnentag, S. (2009). Do we recover from vacation? Meta-analysis of vacation effects on health and well-being. Journal of Occupational Health, 51(1), 13–25.", note: "Meta-analysis of vacation effects: health and well-being improved during and shortly after vacation, but effects faded within days to weeks after return.", link: doi("10.1539/joh.K8004"), kind: "doi" },
      { cite: "Nawijn, J., Marchand, M. A., Veenhoven, R., & Vingerhoets, A. J. (2010). Vacationers happier, but most not happier after a holiday. Applied Research in Quality of Life, 5(1), 35–47.", note: "Dutch panel study: vacationers reported higher pre-trip happiness (anticipation), but most were not happier after the holiday than non-vacationers — the lasting value is not the afterglow.", link: doi("10.1007/s11482-009-9091-9"), kind: "doi" },
      { cite: "Lehto, X. Y., Choi, S., Lin, Y.-C., & MacDermid, S. M. (2009). Vacation and family functioning. Annals of Tourism Research, 36(3), 459–479.", note: "Survey of families linking vacation experiences to family communication, cohesion and adaptability.", link: doi("10.1016/j.annals.2009.04.003"), kind: "doi" },
      { cite: "Durko, A. M., & Petrick, J. F. (2013). Family and relationship benefits of travel experiences: A literature review. Journal of Travel Research, 52(6), 720–730.", note: "Literature review of the family and relationship benefits of travel, including bonding, communication and shared memories.", link: doi("10.1177/0047287513496478"), kind: "doi" },
    ],
  },
  {
    id: "gs-family-time-siblings",
    goal: "family-time", tier: "moderate", section: "9112",
    title: "Coach the Sibling Relationship",
    subtitle: "Weekly structured sibling activities plus explicit warmth-and-conflict skills",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "months", durability: "lasting", effort: "moderate" },
    feeds: ["sibling warmth", "child adjustment", "lifelong family ties"],
    description:
      "Sibling relationships are the longest family bonds most people have, and their quality in childhood predicts adjustment: a meta-analysis found more warmth and less conflict associated with fewer internalising and externalising problems. Reviews describe siblings as sources of social learning, support and — when conflict-ridden — risk. A universal prevention programme delivered at school (Siblings Are Special) improved sibling relationships, child self-control and social competence, and maternal depressive symptoms in an initial randomised test. The boundary: most of the field is correlational and the programme evidence is a single trial.",
    action: "Once a week, run one 30-minute structured activity that siblings must complete together (a cooking task, building something, a two-person game), and coach one skill each time — taking turns, naming a feeling, or a repair after a fight — rather than refereeing.",
    sources: [
      { cite: "Feinberg, M. E., Solmeyer, A. R., Hostetler, M. L., Sakuma, K.-L., Jones, D., & McHale, S. M. (2013). Siblings Are Special: Initial test of a new approach for preventing youth behavior problems. Journal of Adolescent Health, 53(2), 166–173.", note: "Initial randomised test of Siblings Are Special, a school-based programme for fifth-graders and a younger sibling: improved sibling relationship quality, child self-control and social competence, and reduced maternal depression.", link: doi("10.1016/j.jadohealth.2012.10.004"), kind: "doi" },
      { cite: "McHale, S. M., Updegraff, K. A., & Whiteman, S. D. (2012). Sibling relationships and influences in childhood and adolescence. Journal of Marriage and Family, 74(5), 913–930.", note: "Decade review of sibling relationships and influences in childhood and adolescence, documenting sibling effects on development and the family system.", link: doi("10.1111/j.1741-3737.2012.01011.x"), kind: "doi" },
      { cite: "Buist, K. L., Deković, M., & Prinzie, P. (2013). Sibling relationship quality and psychopathology of children and adolescents: A meta-analysis. Clinical Psychology Review, 33(1), 97–106.", note: "Meta-analysis: more sibling warmth, less conflict and less differential parental treatment were associated with less internalising and externalising psychopathology.", link: doi("10.1016/j.cpr.2012.10.007"), kind: "doi" },
      { cite: "Brody, G. H. (1998). Sibling relationship quality: Its causes and consequences. Annual Review of Psychology, 49(1), 1–24.", note: "Annual Review synthesis of the causes and consequences of sibling relationship quality, including parenting and family-climate contributions.", link: doi("10.1146/annurev.psych.49.1.1"), kind: "doi" },
    ],
  },
  {
    id: "gs-family-time-grandparents",
    goal: "family-time", tier: "moderate", section: "9113",
    title: "Bring Grandparents Into the Weekly Rhythm",
    subtitle: "A standing weekly contact and a monthly involvement that grandparents choose",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "weeks", durability: "lasting", effort: "low" },
    feeds: ["child adjustment", "parental support", "intergenerational bonds"],
    description:
      "Across cultures, involved grandparents — especially maternal grandmothers — are associated with better child survival historically and better adolescent adjustment today, including in lone-parent and step-families. Reviews find grandparents influence child health and development mostly through support to parents, and a meta-analysis links grandparental support to better maternal postpartum mental health. Within-child evidence finds grandparental contact associated with children's cognitive and socio-emotional outcomes. The boundary: effects are modest and mostly observational, and children raised primarily by grandparents (rather than helped by them) show slightly worse mental health in a large meta-analysis — support, not substitution, is the model.",
    action: "Set one standing weekly contact between each child and a grandparent (a call, a video story, a shared meal) and one monthly involvement the grandparent chooses — a pickup, a cooking lesson, a game — and put both on the family calendar.",
    sources: [
      { cite: "Sear, R., & Mace, R. (2008). Who keeps children alive? A review of the effects of kin on child survival. Evolution and Human Behavior, 29(1), 1–18.", note: "Review of kin effects on child survival across populations: maternal grandmothers consistently improved child survival, fathers less consistently.", link: doi("10.1016/j.evolhumbehav.2007.10.001"), kind: "doi" },
      { cite: "Attar-Schwartz, S., Tan, J.-P., Buchanan, A., Flouri, E., & Griggs, J. (2009). Grandparenting and adolescent adjustment in two-parent biological, lone-parent, and step-families. Journal of Family Psychology, 23(1), 67–75.", note: "In a large sample of adolescents, greater grandparent involvement was associated with fewer emotional and behavioural problems and more prosocial behaviour, with stronger effects in lone-parent and step-families.", link: doi("10.1037/a0014383"), kind: "doi" },
      { cite: "Griggs, J., Tan, J.-P., Buchanan, A., Attar-Schwartz, S., & Flouri, E. (2010). 'They've always been there for me': Grandparental involvement and child well-being. Children & Society, 24(3), 200–214.", note: "Mixed-methods study of adolescents' own accounts of what involved grandparents provide — emotional support, advice and a sense of continuity.", link: doi("10.1111/j.1099-0860.2009.00215.x"), kind: "doi" },
      { cite: "Dunifon, R., & Bajracharya, A. (2012). The role of grandparents in the lives of youth. Journal of Family Issues, 33(9), 1168–1194.", note: "Review of research on grandparents in the lives of youth, covering co-residence, custodial care and involvement, and their associations with child outcomes.", link: doi("10.1177/0192513X12444271"), kind: "doi" },
      { cite: "Tanskanen, A. O., & Danielsbacka, M. (2018). Multigenerational effects on children's cognitive and socioemotional outcomes: A within-child investigation. Child Development, 89(5), 1856–1870.", note: "Within-child analysis of a UK cohort: changes in grandparental involvement tracked changes in children's cognitive and socio-emotional outcomes.", link: doi("10.1111/cdev.12968"), kind: "doi" },
      { cite: "Sadruddin, A. F. A., Ponguta, L. A., Zonderman, A. L., Wiley, K. S., Grimshaw, A., & Panter-Brick, C. (2019). How do grandparents influence child health and development? A systematic review. Social Science & Medicine, 239, 112476.", note: "Systematic review of how grandparents influence child health and development, identifying pathways through caregiving, resources and support to parents.", link: doi("10.1016/j.socscimed.2019.112476"), kind: "doi" },
      { cite: "Coall, D. A., & Hertwig, R. (2010). Grandparental investment: Past, present, and future. Behavioral and Brain Sciences, 33(1), 1–19.", note: "Theoretical and empirical review of grandparental investment, its evolutionary roots and its measurable effects on grandchildren and parents.", link: doi("10.1017/S0140525X09991105"), kind: "doi" },
      { cite: "Riem, M. M. E., Bakermans-Kranenburg, M. J., Cima, M., & van IJzendoorn, M. H. (2023). Grandparental support and maternal postpartum mental health: A review and meta-analysis. Human Nature, 34(1), 25–45.", note: "Meta-analysis of 11 studies (N = 3,381): grandparental support was associated with better maternal postpartum mental health (r = 0.16), most strongly for support from the maternal grandmother.", link: doi("10.1007/s12110-023-09440-8"), kind: "doi" },
    ],
  },
  {
    id: "gs-family-time-grandparent-health",
    goal: "family-time", tier: "elite", section: "9113",
    title: "Grandparent as Active Caregiver — Regular, Not Full-Time",
    subtitle: "Designing a multigenerational care arrangement that helps the grandparent's health rather than harming it",
    evidenceTag: "Mixed",
    impact: { magnitude: 3, latency: "months", durability: "lasting", effort: "high" },
    feeds: ["grandparent health and cognition", "parents' time", "family cohesion"],
    description:
      "European panel data find that regular, non-intensive grandchild care is associated with better grandparent health and cognitive functioning, while custodial or very intensive care shows no benefit or harm. Surveys across Europe show how common grandparental child care is and how it varies with family structure. Reviews suggest a trend towards better cognition with moderate grandparenting but flag heterogeneity and bias. The boundary: children raised primarily by grandparents show small negative mental-health associations in meta-analysis, so the design principle is supplementary care with parents present in the arrangement.",
    action: "If a grandparent is willing and able, agree a written weekly care slot (for example one afternoon or one school pickup a week), review the grandparent's energy and health every three months, and keep it below full-time — the aim is a rhythm that benefits three generations.",
    sources: [
      { cite: "Di Gessa, G., Glaser, K., & Tinker, A. (2016). The impact of caring for grandchildren on the health of grandparents in Europe: A lifecourse approach. Social Science & Medicine, 152, 166–175.", note: "Lifecourse analysis of European panel data: intensive and non-intensive grandchild care were associated with better self-rated and physical health among grandparents, after accounting for earlier health and life histories.", link: doi("10.1016/j.socscimed.2016.01.041"), kind: "doi" },
      { cite: "Arpino, B., & Bordone, V. (2014). Does grandparenting pay off? The effect of child care on grandparents' cognitive functioning. Journal of Marriage and Family, 76(2), 337–351.", note: "Using SHARE data with instrumental-variable methods, providing grandchild care was associated with better verbal fluency in grandparents.", link: doi("10.1111/jomf.12096"), kind: "doi" },
      { cite: "Rafael, A., Sousa, L., Martins, S., & Fernandes, L. (2021). Cognitive impairment in grandparents: A systematic review. Psychiatry Investigation, 18(7), 593–602.", note: "Systematic review of eight sources on grandparenting and cognition: four of five original studies suggested a positive effect, but with high heterogeneity and risk of bias, and hints that very frequent care may be harmful.", link: doi("10.30773/pi.2021.0034"), kind: "doi" },
      { cite: "Hank, K., & Buber, I. (2009). Grandparents caring for their grandchildren: Findings from the 2004 Survey of Health, Ageing, and Retirement in Europe. Journal of Family Issues, 30(1), 53–73.", note: "Findings from the Survey of Health, Ageing and Retirement in Europe on the prevalence and patterns of grandparents caring for grandchildren.", link: doi("10.1177/0192513X08322627"), kind: "doi" },
      { cite: "Wang, Y., Chen, X., Wang, A., Jordan, L. P., & Lu, S. (2024). Research Review: Grandparental care and child mental health – a systematic review and meta-analysis. Journal of Child Psychology and Psychiatry, 65(4), 568–586.", note: "Meta-analysis of 38 studies (344,860 children): children cared for primarily by grandparents had slightly worse mental health (internalising d = −0.20) — the case for supplementary rather than substitute care.", link: doi("10.1111/jcpp.13943"), kind: "doi" },
    ],
  },
  {
    id: "gs-family-time-adult-parents",
    goal: "family-time", tier: "moderate", section: "9114",
    title: "A Standing Call and a Real Visit With Your Own Parents",
    subtitle: "Weekly contact and an in-person visit on a fixed rhythm, before care needs arrive",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "low" },
    feeds: ["parents' well-being", "your own well-being", "readiness for caregiving"],
    description:
      "Relationships between adult children and their parents carry psychological consequences for both generations: strained ties predict distress, and supportive ties predict well-being. Intergenerational solidarity research describes the structural, associational, affectual and functional dimensions of these ties and shows how contact frequency and emotional closeness cluster into distinct types. Recent decade reviews document how technology and demographic change have increased contact and support between generations. The boundary: intense support flowing to grown children is associated with better outcomes for them but with lower well-being for the parents when the children are perceived as needing it, so the direction and tone of contact matter.",
    action: "Fix one weekly call or video with each parent at a standing time, plus one in-person visit on a rhythm you can actually keep (monthly if local, quarterly if not), and use one of those contacts each quarter to ask what help they would want if their health changed.",
    sources: [
      { cite: "Umberson, D. (1992). Relationships between adult children and their parents: Psychological consequences for both generations. Journal of Marriage and the Family, 54(3), 664–674.", note: "National survey study showing that the quality of adult child–parent relationships had psychological consequences for both generations, with strained ties linked to distress.", link: doi("10.2307/353252"), kind: "doi" },
      { cite: "Silverstein, M., & Bengtson, V. L. (1997). Intergenerational solidarity and the structure of adult child-parent relationships in American families. American Journal of Sociology, 103(2), 429–460.", note: "Latent-class analysis of adult child–parent relationships identifying types of intergenerational solidarity based on contact, closeness, agreement and exchange.", link: doi("10.1086/231213"), kind: "doi" },
      { cite: "Fingerman, K. L., Cheng, Y.-P., Wesselmann, E. D., Zarit, S., Furstenberg, F., & Birditt, K. S. (2012). Helicopter parents and landing pad kids: Intense parental support of grown children. Journal of Marriage and Family, 74(4), 880–896.", note: "Parents who gave intense support to grown children reported lower life satisfaction when they perceived those children as needing too much support; grown children receiving it fared better.", link: doi("10.1111/j.1741-3737.2012.00987.x"), kind: "doi" },
      { cite: "Fingerman, K. L., Huo, M., & Birditt, K. S. (2020). A decade of research on intergenerational ties: Technological, economic, political, and demographic changes. Journal of Marriage and Family, 82(1), 383–403.", note: "Decade review of intergenerational ties documenting increased contact and support between generations amid technological, economic and demographic change.", link: doi("10.1111/jomf.12604"), kind: "doi" },
    ],
  },
  {
    id: "gs-family-time-caregiver-selfcheck",
    goal: "family-time", tier: "moderate", section: "9115",
    title: "Run a Caregiver Self-Check Before You Burn Out",
    subtitle: "Know the burden signs, get an early-stage support programme, and schedule your own health care",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "low" },
    feeds: ["caregiver mental health", "sustainability of care", "care quality"],
    description:
      "Family caregivers of older adults show more depressive symptoms, stress and worse self-rated health than non-caregivers in meta-analysis, and strained spousal caregivers had elevated mortality in a landmark cohort — though population-based reappraisals find that many caregivers, when not strained, do as well as or better than non-caregivers. A clinical review recommends screening caregivers for burden and depression. Meta-analysis of early-stage interventions for caregivers of people with mild dementia or mild cognitive impairment finds small positive effects, with the largest on anxiety and caring-related distress. The boundary: the harms concentrate in strained, high-hours caregivers, and screening only helps if it leads to support.",
    action: "If you are helping an aging parent, complete a caregiver burden and depression screen with your own clinician this month, book your own overdue health appointments, and ask the parent's care team about an early-stage caregiver programme — before the care hours climb.",
    sources: [
      { cite: "Pinquart, M., & Sörensen, S. (2003). Differences between caregivers and noncaregivers in psychological health and physical health: A meta-analysis. Psychology and Aging, 18(2), 250–267.", note: "Meta-analysis comparing caregivers and non-caregivers: caregivers showed more stress and depression and lower well-being and self-efficacy, with larger differences for dementia caregivers.", link: doi("10.1037/0882-7974.18.2.250"), kind: "doi" },
      { cite: "Schulz, R., & Beach, S. R. (1999). Caregiving as a risk factor for mortality: The Caregiver Health Effects Study. JAMA, 282(23), 2215–2219.", note: "Caregiver Health Effects Study: older spousal caregivers who reported strain had higher mortality over four years than non-caregivers.", link: doi("10.1001/jama.282.23.2215"), kind: "doi" },
      { cite: "Roth, D. L., Fredman, L., & Haley, W. E. (2015). Informal caregiving and its impact on health: A reappraisal from population-based studies. The Gerontologist, 55(2), 309–319.", note: "Reappraisal from population-based studies showing that caregiving per se is not uniformly harmful and that many caregivers show equal or better health than non-caregivers; strain is the risk marker.", link: doi("10.1093/geront/gnu177"), kind: "doi" },
      { cite: "Adelman, R. D., Tmanova, L. L., Delgado, D., Dion, S., & Lachs, M. S. (2014). Caregiver burden: A clinical review. JAMA, 311(10), 1052–1060.", note: "Clinical review of caregiver burden recommending assessment of burden and depression and describing evidence-based supports.", link: doi("10.1001/jama.2014.304"), kind: "doi" },
      { cite: "Bayly, M., Morgan, D., Elliot, V., Kosteniuk, J., Froehlich Chow, A., Peacock, S., & O'Connell, M. E. (2021). Does early-stage intervention improve caregiver well-being or their ability to provide care to persons with mild dementia or mild cognitive impairment? A systematic review and meta-analysis. Psychology and Aging, 36(7), 834–854.", note: "Meta-analysis of 18 controlled early-stage intervention studies: small positive effects on caregiver well-being and ability to provide care, largest for anxiety and caring-related distress.", link: doi("10.1037/pag0000642"), kind: "doi" },
      { cite: "Cheng, S.-T., Li, K.-K., Or, P. P. L., & Losada, A. (2022). Do caregiver interventions improve outcomes in relatives with dementia and mild cognitive impairment? A comprehensive systematic review and meta-analysis. Psychology and Aging, 37(8), 929–953.", note: "Review of 142 randomised trials: caregiver interventions also improved outcomes for the relatives with dementia, including fewer neuropsychiatric symptoms and delayed institutionalisation, with small effects.", link: doi("10.1037/pag0000696"), kind: "doi" },
    ],
  },
  {
    id: "gs-family-time-caregiver-program",
    goal: "family-time", tier: "advanced", section: "9115",
    title: "Enrol in a Multicomponent Caregiver Programme",
    subtitle: "Psychoeducation plus counselling and skills training, sustained over months",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "months", durability: "lasting", effort: "high" },
    feeds: ["caregiver depression and burden", "time to institutional placement", "family functioning"],
    description:
      "Meta-analyses of caregiver interventions find small-to-moderate improvements in burden, depression, well-being and ability, with psychoeducational and multicomponent programmes the most consistent. Randomised trials — the NYU counselling and support intervention, REACH II, and the COPE home-based programme — reduced caregiver depression for years, improved quality of life across ethnic groups, and delayed nursing-home placement. The boundary: effects are on average small, dementia caregivers gain less than others, respite alone shows little effect, and programmes must be tailored to the outcome you need.",
    action: "Within 60 days, enrol in a structured caregiver programme through the parent's clinic, the Alzheimer's Association or the Area Agency on Aging that includes psychoeducation, individual or family counselling and ongoing check-ins, and commit to the full course rather than a single session.",
    sources: [
      { cite: "Sörensen, S., Pinquart, M., & Duberstein, P. (2002). How effective are interventions with caregivers? An updated meta-analysis. The Gerontologist, 42(3), 356–372.", note: "Meta-analysis of 78 caregiver intervention studies: average improvements of 0.14 to 0.41 SD in burden, depression, well-being, satisfaction and ability, with psychoeducational and psychotherapeutic interventions showing the most consistent effects.", link: doi("10.1093/geront/42.3.356"), kind: "doi" },
      { cite: "Pinquart, M., & Sörensen, S. (2006). Helping caregivers of persons with dementia: Which interventions work and how large are their effects?. International Psychogeriatrics, 18(4), 577–595.", note: "Meta-analysis of dementia caregiver interventions identifying which types work and how large their effects are; multicomponent interventions reduced institutionalisation risk.", link: doi("10.1017/S1041610206003462"), kind: "doi" },
      { cite: "Walter, E., & Pinquart, M. (2020). How effective are dementia caregiver interventions? An updated comprehensive meta-analysis. The Gerontologist, 60(8), 609–619.", note: "Updated meta-analysis of 282 controlled studies: small-to-moderate effects on knowledge, well-being, burden, depression and anxiety, with psychoeducation and multicomponent interventions affecting most outcomes.", link: doi("10.1093/geront/gnz118"), kind: "doi" },
      { cite: "Cheng, S.-T., Li, K.-K., Losada, A., Zhang, F., Au, A., Thompson, L. W., & Gallagher-Thompson, D. (2020). The effectiveness of nonpharmacological interventions for informal dementia caregivers: An updated systematic review and meta-analysis. Psychology and Aging, 35(1), 55–77.", note: "Updated systematic review and meta-analysis of nonpharmacological interventions for informal dementia caregivers, identifying effective components.", link: doi("10.1037/pag0000401"), kind: "doi" },
      { cite: "Belle, S. H., Burgio, L., Burns, R., Coon, D., Czaja, S. J., Gallagher-Thompson, D., & … Zhang, S. (2006). Enhancing the quality of life of dementia caregivers from different ethnic or racial groups: A randomized, controlled trial. Annals of Internal Medicine, 145(10), 727–738.", note: "REACH II randomised trial (642 caregivers): a structured multicomponent intervention improved quality of life across Hispanic, white and Black caregivers and lowered clinical depression (12.6% vs 22.7%).", link: doi("10.7326/0003-4819-145-10-200611210-00005"), kind: "doi" },
      { cite: "Mittelman, M. S., Roth, D. L., Coon, D. W., & Haley, W. E. (2004). Sustained benefit of supportive intervention for depressive symptoms in caregivers of patients with Alzheimer's disease. American Journal of Psychiatry, 161(5), 850–856.", note: "NYU intervention trial (406 spouse-caregivers): six sessions of counselling plus support groups reduced depressive symptoms, with benefits sustained for 3.1 years.", link: doi("10.1176/appi.ajp.161.5.850"), kind: "doi" },
      { cite: "Mittelman, M. S., Haley, W. E., Clay, O. J., & Roth, D. L. (2006). Improving caregiver well-being delays nursing home placement of patients with Alzheimer disease. Neurology, 67(9), 1592–1599.", note: "The same NYU counselling and support intervention delayed nursing-home placement of patients with Alzheimer disease, mediated by improvements in caregiver well-being.", link: doi("10.1212/01.wnl.0000242727.81172.91"), kind: "doi" },
      { cite: "Gitlin, L. N., Winter, L., Dennis, M. P., Hodgson, N., & Hauck, W. W. (2010). A biobehavioral home-based intervention and the well-being of patients with dementia and their caregivers: The COPE randomized trial. JAMA, 304(9), 983–991.", note: "COPE randomised trial: a home-based biobehavioural intervention improved functional dependence and engagement in patients with dementia and caregiver well-being and confidence.", link: doi("10.1001/jama.2010.1253"), kind: "doi" },
    ],
  },
  {
    id: "gs-family-time-respite-myth",
    goal: "family-time", tier: "advanced", section: "9116",
    title: "Myth: Respite Care Alone Fixes Caregiver Burden",
    subtitle: "Buying a break as the whole plan for an exhausted caregiver",
    evidenceTag: "Mixed",
    impact: { magnitude: 1, latency: "weeks", durability: "transient", effort: "moderate" },
    callout: "Rated at the floor because the Cochrane review found no demonstrated benefit or harm of respite for people with dementia or their carers, and a systematic review of respite for frail older people found generally small effects. Respite is often welcomed and may be part of a plan, but the evidence does not support it as the intervention. Pair any break with a structured caregiver programme.",
    description:
      "Respite — day care, in-home relief or short residential stays — is the most commonly advocated support for family caregivers, and caregivers report high satisfaction with it. Yet randomised evidence is thin and of very low quality: the Cochrane review found no significant effects of respite versus no respite on any caregiver variable, and a large systematic review found modest benefits only for certain subgroups and no reliable evidence that respite delays residential care. A later systematic review found some positive effects of day care on burden and behaviour, with inconsistent findings elsewhere.",
    action: "Use respite as relief, not treatment: if you take a break, pair it with enrolment in a psychoeducational or multicomponent caregiver programme (previous section) and measure your own depression and burden before and after.",
    sources: [
      { cite: "Maayan, N., Soares-Weiser, K., & Lee, H. (2014). Respite care for people with dementia and their carers. Cochrane Database of Systematic Reviews, 2014(1), CD004396.", note: "Cochrane review of four trials (753 participants): no significant effects of respite care compared with no respite on any caregiver variable, with very low quality evidence.", link: doi("10.1002/14651858.CD004396.pub3"), kind: "doi" },
      { cite: "Mason, A., Weatherly, H., Spilsbury, K., Golder, S., Arksey, H., Adamson, J., & Drummond, M. (2007). The effectiveness and cost-effectiveness of respite for caregivers of frail older people. Journal of the American Geriatrics Society, 55(2), 290–299.", note: "Systematic review of 22 studies (10 RCTs): effects of respite on caregivers were generally small, with modest benefits only for certain subgroups and no reliable evidence that respite delays entry to residential care.", link: doi("10.1111/j.1532-5415.2006.01037.x"), kind: "doi" },
      { cite: "Vandepitte, S., Van Den Noortgate, N., Putman, K., Verhaeghe, S., Verdonck, C., & Annemans, L. (2016). Effectiveness of respite care in supporting informal caregivers of persons with dementia: A systematic review. International Journal of Geriatric Psychiatry, 31(12), 1277–1288.", note: "Systematic review of respite care for informal dementia caregivers, finding some positive effects of day care on burden and behavioural problems but inconsistent evidence overall.", link: doi("10.1002/gps.4504"), kind: "doi" },
      { cite: "Walter, E., & Pinquart, M. (2020). How effective are dementia caregiver interventions? An updated comprehensive meta-analysis. The Gerontologist, 60(8), 609–619.", note: "Updated meta-analysis of 282 caregiver intervention studies calling for more research on the efficacy of respite and support interventions, whose effects were domain-specific and small.", link: doi("10.1093/geront/gnz118"), kind: "doi" },
    ],
  },
  {
    id: "gs-family-time-intergenerational",
    goal: "family-time", tier: "elite", section: "9117",
    title: "Join or Build an Intergenerational Program",
    subtitle: "A structured, sustained program that pairs older adults with children — Experience Corps and its relatives",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "months", durability: "lasting", effort: "high" },
    feeds: ["older adults' physical and cognitive activity", "children's attitudes and skills", "community trust"],
    description:
      "Experience Corps places older volunteers in elementary schools for regular tutoring and mentoring. A pilot randomised trial found increased physical, cognitive and social activity in volunteers, and a later study found evidence of neurocognitive plasticity in at-risk older adults. Reviews of intergenerational programmes find consistent positive effects on children's attitudes toward older adults and variable but often beneficial effects on older participants' well-being, depression and self-esteem, and community-level work links sustained programmes to neighbourhood trust and social capital. The boundary: many studies are small and non-randomised, benefits are not systematic, and quality depends on organisation and staff training.",
    action: "Enrol an aging parent (or yourself, if retired) in a structured intergenerational program with a fixed weekly commitment — school tutoring, a shared-site care program or a community mentoring scheme — and review energy, mood and enjoyment after three months.",
    sources: [
      { cite: "Fried, L. P., Carlson, M. C., Freedman, M., Frick, K. D., Glass, T. A., Hill, J., & … Zeger, S. (2004). A social model for health promotion for an aging population: Initial evidence on the Experience Corps model. Journal of Urban Health, 81(1), 64–78.", note: "Pilot randomised trial of Experience Corps in Baltimore (128 volunteers aged 60–86): physical activity, strength, social support and cognitive activity increased relative to controls over 4–8 months.", link: doi("10.1093/jurban/jth094"), kind: "doi" },
      { cite: "Carlson, M. C., Erickson, K. I., Kramer, A. F., Voss, M. W., Bolea, N., Mielke, M., & … Fried, L. P. (2009). Evidence for neurocognitive plasticity in at-risk older adults: The Experience Corps program. The Journals of Gerontology Series A: Biological Sciences and Medical Sciences, 64A(12), 1275–1282.", note: "Evidence of neurocognitive plasticity in at-risk older adults participating in the Experience Corps program, including improvements in executive function.", link: doi("10.1093/gerona/glp117"), kind: "doi" },
      { cite: "Gualano, M. R., Voglino, G., Bert, F., Thomas, R., Camussi, E., & Siliquini, R. (2018). The impact of intergenerational programs on children and older adults: A review. International Psychogeriatrics, 30(4), 451–468.", note: "Review of 27 sources on intergenerational programmes: positive impacts on children's perceptions of older adults at short and long term, and variable but overall beneficial effects on older adults, including those with dementia.", link: doi("10.1017/S104161021700182X"), kind: "doi" },
      { cite: "Giraudeau, C., & Bailly, N. (2019). Intergenerational programs: What can school-age children and older people expect from them? A systematic review. European Journal of Ageing, 16(3), 363–376.", note: "Systematic review of 11 programme studies: some showed significant gains in children's attitudes, confidence and competence and in older adults' health and quality of life, but benefits were not systematic.", link: doi("10.1007/s10433-018-00497-4"), kind: "doi" },
      { cite: "Canedo-García, A., García-Sánchez, J.-N., & Pacheco-Sanz, D.-I. (2017). A systematic review of the effectiveness of intergenerational programs. Frontiers in Psychology, 8, 1882.", note: "Systematic review of 50 studies: intergenerational programmes with more evidence-based intervention controls showed greater effectiveness regardless of delivery mode.", link: doi("10.3389/fpsyg.2017.01882"), kind: "doi" },
      { cite: "Murayama, Y., Murayama, H., Hasebe, M., Yamaguchi, J., & Fujiwara, Y. (2019). The impact of intergenerational programs on social capital in Japan: A randomized population-based cross-sectional study. BMC Public Health, 19(1), 156.", note: "Population-based study in Japan: the duration of an intergenerational programme in a community was a significant predictor of neighbourhood trust across generations.", link: doi("10.1186/s12889-019-6480-3"), kind: "doi" },
      { cite: "Nemoto, Y., Nonaka, K., Kuraoka, M., Murayama, S., Tanaka, M., Matsunaga, H., & … Fujiwara, Y. (2022). Effects of intergenerational contact on social capital in community-dwelling adults aged 25–84 years: A non-randomized community-based intervention. BMC Public Health, 22(1), 1815.", note: "Non-randomised community intervention (2,518 analysed): increasing intergenerational contact improved social trust and norms of reciprocity relative to control districts.", link: doi("10.1186/s12889-022-14205-6"), kind: "doi" },
    ],
  },
];
