// Goal shelf: HAPPINESS — be happy: well-being that lasts (sections 8300–8399).
// Verification: every DOI below was resolved against the Crossref record or the
// PubMed record on 2026-09-11 (see the shelf ledger). See types.ts for the contract.
import { doi, type GoalShelfCluster } from "./types";

export const SECTIONS: Record<string, string> = {
  "8300": "How to Read This Shelf",
  "8301": "What the Interventions Actually Deliver — the Meta-Analyses, Re-Analysed",
  "8302": "Gratitude — Small, Real, Cheap",
  "8303": "Savoring — Stretching the Good Moments",
  "8304": "Kindness & Giving — Prosocial Spending and Acts",
  "8305": "Relationships — the Harvard Study's One Finding",
  "8306": "Exercise — the Best-Evidenced Mood Treatment You Can Do Alone",
  "8307": "Sleep — Fix It First",
  "8308": "Nature — Two Hours a Week",
  "8309": "Meaning & Purpose",
  "8310": "Adaptation & the Set Point — What You Can and Cannot Move",
  "8311": "Money — Kahneman, Killingsworth and the Adversarial Collaboration",
  "8312": "Time — Commuting, Time Affluence and Buying Time Back",
  "8313": "Comparison & Social Media — the Honest Evidence",
  "8314": "Mindfulness-Based Programs",
  "8315": "CBT Self-Help & Behavioral Activation",
  "8316": "Religion, Spirituality & Community",
  "8317": "Flow — Challenge Matched to Skill",
  "8318": "Volunteering — 100 Hours a Year",
  "8319": "Journaling — Expressive Writing",
  "8320": "Myths — 'Happiness Is a Choice' and the 40% Pie",
  "8321": "The Combined Program — Exercise Plus Psychology",
};

export const CLUSTERS: GoalShelfCluster[] = [
  {
    id: "gs-happiness-read-me-first",
    goal: "happiness", tier: "fundamental", section: "8300",
    title: "How to Read the Happiness Shelf",
    subtitle: "Effects are smaller than the books say — stack several, expect adaptation",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "low" },
    description:
      "Every protocol here is tiered and ends in an action. Read the first cluster (8301) before any other: the 2019 re-analysis of the positive-psychology meta-analyses found the headline effects much smaller once small-study bias was corrected, so this shelf rates single exercises at 2–3 and reserves 4–5 for the things with hard outcomes behind them — sleep, exercise, relationships, treatment for depression. Two clusters are rated at the floor on purpose.",
    action: "This month, pick one fundamental protocol you are not already doing (sleep, movement, a gratitude list, a weekly call) and run it daily for 30 days; only then add a second.",
    sources: [
      { cite: "White, C. A., Uttl, B., & Holder, M. D. (2019). Meta-analyses of positive psychology interventions: The effects are much smaller than previously reported. PloS one, 14(5), e0216588.", note: "Re-analysis of the two most-cited positive-psychology meta-analyses: after correcting for small-sample bias the effects on well-being were much smaller than originally reported — the calibration for every rating on this shelf.", link: doi("10.1371/journal.pone.0216588"), kind: "doi" },
    ],
  },
  {
    id: "gs-happiness-ppi-honest",
    goal: "happiness", tier: "moderate", section: "8301",
    title: "Positive Psychology Exercises: Small, Real, and Partly Placebo",
    subtitle: "What survives the replications and the 2019 re-analysis",
    evidenceTag: "Mixed",
    impact: { magnitude: 2, latency: "weeks", durability: "transient", effort: "low" },
    callout: "Honest boundary: the original meta-analyses reported medium effects (r ≈ .29 on well-being); the 2019 re-analysis found them much smaller once small-study bias was handled, and a replication of Seligman's classic exercises found a 'positive placebo' worked as well as the real exercises. Effects at 3–6-month follow-up are small. Use the exercises as cheap daily hygiene, not as the answer.",
    description:
      "Sin and Lyubomirsky's 2009 and Bolier's 2013 meta-analyses found positive psychology interventions raise subjective and psychological well-being and reduce depressive symptoms with small-to-medium effects, larger for depressed, older and self-selected participants and for longer, individual formats. White, Uttl and Holder's 2019 re-analysis showed these were inflated by small studies; Carr's 2021 meta-analysis still finds small-to-medium effects that persist to follow-up, and a 2026 network meta-analysis of 183 RCTs rates single positive-psychology interventions at moderate effect, no better than mindfulness, yoga or exercise. Multicomponent programs in clinical samples give small but real gains.",
    action: "Run a two-week trial of one exercise (three good things nightly, or a weekly gratitude letter) and rate your mood 1–10 each evening on paper. Keep it if the average rises; drop it without guilt if it does not — the literature says both outcomes are normal.",
    sources: [
      { cite: "Sin, N. L., & Lyubomirsky, S. (2009). Enhancing well-being and alleviating depressive symptoms with positive psychology interventions: a practice-friendly meta-analysis. Journal of Clinical Psychology.", note: "Meta-analysis of 51 interventions (4,266 people): positive psychology interventions enhanced well-being (mean r = .29) and reduced depressive symptoms (r = .31), with larger effects for depressed, older and motivated participants and for longer individual formats.", link: doi("10.1002/jclp.20593"), kind: "doi" },
      { cite: "Bolier, L., Haverman, M., Westerhof, G. J., Riper, H., Smit, F., & Bohlmeijer, E. (2013). Positive psychology interventions: a meta-analysis of randomized controlled studies. BMC Public Health.", note: "Meta-analysis of 39 RCTs (6,139 participants): small effects on subjective well-being (SMD 0.34), psychological well-being (0.20) and depression (0.23), still significant at 3–6 months, with indications of publication bias.", link: doi("10.1186/1471-2458-13-119"), kind: "doi" },
      { cite: "White, C. A., Uttl, B., & Holder, M. D. (2019). Meta-analyses of positive psychology interventions: The effects are much smaller than previously reported. PloS one, 14(5), e0216588.", note: "Re-analysis correcting for small-sample bias: the effects reported by the two previous meta-analyses were much smaller than claimed.", link: doi("10.1371/journal.pone.0216588"), kind: "doi" },
      { cite: "Carr, A., Cullen, K., Keeney, C., Canning, C., Mooney, O., Chinseallaigh, E., & O'Dowd, A. (2021). Effectiveness of positive psychology interventions: a systematic review and meta-analysis. The Journal of Positive Psychology, 16(6), 749-769.", note: "Meta-analysis of positive psychology interventions reporting small-to-medium effects on well-being, strengths, quality of life, depression, anxiety and stress, maintained at follow-up.", link: doi("10.1080/17439760.2020.1818807"), kind: "doi" },
      { cite: "Chakhssi, F., Kraiss, J. T., Sommers-Spijkerman, M., & Bohlmeijer, E. T. (2018). The effect of positive psychology interventions on well-being and distress in clinical samples with psychiatric or somatic disorders: a systematic review and meta-analysis. BMC Psychiatry.", note: "In clinical samples (30 studies, 1,864 patients): small effects on well-being (g = 0.24) and depression (0.23) and moderate on anxiety (0.36), similar at 8–12-week follow-up; study quality low to moderate.", link: doi("10.1186/s12888-018-1739-2"), kind: "doi" },
      { cite: "Wilkie, L., Fisher, Z., Geidel, A., Goodall, I., Kamil, S., Davies, E., & Kemp, A. H. (2026). A systematic review and network meta-analysis of randomized controlled trials of well-being-focused interventions. Nature Human Behaviour.", note: "Network meta-analysis of 183 RCTs (n = 22,811): most interventions beat inactive controls; single positive psychology interventions, mindfulness, compassion, yoga and exercise all showed moderate effects (SMD 0.41–0.49) with no significant differences between them.", link: doi("10.1038/s41562-025-02369-1"), kind: "doi" },
      { cite: "Seligman, M. E., Steen, T. A., Park, N., & Peterson, C. (2005). Positive psychology progress: empirical validation of interventions. American Psychologist, 60(5), 410-21.", note: "Seligman's six-arm internet RCT: three of five exercises (including 'three good things' and using signature strengths in a new way) lastingly increased happiness and decreased depressive symptoms.", link: doi("10.1037/0003-066X.60.5.410"), kind: "doi" },
      { cite: "Mongrain, M., & Anselmo-Matthews, T. (2012). Do positive psychology exercises work? A replication of Seligman et al. (2005). Journal of Clinical Psychology, 68(4), 382-9.", note: "Replication of that trial with a better control: the exercises raised happiness, but so did a 'positive placebo', and effects on depression were more modest than first assumed.", link: doi("10.1002/jclp.21839"), kind: "doi" },
    ],
  },
  {
    id: "gs-happiness-gratitude",
    goal: "happiness", tier: "fundamental", section: "8302",
    title: "Gratitude: Three Things, Most Nights",
    subtitle: "Beats doing nothing; barely beats any other active exercise",
    evidenceTag: "Moderate",
    impact: { magnitude: 2, latency: "weeks", durability: "transient", effort: "low" },
    feeds: ["positive affect", "optimism about the week", "relationship warmth"],
    description:
      "Emmons and McCullough's experiments found weekly and daily gratitude lists raised well-being relative to hassles or neutral lists. Meta-analyses since are sobering: gratitude interventions outperform measurement-only controls on well-being (d ≈ .31) but perform no better than a psychologically active comparison, and their effects on depression and anxiety symptoms are small. Still cheap, still harmless, still slightly positive — a fundamental, not a cure.",
    action: "Before bed, write three specific things that went well today and why, five nights a week for a month. Once a month write one gratitude letter to a person and read it to them.",
    sources: [
      { cite: "Emmons, R. A., & McCullough, M. E. (2003). Counting blessings versus burdens: an experimental investigation of gratitude and subjective well-being in daily life. Journal of personality and social psychology, 84(2), 377-89.", note: "Three experimental studies: participants who listed blessings weekly or daily reported higher well-being than those listing hassles or neutral events, with some effects on health behaviours and helping.", link: doi("10.1037/0022-3514.84.2.377"), kind: "doi" },
      { cite: "Wood, A. M., Froh, J. J., & Geraghty, A. W. (2010). Gratitude and well-being: a review and theoretical integration. Clinical psychology review, 30(7), 890-905.", note: "Review and theoretical integration of gratitude and well-being: gratitude is strongly related to well-being and interventions are promising, but the literature had neglected its own limitations.", link: doi("10.1016/j.cpr.2010.03.005"), kind: "doi" },
      { cite: "Davis, D. E., Choe, E., Meyers, J., Wade, N., Varjas, K., Gifford, A., …, & Worthington, E. L. (2016). Thankful for the little things: A meta-analysis of gratitude interventions. Journal of Counseling Psychology, 63(1), 20-31.", note: "Meta-analyses of gratitude interventions: better than measurement-only controls on well-being (d = .31) but no better than psychologically active comparisons (d = −.03), with no effect on anxiety.", link: doi("10.1037/cou0000107"), kind: "doi" },
      { cite: "Cregg, D. R., & Cheavens, J. S. (2021). Gratitude Interventions: Effective Self-help? A Meta-analysis of the Impact on Symptoms of Depression and Anxiety. Journal of Happiness Studies, 22(1), 413-445.", note: "Meta-analysis of gratitude interventions on depression and anxiety symptoms: small effects, leading the authors to question gratitude as stand-alone self-help for clinical symptoms.", link: doi("10.1007/s10902-020-00236-6"), kind: "doi" },
    ],
  },
  {
    id: "gs-happiness-savoring",
    goal: "happiness", tier: "fundamental", section: "8303",
    title: "Savoring: Stretch the Good Moments",
    subtitle: "Daily-diary and older-adult trials show a modest lift in positive affect",
    evidenceTag: "Emerging",
    impact: { magnitude: 2, latency: "weeks", durability: "transient", effort: "low" },
    feeds: ["positive affect", "resilience", "counter to hedonic adaptation"],
    description:
      "Savoring — deliberately attending to, sharing and prolonging positive experiences — raised happiness on days when people used it in a diary study; a one-week savoring program improved resilience, depressive symptoms and happiness in older adults who did it faithfully; and a three-week Facebook-based savoring exercise raised positive affect (but not lowered negative affect) in students. The hedonic-adaptation-prevention model explains the mechanism: continued appreciation and variety keep a positive change from fading. Effects are small and mostly short-term.",
    action: "Once a day for a month, pick one good moment (coffee, a walk, a laugh) and spend two full minutes noticing it — sensory detail, what it means, whom to tell. Vary the moment; sameness is what kills the effect.",
    sources: [
      { cite: "Jose, P. E., Lim, B. T., & Bryant, F. B. (2012). Does savoring increase happiness? A daily diary study. The Journal of Positive Psychology, 7(3), 176-187.", note: "Daily diary study: on days when people savored positive events more, they reported greater happiness, with savoring moderating the effect of positive events.", link: doi("10.1080/17439760.2012.671345"), kind: "doi" },
      { cite: "Smith, J. L., & Hanni, A. A. (2019). Effects of a Savoring Intervention on Resilience and Well-Being of Older Adults. Journal of Applied Gerontology, 38(1), 137-152.", note: "Pilot of a one-week savoring intervention in 111 adults aged 60+: those who completed it with high fidelity improved in resilience, depressive symptoms and happiness over three months.", link: doi("10.1177/0733464817693375"), kind: "doi" },
      { cite: "Yu, S. C., Sheldon, K. M., Lan, W. P., & Chen, J. H. (2020). Using Social Network Sites to Boost Savoring: Positive Effects on Positive Emotions. International Journal of Environmental Research and Public Health, 17(17).", note: "RCT of a three-week savoring intervention delivered via Facebook (n = 122 students): positive affect rose at post-test and follow-up; negative affect did not change.", link: doi("10.3390/ijerph17176407"), kind: "doi" },
      { cite: "Sheldon, K. M., & Lyubomirsky, S. (2012). The challenge of staying happier: testing the Hedonic Adaptation Prevention model. Personality and Social Psychology Bulletin, 38(5), 670-80.", note: "Three-wave test of the Hedonic Adaptation Prevention model: continued appreciation and variety in a positive change forestalled its fade-out.", link: doi("10.1177/0146167212436400"), kind: "doi" },
    ],
  },
  {
    id: "gs-happiness-acts-of-kindness",
    goal: "happiness", tier: "fundamental", section: "8304",
    title: "Acts of Kindness and Prosocial Spending",
    subtitle: "A small-to-medium effect that replicates across cultures",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "low" },
    feeds: ["positive affect", "social connection", "peer acceptance in children"],
    description:
      "A meta-analysis of experimental studies finds performing acts of kindness raises the actor's well-being with a small-to-medium effect, and randomized spending experiments show that giving money to others produces more happiness than spending on oneself — a pattern that held in survey data from 136 countries and in experiments on three continents. Loving-kindness meditation, a related practice, built positive emotions that in turn increased life satisfaction. The effect is real and modest; it is one of the more robust items on the shelf.",
    action: "Do three deliberate kind acts on one day each week for a month (a specific favour, a thank-you to someone who is rarely thanked, a small gift), and redirect a small fixed sum monthly from spending on yourself to spending on someone else.",
    sources: [
      { cite: "Curry, O. S., Rowland, L. A., Van Lissa, C. J., Zlotowitz, S., McAlaney, J., & Whitehouse, H. (2018). Happy to help? A systematic review and meta-analysis of the effects of performing acts of kindness on the well-being of the actor. Journal of Experimental Social Psychology, 76, 320-329.", note: "Systematic review and meta-analysis of experimental studies: performing acts of kindness improved the well-being of the actor, with a small-to-medium effect.", link: doi("10.1016/j.jesp.2018.02.014"), kind: "doi" },
      { cite: "Dunn, E. W., Aknin, L. B., & Norton, M. I. (2008). Spending money on others promotes happiness. Science, 319(5870), 1687-8.", note: "Cross-sectional, longitudinal and experimental evidence that spending money on others promotes happiness more than spending on oneself.", link: doi("10.1126/science.1150952"), kind: "doi" },
      { cite: "Aknin, L. B., Barrington-Leigh, C. P., Dunn, E. W., Helliwell, J. F., Burns, J., Biswas-Diener, R., …, & Norton, M. I. (2013). Prosocial spending and well-being: cross-cultural evidence for a psychological universal. Journal of Personality and Social Psychology, 104(4), 635-52.", note: "Prosocial spending associated with happiness in 136 countries, and experiments in Canada, Uganda, India and South Africa showing a causal effect on positive affect.", link: doi("10.1037/a0031578"), kind: "doi" },
      { cite: "Layous, K., Nelson, S. K., Oberle, E., Schonert-Reichl, K. A., & Lyubomirsky, S. (2012). Kindness counts: prompting prosocial behavior in preadolescents boosts peer acceptance and well-being. PLoS One, 7(12), e51380.", note: "Classroom experiment: 9–11-year-olds assigned to three weekly kind acts gained more peer acceptance than controls while both groups' well-being improved.", link: doi("10.1371/journal.pone.0051380"), kind: "doi" },
      { cite: "Fredrickson, B. L., Cohn, M. A., Coffey, K. A., Pek, J., & Finkel, S. M. (2008). Open hearts build lives: positive emotions, induced through loving-kindness meditation, build consequential personal resources. Journal of Personality and Social Psychology, 95(5), 1045-1062.", note: "Field experiment with 139 working adults: loving-kindness meditation increased daily positive emotions, which built personal resources and raised life satisfaction.", link: doi("10.1037/a0013262"), kind: "doi" },
    ],
  },
  {
    id: "gs-happiness-relationship-portfolio",
    goal: "happiness", tier: "elite", section: "8305",
    title: "Build the Relationship Portfolio — the Harvard Study's One Finding",
    subtitle: "Close relationships predict health and happiness into the ninth decade",
    evidenceTag: "Strong",
    impact: { magnitude: 5, latency: "months", durability: "lasting", effort: "high" },
    feeds: ["daily happiness", "late-life security", "mortality risk"],
    description:
      "The most replicated finding in the well-being literature is that social relationships predict survival: a meta-analysis of 148 studies found a 50% higher likelihood of survival with stronger social relationships, and loneliness and isolation carry mortality risks comparable to established health factors. The Harvard Study of Adult Development, following men for 60–80 years, found that variables under personal control predicted good aging, that nurturing childhoods predicted late-life security, and that in octogenarian couples daily happiness still tracked relationship quality. This is elite because it is a multi-decade investment; loneliness interventions that address maladaptive social cognition work best when the portfolio has gaps.",
    action: "Draw your relationship portfolio this month — five people you would call at 3 a.m., ten you would want at a milestone — and schedule a fixed weekly contact with two of the inner five and a monthly one with the rest, for the rest of the year. Treat a missed month like a missed mortgage payment.",
    sources: [
      { cite: "Holt-Lunstad, J., Smith, T. B., & Layton, J. B. (2010). Social relationships and mortality risk: a meta-analytic review. PLoS medicine, 7(7), e1000316.", note: "Meta-analysis of 148 studies (308,849 participants): people with stronger social relationships had a 50% increased likelihood of survival, an effect comparable to quitting smoking.", link: doi("10.1371/journal.pmed.1000316"), kind: "doi" },
      { cite: "Holt-Lunstad, J., Smith, T. B., Baker, M., Harris, T., & Stephenson, D. (2015). Loneliness and social isolation as risk factors for mortality: a meta-analytic review. Perspectives on psychological science : a journal of the Association for Psychological Science, 10(2), 227-37.", note: "Meta-analytic review: social isolation (OR 1.29), loneliness (OR 1.26) and living alone (OR 1.32) each predicted increased mortality — a 26–32% higher likelihood.", link: doi("10.1177/1745691614568352"), kind: "doi" },
      { cite: "Vaillant, G. E., & Mukamal, K. (2001). Successful aging. American Journal of Psychiatry, 158(6), 839-47.", note: "Two Harvard cohorts followed 60 years: successful aging at 70–80 was predicted by variables assessed before age 50, most of them under personal control.", link: doi("10.1176/appi.ajp.158.6.839"), kind: "doi" },
      { cite: "Waldinger, R. J., & Schulz, M. S. (2016). The Long Reach of Nurturing Family Environments: Links With Midlife Emotion-Regulatory Styles and Late-Life Security in Intimate Relationships. Psychological science, 27(11), 1443-1450.", note: "Harvard Study men: nurturing family environments in childhood predicted midlife emotion regulation and late-life attachment security.", link: doi("10.1177/0956797616661556"), kind: "doi" },
      { cite: "Waldinger, R. J., & Schulz, M. S. (2010). What's love got to do with it? Social functioning, perceived health, and daily happiness in married octogenarians. Psychology and aging, 25(2), 422-31.", note: "Married octogenarians: daily happiness was tied to social functioning and relationship quality, not only to health.", link: doi("10.1037/a0019087"), kind: "doi" },
      { cite: "Masi, C. M., Chen, H. Y., Hawkley, L. C., & Cacioppo, J. T. (2011). A meta-analysis of interventions to reduce loneliness. Personality and Social Psychology Review, 15(3), 219-66.", note: "Meta-analysis of loneliness interventions: in randomized comparisons the most effective addressed maladaptive social cognition rather than simply adding social contact.", link: doi("10.1177/1088868310377394"), kind: "doi" },
      { cite: "Repetti, R. L., Taylor, S. E., & Seeman, T. E. (2002). Risky families: Family social environments and the mental and physical health of offspring. Psychological Bulletin, 128(2), 330-366.", note: "The 'risky families' review: cold, conflictual family environments in childhood create cascading risks for adult mental and physical health — the relationship portfolio starts early.", link: doi("10.1037/0033-2909.128.2.330"), kind: "doi" },
    ],
  },
  {
    id: "gs-happiness-exercise-for-mood",
    goal: "happiness", tier: "moderate", section: "8306",
    title: "Exercise as an Antidepressant",
    subtitle: "Walking, jogging, yoga and strength training all work; intensity helps",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "weeks", durability: "sustained", effort: "moderate" },
    feeds: ["mood", "energy", "sleep"],
    description:
      "The 2024 BMJ network meta-analysis of 218 randomized trials found walking or jogging, yoga and strength training produced moderate reductions in depression, with more vigorous activity doing more; Schuch's meta-analysis showed the effect survives adjustment for publication bias and is large in the best studies; and the Cochrane review, updated in 2026, finds exercise moderately more effective than no treatment for depressive symptoms. Effects in the network meta-analysis were comparable to psychotherapy. This is among the few protocols with a hard clinical outcome behind it.",
    action: "Three sessions a week of 30–45 minutes for the next eight weeks — brisk walking or jogging, a strength session, or yoga — at an intensity where talking is slightly hard. Put them in the calendar as appointments and track completion, not mood, for the first month.",
    sources: [
      { cite: "Noetel, M., Sanders, T., Gallardo-Gómez, D., Taylor, P., Del Pozo Cruz, B., van den Hoek, D., …, & Lonsdale, C. (2024). Effect of exercise for depression: systematic review and network meta-analysis of randomised controlled trials. BMJ (Clinical research ed.), 384, e075847.", note: "Network meta-analysis of 218 RCTs (14,170 participants): walking or jogging, yoga and strength training reduced depression with moderate effects, larger with more vigorous intensity and comparable to psychotherapy.", link: doi("10.1136/bmj-2023-075847"), kind: "doi" },
      { cite: "Schuch, F. B., Vancampfort, D., Richards, J., Rosenbaum, S., Ward, P. B., & Stubbs, B. (2016). Exercise as a treatment for depression: A meta-analysis adjusting for publication bias. Journal of psychiatric research, 77, 42-51.", note: "Meta-analysis adjusting for publication bias: exercise remained a large-effect treatment for depression, especially in higher-quality trials.", link: doi("10.1016/j.jpsychires.2016.02.023"), kind: "doi" },
      { cite: "Cooney, G. M., Dwan, K., Greig, C. A., Lawlor, D. A., Rimer, J., Waugh, F. R., …, & Mead, G. E. (2013). Exercise for depression. The Cochrane database of systematic reviews, 2013(9), CD004366.", note: "Cochrane review (2013): exercise was moderately more effective than control for reducing depressive symptoms, with smaller effects in the most rigorous trials.", link: doi("10.1002/14651858.CD004366.pub6"), kind: "doi" },
      { cite: "Clegg, A. J., Hill, J. E., Mullin, D. S., Harris, C., Smith, C. J., Lightbody, C. E., …, & Watkins, C. L. (2026). Exercise for depression. The Cochrane database of systematic reviews, 1(1), CD004366.", note: "Updated Cochrane review (2026) of exercise for depression in adults compared with no intervention, waiting list, placebo and active treatments.", link: doi("10.1002/14651858.CD004366.pub7"), kind: "doi" },
    ],
  },
  {
    id: "gs-happiness-sleep-first",
    goal: "happiness", tier: "fundamental", section: "8307",
    title: "Fix Sleep Before Anything Else",
    subtitle: "Improving sleep causally improves mental health — a dose–response effect",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "weeks", durability: "sustained", effort: "moderate" },
    feeds: ["mood", "emotional regulation", "anxiety"],
    description:
      "A meta-analysis of 65 randomized trials found that interventions which improved sleep quality produced medium-sized improvements in composite mental health (g = −0.53), depression (−0.63) and anxiety (−0.51), with greater sleep gains producing greater mental-health gains — the strongest causal evidence on this shelf for a daily behaviour. Insomnia predicts later depression in longitudinal studies, and sleep loss disrupts emotional processing in the lab. Everything else here works better on seven hours.",
    action: "For one month, fix a wake time seven days a week, get light within 30 minutes of waking, stop caffeine by 2 p.m. and screens 45 minutes before bed, and track sleep on paper. If insomnia persists after four weeks, ask a clinician about cognitive-behavioural therapy for insomnia, the first-line treatment.",
    sources: [
      { cite: "Scott, A. J., Webb, T. L., Martyn-St James, M., Rowse, G., & Weich, S. (2021). Improving sleep quality leads to better mental health: A meta-analysis of randomised controlled trials. Sleep Medicine Reviews, 60, 101556.", note: "Meta-analysis of 65 RCTs (n = 8,608): improving sleep quality led to medium effects on composite mental health, depression and anxiety, with a dose–response relationship.", link: doi("10.1016/j.smrv.2021.101556"), kind: "doi" },
      { cite: "Baglioni, C., Battagliese, G., Feige, B., Spiegelhalder, K., Nissen, C., Voderholzer, U., …, & Riemann, D. (2011). Insomnia as a predictor of depression: a meta-analytic evaluation of longitudinal epidemiological studies. Journal of affective disorders, 135(1-3), 10-9.", note: "Meta-analysis of longitudinal epidemiological studies: insomnia at baseline predicted depression at follow-up, supporting insomnia as an independent clinical predictor.", link: doi("10.1016/j.jad.2011.01.011"), kind: "doi" },
      { cite: "Walker, M. P. (2009). The role of sleep in cognition and emotion. Annals of the New York Academy of Sciences, 1156, 168-97.", note: "Review of sleep's role in cognition and emotion, including the disruption of emotional regulation by sleep loss.", link: doi("10.1111/j.1749-6632.2009.04416.x"), kind: "doi" },
    ],
  },
  {
    id: "gs-happiness-nature-120",
    goal: "happiness", tier: "fundamental", section: "8308",
    title: "Two Hours a Week in Nature",
    subtitle: "A threshold effect in 20,000 people, plus experiments on rumination",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "low" },
    feeds: ["rumination", "self-reported health", "positive affect"],
    description:
      "In a nationally representative English sample of nearly 20,000 people, those who spent at least 120 minutes a week in natural environments were substantially more likely to report good health and high well-being, with the pattern holding regardless of how the time was split. A 90-minute walk in nature reduced rumination and activity in the subgenual prefrontal cortex compared with an urban walk, and a meta-analysis of greenspace exposure links it to lower cortisol, heart rate and risk of preterm birth and type 2 diabetes. Honest boundary: the 2026 network meta-analysis found nature-based programs did not beat controls, so treat nature as a setting for movement and rest, not a therapy.",
    action: "Schedule 120 minutes a week outdoors in green or blue space for the next month — two one-hour walks or four half-hours — and do at least one without headphones.",
    sources: [
      { cite: "White, M. P., Alcock, I., Grellier, J., Wheeler, B. W., Hartig, T., Warber, S. L., …, & Fleming, L. E. (2019). Spending at least 120 minutes a week in nature is associated with good health and wellbeing. Scientific reports, 9(1), 7730.", note: "Cross-sectional study of 19,806 people: at least 120 minutes a week in nature was associated with good health and high well-being, whether taken in one visit or several.", link: doi("10.1038/s41598-019-44097-3"), kind: "doi" },
      { cite: "Bratman, G. N., Hamilton, J. P., Hahn, K. S., Daily, G. C., & Gross, J. J. (2015). Nature experience reduces rumination and subgenual prefrontal cortex activation. Proceedings of the National Academy of Sciences of the United States of America, 112(28), 8567-72.", note: "Experiment: a 90-minute nature walk reduced self-reported rumination and subgenual prefrontal cortex activation compared with an urban walk.", link: doi("10.1073/pnas.1510459112"), kind: "doi" },
      { cite: "Bratman, G. N., Young, G., Mehta, A., Lee Babineaux, I., Daily, G. C., & Gross, J. J. (2021). Affective Benefits of Nature Contact: The Role of Rumination. Frontiers in psychology, 12, 643866.", note: "Review of the affective benefits of nature contact with rumination as a mechanism.", link: doi("10.3389/fpsyg.2021.643866"), kind: "doi" },
      { cite: "Twohig-Bennett, C., & Jones, A. (2018). The health benefits of the great outdoors: A systematic review and meta-analysis of greenspace exposure and health outcomes. Environmental research, 166, 628-637.", note: "Systematic review and meta-analysis of greenspace exposure: associations with lower salivary cortisol, heart rate, diastolic blood pressure and risk of several diseases.", link: doi("10.1016/j.envres.2018.06.030"), kind: "doi" },
    ],
  },
  {
    id: "gs-happiness-purpose",
    goal: "happiness", tier: "moderate", section: "8309",
    title: "Meaning and Purpose: Name It, Serve It",
    subtitle: "Purpose predicts mortality; volunteering and generativity are the training",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "months", durability: "lasting", effort: "moderate" },
    feeds: ["purpose in life", "resilience", "lower mortality risk"],
    description:
      "Purpose in life predicts lower mortality across adulthood (MIDUS) and, in a meta-analysis of ten prospective studies with 136,265 people, lower all-cause mortality and fewer cardiovascular events. The Meaning in Life Questionnaire separates having meaning from searching for it — the search alone does not carry the benefit. In the Health and Retirement Study, taking up 100+ hours of volunteering a year predicted higher purpose and optimism four years later, the most practical lever the literature offers.",
    action: "Write a one-sentence purpose statement this week ('I use X to help Y so that Z') and pick one weekly activity that serves it — mentoring, a cause, a craft that someone else benefits from. Review the sentence quarterly; rewrite it when it stops being true.",
    sources: [
      { cite: "Steger, M. F., Frazier, P., Oishi, S., & Kaler, M. (2006). The meaning in life questionnaire: Assessing the presence of and search for meaning in life. Journal of Counseling Psychology, 53(1), 80-93.", note: "The Meaning in Life Questionnaire, distinguishing presence of meaning from search for meaning.", link: doi("10.1037/0022-0167.53.1.80"), kind: "doi" },
      { cite: "Hill, P. L., & Turiano, N. A. (2014). Purpose in life as a predictor of mortality across adulthood. Psychological science, 25(7), 1482-6.", note: "MIDUS: purpose in life predicted lower mortality over 14 years across adulthood.", link: doi("10.1177/0956797614531799"), kind: "doi" },
      { cite: "Cohen, R., Bavishi, C., & Rozanski, A. (2016). Purpose in Life and Its Relationship to All-Cause Mortality and Cardiovascular Events: A Meta-Analysis. Psychosomatic medicine, 78(2), 122-33.", note: "Meta-analysis of 10 prospective studies (n = 136,265): higher purpose in life associated with lower all-cause mortality and cardiovascular events.", link: doi("10.1097/PSY.0000000000000274"), kind: "doi" },
      { cite: "Kim, E. S., Whillans, A. V., Lee, M. T., Chen, Y., & VanderWeele, T. J. (2020). Volunteering and Subsequent Health and Well-Being in Older Adults: An Outcome-Wide Longitudinal Approach. American Journal of Preventive Medicine, 59(2), 176-186.", note: "Health and Retirement Study: volunteering 100+ hours a year predicted higher purpose in life, positive affect and optimism and lower loneliness four years later.", link: doi("10.1016/j.amepre.2020.03.004"), kind: "doi" },
      { cite: "Cohen, G. L., & Sherman, D. K. (2014). The psychology of change: self-affirmation and social psychological intervention. Annual review of psychology, 65, 333-71.", note: "Review of self-affirmation: brief writing about core values buffers threat and can change behaviour over long periods through recursive processes — the values half of purpose.", link: doi("10.1146/annurev-psych-010213-115137"), kind: "doi" },
      { cite: "de St. Aubin, E., & McAdams, D. P. (1995). The relations of generative concern and generative action to personality traits, satisfaction/happiness with life, and ego development. Journal of Adult Development, 2(2), 99-112.", note: "Generative concern and generative action were related to satisfaction and happiness with life — caring for what outlives you is a route to meaning.", link: doi("10.1007/BF02251258"), kind: "doi" },
      { cite: "Gruenewald, T. L., Liao, D. H., & Seeman, T. E. (2012). Contributing to others, contributing to oneself: perceptions of generativity and health in later life. The journals of gerontology. Series B, Psychological sciences and social sciences, 67(6), 660-5.", note: "Older adults who perceived themselves as generative contributors reported better health and fewer functional limitations.", link: doi("10.1093/geronb/gbs034"), kind: "doi" },
    ],
  },
  {
    id: "gs-happiness-expect-adaptation",
    goal: "happiness", tier: "fundamental", section: "8310",
    title: "Expect Adaptation — Plan Around It",
    subtitle: "The set point is real but not fixed; events fade unevenly",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "months", durability: "sustained", effort: "low" },
    feeds: ["realistic expectations", "protection against chasing purchases", "recovery from setbacks"],
    description:
      "Twin data show 44–52% of the variance in well-being is genetic and the stable component is highly heritable, yet the revised adaptation theory shows set points differ between people, can shift, and that life satisfaction and affect adapt at different rates. A meta-analysis of 188 studies found adaptation varies by event — cognitive well-being reacts more than affective, and unemployment and bereavement are not fully adapted to — and people who married returned to baseline on average while individual trajectories varied widely. The practical lesson: build variety and appreciation into good changes, and do not expect a purchase to last.",
    action: "Before any major happiness purchase or move this year, write down what you expect to feel in six months, then check. For the good changes you already have, apply the two anti-adaptation moves: vary how you enjoy them and name one thing you appreciate about them weekly.",
    sources: [
      { cite: "Lykken, D., & Tellegen, A. (1996). Happiness Is a Stochastic Phenomenon. Psychological Science, 7(3), 186-189.", note: "Twin study of several thousand middle-aged adults: 44–52% of the variance in well-being was associated with genetic variation, and the heritability of the stable component approached 80%.", link: doi("10.1111/j.1467-9280.1996.tb00355.x"), kind: "doi" },
      { cite: "Diener, E., Lucas, R. E., & Scollon, C. N. (2006). Beyond the hedonic treadmill: revising the adaptation theory of well-being. American Psychologist, 61(4), 305-14.", note: "Five revisions to the hedonic-treadmill model: set points are not neutral, differ between people, are multiple, can change, and adaptation varies between individuals.", link: doi("10.1037/0003-066X.61.4.305"), kind: "doi" },
      { cite: "Lucas, R. E., Clark, A. E., Georgellis, Y., & Diener, E. (2003). Reexamining adaptation and the set point model of happiness: reactions to changes in marital status. Journal of personality and social psychology, 84(3), 527-39.", note: "15-year German panel: on average people adapted back to baseline after marriage, but individual differences in adaptation were large.", link: doi("10.1037/0022-3514.84.3.527"), kind: "doi" },
      { cite: "Luhmann, M., Hofmann, W., Eid, M., & Lucas, R. E. (2012). Subjective well-being and adaptation to life events: a meta-analysis. Journal of Personality and Social Psychology, 102(3), 592-615.", note: "Meta-analysis of 188 publications (n = 65,911): life events had different effects on affective versus cognitive well-being, and rates of adaptation differed sharply across events.", link: doi("10.1037/a0025948"), kind: "doi" },
      { cite: "Sheldon, K. M., & Lyubomirsky, S. (2012). The challenge of staying happier: testing the Hedonic Adaptation Prevention model. Personality and Social Psychology Bulletin, 38(5), 670-80.", note: "Longitudinal test of the Hedonic Adaptation Prevention model: continued appreciation and variety slowed the erosion of gains from a positive change.", link: doi("10.1177/0146167212436400"), kind: "doi" },
    ],
  },
  {
    id: "gs-happiness-money-honest",
    goal: "happiness", tier: "moderate", section: "8311",
    title: "Money and Happiness: the Adversarial Collaboration's Answer",
    subtitle: "Rises with income for most people; flattens only for the least happy",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "months", durability: "sustained", effort: "moderate" },
    feeds: ["financial decisions grounded in evidence", "time–money trade-offs"],
    description:
      "Kahneman and Deaton found life evaluation kept rising with income while emotional well-being plateaued around $75,000; Killingsworth's experience-sampling study of 33,000 people found experienced well-being kept rising above that. Their 2023 adversarial collaboration resolved it: happiness rises with income for most people, and the plateau exists only for the least happy people. How money is spent matters too — spending on others and buying time (outsourcing disliked tasks) both raise well-being in experiments.",
    action: "Treat income growth as a real but diminishing lever, and audit spending this month for two moves with evidence: a monthly time-saving purchase (a task you dislike, done by someone else) and a monthly prosocial one. Notice which of the two you feel more.",
    sources: [
      { cite: "Kahneman, D., & Deaton, A. (2010). High income improves evaluation of life but not emotional well-being. Proceedings of the National Academy of Sciences of the United States of America, 107(38), 16489-93.", note: "450,000 Gallup responses: life evaluation rose steadily with log income, but emotional well-being did not improve beyond about $75,000 a year.", link: doi("10.1073/pnas.1011492107"), kind: "doi" },
      { cite: "Killingsworth, M. A. (2021). Experienced well-being rises with income, even above $75,000 per year. Proceedings of the National Academy of Sciences of the United States of America, 118(4).", note: "1,725,994 experience-sampling reports from 33,391 employed US adults: experienced and evaluative well-being rose linearly with log income, with no plateau above $75,000.", link: doi("10.1073/pnas.2016976118"), kind: "doi" },
      { cite: "Killingsworth, M. A., Kahneman, D., & Mellers, B. (2023). Income and emotional well-being: A conflict resolved. Proceedings of the National Academy of Sciences of the United States of America, 120(10), e2208661120.", note: "Adversarial collaboration between Killingsworth, Kahneman and Mellers: reanalysis confirmed the flattening pattern only for the least happy people; happiness rises steadily with log income among happier people and accelerates in the happiest group.", link: doi("10.1073/pnas.2208661120"), kind: "doi" },
      { cite: "Whillans, A. V., Dunn, E. W., Smeets, P., Bekkers, R., & Norton, M. I. (2017). Buying time promotes happiness. Proceedings of the National Academy of Sciences of the United States of America, 114(32), 8523-8527.", note: "Surveys in four countries and a field experiment: spending money on time-saving services was associated with greater life satisfaction and raised end-of-day positive affect.", link: doi("10.1073/pnas.1706541114"), kind: "doi" },
      { cite: "Lee-Yoon, A., & Whillans, A. V. (2018). Making seconds count: when valuing time promotes subjective well-being. Current Opinion in Psychology, 26, 54-57.", note: "Review of when valuing time over money promotes well-being, and the emotional costs of valuing time like money.", link: doi("10.1016/j.copsyc.2018.05.002"), kind: "doi" },
      { cite: "Dunn, E. W., Aknin, L. B., & Norton, M. I. (2008). Spending money on others promotes happiness. Science, 319(5870), 1687-8.", note: "Randomly assigned spending on others produced more happiness than spending on oneself.", link: doi("10.1126/science.1150952"), kind: "doi" },
    ],
  },
  {
    id: "gs-happiness-time-affluence",
    goal: "happiness", tier: "elite", section: "8312",
    title: "Redesign for Time: Cut the Commute, Buy Back Hours",
    subtitle: "The commuting paradox and the case for working near home",
    evidenceTag: "Moderate",
    impact: { magnitude: 4, latency: "months", durability: "lasting", effort: "high" },
    feeds: ["leisure satisfaction", "strain and mental health", "daily positive affect"],
    description:
      "Panel data show people with longer commutes report systematically lower well-being — the 'commuting paradox', because in theory the housing or wage market should compensate — and six waves of UK panel data find longer commutes lower job and leisure satisfaction and raise strain, with walking commutes and working from home associated with better outcomes. Day-reconstruction data rank the morning commute among the least pleasant daily episodes. Buying time raises life satisfaction. This is elite because the fix — where you live and work — is a multi-year, high-cost decision with a durable payoff.",
    action: "Within the next year, make one structural time decision: negotiate two work-from-home days, move within a walkable or cyclable commute, or restructure the job. Until then, buy back two hours a week (cleaning, meals, errands) and protect them for leisure or people.",
    sources: [
      { cite: "Stutzer, A., & Frey, B. S. (2008). Stress that Doesn't Pay: The Commuting Paradox. The Scandinavian Journal of Economics, 110(2), 339-366.", note: "German panel data: people with longer commuting times reported systematically lower subjective well-being, robust to alternative explanations — the commuting paradox.", link: doi("10.1111/j.1467-9442.2008.00542.x"), kind: "doi" },
      { cite: "Clark, B., Chatterjee, K., Martin, A., & Davis, A. (2020). How commuting affects subjective wellbeing. Transportation, 47(6), 2777-2805.", note: "Six waves of Understanding Society (26,000+ workers): longer commutes were associated with lower job and leisure satisfaction, more strain and poorer mental health; walking commutes and working from home fared better.", link: doi("10.1007/s11116-019-09983-9"), kind: "doi" },
      { cite: "Whillans, A. V., Dunn, E. W., Smeets, P., Bekkers, R., & Norton, M. I. (2017). Buying time promotes happiness. Proceedings of the National Academy of Sciences of the United States of America, 114(32), 8523-8527.", note: "Buying time — paying to outsource disliked tasks — was associated with greater life satisfaction across countries and raised positive affect in a field experiment.", link: doi("10.1073/pnas.1706541114"), kind: "doi" },
      { cite: "Kahneman, D., Krueger, A. B., Schkade, D. A., Schwarz, N., & Stone, A. A. (2004). A survey method for characterizing daily life experience: the day reconstruction method. Science, 306(5702), 1776-80.", note: "The Day Reconstruction Method, which documented how people experience the episodes of a day, including the low affect of commuting.", link: doi("10.1126/science.1103572"), kind: "doi" },
      { cite: "Lee-Yoon, A., & Whillans, A. V. (2018). Making seconds count: when valuing time promotes subjective well-being. Current Opinion in Psychology, 26, 54-57.", note: "Conceptual review of when valuing time promotes well-being.", link: doi("10.1016/j.copsyc.2018.05.002"), kind: "doi" },
    ],
  },
  {
    id: "gs-happiness-social-media-diet",
    goal: "happiness", tier: "moderate", section: "8313",
    title: "A Social-Media Diet: Limit, Don't Panic",
    subtitle: "Correlations are tiny; the deactivation experiments show a real but modest gain",
    evidenceTag: "Mixed",
    impact: { magnitude: 2, latency: "weeks", durability: "sustained", effort: "low" },
    callout: "Honest boundary: the best correlational analyses find technology use explains under 1% of adolescent well-being and the association has not grown over time. But randomized deactivation and limiting experiments find modest improvements in well-being, loneliness and depression, and Facebook's staggered college rollout worsened student mental health via social comparison. Both are true: small population effect, real effect for heavy users.",
    description:
      "Specification-curve analyses across 355,358 adolescents found negligible associations between digital technology and well-being; a cohort comparison found no rise in that association over the 2010s; and there are narrow developmental windows where social-media use predicts lower life satisfaction. On the causal side, deactivating Facebook for four weeks increased subjective well-being and offline socializing, limiting use to about 30 minutes a day reduced loneliness and depression over three weeks in students, and a quasi-experiment on Facebook's rollout found negative effects on mental health through unfavourable comparison.",
    action: "For three weeks, cap social apps at 30 minutes a day using the phone's timer, remove them from the home screen, and keep one weekday and one weekend day fully off. Rate loneliness and mood weekly; keep whichever part of the diet moved the numbers.",
    sources: [
      { cite: "Hunt, M. G., Marx, R., Lipson, C., & Young, J. (2018). No More FOMO: Limiting Social Media Decreases Loneliness and Depression. Journal of Social and Clinical Psychology, 37(10), 751-768.", note: "RCT of 143 undergraduates: limiting Facebook, Instagram and Snapchat to 10 minutes per platform per day for three weeks significantly reduced loneliness and depression versus usual use.", link: doi("10.1521/jscp.2018.37.10.751"), kind: "doi" },
      { cite: "Allcott, H., Braghieri, L., Eichmeyer, S., & Gentzkow, M. (2020). The Welfare Effects of Social Media. American Economic Review, 110(3), 629-676.", note: "Randomized deactivation of Facebook for four weeks before the 2018 midterms: increased subjective well-being and offline socializing, reduced polarization and post-experiment use.", link: doi("10.1257/aer.20190658"), kind: "doi" },
      { cite: "Braghieri, L., Levy, R., & Makarin, A. (2022). Social Media and Mental Health. American Economic Review, 112(11), 3660-3693.", note: "Quasi-experiment on Facebook's staggered introduction across US colleges: negative effects on student mental health, with evidence pointing to unfavourable social comparison.", link: doi("10.1257/aer.20211218"), kind: "doi" },
      { cite: "Orben, A., & Przybylski, A. K. (2019). The association between adolescent well-being and digital technology use. Nature human behaviour, 3(2), 173-182.", note: "Specification-curve analysis across three datasets (n = 355,358): digital technology use explained at most 0.4% of variance in adolescent well-being.", link: doi("10.1038/s41562-018-0506-1"), kind: "doi" },
      { cite: "Vuorre, M., Orben, A., & Przybylski, A. K. (2021). There is no evidence that associations between adolescents' digital technology engagement and mental health problems have increased. Clinical psychological science : a journal of the Association for Psychological Science, 9(5), 823-835.", note: "Three representative samples: little evidence that associations between adolescents' technology use and mental health have increased over the past decade; results were mixed across outcomes.", link: doi("10.1177/2167702621994549"), kind: "doi" },
      { cite: "Orben, A., Przybylski, A. K., Blakemore, S. J., & Kievit, R. A. (2022). Windows of developmental sensitivity to social media. Nature Communications, 13(1), 1649.", note: "Developmental windows (11–13 for girls, 14–15 for boys, 19 for both) in which social-media use predicted lower life satisfaction a year later.", link: doi("10.1038/s41467-022-29296-3"), kind: "doi" },
      { cite: "Twenge, J. M., Martin, G. N., & Campbell, W. K. (2018). Decreases in psychological well-being among American adolescents after 2012 and links to screen time during the rise of smartphone technology. Emotion, 18(6), 765-780.", note: "1.1 million US adolescents 1991–2016: well-being fell after 2012, and teens spending more time on screens and less on non-screen activities had lower well-being; light users were happiest.", link: doi("10.1037/emo0000403"), kind: "doi" },
      { cite: "Twenge, J. M., & Campbell, W. K. (2018). Associations between screen time and lower psychological well-being among children and adolescents: Evidence from a population-based study. Preventive Medicine Reports, 12, 271-283.", note: "National US sample of 40,337 children and adolescents: after one hour a day, more screen time was associated with lower well-being, and 7+ hours-a-day adolescents were about twice as likely to have been diagnosed with anxiety or depression.", link: doi("10.1016/j.pmedr.2018.10.003"), kind: "doi" },
    ],
  },
  {
    id: "gs-happiness-mbsr",
    goal: "happiness", tier: "advanced", section: "8314",
    title: "An Eight-Week Mindfulness Program",
    subtitle: "Moderate effects on anxiety, depression and stress in the best trials",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "moderate" },
    feeds: ["anxiety and stress", "attention to the present", "emotional regulation"],
    description:
      "The JAMA Internal Medicine review of 47 trials with active controls found mindfulness meditation programs produced moderate improvements in anxiety, depression and pain and small improvements in stress and quality of life, with no evidence that meditation beat active treatments such as exercise or therapy; the largest meta-analysis of mindfulness-based therapy found moderate effects that held at follow-up, larger for people with anxiety and depression. A daily practice matters partly because a wandering mind is, on average, an unhappy one. Choose a structured eight-week program over an app alone.",
    action: "Enrol in an eight-week MBSR or MBCT course this quarter (in person or live online) and commit to the 30–45-minute daily home practice; if that is impossible, do a 10-minute daily practice for eight weeks and re-evaluate.",
    sources: [
      { cite: "Goyal, M., Singh, S., Sibinga, E. M., Gould, N. F., Rowland-Seymour, A., Sharma, R., …, & Haythornthwaite, J. A. (2014). Meditation programs for psychological stress and well-being: a systematic review and meta-analysis. JAMA internal medicine, 174(3), 357-68.", note: "Systematic review and meta-analysis of 47 trials (3,515 participants): mindfulness programs showed moderate evidence of improving anxiety, depression and pain, with no evidence of superiority over active treatments.", link: doi("10.1001/jamainternmed.2013.13018"), kind: "doi" },
      { cite: "Khoury, B., Lecomte, T., Fortin, G., Masse, M., Therien, P., Bouchard, V., …, & Hofmann, S. G. (2013). Mindfulness-based therapy: a comprehensive meta-analysis. Clinical psychology review, 33(6), 763-71.", note: "Meta-analysis of 209 studies of mindfulness-based therapy: moderate effects on a range of outcomes, maintained at follow-up and larger for anxiety and depression.", link: doi("10.1016/j.cpr.2013.05.005"), kind: "doi" },
      { cite: "Hofmann, S. G., Sawyer, A. T., Witt, A. A., & Oh, D. (2010). The effect of mindfulness-based therapy on anxiety and depression: A meta-analytic review. Journal of consulting and clinical psychology, 78(2), 169-83.", note: "Meta-analysis of 39 studies: mindfulness-based therapy had moderate effects on anxiety and mood symptoms, robust in clinical samples.", link: doi("10.1037/a0018555"), kind: "doi" },
      { cite: "Killingsworth, M. A., & Gilbert, D. T. (2010). A wandering mind is an unhappy mind. Science, 330(6006), 932.", note: "Smartphone experience-sampling: people were thinking about something other than what they were doing almost as often as not, and doing so typically made them unhappy.", link: doi("10.1126/science.1192439"), kind: "doi" },
      { cite: "Fredrickson, B. L., Cohn, M. A., Coffey, K. A., Pek, J., & Finkel, S. M. (2008). Open hearts build lives: positive emotions, induced through loving-kindness meditation, build consequential personal resources. Journal of Personality and Social Psychology, 95(5), 1045-1062.", note: "Loving-kindness meditation in an RCT with working adults increased positive emotions and personal resources, raising life satisfaction.", link: doi("10.1037/a0013262"), kind: "doi" },
    ],
  },
  {
    id: "gs-happiness-ba-cbt",
    goal: "happiness", tier: "advanced", section: "8315",
    title: "Behavioural Activation or Guided CBT Self-Help",
    subtitle: "If low mood is the problem, this is the evidence-based treatment tier",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "weeks", durability: "sustained", effort: "moderate" },
    feeds: ["depressive symptoms", "activity and engagement", "self-efficacy"],
    description:
      "Behavioural activation — scheduling valued, rewarding activities and tracking mood — is a full treatment for depression: meta-analyses find large effects versus controls (SMD −0.74) and the COBRA trial found it non-inferior to cognitive-behavioural therapy while being deliverable by junior staff at lower cost. Guided self-help CBT (a workbook or program with brief support) matched face-to-face therapy in a meta-analysis of 21 direct comparisons. Honest boundary: psychotherapy's added value over care-as-usual on remission was about 14 percentage points — helpful, not magical. Nothing here replaces a clinical assessment.",
    action: "If you have felt low most days for two weeks or more, start a behavioural-activation plan this week: list ten valued activities, schedule three per day at fixed times, rate mood before and after, and review weekly — ideally with a clinician or a guided self-help program. Seek urgent help if you have thoughts of self-harm.",
    sources: [
      { cite: "Cuijpers, P., van Straten, A., & Warmerdam, L. (2006). Behavioral activation treatments of depression: a meta-analysis. Clinical psychology review, 27(3), 318-26.", note: "Meta-analysis of 16 randomized studies (780 subjects): activity scheduling had a large effect versus controls (0.87) and did not differ from cognitive therapy (0.02).", link: doi("10.1016/j.cpr.2006.11.001"), kind: "doi" },
      { cite: "Ekers, D., Webster, L., Van Straten, A., Cuijpers, P., Richards, D., & Gilbody, S. (2014). Behavioural activation for depression; an update of meta-analysis of effectiveness and sub group analysis. PLoS One, 9(6), e100100.", note: "Updated meta-analysis of 26 RCTs (1,524 participants): behavioural activation was superior to controls (SMD −0.74) and to medication (−0.42), though study quality was often low.", link: doi("10.1371/journal.pone.0100100"), kind: "doi" },
      { cite: "Richards, D. A., Ekers, D., McMillan, D., Taylor, R. S., Byford, S., Warren, F. C., …, & Finning, K. (2016). Cost and Outcome of Behavioural Activation versus Cognitive Behavioural Therapy for Depression (COBRA): a randomised, controlled, non-inferiority trial. Lancet (London, England), 388(10047), 871-80.", note: "COBRA randomised non-inferiority trial in UK primary care: behavioural activation, a simpler and cheaper therapy, was tested against CBT for adults with major depression and found non-inferior.", link: doi("10.1016/S0140-6736(16)31140-0"), kind: "doi" },
      { cite: "Richards, D. A., Rhodes, S., Ekers, D., McMillan, D., Taylor, R. S., Byford, S., …, & Woodhouse, R. (2017). Cost and Outcome of BehaviouRal Activation (COBRA): a randomised controlled trial of behavioural activation versus cognitive-behavioural therapy for depression. Health technology assessment (Winchester, England), 21(46), 1-366.", note: "Full HTA report of the COBRA randomised trial, including cost-effectiveness analyses.", link: doi("10.3310/hta21460"), kind: "doi" },
      { cite: "Cuijpers, P., Donker, T., van Straten, A., Li, J., & Andersson, G. (2010). Is guided self-help as effective as face-to-face psychotherapy for depression and anxiety disorders? A systematic review and meta-analysis of comparative outcome studies. Psychological Medicine, 40(12), 1943-57.", note: "Meta-analysis of 21 studies (810 participants): guided self-help had effects equivalent to face-to-face psychotherapy for depression and anxiety, with no difference in dropout.", link: doi("10.1017/S0033291710000772"), kind: "doi" },
      { cite: "Cuijpers, P., Karyotaki, E., Weitz, E., Andersson, G., Hollon, S. D., & van Straten, A. (2014). The effects of psychotherapies for major depression in adults on remission, recovery and improvement: a meta-analysis. Journal of Affective Disorders, 159, 118-26.", note: "Meta-analysis of 92 studies: 62% no longer met criteria for depression after psychotherapy versus 48% in care-as-usual — an added value of about 14 percentage points.", link: doi("10.1016/j.jad.2014.02.026"), kind: "doi" },
    ],
  },
  {
    id: "gs-happiness-community-of-meaning",
    goal: "happiness", tier: "moderate", section: "8316",
    title: "Belong to a Community of Meaning",
    subtitle: "Religious attendance predicts lower mortality and suicide; belonging is the active ingredient",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "months", durability: "lasting", effort: "moderate" },
    feeds: ["social support", "purpose", "lower depressive symptoms"],
    description:
      "Koenig's systematic review of research from 1872 to 2010 links religion and spirituality to well-being, hope, optimism and lower depression and suicide, with mediation through social support and health behaviours. In the Nurses' Health Study, attending services more than weekly was associated with 33% lower all-cause mortality, and weekly attendance with a roughly five-fold lower suicide rate; social support, depressive symptoms, smoking and optimism explained part of the effect. The findings are observational and cannot separate belief from belonging; the protocol is the belonging — a weekly gathering with shared values and service, religious or not.",
    action: "Join or recommit to one weekly community with shared values and a service component — a congregation, a choir, a service club, a recovery fellowship — and attend at least three of four weeks for the next three months before judging it.",
    sources: [
      { cite: "Koenig, H. G. (2012). Religion, spirituality, and health: the research and clinical implications. ISRN Psychiatry, 2012, 278730.", note: "Systematic review of quantitative research on religion, spirituality and mental and physical health, including well-being, depression, suicide and mediating pathways.", link: doi("10.5402/2012/278730"), kind: "doi" },
      { cite: "Li, S., Stampfer, M. J., Williams, D. R., & VanderWeele, T. J. (2016). Association of Religious Service Attendance With Mortality Among Women. JAMA Internal Medicine, 176(6), 777-85.", note: "Nurses' Health Study (74,534 women, 16 years): attending religious services more than once a week was associated with 33% lower all-cause mortality; social support, depression, smoking and optimism partly mediated.", link: doi("10.1001/jamainternmed.2016.1615"), kind: "doi" },
      { cite: "VanderWeele, T. J., Li, S., Tsai, A. C., & Kawachi, I. (2016). Association Between Religious Service Attendance and Lower Suicide Rates Among US Women. JAMA Psychiatry, 73(8), 845-51.", note: "89,708 women: weekly or more religious service attendance was associated with an approximately five-fold lower suicide rate, partly mediated by social integration.", link: doi("10.1001/jamapsychiatry.2016.1243"), kind: "doi" },
      { cite: "Konrath, S., Fuhrel-Forbis, A., Lou, A., & Brown, S. (2012). Motives for volunteering are associated with mortality risk in older adults. Health Psychology, 31(1), 87-96.", note: "Volunteering for other-oriented motives — a feature of many faith and service communities — predicted lower mortality; self-oriented motives did not.", link: doi("10.1037/a0025226"), kind: "doi" },
    ],
  },
  {
    id: "gs-happiness-flow-blocks",
    goal: "happiness", tier: "moderate", section: "8317",
    title: "Schedule Flow: Challenge Matched to Skill",
    subtitle: "The best moments are more often at work than at leisure — engineer them",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "moderate" },
    feeds: ["engagement", "positive affect", "skill growth"],
    description:
      "Experience-sampling of workers found the quality of experience depended more on being in flow — high challenge matched to high skill — than on whether the person was at work or at leisure, and most flow episodes happened at work. A meta-analysis confirms challenge–skill balance as the strongest antecedent of flow. Because a wandering mind is an unhappy one, blocks of absorbed, skill-stretching activity are a direct lever on daily affect.",
    action: "Block two 90-minute sessions a week for a month on one activity slightly harder than you can comfortably do (an instrument, a sport, a craft, a hard piece of work), with clear goals, immediate feedback and no notifications. Rate absorption 1–10 afterward and adjust the difficulty up or down.",
    sources: [
      { cite: "Csikszentmihalyi, M., & LeFevre, J. (1989). Optimal experience in work and leisure. Journal of Personality and Social Psychology, 56(5), 815-22.", note: "Experience-sampling of 78 workers: quality of experience was more affected by flow (high challenge and skill) than by work versus leisure, and most flow was reported at work.", link: doi("10.1037/0022-3514.56.5.815"), kind: "doi" },
      { cite: "Fong, C. J., Zaleski, D. J., & Leach, J. K. (2015). The challenge–skill balance and antecedents of flow: A meta-analytic investigation. The Journal of Positive Psychology, 10(5), 425-446.", note: "Meta-analytic investigation confirming challenge–skill balance as the key antecedent of flow across studies.", link: doi("10.1080/17439760.2014.967799"), kind: "doi" },
      { cite: "Killingsworth, M. A., & Gilbert, D. T. (2010). A wandering mind is an unhappy mind. Science, 330(6006), 932.", note: "A wandering mind predicted unhappiness across activities — the state flow displaces.", link: doi("10.1126/science.1192439"), kind: "doi" },
      { cite: "Kahneman, D., Krueger, A. B., Schkade, D. A., Schwarz, N., & Stone, A. A. (2004). A survey method for characterizing daily life experience: the day reconstruction method. Science, 306(5702), 1776-80.", note: "The Day Reconstruction Method documenting how affect varies across the activities and settings of ordinary days.", link: doi("10.1126/science.1103572"), kind: "doi" },
    ],
  },
  {
    id: "gs-happiness-volunteer-100-hours",
    goal: "happiness", tier: "advanced", section: "8318",
    title: "Volunteer 100 Hours a Year, for Someone Else's Sake",
    subtitle: "Observational benefits are consistent; motive and dose matter",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "months", durability: "lasting", effort: "moderate" },
    feeds: ["purpose", "social contact", "lower depressive symptoms"],
    description:
      "Cohort studies consistently link formal volunteering to less depression, higher life satisfaction and lower mortality (risk ratio 0.78 in meta-analysis), though the few experimental studies did not confirm those effects and causal mechanisms are unclear. Two boundaries sharpen the protocol: the mortality benefit appeared only in people who volunteered for other-oriented reasons, and the outcome-wide Health and Retirement Study found the psychosocial gains at 100 or more hours a year. Advanced tier because it is a real investment of months.",
    action: "Choose one organization and commit to two hours a week for a year (about 100 hours), in a role where you can see the people you serve. Write down why you are doing it before you start; revisit that note at month three.",
    sources: [
      { cite: "Jenkinson, C. E., Dickens, A. P., Jones, K., Thompson-Coon, J., Taylor, R. S., Rogers, M., …, & Richards, S. H. (2013). Is volunteering a public health intervention? A systematic review and meta-analysis of the health and survival of volunteers. BMC Public Health, 13, 773.", note: "Systematic review of 40 papers: cohort studies linked volunteering to better depression, life satisfaction and well-being and to 22% lower mortality; experimental studies were few and did not confirm.", link: doi("10.1186/1471-2458-13-773"), kind: "doi" },
      { cite: "Kim, E. S., Whillans, A. V., Lee, M. T., Chen, Y., & VanderWeele, T. J. (2020). Volunteering and Subsequent Health and Well-Being in Older Adults: An Outcome-Wide Longitudinal Approach. American Journal of Preventive Medicine, 59(2), 176-186.", note: "Health and Retirement Study (n = 12,998): volunteering 100+ hours a year predicted lower mortality and physical limitations and better psychosocial outcomes four years later, but not most physical health outcomes.", link: doi("10.1016/j.amepre.2020.03.004"), kind: "doi" },
      { cite: "Konrath, S., Fuhrel-Forbis, A., Lou, A., & Brown, S. (2012). Motives for volunteering are associated with mortality risk in older adults. Health Psychology, 31(1), 87-96.", note: "Only other-oriented motives for volunteering carried the reduced mortality risk; self-oriented volunteers matched non-volunteers.", link: doi("10.1037/a0025226"), kind: "doi" },
      { cite: "Okun, M. A., Yeung, E. W., & Brown, S. (2013). Volunteering by older adults and risk of mortality: a meta-analysis. Psychology and aging, 28(2), 564-77.", note: "Meta-analysis of volunteering by older adults and mortality risk across cohorts.", link: doi("10.1037/a0031519"), kind: "doi" },
      { cite: "Okun, M. A., August, K. J., Rook, K. S., & Newsom, J. T. (2010). Does volunteering moderate the relation between functional limitations and mortality?. Social science & medicine (1982), 71(9), 1662-8.", note: "Volunteering moderated the relation between functional limitations and mortality — the benefit reached older adults whose health was already declining.", link: doi("10.1016/j.socscimed.2010.07.034"), kind: "doi" },
    ],
  },
  {
    id: "gs-happiness-expressive-writing",
    goal: "happiness", tier: "fundamental", section: "8319",
    title: "Journal the Hard Things, Twenty Minutes at a Time",
    subtitle: "A small, reliable effect on health and mood from 146 randomized studies",
    evidenceTag: "Strong",
    impact: { magnitude: 2, latency: "weeks", durability: "sustained", effort: "low" },
    feeds: ["emotional processing", "reported health", "narrative coherence"],
    description:
      "Writing about deeply personal experiences for 15–20 minutes on several days improved health-centre visits in the original study and, across 146 randomized experiments, produced a small positive effect (r = .075) on psychological and physical outcomes. The mechanism appears to be forming a coherent story out of experience. Gratitude journaling is a different exercise (8302); this one is for what you are struggling with.",
    action: "On four consecutive days this month, write for 20 minutes about something that is weighing on you, exploring your deepest thoughts and feelings without editing; repeat the four-day block whenever something new is unresolved.",
    sources: [
      { cite: "Pennebaker, J. W., & Beall, S. K. (1986). Confronting a traumatic event: toward an understanding of inhibition and disease. Journal of abnormal psychology, 95(3), 274-81.", note: "The original expressive-writing experiment: writing about traumatic events reduced subsequent health-centre visits.", link: doi("10.1037/0021-843x.95.3.274"), kind: "doi" },
      { cite: "Smyth, J. M. (1998). Written emotional expression: effect sizes, outcome types, and moderating variables. Journal of Consulting and Clinical Psychology, 66(1), 174-84.", note: "Research synthesis: written emotional expression improved reported physical health, psychological well-being, physiological functioning and general functioning.", link: doi("10.1037/0022-006X.66.1.174"), kind: "doi" },
      { cite: "Frattaroli, J. (2006). Experimental disclosure and its moderators: a meta-analysis. Psychological Bulletin, 132(6), 823-65.", note: "Random-effects meta-analysis of 146 randomized studies: a positive, significant average effect (r = .075) with moderators identified.", link: doi("10.1037/0033-2909.132.6.823"), kind: "doi" },
      { cite: "Pennebaker, J. W., & Seagal, J. D. (1999). Forming a story: The health benefits of narrative. Journal of Clinical Psychology, 55(10), 1243-1254.", note: "Pennebaker and Seagal on forming a story as the active ingredient of expressive writing.", link: doi("10.1002/(SICI)1097-4679(199910)55:10<1243::AID-JCLP6>3.0.CO;2-N"), kind: "doi" },
    ],
  },
  {
    id: "gs-happiness-pie-myth",
    goal: "happiness", tier: "fundamental", section: "8320",
    title: "'Happiness Is 40% Choice': Rated at the Floor",
    subtitle: "The happiness pie was never measured — and choice-only advice ignores adaptation",
    evidenceTag: "Mixed",
    impact: { magnitude: 1, latency: "days", durability: "transient", effort: "low" },
    callout: "Debunked: the '50% genes, 10% circumstances, 40% intentional activity' pie came from a 2005 theory paper, not from data; Brown and Rohrer's critical re-examination found little empirical basis for the decomposition and noted that even if true it would not tell you how much you can move your own happiness. Popular 'happiness is a choice' claims stack on top of this unmeasured number and on effect sizes that shrank on re-analysis. Rated at the floor so the library counts the slogan as unsupported, not the practices.",
    description:
      "Lyubomirsky, Sheldon and Schkade's architecture-of-sustainable-change paper proposed the pie as a heuristic and argued that intentional activity offers the best route to lasting gains; it became a cultural fact. The twin evidence behind the '50%' describes population variance, not personal leeway; the 2019 re-analysis found intervention effects much smaller than first reported; and a replication found a positive placebo matched the exercises. What replicates is modest: the fundamentals on this shelf, done consistently, plus treatment when mood is clinically low.",
    action: "Retire the slogan. Replace it with one measurable commitment from this shelf for 30 days and a number you will track (nights slept 7+, sessions exercised, calls made). Judge the month by the number, not by whether you 'chose' to be happy.",
    sources: [
      { cite: "Lyubomirsky, S., Sheldon, K. M., & Schkade, D. (2005). Pursuing Happiness: The Architecture of Sustainable Change. Review of General Psychology, 9(2), 111-131.", note: "The source of the pie: a theoretical model proposing chronic happiness is governed by a genetic set point, circumstances and intentional activity, with two preliminary interventions.", link: doi("10.1037/1089-2680.9.2.111"), kind: "doi" },
      { cite: "Brown, N. J. L., & Rohrer, J. M. (2020). Easy as (Happiness) Pie? A Critical Evaluation of a Popular Model of the Determinants of Well-Being. Journal of Happiness Studies, 21(4), 1285-1301.", note: "Critical re-examination: little empirical evidence for the 50/10/40 variance decomposition, and even if valid it would not show how much individuals can change their own happiness.", link: doi("10.1007/s10902-019-00128-4"), kind: "doi" },
      { cite: "Lykken, D., & Tellegen, A. (1996). Happiness Is a Stochastic Phenomenon. Psychological Science, 7(3), 186-189.", note: "The twin study behind the genetic share: 44–52% of variance in well-being genetic, stable component ~80% heritable — population statistics, not personal limits.", link: doi("10.1111/j.1467-9280.1996.tb00355.x"), kind: "doi" },
      { cite: "White, C. A., Uttl, B., & Holder, M. D. (2019). Meta-analyses of positive psychology interventions: The effects are much smaller than previously reported. PloS one, 14(5), e0216588.", note: "Re-analysis showing positive-psychology intervention effects are much smaller than the widely cited meta-analyses reported.", link: doi("10.1371/journal.pone.0216588"), kind: "doi" },
      { cite: "Mongrain, M., & Anselmo-Matthews, T. (2012). Do positive psychology exercises work? A replication of Seligman et al. (2005). Journal of Clinical Psychology, 68(4), 382-9.", note: "Replication of Seligman's exercises in which a positive placebo produced the same lasting happiness gains — a caution against attributing effects to the specific 'choice'.", link: doi("10.1002/jclp.21839"), kind: "doi" },
    ],
  },
  {
    id: "gs-happiness-material-upgrades",
    goal: "happiness", tier: "fundamental", section: "8320",
    title: "'The Upgrade Will Fix It': Rated at the Floor",
    subtitle: "Purchases and status changes adapt away; people and time do not",
    evidenceTag: "Strong",
    impact: { magnitude: 1, latency: "weeks", durability: "transient", effort: "moderate" },
    callout: "Debunked: the belief that the next house, car or promotion will produce lasting happiness runs into the best-documented finding in the field — adaptation. Cognitive well-being reacts and then returns; even marriage returns to baseline on average. Rated at the floor so the library counts 'retail therapy' as a cost. Spend on others, on time and on experiences with people instead.",
    description:
      "The revised adaptation theory and a 188-study meta-analysis show that most positive life changes produce a reaction that fades, with affective well-being adapting fastest; the marriage panel data show a return to baseline on average within years. Income does raise life evaluation, but the marginal gain is diminishing and depends on how the money is spent — prosocial and time-buying spending produce measurable gains where self-directed consumption generally does not.",
    action: "Impose a 30-day wait on any purchase above a threshold you set, and log what you expected to feel versus what you felt a month after the last three big buys. Redirect one planned upgrade this year into a shared experience or a time-saving service.",
    sources: [
      { cite: "Diener, E., Lucas, R. E., & Scollon, C. N. (2006). Beyond the hedonic treadmill: revising the adaptation theory of well-being. American Psychologist, 61(4), 305-14.", note: "Revised hedonic-treadmill theory: people adapt to many events, with affect and life satisfaction moving at different rates and set points that can shift only under some conditions.", link: doi("10.1037/0003-066X.61.4.305"), kind: "doi" },
      { cite: "Luhmann, M., Hofmann, W., Eid, M., & Lucas, R. E. (2012). Subjective well-being and adaptation to life events: a meta-analysis. Journal of Personality and Social Psychology, 102(3), 592-615.", note: "Meta-analysis of adaptation to eight life events: effects were not a function of the alleged desirability of the event, and cognitive well-being reacted more than affect.", link: doi("10.1037/a0025948"), kind: "doi" },
      { cite: "Lucas, R. E., Clark, A. E., Georgellis, Y., & Diener, E. (2003). Reexamining adaptation and the set point model of happiness: reactions to changes in marital status. Journal of personality and social psychology, 84(3), 527-39.", note: "Marriage produced a small average boost followed by a return to baseline, with wide individual variation.", link: doi("10.1037/0022-3514.84.3.527"), kind: "doi" },
      { cite: "Kahneman, D., & Deaton, A. (2010). High income improves evaluation of life but not emotional well-being. Proceedings of the National Academy of Sciences of the United States of America, 107(38), 16489-93.", note: "Emotional well-being did not improve with income beyond about $75,000 in the Gallup data, even as life evaluation rose.", link: doi("10.1073/pnas.1011492107"), kind: "doi" },
      { cite: "Whillans, A. V., Dunn, E. W., Smeets, P., Bekkers, R., & Norton, M. I. (2017). Buying time promotes happiness. Proceedings of the National Academy of Sciences of the United States of America, 114(32), 8523-8527.", note: "Spending on time-saving services, unlike material purchases, was associated with higher life satisfaction and raised positive affect experimentally.", link: doi("10.1073/pnas.1706541114"), kind: "doi" },
    ],
  },
  {
    id: "gs-happiness-combined-program",
    goal: "happiness", tier: "elite", section: "8321",
    title: "The Combined Program: Exercise Plus a Psychological Protocol",
    subtitle: "The largest effect in the 2026 network meta-analysis — and the hardest to sustain",
    evidenceTag: "Moderate",
    impact: { magnitude: 5, latency: "months", durability: "lasting", effort: "high" },
    feeds: ["well-being", "depressive symptoms", "sustained routine"],
    description:
      "In the preregistered network meta-analysis of 183 randomized trials of well-being interventions in adults without diagnosed conditions, combined exercise–psychological programs produced the largest effect (SMD 0.73) — well above any single approach. The components each have strong bases: exercise as an antidepressant, mindfulness or CBT-based programs for anxiety and stress, and behavioural activation for low mood. Certainty was moderate and risk of bias frequent, so treat the number as a direction, not a promise. This is elite because it is a structured, months-long system with a coach or program behind it.",
    action: "For the next six months, run a combined program: three supervised or scheduled exercise sessions a week plus an eight-week structured psychological course (MBSR/MBCT, CBT-based or behavioural activation) with weekly practice, ideally through a clinic, gym or workplace program that tracks attendance. Re-measure mood and life satisfaction at month three and six.",
    sources: [
      { cite: "Wilkie, L., Fisher, Z., Geidel, A., Goodall, I., Kamil, S., Davies, E., & Kemp, A. H. (2026). A systematic review and network meta-analysis of randomized controlled trials of well-being-focused interventions. Nature Human Behaviour.", note: "Network meta-analysis of 183 RCTs (n = 22,811): combined exercise–psychological interventions had the largest effect on well-being (SMD 0.73), with mindfulness, compassion, single positive-psychology, yoga and exercise programs at 0.41–0.49.", link: doi("10.1038/s41562-025-02369-1"), kind: "doi" },
      { cite: "Noetel, M., Sanders, T., Gallardo-Gómez, D., Taylor, P., Del Pozo Cruz, B., van den Hoek, D., …, & Lonsdale, C. (2024). Effect of exercise for depression: systematic review and network meta-analysis of randomised controlled trials. BMJ (Clinical research ed.), 384, e075847.", note: "Exercise modalities reduced depression with moderate effects comparable to psychotherapy across 218 RCTs.", link: doi("10.1136/bmj-2023-075847"), kind: "doi" },
      { cite: "Schuch, F. B., Vancampfort, D., Richards, J., Rosenbaum, S., Ward, P. B., & Stubbs, B. (2016). Exercise as a treatment for depression: A meta-analysis adjusting for publication bias. Journal of psychiatric research, 77, 42-51.", note: "Exercise remained an effective depression treatment after adjusting for publication bias.", link: doi("10.1016/j.jpsychires.2016.02.023"), kind: "doi" },
      { cite: "Goyal, M., Singh, S., Sibinga, E. M., Gould, N. F., Rowland-Seymour, A., Sharma, R., …, & Haythornthwaite, J. A. (2014). Meditation programs for psychological stress and well-being: a systematic review and meta-analysis. JAMA internal medicine, 174(3), 357-68.", note: "Structured mindfulness programs produced moderate improvements in anxiety, depression and pain in active-controlled trials.", link: doi("10.1001/jamainternmed.2013.13018"), kind: "doi" },
      { cite: "Richards, D. A., Ekers, D., McMillan, D., Taylor, R. S., Byford, S., Warren, F. C., …, & Finning, K. (2016). Cost and Outcome of Behavioural Activation versus Cognitive Behavioural Therapy for Depression (COBRA): a randomised, controlled, non-inferiority trial. Lancet (London, England), 388(10047), 871-80.", note: "Behavioural activation was non-inferior to CBT for depression in the COBRA trial — a scalable psychological component.", link: doi("10.1016/S0140-6736(16)31140-0"), kind: "doi" },
      { cite: "Clegg, A. J., Hill, J. E., Mullin, D. S., Harris, C., Smith, C. J., Lightbody, C. E., …, & Watkins, C. L. (2026). Exercise for depression. The Cochrane database of systematic reviews, 1(1), CD004366.", note: "Cochrane's 2026 update on exercise for depression, including comparisons with psychological and pharmacological treatments.", link: doi("10.1002/14651858.CD004366.pub7"), kind: "doi" },
    ],
  },
];
