// Goal shelf: HEALTH, ENERGY & BEAUTY — great health, energy and looking and
// feeling young for as long as possible (sections 9300–9399).
// Scope: the daily energy, appearance and vitality protocols. The longevity
// shelf (7000–7059) already covers mortality-scale interventions (lipids,
// blood pressure, VO2max, geroprotector drugs, sleep duration, NAD precursors
// as longevity agents); this shelf points to it rather than repeating it.
// Verification: every DOI below was resolved against the PubMed record on
// 2026-09-11. See types.ts for the contract. Nothing here is medical advice —
// drugs and procedures are described as the trials tested them.
import { doi, type GoalShelfCluster } from "./types";

export const SECTIONS: Record<string, string> = {
  "9300": "How to Read This Shelf",
  "9301": "Daily Energy — Exercise Is the First-Line Fatigue Treatment",
  "9302": "Sleep Regularity & the Short Nap",
  "9303": "Iron Deficiency Without Anemia — The Fatigue Cause Worth Testing",
  "9304": "Hydration — The Honest Version",
  "9305": "Caffeine Timing",
  "9306": "Morning Light for Mood & Alertness",
  "9307": "Daily Sunscreen & the Sun Balance",
  "9308": "Topical Retinoids — The Cream With Trial Evidence",
  "9309": "Collagen, Vitamin C Serums & Anti-Aging Creams — What the Trials Say",
  "9310": "Diet Quality & Skin",
  "9311": "Smoking, Alcohol & the Face",
  "9312": "Sleep & Perceived Attractiveness",
  "9313": "Hair Loss — Treatments With Trial Evidence (Described, Not Advised)",
  "9314": "Teeth & Smile — Oral Appearance",
  "9315": "Posture — Perception, Mood & the Power-Pose Correction",
  "9316": "Resistance Training for Body Composition & Body Image",
  "9317": "Weight-Loss Maintenance — What the National Weight Control Registry Does",
  "9318": "GLP-1 Medications — Described With the Trials",
  "9319": "Grip, Legs & Mobility — Youthful Movement",
  "9320": "Hearing & Vision Protection",
  "9321": "Cosmetic Procedures & Well-Being — The Honest Evidence",
  "9322": "Myths — 'Detox', Miracle Creams & NAD 'Youth' Pills",
};

export const CLUSTERS: GoalShelfCluster[] = [
  {
    id: "gs-health-energy-beauty-read-me-first",
    goal: "health-energy-beauty", tier: "fundamental", section: "9300",
    title: "How to Read the Health, Energy & Beauty Shelf",
    subtitle: "Daily vitality and appearance protocols — the longevity shelf (7000+) holds the drugs, lipids and fitness targets",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "low" },
    description:
      "This shelf is about how you feel and look day to day: energy, sleep timing, skin, hair, teeth, posture, body composition and the honest evidence on the products sold for them. Mortality-scale medicine — ApoB, blood pressure, VO2max, statins, rapamycin, NAD precursors as longevity agents — lives on the longevity shelf; where the two overlap (GLP-1 drugs, collagen, hearing, grip) this shelf takes the appearance-and-energy angle and points across. Two facts anchor everything here: regular exercise is the best-replicated treatment for low energy, and daily sunscreen is the only cream with a randomized trial showing less skin aging.",
    action: "This month, pick the fundamental protocol you are not doing — for most people it is 9301 (exercise for energy) or 9307 (daily sunscreen) — and run it for 30 days before adding anything from the tiers above.",
    sources: [
      { cite: "Puetz, T. W., O'Connor, P. J., & Dishman, R. K. (2006). Effects of chronic exercise on feelings of energy and fatigue: A quantitative synthesis. Psychological Bulletin, 132(6), 866–876.", note: "Meta-analysis of 70 randomized trials: chronic exercise increased feelings of energy and reduced fatigue with a moderate effect — the single best-replicated energy intervention on this shelf.", link: doi("10.1037/0033-2909.132.6.866"), kind: "doi" },
      { cite: "Hughes, M. C. B., Williams, G. M., Baker, P., & Green, A. C. (2013). Sunscreen and prevention of skin aging: A randomized trial. Annals of Internal Medicine, 158(11), 781–790.", note: "The Nambour randomized trial: daily broad-spectrum sunscreen produced 24% less measured skin aging over 4.5 years than discretionary use — the only cream on this shelf with that kind of evidence.", link: doi("10.7326/0003-4819-158-11-201306040-00002"), kind: "doi" },
    ],
  },
  {
    id: "gs-health-energy-beauty-exercise-for-energy",
    goal: "health-energy-beauty", tier: "fundamental", section: "9301",
    title: "Treat Low Energy With Regular Exercise — Low Intensity Works",
    subtitle: "Seventy trials say chronic exercise raises energy and lowers fatigue; in persistently fatigued adults, low-intensity sessions beat moderate ones for fatigue",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "weeks", durability: "sustained", effort: "moderate" },
    feeds: ["Daily energy", "Mood", "Sleep quality"],
    description:
      "The counter-intuitive finding is one of the most replicated in exercise science: spending energy on movement returns more energy. A meta-analysis of 70 randomized trials found chronic exercise increased feelings of energy and reduced fatigue; a 2022 update of randomized trials confirmed it. In sedentary young adults with persistent fatigue, six weeks of three 20-minute sessions a week raised energy in both low- and moderate-intensity groups, and the low-intensity group reduced fatigue more. Epidemiological data show the same dose–response, and even 3-minute walking breaks every 30 minutes reduce fatigue across a sitting day.",
    action: "Three times a week for six weeks, do 20 minutes of easy movement — a brisk walk, an easy bike — at an effort where you can talk, and break every 30 minutes of sitting with a 3-minute walk. Rate your energy each evening on a 1–10 scale so you can see the change by week four.",
    sources: [
      { cite: "Puetz, T. W., O'Connor, P. J., & Dishman, R. K. (2006). Effects of chronic exercise on feelings of energy and fatigue: A quantitative synthesis. Psychological Bulletin, 132(6), 866–876.", note: "Seventy randomized trials pooled: chronic exercise produced a moderate increase in feelings of energy and decrease in fatigue across healthy and clinical samples.", link: doi("10.1037/0033-2909.132.6.866"), kind: "doi" },
      { cite: "Puetz, T. W., Flowers, S. S., & O'Connor, P. J. (2008). A randomized controlled trial of the effect of aerobic exercise training on feelings of energy and fatigue in sedentary young adults with persistent fatigue. Psychotherapy and Psychosomatics, 77(3), 167–174.", note: "Six weeks of 20-minute sessions three times a week: both low- and moderate-intensity exercise raised energy versus control, and low intensity reduced fatigue more than moderate — you do not need to train hard to feel less tired.", link: doi("10.1159/000116610"), kind: "doi" },
      { cite: "Wender, C. L. A., Manninen, M., & O'Connor, P. J. (2022). The effect of chronic exercise on energy and fatigue states: A systematic review and meta-analysis of randomized trials. Frontiers in Psychology, 13, 907637.", note: "Updated meta-analysis restricted to randomized trials confirming that chronic exercise improves energy and fatigue states — the 2006 result holds with stricter inclusion.", link: doi("10.3389/fpsyg.2022.907637"), kind: "doi" },
      { cite: "Dishman, R. K., Thom, N. J., Puetz, T. W., O'Connor, P. J., & Clementz, B. A. (2010). Effects of cycling exercise on vigor, fatigue, and electroencephalographic activity among young adults who report persistent fatigue. Psychophysiology, 47(6), 1066–1074.", note: "In persistently fatigued young adults, cycling sessions increased vigor and reduced fatigue with corresponding EEG changes — a mechanism-level companion to the trials.", link: doi("10.1111/j.1469-8986.2010.01014.x"), kind: "doi" },
      { cite: "Puetz, T. W. (2006). Physical activity and feelings of energy and fatigue: Epidemiological evidence. Sports Medicine, 36(9), 767–780.", note: "Review of population studies: physically active people consistently report more energy and less fatigue, with a dose–response that survives adjustment for health status.", link: doi("10.2165/00007256-200636090-00004"), kind: "doi" },
      { cite: "Wennberg, P., Boraxbekk, C.-J., Wheeler, M., Howard, B., Dempsey, P. C., Lambert, G., et al. (2016). Acute effects of breaking up prolonged sitting on fatigue and cognition: A pilot study. BMJ Open, 6(2), e009630.", note: "Randomized crossover in 19 overweight adults: 3-minute light walking breaks every 30 minutes lowered fatigue at 4 and 7 hours versus uninterrupted sitting.", link: doi("10.1136/bmjopen-2015-009630"), kind: "doi" },
    ],
  },
  {
    id: "gs-health-energy-beauty-sleep-regularity",
    goal: "health-energy-beauty", tier: "fundamental", section: "9302",
    title: "Fix the Wake Time, Not Just the Hours — and Nap Ten Minutes",
    subtitle: "Sleep regularity predicts mortality more strongly than sleep duration; a 10-minute afternoon nap is the most recuperative length",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "low" },
    feeds: ["Alertness", "Circadian stability", "Daytime energy"],
    description:
      "The longevity shelf covers how many hours to sleep; this shelf covers when. In 60,977 UK Biobank adults with accelerometer data, higher day-to-day regularity of sleep–wake timing was associated with 20–48% lower all-cause mortality across the top four quintiles, and regularity predicted mortality better than duration. In students, irregular sleep–wake patterns went with delayed circadian timing and worse performance even at similar total sleep. For the afternoon dip, a controlled comparison of nap lengths found a 10-minute nap produced immediate and lasting improvements with no sleep inertia, while 30 minutes caused grogginess before benefits appeared.",
    action: "Pick one wake time and hold it within 30 minutes seven days a week for the next month, including weekends; if you need a nap, set a timer for 10 minutes before 3 pm.",
    sources: [
      { cite: "Windred, D. P., Burns, A. C., Lane, J. M., et al. (2024). Sleep regularity is a stronger predictor of mortality risk than sleep duration: A prospective cohort study. Sleep, 47(1), zsad253.", note: "60,977 UK Biobank participants with over 10 million hours of accelerometry: higher Sleep Regularity Index was associated with 20–48% lower all-cause mortality and predicted mortality better than sleep duration.", link: doi("10.1093/sleep/zsad253"), kind: "doi" },
      { cite: "Phillips, A. J. K., Clerx, W. M., O'Brien, C. S., et al. (2017). Irregular sleep/wake patterns are associated with poorer academic performance and delayed circadian and sleep/wake timing. Scientific Reports, 7, 3216.", note: "College students with irregular sleep–wake timing had delayed circadian phase and lower academic performance despite similar sleep duration — regularity is its own variable.", link: doi("10.1038/s41598-017-03171-4"), kind: "doi" },
      { cite: "Milner, C. E., & Cote, K. A. (2009). Benefits of napping in healthy adults: Impact of nap length, time of day, age, and experience with napping. Journal of Sleep Research, 18(2), 272–281.", note: "Review of napping in healthy adults: brief naps improve alertness and performance, with nap length, time of day and habitual napping shaping the benefit and the inertia cost.", link: doi("10.1111/j.1365-2869.2008.00718.x"), kind: "doi" },
      { cite: "Brooks, A., & Lack, L. (2006). A brief afternoon nap following nocturnal sleep restriction: Which nap duration is most recuperative? Sleep, 29(6), 831–840.", note: "Compared 5, 10, 20 and 30-minute afternoon naps after restricted sleep: the 10-minute nap produced immediate improvements lasting up to 155 minutes with no sleep inertia; the 30-minute nap impaired alertness first.", link: doi("10.1093/sleep/29.6.831"), kind: "doi" },
    ],
  },
  {
    id: "gs-health-energy-beauty-iron-deficiency",
    goal: "health-energy-beauty", tier: "advanced", section: "9303",
    title: "Get Ferritin Checked — Non-Anemic Iron Deficiency Is a Treatable Fatigue Cause",
    subtitle: "Randomized trials in fatigued, non-anemic women with low ferritin show iron repletion reduces fatigue; it does nothing if iron is normal",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "weeks", durability: "sustained", effort: "moderate" },
    feeds: ["Daily energy", "Physical capacity"],
    description:
      "Fatigue in menstruating women is often iron deficiency without anemia, and it responds to treatment. In a Canadian randomized trial of 198 non-anemic women with ferritin under 50, twelve weeks of oral iron reduced fatigue more than placebo; a Swiss trial found the same, with the benefit concentrated in women with low ferritin; and a single intravenous dose improved fatigue in the PREFER trial. A systematic review of randomized trials confirms iron reduces fatigue in non-anemic iron-deficient adults. The boundary: this is a clinician's decision — iron is not a general energy supplement, it can be harmful when stores are normal, and the finding is specific to people with measured deficiency.",
    action: "If you are persistently tired, ask your clinician for a ferritin (and full blood count) test before buying any supplement; if deficiency is confirmed, follow the prescribed repletion course for the full 12 weeks and re-test.",
    sources: [
      { cite: "Vaucher, P., Druais, P.-L., Waldvogel, S., & Favrat, B. (2012). Effect of iron supplementation on fatigue in nonanemic menstruating women with low ferritin: A randomized controlled trial. CMAJ, 184(11), 1247–1254.", note: "198 non-anemic women with ferritin below 50 µg/L and unexplained fatigue: 12 weeks of oral iron reduced fatigue scores more than placebo.", link: doi("10.1503/cmaj.110950"), kind: "doi" },
      { cite: "Houston, B. L., Hurrie, D., Graham, J., et al. (2018). Efficacy of iron supplementation on fatigue and physical capacity in non-anaemic iron-deficient adults: A systematic review of randomised controlled trials. BMJ Open, 8(4), e019240.", note: "Systematic review of randomized trials: iron supplementation reduced self-reported fatigue in non-anemic iron-deficient adults, with less consistent effects on objective physical capacity.", link: doi("10.1136/bmjopen-2017-019240"), kind: "doi" },
      { cite: "Verdon, F., Burnand, B., Stubi, C.-L. F., et al. (2003). Iron supplementation for unexplained fatigue in non-anaemic women: Double blind randomised placebo controlled trial. BMJ, 326(7399), 1124.", note: "Swiss primary-care trial: four weeks of oral iron reduced fatigue in non-anemic women, with the benefit confined to those with low or borderline ferritin — the reason to test before treating.", link: doi("10.1136/bmj.326.7399.1124"), kind: "doi" },
      { cite: "Favrat, B., Balck, K., Breymann, C., et al. (2014). Evaluation of a single dose of ferric carboxymaltose in fatigued, iron-deficient women — PREFER, a randomized, placebo-controlled study. PLoS ONE, 9(4), e94217.", note: "Randomized placebo-controlled trial of a single intravenous iron dose in fatigued iron-deficient women: fatigue improved more than with placebo — a physician-delivered option when oral iron fails.", link: doi("10.1371/journal.pone.0094217"), kind: "doi" },
    ],
  },
  {
    id: "gs-health-energy-beauty-hydration-honest",
    goal: "health-energy-beauty", tier: "fundamental", section: "9304",
    title: "Hydration — Mild Dehydration Dents Mood; 'Eight Glasses' Is Not the Evidence",
    subtitle: "About 1–1.5% body-water loss worsens mood, fatigue and concentration in controlled studies; beyond correcting that, more water is not more energy",
    evidenceTag: "Moderate",
    impact: { magnitude: 2, latency: "days", durability: "transient", effort: "low" },
    feeds: ["Mood", "Concentration"],
    description:
      "The honest version of the hydration story is modest and real. Controlled studies that dehydrated healthy young men and women by about 1–1.5% of body mass found worse mood, more fatigue and headache, and lower concentration, with the effects appearing at rest as well as during exercise; progressive fluid restriction in women produced the same pattern. What the evidence does not show is that drinking beyond normal thirst-guided intake produces extra energy or clearer skin. Treat water as a floor, not a lever.",
    action: "Keep a water bottle within reach all day and drink to thirst, front-loading a glass on waking and one with each meal; if afternoon headaches or brain-fog are routine, check that your urine is pale before reaching for caffeine.",
    sources: [
      { cite: "Ganio, M. S., Armstrong, L. E., Casa, D. J., et al. (2011). Mild dehydration impairs cognitive performance and mood of men. British Journal of Nutrition, 106(10), 1535–1543.", note: "Controlled dehydration of about 1.6% in young men impaired vigilance and working memory and increased tension, anxiety and fatigue, at rest and during exercise.", link: doi("10.1017/S0007114511002005"), kind: "doi" },
      { cite: "Armstrong, L. E., Ganio, M. S., Casa, D. J., et al. (2012). Mild dehydration affects mood in healthy young women. Journal of Nutrition, 142(2), 382–388.", note: "About 1.4% dehydration in young women degraded mood, raised perceived task difficulty and produced headaches and lower concentration, with only small cognitive-performance effects.", link: doi("10.3945/jn.111.142000"), kind: "doi" },
      { cite: "Pross, N., Demazières, A., Girard, N., et al. (2013). Influence of progressive fluid restriction on mood and physiological markers of dehydration in women. British Journal of Nutrition, 109(2), 313–321.", note: "Twenty-four hours of fluid restriction in women worsened mood and increased thirst and fatigue alongside urinary markers of dehydration — the mood effect appears before any medical dehydration.", link: doi("10.1017/S0007114512001080"), kind: "doi" },
    ],
  },
  {
    id: "gs-health-energy-beauty-caffeine-timing",
    goal: "health-energy-beauty", tier: "fundamental", section: "9305",
    title: "Caffeine — Cut It Off Eight Hours Before Bed",
    subtitle: "400 mg taken six hours before bedtime still cut sleep by an hour; the meta-analysis puts the cutoff for a standard coffee at about 8.8 hours",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "days", durability: "sustained", effort: "low" },
    feeds: ["Sleep depth", "Morning energy", "Stable mood"],
    description:
      "Caffeine is the most-used energy tool and the most common self-inflicted sleep problem. In a controlled study, 400 mg taken at bedtime, three hours before or six hours before bed all reduced objectively measured sleep — the six-hour dose by more than an hour — and participants did not notice the six-hour effect. A 2023 meta-analysis found caffeine reduced total sleep time by about 45 minutes and sleep efficiency by 7%, and estimated that a standard cup of coffee (107 mg) should be consumed at least 8.8 hours before bed to avoid disruption. Withdrawal is real: headache, fatigue and low mood peak at 20–51 hours after stopping, which is why 'I need coffee to function' is partly the coffee talking.",
    action: "Set a hard caffeine cutoff eight hours before your target bedtime (2 pm for a 10 pm bed), keep the total under about 400 mg, and if you want to reset, taper by one cup every three days rather than stopping cold.",
    sources: [
      { cite: "Drake, C., Roehrs, T., Shambroom, J., & Roth, T. (2013). Caffeine effects on sleep taken 0, 3, or 6 hours before going to bed. Journal of Clinical Sleep Medicine, 9(11), 1195–1200.", note: "400 mg caffeine at 0, 3 or 6 hours before bed all reduced sleep measured by home monitor; the 6-hour dose cut total sleep by more than an hour without participants perceiving it.", link: doi("10.5664/jcsm.3170"), kind: "doi" },
      { cite: "Gardiner, C., Weakley, J., Burke, L. M., et al. (2023). The effect of caffeine on subsequent sleep: A systematic review and meta-analysis. Sleep Medicine Reviews, 69, 101764.", note: "Meta-analysis: caffeine reduced total sleep time by about 45 minutes and sleep efficiency by 7%, and modeled that a 107 mg coffee should be taken at least 8.8 hours before bed to avoid reductions.", link: doi("10.1016/j.smrv.2023.101764"), kind: "doi" },
      { cite: "Juliano, L. M., & Griffiths, R. R. (2004). A critical review of caffeine withdrawal: Empirical validation of symptoms and signs, incidence, severity, and associated features. Psychopharmacology, 176(1), 1–29.", note: "Review of 57 experimental and 9 survey studies: caffeine withdrawal produces headache, fatigue, decreased energy and depressed mood, onset 12–24 hours and peak 20–51 hours after abstinence.", link: doi("10.1007/s00213-004-2000-x"), kind: "doi" },
    ],
  },
  {
    id: "gs-health-energy-beauty-morning-light",
    goal: "health-energy-beauty", tier: "fundamental", section: "9306",
    title: "Get Bright Light Within an Hour of Waking",
    subtitle: "Bright light treats seasonal and non-seasonal depression with effect sizes comparable to medication; daylight-exposed workers sleep longer and report better vitality",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "days", durability: "sustained", effort: "low" },
    feeds: ["Morning alertness", "Mood", "Sleep timing"],
    description:
      "Light is the strongest signal your circadian system receives. A meta-analysis of randomized trials found bright light therapy produced significant reductions in depressive symptoms in both seasonal and non-seasonal depression, with effect sizes in the range of antidepressant trials. Alertness rises with light intensity in a dose–response fashion, and office workers with windows slept about 46 minutes more per night and scored higher on vitality and physical function than windowless colleagues. The cheapest version is a walk outside soon after waking.",
    action: "Every morning for the next two weeks, get 10–30 minutes of outdoor light within an hour of waking (or sit by a bright window); in winter or on dark shifts, describe a 10,000-lux light box to your clinician as an option rather than self-prescribing it.",
    sources: [
      { cite: "Golden, R. N., Gaynes, B. N., Ekstrom, R. D., et al. (2005). The efficacy of light therapy in the treatment of mood disorders: A review and meta-analysis of the evidence. American Journal of Psychiatry, 162(4), 656–662.", note: "Meta-analysis of randomized trials: bright light treatment reduced depressive symptoms in seasonal and non-seasonal depression with effect sizes equivalent to those in most antidepressant trials.", link: doi("10.1176/appi.ajp.162.4.656"), kind: "doi" },
      { cite: "Boubekri, M., Cheung, I. N., Reid, K. J., Wang, C.-H., & Zee, P. C. (2014). Impact of windows and daylight exposure on overall health and sleep quality of office workers: A case-control pilot study. Journal of Clinical Sleep Medicine, 10(6), 603–611.", note: "Office workers with windows had more light exposure, about 46 minutes more sleep per night, and better vitality and quality-of-life scores than workers in windowless offices.", link: doi("10.5664/jcsm.3780"), kind: "doi" },
      { cite: "Cajochen, C., Zeitzer, J. M., Czeisler, C. A., & Dijk, D.-J. (2000). Dose-response relationship for light intensity and ocular and electroencephalographic correlates of human alertness. Behavioural Brain Research, 115(1), 75–83.", note: "Controlled laboratory study: alertness, melatonin suppression and EEG correlates rose with light intensity in a dose–response curve — the physiological basis for morning bright light.", link: doi("10.1016/s0166-4328(00)00236-9"), kind: "doi" },
    ],
  },
  {
    id: "gs-health-energy-beauty-daily-sunscreen",
    goal: "health-energy-beauty", tier: "fundamental", section: "9307",
    title: "Daily Sunscreen — The One Anti-Aging Cream With a Randomized Trial",
    subtitle: "Daily broad-spectrum SPF cut measured skin aging by 24% over 4.5 years and lowered squamous-cell carcinoma; sun plus smoking multiplies wrinkling",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "months", durability: "lasting", effort: "low" },
    feeds: ["Skin aging", "Skin cancer risk"],
    description:
      "The Nambour trial randomized 903 adults under 55 to daily versus discretionary sunscreen: after 4.5 years the daily group showed no detectable increase in skin aging and 24% less aging than the discretionary group, while beta-carotene did nothing. The same community trial found daily sunscreen reduced squamous-cell carcinoma tumours by about 40%. Smoking and sun exposure are each independent wrinkle risk factors and together multiply the risk twelve-fold. The balance note: the Swedish cohort that found sun avoidance associated with higher mortality is observational and does not overturn the trial — the protocol is protect the face and hands daily, and get your daylight for mood in the morning.",
    action: "Apply a broad-spectrum SPF 30+ to face, neck and the backs of your hands every morning as part of brushing your teeth, year-round, and reapply before midday outdoor time; keep the morning-light walk from 9306.",
    sources: [
      { cite: "Hughes, M. C. B., Williams, G. M., Baker, P., & Green, A. C. (2013). Sunscreen and prevention of skin aging: A randomized trial. Annals of Internal Medicine, 158(11), 781–790.", note: "903 adults randomized: daily sunscreen showed no detectable increase in skin aging over 4.5 years and 24% less aging than discretionary use (relative odds 0.76); beta-carotene had no overall effect.", link: doi("10.7326/0003-4819-158-11-201306040-00002"), kind: "doi" },
      { cite: "Green, A., Williams, G., Neale, R., et al. (1999). Daily sunscreen application and betacarotene supplementation in prevention of basal-cell and squamous-cell carcinomas of the skin: A randomised controlled trial. The Lancet, 354(9180), 723–729.", note: "1,621 Nambour residents randomized: daily sunscreen reduced the number of squamous-cell carcinomas (rate ratio 0.61) with no effect on basal-cell carcinoma and no harm — the safety and cancer half of the sunscreen case.", link: doi("10.1016/S0140-6736(98)12168-2"), kind: "doi" },
      { cite: "Kadunce, D. P., Burr, R., Gress, R., Kanner, R., Lyon, J. L., & Zone, J. J. (1991). Cigarette smoking: Risk factor for premature facial wrinkling. Annals of Internal Medicine, 114(10), 840–844.", note: "Heavy smokers were 4.7 times more likely to be prematurely wrinkled, over 50,000 lifetime hours of sun 3.1 times, and the two together multiplied to a prevalence ratio of 12.", link: doi("10.7326/0003-4819-114-10-840"), kind: "doi" },
      { cite: "Lindqvist, P. G., Epstein, E., Nielsen, K., et al. (2016). Avoidance of sun exposure as a risk factor for major causes of death: A competing risk analysis of the Melanoma in Southern Sweden cohort. Journal of Internal Medicine, 280(4), 375–387.", note: "Observational Swedish cohort: women who avoided sun exposure had higher all-cause mortality — the reason this shelf pairs facial sunscreen with deliberate daylight rather than total avoidance; it is not a trial.", link: doi("10.1111/joim.12496"), kind: "doi" },
    ],
  },
  {
    id: "gs-health-energy-beauty-retinoids",
    goal: "health-energy-beauty", tier: "advanced", section: "9308",
    title: "Topical Retinoids — Prescription Tretinoin and Over-the-Counter Retinol Both Have Trials",
    subtitle: "Two-year placebo-controlled tretinoin trial improved fine and coarse wrinkling; 0.4% retinol improved fine wrinkles in 24 weeks; expect irritation early",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "months", durability: "sustained", effort: "moderate" },
    feeds: ["Fine wrinkles", "Skin texture", "Pigmentation"],
    description:
      "Retinoids are the only class of topical besides sunscreen with consistent randomized evidence. A two-year, 204-subject placebo-controlled trial of tretinoin 0.05% cream improved fine and coarse wrinkling, mottled pigmentation and overall photodamage with no histologic harm and increased procollagen; tretinoin restored collagen formation in photodamaged skin by 80% versus a 14% decrease with vehicle; and over-the-counter 0.4% retinol applied three times a week for 24 weeks reduced fine wrinkles in people in their late 80s. A 2024 systematic review confirms tretinoin as the benchmark against which other topicals are compared. Prescription tretinoin is a physician decision (it is not used in pregnancy); retinol is the accessible version.",
    action: "Start a pea-sized amount of over-the-counter retinol on clean skin two nights a week, build to nightly over six weeks as irritation allows, always with morning sunscreen; if you want prescription-strength tretinoin, ask a dermatologist and plan on 6–12 months to judge it.",
    sources: [
      { cite: "Kang, S., Bergfeld, W., Gottlieb, A. B., et al. (2005). Long-term efficacy and safety of tretinoin emollient cream 0.05% in the treatment of photodamaged facial skin: A two-year, randomized, placebo-controlled trial. American Journal of Clinical Dermatology, 6(4), 245–253.", note: "204 subjects, two years: tretinoin 0.05% significantly improved fine and coarse wrinkling, mottled hyperpigmentation, lentigines and sallowness versus placebo, with no keratinocyte or melanocyte atypia on biopsy.", link: doi("10.2165/00128071-200506040-00005"), kind: "doi" },
      { cite: "Griffiths, C. E., Russman, A. N., Majmudar, G., Singer, R. S., Hamilton, T. A., & Voorhees, J. J. (1993). Restoration of collagen formation in photodamaged human skin by tretinoin (retinoic acid). New England Journal of Medicine, 329(8), 530–535.", note: "Collagen I formation was 56% lower in photodamaged skin; 10–12 months of 0.1% tretinoin produced an 80% increase in collagen formation versus a 14% decrease with vehicle.", link: doi("10.1056/NEJM199308193290803"), kind: "doi" },
      { cite: "Kafi, R., Kwak, H. S. R., Schumacher, W. E., et al. (2007). Improvement of naturally aged skin with vitamin A (retinol). Archives of Dermatology, 143(5), 606–612.", note: "Randomized, vehicle-controlled arm comparison in 36 elderly subjects: 0.4% retinol up to three times a week for 24 weeks reduced fine wrinkle scores and increased glycosaminoglycan and procollagen expression.", link: doi("10.1001/archderm.143.5.606"), kind: "doi" },
      { cite: "Siddiqui, Z., Zufall, A., Nash, M., et al. (2024). Comparing tretinoin to other topical therapies in the treatment of skin photoaging: A systematic review. American Journal of Clinical Dermatology, 25(6), 873–890.", note: "Systematic review positioning tretinoin as the reference topical for photoaging and summarizing how retinol, vitamin C and other agents compare — useful for reading product claims.", link: doi("10.1007/s40257-024-00893-w"), kind: "doi" },
      { cite: "Sanabria, B., Berger, L. E., Mohd, H., et al. (2023). Clinical efficacy of topical vitamin C on the appearance of wrinkles: A systematic literature review. Journal of Drugs in Dermatology, 22(9), 898–904.", note: "Systematic review of topical vitamin C trials for wrinkles: evidence of modest improvement in small, short studies with variable formulations — a second-tier adjunct, not a retinoid substitute.", link: doi("10.36849/JDD.7332"), kind: "doi" },
    ],
  },
  {
    id: "gs-health-energy-beauty-collagen-creams-honest",
    goal: "health-energy-beauty", tier: "moderate", section: "9309",
    title: "Collagen Powder, Vitamin C Serum and 'Anti-Aging' Creams — Small Effects, Industry Trials",
    subtitle: "Meta-analyses find hydrolyzed collagen modestly improves hydration and elasticity over 8–12 weeks; most cosmetic creams have no comparable evidence",
    evidenceTag: "Mixed",
    impact: { magnitude: 2, latency: "months", durability: "transient", effort: "moderate" },
    callout: "Rated honestly at 2, not at the floor: pooled trials do show statistically significant improvements in skin hydration and elasticity from hydrolyzed collagen, but the trials are small, short, heterogeneous and largely industry-funded, and the effect sizes are modest. Longevity shelf 7038 covers the same evidence from the aging angle. Ordinary anti-aging creams without a retinoid or sunscreen have no evidence base of this quality.",
    feeds: ["Skin hydration", "Elasticity"],
    description:
      "Two meta-analyses — 19 randomized trials with 1,125 participants, and 26 trials with 1,721 — found hydrolyzed collagen supplementation improved skin hydration and elasticity versus placebo, with better results after more than eight weeks and with the authors flagging bias in the included trials. Topical vitamin C shows modest wrinkle improvement in small studies. A dermatology review of anti-aging creams concludes that outside sunscreen, retinoids and a few actives, product claims are not backed by controlled trials. The protocol here is to spend on the evidence-tiered items first and treat the rest as optional.",
    action: "If you want to try collagen, run a 12-week trial of a hydrolyzed collagen product with a before-and-after photo in the same light, and keep it only if you can see the difference; put the sunscreen-and-retinoid routine in place first.",
    sources: [
      { cite: "de Miranda, R. B., Weimer, P., & Rossi, R. C. (2021). Effects of hydrolyzed collagen supplementation on skin aging: A systematic review and meta-analysis. International Journal of Dermatology, 60(12), 1449–1461.", note: "Nineteen randomized double-blind trials, 1,125 participants: hydrolyzed collagen improved skin hydration, elasticity and wrinkles versus placebo, with 90 days of use the effective window in the pooled data.", link: doi("10.1111/ijd.15518"), kind: "doi" },
      { cite: "Pu, S.-Y., Huang, Y.-L., Pu, C.-M., et al. (2023). Effects of oral collagen for skin anti-aging: A systematic review and meta-analysis. Nutrients, 15(9), 2080.", note: "Twenty-six randomized trials, 1,721 patients: collagen improved hydration (pooled effect 0.63) and elasticity (0.72), more so beyond eight weeks; the authors identified several biases in the included trials.", link: doi("10.3390/nu15092080"), kind: "doi" },
      { cite: "Sanabria, B., Berger, L. E., Mohd, H., et al. (2023). Clinical efficacy of topical vitamin C on the appearance of wrinkles: A systematic literature review. Journal of Drugs in Dermatology, 22(9), 898–904.", note: "Topical vitamin C trials show modest wrinkle improvement in short, small studies with variable formulations — evidence exists but is thin compared with retinoids.", link: doi("10.36849/JDD.7332"), kind: "doi" },
      { cite: "Kerscher, M., & Buntrock, H. (2011). Anti-aging creams: What really helps? [Anti-Aging-Cremes. Was hilft wirklich?]. Der Hautarzt, 62(8), 607–613.", note: "Dermatology review of anti-aging cream ingredients: controlled evidence supports sunscreens and retinoids and a small number of actives; most marketed creams lack trial support.", link: doi("10.1007/s00105-011-2137-6"), kind: "doi" },
    ],
  },
  {
    id: "gs-health-energy-beauty-diet-skin",
    goal: "health-energy-beauty", tier: "fundamental", section: "9310",
    title: "Eat for Your Skin — Vegetables, Olive Oil, Fish; Less Red Meat and Snacks",
    subtitle: "Across cohorts, higher vitamin C and linoleic acid intake, olive oil and a fruit-rich pattern go with fewer wrinkles; fat- and sugar-heavy patterns go with more",
    evidenceTag: "Moderate",
    impact: { magnitude: 2, latency: "months", durability: "sustained", effort: "moderate" },
    feeds: ["Skin appearance", "Photoaging"],
    description:
      "The diet–skin evidence is observational but consistent across countries. In 4,025 American women, higher vitamin C intake was associated with less wrinkling and dryness, higher linoleic acid with less dryness and atrophy, and higher fat and carbohydrate intake with more wrinkling. In 2,753 Rotterdam adults, women who followed Dutch dietary guidelines had fewer wrinkles, a red-meat-and-snack pattern more and a fruit-dominant pattern fewer. In the French SU.VI.MAX cohort, monounsaturated fat from olive oil — but not from animal sources — and omega-3 intake were associated with less severe photoaging. Elderly cohorts in Greece, Australia and Sweden showed vegetables, olive oil and legumes protective and butter, sugar and processed meat harmful.",
    action: "For the next month, build every dinner around vegetables and a serving of olive oil, eat fish twice a week, and swap the daily snack for fruit; treat the mirror at 12 weeks as the outcome measure.",
    sources: [
      { cite: "Cosgrove, M. C., Franco, O. H., Granger, S. P., Murray, P. G., & Mayes, A. E. (2007). Dietary nutrient intakes and skin-aging appearance among middle-aged American women. American Journal of Clinical Nutrition, 86(4), 1225–1231.", note: "4,025 women aged 40–74 in NHANES: higher vitamin C intake was associated with less wrinkling and dryness, higher linoleic acid with less dryness and atrophy, and higher fat and carbohydrate intake with more wrinkling.", link: doi("10.1093/ajcn/86.4.1225"), kind: "doi" },
      { cite: "Purba, M. B., Kouris-Blazos, A., Wattanapenpaiboon, N., et al. (2001). Skin wrinkling: Can food make a difference? Journal of the American College of Nutrition, 20(1), 71–80.", note: "Elderly cohorts in Greece, Australia and Sweden: higher intake of vegetables, olive oil, legumes and fish was associated with less skin wrinkling in sun-exposed sites, while butter, sugar, milk products and processed meat went with more.", link: doi("10.1080/07315724.2001.10719017"), kind: "doi" },
      { cite: "Mekić, S., Jacobs, L. C., Hamer, M. A., et al. (2019). A healthy diet in women is associated with less facial wrinkles in a large Dutch population-based cohort. Journal of the American Academy of Dermatology, 80(5), 1358–1363.", note: "2,753 Rotterdam Study participants: better adherence to Dutch dietary guidelines was associated with fewer digitally measured wrinkles in women; a red-meat-and-snack pattern with more, a fruit-dominant pattern with fewer.", link: doi("10.1016/j.jaad.2018.03.033"), kind: "doi" },
      { cite: "Latreille, J., Kesse-Guyot, E., Malvy, D., et al. (2013). Association between dietary intake of n-3 polyunsaturated fatty acids and severity of skin photoaging in a middle-aged Caucasian population. Journal of Dermatological Science, 72(3), 233–239.", note: "2,919 SU.VI.MAX participants aged 45–60: higher alpha-linolenic acid intake in men and EPA intake in women were associated with less severe facial photoaging.", link: doi("10.1016/j.jdermsci.2013.07.006"), kind: "doi" },
      { cite: "Latreille, J., Kesse-Guyot, E., Malvy, D., et al. (2012). Dietary monounsaturated fatty acids intake and risk of skin photoaging. PLoS ONE, 7(9), e44490.", note: "Same cohort: monounsaturated fat from olive oil was associated with lower risk of severe photoaging in both sexes, with no association for monounsaturated fat from animal sources.", link: doi("10.1371/journal.pone.0044490"), kind: "doi" },
    ],
  },
  {
    id: "gs-health-energy-beauty-smoking-alcohol-face",
    goal: "health-energy-beauty", tier: "fundamental", section: "9311",
    title: "Quit Smoking and Cut Evening Alcohol — Identical Twins Show the Face Cost",
    subtitle: "In 79 twin pairs the smoking twin had worse eyelid bags, jowls and lip wrinkles; alcohol reduces REM and fragments sleep in a dose-dependent way",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "months", durability: "lasting", effort: "high" },
    feeds: ["Facial aging", "Sleep quality", "Skin tone"],
    description:
      "The cleanest evidence on smoking and appearance comes from identical twins photographed at the Twins Days festival: with genetics held constant, the smoking twin scored worse on upper-eyelid redundancy, lower-lid bags, malar bags, nasolabial folds, upper-lip wrinkles and jowls, and blinded judges picked the smoker as older 57% of the time; even a five-year difference in smoking duration between smoking twins was visible. Cross-sectional data put heavy smokers at nearly five times the risk of premature wrinkling. Alcohol's appearance cost runs partly through sleep: a 2024 meta-analysis found alcohol reduced REM sleep and increased wakefulness in the second half of the night, worse at higher doses. The longevity shelf (7036) carries the mortality side.",
    action: "If you smoke, book a cessation program this month and use the twin photographs as your reason; if you drink, keep alcohol to two or fewer drinks, finished at least three hours before bed, on no more than three nights a week.",
    sources: [
      { cite: "Okada, H. C., Alleyne, B., Varghai, K., Kinder, K., & Guyuron, B. (2013). Facial changes caused by smoking: A comparison between smoking and nonsmoking identical twins. Plastic and Reconstructive Surgery, 132(5), 1085–1092.", note: "79 identical twin pairs discordant for smoking: smoking twins had worse scores for eyelid bags, malar bags, nasolabial folds, lip wrinkles and jowls; a 5-year smoking-duration difference produced visible aging differences.", link: doi("10.1097/PRS.0b013e3182a4c20a"), kind: "doi" },
      { cite: "Kadunce, D. P., Burr, R., Gress, R., Kanner, R., Lyon, J. L., & Zone, J. J. (1991). Cigarette smoking: Risk factor for premature facial wrinkling. Annals of Internal Medicine, 114(10), 840–844.", note: "After adjusting for age, sex and sun exposure, premature wrinkling rose with pack-years; heavy smokers were 4.7 times more likely to be wrinkled than nonsmokers.", link: doi("10.7326/0003-4819-114-10-840"), kind: "doi" },
      { cite: "Gardiner, C., Weakley, J., Burke, L. M., et al. (2024). The effect of alcohol on subsequent sleep in healthy adults: A systematic review and meta-analysis. Sleep Medicine Reviews, 80, 102030.", note: "Meta-analysis in healthy adults: alcohol before bed reduced REM sleep and increased wake after sleep onset in a dose-dependent way — the mechanism behind the 'you look tired' morning after.", link: doi("10.1016/j.smrv.2024.102030"), kind: "doi" },
    ],
  },
  {
    id: "gs-health-energy-beauty-beauty-sleep",
    goal: "health-energy-beauty", tier: "fundamental", section: "9312",
    title: "Beauty Sleep Is Measurable — Rested Faces Are Rated Healthier, More Attractive and More Approachable",
    subtitle: "Untrained raters scored the same people as less healthy and less attractive after sleep loss, and were less willing to socialize with them",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "days", durability: "transient", effort: "low" },
    feeds: ["Perceived attractiveness", "Social appeal"],
    description:
      "Two Karolinska experiments photographed the same people after normal sleep and after sleep loss and had untrained observers rate the photos. After 31 hours awake following a short night, people were rated less healthy, more tired and less attractive; after two nights of restricted sleep, raters were less inclined to socialize with them and rated them less attractive, less healthy and sleepier, with no change in perceived trustworthiness. Combined with the regularity finding in 9302, the practical point is that the cheapest appearance intervention on this shelf is the one you already own.",
    action: "Protect a consistent 7–9 hour sleep window on the two nights before anything where your appearance matters — an interview, a date, a photo — and treat it as part of the preparation rather than optional.",
    sources: [
      { cite: "Axelsson, J., Sundelin, T., Ingre, M., Van Someren, E. J. W., Olsson, A., & Lekander, M. (2010). Beauty sleep: Experimental study on the perceived health and attractiveness of sleep deprived people. BMJ, 341, c6614.", note: "23 adults photographed after 8 hours' sleep and after 31 hours awake: 65 raters scored the sleep-deprived photos less healthy (63 vs 68), more tired (53 vs 44) and less attractive (38 vs 40) on 100-mm scales.", link: doi("10.1136/bmj.c6614"), kind: "doi" },
      { cite: "Sundelin, T., Lekander, M., Sorjonen, K., & Axelsson, J. (2017). Negative effects of restricted sleep on facial appearance and social appeal. Royal Society Open Science, 4(5), 160918.", note: "25 participants photographed after two nights of restricted sleep and after normal sleep: 122 raters were less inclined to socialize with the sleep-restricted faces and rated them less attractive, less healthy and sleepier.", link: doi("10.1098/rsos.160918"), kind: "doi" },
      { cite: "Windred, D. P., Burns, A. C., Lane, J. M., et al. (2024). Sleep regularity is a stronger predictor of mortality risk than sleep duration: A prospective cohort study. Sleep, 47(1), zsad253.", note: "Regular sleep–wake timing predicted lower mortality more strongly than duration in 60,977 adults — the same habit that keeps the face rested keeps the body healthier.", link: doi("10.1093/sleep/zsad253"), kind: "doi" },
    ],
  },
  {
    id: "gs-health-energy-beauty-hair-loss",
    goal: "health-energy-beauty", tier: "advanced", section: "9313",
    title: "Hair Loss — What the Trials Tested (Described, Not Advised)",
    subtitle: "Finasteride 1 mg and 5% topical minoxidil have two-year and 48-week randomized trials; low-dose oral minoxidil did not beat topical in a 2024 head-to-head",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "months", durability: "sustained", effort: "moderate" },
    feeds: ["Hair density", "Confidence"],
    description:
      "Male-pattern hair loss has two treatments with large randomized trials. In two one-year trials of 1,553 men (1,215 continuing to two years), oral finasteride 1 mg increased hair counts by 107 and 138 hairs in a one-inch circle at one and two years while placebo lost hair. In a 48-week trial of 393 men, 5% topical minoxidil beat 2% and placebo, with 45% more regrowth than 2% and more scalp itching. A 2024 double-blind trial found oral minoxidil 5 mg was not superior to topical 5% overall, with hypertrichosis in half the oral group. All are prescription or physician-guided decisions with side-effect profiles the trials describe; this cluster describes, it does not advise.",
    action: "If thinning bothers you, see a dermatologist within the next three months rather than a supplement aisle, take dated photographs under the same light before starting anything, and judge any treatment at 6 and 12 months.",
    sources: [
      { cite: "Kaufman, K. D., Olsen, E. A., Whiting, D., et al. (1998). Finasteride in the treatment of men with androgenetic alopecia. Finasteride Male Pattern Hair Loss Study Group. Journal of the American Academy of Dermatology, 39(4 Pt 1), 578–589.", note: "1,553 men in two one-year trials with a blinded second year: finasteride 1 mg increased hair counts by 107 and 138 hairs at 1 and 2 years versus placebo, which lost hair progressively; adverse effects were minimal.", link: doi("10.1016/s0190-9622(98)70007-6"), kind: "doi" },
      { cite: "Olsen, E. A., Dunlap, F. E., Funicella, T., Koperski, J. A., Swinehart, J. M., Tschen, E. H., & Trancik, R. J. (2002). A randomized clinical trial of 5% topical minoxidil versus 2% topical minoxidil and placebo in the treatment of androgenetic alopecia in men. Journal of the American Academy of Dermatology, 47(3), 377–385.", note: "393 men, 48 weeks: 5% minoxidil was superior to 2% and placebo on hair counts and scalp coverage, with 45% more regrowth than 2% at week 48 and more pruritus and irritation.", link: doi("10.1067/mjd.2002.124088"), kind: "doi" },
      { cite: "Penha, M. A., Miot, H. A., Kasprzak, M., & Müller Ramos, P. (2024). Oral minoxidil vs topical minoxidil for male androgenetic alopecia: A randomized clinical trial. JAMA Dermatology, 160(6), 600–605.", note: "Double-blind trial of 90 men: oral minoxidil 5 mg daily did not demonstrate superiority over topical 5% twice daily on hair density at 24 weeks; hypertrichosis occurred in 49% of the oral group.", link: doi("10.1001/jamadermatol.2024.0284"), kind: "doi" },
    ],
  },
  {
    id: "gs-health-energy-beauty-oral-appearance",
    goal: "health-energy-beauty", tier: "fundamental", section: "9314",
    title: "Teeth Are Read as Character — Keep Them Clean, White and Straight Enough",
    subtitle: "Raters judge people with visible decay as less socially competent and less intelligent; whitened teeth are read as younger and more successful",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "low" },
    feeds: ["First impressions", "Perceived age", "Confidence"],
    description:
      "A line of experiments from King's College London digitally alters the teeth in otherwise identical photographs and asks strangers to judge the person. Visible dental disease lowered ratings of social competence, intellectual achievement and psychological adjustment in British and Chinese raters alike; darkened teeth lowered ratings of popularity, success and attractiveness while whitened teeth raised them and made faces look younger; and social-comparison context shifts the judgments. The boundary: these are perception studies, not trials of dental treatments on life outcomes — but the perception effect is large and the fix is a dentist and a toothbrush.",
    action: "Book a dental cleaning and check-up this month if it has been more than a year, brush twice a day with a fluoride toothpaste and floss nightly, and discuss safe whitening with the dentist rather than buying it online.",
    sources: [
      { cite: "Newton, J. T., Subramanian, S. S., Westland, S., Gupta, A. K., Luo, W., & Joiner, A. (2021). The impact of tooth colour on the perceptions of age and social judgements. Journal of Dentistry, 112, 103771.", note: "Fifty raters judged 54 digitally modified photographs: darkened teeth drew the poorest ratings across popularity, success, intelligence and attractiveness, whitened teeth the highest, and whitened faces were perceived as younger.", link: doi("10.1016/j.jdent.2021.103771"), kind: "doi" },
      { cite: "Kershaw, S., Newton, J. T., & Williams, D. M. (2008). The influence of tooth colour on the perceptions of personal characteristics among female dental patients: Comparisons of unmodified, decayed and 'whitened' teeth. British Dental Journal, 204(5), E9.", note: "180 women rated images altered to show unmodified, decayed or whitened teeth: decay lowered judgments of social competence, intellectual ability, psychological adjustment and relationship satisfaction; whitening raised them.", link: doi("10.1038/bdj.2008.134"), kind: "doi" },
      { cite: "Al-Kharboush, G. H., Asimakopoulou, K., AlJabaa, A. H., & Newton, J. T. (2017). The role of social comparison in social judgments of dental appearance: An experimental study. Journal of Dentistry, 61, 33–38.", note: "Experimental study showing that judgments of dental appearance depend on social comparison context — the same smile is rated differently depending on what it is seen next to.", link: doi("10.1016/j.jdent.2017.04.003"), kind: "doi" },
      { cite: "Jeremiah, H. G., Bister, D., & Newton, J. T. (2011). Social perceptions of adults wearing orthodontic appliances: A cross-sectional study. European Journal of Orthodontics, 33(5), 476–482.", note: "Cross-sectional rating study of adults wearing orthodontic appliances — relevant to the adult who is weighing straightening: the appliance phase itself changes how one is perceived.", link: doi("10.1093/ejo/cjq069"), kind: "doi" },
      { cite: "Feng, X. P., Newton, J. T., & Robinson, P. G. (2001). The impact of dental appearance on perceptions of personal characteristics among Chinese people in the United Kingdom. International Dental Journal, 51(4), 282–286.", note: "Replication among Chinese raters in the UK: dental appearance influenced judgments of personal characteristics in the same direction as in British samples.", link: doi("10.1002/j.1875-595x.2001.tb00839.x"), kind: "doi" },
    ],
  },
  {
    id: "gs-health-energy-beauty-posture",
    goal: "health-energy-beauty", tier: "fundamental", section: "9315",
    title: "Sit and Stand Upright — It Changes How You Feel and How You Are Read; 'Power Posing' Hormones Do Not Replicate",
    subtitle: "Randomized posture trials show upright sitting improves mood, self-esteem and fatigue under stress; open postures are rated more attractive; the hormone claims failed a large replication",
    evidenceTag: "Moderate",
    impact: { magnitude: 2, latency: "days", durability: "transient", effort: "low" },
    feeds: ["Mood under stress", "Perceived confidence"],
    description:
      "The honest posture literature splits in two. Randomized trials that taped participants into upright or slumped sitting found the upright group reported higher self-esteem, better mood and less fear during a stress test, and people with depressive symptoms sitting upright had more positive affect and less fatigue. In speed-dating and photo studies, expansive, open postures were rated more attractive and got more 'yes' responses. What did not replicate is the famous claim that two minutes of power posing changes testosterone, cortisol and risk-taking — a 200-person replication found no hormonal or behavioral effect. Use posture for how you feel and are seen; do not expect a hormone change.",
    action: "Set a phone reminder three times a day to sit tall — ears over shoulders, shoulders back — and hold it for the next task; before any stressful conversation, spend one minute standing upright and open rather than hunched over your phone.",
    sources: [
      { cite: "Nair, S., Sagar, M., Sollers, J., Consedine, N., & Broadbent, E. (2015). Do slumped and upright postures affect stress responses? A randomized trial. Health Psychology, 34(6), 632–641.", note: "74 participants taped into upright or slumped seated posture during a stress task: upright participants reported higher self-esteem, better mood and lower fear, spoke more words and used fewer negative-emotion words.", link: doi("10.1037/hea0000146"), kind: "doi" },
      { cite: "Wilkes, C., Kydd, R., Sagar, M., & Broadbent, E. (2017). Upright posture improves affect and fatigue in people with depressive symptoms. Journal of Behavior Therapy and Experimental Psychiatry, 54, 143–149.", note: "61 people with mild-to-moderate depressive symptoms randomized to upright or usual posture during a stress task: upright posture increased high-arousal positive affect and reduced fatigue and self-focus.", link: doi("10.1016/j.jbtep.2016.07.015"), kind: "doi" },
      { cite: "Vacharkulksemsuk, T., Reit, E., Khambatta, P., Eastwick, P. W., Finkel, E. J., & Carney, D. R. (2016). Dominant, open nonverbal displays are attractive at zero-acquaintance. Proceedings of the National Academy of Sciences, 113(15), 4009–4014.", note: "In a speed-dating field study and an online dating experiment, expansive open postures increased attractiveness ratings and 'yes' responses — posture is read by others at first sight.", link: doi("10.1073/pnas.1508932113"), kind: "doi" },
      { cite: "Ranehill, E., Dreber, A., Johannesson, M., Leiberg, S., Sul, S., & Weber, R. A. (2015). Assessing the robustness of power posing: No effect on hormones and risk tolerance in a large sample of men and women. Psychological Science, 26(5), 653–656.", note: "Replication with 200 participants: power posing produced a small increase in felt power but no effect on testosterone, cortisol or risk tolerance — the hormonal claim does not hold.", link: doi("10.1177/0956797614553946"), kind: "doi" },
    ],
  },
  {
    id: "gs-health-energy-beauty-resistance-training",
    goal: "health-energy-beauty", tier: "moderate", section: "9316",
    title: "Lift Twice a Week Per Muscle, 10+ Hard Sets, Any Load — For Shape and for Body Image",
    subtitle: "Meta-analyses: training a muscle twice weekly beats once, more than 10 weekly sets grows more, light and heavy loads build similar muscle; resistance training improves body image",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "months", durability: "sustained", effort: "moderate" },
    feeds: ["Body composition", "Body image", "Resting metabolism"],
    description:
      "Resistance training is the appearance intervention with the most trial evidence and the one most people under-dose. Meta-analyses show that training a muscle group twice a week produces more hypertrophy than once, that muscle growth rises with weekly volume with more than 10 sets per muscle outperforming fewer, that light loads taken near failure build muscle as well as heavy loads (heavy loads win for strength), and that higher frequency helps strength mainly by allowing more volume. A systematic review finds resistance training improves body image across populations, and a review of health effects documents fat loss, resting-metabolic-rate gains and better glucose control. The longevity shelf (7002) holds the mortality and grip data.",
    action: "Do two full-body sessions a week for 12 weeks — six exercises, three sets each, the last two reps of every set hard — adding weight or a rep each week, and take front and side photos every four weeks in the same light.",
    sources: [
      { cite: "Schoenfeld, B. J., Ogborn, D., & Krieger, J. W. (2016). Effects of resistance training frequency on measures of muscle hypertrophy: A systematic review and meta-analysis. Sports Medicine, 46(11), 1689–1697.", note: "Ten studies: training a muscle group twice a week produced greater hypertrophy than once a week (effect size 0.49 vs 0.30).", link: doi("10.1007/s40279-016-0543-8"), kind: "doi" },
      { cite: "Schoenfeld, B. J., Ogborn, D., & Krieger, J. W. (2017). Dose-response relationship between weekly resistance training volume and increases in muscle mass: A systematic review and meta-analysis. Journal of Sports Sciences, 35(11), 1073–1082.", note: "Meta-analysis: muscle growth rose with weekly set volume, with 10 or more sets per muscle per week producing greater gains than fewer than 10.", link: doi("10.1080/02640414.2016.1210197"), kind: "doi" },
      { cite: "Schoenfeld, B. J., Grgic, J., Ogborn, D., & Krieger, J. W. (2017). Strength and hypertrophy adaptations between low- vs. high-load resistance training: A systematic review and meta-analysis. Journal of Strength and Conditioning Research, 31(12), 3508–3523.", note: "Twenty-one studies: low-load (under 60% 1RM) and high-load training produced similar hypertrophy when sets were taken near failure, while high loads produced greater strength gains.", link: doi("10.1519/JSC.0000000000002200"), kind: "doi" },
      { cite: "Schoenfeld, B. J., Grgic, J., & Krieger, J. (2019). How many times per week should a muscle be trained to maximize muscle hypertrophy? A systematic review and meta-analysis of studies examining the effects of resistance training frequency. Journal of Sports Sciences, 37(11), 1286–1295.", note: "Updated meta-analysis: when volume is equated, frequency has little independent effect on hypertrophy — frequency matters because it lets you do more quality sets.", link: doi("10.1080/02640414.2018.1555906"), kind: "doi" },
      { cite: "Grgic, J., Schoenfeld, B. J., Davies, T. B., Lazinica, B., Krieger, J. W., & Pedisic, Z. (2018). Effect of resistance training frequency on gains in muscular strength: A systematic review and meta-analysis. Sports Medicine, 48(5), 1207–1220.", note: "Twenty-two studies: higher training frequency was associated with greater strength gains, an effect that disappeared when weekly volume was equated.", link: doi("10.1007/s40279-018-0872-x"), kind: "doi" },
      { cite: "SantaBarbara, N. J., Whitworth, J. W., & Ciccolo, J. T. (2017). A systematic review of the effects of resistance training on body image. Journal of Strength and Conditioning Research, 31(10), 2880–2888.", note: "Systematic review: resistance training interventions improved body image across studies and populations, with effects partly independent of actual body-composition change.", link: doi("10.1519/JSC.0000000000002135"), kind: "doi" },
      { cite: "SantaBarbara, N. J., Nosrat, S., Whitworth, J. W., et al. (2023). Acute psychological effects of resistance exercise in men with symptoms of muscle dysmorphia: A pilot study. Journal of Strength and Conditioning Research, 37(2), 277–283.", note: "Pilot study of the acute psychological response to resistance exercise in men with muscle-dysmorphia symptoms — a caution that appearance-driven training can feed, as well as fix, body-image problems.", link: doi("10.1519/JSC.0000000000003615"), kind: "doi" },
      { cite: "Westcott, W. L. (2012). Resistance training is medicine: Effects of strength training on health. Current Sports Medicine Reports, 11(4), 209–216.", note: "Review of strength training's effects on body composition, resting metabolic rate, glucose control, blood pressure and bone — the health case that accompanies the appearance case.", link: doi("10.1249/JSR.0b013e31825dabb8"), kind: "doi" },
    ],
  },
  {
    id: "gs-health-energy-beauty-weight-maintenance-nwcr",
    goal: "health-energy-beauty", tier: "moderate", section: "9317",
    title: "Keep Weight Off the Way the Registry Does — Daily Activity, Breakfast, Weekly Weighing, Same Diet on Weekends",
    subtitle: "NWCR members maintained 23 kg of a 31 kg loss at 10 years; regain tracked drops in activity, restraint and self-weighing",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "months", durability: "lasting", effort: "moderate" },
    feeds: ["Weight stability", "Body composition", "Energy"],
    description:
      "The National Weight Control Registry follows people who lost at least 13.6 kg and kept it off for a year. Its members report about an hour a day of physical activity, eating breakfast, a consistent low-fat, lower-calorie diet kept the same on weekends, and frequent self-weighing. In the 10-year follow-up of 2,886 members, mean loss was 31.3 kg at entry and 23.1 kg at ten years, with over 87% still maintaining at least a 10% loss; regain was predicted by decreases in leisure activity, dietary restraint and self-weighing frequency and increases in dietary fat and disinhibition. A 2022 randomized trial found adding time-restricted eating to calorie restriction produced no extra weight loss — the calories, not the clock, did the work.",
    action: "Weigh yourself every morning and log it weekly, eat breakfast, keep your weekday eating pattern on weekends, and accumulate 60 minutes of daily movement (walking counts) — the four habits that separate maintainers from regainers.",
    sources: [
      { cite: "Klem, M. L., Wing, R. R., McGuire, M. T., Seagle, H. M., & Hill, J. O. (1997). A descriptive study of individuals successful at long-term maintenance of substantial weight loss. American Journal of Clinical Nutrition, 66(2), 239–246.", note: "The founding NWCR description: 784 people who had lost an average 30 kg and kept it off five years reported a low-fat, low-calorie diet, high physical activity and regular self-monitoring.", link: doi("10.1093/ajcn/66.2.239"), kind: "doi" },
      { cite: "Wing, R. R., & Phelan, S. (2005). Long-term weight loss maintenance. American Journal of Clinical Nutrition, 82(1 Suppl), 222S–225S.", note: "Summary of NWCR behaviors: about an hour of daily activity, breakfast, a consistent eating pattern across weekdays and weekends, and weekly or more frequent weighing; maintaining a loss for 2–5 years greatly reduces regain risk.", link: doi("10.1093/ajcn/82.1.222S"), kind: "doi" },
      { cite: "Thomas, J. G., Bond, D. S., Phelan, S., Hill, J. O., & Wing, R. R. (2014). Weight-loss maintenance for 10 years in the National Weight Control Registry. American Journal of Preventive Medicine, 46(1), 17–23.", note: "2,886 members over ten years: mean loss 31.3 kg at entry, 23.8 kg at 5 years and 23.1 kg at 10; over 87% kept off at least 10%; regain tracked decreases in activity, restraint and self-weighing and increases in dietary fat and disinhibition.", link: doi("10.1016/j.amepre.2013.08.019"), kind: "doi" },
      { cite: "Liu, D., Huang, Y., Huang, C., et al. (2022). Calorie restriction with or without time-restricted eating in weight loss. New England Journal of Medicine, 386(16), 1495–1504.", note: "Twelve-month randomized trial of 139 adults with obesity: adding an 8-hour eating window to calorie restriction did not produce more weight loss than calorie restriction alone (−8.0 vs −6.3 kg, not significant).", link: doi("10.1056/NEJMoa2114833"), kind: "doi" },
    ],
  },
  {
    id: "gs-health-energy-beauty-glp1-described",
    goal: "health-energy-beauty", tier: "elite", section: "9318",
    title: "GLP-1 Medications — What the Trials Showed, Including What Happens When You Stop",
    subtitle: "Semaglutide −14.9% and tirzepatide up to −20.9% body weight over 68–72 weeks; two-thirds of the loss returned within a year of stopping unless exercise continued",
    evidenceTag: "Strong",
    impact: { magnitude: 5, latency: "months", durability: "sustained", effort: "high" },
    feeds: ["Body weight", "Cardiometabolic risk", "Appearance"],
    description:
      "Described, not advised: these are prescription drugs with gastrointestinal side effects, cost, and lean-mass considerations that belong with a physician. In STEP 1, weekly semaglutide 2.4 mg produced 14.9% weight loss at 68 weeks versus 2.4% with placebo; in SURMOUNT-1, tirzepatide produced 15.0–20.9% at 72 weeks. Stopping matters: after withdrawal in the STEP 1 extension, participants regained two-thirds of the lost weight within a year, and in STEP 4 those switched to placebo regained 6.9% while continuers lost a further 7.9%. The most useful trial for this shelf combined a GLP-1 drug with supervised exercise and then withdrew both: the exercise-plus-drug group kept more of its loss and its fitness after a year off treatment. The longevity shelf (7010) covers the cardiovascular outcomes.",
    action: "If you and your physician decide on a GLP-1 medication, treat the prescription as a multi-year program: pair it from day one with the twice-weekly resistance training in 9316 and 150 minutes of weekly cardio, and agree in advance how the drug will be tapered rather than stopped.",
    sources: [
      { cite: "Wilding, J. P. H., Batterham, R. L., Calanna, S., et al. (2021). Once-weekly semaglutide in adults with overweight or obesity. New England Journal of Medicine, 384(11), 989–1002.", note: "STEP 1: 1,961 adults randomized to semaglutide 2.4 mg weekly or placebo with lifestyle intervention: mean weight change −14.9% versus −2.4% at 68 weeks; gastrointestinal events were the main side effect.", link: doi("10.1056/NEJMoa2032183"), kind: "doi" },
      { cite: "Jastreboff, A. M., Aronne, L. J., Ahmad, N. N., et al. (2022). Tirzepatide once weekly for the treatment of obesity. New England Journal of Medicine, 387(3), 205–216.", note: "SURMOUNT-1: 2,539 adults randomized to tirzepatide 5, 10 or 15 mg or placebo: mean weight change −15.0%, −19.5% and −20.9% versus −3.1% at 72 weeks.", link: doi("10.1056/NEJMoa2206038"), kind: "doi" },
      { cite: "Wilding, J. P. H., Batterham, R. L., Davies, M., et al. (2022). Weight regain and cardiometabolic effects after withdrawal of semaglutide: The STEP 1 trial extension. Diabetes, Obesity and Metabolism, 24(8), 1553–1564.", note: "One year after semaglutide and lifestyle intervention were withdrawn, participants regained two-thirds of their prior weight loss and most cardiometabolic improvements reverted toward baseline.", link: doi("10.1111/dom.14725"), kind: "doi" },
      { cite: "Rubino, D., Abrahamsson, N., Davies, M., et al. (2021). Effect of continued weekly subcutaneous semaglutide vs placebo on weight loss maintenance in adults with overweight or obesity: The STEP 4 randomized clinical trial. JAMA, 325(14), 1414–1425.", note: "After a 20-week run-in on semaglutide, those switched to placebo regained 6.9% of body weight over 48 weeks while those continuing lost a further 7.9% — continuation is what maintains the effect.", link: doi("10.1001/jama.2021.3224"), kind: "doi" },
      { cite: "Jensen, S. B. K., Blond, M. B., Sandsdal, R. M., et al. (2024). Healthy weight loss maintenance with exercise, GLP-1 receptor agonist, or both combined followed by one year without treatment: A post-treatment analysis of a randomised placebo-controlled trial. EClinicalMedicine, 69, 102475.", note: "One year after withdrawing liraglutide and/or supervised exercise, the combined exercise-plus-drug group maintained more weight loss and better fitness than the drug-alone group — the case for pairing any GLP-1 program with exercise.", link: doi("10.1016/j.eclinm.2024.102475"), kind: "doi" },
    ],
  },
  {
    id: "gs-health-energy-beauty-grip-mobility",
    goal: "health-energy-beauty", tier: "fundamental", section: "9319",
    title: "Train the Two Numbers That Predict Your Future — Grip and Chair-Rise",
    subtitle: "Each 5 kg less grip strength meant 16% higher mortality across 17 countries; slow chair-rises and gait in your 70s predict disability four years later",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "months", durability: "lasting", effort: "moderate" },
    feeds: ["Youthful movement", "Independence", "Injury resilience"],
    description:
      "Two cheap tests track how young your body moves. In the PURE study of 139,691 adults in 17 countries, each 5 kg reduction in grip strength was associated with a 16% higher risk of death from any cause and 17% higher cardiovascular mortality, and grip predicted mortality better than systolic blood pressure. In 1,122 Americans over 70, a short battery of chair-rises, gait speed and balance predicted disability four years later even in people with no disability at baseline; a review of grip dynamometry finds it predicts future function, hospital stay and mortality. Both improve with the resistance training in 9316; this cluster is about measuring them.",
    action: "This week, time five sit-to-stands from a chair without using your arms and, if you can, measure grip with a dynamometer at a gym or clinic; retest every three months and treat any decline as a signal to add leg and grip work.",
    sources: [
      { cite: "Leong, D. P., Teo, K. K., Rangarajan, S., et al. (2015). Prognostic value of grip strength: Findings from the Prospective Urban Rural Epidemiology (PURE) study. The Lancet, 386(9990), 266–273.", note: "139,691 adults in 17 countries followed four years: each 5 kg lower grip strength was associated with 16% higher all-cause and 17% higher cardiovascular mortality, and grip was a stronger predictor than systolic blood pressure.", link: doi("10.1016/S0140-6736(14)62000-6"), kind: "doi" },
      { cite: "Bohannon, R. W. (2008). Hand-grip dynamometry predicts future outcomes in aging adults. Journal of Geriatric Physical Therapy, 31(1), 3–10.", note: "Review of prospective studies: grip strength measured by dynamometer predicts future mortality, disability, complications and length of hospital stay in aging adults.", link: doi("10.1519/00139143-200831010-00002"), kind: "doi" },
      { cite: "Guralnik, J. M., Ferrucci, L., Simonsick, E. M., Salive, M. E., & Wallace, R. B. (1995). Lower-extremity function in persons over the age of 70 years as a predictor of subsequent disability. New England Journal of Medicine, 332(9), 556–561.", note: "1,122 non-disabled adults over 70: a short battery of chair-rises, walking speed and balance strongly predicted disability in daily and mobility tasks four years later.", link: doi("10.1056/NEJM199503023320902"), kind: "doi" },
      { cite: "Westcott, W. L. (2012). Resistance training is medicine: Effects of strength training on health. Current Sports Medicine Reports, 11(4), 209–216.", note: "Summarizes how progressive resistance training restores muscle mass, strength and function in adults of all ages — the intervention that moves both numbers.", link: doi("10.1249/JSR.0b013e31825dabb8"), kind: "doi" },
    ],
  },
  {
    id: "gs-health-energy-beauty-hearing-vision",
    goal: "health-energy-beauty", tier: "elite", section: "9320",
    title: "Protect Hearing and Eyes — Hearing Aids Slowed Cognitive Decline 48% in At-Risk Adults; Outdoor Time Protects Children's Eyes; Blue-Light Glasses Don't",
    subtitle: "Untreated hearing loss accelerates cognitive decline; the ACHIEVE trial's hearing intervention cut three-year decline by nearly half in the higher-risk cohort",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "months", durability: "lasting", effort: "high" },
    feeds: ["Cognitive youth", "Social engagement", "Vision"],
    description:
      "Hearing is an appearance-and-energy issue because untreated loss makes people withdraw and look older than they are, and because it tracks cognition. In the Health ABC cohort, older adults with hearing loss had 41% faster global cognitive decline and 24% higher risk of incident impairment; 8-year data from ARIC confirm the link to dementia. The ACHIEVE randomized trial gave 977 adults aged 70–84 hearing aids and counseling or health education: no effect in the total cohort, but in the higher-risk ARIC subgroup the hearing intervention reduced three-year cognitive decline by 48%. For eyes, two randomized school trials show outdoor time reduces myopia onset in children, while a Cochrane review finds blue-light-filtering lenses do not reduce eyestrain or improve sleep. The longevity shelf (7029) covers the dementia-risk framing.",
    action: "Get a baseline audiogram and eye exam this year if you are over 45 (sooner if you notice strain), wear hearing protection above 85 dB, and if hearing loss is found, treat fitting hearing aids as a cognitive-health investment rather than a concession to age.",
    sources: [
      { cite: "Lin, F. R., Pike, J. R., Albert, M. S., et al. (2023). Hearing intervention versus health education control to reduce cognitive decline in older adults with hearing loss in the USA (ACHIEVE): A multicentre, randomised controlled trial. The Lancet, 402(10404), 786–797.", note: "977 adults aged 70–84 randomized to hearing aids plus counseling or health education: no difference in the whole cohort, but a 48% reduction in three-year cognitive decline in the higher-risk ARIC subgroup.", link: doi("10.1016/S0140-6736(23)01406-X"), kind: "doi" },
      { cite: "Lin, F. R., Yaffe, K., Xia, J., et al. (2013). Hearing loss and cognitive decline in older adults. JAMA Internal Medicine, 173(4), 293–299.", note: "1,984 older adults followed six years: baseline hearing loss was associated with 41% faster decline on a global cognitive test, 32% faster on executive function, and a 24% higher risk of incident cognitive impairment.", link: doi("10.1001/jamainternmed.2013.1868"), kind: "doi" },
      { cite: "Deal, J. A., Shin, J. J., Jiang, K., et al. (2026). Hearing loss and incident dementia over 8 years in Black and White older adults: The Atherosclerosis Risk in Communities Neurocognitive Study. Frontiers in Epidemiology, 6, 1798451.", note: "Eight-year ARIC follow-up linking audiometric hearing loss with incident dementia in both Black and White older adults — the observational base beneath the ACHIEVE trial.", link: doi("10.3389/fepid.2026.1798451"), kind: "doi" },
      { cite: "Singh, S., Keller, P. R., Busija, L., et al. (2023). Blue-light filtering spectacle lenses for visual performance, sleep, and macular health in adults. Cochrane Database of Systematic Reviews, 8, CD013244.", note: "Cochrane review of 17 randomized trials: blue-light-filtering lenses probably do not reduce eyestrain from computer use and their effects on sleep and macular health are uncertain — no basis for the marketing.", link: doi("10.1002/14651858.CD013244.pub2"), kind: "doi" },
      { cite: "He, M., Xiang, F., Zeng, Y., et al. (2015). Effect of time spent outdoors at school on the development of myopia among children in China: A randomized clinical trial. JAMA, 314(11), 1142–1148.", note: "Cluster-randomized trial of 1,903 children: adding a 40-minute outdoor class each school day reduced the three-year incidence of myopia from 39.5% to 30.4%.", link: doi("10.1001/jama.2015.10803"), kind: "doi" },
      { cite: "Wu, P.-C., Tsai, C.-L., Wu, H.-L., Yang, Y.-H., & Kuo, H.-K. (2013). Outdoor activity during class recess reduces myopia onset and progression in school children. Ophthalmology, 120(5), 1080–1085.", note: "Taiwanese school trial: outdoor recess reduced new myopia onset (8.4% vs 17.7%) and myopic shift over one year — a family protocol for children's eyes.", link: doi("10.1016/j.ophtha.2012.11.009"), kind: "doi" },
    ],
  },
  {
    id: "gs-health-energy-beauty-cosmetic-procedures-honest",
    goal: "health-energy-beauty", tier: "elite", section: "9321",
    title: "Cosmetic Surgery — Satisfaction Is High, Self-Esteem Gains Are Small, and Pre-Existing Distress Predicts Regret",
    subtitle: "Prospective studies show satisfaction with the treated feature but little change in general self-esteem or mental health; women with prior symptoms fared worse",
    evidenceTag: "Moderate",
    impact: { magnitude: 2, latency: "months", durability: "sustained", effort: "high" },
    callout: "Rated honestly at 2: cosmetic surgery reliably improves satisfaction with the specific feature and body-area image, but population-based follow-up found no improvement — and in some domains worsening — in general mental health, and the women most likely to seek surgery had more pre-existing symptoms. It is an elite-tier spend because of cost and risk, not because of large well-being returns.",
    feeds: ["Feature-specific satisfaction", "Body image"],
    description:
      "The evidence is more sober than the marketing. A prospective multi-site study found high patient satisfaction and improved body image for the treated feature after cosmetic surgery, with general self-esteem and quality of life roughly unchanged. In a 13-year Norwegian population follow-up, women who went on to have cosmetic surgery had more depression, anxiety, eating problems and suicidal ideation beforehand, and surgery did not improve those outcomes afterward. A Medical Journal of Australia review reached the same conclusion: psychosocial benefit is real but modest and feature-specific, and screening for body dysmorphic disorder matters. Protocol: fix the fundamentals first, then decide with a board-certified surgeon and, if there is any history of body-image distress, a psychologist.",
    action: "If you are considering a procedure, first run 9307, 9308, 9312 and 9316 for six months and re-photograph; if you still want it, consult a board-certified surgeon and ask specifically about the evidence for the psychological outcome you are hoping for.",
    sources: [
      { cite: "von Soest, T., Kvalem, I. L., & Wichstrøm, L. (2012). Predictors of cosmetic surgery and its effects on psychological factors and mental health: A population-based follow-up study among Norwegian females. Psychological Medicine, 42(3), 617–626.", note: "13-year follow-up of 1,597 Norwegian women: those who had cosmetic surgery had more depression, anxiety, eating problems and suicidal ideation beforehand, and surgery did not improve these outcomes afterward.", link: doi("10.1017/S0033291711001267"), kind: "doi" },
      { cite: "Sarwer, D. B., Gibbons, L. M., Magee, L., et al. (2005). A prospective, multi-site investigation of patient satisfaction and psychosocial status following cosmetic surgery. Aesthetic Surgery Journal, 25(3), 263–269.", note: "Prospective multi-site study: patients reported high satisfaction and improved body image for the treated feature at follow-up, with smaller or absent changes in general self-esteem and quality of life.", link: doi("10.1016/j.asj.2005.03.009"), kind: "doi" },
      { cite: "Sarwer, D. B., Cash, T. F., Magee, L., et al. (2005). Female college students and cosmetic surgery: An investigation of experiences, attitudes, and body image. Plastic and Reconstructive Surgery, 115(3), 931–938.", note: "Survey of 559 college women: interest in cosmetic surgery was linked to body dissatisfaction, media exposure and teasing history — the psychological profile clinicians are asked to screen for.", link: doi("10.1097/01.prs.0000153204.37065.d3"), kind: "doi" },
      { cite: "Castle, D. J., Honigman, R. J., & Phillips, K. A. (2002). Does cosmetic surgery improve psychosocial wellbeing? Medical Journal of Australia, 176(12), 601–604.", note: "Review concluding that most patients are satisfied and show modest psychosocial gains, that benefits are feature-specific, and that body dysmorphic disorder predicts poor outcomes and should be screened for.", link: doi("10.5694/j.1326-5377.2002.tb04593.x"), kind: "doi" },
    ],
  },
  {
    id: "gs-health-energy-beauty-myth-detox",
    goal: "health-energy-beauty", tier: "fundamental", section: "9322",
    title: "Myth: 'Detox' Cleanses and Miracle Anti-Aging Creams",
    subtitle: "No compelling evidence that commercial detox diets remove toxins or produce durable benefits; creams without sunscreen or retinoids have no comparable trials",
    evidenceTag: "Strong",
    impact: { magnitude: 1, latency: "days", durability: "transient", effort: "moderate" },
    callout: "Rated at the floor. A critical review of the detox literature found no compelling evidence that commercial detox diets eliminate toxins or improve health, with the only weight loss attributable to calorie restriction, and it noted safety concerns with prolonged fasting and unregulated products. Dermatology reviews find most anti-aging cream claims unsupported by controlled trials. Your liver and kidneys are the detox; sunscreen and a retinoid are the creams.",
    feeds: ["Money saved", "Realistic expectations"],
    description:
      "The 'detox' market sells the feeling of a fresh start. The evidence review is blunt: the handful of studies are small, uncontrolled and often industry-run, none demonstrate removal of named toxins, and the acute weight loss is water and calories. The parallel for skin is the shelf of creams whose active ingredients lack any trial of the kind sunscreen and tretinoin have; vitamin C serums sit between with thin evidence. Spend the money on the fundamentals of this shelf instead.",
    action: "Skip the cleanse; if you want a reset, do a two-week alcohol-free, sugar-free, early-bedtime fortnight and keep whichever habit felt best. Read any cream's ingredient list for a retinoid or SPF before paying for it.",
    sources: [
      { cite: "Klein, A. V., & Kiat, H. (2015). Detox diets for toxin elimination and weight management: A critical review of the evidence. Journal of Human Nutrition and Dietetics, 28(6), 675–686.", note: "Critical review: no compelling evidence that commercial detox diets eliminate toxins or produce sustained health benefits; weight loss reflects calorie restriction and prolonged fasting and unregulated products carry risks.", link: doi("10.1111/jhn.12286"), kind: "doi" },
      { cite: "Kerscher, M., & Buntrock, H. (2011). Anti-aging creams: What really helps? [Anti-Aging-Cremes. Was hilft wirklich?]. Der Hautarzt, 62(8), 607–613.", note: "Dermatology review of anti-aging cream ingredients: sunscreens, retinoids and a few actives have controlled evidence; most marketed creams do not.", link: doi("10.1007/s00105-011-2137-6"), kind: "doi" },
      { cite: "Siddiqui, Z., Zufall, A., Nash, M., et al. (2024). Comparing tretinoin to other topical therapies in the treatment of skin photoaging: A systematic review. American Journal of Clinical Dermatology, 25(6), 873–890.", note: "Systematic review using tretinoin as the benchmark: most other topicals have smaller and shorter trials — the comparison to make before believing a cream's claim.", link: doi("10.1007/s40257-024-00893-w"), kind: "doi" },
    ],
  },
  {
    id: "gs-health-energy-beauty-myth-nad-youth-pills",
    goal: "health-energy-beauty", tier: "fundamental", section: "9322",
    title: "Myth: NMN and NR 'Youth' Pills Make You Look and Feel Younger",
    subtitle: "Human trials raise blood NAD+ and are well tolerated; none shows younger skin, more energy or slower aging in healthy people",
    evidenceTag: "Mixed",
    impact: { magnitude: 1, latency: "months", durability: "transient", effort: "moderate" },
    callout: "Rated at the floor as an appearance-and-energy claim. Randomized human trials of nicotinamide riboside and nicotinamide mononucleotide reliably raise NAD-related metabolites and are safe over weeks to a year, and one small trial improved muscle insulin sensitivity in prediabetic women. What none has shown is improved energy, exercise capacity, skin or any marker of looking younger in healthy adults; a 12-week NR trial in obese men found no metabolic benefit. The longevity shelf (7015) carries the geroscience framing; here the verdict is that the marketing outruns the trials.",
    feeds: ["Money saved", "Realistic expectations"],
    description:
      "NAD precursors are sold on the promise of cellular youth. The human evidence is a set of small, mostly short trials: six weeks of NR in healthy middle-aged adults raised NAD+ and was well tolerated but did not change energy expenditure, exercise capacity or motor function; 12 weeks in obese men produced no insulin-sensitivity or lipid benefit; NMN over 10 weeks raised muscle insulin sensitivity in prediabetic women without changing body composition, and single-dose and 12-month Japanese trials established safety and metabolite increases. That is a pharmacology story, not a beauty or energy story.",
    action: "Spend the supplement budget on the iron test in 9303, the sunscreen in 9307 and the gym membership in 9316; revisit NAD precursors only if a future trial reports an outcome you can see or feel.",
    sources: [
      { cite: "Martens, C. R., Denman, B. A., Mazzo, M. R., et al. (2018). Chronic nicotinamide riboside supplementation is well-tolerated and elevates NAD+ in healthy middle-aged and older adults. Nature Communications, 9, 1286.", note: "Six-week randomized crossover in healthy middle-aged and older adults: 1,000 mg/day NR raised blood NAD+ and was well tolerated, with no change in energy expenditure, exercise capacity or motor function; blood pressure signals were exploratory.", link: doi("10.1038/s41467-018-03421-7"), kind: "doi" },
      { cite: "Dollerup, O. L., Christensen, B., Svart, M., et al. (2018). A randomized placebo-controlled clinical trial of nicotinamide riboside in obese men: Safety, insulin-sensitivity, and lipid-mobilizing effects. American Journal of Clinical Nutrition, 108(2), 343–353.", note: "Twelve weeks of 2,000 mg/day NR in 40 obese, insulin-resistant men: safe, but no improvement in insulin sensitivity, energy expenditure or body composition versus placebo.", link: doi("10.1093/ajcn/nqy132"), kind: "doi" },
      { cite: "Yoshino, M., Yoshino, J., Kayser, B. D., et al. (2021). Nicotinamide mononucleotide increases muscle insulin sensitivity in prediabetic women. Science, 372(6547), 1224–1229.", note: "Ten weeks of 250 mg/day NMN in 25 postmenopausal prediabetic women increased muscle insulin sensitivity without changing body composition or other metabolic markers — a mechanistic signal, not an anti-aging outcome.", link: doi("10.1126/science.abe9985"), kind: "doi" },
      { cite: "Irie, J., Inagaki, E., Fujita, M., et al. (2020). Effect of oral administration of nicotinamide mononucleotide on clinical parameters and nicotinamide metabolite levels in healthy Japanese men. Endocrine Journal, 67(2), 153–160.", note: "First human NMN study: single oral doses up to 500 mg in ten healthy men were safe and raised NMN metabolites, with no clinical effects measured.", link: doi("10.1507/endocrj.EJ19-0313"), kind: "doi" },
      { cite: "Yamaguchi, S., Irie, J., Mitsuishi, M., et al. (2024). Safety and efficacy of long-term nicotinamide mononucleotide supplementation on metabolism, sleep, and nicotinamide adenine dinucleotide biosynthesis in healthy, middle-aged Japanese men. Endocrine Journal, 71(2), 153–169.", note: "Twelve-month NMN supplementation in healthy middle-aged men: safe and NAD-raising, with no clear improvement in metabolism or sleep — the longest human trial and still no youth outcome.", link: doi("10.1507/endocrj.EJ23-0431"), kind: "doi" },
    ],
  },
];
