// Goal shelf: HOBBY & SKILL — pick up a new hobby or skill (sections 8600–8699).
// Verification: every DOI below was resolved against the Crossref record or the
// PubMed record on 2026-09-11 (see the ledger in the research scratchpad). See
// types.ts for the contract. Nothing here is medical advice; each note describes
// what the cited study tested.
import { doi, type GoalShelfCluster } from "./types";

export const SECTIONS: Record<string, string> = {
  "8600": "How to Read This Shelf",
  "8601": "Leisure and Wellbeing — Serious Leisure and the Enjoyable-Activities Evidence",
  "8602": "Flow — Match Challenge to Skill",
  "8603": "How Skills Are Learned — Spacing, Retrieval, Feedback and Desirable Difficulty",
  "8604": "Deliberate Practice — The Honest Verdict",
  "8605": "Learning an Instrument in Adulthood",
  "8606": "Learning a Language in Adulthood",
  "8607": "Arts, Crafts and Mental Health",
  "8608": "Gardening and Time in Nature",
  "8609": "Birdwatching and Everyday Wildlife",
  "8610": "Reading for Pleasure",
  "8611": "Chess and Video Games — Honest About Transfer",
  "8612": "Dance",
  "8613": "Cooking Classes and Diet",
  "8614": "Volunteering as a Hobby",
  "8615": "Social Hobbies and Loneliness",
  "8616": "Hobbies in Later Life — Dementia and Depression Risk",
  "8617": "Productive Engagement — Learning Something Genuinely Hard",
  "8618": "Creative Hobbies, Recovery and Work Performance",
  "8619": "Myth: Brain-Training Apps",
  "8620": "Group Music-Making — Choirs and Ensembles",
};

export const CLUSTERS: GoalShelfCluster[] = [
  {
    id: "gs-hobby-read-me-first",
    goal: "hobby", tier: "fundamental", section: "8600",
    title: "How to Read the Hobby & Skill Shelf",
    subtitle: "Protocols for choosing, starting and sticking with a hobby — pick one per tier each month",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "low" },
    description:
      "Every protocol on this shelf is tagged fundamental, moderate, advanced or elite and carries a concrete action. Two findings organize the shelf: enjoyable leisure is associated with better psychological and physical health across large samples, and the way a new skill is practiced (spaced, tested, with feedback) matters more than raw hours. The floor-rated cluster at the end names the popular 'brain-training' claim the evidence does not support.",
    action: "This month, choose one hobby you can do at least twice a week for 30 days, and run the skill-acquisition principles cluster alongside it before adding anything else.",
    sources: [
      { cite: "Mak, H. W., Noguchi, T., Bone, J. K., Wels, J., Gao, Q., Kondo, K., Saito, T., & Fancourt, D. (2023). Hobby engagement and mental wellbeing among people aged 65 years and older in 16 countries. Nature Medicine, 29(9), 2233–2240.", note: "Harmonized five longitudinal studies (N = 93,263) across 16 countries; having a hobby was associated with fewer depressive symptoms and higher self-rated health, happiness and life satisfaction, with a temporal pattern consistent with hobbies preceding the benefit.", link: doi("10.1038/s41591-023-02506-1"), kind: "doi" },
      { cite: "Pressman, S. D., Matthews, K. A., Cohen, S., Martire, L. M., Scheier, M., Baum, A., & Schulz, R. (2009). Association of enjoyable leisure activities with psychological and physical well-being. Psychosomatic Medicine, 71(7), 725–732.", note: "Across four studies (n = 1,399), more participation in enjoyable leisure activities was associated with lower blood pressure, cortisol, waist circumference and BMI and with better psychosocial states.", link: doi("10.1097/PSY.0b013e3181ad7978"), kind: "doi" },
    ],
  },
  {
    id: "gs-hobby-serious-leisure",
    goal: "hobby", tier: "fundamental", section: "8601",
    title: "Pick a Hobby You Can Get Serious About",
    subtitle: "Leisure engagement relates to wellbeing through leisure satisfaction; 'serious leisure' with skills and a community carries the most",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "low" },
    feeds: ["life satisfaction", "identity outside work"],
    description:
      "Stebbins distinguished serious leisure — amateur, hobbyist and volunteer pursuits with perseverance, skill development and a social world — from casual leisure. The meta-analytic evidence is consistent: leisure engagement is moderately associated with subjective wellbeing, mediated by leisure satisfaction, and experimental leisure interventions raise wellbeing. Frequency and variety of engagement matter more than total leisure time, and the association is stronger for retirees.",
    action: "Write down two hobbies you could plausibly still be doing in five years, choose the one with a local community attached, and schedule its first three sessions before the end of this week.",
    sources: [
      { cite: "Stebbins, R. A. (1982). Serious leisure: A conceptual statement. The Pacific Sociological Review, 25(2), 251–272.", note: "Introduces serious leisure — amateurs, hobbyists and career volunteers — and its six qualities, including perseverance, effort to acquire skill, durable benefits and a unique ethos.", link: doi("10.2307/1388726"), kind: "doi" },
      { cite: "Stebbins, R. A. (2001). Serious leisure. Society, 38(4), 53–57.", note: "Short synthesis of two decades of serious-leisure research, contrasting it with casual leisure and describing the identity and community that hobbyists build.", link: doi("10.1007/s12115-001-1023-8"), kind: "doi" },
      { cite: "Kuykendall, L., Tay, L., & Ng, V. (2015). Leisure engagement and subjective well-being: A meta-analysis. Psychological Bulletin, 141(2), 364–403.", note: "Meta-analysis of 37 effect sizes (11,834 people): leisure engagement and wellbeing correlate at r = .26, mediated by leisure satisfaction; experimental leisure interventions raised wellbeing (d = 1.02); frequency and diversity mattered more than time.", link: doi("10.1037/a0038508"), kind: "doi" },
      { cite: "Pressman, S. D., Matthews, K. A., Cohen, S., Martire, L. M., Scheier, M., Baum, A., & Schulz, R. (2009). Association of enjoyable leisure activities with psychological and physical well-being. Psychosomatic Medicine, 71(7), 725–732.", note: "Higher scores on an enjoyable-activities inventory were associated with lower blood pressure, cortisol and body measures and with more positive psychosocial states, controlling for demographics.", link: doi("10.1097/PSY.0b013e3181ad7978"), kind: "doi" },
      { cite: "Mak, H. W., Noguchi, T., Bone, J. K., Wels, J., Gao, Q., Kondo, K., Saito, T., & Fancourt, D. (2023). Hobby engagement and mental wellbeing among people aged 65 years and older in 16 countries. Nature Medicine, 29(9), 2233–2240.", note: "Fixed-effects models across 16 countries found hobby engagement associated with lower depressive symptoms and higher happiness and life satisfaction, with little of the variation explained by country-level factors.", link: doi("10.1038/s41591-023-02506-1"), kind: "doi" },
    ],
  },
  {
    id: "gs-hobby-flow",
    goal: "hobby", tier: "fundamental", section: "8602",
    title: "Set the Difficulty So You Can Reach Flow",
    subtitle: "Flow — high challenge met by high skill — predicts the quality of experience more than whether you are at work or at leisure",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "days", durability: "sustained", effort: "low" },
    feeds: ["absorption", "intrinsic motivation"],
    description:
      "Csikszentmihalyi and LeFevre's experience-sampling study of 78 workers found that being in flow — challenges matched by skills — affected almost every measure of experience quality more than whether the person was working or at leisure, and that most flow was reported at work, not in passive leisure. Later work links flow experience to wellbeing and to an 'autotelic' disposition, and experience sampling at work shows flow rises with skill variety and autonomy. Everyday creative activity likewise predicts next-day positive affect and flourishing.",
    action: "For your hobby, keep a simple scale: after each session rate challenge and skill from 1 to 5; if challenge is two points below skill, add a harder goal next time, and if two points above, break the task down.",
    sources: [
      { cite: "Csikszentmihalyi, M., & LeFevre, J. (1989). Optimal experience in work and leisure. Journal of Personality and Social Psychology, 56(5), 815–822.", note: "Experience sampling of 78 adult workers for a week; quality of experience was more affected by being in flow than by whether the person was at work or at leisure, and most flow occurred at work.", link: doi("10.1037//0022-3514.56.5.815"), kind: "doi" },
      { cite: "Tse, D. C. K., Nakamura, J., & Csikszentmihalyi, M. (2021). Living well by \"flowing\" well: The indirect effect of autotelic personality on well-being through flow experience. The Journal of Positive Psychology, 16(3), 310–321.", note: "Tests the pathway from an autotelic disposition to wellbeing through the frequency of flow experiences, supporting flow as a mechanism rather than a by-product.", link: doi("10.1080/17439760.2020.1716055"), kind: "doi" },
      { cite: "Fullagar, C. J., & Kelloway, E. K. (2009). Flow at work: An experience sampling approach. Journal of Occupational and Organizational Psychology, 82(3), 595–615.", note: "Experience-sampling study showing flow varies mostly within persons over time and is predicted by task and situational features such as autonomy and skill variety.", link: doi("10.1348/096317908X357903"), kind: "doi" },
      { cite: "Conner, T. S., DeYoung, C. G., & Silvia, P. J. (2018). Everyday creative activity as a path to flourishing. The Journal of Positive Psychology, 13(2), 181–189.", note: "Daily-diary study of young adults; engaging in small creative activities on one day predicted higher positive affect and flourishing the next day.", link: doi("10.1080/17439760.2016.1257049"), kind: "doi" },
    ],
  },
  {
    id: "gs-hobby-skill-acquisition-principles",
    goal: "hobby", tier: "fundamental", section: "8603",
    title: "Practice in Short Spaced Sessions, Test Yourself, Get Feedback",
    subtitle: "Spacing, retrieval and informative feedback beat massed cramming for long-term skill — even though cramming feels better",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "weeks", durability: "lasting", effort: "low" },
    feeds: ["retention", "transfer to real use"],
    description:
      "The learning sciences converge on a few principles that apply to chords, vocabulary and forehands alike. Spacing practice across sessions beats massing it, with the optimal gap growing as the goal horizon lengthens; retrieving from memory beats re-reading or re-watching; and feedback helps on average but can hurt when it focuses on the self rather than the task. Schmidt and Bjork showed that conditions which slow improvement during practice — variability, spacing, delayed feedback — often produce better long-term retention and transfer. A study of 854,064 online game players confirmed both the practice-amount and spacing effects in the wild.",
    action: "Split your weekly practice into at least four short sessions instead of one long one, start each session by attempting yesterday's material from memory before reviewing it, and ask one more skilled person for specific task-level feedback every two weeks.",
    sources: [
      { cite: "Cepeda, N. J., Pashler, H., Vul, E., Wixted, J. T., & Rohrer, D. (2006). Distributed practice in verbal recall tasks: A review and quantitative synthesis. Psychological Bulletin, 132(3), 354–380.", note: "Synthesis of 839 assessments in 317 experiments; spaced study beats massed study, and the best spacing interval grows with the retention interval.", link: doi("10.1037/0033-2909.132.3.354"), kind: "doi" },
      { cite: "Cepeda, N. J., Vul, E., Rohrer, D., Wixted, J. T., & Pashler, H. (2008). Spacing effects in learning: A temporal ridgeline of optimal retention. Psychological Science, 19(11), 1095–1102.", note: "More than 1,350 people learned facts with gaps up to 3.5 months and tests up to a year later; the optimal gap was roughly 10–20% of the test delay for short horizons and 5–10% for a one-year horizon.", link: doi("10.1111/j.1467-9280.2008.02209.x"), kind: "doi" },
      { cite: "Kornell, N., & Bjork, R. A. (2008). Learning concepts and categories: Is spacing the \"enemy of induction\"? Psychological Science, 19(6), 585–592.", note: "Interleaving different artists' paintings improved learning to recognize styles even though participants believed massed study worked better — a demonstration of the fluency illusion.", link: doi("10.1111/j.1467-9280.2008.02127.x"), kind: "doi" },
      { cite: "Roediger, H. L., & Karpicke, J. D. (2006). Test-enhanced learning: Taking memory tests improves long-term retention. Psychological Science, 17(3), 249–255.", note: "Repeated testing produced substantially better delayed retention than repeated studying, even though repeated studying raised students' confidence more.", link: doi("10.1111/j.1467-9280.2006.01693.x"), kind: "doi" },
      { cite: "Schmidt, R. A., & Bjork, R. A. (1992). New conceptualizations of practice: Common principles in three paradigms suggest new concepts for training. Psychological Science, 3(4), 207–218.", note: "Argues from parallel motor and verbal learning findings that manipulations which slow gains during practice — variability, spacing, reduced feedback — often improve long-term retention and transfer.", link: doi("10.1111/j.1467-9280.1992.tb00029.x"), kind: "doi" },
      { cite: "Kluger, A. N., & DeNisi, A. (1996). The effects of feedback interventions on performance: A historical review, a meta-analysis, and a preliminary feedback intervention theory. Psychological Bulletin, 119(2), 254–284.", note: "Meta-analysis of feedback interventions; feedback improves performance on average but a substantial minority of interventions reduce it, especially when feedback draws attention to the self rather than the task.", link: doi("10.1037/0033-2909.119.2.254"), kind: "doi" },
      { cite: "Hattie, J., & Timperley, H. (2007). The power of feedback. Review of Educational Research, 77(1), 81–112.", note: "Reviews the evidence that feedback is among the strongest influences on learning and proposes a model in which task-, process- and self-regulation-level feedback are effective while feedback about the person is not.", link: doi("10.3102/003465430298487"), kind: "doi" },
      { cite: "Stafford, T., & Dewar, M. (2014). Tracing the trajectory of skill learning with a very large sample of online game players. Psychological Science, 25(2), 511–518.", note: "Data from 854,064 players of an online game; both amount of practice and spacing of practice predicted later performance, and greater early variability predicted higher eventual skill.", link: doi("10.1177/0956797613511466"), kind: "doi" },
    ],
  },
  {
    id: "gs-hobby-deliberate-practice",
    goal: "hobby", tier: "moderate", section: "8604",
    title: "Use Deliberate Practice — Without Believing the 10,000-Hour Story",
    subtitle: "Structured, goal-directed practice matters for music and games; it explains far less than the popular rule claims",
    evidenceTag: "Mixed",
    impact: { magnitude: 3, latency: "months", durability: "lasting", effort: "moderate" },
    feeds: ["focused practice habits", "realistic expectations"],
    description:
      "Ericsson's deliberate-practice framework — practice designed to improve specific weaknesses, with full attention and feedback — remains a useful way to structure a hobby. But the meta-analysis of the whole literature found deliberate practice explained 26 percent of performance variance in games, 21 percent in music and 18 percent in sports, and a preregistered replication of the original violinist study did not reproduce its core finding. Grit, the trait often invoked alongside the 10,000-hour idea, has modest predictive validity and overlaps heavily with conscientiousness. Practice deliberately; expect it to help, not to guarantee mastery.",
    action: "Each week, name one specific weakness in your hobby (a chord change, a verb tense, a stroke), design a ten-minute drill for it with immediate feedback, and repeat that drill in three sessions before choosing the next weakness.",
    sources: [
      { cite: "Ericsson, K. A., Krampe, R. T., & Tesch-Römer, C. (1993). The role of deliberate practice in the acquisition of expert performance. Psychological Review, 100(3), 363–406.", note: "The foundational paper proposing that accumulated deliberate practice — effortful, feedback-rich work on specific weaknesses — largely explains expert performance in music.", link: doi("10.1037/0033-295X.100.3.363"), kind: "doi" },
      { cite: "Macnamara, B. N., Hambrick, D. Z., & Oswald, F. L. (2014). Deliberate practice and performance in music, games, sports, education, and professions: A meta-analysis. Psychological Science, 25(8), 1608–1618.", note: "Meta-analysis across domains: deliberate practice explained 26% of performance variance for games, 21% for music, 18% for sports, 4% for education and less than 1% for professions.", link: doi("10.1177/0956797614535810"), kind: "doi" },
      { cite: "Macnamara, B. N., & Maitra, M. (2019). The role of deliberate practice in expert performance: Revisiting Ericsson, Krampe & Tesch-Römer (1993). Royal Society Open Science, 6(8), 190327.", note: "Double-blind replication of the violinist study; accumulated deliberate practice did not correspond to each skill level as originally reported, and the effect was substantially smaller.", link: doi("10.1098/rsos.190327"), kind: "doi" },
      { cite: "Duckworth, A. L., Peterson, C., Matthews, M. D., & Kelly, D. R. (2007). Grit: Perseverance and passion for long-term goals. Journal of Personality and Social Psychology, 92(6), 1087–1101.", note: "Introduces the grit construct and scale, relating perseverance and passion for long-term goals to achievement beyond IQ.", link: doi("10.1037/0022-3514.92.6.1087"), kind: "doi" },
      { cite: "Credé, M., Tynan, M. C., & Harms, P. D. (2017). Much ado about grit: A meta-analytic synthesis of the grit literature. Journal of Personality and Social Psychology, 113(3), 492–511.", note: "Meta-analysis showing grit's relations with performance are modest, that it is strongly correlated with conscientiousness, and that the perseverance facet accounts for most of its validity.", link: doi("10.1037/pspp0000102"), kind: "doi" },
    ],
  },
  {
    id: "gs-hobby-music-instrument",
    goal: "hobby", tier: "advanced", section: "8605",
    title: "Take Up an Instrument With Weekly Lessons",
    subtitle: "Piano training in older adults improved executive function, mood and quality of life in randomized and controlled studies",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "months", durability: "sustained", effort: "high" },
    feeds: ["executive function", "mood", "fine-motor skill"],
    description:
      "Small controlled trials of adults with no musical background show that months of instrument lessons plus daily practice improve some cognitive measures. Bugos and colleagues randomized 31 adults aged 60–85 to six months of individualized piano instruction and found gains on executive-function tests relative to controls; Seinfeld's group found four months of piano lessons improved a Stroop measure, reduced depression and improved quality of life compared with other leisure activities. A systematic review and meta-analysis of 13 studies found cognitive and cerebral benefits of musical practice in healthy aging, while cautioning that most evidence is correlational.",
    action: "Book weekly lessons with a teacher for at least four months and commit to 20 minutes of practice on five days a week; keep a log of what you can now play that you could not play a month ago.",
    sources: [
      { cite: "Bugos, J. A., Perlstein, W. M., McCrae, C. S., Brophy, T. S., & Bedenbaugh, P. H. (2007). Individualized piano instruction enhances executive functioning and working memory in older adults. Aging & Mental Health, 11(4), 464–471.", note: "Randomized 31 musically naive adults aged 60–85 to six months of piano instruction or control; the piano group improved on Trail Making and Digit Symbol measures, with follow-up three months later.", link: doi("10.1080/13607860601086504"), kind: "doi" },
      { cite: "Seinfeld, S., Figueroa, H., Ortiz-Gil, J., & Sanchez-Vives, M. V. (2013). Effects of music learning and piano practice on cognitive function, mood and quality of life in older adults. Frontiers in Psychology, 4, 810.", note: "Four months of piano lessons with daily practice (n = 13) versus other leisure activities (n = 16); the piano group improved on the Stroop test, showed less depression and better quality of life.", link: doi("10.3389/fpsyg.2013.00810"), kind: "doi" },
      { cite: "Román-Caballero, R., Arnedo, M., Triviño, M., & Lupiáñez, J. (2018). Musical practice as an enhancer of cognitive function in healthy aging: A systematic review and meta-analysis. PLoS ONE, 13(11), e0207957.", note: "Review of 13 studies (9 correlational, 4 short-term training experiments) in adults aged 59+; musical practice was associated with cognitive and cerebral benefits in both domain-specific and general functions.", link: doi("10.1371/journal.pone.0207957"), kind: "doi" },
    ],
  },
  {
    id: "gs-hobby-language-learning",
    goal: "hobby", tier: "advanced", section: "8606",
    title: "Learn a Language — Adults Can, and It Trains Attention",
    subtitle: "Grammar-learning ability stays high into the late teens then declines gradually; even a week of intensive language study shifted attention switching at any age",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "months", durability: "sustained", effort: "high" },
    feeds: ["attention switching", "cognitive reserve"],
    description:
      "The largest study of second-language acquisition (669,498 English speakers) found grammar-learning ability is preserved almost to adulthood and then declines steadily rather than collapsing, so adult learners can expect real but slower progress. Bak and colleagues found that participants aged 18–78 in a one-week intensive Gaelic course improved attention switching, and those who kept practicing five or more hours a week held the gain nine months later; their cohort study found bilingualism — including languages learned in adulthood — predicted better later-life cognition after controlling for childhood intelligence. Bilingual dementia patients showed symptoms about four years later than monolinguals in a clinic sample. A pilot found a technology-based language program feasible and enjoyable for seniors.",
    action: "Pick one language and one course or tutor, put in a minimum of five hours a week for the first three months, and schedule a spoken conversation with a native speaker at least once a week from week four.",
    sources: [
      { cite: "Hartshorne, J. K., Tenenbaum, J. B., & Pinker, S. (2018). A critical period for second language acquisition: Evidence from 2/3 million English speakers. Cognition, 177, 263–277.", note: "Data from 669,498 native and non-native English speakers; grammar-learning ability is preserved to about 17.4 years and then declines steadily, with the critical period ending much later than previously thought.", link: doi("10.1016/j.cognition.2018.04.007"), kind: "doi" },
      { cite: "Bak, T. H., Long, M. R., Vega-Mendoza, M., & Sorace, A. (2016). Novelty, challenge, and practice: The impact of intensive language learning on attentional functions. PLoS ONE, 11(4), e0153485.", note: "33 participants aged 18–78 in a one-week intensive Scottish Gaelic course improved attention switching versus 34 controls; gains persisted at nine months for those practicing five or more hours a week.", link: doi("10.1371/journal.pone.0153485"), kind: "doi" },
      { cite: "Bak, T. H., Nissan, J. J., Allerhand, M. M., & Deary, I. J. (2014). Does bilingualism influence cognitive aging? Annals of Neurology, 75(6), 959–963.", note: "853 people tested at age 11 in 1947 and again in 2008–2010; bilinguals performed better than predicted from childhood ability, including those who learned the second language in adulthood.", link: doi("10.1002/ana.24158"), kind: "doi" },
      { cite: "Bialystok, E., Craik, F. I. M., & Freedman, M. (2007). Bilingualism as a protection against the onset of symptoms of dementia. Neuropsychologia, 45(2), 459–464.", note: "Among 184 memory-clinic patients with dementia, bilinguals showed symptoms four years later than monolinguals, with similar rates of decline after diagnosis.", link: doi("10.1016/j.neuropsychologia.2006.10.009"), kind: "doi" },
      { cite: "Ware, C., Damnee, S., Djabelkhir, L., Cristancho, V., Wu, Y.-H., Benovici, J., Pino, M., & Rigaud, A.-S. (2017). Maintaining cognitive functioning in healthy seniors with a technology-based foreign language program: A pilot feasibility study. Frontiers in Aging Neuroscience, 9, 42.", note: "Four-month pilot English program for 14 older French adults; feasible and rated stimulating and enjoyable, though cognitive and loneliness scores did not change significantly in this small sample.", link: doi("10.3389/fnagi.2017.00042"), kind: "doi" },
    ],
  },
  {
    id: "gs-hobby-arts-crafts",
    goal: "hobby", tier: "fundamental", section: "8607",
    title: "Make or See Art Every Few Months at Least",
    subtitle: "Arts engagement is associated with lower mortality, depression and dementia incidence in long cohorts; making art lowers cortisol in the moment",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "weeks", durability: "lasting", effort: "low" },
    feeds: ["mood", "social connection", "cognitive reserve"],
    description:
      "In the English Longitudinal Study of Ageing, people who engaged with receptive arts (museums, galleries, theatre, concerts) every few months or more had lower mortality over 14 years, lower incidence of depression over 10 years and lower dementia incidence, independent of demographic, health and social factors; these are observational associations. A quasi-experiment found 45 minutes of art-making lowered salivary cortisol regardless of prior experience. Knitters in an international survey reported calm, happiness and social benefits, and a public-health review catalogues the mechanisms.",
    action: "Put two arts outings (a gallery, a concert, a play) on the calendar for the next three months and one hands-on craft session a week; note your mood before and after each for the first month.",
    sources: [
      { cite: "Fancourt, D., & Steptoe, A. (2019). The art of life and death: 14 year follow-up analyses of associations between arts engagement and mortality in the English Longitudinal Study of Ageing. BMJ, 367, l6377.", note: "Prospective cohort of 6,710 adults aged 50+; infrequent receptive-arts engagement was associated with 14% lower mortality and frequent engagement with 31% lower mortality over 14 years, adjusted for many confounders.", link: doi("10.1136/bmj.l6377"), kind: "doi" },
      { cite: "Fancourt, D., & Tymoszuk, U. (2019). Cultural engagement and incident depression in older adults: Evidence from the English Longitudinal Study of Ageing. The British Journal of Psychiatry, 214(4), 225–229.", note: "2,148 adults free of depression at baseline; attending cultural activities every few months was associated with 32% lower odds of developing depression over ten years, and monthly attendance with 48% lower odds.", link: doi("10.1192/bjp.2018.267"), kind: "doi" },
      { cite: "Fancourt, D., Steptoe, A., & Cadar, D. (2018). Cultural engagement and cognitive reserve: Museum attendance and dementia incidence over a 10-year period. The British Journal of Psychiatry, 213(5), 661–663.", note: "Visiting museums every few months or more was associated with lower dementia incidence over 10 years in adults aged 50+, independent of socioeconomic and health variables.", link: doi("10.1192/bjp.2018.129"), kind: "doi" },
      { cite: "Fancourt, D., Steptoe, A., & Cadar, D. (2020). Community engagement and dementia risk: Time-to-event analyses from a national cohort study. Journal of Epidemiology and Community Health, 74(1), 71–77.", note: "9,550 adults aged 50+ followed 12 years; community cultural engagement was associated with a lower hazard of dementia (fully adjusted HR 0.58) independent of broader social factors.", link: doi("10.1136/jech-2019-213029"), kind: "doi" },
      { cite: "Kaimal, G., Ray, K., & Muniz, J. (2016). Reduction of cortisol levels and participants' responses following art making. Art Therapy, 33(2), 74–80.", note: "Quasi-experiment with 39 healthy adults; 45 minutes of free art-making significantly lowered salivary cortisol, with no difference by prior art experience or media chosen.", link: doi("10.1080/07421656.2016.1166832"), kind: "doi" },
      { cite: "Stuckey, H. L., & Nobel, J. (2010). The connection between art, healing, and public health: A review of current literature. American Journal of Public Health, 100(2), 254–263.", note: "Reviews evidence on music, visual arts, movement and expressive writing; art-based activities reduce adverse physiological and psychological outcomes, with effects on overall health status less established.", link: doi("10.2105/AJPH.2008.156497"), kind: "doi" },
      { cite: "Riley, J., Corkhill, B., & Morris, C. (2013). The benefits of knitting for personal and social wellbeing in adulthood: Findings from an international survey. British Journal of Occupational Therapy, 76(2), 50–57.", note: "International survey of knitters; frequent knitting was associated with reported calm and happiness, and knitting in groups with social contact and wellbeing.", link: doi("10.4276/030802213X13603244419077"), kind: "doi" },
    ],
  },
  {
    id: "gs-hobby-gardening-nature",
    goal: "hobby", tier: "fundamental", section: "8608",
    title: "Garden, or Get Two Hours a Week Outdoors",
    subtitle: "Gardening shows positive effects on health in a meta-analysis; 120 minutes a week in nature is the threshold associated with good health and wellbeing",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "low" },
    feeds: ["stress recovery", "physical activity", "mood"],
    description:
      "A meta-analysis of 22 gardening studies (76 comparisons) found positive effects on outcomes including depression, anxiety, BMI, life satisfaction and sense of community, robust to publication-bias adjustment. A field experiment with allotment gardeners found 30 minutes of gardening after a stressor lowered cortisol more than reading and fully restored positive mood. Survey data from 19,806 people found the likelihood of good health and high wellbeing rose with at least 120 minutes of weekly nature contact and plateaued around 200–300 minutes, however the minutes were split. A 90-minute nature walk reduced rumination and the associated prefrontal activity where an urban walk did not.",
    action: "Commit to 120 minutes a week outdoors in green space, split however suits you, and if you have any patch of soil or a balcony, plant something you will need to tend at least twice a week.",
    sources: [
      { cite: "Soga, M., Gaston, K. J., & Yamaura, Y. (2017). Gardening is beneficial for health: A meta-analysis. Preventive Medicine Reports, 5, 92–99.", note: "Meta-analysis of 22 studies with 76 comparisons; gardening had a significant positive effect on health outcomes such as depression, anxiety, BMI and life satisfaction, robust to trim-and-fill correction.", link: doi("10.1016/j.pmedr.2016.11.007"), kind: "doi" },
      { cite: "Van Den Berg, A. E., & Custers, M. H. G. (2011). Gardening promotes neuroendocrine and affective restoration from stress. Journal of Health Psychology, 16(1), 3–11.", note: "Thirty allotment gardeners did a stressful task then were randomized to 30 minutes of gardening or indoor reading; cortisol fell more and positive mood was fully restored after gardening.", link: doi("10.1177/1359105310365577"), kind: "doi" },
      { cite: "Thompson, R. (2018). Gardening for health: A regular dose of gardening. Clinical Medicine, 18(3), 201–205.", note: "Clinical review summarizing evidence that exposure to plants, green space and gardening benefits mental and physical health and recommending gardening as a health behaviour.", link: doi("10.7861/clinmedicine.18-3-201"), kind: "doi" },
      { cite: "White, M. P., Alcock, I., Grellier, J., Wheeler, B. W., Hartig, T., Warber, S. L., Bone, A., Depledge, M. H., & Fleming, L. E. (2019). Spending at least 120 minutes a week in nature is associated with good health and wellbeing. Scientific Reports, 9, 7730.", note: "Nationally representative English sample (n = 19,806); compared with no contact, 120–179 minutes of weekly nature contact was associated with higher odds of good health and wellbeing, peaking at 200–300 minutes regardless of how the time was split.", link: doi("10.1038/s41598-019-44097-3"), kind: "doi" },
      { cite: "Bratman, G. N., Hamilton, J. P., Hahn, K. S., Daily, G. C., & Gross, J. J. (2015). Nature experience reduces rumination and subgenual prefrontal cortex activation. Proceedings of the National Academy of Sciences, 112(28), 8567–8572.", note: "A 90-minute walk in a natural setting decreased self-reported rumination and subgenual prefrontal activity, while a 90-minute urban walk had no such effect.", link: doi("10.1073/pnas.1510459112"), kind: "doi" },
    ],
  },
  {
    id: "gs-hobby-birdwatching",
    goal: "hobby", tier: "fundamental", section: "8609",
    title: "Start Noticing Birds",
    subtitle: "Everyday encounters with birds are followed by lasting improvements in momentary wellbeing, including in people with depression",
    evidenceTag: "Emerging",
    impact: { magnitude: 2, latency: "days", durability: "sustained", effort: "low" },
    feeds: ["attention to surroundings", "connection to nature"],
    description:
      "A smartphone ecological-momentary-assessment study with 1,292 participants and 26,856 assessments found that seeing or hearing birds was associated with time-lasting improvements in mental wellbeing, in healthy people and in those with a depression diagnosis. Cross-sectional work links afternoon bird abundance in the neighbourhood to lower depression, anxiety and stress, and a European survey associated bird species richness with life satisfaction. People who feed garden birds report feeling more relaxed and connected to nature. Birdwatching is cheap, near-daily and pairs naturally with the nature-time protocol.",
    action: "Put a feeder or a water dish where you can see it, learn to identify the ten commonest birds where you live using a free field guide or app, and log the species you notice on a short daily walk for one month.",
    sources: [
      { cite: "Hammoud, R., Tognin, S., Burgess, L., Bergou, N., Smythe, M., Gibbons, J., Davidson, N., Afifi, A., Bakolis, I., & Mechelli, A. (2022). Smartphone-based ecological momentary assessment reveals mental health benefits of birdlife. Scientific Reports, 12, 17589.", note: "1,292 participants completed 26,856 momentary assessments; everyday encounters with birdlife were associated with time-lasting improvements in wellbeing, in healthy people and in those with diagnosed depression.", link: doi("10.1038/s41598-022-20207-6"), kind: "doi" },
      { cite: "Cox, D. T. C., & Gaston, K. J. (2016). Urban bird feeding: Connecting people with nature. PLoS ONE, 11(7), e0158717.", note: "Household survey in southern English towns; people who fed birds regularly felt more relaxed and connected to nature when watching garden birds, and these feelings were the strongest drivers of feeding.", link: doi("10.1371/journal.pone.0158717"), kind: "doi" },
      { cite: "Cox, D. T. C., Shanahan, D. F., Hudson, H. L., Plummer, K. E., Siriwardena, G. M., Fuller, R. A., Anderson, K., Hancock, S., & Gaston, K. J. (2017). Doses of neighborhood nature: The benefits for mental health of living with nature. BioScience, biw173.", note: "Combined bird surveys with resident mental-health data; afternoon bird abundance and neighbourhood vegetation were associated with lower depression, anxiety and stress.", link: doi("10.1093/biosci/biw173"), kind: "doi" },
      { cite: "Methorst, J., Rehdanz, K., Mueller, T., Hansjürgens, B., Bonn, A., & Böhning-Gaese, K. (2021). The importance of species diversity for human well-being in Europe. Ecological Economics, 181, 106917.", note: "Links European life-satisfaction survey data with bird-species richness; higher local bird diversity was associated with higher life satisfaction across the continent.", link: doi("10.1016/j.ecolecon.2020.106917"), kind: "doi" },
    ],
  },
  {
    id: "gs-hobby-reading",
    goal: "hobby", tier: "fundamental", section: "8610",
    title: "Read Books, Not Just Feeds",
    subtitle: "Book readers lived longer in a national cohort and read less-frequent readers declined faster cognitively; the 'fiction makes you empathic' effect is smaller and less reliable than headlines claimed",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "weeks", durability: "lasting", effort: "low" },
    feeds: ["cognition", "calm", "vocabulary"],
    description:
      "In the U.S. Health and Retirement Study, book readers had a survival advantage over 12 years compared with non-readers, larger than for newspaper or magazine readers and partly mediated by cognition. A 14-year Taiwanese cohort found people who read at least weekly had roughly half the odds of later cognitive decline at every education level. The claim that a single passage of literary fiction improves theory of mind was supported in the original Science experiments but not in a 792-person replication; the original authors' own preregistered replications gave mixed results, though lifetime exposure to fiction consistently correlated with mind-reading ability.",
    action: "Keep a physical or e-reader book in progress at all times and read for 20 minutes on at least five days a week, ideally in the same slot; count books finished per quarter rather than pages per day.",
    sources: [
      { cite: "Bavishi, A., Slade, M. D., & Levy, B. R. (2016). A chapter a day: Association of book reading with longevity. Social Science & Medicine, 164, 44–48.", note: "3,635 Health and Retirement Study participants followed 12 years; book readers had a 20% lower mortality risk than non-book readers after adjustment, a larger advantage than for newspaper or magazine reading, partly mediated by cognition.", link: doi("10.1016/j.socscimed.2016.07.014"), kind: "doi" },
      { cite: "Chang, Y.-H., Wu, I.-C., & Hsiung, C. A. (2021). Reading activity prevents long-term decline in cognitive function in older people: Evidence from a 14-year longitudinal study. International Psychogeriatrics, 33(1), 63–74.", note: "1,962 Taiwanese adults aged 64+ followed 14 years; reading at least weekly was associated with roughly half the odds of cognitive decline at 6, 10 and 14 years across all education levels.", link: doi("10.1017/S1041610220000812"), kind: "doi" },
      { cite: "Kidd, D. C., & Castano, E. (2013). Reading literary fiction improves theory of mind. Science, 342(6156), 377–380.", note: "Five experiments in which reading literary fiction, compared with popular fiction or nonfiction, temporarily improved performance on theory-of-mind tests.", link: doi("10.1126/science.1239918"), kind: "doi" },
      { cite: "Panero, M. E., Weisberg, D. S., Black, J., Goldstein, T. R., Barnes, J. L., Brownell, H., & Winner, E. (2016). Does reading a single passage of literary fiction really improve theory of mind? An attempt at replication. Journal of Personality and Social Psychology, 111(5), e46–e54.", note: "Three independent labs randomized 792 participants; no advantage for literary fiction on the Reading the Mind in the Eyes Test, though lifetime fiction exposure predicted scores across conditions.", link: doi("10.1037/pspa0000064"), kind: "doi" },
      { cite: "Kidd, D., & Castano, E. (2019). Reading literary fiction and theory of mind: Three preregistered replications and extensions of Kidd and Castano (2013). Social Psychological and Personality Science, 10(4), 522–531.", note: "Three preregistered experiments gave mixed results — two uninformative failures and one successful replication — clarifying that the single-passage effect is small and unreliable.", link: doi("10.1177/1948550618775410"), kind: "doi" },
      { cite: "Mar, R. A., Oatley, K., & Peterson, J. B. (2009). Exploring the link between reading fiction and empathy: Ruling out individual differences and examining outcomes. Communications, 34(4), 407–428.", note: "Lifetime exposure to fiction predicted empathy and social ability after controlling for personality and the tendency to be absorbed in stories.", link: doi("10.1515/comm.2009.025"), kind: "doi" },
    ],
  },
  {
    id: "gs-hobby-chess-video-games",
    goal: "hobby", tier: "moderate", section: "8611",
    title: "Play Chess or Games for the Game, Not for Your IQ",
    subtitle: "Chess instruction and video-game training show small effects that shrink with better study designs; action games show modest attention benefits",
    evidenceTag: "Mixed",
    impact: { magnitude: 2, latency: "months", durability: "sustained", effort: "moderate" },
    feeds: ["enjoyment", "social play", "game-specific skill"],
    description:
      "Chess and video games are fine hobbies, but the cognitive-transfer claims are weak. Sala and Gobet's meta-analysis of chess instruction found small-to-moderate effects on academic and cognitive skills that were inversely related to study quality; their comprehensive meta-analysis of video-game training (hundreds of effect sizes) found small or null effects on cognitive ability and no evidence of a causal benefit. Bediou and colleagues' meta-analysis restricted to action video games found a moderate cross-sectional advantage for habitual players and a smaller intervention effect on attention and spatial cognition, with publication bias likely inflating both.",
    action: "If chess or games are your hobby, keep them for enjoyment and social play; if your goal is sharper thinking, spend the same hours on the productive-engagement or language protocols on this shelf.",
    sources: [
      { cite: "Sala, G., & Gobet, F. (2016). Do the benefits of chess instruction transfer to academic and cognitive skills? A meta-analysis. Educational Research Review, 18, 46–57.", note: "Meta-analysis of chess-instruction studies in schools; overall effects on academic and cognitive outcomes were modest and larger in weaker designs without active controls.", link: doi("10.1016/j.edurev.2016.02.002"), kind: "doi" },
      { cite: "Sala, G., Tatlidil, K. S., & Gobet, F. (2018). Video game training does not enhance cognitive ability: A comprehensive meta-analytic investigation. Psychological Bulletin, 144(2), 111–139.", note: "Three meta-analyses (k = 310, 315 and 359) found only weak correlations between gaming skill and cognitive ability and no evidence that video-game training causally improves cognition.", link: doi("10.1037/bul0000139"), kind: "doi" },
      { cite: "Bediou, B., Adams, D. M., Mayer, R. E., Tipton, E., Green, C. S., & Bavelier, D. (2018). Meta-analysis of action video game impact on perceptual, attentional, and cognitive skills. Psychological Bulletin, 144(1), 77–110.", note: "Action video game players showed a cross-sectional advantage of about half a standard deviation (g = 0.55) and intervention studies a smaller effect (g = 0.34), mainly on attention and spatial cognition, with publication bias estimated to inflate effects by about 30%.", link: doi("10.1037/bul0000130"), kind: "doi" },
    ],
  },
  {
    id: "gs-hobby-dance",
    goal: "hobby", tier: "advanced", section: "8612",
    title: "Join a Dance Class",
    subtitle: "Dance combines aerobic, sensorimotor, cognitive and social demands; trials in older adults show gains in balance, cognition and mood",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "months", durability: "sustained", effort: "moderate" },
    feeds: ["balance", "global cognition", "social contact"],
    description:
      "In the Einstein Aging Study cohort, dancing was among the leisure activities associated with lower dementia risk. Controlled trials in older adults found six months of weekly dance improved posture, reaction time and cognition without changing cardiorespiratory fitness, and an 18-month dance program increased hippocampal volume and balance more than conventional fitness training. A meta-analysis of 11 randomized trials (N = 1,412) found dance probably improves global cognitive and executive function, and a broader meta-analysis of dance and dance-movement therapy found medium effects on quality of life, depression and anxiety.",
    action: "Enrol in a weekly partnered or group dance class for at least six months and add a second practice session at home; track balance by timing how long you can stand on one leg each month.",
    sources: [
      { cite: "Verghese, J., Lipton, R. B., Katz, M. J., Hall, C. B., Derby, C. A., Kuslansky, G., Ambrose, A. F., Sliwinski, M., & Buschke, H. (2003). Leisure activities and the risk of dementia in the elderly. The New England Journal of Medicine, 348(25), 2508–2516.", note: "Prospective cohort of 469 adults over 75; reading, board games, playing instruments and dancing were associated with reduced dementia risk, with a one-point rise in the cognitive-activity score linked to a 7% lower hazard.", link: doi("10.1056/NEJMoa022252"), kind: "doi" },
      { cite: "Kattenstroth, J.-C., Kalisch, T., Holt, S., Tegenthoff, M., & Dinse, H. R. (2013). Six months of dance intervention enhances postural, sensorimotor, and cognitive performance in elderly without affecting cardio-respiratory functions. Frontiers in Aging Neuroscience, 5, 5.", note: "Six months of a one-hour weekly dance class improved posture, reaction times, cognition, tactile and motor performance and wellbeing versus controls, with the lowest baseline performers benefiting most.", link: doi("10.3389/fnagi.2013.00005"), kind: "doi" },
      { cite: "Rehfeld, K., Müller, P., Aye, N., Schmicker, M., Dordevic, M., Kaufmann, J., Hökelmann, A., & Müller, N. G. (2017). Dancing or fitness sport? The effects of two training programs on hippocampal plasticity and balance abilities in healthy seniors. Frontiers in Human Neuroscience, 11, 305.", note: "Eighteen months of dance versus fitness training in seniors; both groups showed hippocampal volume increases, but only dancers improved the balance composite score and showed additional subfield gains.", link: doi("10.3389/fnhum.2017.00305"), kind: "doi" },
      { cite: "Hewston, P., Kennedy, C. C., Borhan, S., Merom, D., Santaguida, P., Ioannidis, G., Marr, S., Santesso, N., Thabane, L., Bray, S., & Papaioannou, A. (2021). Effects of dance on cognitive function in older adults: A systematic review and meta-analysis. Age and Ageing, 50(4), 1084–1092.", note: "Eleven randomized trials (N = 1,412); dance produced a mean 1.58-point gain on the Mini-Mental State Examination (moderate certainty) and probably improves executive function, with little effect on complex attention.", link: doi("10.1093/ageing/afaa270"), kind: "doi" },
      { cite: "Koch, S. C., Riege, R. F. F., Tisborn, K., Biondo, J., Martin, L., & Beelmann, A. (2019). Effects of dance movement therapy and dance on health-related psychological outcomes: A meta-analysis update. Frontiers in Psychology, 10, 1806.", note: "41 controlled studies (N = 2,374); a medium overall effect (d = 0.60) on quality of life, depression, anxiety, interpersonal and cognitive skills, with dance interventions strongest for psychomotor skills.", link: doi("10.3389/fpsyg.2019.01806"), kind: "doi" },
    ],
  },
  {
    id: "gs-hobby-cooking",
    goal: "hobby", tier: "moderate", section: "8613",
    title: "Cook Dinner at Home Most Nights",
    subtitle: "Frequent home cooking is associated with a healthier diet; cooking classes improve attitudes and self-efficacy more than cardiometabolic markers",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "moderate" },
    feeds: ["diet quality", "self-efficacy", "shared meals"],
    description:
      "U.S. national dietary data show adults in households that cook dinner six or seven times a week consume fewer calories, less fat and less sugar than those cooking once a week or less, whether or not they are trying to lose weight. Reviews of cooking interventions find improvements in dietary intake, cooking confidence and psychosocial outcomes such as self-esteem and socialization, but a systematic review of 30 studies found no significant change in BMI, blood pressure or LDL cholesterol. Treat cooking as a skill hobby with a diet payoff, not a weight-loss program.",
    action: "Cook dinner at home on at least five nights this week using two new recipes, and take one structured cooking class or course this quarter to learn techniques rather than individual dishes.",
    sources: [
      { cite: "Wolfson, J. A., & Bleich, S. N. (2015). Is cooking at home associated with better diet quality or weight-loss intention? Public Health Nutrition, 18(8), 1397–1406.", note: "NHANES 2007–2010 data on 9,569 adults; households cooking dinner 6–7 times a week consumed fewer daily kilojoules, less fat and less sugar than those cooking 0–1 times, regardless of weight-loss intention.", link: doi("10.1017/S1368980014001943"), kind: "doi" },
      { cite: "Reicks, M., Trofholz, A. C., Stang, J. S., & Laska, M. N. (2014). Impact of cooking and home food preparation interventions among adults: Outcomes and implications for future programs. Journal of Nutrition Education and Behavior, 46(4), 259–276.", note: "Review of 28 cooking-intervention studies; qualitative and quantitative measures suggested positive effects on dietary intake, knowledge, skills and confidence, limited by weak designs.", link: doi("10.1016/j.jneb.2014.02.001"), kind: "doi" },
      { cite: "Hasan, B., Thompson, W. G., Almasri, J., Wang, Z., Lakis, S., Prokop, L. J., Hensrud, D. D., Frie, K. S., Wirtz, M. J., Murad, A. L., Ewoldt, J. S., & Murad, M. H. (2019). The effect of culinary interventions (cooking classes) on dietary intake and behavioral change: A systematic review and evidence map. BMC Nutrition, 5, 29.", note: "Thirty studies (7,381 participants); cooking classes were associated with improved attitudes, self-efficacy and healthier dietary intake but no significant change in BMI, blood pressure or LDL cholesterol.", link: doi("10.1186/s40795-019-0293-8"), kind: "doi" },
      { cite: "Farmer, N., Touchton-Leonard, K., & Ross, A. (2018). Psychosocial benefits of cooking interventions: A systematic review. Health Education & Behavior, 45(2), 167–180.", note: "Eleven studies of cooking interventions; positive influences on socialization, self-esteem, quality of life and affect, with the evidence rated preliminary because of weak designs.", link: doi("10.1177/1090198117736352"), kind: "doi" },
    ],
  },
  {
    id: "gs-hobby-volunteering",
    goal: "hobby", tier: "moderate", section: "8614",
    title: "Volunteer a Few Hours a Month",
    subtitle: "Volunteers show lower mortality, less depression and slower disability progression in cohorts; the experimental evidence is thinner",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "months", durability: "lasting", effort: "moderate" },
    feeds: ["purpose", "social ties", "physical activity"],
    description:
      "A systematic review of 40 papers found cohort studies link volunteering to lower depression and higher wellbeing, and a meta-analysis of five cohorts found volunteers had about 22 percent lower mortality risk; the few randomized trials did not confirm the mental-health effects. A meta-analysis of older adults found volunteering reduced adjusted mortality risk by about a quarter. In the Health and Retirement Study, volunteers used more preventive care and spent fewer nights in hospital, and starting to volunteer later in life was followed by slower progression of disability, especially at higher intensity. Effects are observational and probably partly selection, but the direction is consistent.",
    action: "Choose one organization whose work you care about, commit to a fixed monthly shift of two to four hours for six months, and pick a role that gets you moving and talking rather than sitting alone.",
    sources: [
      { cite: "Jenkinson, C. E., Dickens, A. P., Jones, K., Thompson-Coon, J., Taylor, R. S., Rogers, M., Bambra, C. L., Lang, I., & Richards, S. H. (2013). Is volunteering a public health intervention? A systematic review and meta-analysis of the health and survival of volunteers. BMC Public Health, 13, 773.", note: "Forty papers reviewed; cohort studies showed favourable effects on depression, life satisfaction and wellbeing, and meta-analysis of five cohorts found a mortality risk ratio of 0.78, while experimental studies did not confirm these effects.", link: doi("10.1186/1471-2458-13-773"), kind: "doi" },
      { cite: "Okun, M. A., Yeung, E. W., & Brown, S. (2013). Volunteering by older adults and risk of mortality: A meta-analysis. Psychology and Aging, 28(2), 564–577.", note: "Meta-analysis of organizational volunteering by adults aged 55+; volunteering reduced mortality risk by 47% unadjusted and 24% after adjustment for health and other variables.", link: doi("10.1037/a0031519"), kind: "doi" },
      { cite: "Anderson, N. D., Damianakis, T., Kröger, E., Wagner, L. M., Dawson, D. R., Binns, M. A., Bernstein, S., Caspi, E., & Cook, S. L. (2014). The benefits associated with volunteering among seniors: A critical review and recommendations for future research. Psychological Bulletin, 140(6), 1505–1533.", note: "Critical review of 73 papers; volunteering was most consistently associated with reduced depressive symptoms, better self-reported health, fewer functional limitations and lower mortality in older adults.", link: doi("10.1037/a0037610"), kind: "doi" },
      { cite: "Kim, E. S., & Konrath, S. H. (2016). Volunteering is prospectively associated with health care use among older adults. Social Science & Medicine, 149, 122–129.", note: "7,168 Health and Retirement Study participants tracked two years; volunteers were more likely to receive preventive screenings and spent 38% fewer nights in hospital, with no difference in doctor visits.", link: doi("10.1016/j.socscimed.2015.11.043"), kind: "doi" },
      { cite: "Carr, D. C., Kail, B. L., & Rowe, J. W. (2018). The relation of volunteering and subsequent changes in physical disability in older adults. The Journals of Gerontology: Series B, 73(3), 511–521.", note: "Propensity-weighted analysis of 7,135 older adults; initiating volunteering was related to slower progression of disability, with larger effects at 100+ hours a year and for women at any level.", link: doi("10.1093/geronb/gbx102"), kind: "doi" },
    ],
  },
  {
    id: "gs-hobby-social-hobbies",
    goal: "hobby", tier: "fundamental", section: "8615",
    title: "Choose a Hobby That Comes With People",
    subtitle: "Loneliness and isolation raise mortality risk on par with established risk factors; group-based, participatory activities are the interventions that most often work",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "weeks", durability: "lasting", effort: "moderate" },
    feeds: ["belonging", "routine contact", "mortality risk"],
    description:
      "Holt-Lunstad and colleagues' meta-analysis found social isolation, loneliness and living alone each raise the likelihood of death by roughly a quarter to a third, comparable to well-established risk factors. Masi's meta-analysis of loneliness interventions found the most effective randomized approaches addressed maladaptive social cognition, while a systematic review of interventions for isolated older people found group-based, participatory activities with a theoretical basis most often produced benefits. Walking groups — a hobby that is social by construction — showed wide-ranging health benefits and a reduction in depression scores across 42 studies.",
    action: "Whatever hobby you pick, do it in a group form at least once a week — a club, class, league or walking group — and put the recurring meeting in your calendar for the next three months.",
    sources: [
      { cite: "Holt-Lunstad, J., Smith, T. B., Baker, M., Harris, T., & Stephenson, D. (2015). Loneliness and social isolation as risk factors for mortality: A meta-analytic review. Perspectives on Psychological Science, 10(2), 227–237.", note: "Meta-analysis across 70 studies; social isolation, loneliness and living alone were associated with 29%, 26% and 32% higher likelihood of mortality respectively, comparable to established risk factors.", link: doi("10.1177/1745691614568352"), kind: "doi" },
      { cite: "Masi, C. M., Chen, H.-Y., Hawkley, L. C., & Cacioppo, J. T. (2011). A meta-analysis of interventions to reduce loneliness. Personality and Social Psychology Review, 15(3), 219–266.", note: "Meta-analysis of four intervention strategies; among randomized studies, interventions addressing maladaptive social cognition were the most successful, with social-contact opportunities helping less on their own.", link: doi("10.1177/1088868310377394"), kind: "doi" },
      { cite: "Dickens, A. P., Richards, S. H., Greaves, C. J., & Campbell, J. L. (2011). Interventions targeting social isolation in older people: A systematic review. BMC Public Health, 11, 647.", note: "Thirty-two studies; 79% of group-based and over 80% of participatory interventions reported at least one improved outcome, versus 55% of one-to-one and 44% of non-participatory ones.", link: doi("10.1186/1471-2458-11-647"), kind: "doi" },
      { cite: "Hanson, S., & Jones, A. (2015). Is there evidence that walking groups have health benefits? A systematic review and meta-analysis. British Journal of Sports Medicine, 49(11), 710–715.", note: "Forty-two studies (1,843 participants); walking groups reduced blood pressure, resting heart rate, body fat and depression scores (effect size −0.67) and improved fitness, with good adherence and no notable adverse effects.", link: doi("10.1136/bjsports-2014-094157"), kind: "doi" },
    ],
  },
  {
    id: "gs-hobby-later-life-engagement",
    goal: "hobby", tier: "elite", section: "8616",
    title: "Keep a Mentally Demanding Hobby for Decades",
    subtitle: "Cognitively stimulating and social leisure across later life is associated with lower dementia incidence and depression; the payoff horizon is years",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "months", durability: "lasting", effort: "moderate" },
    feeds: ["cognitive reserve", "mood", "independence"],
    description:
      "Multiple long cohorts converge: frequent participation in cognitively stimulating activities was associated with a 33 percent lower risk of Alzheimer disease in the Religious Orders Study; daily-to-weekly mental, social or productive activities roughly halved dementia incidence in the Kungsholmen Project; and a meta-analysis of 38 longitudinal studies (over two million participants) found cognitive, physical and social leisure activities each associated with lower all-cause dementia incidence. Fixed-effects analyses of hobbies and depression in the same people over time support hobby engagement preceding lower depressive symptoms. Stern's cognitive-reserve framework explains why later-life activity can buffer brain changes. The 'use it or lose it' caveat stands: high-ability people also choose active lives, so the causal share is uncertain.",
    action: "Adopt one hobby that is mentally demanding and social — an instrument, a language, chess club, a choir, a craft guild — and treat it as a standing weekly commitment you renew every January for the rest of your life.",
    sources: [
      { cite: "Wilson, R. S., Mendes de Leon, C. F., Barnes, L. L., Schneider, J. A., Bienias, J. L., Evans, D. A., & Bennett, D. A. (2002). Participation in cognitively stimulating activities and risk of incident Alzheimer disease. JAMA, 287(6), 742–748.", note: "801 older clergy followed 4.5 years; a one-point increase in cognitive-activity frequency was associated with a 33% reduction in Alzheimer disease risk and slower decline in global cognition, working memory and perceptual speed.", link: doi("10.1001/jama.287.6.742"), kind: "doi" },
      { cite: "Wang, H.-X., Karp, A., Winblad, B., & Fratiglioni, L. (2002). Late-life engagement in social and leisure activities is associated with a decreased risk of dementia: A longitudinal study from the Kungsholmen Project. American Journal of Epidemiology, 155(12), 1081–1087.", note: "Stockholm cohort; frequent mental, social or productive activities 6.4 years before diagnosis were associated with adjusted relative risks of dementia of 0.54, 0.58 and 0.58 respectively.", link: doi("10.1093/aje/155.12.1081"), kind: "doi" },
      { cite: "Su, S., Shi, L., Zheng, Y., Sun, Y., Huang, X., Zhang, A., Que, J., Sun, X., Shi, J., Bao, Y., Deng, J., & Lu, L. (2022). Leisure activities and the risk of dementia: A systematic review and meta-analysis. Neurology, 99(15), e1651–e1663.", note: "38 longitudinal studies with 2,154,818 participants; physical (RR 0.83), cognitive (RR 0.77) and social (RR 0.93) leisure activities were each associated with lower all-cause dementia incidence.", link: doi("10.1212/WNL.0000000000200929"), kind: "doi" },
      { cite: "Hultsch, D. F., Hertzog, C., Small, B. J., & Dixon, R. A. (1999). Use it or lose it: Engaged lifestyle as a buffer of cognitive decline in aging? Psychology and Aging, 14(2), 245–263.", note: "250 middle-aged and older adults tested three times over six years; changes in intellectually engaging activity tracked changes in cognition, consistent with buffering but also with high-ability people staying active.", link: doi("10.1037//0882-7974.14.2.245"), kind: "doi" },
      { cite: "Stern, Y. (2012). Cognitive reserve in ageing and Alzheimer's disease. The Lancet Neurology, 11(11), 1006–1012.", note: "Review of the cognitive-reserve concept; education, occupation and later-life leisure activities are associated with greater tolerance of age- and disease-related brain changes.", link: doi("10.1016/S1474-4422(12)70191-6"), kind: "doi" },
      { cite: "Fancourt, D., Opher, S., & de Oliveira, C. (2020). Fixed-effects analyses of time-varying associations between hobbies and depression in a longitudinal cohort study: Support for social prescribing? Psychotherapy and Psychosomatics, 89(2), 111–113.", note: "Within-person fixed-effects analyses in a longitudinal cohort relate taking up or keeping hobbies to lower depressive symptoms over time, supporting hobby-based social prescribing.", link: doi("10.1159/000503571"), kind: "doi" },
      { cite: "Mak, H. W., Noguchi, T., Bone, J. K., Wels, J., Gao, Q., Kondo, K., Saito, T., & Fancourt, D. (2023). Hobby engagement and mental wellbeing among people aged 65 years and older in 16 countries. Nature Medicine, 29(9), 2233–2240.", note: "Across 93,263 older adults in 16 countries, having a hobby was associated with fewer depressive symptoms and higher happiness and life satisfaction, with further analyses suggesting a temporal relationship.", link: doi("10.1038/s41591-023-02506-1"), kind: "doi" },
    ],
  },
  {
    id: "gs-hobby-productive-engagement",
    goal: "hobby", tier: "elite", section: "8617",
    title: "Spend Three Months Learning Something Genuinely Hard",
    subtitle: "Sustained, demanding new-skill learning — quilting, digital photography, acting, juggling, tai chi — changed memory, cognition and even brain structure in controlled studies",
    evidenceTag: "Moderate",
    impact: { magnitude: 4, latency: "months", durability: "sustained", effort: "high" },
    feeds: ["episodic memory", "executive function", "confidence"],
    description:
      "The Synapse Project randomized older adults to learn quilting, digital photography or both for an average of 16.5 hours a week over three months; these productive-engagement conditions improved episodic memory relative to social-only and low-demand conditions. Four weeks of theatre training improved cognitive and wellbeing measures more than visual-arts training or no treatment, and three months of learning to juggle produced measurable grey-matter change in adults. Meta-analyses of tai chi and yoga find moderate cognitive benefits, with tai chi showing large executive-function effects versus non-active controls. The common ingredient is novelty plus sustained effort.",
    action: "Choose one skill you have never tried that demands real concentration, commit 10–15 hours a week for 12 weeks with a class or teacher, and test yourself on the skill at the start, midpoint and end.",
    sources: [
      { cite: "Park, D. C., Lodi-Smith, J., Drew, L., Haber, S., Hebrank, A., Bischof, G. N., & Aamodt, W. (2014). The impact of sustained engagement on cognitive function in older adults: The Synapse Project. Psychological Science, 25(1), 103–112.", note: "Older adults learned quilting, digital photography or both for an average of 16.51 hours a week for three months; these high-demand conditions enhanced episodic memory relative to social and low-demand controls.", link: doi("10.1177/0956797613499592"), kind: "doi" },
      { cite: "Noice, H., Noice, T., & Staines, G. (2004). A short-term intervention to enhance cognitive and affective functioning in older adults. Journal of Aging and Health, 16(4), 562–585.", note: "124 community-dwelling adults aged 60–86; four weeks of theatre-arts training produced greater gains in cognitive and psychological wellbeing measures than visual-arts training or no treatment.", link: doi("10.1177/0898264304265819"), kind: "doi" },
      { cite: "Draganski, B., Gaser, C., Busch, V., Schuierer, G., Bogdahn, U., & May, A. (2004). Neuroplasticity: Changes in grey matter induced by training. Nature, 427(6972), 311–312.", note: "Adults who learned to juggle over three months showed transient grey-matter expansion in motion-processing regions that receded after they stopped practicing.", link: doi("10.1038/427311a"), kind: "doi" },
      { cite: "Wayne, P. M., Walsh, J. N., Taylor-Piliae, R. E., Wells, R. E., Papp, K. V., Donovan, N. J., & Yeh, G. Y. (2014). Effect of tai chi on cognitive performance in older adults: Systematic review and meta-analysis. Journal of the American Geriatrics Society, 62(1), 25–39.", note: "Twenty studies (2,553 participants); in randomized trials of cognitively healthy adults, tai chi showed a large effect on executive function versus non-intervention controls (g = 0.90) and a moderate effect versus exercise controls (g = 0.51).", link: doi("10.1111/jgs.12611"), kind: "doi" },
      { cite: "Gothe, N. P., & McAuley, E. (2015). Yoga and cognition: A meta-analysis of chronic and acute effects. Psychosomatic Medicine, 77(7), 784–797.", note: "Fifteen randomized trials and seven acute studies; yoga showed a moderate effect on cognition in trials (g = 0.33), strongest for attention and processing speed, with the authors noting sample-size and heterogeneity limits.", link: doi("10.1097/PSY.0000000000000218"), kind: "doi" },
    ],
  },
  {
    id: "gs-hobby-creative-recovery-work",
    goal: "hobby", tier: "moderate", section: "8618",
    title: "Use a Creative Hobby as Your Recovery From Work",
    subtitle: "Creative activity outside work relates to recovery experiences and better job performance ratings; recovery itself predicts vigor and fatigue",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "low" },
    feeds: ["psychological detachment", "mastery", "work performance"],
    description:
      "Eschleman and colleagues found that employees' creative activity outside work was positively related to recovery experiences — mastery, control and relaxation — and, through them, to supervisor-rated performance and creativity on the job. The recovery literature explains why: Sonnentag and Fritz distinguished detachment, relaxation, mastery and control as separate recovery experiences, and a meta-analysis of 54 samples found detachment most strongly reduces fatigue while mastery and control experiences most strongly raise vigor. A hobby that demands learning gives you mastery and control in one package.",
    action: "Block a 45-minute creative session on at least two workday evenings this month, keep work devices out of the room, and rate your energy the next morning to see which sessions restore you most.",
    sources: [
      { cite: "Eschleman, K. J., Madsen, J., Alarcon, G., & Barelka, A. (2014). Benefiting from creative activity: The positive relationships between creative activity, recovery experiences, and performance-related outcomes. Journal of Occupational and Organizational Psychology, 87(3), 579–598.", note: "Two studies of employees; creative activity outside work related to recovery experiences and to performance-related outcomes including supervisor-rated job creativity.", link: doi("10.1111/joop.12064"), kind: "doi" },
      { cite: "Sonnentag, S., & Fritz, C. (2007). The Recovery Experience Questionnaire: Development and validation of a measure for assessing recuperation and unwinding from work. Journal of Occupational Health Psychology, 12(3), 204–221.", note: "Develops and validates measures of four recovery experiences — psychological detachment, relaxation, mastery and control — in samples totalling 930 people, and relates them to wellbeing.", link: doi("10.1037/1076-8998.12.3.204"), kind: "doi" },
      { cite: "Bennett, A. A., Bakker, A. B., & Field, J. G. (2018). Recovery from work-related effort: A meta-analysis. Journal of Organizational Behavior, 39(3), 262–275.", note: "Meta-analysis of 299 effect sizes from 54 samples (N = 26,592); detachment most strongly reduced fatigue, control and mastery experiences most strongly raised vigor, and recovery explained variance beyond work characteristics.", link: doi("10.1002/job.2217"), kind: "doi" },
    ],
  },
  {
    id: "gs-hobby-myth-brain-training",
    goal: "hobby", tier: "moderate", section: "8619",
    title: "Myth: Brain-Training Apps Make You Smarter",
    subtitle: "Practice improves the trained tasks; there is little evidence of transfer to untrained tasks or everyday cognition",
    evidenceTag: "Strong",
    impact: { magnitude: 1, latency: "weeks", durability: "transient", effort: "moderate" },
    callout: "Rated at the floor. A six-week online trial with 11,430 participants found improvement on every trained task and no transfer to untrained tasks, even closely related ones; a meta-analysis of working-memory training found short-term, specific gains that did not generalize; and the comprehensive review of the evidence cited by brain-training companies found none of it met best-practice standards for showing everyday benefit. Far transfer from chess, music and working-memory training is likewise not supported. Spend the time on a real hobby with a real community.",
    description:
      "Owen and colleagues' Nature study trained thousands of adults several times a week on tasks designed to improve reasoning, memory, planning and attention and found no transfer. Melby-Lervåg and Hulme's meta-analysis of working-memory training found reliable near-transfer that faded at follow-up and no convincing generalization to other abilities. Simons and colleagues' review concluded there is extensive evidence that brain-training improves the trained tasks, less that it improves closely related tasks, and little that it improves everyday cognitive performance. Sala and Gobet's meta-analyses extend the verdict to chess, music and working-memory training: effect sizes shrink toward zero as designs improve.",
    action: "Cancel any subscription bought for cognitive benefit and redirect that time to the productive-engagement, language or dance protocols on this shelf, which involve novelty, social contact and real-world skill.",
    sources: [
      { cite: "Simons, D. J., Boot, W. R., Charness, N., Gathercole, S. E., Chabris, C. F., Hambrick, D. Z., & Stine-Morrow, E. A. L. (2016). Do \"brain-training\" programs work? Psychological Science in the Public Interest, 17(3), 103–186.", note: "Evaluates every peer-reviewed intervention study cited on leading brain-training websites; extensive evidence of gains on trained tasks, less for closely related tasks, and little for distantly related tasks or everyday cognition, with no study meeting all best-practice criteria.", link: doi("10.1177/1529100616661983"), kind: "doi" },
      { cite: "Owen, A. M., Hampshire, A., Grahn, J. A., Stenton, R., Dajani, S., Burns, A. S., Howard, R. J., & Ballard, C. G. (2010). Putting brain training to the test. Nature, 465(7299), 775–778.", note: "Six-week online study with 11,430 participants training several times a week; performance improved on every trained task but showed no transfer to untrained tasks, even cognitively similar ones.", link: doi("10.1038/nature09042"), kind: "doi" },
      { cite: "Melby-Lervåg, M., & Hulme, C. (2013). Is working memory training effective? A meta-analytic review. Developmental Psychology, 49(2), 270–291.", note: "Meta-analysis of 23 studies; working-memory training produced short-term gains on working-memory tasks that were not sustained for verbal memory and did not generalize to attention, reasoning, decoding or arithmetic.", link: doi("10.1037/a0028228"), kind: "doi" },
      { cite: "Sala, G., & Gobet, F. (2017). Does far transfer exist? Negative evidence from chess, music, and working memory training. Current Directions in Psychological Science, 26(6), 515–520.", note: "Three meta-analyses of chess, music and working-memory training show small-to-moderate effects that are inversely related to design quality, leading the authors to conclude far transfer rarely occurs.", link: doi("10.1177/0963721417712760"), kind: "doi" },
    ],
  },
  {
    id: "gs-hobby-group-music",
    goal: "hobby", tier: "elite", section: "8620",
    title: "Join a Choir or Ensemble for a Year",
    subtitle: "Community singing improved mental-health-related quality of life in a randomized trial of older adults; a year-long chorale reduced doctor visits and loneliness",
    evidenceTag: "Moderate",
    impact: { magnitude: 4, latency: "months", durability: "lasting", effort: "high" },
    feeds: ["social connection", "mood", "breath and voice"],
    description:
      "Group music-making stacks several protocols on this shelf: skill, flow, arts engagement and a weekly social group. In a pragmatic randomized trial of 258 people aged 60 and over, community group singing improved mental-health-related quality of life at six months and reduced anxiety and depression at three months, at marginally lower cost than usual activities. Cohen's year-long comparison of a professionally conducted chorale versus usual activity found fewer doctor visits, less medication use, fewer falls, better morale and less loneliness in the chorale group. In early dementia, ten weeks of caregiver-coached singing or music listening improved mood, orientation and memory in a randomized study.",
    action: "Audition for or join a community choir, band or ensemble that rehearses weekly, commit to a full season of at least nine months including performances, and practice your part between rehearsals.",
    sources: [
      { cite: "Coulton, S., Clift, S., Skingley, A., & Rodriguez, J. (2015). Effectiveness and cost-effectiveness of community singing on mental health-related quality of life of older people: Randomised controlled trial. The British Journal of Psychiatry, 207(3), 250–255.", note: "Pragmatic randomized trial of 258 adults aged 60+ across five centres; group singing improved mental-health-related quality of life at six months and reduced anxiety and depression at three months, and was marginally more cost-effective than usual activities.", link: doi("10.1192/bjp.bp.113.129908"), kind: "doi" },
      { cite: "Cohen, G. D., Perlstein, S., Chapline, J., Kelly, J., Firth, K. M., & Simmens, S. (2006). The impact of professionally conducted cultural programs on the physical health, mental health, and social functioning of older adults. The Gerontologist, 46(6), 726–734.", note: "166 healthy adults aged 65+ assigned to a professionally conducted chorale or usual activities for 12 months; the chorale group reported better health, fewer doctor visits, less medication, fewer falls, better morale and less loneliness.", link: doi("10.1093/geront/46.6.726"), kind: "doi" },
      { cite: "Särkämö, T., Tervaniemi, M., Laitinen, S., Numminen, A., Kurki, M., Johnson, J. K., & Rantanen, P. (2014). Cognitive, emotional, and social benefits of regular musical activities in early dementia: Randomized controlled study. The Gerontologist, 54(4), 634–650.", note: "89 person-with-dementia–caregiver dyads randomized to ten weeks of coached singing, music listening or usual care; both music groups improved mood, orientation and remote memory, and singing also improved working memory and caregiver wellbeing.", link: doi("10.1093/geront/gnt100"), kind: "doi" },
    ],
  },
];
