// Goal shelf: HOME — buy a house (sections 8900–8999).
// Verification: every DOI below was resolved against the Crossref record (api.crossref.org)
// or the PubMed record on 2026-09-11. See types.ts for the contract. Economics sources sit
// outside PubMed and were verified through Crossref. Popular advice the evidence does not
// support is rated at the floor (magnitude 1) with a callout. Nothing on this shelf is
// financial, legal, tax or investment advice; each source is described as what the study
// tested, and the household's own numbers decide the rest.
import { doi, type GoalShelfCluster } from "./types";

export const SECTIONS: Record<string, string> = {
  "8900": "How to Read This Shelf",
  "8901": "Rent Versus Buy — The User Cost of Housing and the Honest Answer",
  "8902": "Housing Cost Burden — The 30% Rule, Residual Income and Health",
  "8903": "Saving the Down Payment — Behavioral Tools That Move Money",
  "8904": "Credit Score — What Actually Moves It",
  "8905": "Homebuyer Education & Counseling — What the Trials Show",
  "8906": "Down-Payment Assistance & Matched Savings — Outcomes",
  "8907": "Homeownership & Wealth Building — The Honest Ledger",
  "8908": "Homeownership, Children & Citizenship — Real Effects or Self-Selection",
  "8909": "Mortgage Choice — Fixed Versus Adjustable, and Why",
  "8910": "Shopping the Mortgage — Rate Dispersion and Overpayment",
  "8911": "Refinancing — A Rule, Not a Feeling",
  "8912": "Timing the Market — Waiting for the Bottom",
  "8913": "Location — Commuting, Time and Wellbeing",
  "8914": "Neighborhood Effects — Moving to Opportunity and Childhood Exposure",
  "8915": "Negotiation — Anchors, First Offers and Loss Aversion",
  "8916": "Mortgage Default Risk — The Double Trigger",
  "8917": "Foreclosure Prevention — Liquidity, Modification and Counseling",
  "8918": "The Ownership System — Down Payment, Rate, Reserve and Horizon",
};

export const CLUSTERS: GoalShelfCluster[] = [
  {
    id: "gs-home-read-me-first",
    goal: "home", tier: "fundamental", section: "8900",
    title: "How to Read the Home Shelf",
    subtitle: "A house is a consumption good and a leveraged asset — the shelf treats it as both",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "low" },
    description:
      "Every protocol on this shelf is tagged fundamental, moderate, advanced or elite and carries a concrete action. The economics literature is clear that whether buying beats renting depends on the user cost of owning, the holding period and what the renter does with the difference — not on a slogan. The shelf starts with the arithmetic and the affordability floor, moves through saving, credit, counseling and the mortgage decision, and ends with the neighborhood and default evidence that determines whether a purchase makes a family better off. Nothing here is financial advice; each cluster describes what the studies tested.",
    action: "This month, run the fundamental protocols in order — the rent-versus-buy calculation, the residual-income affordability check and the automatic down-payment transfer — before you look at a single listing.",
    sources: [
      { cite: "Goodman, L. S., & Mayer, C. (2018). Homeownership and the American Dream. Journal of Economic Perspectives, 32(1), 31–58.", note: "Reviews the evidence on homeownership as a financial and social goal in the United States, including the risks of leverage and the conditions under which ownership builds wealth, as a balanced starting point for the decision.", link: doi("10.1257/jep.32.1.31"), kind: "doi" },
      { cite: "Beracha, E., & Johnson, K. H. (2012). Lessons from over 30 years of buy versus rent decisions: Is the American Dream always wise?. Real Estate Economics, 40(2), 217–247.", note: "Compares 30+ years of buy-versus-rent outcomes across US markets, finding that renting and investing the difference often produced comparable or better wealth than owning — the American Dream is not always the wise choice.", link: doi("10.1111/j.1540-6229.2011.00321.x"), kind: "doi" },
    ],
  },
  {
    id: "gs-home-user-cost",
    goal: "home", tier: "fundamental", section: "8901",
    title: "Run the User-Cost Calculation Before You Shop",
    subtitle: "Compare the annual cost of owning (rate, taxes, maintenance, expected appreciation) with rent — for your horizon",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "weeks", durability: "lasting", effort: "low" },
    feeds: ["decision quality", "overpayment avoidance", "household risk management"],
    description:
      "The user-cost framework prices a year of owning as the after-tax cost of capital plus property taxes, maintenance and a risk premium, minus expected appreciation, and compares it with rent. Applied to US metros it explains when high prices are consistent with fundamentals and when they are not. A second strand shows that owning also hedges rent risk, which is worth more the longer a household expects to stay. A 30-year comparison of buy-versus-rent outcomes across markets found that renting and investing the difference often did as well or better. The honest boundary: the answer depends on holding period, local rent-to-price ratios and whether the renter actually invests the difference.",
    action: "This week, write one page with your numbers: after-tax mortgage cost, property tax, insurance, 1–2% of price for maintenance, minus a conservative appreciation assumption, versus the rent for an equivalent home — and compute it for a 3-, 7- and 12-year stay before you decide.",
    sources: [
      { cite: "Himmelberg, C., Mayer, C., & Sinai, T. (2005). Assessing high house prices: Bubbles, fundamentals and misperceptions. Journal of Economic Perspectives, 19(4), 67–92.", note: "Lays out the user cost of housing and applies it to US metropolitan areas to distinguish bubbles from fundamentals — the standard framework for judging whether prices are high relative to rents.", link: doi("10.1257/089533005775196769"), kind: "doi" },
      { cite: "Poterba, J. M. (1984). Tax subsidies to owner-occupied housing: An asset-market approach. The Quarterly Journal of Economics, 99(4), 729–752.", note: "Foundational asset-market model of owner-occupied housing showing how tax treatment enters the user cost of owning.", link: doi("10.2307/1883123"), kind: "doi" },
      { cite: "Sinai, T., & Souleles, N. S. (2005). Owner-occupied housing as a hedge against rent risk. Quarterly Journal of Economics, 120(2), 763–789.", note: "Shows that owning hedges the risk of rent fluctuations, so the value of owning rises with rent volatility and expected length of stay.", link: doi("10.1162/0033553053970197"), kind: "doi" },
      { cite: "Beracha, E., & Johnson, K. H. (2012). Lessons from over 30 years of buy versus rent decisions: Is the American Dream always wise?. Real Estate Economics, 40(2), 217–247.", note: "Across US regions and decades, a disciplined renter who invested the difference frequently ended with more wealth than an owner — buying wins only under specific conditions.", link: doi("10.1111/j.1540-6229.2011.00321.x"), kind: "doi" },
      { cite: "Jordà, Ò., Knoll, K., Kuvshinov, D., Schularick, M., & Taylor, A. M. (2019). The rate of return on everything, 1870–2015. The Quarterly Journal of Economics, 134(3), 1225–1298.", note: "Long-run returns on housing, equities, bonds and bills across advanced economies since 1870; housing's total return has been comparable to equities with lower volatility, largely through rental yield rather than price appreciation.", link: doi("10.1093/qje/qjz012"), kind: "doi" },
      { cite: "Campbell, J. Y. (2006). Household finance. The Journal of Finance, 61(4), 1553–1604.", note: "Review of household finance documenting how households manage housing and mortgage decisions and where they systematically make mistakes.", link: doi("10.1111/j.1540-6261.2006.00883.x"), kind: "doi" },
    ],
  },
  {
    id: "gs-home-rent-myth",
    goal: "home", tier: "fundamental", section: "8901",
    title: "Myth: Renting Is Throwing Money Away",
    subtitle: "Buying always beats renting, and the sooner the better",
    evidenceTag: "Strong",
    impact: { magnitude: 1, latency: "months", durability: "transient", effort: "low" },
    callout: "Rated at the floor because the long-run comparisons show renting-and-investing frequently matches or beats owning, housing returns come mostly from rental yield rather than price gains, and a leveraged, undiversified, illiquid asset carries risk the slogan ignores. Buy when the user-cost calculation and your horizon say so, not because rent 'disappears'.",
    description:
      "The most common piece of housing advice is that rent is wasted while a mortgage payment builds equity. The economics is more careful: a large share of an early mortgage payment is interest, taxes, insurance and maintenance that also 'disappear'; long-run returns to housing come largely from rental yield, which the owner consumes rather than banks; and portfolio research shows that a house concentrates a household's wealth in one leveraged, illiquid asset. Historical buy-versus-rent comparisons find the renter who invests the difference frequently ends up ahead.",
    action: "Retire the slogan. Replace it with the one-page user-cost comparison from the previous cluster and a written statement of how long you actually expect to stay; if that is under five years, the evidence leans toward renting.",
    sources: [
      { cite: "Beracha, E., & Johnson, K. H. (2012). Lessons from over 30 years of buy versus rent decisions: Is the American Dream always wise?. Real Estate Economics, 40(2), 217–247.", note: "Direct test of the slogan across more than three decades: renters who invested the difference often accumulated more wealth than buyers.", link: doi("10.1111/j.1540-6229.2011.00321.x"), kind: "doi" },
      { cite: "Himmelberg, C., Mayer, C., & Sinai, T. (2005). Assessing high house prices: Bubbles, fundamentals and misperceptions. Journal of Economic Perspectives, 19(4), 67–92.", note: "Explains why price alone says little about whether owning is expensive; the user cost, not the sticker price, is what a buyer pays.", link: doi("10.1257/089533005775196769"), kind: "doi" },
      { cite: "Jordà, Ò., Knoll, K., Kuvshinov, D., Schularick, M., & Taylor, A. M. (2019). The rate of return on everything, 1870–2015. The Quarterly Journal of Economics, 134(3), 1225–1298.", note: "Housing's long-run return came mainly from rental yield rather than capital gains — the part an owner-occupier consumes rather than earns.", link: doi("10.1093/qje/qjz012"), kind: "doi" },
      { cite: "Goodman, L. S., & Mayer, C. (2018). Homeownership and the American Dream. Journal of Economic Perspectives, 32(1), 31–58.", note: "Balanced review of homeownership's financial case, including the role of leverage and the losses of households who bought at the wrong time.", link: doi("10.1257/jep.32.1.31"), kind: "doi" },
      { cite: "Cocco, J. F. (2005). Portfolio choice in the presence of housing. Review of Financial Studies, 18(2), 535–567.", note: "Life-cycle portfolio model showing that housing crowds out stockholding and concentrates risk, especially for younger and poorer households.", link: doi("10.1093/rfs/hhi006"), kind: "doi" },
      { cite: "Campbell, J. Y., & Cocco, J. F. (2007). How do house prices affect consumption? Evidence from micro data. Journal of Monetary Economics, 54(3), 591–621.", note: "Micro evidence that house-price movements drive consumption of older owners far more than young renters — house prices redistribute rather than create wealth for a household that must keep living somewhere.", link: doi("10.1016/j.jmoneco.2005.10.016"), kind: "doi" },
    ],
  },
  {
    id: "gs-home-cost-burden",
    goal: "home", tier: "fundamental", section: "8902",
    title: "Set Your Affordability Floor by Residual Income, Not Just 30%",
    subtitle: "What is left after housing must cover a real budget — and the evidence on what cost burden does to health",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "weeks", durability: "lasting", effort: "low" },
    feeds: ["financial resilience", "mental health", "default risk"],
    description:
      "The 30%-of-income rule is a convention with several competing uses, and the residual-income approach argues that what matters is whether income left after housing covers other necessities. Cost burden is not a brief spell: US panel data show it is deep, frequent and persistent, and linked administrative data tie rising rent burden to higher mortality. Panel studies associate housing cost burden with worse mental health, and renters' financial strain explains part of the mental-health gap between renters and owners. The boundary: these are associations in mostly renter populations, but the mechanism — a budget that cannot absorb shocks — applies to buyers.",
    action: "Before setting a price ceiling, subtract a realistic non-housing budget (food, transport, childcare, debt payments, savings) from take-home pay; the remainder, not 30% of gross income, is your maximum all-in monthly housing cost, and you buy below it.",
    sources: [
      { cite: "Hulchanski, J. D. (1995). The concept of housing affordability: Six contemporary uses of the housing expenditure-to-income ratio. Housing Studies, 10(4), 471–491.", note: "Traces six different uses of the housing expenditure-to-income ratio and argues that the ratio is a weak measure of what a household can actually afford.", link: doi("10.1080/02673039508720833"), kind: "doi" },
      { cite: "Stone, M. E. (2006). What is housing affordability? The case for the residual income approach. Housing Policy Debate, 17(1), 151–184.", note: "Makes the case for a residual-income standard of affordability: housing is affordable when what remains covers a minimum budget for everything else.", link: doi("10.1080/10511482.2006.9521564"), kind: "doi" },
      { cite: "Colburn, G., Hess, C., Allen, R., & Crowder, K. (2024). The dynamics of housing cost burden among renters in the United States. Journal of Urban Affairs, 47(7), 2403–2422.", note: "Fifty years of PSID data: housing cost burden among US renters is deep, frequent and persistent rather than episodic.", link: doi("10.1080/07352166.2023.2288587"), kind: "doi" },
      { cite: "Graetz, N., Gershenson, C., Porter, S. R., Sandler, D. H., Lemmerman, E., & Desmond, M. (2024). The impacts of rent burden and eviction on mortality in the United States, 2000–2019. Social Science & Medicine, 340, 116398.", note: "Linked Census and mortality data for 6.6 million renters: a 70% rent burden versus 30% was associated with 12% higher mortality, and a 20-point rise in burden with 16% higher mortality.", link: doi("10.1016/j.socscimed.2023.116398"), kind: "doi" },
      { cite: "Ogawa, K., Shimatani, K., Endo, K., & Suzuki, N. (2026). Associations between individual housing cost burden and depressive symptoms by relative income: A 13-wave panel study. Public Health, 250, 106087.", note: "13-wave Japanese panel (5,011 adults): individual housing cost burden of 30% or more was associated with more depressive symptoms, concentrated among men who were not primary breadwinners.", link: doi("10.1016/j.puhe.2025.106087"), kind: "doi" },
      { cite: "Kosīte, D., Gueltzow, M., van Lenthe, F. J., Beenackers, M. A., & Groeniger, J. O. (2025). Would intervening on financial strain reduce inequalities in mental health between renters and homeowners?. Health & Place, 92, 103434.", note: "Dutch longitudinal data: renters scored about 5 points lower on mental health than owners, and financial strain accounted for roughly a sixth of that gap.", link: doi("10.1016/j.healthplace.2025.103434"), kind: "doi" },
    ],
  },
  {
    id: "gs-home-down-payment-saving",
    goal: "home", tier: "fundamental", section: "8903",
    title: "Automate the Down Payment",
    subtitle: "A separate earmarked account, an automatic transfer that rises with each raise, and reminders",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "weeks", durability: "lasting", effort: "low" },
    feeds: ["savings rate", "purchase readiness", "follow-through"],
    description:
      "Behavioral field experiments show that saving is driven more by defaults, commitment and salience than by willpower. Automatic enrollment raised participation and contributions; pre-committing to escalate saving with future raises raised saving rates over time; commitment accounts increased balances; text reminders about the goal increased saving; and earmarking money in a separate, labelled envelope or account raised saving among low-income households. The boundary: most trials were on retirement or general saving, not down payments, and peer-comparison information can backfire for those far behind.",
    action: "Open a separate account named for the house, set an automatic transfer on payday sized to reach your target date, commit in writing to raise it by half of every future raise, and set a monthly reminder that names the goal.",
    sources: [
      { cite: "Thaler, R. H., & Benartzi, S. (2004). Save More Tomorrow™: Using behavioral economics to increase employee saving. Journal of Political Economy, 112(S1), S164–S187.", note: "Save More Tomorrow: employees who pre-committed to raising savings with future raises increased their saving rates substantially over successive pay rises.", link: doi("10.1086/380085"), kind: "doi" },
      { cite: "Madrian, B. C., & Shea, D. F. (2001). The power of suggestion: Inertia in 401(k) participation and savings behavior. The Quarterly Journal of Economics, 116(4), 1149–1187.", note: "Automatic enrollment in a 401(k) dramatically increased participation and anchored contributions at the default — evidence that defaults, not decisions, drive saving.", link: doi("10.1162/003355301753265543"), kind: "doi" },
      { cite: "Ashraf, N., Karlan, D., & Yin, W. (2006). Tying Odysseus to the mast: Evidence from a commitment savings product in the Philippines. The Quarterly Journal of Economics, 121(2), 635–672.", note: "Randomised offer of a commitment savings account in the Philippines raised savings balances, especially for those who understood their own self-control problem.", link: doi("10.1162/qjec.2006.121.2.635"), kind: "doi" },
      { cite: "Karlan, D., McConnell, M., Mullainathan, S., & Zinman, J. (2016). Getting to the top of mind: How reminders increase saving. Management Science, 62(12), 3393–3411.", note: "Three field experiments: reminders increased saving, and reminders mentioning the specific goal were most effective.", link: doi("10.1287/mnsc.2015.2296"), kind: "doi" },
      { cite: "Soman, D., & Cheema, A. (2011). Earmarking and partitioning: Increasing saving by low-income households. Journal of Marketing Research, 48(SPL), S14–S22.", note: "Field experiments with low-income households: earmarking savings in a labelled, partitioned envelope raised saving, more so when the earmark was made visually salient.", link: doi("10.1509/jmkr.48.SPL.S14"), kind: "doi" },
      { cite: "Beshears, J., Choi, J. J., Laibson, D., Madrian, B. C., & Milkman, K. L. (2015). The effect of providing peer information on retirement savings decisions. The Journal of Finance, 70(3), 1161–1201.", note: "Field experiment showing that peer-information messages did not reliably raise saving and could discourage those far below the peer benchmark — a caution against comparison-based motivation.", link: doi("10.1111/jofi.12258"), kind: "doi" },
      { cite: "Mills, G., Gale, W. G., Patterson, R., Engelhardt, G. V., Eriksen, M. D., & Apostolov, E. (2008). Effects of individual development accounts on asset purchases and saving behavior: Evidence from a controlled experiment. Journal of Public Economics, 92(5-6), 1509–1530.", note: "Randomised evaluation of Individual Development Accounts (matched savings): the IDA raised homeownership among renters at baseline, with effects concentrated in that group.", link: doi("10.1016/j.jpubeco.2007.09.014"), kind: "doi" },
    ],
  },
  {
    id: "gs-home-credit-score",
    goal: "home", tier: "moderate", section: "8904",
    title: "Improve the Score With Information and On-Time Payments",
    subtitle: "See the score, pay on time, keep balances low — and be cautious with credit-builder products",
    evidenceTag: "Mixed",
    impact: { magnitude: 3, latency: "months", durability: "lasting", effort: "moderate" },
    feeds: ["mortgage pricing", "approval odds", "rate offers"],
    description:
      "A field experiment found that simply giving borrowers access to their FICO score reduced late payments and raised scores. A randomised test of a credit-builder loan found no average effect on credit scores: it helped people with no existing loans and hurt those juggling other debt who missed payments. Credit-marketing experiments show borrowers respond to framing more than to price, and rate-dispersion research shows credit profile drives mortgage price differences. The boundary: score effects are modest, the credit-builder evidence is one trial, and none of this substitutes for a lower balance and an unbroken payment history.",
    action: "Pull your full credit reports and score this week, dispute errors, set every account to autopay the minimum, pay revolving balances down before the statement date, and avoid opening new credit accounts in the six months before applying.",
    sources: [
      { cite: "Homonoff, T., O'Brien, R., & Sussman, A. B. (2021). Does knowing your FICO score change financial behavior? Evidence from a field experiment with student loan borrowers. The Review of Economics and Statistics, 103(2), 236–250.", note: "Randomised field experiment with student-loan borrowers: offering access to the FICO score reduced late payments and improved credit scores.", link: doi("10.1162/rest_a_00888"), kind: "doi" },
      { cite: "Burke, J., Jamison, J., Karlan, D., Mihaly, K., & Zinman, J. (2023). Credit building or credit crumbling? A credit builder loan's effects on consumer behavior and market efficiency in the United States. The Review of Financial Studies, 36(4), 1585–1620.", note: "Randomised trial of a credit-builder loan: no average effect on scores, with gains for those without existing loans and losses for those with other debts who missed payments.", link: doi("10.1093/rfs/hhac060"), kind: "doi" },
      { cite: "Bertrand, M., Karlan, D., Mullainathan, S., Shafir, E., & Zinman, J. (2010). What's advertising content worth? Evidence from a consumer credit marketing field experiment. Quarterly Journal of Economics, 125(1), 263–305.", note: "Consumer-credit marketing field experiment: psychological features of the offer moved take-up as much as sizeable interest-rate changes — a caution about how credit is sold.", link: doi("10.1162/qjec.2010.125.1.263"), kind: "doi" },
      { cite: "Bhutta, N., & Hizmo, A. (2021). Do minorities pay more for mortgages?. The Review of Financial Studies, 34(2), 763–789.", note: "Using detailed mortgage data, differences in interest rates and fees across borrowers were largely explained by credit and loan characteristics rather than race — the score is what prices the loan.", link: doi("10.1093/rfs/hhaa047"), kind: "doi" },
    ],
  },
  {
    id: "gs-home-counseling",
    goal: "home", tier: "moderate", section: "8905",
    title: "Take a Pre-Purchase Homebuyer Course — and Expect Modest Effects",
    subtitle: "HUD-approved education plus one-on-one counseling, with the numbers in hand",
    evidenceTag: "Mixed",
    impact: { magnitude: 2, latency: "months", durability: "sustained", effort: "moderate" },
    feeds: ["mortgage knowledge", "borrowing discipline", "default risk"],
    description:
      "Financial education has small effects on downstream behaviour in meta-analysis, and those effects decay; later meta-analytic work is more favourable, particularly for programmes tied to a specific decision. Studies of first-time homebuyers in a state programme found counseling and education associated with more conservative borrowing relative to capacity, and comparative work found state-subsidised low-income mortgage programmes produced better outcomes than private subprime alternatives. Foreclosure counseling for distressed owners improved cure rates. The boundary: much of the pre-purchase evidence is observational with self-selected participants.",
    action: "Before you sign a purchase agreement, complete a HUD-approved homebuyer education course and one individual counseling session, and bring your user-cost sheet and residual-income budget to the session for the counselor to stress-test.",
    sources: [
      { cite: "Collins, J. M., & O'Rourke, C. M. (2010). Financial education and counseling—Still holding promise. Journal of Consumer Affairs, 44(3), 483–498.", note: "Review of financial education and counseling evidence, concluding it still holds promise but that rigorous evaluations are scarce and effects modest.", link: doi("10.1111/j.1745-6606.2010.01179.x"), kind: "doi" },
      { cite: "Fernandes, D., Lynch, J. G., Jr., & Netemeyer, R. G. (2014). Financial literacy, financial education, and downstream financial behaviors. Management Science, 60(8), 1861–1883.", note: "Meta-analysis of the financial-literacy literature: financial education explained only a small share of variance in financial behaviour, with effects decaying over time.", link: doi("10.1287/mnsc.2013.1849"), kind: "doi" },
      { cite: "Kaiser, T., & Menkhoff, L. (2017). Does financial education impact financial literacy and financial behavior, and if so, when?. The World Bank Economic Review, 31(3), 611–630.", note: "Meta-analysis finding financial education does improve literacy and behaviour, with larger effects when programmes are intensive and tied to teachable moments.", link: doi("10.1093/wber/lhx018"), kind: "doi" },
      { cite: "Kaiser, T., & Menkhoff, L. (2020). Financial education in schools: A meta-analysis of experimental studies. Economics of Education Review, 78, 101930.", note: "Meta-analysis of experimental studies of school financial education finding positive effects on knowledge and behaviour.", link: doi("10.1016/j.econedurev.2019.101930"), kind: "doi" },
      { cite: "Moulton, S., Loibl, C., Samak, A., & Collins, J. M. (2013). Borrowing capacity and financial decisions of low-to-moderate income first-time homebuyers. Journal of Consumer Affairs, 47(3), 375–403.", note: "Low-to-moderate income first-time homebuyers in a state programme: those who borrowed well below their capacity showed better financial outcomes, and counseling related to more conservative borrowing.", link: doi("10.1111/joca.12021"), kind: "doi" },
      { cite: "Hembre, E., Moulton, S., & Record, M. (2021). Low-income homeownership and the role of state subsidies: A comparative analysis of mortgage outcomes. Journal of Policy Analysis and Management, 40(1), 78–106.", note: "Comparative analysis of mortgage outcomes showing that state-subsidised low-income homeownership programmes, which bundle education and underwriting, outperformed comparable private loans.", link: doi("10.1002/pam.22240"), kind: "doi" },
      { cite: "Collins, J. M., & Schmeiser, M. D. (2013). The effects of foreclosure counseling for distressed homeowners. Journal of Policy Analysis and Management, 32(1), 83–106.", note: "Distressed homeowners who received foreclosure counseling were more likely to cure their default and avoid foreclosure than comparable non-counseled borrowers.", link: doi("10.1002/pam.21670"), kind: "doi" },
    ],
  },
  {
    id: "gs-home-dpa",
    goal: "home", tier: "moderate", section: "8906",
    title: "Apply for Down-Payment Assistance and Matched Savings",
    subtitle: "State and local programs, IDAs and employer help — with eyes open about outcomes",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "months", durability: "lasting", effort: "moderate" },
    feeds: ["purchase timing", "cash reserve after closing", "sustainable ownership"],
    description:
      "A randomised evaluation of Individual Development Accounts (matched savings) raised homeownership among renters. Down-payment assistance recipients in a community-lending programme performed no worse on default than other borrowers once credit and loan characteristics were held constant, and state-subsidised programmes that pair assistance with underwriting produced better outcomes than private alternatives. Experimental evidence found the added ownership did not generate measurable social benefits. The boundary: assistance that pushes a household into a purchase above its residual-income floor is not help.",
    action: "Search your state housing finance agency and city for first-time-buyer assistance and matched-savings programmes this month, apply to every one you qualify for, and use the assistance to keep a post-closing cash reserve rather than to stretch to a bigger house.",
    sources: [
      { cite: "Freeman, A., & Harden, J. J. (2015). Affordable homeownership: The incidence and effect of down payment assistance. Housing Policy Debate, 25(2), 308–319.", note: "Analysed the incidence and effect of down-payment assistance in a community-lending programme, examining who received it and how assisted loans performed relative to unassisted ones.", link: doi("10.1080/10511482.2014.915226"), kind: "doi" },
      { cite: "Mills, G., Gale, W. G., Patterson, R., Engelhardt, G. V., Eriksen, M. D., & Apostolov, E. (2008). Effects of individual development accounts on asset purchases and saving behavior: Evidence from a controlled experiment. Journal of Public Economics, 92(5-6), 1509–1530.", note: "Controlled experiment of matched savings accounts: the IDA raised the homeownership rate of baseline renters.", link: doi("10.1016/j.jpubeco.2007.09.014"), kind: "doi" },
      { cite: "Engelhardt, G. V., Eriksen, M. D., Gale, W. G., & Mills, G. B. (2010). What are the social benefits of homeownership? Experimental evidence for low-income households. Journal of Urban Economics, 67(3), 249–258.", note: "Using the same experiment, the increase in homeownership produced no detectable gains in civic engagement, neighbourhood involvement or health — buy for the house, not the social halo.", link: doi("10.1016/j.jue.2009.09.010"), kind: "doi" },
      { cite: "Hembre, E., Moulton, S., & Record, M. (2021). Low-income homeownership and the role of state subsidies: A comparative analysis of mortgage outcomes. Journal of Policy Analysis and Management, 40(1), 78–106.", note: "State-subsidised low-income mortgage programmes outperformed private comparison loans on default and sustainability.", link: doi("10.1002/pam.22240"), kind: "doi" },
      { cite: "Grinstein-Weiss, M., Key, C., Guo, S., Yeo, Y. H., & Holub, K. (2013). Homeownership and wealth among low- and moderate-income households. Housing Policy Debate, 23(2), 259–279.", note: "Low- and moderate-income buyers in a community reinvestment programme accumulated more net wealth than comparable renters over the period studied, with gains concentrated in home equity.", link: doi("10.1080/10511482.2013.771786"), kind: "doi" },
    ],
  },
  {
    id: "gs-home-wealth-honest",
    goal: "home", tier: "moderate", section: "8907",
    title: "Treat Ownership as Forced Saving, Not a Return Engine",
    subtitle: "Equity comes mostly from amortisation and staying put; price gains are the bonus",
    evidenceTag: "Mixed",
    impact: { magnitude: 3, latency: "months", durability: "lasting", effort: "moderate" },
    feeds: ["wealth accumulation", "savings discipline", "expectations"],
    description:
      "Studies of homeownership and wealth find that owners accumulate more wealth than renters on average, that the gains for low-income owners are smaller and sensitive to purchase timing and the ability to stay in the home, and that a Swedish natural experiment identified gains from ownership partly through housing wealth and mobility. Long-run data show housing returns come largely from rental yield, and house-price rises change owners' saving behaviour. The boundary: leverage cuts both ways, transaction costs are large, and households that bought late in a boom lost wealth.",
    action: "Set a plan to hold for at least seven years, choose an amortising loan and treat the principal portion of each payment as your savings contribution; if you cannot commit to the hold, redirect the money to the down-payment account and keep renting.",
    sources: [
      { cite: "Turner, T. M., & Luea, H. (2009). Homeownership, wealth accumulation and income status. Journal of Housing Economics, 18(2), 104–114.", note: "Panel evidence that homeownership was associated with greater wealth accumulation across income groups, with lower-income owners gaining less.", link: doi("10.1016/j.jhe.2009.04.005"), kind: "doi" },
      { cite: "Di, Z. X., Belsky, E., & Liu, X. (2007). Do homeowners achieve more household wealth in the long run?. Journal of Housing Economics, 16(3-4), 274–290.", note: "Long-run panel analysis asking whether homeowners achieve more household wealth than renters; owners did, but the advantage depended on how long they stayed owners.", link: doi("10.1016/j.jhe.2007.08.001"), kind: "doi" },
      { cite: "Grinstein-Weiss, M., Key, C., Guo, S., Yeo, Y. H., & Holub, K. (2013). Homeownership and wealth among low- and moderate-income households. Housing Policy Debate, 23(2), 259–279.", note: "Low- and moderate-income buyers accumulated more net wealth than matched renters, with the gain concentrated in home equity.", link: doi("10.1080/10511482.2013.771786"), kind: "doi" },
      { cite: "Shlay, A. B. (2006). Low-income homeownership: American Dream or delusion?. Urban Studies, 43(3), 511–531.", note: "Critical review of low-income homeownership policy questioning whether the wealth and social benefits promised to low-income buyers are delivered.", link: doi("10.1080/00420980500452433"), kind: "doi" },
      { cite: "Sodini, P., Van Nieuwerburgh, S., Vestman, R., & von Lilienfeld-Toal, U. (2023). Identifying the benefits from homeownership: A Swedish experiment. American Economic Review, 113(12), 3173–3212.", note: "Swedish natural experiment identifying causal benefits of homeownership, including effects on wealth and labour-market mobility.", link: doi("10.1257/aer.20171449"), kind: "doi" },
      { cite: "Engelhardt, G. V. (1996). House prices and home owner saving behavior. Regional Science and Urban Economics, 26(3-4), 313–336.", note: "Household evidence that real house-price gains reduce owners' active saving — the equity windfall is partly consumed rather than added to wealth.", link: doi("10.1016/0166-0462(95)02118-3"), kind: "doi" },
      { cite: "Jordà, Ò., Knoll, K., Kuvshinov, D., Schularick, M., & Taylor, A. M. (2019). The rate of return on everything, 1870–2015. The Quarterly Journal of Economics, 134(3), 1225–1298.", note: "Long-run returns to housing came mainly from rental yield rather than capital gains.", link: doi("10.1093/qje/qjz012"), kind: "doi" },
      { cite: "Goodman, L. S., & Mayer, C. (2018). Homeownership and the American Dream. Journal of Economic Perspectives, 32(1), 31–58.", note: "Reviews when ownership builds wealth (long holds, sensible leverage) and when it destroys it (purchases at peaks, forced sales).", link: doi("10.1257/jep.32.1.31"), kind: "doi" },
    ],
  },
  {
    id: "gs-home-kids-myth",
    goal: "home", tier: "moderate", section: "8908",
    title: "Myth: Buy Because Ownership Makes Better Kids and Citizens",
    subtitle: "Homeownership as a proven cause of children's success and civic virtue",
    evidenceTag: "Mixed",
    impact: { magnitude: 1, latency: "months", durability: "transient", effort: "moderate" },
    callout: "Rated at the floor because the early correlations between ownership and children's outcomes largely disappear when studies account for who selects into buying, and the one experimental test found no social benefits from added ownership. Stability of residence and neighbourhood quality carry the effects, and they can be bought without a deed. Buy for the housing, not the halo.",
    description:
      "Early studies found children of homeowners stayed in school longer and had fewer behaviour problems, and that owners were more civically engaged. Subsequent work with richer controls and better designs attributed much of this to residential stability and to the kind of families who buy: one study found the child-outcome effects vanished with proper controls, another found little evidence of real effects versus self-selection, and the experimental evaluation of added ownership found no measurable civic or health benefits. Ownership does track lower mobility and more neighbourhood investment, which is the real, modest mechanism.",
    action: "Strike 'for the kids' from your reasons to buy. If stability for children is the goal, weigh a longer lease in a good school zone against buying, and let the affordability floor and user-cost sheet decide.",
    sources: [
      { cite: "Holupka, S., & Newman, S. J. (2012). The effects of homeownership on children's outcomes: Real effects or self-selection?. Real Estate Economics, 40(3), 566–602.", note: "Tested whether homeownership's association with children's outcomes reflects real effects or self-selection; with appropriate methods the evidence for causal effects was limited.", link: doi("10.1111/j.1540-6229.2012.00330.x"), kind: "doi" },
      { cite: "Barker, D., & Miller, E. (2009). Homeownership and child welfare. Real Estate Economics, 37(2), 279–303.", note: "Re-examined the ownership and child-welfare link with additional controls and found the apparent effects largely disappeared.", link: doi("10.1111/j.1540-6229.2009.00243.x"), kind: "doi" },
      { cite: "Engelhardt, G. V., Eriksen, M. D., Gale, W. G., & Mills, G. B. (2010). What are the social benefits of homeownership? Experimental evidence for low-income households. Journal of Urban Economics, 67(3), 249–258.", note: "Experimental evidence: the increase in homeownership generated by matched savings produced no detectable social benefits for low-income households.", link: doi("10.1016/j.jue.2009.09.010"), kind: "doi" },
      { cite: "Haurin, D. R., Parcel, T. L., & Haurin, R. J. (2002). Does homeownership affect child outcomes?. Real Estate Economics, 30(4), 635–666.", note: "Earlier panel study reporting positive associations between ownership and children's cognitive and behavioural outcomes — the finding later work qualified.", link: doi("10.1111/1540-6229.t01-2-00053"), kind: "doi" },
      { cite: "Green, R. K., & White, M. J. (1997). Measuring the benefits of homeowning: Effects on children. Journal of Urban Economics, 41(3), 441–461.", note: "Early study finding children of homeowners more likely to stay in school and less likely to have teen births, with limited controls for selection.", link: doi("10.1006/juec.1996.2010"), kind: "doi" },
      { cite: "Aaronson, D. (2000). A note on the benefits of homeownership. Journal of Urban Economics, 47(3), 356–369.", note: "Showed that much of the apparent child benefit of ownership operates through residential stability rather than ownership itself.", link: doi("10.1006/juec.1999.2144"), kind: "doi" },
      { cite: "DiPasquale, D., & Glaeser, E. L. (1999). Incentives and social capital: Are homeowners better citizens?. Journal of Urban Economics, 45(2), 354–384.", note: "Homeowners were more likely to invest in local amenities and civic life, partly because ownership lowers mobility — the mechanism is staying put.", link: doi("10.1006/juec.1998.2098"), kind: "doi" },
      { cite: "Manturuk, K., Lindblad, M., & Quercia, R. (2012). Homeownership and civic engagement in low-income urban neighborhoods. Urban Affairs Review, 48(5), 731–760.", note: "In low-income urban neighbourhoods, ownership was associated with civic engagement through neighbourhood attachment and stability.", link: doi("10.1177/1078087412441772"), kind: "doi" },
    ],
  },
  {
    id: "gs-home-mortgage-choice",
    goal: "home", tier: "advanced", section: "8909",
    title: "Choose the Mortgage for Your Risk, Not the Headline Rate",
    subtitle: "Fixed-rate as the default for borrowing-constrained, income-volatile households; ARM only with a buffer",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "months", durability: "lasting", effort: "moderate" },
    feeds: ["payment stability", "default risk", "refinancing option value"],
    description:
      "Household-finance theory shows the fixed-rate mortgage protects a household from real-rate risk but exposes it to inflation risk, while the adjustable-rate mortgage is attractive to households with stable income, small houses relative to income and a taste for the lower expected cost. Empirical work finds households do use the term-structure premium in choosing between the two, and that international ARM take-up tracks short-term rates. Models of default show that mortgage structure affects who defaults in a downturn. The boundary: the right answer depends on income stability, buffer savings and time horizon, and the literature is explicit that it varies by household.",
    action: "List your income volatility, liquid reserves and expected stay; default to a fixed-rate loan unless you have a six-month reserve, stable income and plan to move within the initial fixed period of an ARM — and read the rate-reset terms before signing.",
    sources: [
      { cite: "Campbell, J. Y., & Cocco, J. F. (2003). Household risk management and optimal mortgage choice. The Quarterly Journal of Economics, 118(4), 1449–1494.", note: "Life-cycle model of mortgage choice: fixed-rate loans suit borrowing-constrained households with volatile income and large mortgages; ARMs suit those with stable income and smaller loans.", link: doi("10.1162/003355303322552847"), kind: "doi" },
      { cite: "Campbell, J. Y. (2006). Household finance. The Journal of Finance, 61(4), 1553–1604.", note: "Household finance review documenting that mortgage choice and refinancing are among the decisions where households make costly mistakes.", link: doi("10.1111/j.1540-6261.2006.00883.x"), kind: "doi" },
      { cite: "Koijen, R. S. J., Van Hemert, O., & Van Nieuwerburgh, S. (2009). Mortgage timing. Journal of Financial Economics, 93(2), 292–324.", note: "Households' choice between fixed and adjustable rates tracks the long-term bond risk premium — a simple rule that captures most of the timing decision.", link: doi("10.1016/j.jfineco.2008.09.005"), kind: "doi" },
      { cite: "Badarinza, C., Campbell, J. Y., & Ramadorai, T. (2018). What calls to ARMs? International evidence on interest rates and the choice of adjustable-rate mortgages. Management Science, 64(5), 2275–2288.", note: "Across countries, the share of adjustable-rate mortgages rises with the gap between fixed and short rates — households respond to the near-term cost difference.", link: doi("10.1287/mnsc.2016.2629"), kind: "doi" },
      { cite: "Dhillon, U. S., Shilling, J. D., & Sirmans, C. F. (1987). Choosing between fixed and adjustable rate mortgages: Note. Journal of Money, Credit and Banking, 19(2), 260–267.", note: "Early empirical evidence on which borrower characteristics predict the choice between fixed and adjustable rates.", link: doi("10.2307/1992281"), kind: "doi" },
      { cite: "Campbell, J. Y., & Cocco, J. F. (2015). A model of mortgage default. The Journal of Finance, 70(4), 1495–1554.", note: "Model of mortgage default showing how negative equity and cash-flow shocks interact and how mortgage structure changes default incidence.", link: doi("10.1111/jofi.12252"), kind: "doi" },
      { cite: "Campbell, J. Y., Clara, N., & Cocco, J. F. (2021). Structuring mortgages for macroeconomic stability. The Journal of Finance, 76(5), 2525–2576.", note: "Analyses how mortgage design affects household and macroeconomic stability, comparing fixed and adjustable structures under stress.", link: doi("10.1111/jofi.13056"), kind: "doi" },
    ],
  },
  {
    id: "gs-home-shop-mortgage",
    goal: "home", tier: "advanced", section: "8910",
    title: "Get Several Written Quotes on the Same Day",
    subtitle: "Rate dispersion is large; shopping effort is the lever",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "weeks", durability: "lasting", effort: "moderate" },
    feeds: ["lifetime interest cost", "closing costs", "bargaining position"],
    description:
      "Mortgage-market evidence shows large dispersion in the rates and fees charged to otherwise identical borrowers, with borrowers who shop less and understand pricing less paying substantially more, and confusion about points and fees exploited by intermediaries. Recent work finds that less financially sophisticated borrowers overpay in ways that shopping would reduce, and that rate differences are largely explained by borrower and loan characteristics rather than group identity. The boundary: quotes must be same-day and like-for-like on points and lock terms, or the comparison is meaningless.",
    action: "On one day, request written loan estimates from at least three lenders for the same loan amount, term and points, compare the APR and total closing costs line by line, and use the best offer to negotiate with the others before locking.",
    sources: [
      { cite: "Woodward, S. E., & Hall, R. E. (2012). Diagnosing consumer confusion and sub-optimal shopping effort: Theory and mortgage-market evidence. American Economic Review, 102(7), 3249–3276.", note: "Theory and evidence that confusion over points and fees and sub-optimal shopping effort left mortgage borrowers paying more than necessary.", link: doi("10.1257/aer.102.7.3249"), kind: "doi" },
      { cite: "Bhutta, N., Fuster, A., & Hizmo, A. (2026). Paying too much? Borrower sophistication and overpayment in the U.S. mortgage market. The Journal of Finance, 81(1), 49–90.", note: "Less sophisticated borrowers pay more for the same mortgage, and rate dispersion across lenders means shopping materially changes what a borrower pays.", link: doi("10.1111/jofi.70001"), kind: "doi" },
      { cite: "Bhutta, N., & Hizmo, A. (2021). Do minorities pay more for mortgages?. The Review of Financial Studies, 34(2), 763–789.", note: "Detailed pricing data show mortgage rate and fee differences are largely explained by credit and loan features — the terms of the loan you bring to the table drive the price.", link: doi("10.1093/rfs/hhaa047"), kind: "doi" },
      { cite: "Agarwal, S., Rosen, R. J., & Yao, V. (2016). Why do borrowers make mortgage refinancing mistakes?. Management Science, 62(12), 3494–3509.", note: "Borrowers make systematic mistakes in mortgage decisions, including timing and terms, with costs concentrated among less financially literate households.", link: doi("10.1287/mnsc.2015.2272"), kind: "doi" },
      { cite: "Andersen, S., Campbell, J. Y., Nielsen, K. M., & Ramadorai, T. (2020). Sources of inaction in household finance: Evidence from the Danish mortgage market. American Economic Review, 110(10), 3184–3230.", note: "Danish administrative data attribute much of households' failure to act on mortgage savings to inattention and inertia rather than costs — a nudge to act deliberately.", link: doi("10.1257/aer.20180865"), kind: "doi" },
    ],
  },
  {
    id: "gs-home-refinance-rule",
    goal: "home", tier: "moderate", section: "8911",
    title: "Write a Refinancing Rule Now",
    subtitle: "A rate-gap threshold and a calendar check, so inertia does not cost you",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "months", durability: "lasting", effort: "low" },
    feeds: ["lifetime interest cost", "payment flexibility"],
    description:
      "A closed-form solution gives the rate drop at which refinancing pays given closing costs and expected tenure, and empirical work shows large numbers of households fail to refinance when it would save them substantial sums, or refinance at the wrong time. Danish administrative data attribute most of the inaction to inattention and psychological inertia rather than to rational costs. The boundary: refinancing resets the amortisation clock and adds costs, so the threshold must include closing costs and how long you will keep the loan.",
    action: "Compute your break-even rate gap today (closing costs divided by monthly savings, compared with expected years in the home), write the trigger rate on your calendar, and check current rates on the first of every quarter.",
    sources: [
      { cite: "Agarwal, S., Driscoll, J. C., & Laibson, D. I. (2013). Optimal mortgage refinancing: A closed-form solution. Journal of Money, Credit and Banking, 45(4), 591–622.", note: "Derives a closed-form rule for the interest-rate differential at which refinancing is optimal, given costs, tenure and rate volatility.", link: doi("10.1111/jmcb.12017"), kind: "doi" },
      { cite: "Keys, B. J., Pope, D. G., & Pope, J. C. (2016). Failure to refinance. Journal of Financial Economics, 122(3), 482–499.", note: "Documented a large share of US households that failed to refinance despite substantial available savings.", link: doi("10.1016/j.jfineco.2016.01.031"), kind: "doi" },
      { cite: "Andersen, S., Campbell, J. Y., Nielsen, K. M., & Ramadorai, T. (2020). Sources of inaction in household finance: Evidence from the Danish mortgage market. American Economic Review, 110(10), 3184–3230.", note: "Sources of inaction in the Danish mortgage market: inattention and inertia, not rational costs, explain most failures to refinance.", link: doi("10.1257/aer.20180865"), kind: "doi" },
      { cite: "Agarwal, S., Rosen, R. J., & Yao, V. (2016). Why do borrowers make mortgage refinancing mistakes?. Management Science, 62(12), 3494–3509.", note: "Identified the kinds of refinancing mistakes borrowers make — refinancing too early, too late or not at all — and who makes them.", link: doi("10.1287/mnsc.2015.2272"), kind: "doi" },
    ],
  },
  {
    id: "gs-home-timing-myth",
    goal: "home", tier: "advanced", section: "8912",
    title: "Myth: Wait for the Bottom in Prices and Rates",
    subtitle: "Timing the purchase to the trough as a strategy",
    evidenceTag: "Mixed",
    impact: { magnitude: 1, latency: "months", durability: "transient", effort: "moderate" },
    callout: "Rated at the floor because homebuyers' expectations are extrapolative and systematically wrong at turning points, short-run momentum in prices does not tell an individual when the bottom is, and the rate you lock can be refinanced later. Buy when the user-cost sheet, the affordability floor and your horizon line up, and use the refinancing rule for the rate.",
    description:
      "House prices show momentum in the short run and mean reversion in the long run, which sounds exploitable but is not for a household that needs a home: buyers' surveys show expectations that extrapolate recent trends, and models built on those extrapolative beliefs reproduce booms and busts. Supply conditions determine which markets bubble. None of this identifies the trough in real time, and the refinancing evidence shows the mortgage rate is not a one-time decision.",
    action: "Stop waiting for a bottom. Decide by the user-cost comparison, the residual-income floor and a seven-year-plus horizon; if rates fall after you buy, apply the refinancing rule.",
    sources: [
      { cite: "Case, K. E., & Shiller, R. J. (1990). Forecasting prices and excess returns in the housing market. Real Estate Economics, 18(3), 253–273.", note: "Case and Shiller found house prices and excess returns partly forecastable — momentum in the short run — which fuels timing attempts without telling anyone when a turn comes.", link: doi("10.1111/1540-6229.00521"), kind: "doi" },
      { cite: "Glaeser, E. L., & Nathanson, C. G. (2017). An extrapolative model of house price dynamics. Journal of Financial Economics, 126(1), 147–170.", note: "Model in which buyers extrapolate past price growth reproduces observed booms and busts; extrapolation is the error, not the edge.", link: doi("10.1016/j.jfineco.2017.06.012"), kind: "doi" },
      { cite: "Piazzesi, M., & Schneider, M. (2009). Momentum traders in the housing market: Survey evidence and a search model. American Economic Review, 99(2), 406–411.", note: "Survey evidence that a meaningful share of buyers in the boom were momentum traders expecting continued price gains.", link: doi("10.1257/aer.99.2.406"), kind: "doi" },
      { cite: "Case, K. E., Shiller, R. J., & Thompson, A. K. (2012). What have they been thinking? Homebuyer behavior in hot and cold markets. Brookings Papers on Economic Activity, 2012(1), 265–315.", note: "Homebuyer surveys in hot and cold markets: expectations of future appreciation tracked recent experience and were far off at turning points.", link: doi("10.1353/eca.2012.0014"), kind: "doi" },
      { cite: "Glaeser, E. L., Gyourko, J., & Saiz, A. (2008). Housing supply and housing bubbles. Journal of Urban Economics, 64(2), 198–217.", note: "Housing bubbles are larger and more frequent where supply is inelastic — the market you are in matters more than the calendar.", link: doi("10.1016/j.jue.2008.07.007"), kind: "doi" },
      { cite: "Keys, B. J., Pope, D. G., & Pope, J. C. (2016). Failure to refinance. Journal of Financial Economics, 122(3), 482–499.", note: "The rate you lock is not permanent: households who failed to refinance left substantial savings on the table, and those who act can capture later rate declines.", link: doi("10.1016/j.jfineco.2016.01.031"), kind: "doi" },
    ],
  },
  {
    id: "gs-home-commute",
    goal: "home", tier: "advanced", section: "8913",
    title: "Price the Commute Into the Location Decision",
    subtitle: "Every extra minute each way is a daily cost to wellbeing that the house price does not show",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "months", durability: "lasting", effort: "moderate" },
    feeds: ["daily mood", "mental health", "time with family"],
    description:
      "Commuting is among the least pleasant daily activities in experience-sampling research, and longer commutes are associated with lower life satisfaction in a way that pay and housing do not fully compensate — the 'commuting paradox'. Reviews find longer commutes reduce wellbeing, with the mode mattering: active and public-transport commuting are associated with better psychological wellbeing than driving in panel data, and maintaining a cycle commute tracked better mental wellbeing and fewer sick days. A 13-wave Australian cohort found more than six hours a week of commuting associated with a small decline in mental health, larger under low job control. The boundary: effects are small per person and larger for those with low job control.",
    action: "For each candidate home, measure the real door-to-door commute at your actual departure time, in both directions, and rule out any option that adds more than 30 minutes a day over your current commute unless you can do it on foot, by bike or by train.",
    sources: [
      { cite: "Stutzer, A., & Frey, B. S. (2008). Stress that doesn't pay: The commuting paradox. The Scandinavian Journal of Economics, 110(2), 339–366.", note: "German panel data: people with longer commutes report systematically lower life satisfaction, and the compensation they receive does not offset it.", link: doi("10.1111/j.1467-9442.2008.00542.x"), kind: "doi" },
      { cite: "Kahneman, D., Krueger, A. B., Schkade, D. A., Schwarz, N., & Stone, A. A. (2004). A survey method for characterizing daily life experience: The Day Reconstruction Method. Science, 306(5702), 1776–1780.", note: "Day Reconstruction Method study of daily experience in which commuting ranked among the least enjoyable activities of the day.", link: doi("10.1126/science.1103572"), kind: "doi" },
      { cite: "Chatterjee, K., Chng, S., Clark, B., Davis, A., De Vos, J., Ettema, D., & … Reardon, L. (2020). Commuting and wellbeing: A critical overview of the literature with implications for policy and future research. Transport Reviews, 40(1), 5–34.", note: "Critical overview of the commuting and wellbeing literature: longer commutes reduce satisfaction and wellbeing, moderated by mode and circumstances.", link: doi("10.1080/01441647.2019.1649317"), kind: "doi" },
      { cite: "Clark, B., Chatterjee, K., Martin, A., & Davis, A. (2020). How commuting affects subjective wellbeing. Transportation, 47(6), 2777–2805.", note: "UK panel analysis showing how commute duration and mode affect subjective wellbeing, including job and leisure-time satisfaction.", link: doi("10.1007/s11116-019-09983-9"), kind: "doi" },
      { cite: "Milner, A., Badland, H., Kavanagh, A., & LaMontagne, A. D. (2017). Time spent commuting to work and mental health: Evidence from 13 waves of an Australian cohort study. American Journal of Epidemiology, 186(6), 659–667.", note: "13 waves of Australian panel data: commuting more than six hours a week was associated with a small decline in mental health, larger for workers with low job control.", link: doi("10.1093/aje/kww243"), kind: "doi" },
      { cite: "Martin, A., Goryakin, Y., & Suhrcke, M. (2014). Does active commuting improve psychological wellbeing? Longitudinal evidence from eighteen waves of the British Household Panel Survey. Preventive Medicine, 69, 296–303.", note: "Eighteen waves of the British Household Panel Survey: switching from driving to active travel and using public transport were associated with better psychological wellbeing.", link: doi("10.1016/j.ypmed.2014.08.023"), kind: "doi" },
      { cite: "Mytton, O. T., Panter, J., & Ogilvie, D. (2016). Longitudinal associations of active commuting with wellbeing and sickness absence. Preventive Medicine, 84, 19–26.", note: "Cambridge cohort: maintaining a cycle commute was associated with better mental wellbeing and about one fewer sick day a year.", link: doi("10.1016/j.ypmed.2015.12.010"), kind: "doi" },
    ],
  },
  {
    id: "gs-home-neighborhood",
    goal: "home", tier: "elite", section: "8914",
    title: "Buy Neighborhood Opportunity, Especially With Young Children",
    subtitle: "Use the childhood-exposure evidence to weight schools, poverty rate and upward mobility above square footage",
    evidenceTag: "Strong",
    impact: { magnitude: 5, latency: "months", durability: "lasting", effort: "high" },
    feeds: ["children's adult earnings", "family health", "long-run mobility"],
    description:
      "The Moving to Opportunity experiment randomised low-income families to housing vouchers usable in low-poverty neighbourhoods. Children who moved when young earned more as adults and were more likely to attend college; adults showed long-run gains in physical and mental health and subjective wellbeing, and lower rates of extreme obesity and diabetes, though not in earnings. Quasi-experimental work shows neighbourhood effects on children's later incomes accumulate with each year of exposure, and a later experiment showed that light-touch help moves families to high-opportunity areas. The boundary: these are effects of leaving high-poverty neighbourhoods for lower-poverty ones; the marginal return to a slightly 'better' suburb is much less clear.",
    action: "Before choosing between homes, look up each neighbourhood's child poverty rate, school quality and published upward-mobility estimates; with children under ten, give a smaller home in a higher-opportunity neighbourhood priority over a larger home in a weaker one.",
    sources: [
      { cite: "Chetty, R., Hendren, N., & Katz, L. F. (2016). The effects of exposure to better neighborhoods on children: New evidence from the Moving to Opportunity experiment. American Economic Review, 106(4), 855–902.", note: "Children who moved to lower-poverty neighbourhoods when young through Moving to Opportunity had better adult outcomes, including earnings, and the gains declined with age at move.", link: doi("10.1257/aer.20150572"), kind: "doi" },
      { cite: "Chetty, R., & Hendren, N. (2018). The impacts of neighborhoods on intergenerational mobility I: Childhood exposure effects. The Quarterly Journal of Economics, 133(3), 1107–1162.", note: "Quasi-experimental evidence that neighbourhoods' effects on children's adult incomes accumulate with each year of childhood exposure.", link: doi("10.1093/qje/qjy007"), kind: "doi" },
      { cite: "Kling, J. R., Liebman, J. B., & Katz, L. F. (2007). Experimental analysis of neighborhood effects. Econometrica, 75(1), 83–119.", note: "Experimental analysis of Moving to Opportunity finding improvements in adult mental health and mixed effects for youth, with no detectable effects on adult earnings.", link: doi("10.1111/j.1468-0262.2007.00733.x"), kind: "doi" },
      { cite: "Ludwig, J., Duncan, G. J., Gennetian, L. A., Katz, L. F., Kessler, R. C., Kling, J. R., & Sanbonmatsu, L. (2012). Neighborhood effects on the long-term well-being of low-income adults. Science, 337(6101), 1505–1510.", note: "Long-term MTO follow-up: moving to a lower-poverty neighbourhood improved adult physical and mental health and subjective wellbeing; a 13-point drop in neighbourhood poverty was worth about $13,000 of income in wellbeing terms.", link: doi("10.1126/science.1224648"), kind: "doi" },
      { cite: "Ludwig, J., Sanbonmatsu, L., Gennetian, L., Adam, E., Duncan, G. J., Katz, L. F., & … McDade, T. W. (2011). Neighborhoods, obesity, and diabetes — a randomized social experiment. New England Journal of Medicine, 365(16), 1509–1519.", note: "Randomised social experiment: the low-poverty voucher group had lower prevalence of extreme obesity and diabetes than controls 10–15 years later, by roughly 3–5 percentage points.", link: doi("10.1056/NEJMsa1103216"), kind: "doi" },
      { cite: "Bergman, P., Chetty, R., DeLuca, S., Hendren, N., Katz, L. F., & Palmer, C. (2024). Creating Moves to Opportunity: Experimental evidence on barriers to neighborhood choice. American Economic Review, 114(5), 1281–1337.", note: "Creating Moves to Opportunity: customised search assistance and landlord engagement sharply raised the share of voucher families moving to high-opportunity neighbourhoods.", link: doi("10.1257/aer.20200407"), kind: "doi" },
      { cite: "Pollack, C. E., Bozzi, D. G., Blackford, A. L., DeLuca, S., Thornton, R., & Herring, B. (2023). Using the Moving To Opportunity experiment to investigate the long-term impact of neighborhoods on healthcare use by specific clinical conditions and type of service. Housing Policy Debate, 33(1), 269–289.", note: "MTO linked to 21 years of hospital data: children in the voucher group had 36% lower hospital admission rates for asthma and 30% lower for mental health disorders.", link: doi("10.1080/10511482.2021.1951804"), kind: "doi" },
      { cite: "Sampson, R. J., Morenoff, J. D., & Gannon-Rowley, T. (2002). Assessing \"neighborhood effects\": Social processes and new directions in research. Annual Review of Sociology, 28(1), 443–478.", note: "Review of neighbourhood-effects research identifying the social processes — collective efficacy, institutions, disorder — through which places shape outcomes.", link: doi("10.1146/annurev.soc.28.110601.141114"), kind: "doi" },
    ],
  },
  {
    id: "gs-home-negotiation",
    goal: "home", tier: "moderate", section: "8915",
    title: "Set Your Own Anchor and Know the Seller's",
    subtitle: "Prepare a written valuation before you see the list price, and make the first offer when you can",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "weeks", durability: "transient", effort: "low" },
    feeds: ["purchase price", "negotiation composure"],
    description:
      "Experiments with real houses and real-estate agents found that an arbitrary listing price shifted both amateurs' and experts' valuations — the anchoring effect — and that experts denied being influenced. First offers act as anchors in negotiation, favouring the party who makes them, unless the other side focuses on its own target. Transaction data show that sellers who face a loss relative to their purchase price set higher asking prices and wait longer to sell, and that list-price anchoring affects final sale prices. The boundary: in a competitive market the anchor is the market, and an aggressive first offer can end the conversation.",
    action: "Before viewing, write down your own valuation from three recent comparable sales and your walk-away price; when negotiating, lead with a justified first offer where the market allows, and check whether the seller bought at a higher price — a loss-averse seller will hold out longer.",
    sources: [
      { cite: "Northcraft, G. B., & Neale, M. A. (1987). Experts, amateurs, and real estate: An anchoring-and-adjustment perspective on property pricing decisions. Organizational Behavior and Human Decision Processes, 39(1), 84–97.", note: "Classic experiment: manipulated listing prices for a real house shifted the valuations of both amateurs and real-estate agents, who denied being influenced.", link: doi("10.1016/0749-5978(87)90046-X"), kind: "doi" },
      { cite: "Galinsky, A. D., & Mussweiler, T. (2001). First offers as anchors: The role of perspective-taking and negotiator focus. Journal of Personality and Social Psychology, 81(4), 657–669.", note: "Experiments showing first offers anchor negotiation outcomes in favour of the party making them, and that focusing on one's own target counters the effect.", link: doi("10.1037/0022-3514.81.4.657"), kind: "doi" },
      { cite: "Bucchianeri, G. W., & Minson, J. A. (2013). A homeowner's dilemma: Anchoring in residential real estate transactions. Journal of Economic Behavior & Organization, 89, 76–92.", note: "Residential transaction data show list-price anchoring: higher listing prices relative to expected value were associated with higher final sale prices, at the cost of longer time on market.", link: doi("10.1016/j.jebo.2013.01.010"), kind: "doi" },
      { cite: "Genesove, D., & Mayer, C. (2001). Loss aversion and seller behavior: Evidence from the housing market. The Quarterly Journal of Economics, 116(4), 1233–1260.", note: "Transaction data: sellers facing a nominal loss set asking prices well above expected value and took longer to sell — loss aversion in practice.", link: doi("10.1162/003355301753265561"), kind: "doi" },
    ],
  },
  {
    id: "gs-home-default-risk",
    goal: "home", tier: "advanced", section: "8916",
    title: "Underwrite Yourself Against the Double Trigger",
    subtitle: "Default happens when negative equity meets a cash-flow shock — plan for both",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "months", durability: "lasting", effort: "moderate" },
    feeds: ["financial resilience", "health protection", "credit preservation"],
    description:
      "Mortgage default research converges on a 'double trigger': negative equity alone rarely causes default, and most households with negative equity keep paying; default rises sharply when negative equity coincides with job loss, illness or another liquidity shock. Illiquidity and credit-score deterioration predict default beyond home equity, and the subprime crisis showed how loan quality deteriorated as underwriting loosened. Health shocks raise the risk of default, and mortgage delinquency in turn is associated with a surge in depressive symptoms and food insecurity. The boundary: the default studies are from the 2007–2012 bust and its aftermath.",
    action: "Before closing, confirm you will hold a cash reserve equal to at least six months of the full housing payment after the down payment, keep a down payment large enough that a moderate price fall does not put you underwater, and buy disability and adequate health coverage — the two shocks that trigger default.",
    sources: [
      { cite: "Foote, C. L., Gerardi, K., & Willen, P. S. (2008). Negative equity and foreclosure: Theory and evidence. Journal of Urban Economics, 64(2), 234–245.", note: "Loan-level data: most owners with negative equity did not default; default required negative equity plus an adverse cash-flow shock.", link: doi("10.1016/j.jue.2008.07.006"), kind: "doi" },
      { cite: "Gerardi, K., Herkenhoff, K. F., Ohanian, L. E., & Willen, P. S. (2018). Can't pay or won't pay? Unemployment, negative equity, and strategic default. The Review of Financial Studies, 31(3), 1098–1131.", note: "Panel data on households' finances: unemployment and other liquidity shocks, together with negative equity, drive the great majority of defaults; purely strategic default is rare.", link: doi("10.1093/rfs/hhx115"), kind: "doi" },
      { cite: "Elul, R., Souleles, N. S., Chomsisengphet, S., Glennon, D., & Hunt, R. (2010). What \"triggers\" mortgage default?. American Economic Review, 100(2), 490–494.", note: "Illiquidity — high credit-card utilisation and low available credit — predicted mortgage default beyond negative equity.", link: doi("10.1257/aer.100.2.490"), kind: "doi" },
      { cite: "Mayer, C., Pence, K., & Sherlund, S. M. (2009). The rise in mortgage defaults. Journal of Economic Perspectives, 23(1), 27–50.", note: "Documents the rise in defaults through 2008, driven by falling prices interacting with weak underwriting and risky loan products.", link: doi("10.1257/jep.23.1.27"), kind: "doi" },
      { cite: "Demyanyk, Y., & Van Hemert, O. (2011). Understanding the subprime mortgage crisis. Review of Financial Studies, 24(6), 1848–1880.", note: "Loan-level analysis showing subprime loan quality deteriorated year over year as underwriting loosened, while prices masked the risk until they fell.", link: doi("10.1093/rfs/hhp033"), kind: "doi" },
      { cite: "Campbell, J. Y., & Cocco, J. F. (2015). A model of mortgage default. The Journal of Finance, 70(4), 1495–1554.", note: "Model showing how mortgage design, negative equity and cash-flow shocks jointly determine who defaults.", link: doi("10.1111/jofi.12252"), kind: "doi" },
      { cite: "Houle, J. N., & Keene, D. E. (2015). Getting sick and falling behind: Health and the risk of mortgage default and home foreclosure. Journal of Epidemiology and Community Health, 69(4), 382–387.", note: "NLSY79 data: new health limitations and chronic conditions raised the risk of mortgage default and foreclosure between 2007 and 2010, partly through income and insurance loss.", link: doi("10.1136/jech-2014-204637"), kind: "doi" },
      { cite: "Alley, D. E., Lloyd, J., Pagán, J. A., Pollack, C. E., Shardell, M., & Cannuscio, C. (2011). Mortgage delinquency and changes in access to health resources and depressive symptoms in a nationally representative cohort of Americans older than 50 years. American Journal of Public Health, 101(12), 2293–2298.", note: "Health and Retirement Study: adults over 50 who fell behind on their mortgage were far more likely to develop depressive symptoms, food insecurity and cost-related medication non-adherence over two years.", link: doi("10.2105/AJPH.2011.300245"), kind: "doi" },
    ],
  },
  {
    id: "gs-home-foreclosure-prevention",
    goal: "home", tier: "elite", section: "8917",
    title: "If Trouble Comes, Act on Liquidity Within the First Missed Payment",
    subtitle: "Payment reduction beats principal reduction; call a HUD-approved counselor before the second missed payment",
    evidenceTag: "Strong",
    impact: { magnitude: 5, latency: "weeks", durability: "lasting", effort: "high" },
    feeds: ["home retention", "credit preservation", "mental health"],
    description:
      "Evidence from the Great Recession's modification programmes shows that reducing monthly payments cut default and raised consumption, while principal reductions that left payments unchanged did little — liquidity, not wealth, was the binding constraint. HAMP modifications reduced foreclosures, though lender capacity limited take-up, and a settlement offering modifications induced some strategic delinquency. Foreclosure counseling improved cure rates. Foreclosure exposure is associated with the onset of depression in older adults and with severe depressive symptoms in new mothers. The boundary: outcomes depend on the servicer and the programme available, and every month of delay narrows options.",
    action: "If you miss or expect to miss a payment, call a HUD-approved housing counselor and your servicer within 30 days, ask specifically for options that reduce the monthly payment, and keep written records of every contact.",
    sources: [
      { cite: "Ganong, P., & Noel, P. (2020). Liquidity versus wealth in household debt obligations: Evidence from housing policy in the Great Recession. American Economic Review, 110(10), 3100–3138.", note: "Quasi-experimental evidence that reducing mortgage payments lowered default and increased consumption, whereas principal reduction without payment change had little effect.", link: doi("10.1257/aer.20181243"), kind: "doi" },
      { cite: "Agarwal, S., Amromin, G., Ben-David, I., Chomsisengphet, S., Piskorski, T., & Seru, A. (2017). Policy intervention in debt renegotiation: Evidence from the Home Affordable Modification Program. Journal of Political Economy, 125(3), 654–712.", note: "Evaluation of HAMP: the programme reduced foreclosures and raised modification rates, with effects limited by servicers' capacity to process modifications.", link: doi("10.1086/691701"), kind: "doi" },
      { cite: "Mayer, C., Morrison, E., Piskorski, T., & Gupta, A. (2014). Mortgage modification and strategic behavior: Evidence from a legal settlement with Countrywide. American Economic Review, 104(9), 2830–2857.", note: "A publicised settlement offering modifications to delinquent borrowers led some current borrowers to become delinquent to qualify — modification design shapes behaviour.", link: doi("10.1257/aer.104.9.2830"), kind: "doi" },
      { cite: "Collins, J. M., & Schmeiser, M. D. (2013). The effects of foreclosure counseling for distressed homeowners. Journal of Policy Analysis and Management, 32(1), 83–106.", note: "Distressed homeowners who received foreclosure counseling were more likely to cure their default and less likely to lose the home.", link: doi("10.1002/pam.21670"), kind: "doi" },
      { cite: "Cagney, K. A., Browning, C. R., Iveniuk, J., & English, N. (2014). The onset of depression during the Great Recession: Foreclosure and older adult mental health. American Journal of Public Health, 104(3), 498–505.", note: "Nationally representative older adults: large increases in neighbourhood foreclosure notices were associated with the onset of depressive symptoms (OR 1.75).", link: doi("10.2105/AJPH.2013.301566"), kind: "doi" },
      { cite: "Osypuk, T. L., Caldwell, C. H., Platt, R. W., & Misra, D. P. (2012). The consequences of foreclosure for depressive symptomatology. Annals of Epidemiology, 22(6), 379–387.", note: "Cohort of 662 new mothers: recent foreclosure carried 1.76 times the risk of severe depressive symptoms.", link: doi("10.1016/j.annepidem.2012.04.012"), kind: "doi" },
    ],
  },
  {
    id: "gs-home-ownership-system",
    goal: "home", tier: "elite", section: "8918",
    title: "Build the Whole Ownership System Before You Buy",
    subtitle: "Down payment, fixed cost, reserve, horizon and neighbourhood — decided together, then executed",
    evidenceTag: "Strong",
    impact: { magnitude: 5, latency: "months", durability: "lasting", effort: "high" },
    feeds: ["sustainable ownership", "wealth building", "family stability"],
    description:
      "Each earlier protocol answers one question; the households that ownership rewards answer all of them at once. The economics says: buy when the user cost and horizon favour it, keep housing costs under a residual-income floor, hold long enough for amortisation and rent hedging to work, structure the loan to your income risk, keep the liquidity that prevents a double-trigger default, and choose the neighbourhood with the children's exposure evidence in mind. The boundary: this is a synthesis of separate literatures, not a single tested programme, and the specific thresholds are judgement calls the studies do not set.",
    action: "Write a one-page ownership plan with six lines — target price from the residual-income floor, down payment and reserve, loan structure, minimum holding period, refinancing trigger, neighbourhood criteria — and do not make an offer until all six are filled in and reviewed with a counselor.",
    sources: [
      { cite: "Beracha, E., & Johnson, K. H. (2012). Lessons from over 30 years of buy versus rent decisions: Is the American Dream always wise?. Real Estate Economics, 40(2), 217–247.", note: "Buy-versus-rent outcomes over 30+ years depended on horizon, market and what renters did with the difference — the plan has to specify all three.", link: doi("10.1111/j.1540-6229.2011.00321.x"), kind: "doi" },
      { cite: "Sinai, T., & Souleles, N. S. (2005). Owner-occupied housing as a hedge against rent risk. Quarterly Journal of Economics, 120(2), 763–789.", note: "The rent-hedging value of owning rises with expected length of stay — a long horizon is part of the case for buying.", link: doi("10.1162/0033553053970197"), kind: "doi" },
      { cite: "Campbell, J. Y., & Cocco, J. F. (2003). Household risk management and optimal mortgage choice. The Quarterly Journal of Economics, 118(4), 1449–1494.", note: "Mortgage structure should match income risk and borrowing constraints, not the lowest headline rate.", link: doi("10.1162/003355303322552847"), kind: "doi" },
      { cite: "Ganong, P., & Noel, P. (2020). Liquidity versus wealth in household debt obligations: Evidence from housing policy in the Great Recession. American Economic Review, 110(10), 3100–3138.", note: "Liquidity, not wealth, determines whether households keep paying in a downturn — the reserve is part of the purchase.", link: doi("10.1257/aer.20181243"), kind: "doi" },
      { cite: "Chetty, R., Hendren, N., & Katz, L. F. (2016). The effects of exposure to better neighborhoods on children: New evidence from the Moving to Opportunity experiment. American Economic Review, 106(4), 855–902.", note: "Neighbourhood exposure during childhood shapes adult outcomes — location is part of the return on the purchase.", link: doi("10.1257/aer.20150572"), kind: "doi" },
      { cite: "Sodini, P., Van Nieuwerburgh, S., Vestman, R., & von Lilienfeld-Toal, U. (2023). Identifying the benefits from homeownership: A Swedish experiment. American Economic Review, 113(12), 3173–3212.", note: "Swedish natural experiment identifying causal benefits of ownership for households who could sustain it, including wealth and mobility effects.", link: doi("10.1257/aer.20171449"), kind: "doi" },
      { cite: "Goodman, L. S., & Mayer, C. (2018). Homeownership and the American Dream. Journal of Economic Perspectives, 32(1), 31–58.", note: "Balanced review: ownership rewards long holds and sensible leverage and punishes purchases at peaks and forced sales.", link: doi("10.1257/jep.32.1.31"), kind: "doi" },
    ],
  },
];
