// Goal shelf: LEGACY — memorialize a life in meaningful ways (sections 9200–9299).
// Verification: every DOI below was resolved against the Crossref record or the
// PubMed record on 2026-09-11 (see the shelf ledger). See types.ts for the contract.
import { doi, type GoalShelfCluster } from "./types";

export const SECTIONS: Record<string, string> = {
  "9200": "How to Read This Shelf",
  "9201": "Generativity — Caring for What Outlives You",
  "9202": "Life Review & Reminiscence — Structured Looking Back",
  "9203": "Dignity Therapy — the Generativity Document",
  "9204": "Legacy Letters & Ethical Wills — Preparation and Life Completion",
  "9205": "Writing Your Own Story — Expressive and Autobiographical Writing",
  "9206": "Family Narratives — the Stories Grandchildren Carry",
  "9207": "Oral History & Digital Storytelling",
  "9208": "Life Story Books, Photos & Memory Books",
  "9209": "Values, Purpose & the Long View",
  "9210": "Advance Care Planning — the Conversations, Not Just the Forms",
  "9211": "Giving — Money, Time and the Well-Being Return",
  "9212": "Mentoring in Later Life — Experience Corps",
  "9213": "Grief & Continuing Bonds — Keeping the Dead in the Family",
  "9214": "Digital Legacy — Accounts, Data and the Afterlife Industry",
  "9215": "Mortality as Motivator — Terror Management and Legacy",
  "9216": "The Legacy Project — a Family-Enacted, Multi-Year Practice",
};

export const CLUSTERS: GoalShelfCluster[] = [
  {
    id: "gs-legacy-read-me-first",
    goal: "legacy", tier: "fundamental", section: "9200",
    title: "How to Read the Legacy Shelf",
    subtitle: "A legacy is built in generative acts, not in a single document",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "low" },
    description:
      "This shelf treats 'memorializing a life' as something done while alive: generative acts, structured looking-back, stories told to the next generation, legacy documents, planning conversations, giving and mentoring. Each protocol is tiered and ends in a concrete step. The evidence is honest about the limits — several well-run trials of legacy interventions found no effect on distress in people who were not distressed to begin with — so the shelf rates meaning, connection and family outcomes rather than promising cures.",
    action: "This month, do one generative thing a week that will outlast the week — teach a skill, write one page of your story, tell one family story at dinner — before you buy any legacy product or service.",
    sources: [
      { cite: "McAdams, D. P., & de St. Aubin, E. (1992). A theory of generativity and its assessment through self-report, behavioral acts, and narrative themes in autobiography. Journal of Personality and Social Psychology, 62(6), 1003-1015.", note: "McAdams and de St. Aubin's theory and measures of generativity (concern, acts and narrative themes) — the construct every cluster on this shelf operationalizes.", link: doi("10.1037/0022-3514.62.6.1003"), kind: "doi" },
    ],
  },
  {
    id: "gs-legacy-generative-acts",
    goal: "legacy", tier: "fundamental", section: "9201",
    title: "One Generative Act a Week",
    subtitle: "Generative concern and action track with life satisfaction and health",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "low" },
    feeds: ["meaning in life", "life satisfaction", "purpose in later life"],
    description:
      "Generativity — Erikson's concern for establishing and guiding the next generation — can be measured as concern (the Loyola Generativity Scale), acts (the Generative Behavior Checklist) and narrative themes, and the three relate to each other and to life satisfaction and happiness. In older adults, perceived generativity predicts better self-rated health and fewer functional limitations, and even caregiving carries a protective generativity component. The associations are correlational, but the activity is cheap and the plausible mechanism (agency plus communion) is well described.",
    action: "Pick one generative act per week for the next month — teach someone a skill, mentor, plant something, donate expertise, tell a story to a younger person — and log it in a single line. At month's end rate the week's meaning 1–10 next to each entry.",
    sources: [
      { cite: "McAdams, D. P., & de St. Aubin, E. (1992). A theory of generativity and its assessment through self-report, behavioral acts, and narrative themes in autobiography. Journal of Personality and Social Psychology, 62(6), 1003-1015.", note: "Introduces the Loyola Generativity Scale and Generative Behavior Checklist and shows that generative concern, acts and narrative themes cohere as a construct.", link: doi("10.1037/0022-3514.62.6.1003"), kind: "doi" },
      { cite: "de St. Aubin, E., & McAdams, D. P. (1995). The relations of generative concern and generative action to personality traits, satisfaction/happiness with life, and ego development. Journal of Adult Development, 2(2), 99-112.", note: "Generative concern and generative action related to personality traits, satisfaction and happiness with life, and ego development in adults.", link: doi("10.1007/BF02251258"), kind: "doi" },
      { cite: "McAdams, D. P., Diamond, A., de St. Aubin, E., & Mansfield, E. (1997). Stories of commitment: The psychosocial construction of generative lives. Journal of Personality and Social Psychology, 72(3), 678-694.", note: "Life-story interviews of highly generative adults revealed a distinctive 'commitment story' — early advantage, sensitivity to others' suffering, steadfast beliefs and prosocial goals.", link: doi("10.1037/0022-3514.72.3.678"), kind: "doi" },
      { cite: "Gruenewald, T. L., Liao, D. H., & Seeman, T. E. (2012). Contributing to others, contributing to oneself: perceptions of generativity and health in later life. The journals of gerontology. Series B, Psychological sciences and social sciences, 67(6), 660-5.", note: "Older adults who perceived themselves as generative contributors reported better health and fewer functional limitations in later life.", link: doi("10.1093/geronb/gbs034"), kind: "doi" },
      { cite: "Grossman, M. R., & Gruenewald, T. L. (2017). Caregiving and Perceived Generativity: A Positive and Protective Aspect of Providing Care?. Clinical gerontologist, 40(5), 435-447.", note: "Family caregivers who perceived their caregiving as generative showed a positive, protective pattern of well-being.", link: doi("10.1080/07317115.2017.1317686"), kind: "doi" },
    ],
  },
  {
    id: "gs-legacy-structured-life-review",
    goal: "legacy", tier: "moderate", section: "9202",
    title: "A Structured Life Review Over Six to Eight Sessions",
    subtitle: "Meta-analyses find medium effects on depression and life satisfaction in older adults",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "weeks", durability: "sustained", effort: "moderate" },
    feeds: ["ego integrity", "mood", "loneliness"],
    description:
      "Reminiscence and life review — deliberately recalling, evaluating and integrating one's past — is among the best-evidenced psychological interventions for older adults: meta-analyses report moderate effects on depressive symptoms, ego integrity and purpose, with structured life review (evaluating and reconciling, not just recalling) outperforming simple reminiscence, and larger effects for people with depression. Recent meta-analyses add gains in quality of life, life satisfaction and loneliness, with six to eight sessions and professional facilitation working best. Negative rumination is the failure mode; integrating meaning and mastery is what helps.",
    action: "Over the next eight weeks, work through one life chapter per week (childhood, family, work, love, hardship, turning points, what I learned, what I want to pass on), one hour each, with a partner, friend or facilitator who asks 'what did that mean to you?' and writes a page of notes.",
    sources: [
      { cite: "Bohlmeijer, E., Smit, F., & Cuijpers, P. (2003). Effects of reminiscence and life review on late-life depression: a meta-analysis. International journal of geriatric psychiatry, 18(12), 1088-94.", note: "Meta-analysis of reminiscence and life review for late-life depression: a moderate overall effect, with life review and studies of people with depression showing the largest effects.", link: doi("10.1002/gps.1018"), kind: "doi" },
      { cite: "Pinquart, M., & Forstmeier, S. (2012). Effects of reminiscence interventions on psychosocial outcomes: a meta-analysis. Aging & mental health, 16(5), 541-58.", note: "Meta-analysis of 128 reminiscence studies: moderate improvements in depression, ego integrity, purpose, death preparation and mastery, strongest for life review and for depressed participants.", link: doi("10.1080/13607863.2011.651434"), kind: "doi" },
      { cite: "Westerhof, G. J., & Bohlmeijer, E. T. (2014). Celebrating fifty years of research and applications in reminiscence and life review: state of the art and new directions. Journal of aging studies, 29, 107-14.", note: "Fifty-year state-of-the-art review of reminiscence and life review, distinguishing simple, life-review and life-review therapy formats and their evidence.", link: doi("10.1016/j.jaging.2014.02.003"), kind: "doi" },
      { cite: "Liu, Z., Yang, F., Lou, Y., Zhou, W., & Tong, F. (2021). The Effectiveness of Reminiscence Therapy on Alleviating Depressive Symptoms in Older Adults: A Systematic Review. Frontiers in Psychology.", note: "Systematic review of 10 RCTs: reminiscence therapy significantly relieved depressive symptoms in older adults, with group formats more cost-effective and structured protocols more replicable.", link: doi("10.3389/fpsyg.2021.709853"), kind: "doi" },
      { cite: "Akazawa, K., Chen, C., & Chen, S. (2023). Effectiveness on Quality of Life and Life Satisfaction for Older Adults: A Systematic Review and Meta-Analysis of Life Review and Reminiscence Therapy across Settings. Behavioral Sciences.", note: "Meta-analysis of 32 RCTs (2,353 participants): life review and reminiscence improved quality of life (SMD 1.07) and life satisfaction (SMD 1.12), with six to eight sessions most effective for satisfaction.", link: doi("10.3390/bs13100830"), kind: "doi" },
      { cite: "Yang, H., Zhong, Q., Han, B., Pu, Y., He, R., Huang, K., …, & Chen, L. (2025). Effects of reminiscence therapy for loneliness in older adults: a systematic review and meta-analysis. Age and Ageing.", note: "Meta-analysis of 22 studies: reminiscence therapy reduced loneliness in older adults, with group formats and professional facilitators more effective.", link: doi("10.1093/ageing/afaf136"), kind: "doi" },
      { cite: "Sabir, M., Henderson, C. R., Kang, S.-Y., & Pillemer, K. (2016). Attachment-focused integrative reminiscence with older African Americans: a randomized controlled intervention study. Aging & Mental Health.", note: "RCT of eight weekly attachment-focused integrative reminiscence sessions with older African Americans: lower depression and perceived stress and fewer emergency-room visits at six months.", link: doi("10.1080/13607863.2015.1023764"), kind: "doi" },
      { cite: "Korte, J., Cappeliez, P., Bohlmeijer, E. T., & Westerhof, G. J. (2012). Meaning in life and mastery mediate the relationship of negative reminiscence with psychological distress among older adults with mild to moderate depressive symptoms. European journal of ageing, 9(4), 343-351.", note: "Meaning in life and mastery mediated the link between negative reminiscence and psychological distress — the mechanism that separates helpful review from rumination.", link: doi("10.1007/s10433-012-0239-3"), kind: "doi" },
    ],
  },
  {
    id: "gs-legacy-dignity-therapy",
    goal: "legacy", tier: "elite", section: "9203",
    title: "Dignity Therapy: Record, Edit and Bequeath the Generativity Document",
    subtitle: "A therapist-led interview becomes a document your family keeps",
    evidenceTag: "Moderate",
    impact: { magnitude: 4, latency: "weeks", durability: "lasting", effort: "high" },
    feeds: ["sense of dignity and meaning", "family appreciation", "generativity"],
    description:
      "Dignity therapy is a brief, individualized psychotherapy for people with life-limiting illness: a recorded interview about what mattered most and what they want remembered is transcribed, edited and returned as a document to bequeath. The large three-arm RCT found no difference in distress scores, but dignity-therapy recipients were significantly more likely to say it helped them, improved quality of life and dignity, and changed how their family saw them; a later RCT found that specifically creating the legacy document (not life review alone) raised generativity and ego integrity. Family members report the documents as a source of comfort. Honest boundary: it does not reliably reduce depression or desire for death.",
    action: "If you or a family member is living with a serious illness, ask the palliative-care or hospice team whether a trained dignity-therapy clinician is available; if not, use the published question protocol (what mattered most, roles, accomplishments, hopes and wishes for loved ones) over two recorded sessions, edit into a document and give copies to the people named in it.",
    sources: [
      { cite: "Chochinov, H. M., Hack, T., Hassard, T., Kristjanson, L. J., McClement, S., & Harlos, M. (2005). Dignity therapy: a novel psychotherapeutic intervention for patients near the end of life. Journal of clinical oncology : official journal of the American Society of Clinical Oncology, 23(24), 5520-5.", note: "The original dignity-therapy feasibility study with terminally ill patients in Winnipeg and Perth: sessions on what mattered most were transcribed, edited and returned to bequeath, with pre–post measures of dignity, depression, meaning and purpose.", link: doi("10.1200/JCO.2005.08.391"), kind: "doi" },
      { cite: "Chochinov, H. M., Kristjanson, L. J., Breitbart, W., McClement, S., Hack, T. F., Hassard, T., & Harlos, M. (2011). Effect of dignity therapy on distress and end-of-life experience in terminally ill patients: a randomised controlled trial. The Lancet Oncology.", note: "Three-arm RCT (n = 441) across Canada, the USA and Australia: no difference in distress scores, but dignity therapy was rated significantly more helpful and more likely to improve quality of life, sense of dignity and how the family saw and appreciated them.", link: doi("10.1016/S1470-2045(11)70153-X"), kind: "doi" },
      { cite: "McClement, S., Chochinov, H. M., Hack, T., Hassard, T., Kristjanson, L. J., & Harlos, M. (2007). Dignity therapy: family member perspectives. Journal of palliative medicine, 10(5), 1076-82.", note: "Family members' perspectives on the generativity documents left by dignity-therapy recipients, and the comfort they provided after the death.", link: doi("10.1089/jpm.2007.0002"), kind: "doi" },
      { cite: "Fitchett, G., Emanuel, L., Handzo, G., Boyken, L., & Wilkie, D. J. (2015). Care of the human spirit and the role of dignity therapy: a systematic review of dignity therapy research. BMC Palliative Care.", note: "Systematic review of 25 dignity-therapy articles: consistently high satisfaction and benefit for patients and families, inconsistent effects on physical and emotional symptoms.", link: doi("10.1186/s12904-015-0007-1"), kind: "doi" },
      { cite: "Scarton, L., Oh, S., Sylvera, A., Lamonge, R., Yao, Y., Chochinov, H., …, & Wilkie, D. (2018). Dignity Impact as a Primary Outcome Measure for Dignity Therapy. American Journal of Hospice and Palliative Medicine.", note: "Reanalysis of the multisite RCT with a Dignity Impact Scale: dignity-therapy recipients scored significantly higher than both comparison arms, consistent with effects in meaning-making and life completion.", link: doi("10.1177/1049909118777987"), kind: "doi" },
      { cite: "Vuksanovic, D., Green, H. J., Dyck, M., & Morrissey, S. A. (2017). Dignity Therapy and Life Review for Palliative Care Patients: A Randomized Controlled Trial. Journal of Pain and Symptom Management, 53(2), 162-170.e1.", note: "RCT of 70 adults comparing dignity therapy, life review and waitlist: only dignity therapy — the arm that produced a legacy document — increased generativity and ego-integrity scores.", link: doi("10.1016/j.jpainsymman.2016.09.005"), kind: "doi" },
      { cite: "Vuksanovic, D., Green, H., Morrissey, S., & Smith, S. (2017). Dignity Therapy and Life Review for Palliative Care Patients: A Qualitative Study. Journal of Pain and Symptom Management, 54(4), 530-537.e1.", note: "Qualitative analysis of the same trial: legacy documents contained more sense of legacy, fighting spirit and hope, while life-review transcripts held more regret and unfinished business.", link: doi("10.1016/j.jpainsymman.2017.07.016"), kind: "doi" },
      { cite: "Velasco Yanez, R. J., de Freitas Corpes, E., Sixsmith, J., Carvalho Fernandes, A. F., de Souza Aquino, P., Moura Barbosa Castro, R. C., & Furtado Jorge, H. M. (2025). Use of dignity therapy in palliative care: a comprehensive scoping review. BMC Palliative Care.", note: "Scoping review of 82 studies: dignity therapy has been adapted across cultures, delivered earlier in illness and posthumously, and shows benefits for family members and underrepresented groups.", link: doi("10.1186/s12904-025-01812-4"), kind: "doi" },
    ],
  },
  {
    id: "gs-legacy-dignity-questions-early",
    goal: "legacy", tier: "moderate", section: "9203",
    title: "Ask the Dignity-Therapy Questions Early, as a Family",
    subtitle: "The protocol adapts to early illness, neurological disease and family-led conversation",
    evidenceTag: "Emerging",
    impact: { magnitude: 3, latency: "weeks", durability: "lasting", effort: "moderate" },
    feeds: ["meaningful end-of-life conversations", "family knowledge of the person", "readiness for later planning"],
    description:
      "Dignity therapy was built for the last months of life, but feasibility studies now deliver it in early-stage cancer and to people with motor neuron disease and their caregivers, and a family-based version was designed so relatives ask the questions in cultures where death is taboo. These are small, uncontrolled or protocol-stage studies, so the tag is emerging; the protocol here is to borrow the question set for an ordinary family conversation long before it is urgent.",
    action: "This quarter, hold one two-hour recorded conversation with an ageing parent using the dignity-therapy question set (what parts of life do you remember most, when did you feel most alive, what roles mattered, what do you want your family to know, what hopes do you hold for them) and transcribe it into a document they can edit and keep.",
    sources: [
      { cite: "Jenewein, J., Moergeli, H., Meyer-Heim, T., Muijres, P., Bopp-Kistler, I., Chochinov, H. M., & Peng-Keller, S. (2021). Feasibility, Acceptability, and Preliminary Efficacy of Dignity Therapy in Patients With Early Stage Dementia and Their Family. A Pilot Randomized Controlled Trial. Frontiers in psychiatry, 12, 795813.", note: "Feasibility, acceptability and preliminary efficacy of dignity therapy delivered to patients with early-stage disease, extending the model beyond the last months of life.", link: doi("10.3389/fpsyt.2021.795813"), kind: "doi" },
      { cite: "Chen, Z., Guo, Q., Geng, H., Xi, L., Lin, J., & Chochinov, H. M. (2022). Development and Formative Evaluation of the Family-Based Dignity Therapy Protocol for Palliative Cancer Patients and Their Families: A Mixed-Methods Study. Cancer nursing.", note: "Development and formative evaluation of a family-based dignity therapy protocol in China: endorsed by over 75% of patients and family members and over 90% of nurses as a way to enable meaningful end-of-life conversations.", link: doi("10.1097/NCC.0000000000001174"), kind: "doi" },
      { cite: "Aoun, S. M., Chochinov, H. M., & Kristjanson, L. J. (2015). Dignity therapy for people with motor neuron disease and their family caregivers: a feasibility study. Journal of palliative medicine, 18(1), 31-7.", note: "Feasibility study of dignity therapy for people with motor neuron disease and their family caregivers.", link: doi("10.1089/jpm.2014.0213"), kind: "doi" },
      { cite: "Bentley, B., Aoun, S. M., O'Connor, M., Breen, L. J., & Chochinov, H. M. (2012). Is dignity therapy feasible to enhance the end of life experience for people with motor neurone disease and their family carers?. BMC palliative care, 11, 18.", note: "Feasibility of dignity therapy to enhance the end-of-life experience for people with motor neurone disease and their family carers.", link: doi("10.1186/1472-684X-11-18"), kind: "doi" },
      { cite: "Hall, S., Chochinov, H., Harding, R., Murray, S., Richardson, A., & Higginson, I. J. (2009). A Phase II randomised controlled trial assessing the feasibility, acceptability and potential effectiveness of dignity therapy for older people in care homes: study protocol. BMC Geriatrics.", note: "Phase II RCT protocol testing dignity therapy for older people in care homes, with the generativity document bequeathed to people of their choosing.", link: doi("10.1186/1471-2318-9-9"), kind: "doi" },
    ],
  },
  {
    id: "gs-legacy-outlook-letters",
    goal: "legacy", tier: "moderate", section: "9204",
    title: "Write the Legacy Letter: Preparation, Life Completion, Forgiveness",
    subtitle: "Three structured conversations — with an honest null result attached",
    evidenceTag: "Mixed",
    impact: { magnitude: 3, latency: "weeks", durability: "lasting", effort: "moderate" },
    callout: "Honest boundary: the Outlook trials found benefits for preparation and completion in hospice patients, but the largest RCTs in people with early life-limiting illness showed no advantage over relaxation on distress, anxiety or depression. The letter is worth writing for what it gives your family and for the sense of completion — not as a treatment for distress you do not have.",
    description:
      "The Outlook intervention is three sessions — a life review, a forgiveness and regret conversation, and a discussion of heritage and legacy — that end in a written or recorded legacy. In its first randomized test it improved functioning, preparation and completion; the 221-patient veterans trial found higher preparation and completion than usual care at the first follow-up but not versus relaxation; and the 135-patient trial in early-stage illness found no differences. A nurse-delivered version proved feasible, and legacy-making with volunteers or online has been tested in families with children. Ethical wills sit here: a values-and-wishes letter, not an asset list.",
    action: "Over three weekends, write a three-part letter to the people who will outlive you: what your life has been (the review), what you regret and forgive (the reckoning), and what you hope for them and want them to keep (the heritage). Date it, store a copy with your estate documents, and re-read it each birthday.",
    sources: [
      { cite: "Steinhauser, K. E., Alexander, S. C., Byock, I. R., George, L. K., Olsen, M. K., & Tulsky, J. A. (2008). Do preparation and life completion discussions improve functioning and quality of life in seriously ill patients? Pilot randomized control trial. Journal of palliative medicine, 11(9), 1234-40.", note: "First randomized test of preparation and life-completion discussions in seriously ill patients, showing improvements in functioning and quality of life.", link: doi("10.1089/jpm.2008.0078"), kind: "doi" },
      { cite: "Steinhauser, K. E., Alexander, S. C., Byock, I. R., George, L. K., & Tulsky, J. A. (2009). Seriously ill patients' discussions of preparation and life completion: an intervention to assist with transition at the end of life. Palliative & supportive care, 7(4), 393-404.", note: "Qualitative account of what seriously ill patients discussed in the Outlook sessions: review, regret and forgiveness, and heritage and legacy.", link: doi("10.1017/S147895150999040X"), kind: "doi" },
      { cite: "Keall, R. M., Butow, P. N., Steinhauser, K. E., & Clayton, J. M. (2013). Nurse-facilitated preparation and life completion interventions are acceptable and feasible in the Australian palliative care setting: results from a phase 2 trial. Cancer nursing, 36(3), E39-46.", note: "Nurse-facilitated preparation and life-completion interventions were acceptable and feasible in cancer care.", link: doi("10.1097/NCC.0b013e3182664c7a"), kind: "doi" },
      { cite: "Steinhauser, K. E., Alexander, S., Olsen, M. K., Stechuchak, K. M., Zervakis, J., Ammarell, N., …, & Tulsky, J. A. (2017). Addressing Patient Emotional and Existential Needs During Serious Illness: Results of the Outlook Randomized Controlled Trial. Journal of Pain and Symptom Management, 54(6), 898-908.", note: "RCT of 221 veterans with serious illness: Outlook improved preparation and completion versus usual care at the first post-assessment but not the second, and did not differ from relaxation meditation.", link: doi("10.1016/j.jpainsymman.2017.06.003"), kind: "doi" },
      { cite: "Steinhauser, K. E., Stechuchak, K. M., Ramos, K., Winger, J., Tulsky, J. A., & Olsen, M. K. (2020). Current measures of distress may not account for what's most important in existential care interventions: Results of the outlook trial. Palliative & Supportive Care, 18(6), 648-657.", note: "RCT of 135 patients with early life-limiting illness and low baseline distress: no differences from relaxation on preparation, completion, anxiety, depression or quality of life.", link: doi("10.1017/S1478951520001170"), kind: "doi" },
      { cite: "Steinhauser, K. E., Olsen, A., Johnson, K. S., Sanders, L. L., Olsen, M., Ammarell, N., & Grossoehme, D. (2016). The feasibility and acceptability of a chaplain-led intervention for caregivers of seriously ill patients: A Caregiver Outlook pilot study. Palliative & Supportive Care, 14(5), 456-67.", note: "Caregiver Outlook pilot: a chaplain-led relationship review, forgiveness and legacy sequence was acceptable to caregivers of seriously ill patients.", link: doi("10.1017/S1478951515001248"), kind: "doi" },
      { cite: "Akard, T. F., Dietrich, M. S., Friedman, D. L., Wray, S., Gerhardt, C. A., Hendricks-Ferguson, V., …, & Gilmer, M. J. (2021). Randomized Clinical Trial of a Legacy Intervention for Quality of Life in Children with Advanced Cancer. Journal of Palliative Medicine, 24(5), 680-688.", note: "RCT of a web-based legacy intervention for 97 child–parent dyads facing advanced cancer: feasible, small effects on procedural anxiety but overall a null study on quality of life.", link: doi("10.1089/jpm.2020.0139"), kind: "doi" },
      { cite: "Akard, T. F., Dietrich, M. S., Friedman, D. L., Gerhardt, C. A., Given, B., Hendricks-Ferguson, V., …, & Gilmer, M. J. (2021). Improved Parent-Child Communication following a RCT Evaluating a Legacy Intervention for Children with Advanced Cancer. Progress in Palliative Care, 29(3), 130-139.", note: "Secondary analysis of the same trial: legacy-making produced meaningful (non-significant) improvements in parent–child communication, strongest for fathers.", link: doi("10.1080/09699260.2020.1826778"), kind: "doi" },
    ],
  },
  {
    id: "gs-legacy-write-your-story",
    goal: "legacy", tier: "fundamental", section: "9205",
    title: "Write Your Story, Twenty Minutes at a Time",
    subtitle: "Expressive writing has a small, reliable effect on health and mood",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "low" },
    feeds: ["meaning-making", "emotional processing", "a written record for descendants"],
    description:
      "Pennebaker's paradigm — writing about deeply personal experiences for 15–20 minutes on several days — produces small but reliable improvements in reported health, psychological well-being and general functioning, with a meta-analysis of 146 randomized studies confirming the effect (r ≈ .075) and identifying moderators. The mechanism is 'forming a story': translating experience into a coherent narrative. For legacy purposes the by-product is the point — the pages become the raw material of a life story.",
    action: "Four days a week for the next month, write for 20 minutes about one episode of your life that shaped you, without stopping to edit. Keep the pages in one folder labelled by decade; that folder is the first draft of your memoir.",
    sources: [
      { cite: "Pennebaker, J. W., & Beall, S. K. (1986). Confronting a traumatic event: toward an understanding of inhibition and disease. Journal of abnormal psychology, 95(3), 274-81.", note: "The original experiment: students who wrote about traumatic events for four days showed fewer health-centre visits in the following months.", link: doi("10.1037/0021-843x.95.3.274"), kind: "doi" },
      { cite: "Smyth, J. M. (1998). Written emotional expression: effect sizes, outcome types, and moderating variables. Journal of Consulting and Clinical Psychology, 66(1), 174-84.", note: "Meta-analysis of written emotional expression: improved reported physical health, psychological well-being, physiological functioning and general functioning in healthy participants.", link: doi("10.1037/0022-006X.66.1.174"), kind: "doi" },
      { cite: "Frattaroli, J. (2006). Experimental disclosure and its moderators: a meta-analysis. Psychological Bulletin, 132(6), 823-65.", note: "Random-effects meta-analysis of 146 randomized disclosure studies: a positive, significant average effect (r = .075) with identified moderators.", link: doi("10.1037/0033-2909.132.6.823"), kind: "doi" },
      { cite: "Pennebaker, J. W., & Seagal, J. D. (1999). Forming a story: The health benefits of narrative. Journal of Clinical Psychology, 55(10), 1243-1254.", note: "Pennebaker and Seagal's account of why narrative works: constructing a coherent story from experience is the active ingredient of expressive writing.", link: doi("10.1002/(SICI)1097-4679(199910)55:10<1243::AID-JCLP6>3.0.CO;2-N"), kind: "doi" },
    ],
  },
  {
    id: "gs-legacy-tell-family-stories",
    goal: "legacy", tier: "fundamental", section: "9206",
    title: "Tell the Family Stories — Especially the Hard Ones",
    subtitle: "Children who know their family history are more resilient",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "weeks", durability: "lasting", effort: "low" },
    feeds: ["children's identity and self-esteem", "family cohesion", "intergenerational continuity"],
    description:
      "Adolescents' knowledge of family history (the 20-item 'Do You Know?' scale) correlates with internal locus of control, self-esteem, family cohesion and lower anxiety and behaviour problems, and observational studies show families who co-construct dinner-table narratives raise children with a stronger sense of self. Intergenerational stories — the ones about parents and grandparents, including setbacks survived — add to a young person's own life story and identity. These are correlational findings from a small research group, but the practice costs nothing and doubles as the memory bank of your legacy.",
    action: "Tell one story about a parent or grandparent at one meal every week this month, choosing an 'oscillating' story (we had good times, hard times, and came through) over pure triumph. Ask your children to retell one back to you at the end of the month.",
    sources: [
      { cite: "Duke, M. P., Lazarus, A., & Fivush, R. (2008). Knowledge of family history as a clinically useful index of psychological well-being and prognosis: A brief report. Psychotherapy: Theory, Research, Practice, Training, 45(2), 268-272.", note: "Knowledge of family history correlated with locus of control, self-esteem, family functioning and cohesion, lower anxiety and fewer behaviour problems in children and adolescents.", link: doi("10.1037/0033-3204.45.2.268"), kind: "doi" },
      { cite: "Bohanek, J. G., Marin, K. A., Fivush, R., & Duke, M. P. (2006). Family narrative interaction and children's sense of self. Family process, 45(1), 39-54.", note: "Families whose dinner-table narratives were collaboratively co-constructed had preadolescents with a stronger sense of self.", link: doi("10.1111/j.1545-5300.2006.00079.x"), kind: "doi" },
      { cite: "Fivush, R., Bohanek, J. G., & Zaman, W. (2011). Personal and intergenerational narratives in relation to adolescents' well-being. New Directions for Child and Adolescent Development, 2011(131), 45-57.", note: "Personal and intergenerational narratives were related to adolescents' well-being, with intergenerational stories contributing over and above personal ones.", link: doi("10.1002/cd.288"), kind: "doi" },
      { cite: "Merrill, N., & Fivush, R. (2016). Intergenerational narratives and identity across development. Developmental Review, 40, 72-92.", note: "Developmental review of how intergenerational narratives shape identity from childhood through adulthood.", link: doi("10.1016/j.dr.2016.03.001"), kind: "doi" },
      { cite: "Elias, A., & Brown, A. D. (2022). The role of intergenerational family stories in mental health and wellbeing. Frontiers in Psychology, 13.", note: "Review of emerging evidence that intergenerational family stories are associated with positive mental health, noting culture and gender as moderators of how stories are told.", link: doi("10.3389/fpsyg.2022.927795"), kind: "doi" },
      { cite: "Fiese, B. H., & Spagnola, M. (2005). Narratives in and about families: an examination of coding schemes and a guide for family researchers. Journal of Family Psychology, 19(1), 51-61.", note: "Overview of narrative methods for studying families, including how coherence and co-construction are coded and validated against observed behaviour.", link: doi("10.1037/0893-3200.19.1.51"), kind: "doi" },
    ],
  },
  {
    id: "gs-legacy-record-oral-history",
    goal: "legacy", tier: "moderate", section: "9207",
    title: "Record an Oral History or Digital Story",
    subtitle: "Reminiscence with a microphone — validation for elders, an heirloom for the family",
    evidenceTag: "Emerging",
    impact: { magnitude: 3, latency: "weeks", durability: "lasting", effort: "moderate" },
    feeds: ["elders' sense of contribution", "intergenerational engagement", "a durable record"],
    description:
      "Oral-history projects with elders are described in nursing practice as validating their contributions, and a scoping review of reminiscence-based digital storytelling reports effects on personal meaning, social connectedness and spiritual well-being for the storyteller, with impacts on the viewers and co-creators too — though intergenerational co-creation is rarely built in. The one randomized test of an online life-story book in mild dementia found small, non-significant effects on symptoms but a significant reduction in caregiver distress during the process. The recording is the legacy; the process is the intervention.",
    action: "This month, record three one-hour audio or video interviews with the oldest living member of your family using a fixed set of twenty questions (childhood home, first job, how they met their partner, the hardest year, advice). Transcribe or summarize each, and share the files with every branch of the family.",
    sources: [
      { cite: "Taft, L. B., Stolder, M. E., Knutson, A. B., Tamke, K., Platt, J., & Bowlds, T. (2004). Oral history: Validating contributions of elders. Geriatric nursing (New York, N.Y.), 25(1), 38-43.", note: "Oral-history work with elders described as validating their contributions and strengthening relationships with those who listen.", link: doi("10.1016/j.gerinurse.2003.11.001"), kind: "doi" },
      { cite: "Xu, L., Fields, N., Highfill, M. C., & Troutman, B. (2023). Remembering the Past with Today's Technology: A Scoping Review of Reminiscence-Based Digital Storytelling with Older Adults. Behavioral Sciences.", note: "Scoping review of reminiscence-based digital storytelling with older adults: impacts on personal meaning, social connectedness, cognition and spiritual well-being, with intergenerational engagement largely untested.", link: doi("10.3390/bs13120998"), kind: "doi" },
      { cite: "DeSanto-Madeya, S., Tjia, J., Fitch, C., & Wachholtz, A. (2020). Feasibility and Acceptability of Digital Legacy-Making: An Innovative Story-Telling Intervention for Adults With Cancer. The American journal of hospice & palliative care, 38(7), 772-777.", note: "Feasibility and acceptability of a digital legacy-making story-telling intervention in serious illness.", link: doi("10.1177/1049909120971569"), kind: "doi" },
      { cite: "Elfrink, T. R., Ullrich, C., Kunz, M., Zuidema, S. U., & Westerhof, G. J. (2021). The Online Life Story Book: A randomized controlled trial on the effects of a digital reminiscence intervention for people with (very) mild dementia and their informal caregivers. PLoS One, 16(9), e0256251.", note: "RCT of the Online Life Story Book in (very) mild dementia (n = 42): small, non-significant effects on neuropsychiatric symptoms, but self-rated caregiver distress fell significantly during the intervention.", link: doi("10.1371/journal.pone.0256251"), kind: "doi" },
      { cite: "Elfrink, T. R., Zuidema, S. U., Kunz, M., & Westerhof, G. J. (2017). The effectiveness of creating an online life story book on persons with early dementia and their informal caregivers: a protocol of a randomized controlled trial. BMC Geriatrics, 17(1), 95.", note: "Protocol for the Online Life Story Book trial: five guided meetings with a trained volunteer over 8–10 weeks to build a digital timeline of stories, pictures and audio.", link: doi("10.1186/s12877-017-0471-y"), kind: "doi" },
    ],
  },
  {
    id: "gs-legacy-life-story-book",
    goal: "legacy", tier: "advanced", section: "9208",
    title: "Build a Life Story Book With a Facilitator",
    subtitle: "Twelve life-review sessions, or a 'gift' book made by relatives — both help",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "weeks", durability: "lasting", effort: "high" },
    feeds: ["quality of relationship with relatives", "staff and family knowledge of the person", "communication in dementia"],
    description:
      "In a randomized trial with care-home residents with dementia, both pathways to a life story book — twelve individual life-review sessions co-creating the book, or a book made by relatives as a gift — improved quality of life, and the life-review route additionally improved autobiographical memory during the sessions; after either route, relatives' rated quality of relationship and staff attitudes improved. Later studies found gains in verbal fluency and apathy, and a review of reviews reports enhanced communication between the person, family and staff in six of seven reviews. Life-review work needs training and supervision; the memory book itself does not.",
    action: "Commission or build a life story book for an ageing parent this season: gather 30–40 photos with captions across decades, ten key stories in their words, and a page of favourite music, foods and places. If they have memory loss, involve a trained facilitator for the review sessions and give copies to their care team.",
    sources: [
      { cite: "Subramaniam, P., Woods, B., & Whitaker, C. (2014). Life review and life story books for people with mild to moderate dementia: a randomised controlled trial. Aging & Mental Health, 18(3), 363-75.", note: "Preliminary RCT (n = 23) in care homes: life story books created either through 12 life-review sessions or as a relative-made gift improved quality of life, relationship quality and staff attitudes; life review also boosted autobiographical memory.", link: doi("10.1080/13607863.2013.837144"), kind: "doi" },
      { cite: "Subramaniam, P., Thillainathan, P., Mat Ghani, N. A., & Sharma, S. (2023). Life Story Book to enhance communication in persons with dementia: A systematic review of reviews. PLoS One, 18(10), e0291620.", note: "Systematic review of reviews: six of seven reviews found life story books enhanced communication between persons with dementia, relatives, care staff and residents.", link: doi("10.1371/journal.pone.0291620"), kind: "doi" },
      { cite: "Asano, T., Wang, C. W., Tsugaruya, M., & Ishikawa, T. (2023). Effectiveness of life story book intervention on apathy and verbal fluency in people with dementia. Clinical Gerontologist, 46(3), 389-399.", note: "Controlled study (43 vs 32): individual life story book sessions improved categorical verbal fluency in mild-to-moderate dementia and apathy in severe dementia.", link: doi("10.1080/07317115.2022.2147887"), kind: "doi" },
      { cite: "McKeown, J., Ryan, T., Ingleton, C., & Clarke, A. (2015). 'You have to be mindful of whose story it is': the challenges of undertaking life story work with people with dementia and their family carers. Dementia, 14(2), 238-56.", note: "Case-study analysis of life story work in an NHS trust: private memories must be respected, book quality varies and the work needs planned facilitation, education and supervision.", link: doi("10.1177/1471301213495864"), kind: "doi" },
      { cite: "Hardy, M. S., Savoie, C., Laberge, M., & Fanaki, C. (2026). The Life Story Book Experience With Residents With Neurocognitive Disorders in Long-Term Care and Their Caregivers: A Mixed-Methods Study. Sage Open Aging, 12, 30495334261481199.", note: "Mixed-methods study in long-term care: life story books were acceptable to residents and caregivers and were associated with more positive affect, pleasure and engagement.", link: doi("10.1177/30495334261481199"), kind: "doi" },
    ],
  },
  {
    id: "gs-legacy-values-and-purpose",
    goal: "legacy", tier: "fundamental", section: "9209",
    title: "Name Your Values, Keep Your Purpose",
    subtitle: "Purpose in life predicts mortality; values affirmation changes behaviour",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "weeks", durability: "lasting", effort: "low" },
    feeds: ["purpose", "resilience to threat", "coherent life story"],
    description:
      "A meta-analysis of ten prospective studies (136,265 people) found higher purpose in life associated with lower all-cause mortality and fewer cardiovascular events, and purpose predicted survival across adulthood in the MIDUS sample. Self-affirmation research shows that briefly writing about core values buffers threat and can shift behaviour over surprisingly long periods. A validated questionnaire (the MLQ) separates presence of meaning from the search for it. For legacy, values are the spine the stories hang on.",
    action: "Write your five core values on one card today with one sentence each on how they show up in your week; re-write the card every quarter. When a decision feels heavy, re-read the card before deciding — that is the affirmation exercise.",
    sources: [
      { cite: "Steger, M. F., Frazier, P., Oishi, S., & Kaler, M. (2006). The meaning in life questionnaire: Assessing the presence of and search for meaning in life. Journal of Counseling Psychology, 53(1), 80-93.", note: "The Meaning in Life Questionnaire: validated subscales for presence of meaning and search for meaning.", link: doi("10.1037/0022-0167.53.1.80"), kind: "doi" },
      { cite: "Hill, P. L., & Turiano, N. A. (2014). Purpose in life as a predictor of mortality across adulthood. Psychological science, 25(7), 1482-6.", note: "MIDUS sample followed 14 years: purpose in life predicted lower mortality across adulthood, independent of age and other well-being measures.", link: doi("10.1177/0956797614531799"), kind: "doi" },
      { cite: "Cohen, R., Bavishi, C., & Rozanski, A. (2016). Purpose in Life and Its Relationship to All-Cause Mortality and Cardiovascular Events: A Meta-Analysis. Psychosomatic medicine, 78(2), 122-33.", note: "Meta-analysis of 10 prospective studies (n = 136,265): higher purpose in life was associated with reduced all-cause mortality and cardiovascular events.", link: doi("10.1097/PSY.0000000000000274"), kind: "doi" },
      { cite: "Cohen, G. L., & Sherman, D. K. (2014). The psychology of change: self-affirmation and social psychological intervention. Annual review of psychology, 65, 333-71.", note: "Review of self-affirmation interventions: brief writing about core values buffers psychological threat and can produce long-lasting behavioural change through recursive processes.", link: doi("10.1146/annurev-psych-010213-115137"), kind: "doi" },
      { cite: "Wade-Benzoni, K. A., Tost, L. P., Hernandez, M., & Larrick, R. P. (2012). It's only a matter of time: death, legacies, and intergenerational decisions. Psychological science, 23(7), 704-9.", note: "Experiments on intergenerational decisions: mortality salience shifted people toward leaving a positive legacy, increasing generosity to future others.", link: doi("10.1177/0956797612443967"), kind: "doi" },
    ],
  },
  {
    id: "gs-legacy-acp-conversation",
    goal: "legacy", tier: "advanced", section: "9210",
    title: "Advance Care Planning: Have the Facilitated Conversation",
    subtitle: "A trained facilitator plus family beats a form in a drawer",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "weeks", durability: "lasting", effort: "moderate" },
    feeds: ["wishes known and respected", "family stress after a death", "concordance between preferences and care"],
    description:
      "In the landmark Australian RCT, facilitated advance care planning for inpatients over 80 meant end-of-life wishes were far more likely to be known and followed, and family members of patients who died had less stress, anxiety and depression. Systematic reviews and a meta-analysis of 55 RCTs confirm that ACP increases advance-directive completion, end-of-life discussions and concordance between preferences and care, and that complex, communication-based interventions outperform documents alone; a nurse-led single session improved patient–physician communication without raising distress. Nothing here is legal advice — it is about the conversation the paperwork should record.",
    action: "Book a facilitated advance-care-planning conversation this quarter (many health systems, hospices and community groups run them) and bring the person you would name as your decision-maker. Write down your values and preferences with them present, then complete the documents your jurisdiction uses with the appropriate professional.",
    sources: [
      { cite: "Detering, K. M., Hancock, A. D., Reade, M. C., & Silvester, W. (2010). The impact of advance care planning on end of life care in elderly patients: randomised controlled trial. BMJ (Clinical research ed.), 340, c1345.", note: "RCT of 309 inpatients aged 80+: facilitated ACP made wishes far more likely to be known and respected, and bereaved family members had significantly less stress, anxiety and depression.", link: doi("10.1136/bmj.c1345"), kind: "doi" },
      { cite: "Brinkman-Stoppelenburg, A., Rietjens, J. A. C., & van der Heide, A. (2014). The effects of advance care planning on end-of-life care: a systematic review. Palliative Medicine, 28(8), 1000-25.", note: "Systematic review of 113 studies: ACP decreased life-sustaining treatment, increased hospice and palliative care, and complex interventions increased compliance with patients' wishes more than written directives alone.", link: doi("10.1177/0269216314526272"), kind: "doi" },
      { cite: "Houben, C. H. M., Spruit, M. A., Groenen, M. T. J., Wouters, E. F. M., & Janssen, D. J. A. (2014). Efficacy of advance care planning: a systematic review and meta-analysis. Journal of the American Medical Directors Association, 15(7), 477-489.", note: "Meta-analysis of 55 RCTs: ACP interventions increased advance-directive completion, end-of-life discussions and concordance between preferred and delivered care, especially when communication was included.", link: doi("10.1016/j.jamda.2014.01.008"), kind: "doi" },
      { cite: "Houben, C. H. M., Spruit, M. A., Luyten, H., Pennings, H. J., van den Boogaart, V. E. M., Creemers, J. P. H. M., …, & Janssen, D. J. A. (2019). Cluster-randomised trial of a nurse-led advance care planning session in patients with COPD and their loved ones. Thorax, 74(4), 328-336.", note: "Cluster RCT of 165 COPD patients: a single 1.5-hour nurse-led ACP session improved patient–physician end-of-life communication and lowered loved ones' anxiety without causing distress.", link: doi("10.1136/thoraxjnl-2018-211943"), kind: "doi" },
      { cite: "McMahan, R. D., Tellez, I., & Sudore, R. L. (2021). Deconstructing the Complexities of Advance Care Planning Outcomes: What Do We Know and Where Do We Go? A Scoping Review. Journal of the American Geriatrics Society, 69(1), 234-244.", note: "Scoping review of 69 ACP RCTs: process and action outcomes were predominantly positive, as were patient and surrogate satisfaction with communication and reduced surrogate distress; utilization outcomes were mixed.", link: doi("10.1111/jgs.16801"), kind: "doi" },
    ],
  },
  {
    id: "gs-legacy-paper-only-planning",
    goal: "legacy", tier: "fundamental", section: "9210",
    title: "'The Will Handles It': Rated at the Floor",
    subtitle: "Documents without conversations do not protect your family or your wishes",
    evidenceTag: "Strong",
    impact: { magnitude: 1, latency: "months", durability: "transient", effort: "low" },
    callout: "Debunked: filing a will or living will and never discussing it is the most common legacy plan and the weakest. Reviews find written directives alone are less effective than communication-based planning at getting wishes followed, and the family stress benefits in the best trial came from facilitated conversations. Rated at the floor so the library counts silence as a cost.",
    description:
      "Across the ACP evidence base, the interventions that changed what actually happened at the end of life were the ones that involved a facilitator, the patient and the family in conversation; do-not-resuscitate orders and written directives studied in isolation were far more variable in effect. Concordance between preferences and care, and the bereaved family's mental health, both depended on the talking. Estate documents matter — but they are the record of a conversation, not a substitute for one.",
    action: "If you have signed documents nobody has read, schedule one hour this month to walk your decision-maker and your children through them, page by page, explaining the why behind each choice. Then move to the facilitated conversation in the cluster above.",
    sources: [
      { cite: "Brinkman-Stoppelenburg, A., Rietjens, J. A. C., & van der Heide, A. (2014). The effects of advance care planning on end-of-life care: a systematic review. Palliative Medicine, 28(8), 1000-25.", note: "Written directives and DNR orders were the most studied forms of ACP, yet complex, communication-based ACP interventions were the ones that increased compliance with patients' end-of-life wishes.", link: doi("10.1177/0269216314526272"), kind: "doi" },
      { cite: "Houben, C. H. M., Spruit, M. A., Groenen, M. T. J., Wouters, E. F. M., & Janssen, D. J. A. (2014). Efficacy of advance care planning: a systematic review and meta-analysis. Journal of the American Medical Directors Association, 15(7), 477-489.", note: "Interventions that added communication about end-of-life care improved concordance between preferences and delivered care beyond what directive-completion alone achieved.", link: doi("10.1016/j.jamda.2014.01.008"), kind: "doi" },
      { cite: "Detering, K. M., Hancock, A. D., Reade, M. C., & Silvester, W. (2010). The impact of advance care planning on end of life care in elderly patients: randomised controlled trial. BMJ (Clinical research ed.), 340, c1345.", note: "The family benefits — less stress, anxiety and depression after a death — came from facilitated conversations that included family members, not from paperwork.", link: doi("10.1136/bmj.c1345"), kind: "doi" },
      { cite: "McMahan, R. D., Tellez, I., & Sudore, R. L. (2021). Deconstructing the Complexities of Advance Care Planning Outcomes: What Do We Know and Where Do We Go? A Scoping Review. Journal of the American Geriatrics Society, 69(1), 234-244.", note: "Facilitated discussions and multimedia programs had among the highest proportions of positive outcomes across 69 trials; goal concordance remained mixed even so.", link: doi("10.1111/jgs.16801"), kind: "doi" },
    ],
  },
  {
    id: "gs-legacy-planned-giving",
    goal: "legacy", tier: "advanced", section: "9211",
    title: "Give While You Live: Money, Time, Motive",
    subtitle: "Prosocial spending raises happiness; other-oriented volunteering predicts survival",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "moderate" },
    feeds: ["positive affect", "purpose", "social connection"],
    description:
      "People randomly assigned to spend money on others report greater happiness than those spending on themselves, a finding replicated across 136 countries and in experiments in Canada, Uganda, India and South Africa. Volunteering is linked in cohort studies to lower mortality (risk ratio 0.78) and, in a 13,000-person outcome-wide analysis, to better psychosocial outcomes and physical functioning at 100+ hours a year — but only other-oriented motives carried the mortality benefit, and experimental evidence for volunteering is thin. Give for the recipient, on a schedule, and the well-being follows.",
    action: "Set two standing commitments this month: an automatic monthly gift to one cause you can name in one sentence, and two hours a week of volunteering aimed at people you can see. Put both on the calendar for a year before judging them.",
    sources: [
      { cite: "Dunn, E. W., Aknin, L. B., & Norton, M. I. (2008). Spending money on others promotes happiness. Science, 319(5870), 1687-8.", note: "Spending on others predicted greater happiness cross-sectionally and longitudinally, and participants randomly assigned to spend on others were happier than those assigned to spend on themselves.", link: doi("10.1126/science.1150952"), kind: "doi" },
      { cite: "Aknin, L. B., Barrington-Leigh, C. P., Dunn, E. W., Helliwell, J. F., Burns, J., Biswas-Diener, R., …, & Norton, M. I. (2013). Prosocial spending and well-being: cross-cultural evidence for a psychological universal. Journal of Personality and Social Psychology, 104(4), 635-52.", note: "Survey data from 136 countries plus experiments in Canada, Uganda, India and South Africa: prosocial spending was associated with and caused greater positive affect across cultures.", link: doi("10.1037/a0031578"), kind: "doi" },
      { cite: "Konrath, S., Fuhrel-Forbis, A., Lou, A., & Brown, S. (2012). Motives for volunteering are associated with mortality risk in older adults. Health Psychology, 31(1), 87-96.", note: "Wisconsin Longitudinal Study: volunteers had lower four-year mortality, but only those with other-oriented motives — self-oriented volunteers resembled non-volunteers.", link: doi("10.1037/a0025226"), kind: "doi" },
      { cite: "Kim, E. S., Whillans, A. V., Lee, M. T., Chen, Y., & VanderWeele, T. J. (2020). Volunteering and Subsequent Health and Well-Being in Older Adults: An Outcome-Wide Longitudinal Approach. American Journal of Preventive Medicine, 59(2), 176-186.", note: "Health and Retirement Study (n = 12,998): volunteering 100+ hours a year predicted lower mortality and physical limitations and higher positive affect, optimism and purpose four years later.", link: doi("10.1016/j.amepre.2020.03.004"), kind: "doi" },
      { cite: "Jenkinson, C. E., Dickens, A. P., Jones, K., Thompson-Coon, J., Taylor, R. S., Rogers, M., …, & Richards, S. H. (2013). Is volunteering a public health intervention? A systematic review and meta-analysis of the health and survival of volunteers. BMC Public Health, 13, 773.", note: "Systematic review: cohort studies show volunteering benefits depression, life satisfaction and survival (RR 0.78), but experimental studies did not confirm them and causal mechanisms remain unclear.", link: doi("10.1186/1471-2458-13-773"), kind: "doi" },
      { cite: "Okun, M. A., Yeung, E. W., & Brown, S. (2013). Volunteering by older adults and risk of mortality: a meta-analysis. Psychology and aging, 28(2), 564-77.", note: "Meta-analysis of volunteering by older adults and mortality risk, quantifying the survival advantage across cohorts.", link: doi("10.1037/a0031519"), kind: "doi" },
      { cite: "Okun, M. A., August, K. J., Rook, K. S., & Newsom, J. T. (2010). Does volunteering moderate the relation between functional limitations and mortality?. Social science & medicine (1982), 71(9), 1662-8.", note: "Volunteering moderated the relation between functional limitations and mortality in older adults — evidence the benefit reaches those with declining health.", link: doi("10.1016/j.socscimed.2010.07.034"), kind: "doi" },
    ],
  },
  {
    id: "gs-legacy-experience-corps",
    goal: "legacy", tier: "elite", section: "9212",
    title: "Mentor in a School for Two Years — the Experience Corps Model",
    subtitle: "High-intensity intergenerational service raises generativity and may protect the ageing brain",
    evidenceTag: "Moderate",
    impact: { magnitude: 5, latency: "months", durability: "lasting", effort: "high" },
    feeds: ["generativity", "physical and cognitive activity", "children's reading and school climate"],
    description:
      "Experience Corps places older adults in elementary schools for 15 hours a week as tutors and mentors. The Baltimore randomized trial found participants' perceptions of generativity rose over two years while controls' fell, cortical and hippocampal volumes were better maintained in men, lifestyle activity increased, and children's academic achievement and school climate improved. Volunteers describe the stressors and rewards frankly. It is the elite move on this shelf because the commitment is large and the return runs in both directions — the mentor and the mentored.",
    action: "Commit to a structured intergenerational mentoring program — Experience Corps/AARP Foundation or a school-tutoring equivalent — for at least two school years at 10–15 hours a week. If none exists locally, build the same structure with one school: fixed days, trained role, the same children all year.",
    sources: [
      { cite: "Fried, L. P., Carlson, M. C., McGill, S., Seeman, T., Xue, Q. L., Frick, K., …, & Rebok, G. W. (2013). Experience Corps: a dual trial to promote the health of older adults and children's academic success. Contemporary clinical trials, 36(1), 1-13.", note: "Design of the Baltimore Experience Corps Trial: a dual randomized trial testing benefits for older adults' health and for children's academic success.", link: doi("10.1016/j.cct.2013.05.003"), kind: "doi" },
      { cite: "Gruenewald, T. L., Tanner, E. K., Fried, L. P., Carlson, M. C., Xue, Q. L., Parisi, J. M., …, & Seeman, T. E. (2015). The Baltimore Experience Corps Trial: Enhancing Generativity via Intergenerational Activity Engagement in Later Life. The journals of gerontology. Series B, Psychological sciences and social sciences, 71(4), 661-70.", note: "Baltimore Experience Corps Trial: perceived generativity increased over two years in participants and declined in controls.", link: doi("10.1093/geronb/gbv005"), kind: "doi" },
      { cite: "Carlson, M. C., Kuo, J. H., Chuang, Y. F., Varma, V. R., Harris, G., Albert, M. S., …, & Fried, L. P. (2015). Impact of the Baltimore Experience Corps Trial on cortical and hippocampal volumes. Alzheimer's & dementia : the journal of the Alzheimer's Association, 11(11), 1340-8.", note: "Two-year trial outcomes: intervention men showed better maintenance of cortical and hippocampal volumes than controls.", link: doi("10.1016/j.jalz.2014.12.005"), kind: "doi" },
      { cite: "Parisi, J. M., Kuo, J., Rebok, G. W., Xue, Q. L., Fried, L. P., Gruenewald, T. L., …, & Carlson, M. C. (2015). Increases in lifestyle activities as a result of experience Corps® participation. Journal of urban health : bulletin of the New York Academy of Medicine, 92(1), 55-66.", note: "Experience Corps participation increased lifestyle activities among sociodemographically at-risk older adults.", link: doi("10.1007/s11524-014-9918-z"), kind: "doi" },
      { cite: "Rebok, G. W., Parisi, J. M., Barron, J. S., Carlson, M. C., Diibor, I., Frick, K. D., …, & Xue, Q. L. (2019). Impact of Experience Corps® Participation on Children's Academic Achievement and School Behavior. Prevention science : the official journal of the Society for Prevention Research, 20(4), 478-487.", note: "Children's academic achievement and school behaviour improved in Experience Corps schools relative to controls.", link: doi("10.1007/s11121-018-0972-8"), kind: "doi" },
      { cite: "Parisi, J. M., Ramsey, C. M., Carlson, M. C., Xue, Q. L., Huang, J., Romani, W. A., …, & Rebok, G. W. (2015). Impact of Experience Corps(®) participation on school climate. Prevention science : the official journal of the Society for Prevention Research, 16(5), 744-53.", note: "Experience Corps participation improved school climate in the participating elementary schools.", link: doi("10.1007/s11121-015-0550-2"), kind: "doi" },
      { cite: "Varma, V. R., Carlson, M. C., Parisi, J. M., Tanner, E. K., McGill, S., Fried, L. P., …, & Gruenewald, T. L. (2014). Experience Corps Baltimore: Exploring the Stressors and Rewards of High-intensity Civic Engagement. The Gerontologist, 55(6), 1038-49.", note: "Qualitative study of Experience Corps Baltimore: volunteers described both the stressors and the rewards of high-intensity civic engagement.", link: doi("10.1093/geront/gnu011"), kind: "doi" },
    ],
  },
  {
    id: "gs-legacy-continuing-bonds",
    goal: "legacy", tier: "moderate", section: "9213",
    title: "Continuing Bonds: Keep the Dead in the Family — the Right Way",
    subtitle: "Oscillate between loss and rebuilding; internalize, don't cling",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "months", durability: "sustained", effort: "low" },
    feeds: ["healthy grief", "family memory", "meaning after loss"],
    description:
      "The dual-process model replaced 'grief work' with oscillation between loss-oriented and restoration-oriented coping, with permission to take respite from both. Continuing-bonds research distinguishes internalized bonds (carrying the person's values and memories) that comfort from externalized, illusion-based bonds that distress, with attachment style moderating adjustment. Rituals of remembrance that tell the person's story fit the comforting pattern — and they are how a legacy is received.",
    action: "For a person you have lost, set one annual remembrance ritual (a meal on their birthday with one story each), keep one object or recipe in daily use, and give yourself explicit days off from grieving. If the bond feels like clinging rather than carrying, that is the signal to talk to a grief counsellor.",
    sources: [
      { cite: "Stroebe, M., & Schut, H. (1999). The dual process model of coping with bereavement: rationale and description. Death Studies, 23(3), 197-224.", note: "The dual process model: adaptive grieving oscillates between loss-oriented and restoration-oriented stressors, with dosed respite from both.", link: doi("10.1080/074811899201046"), kind: "doi" },
      { cite: "Field, N. P., Packman, W., Ronen, R., Pries, A., Davies, B., & Kramer, R. (2013). Type of continuing bonds expression and its comforting versus distressing nature: implications for adjustment among bereaved mothers. Death studies, 37(10), 889-912.", note: "Type of continuing-bond expression matters: internalized bonds were comforting, externalized or illusory bonds distressing, with implications for adjustment.", link: doi("10.1080/07481187.2012.692458"), kind: "doi" },
      { cite: "Ho, S. M., Chan, I. S., Ma, E. P., & Field, N. P. (2013). Continuing bonds, attachment style, and adjustment in the conjugal bereavement among Hong Kong Chinese. Death studies, 37(3), 248-68.", note: "Conjugally bereaved Hong Kong adults: continuing bonds and attachment style jointly predicted adjustment.", link: doi("10.1080/07481187.2011.634086"), kind: "doi" },
      { cite: "Liu, T. H., & Field, N. P. (2019). Continuing bonds and dreams following violent loss among Cambodian survivors of the Pol Pot era. Death studies, 46(2), 297-306.", note: "Cambodian survivors of violent loss described continuing bonds through dreams as part of long-term grieving.", link: doi("10.1080/07481187.2019.1699202"), kind: "doi" },
    ],
  },
  {
    id: "gs-legacy-digital-estate",
    goal: "legacy", tier: "moderate", section: "9214",
    title: "Plan Your Digital Legacy Before Someone Else Has To",
    subtitle: "Accounts, photos, passwords, and who is allowed to decide",
    evidenceTag: "Emerging",
    impact: { magnitude: 3, latency: "weeks", durability: "lasting", effort: "low" },
    feeds: ["family burden after death", "preservation of photos and messages", "privacy"],
    description:
      "Palliative-care professionals report that patients are rarely prepared for their digital legacy, and grounded-theory and survey studies describe staff and volunteers improvising around unmanaged accounts. Concept analyses and a 2026 scoping review now define digital legacy in end-of-life planning, and Öhman and Floridi's ethical framework warns that the 'digital afterlife industry' treats the dead as data assets. The research is descriptive rather than trial-based, so the protocol is simple hygiene rather than a promised outcome.",
    action: "This month, list every account that holds something your family would want (photos, messages, money, subscriptions), designate a legacy contact where the platform allows it, store access instructions with your estate documents, and write one line per account saying keep, memorialize or delete.",
    sources: [
      { cite: "Coop, H., & Marlow, C. (2018). Do we prepare patients for their digital legacy? A survey of palliative care professionals. Palliative medicine, 33(1), 114-115.", note: "Survey of palliative-care professionals: patients are rarely prepared for their digital legacy and staff seldom raise it.", link: doi("10.1177/0269216318802748"), kind: "doi" },
      { cite: "Stanley, S., Higginbotham, K., Finucane, A., & Nwosu, A. C. (2023). A grounded theory study exploring palliative care healthcare professionals' experiences of managing digital legacy as part of advance care planning for people receiving palliative care. Palliative medicine, 37(9), 1424-1433.", note: "Grounded-theory study of palliative-care professionals' experiences managing digital legacy, describing the improvisation that fills the planning gap.", link: doi("10.1177/02692163231194198"), kind: "doi" },
      { cite: "Stanley, S., Hayes, J. A., Mogan, C., Lloyd-Williams, M., Nwosu, A. C., Vasilica, C. M., & Higginbotham, K. (2026). Digital legacy in palliative care and end-of-life care planning: a scoping review. BMJ supportive & palliative care.", note: "Scoping review of digital legacy in palliative and end-of-life care planning.", link: doi("10.1136/spcare-2026-006205"), kind: "doi" },
      { cite: "Meißner, A., Pengel, J., & Steinführer, B. (2026). Digital legacy in palliative care: A concept analysis with Walker and Avant's approach. Palliative medicine, 2692163261455491.", note: "Concept analysis defining digital legacy in palliative care using Walker and Avant's approach.", link: doi("10.1177/02692163261455491"), kind: "doi" },
      { cite: "Meißner, A., & Mahaj, D. (2026). The digital legacy in end-of-life care: unspectacular and meaningless, or not enough recognized? An online survey on the attitudes and personal experiences of professionals and volunteers. BMC palliative care, 25(1).", note: "Online survey of professionals and volunteers on attitudes to and experiences with the digital legacy in end-of-life care.", link: doi("10.1186/s12904-026-02212-y"), kind: "doi" },
      { cite: "Öhman, C., & Floridi, L. (2018). An ethical framework for the digital afterlife industry. Nature human behaviour, 2(5), 318-320.", note: "An ethical framework for the digital-afterlife industry, arguing that the digital remains of the dead deserve protections akin to archaeological remains.", link: doi("10.1038/s41562-018-0335-2"), kind: "doi" },
      { cite: "Pitsillides, S. (2019). Digital legacy: Designing with things. Death studies, 43(7), 426-434.", note: "Design research on digital legacy — how objects and data are designed with, and what they do for the bereaved.", link: doi("10.1080/07481187.2018.1541939"), kind: "doi" },
    ],
  },
  {
    id: "gs-legacy-no-digital-immortality",
    goal: "legacy", tier: "moderate", section: "9214",
    title: "'Digital Immortality' Products: Rated at the Floor",
    subtitle: "No outcome evidence, real ethical hazards — leave your story, not a chatbot",
    evidenceTag: "Emerging",
    impact: { magnitude: 1, latency: "weeks", durability: "transient", effort: "moderate" },
    callout: "Debunked-for-now: services that promise to keep 'you' alive as an avatar or chatbot have no trial evidence for the bereaved and are flagged by ethicists as commercial exploitation of the dead and their families. Rated at the floor: spend the money on the recorded stories, letters and books above, which do have evidence.",
    description:
      "The digital-afterlife industry is growing faster than the research on it. The only rigorous literature consists of ethical frameworks, concept analyses and professional surveys, none of which report benefits for grieving families; the ethical framework argues for consent and dignity protections precisely because the incentives run the other way. The evidence-based digital legacy is the archive — recorded oral histories, digital story books, curated photos — not a simulation.",
    action: "Redirect any impulse to buy an 'AI version of yourself' into the oral-history protocol (9207): three recorded hours in your own voice, shared with family. Write in your digital-legacy list that you do not consent to posthumous simulation, if that is your wish.",
    sources: [
      { cite: "Öhman, C., & Floridi, L. (2018). An ethical framework for the digital afterlife industry. Nature human behaviour, 2(5), 318-320.", note: "Öhman and Floridi's ethical framework for the digital-afterlife industry, identifying the commercial incentive to treat the dead as data and calling for dignity-based regulation.", link: doi("10.1038/s41562-018-0335-2"), kind: "doi" },
      { cite: "Meißner, A., Pengel, J., & Steinführer, B. (2026). Digital legacy in palliative care: A concept analysis with Walker and Avant's approach. Palliative medicine, 2692163261455491.", note: "Concept analysis of digital legacy in palliative care, distinguishing curated records from unmanaged or simulated remains.", link: doi("10.1177/02692163261455491"), kind: "doi" },
      { cite: "Stanley, S., Hayes, J. A., Mogan, C., Lloyd-Williams, M., Nwosu, A. C., Vasilica, C. M., & Higginbotham, K. (2026). Digital legacy in palliative care and end-of-life care planning: a scoping review. BMJ supportive & palliative care.", note: "Scoping review finding that digital legacy in end-of-life planning is underdeveloped in practice and research, with no outcome trials of afterlife services.", link: doi("10.1136/spcare-2026-006205"), kind: "doi" },
      { cite: "Xu, L., Fields, N., Highfill, M. C., & Troutman, B. (2023). Remembering the Past with Today's Technology: A Scoping Review of Reminiscence-Based Digital Storytelling with Older Adults. Behavioral Sciences.", note: "The evidence that does exist points to reminiscence-based digital storytelling — the person's own recorded stories — as the format with reported benefits.", link: doi("10.3390/bs13120998"), kind: "doi" },
    ],
  },
  {
    id: "gs-legacy-mortality-as-motivator",
    goal: "legacy", tier: "fundamental", section: "9215",
    title: "Use Mortality Awareness Deliberately",
    subtitle: "Death reminders push people to worldview defence — or to legacy — depending on the frame",
    evidenceTag: "Moderate",
    impact: { magnitude: 2, latency: "days", durability: "transient", effort: "low" },
    feeds: ["legacy motivation", "generosity to future others", "clarity about priorities"],
    description:
      "Terror management research shows that subtle reminders of death reliably shift attitudes and behaviour (meta-analytic r = .35 across 277 experiments), typically toward defending one's worldview and self-esteem; the effects are strongest when death thoughts are accessible but outside focal awareness. Wade-Benzoni's experiments show the same reminder, framed toward the future, increases willingness to leave a positive legacy for others. A comprehensive model of death anxiety names life review and life planning among the coping mechanisms. The protocol is to choose the legacy frame on purpose.",
    action: "Once a month, spend ten minutes writing the answer to 'if I had one year left, what would I want to have finished and passed on?' — then move one of those items onto this month's calendar. Keep the exercise brief; the effect is a nudge, not a mood.",
    sources: [
      { cite: "Greenberg, J., Pyszczynski, T., Solomon, S., Simon, L., & Breus, M. (1994). Role of consciousness and accessibility of death-related thoughts in mortality salience effects. Journal of Personality and Social Psychology, 67(4), 627-37.", note: "Mortality-salience effects occurred only when death thoughts were highly accessible but outside conscious attention, and were specific to death rather than other aversive events.", link: doi("10.1037/0022-3514.67.4.627"), kind: "doi" },
      { cite: "Burke, B. L., Martens, A., & Faucher, E. H. (2010). Two decades of terror management theory: a meta-analysis of mortality salience research. Personality and Social Psychology Review, 14(2), 155-95.", note: "Meta-analysis of 164 articles and 277 experiments: mortality salience produced moderate effects (r = .35) on worldview- and self-esteem-related outcomes.", link: doi("10.1177/1088868309352321"), kind: "doi" },
      { cite: "Tomer, A., & Eliason, G. (1996). Toward a comprehensive model of death anxiety. Death Studies, 20(4), 343-65.", note: "Comprehensive model of death anxiety naming past- and future-related regret and meaningfulness of death as antecedents, and life review and life planning as coping mechanisms.", link: doi("10.1080/07481189608252787"), kind: "doi" },
      { cite: "Wade-Benzoni, K. A., Tost, L. P., Hernandez, M., & Larrick, R. P. (2012). It's only a matter of time: death, legacies, and intergenerational decisions. Psychological science, 23(7), 704-9.", note: "Experiments on intergenerational decisions: reminders of mortality increased people's willingness to benefit future others, consistent with a legacy motive.", link: doi("10.1177/0956797612443967"), kind: "doi" },
    ],
  },
  {
    id: "gs-legacy-family-enactment",
    goal: "legacy", tier: "elite", section: "9216",
    title: "The Legacy Project: Make Something Together, Over Years",
    subtitle: "A scrapbook, a cookbook, recorded stories — built by the family, not for it",
    evidenceTag: "Moderate",
    impact: { magnitude: 4, latency: "months", durability: "lasting", effort: "high" },
    feeds: ["family communication", "positive emotion in patient and caregiver", "meaning in life for caregivers"],
    description:
      "The Legacy Project trials paired an ill older adult with a family caregiver and an interventionist (later, trained senior volunteers) across three home visits to create a personal legacy — a scrapbook, a cookbook, audiotaped stories. Every family in the pilot started a project and reported better communication; the randomized trial found greater reductions in patients' emotional symptoms and bother and improved spiritual functioning, and caregivers endorsed more meaning in life. Only one effect persisted after volunteer contact stopped, which is why this is elite: the practice has to keep going, with the volunteers describing it as deeply rewarding for them too.",
    action: "Start one tangible family legacy object this year — a printed family cookbook with a story per recipe, a photo book per decade, or an audio archive — and assign each generation a role. Set a fixed monthly session and a delivery date for the first edition twelve months out, then plan the second.",
    sources: [
      { cite: "Allen, R. S. (2009). The Legacy Project Intervention to Enhance Meaningful Family Interactions: Case Examples. Clinical Gerontologist, 32(2), 164-176.", note: "Legacy Project pilot: 17 chronically ill adults and caregivers received three home visits to build a legacy (scrapbook, cookbook, taped stories); all initiated a project and reported improved family communication and more positive emotion.", link: doi("10.1080/07317110802677005"), kind: "doi" },
      { cite: "Allen, R. S., Harris, G. M., Burgio, L. D., & Azuero, C. B. (2014). Can Senior Volunteers Deliver Reminiscence and Creative Activity Interventions? Results of the Legacy Intervention Family Enactment Randomized Controlled Trial. Journal of Pain and Symptom Management, 48(4), 590-601.", note: "Legacy Intervention Family Enactment RCT delivered by senior volunteers: intervention patients had greater reductions in emotional-symptom frequency and bother and improved spiritual functioning; caregivers endorsed more meaning in life; most effects faded after contact ended.", link: doi("10.1016/j.jpainsymman.2013.11.012"), kind: "doi" },
      { cite: "Allen, R. S., Azuero, C. B., Csikai, E. L., Parmelee, P. A., Shin, H. J., Kvale, E., …, & Burgio, L. D. (2016). \"It Was Very Rewarding for Me …\": Senior Volunteers' Experiences With Implementing a Reminiscence and Creative Activity Intervention. The Gerontologist, 56(2), 357-67.", note: "Senior volunteers who delivered the intervention reported personal benefit and increased meaning in life, and all chose to work with additional families.", link: doi("10.1093/geront/gnu167"), kind: "doi" },
      { cite: "Akard, T. F., Dietrich, M. S., Friedman, D. L., Wray, S., Gerhardt, C. A., Hendricks-Ferguson, V., …, & Gilmer, M. J. (2021). Randomized Clinical Trial of a Legacy Intervention for Quality of Life in Children with Advanced Cancer. Journal of Palliative Medicine, 24(5), 680-688.", note: "The pediatric web-based legacy RCT (97 dyads) — feasible and acceptable but a null result on quality of life, a reminder that the process, not a single artefact, carries the value.", link: doi("10.1089/jpm.2020.0139"), kind: "doi" },
      { cite: "Akard, T. F., Dietrich, M. S., Friedman, D. L., Gerhardt, C. A., Given, B., Hendricks-Ferguson, V., …, & Gilmer, M. J. (2021). Improved Parent-Child Communication following a RCT Evaluating a Legacy Intervention for Children with Advanced Cancer. Progress in Palliative Care, 29(3), 130-139.", note: "Secondary outcomes of the same trial: meaningful improvements in parent–child communication, strongest for fathers.", link: doi("10.1080/09699260.2020.1826778"), kind: "doi" },
      { cite: "Vuksanovic, D., Green, H. J., Dyck, M., & Morrissey, S. A. (2017). Dignity Therapy and Life Review for Palliative Care Patients: A Randomized Controlled Trial. Journal of Pain and Symptom Management, 53(2), 162-170.e1.", note: "Creating a legacy document, not life review alone, raised generativity and ego integrity in a randomized palliative-care trial.", link: doi("10.1016/j.jpainsymman.2016.09.005"), kind: "doi" },
    ],
  },
];
