// Goal shelf: PARENTING — be a better parent: children who thrive, and the best memories (sections 8100–8199).
// Verification: every DOI below was resolved against the Crossref record or the
// PubMed record on 2026-09-11 (see the shelf ledger). See types.ts for the contract.
import { doi, type GoalShelfCluster } from "./types";

export const SECTIONS: Record<string, string> = {
  "8100": "How to Read This Shelf",
  "8101": "Parenting Style — Warmth Plus Structure",
  "8102": "Talk, Read & Serve-and-Return — the Language Environment",
  "8103": "Praise & Mindset — What Actually Replicates",
  "8104": "Chores, Contribution & Self-Control",
  "8105": "Children's Sleep — the Bedtime Routine",
  "8106": "Screens — the Honest Evidence and a Family Media Plan",
  "8107": "Movement — Physical Activity, Brains & Grades",
  "8108": "Family Meals, Rituals & the Memories That Last",
  "8109": "Autonomy Support — Choices, Reasons & Perspective-Taking",
  "8110": "Discipline Without Hitting — the Spanking Evidence",
  "8111": "Parent Management Training — Incredible Years, Triple P & Kin",
  "8112": "Parenting Stress — Mindful Parenting Programs",
  "8113": "Fathers — Involvement That Shows Up Decades Later",
  "8114": "Adolescents — Knowing Through Trust, Not Surveillance",
  "8115": "Helicopter Parenting — Why Hovering Backfires",
  "8116": "Music Lessons & Enrichment — the Transfer Myth",
  "8117": "Warmth's Long Reach — Childhood Climate and Adult Health",
  "8118": "The Responsive-Parenting System — Years, Not Weeks",
};

export const CLUSTERS: GoalShelfCluster[] = [
  {
    id: "gs-parenting-read-me-first",
    goal: "parenting", tier: "fundamental", section: "8100",
    title: "How to Read the Parenting Shelf",
    subtitle: "Protocols, not verdicts on you — pick one per tier each month",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "low" },
    description:
      "Every protocol here is tagged fundamental, moderate, advanced or elite and ends in a concrete step. The best-replicated findings in this field are modest, cumulative and about daily patterns — talk, reading, sleep, warmth with limits — not about any single enrichment purchase. Two or three clusters are rated at the floor on purpose: the shelf tells you what does not work as loudly as what does.",
    action: "This month, choose the one fundamental protocol on this shelf you are not already doing (bedtime routine, reading aloud, a family meal) and run it daily for 30 days before adding anything else.",
    sources: [
      { cite: "Jeong, J., Franchett, E. E., Ramos de Oliveira, C. V., Rehmani, K., & Yousafzai, A. K. (2021). Parenting interventions to promote early child development in the first three years of life: A global systematic review and meta-analysis. PLoS Medicine.", note: "A global meta-analysis of 102 randomized trials of parenting interventions in the first three years: pooled gains in cognitive (SMD 0.32), language (0.28), motor and socioemotional development, with larger effects for programs focused on responsive caregiving — the floor every cluster on this shelf builds on.", link: doi("10.1371/journal.pmed.1003602"), kind: "doi" },
    ],
  },
  {
    id: "gs-parenting-authoritative-style",
    goal: "parenting", tier: "fundamental", section: "8101",
    title: "Authoritative Parenting: High Warmth, High Expectations",
    subtitle: "The one style finding that has held up for sixty years",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "months", durability: "lasting", effort: "moderate" },
    feeds: ["self-regulation", "school engagement", "trust between parent and child"],
    description:
      "Since Baumrind's 1966 observations, adolescents who describe their parents as both demanding and responsive (authoritative) show the strongest competence and the least substance use and distress, while the authoritarian, indulgent and neglectful patterns each carry a characteristic cost. Darling and Steinberg's model explains why: style is the emotional climate that makes specific practices land. These are observational findings, so they describe an association, not a guarantee.",
    action: "Write two lists this week — the three non-negotiable rules in your home and the three ways your child knows you are on their side — and say both out loud to them. Re-read the lists monthly and notice which side you are neglecting.",
    sources: [
      { cite: "Baumrind, D. (1966). Effects of Authoritative Parental Control on Child Behavior. Child Development, 37(4), 887.", note: "Baumrind's foundational Child Development study linked authoritative control (firm, reasoned, warm) with more competent child behaviour than either permissive or authoritarian control.", link: doi("10.2307/1126611"), kind: "doi" },
      { cite: "Baumrind, D. (1991). The Influence of Parenting Style on Adolescent Competence and Substance Use. The Journal of Early Adolescence, 11(1), 56-95.", note: "In the Family Socialization longitudinal program (139 adolescents rated at ages 4, 9 and 15), authoritative parents who were highly demanding and highly responsive were 'remarkably successful' in protecting adolescents from problem drug use and in generating competence.", link: doi("10.1177/0272431691111004"), kind: "doi" },
      { cite: "Lamborn, S. D., Mounts, N. S., Steinberg, L., & Dornbusch, S. M. (1991). Patterns of competence and adjustment among adolescents from authoritative, authoritarian, indulgent, and neglectful families. Child development, 62(5), 1049-65.", note: "Roughly 4,100 14–18-year-olds classified into authoritative, authoritarian, indulgent and neglectful families: authoritative homes scored best on competence and adjustment; neglectful homes worst.", link: doi("10.1111/j.1467-8624.1991.tb01588.x"), kind: "doi" },
      { cite: "Steinberg, L., Lamborn, S. D., Dornbusch, S. M., & Darling, N. (1992). Impact of parenting practices on adolescent achievement: authoritative parenting, school involvement, and encouragement to succeed. Child development, 63(5), 1266-81.", note: "Authoritative parenting predicted adolescent school achievement, and parental school involvement only helped when it occurred inside an authoritative climate.", link: doi("10.1111/j.1467-8624.1992.tb01694.x"), kind: "doi" },
      { cite: "Darling, N., & Steinberg, L. (1993). Parenting style as context: An integrative model. Psychological Bulletin, 113(3), 487-496.", note: "The integrative model that separates parenting style (the climate) from parenting practices (the behaviours), explaining why the same practice works in one home and not another.", link: doi("10.1037/0033-2909.113.3.487"), kind: "doi" },
      { cite: "Grolnick, W. S., Ryan, R. M., & Deci, E. L. (1991). Inner resources for school achievement: Motivational mediators of children's perceptions of their parents. Journal of Educational Psychology, 83(4), 508-517.", note: "Children's perceptions of parental autonomy support and involvement predicted school achievement through inner motivational resources — the mechanism behind 'warmth plus structure'.", link: doi("10.1037/0022-0663.83.4.508"), kind: "doi" },
    ],
  },
  {
    id: "gs-parenting-read-aloud-daily",
    goal: "parenting", tier: "fundamental", section: "8102",
    title: "Read Aloud Every Day, Dialogically",
    subtitle: "Ten minutes of shared books — ask, expand, let the child talk",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "months", durability: "lasting", effort: "low" },
    feeds: ["vocabulary and emergent literacy", "parent–child warmth", "lower parenting stress"],
    description:
      "The meta-analytic case for shared book reading is one of the strongest in parenting: parent–preschooler reading explains about 8% of variance in language and later reading (d = .59), and the dialogic style — asking, expanding, handing the story to the child — adds value on top of simple reading. Randomized primary-care trials (Video Interaction Project) show reading-and-play coaching reduces hyperactivity and aggression and raises cognitive stimulation for years, and shared reading at 6 months predicts warmer, less stressed parenting at 18 months.",
    action: "Read one book with your child every day this month at the same time, and ask at least three open questions per book ('what do you think happens next?'). Keep a tally on the fridge; aim for 25 of 30 days.",
    sources: [
      { cite: "Bus, A. G., van IJzendoorn, M. H., & Pellegrini, A. D. (1995). Joint Book Reading Makes for Success in Learning to Read: A Meta-Analysis on Intergenerational Transmission of Literacy. Review of Educational Research, 65(1), 1-21.", note: "Meta-analysis of parent–preschooler book reading: overall d = .59 on language growth, emergent literacy and reading achievement, independent of family SES.", link: doi("10.3102/00346543065001001"), kind: "doi" },
      { cite: "Mol, S. E., Bus, A. G., de Jong, M. T., & Smeets, D. J. H. (2008). Added Value of Dialogic Parent–Child Book Readings: A Meta-Analysis. Early Education and Development, 19(1), 7-26.", note: "Meta-analysis of dialogic reading trials showing added value over ordinary shared reading for expressive vocabulary, largest for younger children.", link: doi("10.1080/10409280701838603"), kind: "doi" },
      { cite: "Mendelsohn, A. L., Cates, C. B., Weisleder, A., Berkule Johnson, S., Seery, A. M., Canfield, C. F., …, & Dreyer, B. P. (2018). Reading Aloud, Play, and Social-Emotional Development. Pediatrics, 141(5).", note: "Randomized trial of a pediatric primary-care reading-and-play intervention (Video Interaction Project): reduced hyperactivity and aggression into early school age.", link: doi("10.1542/peds.2017-3393"), kind: "doi" },
      { cite: "Cates, C. B., Weisleder, A., Berkule Johnson, S., Seery, A. M., Canfield, C. F., Huberman, H., …, & Mendelsohn, A. L. (2018). Enhancing Parent Talk, Reading, and Play in Primary Care: Sustained Impacts of the Video Interaction Project. The Journal of Pediatrics.", note: "In 546 low-income families, VIP raised reading, verbal responsivity and overall cognitive stimulation (0.38 SD), with impacts persisting 1.5 years after the program ended.", link: doi("10.1016/j.jpeds.2018.03.002"), kind: "doi" },
      { cite: "Canfield, C. F., Miller, E. B., Shaw, D. S., Morris, P., Alonso, A., & Mendelsohn, A. L. (2020). Beyond language: Impacts of shared reading on parenting stress and early parent-child relational health. Developmental Psychology.", note: "Among 293 low-income mother–infant dyads, shared book reading at 6 months predicted higher observed warmth and sensitivity and lower parenting stress at 18 months.", link: doi("10.1037/dev0000940"), kind: "doi" },
      { cite: "Chow, B. W.-Y., McBride-Chang, C., Cheung, H., & Chow, C. S.-L. (2008). Dialogic reading and morphology training in Chinese children: effects on language and literacy. Developmental Psychology.", note: "Randomized trial of 148 kindergartners: 12 weeks of dialogic reading produced greater vocabulary gains and higher reading interest than typical reading.", link: doi("10.1037/0012-1649.44.1.233"), kind: "doi" },
    ],
  },
  {
    id: "gs-parenting-conversational-turns",
    goal: "parenting", tier: "moderate", section: "8102",
    title: "Serve-and-Return: Count Conversational Turns, Not Words",
    subtitle: "Responsive back-and-forth in the 18–24-month window predicts IQ a decade later",
    evidenceTag: "Moderate",
    impact: { magnitude: 4, latency: "months", durability: "lasting", effort: "moderate" },
    feeds: ["language processing speed", "later verbal IQ", "attachment security"],
    description:
      "Day-long home recordings show it is the number of adult–child conversational turns — not the raw count of words overheard — that predicts language processing at 24 months, brain activation in Broca's area at 4–6, and IQ and vocabulary ten years later after controlling for SES. Responsive-parenting coaching (PALS) is the randomized version: parents taught to notice signals and respond contingently produced gains in child language and social skills, with the largest effects when started in infancy and continued into toddlerhood. The correlational studies are small; treat them as the mechanism behind the trials.",
    action: "For four weeks, pick one daily 15-minute 'no phone' block (bath, dinner, the walk to school) and make it a rule that every child utterance gets a response that adds one idea. Once a week, record ten minutes and count the turns; try to beat last week.",
    sources: [
      { cite: "Weisleder, A., & Fernald, A. (2013). Talking to children matters: early language experience strengthens processing and builds vocabulary. Psychological science, 24(11), 2143-52.", note: "All-day home recordings in low-SES Spanish-speaking families: infants who heard more child-directed speech processed familiar words more efficiently and had larger expressive vocabularies by 24 months; overheard speech was unrelated.", link: doi("10.1177/0956797613488145"), kind: "doi" },
      { cite: "Gilkerson, J., Richards, J. A., Warren, S. F., Montgomery, J. K., Greenwood, C. R., Kimbrough Oller, D., …, & Paul, T. D. (2017). Mapping the Early Language Environment Using All-Day Recordings and Automated Analysis. American journal of speech-language pathology, 26(2), 248-265.", note: "The LENA day-long recording study that mapped adult words, child vocalizations and conversational turns across the early language environment.", link: doi("10.1044/2016_AJSLP-15-0169"), kind: "doi" },
      { cite: "Gilkerson, J., Richards, J. A., Warren, S. F., Oller, D. K., Russo, R., & Vohr, B. (2018). Language Experience in the Second Year of Life and Language Outcomes in Late Childhood. Pediatrics, 142(4).", note: "146 infants recorded monthly: conversational turns at 18–24 months explained 14–27% of the variance in IQ and vocabulary at ages 9–14 after controlling for SES; adult word counts alone did not survive that control.", link: doi("10.1542/peds.2017-4276"), kind: "doi" },
      { cite: "Romeo, R. R., Leonard, J. A., Robinson, S. T., West, M. R., Mackey, A. P., Rowe, M. L., & Gabrieli, J. D. E. (2018). Beyond the 30-Million-Word Gap: Children's Conversational Exposure Is Associated With Language-Related Brain Function. Psychological Science, 29(5), 700-710.", note: "In 36 children aged 4–6, more conversational turns predicted stronger Broca's-area activation during story listening, independent of SES, IQ and adult words — a neural mechanism for serve-and-return.", link: doi("10.1177/0956797617742725"), kind: "doi" },
      { cite: "Landry, S. H., Smith, K. E., Swank, P. R., & Guttentag, C. (2008). A responsive parenting intervention: the optimal timing across early childhood for impacting maternal behaviors and child outcomes. Developmental psychology, 44(5), 1335-53.", note: "Randomized responsive-parenting intervention (PALS): the strongest effects on maternal responsiveness and child language and social outcomes came when coaching began in infancy and continued into toddlerhood.", link: doi("10.1037/a0013030"), kind: "doi" },
      { cite: "Jeong, J., Franchett, E. E., Ramos de Oliveira, C. V., Rehmani, K., & Yousafzai, A. K. (2021). Parenting interventions to promote early child development in the first three years of life: A global systematic review and meta-analysis. PLoS Medicine.", note: "Across 102 RCTs, programs that focused on responsive caregiving produced significantly larger gains in cognitive development and parent–child interaction than those that did not.", link: doi("10.1371/journal.pmed.1003602"), kind: "doi" },
    ],
  },
  {
    id: "gs-parenting-process-praise",
    goal: "parenting", tier: "moderate", section: "8103",
    title: "Praise the Process, Skip the 'You're So Smart'",
    subtitle: "A real but small effect — and the mindset claims built on it did not replicate",
    evidenceTag: "Mixed",
    impact: { magnitude: 2, latency: "months", durability: "sustained", effort: "low" },
    callout: "Honest boundary: the original lab effect (intelligence praise undermines persistence) is solid and parent process-praise does predict later beliefs, but the wider growth-mindset literature shows small, inconsistent achievement effects and a failed large replication. Use process praise because it is cheap and does no harm, not because it will transform grades.",
    description:
      "Mueller and Dweck's experiments showed that praising a child's intelligence after success made them choose easier tasks and collapse after failure, while praising effort and strategy did the opposite; a five-year home study found parents' process praise to toddlers predicted incremental beliefs later. But two meta-analyses of growth-mindset interventions find small average effects on achievement, and a large UK sample found mindset unrelated to educational attainment or response to setbacks. Keep the practice; drop the hype.",
    action: "For the next month, replace every 'good job' or 'you're smart' with one specific sentence about what the child did ('you kept trying different ways to fit the piece'). Ask your partner to catch you when you slip.",
    sources: [
      { cite: "Mueller, C. M., & Dweck, C. S. (1998). Praise for intelligence can undermine children's motivation and performance. Journal of personality and social psychology, 75(1), 33-52.", note: "Six lab studies with fifth-graders: praise for intelligence led children to choose performance goals, show less persistence and enjoyment after failure and even misrepresent scores; process praise did the reverse.", link: doi("10.1037/0022-3514.75.1.33"), kind: "doi" },
      { cite: "Gunderson, E. A., Gripshover, S. J., Romero, C., Dweck, C. S., Goldin-Meadow, S., & Levine, S. C. (2013). Parent praise to 1- to 3-year-olds predicts children's motivational frameworks 5 years later. Child development, 84(5), 1526-41.", note: "Naturalistic home observations: the proportion of process praise parents gave 1–3-year-olds predicted children's incremental beliefs and preference for challenge five years later.", link: doi("10.1111/cdev.12064"), kind: "doi" },
      { cite: "Sisk, V. F., Burgoyne, A. P., Sun, J., Butler, J. L., & Macnamara, B. N. (2018). To What Extent and Under Which Circumstances Are Growth Mind-Sets Important to Academic Achievement? Two Meta-Analyses. Psychological science, 29(4), 549-571.", note: "Two meta-analyses: growth mindset correlates weakly with achievement, and mindset interventions produce small average effects, with benefits concentrated in some at-risk groups.", link: doi("10.1177/0956797617739704"), kind: "doi" },
      { cite: "Li, Y., & Bates, T. C. (2019). You can't change your basic ability, but you work at things, and that's how we get hard things done: Testing the role of growth mindset on response to setbacks, educational attainment, and cognitive ability. Journal of experimental psychology. General, 148(9), 1640-1655.", note: "In large samples, growth mindset did not predict cognitive ability, educational attainment or resilience to setbacks, questioning strong causal claims.", link: doi("10.1037/xge0000669"), kind: "doi" },
    ],
  },
  {
    id: "gs-parenting-chores-and-self-control",
    goal: "parenting", tier: "fundamental", section: "8104",
    title: "Give Real Chores, Grow Self-Control",
    subtitle: "Contribution in kindergarten, self-regulation for life",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "months", durability: "lasting", effort: "low" },
    feeds: ["self-competence", "prosocial behaviour", "executive function"],
    description:
      "In a US cohort of 9,971 kindergartners, doing chores predicted higher self-reported social, academic and life-satisfaction competence in third grade and better math scores, independent of income and parent education; children who rarely did chores had 17–27% higher odds of landing in the bottom quintile. The Dunedin cohort shows why self-control is worth building: a childhood self-control gradient predicted adult health, wealth and criminal offending, even between siblings. Executive-function reviews find every successful program shares repeated practice with rising challenge — which is what a chore ladder is.",
    action: "Assign each child two age-appropriate chores they own (not 'help with'), post them, and raise the difficulty every three months. Add one weekly act of kindness for someone outside the home; kids randomized to kind acts gained peer acceptance.",
    sources: [
      { cite: "White, E. M., DeBoer, M. D., & Scharf, R. J. (2019). Associations Between Household Chores and Childhood Self-Competency. Journal of Developmental & Behavioral Pediatrics, 40(3), 176-182.", note: "Longitudinal ECLS-K 2011 cohort (n = 9,971): chores in kindergarten predicted third-grade self-competence, prosocial behaviour, life satisfaction and math scores, adjusted for sex, income and parent education.", link: doi("10.1097/DBP.0000000000000637"), kind: "doi" },
      { cite: "Moffitt, T. E., Arseneault, L., Belsky, D., Dickson, N., Hancox, R. J., Harrington, H., …, & Caspi, A. (2011). A gradient of childhood self-control predicts health, wealth, and public safety. Proceedings of the National Academy of Sciences, 108(7), 2693-8.", note: "The Dunedin cohort of 1,000 children followed to age 32: a gradient of childhood self-control predicted physical health, substance dependence, personal finances and offending, disentangled from IQ and social class and replicated between siblings.", link: doi("10.1073/pnas.1010076108"), kind: "doi" },
      { cite: "Diamond, A., & Lee, K. (2011). Interventions shown to aid executive function development in children 4 to 12 years old. Science, 333(6045), 959-64.", note: "Review of interventions that improve executive functions in 4–12-year-olds: all successful programs involve repeated practice with progressively increasing challenge, and children with the weakest skills benefit most.", link: doi("10.1126/science.1204529"), kind: "doi" },
      { cite: "Layous, K., Nelson, S. K., Oberle, E., Schonert-Reichl, K. A., & Lyubomirsky, S. (2012). Kindness counts: prompting prosocial behavior in preadolescents boosts peer acceptance and well-being. PLoS One, 7(12), e51380.", note: "Classroom experiment with 9–11-year-olds: four weeks of three kind acts per week raised well-being and produced larger gains in peer acceptance than a control activity.", link: doi("10.1371/journal.pone.0051380"), kind: "doi" },
    ],
  },
  {
    id: "gs-parenting-bedtime-routine",
    goal: "parenting", tier: "fundamental", section: "8105",
    title: "Protect Sleep With a Consistent Bedtime Routine",
    subtitle: "The same four steps, the same order, every night",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "weeks", durability: "sustained", effort: "low" },
    feeds: ["emotional regulation", "attention and learning", "parent mood"],
    description:
      "Systematic reviews link longer sleep in school-aged children to better emotional regulation, academic performance and quality of life and lower adiposity, though the evidence base is mostly observational and the exact hours a child 'needs' rest on thin data. The intervention evidence is cleaner: a consistent nightly routine improves sleep onset, night wakings and maternal mood, with improvements visible within the first few nights of implementation and dose-dependent on how many nights a week it is kept.",
    action: "Choose a four-step routine (bath, pyjamas, book, lights out) and a fixed lights-out time, and run it seven nights a week for a month. Track wake-ups on a paper chart; expect the first gains inside a week.",
    sources: [
      { cite: "Chaput, J. P., Gray, C. E., Poitras, V. J., Carson, V., Gruber, R., Olds, T., …, & Tremblay, M. S. (2016). Systematic review of the relationships between sleep duration and health indicators in school-aged children and youth. Applied physiology, nutrition, and metabolism = Physiologie appliquee, nutrition et metabolisme, 41(6 Suppl 3), S266-82.", note: "Systematic review of 141 articles (592,215 participants aged 5–17): longer sleep duration was associated with lower adiposity, better emotional regulation, academic achievement and quality of life.", link: doi("10.1139/apnm-2015-0627"), kind: "doi" },
      { cite: "Matricciani, L., Blunden, S., Rigney, G., Williams, M. T., & Olds, T. S. (2013). Children's sleep needs: is there sufficient evidence to recommend optimal sleep for children?. Sleep, 36(4), 527-34.", note: "Critical appraisal finding that recommended sleep durations for children rest on limited evidence — a reason to focus on routine and consistency rather than a magic number.", link: doi("10.5665/sleep.2538"), kind: "doi" },
      { cite: "Matricciani, L., Paquet, C., Galland, B., Short, M., & Olds, T. (2019). Children's sleep and health: A meta-review. Sleep medicine reviews, 46, 136-150.", note: "Meta-review of children's sleep and health synthesizing the systematic reviews on duration, quality and timing across cognitive, emotional and physical outcomes.", link: doi("10.1016/j.smrv.2019.04.011"), kind: "doi" },
      { cite: "Mindell, J. A., & Williamson, A. A. (2017). Benefits of a bedtime routine in young children: Sleep, development, and beyond. Sleep medicine reviews, 40, 93-108.", note: "Review of bedtime routines in young children: consistent routines are associated with better sleep, language, literacy and emotional-behavioural outcomes, plus parent benefits.", link: doi("10.1016/j.smrv.2017.10.007"), kind: "doi" },
      { cite: "Mindell, J. A., Leichman, E. S., Lee, C., Williamson, A. A., & Walters, R. M. (2017). Implementation of a nightly bedtime routine: How quickly do things improve?. Infant behavior & development, 49, 220-227.", note: "Implementation study of a nightly bedtime routine: sleep improvements appeared within the first few nights and grew with the number of nights per week the routine was kept.", link: doi("10.1016/j.infbeh.2017.09.013"), kind: "doi" },
    ],
  },
  {
    id: "gs-parenting-family-media-plan",
    goal: "parenting", tier: "moderate", section: "8106",
    title: "Write a Family Media Plan — Without the Panic",
    subtitle: "The screen effect is small and mostly about what it displaces",
    evidenceTag: "Mixed",
    impact: { magnitude: 2, latency: "weeks", durability: "sustained", effort: "moderate" },
    callout: "Honest boundary: the largest, best-controlled analyses find digital-technology use explains well under 1% of the variance in adolescent well-being — comparable to eating potatoes. Heavy use (many hours daily) does track with poorer outcomes in cohort studies, and a Canadian cohort found early screen time predicts later developmental-screening scores, so the defensible rule is 'protect sleep, movement, reading and conversation first', not 'screens are poison'.",
    description:
      "Specification-curve analyses of 355,358 adolescents and three time-use-diary studies found associations between screen use and well-being that were negative but tiny, and no evidence they have grown since the 2000s. Against that, large US surveys show that very heavy users (7+ hours a day) have roughly double the rate of diagnosed anxiety or depression, a longitudinal panel found higher screen time at 24 and 36 months predicted poorer developmental screening later, and there appear to be age windows (11–13 for girls, 14–15 for boys) where social-media use predicts lower life satisfaction a year later. The plan that fits all of this: firm limits around sleep and meals, co-viewing when young, and no catastrophizing.",
    action: "This week, write a one-page family media plan with three rules everyone signs: no devices in bedrooms overnight, none at the table, and screens only after homework, movement and reading are done. Review it together at the end of the month.",
    sources: [
      { cite: "Orben, A., & Przybylski, A. K. (2019). The association between adolescent well-being and digital technology use. Nature human behaviour, 3(2), 173-182.", note: "Specification-curve analysis across three large-scale datasets (n = 355,358): the association between digital-technology use and adolescent well-being was negative but tiny, explaining at most 0.4% of the variance.", link: doi("10.1038/s41562-018-0506-1"), kind: "doi" },
      { cite: "Orben, A., & Przybylski, A. K. (2019). Screens, Teens, and Psychological Well-Being: Evidence From Three Time-Use-Diary Studies. Psychological science, 30(5), 682-696.", note: "Three nationally representative time-use-diary datasets from Ireland, the USA and the UK (N = 17,247): little clear-cut evidence that screen engagement decreases adolescent well-being, using both exploratory and confirmatory designs.", link: doi("10.1177/0956797619830329"), kind: "doi" },
      { cite: "Vuorre, M., Orben, A., & Przybylski, A. K. (2021). There is no evidence that associations between adolescents' digital technology engagement and mental health problems have increased. Clinical psychological science : a journal of the Association for Psychological Science, 9(5), 823-835.", note: "Three nationally representative samples: technology engagement became less strongly associated with depression over the past decade while social-media use became more associated with emotional problems — little evidence overall that the associations have increased.", link: doi("10.1177/2167702621994549"), kind: "doi" },
      { cite: "Madigan, S., Browne, D., Racine, N., Mori, C., & Tough, S. (2019). Association Between Screen Time and Children's Performance on a Developmental Screening Test. JAMA pediatrics, 173(3), 244-250.", note: "Random-intercepts cross-lagged panel of 2,441 Canadian children: higher screen time at 24 and 36 months predicted poorer developmental-screening performance at 36 and 60 months, not the reverse.", link: doi("10.1001/jamapediatrics.2018.5056"), kind: "doi" },
      { cite: "Ferguson, C. J. (2017). Everything in Moderation: Moderate Use of Screens Unassociated with Child Behavior Problems. Psychiatric Quarterly, 88(4), 797-805.", note: "Representative Florida youth sample: moderate screen use above the old AAP limit was unassociated with delinquency, risky behaviour, grades or mental health; excessive use was only weakly associated with depression, delinquency and grades.", link: doi("10.1007/s11126-016-9486-3"), kind: "doi" },
      { cite: "Twenge, J. M., & Campbell, W. K. (2018). Associations between screen time and lower psychological well-being among children and adolescents: Evidence from a population-based study. Preventive Medicine Reports, 12, 271-283.", note: "National US sample of 40,337 children and teens: after one hour a day, more screen time tracked with lower psychological well-being, and 7+ hours-a-day adolescents were about twice as likely to have been diagnosed with anxiety or depression.", link: doi("10.1016/j.pmedr.2018.10.003"), kind: "doi" },
      { cite: "Orben, A., Przybylski, A. K., Blakemore, S. J., & Kievit, R. A. (2022). Windows of developmental sensitivity to social media. Nature Communications, 13(1), 1649.", note: "UK data on 84,011 people: the negative link between social-media use and life satisfaction is concentrated in developmental windows (11–13 in girls, 14–15 in boys, and 19 in both), with effects running in both directions.", link: doi("10.1038/s41467-022-29296-3"), kind: "doi" },
      { cite: "Nagata, J. M., Chu, J., Ganson, K. T., Murray, S. B., Iyer, P., Gabriel, K. P., …, & Baker, F. C. (2022). Contemporary screen time modalities and disruptive behavior disorders in children: a prospective cohort study. Journal of child psychology and psychiatry, and allied disciplines, 64(1), 125-135.", note: "ABCD prospective cohort: contemporary screen-time modalities were associated with later disruptive behaviour disorders in 9–10-year-olds, supporting limits on the heaviest use.", link: doi("10.1111/jcpp.13673"), kind: "doi" },
    ],
  },
  {
    id: "gs-parenting-daily-movement",
    goal: "parenting", tier: "fundamental", section: "8107",
    title: "An Hour of Movement a Day — It Helps the Grades Too",
    subtitle: "Physical activity improves executive control and does not cost achievement",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "months", durability: "sustained", effort: "low" },
    feeds: ["executive function", "attention", "academic achievement"],
    description:
      "Systematic reviews and a 2017 meta-analysis find physical activity programs improve children's executive function, classroom behaviour and academic achievement, with the strongest evidence for mathematics and reading. The FITKids randomized trial gave 8–9-year-olds nine months of after-school activity and found gains in inhibitory control and cognitive flexibility alongside brain-function changes — the causal anchor beneath the correlational literature.",
    action: "Build 60 minutes of movement into every school day this month — a walk or bike to school, active play after school, a family sport at weekends — and time it before homework rather than as a reward after it.",
    sources: [
      { cite: "Singh, A., Uijtdewilligen, L., Twisk, J. W., van Mechelen, W., & Chinapaw, M. J. (2012). Physical activity and performance at school: a systematic review of the literature including a methodological quality assessment. Archives of pediatrics & adolescent medicine, 166(1), 49-55.", note: "Systematic review with methodological quality assessment: physical activity was positively related to academic performance in the higher-quality studies.", link: doi("10.1001/archpediatrics.2011.716"), kind: "doi" },
      { cite: "Donnelly, J. E., Hillman, C. H., Castelli, D., Etnier, J. L., Lee, S., Tomporowski, P., …, & Szabo-Reed, A. N. (2016). Physical Activity, Fitness, Cognitive Function, and Academic Achievement in Children: A Systematic Review. Medicine and science in sports and exercise, 48(6), 1197-222.", note: "American College of Sports Medicine review: physical activity and fitness benefit cognitive function and academic achievement in children without detracting from learning time.", link: doi("10.1249/MSS.0000000000000901"), kind: "doi" },
      { cite: "Álvarez-Bueno, C., Pesce, C., Cavero-Redondo, I., Sánchez-López, M., Garrido-Miguel, M., & Martínez-Vizcaíno, V. (2017). Academic Achievement and Physical Activity: A Meta-analysis. Pediatrics, 140(6).", note: "Meta-analysis in Pediatrics: physical-activity interventions improved academic achievement, especially mathematics and reading-related outcomes.", link: doi("10.1542/peds.2017-1498"), kind: "doi" },
      { cite: "Hillman, C. H., Pontifex, M. B., Castelli, D. M., Khan, N. A., Raine, L. B., Scudder, M. R., …, & Kamijo, K. (2014). Effects of the FITKids randomized controlled trial on executive control and brain function. Pediatrics, 134(4), e1063-71.", note: "FITKids randomized trial: nine months of daily after-school physical activity improved executive control and brain function in 8–9-year-olds versus wait-list.", link: doi("10.1542/peds.2013-3219"), kind: "doi" },
      { cite: "Drollette, E. S., Pontifex, M. B., Raine, L. B., Scudder, M. R., Moore, R. D., Kao, S. C., …, & Hillman, C. H. (2017). Effects of the FITKids physical activity randomized controlled trial on conflict monitoring in youth. Psychophysiology, 55(3).", note: "FITKids secondary analysis: the intervention improved conflict monitoring, an electrophysiological marker of the cognitive control that underlies classroom attention.", link: doi("10.1111/psyp.13017"), kind: "doi" },
    ],
  },
  {
    id: "gs-parenting-family-dinner",
    goal: "parenting", tier: "fundamental", section: "8108",
    title: "Five Family Meals a Week",
    subtitle: "A protected table, phones away, everyone talks",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "low" },
    feeds: ["adolescent emotional well-being", "nutrition", "family identity"],
    description:
      "Across large adolescent surveys, more frequent family meals track with less substance use, better grades, fewer depressive symptoms and better emotional well-being even after controlling for family connectedness, and a Pediatrics meta-analysis links three-plus shared meals a week to healthier weight and eating. These are observational associations — the mealtime is partly a marker of a functioning family — but mealtime is also where routines and rituals are enacted, which is the mechanism the next cluster builds on.",
    action: "Book five family meals this week on the calendar, put every phone in a basket by the door, and open each meal with one question everyone answers ('best and worst part of today'). Keep the count for a month.",
    sources: [
      { cite: "Eisenberg, M. E., Olson, R. E., Neumark-Sztainer, D., Story, M., & Bearinger, L. H. (2004). Correlations between family meals and psychosocial well-being among adolescents. Archives of Pediatrics & Adolescent Medicine, 158(8), 792-6.", note: "Survey of 4,746 Minnesota adolescents: family-meal frequency was inversely associated with tobacco, alcohol and marijuana use, low GPA, depressive symptoms and suicide involvement after controlling for family connectedness.", link: doi("10.1001/archpedi.158.8.792"), kind: "doi" },
      { cite: "Hammons, A. J., & Fiese, B. H. (2011). Is frequency of shared family meals related to the nutritional health of children and adolescents?. Pediatrics, 127(6), e1565-74.", note: "Meta-analysis in Pediatrics: children and adolescents sharing three or more family meals a week were more likely to be in a healthy weight range and to have healthier eating patterns.", link: doi("10.1542/peds.2010-1440"), kind: "doi" },
      { cite: "Utter, J., Denny, S., Peiris-John, R., Moselen, E., Dyson, B., & Clark, T. (2016). Family Meals and Adolescent Emotional Well-Being: Findings From a National Study. Journal of nutrition education and behavior, 49(1), 67-72.e1.", note: "National US study linking family meals to adolescent emotional well-being.", link: doi("10.1016/j.jneb.2016.09.002"), kind: "doi" },
      { cite: "Utter, J., Denny, S., Robinson, E., Fleming, T., Ameratunga, S., & Grant, S. (2013). Family meals and the well-being of adolescents. Journal of paediatrics and child health, 49(11), 906-911.", note: "New Zealand adolescent survey associating regular family meals with better well-being.", link: doi("10.1111/jpc.12428"), kind: "doi" },
      { cite: "Utter, J., Larson, N., Berge, J. M., Eisenberg, M. E., Fulkerson, J. A., & Neumark-Sztainer, D. (2018). Family meals among parents: Associations with nutritional, social and emotional wellbeing. Preventive medicine, 113, 7-12.", note: "Family meals were associated with better nutritional, social and emotional well-being among the parents themselves, not only the children.", link: doi("10.1016/j.ypmed.2018.05.006"), kind: "doi" },
      { cite: "Fiese, B. H., Foley, K. P., & Spagnola, M. (2006). Routine and ritual elements in family mealtimes: contexts for child well-being and family identity. New Directions for Child and Adolescent Development(111), 67-89.", note: "Fiese's analysis of the routine and ritual elements of family mealtimes as a context for child well-being and family identity.", link: doi("10.1002/cd.156"), kind: "doi" },
    ],
  },
  {
    id: "gs-parenting-family-story-archive",
    goal: "parenting", tier: "elite", section: "8108",
    title: "Become the Family Historian: Rituals and the Stories Children Carry",
    subtitle: "Fifty years of ritual research plus the 'Do You Know?' scale",
    evidenceTag: "Moderate",
    impact: { magnitude: 4, latency: "months", durability: "lasting", effort: "moderate" },
    feeds: ["children's sense of self", "family cohesion", "resilience under stress"],
    description:
      "Fifty years of research on naturally occurring family routines and rituals link them to child adjustment, marital satisfaction and family identity, and narrative studies show children whose families tell coherent, co-constructed stories about the past have a stronger sense of self. Adolescents who know more of their family history (the 20-item 'Do You Know?' scale) score higher on self-esteem and internal locus of control and lower on anxiety and behaviour problems. This is an association built over years — the elite move is to make story-telling and rituals a deliberate, multi-year practice.",
    action: "Start a family story practice this quarter: one intergenerational story at each Sunday meal (how grandparents met, a family setback and how it was survived), one photo-and-caption page a month in a shared album, and one yearly ritual you never cancel. Give the 20 'Do You Know?' questions to your kids once a year and fill the gaps.",
    sources: [
      { cite: "Fiese, B. H., Tomcho, T. J., Douglas, M., Josephs, K., Poltrock, S., & Baker, T. (2002). A review of 50 years of research on naturally occurring family routines and rituals: cause for celebration?. Journal of family psychology : JFP : journal of the Division of Family Psychology of the American Psychological Association (Division 43), 16(4), 381-90.", note: "Review of 50 years of research: family routines and rituals are associated with child adjustment, health and family identity, with rituals carrying the symbolic meaning that predicts well-being.", link: doi("10.1037/0893-3200.16.4.381"), kind: "doi" },
      { cite: "Spagnola, M., & Fiese, B. H. (2007). Family Routines and Rituals. Infants & Young Children, 20(4), 284-299.", note: "Spagnola and Fiese on routines and rituals as a context for development in young children, distinguishing predictable routines from meaning-laden rituals.", link: doi("10.1097/01.IYC.0000290352.32170.5a"), kind: "doi" },
      { cite: "Bohanek, J. G., Marin, K. A., Fivush, R., & Duke, M. P. (2006). Family narrative interaction and children's sense of self. Family process, 45(1), 39-54.", note: "Observed family dinner-table narratives: families who co-constructed stories collaboratively had preadolescents with a stronger, more secure sense of self.", link: doi("10.1111/j.1545-5300.2006.00079.x"), kind: "doi" },
      { cite: "Duke, M. P., Lazarus, A., & Fivush, R. (2008). Knowledge of family history as a clinically useful index of psychological well-being and prognosis: A brief report. Psychotherapy: Theory, Research, Practice, Training, 45(2), 268-272.", note: "The 'Do You Know?' study: adolescents' knowledge of family history correlated with internal locus of control, higher self-esteem, better family functioning, lower anxiety and fewer behaviour problems.", link: doi("10.1037/0033-3204.45.2.268"), kind: "doi" },
      { cite: "Fivush, R., Bohanek, J. G., & Zaman, W. (2011). Personal and intergenerational narratives in relation to adolescents' well-being. New Directions for Child and Adolescent Development, 2011(131), 45-57.", note: "Personal and intergenerational narratives told by adolescents related to their well-being, with intergenerational stories adding to the child's own life story.", link: doi("10.1002/cd.288"), kind: "doi" },
      { cite: "Merrill, N., & Fivush, R. (2016). Intergenerational narratives and identity across development. Developmental Review, 40, 72-92.", note: "Developmental review of how intergenerational narratives shape identity across development — the theoretical basis for making family stories deliberate.", link: doi("10.1016/j.dr.2016.03.001"), kind: "doi" },
      { cite: "Elias, A., & Brown, A. D. (2022). The role of intergenerational family stories in mental health and wellbeing. Frontiers in Psychology, 13.", note: "Review of the emerging evidence that intergenerational knowledge of family history is associated with positive mental health and well-being, and of culture and gender as moderators.", link: doi("10.3389/fpsyg.2022.927795"), kind: "doi" },
    ],
  },
  {
    id: "gs-parenting-autonomy-support",
    goal: "parenting", tier: "moderate", section: "8109",
    title: "Autonomy Support: Choices, Reasons, Their Point of View",
    subtitle: "Structure without control — the self-determination playbook",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "months", durability: "lasting", effort: "moderate" },
    feeds: ["intrinsic motivation", "academic achievement", "adolescent disclosure"],
    description:
      "A meta-analysis of parental autonomy support finds it associated with higher academic achievement and better psychosocial functioning, and the self-determination account explains the ingredients: offer choices within limits, give reasons for rules, and acknowledge the child's perspective. Children who perceive parents as autonomy-supportive show more inner motivational resources at school, and teenagers who feel controlled adjust worse even when parents know a lot about their lives.",
    action: "For one month, before any instruction, add one of three moves: offer a bounded choice ('bath before or after the book?'), give the reason in one sentence, or reflect their view first ('you're in the middle of something — two minutes, then it's time'). Count how often you managed it each evening.",
    sources: [
      { cite: "Joussemet, M., Landry, R., & Koestner, R. (2008). A self-determination theory perspective on parenting. Canadian Psychology / Psychologie canadienne, 49(3), 194-200.", note: "Self-determination-theory account of parenting: autonomy support (choice, rationale, perspective-taking) versus control, and its links to child well-being.", link: doi("10.1037/a0012754"), kind: "doi" },
      { cite: "Grolnick, W. S., Ryan, R. M., & Deci, E. L. (1991). Inner resources for school achievement: Motivational mediators of children's perceptions of their parents. Journal of Educational Psychology, 83(4), 508-517.", note: "Children's perceptions of parental autonomy support and involvement predicted school achievement via inner motivational resources (autonomy, competence, control understanding).", link: doi("10.1037/0022-0663.83.4.508"), kind: "doi" },
      { cite: "Vasquez, A. C., Patall, E. A., Fong, C. J., Corrigan, A. S., & Pine, L. (2016). Parent Autonomy Support, Academic Achievement, and Psychosocial Functioning: a Meta-analysis of Research. Educational Psychology Review, 28(3), 605-644.", note: "Meta-analysis of parent autonomy support finding positive associations with academic achievement and psychosocial functioning across studies.", link: doi("10.1007/s10648-015-9329-z"), kind: "doi" },
      { cite: "Kerr, M., & Stattin, H. (2000). What parents know, how they know it, and several forms of adolescent adjustment: Further support for a reinterpretation of monitoring. Developmental Psychology, 36(3), 366-380.", note: "1,186 Swedish 14-year-olds: parents' control efforts related to good adjustment only after partialling out the child's feeling of being controlled, which was linked to poor adjustment.", link: doi("10.1037/0012-1649.36.3.366"), kind: "doi" },
    ],
  },
  {
    id: "gs-parenting-no-spanking",
    goal: "parenting", tier: "fundamental", section: "8110",
    title: "Spanking: Rated at the Floor",
    subtitle: "Two meta-analyses and 69 prospective studies point the same way",
    evidenceTag: "Strong",
    impact: { magnitude: 1, latency: "days", durability: "lasting", effort: "low" },
    callout: "Debunked: physical punishment has no demonstrated benefit beyond immediate compliance and is consistently associated with more aggression, more later behaviour problems and worse mental health, with quasi-experimental studies showing worsening over time. Rated at the floor so the library counts it as harmful, not neutral. The replacement is the parent-training toolkit in 8111.",
    description:
      "Gershoff's 2002 meta-analysis across 11 child outcomes found corporal punishment associated with higher aggression and lower moral internalization and mental health; the 2016 update separating spanking from abuse still found no evidence of improved behaviour and adverse outcomes across 111 effect sizes; the 2021 Lancet review of 69 prospective longitudinal studies concluded physical punishment predicts increases in behaviour problems over time and is not associated with any positive outcome. Group parent-training programs are the evidence-based alternative.",
    action: "Decide today that hitting is off the table, tell your co-parent and your children, and replace it with one pre-planned consequence ladder (warning, brief time-out or loss of privilege) written on the fridge. If you find yourself unable to keep the rule, that is the signal to enrol in a parent-training group (8111).",
    sources: [
      { cite: "Gershoff, E. T. (2002). Corporal punishment by parents and associated child behaviors and experiences: a meta-analytic and theoretical review. Psychological Bulletin, 128(4), 539-79.", note: "Meta-analytic review across 11 child constructs: parental corporal punishment was associated with immediate compliance but also with more aggression, less moral internalization and poorer mental health.", link: doi("10.1037/0033-2909.128.4.539"), kind: "doi" },
      { cite: "Gershoff, E. T., & Grogan-Kaylor, A. (2016). Spanking and child outcomes: Old controversies and new meta-analyses. Journal of family psychology : JFP : journal of the Division of Family Psychology of the American Psychological Association (Division 43), 30(4), 453-69.", note: "Meta-analyses isolating spanking from harsher abuse: across 111 effect sizes, spanking was associated with detrimental outcomes and showed no evidence of improving child behaviour.", link: doi("10.1037/fam0000191"), kind: "doi" },
      { cite: "Heilmann, A., Mehay, A., Watt, R. G., Kelly, Y., Durrant, J. E., van Turnhout, J., & Gershoff, E. T. (2021). Physical punishment and child outcomes: a narrative review of prospective studies. The Lancet, 398(10297), 355-364.", note: "Narrative review of 69 prospective longitudinal studies: physical punishment consistently predicts increases in child behaviour problems, is not associated with positive outcomes, and shows a dose–response relationship.", link: doi("10.1016/S0140-6736(21)00582-1"), kind: "doi" },
      { cite: "Barlow, J., Bergman, H., Kornør, H., Wei, Y., & Bennett, C. (2016). Group-based parent training programmes for improving emotional and behavioural adjustment in young children. The Cochrane database of systematic reviews, 2016(8), CD003680.", note: "Cochrane review of group-based parent-training programs: the evidence-based alternative for improving young children's emotional and behavioural adjustment.", link: doi("10.1002/14651858.CD003680.pub3"), kind: "doi" },
    ],
  },
  {
    id: "gs-parenting-incredible-years",
    goal: "parenting", tier: "advanced", section: "8111",
    title: "Enrol in a Group Parent-Training Program (Incredible Years)",
    subtitle: "Twelve to fourteen weekly sessions with a trained leader",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "months", durability: "sustained", effort: "high" },
    feeds: ["consistent positive discipline", "child conduct", "parent stress"],
    description:
      "Incredible Years is one of the best-tested parenting programs in existence: a meta-analysis of 50 studies finds it improves disruptive child behaviour (d = .27 across informants, d = .50 in treatment samples), a Norwegian RCT found two-thirds of children with ODD/CD functioning in the normal range after treatment, and a Dutch prevention trial found parent-reported reductions sustained 2.5 years later. Honest boundaries: teacher- and child-reported effects were not sustained in that trial, and it did not produce broader mental-health benefits — it is a conduct-problem tool, strongest for families with the most severe problems.",
    action: "If your child's behaviour is a daily struggle, search for an Incredible Years or equivalent group-based parent program near you (community mental-health centres, Head Start, pediatric clinics) and commit to attending all 12–14 weekly sessions this season with your co-parent.",
    sources: [
      { cite: "Menting, A. T., Orobio de Castro, B., & Matthys, W. (2013). Effectiveness of the Incredible Years parent training to modify disruptive and prosocial child behavior: a meta-analytic review. Clinical psychology review, 33(8), 901-13.", note: "Meta-analytic review of 50 Incredible Years parent-training studies: mean effect d = .27 on disruptive behaviour across informants, d = .50 in treatment samples, with larger effects for more severe cases.", link: doi("10.1016/j.cpr.2013.07.006"), kind: "doi" },
      { cite: "Webster-Stratton, C., Reid, M. J., & Hammond, M. (2004). Treating children with early-onset conduct problems: intervention outcomes for parent, child, and teacher training. Journal of clinical child and adolescent psychology : the official journal for the Society of Clinical Child and Adolescent Psychology, American Psychological Association, Division 53, 33(1), 105-24.", note: "Webster-Stratton's randomized comparison of parent, child and teacher training for early-onset conduct problems, establishing the combined-treatment effects.", link: doi("10.1207/S15374424JCCP3301_11"), kind: "doi" },
      { cite: "Reid, M. J., Webster-Stratton, C., & Baydar, N. (2004). Halting the development of conduct problems in Head Start children: the effects of parent training. Journal of Clinical Child and Adolescent Psychology.", note: "Head Start classrooms (882 children) randomized to Incredible Years: children with high initial conduct problems and mothers with high critical parenting benefited most, and maternal engagement predicted change.", link: doi("10.1207/s15374424jccp3302_10"), kind: "doi" },
      { cite: "Larsson, B., Fossum, S., Clifford, G., Drugli, M. B., Handegård, B. H., & Mørch, W.-T. (2009). Treatment of oppositional defiant and conduct problems in young Norwegian children: results of a randomized controlled trial. European Child & Adolescent Psychiatry.", note: "Norwegian RCT of 127 children aged 4–8 with ODD/CD: parent training reduced conduct problems, about two-thirds functioned within normal range after treatment, and harsh discipline and maternal stress fell.", link: doi("10.1007/s00787-008-0702-z"), kind: "doi" },
      { cite: "Overbeek, G., van Aar, J., Orobio de Castro, B., Matthys, W., Weeland, J., Chhangur, R. R., & Leijten, P. (2021). Longer-Term Outcomes of the Incredible Years Parenting Intervention. Prevention Science.", note: "Dutch indicated-prevention RCT (n = 387): parent-reported conduct-problem reductions (d = 0.31) were sustained 2.5 years later, but teacher and child reports were not and there were no broader mental-health benefits.", link: doi("10.1007/s11121-020-01176-6"), kind: "doi" },
      { cite: "Leijten, P., Raaijmakers, M., Wijngaards, L., Matthys, W., Menting, A., Hemink-van Putten, M., & Orobio de Castro, B. (2018). Understanding Who Benefits from Parenting Interventions for Children's Conduct Problems: an Integrative Data Analysis. Prevention Science.", note: "Integrative analysis of 786 Dutch families across four trials: Incredible Years reduced conduct problems (d = −.34) regardless of parental education or ethnicity; children with more severe problems benefited more.", link: doi("10.1007/s11121-018-0864-y"), kind: "doi" },
      { cite: "Eyberg, S. M., Nelson, M. M., & Boggs, S. R. (2008). Evidence-based psychosocial treatments for children and adolescents with disruptive behavior. Journal of clinical child and adolescent psychology : the official journal for the Society of Clinical Child and Adolescent Psychology, American Psychological Association, Division 53, 37(1), 215-37.", note: "Evidence-based treatment review naming parent-management training the well-established approach for disruptive behaviour in children.", link: doi("10.1080/15374410701820117"), kind: "doi" },
      { cite: "Stattin, H., Enebrink, P., Özdemir, M., & Giannotta, F. (2015). A national evaluation of parenting programs in Sweden: The short-term effects using an RCT effectiveness design. Journal of Consulting and Clinical Psychology.", note: "Swedish national effectiveness RCT of 908 children: behavioural parent programs strongly reduced conduct problems and ADHD symptoms, and parents' stress and depressive symptoms fell.", link: doi("10.1037/a0039328"), kind: "doi" },
    ],
  },
  {
    id: "gs-parenting-triple-p",
    goal: "parenting", tier: "advanced", section: "8111",
    title: "Triple P — Strong Program, Contested Evidence Base",
    subtitle: "Works for mothers who report on it; read the critiques before you pay",
    evidenceTag: "Mixed",
    impact: { magnitude: 3, latency: "months", durability: "sustained", effort: "high" },
    callout: "Honest boundary: the developers' meta-analysis of 101 studies reports medium effects across child and parent outcomes, but an independent PRISMA review found most trials were small, wait-list controlled, author-affiliated and reliant on maternal report, with paternal reports not significantly different from control. Choose it for the structured skills, not the marketing.",
    description:
      "Triple P is a multi-level system (self-directed booklets through intensive group and individual formats). Sanders' own trials and meta-analysis find short-term effects on child behaviour (d ≈ .47) and parenting practices (d ≈ .58), and independent meta-analyses of Level 4 also find reduced disruptive behaviour. The Wilson et al. review and Coyne's follow-up argue the literature is underpowered and selectively reported; a 2025 network meta-analysis of online parenting programs finds moderate effects for learning-theory-based content, which is what Triple P delivers.",
    action: "If a group program is not available, use a structured Level-4-style curriculum (online or workbook) for eight weeks: pick two target behaviours, record them daily, and apply one positive strategy and one consistent consequence. Ask your co-parent to rate progress independently so you are not relying on a single reporter.",
    sources: [
      { cite: "Sanders, M. R., Markie-Dadds, C., Tully, L. A., & Bor, W. (2000). The Triple P-Positive Parenting Program: A comparison of enhanced, standard, and self-directed behavioral family intervention for parents of children with early onset conduct problems. Journal of Consulting and Clinical Psychology, 68(4), 624-640.", note: "Sanders' randomized comparison of enhanced, standard and self-directed Triple P for early-onset conduct problems — the trial that established the multi-format system.", link: doi("10.1037/0022-006X.68.4.624"), kind: "doi" },
      { cite: "Sanders, M. R., Kirby, J. N., Tellegen, C. L., & Day, J. J. (2014). The Triple P-Positive Parenting Program: a systematic review and meta-analysis of a multi-level system of parenting support. Clinical Psychology Review.", note: "Developer-led meta-analysis of 101 studies (16,099 families): short-term effects on children's social-emotional-behavioural outcomes d = 0.473, parenting practices d = 0.578, with significant long-term effects.", link: doi("10.1016/j.cpr.2014.04.003"), kind: "doi" },
      { cite: "Nowak, C., & Heinrichs, N. (2008). A comprehensive meta-analysis of Triple P-Positive Parenting Program using hierarchical linear modeling: effectiveness and moderating variables. Clinical Child and Family Psychology Review, 11(3), 114-44.", note: "Independent hierarchical-linear-model meta-analysis of 55 studies: small-to-moderate improvements in parenting, child behaviour and parental well-being, larger on parent report than observation and for more intensive formats.", link: doi("10.1007/s10567-008-0033-0"), kind: "doi" },
      { cite: "de Graaf, I., Speetjens, P., Smit, F., de Wolff, M., & Tavecchio, L. (2008). Effectiveness of the Triple P Positive Parenting Program on behavioral problems in children: a meta-analysis. Behavior Modification.", note: "Meta-analysis of Level 4 Triple P: reduced disruptive behaviours in children, maintained and improved at follow-up.", link: doi("10.1177/0145445508317134"), kind: "doi" },
      { cite: "Thomas, R., & Zimmer-Gembeck, M. J. (2007). Behavioral outcomes of Parent-Child Interaction Therapy and Triple P-Positive Parenting Program: a review and meta-analysis. Journal of abnormal child psychology, 35(3), 475-95.", note: "Review and meta-analysis comparing Parent–Child Interaction Therapy and Triple P behavioural outcomes.", link: doi("10.1007/s10802-007-9104-9"), kind: "doi" },
      { cite: "Wilson, P., Rush, R., Hussey, S., Puckering, C., Sim, F., Allely, C. S., …, & Gillberg, C. (2012). How evidence-based is an 'evidence-based parenting program'? A PRISMA systematic review and meta-analysis of Triple P. BMC Medicine.", note: "Independent PRISMA review of 33 studies: maternally reported effect 0.61 but paternal reports not significantly different from control, substantial selective reporting, 32 of 33 studies author-affiliated, no registered trials.", link: doi("10.1186/1741-7015-10-130"), kind: "doi" },
      { cite: "Coyne, J. C., & Kwakkenbos, L. (2013). Triple P-Positive Parenting programs: the folly of basing social policy on underpowered flawed studies. BMC Medicine.", note: "Commentary applying a minimum-sample criterion: 19 of 23 Triple P trials were too small to detect an effect even if present, with policy implications.", link: doi("10.1186/1741-7015-11-11"), kind: "doi" },
      { cite: "Canário, C., Del Pinto, R., Silva-Martins, M., Rienks, K., Kömürcü Akik, B., Modić Stanke, K., …, & Leijten, P. (2025). Online Parenting Programs for Children's Behavioral and Emotional Problems: a Network Meta-Analysis. Prevention Science.", note: "Network meta-analysis of 27 RCTs (n = 5,312) of online parenting programs: moderate effects on child behavioural and emotional problems, strongest for learning-theory-based content.", link: doi("10.1007/s11121-024-01735-1"), kind: "doi" },
    ],
  },
  {
    id: "gs-parenting-mindful-parenting",
    goal: "parenting", tier: "advanced", section: "8112",
    title: "An Eight-Week Mindful Parenting Course for Your Own Stress",
    subtitle: "Lower over-reactive discipline, lower parental anxiety — child effects follow",
    evidenceTag: "Emerging",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "moderate" },
    feeds: ["parental self-compassion", "less over-reactive discipline", "parent mood"],
    description:
      "Parenting stress is a driver of harsh, inconsistent discipline. An online eight-session mindful parenting RCT for mothers with elevated stress reduced over-reactive discipline and depressive and anxiety symptoms with small-to-medium effects; a clinic study of 70 parents found gains in mindful parenting predicted reductions in child psychopathology. The behavioural programs above also cut parental stress and depression as a side effect. Evidence is still early, mostly waitlist-controlled, so treat it as a promising add-on rather than a substitute for behavioural training.",
    action: "Enrol in an eight-week mindful-parenting course (online is fine) this quarter and practise the daily ten-minute exercise; at the same time, keep the fundamental protocols running so the child-side gains have something to land on.",
    sources: [
      { cite: "Potharst, E. S., Boekhorst, M. G. B. M., Cuijlits, I., van Broekhoven, K. E. M., Jacobs, A., Spek, V., …, & Pop, V. J. M. (2019). A Randomized Control Trial Evaluating an Online Mindful Parenting Training for Mothers With Elevated Parental Stress. Frontiers in Psychology, 10, 1550.", note: "RCT of 76 stressed mothers: an 8-session online mindful parenting training beat waitlist on over-reactive discipline and depression/anxiety (small-to-medium effects), with delayed improvement in parental role restriction.", link: doi("10.3389/fpsyg.2019.01550"), kind: "doi" },
      { cite: "Meppelink, R., de Bruin, E. I., Wanders-Mulder, F. H., Vennik, C. J., & Bögels, S. M. (2016). Mindful Parenting Training in Child Psychiatric Settings: Heightened Parental Mindfulness Reduces Parents' and Children's Psychopathology. Mindfulness, 7, 680-689.", note: "70 parents of referred children completed 8-week mindful parenting training: child and parent psychopathology fell, and improvement in mindful parenting specifically predicted child improvement.", link: doi("10.1007/s12671-016-0504-1"), kind: "doi" },
      { cite: "Stattin, H., Enebrink, P., Özdemir, M., & Giannotta, F. (2015). A national evaluation of parenting programs in Sweden: The short-term effects using an RCT effectiveness design. Journal of Consulting and Clinical Psychology.", note: "In the Swedish national parenting-program RCT, parents showed less negative behaviour and reduced stress and depressive symptoms after treatment.", link: doi("10.1037/a0039328"), kind: "doi" },
      { cite: "Canfield, C. F., Miller, E. B., Shaw, D. S., Morris, P., Alonso, A., & Mendelsohn, A. L. (2020). Beyond language: Impacts of shared reading on parenting stress and early parent-child relational health. Developmental Psychology.", note: "Shared book reading at 6 months predicted lower parenting stress and higher warmth at 18 months — a low-cost stress lever inside daily routines.", link: doi("10.1037/dev0000940"), kind: "doi" },
    ],
  },
  {
    id: "gs-parenting-father-involvement",
    goal: "parenting", tier: "fundamental", section: "8113",
    title: "Father Involvement That Shows Up Decades Later",
    subtitle: "Engaged fathers, independently of mothers, predict education and adjustment",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "months", durability: "lasting", effort: "moderate" },
    feeds: ["educational attainment", "behavioural adjustment", "father–child communication"],
    description:
      "A systematic review of longitudinal studies found father engagement predicts fewer behavioural problems and better cognitive and psychological outcomes in children, and the British National Child Development Study showed father involvement at age 7 predicted educational attainment by 20 independently of mother involvement and regardless of family structure. A legacy-making trial with seriously ill children found its strongest communication effects for fathers — fathers respond to structured, activity-based ways in.",
    action: "If you are the father, own one daily routine outright this month (bedtime books, the school run, Saturday breakfast) rather than 'helping'. If you are the mother, hand one over and do not supervise it.",
    sources: [
      { cite: "Sarkadi, A., Kristiansson, R., Oberklaid, F., & Bremberg, S. (2007). Fathers' involvement and children's developmental outcomes: a systematic review of longitudinal studies. Acta paediatrica (Oslo, Norway : 1992), 97(2), 153-8.", note: "Systematic review of longitudinal studies: father involvement was associated with fewer behavioural problems, less delinquency and better cognitive development in children.", link: doi("10.1111/j.1651-2227.2007.00572.x"), kind: "doi" },
      { cite: "Flouri, E., & Buchanan, A. (2004). Early father's and mother's involvement and child's later educational outcomes. British Journal of Educational Psychology, 74(Pt 2), 141-53.", note: "National Child Development Study: father involvement at age 7 independently predicted school-leaving qualifications by age 20, for sons and daughters alike and regardless of family structure.", link: doi("10.1348/000709904773839806"), kind: "doi" },
      { cite: "Akard, T. F., Dietrich, M. S., Friedman, D. L., Gerhardt, C. A., Given, B., Hendricks-Ferguson, V., …, & Gilmer, M. J. (2021). Improved Parent-Child Communication following a RCT Evaluating a Legacy Intervention for Children with Advanced Cancer. Progress in Palliative Care, 29(3), 130-139.", note: "RCT of a legacy-making intervention for children with advanced cancer: the strongest (if non-significant) effects were improvements in father–child communication.", link: doi("10.1080/09699260.2020.1826778"), kind: "doi" },
      { cite: "Waldinger, R. J., & Schulz, M. S. (2016). The Long Reach of Nurturing Family Environments: Links With Midlife Emotion-Regulatory Styles and Late-Life Security in Intimate Relationships. Psychological science, 27(11), 1443-1450.", note: "Harvard Study of Adult Development men: a nurturing childhood family environment predicted midlife emotion-regulatory styles and late-life attachment security decades later.", link: doi("10.1177/0956797616661556"), kind: "doi" },
    ],
  },
  {
    id: "gs-parenting-know-through-trust",
    goal: "parenting", tier: "moderate", section: "8114",
    title: "Teen Monitoring: Knowledge Comes From Disclosure, Not Surveillance",
    subtitle: "Build the relationship that makes them tell you",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "months", durability: "sustained", effort: "moderate" },
    feeds: ["adolescent disclosure", "parent–teen trust", "lower delinquency"],
    description:
      "The Swedish reinterpretation of 'parental monitoring' found that what protects adolescents is parental knowledge, and that knowledge comes mostly from the teen's spontaneous disclosure rather than from tracking and control; feeling controlled was linked to worse adjustment. Later within-person studies confirm that increases in parental control do not reduce delinquency and can backfire, especially in low-SES families and with empathic teens. Autonomy support (8109) and a good relationship are the levers.",
    action: "Replace one interrogation a day with one low-stakes conversation where you only listen (car rides work). Keep the rules you have, but for a month stop adding surveillance and track instead how often your teen volunteers something.",
    sources: [
      { cite: "Stattin, H., & Kerr, M. (2000). Parental monitoring: a reinterpretation. Child development, 71(4), 1072-85.", note: "Stattin and Kerr's reinterpretation: parental knowledge, not tracking, was linked to adjustment, and the main source of knowledge was the adolescent's own disclosure.", link: doi("10.1111/1467-8624.00210"), kind: "doi" },
      { cite: "Kerr, M., & Stattin, H. (2000). What parents know, how they know it, and several forms of adolescent adjustment: Further support for a reinterpretation of monitoring. Developmental Psychology, 36(3), 366-380.", note: "1,186 14-year-olds and parents: child disclosure explained more of the knowledge–adjustment links than parental surveillance; feeling controlled was linked to poor adjustment.", link: doi("10.1037/0012-1649.36.3.366"), kind: "doi" },
      { cite: "Rekker, R., Keijsers, L., Branje, S., Koot, H., & Meeus, W. (2017). The interplay of parental monitoring and socioeconomic status in predicting minor delinquency between and within adolescents. Journal of Adolescence, 59, 155-165.", note: "Six-wave Dutch study (n = 824): between adolescents, more monitoring did not mean less delinquency; within low-SES adolescents, periods of more control were associated with more delinquency.", link: doi("10.1016/j.adolescence.2017.06.001"), kind: "doi" },
      { cite: "Crocetti, E., Van der Graaff, J., Moscatelli, S., Keijsers, L., Koot, H. M., Rubini, M., …, & Branje, S. (2016). A Longitudinal Study on the Effects of Parental Monitoring on Adolescent Antisocial Behaviors: The Moderating Role of Adolescent Empathy. Frontiers in Psychology, 7, 1726.", note: "Longitudinal Dutch study: parental solicitation had unfavourable effects on antisocial behaviour in high-empathy adolescents and helpful effects only in low-empathy adolescents.", link: doi("10.3389/fpsyg.2016.01726"), kind: "doi" },
      { cite: "Padilla-Walker, L. M., & Nelson, L. J. (2012). Black Hawk down? Establishing helicopter parenting as a distinct construct from other forms of parental control during emerging adulthood. Journal of Adolescence, 35(5), 1177-90.", note: "Helicopter parenting measured in 438 emerging adults: positively related to parental involvement but negatively related to autonomy granting and school engagement.", link: doi("10.1016/j.adolescence.2012.03.007"), kind: "doi" },
    ],
  },
  {
    id: "gs-parenting-no-helicopter",
    goal: "parenting", tier: "moderate", section: "8115",
    title: "Helicopter Parenting: Rated at the Floor",
    subtitle: "Hovering predicts worse well-being and less competence in young adults",
    evidenceTag: "Moderate",
    impact: { magnitude: 1, latency: "months", durability: "sustained", effort: "low" },
    callout: "Debunked: over-involvement that removes the young adult's own problem-solving is associated with more depression and anxiety, lower life satisfaction and lower autonomy and competence in every study on this shelf. The evidence is correlational and drawn from college samples, but it points one way. Rated at the floor so it counts as a cost, not a style choice.",
    description:
      "Sociological and psychological studies of college students find that helicopter parenting is linked to greater use of psychiatric medication and lower well-being, and that its effect runs through thwarted autonomy, competence and relatedness — the same needs autonomy-supportive parenting (8109) feeds. The construct is distinct from ordinary involvement: high warmth combined with low autonomy-granting.",
    action: "For the next month, before you step in on a problem your child (or young adult) could plausibly solve, ask 'what's your plan?' and wait 24 hours. Keep a list of the problems they solved without you.",
    sources: [
      { cite: "LeMoyne, T., & Buchanan, T. (2011). Does \"Hovering\" Matter? Helicopter Parenting and Its Effect on Well-Being. Sociological Spectrum, 31(4), 399-418.", note: "Helicopter parenting in college students was negatively associated with psychological well-being and positively with use of medication for anxiety and depression.", link: doi("10.1080/02732173.2011.574038"), kind: "doi" },
      { cite: "Schiffrin, H. H., Liss, M., Miles-McLean, H., Geary, K. A., Erchull, M. J., & Tashner, T. (2014). Helping or Hovering? The Effects of Helicopter Parenting on College Students' Well-Being. Journal of Child and Family Studies, 23(3), 548-557.", note: "College students reporting helicopter parenting had lower autonomy, competence and relatedness, which in turn predicted more depression and lower life satisfaction.", link: doi("10.1007/s10826-013-9716-3"), kind: "doi" },
      { cite: "Padilla-Walker, L. M., & Nelson, L. J. (2012). Black Hawk down? Establishing helicopter parenting as a distinct construct from other forms of parental control during emerging adulthood. Journal of Adolescence, 35(5), 1177-90.", note: "Helicopter parenting formed a separate factor from behavioural and psychological control and was negatively related to parental autonomy granting and school engagement.", link: doi("10.1016/j.adolescence.2012.03.007"), kind: "doi" },
      { cite: "Vasquez, A. C., Patall, E. A., Fong, C. J., Corrigan, A. S., & Pine, L. (2016). Parent Autonomy Support, Academic Achievement, and Psychosocial Functioning: a Meta-analysis of Research. Educational Psychology Review, 28(3), 605-644.", note: "Meta-analysis showing the opposite pattern: parent autonomy support is associated with better achievement and psychosocial functioning.", link: doi("10.1007/s10648-015-9329-z"), kind: "doi" },
    ],
  },
  {
    id: "gs-parenting-music-transfer-myth",
    goal: "parenting", tier: "moderate", section: "8116",
    title: "Music Lessons for Music's Sake — Not for IQ",
    subtitle: "The 2004 effect did not survive randomized trials or meta-analysis",
    evidenceTag: "Mixed",
    impact: { magnitude: 2, latency: "months", durability: "sustained", effort: "moderate" },
    callout: "Honest boundary: Schellenberg's 2004 trial reported a small IQ gain from a year of lessons, but two preschool RCTs found no consistent non-musical benefit, and multilevel meta-analyses of 54 studies find the effect on cognitive and academic outcomes is essentially zero once study quality is controlled. Music is worth doing for skill, joy and shared family activity; do not pay for it as brain training.",
    description:
      "Sala and Gobet's 2017 and 2020 meta-analyses show music training's transfer to cognitive and academic skills shrinks to null when randomization and active controls are present, regardless of age, duration or outcome type; Mehr's randomized preschool trials found no reliable benefit over visual-arts classes or no treatment. The magnitude here is for the direct benefits — musical skill, discipline of practice, a shared interest — not for transfer.",
    action: "If your child wants lessons, choose the instrument and teacher for enjoyment and a 15-minute daily practice habit, and drop the expectation that it will move grades. Put the 'enrichment' budget you save into books, sleep and family time.",
    sources: [
      { cite: "Schellenberg, E. G. (2004). Music lessons enhance IQ. Psychological science, 15(8), 511-4.", note: "Schellenberg's randomized study reporting that a year of music lessons produced a small increase in IQ relative to drama or no lessons — the origin of the claim.", link: doi("10.1111/j.0956-7976.2004.00711.x"), kind: "doi" },
      { cite: "Sala, G., & Gobet, F. (2017). When the music's over. Does music skill transfer to children's and young adolescents' cognitive and academic skills? A meta-analysis. Educational Research Review, 20, 55-67.", note: "Meta-analysis of music-skill transfer to children's cognitive and academic skills: small effects that shrink with better study design.", link: doi("10.1016/j.edurev.2016.11.005"), kind: "doi" },
      { cite: "Sala, G., & Gobet, F. (2020). Cognitive and academic benefits of music training with children: A multilevel meta-analysis. Memory & Cognition, 48(8), 1429-1441.", note: "Multilevel meta-analysis (54 studies, n = 6,984): overall effect of music training on cognitive and academic outcomes ≈ 0 once design quality is controlled; small effects only in non-randomized studies with non-active controls.", link: doi("10.3758/s13421-020-01060-2"), kind: "doi" },
      { cite: "Mehr, S. A., Schachner, A., Katz, R. C., & Spelke, E. S. (2013). Two randomized trials provide no consistent evidence for nonmusical cognitive benefits of brief preschool music enrichment. PLoS One, 8(12), e82007.", note: "Two randomized preschool trials found no consistent evidence of non-musical cognitive benefits from brief music enrichment versus visual-arts classes or no treatment.", link: doi("10.1371/journal.pone.0082007"), kind: "doi" },
    ],
  },
  {
    id: "gs-parenting-warmth-long-reach",
    goal: "parenting", tier: "elite", section: "8117",
    title: "Warmth Is a Decades-Long Investment in Their Body",
    subtitle: "Childhood family climate shows up in midlife inflammation and 80-year-old happiness",
    evidenceTag: "Moderate",
    impact: { magnitude: 5, latency: "months", durability: "lasting", effort: "moderate" },
    feeds: ["adult stress physiology", "late-life security and happiness", "resilience to early adversity"],
    description:
      "The 'risky families' model and its biological follow-ups show that cold, conflictual homes predict disrupted stress physiology and worse adult mental and physical health, while parental warmth buffers the damage: adults who grew up poor but with warm mothers showed less pro-inflammatory signalling, and in the CARDIA study parental warmth offset the multisystem biological risk associated with childhood abuse. Men followed for 60–80 years in the Harvard Study who had nurturing childhoods regulated emotion better in midlife and were more securely attached in old age. This is the elite protocol because the horizon is your child's whole life.",
    action: "Make one unmistakable act of warmth non-negotiable every single day for the next year — a specific appreciation, twenty minutes of undivided attention, physical affection — and keep it especially on the days you had to discipline. Review monthly whether your child would say you are 'on their side'.",
    sources: [
      { cite: "Repetti, R. L., Taylor, S. E., & Seeman, T. E. (2002). Risky families: Family social environments and the mental and physical health of offspring. Psychological Bulletin, 128(2), 330-366.", note: "The 'risky families' review: conflict-ridden, cold or neglectful family environments create cascading vulnerabilities in emotion processing, stress-response systems and health behaviours across the lifespan.", link: doi("10.1037/0033-2909.128.2.330"), kind: "doi" },
      { cite: "Chen, E., Miller, G. E., Kobor, M. S., & Cole, S. W. (2011). Maternal warmth buffers the effects of low early-life socioeconomic status on pro-inflammatory signaling in adulthood. Molecular Psychiatry, 16(7), 729-37.", note: "Adults from low-SES childhoods whose mothers were high in warmth showed lower Toll-like-receptor-stimulated IL-6 production and reduced pro-inflammatory transcription-factor activity than those with low maternal warmth.", link: doi("10.1038/mp.2010.53"), kind: "doi" },
      { cite: "Carroll, J. E., Gruenewald, T. L., Taylor, S. E., Janicki-Deverts, D., Matthews, K. A., & Seeman, T. E. (2013). Childhood abuse, parental warmth, and adult multisystem biological risk in the Coronary Artery Risk Development in Young Adults study. Proceedings of the National Academy of Sciences, 110(42), 17149-53.", note: "CARDIA substudy (n = 756): childhood abuse predicted higher 18-biomarker multisystem risk, parental warmth predicted lower risk, and warmth moderated the abuse effect.", link: doi("10.1073/pnas.1315458110"), kind: "doi" },
      { cite: "Waldinger, R. J., & Schulz, M. S. (2016). The Long Reach of Nurturing Family Environments: Links With Midlife Emotion-Regulatory Styles and Late-Life Security in Intimate Relationships. Psychological science, 27(11), 1443-1450.", note: "Harvard Study men: nurturing family environments in childhood predicted midlife emotion-regulatory styles and late-life attachment security.", link: doi("10.1177/0956797616661556"), kind: "doi" },
      { cite: "Vaillant, G. E., & Mukamal, K. (2001). Successful aging. American Journal of Psychiatry, 158(6), 839-47.", note: "Two cohorts of boys followed 60 years: variables assessed before 50 predicted good and bad aging at 70–80, with many under personal control.", link: doi("10.1176/appi.ajp.158.6.839"), kind: "doi" },
      { cite: "Waldinger, R. J., & Schulz, M. S. (2010). What's love got to do with it? Social functioning, perceived health, and daily happiness in married octogenarians. Psychology and aging, 25(2), 422-31.", note: "Octogenarian couples from the same study: social functioning and daily happiness remained tied to the quality of close relationships into the ninth decade.", link: doi("10.1037/a0019087"), kind: "doi" },
    ],
  },
  {
    id: "gs-parenting-responsive-system",
    goal: "parenting", tier: "elite", section: "8118",
    title: "Run the Responsive-Parenting System for Years",
    subtitle: "Coaching that starts in infancy and continues into toddlerhood is where the big effects live",
    evidenceTag: "Strong",
    impact: { magnitude: 5, latency: "months", durability: "lasting", effort: "high" },
    feeds: ["language and cognition", "attachment", "school readiness"],
    description:
      "The largest randomized effects in this field come from programs that coach responsive caregiving (noticing signals, contingent replies, rich talk, play and reading) and keep going: Landry's PALS trial found the strongest child outcomes when coaching began in infancy and continued into toddlerhood; the Video Interaction Project produced sustained gains in cognitive stimulation and reduced behaviour problems years after enrolment; and the 102-trial meta-analysis found responsive-caregiving content produced the largest gains in cognition, parenting knowledge and interaction. The elite move is to treat this as a multi-year system — coaching, feedback and routines — rather than a class.",
    action: "Enrol in a responsive-parenting program that includes coaching and video feedback (pediatric-clinic programs such as VIP or PALS-style home coaching) before your child's first birthday, and keep a structured version running — monthly review of talk, play and reading routines — until school entry.",
    sources: [
      { cite: "Landry, S. H., Smith, K. E., Swank, P. R., & Guttentag, C. (2008). A responsive parenting intervention: the optimal timing across early childhood for impacting maternal behaviors and child outcomes. Developmental psychology, 44(5), 1335-53.", note: "PALS randomized trial: responsive-parenting coaching had its largest effects on maternal behaviour and child language and social outcomes when delivered in infancy and continued through toddlerhood.", link: doi("10.1037/a0013030"), kind: "doi" },
      { cite: "Cates, C. B., Weisleder, A., Berkule Johnson, S., Seery, A. M., Canfield, C. F., Huberman, H., …, & Mendelsohn, A. L. (2018). Enhancing Parent Talk, Reading, and Play in Primary Care: Sustained Impacts of the Video Interaction Project. The Journal of Pediatrics.", note: "Video Interaction Project RCT: enhanced reading, verbal responsivity and overall stimulation at every assessment from 6 to 54 months, persisting 1.5 years after program completion.", link: doi("10.1016/j.jpeds.2018.03.002"), kind: "doi" },
      { cite: "Mendelsohn, A. L., Cates, C. B., Weisleder, A., Berkule Johnson, S., Seery, A. M., Canfield, C. F., …, & Dreyer, B. P. (2018). Reading Aloud, Play, and Social-Emotional Development. Pediatrics, 141(5).", note: "VIP reading-and-play intervention reduced hyperactivity and aggression into early school age in a randomized primary-care trial.", link: doi("10.1542/peds.2017-3393"), kind: "doi" },
      { cite: "Jeong, J., Franchett, E. E., Ramos de Oliveira, C. V., Rehmani, K., & Yousafzai, A. K. (2021). Parenting interventions to promote early child development in the first three years of life: A global systematic review and meta-analysis. PLoS Medicine.", note: "Global meta-analysis of 102 RCTs: responsive-caregiving programs produced larger effects on cognitive development, parenting knowledge, practices and parent–child interaction.", link: doi("10.1371/journal.pmed.1003602"), kind: "doi" },
      { cite: "Gilkerson, J., Richards, J. A., Warren, S. F., Oller, D. K., Russo, R., & Vohr, B. (2018). Language Experience in the Second Year of Life and Language Outcomes in Late Childhood. Pediatrics, 142(4).", note: "Conversational turns in the 18–24-month window predicted IQ and language a decade later — the developmental window the system protects.", link: doi("10.1542/peds.2017-4276"), kind: "doi" },
    ],
  },
];
