// Goal shelf: PARTNER — find the right partner and settle down (sections 8800–8899).
// Verification: every DOI below was resolved against the Crossref record or the
// PubMed record on 2026-09-11. See types.ts for the contract. Popular advice the
// evidence does not support is rated at the floor (magnitude 1) with a callout.
import { doi, type GoalShelfCluster } from "./types";

export const SECTIONS: Record<string, string> = {
  "8800": "How to Read This Shelf",
  "8801": "What Actually Predicts a Good Relationship",
  "8802": "Where Couples Meet — Online Dating Used Well",
  "8803": "Dating Apps and Wellbeing — The Honest Picture",
  "8804": "Similarity, Complementarity and Perceived Fit",
  "8805": "Attachment Style — Yours and Theirs",
  "8806": "First Meetings — Speed-Dating and the Spark",
  "8807": "The Slow Burn — Familiarity, Friends-First and Uniqueness",
  "8808": "What People Say They Want Versus Whom They Choose",
  "8809": "Values, Faith and Shared Meaning",
  "8810": "How Long to Date, How Old to Marry",
  "8811": "Cohabitation — Sliding Versus Deciding",
  "8812": "Red Flags — Risk Markers for Partner Violence",
  "8813": "Loneliness While Single — Interventions That Work",
  "8814": "Dating Anxiety — Treating Social Anxiety First",
  "8815": "Self-Expansion — Becoming the Partner You Want to Meet",
  "8816": "Relationship Education Before You Commit",
  "8817": "The Stay-or-Leave Decision, Made Deliberately",
  "8818": "Widening the Pool — A Year-Long Meeting System",
  "8819": "Myths — Soulmates, Opposites and the Checklist",
};

export const CLUSTERS: GoalShelfCluster[] = [
  {
    id: "gs-partner-read-me-first",
    goal: "partner", tier: "fundamental", section: "8800",
    title: "How to Read the Finding-a-Partner Shelf",
    subtitle: "Protocols, not prophecies — pick one per tier each month",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "low" },
    description:
      "Every protocol on this shelf is tagged fundamental, moderate, advanced or elite and carries a concrete action. The monthly menu hands you one or two from each tier. The through-line of the research is humbling: what predicts a good relationship is mostly how two people treat each other once together, not the traits either brought — so this shelf spends as much time on who you are becoming and how you meet people as on whom to pick.",
    action: "This month, pick the one fundamental protocol on this shelf you are not already doing and run it for 30 days before adding anything else.",
    sources: [
      { cite: "Joel, S., Eastwick, P. W., Allison, C. J., Arriaga, X. B., Baker, Z. G., Bar-Kalifa, E., et al. (2020). Machine learning uncovers the most robust self-report predictors of relationship quality across 43 longitudinal couples studies. Proceedings of the National Academy of Sciences, 117(32), 19061–19071.", note: "Across 43 datasets and 11,196 couples, relationship-specific perceptions — perceived partner commitment, appreciation, sexual satisfaction, perceived partner satisfaction and conflict — predicted relationship quality far better than any individual difference.", link: doi("10.1073/pnas.1917036117"), kind: "doi" },
      { cite: "Finkel, E. J., Eastwick, P. W., Karney, B. R., Reis, H. T., & Sprecher, S. (2012). Online dating: A critical analysis from the perspective of psychological science. Psychological Science in the Public Interest, 13(1), 3–66.", note: "The definitive review of online dating's access, communication and matching claims: access is a genuine benefit, browsing profiles and algorithmic matching are much weaker than advertised.", link: doi("10.1177/1529100612436522"), kind: "doi" },
    ],
  },
  {
    id: "gs-partner-what-predicts",
    goal: "partner", tier: "fundamental", section: "8801",
    title: "Screen for How They Treat You, Not Their Résumé",
    subtitle: "The relationship variables beat the trait variables",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "weeks", durability: "lasting", effort: "low" },
    feeds: ["judgement", "appreciation", "commitment"],
    description:
      "The largest study of relationship quality ever assembled found that how people perceive the relationship — the partner's commitment, appreciation, responsiveness, low conflict — accounted for most of the predictable variance, while personality, attachment style and demographics added little once relationship variables were known. Newlywed studies show the same thing on a 13-year horizon: it was disillusionment (declining affection, rising ambivalence, waning belief in the partner's responsiveness) rather than early negativity that foreshadowed divorce. Nationally representative samples found partner personality explained only 1–3% of relationship satisfaction. The boundary: these are predictors of quality once a relationship exists; they cannot tell you on a first date who will become that partner.",
    action: "After each of the next five dates, write two lines: one on how they treated you and others (appreciation, follow-through, kindness under friction) and one on how you felt about yourself in their company — and weight those over the checklist.",
    sources: [
      { cite: "Joel, S., Eastwick, P. W., Allison, C. J., Arriaga, X. B., Baker, Z. G., Bar-Kalifa, E., et al. (2020). Machine learning uncovers the most robust self-report predictors of relationship quality across 43 longitudinal couples studies. Proceedings of the National Academy of Sciences, 117(32), 19061–19071.", note: "Relationship-specific perceptions predicted quality; individual differences added little beyond them across 11,196 couples.", link: doi("10.1073/pnas.1917036117"), kind: "doi" },
      { cite: "Huston, T. L., Caughlin, J. P., Houts, R. M., Smith, S. E., & George, L. J. (2001). The connubial crucible: Newlywed years as predictors of marital delight, distress, and divorce. Journal of Personality and Social Psychology, 80(2), 237–252.", note: "Newlywed romance and expressed negativity foreshadowed happiness and divorce timing 13 years later; disillusionment — abating love, declining affection, rising ambivalence — marked couples headed for divorce.", link: doi("10.1037/0022-3514.80.2.237"), kind: "doi" },
      { cite: "Karney, B. R., & Bradbury, T. N. (1995). The longitudinal course of marital quality and stability: A review of theory, method, and research. Psychological Bulletin, 118(1), 3–34.", note: "The vulnerability–stress–adaptation review of 115 longitudinal studies: enduring vulnerabilities, stressful events and adaptive processes jointly shape marital trajectories.", link: doi("10.1037/0033-2909.118.1.3"), kind: "doi" },
      { cite: "Dyrenforth, P. S., Kashy, D. A., Donnellan, M. B., & Lucas, R. E. (2010). Predicting relationship and life satisfaction from personality in nationally representative samples from three countries: The relative importance of actor, partner, and similarity effects. Journal of Personality and Social Psychology, 99(4), 690–702.", note: "In 23,250 couples from Australia, the UK and Germany, partner personality explained 1–3% of relationship satisfaction and couple similarity less than 0.5%.", link: doi("10.1037/a0020385"), kind: "doi" },
      { cite: "Candel, O.-S., & Turliuc, M. N. (2019). Insecure attachment and relationship satisfaction: A meta-analysis of actor and partner associations. Personality and Individual Differences, 147, 190–199.", note: "Meta-analysis of actor and partner effects: both anxious and avoidant attachment predict lower satisfaction for self and partner — a trait that does matter, and one that can change.", link: doi("10.1016/j.paid.2019.04.037"), kind: "doi" },
      { cite: "Li, T., & Chan, D. K.-S. (2012). How anxious and avoidant attachment affect romantic relationship quality differently: A meta-analytic review. European Journal of Social Psychology, 42(4), 406–419.", note: "Avoidance was more strongly linked to low connectedness and support; anxiety to conflict — different insecurities, different relationship costs.", link: doi("10.1002/ejsp.1842"), kind: "doi" },
      { cite: "Eastwick, P. W., Luchies, L. B., Finkel, E. J., & Hunt, L. L. (2014). The predictive validity of ideal partner preferences: A review and meta-analysis. Psychological Bulletin, 140(3), 623–665.", note: "Meta-analysis: stated ideal-partner preferences predict attraction to a partner's traits in the abstract but not romantic evaluations of real, live partners.", link: doi("10.1037/a0032432"), kind: "doi" },
    ],
  },
  {
    id: "gs-partner-meeting-online",
    goal: "partner", tier: "fundamental", section: "8802",
    title: "Use Online Dating for Access, Not for Matching",
    subtitle: "Short profiles-to-meeting cycles; ignore compatibility scores",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "low" },
    feeds: ["access to partners", "decision speed", "realism"],
    description:
      "Online dating is now the most common way US couples meet, displacing friends and family as intermediaries, and marriages that began online were slightly more satisfying and less likely to end in the first years in a 19,131-person national sample. The scientific review is equally clear that its power is access — more potential partners — while browsing many profiles and algorithmic matching perform poorly, because the traits that predict compatibility are hard to see in a profile and easy to see in person. Excess choice has its own cost: experimentally increasing partner availability raised choice overload and fear of being single. The boundary: the satisfaction advantage of meeting online is small and observational.",
    action: "This month, limit yourself to two apps or sites, cap browsing to 15 minutes a day, and move any promising match to a real meeting within two weeks of first contact.",
    sources: [
      { cite: "Rosenfeld, M. J., Thomas, R. J., & Hausen, S. (2019). Disintermediating your friends: How online dating in the United States displaces other ways of meeting. Proceedings of the National Academy of Sciences, 116(36), 17753–17758.", note: "Nationally representative data: meeting online became the most common way heterosexual US couples met, displacing friends as intermediaries.", link: doi("10.1073/pnas.1908630116"), kind: "doi" },
      { cite: "Rosenfeld, M. J., & Thomas, R. J. (2012). Searching for a mate: The rise of the Internet as a social intermediary. American Sociological Review, 77(4), 523–547.", note: "How Couples Meet and Stay Together survey: the internet's search efficiency especially benefited people in thin dating markets.", link: doi("10.1177/0003122412448050"), kind: "doi" },
      { cite: "Cacioppo, J. T., Cacioppo, S., Gonzaga, G. C., Ogburn, E. L., & VanderWeele, T. J. (2013). Marital satisfaction and break-ups differ across on-line and off-line meeting venues. Proceedings of the National Academy of Sciences, 110(25), 10135–10140.", note: "19,131 respondents married 2005–2012: more than a third of marriages began online, and those marriages had slightly higher satisfaction and lower break-up rates.", link: doi("10.1073/pnas.1222447110"), kind: "doi" },
      { cite: "Finkel, E. J., Eastwick, P. W., Karney, B. R., Reis, H. T., & Sprecher, S. (2012). Online dating: A critical analysis from the perspective of psychological science. Psychological Science in the Public Interest, 13(1), 3–66.", note: "Access helps; profile browsing and matching algorithms do not deliver on compatibility because compatibility emerges in interaction.", link: doi("10.1177/1529100612436522"), kind: "doi" },
      { cite: "Konings, F., Sumter, S. R., Vranken, I., Dredge, R., & Vandenbosch, L. (2022). Behind the screens: A systematic literature review of quantitative research on mobile dating. Archives of Sexual Behavior, 51(6), 2969–3020.", note: "Systematic review of quantitative mobile-dating research mapping who uses apps, why, and with what relational outcomes.", link: doi("10.1007/s10508-022-02312-9"), kind: "doi" },
      { cite: "Castro, Á., & Barrada, J. R. (2020). Dating apps and their sociodemographic and psychosocial correlates: A systematic review. International Journal of Environmental Research and Public Health, 17(18), 6500.", note: "70 studies from 2016–2020: user characteristics, motives, and the benefits and risks of dating-app use.", link: doi("10.3390/ijerph17186500"), kind: "doi" },
      { cite: "Thomas, M. F., Binder, A., & Matthes, J. (2022). The agony of partner choice: The effect of excessive partner availability on fear of being single, self-esteem, and partner choice overload. Computers in Human Behavior, 126, 106977.", note: "Experimentally increasing the number of available partners raised choice overload and fear of being single — a case for capping browsing.", link: doi("10.1016/j.chb.2021.106977"), kind: "doi" },
    ],
  },
  {
    id: "gs-partner-apps-wellbeing",
    goal: "partner", tier: "fundamental", section: "8803",
    title: "Dating Apps and Your Wellbeing",
    subtitle: "Users report more distress; the arrow's direction is unclear",
    evidenceTag: "Mixed",
    impact: { magnitude: 2, latency: "weeks", durability: "transient", effort: "low" },
    callout: "The honest picture: swipe-app users report higher psychological distress and depression than non-users in cross-sectional data, women's lifetime app use predicts daily body dissatisfaction, and problematic use tracks sex-search and self-esteem motives — but almost none of this is longitudinal, and lonelier or more anxious people may simply use apps more. Treat apps as a tool with side effects to manage, not a verdict on your worth.",
    feeds: ["self-esteem", "body image", "mood"],
    description:
      "In a 437-person survey, current swipe-app users had roughly double the odds of psychological distress and higher depression scores, with heavier use associated with more distress; yet more users reported a positive than a negative effect on self-esteem, and 40% had entered a serious relationship through an app. A systematic review of problematic online dating found neuroticism, sensation-seeking and self-esteem-enhancement motives predict heavier and more problematic use. A daily-diary study found women's lifetime app use predicted daily body dissatisfaction and disordered-eating urges. The boundary: cross-sectional designs cannot separate cause from selection.",
    action: "Track your mood before and after app sessions for two weeks; if sessions reliably leave you worse, cut daily use in half and move contact off-app faster.",
    sources: [
      { cite: "Holtzhausen, N., Fitzgerald, K., Thakur, I., Ashley, J., Rolfe, M., & Pit, S. W. (2020). Swipe-based dating applications use and its association with mental health outcomes: A cross-sectional study. BMC Psychology, 8, 22.", note: "437 adults: swipe-app users had higher odds of psychological distress (OR = 2.51) and depression (OR = 1.91); frequency and duration of use tracked greater distress, though more users reported a positive than negative effect on self-esteem.", link: doi("10.1186/s40359-020-0373-1"), kind: "doi" },
      { cite: "Bonilla-Zorita, G., Griffiths, M. D., & Kuss, D. J. (2021). Online dating and problematic use: A systematic review. International Journal of Mental Health and Addiction, 19(6), 2245–2278.", note: "43 studies: neuroticism, sociability, sensation-seeking and sexual permissiveness related to greater use; sex-search and self-esteem enhancement predicted problematic use.", link: doi("10.1007/s11469-020-00318-9"), kind: "doi" },
      { cite: "Portingale, J., Fuller-Tyszkiewicz, M., Liu, S., Eddy, S., Liu, X., Giles, S., & Krug, I. (2022). Love me Tinder: The effects of women's lifetime dating app use on daily body dissatisfaction, disordered eating urges, and negative mood. Body Image, 40, 310–321.", note: "Daily-diary study: women's lifetime dating-app use predicted daily body dissatisfaction, disordered-eating urges and negative mood.", link: doi("10.1016/j.bodyim.2022.01.005"), kind: "doi" },
      { cite: "Thomas, M. F., Binder, A., & Matthes, J. (2022). The agony of partner choice: The effect of excessive partner availability on fear of being single, self-esteem, and partner choice overload. Computers in Human Behavior, 126, 106977.", note: "Excess partner availability experimentally increased fear of being single and choice overload.", link: doi("10.1016/j.chb.2021.106977"), kind: "doi" },
      { cite: "Cummings, J. J., & Mays, K. (2021). Trait motivational reactivity as a predictor of online dating app behavior. Computers in Human Behavior, 121, 106775.", note: "Individual differences in approach and avoidance reactivity predicted patterns of app behaviour — the same app affects different users differently.", link: doi("10.1016/j.chb.2021.106775"), kind: "doi" },
      { cite: "Castro, Á., & Barrada, J. R. (2020). Dating apps and their sociodemographic and psychosocial correlates: A systematic review. International Journal of Environmental Research and Public Health, 17(18), 6500.", note: "Review documenting both benefits (access, relationship formation) and risks (deception, objectification) of app use.", link: doi("10.3390/ijerph17186500"), kind: "doi" },
      { cite: "Konings, F., Sumter, S. R., Vranken, I., Dredge, R., & Vandenbosch, L. (2022). Behind the screens: A systematic literature review of quantitative research on mobile dating. Archives of Sexual Behavior, 51(6), 2969–3020.", note: "Systematic review noting that most mobile-dating research is cross-sectional and cannot establish causal effects on wellbeing.", link: doi("10.1007/s10508-022-02312-9"), kind: "doi" },
    ],
  },
  {
    id: "gs-partner-similarity",
    goal: "partner", tier: "fundamental", section: "8804",
    title: "Similarity Matters — but Mostly the Perceived Kind",
    subtitle: "Attitudes and attachment similarity help; personality matching barely does",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "weeks", durability: "sustained", effort: "low" },
    feeds: ["compatibility judgement", "attraction"],
    description:
      "A meta-analysis of 313 studies found actual similarity strongly predicted attraction in no-interaction and brief-interaction studies but not in existing relationships, whereas perceived similarity predicted attraction everywhere. In 291 newlywed couples, spouses were substantially similar on attitudes but little on personality; personality-profile similarity predicted marital quality, and similarity on attachment characteristics was the strongest predictor. In a live speed-dating study perceived, not actual, similarity predicted romantic liking. Nationally, couple similarity explained under 0.5% of satisfaction. Practical reading: shared values and a similar way of relating help; matching Big Five scores is a distraction.",
    action: "In early conversations, ask about three concrete values (money, family, faith or purpose) and notice whether you feel understood — track felt similarity, not a trait tally.",
    sources: [
      { cite: "Montoya, R. M., Horton, R. S., & Kirchner, J. (2008). Is actual similarity necessary for attraction? A meta-analysis of actual and perceived similarity. Journal of Social and Personal Relationships, 25(6), 889–922.", note: "460 effect sizes from 313 studies: actual similarity (r = .47) and perceived similarity (r = .39) predicted attraction, but actual similarity's effect vanished in existing relationships while perceived similarity persisted.", link: doi("10.1177/0265407508096700"), kind: "doi" },
      { cite: "Luo, S., & Klohnen, E. C. (2005). Assortative mating and marital quality in newlyweds: A couple-centered approach. Journal of Personality and Social Psychology, 88(2), 304–326.", note: "291 newlywed couples: substantial similarity on attitudes but little on personality; similarity on attachment characteristics most strongly predicted satisfaction.", link: doi("10.1037/0022-3514.88.2.304"), kind: "doi" },
      { cite: "Tidwell, N. D., Eastwick, P. W., & Finkel, E. J. (2013). Perceived, not actual, similarity predicts initial attraction in a live romantic context: Evidence from the speed-dating paradigm. Personal Relationships, 20(2), 199–215.", note: "In speed-dating, perceived but not actual similarity predicted romantic liking, and general perceived similarity mattered more than trait-specific similarity.", link: doi("10.1111/j.1475-6811.2012.01405.x"), kind: "doi" },
      { cite: "Dyrenforth, P. S., Kashy, D. A., Donnellan, M. B., & Lucas, R. E. (2010). Predicting relationship and life satisfaction from personality in nationally representative samples from three countries: The relative importance of actor, partner, and similarity effects. Journal of Personality and Social Psychology, 99(4), 690–702.", note: "Couple personality similarity consistently explained less than 0.5% of satisfaction after actor and partner effects.", link: doi("10.1037/a0020385"), kind: "doi" },
      { cite: "Norton, M. I., Frost, J. H., & Ariely, D. (2007). Less is more: The lure of ambiguity, or why familiarity breeds contempt. Journal of Personality and Social Psychology, 92(1), 97–105.", note: "Learning more about a stranger on average reduced liking as dissimilarities surfaced — why profile-based impressions inflate expectations before a meeting.", link: doi("10.1037/0022-3514.92.1.97"), kind: "doi" },
      { cite: "Joel, S., Eastwick, P. W., Allison, C. J., Arriaga, X. B., Baker, Z. G., Bar-Kalifa, E., et al. (2020). Machine learning uncovers the most robust self-report predictors of relationship quality across 43 longitudinal couples studies. Proceedings of the National Academy of Sciences, 117(32), 19061–19071.", note: "Partner characteristics, including similarity-based ones, added little to the prediction of relationship quality beyond relationship perceptions.", link: doi("10.1073/pnas.1917036117"), kind: "doi" },
    ],
  },
  {
    id: "gs-partner-attachment",
    goal: "partner", tier: "moderate", section: "8805",
    title: "Know Your Attachment Style — and Watch Theirs Under Stress",
    subtitle: "A six-week self-study of anxiety and avoidance patterns",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "months", durability: "lasting", effort: "moderate" },
    feeds: ["self-awareness", "partner selection", "responsiveness"],
    description:
      "Adult attachment — anxious, avoidant, secure — is among the best-replicated individual predictors of relationship quality: meta-analyses show both insecure dimensions lower satisfaction for oneself and one's partner, with avoidance costing connectedness and anxiety fuelling conflict. Attachment similarity was the single strongest similarity predictor of newlywed satisfaction, and avoidant partners are measurably less responsive when their partner shares good news. Attachment is not destiny: in a couple-therapy trial, improvements in satisfaction drove later reductions in attachment anxiety. The practical move is to learn your own pattern and to watch a prospective partner's behaviour in the moments that reveal theirs — good news, conflict, needing help.",
    action: "Complete a validated adult-attachment questionnaire this week, write one paragraph on how your pattern showed up in your last relationship, and for the next six weeks note how each person you date responds to your good news and to small disagreements.",
    sources: [
      { cite: "Hazan, C., & Shaver, P. (1987). Romantic love conceptualized as an attachment process. Journal of Personality and Social Psychology, 52(3), 511–524.", note: "The founding study applying secure, anxious and avoidant attachment to adult romantic love, with the three styles tracking different experiences of relationships.", link: doi("10.1037/0022-3514.52.3.511"), kind: "doi" },
      { cite: "Collins, N. L., & Read, S. J. (1990). Adult attachment, working models, and relationship quality in dating couples. Journal of Personality and Social Psychology, 58(4), 644–663.", note: "In dating couples, attachment dimensions predicted relationship quality, with partners' attachment styles jointly shaping outcomes.", link: doi("10.1037/0022-3514.58.4.644"), kind: "doi" },
      { cite: "Li, T., & Chan, D. K.-S. (2012). How anxious and avoidant attachment affect romantic relationship quality differently: A meta-analytic review. European Journal of Social Psychology, 42(4), 406–419.", note: "Meta-analysis distinguishing avoidance (lower connectedness and support) from anxiety (more conflict) in their effects on relationship quality.", link: doi("10.1002/ejsp.1842"), kind: "doi" },
      { cite: "Candel, O.-S., & Turliuc, M. N. (2019). Insecure attachment and relationship satisfaction: A meta-analysis of actor and partner associations. Personality and Individual Differences, 147, 190–199.", note: "Both attachment anxiety and avoidance predicted lower satisfaction for the person and for their partner.", link: doi("10.1016/j.paid.2019.04.037"), kind: "doi" },
      { cite: "Luo, S., & Klohnen, E. C. (2005). Assortative mating and marital quality in newlyweds: A couple-centered approach. Journal of Personality and Social Psychology, 88(2), 304–326.", note: "Similarity on attachment characteristics was the strongest similarity predictor of marital satisfaction among 291 newlywed couples.", link: doi("10.1037/0022-3514.88.2.304"), kind: "doi" },
      { cite: "Shallcross, S. L., Howland, M., Bemis, J., Simpson, J. A., & Frazier, P. (2011). Not 'capitalizing' on social capitalization interactions: The role of attachment insecurity. Journal of Family Psychology, 25(1), 77–85.", note: "In 101 dating couples, avoidant responders were less responsive to a partner's good news and underestimated their partner's responsiveness — an observable early signal.", link: doi("10.1037/a0021876"), kind: "doi" },
      { cite: "Benson, L. A., Sevier, M., & Christensen, A. (2013). The impact of behavioral couple therapy on attachment in distressed couples. Journal of Marital and Family Therapy, 39(4), 407–420.", note: "In 134 couples in therapy, early gains in satisfaction predicted later reductions in attachment anxiety — attachment can change with experience.", link: doi("10.1111/jmft.12020"), kind: "doi" },
    ],
  },
  {
    id: "gs-partner-speed-dating-spark",
    goal: "partner", tier: "moderate", section: "8806",
    title: "First Meetings — What the Spark Actually Is",
    subtitle: "Short live meetings, selective interest, real eye contact",
    evidenceTag: "Strong",
    impact: { magnitude: 3, latency: "weeks", durability: "transient", effort: "moderate" },
    feeds: ["initial attraction", "selectivity", "presence"],
    description:
      "Speed-dating research shows that initial attraction is dyad-specific and poorly predicted by anything measured beforehand: machine-learning models using more than 100 self-report traits predicted 4–27% of a person's general desirability but none of the unique desire between two particular people. Being selective helps — people who liked everyone were liked by no one, while unique interest was reciprocated. Live cues drive attraction: shared eye contact predicted mate choice after a five-minute conversation, experimentally aligning partners' smiles causally increased attraction, and people who synchronise with others were rated more attractive. The boundary: the spark forecasts a second date, not a relationship.",
    action: "Attend two structured in-person meeting events this month (speed dating, a singles mixer, a recurring class) and, at each, choose only the two people you genuinely want to see again.",
    sources: [
      { cite: "Finkel, E. J., & Eastwick, P. W. (2008). Speed-dating. Current Directions in Psychological Science, 17(3), 193–197.", note: "Introduces speed-dating as a tool for studying real dyadic attraction with strong external validity, and summarises its early contributions.", link: doi("10.1111/j.1467-8721.2008.00573.x"), kind: "doi" },
      { cite: "Joel, S., Eastwick, P. W., & Finkel, E. J. (2017). Is romantic desire predictable? Machine learning applied to initial romantic attraction. Psychological Science, 28(10), 1478–1489.", note: "Random forests predicted 4–18% of actor and 7–27% of partner variance in desire but could not predict the unique desire between two specific people from over 100 pre-date measures.", link: doi("10.1177/0956797617714580"), kind: "doi" },
      { cite: "Eastwick, P. W., Finkel, E. J., Mochon, D., & Ariely, D. (2007). Selective versus unselective romantic desire: Not all reciprocity is created equal. Psychological Science, 18(4), 317–319.", note: "In speed-dating, unselective desire for everyone was reciprocated less; desire unique to one person was reciprocated — selectivity is attractive.", link: doi("10.1111/j.1467-9280.2007.01897.x"), kind: "doi" },
      { cite: "Eastwick, P. W., & Finkel, E. J. (2008). Sex differences in mate preferences revisited: Do people know what they initially desire in a romantic partner? Journal of Personality and Social Psychology, 94(2), 245–264.", note: "Stated sex-differentiated preferences for attractiveness and earning prospects did not predict romantic interest in real speed-dating partners.", link: doi("10.1037/0022-3514.94.2.245"), kind: "doi" },
      { cite: "Hoffmann, A., Schiestl, S., Sinske, P., Gondan, M., Sachse, P., & Maran, T. (2024). Sharing and receiving eye-contact predicts mate choice after a 5-minute conversation: Evidence from a speed-dating study. Archives of Sexual Behavior, 53(3), 959–968.", note: "Dual mobile eye-tracking across 240 speed-dates: partners who shared more eye contact were more likely to be chosen, and receiving eye contact predicted choice.", link: doi("10.1007/s10508-023-02806-0"), kind: "doi" },
      { cite: "Arias-Sarah, P., Bedoya, D., Daube, C., Aucouturier, J.-J., Hall, L., & Johansson, P. (2024). Aligning the smiles of dating dyads causally increases attraction. Proceedings of the National Academy of Sciences, 121(45), e2400369121.", note: "Covertly aligning participants' smiles in real time during video speed-dates causally increased the romantic attraction they felt.", link: doi("10.1073/pnas.2400369121"), kind: "doi" },
      { cite: "Cohen, M., Abargil, M., Ahissar, M., & Atzil, S. (2024). Social and nonsocial synchrony are interrelated and romantically attractive. Communications Psychology, 2, 57.", note: "Induced physiological synchrony raised attractiveness ratings, and people who synchronise well in social and non-social tasks were rated more attractive in live speed-dating.", link: doi("10.1038/s44271-024-00109-1"), kind: "doi" },
      { cite: "Gazzard Kerr, L., & Human, L. J. (2024). Like yourself, and others will follow: The role of target self-esteem in the association between being seen accurately and being liked in platonic and romantic first impressions. Journal of Personality and Social Psychology, 127(4), 936–948.", note: "Across 4,797 speed-dating dyads, being seen accurately hurt liking for people low in self-esteem — self-regard shapes first impressions.", link: doi("10.1037/pspp0000521"), kind: "doi" },
    ],
  },
  {
    id: "gs-partner-slow-burn",
    goal: "partner", tier: "moderate", section: "8807",
    title: "The Slow Burn — Let Familiarity Do Its Work",
    subtitle: "Give people more than one meeting; friends-first is common and sound",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "months", durability: "lasting", effort: "moderate" },
    feeds: ["patience", "uniqueness", "deeper acquaintance"],
    description:
      "Live-interaction studies find that familiarity increases attraction, and that the longer two people knew each other before dating, the less their attractiveness levels matched — consensus about who is desirable fades as unique, relationship-specific appraisals grow. Romantic evaluations after acquaintance are largely idiosyncratic rather than shared, which is why a person overlooked in a lineup can become irreplaceable over months. Metaperception studies show that underestimating how positively others see you dampens your own romantic interest. The boundary: familiarity can also breed contempt when what you learn is dissimilar — the slow burn favours people you already like a little.",
    action: "Give anyone you feel neutral-to-positive about a second and third meeting in a different setting before deciding, and let one shared activity group run for at least three months before judging its romantic potential.",
    sources: [
      { cite: "Reis, H. T., Maniaci, M. R., Caprariello, P. A., Eastwick, P. W., & Finkel, E. J. (2011). Familiarity does indeed promote attraction in live interaction. Journal of Personality and Social Psychology, 101(3), 557–570.", note: "In live interactions, greater familiarity increased attraction, contrary to claims that familiarity breeds contempt.", link: doi("10.1037/a0022885"), kind: "doi" },
      { cite: "Hunt, L. L., Eastwick, P. W., & Finkel, E. J. (2015). Leveling the playing field: Longer acquaintance predicts reduced assortative mating on attractiveness. Psychological Science, 26(7), 1046–1053.", note: "Couples who knew each other longer before dating, or were friends first, were less matched on physical attractiveness — acquaintance loosens the market logic of looks.", link: doi("10.1177/0956797615579273"), kind: "doi" },
      { cite: "Eastwick, P. W., & Hunt, L. L. (2014). Relational mate value: Consensus and uniqueness in romantic evaluations. Journal of Personality and Social Psychology, 106(5), 728–751.", note: "Romantic evaluations became increasingly unique rather than consensual as people got to know one another — mate value is largely relational.", link: doi("10.1037/a0035884"), kind: "doi" },
      { cite: "Norton, M. I., Frost, J. H., & Ariely, D. (2007). Less is more: The lure of ambiguity, or why familiarity breeds contempt. Journal of Personality and Social Psychology, 92(1), 97–105.", note: "More information about a stranger reduced liking on average because dissimilarity cascades — the slow burn works best from a base of some liking.", link: doi("10.1037/0022-3514.92.1.97"), kind: "doi" },
      { cite: "Eastwick, P. W., Finkel, E. J., & Eagly, A. H. (2011). When and why do ideal partner preferences affect the process of initiating and maintaining romantic relationships? Journal of Personality and Social Psychology, 101(5), 1012–1032.", note: "Ideal preferences predicted evaluations of abstract partners but weakly predicted feelings about live and established partners, where relationship-specific experience dominated.", link: doi("10.1037/a0024062"), kind: "doi" },
      { cite: "Tissera, H., Overall, N. C., Cross, E. J., Human, L. J., & Lydon, J. E. (2026). Comparing trait-wise and profile-wise approaches to assess the links between metaperceptions and romantic interest during speed-dating. Personality and Social Psychology Bulletin.", note: "Across 1,730 speed-dating dyads, people who underestimated how positively others saw them expressed lower romantic interest — self-doubt shrinks the pool.", link: doi("10.1177/01461672261436564"), kind: "doi" },
      { cite: "Wu, E. Z., Molden, D. C., & Eastwick, P. W. (2025). Promotion- or prevention-focused self-evaluation and the preferential pursuit of more desirable romantic partners. Journal of Personality, 94(5), 834–848.", note: "Promotion-focused people evaluated themselves more positively and pursued more desirable partners; prevention focus predicted the reverse, beyond self-esteem.", link: doi("10.1111/jopy.70043"), kind: "doi" },
    ],
  },
  {
    id: "gs-partner-strategies",
    goal: "partner", tier: "moderate", section: "8808",
    title: "Stated Preferences Versus Real Choices",
    subtitle: "Know the population patterns; do not use them to judge an individual",
    evidenceTag: "Moderate",
    impact: { magnitude: 2, latency: "weeks", durability: "sustained", effort: "low" },
    feeds: ["realism", "self-knowledge"],
    description:
      "Cross-cultural surveys find stable average sex differences in stated mate preferences and in sociosexual orientation, with 48-nation data showing those differences shrink where gender equality is greater. But the speed-dating literature shows stated preferences fail to predict whom people actually desire in person, and implicit preferences predict live attraction better than explicit ones. Physical attractiveness dominated first-date liking in the classic 1966 experiment, and in modern speed-dating vulnerable narcissism predicted fewer second dates while rivalrous narcissism predicted more. The honest reading: population patterns describe markets, not the person in front of you.",
    action: "Write down your top five stated must-haves, then review your last three real attractions against them; where they diverge, trust the pattern of your behaviour over your list.",
    sources: [
      { cite: "Buss, D. M. (1989). Sex differences in human mate preferences: Evolutionary hypotheses tested in 37 cultures. Behavioral and Brain Sciences, 12(1), 1–14.", note: "37-culture survey documenting average sex differences in stated preferences for earning capacity, youth and attractiveness.", link: doi("10.1017/S0140525X00023992"), kind: "doi" },
      { cite: "Buss, D. M., & Schmitt, D. P. (1993). Sexual strategies theory: An evolutionary perspective on human mating. Psychological Review, 100(2), 204–232.", note: "Proposes that short-term and long-term mating contexts activate different preferences, with nine hypotheses and 22 predictions tested.", link: doi("10.1037/0033-295x.100.2.204"), kind: "doi" },
      { cite: "Schmitt, D. P. (2005). Sociosexuality from Argentina to Zimbabwe: A 48-nation study of sex, culture, and strategies of human mating. Behavioral and Brain Sciences, 28(2), 247–275.", note: "14,059 people in 48 nations: sex differences in sociosexuality were universal but smaller in cultures with more political and economic gender equality.", link: doi("10.1017/s0140525x05000051"), kind: "doi" },
      { cite: "Eastwick, P. W., & Finkel, E. J. (2008). Sex differences in mate preferences revisited: Do people know what they initially desire in a romantic partner? Journal of Personality and Social Psychology, 94(2), 245–264.", note: "Sex-differentiated stated preferences did not predict romantic interest in real partners met at speed-dating events or afterwards.", link: doi("10.1037/0022-3514.94.2.245"), kind: "doi" },
      { cite: "Eastwick, P. W., Eagly, A. H., Finkel, E. J., & Johnson, S. E. (2011). Implicit and explicit preferences for physical attractiveness in a romantic partner: A double dissociation in predictive validity. Journal of Personality and Social Psychology, 101(5), 993–1011.", note: "Explicit attractiveness preferences predicted responses to photographs; implicit preferences predicted interest in live partners — and the two were uncorrelated.", link: doi("10.1037/a0024061"), kind: "doi" },
      { cite: "Walster, E., Aronson, V., Abrahams, D., & Rottman, L. (1966). Importance of physical attractiveness in dating behavior. Journal of Personality and Social Psychology, 4(5), 508–516.", note: "The computer-dance experiment: physical attractiveness was the dominant predictor of liking a randomly assigned first date.", link: doi("10.1037/h0021188"), kind: "doi" },
      { cite: "Hall, B. T., Hart, W., & Lambert, J. T. (2026). Do narcissistic people have more dating success? Evidence from a speed-dating study. Journal of Personality.", note: "Across eight events, vulnerable narcissism predicted fewer second-date offers while rivalrous narcissism predicted more — charm at a first meeting is not a green flag.", link: doi("10.1111/jopy.70059"), kind: "doi" },
      { cite: "Lee, A. J., Zhao, A. A. Z., Sidari, M. J., & Zietsch, B. P. (2026). Do social judgements made from facial photographs predict those made in-person? Quarterly Journal of Experimental Psychology.", note: "In 689 speed-daters, photo-based judgements of attractiveness matched in-person ratings, but judgements of most non-physical traits did not — profiles cannot show character.", link: doi("10.1177/17470218261434907"), kind: "doi" },
    ],
  },
  {
    id: "gs-partner-values-faith",
    goal: "partner", tier: "moderate", section: "8809",
    title: "Shared Values and Faith — a Modest, Real Effect",
    subtitle: "Talk about meaning early; homogamy helps a little",
    evidenceTag: "Moderate",
    impact: { magnitude: 2, latency: "months", durability: "lasting", effort: "low" },
    feeds: ["values alignment", "commitment", "forgiveness"],
    description:
      "A meta-analysis of 94 studies found greater religiousness modestly lowered divorce risk and helped marital functioning, with effects described as small; a decade review of relational spirituality documents that shared sanctification of the relationship tracks better maintenance while religious conflict does harm. Attending services together and shared beliefs predicted marital stability in national data, and praying for one's partner predicted partner-reported forgiveness. Attitude similarity — including on faith and values — is where newlyweds actually match. The boundary: effects are small, mostly correlational, and the mechanism looks like shared meaning and community rather than doctrine.",
    action: "By the third date, name what gives your life meaning and ask the same; by the third month, spend one weekend inside each other's communities — family, faith or friends — and notice whether you could belong there.",
    sources: [
      { cite: "Mahoney, A., Pargament, K. I., Tarakeshwar, N., & Swank, A. B. (2001). Religion in the home in the 1980s and 1990s: A meta-analytic review and conceptual analysis of links between religion, marriage, and parenting. Journal of Family Psychology, 15(4), 559–596.", note: "94 studies: greater religiousness decreased divorce risk and facilitated marital functioning, but the effects were small and measures often crude.", link: doi("10.1037//0893-3200.15.4.559"), kind: "doi" },
      { cite: "Mahoney, A. (2010). Religion in families, 1999–2009: A relational spirituality framework. Journal of Marriage and Family, 72(4), 805–827.", note: "Decade review organising findings into relationship formation, maintenance and transformation, for better and worse.", link: doi("10.1111/j.1741-3737.2010.00732.x"), kind: "doi" },
      { cite: "Call, V. R. A., & Heaton, T. B. (1997). Religious influence on marital stability. Journal for the Scientific Study of Religion, 36(3), 382–392.", note: "Joint attendance and shared religiosity predicted marital stability; differences in attendance raised dissolution risk.", link: doi("10.2307/1387856"), kind: "doi" },
      { cite: "Fincham, F. D., & May, R. W. (2017). Prayer and forgiveness: Beyond relationship quality and extension to marriage. Journal of Family Psychology, 31(6), 734–741.", note: "In dating and married samples, praying for one's partner predicted forgiveness of partner transgressions, including partner-reported forgiveness, controlling for religiosity.", link: doi("10.1037/fam0000331"), kind: "doi" },
      { cite: "Luo, S., & Klohnen, E. C. (2005). Assortative mating and marital quality in newlyweds: A couple-centered approach. Journal of Personality and Social Psychology, 88(2), 304–326.", note: "Newlyweds were substantially similar on attitude-related domains including values — the domain where people actually sort.", link: doi("10.1037/0022-3514.88.2.304"), kind: "doi" },
      { cite: "Lyngstad, T. H., & Jalovaara, M. (2010). A review of the antecedents of union dissolution. Demographic Research, 23, 257–292.", note: "Review of demographic antecedents of divorce and separation, including heterogamy, age at union and prior cohabitation.", link: doi("10.4054/DemRes.2010.23.10"), kind: "doi" },
    ],
  },
  {
    id: "gs-partner-timing",
    goal: "partner", tier: "moderate", section: "8810",
    title: "How Long to Date, How Old to Marry",
    subtitle: "Aim for enough time to see conflict, and marry when ready rather than early",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "months", durability: "lasting", effort: "low" },
    feeds: ["patience", "decision quality"],
    description:
      "Demographic reviews consistently find early marriage a risk factor for dissolution, and US data show later first marriage associated with greater stability, with marital quality gains flattening after the mid-twenties. What you learn while dating matters: self-reported negative premarital communication predicted divorce across the first five years, couples who cohabited before engagement showed more negative interactions and lower commitment ten months into marriage, and disillusionment over the first two years — not early conflict — foreshadowed divorce at 13 years. The boundary: there is no evidence for a magic number of months; the evidence favours seeing each other through stress, money and family before committing.",
    action: "Before getting engaged, make sure you have been through at least one holiday season, one serious disagreement and one financial decision together, and write down what each taught you about how you two repair.",
    sources: [
      { cite: "Glenn, N. D., Uecker, J. E., & Love, R. W. B. (2010). Later first marriage and marital success. Social Science Research, 39(5), 787–800.", note: "Later first marriage was associated with lower divorce, while reported marital quality peaked for marriages in the mid-to-late twenties.", link: doi("10.1016/j.ssresearch.2010.06.002"), kind: "doi" },
      { cite: "Lyngstad, T. H., & Jalovaara, M. (2010). A review of the antecedents of union dissolution. Demographic Research, 23, 257–292.", note: "Young age at union is among the most consistent antecedents of dissolution across countries and cohorts.", link: doi("10.4054/DemRes.2010.23.10"), kind: "doi" },
      { cite: "Markman, H. J., Rhoades, G. K., Stanley, S. M., Ragan, E. P., & Whitton, S. W. (2010). The premarital communication roots of marital distress and divorce: The first five years of marriage. Journal of Family Psychology, 24(3), 289–298.", note: "In 210 couples, self-reported negative premarital communication predicted divorce and lower adjustment across the first five years.", link: doi("10.1037/a0019481"), kind: "doi" },
      { cite: "Huston, T. L., Caughlin, J. P., Houts, R. M., Smith, S. E., & George, L. J. (2001). The connubial crucible: Newlywed years as predictors of marital delight, distress, and divorce. Journal of Personality and Social Psychology, 80(2), 237–252.", note: "Disillusionment across the first two years of marriage distinguished couples headed for divorce — the dating period should reveal whether affection survives ordinary life.", link: doi("10.1037/0022-3514.80.2.237"), kind: "doi" },
      { cite: "Kline, G. H., Stanley, S. M., Markman, H. J., Olmos-Gallo, P. A., St. Peters, M., Whitton, S. W., & Prado, L. M. (2004). Timing is everything: Pre-engagement cohabitation and increased risk for poor marital outcomes. Journal of Family Psychology, 18(2), 311–318.", note: "136 couples: those who cohabited before engagement had more negative interactions, lower commitment and lower relationship confidence before and after marriage, controlling for selection.", link: doi("10.1037/0893-3200.18.2.311"), kind: "doi" },
      { cite: "Karney, B. R., & Bradbury, T. N. (1995). The longitudinal course of marital quality and stability: A review of theory, method, and research. Psychological Bulletin, 118(1), 3–34.", note: "Review of longitudinal predictors of marital outcomes, including age at marriage and premarital factors.", link: doi("10.1037/0033-2909.118.1.3"), kind: "doi" },
    ],
  },
  {
    id: "gs-partner-cohabitation",
    goal: "partner", tier: "moderate", section: "8811",
    title: "Move In by Deciding, Not Sliding",
    subtitle: "Make cohabitation an explicit, mutual commitment step",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "months", durability: "lasting", effort: "moderate" },
    feeds: ["commitment clarity", "inertia awareness"],
    description:
      "A meta-analysis of 16 studies found premarital cohabitation negatively associated with marital stability and quality, and the effect is concentrated among couples who moved in before deciding to marry: pre-engagement cohabiters reported lower satisfaction, dedication and confidence and more negative communication than those who cohabited after engagement or not at all. The 'sliding versus deciding' account explains this through inertia — shared leases and belongings make it harder to leave a relationship that would otherwise have ended. The honest boundary: a recent national analysis found cohabitation's association with divorce depends on the timing and the couple's cohabitation history, and relationship education erased the pre-engagement cohabitation risk in an Army trial.",
    action: "Do not move in together until you have both said out loud what it means for the future; if you already live together without that conversation, have it this month and set a date to revisit the decision.",
    sources: [
      { cite: "Stanley, S. M., Rhoades, G. K., & Markman, H. J. (2006). Sliding versus deciding: Inertia and the premarital cohabitation effect. Family Relations, 55(4), 499–509.", note: "Proposes that cohabitation raises constraints before dedication, creating inertia that carries some couples into marriages they would not otherwise have chosen.", link: doi("10.1111/j.1741-3729.2006.00418.x"), kind: "doi" },
      { cite: "Rhoades, G. K., Stanley, S. M., & Markman, H. J. (2009). The pre-engagement cohabitation effect: A replication and extension of previous findings. Journal of Family Psychology, 23(1), 107–111.", note: "Random telephone survey of 1,050 married people: cohabiting before engagement predicted lower satisfaction, dedication and confidence and more negative communication than cohabiting after engagement or not at all.", link: doi("10.1037/a0014358"), kind: "doi" },
      { cite: "Kline, G. H., Stanley, S. M., Markman, H. J., Olmos-Gallo, P. A., St. Peters, M., Whitton, S. W., & Prado, L. M. (2004). Timing is everything: Pre-engagement cohabitation and increased risk for poor marital outcomes. Journal of Family Psychology, 18(2), 311–318.", note: "Longitudinal, observationally coded data replicating the pre-engagement cohabitation risk after controlling for selection and cohabitation duration.", link: doi("10.1037/0893-3200.18.2.311"), kind: "doi" },
      { cite: "Jose, A., O'Leary, K. D., & Moyer, A. (2010). Does premarital cohabitation predict subsequent marital stability and marital quality? A meta-analysis. Journal of Marriage and Family, 72(1), 105–116.", note: "Meta-analysis: cohabitation had a significant negative association with marital stability (k = 16) and quality (k = 12).", link: doi("10.1111/j.1741-3737.2009.00686.x"), kind: "doi" },
      { cite: "Rosenfeld, M. J., & Roesler, K. (2019). Cohabitation experience and cohabitation's association with marital dissolution. Journal of Marriage and Family, 81(1), 42–58.", note: "National data: premarital cohabitation was associated with lower dissolution in the first year of marriage and higher dissolution later — the association depends on timing.", link: doi("10.1111/jomf.12530"), kind: "doi" },
      { cite: "Rhoades, G. K., Stanley, S. M., Markman, H. J., & Allen, E. S. (2015). Can marriage education mitigate the risks associated with premarital cohabitation? Journal of Family Psychology, 29(3), 500–506.", note: "In 662 Army couples, the pre-commitment cohabitation risk for satisfaction, dedication and divorce appeared only in the control group, not among couples who received relationship education.", link: doi("10.1037/fam0000081"), kind: "doi" },
    ],
  },
  {
    id: "gs-partner-red-flags",
    goal: "partner", tier: "advanced", section: "8812",
    title: "Red Flags — Risk Markers for Partner Violence",
    subtitle: "Controlling behaviour, jealousy, prior violence and threats are not quirks",
    evidenceTag: "Strong",
    impact: { magnitude: 5, latency: "days", durability: "lasting", effort: "low" },
    feeds: ["safety", "boundary setting"],
    description:
      "Meta-analyses spanning hundreds of studies converge on the strongest risk markers for physical partner violence: other forms of violence, especially emotional abuse and prior aggression, plus relationship dynamics such as controlling behaviour, jealousy and demand–withdraw conflict. A 503-study synthesis found perpetration and victimisation histories and relationship dynamics dominated; a homicide meta-analysis identified access to a gun, prior non-fatal strangulation, threats with a weapon, controlling behaviour and prior threats as the strongest markers for intimate partner homicide. Control, power, jealousy and patriarchal beliefs were stronger markers in clinical than community samples, marking the more dangerous 'intimate terrorism' pattern. This is a screening list, not a diagnosis: a single marker proves nothing, a cluster warrants leaving with support.",
    action: "In the first three months, watch specifically for monitoring, jealousy, attempts to isolate you from friends, contempt toward exes and any threat or shove; if two or more appear, tell someone you trust this week and end the relationship with a safety plan.",
    sources: [
      { cite: "Stith, S. M., Smith, D. B., Penn, C. E., Ward, D. B., & Tritt, D. (2004). Intimate partner physical abuse perpetration and victimization risk factors: A meta-analytic review. Aggression and Violent Behavior, 10(1), 65–98.", note: "Foundational meta-analysis of individual, relationship and contextual risk factors for physical partner abuse, with emotional abuse and prior violence among the strongest.", link: doi("10.1016/j.avb.2003.09.001"), kind: "doi" },
      { cite: "Capaldi, D. M., Knoble, N. B., Shortt, J. W., & Kim, H. K. (2012). A systematic review of risk factors for intimate partner violence. Partner Abuse, 3(2), 231–280.", note: "228 articles organised by a developmental-systems perspective: demographic, family-of-origin, psychological, relationship and contextual risk factors.", link: doi("10.1891/1946-6560.3.2.231"), kind: "doi" },
      { cite: "Spencer, C. M., Stith, S. M., & Cafferky, B. (2022). What puts individuals at risk for physical intimate partner violence perpetration? A meta-analysis examining risk markers for men and women. Trauma, Violence, & Abuse, 23(1), 36–51.", note: "503 studies, 2,972 effect sizes: the strongest markers were other acts of violence (perpetration and victimisation) and relationship dynamics, with 9 of 44 markers differing by sex.", link: doi("10.1177/1524838020925776"), kind: "doi" },
      { cite: "Spencer, C., Stith, S. M., & Cafferky, B. (2020). Risk factors for male perpetration and female victimization of intimate partner homicide: A meta-analysis. Trauma, Violence, & Abuse, 21(3), 527–540.", note: "17 studies: direct access to a gun, prior non-fatal strangulation, prior rape of the victim, threats with a weapon, controlling behaviours and prior threats were the strongest homicide risk factors.", link: doi("10.1177/1524838018781101"), kind: "doi" },
      { cite: "Love, H. A., Spencer, C. M., May, S. A., Mendez, M., & Stith, S. M. (2020). Perpetrator risk markers for intimate terrorism and situational couple violence: A meta-analysis. Trauma, Violence, & Abuse, 21(5), 922–931.", note: "149 studies: control, power, jealousy and patriarchal beliefs were significantly stronger markers in clinical samples, supporting a continuum with controlling violence at the severe end.", link: doi("10.1177/1524838018801331"), kind: "doi" },
      { cite: "Kimmes, J. G., Mallory, A. B., Spencer, C., Beck, A. R., Cafferky, B., & Stith, S. M. (2019). A meta-analysis of risk markers for intimate partner violence in same-sex relationships. Trauma, Violence, & Abuse, 20(3), 374–384.", note: "24 studies: psychological-abuse perpetration was the strongest risk marker for physical IPV in same-sex relationships for both men and women.", link: doi("10.1177/1524838017708784"), kind: "doi" },
      { cite: "Spencer, C. M., Toews, M. L., Anders, K. M., & Emanuels, S. K. (2021). Risk markers for physical teen dating violence perpetration: A meta-analysis. Trauma, Violence, & Abuse, 22(3), 619–631.", note: "37 US studies: approval of violence, externalising behaviours and controlling behaviour (stronger for males) predicted dating-violence perpetration; conflict-resolution skills were protective.", link: doi("10.1177/1524838019875700"), kind: "doi" },
      { cite: "Jongsma, K., & Timmons Fritz, P. (2022). The role of pornography use in intimate partner violence in different-sex couples: A prospective longitudinal study. Journal of Interpersonal Violence, 37(21–22), NP20260–NP20281.", note: "132 couples over four months: men's frequent pornography use predicted increases in IPV perpetration and victimisation for both partners.", link: doi("10.1177/08862605211055145"), kind: "doi" },
    ],
  },
  {
    id: "gs-partner-loneliness",
    goal: "partner", tier: "advanced", section: "8813",
    title: "Treat Loneliness Directly While You Search",
    subtitle: "Cognitive-behavioural work on social cognition, not just more events",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "weeks", durability: "sustained", effort: "moderate" },
    feeds: ["mood", "social confidence", "health"],
    description:
      "Loneliness is a health risk on the scale of established mortality risk factors, and in a meta-analysis of loneliness interventions the most effective randomised approach was not creating more social contact but addressing maladaptive social cognition — the expectation of rejection that makes lonely people withdraw. An eight-week therapist-guided internet CBT program reduced loneliness with a moderate effect (d = 0.77) in a pilot RCT and d = 0.71 against waitlist in a 170-person three-arm trial, where internet interpersonal therapy did not outperform waitlist. The boundary: gains were maintained but not improved at four-month follow-up, and most trials are small and Swedish.",
    action: "If loneliness is a daily feeling, enrol in a structured CBT-based loneliness program (online or with a therapist) for eight weeks and keep dating alongside it rather than waiting to feel better first.",
    sources: [
      { cite: "Masi, C. M., Chen, H.-Y., Hawkley, L. C., & Cacioppo, J. T. (2011). A meta-analysis of interventions to reduce loneliness. Personality and Social Psychology Review, 15(3), 219–266.", note: "Among randomised comparisons, interventions addressing maladaptive social cognition were the most effective; social-skills and social-contact approaches yielded smaller effects.", link: doi("10.1177/1088868310377394"), kind: "doi" },
      { cite: "Hickin, N., Käll, A., Shafran, R., Sutcliffe, S., Manzotti, G., & Langan, D. (2021). The effectiveness of psychological interventions for loneliness: A systematic review and meta-analysis. Clinical Psychology Review, 88, 102066.", note: "Meta-analysis of psychological interventions confirming a moderate pooled effect on loneliness, with CBT-based approaches best supported.", link: doi("10.1016/j.cpr.2021.102066"), kind: "doi" },
      { cite: "Käll, A., Jägholm, S., Hesser, H., Andersson, F., Mathaldi, A., Norkvist, B. T., Shafran, R., & Andersson, G. (2020). Internet-based cognitive behavior therapy for loneliness: A pilot randomized controlled trial. Behavior Therapy, 51(1), 54–68.", note: "73 adults: eight weeks of guided internet CBT reduced loneliness versus waitlist (d = 0.77) and improved quality of life and social anxiety.", link: doi("10.1016/j.beth.2019.05.001"), kind: "doi" },
      { cite: "Käll, A., Bäck, M., Welin, C., Åman, H., Bjerkander, R., Wänman, M., et al. (2021). Therapist-guided internet-based treatments for loneliness: A randomized controlled three-arm trial comparing cognitive behavioral therapy and interpersonal psychotherapy. Psychotherapy and Psychosomatics, 90(5), 351–358.", note: "170 participants: internet CBT reduced loneliness versus waitlist (d = 0.71) and versus internet interpersonal therapy (d = 0.53), which did not beat waitlist; gains held at four months.", link: doi("10.1159/000516989"), kind: "doi" },
      { cite: "Cacioppo, S., Grippo, A. J., London, S., Goossens, L., & Cacioppo, J. T. (2015). Loneliness: Clinical import and interventions. Perspectives on Psychological Science, 10(2), 238–249.", note: "Review of loneliness assessment and treatment, building on the meta-analytic case for targeting maladaptive social cognition.", link: doi("10.1177/1745691615570616"), kind: "doi" },
      { cite: "Holt-Lunstad, J., Smith, T. B., & Layton, J. B. (2010). Social relationships and mortality risk: A meta-analytic review. PLoS Medicine, 7(7), e1000316.", note: "148 studies, 308,849 participants: stronger social relationships were associated with 50% greater likelihood of survival, comparable to established mortality risk factors.", link: doi("10.1371/journal.pmed.1000316"), kind: "doi" },
      { cite: "Eccles, A. M., & Qualter, P. (2021). Alleviating loneliness in young people — a meta-analysis of interventions. Child and Adolescent Mental Health, 26(1), 17–33.", note: "39 studies: interventions reduced loneliness among people aged 25 and under, though few targeted those who actually reported loneliness.", link: doi("10.1111/camh.12389"), kind: "doi" },
    ],
  },
  {
    id: "gs-partner-social-anxiety",
    goal: "partner", tier: "advanced", section: "8814",
    title: "If Dating Terrifies You, Treat the Anxiety First",
    subtitle: "Individual CBT for social anxiety has the strongest evidence",
    evidenceTag: "Strong",
    impact: { magnitude: 4, latency: "months", durability: "lasting", effort: "high" },
    feeds: ["approach behaviour", "confidence", "presence on dates"],
    description:
      "For adults whose fear of judgement blocks dating, a network meta-analysis of 101 trials found individual cognitive-behavioural therapy the most effective intervention for social anxiety disorder (SMD −1.19 versus waitlist), outperforming psychodynamic, interpersonal, mindfulness and supportive therapies and matching or beating medication; a randomised trial found cognitive therapy left 84% free of the diagnosis versus 42% for exposure plus relaxation. A meta-analysis of 29 randomised psychological-treatment studies found mean effects of 0.70 on social anxiety. Loneliness CBT also reduced social anxiety as a secondary outcome. The boundary: this is for clinical-level anxiety; ordinary first-date nerves respond to exposure — more dates.",
    action: "If social anxiety has kept you from asking anyone out for a year, book an assessment with a CBT-trained clinician this month and complete a full course before judging your dating prospects.",
    sources: [
      { cite: "Mayo-Wilson, E., Dias, S., Mavranezouli, I., Kew, K., Clark, D. M., Ades, A. E., & Pilling, S. (2014). Psychological and pharmacological interventions for social anxiety disorder in adults: A systematic review and network meta-analysis. The Lancet Psychiatry, 1(5), 368–376.", note: "101 trials, 13,164 participants: individual CBT had the largest effect (SMD −1.19 versus waitlist) and outperformed psychodynamic, interpersonal, mindfulness and supportive therapies.", link: doi("10.1016/S2215-0366(14)70329-3"), kind: "doi" },
      { cite: "Acarturk, C., Cuijpers, P., van Straten, A., & de Graaf, R. (2009). Psychological treatment of social anxiety disorder: A meta-analysis. Psychological Medicine, 39(2), 241–254.", note: "29 randomised studies, 1,628 participants: mean effect of 0.70 on social anxiety measures, smaller against placebo and care-as-usual controls.", link: doi("10.1017/S0033291708003590"), kind: "doi" },
      { cite: "Clark, D. M., Ehlers, A., Hackmann, A., McManus, F., Fennell, M., Grey, N., Waddington, L., & Wild, J. (2006). Cognitive therapy versus exposure and applied relaxation in social phobia: A randomized controlled trial. Journal of Consulting and Clinical Psychology, 74(3), 568–578.", note: "62 patients: after cognitive therapy 84% no longer met criteria for social phobia versus 42% after exposure plus applied relaxation, with differences persisting at one year.", link: doi("10.1037/0022-006X.74.3.568"), kind: "doi" },
      { cite: "Käll, A., Bäck, M., Welin, C., Åman, H., Bjerkander, R., Wänman, M., et al. (2021). Therapist-guided internet-based treatments for loneliness: A randomized controlled three-arm trial comparing cognitive behavioral therapy and interpersonal psychotherapy. Psychotherapy and Psychosomatics, 90(5), 351–358.", note: "Internet CBT for loneliness also lowered depression and generalised anxiety relative to waitlist — the same skills transfer.", link: doi("10.1159/000516989"), kind: "doi" },
      { cite: "Gazzard Kerr, L., & Human, L. J. (2024). Like yourself, and others will follow: The role of target self-esteem in the association between being seen accurately and being liked in platonic and romantic first impressions. Journal of Personality and Social Psychology, 127(4), 936–948.", note: "Being seen accurately hurt liking for people low in self-esteem in romantic first impressions — self-regard is worth treating before the date.", link: doi("10.1037/pspp0000521"), kind: "doi" },
      { cite: "Masi, C. M., Chen, H.-Y., Hawkley, L. C., & Cacioppo, J. T. (2011). A meta-analysis of interventions to reduce loneliness. Personality and Social Psychology Review, 15(3), 219–266.", note: "Social-skills training was one of four intervention families reviewed; cognitive approaches outperformed it in randomised comparisons.", link: doi("10.1177/1088868310377394"), kind: "doi" },
    ],
  },
  {
    id: "gs-partner-self-expansion",
    goal: "partner", tier: "advanced", section: "8815",
    title: "Self-Expansion — Become the Partner You Want to Meet",
    subtitle: "A three-month program of new skills, places and people",
    evidenceTag: "Moderate",
    impact: { magnitude: 3, latency: "months", durability: "lasting", effort: "moderate" },
    feeds: ["self-concept", "attractiveness", "resilience after breakups"],
    description:
      "The self-expansion model holds that people seek relationships to grow — and that falling in love measurably enlarges the self-concept, as prospective studies of students entering relationships showed. Novel, arousing shared activities raise relationship quality in experiments, and people with a promotion-focused self-view pursue more desirable partners. The practical inversion for singles is to expand deliberately: new competences, places and communities both make you more interesting to meet and widen the field. The boundary: the direct evidence is on couples and self-concept change; the single-person application is an extrapolation with face validity, not a tested program.",
    action: "For the next three months, take up one skill you have wanted for years and join one recurring group around it; treat the growth as the goal and any meeting as a by-product.",
    sources: [
      { cite: "Aron, A., Aron, E. N., & Smollan, D. (1992). Inclusion of Other in the Self Scale and the structure of interpersonal closeness. Journal of Personality and Social Psychology, 63(4), 596–612.", note: "Introduces the inclusion-of-other-in-the-self measure underlying the self-expansion model of closeness.", link: doi("10.1037/0022-3514.63.4.596"), kind: "doi" },
      { cite: "Aron, A., Aron, E. N., Tudor, M., & Nelson, G. (1991). Close relationships as including other in the self. Journal of Personality and Social Psychology, 60(2), 241–253.", note: "Experiments showing that in close relationships the partner's resources, perspectives and identities are cognitively included in the self.", link: doi("10.1037/0022-3514.60.2.241"), kind: "doi" },
      { cite: "Aron, A., Paris, M., & Aron, E. N. (1995). Falling in love: Prospective studies of self-concept change. Journal of Personality and Social Psychology, 69(6), 1102–1112.", note: "Prospective studies: students who fell in love showed increased self-concept diversity and self-efficacy compared with those who did not.", link: doi("10.1037/0022-3514.69.6.1102"), kind: "doi" },
      { cite: "Aron, A., Norman, C. C., Aron, E. N., McKenna, C., & Heyman, R. E. (2000). Couples' shared participation in novel and arousing activities and experienced relationship quality. Journal of Personality and Social Psychology, 78(2), 273–284.", note: "Seven minutes of a novel, arousing joint task raised relationship quality in three experiments — expansion is what people want from a partner.", link: doi("10.1037/0022-3514.78.2.273"), kind: "doi" },
      { cite: "Wu, E. Z., Molden, D. C., & Eastwick, P. W. (2025). Promotion- or prevention-focused self-evaluation and the preferential pursuit of more desirable romantic partners. Journal of Personality, 94(5), 834–848.", note: "In longitudinal and speed-dating samples, promotion-focused self-evaluation predicted pursuing more desirable partners beyond self-esteem — growth orientation shapes whom you approach.", link: doi("10.1111/jopy.70043"), kind: "doi" },
    ],
  },
  {
    id: "gs-partner-education-before-commit",
    goal: "partner", tier: "elite", section: "8816",
    title: "Relationship Education Before You Commit",
    subtitle: "A structured program while still free to walk away",
    evidenceTag: "Moderate",
    impact: { magnitude: 4, latency: "months", durability: "lasting", effort: "high" },
    feeds: ["communication", "commitment clarity", "later help-seeking"],
    description:
      "Divorced people who had received premarital education recommended, above all, getting it before committing — when a break-up would still be easy. A large random survey linked premarital education to higher satisfaction and lower divorce odds across income and race, and couples who had it later sought therapy earlier and at higher satisfaction. Relationship education neutralised the pre-engagement cohabitation risk in an Army trial. The honest boundary: an eight-year RCT found no overall divorce reduction, and couples already high in negative communication before marriage divorced more after the program — so use it as a stress test of the relationship, not a guarantee.",
    action: "Once a relationship is serious but before engagement or moving in, complete a structured relationship-education course together and treat what it surfaces — especially how you argue — as decision-grade information.",
    sources: [
      { cite: "Scott, S. B., Rhoades, G. K., Stanley, S. M., Allen, E. S., & Markman, H. J. (2013). Reasons for divorce and recollections of premarital intervention: Implications for improving relationship education. Couple and Family Psychology: Research and Practice, 2(2), 131–145.", note: "52 divorced people who had PREP while engaged: top reasons for divorce were lack of commitment, infidelity and conflict, and they recommended receiving education before committing to marry.", link: doi("10.1037/a0032025"), kind: "doi" },
      { cite: "Stanley, S. M., Amato, P. R., Johnson, C. A., & Markman, H. J. (2006). Premarital education, marital quality, and marital stability: Findings from a large, random household survey. Journal of Family Psychology, 20(1), 117–126.", note: "Random survey of four states: premarital education was associated with higher satisfaction and commitment, lower conflict and reduced odds of divorce across race, income and education.", link: doi("10.1037/0893-3200.20.1.117"), kind: "doi" },
      { cite: "Markman, H. J., Rhoades, G. K., Stanley, S. M., Ragan, E. P., & Whitton, S. W. (2010). The premarital communication roots of marital distress and divorce: The first five years of marriage. Journal of Family Psychology, 24(3), 289–298.", note: "Negative premarital communication predicted divorce and lower adjustment — the thing a pre-commitment program can expose.", link: doi("10.1037/a0019481"), kind: "doi" },
      { cite: "Williamson, H. C., Hammett, J. F., Ross, J., Karney, B. R., & Bradbury, T. N. (2018). Premarital education and later relationship help-seeking. Journal of Family Psychology, 32(2), 276–281.", note: "Among 431 low-income newlywed couples, premarital education predicted considering and seeking therapy earlier and at higher satisfaction.", link: doi("10.1037/fam0000383"), kind: "doi" },
      { cite: "Rhoades, G. K., Stanley, S. M., Markman, H. J., & Allen, E. S. (2015). Can marriage education mitigate the risks associated with premarital cohabitation? Journal of Family Psychology, 29(3), 500–506.", note: "The pre-commitment cohabitation risk for declining satisfaction and divorce appeared only among control couples, not those who received PREP.", link: doi("10.1037/fam0000081"), kind: "doi" },
      { cite: "Markman, H. J., Rhoades, G. K., Stanley, S. M., & Peterson, K. M. (2013). A randomized clinical trial of the effectiveness of premarital intervention: Moderators of divorce outcomes. Journal of Family Psychology, 27(1), 165–172.", note: "Eight-year RCT: no overall divorce difference, and couples with high premarital negativity divorced more after PREP than after usual services — education can reveal a poor fit.", link: doi("10.1037/a0031134"), kind: "doi" },
      { cite: "Owen, J., Rhoades, G. K., Stanley, S. M., & Markman, H. J. (2011). The role of leaders' working alliance in premarital education. Journal of Family Psychology, 25(1), 49–57.", note: "Outcomes varied by program leader and by attendees' alliance with the leader — choose the facilitator carefully.", link: doi("10.1037/a0022084"), kind: "doi" },
    ],
  },
  {
    id: "gs-partner-stay-leave",
    goal: "partner", tier: "elite", section: "8817",
    title: "Decide to Stay or Leave on Purpose",
    subtitle: "A structured review of reasons, ambivalence and growth beliefs",
    evidenceTag: "Moderate",
    impact: { magnitude: 4, latency: "weeks", durability: "lasting", effort: "moderate" },
    feeds: ["decision quality", "self-honesty", "growth mindset"],
    description:
      "Research on stay/leave decisions catalogued 27 reasons people want to stay and 23 to leave, found most map onto satisfaction and commitment, and found that many people contemplating a break-up were simultaneously motivated to stay and to go — ambivalence is the norm, and attachment anxiety amplifies both. Whether you read a relationship as 'meant to be' shapes the decision: destiny beliefs tie longevity to initial satisfaction and predict avoidance coping and quicker exits, while growth beliefs predict relationship-maintaining coping; experimentally inducing a work-it-out theory changed satisfaction processes. The largest predictors of quality are how the two of you treat each other, so the review should weigh that above the checklist. The boundary: no study shows a decision protocol improves later outcomes.",
    action: "When you are seriously unsure about a relationship, write two columns — reasons to stay and reasons to leave — sort each by whether it is about how you treat each other or about circumstances, then discuss the top three in each column with a trusted friend or therapist before deciding within 30 days.",
    sources: [
      { cite: "Joel, S., MacDonald, G., & Page-Gould, E. (2018). Wanting to stay and wanting to go: Unpacking the content and structure of relationship stay/leave decision processes. Social Psychological and Personality Science, 9(6), 631–644.", note: "27 reasons to stay and 23 to leave were identified; among people contemplating break-up or divorce, many endorsed both, and attachment anxiety predicted stronger endorsement of both.", link: doi("10.1177/1948550617722834"), kind: "doi" },
      { cite: "Joel, S., Eastwick, P. W., Allison, C. J., Arriaga, X. B., Baker, Z. G., Bar-Kalifa, E., et al. (2020). Machine learning uncovers the most robust self-report predictors of relationship quality across 43 longitudinal couples studies. Proceedings of the National Academy of Sciences, 117(32), 19061–19071.", note: "Perceived partner commitment, appreciation, sexual satisfaction and conflict were the robust predictors — the columns that should carry the most weight.", link: doi("10.1073/pnas.1917036117"), kind: "doi" },
      { cite: "Knee, C. R. (1998). Implicit theories of relationships: Assessment and prediction of romantic relationship initiation, coping, and longevity. Journal of Personality and Social Psychology, 74(2), 360–370.", note: "Belief in romantic destiny strengthened the link between initial satisfaction and longevity and predicted avoidance coping; growth belief predicted relationship-maintaining coping.", link: doi("10.1037/0022-3514.74.2.360"), kind: "doi" },
      { cite: "Franiuk, R., Cohen, D., & Pomerantz, E. M. (2002). Implicit theories of relationships: Implications for relationship satisfaction and longevity. Personal Relationships, 9(4), 345–367.", note: "Soulmate theorists' satisfaction and longevity depended far more on feeling the partner was ideal than work-it-out theorists' did; theories were highly stable over eight months.", link: doi("10.1111/1475-6811.09401"), kind: "doi" },
      { cite: "Franiuk, R., Pomerantz, E. M., & Cohen, D. (2004). The causal role of theories of relationships: Consequences for satisfaction and cognitive strategies. Personality and Social Psychology Bulletin, 30(11), 1494–1507.", note: "Experimentally inducing a soulmate versus work-it-out theory changed how satisfaction depended on perceived partner fit.", link: doi("10.1177/0146167204264894"), kind: "doi" },
      { cite: "Huston, T. L., Caughlin, J. P., Houts, R. M., Smith, S. E., & George, L. J. (2001). The connubial crucible: Newlywed years as predictors of marital delight, distress, and divorce. Journal of Personality and Social Psychology, 80(2), 237–252.", note: "Disillusionment — abating love and affection, rising ambivalence — rather than early conflict marked the couples who later divorced.", link: doi("10.1037/0022-3514.80.2.237"), kind: "doi" },
      { cite: "Love, H. A., Spencer, C. M., May, S. A., Mendez, M., & Stith, S. M. (2020). Perpetrator risk markers for intimate terrorism and situational couple violence: A meta-analysis. Trauma, Violence, & Abuse, 21(5), 922–931.", note: "Control, jealousy and power markers distinguish the dangerous pattern — any of these moves the decision from ambivalence to safety planning.", link: doi("10.1177/1524838018801331"), kind: "doi" },
    ],
  },
  {
    id: "gs-partner-widen-pool",
    goal: "partner", tier: "elite", section: "8818",
    title: "A Year-Long System for Meeting People",
    subtitle: "Two recurring in-person communities plus one online channel, reviewed quarterly",
    evidenceTag: "Moderate",
    impact: { magnitude: 4, latency: "months", durability: "lasting", effort: "high" },
    feeds: ["access", "familiarity", "social network"],
    description:
      "The research points to a two-channel strategy. Online dating delivers access and now accounts for the largest share of new US couples, with slightly better marital outcomes in one national sample. Live interaction delivers what profiles cannot: familiarity increases attraction, long acquaintance loosens the attractiveness market, and unique appraisals form only through repeated contact — which favours recurring groups over one-off events. Social integration itself is a health asset. The elite move is to run both channels deliberately for a year: online for reach, recurring communities for depth, and a quarterly review of what is producing real meetings.",
    action: "Commit for twelve months to two recurring in-person communities (weekly or fortnightly) and one online channel; every quarter, count first meetings from each and drop or replace the weakest channel.",
    sources: [
      { cite: "Rosenfeld, M. J., Thomas, R. J., & Hausen, S. (2019). Disintermediating your friends: How online dating in the United States displaces other ways of meeting. Proceedings of the National Academy of Sciences, 116(36), 17753–17758.", note: "Online meeting overtook meeting through friends — the online channel is where reach now lives.", link: doi("10.1073/pnas.1908630116"), kind: "doi" },
      { cite: "Rosenfeld, M. J., & Thomas, R. J. (2012). Searching for a mate: The rise of the Internet as a social intermediary. American Sociological Review, 77(4), 523–547.", note: "Internet search helped most in thin markets — people with fewer natural opportunities to meet partners.", link: doi("10.1177/0003122412448050"), kind: "doi" },
      { cite: "Cacioppo, J. T., Cacioppo, S., Gonzaga, G. C., Ogburn, E. L., & VanderWeele, T. J. (2013). Marital satisfaction and break-ups differ across on-line and off-line meeting venues. Proceedings of the National Academy of Sciences, 110(25), 10135–10140.", note: "Marriages that began online showed slightly higher satisfaction and lower break-up in a national sample of 19,131.", link: doi("10.1073/pnas.1222447110"), kind: "doi" },
      { cite: "Reis, H. T., Maniaci, M. R., Caprariello, P. A., Eastwick, P. W., & Finkel, E. J. (2011). Familiarity does indeed promote attraction in live interaction. Journal of Personality and Social Psychology, 101(3), 557–570.", note: "Repeated live interaction increased attraction — the case for recurring groups over single events.", link: doi("10.1037/a0022885"), kind: "doi" },
      { cite: "Hunt, L. L., Eastwick, P. W., & Finkel, E. J. (2015). Leveling the playing field: Longer acquaintance predicts reduced assortative mating on attractiveness. Psychological Science, 26(7), 1046–1053.", note: "Longer acquaintance before dating reduced attractiveness matching — time in a community changes who becomes possible.", link: doi("10.1177/0956797615579273"), kind: "doi" },
      { cite: "Finkel, E. J., Eastwick, P. W., Karney, B. R., Reis, H. T., & Sprecher, S. (2012). Online dating: A critical analysis from the perspective of psychological science. Psychological Science in the Public Interest, 13(1), 3–66.", note: "Access is online dating's real advantage; compatibility must be discovered in person.", link: doi("10.1177/1529100612436522"), kind: "doi" },
      { cite: "Holt-Lunstad, J., Smith, T. B., & Layton, J. B. (2010). Social relationships and mortality risk: A meta-analytic review. PLoS Medicine, 7(7), e1000316.", note: "Complex measures of social integration showed the strongest association with survival (OR = 1.91) — the communities are worth it even before they produce a partner.", link: doi("10.1371/journal.pmed.1000316"), kind: "doi" },
    ],
  },
  {
    id: "gs-partner-myth-soulmate",
    goal: "partner", tier: "fundamental", section: "8819",
    title: "Myth: 'There Is One Soulmate' and 'Opposites Attract'",
    subtitle: "Destiny beliefs shorten relationships; complementarity has no support",
    evidenceTag: "Strong",
    impact: { magnitude: 1, latency: "weeks", durability: "transient", effort: "low" },
    callout: "Rated at the floor because both ideas fail the evidence. Belief in romantic destiny predicts avoidance coping and faster exits when a relationship stops feeling perfect, whereas belief that relationships are grown predicts maintenance. And a 313-study meta-analysis found similarity, not complementarity, predicts attraction, while newlyweds match on attitudes and attachment, not opposing traits. The useful residue: expect to build, not to find.",
    description:
      "Soulmate and destiny theories are stable, widespread and costly: for destiny believers the relationship's future hinges on initial satisfaction and on feeling the partner is ideal, and inducing a soulmate theory experimentally makes satisfaction depend on perceived fit. Growth or work-it-out theories predict long-term dating approaches and constructive coping. On complementarity, there is no meta-analytic support for opposites attracting; actual similarity predicts attraction early on, perceived similarity throughout, and personality similarity explains almost nothing either way.",
    action: "Replace 'is this the one?' with 'are we getting better at this?' — after each disagreement over the next month, note whether the two of you repaired faster than the time before.",
    sources: [
      { cite: "Knee, C. R. (1998). Implicit theories of relationships: Assessment and prediction of romantic relationship initiation, coping, and longevity. Journal of Personality and Social Psychology, 74(2), 360–370.", note: "Destiny belief tied longevity to initial satisfaction and predicted avoidance coping and taking responsibility for ending relationships; growth belief predicted maintenance-oriented coping.", link: doi("10.1037/0022-3514.74.2.360"), kind: "doi" },
      { cite: "Franiuk, R., Cohen, D., & Pomerantz, E. M. (2002). Implicit theories of relationships: Implications for relationship satisfaction and longevity. Personal Relationships, 9(4), 345–367.", note: "527 students followed eight months: for soulmate theorists, feeling the partner was ideal predicted satisfaction and longevity far more than for work-it-out theorists.", link: doi("10.1111/1475-6811.09401"), kind: "doi" },
      { cite: "Franiuk, R., Pomerantz, E. M., & Cohen, D. (2004). The causal role of theories of relationships: Consequences for satisfaction and cognitive strategies. Personality and Social Psychology Bulletin, 30(11), 1494–1507.", note: "Inducing soulmate versus work-it-out theories causally changed the dependence of satisfaction on perceived partner fit.", link: doi("10.1177/0146167204264894"), kind: "doi" },
      { cite: "Montoya, R. M., Horton, R. S., & Kirchner, J. (2008). Is actual similarity necessary for attraction? A meta-analysis of actual and perceived similarity. Journal of Social and Personal Relationships, 25(6), 889–922.", note: "Similarity, not complementarity, predicted attraction across 313 studies.", link: doi("10.1177/0265407508096700"), kind: "doi" },
      { cite: "Luo, S., & Klohnen, E. C. (2005). Assortative mating and marital quality in newlyweds: A couple-centered approach. Journal of Personality and Social Psychology, 88(2), 304–326.", note: "Newlyweds matched on attitudes, and similarity — not opposition — on personality and attachment predicted marital quality.", link: doi("10.1037/0022-3514.88.2.304"), kind: "doi" },
      { cite: "Dyrenforth, P. S., Kashy, D. A., Donnellan, M. B., & Lucas, R. E. (2010). Predicting relationship and life satisfaction from personality in nationally representative samples from three countries: The relative importance of actor, partner, and similarity effects. Journal of Personality and Social Psychology, 99(4), 690–702.", note: "Neither similarity nor difference in personality explained meaningful variance in satisfaction across three national samples.", link: doi("10.1037/a0020385"), kind: "doi" },
    ],
  },
  {
    id: "gs-partner-myth-checklist",
    goal: "partner", tier: "fundamental", section: "8819",
    title: "Myth: 'Know Exactly What You Want and Filter for It'",
    subtitle: "Stated ideals do not predict whom you will actually want",
    evidenceTag: "Strong",
    impact: { magnitude: 1, latency: "weeks", durability: "transient", effort: "low" },
    callout: "Rated at the floor because a meta-analysis and multiple live-interaction studies show stated ideal-partner preferences predict evaluations of hypothetical partners but not attraction to real ones; implicit preferences and the interaction itself do. Machine learning on more than 100 pre-date traits could not predict who would desire whom. Filtering hard on a checklist mostly removes people you would have liked.",
    description:
      "In the speed-dating paradigm, people's stated preferences for attractiveness and earning prospects failed to predict what actually inspired their desire; explicit and implicit attractiveness preferences were uncorrelated and predicted different things; and the best machine-learning models found no pre-date measure that forecast the unique desire between two people. Ideals matter more once a relationship exists, where partners are judged against them — which is a reason to hold ideals lightly at the start and to keep only the few that are genuinely non-negotiable.",
    action: "Cut your filter list to three true deal-breakers (safety, core values, life-shape such as children) and say yes to a first meeting with anyone who clears them.",
    sources: [
      { cite: "Eastwick, P. W., Luchies, L. B., Finkel, E. J., & Hunt, L. L. (2014). The predictive validity of ideal partner preferences: A review and meta-analysis. Psychological Bulletin, 140(3), 623–665.", note: "Meta-analysis: ideal preferences predicted attraction to hypothetical targets but not romantic evaluations of live or established partners.", link: doi("10.1037/a0032432"), kind: "doi" },
      { cite: "Eastwick, P. W., & Finkel, E. J. (2008). Sex differences in mate preferences revisited: Do people know what they initially desire in a romantic partner? Journal of Personality and Social Psychology, 94(2), 245–264.", note: "Pre-event ideal preferences failed to predict what inspired desire at a speed-dating event or in relationships that followed.", link: doi("10.1037/0022-3514.94.2.245"), kind: "doi" },
      { cite: "Joel, S., Eastwick, P. W., & Finkel, E. J. (2017). Is romantic desire predictable? Machine learning applied to initial romantic attraction. Psychological Science, 28(10), 1478–1489.", note: "No combination of over 100 self-reported traits and preferences predicted the unique desire between two specific people.", link: doi("10.1177/0956797617714580"), kind: "doi" },
      { cite: "Eastwick, P. W., Eagly, A. H., Finkel, E. J., & Johnson, S. E. (2011). Implicit and explicit preferences for physical attractiveness in a romantic partner: A double dissociation in predictive validity. Journal of Personality and Social Psychology, 101(5), 993–1011.", note: "Explicit preferences predicted photo ratings only; implicit preferences predicted live interest — the checklist measures the wrong thing.", link: doi("10.1037/a0024061"), kind: "doi" },
      { cite: "Eastwick, P. W., Finkel, E. J., & Eagly, A. H. (2011). When and why do ideal partner preferences affect the process of initiating and maintaining romantic relationships? Journal of Personality and Social Psychology, 101(5), 1012–1032.", note: "Ideals gain predictive power only once a partner is being evaluated within an ongoing relationship.", link: doi("10.1037/a0024062"), kind: "doi" },
      { cite: "Joel, S., Eastwick, P. W., Allison, C. J., Arriaga, X. B., Baker, Z. G., Bar-Kalifa, E., et al. (2020). Machine learning uncovers the most robust self-report predictors of relationship quality across 43 longitudinal couples studies. Proceedings of the National Academy of Sciences, 117(32), 19061–19071.", note: "Relationship quality was predicted by how partners perceived the relationship, not by the traits a checklist screens for.", link: doi("10.1073/pnas.1917036117"), kind: "doi" },
    ],
  },
];
